### PR TITLE
#Flink-5522 Storm Local Cluster can't work with powermock

### PR DESCRIPTION
**Pull request by liuyuzhong7**
Storm Local Cluster can't work with powermock.

Delete it because WrapperSetupHelperTest.testCreateTopologyContext doesn't need LocalCluster,

### CODE REVIEW

**Comment by zentol** [comment]
The `org.apache.storm.LocalCluster` import can be removed as well.

**Comment by zentol** [comment]
merging, will fix the import while doing so.

**Comment by StephanEwen** [comment]
I think the correct fix would be not to remove the code, but
  - either make sure that storm classes are ignored by powermnock (add an ignore pattern)
  - rework the test such that powermock is not needed

How about that?

**Comment by liuyuzhong7** [comment]
@StephanEwen 
Only LocalCluster in storm can't workwith powermock.
And it fail to init if ignore LocalCluster by powermock in WrapperSetupHelperTest.

So I think delete or give a new example for LocalCluster is the better solution.

**Comment by zentol** [comment]
I played around a bit with ignore pattern but couldn't get it to work.

However, moving WrapperSetupHelperTest into a separate class and replacing the StreamingRuntimeContext mocking (which in turn removes the need for PowerMock) should do the trick.

**Comment by liuyuzhong7** [comment]
@zentol Right, Strom LocalCluster can run in a single class without powermock.

**Comment by StephanEwen** [comment]
@liuyuzhong7 Would be good to know if you plan to follow up on this issue.
Thanks!

**Comment by liuyuzhong7** [comment]
OK

**Comment by liuyuzhong7** [comment]
@StephanEwen  What should to to with this pull request?

**Comment by StephanEwen** [comment]
It would be good to add the removed code back in a way that does not conflict with powermock, like @zentol suggested.

**Comment by liuyuzhong7** [comment]
@StephanEwen Fixed

**Comment by liuyuzhong7** [comment]
@zentol @StephanEwen Please help me to review this PR. Thanks.

**Comment by StephanEwen** [comment]
I think that is a good fix, thank you!

Merging this...

**Pull request closed without merging**
