### PR TITLE
[FLINK-1669] [wip] Test for streaming recovery from process failure 

### PR DESCRIPTION
**Pull request by mbalassi**
Testing at least once property guarantee of the streaming output when taskmanager failure happens.

Heads up: The current version gets stuck during the wait for the test program and does not finish. Without waiting for the test program it seems fine.

### CODE REVIEW

**Comment by rmetzger** [comment]
Maybe, the `execution-retries.delay` is set too high?

**Comment by mbalassi** [comment]
I would not suspect that as the batch is using the same config on paper.

**Comment by StephanEwen** [comment]
I'll do a pass over this and merge it today or tomorrow...

**Comment by mbalassi** [comment]
Thanks.

**Comment by mbalassi** [comment]
When merging this please put the outputs to a TempFolder, right now they are only deleted if the check of the output is reached.

**Pull request closed without merging**
