### PR TITLE
[FLINK-6923] [Kafka Connector] Expose in-processing/in-flight record …

### PR DESCRIPTION
**Pull request by zhenzhongxu**
This PR exposes current in-processing record partition and offset information per Kafka consumer instance. This allows custom offset management and/or periodical metric reporting etc.

### CODE REVIEW

**Comment by tzulitai** [comment]
@zhenzhongxu could you explain a bit why you need to expose these two values? What are you trying to achieve in your custom fetcher?

**Comment by zhenzhongxu** [comment]
Hi @tzulitai. Yes, we do have a use case where we need to disable Flink checkpointing because the time interval checkpointing model does not work with our constraints. We had to trigger Kafka commits by manually taking offset snapshot and commit after sink flushes (parallel source/sink operators are chained together), in this case, the partition offset is not incremented until the thread exits sink operator logic. Now, the only way to make the commit accurate is to expose which partition the in-flight message belongs to and we can consciously +1 to the offset at the time of snapshoting.

**Comment by tzulitai** [comment]
@zhenzhongxu if I understood you correctly, instead of this solution, would it then make sense for your case to make the Kafka offset committing happen only when the checkpoint is completed, not when it is triggered, i.e. commit in the `notifyCheckpointComplete` callback of `CheckpointListener`?

**Comment by zhenzhongxu** [comment]
Hi @tzulitai, in this particular case, we actually disabled Flink checkpointing (because we do not want to rely on fixed interval barrier to trigger sink flush/offset commit). As a workaround, we manually trigger snapshot and commit upon sink flushing by hooking into source operator's consumer object. Thus this change. We have also previously discussed this approach with @StephanEwen

**Comment by aljoscha** [comment]
Just a quick comment: without a test or a very explicit comment about why these fields are there they might get "fixed away" in the future by someone who notices that there are unused fields.

**Comment by tzulitai** [comment]
+1 agree with @aljoscha here.
The main problem with this change is that there is no usages of it in other parts of the codebase, and can very easily be removed "accidentally" in the future.

**Comment by zhenzhongxu** [comment]
Sounds fair. @aljoscha @tzulitai Any recommendations on what particular test and where I should put the tests in? I'll also improve the documentation as well.

**Comment by tzulitai** [comment]
@zhenzhongxu at the very least, I would expose these new values as protected methods, and let the fields be private. Then, have particular tests that verify the values are correct.

The exposing methods should have good Javadoc on the purpose of exposing them (and in what cases they could be used for).

**Comment by aljoscha** [comment]
@zhenzhongxu Have you looked into `KeyedDeserializationSchema`? In there you have access to the partition and the offset at which the record originated.

**Comment by zhenzhongxu** [comment]
thanks @aljoscha for the suggestion. KeyedDeserializationSchema seems like a better approach. I'll close this PR.

**Pull request closed without merging**
