### PR TITLE
[FLINK-5426] Clean up the Flink Machine Learning library

### PR DESCRIPTION
**Pull request by Fokko**
Hi guys,

I would like to contribute to the Flink ML library. I took the liberty to clean up some of the code and improve the scaladoc. Beside that I've implemented #3077 to get more familiar with the Flink API and I would love to contribute more in the future, in particular the machine learning library.

If you have any questions, please let me know. Let me know if improvements to the ML library are appreciated in general.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by Fokko** [comment]
I think we have some flakey tests, since it passes on my own travis:
https://travis-ci.org/Fokko/flink/builds/189855914

**Comment by Fokko** [comment]
I think we have some flakey tests, since it passes on my own travis:
https://travis-ci.org/Fokko/flink/builds/189854940

**Comment by tillrohrmann** [comment]
Thanks for your contribution @Fokko. I'll take a look at your PR in the next days.

**Comment by Fokko** [comment]
Hi @tillrohrmann, did you find any time to check #3077 and this PR?

**Comment by Fokko** [comment]
I've rebased both branches with master.

**Comment by tillrohrmann** [comment]
Changes look good to me. Thanks a lot for your contributions @Fokko. Merging this PR.

**Pull request closed without merging**
