### PR TITLE
[hotfix] Keep consistent implementation style in VoidHistoryServerArchivist and UnregisteredJobManagerJobMetricGroupFactory

### PR DESCRIPTION
**Pull request by TisonKun**
## What is the purpose of the change

It is a bit more than style issue. The previous implementation create an extra subclass of `VoidHistoryServerArchivist` and `UnregisteredJobManagerJobMetricGroupFactory`.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector:(no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

cc @zentol

### CODE REVIEW

**Comment by zentol** [comment]
@flinkbot approve description
Is this the only place where we do this?

**Comment by TisonKun** [comment]
I am not sure and thus the commit message is "[hotfix] Keep consistent implementation style **in VoidHistoryServerArchivist**".

Otherwhere I meet enums doesn't suffer this issue, but I have no idea how to do a global search to ensure that there is no other place.

**Comment by zentol** [comment]
There are 2 instances of this issue in total, `UnregisteredJobManagerJobMetricGroupFactory` and `VoidHistoryServerArchivist`.
@tillrohrmann What's your take on this?

@TisonKun FYI, I searched these with a regex: `enum.*\{\n\s[a-zA-Z]+ \{`

**Comment by zentol** [comment]
@flinkbot attention tillrohrmann

**Comment by TisonKun** [comment]
@tillrohrmann prefer adding one more commit to this pr since both of them are minimal hotfixes.

**Pull request merged**
