### PR TITLE
[hotfix][jdbc][docs] - Updated key handling section text

### PR DESCRIPTION
**Pull request by mans2singh**
## What is the purpose of the change

* Updated text in key handling section

## Brief change log

* Corrected text

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by mans2singh** [comment]
@flinkbot run azure

**Comment by mans2singh** [comment]
@tisonkun - Can you please review this doc PR ?  Thanks

**Comment by mans2singh** [comment]
@wuchong @leonardBang - Just wanted to request you to review this minor doc PR.  Thanks

**Review by leonardBang — APPROVED** [review]
Thanks @mans2singh , LGTM

**Pull request merged**
