### PR TITLE
[FLINK-1399] Add support for registering Serializers with Kryo

### PR DESCRIPTION
**Pull request by aljoscha**

### CODE REVIEW

**Comment by aljoscha** [comment]
Right now, what a user does is:
```
KryoSerializer.addDefaultSerializer(..., ...)
```

I like this better, and would also change my Pojo Subclass Serializer Pull Request to adhere to this convention. 

The other option (what I currently have in the Pojo Subclass PR) is to have:
```
env.addDefaultSerializer(..., ...)
```

What do you think?

**Comment by rmetzger** [comment]
The second option (env) is probably better because people will see the method when their IDE suggests method names.

**Comment by uce** [comment]
I agree with @rmetzger, but I can see why @aljoscha likes the first suggestion more ;)

**Comment by aljoscha** [comment]
The reason I don't like option 2 is that it introduces knowledge about Kryo at the ExecutionEnvironment while it is right now agnostic of types and serialisers.

**Comment by aljoscha** [comment]
But I also see that option 2 is more discoverable.

**Comment by rmetzger** [comment]
I think its more important to have a smooth user experience.
The ExecutionEnvironment is not used anywhere else, kryo is already a dependency of "flink-java", so I don't see an issue with making the EE aware of Kryo.

**Comment by aljoscha** [comment]
I added register methods at the ExecutionEnvironment.

**Comment by StephanEwen** [comment]
This would do it for now. However, the use of static variables to communicate between components is an antipattern and one that has caused problems before. I would like to change this.

**Comment by StephanEwen** [comment]
I do not see how this can possibly work on a cluster... Everything is in static variables (in the client) that do not get transferred via serialization when moving the code to the cluster. Maybe `registeredSerializers` and `registeredSerializerClasses` should not be static?

**Comment by StephanEwen** [comment]
The registration at Kryo seems to be a bit incomplete. Adding a default serializer does not to type/tag registration, which is very much desirable. Also, it registers the serializer for that type and all subtypes, which is not necessarily desired. I would change the code to call `register`, rather than `addDefaultSerializer`.

**Comment by rmetzger** [comment]
Maybe we should offer users both options: register and default serializer. 
In some cases, you don't know the exact types and you want to go for a default serializer.
I agree that we should in each case register the class.

**Pull request closed without merging**
