### PR TITLE
Adds akka interal docs and configuration description

### PR DESCRIPTION
**Pull request by tillrohrmann**
Adds Akka documentation and configuration description to docs. The Akka internal documentation is the same as the one published in the wiki at the moment of opening this PR.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Looks good. This is basically a copy of the Wiki, right?
How about we keep the docs in one place only. Otherwise, they are almost sure to get out of sync. 
We can 
  - move them to the git repo later (in a batch, when we have more components)
  - Keep them in the wiki and have in the git repo a few pages that link to the wiki. For the detail internals (actors, memory, network stack), we can have on overview page in the docs and link to the wiki from there.

**Comment by hsaputra** [comment]
+1 to keep it in Wiki for now. There is already a stub in the Doc so we could just set it to point to the wiki

**Comment by tillrohrmann** [comment]
Yes I agree that we should keep the internals only at one place. Even then, it is probably hard enough to keep the docs in sync with the code.

But what still might be interesting to add to the docs is the description of the configuration parameters. There is still a big hole under "Distributed coordination (via Akka)".

**Comment by rmetzger** [comment]
+1 for updating the configuration guide with the Akka variables.

**Comment by tillrohrmann** [comment]
Ok, I'll close this PR and open a new one only containing the respective configuration documentation.

**Pull request closed without merging**
