### PR TITLE
[hotfix][doc] Generate and use docs of RpcOptions instead of AkkaOptions

### PR DESCRIPTION
**Pull request by Zakelly**
## What is the purpose of the change

Currently, when re-generating docs on master branch, the `rpc_configuration.html` is generated. The `AkkaOptions` is renamed to `RpcOptions` via FLINK-32684 so docs should be re-generated and all the content including should point to the new one.

## Brief change log

 - Re-generate docs. `rpc_configuration.html` is generated.
 - Replace all including of `akka_configuration.html` with `rpc_configuration.html`

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

### CODE REVIEW

**Comment by Zakelly** [comment]
@XComp Would you please take a look?

**Review by charlesy6 — APPROVED** [review]

**Comment by charlesy6** [comment]
lgtm

**Comment by zoltar9264** [comment]
Hi @Zakelly , it seems that we should delete the file `docs/layouts/shortcodes/generated/akka_configuration.html` ?

**Comment by Zakelly** [comment]
> Hi @Zakelly , it seems that we should delete the file `docs/layouts/shortcodes/generated/akka_configuration.html` ?

Yes, I forgot to delete it manually. Done & pushed.

**Comment by zoltar9264** [comment]
LGTM

**Comment by fredia** [comment]
@Zakelly Thanks for the PR, I'm curious

> > Hi @Zakelly , it seems that we should delete the file `docs/layouts/shortcodes/generated/akka_configuration.html` ?
> 
> Yes, I forgot to delete it manually. Done & pushed.

I'm wondering if `ConfigOptionsDocsCompletenessITCase#testCompleteness` can pass? After I deleting `akka_configuration.html` in local, the `ConfigOptionsDocsCompletenessITCase#testCompleteness` failed.

**Comment by fredia** [comment]
@flinkbot run azure

**Comment by Zakelly** [comment]
> > > Hi @Zakelly , it seems that we should delete the file `docs/layouts/shortcodes/generated/akka_configuration.html` ?
> > 
> > 
> > Yes, I forgot to delete it manually. Done & pushed.
> 
> @Zakelly Thanks for the PR, I'm wondering if `ConfigOptionsDocsCompletenessITCase#testCompleteness` can pass? After I deleting `akka_configuration.html` in local, the `ConfigOptionsDocsCompletenessITCase#testCompleteness` failed.

After you delete `akka_configuration.html` and add `rpc_configuration.html`, it can pass. IIUC, deleting `akka_configuration.html` only will cause incompletion of documents.

**Review by fredia — APPROVED** [review]
Thanks for the clarification, LGTM

**Pull request merged**
