### PR TITLE
[FLINK-26604][doc] backport the AvroParquet doc to 1.15

### PR DESCRIPTION
**Pull request by JingGe**
backport the AvroParquet doc to 1.15. For more information please refer to #19083

### CODE REVIEW

**Comment by MartijnVisser** [comment]
@JingGe - I guess we have to wait for the build to have passed since I haven't seen a release-1.15 CI run complete today. I'll merge it straight after it has completed.

**Comment by JingGe** [comment]
Fair enough, thanks!

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Review by MartijnVisser — APPROVED** [review]
LGTM

**Pull request merged**
