### PR TITLE
[FLINK-32755][docs] Add doc for OLAP quickstart

### PR DESCRIPTION
**Pull request by xiangyuf**
## What is the purpose of the change

Add quick-start docs for Flink OLAP

## Brief change log

  - added olap_quickstart.md in docs

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by xiangyuf** [comment]
@FangYongs @KarmaGYZ hi, can u help review this doc?

**Comment by xiangyuf** [comment]
@flinkbot run azure

**Comment by xiangyuf** [comment]
Hi @FangYongs  @KarmaGYZ  this is a joint work between @zoudan and me. Pls add this into the commit message if it has passed the review.

**Comment by KarmaGYZ** [comment]
> Hi @FangYongs @KarmaGYZ @libenchao this is a joint work between @zoudan and me. Pls add this into the commit message if it has passed the review.

You can directly add him. Pls take a look https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors .

**Comment by FangYongs** [comment]
Thanks @xiangyuf , LGTM

**Pull request merged**
