### PR TITLE
[FLINK-23902][connectors/hive] Make flink support Hive 3.1.3 version

### PR DESCRIPTION
**Pull request by yangjf2019**
## What is the purpose of the change

*I modified the flink-connectors module to support hive 3.1.3 version.*

## Brief change log

*I added a new class and modified _HiveShimLoader.java_ .*

## Verifying this change

*I ran the corresponding test class and didn't see any failures.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

Hi, @wuchong @gaoyunhaii   Please take a look in your free time ,thank you.

### CODE REVIEW

**Comment by gaoyunhaii** [comment]
@flinkbot run azure

**Review by gaoyunhaii — APPROVED** [review]
Thanks @yangjf2019 for the PR! LGTM

**Comment by yangjf2019** [comment]
Hi @gaoyunhaii ,Thanks for your review,I will keep trying!

**Comment by gaoyunhaii** [comment]
Thanks @yangjf2019! Merged~

**Pull request closed without merging**
