### PR TITLE
[FLINK-6128] Optimize JVM options for improve test performance

### PR DESCRIPTION
**Pull request by DmytroShkvyra**
The main goal of this PR improve latency of running tests with travis and prevent OOM.
1. Increased heap size
2. Use UseSerialGC
3. Remove UseGCOverheadLimit option

- [ ] General
  - The pull request references the related JIRA issue ("[FLINK-6128] Optimize JVM options for improve test performance")

### CODE REVIEW

**Comment by DmytroShkvyra** [comment]
Hi @rmetzger could you review this PR?

**Comment by DmytroShkvyra** [comment]
I don't think that:
**Results :
Failed tests: 
  ZooKeeperLeaderElectionTest.testZooKeeperReelection:197 null**
is mine fault.

**Comment by twalthr** [comment]
Do you have some numbers about how much your changes improve tests?

**Comment by DmytroShkvyra** [comment]
@twalthr Yes of course! Following data I have sent to dev list
> 
> # Test|Present JVM options	|"-Xms256m -Xmx1536m -XX:+UseSerialGC"
> -----------------------------------------------------------------			
> 1	35 min	53 sec		|35 min 35 sec
> 2	38 min	49 sec		|34 min	 18 sec
> 3	35 min	34 sec		|29 min	 38 sec
> 4	34 min	38 sec		|31 min	 14 sec
> 5	35 min	41 sec		|35 min	 11 sec
> 6	36 min	41 sec		|33 min	 52 sec
> 7	49 min	59 sec		|31 min	 35 sec
> 8	37 min	0 sec		|36 min	 20 sec
> 9	32 min	28 sec		|31 min	 48 sec
> 10	38 min	25 sec		|33 min	 28 sec
> 11	36 min	19 sec		|38 min	 24 sec
> 12	25 min	0 sec		|24 min	 3 sec
> ------------------------------------------------------------------
> Total	26187 sec		|23726	sec
> ------------------------------------------------------------------
> Acceleration			|9.40%	

Also Evgeny Kincharov have done some tests with different options https://travis-ci.org/kenmy/flink/builds  (see builds with "fix unittests time" description). He and I sure that using serial GC more suitable for tests than use default GCs of Java 7 and 8 (we have only one core per fork)

**Comment by twalthr** [comment]
I also did some testing and also saw performance improvements. +1 for this.

**Comment by rmetzger** [comment]
+1

**Comment by greghogan** [comment]
Merging ...

**Pull request closed without merging**
