### PR TITLE
[BP-1.17][FLINK-32029][core] Adds fallback error handling to FutureUtils.handleUncaughtException.

### PR DESCRIPTION
**Pull request by XComp**
1.17 backport PR for PR #22544.

### CODE REVIEW

**Comment by XComp** [comment]
I didn't backport the JUnit5 hotfix commit and, therefore, had to adapt the test slightly. Hence, the additional review request @snuyanzin :innocent:

**Comment by snuyanzin** [comment]
From one side it looks good
from another side I wonder whether it's better to use same code as in master's PR + replacement of `assertThat` to `Assertions.assertThat` and add public modifier since junit4 requires it.

**Comment by XComp** [comment]
Initially, I thought of backporting the junit5 migraiton as well. But it looks like we didn't do it in the past, either: `assertThatFuture` isn't backported. I backed off then because it felt like a quite big change to the `FutureUtilsTest` class just to have this kind-of cosmetic change (talking about the junit5 migration) be included as well. I didn't want to open the rabbit hole of migrating other JUnit5 migrations as well. WDYT? :thinking:

**Comment by snuyanzin** [comment]
in fact I don't have strong opinion about that... 
may be you're right it's better either migrate the whole class to junit5/assertj or nothing

**Review by snuyanzin — APPROVED** [review]

**Review by snuyanzin — APPROVED** [review]

**Pull request merged**
