### PR TITLE
[FLINK-22775][connectors][cassandra][test] Lower consistency expectation in write operations to avoid waiting for replica acknowledge

### PR DESCRIPTION
**Pull request by echauchot**
This PR lowers consistency expectancy from ONE to ANY in write operations to avoid waiting for a replica write acknowledge in ITest. This consistency level is only available on write, so we need to create one builder for reading and one for writing. Some sinks are used for both reading and writing (in committer tests, and in base class tests), in that case, reading builder (with consistency set to ONE) is used.

This should remove the timeout flakiness error. As said in the ticket, we need to monitor the ITest for some weeks to acknowledge that there is no more write timeouts.

Hi @zentol, I saw your name in the commit history, can you please take a look?

### CODE REVIEW

**Comment by echauchot** [comment]
@zentol the PR is not ready for review yet. I still have another thing to fix, I'll ping you when ready

**Comment by echauchot** [comment]
@flinkbot run azure

**Comment by echauchot** [comment]
@flinkbot run azure

**Comment by echauchot** [comment]
@flinkbot run azure

**Comment by echauchot** [comment]
@flinkbot run azure

**Comment by echauchot** [comment]
@zentol ready for review PTAL

**Comment by echauchot** [comment]
I don't know what happens with AZP, but I can't get the status, it is in PENDING status then CANCEL

**Comment by zentol** [comment]
Please rebase the branch. It is a tad out-dated (hence the python failure)

**Comment by zentol** [comment]
Were you able to replicate the issue locally, or is this more of a "throw-stuff-at-a-wall-and-see-what-sticks" kind of situation? (Which I wouldn't mind for this particular test...)

**Comment by echauchot** [comment]
> Were you able to replicate the issue locally, or is this more of a "throw-stuff-at-a-wall-and-see-what-sticks" kind of situation? (Which I wouldn't mind for this particular test...)

No, as this timeout is a flakiness issue which happens under load (see [my comment](https://issues.apache.org/jira/browse/FLINK-22775?focusedCommentId=17446552&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17446552) in the ticket) I did not manage to reproduce it out of 30 local runs. But I have pretty good confidence that avoiding the cluster to wait for a replicate on write would avoid the timeout under load. 

As explain in my comment in the ticket I plan to monitor the ITest for some weeks and see if it is still flaky with my fix. If it is still flaky  then we could consider migrate the cassandra test cluster from embedded daemon to either testContainers (relies on docker so less sensitive to load) or ASF v2 licenced test component such as Achilles (that I used in Apache Beam and that I contributed to) which has a lot of knobs for configuring the cluster.

**Comment by echauchot** [comment]
rebased on master

**Comment by echauchot** [comment]
Thanks @zentol for merging !

**Pull request merged**
