### PR TITLE
[FLINK-1650] Configure Netty (akka) to use Slf4j.

### PR DESCRIPTION
**Pull request by rmetzger**
It seems that Netty 3.8.0 used by Akka was using `java.util.logging` for its internal logging, that's why this entry was without effect: https://github.com/apache/flink/blob/master/flink-dist/src/main/flink-bin/conf/log4j.properties#L29.

The change sets the Netty logging factory to Slf4j. This means that Netty is now using Sfl4j. It'll also respect our logging settings (`org.jboss.netty.channel.DefaultChannelPipeline` to lvl ERROR).

Lets see if the exception now disappears.

### CODE REVIEW

**Comment by rmetzger** [comment]
The build passed in my travis: https://travis-ci.org/rmetzger/flink/builds/55487319

**Comment by tillrohrmann** [comment]
Great to hear that you figured out why we could not suppress this error :-)

**Comment by hsaputra** [comment]
+1 nice find

**Comment by StephanEwen** [comment]
Good find, but just calling it in the beginning of every main() method seems hacky.

I think the code should go to the AkkaUtils.createActorSystem() method. Then we also need it only once.

**Comment by rmetzger** [comment]
I moved the call to the Akka utils.

**Comment by tillrohrmann** [comment]
LGTM.

**Comment by rmetzger** [comment]
I'll merge the change

**Pull request merged**
