### PR TITLE
[FLINK-29097][sql-gateway]Moving json se/deserializers from sql-gateway-api to sql-gateway

### PR DESCRIPTION
**Pull request by WencongLiu**
## What is the purpose of the change

*Moving json se/deserializers from sql-gateway-api to sql-gateway*

## Brief change log

  - *Moving json se/deserializers from sql-gateway-api to sql-gateway*

## Verifying this change

This change added tests and can be verified as follows:

  - *None*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by WencongLiu** [comment]
@flinkbot run azure

**Comment by WencongLiu** [comment]
@flinkbot run azure

**Comment by WencongLiu** [comment]
@flinkbot run azure

**Review by fsk119 — COMMENTED** [review]
The commit LGTM in general. But I think we can move all rest-related serializer/deserializer into the sql-gateway package.

**Comment by fsk119** [comment]
I add a commit to 
1. move the serializer
2. modify the ColumnInfo. I find the `Column` also has comment field.

**Comment by fsk119** [comment]
The failed test is not releated to the current change. 

@flinkbot run azure

**Review by fsk119 — APPROVED** [review]

**Pull request closed without merging**
