### PR TITLE
[FLINK-20654][tests] Forcing network action logger on TRACE for Unaligned Checkpoint ITCases.

### PR DESCRIPTION
**Pull request by AHeise**
## What is the purpose of the change

To debug FLINK-20654, we need all network buffers to be logged.

## Brief change log

- Adds a junit rule to change log levels for specific logs (currently only for log4j2 loggers).
- Switches `NetworkActionsLogger` to `TRACE` in `UnalignedCheckpointITCase` and `UnalignedCheckpointRescaleITCase`.

## Verifying this change

Manually verified locally and on AZP.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (**yes** / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by dawidwys** [comment]
The approach to setting the log level programmatically looks good to me.

However I am a bit concerned that with the `TRACE` level enabled for `UnalignedCheckpointTestBase` the log files become huge. For the azure run for this PR, the size of mvn-2.log reaches ~2GB, whereas the latest successful run on master produces log files of around ~100MB. I am slightly concerned if we should enable it for all test runs...

**Comment by AHeise** [comment]
> The approach to setting the log level programmatically looks good to me.
> 
> However I am a bit concerned that with the `TRACE` level enabled for `UnalignedCheckpointTestBase` the log files become huge. For the azure run for this PR, the size of mvn-2.log reaches ~2GB, whereas the latest successful run on master produces log files of around ~100MB. I am slightly concerned if we should enable it for all test runs...

Thanks for the feedback. I investigated two reasons why the logs grew so big:
- Buffers were logged even though respective checkpoint was cancelled and effectively NOT written (so a bug in tracing)
- The test setup caused a long recovery time where many checkpoints were rapidly triggered and subsequently canceled. That could easily lead to 300 checkpoints in 1 min each leading to quite a few buffers being written before checkpoint was cancelled downstream. I modified the test to pump data on the source and sink in bursts equal to the checkpointing interval (so causing full buffers during checkpointing but not elsewhere).

**Review by dawidwys — APPROVED** [review]
LGTM % azure

**Comment by AHeise** [comment]
Okay has been green the last 3 builds (+personal), so the tactic to reduce checkpointing interval definitively stabilized the tests. I'm merging.

**Pull request merged**
