### PR TITLE
[FLINK-17074] Deprecate key based methods that do not use KeySelector in Datastreams API 

### PR DESCRIPTION
**Pull request by echauchot**
## What is the purpose of the change

Deprecate key based methods that do not use KeySelector in Datastreams API 

## Brief change log
javadoc update + deprecate annotation for Datastream.keyBy and Datastream.partitionCustom methods

## Verifying this change

This change is a trivial rework

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no). Only on a class annotated @Public
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by echauchot** [comment]
R: @aljoscha

**Comment by echauchot** [comment]
I just realized that I did not update the docs on the website among others https://ci.apache.org/projects/flink/flink-docs-release-1.10/dev/api_concepts.html#specifying-keys, I'll add a commit, please wait for it before merging

**Comment by aljoscha** [comment]
Ok, standing by.

**Comment by echauchot** [comment]
@aljoscha, done, PTAL

**Comment by aljoscha** [comment]
@echauchot Ah sorry, I forgot there is also the Scala `DataStream` API. 😅Could you also do those?

**Comment by echauchot** [comment]
@aljoscha sure ! And I forgot as well :)

**Comment by echauchot** [comment]
Done, PTAL

**Comment by aljoscha** [comment]
Thanks, I'll take a look!

By the way, I prefer shorter commit titles, but it's up to you. Some people like putting the tags, but for example in the github view the commit titles show as `[FLINK-17074][Datastream java api]Deprecate Datastream.keyBy methods … ` which doesn't give me much information. 😅

**Comment by echauchot** [comment]
> Thanks, I'll take a look!
> 
> By the way, I prefer shorter commit titles, but it's up to you. Some people like putting the tags, but for example in the github view the commit titles show as `[[FLINK-17074](https://issues.apache.org/jira/browse/FLINK-17074)][Datastream java api]Deprecate Datastream.keyBy methods … ` which doesn't give me much information.

Me too, short commit titles seem better to me. I was just applying the what was in the commit guide. I thought tags were mandatory but I can rebase and remove them if you prefer

**Comment by echauchot** [comment]
Done, I removed the tags from commit messages. I also fixed the conflict with the docs: you removed api_concepts.md page that I was updating but you also added the comment on deprecation of key uses in state.md file so that is perfect! I simply dropped my docs update commit. PTAL

**Comment by aljoscha** [comment]
Thanks a lot! I merged.

**Pull request closed without merging**
