### PR TITLE
[FLINK-27909][doc] Add document for hybrid shuffle

### PR DESCRIPTION
**Pull request by reswqa**
## What is the purpose of the change

*Add document for hybrid shuffle*

## Brief change log

  - *Add hybrid shuffle to taskmanager.memory.framework.off-heap.batch-shuffle.size description.*
  - *Add document for hybrid shuffle mode.*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? docs

### CODE REVIEW

**Comment by reswqa** [comment]
@flinkbot run azure

**Review by xintongsong — APPROVED** [review]
Thanks @reswqa. LGTM.

**Comment by xintongsong** [comment]
@flinkbot run azure

**Comment by xintongsong** [comment]
@flinkbot run azure

**Comment by xintongsong** [comment]
@flinkbot run azure

**Comment by xintongsong** [comment]
@flinkbot run azure

**Comment by reswqa** [comment]
@flinkbot run azure

**Pull request closed without merging**
