### PR TITLE
[hotfix][docs] Fix HTML formatting in ops/metrics.md

### PR DESCRIPTION
**Pull request by smattheis**
## What is the purpose of the change

Fix HTML in ops/metrics.md (Rendering of HTML was broken due to misplaced newline)

## Brief change log

Fix 'Note' paragraph and adapt to style to other 'Note' paragraphs of the rest of the document.

## Verifying this change

Verified locally with IDE-integrated markdown renderer

## Does this pull request potentially affect one of the following parts:

Only docs affected

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by pnowojski — COMMENTED** [review]
Thanks for the fix @smattheis . Have you checked locally that this is now working fine?

Can you explain what was the problem before? Empty line was prematurely terminating the table?

**Comment by smattheis** [comment]
> Thanks for the fix @smattheis . Have you checked locally that this is now working fine?
> 
> Can you explain what was the problem before? Empty line was prematurely terminating the table?

Yes, exactly the new line was breaking the HTML rendering. I have checked locally via IntelliJ markdown rendering that it should be fixed now.

**Comment by pnowojski** [comment]
By locally I meant building the docs locally (described in the readme I think: https://github.com/apache/flink/tree/master/docs ), just to be sure it's working fine.

**Comment by smattheis** [comment]
> By locally I meant building the docs locally (described in the readme I think: https://github.com/apache/flink/tree/master/docs ), just to be sure it's working fine.

No, I wasn't aware of that. Will check it.

**Comment by smattheis** [comment]
> By locally I meant building the docs locally (described in the readme I think: https://github.com/apache/flink/tree/master/docs ), just to be sure it's working fine.

@pnowojski Checked it. It's fine.

**Comment by smattheis** [comment]
@pnowojski backport to any previous version not required as `watermarkAlignmentDrift` is new in 1.15

**Pull request merged**
