### PR TITLE
[FLINK-31006][connector/kafka] Fix noMoreNewPartitionSplits is not se…

### PR DESCRIPTION
**Pull request by liuyongvs**
…t correct when using pipeline mode runs bounded source.

## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluster with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by liuyongvs** [comment]
@flinkbot run azure

**Comment by liuyongvs** [comment]
@flinkbot run azure

**Review by PatrickRen — CHANGES_REQUESTED** [review]
Thanks for the patch @liuyongvs , but I'm afraid there's a race condition that will cause some splits to be dropped by readers. I guess this is probably the reason why CI failed:

0. Kafka source runs in bounded mode.
1. The enumerator starts and `noMoreNewPartitionSplits` is set to true, then the initial partition discovery is triggered. 
2. As the partition discovery runs asynchronously in the worker thread, it's possible that a reader can register on the enumerator before the partition discovery finishes. 
3. The reader registration invokes `addReader()`, then NoMoreSplitsEvent is sent to the new reader in the `assignPendingPartitionSplits()`. 

As a result, all partitions belongs to this reader will be dropped, as it's already received `NoMoreSplitsEvent` before any partitions could be discovered and assigned. This is why the comment on the `noMoreNewPartitionSplits` said that this flag should be set to true **after the initial discovery finishes**, otherwise partitions will be dropped then.

**Comment by tzulitai** [comment]
I believe that this PR is subsumed by https://issues.apache.org/jira/browse/FLINK-31319.
Can we close this PR @liuyongvs?

**Comment by liuyongvs** [comment]
hi @tzulitai , it is a different problem.

**Comment by liuyongvs** [comment]
@tzulitai i talked with @PatrickRen offline, don't have a suitable way to fix it before. and  we will solved it in next weeke

**Comment by davidradl** [comment]
@liuyongvs  I see https://github.com/apache/flink/pull/22797 , this pr is no longer relevant to this repository, I suggest closing this pr and porting the change to the [new Flink connector kafka repo]( https://github.com/apache/flink-connector-kafka) if it is still relevant.

**Pull request closed without merging**
