### PR TITLE
[FLINK-4284] [docu] Fix broken links

### PR DESCRIPTION
**Pull request by zentol**
Fixes several broken links in the documentation. There were all links to the Batch documentation that are now under "Basic API Concepts".

### CODE REVIEW

**Comment by StephanEwen** [comment]
Out of curiosity: Are pure anchor linkes in general broken in the docs?

**Comment by zentol** [comment]
If this `[transformations](#dataset-transformations)` is a pure anchor link then they aren't broken.

**Comment by uce** [comment]
+1 to merge. Anchor links have been broken while moving the batch docs pages around...

**Comment by zentol** [comment]
merging

**Pull request closed without merging**
