### PR TITLE
[FLINK-2906] Remove Record API

### PR DESCRIPTION
**Pull request by zentol**
This PR removes the old Record API and all Collector-Map related classes since they are unused now.

I'm not sure i found all files, i went through the deprecated classes and did a text search for "Record API". So if anyone knows of some obscure file somewhere fire away ;)

### CODE REVIEW

**Comment by fhueske** [comment]
Look good to me. I was about to prepare the same PR and did not find more files.

I'm very happy that we finally get rid of this heritage :-)

**Comment by StephanEwen** [comment]
Nice! Waiting for this for over a year now ;-)

**Comment by fhueske** [comment]
Will merge this PR.

**Comment by hsaputra** [comment]
Awesome!

**Pull request closed without merging**
