### PR TITLE
[FLINK-21178][Runtime/Checkpointing] Task failure should trigger master hook's reset()

### PR DESCRIPTION
**Pull request by crazyzhou**
## What is the purpose of the change

With FLINK-20222 fix, it brings the regression that the master hook's `reset()` is called only in global recovery case, which causes the test failure(details in https://github.com/pravega/flink-connectors/issues/441) in [Pravega Flink connector](https://github.com/pravega/flink-connectors)

## Brief change log

- Always reset the master hooks at the restore.

## Verifying this change

This change is already covered by existing tests, such as the test case in Pravega Flink connector.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (**no**)
  - The serializers: (**no**)
  - The runtime per-record code paths (performance sensitive): (**no**)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (**yes**)
  - The S3 file system connector: (**no**)

## Documentation

  - Does this pull request introduce a new feature? (**no**)

### CODE REVIEW

**Comment by StephanEwen** [comment]
I think this PR is fine. It means that the `reset()` method of the Master Hooks is always invoked, also on partial failover and on starting a new job. Given that this is an internal API with Pravega as the only user I am aware of, I think this change is no problem.

So +1 to merge this.

**Comment by StephanEwen** [comment]
One question out of curiosity: How does Pravega's recovery and Flink's regional failover go together today?.

If Flink recovers only a part of the graph (regional failover) and Pravega restores all readers to the latest checkpoint, we can get weird effects, I assume. How do you solve this?
  - Do Pravega setups always configure "ALL" as the failover strategy?
  - Do the readers in the not-restarted regions throw an exception when reset to the checkpoint so that these regions implicitly also fail over?

**Comment by crazyzhou** [comment]
Hi Stephan, sorry for the late reply for our holiday. 

> * Do Pravega setups always configure "ALL" as the failover strategy?

We use the default `region`, it's theoretically fine because we solve this as the next answer. We actually did not care much about this before because almost all of the current Pravega Flink tests and real use cases are streaming based, so all the tasks are in the same pipelined region, so it's always a "global" recovery during a failover. 

> * Do the readers in the not-restarted regions throw an exception when reset to the checkpoint so that these regions implicitly also fail over?

Yes, for non-restarted readers, it will throw `ReinitializationRequiredException` when reading events (ref: https://github.com/pravega/pravega/blob/f6971bd0a1213263ed9e89c644f7619ceb62603c/client/src/main/java/io/pravega/client/stream/ReaderGroup.java#L88), and then these regions will implicitly fail over.

**Comment by crazyzhou** [comment]
@StephanEwen @becketqin Can you assign this Flink jira ticket to me and are there any more concerns about this pull request? If we are fine about this, can we merge it now and cherry-pick this into the `1.12` branch? It would be convenient for Pravega if this issue can be fixed in 1.12.2 release.

**Comment by becketqin** [comment]
@crazyzhou Thanks for the patch. It looks that the unit test has format issue that failed the CI. Can you fix that. Otherwise the patch LGTM.

**Comment by crazyzhou** [comment]
> @crazyzhou Thanks for the patch. It looks that the unit test has format issue that failed the CI. Can you fix that. Otherwise the patch LGTM.

@becketqin I have fixed the format issue and the build is succeeding now.

**Comment by wangyang0918** [comment]
cc @becketqin It seems that this PR breaks the master branch. Because the `CheckpointCoordinatorBuilder#setJobId` has been removed. Now the Flink master branch could not compile successfully.

**Comment by wuchong** [comment]
I have reverted this commit to make master can compile. Please open another PR to fix the conflicts.

**Comment by crazyzhou** [comment]
> I have reverted this commit to make master can compile. Please open another PR to fix the conflicts.

Sorry for not rebasing master, I can raise another one based on latest master today.

**Pull request merged**
