### PR TITLE
[FLINK-10932][ResourceManager] Initial flink-kubernetes module with e…

### PR DESCRIPTION
**Pull request by chunhui-shi**
## What is the purpose of the change
Initialize the skeleton module to start native k8s integration

## Brief change log
* _Add flink-kubernetes module_
* _Add first Implement of ClusterDescriptor_
* _Add Interface of Kubernetes client_

## Verifying this change
This change is an initial empty implementation, verified by `mvn clean install` and Travis CI.

## Does this pull request potentially affect one of the following parts:
* Dependencies (does it add or upgrade a dependency): (no)
* The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
* The serializers: (no )
* The runtime per-record code paths (performance sensitive): ( no )
* Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no )
* The S3 file system connector: ( no )

## Documentation
* Does this pull request introduce a new feature? (yes)
* If yes, how is the feature documented? (the document will be introduced in later pull requests)

### CODE REVIEW

**Comment by tillrohrmann** [comment]
Failing test cases seem to be unrelated since these are Yarn tests which are failing.

**Comment by wangyang0918** [comment]
Hi @tillrohrmann, could you help to get this PR committed so that the follow-up works could be started.
We already have a kubernetes integration in blink and hope to get involved and make some contributions.

**Comment by chunhui-shi** [comment]
Thanks for the interests in this PR. I have talked with Till offline and Till gave some feed back to the complete feature we have done. I will be updating PRs and send out new PR with complete commits in a couple of days for the community to review.

Best,
Chunhui
------------------------------------------------------------------

**Comment by tianchen92** [comment]
This PR is outdated, see new PR [#8624](https://github.com/apache/flink/pull/8624)

**Comment by tillrohrmann** [comment]
Closing this PR as it has been subsumed.

**Pull request closed without merging**
