### PR TITLE
[FLINK-5819] [webui] implements numeric option on metrics graphs

### PR DESCRIPTION
**Pull request by nellboy**
enables toggling between numeric and graph view for metrics graphs

### CODE REVIEW

**Comment by zentol** [comment]
Could you add a screenshot how it would look like after the changes?

**Comment by nellboy** [comment]
certainly, my apologies. Please find attached

pasted image at 2017_02_17 13_56

**Comment by zentol** [comment]
How well does this handle long metric names? (100+ characters)

(You can emulate this by running the SocketWindowWordCount example)

**Comment by zentol** [comment]
ah, ignore my previous comment; that's not relevant to this PR.

**Pull request closed without merging**
