### PR TITLE
[FLINK-2103] Expose partitionBy to user

### PR DESCRIPTION
**Pull request by aljoscha**

### CODE REVIEW

**Comment by mbalassi** [comment]
Merging.

**Comment by aljoscha** [comment]
We should first update the documentation.

**Comment by mbalassi** [comment]
Good point, will do that anyway because of the renaming discussed on the mailing list.

**Comment by mbalassi** [comment]
While merging realized, that it is missing from the windowed and connected datastreams and the from the scala API. Also adding those.

**Pull request closed without merging**
