### PR TITLE
[FLINK-6422] [core] Unreachable code in FileInputFormat#createInputSp…

### PR DESCRIPTION
**Pull request by zhangminglei**
Fix Unreachable code in FileInputFormat#createInputSplits.

### CODE REVIEW

**Comment by zhangminglei** [comment]
Thanks  @tedyu for reporting this. cc  @StephanEwen @tedyu Could both you take a look ? I checked the first version you designed.

**Comment by tedyu** [comment]
Can you take a look at the error in CI ?

**Comment by zhangminglei** [comment]
Seems I could not get any useful information from CI, except for this kinda stuff following and it seems  not relevant to this issue.

```
Running org.apache.flink.test.recovery.JobManagerHACheckpointRecoveryITCase
java.lang.RuntimeException: org.apache.zookeeper.server.ZooKeeperServer class is frozen
	at javassist.CtClassType.checkModify(CtClassType.java:288)
	at javassist.CtBehavior.setBody(CtBehavior.java:432)
	at javassist.CtBehavior.setBody(CtBehavior.java:412)
	at org.apache.curator.test.ByteCodeRewrite.fixMethods(ByteCodeRewrite.java:91)
	at org.apache.curator.test.ByteCodeRewrite.<clinit>(ByteCodeRewrite.java:50)
	at org.apache.curator.test.TestingServer.<clinit>(TestingServer.java:33)
	at org.apache.flink.test.recovery.JobManagerHACheckpointRecoveryITCase.testCheckpointedStreamingProgram(JobManagerHACheckpointRecoveryITCase.java:345)
	at org.apache.flink.test.recovery.JobManagerHACheckpointRecoveryITCase.testCheckpointedStreamingProgramIncrementalRocksDB(JobManagerHACheckpointRecoveryITCase.java:331)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by tzulitai** [comment]
LGTM, merging ..

**Comment by zhangminglei** [comment]
Thanks @tzulitai for review! And thanks @tedyu for reporting this!

**Pull request closed without merging**
