### PR TITLE
[FLINK-17826][jdbc] Add missing custom query support on new jdbc connector

### PR DESCRIPTION
**Pull request by leonardBang**
## What is the purpose of the change

* This pull request add `scan.query` option for dynamic JDBC connector.

## Brief change log

  - introduce option `scan.query`
  - use custom query first when scan a JDBC table

## Verifying this change

- Add unit test in `JdbcDynamicTableFactoryTest` and ITCase in `JdbcDynamicTableSourceITCase`. 

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): ( no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (docs )

### CODE REVIEW

**Review by fpompermaier — COMMENTED** [review]
LGTM. It could be worth to mention in the documentation that when **scan.query** is present then **table-name** is ignored

**Comment by leonardBang** [comment]
> LGTM. It could be worth to mention in the documentation that when **scan.query** is present then **table-name** is ignored

Thanks @fpompermaier for the review very much.
I consider that a JDBC source table can be source table and dimension table(lookup) at the same time, and the  **table-name** is necessary when it used as dimension table not matter the **scan.query** is present or not.

So how about add an explanation for **scan.query** that  if the **scan.query** option is present then **table-name** option is ignored when used as source table ?

**Comment by tonychen0716** [comment]
Looking forward to this merger

**Comment by MartijnVisser** [comment]
We've now moved the code from the JDBC connector to its own dedicated repository; please re-route this PR to https://github.com/apache/flink-connector-jdbc

**Pull request closed without merging**
