### PR TITLE
[FLINK-22315][table] Support ADD column/constraint/watermark for ALTER TABLE statement.

### PR DESCRIPTION
**Pull request by RocMarshal**
## What is the purpose of the change

*Support ADD column/constraint/watermark for ALTER TABLE statement.*

## Brief change log

  - *Modify Parser.tdd for adding keywords 'FIRST' and 'AFTER'*
  - *Modify parserImpls.ftl for new syntax of the PR*
  - *Introduce ColumnPositionDesc.java class to describe the referenced column information.*
  - *Introduce SqlAlterTableAddWatermark.java, SqlAlterTableAddColumn.java, SqlAlterTableAddColumns.java for syntax parser*
  - *Extract 'SqlAlterTable convert to AlterTableOperation' logic into SqlAlterTableConverter.java*
  - *Reuse the code of MergeTableLikeUtil.java to process the operation of the syntax.*

## Verifying this change

This change added tests and can be verified as follows:

  - *table.q & view.q for sql-client test cases.*
  - *Modify FlinkSqlParserImplTest.java for adding sql parser test cases*
  - *Add test cased in org.apache.flink.table.api.sql.ddl.ExecuteAlterAddColumnComponentsSqlTest*
  - *Modify test cases in MergeTableLikeUtilTest*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**yes** / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (**yes** / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by RocMarshal** [comment]
Could someone help me to review this PR? Thanks.

**Comment by RocMarshal** [comment]
@flinkbot run azure

**Comment by RocMarshal** [comment]
Hi, @wuchong Could you  help me to review this PR? Thanks.

**Comment by RocMarshal** [comment]
@MartijnVisser Anyone help to review this pull request ? Thx.

**Comment by MartijnVisser** [comment]
Thank you for your contribution @RocMarshal - Please don't ping multiple people. It can be quite annoying for people who are working on open source contributions and can actually cause people to ignore these types of pings. As you can see (based on the number of open PRs), there are a lot of open items that need attention. Everyone tries their best to get as many contributions in as possible. I'm not sure that this can be reviewed before the release-1.15 branch is cut (beginning of February).

**Comment by RocMarshal** [comment]
@MartijnVisser 

Thank you very much for your reply. I guess you misunderstood it. You are very active in the community, this sign of authority indicates your familiarity with the community and the plan. I'm just looking for someone who can be familiar with this area to advance pr. In other words, I hope you can recommend a contributor who is familiar with the relevant modules to promote together. I don't know what call frequency is noise. If you know, any suggestion is appreciated. Or we need a mapping list of modules to related more active personnel to find accurately people who can communicate. IMO, this will be also helpful to solve the problem of so many PR(about 700) at present. 

The same thorny things will happen in reviewing pr. For example, some issues need final discussion or final checking, but because the last step is not in time, conflicts caused by other changes will occur to it when merging. This will make the advance time of the whole PR increase linearly, and it will also increase the burden on authors and reviewers. This is undoubtedly a slow unhealthy cycle.

Again, Thank you very much for your attention.

**Comment by RocMarshal** [comment]
@flinkbot run azure

**Comment by lsyldliu** [comment]
@RocMarshal Thanks for your contribution, I will take a look for this PR, please be patient.

**Comment by lsyldliu** [comment]
Thanks for your contribution, this PR is a bit big, we can break it down into two, first pr supports add column syntax, then the second supports convert SqlNode to Operation. I took a brief glance at the code and the implementation at the calcite syntax level is a bit short of expectations. Therefore, I suggest that I do the add column syntax first, and then you implement the second PR, how do you feel about it?

**Comment by RocMarshal** [comment]
Please let me know what is your expectation in the  jira. thx a lot.

**Comment by lsyldliu** [comment]
@RocMarshal Thanks for your contribution, the syntax pr has merged into master, you can continue this work.

**Comment by RocMarshal** [comment]
> @RocMarshal Thanks for your contribution, the syntax pr has merged into master, you can continue this work.

@lsyldliu Nice work on FLINK-21683 !. Would you like to take the current ticket ?

**Comment by lsyldliu** [comment]
> > @RocMarshal Thanks for your contribution, the syntax pr has merged into master, you can continue this work.
> 
> @lsyldliu Nice work on [FLINK-21683](https://issues.apache.org/jira/browse/FLINK-21683) !. Would you like to take the current ticket ?

Ok, we can take over this work, cc @LadyForest .

**Comment by LadyForest** [comment]
> > > @RocMarshal Thanks for your contribution, the syntax pr has merged into master, you can continue this work.
> > 
> > 
> > @lsyldliu Nice work on [FLINK-21683](https://issues.apache.org/jira/browse/FLINK-21683) !. Would you like to take the current ticket ?
> 
> Ok, we can take over this work, cc @LadyForest .

Thanks for the update and let me take a look :)

**Pull request closed without merging**
