### PR TITLE
[FLINK-1318] CsvInputFormat: Made quoted string parsing optional with configurable quote character. Simplified parsing

### PR DESCRIPTION
**Pull request by fhueske**
- Parsing of quoted strings is disabled by default
- When enabling a quoting character needs to be specified
- If quoting parsing is enabled, Strings are parsed as quoted if the first character is the quoting character (leading and tailing whitespace characters are NOT ignored)
- If quoting parsing is enabled and the first character is NOT the quoting character, Strings are treated as unquoted
- Quoted parsing fails 1) if the last character of the field ist NOT the quote character (tailing characters), or 2) the closing quote character is missing

This mode of operation differs from the previous implementation:
- Leading and tailing characters were ignored in case of quoted strings but would have caused problems if whitespaces were used as field delimiters.
- double quote characters could be used to escape quotes in quoted strings

### CODE REVIEW

**Comment by fhueske** [comment]
Any comments on this PR?

**Comment by mxm** [comment]
Looks good to me. How about adding some documentation for this feature? Maybe under http://flink.apache.org/docs/0.8/programming_guide.html#data-sources

**Comment by fhueske** [comment]
Yes, that's still left to do... ;-)

**Comment by fhueske** [comment]
I added documentation. Any objections against merging this?

**Comment by StephanEwen** [comment]
Looks good so far. What about this PR is API breaking?

**Comment by fhueske** [comment]
The API was just extended, but the parsing logic for strings changed (see PR description). So programs that relied on the previous way of parsing will fail now.

**Comment by mxm** [comment]
Looks good to me.

**Comment by fhueske** [comment]
Other comments on the API breaking.
If not, I'd merge it...

**Pull request closed without merging**
