### PR TITLE
[FLINK-2677] Add a general-purpose keyed-window operator

### PR DESCRIPTION
**Pull request by aljoscha**
This adds a new window operator that works like a combination of the Google Dataflow windowing semantics and our existing trigger/eviction semantics.

There are now two styles of API, the old policy based style:
```java
DataStream<MyType> stream = ...;

stream.keyBy("id")
      .window(Time.of(5, SECONDS), Count.of(10))
      .reduceWindow( (a, b) -> a.fuse(b) )
```

and a new assigner/trigger API:
```java
DataStream<MyType> stream = ...;

stream.keyBy("id")
      .window(SlidingTimeWindows.of(1000, 100))
      .trigger(Count.of(100))
      .evictor(DeltaEvictor.of(...))
      .reduceWindow( (a, b) -> a.fuse(b) )
```
(both trigger and evictor are optional, window assigners have default triggers specified).

The new operator basically works by grouping elements by key and window where the key is assigned by the `KeySelector` and the window is assigned by the `WindowAssigner`. The `Trigger` specifies when one of the groups that emerge from this should fire. The windows for different groups can fire at arbitrary times.

The policy based windows are translated to either @StephanEwen's new fast aligned time windows operator or the generic assigner/trigger/evictor operator, based on what is possible.

I added tests for the `WindowOperator` itself in `WindowOperatorTest` and `EvictingWindowOperatorTest`. The translation from the API to correct window operator is verified in `PolicyWindowTranslationTest` and `TriggerWindowTranslationTest`.

This does not yet change the documentation since the old API is still completely intact. The new API is added in parallel to the old API. Once we write the documentation the old code should be removed.

This subsumes #1175

### CODE REVIEW

**Comment by StephanEwen** [comment]
Very nice. Just tried this out, the examples seem to work nicely.

+1 to merge this!

**Comment by StephanEwen** [comment]
A follow-up question: How far do the implementations support event-time based windowing so far?

**Comment by aljoscha** [comment]
Event-time windowing is supported if you manually enable watermarks using `setWatermarkInterval` (it is still called `setAutoWatermarkInterval` but I want to change this in an upcoming PR. 

It is very tricky to derive a watermark interval, that's why I'm not doing it yet. In the upcoming PR I want to add an operator that can extract timestamps from records and also emit watermarks based on these timestamps. I guess no one would implement a custom source for watermark emission. Most people would use Kafka and then extract timestamps after that.

**Comment by aljoscha** [comment]
One thing to note here is that you cannot use the old `TriggerPolicy` and `EvictionPolicy` anymore. The old concept of windowing helpers is replaced by windowing policies. There is `Time`, `Count` and `Delta`.  These are translated to `Trigger` and `Evictor` instances using a fixed translation mapping in `PolicyToOperator`.

If a user wan't the full flexibility they have to specify a `WindowAssigner`. For example, this old API code:
```java
input.window(new MyCustomEvictionPolicy).every(new MyCustomTriggerPolicy)
```

can be written with the new API as:
```java
input.window(GlobalWindows.create())
  .trigger(new MyCustomTrigger)
  .evictor(new MyCustomEvictor)
```

(I could add a shortcut to `KeyedDataStream`, so that you can directly do `.window(Evictor, Trigger)` with an implied `GlobalWindows` assigner.)

Also worth mentioning is that there is no pre-aggregation if an `Evictor` is used.

**Comment by StephanEwen** [comment]
I assume global windows here means something different than the old API implied with global windows (= discretization across streams, before grouping).

From my side, +1 to merge as it is

We'll file followup JIRAs for the other issues.

**Pull request merged**
