### PR TITLE
[FLINK-5718] [core] TaskManagers exit the JVM on fatal exceptions.

### PR DESCRIPTION
**Pull request by zimmermatt**
Manually applied and adapted commit dfc6fba5b9830e6a7804a6a0c9f69b36bf772730 for
the `release-1.2` branch.

### CODE REVIEW

**Comment by zimmermatt** [comment]
@tillrohrmann, this is the port of FLINK-5718 to the `release-1.2` branch I mentioned.  It mostly transferred over, but I needed to make some judgement calls in `TaskManagerConfiguration`, `TaskManagerRuntimeInfo`, and `JvmExitOnFatalErrorTest`.

Please let me know if you see anything that should be done differently.

**Comment by tillrohrmann** [comment]
Thanks for your contribution @zimmermatt. Changes look good to me. Merging this PR.

**Comment by tillrohrmann** [comment]
I've merged your PR. Please close this PR since it does not get closed automatically if the commit is not merged into the master.

**Comment by zimmermatt** [comment]
Done @tillrohrmann. This is my first github pull request, so I didn't know I needed to do that manually :-)

**Comment by tillrohrmann** [comment]
Only for PR which are opened against another branch than `master`. For `master` I can close it. Thanks again for your work.

**Pull request closed without merging**
