### PR TITLE
[FLINK-4705] Instrument FixedLengthRecordSorter

### PR DESCRIPTION
**Pull request by greghogan**
Updates comparators with support for key normalization.

### CODE REVIEW

**Comment by StephanEwen** [comment]
I have started like to take a look at this...

The `FixLegthRecordSorter` and its interactions with the serializers / comparators was not very well tested before, hence not activated. I am trying to double-check that...

**Comment by greghogan** [comment]
Hi @StephanEwen, should we endeavor to get this into 1.2 or defer to the next release?

**Comment by StephanEwen** [comment]
@greghogan I am quite deep into some large scale deployment and scalability issues right now. I plan to write a mail to the mailing list on that, actually.

If possible, I'd like to defer this for a bit. I hope to find some time between the years to go over pull request and do catching up with these threads.

**Comment by greghogan** [comment]
@StephanEwen, no worries about deferring this. Performance is nice but scaling and stability certainly takes precedence. Just wanted to make sure there was ample time between review and release.

**Comment by aljoscha** [comment]
I'm closing this as "Abandoned", since there is no more activity and the code base has moved on quite a bit. Please re-open this if you feel otherwise and work should continue.

**Pull request closed without merging**
