### PR TITLE
[FLINK-12928][docs] Remove old Flink ML docs

### PR DESCRIPTION
**Pull request by sjwiesman**
## What is the purpose of the change

The old Flink ML library has been removed so we should also remove the documentation. Existing users can use documentation from a prior version.

## Brief change log

- Remove Old FlinkML docs and set up proper redirects

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

### CODE REVIEW

**Comment by sjwiesman** [comment]
cc @rmetzger

**Comment by zentol** [comment]
The old flink-ml library totally still exists: https://github.com/apache/flink/tree/master/flink-libraries/flink-ml, #8526 has not been merged yet.

**Comment by sjwiesman** [comment]
Well this is embarrassing, closing.

**Comment by shaoxuan-wang** [comment]
@sjwiesman #8526 is closed, let us move onto this PR. @c4emmmm please also take some time to review this PR. Thanks.

**Comment by sjwiesman** [comment]
@shaoxuan-wang +1 

I did a quick grep and believe I've removed all remnants of FlinkML from the docs.

**Comment by c4emmmm** [comment]
The changes look good to me. @shaoxuan-wang

**Comment by sjwiesman** [comment]
If there aren't any issues it would be great to have this merged into the 1.9 branch so that the docs reflect the state of that release.

**Comment by sjwiesman** [comment]
@shaoxuan-wang @fhueske If there aren't any issues I believe it is really important to get this merged in and backported to the release-1.9 branch

**Comment by StephanEwen** [comment]
Thanks, @sjwiesman will merge this...

**Pull request closed without merging**
