### PR TITLE
[FLINK-24351][docs] Translate "JSON Function" pages into Chinese

### PR DESCRIPTION
**Pull request by MonsterChenzhuo**
## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by RocMarshal** [comment]
@MonsterChenzhuo Maybe you should rebase from latest master branch for your branch and resolve the conflicting file before next review .

**Comment by MonsterChenzhuo** [comment]
> 
> 
> @MonsterChenzhuo 感谢您的更新。 也许你应该从最新的 master 分支为你的分支 rebase 并在下次审查之前解决冲突的文件。
@RocMarshal  I'm really sorry for the recent delay. I will deal with it as soon as possible tomorrow

**Comment by MonsterChenzhuo** [comment]
@RocMarshal https://github.com/apache/flink/pull/17789   Please check it again. I was delayed by something at home

**Comment by RocMarshal** [comment]
> @RocMarshal #17789 Please check it again. I was delayed by something at home

Excuse me, please let me know why did you switch the pr to #17789 instead of keeping it currently?

**Comment by MonsterChenzhuo** [comment]
@RocMarshal Sorry for the trouble,I'm new to Github and it's not very clear how it works, which led to a previous shutdown and the creation of a new PR.Now I know I can submit multiple times on a PR.

**Comment by RocMarshal** [comment]
> @RocMarshal Sorry for the trouble,I'm new to Github and it's not very clear how it works, which led to a previous shutdown and the creation of a new PR.Now I know I can submit multiple times on a PR.

Take it easy. If you have any questions, you could discuss its on the email or in the pr. 
So, if you are willing to advance the jira in the new pr,  I'll do the review based on the new one. 
If you still use this pr page, may be you could rebase the latest master branch in your pr-branch and push it forced to your remote pr-branch.

**Comment by MonsterChenzhuo** [comment]
@RocMarshal Please go to #17789 to review

**Pull request closed without merging**
