### PR TITLE
[FLINK-13714] Remove Program-related code.

### PR DESCRIPTION
**Pull request by kl0u**
## What is the purpose of the change

This PR implements the removal of the `Program` interface, as discussed in [FLIP-52](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=125308637)

It contains 2 commits, one for the code removal and one for the english documentation update.

## Verifying this change

This change is code cleanup and it is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (**yes** / no)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - How is the feature documented? (not applicable / **docs** / JavaDocs / not documented)

### CODE REVIEW

**Comment by kl0u** [comment]
@TisonKun @aljoscha I am waiting for Travis but after that could you please have a look?

@TisonKun do you think you could update the chinese version of the docs?

**Comment by TisonKun** [comment]
I'm glad to update the Chinese version of the docs. Follow the workflow I need a committer assign the JIRA to me but of course I would concurrently work on it.

**Comment by zentol** [comment]
@TisonKun could you just prepare a branch with the commit and send it to @kl0u ? Let's handle this in one go if possible.

**Comment by TisonKun** [comment]
@zentol I think attach a patch on the JIRA and @kl0u merge it locally works?

**Comment by TisonKun** [comment]
Hi @kl0u with this pr merged we can fix FLINK-13332 and FLINK-13333 as a side-effect. Also I attached a patch on [FLINK-13716](https://issues.apache.org/jira/browse/FLINK-13716) that fix Chinese document side.

Could you see whether include that patch in this merging thread or I open an extra pr and let's finish FLIP-52?

**Pull request closed without merging**
