### PR TITLE
[FLINK-8053] Default to asynchronous snapshots for FsStateBackend and MemoryStateBackend

### PR DESCRIPTION
**Pull request by StefanRRichter**
## What is the purpose of the change

This PR changes the default configuration for all heap based state backends to use asynchronous snapshots.

## Brief change log

All constructors now use `true` as value for setting asynchronous snapshot mode.

## Verifying this change

I added `HeapKeyedStateBackendAsyncByDefaultTest`.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (yes)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (changed the docs)

### CODE REVIEW

**Comment by StefanRRichter** [comment]
CC @aljoscha

**Comment by aljoscha** [comment]
This looks good! 👍 

Please make sure to merge onto `master` as well as `release-1.4`.

**Comment by aljoscha** [comment]
@StefanRRichter Will you merge this?

**Comment by StefanRRichter** [comment]
Sure, I can merge it immediately if you want.

**Pull request closed without merging**
