### PR TITLE
[FLINK-15807][docs] Add Java 11 to supported JDKs

### PR DESCRIPTION
**Pull request by zentol**
Adds Java 11 to the set of supported JDKs.

Note that certain features (cassandra, hive, hbase, kafka 0.X) may not work on Java 11, but I don't know whether this is due to an incompatibility in our connector or the external server (the more likely). Hence I opted to not document this, on the assumption that users will run their stuff on a single Java version, and if they have Java 11 with a working cassandra server then the connector will likely work as well.

### CODE REVIEW

**Comment by GJL** [comment]
> Meanwhile, if we're going to announce java 11 support in 1.10.0 release, hopefully somewhere we could remind our users that certain source/sink (cassandra/hbase/hive/old-version-kafka) don't support java 11 yet, 

I don't understand what we want to document exactly. The description of the PR says that we do not fully understand why some connectors don't work. I am against documenting things that we don't understand ourselves.

**Comment by zentol** [comment]
We could document that we haven't tested these features on Java 11, since the backing library does not officially support Java 11.

**Comment by GJL** [comment]
I am ok with saying that we haven't tested some connectors. Is there a list of untested connectors or should we just say all of them?

**Comment by zentol** [comment]
What is listed in the PR description (Cassandra, Hive, HBase, Kafka 0.8-0.11), and YARN. These are the features for which we have tests that are not running on Java 11.

**Comment by carp84** [comment]
> What is listed in the PR description (Cassandra, Hive, HBase, Kafka 0.8-0.11). These are the features for which we have tests that are not being run on Java 11. We also have no e2e runs on YARN, but the IT cases are passing.

I could see this already tracked by #10997 , so it seems the PR here is ready to go.

**Pull request merged**
