### PR TITLE
[FLINK-26614]Upsert Kafka SQL Connector:Support startup mode of timestamp and specific offsets

### PR DESCRIPTION
**Pull request by mnmaning**
When we run Flink SQL using upsert-kafka connector, it cannot support startup mode of timestamp or specific offsets. It is determined to read data from the earliest.

I don't think it's reasonable. Because the data stored in Kafka is incomplete that it only saves data for 7 days in most cases. So why don't we consume data from the specified timestamp or offsets, and this can improve the efficiency of reading data from Kafka.

### CODE REVIEW

**Comment by dengziming** [comment]
Maybe we should add a test case since this is a new feature.

**Comment by mnmaning** [comment]
> Maybe we should add a test case since this is a new feature.

How to add a test case?

**Comment by slinkydeveloper** [comment]
@mnmaning I think in this case just adding a test to `UpsertKafkaDynamicTableFactoryTest` is fine, as you're just exposing a config option

**Comment by davidradl** [comment]
@slinkydeveloper  I see https://github.com/apache/flink/pull/22797 , this pr is no longer relevant to this repository, I suggest closing this pr and porting the change to the [new Flink connector kafka repo]( https://github.com/apache/flink-connector-kafka) if it is still relevant.

**Comment by MartijnVisser** [comment]
@mnmaning The Flink Kafka connector resides in it's own repository nowadays, if this code change is still relevant, please open the PR in https://github.com/apache/flink-connector-kafka

**Pull request closed without merging**
