### PR TITLE
[FLINK-33626] Revert accidentally committed changes to docs

### PR DESCRIPTION
**Pull request by snuyanzin**
## What is the purpose of the change

This the revert of changes in docs accidentally introduced in https://github.com/apache/flink/pull/23751

## Verifying this change
```sh
$ git submodule update --init --recursive
$ ./setup_docs.sh
$ docker pull jakejarvis/hugo-extended:latest
$ docker run -v $(pwd):/src -p 1313:1313 jakejarvis/hugo-extended:latest server --buildDrafts --buildFuture --bind 0.0.0.0
```
and look into docs locally

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: ( no)
  - The runtime per-record code paths (performance sensitive): ( no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: ( no)
  - The S3 file system connector: ( no )

## Documentation

  - Does this pull request introduce a new feature? ( no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by snuyanzin** [comment]
@WencongLiu , @FangYongs could you please have a look here since you are participating in jira issue?

**Review by RyanSkraba — COMMENTED** [review]
LGTM - I checked that the website builds **without** the navigation bar glitches after the submodule is restored.

**Review by XComp — APPROVED** [review]
LGTM2 :+1: 

I noticed that as well that the book submodule changed in my local checkout. I had to revert it manually. Shall we investigate further why this happened as part of FLINK-33626? Or shall we create a new Jira issue. I'd say keeping FLINK-33626 open till this is fixed should be sufficient enough. :thinking:

**Review by RyanSkraba — APPROVED** [review]

**Comment by snuyanzin** [comment]
Thanks for taking a look
I will try to investigate more within [FLINK-33626](https://issues.apache.org/jira/browse/FLINK-33626)

**Pull request merged**
