### PR TITLE
[FLINK-11326] [streaming] Fix forbidden negative offset in window assigners

### PR DESCRIPTION
**Pull request by kezhuw**
## What is the purpose of the change
Allow negative window offset in window assignment as the javadoc says.

## Brief change log
- Allow negative window offset in window assignment.
- Throw `IllegalArgumentException` if offset is out of range for `SlidingEventTimeWindows.of` and `SlidingProcessingTimeWindows.of`. 

## Verifying this change

This change is already covered by existing tests and new test cases has been added to allow negative window offset.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

## Breaking changes
* `@PublicEvolving` API `SlidingEventTimeWindows.of` and `SlidingProcessingTimeWindows.of` allows out of window offset previously, this merge request forbid this behavior. This way they behaves same as `TumblingEventTimeWindows.of` and `TumblingProcessingTimeWindows.of`. I think it is easier for caller to understand [sliding windows](https://ci.apache.org/projects/flink/flink-docs-master/dev/stream/operators/windows.html#sliding-windows).

### CODE REVIEW

**Comment by kezhuw** [comment]
@aljoscha Could you take time to review this merge request ?

**Comment by rmetzger** [comment]
Thank you for opening this pull request. Aljoscha is on vacation this week, so you have to be a little bit patient till he (or somebody else) looks at the change.

**Comment by kezhuw** [comment]
@rmetzger Thanks, I know it. By the way, is there any document somewhere listing component maintainers so newbies like me know who is appropriate reviewer to cc ? Or we rely on robots to notify component maintainers from component name associated with issue or merge request title ?

**Comment by rmetzger** [comment]
@kezhuw The community is currently discussing to introduce labels, so that component owners can have a better overview over "their" pull requests.

**Pull request closed without merging**
