### PR TITLE
[FLINK-21829][Hive Connect]Fix to throw exception when custom hadoop conf path does not exist or there is no conf file

### PR DESCRIPTION
**Pull request by hehuiyuan**
## What is the purpose of the change
There is no prompt when the the path to hadoop conf configured is wrong unintentional.
It is better to  load hadoop conf from possiable  hadoop path when the path is wrong.

[PR ahead](https://github.com/apache/flink/pull/15274)

### CODE REVIEW

**Comment by hehuiyuan** [comment]
Hi @wuchong ,
there are some problems with my local branch, I create  new branch to resolve.

**Comment by hehuiyuan** [comment]
@flinkbot re-run

**Comment by hehuiyuan** [comment]
Hi  @wuchong @lirui-apache ,
is there any conflict?

**Review by lirui-apache — APPROVED** [review]
+1

**Comment by lirui-apache** [comment]
Hi @hehuiyuan , the new PR looks good to me. But it's better to rebase your old PR than opening a new one. A new PR usually means it needs to be reviewed again.

**Comment by hehuiyuan** [comment]
> Hi @hehuiyuan , the new PR looks good to me. But it's better to rebase your old PR than opening a new one. A new PR usually means it needs to be reviewed again.

Hi @lirui-apache  @wuchong  , i'm sorry for bringing you extra work , please review it again.
There are some problems for old branch.

**Comment by hehuiyuan** [comment]
Hi @wuchong ，have a look at it sometime

**Comment by hehuiyuan** [comment]
Hi @lirui-apache  @wuchong , please take a look when you have time.

**Comment by hehuiyuan** [comment]
Hi @wuchong ,  please take a look when you have time.

**Review by wuchong — APPROVED** [review]
LGTM

**Pull request closed without merging**
