### PR TITLE
[FLINK-2342] [ml]  Add new fit operation and more tests for StandardScaler

### PR DESCRIPTION
**Pull request by thvasilo**
StandardScaler currently has a transform operation for types (Vector, Double), but no corresponding fit operation.

The test cases also do not cover all the possible types that we can call fit and transform on.

This PR addresses this, and removes some unused code.

### CODE REVIEW

**Comment by fhueske** [comment]
Thanks @thvasilo for the PR.
LGTM, @tillrohrmann can you check as well?

**Comment by chiwanpark** [comment]
Looks good to merge. If there is no other opinions in 2-3 days, I'll merge this to master.

**Comment by tillrohrmann** [comment]
+1 for merging

**Comment by chiwanpark** [comment]
Merging this...

**Pull request closed without merging**
