### PR TITLE
[FLINK-1460] fix typos

### PR DESCRIPTION
**Pull request by coderxiang**
Fix some typos. Also fix some inconsistent uses of **partition operator** and **partitioning operator** in the codebase.

### CODE REVIEW

**Comment by hsaputra** [comment]
+1 

LGTM

**Comment by aljoscha** [comment]
+1, can you merge it @hsaputra or should I?

**Comment by coderxiang** [comment]
@hsaputra @aljoscha I failed one check which I don't have much idea about. Could you please retest?

**Comment by hsaputra** [comment]
HI @aljoscha, thanks. 
If you could merge it before later tonight please do. Otherwise I could do it later tonight if you did not have time to get to this one =)

**Comment by hsaputra** [comment]
@coderxiang, ah that the tests do comparison in the after method so it is hard to figure out which method fail. But seemed like other builds passed and I am sure that your change does not cause this problem

**Comment by hsaputra** [comment]
Merged, thanks for the fix @coderxiang

**Pull request closed without merging**
