### PR TITLE
[FLINK-4693][tableApi] Add session group-windows for batch tables

### PR DESCRIPTION
**Pull request by sunjincheng121**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [×] General
  - The pull request references the related JIRA issue ("[FLINK-4693] Add session group-windows for batch tables")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [×] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by KurtYoung** [comment]
@sunjincheng121 Thanks for your work, can you rebase this to the latest master first, i will try to take a look then.

**Comment by twalthr** [comment]
I think it would make sense to wait until #2938 is merged and rebase it on top of it.

**Comment by sunjincheng121** [comment]
@twalthr that's right. Thanks @KurtYoung I'll rebase code until #2938 is merged.

**Comment by twalthr** [comment]
@sunjincheng121 I have merged #2938. You can update this PR.

**Pull request closed without merging**
