### PR TITLE
[FLINK-21390] Rename DeclarativeScheduler to AdaptiveScheduler 

### PR DESCRIPTION
**Pull request by tillrohrmann**
Renames the `DeclarativeScheduler` into `AdaptiveScheduler`.

Note that this commit also changes the system property to enable the adaptive scheduler
from `flink.tests.enable-declarative-scheduler` to `flink.tests.enable-adaptive-scheduler`.

This PR is based on #14969.

### CODE REVIEW

**Review by zentol — APPROVED** [review]

**Comment by tillrohrmann** [comment]
Thanks for the review @zentol. Merging this PR now.

**Comment by rmetzger** [comment]
Why were the configuration keys not renamed in this PR? 
https://github.com/apache/flink/blob/master/flink-core/src/main/java/org/apache/flink/configuration/JobManagerOptions.java#L391

**Comment by tillrohrmann** [comment]
I forgot to rename them. I will update them in a hotfix commit.

**Comment by rmetzger** [comment]
Thanks a lot!

**Pull request closed without merging**
