### PR TITLE
[hotfix][doc] Fix invalid sql comments and words in timezone.md

### PR DESCRIPTION
**Pull request by hackergin**
## What is the purpose of the change

*Fix invalid sql comment and words in timezone.md*

## Brief change log

  - *Fix invalid sql comment and words in timezone.md*

## Verifying this change

* doc fix , not need to verify 

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by hackergin** [comment]
@leonardBang  A small fix for timezone doc.

**Comment by leonardBang** [comment]
Thanks @hackergin for the contribution, could we fix this one another translation PR?

**Review by leonardBang — APPROVED** [review]
LGTM

**Comment by hackergin** [comment]
move changes to  https://github.com/apache/flink/pull/15753  and close this pr.

**Pull request closed without merging**
