### PR TITLE
[FLINK-1582][streaming]Allow SocketStream to reconnect when socket closes

### PR DESCRIPTION
**Pull request by qmlmoon**

### CODE REVIEW

**Comment by mbalassi** [comment]
Thanks for quickly picking out the issue. Looks good to me I might modify it to exponentially increase wait time until a limit instead of constant 5 seconds. What do you think, which would you prefer as a user?

**Comment by chiwanpark** [comment]
+1 for exponentially increasing wait time

**Comment by qmlmoon** [comment]
As a user I would expect the system could carry on quickly after server socket is reinitiated. A large limit of exponentially increase may lead to potential long wait and a small one makes it similar to constant way. what number do you suggest?

**Comment by mbalassi** [comment]
I was thinking as high as a minute to have as a limit. But after reconsidering it I am for your argument, trying to establish the connection every couple of seconds should not be a big overhead, so my whole idea might be an overkill. Let us have your version for now and generalize it on request.

**Pull request closed without merging**
