### PR TITLE
[FLINK-32585] Use flink-connector-pulsar shade pattern

### PR DESCRIPTION
**Pull request by tisonkun**
This commit https://github.com/apache/flink-connector-pulsar/pull/54/commits/c78689c4ea62b17e99e2353f9e05967558e09465 change the relocation strategy for flink-connector-pulsar to try to resolve class loading issue. As it doesn't introduce regression, I'd prefer to apply the new shade pattern to all the deps there for consistency.

If we have a suppression file for these checks it can be more smooth, but I'm OK with cross repo updating as long as it's temporary traffic and we can finally converge.

cc @zentol 

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by zentol — COMMENTED** [review]
I'm a bit wary about _modifying_ existing entries; wouldn't that prevent the pulsar 2.x connector version from working against 1.18?

**Comment by tisonkun** [comment]
@zentol IIUC `LicenseCheck` works for CI only and this is a false positive. As long as previous connector versions pin a previous ci-tool version, it should be fine.

But I notice that change the relocate pattern may not fix the real class not found issue, so if it's proven I'll close this PR.

**Comment by zentol** [comment]
> But I notice that change the relocate pattern may not fix the real class not found issue, so if it's proven I'll close this PR.

Can you link some ticket or context for the problem?

**Comment by tisonkun** [comment]
@zentol this is the related PR - https://github.com/apache/flink-connector-pulsar/pull/54

I'm filing a ticket now.

It seems without this new shade pattern tests always failed. According to your suggestions above, duplicating the before and after shade patterns can be a solution?

**Comment by zentol** [comment]
> I notice that change the relocate pattern may not fix the real class not found issue,

> It seems without this new shade pattern tests always failed.

I'd love to get a summary of what works and what doesn't with what changes to the shade-plugin / ci-tools; I can't wrap my head around the current state.

The PR description states that the original PR failed with a CNFE for a relocated netty class, using the original pulsar relocation.
You then tried to change the relocation pattern (why?), which required changes to ci-tools; what's still unclear to me is whether it fixed the issue or not. 

If some class is missing from pulsar then another round of relocations shouldn't make a difference _unless_ you also bundle another netty version and relocate that as well.
Double-check whether the final jar actually contains the relocated netty.
In fact, double-check that the original pulsar jars actually contain the relocated netty.
Let's make sure we aren't trying to build on a rotten foundation here (== packaging issues on the pulsar side).

**Comment by tisonkun** [comment]
I hope the upgrade doesn't cause anything else to change, or if I can understand why tests failed.

But the test can pass in locally -

image

So it can be a CI environment issue 🤣

**Comment by tisonkun** [comment]
It seems the failure is related to other exceptions instead of CNFE. I'll check for details.

It's strange that it's related to the change, but if an initial correct solution can resolve the issue, it is not a hack to owe some debts.

**Comment by tisonkun** [comment]
From another aspect, if with the shade pattern changes we can avoid the issue, but we cannot update LicenseChecker so that we change the shade pattern particially, it's a hack to me.

**Comment by tisonkun** [comment]
The original patch failed seems on difference about OOM, perhaps retry helps. I don't know if we can extend the memory limit or it's something that the pulsar connector consume too much memory.

**Comment by tisonkun** [comment]
Closing...

Although I'd prefer to use the connector's shade pattern instead of the pulsar's one even without the CI failure, I can spend time to investigate the other issue now.

**Pull request closed without merging**
