### PR TITLE
[FLINK-1463] Fix stateful/stateless Serializers and Comparators

### PR DESCRIPTION
**Pull request by aljoscha**
Before, Serializers would announce whether they are stateful or not and
rely on RuntimeStatefulSerializerFactory to do the duplication.
Comparators, on the other hand, had a duplicate method that the user was
required to call.

This commit removes the statful/stateless property from Serializers but
instead introduces a duplicate() method, similar to Comparators, that
can return the same instance.

The two serializer factories are merged into one that always calls
duplicate() before returning a serializer.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Looks good. For efficiency, we could change the factory such that it returns the original in the first request, and a duplicate after that.

Good change otherwise.

+1 to merge

**Comment by aljoscha** [comment]
Do you think that with the additional checking logic this would really make up for one superfluous duplication?

**Comment by StephanEwen** [comment]
Yes. Some serializers are heavyweight and often, the factories produce only one serializer through their lifetime. It is a nice improvement, bot a crucial one, though.

**Comment by aljoscha** [comment]
Ok, then I'll add this.

**Comment by StephanEwen** [comment]
Thanks. Sorry for being picky ;-)

**Comment by StephanEwen** [comment]
+1 to merge

**Comment by aljoscha** [comment]
Manually merged.

**Pull request closed without merging**
