### PR TITLE
[FLINK-10911][scala-shell] Enable flink-scala-shell with Scala 2.12

### PR DESCRIPTION
**Pull request by zjffdu**
## What is the purpose of the change

This PR is to enable flink-scala-shell with scala-2.12. Previous we disable it because flink scala shell doesn't work with scala 2.12, but now it seems not true. The CI is passed and I also verify it in my local machine. flink scala-shell works well with scala 2.12.

## Brief change log

Just enable flink-scala-shell with scala 2.12 in pom file

## Verifying this change

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency):  (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by zjffdu** [comment]
@flinkbot run azure

**Comment by zentol** [comment]
Can you give a quick note on what the goal of this PR is?

**Comment by zjffdu** [comment]
@zentol It is WIP PR, I can run scala shell 2.12 successfully in my local machine. I just want to run it in CI to check whether it can pass CI.

**Comment by zjffdu** [comment]
@flinkbot run azure

**Comment by zjffdu** [comment]
@tillrohrmann @aljoscha @zentol Could you help review this PR ? Thanks

**Comment by aljoscha** [comment]
Ah sorry @tillrohrmann! While you were writing your message I was merging the PR. I was assuming that azure and travis run the Scala 2.12 profiles.

What should we do?

**Comment by aljoscha** [comment]
I'm running the test locally now.

**Comment by aljoscha** [comment]
The tests don't pass, I reverted the change on master. Sorry about this, I was too eager in merging.

**Comment by zjffdu** [comment]
@aljoscha What kind of error do you see  ?

**Comment by aljoscha** [comment]
The assertions in `ScalaShellITCase` fail because the invoked programs produce null pointer exceptions. I didn't look further, so I don't know why the exceptions are thrown.

**Comment by zjffdu** [comment]
It is weird, I remember I ran test successfully before, let me try it again.
BTW, do you mean all the tests of scala 2.12 is not enabled in CI ? I thought only tests for flink scala shell is disabled, and I enable it in this PR.

**Comment by zentol** [comment]
We only use scala 2.11 on CI; this is fully independent of whether the scala-shell tests run or not.

**Comment by zjffdu** [comment]
@aljoscha I found the reason why I ran it successfully last time. I only run `mvn test`, but should run `mvn verify`, otherwise the tests under scala folder is not executed.

Regarding this issue, I found that after I use `repl-class-based`, CI can pass with scala-2.12. Maybe it is related with this (https://users.scala-lang.org/t/is-this-a-known-repl-bug/3271). But it causes the case class can not be used in scala-shell, which I talked with you before. How about we fix the case class issue later ? Because I think it is fixable, spark scala shell support case class, we can borrow some ideas from spark.

**Comment by aljoscha** [comment]
@zentol How do you mean? When building with Scala 2.11 `flink-scala-shell` is excluded, so the tests for the shell are not run on a Scala 2.12 build.

**Comment by zentol** [comment]
@aljoscha yes? In any case we only run 2.11 on CI, that's all I was saying. This was a response to the previous comment from Jeff:
> BTW, do you mean all the tests of scala 2.12 is not enabled in CI ? I thought only tests for flink scala shell is disabled, and I enable it in this PR.

**Comment by aljoscha** [comment]
@zjffdu Is spark also using `repl-class-based`? If yes, do you know how they manage to support case classes.

@zentol Yes, `flink-scala-shell` is excluded when the `scala-2.12` profile is active, which is what this PR changes.

**Comment by zjffdu** [comment]
@aljoscha Right, spark use `repl-class-based`. Regarding how spark support case classes, I need investigation further

**Comment by zjffdu** [comment]
@aljoscha I found that the case class issue is caused by `FLINK-10493` which introduce `ScalaCaseClassSerializer`. In our internal flink branch which is based on 1.5 that has no `ScalaCaseClassSerializer` it works even when I use `repl-class-based` in scala shell.

**Comment by aljoscha** [comment]
@zjffdu Should we still try and get this in for Flink 1.12? Sorry for the very long delay on this one! 😱

**Comment by zjffdu** [comment]
Sorry @aljoscha I am afraid I don't have time to get it into 1.12, let's try that in the next release.

**Comment by aljoscha** [comment]
No worries. 😃

**Comment by aalexandrov** [comment]
Just to clarify - after building a scala-shell with the changes from this PR, and testing as follows:

1. Start scala-shell:

```bash
bin/start-scala-shell.sh local
```

2. Run 

```scala
scala> case class Pair(x: Int, y: Int)
defined class Pair

scala> benv.fromElements(1,2,3).map(x => Pair(x,x)).collect()
java.lang.IllegalArgumentException: requirement failed:
The class Pair is an instance class, meaning it is not a member of a
toplevel object, or of an object contained in a toplevel object,
therefore it requires an outer instance to be instantiated, but we don't have a
reference to the outer instance. Please consider changing the outer class to an object.

  at scala.Predef$.require(Predef.scala:277)
  at org.apache.flink.api.scala.typeutils.ScalaCaseClassSerializer$.lookupConstructor(ScalaCaseClassSerializer.scala:97)
  at org.apache.flink.api.scala.typeutils.ScalaCaseClassSerializer.<init>(ScalaCaseClassSerializer.scala:46)
  ... 70 elided
```

The problem is that with `-Yrepl-class-based` enabled, UDTs (such as case classes) are defined within a nested class, and as such cannot be easily serialized (the `ScalaCaseClassSerializer` invoked by the `org.apache.flink.api.scala.createTypeInformation` throws a very detailed error explaining this).

I am not sure what were the use-cases that lead the Scala team (and Spark) to adopt `-Yrepl-class-based` over the traditional object-based wrapping - it seems that nesting objects in objects is more robust w.r.t. serialization. 

FYI in Scala 2.13 the default is class-based and it needs to be explicitly disabled with `-Yrepl-class-based:false`.

@aljoscha / @zjffdu: do you know any particular scenarios where object-based REPL is problematic?

**Comment by zjffdu** [comment]
@aalexandrov Thanks for looking into this issue, here's 2 tickets that are related
https://issues.apache.org/jira/browse/SPARK-1199
https://issues.apache.org/jira/browse/SPARK-17103

**Comment by AHeise** [comment]
Closing this PR due to https://issues.apache.org/jira/browse/FLINK-24360 / https://github.com/apache/flink/pull/17340

**Pull request closed without merging**
