### PR TITLE
[FLINK-1271] Remove writable limitation

### PR DESCRIPTION
**Pull request by FelixNeutatz**
This pull request will remove the limitation of the Hadoop Format to use writables. This makes it possible to use Parquet.

### CODE REVIEW

**Comment by rmetzger** [comment]
Hi,

the changes look good. Can you apply the changes also to the "mapred" input/output format? https://github.com/apache/flink/blob/master/flink-addons/flink-hadoop-compatibility/src/main/java/org/apache/flink/hadoopcompatibility/mapred/HadoopInputFormat.java#L53

Also, it would be nice if you could squash your changes into one commit.

**Comment by StephanEwen** [comment]
Looks good to me.

Can we add a simple test that instantiates the input format wrapper with a MapRed input format <Void, Long> (as in the buggy case) and see that it returns the correct type?

**Comment by FelixNeutatz** [comment]
I have three questions: 
1) Shall I also remove the limitations from HadoopMapFunction.java, and HadoopReduceFunction.java, ...
2) With "add a simple test that instantiates the input format wrapper" you mean another Wordcount example with the corresponding "buggy" configuration or can you explain that in more detail?

3) What about a Parquet example?

**Comment by hsaputra** [comment]
To clean up history of the changes, could you munge the commits into one?

**Comment by FelixNeutatz** [comment]
I will try ;)

**Comment by rmetzger** [comment]
1) Should be possible right? Our system supports all types. So I would do it.
2) You probably don't need a full word count for testing the instantiation and type extraction.
3) In the flink-java-examples? I'm not so sure about that because it adds a lot of new dependencies to the project. If you want you can write a blog post about using Parquet with Flink.

**Comment by StephanEwen** [comment]
Concerning (2) - Let's not add another WordCount - simply making sure that the right type info is found should be sufficient.

**Comment by FelixNeutatz** [comment]
I added a simple unit test: HadoopInputFormatTest.java
Did you mean this test?

**Comment by StephanEwen** [comment]
That looks good, thank you!

**Comment by FelixNeutatz** [comment]
Shall also add the same test for the mapred package?

**Comment by StephanEwen** [comment]
Yes, that would be nice. The test looks good.

A bit of style cleanup and some commit squashing and this is good to merge in my opinion.

**Comment by FelixNeutatz** [comment]
I rebased some of the commits as requested

**Comment by fhueske** [comment]
LGTM
Will do some tests, clean-up and merge if everything is fine

**Comment by MohamedNadjibMAMI** [comment]
"If you want you can write a blog post about using Parquet with Flink." This would a great plus for the project. Hope it goes a bit deeper and enters the official documentation.

**Pull request closed without merging**
