### PR TITLE
[FLINK-7609][examples] WindowWordCount example doesn't print countWindow output with default configs

### PR DESCRIPTION
**Pull request by bowenli86**
## What is the purpose of the change

When running WindowWordCount example with no params (using default params), no output is generated and thus printed, because the default 'window' and 'slide' value is too large (250 and 150).

The solution is to lower default 'window' and 'slide' values to probably 4 and 2

## Brief change log

Lower default 'window' and 'slide' values in this example to 4 and 2

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

I tested the example with updated default values, and it now generates and prints output.

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by zentol** [comment]
Aren't these values a bit too low? (I'm specifically worried about cases where users supply their own data)
Would 100/50 maybe work?

**Comment by bowenli86** [comment]
There's no output with 100/50 either, because the default text we use at WordCountData.WORDS is not very long and cannot satisfy the count window size. There's only 11 window ouputs even with 10/5, which are still a bigger size.

I prefer 4/2, but also think 10/5 is also ok, because the program is for demo purpose and new users would doubt the program's accuracy if it doesn't generate enough output. What do you think? @zentol

**Comment by zentol** [comment]
lets go with 10/5 then.

**Comment by bowenli86** [comment]
@zentol Done

**Comment by bowenli86** [comment]
@zentol and this one. Thanks!

**Comment by zentol** [comment]
merging.

**Pull request closed without merging**
