### PR TITLE
Modified the equals method in all the Value type classes

### PR DESCRIPTION
**Pull request by sahitya-pavurala**
Added check for null in all the equals methods in all the Value type classes

### CODE REVIEW

**Comment by uce** [comment]
So, we have been handling `null` values inconsistently from what I can see. `LongValue` checks for `null` whereas the changed classes in this PR did not. The equals contract is to return `false` for `obj.equals(null)` but I think there are [fair arguments for throwing NPE](http://stackoverflow.com/questions/2887761/is-it-a-bad-idea-if-equalsnull-throws-nullpointerexception-instead) as well.

I think it's good to have it consistent in all `Value` classes. I'm in favor of your change, but it is essentially API breaking. There could be someone out there relying on the NPE. ;-)

Need more opinions on this, @tillrohrmann, @fhueske.

**Comment by sahitya-pavurala** [comment]
Well yes, my opinion is to use getClass in place of instanceOf , I didnt make the change yet , so in that case I think we need to have a check for null reference.

**Comment by sahitya-pavurala** [comment]
instanceOf being an operator will return false if its a null reference , but getClass being a method will give an exception(I think so), also use of getClass makes more sense since its a equals method and we want both the types to be identical(no sub types)

**Comment by sahitya-pavurala** [comment]
If there is someone out there relying on the NPE, i think it should be thrown.(throw)

**Comment by StephanEwen** [comment]
I would not expect `equals()` to throw an exception, so this is a good fix in my opinion.

**Comment by sahitya-pavurala** [comment]
either way, it should be one of either getClass or instanceOf , it is inconsistent right now

**Comment by uce** [comment]
Merging. Thanks for the PR. Going for getClass.

**Pull request closed without merging**
