### PR TITLE
[FLINK-2668] Chained Projections are no longer appended

### PR DESCRIPTION
**Pull request by zentol**
Chained project() calls (like project(0).project(1)) are no longer merged into a single projection, but instead applied separately. This means that a project() call will now have a consistent behaviour between DataSet and ProjectOperator.

### CODE REVIEW

**Comment by fhueske** [comment]
Do we agree to break the API for this change? 
And if so, should we add this change before or after the 0.10 release?

**Comment by aljoscha** [comment]
I would break the API since the old behavior can be confusing.

**Comment by fhueske** [comment]
Regarding the PR itself: 
The `ProjectOperator` class can be cleaned up a bit more. By removing the two methods, the member variable `proj` becomes unused and the constructor with the signature `public ProjectOperator(DataSet<IN> input, int[] fields, TupleTypeInfo<OUT> returnType, Projection<IN> proj)` can be removed, if the code generated by the `TupleGenerator` is adapted such that it does not use the `Projection` anymore.

I am also OK with breaking the API, but we should do it now (with the 0.10 release), IMO.

**Comment by zentol** [comment]
@fhueske I've made the changes you suggested

**Comment by fhueske** [comment]
Thanks for the update, looks good. 
I will merge this into `master` and `release-0.10` unless somebody objects.

**Comment by aljoscha** [comment]
Go ahead

**Comment by fhueske** [comment]
Will merge this

**Pull request closed without merging**
