### PR TITLE
[hotfix][tests] Update ci/log4j.properties to use rootLogger for streaming.connectors.kafka

### PR DESCRIPTION
**Pull request by lindong28**
## Contribution Checklist

This PR updated log4j config files. It simplifies the parsing of Azure Pipeline logs by not flooding Azure Pipeline logs with INFO/WARN messages.

## Brief change log

This PR made the following changes:
- Set flink-tests/src/test rootLogger level to OFF
- Updated ci/log4j.properties to use rootLogger for streaming.connectors.kafka

## Verifying this change

To be done in Azure pipeline execution.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by lindong28** [comment]
@rmetzger

**Comment by lindong28** [comment]
For the context, @tillrohrmann asked in this comment about the excessive INFO level logging in AZP.

It appears that INFO level logging from org.apache.flink.streaming.connectors.kafka are printed in AZP due to the following reasons:
- By searching for "log4j.configurationFile", we could see that `tools/ci/log4j.properties` is used to configure the log4j level in AZP.
- `org.apache.flink.streaming.connectors.kafka` is specifically updated to use ConsoleAppender instead of FileAppender inside the file `tools/ci/log4j.properties`

I guess the questions are:
- Is it expected that AZP test uses `tools/ci/log4j.properties` instead of `src/test/log4j2-test.properties` for log4j configuration?
- Why do we specifically set `org.apache.flink.streaming.connectors.kafka` to use `ConsoleAppender` in `tools/ci/log4j.properties`?

@rmetzger, @zentol: do you have any suggestion? Thanks.

[1] https://issues.apache.org/jira/browse/FLINK-18634?focusedCommentId=17316208&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17316208
[2] https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=16080&view=logs&j=c5f0071e-1851-543e-9a45-9ac140befc32&t=1fb1a56f-e8b5-5a82-00a0-a2db7757b4f5

**Comment by zentol** [comment]
> Why do we specifically set org.apache.flink.streaming.connectors.kafka to use ConsoleAppender in tools/ci/log4j.properties?

Kafka logging was enabled in https://github.com/apache/flink/commit/cdec46e112adadefe05a42d39a6be8fd181262ea for debugging purposes, and we never followed-up to remove the logging.

> Is it expected that AZP test uses tools/ci/log4j.properties instead of src/test/log4j2-test.properties for log4j configuration?

yes.

**Comment by lindong28** [comment]
Thanks @zentol. I have updated PR to use rootLogger for streaming.connectors.kafka in ci/log4j.properties.

**Comment by rmetzger** [comment]
There seems to be a concurrent PR fixing the same issue?! https://github.com/apache/flink/pull/15512

**Comment by rmetzger** [comment]
Given that Till's PR was first, I propose to close this one.

**Comment by lindong28** [comment]
@rmetzger Cool. Sounds good.

**Comment by sonaa55** [comment]
$ ./bin/xinfra-monitor-start.sh config/xinfra-monitor.properties

**Pull request closed without merging**
