### PR TITLE
[FLINK-5723][UI]Use Used instead of Initial to make taskmanager tag more readable

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
Now in JobManager web fronted, the used memory of task managers is presented as "Initial" in table header, which actually means "memory used", from codes.

I'd like change it to be more readable, even it is trivial one.

**Before：**
pr1
**After：**
pr2

### CODE REVIEW

**Comment by zentol** [comment]
you have to modify the corresponding jade files; modifications to the html files will be overridden the next time someone builds the web-ui.

**Comment by WangTaoTheTonic** [comment]
@zentol Thanks for review. I've changed .jade file, but it looks like CI is not up properly :(

**Comment by WangTaoTheTonic** [comment]
Travis timeout :) How to kick it up again?

**Comment by greghogan** [comment]
Travis is effectively passing. The tests are duplicated under multiple environments.

This would also be a nice fix for 1.2.1.

**Comment by WangTaoTheTonic** [comment]
Thanks @greghogan. Should I make another PR against branch `release-1.2`?

**Comment by greghogan** [comment]
I don't know the best workflow for multi-release PRs. It can work either way, so hopefully another developer will chime in here. I think we tend to only create a single PR for simple changes and the committer can patch the changes onto the stable branches.

**Comment by WangTaoTheTonic** [comment]
Thanks. That makes sense :)

**Comment by tzulitai** [comment]
AFAIK, for simple changes we don't strictly require a separate PR for backporting to a release branch. Committers usually just cherry-pick the changes on the release branch.

**Comment by WangTaoTheTonic** [comment]
@zentol Is it ok to go?

**Comment by zentol** [comment]
+1 from my side.

**Comment by WangTaoTheTonic** [comment]
@StephanEwen What do you think about this? Could you help merge this if you're ok with it? Thanks :)

**Comment by StephanEwen** [comment]
Looks good, merging this...

**Comment by uce** [comment]
@WangTaoTheTonic We forgot to close this PR while merging. Could you please close this manually?

**Comment by WangTaoTheTonic** [comment]
sure.

Fixed in 
 - 1.2.1 via e3e3c2a7f9c8dd8576e0e27b2efddb7ff42c7c0d 
 - 1.3.0 via 03e6c249156fbbfeef39397a70c70bb905469d09

**Pull request closed without merging**
