### PR TITLE
[FLINK-30855][Connector/Google Cloud PubSub] Remove GCP PubSub connector

### PR DESCRIPTION
**Pull request by MartijnVisser**
## What is the purpose of the change

* Remove GCP connector from Flink since it's now externalized at https://www.github.com/apache/flink-connector-gcp-pubsub

## Brief change log

* Integrate docs with docs from GCP's external repo
* Remove GCP docs from Flink itself
* Remove GCP connector 

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by snuyanzin** [comment]
There is also `flink-examples-streaming-gcp-pubsub` at https://github.com/apache/flink/tree/master/flink-examples/flink-examples-build-helper/flink-examples-streaming-gcp-pubsub
depending on pubsub connector.

I guess it should be also moved to pubsub connector repo and removed from flink repo....
Or did I miss anything?

**Comment by MartijnVisser** [comment]
> I guess it should be also moved to pubsub connector repo and removed from flink repo....
> Or did I miss anything?

I would actually lean into that the examples need to be removed as a whole; I don't see much value in an example that's based on GCP tbh (especially given the state of the connector)

**Comment by MartijnVisser** [comment]
@snuyanzin I've opened https://github.com/apache/flink-connector-gcp-pubsub/pull/3 to move the example :)

**Comment by snuyanzin** [comment]
> @snuyanzin I've opened https://github.com/apache/flink-connector-gcp-pubsub/pull/3 to move the example :)

great!

I've checked once more and now not able to find other pubsub related artifacts .
LGTM

**Review by snuyanzin — APPROVED** [review]

**Review by XComp — APPROVED** [review]
LGTM, too. I checked the touched files and grep'd through the code for `Google`, `gcp` and pubsub` without any relevant occurrences popping up. :+1:

**Pull request merged**
