### PR TITLE
[hotfix][javadocs] Fix some typo in java doc and comments

### PR DESCRIPTION
**Pull request by zoltar9264**
## What is the purpose of the change

As the title, fix some typo in java doc and comments.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by zoltar9264** [comment]
Hi @reswqa , I try fix some type, can you help to review it ?

**Review by lsyldliu — APPROVED** [review]
@zoltar9264 Thanks for your contribution, this fix looks good to me.

**Review by reswqa — COMMENTED** [review]
Sorry for the delay, LGTM and thanks for the fix. 
nit: Rename commit to `[hotfix][javadocs] Fix some typo in java doc and comments`.

**Review by reswqa — APPROVED** [review]

**Comment by zoltar9264** [comment]
Thanks for reviewing @reswqa and @lsyldliu , and reworded @reswqa .

**Review by reswqa — APPROVED** [review]
Thanks for the update.

**Comment by reswqa** [comment]
Feel free to pin me if CI passes.

**Comment by zoltar9264** [comment]
Thanks @reswqa , the CI is passed.

**Pull request merged**
