### PR TITLE
[FLINK-15175]Fix CTES not supported in SQL CLI

### PR DESCRIPTION
**Pull request by liupc**
## What is the purpose of the change

Currently, flink sql cli not suported ctes syntax(akka. WITH...SELECT), This PR will fix it as a temporary solution.

## Brief change log

  - Update SELECT regex expressions to support ctes in Sql cli

## Verifying this change

Real cluster test with TPCDS.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable )

### CODE REVIEW

**Comment by liupc** [comment]
cc @KurtYoung @JingsongLi

**Comment by JingsongLi** [comment]
Thanks @liupc , can you can some tests?

**Comment by JingsongLi** [comment]
> We should be careful with introducing new SQL syntax. Is this official SQL standard? Are other vendors (like Oracle, Hive, Postgres) supporting this as well? It would be nice if you can do some research here.

+1.
Calcite support this syntax.
If not so official, I think we can wait the refactor of SQL-CLI, then using calcite to parse query in SQL-CLI, and this syntax will be supported.

**Comment by liupc** [comment]
@JingsongLi  @twalthr 
This SQL syntax is official and it's in standard tpcds queries, and we've already supported running all tpcds queries in flink.
The current syntax parser is implemented with regex in SQL CLI which is not strict, so I think it's ok for my fix. It will not introduce any new SQL syntax and it's already supported in planner.
As discussed in the jira [FLINK-15175|https://issues.apache.org/jira/browse/FLINK-15175], the final solution will be supporting those syntax in calcite. But for now, we can take this fix to support running tpcds quries through SQL CLI.

**Comment by liupc** [comment]
@KurtYoung  Done

**Pull request closed without merging**
