### PR TITLE
[FLINK-14861][Client / Job Submission] parallelism.default in flink-conf.yaml do not work 

### PR DESCRIPTION
**Pull request by leonardBang**
parallelism.default in flink-conf.yaml do not work which is a bug imported by FLINK-14745

## What is the purpose of the change

* This pull request fix parameters "parallelism.default" in flink-conf.yaml do not work when user submit task by flink run commandline .*

## Brief change log

  - *update file flink-clients/src/main/java/org/apache/flink/client/cli/CliFrontend.java*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): ( no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by leonardBang** [comment]
@flinkbot  run travis

**Comment by leonardBang** [comment]
> Hi @leonardBang , thanks for the work. Could you add a test for this. For inspiration you can have a look at the `CliFrontendRunTest`.

@kl0u Thanks for your tip， I'll add a test ASAP.

**Comment by kl0u** [comment]
@leonardBang The `CliFrontendInfoTest.testShowExecutionPlan()` failed on Travis but I can fix it before merging.

**Comment by leonardBang** [comment]
> @leonardBang The `CliFrontendInfoTest.testShowExecutionPlan()` failed on Travis but I can fix it before merging.

@kl0u Thanks for your assistance.

**Comment by kl0u** [comment]
Merged.

**Pull request closed without merging**
