### PR TITLE
[FLINK-2675] [streaming] Integrate Timer Service with StreamTask

### PR DESCRIPTION
**Pull request by aljoscha**
This integrates the timer as a service in StreamTask that
StreamOperators can use by calling a method on the
StreamingRuntimeContext.

This also ensures that the timer callbacks can not be called
concurrently with other methods on the StreamOperator. This behaviour is
ensured by an ITCase.

### CODE REVIEW

**Comment by aljoscha** [comment]
@StephanEwen, I removed the special handling of exceptions in the ProcessingTimeWindows operator since this is now handled in a generic way by the stream tasks.

**Comment by uce** [comment]
Not the expert on this, but the changes look good. Had some minor comments. The tests look very good. :)

**Comment by aljoscha** [comment]
I addressed your comments. I also ran five travis builds overnight and none of them failed so this should be good to merge.

@StephanEwen Could you please have a look at how I moved the exception handling from your WindowingOperators to the StreamTasks. We should be damn sure this is correct. :smile: 

Other than that, I would merge this later today.

**Comment by StephanEwen** [comment]
I think this is good.

In the long run, I would like to change that all functionality is currently pushed into the StreamRuntimeContext (it gets overloaded and exposes concepts to user functions that we may not want to expose), but that is a separate issue not blocking this pull request.

**Comment by StephanEwen** [comment]
Merging this...

**Pull request closed without merging**
