### PR TITLE
[FLINK-17719][task][checkpointing] Provide ChannelStateReader#hasStates for hints of reading channel states

### PR DESCRIPTION
**Pull request by zhijiangW**
## What is the purpose of the change

Currently we rely on whether unaligned checkpoint is enabled to determine whether to read recovered states during task startup,  then it will block the requirements of recovery from previous unaligned states even though the current mode is aligned. 

We can make `ChannelStateReader` provide the hint whether there are any channel states to be read during startup, then we will never lose any chances to recover from them.

## Brief change log

- Provide `ChannelStateReader#hasStates` interface methods and implements it in related instances.

- Adjust the condition in `StreamTask#beforeInvoke` to reuse the new hint.

## Verifying this change

new unit test in `StreamTaskTest#testBeforeInvokeWithoutChannelStates`.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by zhijiangW** [comment]
@flinkbot run azure

**Comment by zhijiangW** [comment]
@flinkbot run azure

**Comment by zhijiangW** [comment]
@flinkbot run azure

**Comment by pnowojski** [comment]
Private azure build succeeded https://dev.azure.com/pnowojski/Flink/_build/results?buildId=35&view=results % unrelated known issue https://issues.apache.org/jira/browse/FLINK-17724

Merging.

**Comment by zhijiangW** [comment]
Thanks for review and merging @pnowojski

**Pull request merged**
