### PR TITLE
[FLINK-20001] Don't use setAllVerticesInSameSlotSharingGroupByDefault in StreamGraphGenerator

### PR DESCRIPTION
**Pull request by aljoscha**
I think the default of having all vertices in the same slot sharing
group should be good for both BATCH and STREAMING right now. We can
reconsider actually setting this flag in the future.

Background information: this is a special setting that was introduced
for the Table API Blink runner/planner, which does special things with
slot sharing (or lack thereof) and is more aware of memory requirements
and such. For general DataStream/DataSet programs changing the setting
doesn't make sense.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? no

### CODE REVIEW

**Comment by kl0u** [comment]
Definitely tests in the `StreamGraphGeneratorExecutionModeDetectionTest` (and maybe elsewhere) will fail.

**Comment by kl0u** [comment]
There are definitely tests in the `StreamGraphGeneratorExecutionModeDetectionTest` that will fail.

**Review by kl0u — APPROVED** [review]
I can only comment on the PR and not on the correctness of the approach as I do not have a complete view of the implications of this setting. 

With this disclaimer, +1 to merge this PR after AZP gives green.

**Comment by aljoscha** [comment]
Merged!

**Pull request closed without merging**
