### PR TITLE
[FLINK-32180][runtime] Moves error handling from DefaultMultipleComponentLeaderElectionService into the MultipleComponentLeaderElectionDriver implementations

### PR DESCRIPTION
**Pull request by XComp**
* https://github.com/apache/flink/pull/21742
* https://github.com/apache/flink/pull/22379
* https://github.com/apache/flink/pull/22422
* https://github.com/apache/flink/pull/22380
* https://github.com/apache/flink/pull/22623
* https://github.com/apache/flink/pull/22384
* https://github.com/apache/flink/pull/22390
* https://github.com/apache/flink/pull/22404
* https://github.com/apache/flink/pull/22601
* https://github.com/apache/flink/pull/22642
* https://github.com/apache/flink/pull/22640
* === THIS PR === FLINK-32180
  * https://github.com/apache/flink/pull/22829
  * https://github.com/apache/flink/pull/22830
  * https://github.com/apache/flink/pull/22828
* https://github.com/apache/flink/pull/22661

## What is the purpose of the change

The error handling needs to be moved into the driver to allow errors that were reported to the 
k8s watcher to be forwarded to the `LeaderContender`'s error handling. This aligns with how the `LeaderElectionDriver` was used.

This step is necessary so that we can replace the `LeaderElectionDriver` within `DefaultLeaderElectionService` with the `MultipleComponentLeaderElectionDriver`.

## Brief change log

* Makes the `fatalErrorHandler` being a parameter of `MultipleComponentLeaderElectionDriverFactory.create`
* Moves `fatalErrorHandler` from `DefaultMultipleComponentLeaderElectionService` into the `MultipleComponentLeaderElectionDriver` implementations

## Verifying this change

* added a test in `handleFatalError` in `DefaultMultipleComponentLeaderElectionService`

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: yes
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Review by zentol — COMMENTED** [review]
Why wouldn't the service be able to forward errors to the contender? Is it because the driver is doing stuff internally that the service doesn't even know about?
How will the driver get access to a contender-specific failure handler?

I'm wondering if rather there should be a way for the driver to report errors to the service, which forwards it to the contender.

**Comment by XComp** [comment]
> Why wouldn't the service be able to forward errors to the contender? Is it because the driver is doing stuff internally that the service doesn't even know about?

The k8s implementation forwards errors that were caught by the watcher to the contender independently of the calls the service sends to the driver.

> How will the driver get access to a contender-specific failure handler?

The driver got access to the error handler during instnatiation. I followed that approach for the `DefaultMultipleComponentLeaderElectionService`.

> I'm wondering if rather there should be a way for the driver to report errors to the service, which forwards it to the contender.

I could do that. Adding a `onError` method to the `MultipleComponentLeaderElectionService` through the `Listener` interface feels like the more consistent way of passing over the error

**Comment by XComp** [comment]
Rebased to the most-recent version of FLINK-31782 (to fix the conflicts).

**Comment by XComp** [comment]
Aaaand another rebase to include the checkstyle fix

**Comment by zentol** [comment]
> we should do that in a separate (followup-)ticket after the migration is done.

sounds good.

**Comment by XComp** [comment]
@flinkbot run azure

**Comment by XComp** [comment]
@flinkbot run azure

**Pull request merged**
