### PR TITLE
[FLINK-7175] Add first simplest Flink benchmark

### PR DESCRIPTION
**Pull request by pnowojski**
Example output:

```
Benchmark                           (objectReuse)  (parallelism)  (stateBackend)   Mode  Cnt     Score     Error   Units
EventCountBenchmark.benchmarkCount           true              1          memory  thrpt    5  4433.286 ± 777.338  ops/ms
EventCountBenchmark.benchmarkCount           true              1           rocks  thrpt    5   569.078 ±  15.298  ops/ms
```

### CODE REVIEW

**Comment by greghogan** [comment]
JMH's GPLv2 license is not compatible with the ASL (see 2063fa12)? This would need to be a separate repo distinct from the Apache Flink project and licensed under the GPL.

**Comment by greghogan** [comment]
Another idea: a separate repo but never released since this looks to be for observation by developers rather than the community at large (results could be summarized in the documentation).

**Comment by pnowojski** [comment]
Thanks for pointing this out. Indeed we will probably have to move it to separate project in that case.

**Comment by pnowojski** [comment]
Closing this PR. Benchmarks will be in separate repository.

**Pull request closed without merging**
