### PR TITLE
[BP-1.16][FLINK-29830][Connector/Pulsar] Create the topic with schema before consuming messages in PulsarSinkITCase. (#21252)

### PR DESCRIPTION
**Pull request by XComp**
1.16 backport PR for parent PR #21252

### CODE REVIEW

**Comment by XComp** [comment]
@syhily can you have a look?

**Comment by MartijnVisser** [comment]
@XComp Can you please also create this backport to https://github.com/apache/flink-connector-pulsar ? It should be target towards to the v3.0 branch there.

**Comment by XComp** [comment]
@MartijnVisser there is no `v3.0` branch in [apache/flink-connector-pulsar]( https://github.com/apache/flink-connector-pulsar)(,yet?). :thinking:

**Comment by MartijnVisser** [comment]
Meh it's fixed

**Comment by XComp** [comment]
But what's puzzling me now. Shouldn't that change already be in the external repository? Or didn't you base the external repository on `apache/flink:master`? :thinking: 

The original change made it to `apache/flink:master` with PR #21252 20 days ago.

**Comment by MartijnVisser** [comment]
> Or didn't you base the external repository on `apache/flink:master`? 🤔

Correct, because `master` has a breaking change in 1.17 (see https://issues.apache.org/jira/browse/FLINK-28853). So the sync was based on `release-1.16`, that's now being released as 3.0. When that release is completed, we'll merge https://github.com/apache/flink-connector-pulsar/pull/2 which contains the remaining changes between `release-1.16` and `master`. That can only be released when Flink 1.17 is released and will be released as 4.0. 

This is the only way we can get the Pulsar connector code out of `apache/flink:master` during the 1.17 release cycle.

**Comment by XComp** [comment]
thanks for clarification :+1:

**Pull request merged**
