### PR TITLE
check in if clause in LongValue.java

### PR DESCRIPTION
**Pull request by sahitya-pavurala**
Should be logical(&&) and not bit wise(&)

### CODE REVIEW

**Comment by sahitya-pavurala** [comment]
It looks like I deleted my local repository accidentally. Let me know if I have to make this change again.

**Comment by fhueske** [comment]
Thanks für the PR.
As long as you keep the PR branch in your GH repository, things are fine.

**Comment by sahitya-pavurala** [comment]
okay thanks , so after you merge the code , there are few more things to be changed in those classes , will make the changes shortly.

**Comment by uce** [comment]
Since both are booleans, this check is equivalent to `&&` w/o the short-circuit evaluation. So good to merge.

**Comment by sahitya-pavurala** [comment]
I am relatively new to github, i cant close the pr until you merge the code right?

**Comment by hsaputra** [comment]
Hi @sahitya-pavurala , if the PR is merged we will automatically close the PR for you.

**Comment by sahitya-pavurala** [comment]
Okay, thanks.

**Comment by StephanEwen** [comment]
I think that the correct thing is to drop the check for not null, because the `instanceof` keyword checks that the argument is not null already. The current code hence checks twice that the value is not null.

**Comment by sahitya-pavurala** [comment]
I think that the instanceOf should be changed to getClass in the first place. getClass makes more sense since its a equals method and we want both the types to be identical(not allow sub types)

**Comment by uce** [comment]
Will squash with the other PR and merge.

**Pull request closed without merging**
