### PR TITLE
[FLINK-17710][python][hotfix] StreamSqlTests.test_execute_sql test is…

### PR DESCRIPTION
**Pull request by SteNicholas**
## What is the purpose of the change

*`StreamSqlTests#test_execute_sql` test method is not stable because this method verify the `JobStatus` state for the returned `JobClient`, which state is possible to be globally terminal state when the job hasn't yet finished.*

## Brief change log

  - *Modify `StreamSqlTests#test_execute_sql` test method with `JobStatus` not none verification.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by hequn8128** [comment]
It is wired that the test has not been triggered due to some "Bad credentials" problem. 
https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=1354&view=results
@rmetzger Hi, would be great if you can double-check on this.

**Comment by hequn8128** [comment]
Still not sure about the reasons, I have reverted the related commits for safety consideration. The test begins normally now. I will check more later. Sorry about this.

**Comment by rmetzger** [comment]
I don't know what happened there. I manually triggered a build for commit "be9779df4a817697788ed44fc618900595b248d8" here: https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=1372&view=results

**Comment by hequn8128** [comment]
@rmetzger Thank you for your help.

**Pull request merged**
