### PR TITLE
 [FLINK-9061][checkpointing] add entropy to s3 path for better scalability

### PR DESCRIPTION
**Pull request by indrc**
## What is the purpose of the change

*This pull request adds entropy to the checkpoint path based upon a user defined pattern in the configuration for better s3 scalability*

## Brief change log
  - *Read the entropy pattern from the config*
  - *In the checkpoint path for FSbackend, substitute the entropy key with a 4 character random alpha numeric string*

## Verifying this change

This change added tests and can be verified as follows:

  - *Added unit tests under FileStateBackendTest to cover different scenarios for the entropy substitution*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes )
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: ( no )
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes )
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by StephanEwen** [comment]
Thanks for this contribution, that's a valuable fix. I have a few thoughts and suggestions on how we might improve the feature a bit still:

  - Can we get id of the `commons-text` dependency? The fewer dependencies, the fewer possible problems for users due to dependency clashes. It seems a bit heavy to add a new library for just one random string generation.

  - The feature is configured through additional constructor parameters. I am wondering if we may want to move this to the `Configuration`. That would allow the "ops side of things" to configure this for a setup (setting entropy key and checkpoints directory) without needing everyone that writes a Flink program to be aware of this.

  - If I read the code correctly, the code logs warnings for every file in case the feature is not activated. That will probably confuse a lot of users and make them dig into whether they have a wrong setup, when they simply don't use this new feature.

**Comment by indrc** [comment]
@StephanEwen Thanks for your comments and feedback, my replies below
1. after talking to @StefanRRichter we decided to bring in this dependency to use a standard library instead; initially the pr had an impl of random generator function. Are you suggesting to revert to the old?
(And due to a squash, i lost the review comments; sorry about losing the context)
2. the feature gets enabled through a new config key; the specific constructor helps initializing the new feature. My thought was this way, it doesn't get exposed to default codepath. Do you see a problem with this approach?
3. sounds good, i will remove that warning.

**Comment by StefanRRichter** [comment]
@indrc I think there is no contradiction between Stephan's comment and my suggestion about 1. I stand by my point that this is a very common task and there is no very special requirement in the random string that would really require a new method. My initial suggestions `RandomStringUtils` and Flink's `UUID` are both already available without adding another dependency and a full-test search for `randomstring` in the project also gave some hits like e.g. `StringUtil`, that could also be used or extended in a more general way than putting our own algorithm in this particular place.

**Comment by indrc** [comment]
@StefanRRichter @StephanEwen okay, added the suggested changes; let me know.

**Comment by mdaxini** [comment]
@indrc 

In addition to removing the additional dependency, I think there should be a test for validating the randomness of the chose algorithm, and to make sure there are no conflicts. For a Flink Job with large number of Task Managers and state in Terrabytes resulting in several files, there could be a possibility of conflicts with the current random string generation method. 

fyi @StefanRRichter @StephanEwen

**Comment by indrc** [comment]
@mdaxini i don't think we have to validate the public api; with the 4 char alphanumeric there is more than enough entropy to cover all filewrites in a conceivable TM cluster. And to add to that, this is a best effort approach, no harm reached if a collision happens.

**Comment by StephanEwen** [comment]
I rebased and adopted this PR for Flink 1.5/1.6 under #6604

**Comment by StephanEwen** [comment]
I have adjusted this and merge it for `release-1.6` and `master`.
Docs are under https://github.com/apache/flink/blob/master/docs/ops/filesystems.md#entropy-injection-for-s3-file-systems

**Comment by GJL** [comment]
Closing this PR because FLINK-9061 is closed.

**Pull request closed without merging**
