### PR TITLE
[FLINK-26381][docs] Wrong document order of Chinese version

### PR DESCRIPTION
**Pull request by paul8263**
## What is the purpose of the change

Compared English with Chinese version, the orders of articles locates in TOC for docs learn Flink are different.

## Brief change log

- docs/content.zh/docs/learn-flink/datastream_api.md
- docs/content.zh/docs/learn-flink/event_driven.md
- docs/content.zh/docs/learn-flink/fault_tolerance.md
- docs/content.zh/docs/learn-flink/streaming_analytics.md

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Review by MartijnVisser — APPROVED** [review]
@paul8263 Thanks a lot for the PR and the fix. I've rebased your PR and will wait for CI to pass, I'll merge it afterwards.

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Comment by MartijnVisser** [comment]
Thanks for the PR @paul8263 - Do you also want to create backports to release-1.15 and release-1.14?

**Comment by paul8263** [comment]
Hi @MartijnVisser ,
Thanks. I will do it.

**Pull request merged**
