### PR TITLE
[hotfix][tests] Use G1GC for tests

### PR DESCRIPTION
**Pull request by pnowojski**
We are using G1GC for running TaskManager, I think we should do it so also for tests.

### CODE REVIEW

**Comment by greghogan** [comment]
For speed or consistency?

**Comment by pnowojski** [comment]
Mostly for consistency, however using Serial GC on it's own doesn't seem like a better idea compared t G1GC (avoiding long pauses)

**Comment by haohui** [comment]
+1

It's very rare to see people using SerialGC in production environment. Running the tests using SerialGC seems bringing in little values.

**Comment by pnowojski** [comment]
Thanks for merging!

**Pull request closed without merging**
