### PR TITLE
[FLINK-21935] Remove 'state.backend.async' option

### PR DESCRIPTION
**Pull request by StephanEwen**
## What is the purpose of the change

Removes the `state.backend.async` option and makes all state snapshots asnchronous by default.

## Brief change log

  - Removes the flag for async snapshots from the `HashMapStateBackend` and related examples and tests. This code was not released before, so this change is not breaking any backwards compatibility.
  - Ignores the flag for async snapshots in the `MemoryStateBackend` and `FsStateBackend` and always uses async snapshots. This change does not break any API. Methods and constructors are changed to ignore the flag, JavaDocs updated.
  - Deprecates the `ConfigOption` for *state.backend.async*.

## Verifying this change

  - Existing tests are adjusted.
  - 
## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by sjwiesman** [comment]
@Myasuka I've updated the pydoc in `state_backend.py` in #15441

**Comment by StephanEwen** [comment]
@sjwiesman From what I see, you updated the pydoc to mention that the old state backends are deprecated. I think @Myasuka was referring to update the docs that the *async* flag is no longer taking any effect and that snapshots are always asynchronous.

**Comment by Myasuka** [comment]
@sjwiesman Yes, what actually I meant is those pydoc about `is_using_asynchronous_snapshots` is actually out of date after this PR.

**Review by carp84 — COMMENTED** [review]
I suggest we also deprecate (or directly remove) `NestedMapsStateTable` and `NestedStateMap` classes since now there are actually no way to use them through any configuration setting, maybe deprecate first to reduce the changes this time.

**Comment by StephanEwen** [comment]
@carp84 Yes, I would do this when removing the actual internal synchronous checkpointing code. There is even a bit more than those two classes. This first change is mainly to reduce API and config surface.

**Comment by StephanEwen** [comment]
Merging this with an adjustment of the pydocs...

**Pull request closed without merging**
