### PR TITLE
[FLINK-11450][table] Port and move TableSource and TableSink to flink-table-common

### PR DESCRIPTION
**Pull request by dianfu**
## What is the purpose of the change

*This pull request ported the following classes to flink-table-common:
   TableSource, TableSink, TableSinkBase, DefinedFieldMapping, NestedFieldsProjectableTableSource, ProjectableTableSource, TableConnectorUtil*

## Brief change log

  - *Ported source/sink related classes to flink-table-common: TableSource, TableSink, TableSinkBase, DefinedFieldMapping, NestedFieldsProjectableTableSource, ProjectableTableSource, TableConnectorUtil*

The following things should be noted:
  - *The package name of TableConnectorUtil is changed from util to utils as there is already a package utils in flink-table-common. To keep the backward compatibility, I have created a package util also and forward the call to the implementation in utils. Please help to take a look at if this is needed?*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by dawidwys** [comment]
Hi @dianfu ,
I have few comments before starting to review the PR:
- I appreciate your work, but it would be better if you could keep the scope as it was originally planned in the corresponding JIRA? This PR actually covers multiple different JIRAs: [FLINK-10755](https://issues.apache.org/jira/browse/FLINK-10755), [FLINK-11451](https://issues.apache.org/jira/browse/FLINK-11451) and probably few more
- Could you please split PRs into smaller chunks(commits) that make sense on their own. It simplifies reviewing enormously. Right now it is nearly impossible to review 4k changed lines at once. This somewhat relates to the previous point, as the JIRAs try to split the rework into those individual subtasks.

**Comment by twalthr** [comment]
Thanks for the great work @dianfu. You ported a lot of classes. Maybe a bit too many. We talked about `TableDescriptor` but maybe there was some miscommunication. Not all subclasses of table descriptor must be ported at this point. Especially classes such as `Schema` has you have noticed need some rework. But we should finish the DDL discussion until we rework and break the API again.

**Comment by dianfu** [comment]
@twalthr ExternalCatalog depends on TableDescriptor currently and do you mean that the port of ExternalCatalog should be done after FLINK-11240 is committed?

**Comment by twalthr** [comment]
@dianfu The external catalog table can be ported but we could skip the ExternalCatalogBuilder to not pull in `Schema`.

**Comment by dawidwys** [comment]
But I think porting of external catalog should be done as part of https://issues.apache.org/jira/browse/FLINK-10755, it is not necessary to do it as part of this PR/JIRA.

**Comment by dianfu** [comment]
@twalthr @dawidwys Thanks for your clarification and suggestion. Please correct me if I understand not correctly: we will port TableSource/TableSink related classes and ExternalCatalog, TableDescriptor, DescriptorBase, Descriptor, TableStats and ColumnStats to flink-table-common  as these descriptor classes are very simple and will not pull too much dependencies and port other descriptor related classes in FLINK-10755.

**Comment by twalthr** [comment]
Thanks for working on this @dianfu. Here are my thoughts:

- Add ColumnStats to this list.
- SchematicDescriptor requires Schema. I would postpone this for now.
- RegistrableDescriptor is more an API thing and must not be used by extension points in common.

**Comment by dianfu** [comment]
@twalthr Thanks for the suggestion. Make sense to me. Regarding to StreamableDescriptor, I'd like to declare it an interface and doesn't extend TableDescriptor anymore. The reason is that TableDescriptor is an abstract class and StreamableDescriptor has to be declared as an abstract class if it extends TableDescriptor. Given that StreamTableDescriptor extends both ConnectTableDescriptor and StreamableDescriptor, it will be impossible. What's your thought about this change?

**Comment by twalthr** [comment]
@dianfu that makes sense to me. The overall goal should be that the API mentioned in https://ci.apache.org/projects/flink/flink-docs-release-1.7/dev/table/connect.html is still valid.

**Comment by dianfu** [comment]
OK. I'll keep it in mind and create another JIRA for this change. Thanks a lot.

**Pull request closed without merging**
