### PR TITLE
[FLINK-5634] Flink should not always redirect stdout to a file.	

### PR DESCRIPTION
**Pull request by jgrier**
Adding flag to flink-daemon.sh and related scripts so that we can actually log to the console -- which is better for Docker environments.  Also modifying Docker entrypoint to use this.

There is a follow on PR with many more changes to the Docker scripts and tooling based on this one.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Looks good to me, +1

@uce the ScriptMeister should probably give his blessing as well...

**Comment by greghogan** [comment]
In regards to FLINK-4326, should the daemon scripts called by the docker script run in the foreground or background? It seems that this PR may be unnecessary.

**Comment by StephanEwen** [comment]
I think @greghogan may be right - if the docker scripts are okay with running the Flink processes in the foreground, then https://issues.apache.org/jira/browse/FLINK-4326 seems like the more general solution.

**Comment by jgrier** [comment]
Agreed.. If https://issues.apache.org/jira/browse/FLINK-4326 were merged this would also work fine. Whether or not Flink runs in the background or foreground is orthogonal to where the logs go – as long as Flink can be configured to log to stdout we're good.

**Comment by StephanEwen** [comment]
Does anyone want to take a stab at addressing this the https://issues.apache.org/jira/browse/FLINK-4326 way? I think no one is active on that issue right now...

**Comment by greghogan** [comment]
This is now looking like a game of hot potato :) I'm happy to let @iemejia create the PR but he had offered the same to me. If I don't hear otherwise first I'll create a PR for FLINK-4326. While sitting down so I don't step on anyone's toes.

**Comment by iemejia** [comment]
@greghogan Definitely a misunderstanding, I had the impression you just didn't like my solution, so I didn't continue pushing for it (even if we finished with similar ideas).

For ref, Greg's PR, so someone (a committer) reviews it
https://github.com/apache/flink/pull/3351

I will move the docker scripts to use start-foreground once it is merged.

**Comment by patricklucas** [comment]
I vote to close this issue since #3492 has been merged/FLINK-4326 has been resolved.

**Pull request closed without merging**
