### PR TITLE
[FLINK-21930][DOC]fix hive dim doc  replace o to order

### PR DESCRIPTION
**Pull request by hehuiyuan**
## What is the purpose of the change

doc error

image

### CODE REVIEW

**Comment by hehuiyuan** [comment]
@flinkbot re-run

**Comment by hehuiyuan** [comment]
@flinkbot re-run

**Comment by hehuiyuan** [comment]
Hi @lirui-apache ,  
please have a look this.

**Comment by lirui-apache** [comment]
Thanks @hehuiyuan for fixing the doc. It looks good to me, but you need a jira ticket to associate with your PR.

**Comment by hehuiyuan** [comment]
> Thanks @hehuiyuan for fixing the doc. It looks good to me, but you need a jira ticket to associate with your PR.

Hi @lirui-apache ,    okay  i do it.

I have changed some documents before, and then others said that simple doc changes do not need to create jira.

**Comment by hehuiyuan** [comment]
Hi @lirui-apache , done

**Review by lirui-apache — APPROVED** [review]
+1

**Review by wuchong — APPROVED** [review]
LGTM.

**Pull request merged**
