### PR TITLE
[FLINK-17327] Fix Kafka Producer Resource Leaks (backport to Flink 1.10)

### PR DESCRIPTION
**Pull request by aljoscha**
This is a backport of #12589 for Flink 1.10.x. Porting was simple, there were (almost) no incompatibilities in the code. The big question is whether to do a version bump from Kafka 2.2.x to 2.4.1 in a Flink 1.10.x release. I do think that this is a very critical bug to fix, though.

The review and PR form for #12589 should hold for this PR.

### CODE REVIEW

**Comment by aljoscha** [comment]
@flinkbot run travis

**Comment by qinjunjerry** [comment]
Anything blocking here?

**Comment by aljoscha** [comment]
It's only that a version bump on a Flink 1.10.x release seems somewhat bigger. I'll ask @StephanEwen and @knaufk what they think.

**Comment by aljoscha** [comment]
@qinjunjerry Was this an issue in the end or could we close this now? I'm hesitant because of the big version bump.

**Pull request closed without merging**
