### PR TITLE
[FLINK-5486] Fix lacking of synchronization in BucketingSink#handleRe…

### PR DESCRIPTION
**Pull request by zhangminglei**

### CODE REVIEW

**Comment by tedyu** [comment]
lgtm

**Comment by zhangminglei** [comment]
```
Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 91.985 sec <<< FAILURE! - in org.apache.flink.test.checkpointing.ExternalizedCheckpointITCase
testExternalizedFullRocksDBCheckpointsStandalone(org.apache.flink.test.checkpointing.ExternalizedCheckpointITCase)  Time elapsed: 29.976 sec  <<< ERROR!
java.io.IOException: java.lang.Exception: Failed to complete checkpoint
	at org.apache.flink.runtime.testingUtils.TestingCluster.requestCheckpoint(TestingCluster.scala:399)
	at org.apache.flink.test.checkpointing.ExternalizedCheckpointITCase.testExternalizedCheckpoints(ExternalizedCheckpointITCase.java:218)
	at org.apache.flink.test.checkpointing.ExternalizedCheckpointITCase.testExternalizedFullRocksDBCheckpointsStandalone(ExternalizedCheckpointITCase.java:78)
Caused by: java.lang.Exception: Failed to complete checkpoint
	at org.apache.flink.runtime.testingUtils.TestingJobManagerLike$$anonfun$handleTestingMessage$1$$anon$2.apply(TestingJobManagerLike.scala:375)
	at org.apache.flink.runtime.testingUtils.TestingJobManagerLike$$anonfun$handleTestingMessage$1$$anon$2.apply(TestingJobManagerLike.scala:358)
	at org.apache.flink.runtime.concurrent.impl.FlinkFuture$5.onComplete(FlinkFuture.java:272)
	at akka.dispatch.OnComplete.internal(Future.scala:247)
	at akka.dispatch.OnComplete.internal(Future.scala:245)
	at akka.dispatch.japi$CallbackBridge.apply(Future.scala:175)
	at akka.dispatch.japi$CallbackBridge.apply(Future.scala:172)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
```

**Comment by tedyu** [comment]
Run QA again ?

**Comment by zhangminglei** [comment]
Okay. Ted. I will trigger the QA soon.

**Comment by zhangminglei** [comment]
triggering now....

**Comment by tedyu** [comment]
retest this please

**Comment by zhangminglei** [comment]
OKay. Thanks , Ted. Will retest again soon enough./

**Comment by zhangminglei** [comment]
@tedyu I am retesting now......let us wait what will happen.

**Comment by GJL** [comment]
Thanks for your contribution. I have a few questions because the submitted code does not match with what the ticket currently says:

From https://issues.apache.org/jira/browse/FLINK-5486:
>The handlePendingFilesForPreviousCheckpoints() call should be enclosed inside the synchronization block. Otherwise during the processing of handlePendingFilesForPreviousCheckpoints(), some entries of the map may be cleared.

I am confused because the submitted code encloses `bucketState.pendingFilesPerCheckpoint.clear();` in a synchronized block.

@tedyu Did you run into actual production issues, or did you find the problem while reviewing the code? Can you elaborate why the additional synchronized block is needed?

**Comment by GJL** [comment]
I am closing this PR because [FLINK-5486](https://issues.apache.org/jira/browse/FLINK-5486?focusedCommentId=16649304&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16649304) got closed. Please reopen the ticket/PR if you disagree.

**Pull request closed without merging**
