### PR TITLE
[FLINK-15081][docs-zh] Translate "Concepts & Common API" page of Table API into Chinese

### PR DESCRIPTION
**Pull request by CrazyTomatoOo**
## What is the purpose of the change

To complete finish the translation work of this page.

## Brief change log

This page is about Flink's Table API & SQL. Mainly showing the usage of Table API & SQL, how Flink optimize SQL queries and the difference between Blink and Flink planner. Now it has been translate into Chinese.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency):  no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers:  no 
  - The runtime per-record code paths (performance sensitive): no 
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper:  no 
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature?  no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by klion26** [comment]
@CrazyTomatoOo thanks for your contribution, could you please update the pr title to respect the issue title? so that others can know what this pr do from the title.

**Comment by CrazyTomatoOo** [comment]
OK

**Comment by wuchong** [comment]
Hi @CrazyTomatoOo , thanks for the contribution. Usually, a PR title is the same to JIRA title with additional issue ID and component name. You can refer to the guideline before contribution: https://flink.apache.org/zh/contributing/contribute-documentation.html.

Btw, I noticed that the code part is inconsistent before and after translation, please check that.

**Comment by CrazyTomatoOo** [comment]
OK, thanks for reminding me! I will check it now.

**Comment by CrazyTomatoOo** [comment]
Do I need to resubmit PR after modification？

**Comment by wuchong** [comment]
> Do I need to resubmit PR after modification？

No, you don't need. Please just push your changes to your branch.

**Comment by CrazyTomatoOo** [comment]
> > Do I need to resubmit PR after modification？
> 
> No, you don't need. Please just push your changes to your branch.

Sorry, I think I made a mistake. The document I translated is version 1.9.

**Pull request closed without merging**
