### PR TITLE
[FLINK-9854][sql-client] Allow passing multi-line input to SQL Client…

### PR DESCRIPTION
**Pull request by docete**
… CLI

## What is the purpose of the change
this pr allows SQL Client to execute multiple statements in command line or sql script file.

## Brief change log

- Allow parse multiple statements and execute them one by one.

## Verifying this change

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? ( no)

### CODE REVIEW

**Comment by yanghua** [comment]
Hi @docete Thanks for your contribution! However, I have opened a PR #7960 for FLINK-9854. I suggest you should ask the status before you start an issue if it was assigned.

**Comment by docete** [comment]
> Hi @docete Thanks for your contribution! However, I have opened a PR #7960 for FLINK-9854. I suggest you should ask the status before you start an issue if it was assigned.

sorry for my negligence, could u have a look at this PR and consider whether it makes sense？
Let's take it forward together, and i would close this PR if you're concerned.

**Comment by yanghua** [comment]
@docete OK, I will have another look soon. If I think it makes sense, I will ping Timo to listen to his opinion.

**Comment by docete** [comment]
This PR associates wrong JIRA issue by mistake.

**Pull request closed without merging**
