### PR TITLE
[streaming-scala] Code cleanup: unused imports, fix javadocs

### PR DESCRIPTION
**Pull request by smarthi**

### CODE REVIEW

**Comment by rmetzger** [comment]
According to travis, this PR is breaking the build
```
[ERROR] /home/travis/build/apache/flink/flink-staging/flink-table/src/main/scala/org/apache/flink/api/scala/table/ScalaStreamingTranslator.scala:40: error: overriding type Representation in class PlanTranslator with bounds[A] <: AnyRef{def getType(): org.apache.flink.api.common.typeinfo.TypeInformation[A]};
[ERROR]  type Representation has incompatible type
[ERROR]   override type Representation[A] = DataStream[A]
[ERROR]                 ^
```

**Comment by smarthi** [comment]
@rmetzger This is from the Table API which this PR does not touch, I can either withdraw the PR or we could trigger another travis build for this PR and see if the error recurs, at which point its best to withdraw this PR. sounds OK ?

**Comment by rmetzger** [comment]
The tests of `master` on travis are green. Maybe your changes are side-effecting something with the table API? You could also try to rebase your changes to the current master and push it again.

**Comment by smarthi** [comment]
@rmetzger good to merge now, travis builds are successful.

**Comment by tillrohrmann** [comment]
LGTM. Thanks for your contribution @smarthi.

Will be merging.

**Pull request closed without merging**
