### PR TITLE
[FLINK-6994] [docs] Wrong base url in master docs

### PR DESCRIPTION
**Pull request by twalthr**
See Jira issue.

### CODE REVIEW

**Comment by greghogan** [comment]
Why do we have both `flink-docs-master` and `flink-docs-release-1.4`? The main page only links to 1.3 and 1.4 but the flink-docs-master documentation links to 1.3, 1.2, 1.1, and 1.0. But each of those packages only links to older releases so if a user arrives on a 1.2 page they won't see 1.3.

**Comment by twalthr** [comment]
I agree. This is confusing. I think it is ok to have both `flink-docs-master` and `flink-docs-release-1.4`. `flink-docs-master` should always link to the newest doc version. I created FLINK-6995. I will add some more content to it.

**Comment by twalthr** [comment]
I will merge this now. I added your comments to FLINK-6995.

**Comment by rmetzger** [comment]
+1

**Pull request closed without merging**
