### PR TITLE
[FLINK-32141][checkpointing] turn down a log level in the SharedState…

### PR DESCRIPTION
**Pull request by zoltar9264**
…Registry

## What is the purpose of the change

Turn down a log level in the SharedStateRegistry, described in  [FLINK-32141](https://issues.apache.org/jira/browse/FLINK-24611).

### CODE REVIEW

**Review by reswqa — APPROVED** [review]
I am not aware of any other issues, but I am not very familiar with the details here. Perhaps @fredia can help confirm.

**Review by fredia — APPROVED** [review]

**Comment by fredia** [comment]
@zoltar9264 Thanks for the PR, +1 for "FsStateChangelogStorage will directly use the FileStateHandle of the previous checkpoint instead of PlaceholderStreamStateHandle."  When changelog is enabled, `SharedStateRegistry` would print too much info log.

**Comment by zoltar9264** [comment]
Thanks @reswqa for helping merge to master.

> Can you open a PR and backport it to release-1.17.

Sure, but I just checked the 1.17 code and found no conflicts (this commit can be merge into 1.17 directly), am I missing something?

**Comment by reswqa** [comment]
> but I just checked the 1.17 code and found no conflicts (this commit can be merge into 1.17 directly), am I missing something? 

I just found the fix version on the ticket is `1.17.2`, so I would like you to confirm if this need to pick it to 1.17. 

Thank you for your confirmation, I will manually merge it :)

**Pull request merged**
