### PR TITLE
[FLINK-6117]Make setting of 'zookeeper.sasl.disable' work correctly

### PR DESCRIPTION
**Pull request by zhengcanbin**
The value of 'zookeeper.sasl.disable' not used in the right way when starting CuratorFramework.  When 'zookeeper.sasl.disable' is set to true, both of FlinkYarnSessionCli & FlinkApplicationMasterRunner logs show that they attempt connecting to zookeeper in SASL mode.

On my side, this patch works and All tests passed with 'mvn clean verify', can someone review this?

### CODE REVIEW

**Comment by zhengcanbin** [comment]
Hi, this patch works and passes all tests on my side, but now all checks have failed, I check all the five raw logs, obviously those errors are not from my side.
image

image

image

I found it's so hard to pass the CI build, is there something wrong with the servers?
Who can help look over?

**Comment by StephanEwen** [comment]
Yes, CI seems to be unstable.

Can you try to push again to the branch (maybe change the commit message, force push then) to retrigger the CI?

**Comment by StephanEwen** [comment]
@EronWright @vijikarthi If you find the time, what do you think about this patch?

**Comment by EronWright** [comment]
To recap, when the ZK server is configured to use SASL, the client is challenged accordingly.  The client checks for a login entry in the JAAS config to obtain a kerberos credential, and issues a warning if one isn't found.  SASL may be explicitly disabled on the client using the system property `zookeeper.sasl.clientconfig`.   

Flink provides a configuration setting with which to disable SASL on the client, which causes the system property to be set.     _I cannot think of why the default value would be 'true'._   The behavior of 1.2.0 is that the default is 'false' (because it effectively wasn't implemented).   Maybe the default should remain 'false'?

**Comment by zhengcanbin** [comment]
@EronWright  @StephanEwen
In ZookeeperSaslClient.java, 'zookeeper.sasl.client' is true by default, so I agree to set 'zookeeper.sasl.disable' to false by default, for consistency.

**Comment by shijinkui** [comment]
@Rucongzhang Please review it whether it meet your requirement.

**Comment by zhengcanbin** [comment]
@EronWright @vijikarthi

**Comment by Rucongzhang** [comment]
@zhengcanbin ,@StephanEwen ,@shijinkui. After push this issue, we must  illustrate in flink configuration. If we want to use kerberos authentication  with ZK server, we must set zookeeper.sasl.disable:false and set the security.kerberos.login.contexts:zookeeper. But before, we only set security.kerberos.login.contexts:zookeeper. Thanks!

**Comment by gaqzcb** [comment]
@EronWright @vijikarthi If you find the time, pls review this patch.

**Comment by StephanEwen** [comment]
I am a bit confused here, this seems to make things more complicated.

Before, if you wanted to use ZK and Kerberos, you only added `zookeeper` to `security.kerberos.login.contexts`. Now you need additionally to set `zookeeper.sasl.disable` to `false`?

Why don't we keep `zookeeper.sasl.disable` as `false` by default? If I understand it correctly, it is anyways only ever relevant when the ZooKeeper login context has been enabled...

**Comment by vijikarthi** [comment]
The default ZK SASL client behavior is to enable SASL client and to be in consistent it makes sense for us to leave the default option enabled.

**Comment by EronWright** [comment]
The thread is becoming confused as to what the default behavior should be.     In brief I think the code should say:
```
public static final ConfigOption<Boolean> ZOOKEEPER_SASL_DISABLE =
		key("zookeeper.sasl.disable")
		.defaultValue(false);
```

The above would leave SASL _enabled_ by default, as is consistent with Flink 1.2.0.

**Comment by Rucongzhang** [comment]
@StephanEwen , yes, now if you want to use kerberos , you need additionally to set zookeeper.sasl.disable to false. And I agree with you, the default value of  zookeeper.sasl.disable can set to false. Then, If you want to use the kerberos, can only set  ZooKeeper login context . Thanks!

**Comment by zhengcanbin** [comment]
@StephanEwen @vijikarthi @EronWright @Rucongzhang 
Thanks all! I have changed this default behaviour, now `zookeeper.sasl.disable` is `false` by default.

**Comment by vijikarthi** [comment]
The changes looks good to me.

**Comment by zhengcanbin** [comment]
@StephanEwen @EronWright

**Comment by StephanEwen** [comment]
Thanks @zhengcanbin and @vijikarthi 

Merging this...

**Pull request closed without merging**
