### PR TITLE
[hotfix][docs] Update local setup tutorials to fit new log messages

### PR DESCRIPTION
**Pull request by TisonKun**
## What is the purpose of the change

With scheduler/slot refactoring we change log messages and the changes should be reflected to document.

## Brief change log

Update local setup tutorials to fit new log messages

## Verifying this change

It is about documentation.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

cc @rmetzger also a nit to backport to 1.9 docs.

### CODE REVIEW

**Comment by TisonKun** [comment]
@fhueske it would be nice if you have time to take a look. Tiny document changes I think.

**Comment by TisonKun** [comment]
@rmetzger could you help merge this hotfix?

**Comment by StephanEwen** [comment]
Looks good, merging this.

**Comment by TisonKun** [comment]
Thanks for your review!

**Pull request closed without merging**
