### PR TITLE
[FLINK-32419][runtime] Removal of obsolete/unused classes/interfaces/fields

### PR DESCRIPTION
**Pull request by XComp**
## PR Hierarchy

* https://github.com/apache/flink/pull/21742
* https://github.com/apache/flink/pull/22379
* https://github.com/apache/flink/pull/22422
* https://github.com/apache/flink/pull/22380
* https://github.com/apache/flink/pull/22623
* https://github.com/apache/flink/pull/22384
* https://github.com/apache/flink/pull/22390
* https://github.com/apache/flink/pull/22404
* https://github.com/apache/flink/pull/22601
* https://github.com/apache/flink/pull/22642
* https://github.com/apache/flink/pull/22640
* https://github.com/apache/flink/pull/22656
* https://github.com/apache/flink/pull/22828
* https://github.com/apache/flink/pull/22830
* https://github.com/apache/flink/pull/22829
* https://github.com/apache/flink/pull/22661
* https://github.com/apache/flink/pull/22844
* https://github.com/apache/flink/pull/22848
* === THIS PR === FLINK-32419
* https://github.com/apache/flink/pull/22935

## What is the purpose of the change

This is a cleanup PR that removes unused classes/interfaces/fields and renames the MultipleComponent*-related classes into a shorter version.

## Brief change log

* Removes obsolete/unused MultipleComponentLeaderElection-related classes and interfaces
* Deletes old k8s-related classes
* Deletes old zk-related classes/methods/interfaces
* Deletes LeaderElectionDriver- and LeaderElectionEventHandler-related classes/methods/interfaces
* Renames MultipleComponentLeaderElectionDriver (and its subclasses) into LeaderElectionDriver
* Renames MultipleComponentLeaderElectionDriverFactory (and its subclasses) into LeaderElectionDriverFactory

## Verifying this change

* CI succeeds

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: yes
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by XComp** [comment]
force-push after I rebased to the most-recent version of FLINK-32409 that fixed CI

**Comment by XComp** [comment]
@flinkbot run azure

**Comment by XComp** [comment]
Force-pushed rebase onto most-recent version of FLINK-32409

**Review by zentol — APPROVED** [review]

**Comment by XComp** [comment]
args, I screwed up and force pushed the wrong version. I fixed that a force-pushed the squashed version once more. I'm gonna go ahead and rebased to the most-recent version of FLINK-32409

**Comment by XComp** [comment]
Force-pushed a rebase to `master` after FLINK-32409 was merged. This resolves the listed conflicts (where I actually don't understand why Github listed them :thinking: )

**Comment by XComp** [comment]
The CI failure in `flink-python` was probably caused by a [concurrent CI run](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=51019&view=logs&j=0c940707-2659-5648-cbe6-a1ad63045f0a&t=075c2716-8010-5565-fe08-3c4bb45824a4) on `Alibaba001` (see the [related PR](https://github.com/apache/flink/pull/22880)).

**Review by zentol — APPROVED** [review]
+1, although separate delete/rename commits would make for a nicer history; right now it looks like we are re-writing the election drivers.

**Comment by XComp** [comment]
Thanks for pointing that out - I will reorganize the commits once more since we're not in a rush. :+1:

**Comment by XComp** [comment]
I reorganized the commits as suggested by @zentol. I found a few renames that we missed initially which I added to the last commit:
- Renames componentId into contenderID to align the usage
- Renames DefaultLeaderElectionServiceTest test method names to use close instead of stop
- Renames KubernetesMultipleComponentLeaderRetrievalDriverFactory into KubernetesLeaderRetrievalDriverFactory
- Renames ZooKeeperMultipleComponentLeaderElectionHaServices into ZooKeeperLeaderElectionHaServices
- Renames KubernetesMultipleComponentLeaderElectionHaServices into KubernetesLeaderElectionHaServices

**Comment by XComp** [comment]
of course checkstyle issue :roll_eyes: fixed

**Review by zentol — APPROVED** [review]

**Pull request merged**
