### PR TITLE
[FLINK-22385][runtime] Fix type mismatch in NetworkBufferPool

### PR DESCRIPTION
**Pull request by sharkdtu**
## What is the purpose of the change

This pull request fix type mismatch in NetworkBufferPool which will result in ui error as follows:

image

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Review by XComp — APPROVED** [review]
Thanks for addressing this issue @sharkdtu . The changes look good. I was wondering whether we could have added test cases for this but I guess it's tricky as we would run into OOMs while testing since the `NetworkBufferPool`'s constructor does already allocate the memory.

**Comment by sharkdtu** [comment]
@flinkbot run azure

**Comment by XComp** [comment]
@sharkdtu one thing I realized. Can you update the commit message to comply to the proper format? Something like `[FLINK-22385][runtime] Fix type mismatch in NetworkBufferPool`

**Comment by XComp** [comment]
The failures seem to be unrelated:
* `OrcFileSystemITCase` ([build failure](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=16923&view=logs&j=d44f43ce-542c-597d-bf94-b0718c71e5e8&t=03dca39c-73e8-5aaf-601d-328ae5c35f20)) is covered by [FLINK-22397](https://issues.apache.org/jira/browse/FLINK-22397)
* `CassandraConnectorITCase` ([build failure](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=16947&view=logs&j=d44f43ce-542c-597d-bf94-b0718c71e5e8&t=03dca39c-73e8-5aaf-601d-328ae5c35f20&l=13953)) is covered by [FLINK-20723](https://issues.apache.org/jira/browse/FLINK-20723)
* For `KinesisTableApiITCase` ([build failure](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=16947&view=logs&j=c88eea3b-64a0-564d-0031-9fdcd7b8abee&t=ff888d9b-cd34-53cc-d90f-3e446d355529)) I created a new issue [FLINK-22399](https://issues.apache.org/jira/browse/FLINK-22399)

**Comment by sharkdtu** [comment]
@XComp Thanks, the commit message has been updated.

**Review by tillrohrmann — APPROVED** [review]
Thanks for the contribution @sharkdtu  and the review @XComp. LGTM. Merging this PR now.

**Pull request closed without merging**
