### PR TITLE
[FLINK-36327][table] Remove dependency about flink-scala and flink-streaming-scala in table module

### PR DESCRIPTION
**Pull request by xuyangzhong**
## What is the purpose of the change

*Remove dependency about flink-scala and flink-streaming-scala in table module.*

## Brief change log

  - *Copy utils and tests from flink-scala to flink-table-api-scala*
  - *Remove dependency about flink-scala and flink-streaming-scala in table module*
  - *Update tests*

## Verifying this change

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented?

### CODE REVIEW

**Review by lincoln-lil — COMMENTED** [review]
@xuyangzhong Thank you for making large number of changes! 
Only one comment for the 1st commit.

**Comment by lincoln-lil** [comment]
I searched scala `DataStream` usage after your removal, there left only 3 files
image
Is there any ongong pr covering those files? If not, we can create a Jira.

**Comment by lincoln-lil** [comment]
Checked there're no `org.apache.flink.streaming.api.scala` occurs in flink-table directory now.

**Comment by lincoln-lil** [comment]
The 2nd commit looks good! We should fix the left failure cases @xuyangzhong

**Comment by xuyangzhong** [comment]
> I searched scala `DataStream` usage after your removal, there left only 3 files image Is there any ongong pr covering those files? If not, we can create a Jira.

Good catch, I can create a new Jira to trace it because this part is not affected by the deadline of 2.0-preview.

**Review by lincoln-lil — APPROVED** [review]
@xuyangzhong thank you for contributing such large number of changes!
Could you squash the commits before merging?

**Pull request merged**
