### PR TITLE
[FLINK-FLINK][docs] Update the version in docs/_config.yml to be the latest released minor version

### PR DESCRIPTION
**Pull request by zhuzhurk**
Update version to 1.11.2 for release-1.11.

### CODE REVIEW

**Comment by zhuzhurk** [comment]
@JingsongLi @zentol @wuchong would you take a look at this fix?

**Review by JingsongLi — APPROVED** [review]
Looks good to me.

**Review by wuchong — APPROVED** [review]
LGTM.

**Comment by zhuzhurk** [comment]
Thanks for reviewing! @JingsongLi @wuchong 
The E2E test timeout is not caused by this change.
Merging.

**Pull request merged**
