### PR TITLE
[FLINK-2814] Fix for DualInputPlanNode cannot be cast to SingleInputPlanNode

### PR DESCRIPTION
**Pull request by rekhajoshm**
[FLINK-2814] Fix for DeltaIteration: DualInputPlanNode cannot be cast to SingleInputPlanNode

### CODE REVIEW

**Comment by StephanEwen** [comment]
Thanks for this fix! I think it may be sufficient, but to be sure, this would need a test.
Maybe @greghogan can contribute his example that caused the error as a test?

**Comment by greghogan** [comment]
@StephanEwen it is line 454: `solutionSetCandidate = siSolutionDeltaCandidate.getInput().getSource();` where I am seeing `solutionSetCandidate` changed from a `SingleInputPlanNode` to `DualInputPlanNode`. Why are we not exiting the loops after creating and adding the `WorksetIterationPlanNode`?

**Comment by greghogan** [comment]
@StephanEwen should I create an alternate PR?

**Comment by StephanEwen** [comment]
@greghogan I think you are right with your suggestion. Would be great if you can create an alternate fix.

**Comment by greghogan** [comment]
I created #3563 which combines this PR and my suggestion.

**Comment by greghogan** [comment]
@rehevkor5 thanks for this identifying bug and submitting this PR. My apologies for taking so long to look into this issue. With #3563 accepted I think you can go ahead and close this PR.

**Pull request closed without merging**
