### PR TITLE
[FLINK-26166][runtime-web] Add auto newline detection to prettier formatter

### PR DESCRIPTION
**Pull request by gaborgsomogyi**
## What is the purpose of the change

Normally I'm developing on linux based system but sometimes reviewing on Windows based machines. Compile blows up in the following way:
```
[INFO] d:\projects\flink\flink-runtime-web\web-dashboard\src\@types\d3-flame-graph\index.d.ts
[INFO]    1:3   error  Delete `â??`  prettier/prettier
...
```

The following git config hacks it around:
```
core.eol=lf
core.autocrlf=input
```

but it would be good to make it work out of the box so changed prettier formatter config to auto detect the newline.

Here is how auto behaves:
`"auto" - Maintain existing line endings (mixed values within one file are normalised by looking at what’s used after the first line)`

## Brief change log

Changed prettier formatter config to auto detect the newline.

## Verifying this change

Flink compile on linux + windows.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by gaborgsomogyi** [comment]
cc @gyfora @mbalassi

**Comment by gaborgsomogyi** [comment]
@flinkbot run azure

**Comment by mbalassi** [comment]
Hi @gaborgsomogyi!

The output on Linux via the Azura CI looks good, I will run a build on Mac, however I do not have Windows handy, so I might give you a call to show me how it looks there.

**Comment by gaborgsomogyi** [comment]
@mbalassi started a build on my win box and gathering the logs. When it's done hopefully I can attach it here.

**Comment by gaborgsomogyi** [comment]
I've made much more extensive tests to make it bulletproof. It has turned out that the first approach worked only under some circumstances. Namely if `flink-runtime-web` is compiled anytime after the checkout alone then the full build worked, BUT and here comes the nasty trick :)

I've made a full clean checkout and there it was failing for whatever reason consistently. I've changed the approach and with the new code it works with clean checkout too. I've attached the maven output from my win box:
[build.log](https://github.com/apache/flink/files/8088613/build.log)

**Comment by gaborgsomogyi** [comment]
@flinkbot run azure

**Comment by mbalassi** [comment]
Will merge this once the master branch has been been updated to `1.16-SNAPSHOT`, hopefully we get a passing CI run by then too.

**Comment by gaborgsomogyi** [comment]
Oh gosh, tests are super flaky.

**Comment by gaborgsomogyi** [comment]
@flinkbot run azure

**Comment by gaborgsomogyi** [comment]
@flinkbot run azure

**Comment by mbalassi** [comment]
Merging, I acknowledge that there were unrelated test failures. This change is small and self-contained.

**Pull request merged**
