### PR TITLE
[FLINK-1372] [runtime] Fixes Akka logging

### PR DESCRIPTION
**Pull request by tillrohrmann**
Adds EnvironmentInformation.logEnvironmentInfo method calls to JobManager's and TaskManager's main methods.

### CODE REVIEW

**Comment by uce** [comment]
+1

**Comment by rmetzger** [comment]
Good to merge

**Comment by uce** [comment]
I think small changes like this can be committed directly.

**Comment by hsaputra** [comment]
+1 agree

**Comment by tillrohrmann** [comment]
Ok, I'll merge it.

**Pull request closed without merging**
