### PR TITLE
[FLINK-16909][doc] fix doc : The default value for params for HBase Connector

### PR DESCRIPTION
**Pull request by gk0916**
## What is the purpose of the change

*This pull request fixes the Hbase Connector doc:
The default value for "connector.write.buffer-flush.max-rows" and "connector.write.buffer-flush.interval" for HBase Connector is "-1"

## Brief change log
- * ”connector.write.buffer-flush.max-rows“ default value is "-1"
- * “connector.write.buffer-flush.interval” default value is "-1ms"
## Verifying this change
* This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by gk0916** [comment]
> Hi, @gk0916 thanks for your contribution. but `-1` is not the default value, just an invalid value to play a flag role.
> see：
> https://github.com/apache/flink/blob/4412c6ef4fbb208cba6e44e7a90fdfe1e07bf727/flink-connectors/flink-hbase/src/main/java/org/apache/flink/addons/hbase/HBaseUpsertSinkFunction.java#L133
> 
> https://github.com/apache/flink/blob/4412c6ef4fbb208cba6e44e7a90fdfe1e07bf727/flink-connectors/flink-hbase/src/main/java/org/apache/flink/addons/hbase/HBaseUpsertSinkFunction.java#L194

**Comment by gk0916** [comment]
Yes! you are right.Should i close this?

**Comment by leonardBang** [comment]
> Yes! you are right.Should i close this?

Yes, you could close the JIRA issue too.

**Comment by leonardBang** [comment]
I close the JIRA issue

**Pull request closed without merging**
