### PR TITLE
[FLINK-17800][roksdb] Ensure total order seek to avoid user misuse

### PR DESCRIPTION
**Pull request by Myasuka**
## What is the purpose of the change

Flink open RocksDB column family options configuration for users. However, user might misuse `OptimizeForPointLookup` which lead to RocksDB timer and map state did not give correct result.

The perfect solution is to bump RocksDB version larger than 6.2.2 (see https://github.com/facebook/rocksdb/issues/6893 ), however, this might be better done in release-1.12 cycle and we use explicitly `new ReadOptions().setTotalOrderSeek(true)` to pass to RocksDB iterators to ensure the seek order.

## Brief change log

  - Add method `RocksDBOperationUtils#createTotalOrderSeekReadOptions` to create read options and pass this to places where need a RocksDB iterator.

## Verifying this change

This change added tests and can be verified as follows:

  - Added parameter running for `RocksDBStateBackendTest` to verify tests could still get the correct result even user misuse `OptimizeForPointLookup`.
  - Added parameter running for `RocksDBRocksStateKeysIteratorTest` to ensure iterator actions could still get the correct result even user misuse `OptimizeForPointLookup`.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): **should no**
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by carp84** [comment]
Let's also test the performance and make sure the newly added `ReadOptions.setTotalOrderSeek(true)` logic won't cause any regression for none `optimizeForPointLookup` cases.

**Comment by carp84** [comment]
Thanks @Myasuka for the updates, the latest changes LGTM. I've triggered a micro-benchmark run on our Jenkins, will give my +1 if there's no performance regression.

**Comment by carp84** [comment]
PS. The latest pre-commit check failed on e2e part at `Kubernetes test` due to some connection problem, thus is irrelative to the changes here. It would be nice if we could get a green one with the latest changes, though.

**Comment by Myasuka** [comment]
@flinkbot run azure

**Comment by carp84** [comment]
From the [benchmark result](https://s.apache.org/jvs7u), everything looks good except for `listAddAll`. @Myasuka Could you run the `listAddAll` benchmark locally and see whether the regression is stable?

image

**Comment by Myasuka** [comment]
I run `listAddAll` benchmark locally and the result turns to be no difference for twice run:

|  Operation  | original  | setTotalOrderSeek true |
|  ----  | ----  | ----  | 
| org.apache.flink.state.benchmark.ListStateBenchmark.listAddAll | 278.836437 ops/ms |279.395449 ops/ms |

**Comment by StephanEwen** [comment]
Forwarding my comments from the #12529 PR (the 1.11.0 port of this PR)

I would suggest that we avoid "parameterized" tests for this. I think this is not a configuration option that we need to cross test all with all unit tests. This adds a huge amount of test runtime.

Instead I would add tests that are very targeted, for the behavior that is affected by this (range iterators, like in MapState and in Timers).

**Comment by carp84** [comment]
> Forwarding my comments from the #12529 PR (the 1.11.0 port of this PR)
> 
> I would suggest that we avoid "parameterized" tests for this. I think this is not a configuration option that we need to cross test all with all unit tests. This adds a huge amount of test runtime.
> 
> Instead I would add tests that are very targeted, for the behavior that is affected by this (range iterators, like in MapState and in Timers).

@StephanEwen It seems the latest changes here have followed the suggestions and extracted the test cases into a new `RocksDBStateMisuseOptionTest` class. Would you mind to take another look? Thanks.

**Comment by StephanEwen** [comment]
All in all, looks good to me.

One thing that surprised me a bit was adding the `ReadOptions` and `WriteOptions` to the `PredefinedOptions`. I always thought that the `PredefinedOptions` are a "shortcut" for users to configure common options.
These read options and write options are not configurable options in the end, but "must-have" options that users cannot change (similar to the RocksDB option "create if not exists") so I am a bit confused about them being added to a class that managed user-defined options.

**Comment by carp84** [comment]
The main reason of making `ReadOptions` configurable through `RocksDBOptionsFactory` is to provide a convenient way to revert the `setTotalOrderSeek(true)` setting and prevent possible (unexpected) performance regression under real-world workload, although we have try our best to safeguard it through micro-benchmark.

OTOH, we actually find there're more setters in `ReadOptions` and `WriteOptions` than what we set as default:
* ReadOptions: `setFillCache`, `setManaged`, `setPinData`, `setReadTier`, **`setTotalOrderSeek`**, `setVerifyChecksums`, etc.
* WriteOptions: **`setDisableWAL`**, `setIgnoreMissingColumnFamilies`, `setNoSlowdown`, `setSync`, etc.

However, I could also understand if we choose to hide these detailed options from our users and believe our micro-benchmark result that `setTotalOrderSeek(true)` won't cause any regression in Flink use case. So just to clarify my thoughts and look forward to your opinion @StephanEwen. Thanks.

**Comment by StephanEwen** [comment]
I think having these in the `RocksDBOptionsFactory` is fine. I am confused a bit about the `PedefinedOptions` because you cannot override anything there (it is a fixed et of enums).

**Pull request closed without merging**
