### PR TITLE
FLINK-4480: Incorrect link to elastic.co in documentation

### PR DESCRIPTION
**Pull request by smarthi**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [X] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [X] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [X] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by smarthi** [comment]
1. Changed the ES2 version to 2.3.5
2. Fixed broken ElasticsearchExample.java
3. Removed use of Guava API.

**Comment by tzulitai** [comment]
Hi @smarthi,
Thank you for picking this up. The changes LGTM :) Also tested the 2.3.5 ES version bump.
Good catches on the Guava and broken example also!

**Comment by rmetzger** [comment]
+1 to merge

**Comment by StephanEwen** [comment]
Merging this...

**Pull request closed without merging**
