### PR TITLE
[FLINK-20710][Hive] HiveTableInputFormat and HiveSourceFileEnumerator will throw IllegalArgumentException when creating splits for tables with partitions on different hdfs nameservices

### PR DESCRIPTION
**Pull request by JackWangCS**
## What is the purpose of the change

HiveTableInputFormat will throws the IllegalArgumentException if partitions of a table are in different HDFS nameservices:
```java
Caused by: java.lang.IllegalArgumentException: Wrong FS: hdfs://ns1/hive/warehouse/test.db/flink_test/day=4, expected: hdfs://ns2
        at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:662)
        at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:222)
        at org.apache.hadoop.hdfs.DistributedFileSystem.access$000(DistributedFileSystem.java:114)
        at org.apache.hadoop.hdfs.DistributedFileSystem$20.doCall(DistributedFileSystem.java:1266)
        at org.apache.hadoop.hdfs.DistributedFileSystem$20.doCall(DistributedFileSystem.java:1262)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1262)
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1418)
        at org.apache.flink.connectors.hive.read.HiveTableInputFormat.createInputSplits(HiveTableInputFormat.java:299)
        at org.apache.flink.connectors.hive.read.HiveTableInputFormat.createInputSplits(HiveTableInputFormat.java:282)
        at org.apache.flink.connectors.hive.HiveTableSource.createBatchSource(HiveTableSource.java:214)
        at org.apache.flink.connectors.hive.HiveTableSource.getDataStream(HiveTableSource.java:188)
```
The FLINK-16197 introduced this issue.

## Brief change log

  - Use inputPath to get FileSystem when checking the input existence

## Verifying this change

*(Please pick either of the following options)*

This change is already covered by existing tests, such as *TableEnvHiveConnectorITCase.testNonExistingPartitionFolder()*.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializer:  no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? NA

### CODE REVIEW

**Comment by lirui-apache** [comment]
Hey @JackWangCS thanks for fixing the issue. Currently there're two classes that have the creating splits logic. One is `HiveTableInputFormat`, and the other is `HiveSourceFileEnumerator`. So your fix needs to be applied to both classes. Ideally we should do some refactor to consolidate them, but I guess that can be done after this fix.

**Comment by JackWangCS** [comment]
Hi @lirui-apache , thanks for your reply. From my understanding, the  `HiveSourceFileEnumerator` uses the new source API and will finally replace the `HiveTableInputFormat`, is it right? 
I could apply the fix to both classes in this PR and change the description.

**Comment by lirui-apache** [comment]
> Hi @lirui-apache , thanks for your reply. From my understanding, the `HiveSourceFileEnumerator` uses the new source API and will finally replace the `HiveTableInputFormat`, is it right?
> I could apply the fix to both classes in this PR and change the description.

That's absolutely correct :D

**Comment by JackWangCS** [comment]
Hi @lirui-apache , I have updated this PR, could you help to review this? Thank you.

**Review by lirui-apache — APPROVED** [review]
+1 pending tests

**Comment by JingsongLi** [comment]
+1 Merged to commit "[FLINK-20710][hive] Hive reading fail when splits on different FileSystem nameservices"

**Comment by JackWangCS** [comment]
@JingsongLi , do we have any plan to support write(INSERT INTO and INSERT OVERWRITE) hive partitions on different nameservices?  It's very common that some old partitions of a Hive table on different nameservices and the latest partitions and table location in hivemetastore on an another nameservice.

**Comment by lirui-apache** [comment]
> @JingsongLi , do we have any plan to support write(INSERT INTO and INSERT OVERWRITE) hive partitions on different nameservices? It's very common that some old partitions of a Hive table on different nameservices and the latest partitions and table location in hivemetastore on an another nameservice.

I don't think we support writing to hive partitions on different FS at the moment. But it should be possible to support such features. If you're interested, PR is always welcome ~

**Comment by JackWangCS** [comment]
Thank you for your reply. I will create a ticket to implement the feature. And there are some design decisions that need to be discussed. I will ping you on the new JIRA ticket about the details.

**Pull request merged**
