### PR TITLE
Bumped the docker container to the latest version

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by rmetzger** [comment]
Did you test the change?

I've tried it but got the following error

```
Removing intermediate container 0b4ba3a6115e
Step 3 : RUN mkdir ~/downloads && cd ~/downloads &&     wget -q -O - http://mirrors.advancedhosters.com/apache/flink/flink-0.10.0/flink-0.10.0-bin-hadoop2.tgz | tar -zxvf - -C /usr/local/
 ---> Running in ad41096423ab

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c mkdir ~/downloads && cd ~/downloads &&     wget -q -O - http://mirrors.advancedhosters.com/apache/flink/flink-0.10.0/flink-0.10.0-bin-hadoop2.tgz | tar -zxvf - -C /usr/local/' returned a non-zero code: 2
```

**Comment by thedrow** [comment]
No I just hoped it's the right way to do it.
I'll look into it.

**Comment by rmetzger** [comment]
Okay, thank you

**Comment by thedrow** [comment]
@rmetzger That should do it.

**Comment by rmetzger** [comment]
+1 to merge. I've verified the change locally.

I'll merge it.

**Comment by thedrow** [comment]
Thanks!

**Pull request closed without merging**
