### PR TITLE
[gelly][Refactoring] Removed example string

### PR DESCRIPTION
**Pull request by andralungu**
@vasia,

Just FYI :), in example/utils we have a class EdgeWithLongIdNullValueParser that is never used.
 
The examples that correspond to the library methods, e.g. PageRankExample cannot be renamed because that will cause a collision with the method name, in this case, PageRank. I guess that's why we added "Example" to the class name in the first place. 

To me the examples look good as they are in this commit. If you have another idea for the library method examples, let me know, but in my view Example is better than Usage, or whatever different word we may come up with.

### CODE REVIEW

**Comment by andralungu** [comment]
@vasia 
Don't forget to also have a look at this PR. It's rebased :)

**Comment by vasia** [comment]
Hi @andralungu,

regarding `EdgeWithLongIdNullValueParser`: good catch, let's remove it then.

As for the renaming, I would like the examples naming to be consistent. Right now, we have some named `xyzExample` like `GSAConnectedComponentsExample` and others without "Example" in the end, like `GSAPageRank`. I personally don't like "Example" in the end, because it makes class names unnecessarily long (we already know they're examples since they're in the respective package).
For the ones that don't use a library method, this is no problem. For the ones that use a library method and we have a collision. I guess we have two choices: (a) keep the word "Example" for the ones using a library method or (b) renaming the library methods to something like `xzyAlgorithm`.

Any other ideas?

**Comment by andralungu** [comment]
If you don't like the example string at the end, then we can go for sol (b)

**Comment by andralungu** [comment]
PR updated.

**Comment by vasia** [comment]
I take it your update means you agreed with my suggestion :)
I'll merge this one as well!

**Pull request closed without merging**
