### PR TITLE
[FLINK-28860] Fix CacheITCase

### PR DESCRIPTION
**Pull request by Sxnan**
## What is the purpose of the change

The PR address the two problems that cause CacheITCase to fail randomly. 

- Cache consumption in stream mode should recompute the result in case of cache miss instead of throwing an exception.
- JobMaster waits for the acknowledgment of partition release and promotion before reaching the globally terminal state. Otherwise, partitions that should be promoted may be released.

## Brief change log

- Cache consumption in stream mode recompute result in case of cache miss
- JobMaster wait for partition release and promote before close

## Verifying this change

This change is already covered by existing tests, such as CacheITCase.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by Sxnan** [comment]
@flinkbot run azure

**Comment by Sxnan** [comment]
@flinkbot run azure

**Review by gaoyunhaii — COMMENTED** [review]
Very thanks @Sxnan for the fix!

For the current implementation, I have one concern that we makes the JobMaster waits till all the partitions are released or promoted. This seems overkilled, right? We should only waits for promoted partitions, and the released partitions does not affect the rightness.

I'm a bit afraid the waiting here might cause additional overheads for jobs not using cached datastreams, especially for batch jobs with large scale.

**Comment by Sxnan** [comment]
@flinkbot run azure

**Comment by Sxnan** [comment]
@flinkbot run azure

**Review by gaoyunhaii — COMMENTED** [review]
Thanks @Sxnan for the udpating! It seems currently `JobMasterPartitionTracker` contains both `stopTrackingAndReleasePartitions` and `stopTrackingAndReleaseJobPartitions`. The two methods seems to be in fact provide the same functionality except that the latter one could filter from a super set. Perhaps we could split the sets in the caller side and merge the two methods?

**Review by gaoyunhaii — COMMENTED** [review]
Thanks @Sxnan for the updates! I only have some minor comments left.

**Review by gaoyunhaii — APPROVED** [review]
Thanks @Sxnan for the updates! LGTM

**Comment by gaoyunhaii** [comment]
Merged on master and 1.16, closed.

**Pull request closed without merging**
