### PR TITLE
[FLINK-4410] Expose more fine grained checkpoint statistics

### PR DESCRIPTION
**Pull request by uce**
This PR exposes more fine grained checkpoint statistics. The previous version of the tracking code had a couple of short comings:
- Only completed checkpoints were tracked in the history. You did not see in progress or failed checkpoints.
- Only the latest completed checkpoint had more fine grained stats per operator and sub tasks. This meant that a possibly interesting checkpoint statistics could be live updated as you was looking at it.
- Many newly tracked statistics like checkpoint duration at the operator or alignment duration were not exposed.

This PR addresses these issues. For the extended tracking of the life cycle I decided to add tracking callbacks of all relevant entities like `PendingCheckpointStats`, `CompletedCheckpointStats`, `SubtaskStateStats`, `TaskStateStats`, etc. The life cycle of these objects follows that of their corresponding entities.

Furtheremore, this add new REST API handlers that work with the new tracker and also new layout for displaying them.

---

Some screenshots:

**Clicking on the Checkpoints Tab**: Sub tabs for overview, history, summary stats, and the config.

00-start

**Clicking on the History Tab**: Lists recent checkpoints, including in progress ones.

01-history

**Clicking on details for a checkpoint**:

02-details

**After triggering a savepoint**:

03-savepoint

**Details for the triggered savepoint**:

04-savepoint_details

**Failed checkpoint while cancelling job**:

05-failed_checkpoint

06-failed_checkpoint_details

07-failed_checkpoint_overview

**Clicking on the config tab**:

09-config

**After restoring from the savepoint**:

08-restore_from_savepoint

### CODE REVIEW

**Comment by StephanEwen** [comment]
Wow, this looks awesome, great work.

Small note: In screenshot 2, it says "End to Duration", which should probably be "End to End Duration".

Is there also a column that shows the synchronous and asynchronous parts of the checkpointing time?

**Comment by StephanEwen** [comment]
I think what would put a cherry on top is if we can break the "End To End Duration" down into
  - Delay till triggering (how long until all barriers were there)
  - Synchronous checkpoint time
  - Asynchronous checkpoint time

That would help big time, as many users currently get confused when checkpoints have long async times, assuming that the computation halts for that time.

**Comment by uce** [comment]
Hey Stephan! Thanks for spotting the typo. The numbers are already reported but I forgot to attach the screenshot. They are only reported for each operator/task though, because I'm not sure what would be the best way to summarize those numbers as simply displaying the sum or maximum as the checkpoint alignment duration, sync/async checkpoint duration does not work well imo.

subtask-details

These numbers you get for all tracked checkpoints.

**Comment by StephanEwen** [comment]
Okay, super. The 'time to triggering' is then `end_to_end_time - sync_time - async_time`?

**Comment by uce** [comment]
Sorry for the long delay here. We can add that number as a separate column *Triggering Delay*. What do you think? As a follow up I would also like to add documentation about what all the numbers mean.

**Comment by StephanEwen** [comment]
I think a triggering delay would be very nice and helpful.
We can do this as a next step, separate from this pull request.

**Comment by rmetzger** [comment]
Very nice change!

I would love to merge it to 1.2 as well, its so helpful!
One very minor thing: I would suggest to round the percentages shown for the completion. I had an instance where it was showing a progress of 51.000000001%.

Here's a screenshot from my testing job:
image

**Comment by uce** [comment]
Thanks for checking it out Robert. Would love to merge it for 1.2 as well. I fixed the rounding issue.

**Comment by rmetzger** [comment]
+1 to merge

**Pull request closed without merging**
