### PR TITLE
[FLINK-6877] [runtime] Activate checkstyle for runtime/security

### PR DESCRIPTION
**Pull request by greghogan**

### CODE REVIEW

**Comment by hsaputra** [comment]
Looks like the tests not related to this PR.

+1
LGTM

**Comment by zentol** [comment]
Please don't merge this or any other runtime related checkstyle PR's over the weekend. I'm gonna have a chat with @StephanEwen early next week about which packages we can cover with checkstyle without significantly impacting existing feature branches.

**Comment by hsaputra** [comment]
@zentol thats just matter of rebasing to feature branches. Not sure how would you coordinate among all feature branches

**Comment by zentol** [comment]
Of course we can't account for feature branches, nor prevent merge conflicts entirely. But there are people who are very aware of what is going on right now in regards to bigger initiatives. We can use this information to coordinate on a best-effort basis to prevent us from activating checkstyle in a package right before a PR is being opened. This saves time both for the contributor and the person applying the checkstyle.

Keep in mind that the whole point of introducing it package by package was to reduce the amount of merge conflicts by targeting areas of flink-runtime that are not actively being worked on, as outlined in #4032 and FLINK-6729.

**Comment by greghogan** [comment]
@hsaputra thanks for the review. @zentol thanks for checking on the ongoing development so as not to interfere. If a delay is necessary then at least new contributions will be influenced by the new strict checkstyle.

A second point for introducing the checkstyle package by package is to reduce the number of times a manual merge is required during a rebase. With separate commits for import order, whitespace, and other reformatting the user may be asked to manually fix conflicts multiple times for the same file.

**Comment by greghogan** [comment]
@zentol what is the status of the checkstyle changes?

**Comment by zentol** [comment]
Didn't get a chance to talk to @StephanEwen yet, but TBH I'm also kind of getting tired of waiting. From my side this PR can be merged.

**Comment by zentol** [comment]
We'll just have to rely on our own judgement.

**Comment by hsaputra** [comment]
+1 for merging. The longer it waits the more conflicts it will cause

**Comment by zentol** [comment]
merging.

**Pull request closed without merging**
