### PR TITLE
[backport] [FLINK-5114] [network] Handle partition producer state check for unregistered executions

### PR DESCRIPTION
**Pull request by uce**
This is a backport of #2912.

Code between 1.1 and 1.2 slightly changed. I decided to further backport the new callback method via `TaskActions`.

This would be important to get into 1.1.4.

\cc @tillrohrmann

### CODE REVIEW

**Comment by StephanEwen** [comment]
Having a quick look at this: I think this breaks with a fundamental design in the ExecutionGraph:
The `findExecutionAttemptWithId(...)` method searches the prior execution attempts.

Why is that necessary? Can we not just assume that if the attempt is not equal to the current execution attempt, then the status is some form of "disposed".

If the produced result is finished, the execution will still not be in the "prior execution attempts". That can only happen once the task restarts, in which case you should not try and fetch the partition any more.

**Comment by uce** [comment]
> Why is that necessary? Can we not just assume that if the attempt is not equal to the current execution attempt, then the status is some form of "disposed".

It's not necessary. It's perfectly fine to do it as you describe. Not having the `currentExecution` set to the producer execution means that the producer was restarted (hence cancelled or failed). This only made the handling in `Task` easier, but it should not dictate this change in the `ExecutionVertex`. I'll change that to only check the `currentExecution` and handle it accordingly.

**Comment by uce** [comment]
I removed the `findExecutionAttemptWithId` and only check the latest attempt. If that does not match the expected producer attempt, I answer with a `PartitionProducerDisposedException` to which the requesting `Task` reacts with a `cancelExecution`. I would really like to merge this and kick off a new RC for 1.1.4 soon.

**Comment by uce** [comment]
Closing in favour of #2975.

**Pull request closed without merging**
