### PR TITLE
[FLINK-7679][build][java9] Upgrade maven enforcer plugin to 3.0.0-M1

### PR DESCRIPTION
**Pull request by yew1eb**
## What is the purpose of the change

Maven enforcer plugin fails after Java 9 build 175 [(MENFORCER-274)](https://issues.apache.org/jira/browse/MENFORCER-274) Let's upgrade the version to 3.0.0 when released.

## Brief change log

* Bump `maven-enforcer-plugin` version from 1.4.1 to 3.0.0-M1.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**yes** / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by greghogan** [comment]
+1 tests are passing and the 1.4 release has been forked so we're at the start of a new release cycle

**Comment by zentol** [comment]
merging.

**Comment by zentol** [comment]
The PR was messed up during a merge; the enforcer plugin is no correctly properly incremented in the root pom, but only in force-shading.

**Comment by yew1eb** [comment]
:wink:  @zentol ,  Thank you for your careful review.
This PR has been updated.

**Pull request closed without merging**
