### PR TITLE
Added member currentSplit for FileInputFormat.java

### PR DESCRIPTION
**Pull request by peedeeX21**
According to [this stackoverflow discussion] (http://stackoverflow.com/questions/30599616/create-objects-from-input-files-in-apache-flink/30600148?noredirect=1#comment49358891_30600148) with 
@rmetzger the attribute currentSplit is now accessible through FileInputFormat. It provides the split that this parallel instance must consume.

### CODE REVIEW

**Comment by rmetzger** [comment]
Thank you for the contribution.

+1 to merge.

**Comment by peedeeX21** [comment]
Travis fails executing this test: `KafkaITCase.testPersistentSourceWithOffsetUpdates`. Unfortunately I have no idea what the problem is. I am not even sure if this is related to my commit.
Can someone have a look at it? Thanks

**Comment by rmetzger** [comment]
Hi, this `KafkaITCase` is known to be unstable and I have actually a fix that disables the test for now. Since only 1 out of 5 jobs failed, your change doesn't break anything and is still good to merge (in my opinion)
I would like to get confirmation from at least one other committer before merging it.

**Comment by StephanEwen** [comment]
+1 , good addition

**Comment by rmetzger** [comment]
Merging ...

**Comment by rmetzger** [comment]
... merged (github mirror broken?!)

**Pull request closed without merging**
