### PR TITLE
[FLINK-16494][k8s] Switch to enum type for config option KubernetesConfigOptions.CONTAINER_IMAGE_PULL_POLICY

### PR DESCRIPTION
**Pull request by zhengcanbin**
## What is the purpose of the change

Switch from string type to enum type for config option KubernetesConfigOptions.CONTAINER_IMAGE_PULL_POLICY.

## Verifying this change

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)

### CODE REVIEW

**Comment by zhengcanbin** [comment]
@flinkbot run travis

**Comment by zhengcanbin** [comment]
@flinkbot run travis

**Comment by zhengcanbin** [comment]
@flinkbot run azure

**Comment by zhengcanbin** [comment]
Hi, @rmetzger! It's quite strange that the **CI** is not timely triggered these two days when I make a force-push or comment `@flinkbot run travis` here for this PR. Do you know what happens behind?

**Comment by rmetzger** [comment]
Thanks a lot for pining me. @zentol it seems that the ci-bot is down. No PR builds were triggered since Friday

**Comment by rmetzger** [comment]
The problem was actually not the bot, but an outage in Azure: https://status.dev.azure.com/_event/179641421
Can you rebase your pr to the current master and push it again, then a build will be triggered.
Sorry for the inconvenience.

**Comment by zhengcanbin** [comment]
> The problem was actually not the bot, but an outage in Azure: https://status.dev.azure.com/_event/179641421
> Can you rebase your pr to the current master and push it again, then a build will be triggered.
> Sorry for the inconvenience.

Thanks for the information @rmetzger! I have rebased the pr and push it again.

**Comment by rmetzger** [comment]
Did you fetch before rebasing? Your branch does not seem to contain this commit yet https://github.com/apache/flink/commit/4a4baf0c81c23ed3125078500605a7db11f3cbba

**Comment by zhengcanbin** [comment]
Hi @rmetzger! You are right. I forgot to fetch the newest commits before rebasing yesterday. I have fetched before rebasing and push it again.

**Comment by zhengcanbin** [comment]
> LGTM.
> 
> Please ping me on test passed.

cc @TisonKun. The Travis succeeded but the Azure failed. I am not sure why the Azure failed, could you help take a look?

**Comment by rmetzger** [comment]
I'm pretty sure that all of the Azure failures are unrelated to your change.
Builds on master additionally have S3 credentials available, pull requests don't. I'm pretty sure that the s3 tests don't cope properly with not having the credentials available.
I'll soon file a ticket for this.

**Comment by rmetzger** [comment]
Here's the ticket: https://issues.apache.org/jira/browse/FLINK-16633

**Comment by zhengcanbin** [comment]
> Here's the ticket: https://issues.apache.org/jira/browse/FLINK-16633

Thanks a lot for the explanation. Will fetch and rebase again after FLINK-16633 is resolved.

**Comment by zhengcanbin** [comment]
Ping @TisonKun. The Travis has passed.

**Comment by TisonKun** [comment]
Thanks for your contribution @zhengcanbin ! Merged.

**Pull request merged**
