### PR TITLE
[hotfix] [docs] Small fix in CLI documentation

### PR DESCRIPTION
**Pull request by knaufk**
## What is the purpose of the change

Fix syntax error in CLI documentation

## Brief change log

Fix syntax error in CLI documentation

## Verifying this change

Build documentation

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency):  no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no 
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by knaufk** [comment]
This should also be merged into {{master}}.

**Comment by rmetzger** [comment]
I guess this was introduced in https://github.com/apache/flink/commit/a796fff7901f3f329eff6d33bf41cd6ef391a0c0

**Comment by rmetzger** [comment]
@flinkbot approve all

I'll merge it

**Comment by rmetzger** [comment]
This has already been fixed in master in https://github.com/apache/flink/commit/e9db130023b4e975cad9648864f1afb5eae2ec0b

**Pull request merged**
