### PR TITLE
[FLINK-24745][format][json] Add support for Oracle OGG JSON format parser

### PR DESCRIPTION
**Pull request by wgzhao**
## What is the purpose of the change

The data written to kafka via Oracle OGG CDC is not parsed by the current json parser (json, debezium), add a module that can parse ogg json format

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): ( no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (JavaDocs)

### CODE REVIEW

**Comment by wuchong** [comment]
Could you add some tests for the new format just like how debezium-json does?

**Comment by wgzhao** [comment]
@wuchong  ok. This feature is still under development, I will add the necessary tests and documentation

**Comment by wjcgood** [comment]
Thank you. I've been looking for this plan for a long time。

**Comment by wjcgood** [comment]
I think there are some problems in  ReadableMetadata of OggJsonDecodingFormat
1 "current_ts","op_ts","table " not nested inside ogg json. So key is themselves , isJsonPayload should false ,Override convert should change.I don't understand what is "source.properties" in ogg json ,But it should have the same problem

**Comment by MartijnVisser** [comment]
@leonardBang Will you do a review for this one?

**Comment by leonardBang** [comment]
@MartijnVisser I'd like to, @wgzhao could you fix the test failure and doc failure before we start review it ?

**Comment by wgzhao** [comment]
> @MartijnVisser I'd like to, @wgzhao could you fix the test failure and doc failure before we start review it ?

OK

**Comment by leonardBang** [comment]
> > @MartijnVisser I'd like to, @wgzhao could you fix the test failure and doc failure before we start review it ?
> 
> OK

@wgzhao Do you have time to update this PR ?

**Comment by leonardBang** [comment]
> @leonardBang I'm sorry, I've been a bit busy for a while, in fact, I probably won't be able to fix the bugs for the month. or should I close this PR for now or set it to draft mode and submit it when I'm done fixing it?

It's okay, let me find someone to help take over this PR, we hope this feature can appear in 1.15.

**Comment by luoyuxia** [comment]
@wgzhao Hi, I would like to continue your work in #18738 . I wil fix the build failure, add some more test and address the comments if have.  Anyway, feel free to take over my upated pr #18738 when you're free before it's merged.

**Comment by wgzhao** [comment]
> 

I appreciate you continuing the PR. thanks

**Comment by leonardBang** [comment]
> > 
> 
> I appreciate you continuing the PR. thanks

I closed this PR with keeping your contributions in #18738  @wgzhao, thanks for your contribution.

**Pull request closed without merging**
