### PR TITLE
[FLINK-5146] Improved resource cleanup in RocksDB keyed state backend

### PR DESCRIPTION
**Pull request by StefanRRichter**
Currently, the resources such as taken snapshots or iterators are not always cleaned up in the RocksDB state backend. In particular, not starting the runnable future will leave taken snapshots unreleased.

This preliminary PR improves the behaviour of releasing resources obtained through the RocksDB JNI bridge.

IMPORTANT NOTICE: This PR also upticks the current version of RocksDB to 4.11.2, as I found some instabilities in the old version that could lead to segfaults, in particular at GC time.

### CODE REVIEW

**Comment by aljoscha** [comment]
Overall, the changes and the tests look very good. There are some `TODO`s left in the code, what about those?

**Comment by StefanRRichter** [comment]
This was a preliminary PR, so that people can already take a look. However, I think besides one sleep in a test, the added value is already enough to have this in. Leftover todos can go to a followup PR.

**Comment by StefanRRichter** [comment]
I introduced the planned change to the test. You could take another look if you want :-)

**Comment by aljoscha** [comment]
Thanks for your work: 👍 

I merged it, could you please close this PR?

**Comment by StefanRRichter** [comment]
Thanks for the reviews and merging, @aljoscha @tillrohrmann . Closing this.

**Pull request closed without merging**
