### PR TITLE
[FLINK-27315] Fix the demo of MemoryStateBackendMigration

### PR DESCRIPTION
**Pull request by EchoLee5**
## What is the purpose of the change

JobManagerStateBackend changed to JobManagerCheckpointStorage

## Brief change log

JobManagerStateBackend changed to JobManagerCheckpointStorage

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by Myasuka** [comment]
@EchoLee5 I think the patch is good. However, this PR cannot be merged due to current commits in your `EchoLee5:master` branch. You should let your commit on top of the latest master branch without any commit like `Merge branch 'apache:master' into master`, in general, we would use different branch instead of the `master` branch in your forked repo to create the pull request.

**Comment by EchoLee5** [comment]
> @EchoLee5 I think the patch is good. However, this PR cannot be merged due to current commits in your `EchoLee5:master` branch. You should let your commit on top of the latest master branch without any commit like `Merge branch 'apache:master' into master`, in general, we would use different branch instead of the `master` branch in your forked repo to create the pull request.

@Myasuka Thanks for the suggestion, I will change the pr and resubmit

**Comment by Myasuka** [comment]
It seems you still did not get what I mean, I think you'd better create another PR based on your another forked branch instead of `EchoLee5:master` branch.

**Comment by EchoLee5** [comment]
> It seems you still did not get what I mean, I think you'd better create another PR based on your another forked branch instead of `EchoLee5:master` branch.

Sorry, I misunderstood your point, I closed this pr first

**Pull request closed without merging**
