### PR TITLE
[FLINK-14382] Incorrect handling of FLINK_PLUGINS_DIR on Yarn (Backport to 1.9)

### PR DESCRIPTION
**Pull request by wangyang0918**
## What is the purpose of the change

Backport #10084 to release-1.9

## Brief change log
none

## Verifying this change
none

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by pnowojski** [comment]
Can you @wangyang0918 ping me once travis is green?

**Comment by wangyang0918** [comment]
@flinkbot run travis

**Comment by wangyang0918** [comment]
@flinkbot run travis

**Comment by wangyang0918** [comment]
@pnowojski Finally, the travis is green. Please help to merge.

**Comment by wangyang0918** [comment]
@pnowojski Could you please help to merge the PR? Thanks a lot.

**Comment by pnowojski** [comment]
PR title is very vague (it should include the original title somehow), I will change it.

Has anything changed compared to the master version? Were there some rebasing conflicts that were non trivial to resolve?

**Comment by wangyang0918** [comment]
@pnowojski Since the `AbstractYarnClusterDescriptor` has been removed in the master branch, so we can not cherry-pick last commit. It should be reworked manually. The codes are same. There is no other changes except the version in pom of flink-plugins-test.

**Comment by pnowojski** [comment]
Thanks for the clarification. Merging!

**Pull request merged**
