### PR TITLE
[FLINK-33588][Flink-Runtime] Fix NullArgumentException of getQuantile method in DescriptiveStatisticsHistogramStatistics

### PR DESCRIPTION
**Pull request by zhutong6688**
## What is the purpose of the change

Fix NullArgumentException of getQuantile method in DescriptiveStatisticsHistogramStatistics

## Brief change log

This DescriptiveStatisticsHistogramStatistics class has added null initialization
1、DescriptiveStatisticsHistogramStatistics.java

## Verifying this change

3799e5aae7fa3cc0500aa1cd0b06856

During the verification process, the task was submitted to Yarn and run in Yarn cluster mode. After multiple stops and restarts, it was found that the NullArgumentException exception had disappeared. This fully verified the correctness of the modification, improved the stability of program operation, and also improved the accuracy of displaying statistical information in the web UI interface of the Flink task (as shown in the above figure).
The highlighted log section in the above figure is the log I printed to assist in troubleshooting, which can be ignored.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (no)

### CODE REVIEW

**Comment by zhutong6688** [comment]
issue link is https://issues.apache.org/jira/browse/FLINK-33588

**Comment by zhutong6688** [comment]
old PR is https://github.com/apache/flink/pull/23749, #23749, this PR is new, but the content is the same

**Comment by zhutong6688** [comment]
@flinkbot run azure

**Comment by zhutong6688** [comment]
@flinkbot run azure

**Comment by zhutong6688** [comment]
@flinkbot run azure

**Comment by zhutong6688** [comment]
@flinkbot run azure

**Comment by JingGe** [comment]
Thanks @zhutong6688 for driving it. Could you squash the commits?

**Comment by zhutong6688** [comment]
@JingGe Okay, I will resubmit it this evening and compress the submission

**Pull request closed without merging**
