### PR TITLE
[FLINK-10967] Update kafka dependency to 2.2.0

### PR DESCRIPTION
**Pull request by ijuma**
## What is the purpose of the change

Apache Kafka 2.1+ includes an important improvement with regards to producer
timeouts as described in KIP-91:

https://cwiki.apache.org/confluence/display/KAFKA/KIP-91+Provide+Intuitive+User+Timeouts+in+The+Producer

## Brief change log

The kafka connector kafka dependency has been updated to 2.2.0.

## Verifying this change

This change is already covered by the existing kafka connector tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): yes
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by yanghua** [comment]
cc @tillrohrmann @pnowojski

**Comment by ijuma** [comment]
I rebased and updated to the now released Kafka 2.1.1. Any chance of getting this merged?

**Comment by aljoscha** [comment]
The test failed, although one failure was in the (unrelated) Kafka 0.11 connector. I restarted, let's see what we get.

**Comment by aljoscha** [comment]
Could you try and rebase to latest master?

**Comment by ijuma** [comment]
@aljoscha I have rebased and also updated the PR to use Kafka 2.2.0 that has been released a few months ago.

**Comment by yanghua** [comment]
@ijuma Thanks for your contribution, actually, there is another PR #8055 try to upgrade Kafka client dependency to 2.2.0. There are more changes than the version number. So I suggest we could close this PR. cc @aljoscha and @pnowojski

**Comment by ijuma** [comment]
Thanks for the reference. I'll close this PR. Hopefully #8055 gets reviewed and merged more quickly than this one. :)

**Comment by pnowojski** [comment]
Sorry that you had to wait @ijuma and @yanghua that there were couple of things missing here. I merged #8055 so I'm closing this one as well.

**Pull request closed without merging**
