### PR TITLE
[FLINK-14533][flink-table-planner] Fix LOWER/UPPER not being pushed down to TableSource

### PR DESCRIPTION
**Pull request by YuvalItzchakov**
## What is the purpose of the change

Fix issue [FLINK-14533](https://issues.apache.org/jira/browse/FLINK-14533) where using `LOWER/UPPER` in predicate would cause predicate pushdown to fail

## Brief change log

Change `BuiltInFunctionDefinition` to match the `SqlFunction` string.

## Verifying this change

Added tests

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by aljoscha** [comment]
@YuvalItzchakov Thanks for working on this! There is a test failure that points to an actual problem. The name `lowerCase` is what is used when writing Table expressions (and when using the Scala Expression DSL) so we cannot simply change it.

Btw, did you only observe this when using the new (blink-based) planner or also with the classic planner?

**Comment by aljoscha** [comment]
Also: https://twitter.com/schneems/status/1191844272682786822

**Comment by aljoscha** [comment]
I pushed a proposed fix.

**Comment by aljoscha** [comment]
@YuvalItzchakov Can you confirm that your newly added test actually works on your branch? I think something might have changed after you implemented it but I'm wondering why it ever worked. This seems very strange to me. 😅 

The test fails because your tests (before translation) expect
```
  LogicalProject(a=[$0], b=[$1])
  +- LogicalFilter(condition=[LIKE(LOWER($0), _UTF-16LE'foo')])
   +- LogicalTableScan(table=[[default_catalog, default_database, MTable]])
```
but it is
```
LogicalProject(a=[$0], b=[$1])
+- LogicalFilter(condition=[LIKE(LOWER($0), _UTF-16LE'foo')])
   +- LogicalTableScan(table=[[default_catalog, default_database, MTable, source: [filterPushedDown=[false], filter=[]]]])
```
the `filterPushedDown` part is a newer addition.

When I fix that, your tests fail because `shouldPushDown` doesn't return true because the top-level call is a `like`, and not a `lower`.

**Comment by YuvalItzchakov** [comment]
@aljoscha I definitely know it passed on my branch. I'll make sure to re-run it tomorrow.

**Comment by aljoscha** [comment]
@YuvalItzchakov Any news?

**Comment by aljoscha** [comment]
@wuchong Could you maybe look at this? It also contains a fix for the Blink Runner.

**Comment by wuchong** [comment]
@aljoscha sure, I will have a look too. 

@YuvalItzchakov could you rebase the code when you are free?

**Comment by aljoscha** [comment]
I think the contributor is not reacting anymore so we either have to take over or close the PR.

**Comment by wuchong** [comment]
Hi @aljoscha , I rebased and fixes test failures and also update the implementation of the testing filteralbe source to make it support to filter records based on the pushdowned functions. Appreciate if you can have a look.

**Comment by wuchong** [comment]
cc @godfreyhe , could you help to review the `TestingFilterableTableSource` changes?

**Comment by wuchong** [comment]
cc @godfreyhe , could you help to review the `TestingFilterableTableSource` changes?

**Comment by aljoscha** [comment]
This looks good to me. Thanks for the help with this, @wuchong!

**Comment by YuvalItzchakov** [comment]
I totally forgot about this! sorry. Thanks @wuchong for making this happen.

**Comment by wuchong** [comment]
Never mind @YuvalItzchakov :)

**Comment by YuvalItzchakov** [comment]
Is there anything else I can do to push this through? @aljoscha

**Comment by wuchong** [comment]
Once @godfreyhe is fine with the changes on `TestingFilterableTableSource`, I think it can be merged then.

**Comment by godfreyhe** [comment]
sorry for the late reply. 
the changes looks good to me. I have a minor question: It's better to add some comment like "Only upper and lower function is supported" or we can add a constructor argument like ` filterableFunctions: Set[(String, Function)] = Set()` to make `TestingFilterableTableSource` more generic.

**Comment by wuchong** [comment]
Hi @godfreyhe , thanks for the reviewing, I added a comment on the `TestingFilterableTableSource` class.

```
NOTE: Currently, only >, >=, <, =, =, <> operators and UPPER and LOWER functions are allowed to be pushed down into this source.
```

**Comment by godfreyhe** [comment]
thanks for the update, LGTM, +1 to merge

**Comment by aljoscha** [comment]
Cool that this can finally be resolved. @wuchong do you want to merge?

**Comment by wuchong** [comment]
Merging...

**Pull request merged**
