### PR TITLE
[FLINK-7220] [checkpoints] Update RocksDB dependency to 5.6.1

### PR DESCRIPTION
**Pull request by StefanRRichter**
This PR updates the RocksDB dependency to 5.6.1. Further changes:

- the more performant merge operator is used via `setMergeOperatorName("stringappendtest")`.
- the option `.setDisableDataSync(...)` was removed from RocksDB. Usage is also removed from Flink.
- Takes care of also close the default column family before closing the RocksDB instance.

### CODE REVIEW

**Comment by StefanRRichter** [comment]
CC @aljoscha - suggesting to add this change also to the 1.3.2 release.

**Comment by StefanRRichter** [comment]
Just noticed that the license is not updated in the 5.5.1 branch, but only in master. So I guess this means we have to wait for a release that has the updated Apache compatible license?

**Comment by zentol** [comment]
We should still be able to switch back to the original RocksDB dependency. The licensing issue should also apply to frocksdb.

**Comment by greghogan** [comment]
RocksDB 5.5.5 looks to include the desired licensing.

**Comment by StefanRRichter** [comment]
Yes, that is correct, I kindly asked them to also update their license in the releases on their issue tracker https://github.com/facebook/rocksdb/issues/2605.

I will update the PR as soon as this version is available from Maven Central.

**Comment by StephanEwen** [comment]
Very good news, thanks for taking care of that!

**Comment by StefanRRichter** [comment]
Version 5.5.5 is already published, so from my side this is now good to merge. Can somebody give me another +1?

**Comment by StephanEwen** [comment]
Looks good, +1 with request for minor change:

I would pull out the setting of the merge operator from the option factories. We should not allow users to override (or forget to set it), because we make a hard assumption on the fact that exactly that merge operator is configured.

**Comment by StefanRRichter** [comment]
Thanks for the review @StephanEwen . I changed my PR according to your comments. Will merge now.

**Comment by StefanRRichter** [comment]
Merged in 219ae33d36

**Comment by greghogan** [comment]
The merge looks to have not been squashed.

**Comment by uce** [comment]
@StefanRRichter As mentioned by Greg, we should either squash follow up commits like `Stephan's comments` into their parent or tag them similar to the main commit with a more descriptive message.

**Comment by StephanEwen** [comment]
Agree. There are two very non-descriptive commits in the master now.
Let's try to avoid that in the future...

**Comment by StefanRRichter** [comment]
@uce I know, but this was not intentional. I squashed them but pushed the wrong (unsquashed) branch because of my shell history.

**Comment by greghogan** [comment]
@uce @StephanEwen we had a bit of continued discussion in the JIRA. Can we add a pre-commit hook to the Apache repo to validate the format of the summary line?

**Comment by uce** [comment]
Thanks for the pointer Greg. I didn't look at the JIRA issue. I like the idea of automating this but I would go with a pre-push hook instead of a pre-commit hook. It could be annoying during local dev if we force every commit to have the format already. I'm not sure whether INFRA allows this or not though.

@StefanRRichter Sure, can happen. 😊

**Pull request closed without merging**
