### PR TITLE
[FLINK-6492] Fix unclosed DataOutputViewStream usage

### PR DESCRIPTION
**Pull request by huafengw**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by huafengw** [comment]
Can anyone take a look at this one?

**Comment by huafengw** [comment]
Hi @tzulitai, I'm new to Flink and would you mind taking a look at this one?

**Comment by tzulitai** [comment]
Hi @huafengw, thanks for the fixes! I'll probably merge this along with #3937 as there are some overlapping changes here and there.

**Comment by gallenvara** [comment]
Hi, @huafengw . Welcome to Flink family. Thanks for your PR and the changes look good to me. :)

**Comment by huafengw** [comment]
Thank you guys :)

**Comment by zhangminglei** [comment]
Hi, @huafengw Welcome also.

**Comment by zentol** [comment]
@tzulitai Did you forget about this PR? :)

**Comment by tzulitai** [comment]
ah ... yes indeed, thanks for reminding me. I'll merge this to master and 1.3; it should be ok if it ends up missing in the 1.3.0 release.

**Pull request closed without merging**
