### PR TITLE
[FLINK-30501] Update Flink build instruction to deprecate Java 8 instead of requiring Java 11

### PR DESCRIPTION
**Pull request by lindong28**
## What is the purpose of the change

Flink 1.15 and later versions require at least Java 11 to build from sources [1], whereas the pom.xml specifies the source/target is 1.8. This inconsistency confuses users.

As mentioned in the [FLINK-25247](https://issues.apache.org/jira/browse/FLINK-25247) title, the goal of that ticket is to "Inform users about deprecation". It will be better to inform users that "Java 8 is deprecated" instead of saying "Fink requires at least Java 11 to build", so that users have the right information to make the right choice for themselves.

Also note that Flink community is regularly running flink-ml benchmark for both Java 8 and Java 11 [2], which suggests that we are practically ensuring Java 8 is supported.

If we decide to official drop Java 8 support, Flink community probably should give explicit notice regarding the deprecation period so that users can be prepared for this breaking change. We can follow the Kafka website doc [3] for example, which says "Java 8, Java 11, and Java 17 are supported. Note that Java 8 support has been deprecated since Apache Kafka 3.0 and will be removed in Apache Kafka 4.0".

[1] https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/flinkdev/building/
[2] http://codespeed.dak8s.net:8000/timeline/?ben=mapSink.F27_UNBOUNDED&env=2
[3] https://kafka.apache.org/documentation/

## Brief change log

Update Flink doc to mention that "Java 8 is deprecated" instead of saying "Flink requires at least Java 11 to build".

## Verifying this change

N/A.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector:  no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? N/A

### CODE REVIEW

**Comment by lindong28** [comment]
@zentol Would you have time to review this PR?

**Comment by lindong28** [comment]
@flinkbot run azure

**Comment by lindong28** [comment]
@flinkbot run azure

**Comment by lindong28** [comment]
The CI failed because the container is still using Java 8 to build Flink sources [1]. Since our README is already asking users to use Java 11 to build Flink [2], maybe we should also update CI container to use Java 11?

[1] https://github.com/apache/flink/blob/master/azure-pipelines.yml#L42
[2] https://nightlies.apache.org/flink/flink-docs-master/docs/flinkdev/building/

**Comment by zentol** [comment]
Closing the PR as per my JIRA comment.

**Comment by lindong28** [comment]
@zentol @yunfengzhou-hub Do you have time to review this PR?

**Comment by lindong28** [comment]
@reswqa Can you help review this PR? Thanks!

**Review by reswqa — APPROVED** [review]
Thanks @lindong28, LGTM!

**Pull request merged**
