### PR TITLE
FLINK-3397 Failed streaming jobs should fall back to the most recent

### PR DESCRIPTION
**Pull request by ramkrish86**
Initial patch to see if this is what is intended out of the JIRA. Thought a PR could help me in getting a better feedback. I tried to tweak and add a test case but I could not. I followed what was done in SavePointITCase and particularly testRestoreFailure(). But am not able to get a flow where there could be a checkpoint and also a save point because this test case allows the notification to happen when the job is removed and that clears all the existing savePoints. So when the test case restores it always goes with the savePoint.

### CODE REVIEW

**Comment by ramkrish86** [comment]
@uce - any feedback/suggestions are welcome.

**Comment by uce** [comment]
Sorry for not responding earlier in the JIRA issue. I've somehow missed your mentions. I agree with what Stephan said in JIRA. Before trying to fix something here, we would have to think about the relationship between checkpoints and savepoints in general. I also have some other ideas. Is it OK for you to close this PR for now? Sorry again for not getting back earlier.

**Comment by ramkrish86** [comment]
Sure. I can close this. I always had a doubt on the scope of this JIRA. As per the suggestion I have already started working on a doc. I will try to list out how things are working now and may be that we can use to see if all the current relationship between savepoints and checkpoints are captured. And you can also add your ideas to it. If the task is a bigger one can split up the tasks and I can see which one I can take up. @uce - your thoughts?

**Comment by uce** [comment]
Makes sense :-)

**Pull request closed without merging**
