### PR TITLE
[FLINK-2557] TypeExtractor properly returns MissingTypeInfo

### PR DESCRIPTION
**Pull request by zentol**
This fix is not really obvious so let me explain:

getParameterTye() is called from two different places in the TypeExtractor; to validate the input type and to extract the output type.

Both cases consider the possibility that getParameterType() fails, but check for different exceptions. 

The TypeExtractor only returns a MissingTypeInfo if it encounters an InvalidTypesException; IllegalArgumentExceptions are not catched. This is what @mjsax encountered.
Changing the exception type causes the TypeExtractor to properly return a MissingTypeInfo, which is later overridden by the returns(...) call.

In order for the input validation to still work properly aswell, it now catches InvalidTypesExceptions instead.

### CODE REVIEW

**Comment by tillrohrmann** [comment]
The PR seems to solve the problem. However, I'm wondering why the `InvalidTypesException` is an unchecked exception. I think that this is the actual culprit and should be fixed. Moreover, according to: Joshua Bloch in "Effective Java"

> Use checked exceptions for recoverable conditions and runtime exceptions for programming errors (Item 58 in 2nd edition)

In our case we can recover from it by returning a `MissingTypeInformation`.

**Comment by zentol** [comment]
I agree, will get right on it.

**Comment by zentol** [comment]
InvalidTypesException (from here on abbreviated as ITE) is no longer unchecked.

For this to work i had to make changes in surprisingly many classes so let's break it down:

* In general, InvalidProgramExceptions are now thrown for unrecoverable conditions, where previously an ITE would be thrown..

* TypeExtractor methods that return a TypeInformation will never throw an ITE and instead return a MissingTypeInfo if it is allowed, otherwise an InvalidProgramException.
* One public TypeExtractor method now throws an ITE, which is getParameterType(). This method is heavily used in the TypeExtractor itself as well, so i didn't see a way to fix this in a non API breaking way that doesn't rely yet again on unchecked exceptions.
 * affects hadoop-compatibility functions, which now catch them

* A few OperatorClasses catched ITE's in returns(TypeInformation ...) and then manually created a MissingTypeInfo. This now happens in the TypeExtractor directly.

* TypeInformation classes threw an ITE in getInfoFor(Class ...) if the given class didn't match the TypeInformation class. These have been changed to IllegalArgumentExceptions.

* DataSet/DataStream threw an ITE in getType() if the type was a MissingTypeInfo, changed to InvalidProgramException.
 * similiar issue in StreamExecutionEnvironment

**Comment by StephanEwen** [comment]
@tillrohrmann This distinction between checked and unchecked exceptions is a good point. It is not very consistent in the project so far, but we should definitely improve on that!

**Comment by StephanEwen** [comment]
@zentol This is a delicate change, so let's make sure we understand this correctly:

The InvalidTypesException is now only used internally in the type extractor, and never propagated?

I am a bit skeptical about returning the "MissingTypeInfo" in the type extractor directly. A lot of other places / user code classes create type infos and most of them will not check for "MissingTypeInfo" - they rather expect to fail. Only very specific operator places can tolerate the MissingTypeInfo, because they can swap it with a type hint later.

**Comment by zentol** [comment]
@StephanEwen yes, generally InvalidTypesExceptions are not propagated, except TypeExtractor.getInfoFor(Class ...), which is both public and used in the TypeExtractor. 

If an operator that can't tolerate MissingTypeInfo is given one, when will it fail?

There are basically 2 options that i see:
* keep returning a MissingTypeInfo, but go through call to TypeExtractor methods and add a check for MissingTypeInfo if necessary
* throw a checked exception instead of returning a MissingTypeInfo, and go through every call to TypeExtractor methods and add try/catch blocks.

essentially both options are the same, so do we prefer an exception or a MissingTypeInfo?

either way, we're gonna need a lot more changes :/

**Comment by zentol** [comment]
An exception is probably preferable since it would be consistent with the getInfoFor() method.

**Comment by fhueske** [comment]
@zentol Any news on this PR?

**Comment by zentol** [comment]
@fhueske well I'm still waiting for an answer as to how to proceed. Either return a MissingTypeInfo or throw some checked Exception when the type could not be determined. This is just a choice of style; both solutions require a pass over (probably) all calls to type extractor methods.

It might also be a good idea to separate the original fix (in the first commit) from the exception stuff. The fix did not fail any tests and resolved the issue, while the rest is essentially a refactoring.

**Comment by fhueske** [comment]
I am not familiar with the TypeExtractor in detail, but would support to fix the bug first and open a separate issue to refactor the extractor, if that is possible.
@StephanEwen, @tillrohrmann What do you think?

**Comment by tillrohrmann** [comment]
I'm ok with this approach.

**Comment by zentol** [comment]
I've removed the refactoring commit and did a rebase.

**Comment by mjsax** [comment]
Can you add a test case that checks if "returns" works now. See the JIRA example.

**Comment by zentol** [comment]
@mjsax test case added

**Comment by twalthr** [comment]
Looks good to merge, if build succeeds.

**Comment by mjsax** [comment]
One failing test in new to me. Do we need a JIRA for it?
```
Tests in error: 
  CompactingHashTableTest.testHashTableGrowthWithInsert:98->getMemory:243 » OutOfMemory
```
The other one, is our good old friend `YARNSessionFIFOITCase`.

I guess it can get merged.

**Comment by StephanEwen** [comment]
Merging this...

**Pull request closed without merging**
