### PR TITLE
[FLINK-2804] [client, runtime] Add blocking job submission support in case of JobManager recovery

### PR DESCRIPTION
**Pull request by uce**
This is based on some other PRs. Only review the last commit.

The client submit and wait method gets a configuration parameter, which it uses to determine how to react to a lost job manager. In normal operation, nothing changes.

This is the log output of a test for this. This is tailored to the current state of the job graph recovery. I think there is some room for improvement in the future in the messages the client gets on recovery. Currently the job manager simply assumes that the same job client actor is waiting for updates (that's why you see multiple submission messages.

The most important part to review is the retry loop in `submitJobAndWait#submitJobAndWait`. @tillrohrmann, can you review this please?

```
1 > 10:21:48,754 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - ================================================================================
1 > 10:21:48,756 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Test testJobManagerConnectionLoss(org.apache.flink.runtime.client.JobClientRecoveryITCase) is running.
1 > 10:21:48,756 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - --------------------------------------------------------------------------------
1 > 10:21:48,970 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Started JobManagerProcess(id=0, port=52432).
1 > 10:21:49,037 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Started JobManagerProcess(id=1, port=52433).
1 > 10:21:49,104 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Started JobManagerProcess(id=2, port=52434).
1 > 10:21:49,863 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Started taskmanager.
1 > 10:21:49,899 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Waiting for leader retrieval.
1 > 10:21:50,549 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Leader determined as akka.tcp://flink@127.0.0.1:52432/user/jobmanager. Trying to determine, which job manager process this is.
1 > 10:21:50,555 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Leader determined as process 0.
1 > 10:21:50,716 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Waiting for task manager to connect.
1 > 10:21:50,724 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Task manager connected.
1 > 10:21:50,726 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Waiting for first execution of job graph.
1 > 10:21:50,726 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Submitting blocking twice job.
1 > 10:21:50,729 INFO  org.apache.flink.runtime.client.JobClient                     - Submitting job f56fb890afbddc1f25ab5d0e56771cad in recovery mode ZOOKEEPER
1 > 10:21:50,732 INFO  org.apache.flink.runtime.client.JobClient                     - Sending message to JobManager akka.tcp://flink@127.0.0.1:52432/user/jobmanager to submit job blocking job graph (f56fb890afbddc1f25ab5d0e56771cad) and wait for progress
1 > 10:21:50,846 INFO  org.apache.flink.runtime.client.JobClient                     - Job was successfully submitted to the JobManager
1 > 10:21:50,849 INFO  org.apache.flink.runtime.client.JobClient                     - 10/06/2015 10:21:50	Job execution switched to status RUNNING.
1 > 10:21:50,854 INFO  org.apache.flink.runtime.client.JobClient                     - 10/06/2015 10:21:50	blocking vertex(1/1) switched to SCHEDULED 
1 > 10:21:50,855 INFO  org.apache.flink.runtime.client.JobClient                     - 10/06/2015 10:21:50	blocking vertex(1/1) switched to DEPLOYING 
1 > 10:21:50,876 INFO  org.apache.flink.runtime.client.JobClient                     - 10/06/2015 10:21:50	blocking vertex(1/1) switched to RUNNING 
1 > 10:21:50,934 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Killing the leader.
1 > 10:21:50,935 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Waiting for leader retrieval
1 > 10:21:57,022 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Leader determined as akka.tcp://flink@127.0.0.1:52433/user/jobmanager. Trying to determine, which job manager process this is.
1 > 10:21:57,022 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Leader determined as process 1
1 > 10:21:57,022 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Waiting for second execution of job graph.
1 > 10:21:59,907 INFO  org.apache.flink.runtime.client.JobClient                     - Lost connection to JobManager akka.tcp://flink@127.0.0.1:52432/user/jobmanager
1 > 10:21:59,908 INFO  org.apache.flink.runtime.client.JobClient                     - Lost connection to job manager. Retrieving new one.
1 > 10:21:59,930 INFO  org.apache.flink.runtime.client.JobClient                     - New job manager address akka.tcp://flink@127.0.0.1:52433/user/jobmanager and id 43147f59-30bc-4a9c-a5db-43136d14b409
1 > 10:21:59,930 INFO  org.apache.flink.runtime.client.JobClient                     - Updating job client actor with new job manager.
1 > 10:22:07,137 INFO  org.apache.flink.runtime.client.JobClient                     - Job was successfully submitted to the JobManager
1 > 10:22:07,141 INFO  org.apache.flink.runtime.client.JobClient                     - 10/06/2015 10:22:07	Job execution switched to status RUNNING.
1 > 10:22:07,144 INFO  org.apache.flink.runtime.client.JobClient                     - 10/06/2015 10:22:07	blocking vertex(1/1) switched to SCHEDULED 
1 > 10:22:07,145 INFO  org.apache.flink.runtime.client.JobClient                     - 10/06/2015 10:22:07	blocking vertex(1/1) switched to DEPLOYING 
1 > 10:22:07,157 INFO  org.apache.flink.runtime.client.JobClient                     - 10/06/2015 10:22:07	blocking vertex(1/1) switched to RUNNING 
1 > 10:22:07,241 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Killing the leader.
1 > 10:22:07,241 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Waiting for job submission to return.
1 > 10:22:19,906 INFO  org.apache.flink.runtime.client.JobClient                     - Lost connection to JobManager akka.tcp://flink@127.0.0.1:52433/user/jobmanager
1 > 10:22:19,907 INFO  org.apache.flink.runtime.client.JobClient                     - Lost connection to job manager. Retrieving new one.
1 > 10:22:19,926 INFO  org.apache.flink.runtime.client.JobClient                     - New job manager address akka.tcp://flink@127.0.0.1:52434/user/jobmanager and id d195f698-9cbd-4695-8809-8c93bfe96fac
1 > 10:22:19,926 INFO  org.apache.flink.runtime.client.JobClient                     - Updating job client actor with new job manager.
1 > 10:22:25,102 INFO  org.apache.flink.runtime.client.JobClient                     - Job was successfully submitted to the JobManager
1 > 10:22:25,105 INFO  org.apache.flink.runtime.client.JobClient                     - 10/06/2015 10:22:25	Job execution switched to status RUNNING.
1 > 10:22:25,108 INFO  org.apache.flink.runtime.client.JobClient                     - 10/06/2015 10:22:25	blocking vertex(1/1) switched to SCHEDULED 
1 > 10:22:25,108 INFO  org.apache.flink.runtime.client.JobClient                     - 10/06/2015 10:22:25	blocking vertex(1/1) switched to DEPLOYING 
1 > 10:22:25,119 INFO  org.apache.flink.runtime.client.JobClient                     - 10/06/2015 10:22:25	blocking vertex(1/1) switched to RUNNING 
1 > 10:22:25,121 INFO  org.apache.flink.runtime.client.JobClient                     - 10/06/2015 10:22:25	blocking vertex(1/1) switched to FINISHED 
1 > 10:22:25,122 INFO  org.apache.flink.runtime.client.JobClient                     - 10/06/2015 10:22:25	Job execution switched to status FINISHED.
1 > 10:22:25,135 INFO  org.apache.flink.runtime.client.JobClient                     - Job execution complete
1 > 10:22:25,135 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Job submission returned.
1 > 10:22:25,137 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - --------------------------------------------------------------------------------
1 > 10:22:25,137 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - Test testJobManagerConnectionLoss(org.apache.flink.runtime.client.JobClientRecoveryITCase) successfully run.
1 > 10:22:25,137 INFO  org.apache.flink.runtime.client.JobClientRecoveryITCase       - ================================================================================
```

### CODE REVIEW

**Comment by tillrohrmann** [comment]
I'm on it :-)

**Comment by tillrohrmann** [comment]
For the sake of completeness I repost what I've just commented on the last commit:

I think it would be better to move the `JobManager` retrieval logic into the `JobClientActor`. Then the `JobClientActor` would be responsible for finding the current leader and resubmit the `JobGraph`. The `Client` would simply wait for the `JobExecutionResult` or an `Exception`.

That way, we would unify the retry logic in one place which would reduce a little bit of complexity.

Since @uce is quite overloaded right now, I can take a shot at it. Does the PR depends on anything from the PRs #1227 and #1153?

**Comment by uce** [comment]
OK, I like your idea! And thanks for finishing it. It depends on the job graph recovery for the added IT cases to work. I think you can work your way around the tests, but just working on top of this branch should also work.

**Comment by uce** [comment]
Closing this in favour of Tills upcoming PR.

**Pull request closed without merging**
