### PR TITLE
[FLINK-4209] Fix issue on docker with multiple NICs and remove supervisord dependency

### PR DESCRIPTION
**Pull request by iemejia**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by iemejia** [comment]
I added some additional fixes for example to exclude build dependencies from the final image, and to make the docker-compose script simpler.
@aljoscha This is a set of small fixes that I missed at FLINK-4118.

**Comment by iemejia** [comment]
I added this last commit to remove the dependency on supervisord, thanks to @greghogan for the 'wait' idea. Now flink has the thinnest docker image possible :).

**Comment by aljoscha** [comment]
@iemejia This is now good to merge?

From my side it looks good!

**Comment by iemejia** [comment]
Yes, it is done, I am really happy of getting rid of python/supervisord in the image now.
Please merge if you consider it ok.

**Comment by iemejia** [comment]
One last thing, are you interested on getting the flink image into becoming an official docker image ? I took a look around it and it seems we can ask for this.
The benefit is that users can just make 'docker pull flink' and get the flink image from the hub.docker.com repository ready to use (e.g. I am publishing for the moment my own 'unofficial' builds at 
https://hub.docker.com/r/iemejia/flink/

**Comment by aljoscha** [comment]
Would the Flink image be tied to a specific Flink version?

**Comment by aljoscha** [comment]
I merged it. Could you please close this PR if it doesn't close automatically.

Thanks for the work! 😃

**Comment by iemejia** [comment]
Great, closing now.

**Comment by iemejia** [comment]
About the flink image version, we can support multiple versions via tags, those are pulled with the: separator, e.g. docker pull flink:1.0.3-hadoop26-scala_2.10
And we can agree on a default (e.g. most recent versions which would be -> :latest).

**Comment by aljoscha** [comment]
Yes, that would probably be good.

**Comment by iemejia** [comment]
Ok, I will check how is the procedure and I will tell you if we need something else.

**Comment by aljoscha** [comment]
Thanks!

**Comment by jagatfx** [comment]
@iemejia Were you able to followup on creating the official docker image. It's a great idea.

**Comment by iemejia** [comment]
@jagatfx Yes, this is still in my TODO list, I have not had a lot of time to follow the process to make an image official, but I hope I will in the next days.

**Pull request closed without merging**
