### PR TITLE
[FLINK-441] Rename Pact* and Nephele* classes in the optimizer

### PR DESCRIPTION
**Pull request by StephanEwen**
Renames the package `org.apache.flink.compiler` to `org.apache.fink.optimizer`
Renames `PactCompiler` to `Optimizer`
Renames `NepheleJobGraphGenerator` to `JobGraphGenerator`
Renames `PactConnection` to `DagConnection` (since the enclosing data structure is the Optimizer DAG).
Renames instances of internal variables and methods that referred to `PactContract` to refer to `Operator` instead.

Removes the unnecessary context checker. Was only ever valuable in the deprecated record API.

Makes the various graph traversals (previously inner classes of the Optimizer) standalone classes, which makes the Optimizer class more graspable.

Migrates some changes from the deprecated Record API to the Java API.

### CODE REVIEW

**Comment by rmetzger** [comment]
Why aren't we renaming the `flink-compiler` module into `flink-optimizer`?
Its an internal module only, so users won't see what we reorganized our code internally.

**Comment by StephanEwen** [comment]
We can do that, I am okay with this. So far, all renaming was strictly internal.

The renaming of the maven project may affect some people who have added it as a (redundant) dependency.

**Comment by rmetzger** [comment]
I think it is fine if we mention in the release notes that the name has changed.
All the quickstart pom users won't be affected.

**Comment by StephanEwen** [comment]
Agree, let's do it.

**Comment by StephanEwen** [comment]
Any objections against merging this?

**Comment by rmetzger** [comment]
LGTM

**Comment by matadorhong** [comment]
As in your comment in this PR, I think you make a small spelling mistake "Renames the package org.apache.flink.compiler to org.apache.fink.optimizer", which should be "org.apache.flink.optimizer".
But the codes are all OK. HAHA.

**Comment by hsaputra** [comment]
+1 SHIP IT

**Comment by StephanEwen** [comment]
Good, then I'll try and merge this today...

**Comment by StephanEwen** [comment]
After correcting the commit message ;-)

**Comment by StephanEwen** [comment]
Manually merged in 633b0d6a9b25fd324f1aa007bbce246be304c099

**Pull request closed without merging**
