### PR TITLE
[FLINK-30386] Fix the issue that column constraint lacks primary key not enforced check

### PR DESCRIPTION
**Pull request by LadyForest**
## What is the purpose of the change

This pull request aims to fix the issue that the column constraint lacks the not enforced check.
```sql
CREATE TABLE foo (
  a INT PRIMARY KEY, -- currently this passes the validation, but it should be `a INT PRIMARY KEY NOT ENFORCED`
  b STRING
) WITH (...)
```

## Brief change log

Currently, the constraint check(on the duplicate primary key, unique key, and enforced mode) spreads over the parse and conversion phase(see `SqlCreateTable#validate` and `SqlToOperatoinConverter#validateTableConstraint`).

To improve this, introduce a `SqlConstraintValidator` to perform the unified check for both column and table constraints. 
The logic of`SqlToOperatoinConverter#validateTableConstraint` is moved to `SqlConstraintValidator`.

## Verifying this change

This change added tests and can be verified as follows:
- FlinkSqlParserImplTest
- SqlToOperationConverterTest
- HBaseConnectorITCase
- HiveServer2EndpointITCase

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduces a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by LadyForest** [comment]
@flinkbot run azure

**Review by lincoln-lil — COMMENTED** [review]
@LadyForest thanks for fixing this! I've left some comments, and it's better to also add some tests for 'create table as' and 'create table like' which has duplicate constraints or non-enforced ones

**Comment by lincoln-lil** [comment]
@flinkbot run azure

**Comment by LadyForest** [comment]
@flinkbot run azure

**Review by lincoln-lil — APPROVED** [review]
LGTM

**Comment by lincoln-lil** [comment]
@LadyForest could you also create a backport pr for 1.16?

**Pull request merged**
