### PR TITLE
[hotfix] [docs] Fix typo

### PR DESCRIPTION
**Pull request by YngwieWang**
[hotfix] [docs] Fix typo

### CODE REVIEW

**Comment by 1u0** [comment]
Hi @YngwieWang,

can you run the following command on your local machine:
```git cherry-pick 07c0404```
and then push your `patch-4` branch to remote.

This way you would cherry-pick your other changes (for English version of the documentation) into this PR.

**Comment by YngwieWang** [comment]
@1u0, sorry, I just open the PR on github, I didn't do it from my local respo. I hava translated the Chinese version of this doc and opened a PR to fix the typo of the Chinese version. Could I close this PR and open a new one that just fix these typos of the English version?

**Comment by 1u0** [comment]
In my opinion, it would be better if you just submit both fixes (English version and Chinese version) in one PR. Because the change you are proposing is very small.

I've suggested you before to address this in #9538, by just rebasing and editing your changes.
I gave the last suggestion here, because it should be more easier for you to just cherry pick your changes from #9538 to here.

You don't need to (and **shouldn't**) open new pull requests for minor adjustments of already opened PR. This looses communication chain and distracts reviewers.

What I ask you in this PR is to run `git cherry-pick 07c0404` and then `git push origin patch-4` (assuming that `origin` points to `YngwieWang/flink.git`). If done correctly, we can close #9538 (as duplicate) and continue with only this PR.

**Comment by YngwieWang** [comment]
@1u0 , I am greatly appreciated for your help and patient, and I am very sorry that my git skill is poor.
I followed your instruction and got some error. I think this time I'm still not doing the right thing.  
I'm very sorry to trouble you and the community.

**Comment by 1u0** [comment]
Hi @YngwieWang, no worries.

I've cherry-picked and combined your changes in my fork (https://github.com/1u0/flink/tree/pr-9538-docs-hotfix), but I cannot merge into main `flink` repo or update your fork (your PRs).

If you can manage to reset one of your PR branches (for example `patch-1`) and push to your fork, you should see the PR updated with changes.

If you still have difficulties with git, I can also open a new PR with your changes as a last resort. But first let me know if you are ok with that.

**Comment by YngwieWang** [comment]
@1u0 , you can open a new PR with my changes, it's OK to me,  appreciate for your help.

**Pull request closed without merging**
