### PR TITLE
[FLINK-10768][Table & SQL] Move external catalog related code from TableEnvironment to CatalogManager

### PR DESCRIPTION
**Pull request by bowenli86**
## What is the purpose of the change

In the design of Flink-Hive integration and external catalog enhancements, we propose using `CatalogManager` to manage all external catalogs and related aspects for a clearer separation. Currently all external catalogs are managed by `TableEnvironment`, which makes TableEnvironment bloated.

Background: there are two parallel efforts going on right now - FLINK-10686, driven by Timo, includes moving external catalogs APIs from flink-table to flink-table-common, also from Scala to Java; FLINK-10744 I'm working on right now to integrate Flink with Hive and enhance external catalog functionality.

As discussed with @twalthr in FLINK-10689, we'd better parallelize these efforts while introducing minimal overhead for integrating them later. Our agreed way is to writing new code/feature related to external catalogs/hive in Java in flink-table first then move to other module like flink-table-common, this way we can minimize migration efforts. If existing classes are modified for a feature we can start migrating them to Java in a separate commit first and then perform the actual feature changes, and migrated classes can be placed in flink-table/src/main/java until we find a better module structure.

This PR moves all EXISTING external catalogs related code from `TableEnvironment` to `CatalogManager`, and it's the initial step for `CatalogManager`. It blocks `[[FLINK-10698]Create CatalogManager class manages all external catalogs and temporary meta objects](https://issues.apache.org/jira/browse/FLINK-10698)`

This PR is a PURE REFACTOR, only moving APIs around, NO change on the behaviors and NO new feature is added. 

## Brief change log

  - added `CatalogManager` in Java
  - moved external catalog related code from `TableEnvironment` to `CatalogManager`
  - added unit tests in `CatalogManagerTest`

## Verifying this change

- This change is already covered by existing tests, such as *TableEnvironmentTest*.
- This change added tests and can be verified as follows:
  - Added unit tests in `CatalogManagerTest`

## Does this pull request potentially affect one of the following parts:

none

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by bowenli86** [comment]
@twalthr @fhueske @xuefuz Can you please take a look?

**Comment by xuefuz** [comment]
Thanks for the PR. I quickly went over the changes and have some high-level comments:

1. It would be better if there is clearer distinction of responsibility for the CatalogManager class. If it manages catalogs and temp tables/functions, then it should just expose those as needed. If we need something extra, then we need some justification.

2. Since we are encapsulating catalog, Calcite schema, and temp tables/functions in CatalogManager, we should hide them as much as possible. Exposing something like registerExternalCatalog() might trigger some questions.

3. Intuitively TableEnvironment depends on CatalogManager but not vise versa. Thus, I'm not sure if and why we need a circular reference between them.

**Comment by bowenli86** [comment]
holding on this PR as there are some related discussion going on at[ the design doc](https://docs.google.com/document/d/1SkppRD_rE3uOKSN-LuZCqn4f7dz0zW5aa6T_hBZq5_o/edit)

**Comment by bowenli86** [comment]
closing this PR in favor of new plan

**Pull request closed without merging**
