### PR TITLE
[FLINK-5824] Fix String/byte conversions without explicit encoding

### PR DESCRIPTION
**Pull request by dawidwys**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [ ] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [ ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by shijinkui** [comment]
Good changes. `ConfigConstants.DEFAULT_CHARSET` change to `ConfigConstants.UTF_8 ` may be more clear.

**Comment by dawidwys** [comment]
@shijinkui I think the idea of having this Constant in `ConfigConstant` is it could potentially be set to some other value. If I am mistaken I would instead of using `ConfigConstants.UTF_8` opt for java7's `StandardCharsets.UTF_8` directly.

**Comment by shijinkui** [comment]
As your current replacement with `ConfigConstants.DEFAULT_CHARSET`, it's better for setting other charsets. UTF_8 has clear semantics. If we'll never change the default charset utf_8 to other charset, I prefer `ConfigConstants.UTF_8`

**Comment by zentol** [comment]
I'm in favor of using ```ConfigConstants.DEFAULT_CHARSET```. Using ```ConfigConstants.UTF_8``` does not imply in any way that this is the default that anyone should use; it would be equivalent to using ```StandardCharsets.UTF_8```.

**Comment by StephanEwen** [comment]
I would prefer to keep the value in `ConfigConstants`, just because it clearly defines in one place what we want to use as the default (rather than passing `StandardCharsets.UTF_8` everywhere).

As for the name, I think both suggestions are fine in the end. It is unlikely that we ever switch the charset, especially since checkpoints and high-availability storage encodes data in that charset.

What would be good to have is a test that checks that we never use a byte conversion without a charset. Maybe a checkstyle rule. If that does not work, we can try and do a `Reflections` test (see RpcCompletenessTest for an example of how to reflectively analyze code in tests).

**Comment by dawidwys** [comment]
So as I mentioned in JIRA I don't see a way to do it in checkstyle rule. 

I managed to implement a test that performs the check using `Reflections` but I don't know where shall I place it. The problem is that only files from packages that are dependencies to the module with this test will be checked. First idea I had was to put it in the `filnk-tests` module, but it does not depend on e.g. any of `flink-connectors`

**Comment by StephanEwen** [comment]
I think starting with `flink-tests` is good, we can then improve from there.

**Comment by StephanEwen** [comment]
Good change, thanks!
Merging this...

**Pull request closed without merging**
