### PR TITLE
[hotfix][docs] Fix typo in textLines parameter for Map transformation

### PR DESCRIPTION
**Pull request by hackergin**
Fix dateset related doc typo.

### CODE REVIEW

**Comment by hackergin** [comment]
@MartijnVisser  I noticed https://issues.apache.org/jira/browse/FLINK-18274 and create a pr.

**Review by MartijnVisser — CHANGES_REQUESTED** [review]
Thanks for opening the PR and the fixes. The changes are OK, but we need to make sure that the commit message and the PR title are meeting the standards as written down on https://flink.apache.org/contributing/code-style-and-quality-pull-requests.html

As commit message and as PR, I would expect something like `[hotfix][docs] Fix typo in textLines parameter for FlatMap transformation`

If you can fix that, I can approve the PR. When it's merged, we should also create backports of this documentation fix to `release-1.14`, `release-1.13` and `release-1.12`

**Comment by hackergin** [comment]
> Thanks for opening the PR and the fixes. The changes are OK, but we need to make sure that the commit message and the PR title are meeting the standards as written down on https://flink.apache.org/contributing/code-style-and-quality-pull-requests.html
> 
> As commit message and as PR, I would expect something like `[hotfix][docs] Fix typo in textLines parameter for FlatMap transformation`
> 
> If you can fix that, I can approve the PR. When it's merged, we should also create backports of this documentation fix to `release-1.14`, `release-1.13` and `release-1.12`

@MartijnVisser  Thanks for reminding, I will pay more attention next time.  I have already change the commit message and pr title.

**Review by MartijnVisser — APPROVED** [review]
Thanks for addressing the comments. Looks good from my end.

@AHeise I think this can be merged, LMKWYT

**Review by deadwind4 — APPROVED** [review]
LGTM.

**Review by RocMarshal — APPROVED** [review]
LGTM +1.

**Pull request merged**
