### PR TITLE
[FLINK-28783] [flink-core] Class ConfigOptions's example code have error.

### PR DESCRIPTION
**Pull request by GOODBOY008**
## What is the purpose of the change

https://issues.apache.org/jira/browse/FLINK-28783

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector:  no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? JavaDocs

### CODE REVIEW

**Comment by GOODBOY008** [comment]
@PatrickRen Please cc, if you are avalible.Thank you.

**Comment by GOODBOY008** [comment]
@flinkbot run azure

**Review by liuzhuang2017 — APPROVED** [review]
LGTM

**Review by leonardBang — APPROVED** [review]
+1

**Pull request merged**
