### PR TITLE
[FLINK-1406] update Flink compatibility notice

### PR DESCRIPTION
**Pull request by mxm**
I will also attach a patch for the "how to contribute" guide.

### CODE REVIEW

**Comment by rmetzger** [comment]
Good to merge.

**Comment by fhueske** [comment]
I would add that Windows is only supported for local setups and link to the [Flink on Windows section of the Local Setup page](http://flink.apache.org/docs/0.7-incubating/local_setup.html#flink-on-windows)  since the following instructions assume a UNIX setup.

**Comment by mxm** [comment]
@fhueske I updated the documentation to include the link.

**Comment by uce** [comment]
:+1:

**Comment by fhueske** [comment]
Good to merge

**Pull request closed without merging**
