### PR TITLE
[FLINK-18044][Connectors/Common] Add the subtask index information to the SourceReaderContext.

### PR DESCRIPTION
**Pull request by pyscala**
## What is the purpose of the change
Add the subtask index information to the SourceReaderContext.

## Brief change log
Add the subtask index information to the SourceReaderContext.

## Verifying this change

This change is already covered by existing tests

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? ( no)

### CODE REVIEW

**Comment by pyscala** [comment]
Hi @becketqin , appreciate for your time to review this PR , thanks

**Review by becketqin — COMMENTED** [review]
@pyscala Really sorry for the belated review and thanks for the patch. Do you mind rebasing the patch? BTW, I think in the `SourceReaderContext` we are following the naming convention of `getXXX()`.

**Comment by pyscala** [comment]
> @pyscala Really sorry for the belated review and thanks for the patch. Do you mind rebasing the patch? BTW, I think in the `SourceReaderContext` we are following the naming convention of `getXXX()`.

@becketqin Thanks for your reply. I will finish it later.

**Comment by becketqin** [comment]
Thanks for the patch. LGTM.

**Pull request merged**
