### PR TITLE
[FLINK-8914][CEP]Fix wrong semantic when greedy pattern is the head of the pattern

### PR DESCRIPTION
**Pull request by Aitozi**
## What is the purpose of the change

As described in the jira [FLINK-8914](https://issues.apache.org/jira/projects/FLINK/issues/FLINK-8914)
There is something wrong with `greedy` when it is the head of the pattern. Because the `NFA` process each `ComputationState` and will produce a new `Start ComputationState`. So when it runs into the greedy match, other `start runs` can also be set up

## Brief change log

*(for example:)*
  - *Add a new StateType `Greedy` for convenience of distinguishing the greedy in computations*
  - *Remove the redundant start state during process*

## Verifying this change

Add two UT in `GreedyITCase`

### CODE REVIEW

**Comment by Aitozi** [comment]
@dawidwys please help review this pr when you free,thx

**Comment by dawidwys** [comment]
Hi @Aitozi , thanks for your contribution. 

FYI. We had some discussions offline with @kl0u about how to approach this issue. We plan to adjust the behaviour of AfterMatchSkip clause a bit and it will also affect the greedy in the beginning. Therefore it might take a while to comment on this PR.

**Comment by Aitozi** [comment]
Got it. Thanks for your response @dawidwys and waiting for you further comment on this PR.  I am glad to contribute to the cep library and really hope to get more ideas or share from you guys discussion about CEP, thanks.

**Comment by dawidwys** [comment]
Hi @Aitozi. As I described previously, this case should be handled with greedy and proper `AfterMatchSkip` strategy. Would you be ok with closing this PR?

**Comment by Aitozi** [comment]
Sure, closing.

**Comment by sunsence** [comment]
@dawidwys The proper AfterMatchSkip strategy can only work on some situations, such as `List<String> strings = Arrays.asList("1,3,5,5,5,5,1,6,".split(","));

        DataStream<String> input = env.fromCollection(strings);

        Pattern<String, ?> pattern = Pattern.<String>
                begin("start", AfterMatchSkipStrategy.skipPastLastEvent()).where(new SimpleCondition<String>() {
            @Override
            public boolean filter(String value) {
                return value.equals("5");
            }
        }).oneOrMore()
                .followedBy("end").where(new SimpleCondition<String>() {

                    @Override
                    public boolean filter(String value) {
                        return value.equals("6");
                    }
                });`
The output is :
### **=======
5
5
5
5
6
=======**

While ,when I have only one pattern，it doesn't work fine.
` List<String> strings = Arrays.asList("1,3,5,5,5,5,1,6,".split(","));

        DataStream<String> input = env.fromCollection(strings);

        Pattern<String, ?> pattern = Pattern.<String>
                begin("start", AfterMatchSkipStrategy.skipPastLastEvent()).where(new SimpleCondition<String>() {
            @Override
            public boolean filter(String value) {
                return value.equals("5");
            }
        }).oneOrMore().greedy()`

The output is :
**=======
5
======
=======
5
======
=======
5
======
=======
5
======**

**Comment by markoknez** [comment]
@dawidwys  If I can just try to reopen this topic. AfterMatchSkipStrategy does really work for cases in which greedy is used, problem with AfterMatch is that we have really long states which can generate millions of partial matches which are only discarded after the full matching is done. Of course this never gets done because before that, we run out of resources

**Pull request closed without merging**
