### PR TITLE
[FLINK-21511][es] Bump Elasticsearch6 version to 6.8.12

### PR DESCRIPTION
**Pull request by zhangmeng0426**
## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

on Elasticsearch 6.3.1 there is a bug BulkProcessor hangs for threads deadlocked

description bug : https://github.com/elastic/elasticsearch/issues/44556

fix bug : https://github.com/elastic/elasticsearch/issues/47599

upgrate Elasticsearch version to 6.8.12

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*
upgrate Elasticsearch version to 6.8.12

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: ( no )
  - The runtime per-record code paths (performance sensitive): ( no )
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: ( no )
  - The S3 file system connector: ( no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by KarmaGYZ** [comment]
@zhangmeng0426 The commit message could be changed to "[FLINK-21511][es] Bump Elasticsearch6 version to 6.8.12". You can try to rerun the CI.

**Review by KarmaGYZ — CHANGES_REQUESTED** [review]
Hi, @zhangmeng0426 . Thanks for the contribution.
We need also to change the version in other places:
- ElasticsearchSinkITCase
- run-nightly-tests.sh
- NOTICE files
- Elasticsearch6DynamicSinkITCase

Also, the commit message should be changed.

**Comment by KarmaGYZ** [comment]
@zhangmeng0426 Do you still work on it?

**Comment by fapaul** [comment]
As part of https://issues.apache.org/jira/browse/FLINK-24323, we upgraded the elastic search versions. I'll close this ticket.

**Pull request closed without merging**
