### PR TITLE
[FLINK-22304][table] Refactor some interfaces for TVF based window to…

### PR DESCRIPTION
**Pull request by cshuo**
… improve the extendability

## What is the purpose of the change
Refactor some interfaces for tvf based window to make it more extendable.

## Brief change log
  - Refactor WindowBuffer#Factory so that the creation of records combiner can be delegated to it.
  - Rename some interfaces/classes to make them more clear and easier to understand.
  - make BytesMap#getEntryIterator copy-aware.

## Verifying this change
This change is already covered by existing tests, such as `WindowAggregateITCase`, `WindowRankITCase`.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Review by wuchong — APPROVED** [review]
LGTM.

**Review by wuchong — APPROVED** [review]
LGTM.

**Comment by wuchong** [comment]
Some tests are failed, please have a check @cshuo .

**Comment by cshuo** [comment]
> Some tests are failed, please have a check @cshuo .

**Comment by cshuo** [comment]
The failed test is python docs, which is already fixed. I will rebase and trigger test again.

**Pull request closed without merging**
