### PR TITLE
[FLINK-32965][flink-runtime] Removing the deprecated MutableObjectMode and restore related tests

### PR DESCRIPTION
**Pull request by 1996fanrui**
## What is the purpose of the change

[FLINK-1285](https://issues.apache.org/jira/browse/FLINK-1285) updated the MutableObjectMode to ObjectReuse. The TaskConfig#getMutableObjectMode() is not used for a long long time, and it's internal class, so it can be removed directly.

Also, we should update the GroupReduceDriverTest:

- Updating the testAllReduceDriverAccumulatingImmutable() from `context.setMutableObjectMode(false);` to `context.getExecutionConfig().disableObjectReuse();`.
- Updating the testAllReduceDriverIncorrectlyAccumulatingMutable() to `context.getExecutionConfig().disableObjectReuse();`, and fix the assert.

 
More details can be get from https://github.com/apache/flink/pull/23233#discussion_r1304595960

## Brief change log

- [FLINK-32965][flink-runtime] Removing the deprecated MutableObjectMode and restore related tests
- [FLINK-32965][flink-runtime][hotfix] Refactor some code with code style warning

## Verifying this change

Improve the old tests:

- GroupReduceDriverTest#testAllReduceDriverIncorrectlyAccumulatingMutable
- GroupReduceDriverTest#testAllReduceDriverAccumulatingImmutable

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by 1996fanrui** [comment]
Hi @Jiabao-Sun  @RocMarshal  would you mind helping review this PR in your free time? thanks~

**Review by ferenc-csaky — APPROVED** [review]
Thanks @1996fanrui for this change, LGTM!

**Review by RocMarshal — APPROVED** [review]
Hi, @1996fanrui 
Thanks for the contribution and ping.
LGTM +1.

**Review by 1996fanrui — COMMENTED** [review]
Thanks @ferenc-csaky and @RocMarshal  for the review, merging~

**Pull request merged**
