### PR TITLE
[FLINK-18802][formats] Package uber jar including all dependencies for flink-avro

### PR DESCRIPTION
**Pull request by PatrickRen**
## What is the purpose of the change

This pull request changes the pom.xml of flink-avro module in order to create a uber jar in packaging phase, including dependencies such as avro, jackson-core-asl, jackson-mapper-asl and joda-time. 

## Brief change log

- Add another execution in maven-assembly-plugin to create a jar-with-dependencies
- Remove the "provided" scope and "optional" tag of joda-time dependency to include it in the uber jar

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by becketqin** [comment]
LGTM. We probably also want to have uber jars for other formats as well. 
@wuchong Do you want to take a look?

**Comment by PatrickRen** [comment]
Looks like CI failed. Fixed in 766339d

**Review by twalthr — CHANGES_REQUESTED** [review]
As I mentioned in the JIRA issue, we should have consensus on adding a default Avro version. I'm fine with adding one for the SQL Client JAR file because we will always use GenericRecord there. However, for DataStream API jobs users often use SpecificRecord which might compile against a specific Avro version.

Also, for SQL Client JAR files with GenericRecord we probably don't need JodaTime anymore. The newest Avro version is JodaTime free, no?
https://issues.apache.org/jira/browse/AVRO-2079

**Comment by PatrickRen** [comment]
Thanks a lot @twalthr ~ What about upgrading Avro version to 1.9.0 so that we can get rid of joda-time, and packaging it into sql-jar as the default Avro version?

**Comment by dawidwys** [comment]
Hey @PatrickRen,
I think it would be fine upgrading the avro version for the sql jar. We could even think of upgrading it straight to the 1.10 version. Again I very much agree with @twalthr that we can do that for the sql jar only. 

In case of the {{flink-avro}} module the situation is not that easy. Users might've generated their classes against specific version. Moreover they might want to use the version of avro that comes with hadoop they're using. Therefore they should have an easy way to replace the avro version.

**Comment by dawidwys** [comment]
I am closing this PR because of inactivity and because it is subsumed by https://github.com/apache/flink/pull/13373 . Feel free to reopen if you think otherwise.

**Pull request closed without merging**
