### PR TITLE
[FLINK-12576][docs,metrics] Document that input pool usage metrics ignore LocalInputChannels

### PR DESCRIPTION
**Pull request by pnowojski**
This is just a simple documentation update.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / **docs** / JavaDocs / not documented)

### CODE REVIEW

**Comment by pnowojski** [comment]
Thanks for pointing this out. I forgot to do it. Will update PR shortly.

**Comment by pnowojski** [comment]
Actually @zhijiangW I don't think that we need to do it, or at least I can not find an option how to do it. Or am I missing something? Aren't the docs from `docs` subdirectory generated on the fly during some build or something? According the previous committers to the `docs` subdirectory were not regenerating anything.

**Comment by zhijiangW** [comment]
Sorry for the misleading, and my last memory for updating html files was for the case of optional configuration. Then it seems no need for this PR.

The travis failure is caused by known fragile `Kafka010ProducerITCase`, so ignore it to merge.

**Comment by zhijiangW** [comment]
@pnowojski do you think we should merge it also into FLINK-1.9.0?

**Comment by pnowojski** [comment]
@zhijiangW thanks for merging. I will back port it to FLINK-1.9.

**Pull request merged**
