### PR TITLE
[FLINK-4560] enforcer java version as 1.7

### PR DESCRIPTION
**Pull request by shijinkui**
[FLINK-4560](https://issues.apache.org/jira/browse/FLINK-4560) enforcer java version as 1.7
1. maven-enforcer-plugin add java version enforce
2. maven-enforcer-plugin version upgrade to 1.4.1
explicit require java version

Only modify the root pom file.

The pull request references the related JIRA issue ("[FLINK-4560] enforcer java version as 1.7")

### CODE REVIEW

**Comment by StephanEwen** [comment]
Hi!

Can you explain a bit what this pull request fixes? I think Maven complains by itself if the JDK is of a lower version than the compiler target version. So what changes here?

Thanks!

**Comment by shijinkui** [comment]
hi, @StephanEwen  
There are much difference between JDK 6 and JDK 7+.  It's better for  compatible low version JDK，but there are better performance for Scala with Lambda support, and JDK 7 and 8 are enhanced on many features.  

Now JDK7 is wide used. Give up JDK 6 compatible. It's clearly for developer: use JDK 7+ features relieved

**Comment by greghogan** [comment]
Would this be useful to prevent building Flink with Maven 3.3.x?
  https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
  https://maven.apache.org/enforcer/enforcer-rules/

**Comment by shijinkui** [comment]
@greghogan exactly 3.0.3 will be OK. This limit is some module require, I forget where it is, I am sorry..

**Comment by StephanEwen** [comment]
We already gave up Java 6, and setting the source and target version in the Maven compiler plugin already prevents Java 6 usage. That is why I am wondering...

**Comment by shijinkui** [comment]
enforce java 7 before compile. There is no conflict between source/target and enforcer java version.

**Comment by shijinkui** [comment]
@StephanEwen OK.

**Pull request closed without merging**
