### PR TITLE
[FLINK-4561] replace all the scala version as a `scala.binary.version` property

### PR DESCRIPTION
**Pull request by shijinkui**
Replace all the scala version(2.10) as a property `scala.binary.version` defined in root pom properties. default scala version property is 2.10.
modify:
1. dependency include scala version
2. module defining include scala version
3. scala version upgrade to 2.11.8 from 2.11.7

Only modify pom file.

The pull request references the related JIRA issue ("[FLINK-4561] replace all the scala version as a `scala.binary.version` property")

### CODE REVIEW

**Comment by chiwanpark** [comment]
Hi @shijinkui, thanks for opening pull request. Unfortunately, this pull request cause a problem with maven shading plugin (https://issues.apache.org/jira/browse/MSHADE-200). Due to the problem, Flink community decided to use version string instead of property and add to a shell script (tools/change-scala-version.sh) to convert Scala version.

**Comment by StephanEwen** [comment]
Yes, @chiwanpark is right. This does not work, we tried it before. As long as the Maven Shade plugin is not fixed, we need to keep it as it is.

Could you close this pull request?

**Comment by shijinkui** [comment]
@chiwanpark @StephanEwen thanks for the reply.  dependency's version which contain scala 2.10 replace as property?

**Comment by StephanEwen** [comment]
I would really like to not change the way it is done right now.
It works and it is the result of many user interactions, testing across Maven, SBT, Gradle, etc.

These various build systems have such subtle differences that I think we should stick with paradigm of "don't change it unless it is broken".

**Comment by shijinkui** [comment]
@StephanEwen I can accept "don't change it unless it is broken". 

I explain why I made such a insipid and too much changes PR. I have such habit, that  is the code need continuous improvement and refactor until have no any improvement at this time.  That's why i doesn't want to tolerate bad smell code.

I think such matter belong to myself' habit. The others like this PR are generated conveniently when I read Flink code. These PRs are not important, can be close at any time.

：）

**Comment by StephanEwen** [comment]
@shijinkui I understand your motivation, it is a good idea in general. Please do not feel discouraged to suggest improvements.

There are some things that look like they could be done better, but actually cannot be changed, because of some tricky bugs or limitations in other parts (like build plugins). That was the case here, so sometimes we cannot change some things.

**Comment by shijinkui** [comment]
@StephanEwen Thank for your reply, understand it.

**Comment by shijinkui** [comment]
hi, @StephanEwen I have an idea in mind, If there are to much tricky bugs, and follow "don't change it unless it is broken", after two years can you image the code like? Full of tricky bugs fix.

I think we should make the code robust, reasonable and readable.

Can we make a long plan with many sub-tasks to reach the above purpose? 
Such as reduce the unnecessary module, pom more simple and easy maintain the pom.xml

Many people consider the Flink code confused and then give up Flink. I think Flink's features in whole are better, the detail of project need enhance.

How do you think about that?

**Pull request closed without merging**
