### PR TITLE
[FLINK-4453] [docs] Scala code example in Window documentation shows Java

### PR DESCRIPTION
**Pull request by wuchong**
quick fix...  😄

### CODE REVIEW

**Comment by fhueske** [comment]
Thanks for the quick fix, @wuchong!
The change looks good, but I just realized that the Java code might be on purpose in the Scala tab. It shows the interface of the `WindowFunction` which is defined in Java and the same interface is used by the Scala API. So not sure if we should translate the code to Scala because a Scala version of the interface does not exist.

Maybe adding a comment that the Scala API uses Java interfaces is better?

**Comment by wuchong** [comment]
Hi @fhueske , it seems that a Scala version of WindowFunction does exist, which is `org.apache.flink.streaming.api.scala.function.WindowFunction`. And both Scala WindowedStream and AllWindowedStream only accept the Scala version of WindowFunction.  The difference between Scala and Java version is that the `input` parameter is a Scala Iterable and a Java Iterable.

**Comment by fhueske** [comment]
Ah, OK. Didn't know that. Thanks! :-)
+1 to merge

**Comment by StephanEwen** [comment]
Merging this...

**Pull request closed without merging**
