### PR TITLE
[FLINK-25225][e2e] Add e2e TPCDS tests to run against the AdaptiveBatchScheduler

### PR DESCRIPTION
**Pull request by wanglijie95**
## What is the purpose of the change
Add e2e TPCDS tests to run against the AdaptiveBatchScheduler

## Verifying this change
e2e test

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (**no**)
  - The serializers: (**no**)
  - The runtime per-record code paths (performance sensitive): (**no**)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (**no**)
  - The S3 file system connector: (**no**)

## Documentation

  - Does this pull request introduce a new feature? (**no**)
  - If yes, how is the feature documented? (**not applicable**)

### CODE REVIEW

**Review by zhuzhurk — APPROVED** [review]
The change looks good, and I can see TPC-DS e2e tests for adaptive batch scheduler in the CI log.

**Comment by zhuzhurk** [comment]
Will merge it after #18715 is merged.

**Comment by wanglijie95** [comment]
@flinkbot run azure

**Comment by zhuzhurk** [comment]
Merging.

**Pull request closed without merging**
