### PR TITLE
[FLINK-5586] [table] Extend TableProgramsClusterTestBase for object reuse mode

### PR DESCRIPTION
**Pull request by KurtYoung**
Make all cluster-based ITCases verified in object reuse mode. This only includes batch table tests now.

### CODE REVIEW

**Comment by KurtYoung** [comment]
rebased to the latest master.

**Comment by KurtYoung** [comment]
hey @fhueske can you take a look at this?

**Comment by fhueske** [comment]
The changes look good to me. Thanks @KurtYoung

**Comment by KurtYoung** [comment]
I don't have merge permission yet, can you help merge this @twalthr ? Thanks.

**Comment by fhueske** [comment]
I can do it as well.

**Comment by KurtYoung** [comment]
Seems like this will effect the new aggregate interface and make the tests failed, will wait for that fix first.

**Comment by fhueske** [comment]
Hi @KurtYoung, FLINK-5955 was resolved by #3465.
This PR should be good to merge now.

**Pull request closed without merging**
