### PR TITLE
[FLINK-4316] [core] [hadoop compatibility] Make flink-core independent of Hadoop

### PR DESCRIPTION
**Pull request by StephanEwen**
This pull request moves all 'Writable' related code to the 'flink-hadoop-compatibility' project
and uses reflection in 'flink-core' to instantiate WritableTypeInfo when needed.

The test are also moved and adjusted to reflect this.

### CODE REVIEW

**Comment by StephanEwen** [comment]
The Scala type extraction has now also been addressed.

**Comment by aljoscha** [comment]
@StephanEwen that's exactly what I was just going to suggest for Scala. 👍

**Comment by rmetzger** [comment]
+1 to merge, once the failing tests are fixed.

I think the exception to the API stability check is okay in this case. The class is still in the same java package.

This are the test failures:
```
Results :

Failed tests: 
  PojoTypeExtractionTest.testPojoWC:203->checkWCPojoAsserts:244 position of field complex.valueType wrong expected:<2> but was:<5>
Tests in error: 
  TypeInfoParserTest.testMultiDimensionalArray:321 Â» IllegalArgument String coul...
  TypeInfoParserTest.testPojoType:190 Â» IllegalArgument String could not be pars...
```

**Comment by StephanEwen** [comment]
Good point. I'll fix those tests...

**Pull request closed without merging**
