### PR TITLE
[FLINK-11511] Remove legacy class JobAttachmentClientActor

### PR DESCRIPTION
**Pull request by TisonKun**
## What is the purpose of the change

Based on #7635 

JobAttachmentClientActor is only for legacy usages and even those usages are no longer exist. Drop JobAttachmentClientActor and clean up unused methods.

## Brief change log

Delete `JobAttachmentClientActor.java` and its invalid use points.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector:(no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

cc @tillrohrmann  @mxm

### CODE REVIEW

**Comment by TisonKun** [comment]
> Doesn't compile.
> 
> ```
> 09:13:34.858 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:testCompile (default-testCompile) on project flink-runtime_2.11: Compilation failure: Compilation failure:
> 09:13:34.858 [ERROR] /home/travis/build/apache/flink/flink-runtime/src/test/java/org/apache/flink/runtime/client/JobClientActorTest.java:[132,45] cannot find symbol
> 09:13:34.858 [ERROR] symbol:   variable JobAttachmentClientActor
> 09:13:34.858 [ERROR] location: class org.apache.flink.runtime.client.JobClientActorTest
> 09:13:34.858 [ERROR] /home/travis/build/apache/flink/flink-runtime/src/test/java/org/apache/flink/runtime/client/JobClientActorTest.java:[190,45] cannot find symbol
> 09:13:34.858 [ERROR] symbol:   variable JobAttachmentClientActor
> 09:13:34.858 [ERROR] location: class org.apache.flink.runtime.client.JobClientActorTest
> 09:13:34.858 [ERROR] /home/travis/build/apache/flink/flink-runtime/src/test/java/org/apache/flink/runtime/client/JobClientActorTest.java:[269,45] cannot find symbol
> 09:13:34.858 [ERROR] symbol:   variable JobAttachmentClientActor
> 09:13:34.858 [ERROR] location: class org.apache.flink.runtime.client.JobClientActorTest
> 09:13:34.858 [ERROR] -> [Help 1]
> ```

Sure. It should be based on #7635 . Rebase and update description.

**Comment by GJL** [comment]
Thanks, I will have a look.

**Comment by GJL** [comment]
LGTM, merging.

**Comment by GJL** [comment]
@flinkbot approve all

**Pull request closed without merging**
