### PR TITLE
[FLINK-19553][web] Make timestamp of checkpoints shown with date format

### PR DESCRIPTION
**Pull request by pyscala**
## What is the purpose of the change

The format of checkpoint Completion Time and Failure Time should be changed from HH:mm:ss to yyyy-MM-dd HH:mm:ss

## Brief change log
change the following format from 'HH:mm:ss' to 'yyyy-MM-dd HH:mm:ss'
Latest Completed Checkpoint:Completion Time
Latest Failed Checkpoint:Failure Time
Latest Savepoint:Completion Time
Latest Restore:Restore Time

## Verifying this change

This change was tested in locally.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by Myasuka** [comment]
@pyscala Thanks for your contribution. Could you please paste the new web UI pictures here if applied your changes?

**Comment by pyscala** [comment]
> @pyscala Thanks for your contribution. Could you please paste the new web UI pictures here if applied your changes?

@Myasuka of course. Thanks for your reply.
image

**Review by Myasuka — COMMENTED** [review]
Thanks for your update!

I think we should also update the timestamp format in `job-checkpoints-detail.component.html` and `job-checkpoints-subtask.component.html` except your current changes. Please update the pictures withe new changes.

**Comment by pyscala** [comment]
> Thanks for your update!
> 
> I think we should also update the timestamp format in `job-checkpoints-detail.component.html` and `job-checkpoints-subtask.component.html` except your current changes. Please update the pictures withe new changes.

@Myasuka Sounds good to me. I will do it later.

**Comment by pyscala** [comment]
image
@Myasuka What do you think of ? Do the timestamp format of Trigger Timestamp and Latest Acknowledgement need to be changed?

**Comment by pyscala** [comment]
image
@Myasuka Done

**Review by Myasuka — COMMENTED** [review]
Thanks for your update, I think we should also include date information for trigger timestamp, please update related code and offer the updated UI with your new changes.

**Comment by pyscala** [comment]
> Thanks for your update, I think we should also include date information for trigger timestamp, please update related code and offer the updated UI with your new changes.

@Myasuka Thanks for your reply. We have the same views and I will finish it as soon as possible.

**Comment by pyscala** [comment]
image
@Myasuka Done

**Review by Myasuka — APPROVED** [review]
LGTM

**Comment by Myasuka** [comment]
@pyscala Before I merge this PR, could you merge your commits as single one and rename the title as `[FLINK-19553][web] Make timestamp of checkpoints shown with date format`?

**Comment by pyscala** [comment]
> @pyscala Before I merge this PR, could you merge your commits as single one and rename the title as `[FLINK-19553][web] Make timestamp of checkpoints shown with date format`?

@Myasuka Sure

**Pull request merged**
