### PR TITLE
[hotfix][docs] Fix typo

### PR DESCRIPTION
**Pull request by YngwieWang**
[docs][hotfix] fix two typos

### CODE REVIEW

**Comment by TisonKun** [comment]
Thanks for your contribution @YngwieWang!

Follow the standard in our community we use pattern `[hotfix][<component>] ...` thus I would suggest commit with message `[hotfix][docs] Fix typo in Basic API Concepts page`

**Comment by YngwieWang** [comment]
> Thanks for your contribution @YngwieWang!
> 
> Follow the standard in our community we use pattern `[hotfix][<component>] ...` thus I would suggest commit with message `[hotfix][docs] Fix typo in Basic API Concepts page`

Thanks, I corrected the subject.

**Comment by YngwieWang** [comment]
@1u0, Am I doing the right thing?

**Comment by 1u0** [comment]
@YngwieWang,
you would need to rebase (and also translate the Chinese version) your changes in this PR against the latest changes in `master` branch. You have a merge conflict due to your changes in #9299 PR that were merged earlier 😃.

English version looks good to me.

**Pull request closed without merging**
