### PR TITLE
[hotfix] [docs] Fix broken link to "Anatomy of the Flink distribution" in dev/configuration/connector

### PR DESCRIPTION
**Pull request by mattayes**
## What is the purpose of the change

Fix broken link to "Anatomy of the Flink distrubution" documentation in dev/configuration/connector.

## Brief change log

Fix broken link to "Anatomy of the Flink distrubution" documentation in dev/configuration/connector.

## Verifying this change

This change is already covered by existing tests, such as verifying the link locally.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Review by SamBarker — APPROVED** [review]
LGTM

for what its worth...

**Comment by mattayes** [comment]
Thanks @SamBarker!

**Review by hlteoh37 — APPROVED** [review]
Thanks for the fix @mattayes !

**Comment by hlteoh37** [comment]
Could we reword the commit message to the standard Flink format? 👀 
For example something like `[hotfix] [docs] Fix broken link to "Anatomy of the Flink distribution"`

**Comment by mattayes** [comment]
@hlteoh37 Thanks for the review! Commit renamed 🚀

**Pull request merged**
