### PR TITLE
[FLINK-3761] Introduction of key groups

### PR DESCRIPTION
**Pull request by tillrohrmann**
This pull request introduces the concept of key groups to Flink. A key group is the smallest assignable unit of key-value state to a stream operator. Differently said, it is a sub set of the key space which is assigned to a stream operator. With the introduction of key groups, it will be possible to dynamically scale Flink operators which use partitioned (=key-value) state.

In order to support key groups, the following components were added/changed:

## Introduction of KeyGroupStateBackend

In order to make the state backends aware of the key groups, we had to introduce a new type of state backend `KeyGroupStateBackend`. A key group state backend behaves similarly to the old `AbstractStateBackend` just with the difference that it is aware of key groups. This means that it generates a snapshot for each key group upon snapshotting.

In order to leverage the existing implementation of state backends, the `AbstractStateBackend` was split up into the new `AbstractStateBackend` which is responsible for managing non-partitioned state and the `PartitionedStateBackend` which is responsible for managing the partitioned state.

Furthermore, the PR comes with a `GenericKeyGroupStateBackend` implementation which is the standard for the `KeyGroupStateBackend`. The `GenericKeyGroupStateBackend` simply creates for every key group a `PartitionedStateBackend` which manages this key group. Upon snapshotting, each `PartitionedStateBackend` is snapshot.

## Introduction of KeyGroupAssigner

In order to assign keys to a key group, the `KeyGroupAssigner` interface is introduced. The `KeyGroupAssigner` implementation is used by the `GenericKeyGroupStateBackend` to select the proper `PartitionedStateBackend` for the current key. Furthermore, the former `HashPartitioner`, which is renamed now into `KeyGroupStreamPartitioner` uses the `KeyGroupAssigner` to distribute the streaming records in a consistent way wrt to the key group mappings. The key groups itself are mapped in a round robin fashion (key group index modulo #channels = out-going channel) to the downstream tasks.  

## Introduction of MaxParallelism to user API

In order to scale programs up or down, it is necessary to define the maximum number of key groups. The maximum number of key groups denotes the maximum parallelism of an operator, because every operator needs at least one key group to get elements assigned. Thus, in order to specify this upper limit, the `ExecutionConfig` allows to set a job-wide max parallelism value via `ExecutionConfig.setMaxParallelism`. In addition to that the `SingleOutputStreamOperator` allows to set similarly to the parallelism a max parallelism value on an operator basis. If the max parallelism has not been set and there is no job-wide max parallelism set, the parallelism of the operator will be taken as the max parallelism. Thus, every operator would then receive a single key group.

However, in order to scale jobs up and down, one has to set a max parallelism for the operators which shall be scaled up/down. The upper limit for the scaling is the max parallelism value. The max parallelism mustn't change when scaling the job, because it would destroy the mapping of keys to key groups. 

- [X] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [X] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [X] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by gyfora** [comment]
Very cool stuff! I was wondering did you do any benchmarks for the performance impact of this change? For instance it would be good to know how well RocksDB behaves with a large number of instances etc.

**Comment by tillrohrmann** [comment]
No I haven't run performance benchmarks, yet. Should definitely do that as a follow-up. 

You're right that the behaviour of RocksDB is interesting in particular. It might make sense for the future to implement a RocksDB specialised `KeyGroupStateBackend` implementation, which uses only a single RocksDB instance for all key groups.

**Comment by tillrohrmann** [comment]
@aljoscha would be great to get some feedback from you :-)

**Comment by gyfora** [comment]
So if I understand currently there is no way to scale jobs with non-partitioned states. This also means that window operations (that register timers) will not be scalable right?

**Comment by aljoscha** [comment]
@gyfora Yes, this is correct. We'll have to put the timers into partitioned state and upon restarting iterate over the saved timers to re-set any callbacks at the `StreamTask`.

Doing this naively would slow things down. What I had in mind is to still keep the timers in an in-memory `Map` but before snapshotting put them into a partitioned state. This way, we don't have the overhead every time that we deal with timers but just when checkpointing.

**Comment by tillrohrmann** [comment]
In order to support scaling for non-partitioned state, the next step could be the introduction of a kind of union state. The idea would be to aggregate the non-partitioned state of each subtask and then sending it to all subtasks upon recovery. Then every subtask can pick from the union state what it needs for its execution

**Comment by aljoscha** [comment]
Yeah, we were also wondering wether it would make sense to allow the state itself to be repartitioned, i.e. union and then split into the new parallelism. In this way we wouldn't read all state in every operator.

**Comment by aljoscha** [comment]
I started looking into it, but man this is one big change... 😃 

I have some first remarks about API and internals:

Whats the reason for the introduction of `PartitionedState`? The Javadoc for `State` already says that it is the base class for partitioned state and that it is only usable on a `KeyedStream`.

The signature of `KeyGroupedStateBackend` and `PartitionedStateBackend` is exactly the same. `AbstractStateBackend` has both, method `createPartitionedStateBackend` and `createKeyGroupStateBackend`. Users of an `AbstractStateBackend` should only ever call the latter while the former is reserved for internal use by the default implementation for `KeyGroupedStateBackend` which is `GenericKeyGroupStateBackend`. Also, `AbstractStreamOperator` has the new method `getKeyGroupStateBackend` that should be used by operators such as the `WindowOperator` to deal with partitioned state. Now, where am I going with this? What I think is that the `AbstractStateBackend` should only have a method `createPartitionedStateBackend` that is externally visible. This would be used by the `AbstractStreamOperator` to create a state backend and users of the interface, i.e. `WindowOperator` would also deal just with `PartitionedStateBackend`, which they get from `AbstractStreamOperator.getPartitionedStateBackend`. The fact that there are these key groups should not be visible to users of a state backend. Internally, state backends would use the `GenericKeyGroupStateBackend`, they could provide an interface to it for creating non-key-grouped backends.

Above, "exactly the same" is not 100 % correct, since the snapshot/restore methods differ slightly but I think this could be worked around. Also, I found it quite hard to express what I actually mean but I hope you get my point. 😅

**Comment by tillrohrmann** [comment]
Thanks for the initial feedback @aljoscha :-)

The introduction of `PartitionedState` is indeed not strictly necessary for this PR. The idea was that we will have partitioned and non-partitioned state in the future. `PartitionedState` is the key-value state backed by the `PartitionedStateBackend` whereas non-partitioned state is backed by the `AbstractStateBackend`. The first non-partitioned state (apart from the state serialized via `CheckpointStateOutputStream`) could be the redistributable non-partitioned state necessary for the `KafkaSources`, for example. Thus, the `PartitionedState` is more of a logical separation and it lays the foundation so that also non-keyed stream operators can use a proper state abstraction. But I can revert it, if you deem it redundant or pre-mature.

It is true that the `PartitionedStateBackend` and the `KeyGroupStateBackend` have **almost** the same signature. However, the changes you've mentioned are imho crucial and made the whole refactoring of the state backends necessary in the first place. The difference is that the `KeyGroupStateBackend` is aware of the key groups and, consequently, is able to snapshot and restore each key group individually. Trying to work around this would mean that the `PartitionedStateBackend` always has a single key group associated. But for that, it would have to know the sub task index of the enclosing `StreamOperator` to assign a sensible key group index. Furthermore, it wouldn't make sense to use any other `PartitionedStateBackend` than the `KeyGroupStateBackend` (given that it respects the `KeyGroupAssigner`) for the `AbstractStreamOperator`, because the data is shuffled according to the key group assignments. In general, I think the notion of key groups are touching too many parts of the Flink runtime so that it makes no longer sense to try to unify the `KeyGroupStateBackends` and `PartitionedStateBackends`. The state backends used by the `AbstractStreamOperator` have to be aware of that notion.

You can regard the `PartitionedStateBackend` as an internal class which was introduced to reuse the existing state backend implementations via the `GenericKeyGroupStateBackend`. In the future it might make sense to directly implement the `KeyGroupStateBackend` interface to decrease the key group overhead. It's just unfortunate that Java does not allow to specify package private methods. Otherwise, I would have declared the `createPartitionedStateBackend` as package private. But since the `GenericKeyGroupStateBackend` resides in a sub-package of `o.a.f.runtime.state`, it cannot access this method. But I think we could refactor it the following way: Remove `createPartitionedStateBackend`, make `createKeyGroupStateBackend` abstract, let the implementations of `AbstractStateBackend` implement a `PartitionedStateBackendFactory` interface and define the `createKeyGroupStateBackend` method for all `AbstractStateBackend` implementations with creating a `GenericKeyGroupStateBackend` which requires a `PartitionedStateBackendFactory`. That would be probably a better design.

**Comment by aljoscha** [comment]
Jip, this last paragraph with the Factory is what I hinted at with my comment. 😃 This may be somewhat academic but if there is a method `getPartitionedStateBackend` the likelihood of it being wrongly used is somewhat high.

**Comment by tillrohrmann** [comment]
Yes definitely: better be safe than sorry. Will remove the `createPartitionedStateBackend` method from `AbstractStateBackend`.

**Comment by StephanEwen** [comment]
I think this is subsumed by #2376 

Should we close this Pull Request?

**Comment by tillrohrmann** [comment]
Yes will close the PR because it has been subsumed by #2440.

**Pull request closed without merging**
