### PR TITLE
[FLINK-32869][e2e] Fix Kubernetes tests on aarch64

### PR DESCRIPTION
**Pull request by mimaomao**
## What is the purpose of the change

This pull request fixes Flink Kubernetes related tests on `aarch64` architecture.

## Brief change log

- Download both `crictl` and `cri-dockerd` based on current architecture, not `amd64` only.

## Verifying this change

This change is already covered by existing tests - all Kubernetes related end-to-end test cases. I manually verified this change on AWS EMR by running 3 node cluster with 1 JobManagers and 2 TaskManagers with `aarch64` instance type.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Review by XComp — APPROVED** [review]
LGTM :+1: Thanks for picking it up. Can you provide 1.17 and 1.16 backports for it?

**Comment by mimaomao** [comment]
Hi @XComp, thanks for review! It seems I'm only allowed to fork one repo for Flink. And in this fork, I only forked the master branch. This change can be simply cherry-picked to target release branches such 1.16, 1.17. Maybe we can first merge this PR and then I re-create a new fork with all branches for back-ports? Or could you help do the cherry-pick work to backport?

**Comment by XComp** [comment]
You should be allowed to fork the entire repo. You would clone the repo then and add Flink's upstream repository as a remote location:
```
# this creates a remote reference "origin" by default
$ git clone https://github.com/mimaomao/flink
$ git remote add upstream https://github.com/apache/flink
$ git fetch upstream
$ git checkout -b FLINK-32869-1.18 upstream/release-1.18
$ git cherry-pick <commit-sha>
# This pushes your local branch FLINK-32869-1.18 to your forked repo that is referenced under origin (compare with the clone command above)
$ git push origin FLINK-32869-1.18
```
Then you can create a dedicated PR in Github as usual. Keep in mind to set the correct base branch in the corresponding PR (it's set to `master` by default).
This would need to be done for `release-1.18` (which was created two days ago), `release-1.17` and `release-1.16`.

Another remark: You added your change in your fork's `master` branch which is kind of unusual. You would create a dedicated branch for the change and push that to your fork (i.e. `origin`), instead.

**Comment by mimaomao** [comment]
Thanks for the instructions! I have created another three separate PRs for 1.18, 1.17, 1.16 as the following:
* https://github.com/apache/flink/pull/23275
* https://github.com/apache/flink/pull/23276
* https://github.com/apache/flink/pull/23277

Please help review it!

**Comment by mimaomao** [comment]
Hi @XComp , when will those PRs be merged? I don't have write permission to merge it.

**Comment by XComp** [comment]
> Hi @XComp , when will those PRs be merged? I don't have write permission to merge it.
...whenever a committer has the time/capacity to do so. :wink:

**Pull request merged**
