### PR TITLE
[FLINK-3354] Determine correct size for RocksDB snapshots

### PR DESCRIPTION
**Pull request by gyfora**

### CODE REVIEW

**Comment by aljoscha** [comment]
Thanks :smile: You tried this on a cluster, I guess?

**Comment by gyfora** [comment]
Yes, this returns the correct size, I tried on HDFS.

http://stackoverflow.com/questions/16581327/get-folder-size-of-hdfs-from-java

**Comment by gyfora** [comment]
It counts the size without HDFS replication I think that is better.

**Comment by aljoscha** [comment]
Ok, could you please go ahead and merge it if no one else objects. :+1:

**Comment by gyfora** [comment]
Sure

**Comment by aljoscha** [comment]
thanks

**Pull request closed without merging**
