### PR TITLE
[FLINK-10085][tests] Update AbstractOperatorRestoreTestBase for 1.5

### PR DESCRIPTION
**Pull request by zentol**
## What is the purpose of the change

This PR extends the `AbstractOperatorRestoreTestBase` sub-classes to also cover migration from 1.5.

## Brief change log

* add 1.5 savepoints
* add 1.5 to migration versions

### CODE REVIEW

**Comment by dawidwys** [comment]
Do we have any reasonable way to verify those kinds of PRs? Or shall we just look for typos while reviewing it? 

If the latter than +1.

**Comment by zentol** [comment]
the added migration versions can be verified by running the test locally. Verifying the savepoint is a bit trickier as they don't include the actual flink version. For this test, where the content of the savepoint is deterministic, you could generate a savepoint locally and compare the contents.

**Comment by dawidwys** [comment]
Are the savepoints binary deterministic? I've tried to generate savepoints twice and each time I got different contents (also compared with savepoint in this PR). If it should be deterministic I will try to repeat it once again. Maybe I've done sth completely wrong.

**Comment by zentol** [comment]
I'm not sure about the binary contents being deterministic, but the _state_ contents most definitely should be. I'm not aware of any truly random savepoint components, as the operator IDs should also be deterministic.

**Pull request merged**
