### PR TITLE
[FLINK-17309][e2e tests]TPC-DS fail to run data generator due to network issues

### PR DESCRIPTION
**Pull request by leonardBang**
## What is the purpose of the change

* This pull request fix TPC-DS e2e test stability issue on Azure pipeline
**Especially, this PR shoule merge until Azure pipeline stable enough** 

## Brief change log

  - *update file tpcds-tool/data_generator.sh*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): ( no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by leonardBang** [comment]
@flinkbot run azure

**Comment by leonardBang** [comment]
@flinkbot run azure

**Comment by leonardBang** [comment]
@flinkbot run azure

**Comment by rmetzger** [comment]
The end to end test failed because GitHub is currently down.
This is what the test reported
```
[WARN] md5sum of tpcds.idx unexpected, this may caused by network issue. Retry download, rertyTimes:1
```

I tried downloading the file from my laptop, and I got
```
➜  /tmp wget https://raw.githubusercontent.com/ververica/tpc-ds-generators/f5d6c11681637908ce15d697ae683676a5383641/generators/dsdgen_linux
--2020-04-23 16:01:11--  https://raw.githubusercontent.com/ververica/tpc-ds-generators/f5d6c11681637908ce15d697ae683676a5383641/generators/dsdgen_linux
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2020-04-23 16:01:24 ERROR 500: Internal Server Error.
```

Quite a few Azure tests are failing at the moment because GitHub is down. I guess we need to re-run the test once GitHub is stable again.

**Comment by leonardBang** [comment]
@rmetzger Yes, you're wright, I noticed the log too. It seems Github recover now, I'll re-run the tests.

**Comment by leonardBang** [comment]
@flinkbot run azure

**Comment by leonardBang** [comment]
@flinkbot run azure

**Comment by dawidwys** [comment]
Thank you @leonardBang for working on it. I think your proposal makes sense. One thing I spotted is that you can probably reuse the retry function: `common.sh#retry_times_with_backoff_and_cleanup`

**Comment by leonardBang** [comment]
> retry_times_with_backoff_and_cleanup

Nice catch, I'd like to reuse it.

**Comment by leonardBang** [comment]
Improve according to @dawidwys 's suggestion.

**Comment by dawidwys** [comment]
I am good with these changes. However, I'd prefer if @rmetzger had a final say on this PR.

**Comment by leonardBang** [comment]
Thanks @dawidwys, cc @rmetzger for help take a look.

**Pull request merged**
