### PR TITLE
[FLINK-5468] Improved error message for migrating semi async snapshot

### PR DESCRIPTION
**Pull request by StefanRRichter**
This PR addresses [FLINK-5468].

### CODE REVIEW

**Comment by StefanRRichter** [comment]
cc @rmetzger

**Comment by StephanEwen** [comment]
Good fix!

I was wondering if we can make the "separation of concerns" a bit nicer if we keep this special case check out of the Savepoint Serializer, but instead add the "SemiAsyncSnapshot" class to the migration package and throw this exception in a static initializer of that class.
Do you think that would work?

**Comment by StefanRRichter** [comment]
I changed the PR like @StephanEwen suggested.

**Comment by StephanEwen** [comment]
Looks good to me, +1 to merge it

**Comment by uce** [comment]
Thanks for the PR. Looks good to me. I'm going to merge this.

**Pull request closed without merging**
