### PR TITLE
[FLINK-4619] - JobManager does not answer to client when restore from savepoint fails

### PR DESCRIPTION
**Pull request by mproch**

### CODE REVIEW

**Comment by StephanEwen** [comment]
Good idea. Unfortunately, the changed broke some tests:

  - `SavepointITCase.testSubmitWithUnknownSavepointPath`
  - `RescalingITCase.testSavepointRescalingFailureWithNonPartitionedState`

You can see more in the Travis CI report.

**Comment by mproch** [comment]
Yes, it's a bit more tricky then I expected... These tests probably also need to be changed, because they relied on previous behaviour... What's more with the change some checks on FlinkMiniCluster start to be non-deterministic... I'll commit fixes when I'll fully understand how it works...

**Comment by mproch** [comment]
Hmm... I managed to make travis build pass, but I cannot see how jenkins test failures relate to my change...

**Comment by mproch** [comment]
@StephanEwen can I retrigger this or whatever?

**Comment by StephanEwen** [comment]
No need to re-trigger this. Travis green light is good.

@uce - Do you think this works well with your latest changes?

**Comment by uce** [comment]
Yes, I merge this later today.

**Pull request closed without merging**
