### PR TITLE
[FLINK-32709][network] Fix the bug of low memory utilization for Hybrid Shuffle

### PR DESCRIPTION
**Pull request by TanYuxin-tyx**
## What is the purpose of the change

*Currently, each subpartition in Disk/Remote has a segment size of 8M. When writing segments to the Disk tier with a parallelism of 1000, only shuffle data exceeding 1000 * 8M can be written to the Memory tier again. However, for most shuffles, the data volume size falls below this limit, significantly impacting Memory tier utilization.
For better performance, it is necessary to address this issue to improve the memory tier utilization.*

## Brief change log

  - *Modify segment size to improve memory utilization for Hybrid Shuffle*

## Verifying this change

This change is an internal option default value hotfix change without tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by TanYuxin-tyx** [comment]
@flinkbot run azure

**Review by reswqa — APPROVED** [review]
Thanks for the quick update, LGTM.

**Review by reswqa — APPROVED** [review]
Due to significant changes made to the code, review this again and also looks good to me.

**Comment by TanYuxin-tyx** [comment]
@reswqa Thanks for helping review. In addition, I added tests for the new logic.

**Comment by TanYuxin-tyx** [comment]
@flinkbot run azure

**Pull request merged**
