### PR TITLE
[FLINK-23044] fix typos in docs

### PR DESCRIPTION
**Pull request by raywill**
## What is the purpose of the change

Fix typo.

Found some typos using the tool provided by [https://github.com/raywill/codetypo](https://github.com/raywill/codetypo)

## Brief change log

fix typos in `flink/docs/README.md`.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Review by Myasuka — COMMENTED** [review]
Thanks for the contribution, I wonder only three lines in the documentation have typos?

**Comment by raywill** [comment]
> Thanks for the contribution, I wonder only three lines in the documentation have typos?

No, there are tons of typos. I don't have enough time to fix all of them. you can run a full typo check by yourself.

checker I wrote: https://www.github.com/raywill/codetypo

**Comment by Myasuka** [comment]
> > Thanks for the contribution, I wonder only three lines in the documentation have typos?
> 
> No, there are tons of typos. I don't have enough time to fix all of them. you can run a full typo check by yourself.
> 
> checker I wrote: https://www.github.com/raywill/codetypo

If you decided to fix typos in Flink docs, why not try your best to fix them all? This PR includes three typos and others could create more PRs with different number fix of typos, which actually makes the progress endless.
We can try to fix all typos at some intervals but only fixing three lines sometimes, especially we know there exist many typos, would waste reviewer's energy.

**Comment by raywill** [comment]
> > > Thanks for the contribution, I wonder only three lines in the documentation have typos?
> > 
> > 
> > No, there are tons of typos. I don't have enough time to fix all of them. you can run a full typo check by yourself.
> > checker I wrote: https://www.github.com/raywill/codetypo
> 
> If you decided to fix typos in Flink docs, why not try your best to fix them all? This PR includes three typos and others could create more PRs with different number fix of typos, which actually makes the progress endless.
> We can try to fix all typos at some intervals but only fixing three lines sometimes, especially we know there exist many typos, would waste reviewer's energy.

You are right. I decide to close this PR.

**Pull request closed without merging**
