### PR TITLE
[FLINK-2433][docs]Add script to build local documentation on windows

### PR DESCRIPTION
**Pull request by sachingoel0101**
Okay, this can probably be done with the build_docs.sh file using cygwin. I didn't have cygwin installed, and ended up writing this.
Let me know if there's no need for this. I'll close this PR.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Are all the dependencies (jekyll + libraries) available on windows as well?

**Comment by StephanEwen** [comment]
If the libraries are available, this is a good addition, as far as I am concerned...

**Comment by sachingoel0101** [comment]
Yes.

**Comment by sachingoel0101** [comment]
Ah. Yes, actually.
I tried running the webclient on cygwin once and it didn't work [I was ignorant to the fact that I had to add those two lines in the bash profile.]. I would've probably written a bat file for that too. :')

**Pull request closed without merging**
