### PR TITLE
[FLINK-24674][kubernetes] Create corresponding resouces for task manager Pods

### PR DESCRIPTION
**Pull request by mbalassi**
This is a rebased version of #17582 to the latest master branch to trigger CI runs, as the CI seems to be consistently producing seemingly unrelated [failures](https://github.com/apache/flink/pull/17582#issuecomment-996521399) on the original PR.

Fyi @viirya @gyfora

### CODE REVIEW

**Comment by mbalassi** [comment]
@flinkbot run azure

**Comment by mbalassi** [comment]
Hi @viirya,

@gyfora and I have investigated the issue and we could reproduce the following [failure](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=28340&view=logs&j=81be5d54-0dc6-5130-d390-233dd2956037&t=81e697a1-afb6-56e2-7d6c-47095b046a9f&l=3329) locally:

```
Dec 17 21:52:24 2021-12-17 21:52:07,419 ERROR org.apache.flink.runtime.entrypoint.ClusterEntrypoint        [] - Could not create application program.
Dec 17 21:52:24 java.lang.IllegalArgumentException: Only "local" is supported as schema for application mode. This assumes that the jar is located in the image, not the Flink client. An example of such path is: local:///opt/flink/examples/streaming/WindowJoin.jar
Dec 17 21:52:24 	at org.apache.flink.kubernetes.utils.KubernetesUtils.lambda$checkJarFileForApplicationMode$2(KubernetesUtils.java:386) ~[flink-dist-1.15-SNAPSHOT.jar:1.15-SNAPSHOT]
```

This happens in the k8s native ha e2e [test](https://github.com/apache/flink/blob/master/flink-end-to-end-tests/test-scripts/test_kubernetes_application_ha.sh#L52-L74) after the forced restart of the jobmanager pod. Note that initially the job starts fine (and the non-ha test passes successfully), but on restarting from a jobmanager pod failure is bugged after your change.

On jobmanager restore the new jobmanager reads the `flink-conf.yaml` in the relevant configmap, in the case of the test from `flink-config-flink-native-k8s-application-ha-1`. This initally contained the following line to note the location of the job jar submitted:

```
pipeline.jars: local:///opt/flink/examples/streaming/StateMachineExample.jar
```

However after your change the taskmanager pod [overwrites](https://github.com/apache/flink/pull/18144/commits/acb7da45bd3c00778c82e3a9ad5a6cb8a3e0020a#diff-8c94eb0faebcdc0528869b32be042da7b30866e71c6279888f80f5b44cac661cR160) the configmap that was until now only created by the jobmanager, with the following value which leads to the failure:

```
pipeline.jars: file:///opt/flink/examples/streaming/StateMachineExample.jar
```

The `file` or `local` scheme is a trivial change to code around, but investigating this broken test revealed a conceptual issue with your proposal. After your change all the accompanying resources always get overwritten taskmanager pod, which leads to unintended consequences. To my knowledge we always expected in Flink that the jobmanager and taskmanagers share the same Hadoop configuration and Kerberos configuration, having this different can lead to gnarly bugs.

If we understand correctly from the original [issue description](https://issues.apache.org/jira/browse/FLINK-24674) you had a case where the Hadoop config was present in the taskmanager docker image, but not in the jobmanager one. We feel that this is a cornercase that does not merit special coverage given the above consequences, we suggest that you use one of the two existing mechanism to ship your Hadoop config instead:
1. Specify on the client that is doing the job submission via the `HADOOP_CONF_DIR` environment variable
2. Deploy a long lived configmap to the k8s environment and reference that via `kubernetes.hadoop.conf.config-map.name`

Taking a step back your Hadoop config is probably environment specific and often changes between your test and production environment, so we would discourage you from baking this into the image itself - rather keep it as part of the environment itself via either of the aforementioned methods. Based on this assessment we are advising against merging this change.

Thank you for your contribution, let me know if you have any further questions, concerns or suggestions.

**Comment by viirya** [comment]
> If we understand correctly from the original issue description you had a case where the Hadoop config was present in the taskmanager docker image, but not in the jobmanager one. We feel that this is a cornercase that does not merit special coverage given the above consequences, we suggest that you use one of the two existing mechanism to ship your Hadoop config instead:

Thanks for the investigation. I suspected that could be caused by overwriting the configmap, but didn't know the details of job manager restarting behavior. That makes sense.

One point that is not exactly, is the Hadoop config was present both in task manager and job manager docker image (they use same docker image).

I knew that the official support case is to set up a configmap on K8S and use `kubernetes.hadoop.conf.config-map.name` to refer it. I personally don't prefer this approach as I don't think end-users need to worry about setting up configmap for Hadoop configs. Especially for test purpose, we don't need to change Hadoop configs, so setting configmap every time launching a new cluster is a bit trouble. Encapsulating the Hadoop config files into the docker image is easiest way to test it across every clusters with same configs.

In many cases, the job submission is not happened in local but in another container running on K8S, for example the Flink operator works like that. So the local `HADOOP_CONF_DIR` environment variable is not work. Maybe there is a workaround to put Hadoop config on the docker image, and modify the submitting script to include the environment variable.

I also need to mention that one motivation of this patch is, if we put the Hadoop config files in the docker image (e.g., once you un-tar the Hadoop distribution into the docker image), the Flink pod creation will fail as it cannot mount the configmap. This is very confusing for end-users if they don't know the implementation details. At least when I saw the error, I don't know what's going on with it. So that is why I was digging into this part of code and changed it to set up a configmap instead of just failing the Pod creation.

> Taking a step back your Hadoop config is probably environment specific and often changes between your test and production environment, so we would discourage you from baking this into the image itself - rather keep it as part of the environment itself via either of the aforementioned methods. Based on this assessment we are advising against merging this change.

I understood your concern here and I also don't have intent to forcibly push this patch, it's just how I overcome the error I encountered during test. I believe you are more knowledgeable in Flink than me and can make better decision. Let me close this PR.

**Comment by mbalassi** [comment]
Hi @viirya,

Thanks for the detailed answer and the flexibility in your approach. You clarified a valid point: if both the jobmanager and the taskmanager image already have the Hadoop config baked in we could technically just use that instead of enforcing a configmap being available with this information. This seemingly contradicts my previous position (that environment specific configuration should not be in the container image), but if we think that it streamlines initial user experience or valid use cases as you mention and is reasonably easy to implement it might make sense to do so. I will play with this a bit during the holiday season - let us catch up afterwards, and more importantly happy holidays. 😊

**Comment by viirya** [comment]
Thanks @mbalassi 

My basic point is to allow a different approach which can enable more use cases and scenarios. I feel that flexibility is important for end users. At least I think it should be reasonable thinking that if we put Hadoop configs in the docker image, job manager/task manager should be able to recognize it and use it.

Yea, let's have a happy holidays first! :)

**Comment by mbalassi** [comment]
Closing as this is no longer relevant.

**Pull request closed without merging**
