### PR TITLE
[FLINK-6394] [runtime] Respect object reuse configuration when execut…

### PR DESCRIPTION
**Pull request by KurtYoung**
…ing group combining function

### CODE REVIEW

**Comment by StephanEwen** [comment]
Good catch and good changes. Thanks @KurtYoung 

+1 to merge these

**Comment by KurtYoung** [comment]
Sorry i wasn't available in the last couple days, it seems the 1.3 branch has been created, should i merge this PR in to 1.3 branch too?

**Comment by fhueske** [comment]
Yes, 1.3 and 1.2 as well. Thank you!

**Comment by KurtYoung** [comment]
Ok, do it right way.

**Pull request closed without merging**
