### PR TITLE
[FLINK-21576][runtime] Remove legacy ExecutionVertex#getPreferredLocations()

### PR DESCRIPTION
**Pull request by zhuzhurk**
## What is the purpose of the change

ExecutionVertex#getPreferredLocations() is superseded by DefaultPreferredLocationsRetriever and is no longer used. Hence, we can remove it. Its test ExecutionVertexLocalityTest is superseded by DefaultPreferredLocationsRetrieverTest.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by Thesharing** [comment]
Since there's no reference of `Execution#calculatePreferredLocations`, I think it's safe to remove it. I'll rebase my PR [FLINK-21326](https://github.com/apache/flink/pull/14868) after this PR is merged.

**Review by Thesharing — APPROVED** [review]
Since there's no reference of `Execution#calculatePreferredLocations`, I think it's safe to remove it and the methods solely used by it. 

I'll rebase my PR [FLINK-21326](https://github.com/apache/flink/pull/14868) after this PR is merged.

**Comment by zhuzhurk** [comment]
@flinkbot run azure

**Comment by zhuzhurk** [comment]
@flinkbot run azure

**Comment by zhuzhurk** [comment]
The failed test case is a known issue FLINK-21574.
Merging.

**Pull request merged**
