### PR TITLE
[FLINK-17562][document]Monitoring REST API page has duplicate items

### PR DESCRIPTION
**Pull request by SteNicholas**
## What is the purpose of the change

*Monitoring REST API has two `/jars/:jarid/plan` column and there descriptions are same, which of  them should be removed. Because in `WebSubmissionExtension`, `PostJarPlanHandler` specifies the wrong `AbstractJarPlanHeaders` instance to `JarPlanGetHeaders`, which should be `JarPlanPostHeaders`.*

## Brief change log

  - *Modify `WebSubmissionExtension` constructor method to specify `AbstractJarPlanHeaders` instance to `JarPlanPostHeaders`.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by zentol** [comment]
The REST API documentation is generated; did you verify that running the generator does not re-introduce the duplicate entry? (see flink-docs/README.md for instructions)

**Comment by SteNicholas** [comment]
@zentol Sorry for not verifying that running the generator does not re-introduce the duplicate entry. I have already run `RestAPIDocGenerator` to verify and found that the `WebSubmissionExtension ` exists bug in `PostJarPlanHandler` specifying the wrong `AbstractJarPlanHeaders` instance to `JarPlanGetHeaders`. Please review this again.

**Comment by SteNicholas** [comment]
@zentol Could this pull request be merged?

**Comment by zentol** [comment]
@SteNicholas Just waiting for CI to pass.

**Comment by SteNicholas** [comment]
@zentol CI has already passed. Please help to merge. Thanks.

**Pull request merged**
