### PR TITLE
[FLINK-12190] Fix IllegalArgumentException thrown by FlinkKinesisConsumerMigrationTest#writeSnapshot

### PR DESCRIPTION
**Pull request by yanghua**
## What is the purpose of the change

*This pull request fixes IllegalArgumentException thrown by FlinkKinesisConsumerMigrationTest#writeSnapshot*

## Brief change log

  - *Fix IllegalArgumentException throwed by FlinkKinesisConsumerMigrationTest#writeSnapshot*

## Verifying this change

This change is already verified by commits [86e33fe36ed29b6e01dd7fe4151a8650ad25612c](86e33fe36ed29b6e01dd7fe4151a8650ad25612c) in PR #8168 *.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by yanghua** [comment]
@tzulitai The Travis is failed because of Kafka connector IT test case, I have reported an issue: [FLINK-12196](https://issues.apache.org/jira/browse/FLINK-12196).

**Comment by zentol** [comment]
Please expand the description. It should explain what the underlying problem is and how your solutio addresses it.

**Comment by yanghua** [comment]
@zentol Sorry, I have added more details. It is because the exists code did not initialize `TestFetcher` correctly. Actually, there is a discussion in FLINK-10785. I have discussed with @tzulitai about the solution before.

**Comment by yanghua** [comment]
@tzulitai Can you review this PR? thanks.

**Comment by yanghua** [comment]
@tzulitai I think this PR can make sense for someone who wants to do the migration test after releasing Flink 1.9. If you have time, can you review this PR? thanks.

**Comment by tzulitai** [comment]
Sorry for the late review on this one. LGTM, +1.
Merging ..

**Comment by yanghua** [comment]
Hi @tzulitai I think this PR can also be merged. WDYT?

**Comment by tzulitai** [comment]
Merging ...

**Pull request closed without merging**
