### PR TITLE
[FLINK-15355][plugin] Remove parent first from plugin classloader.

### PR DESCRIPTION
**Pull request by AHeise**
## What is the purpose of the change

Parent first classes are mostly used to guard against shaded flink classes in user code. Since plugins are currently provided by us or will be provided by expert users, the chance of wrongly shaded flink classes are minuscule.

## Brief change log

Remove parent first from plugin classloader.

## Verifying this change

- Existing e2e tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (**yes** / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by AHeise** [comment]
@flinkbot run travis

**Comment by AHeise** [comment]
@flinkbot run travis

**Comment by carp84** [comment]
From the travis run the FLINK-15355 problem has disappeared but it seems [FLINK-13567](https://issues.apache.org/jira/browse/FLINK-13567) reoccurs...

**Comment by AHeise** [comment]
Yes, I ran 3 times on travis, each time it failed on other known e2e flaky tests.

**Comment by AHeise** [comment]
@flinkbot run travis

**Comment by wangyang0918** [comment]
Hi @pnowojski, i think we should use `parent loaded first` for user jars to avoid the class conflict and some fixed bugs of flink new version. However, for plugin jars, i do not think we need to do the same behavior. It will be better if we will delegate the `always-parent-first-pattern` configuration to each plugin implementation. Every plugin could decide which packages need to always load from parent.

Otherwise, if we have two plugins and they have the different `always-parent-first-pattern`, we will have no idea how to deal with this.

**Comment by zentol** [comment]
Parent-first patterns still make sense for plugins for things like jdk classes, logging and similar, if anything to reduce the amount of loaded classes.

The issue isn't even that we defer to the parent in some cases, but that hadoop of all things is in the default list.

My feeling is that we should just introduce a separate pattern for plugins that doesn't include any library patterns. The existing patterns was added for usages in user-code in the first place; it seems reasonable that plugins would use a different one.
This should be simple to add; we'd just have to modify PluginConfig to use a separate pattern instead.

**Comment by zhuzhurk** [comment]
Agree with @zentol to have a separate pattern config for plugins and exclude hadoop from it. A plugin should never rely on specific libraries (i.e. hadoop) in the system classloader. @pnowojski also proposed it in the [JIRA FLINK-15355](https://issues.apache.org/jira/browse/FLINK-15355?focusedCommentId=17006836&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17006836).

@wangyang0918 I think each plugin can use `PluginDescriptor#loaderExcludePatterns` to specify classes to load from parent first (though not ready yet, see `DirectoryBasedPluginFinder#createPluginDescriptorForSubDirectory`). It could be an optional file for each plugin.

**Comment by pnowojski** [comment]
@zentol, @zhuzhurk that's the same that I suggested in the [JIRA ticket](https://issues.apache.org/jira/browse/FLINK-15355?focusedCommentId=17006836&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17006836)

Since it looks like we have an agreement, I'm closing this PR in that case.

> Besides that, a plugin also has its own exclude patterns

I don't see a need to expose/use this at this moment. We just should clean up the default parent first packages list for plugins, to limit it just to the SPI packages.

**Pull request closed without merging**
