### PR TITLE
[FLINK-1962] Add Gelly Scala API

### PR DESCRIPTION
**Pull request by PieterJanVanAeken**
Pull request for adding the Gelly Scala API. There were some issues with rebasing due to both the Java Gelly API and the Testing API changing, so if someone could verify that no changes were lost in the process that would be great.

### CODE REVIEW

**Comment by andralungu** [comment]
I am super excited about this one! :) Will also have a look in the next days! Awesome job!

**Comment by aljoscha** [comment]
I will thoroughly check it once the release that is currently happening is done. Then people can check it out and it will have had some expose before releasing it in 0.10.

**Comment by chiwanpark** [comment]
Hi. I'm very excited about Gelly's Scala API. I'm reading the changes from this PR. I found a problem about re-formatting. Unlike Flink's Java code, Flink's Scala code use 2 spaces as indent. But I think the IDE did re-format all code to use 4 spaces as indent.

We should preserve the previous indent setting to preserve modification history.

**Comment by aljoscha** [comment]
Yes, the formatting would indeed have to be changed to conform to the pre-existing Flink Scala style.

**Comment by aljoscha** [comment]
ExecutionEnvironment.scala, UnionOperator.java and Graph.java have a lot of whitespace/formatting changes. This makes it hard to see the actual changes to functionality.

None of the methods in the new Scala code have comments/Scaladoc. Especially the methods on Graph.scala, these should have documentation, similar to the methods on Graph.java.

Other than that, this looks good. I especially like that basically half of the new files are test cases. :+1: 

Could someone from the Graph side ( @vasia, @andralungu ) please chime in on this.

**Comment by andralungu** [comment]
Thanks @aljoscha for reminding me... This slipped my mind for a sec. 

I agree that the methods should have Scaladoc (this should be straightforward to add starting from  the existing Javadoc). What would also be nice, IMO would be to update  the docs so that they would also contain a Scala version of the example code snippets, similar to the programming guide, for example (http://ci.apache.org/projects/flink/flink-docs-release-0.8/programming_guide.html).

Furthermore, the newly added methods (e.g. `addVertices`) are missing. However, that should be a separate Jira.

Apart from the formatting issue and the documentation issue, everything looks nice and clean :)

**Comment by vasia** [comment]
Hey,

I also checked this over the weekend!
(and realized how rusty my Scala has gotten :-S)

I agree with both of you on the scaladocs, docs and formatting issues.
There is some functionality missing, but since the Java API is also evolving, we should probably stop at some point and add the missing methods as separate issues.
It would also be nice to have 1-2 examples implemented with the Scala API and then we can work on adding the rest at a later point.

**Comment by vasia** [comment]
Oh, one more thing :)
In order to make this work in Eclipse, I had to add a few lines to the pom.xml.
Basically, I copied the `<build>` block from the streaming-scala project. I'm not sure whether everything in there is needed, so if someone knows better, please let us know ;)
Thanks!

**Comment by PieterJanVanAeken** [comment]
Hi,

Thanks all for the comments. Unfortunately, I will be gone until the 13th of July so I will not be able to resolve these issues until then. They are however all valid points. One more note perhaps, in regard to the unit tests, I added the basic ones (based on the Java version of them), but they are most certainly not all there. The same can be said for the methods that were added recently to the java Gelly API.

Since I am a bit strapped for time atm, I was hoping to push this into the official Flink repo (maybe not master branch?) so other people could more easily contribute and help resolve these final issues thus speeding up the process a bit.

**Comment by vasia** [comment]
Hey @PieterJanVanAeken!
Are you back working on this or would you rather someone else takes over?
I think I can find some time next week to resolve remaining issues and bring this to "mergeable" state :) Just let me know! Thanks!

**Comment by PieterJanVanAeken** [comment]
@Vasia I have been a bit strapped for time but I should have some time this week to work on this some more. If I am not done by the end of the week, you can always pick up where I left off. 

So I don't miss anything, what needs to happen now to get this to a mergeable state is add JavaDoc/ScalaDoc, add the Eclipse pom segment, change 4 space tabs to 2 space tabs in Scala and remove some of the unnecessary formatting as a result of auto-format. Did I miss anything?

**Comment by aljoscha** [comment]
Nope, I think that's spot on.

**Comment by vasia** [comment]
Perfect, thanks @PieterJanVanAeken!

**Comment by PieterJanVanAeken** [comment]
So I fixed some of the issues and tried to merge with the master branch again. Not sure if I did everything correctly though so if someone could check this again, that would be great.

**Comment by vasia** [comment]
Hi @PieterJanVanAeken! Thanks for the update. It seems something went wrong with your merge. Your last commit shows 1000+ files changed... Could you try to rebase instead?

**Comment by PieterJanVanAeken** [comment]
Really? It says 26 files changed for me?

**Comment by fhueske** [comment]
26 files for me as well.

**Comment by chiwanpark** [comment]
[Your last commit](https://github.com/PieterJanVanAeken/flink/commit/463a1f30b3b0785f46c76f9c290da3dee5555c26) includes all updates of master branch. Please remove last commit (`git reset --hard HEAD~1` on your master branch) and rebase your branch on master branch (`git rebase apache/master`) and push to your branch with force update (`git push origin +master`).

Additionally, working on non-master branch is better than on master branch. If you work on non-master branch, you can sync your master branch to apache master branch while you are changing your branch.

**Comment by fhueske** [comment]
Right @chiwanpark, its the last commit not the PR as a whole. Thanks for clarifying!

**Comment by PieterJanVanAeken** [comment]
Things are getting quite messy now in my repo (as if it wasn't messy already). The rebase didn't quite go as expected, because of the fact that I had already been working in my own master branch which wasn't the best idea.

I will probably start with a clean slate. I only made a few  very minor modifications to the current code base, which I can easily reapply manually and then I can just copy/paste the flink-gelly-scala module from a local backup. Then update my fork's master, rebase the topic branch and submit the pull request. That way, I can also set up things properly and work from topic branches as the documentation ( and now @chiwanpark as well) suggested I should have done in the first place. It also makes things easier for future commits.

I will probably do this early next week, unless you guys can think of a reason why this would be a very bad idea.

**Comment by vasia** [comment]
I think it's a good idea and it will probably save you time :) Thank you!

**Comment by PieterJanVanAeken** [comment]
Opened up a second PR from a cleaned out repo. Closing this one.

**Pull request closed without merging**
