### PR TITLE
[FLINK-6508] [table] Include license files of packaged dependencies.

### PR DESCRIPTION
**Pull request by fhueske**
Adds the license files of Janino and Reflections to the resources folder and copies them into the JAR file under `./META-INF/PACKAGED_LICENSES/`.

### CODE REVIEW

**Comment by greghogan** [comment]
Should we add a stronger attribution as in Flink's main `LICENSE` file?

**Comment by StephanEwen** [comment]
@greghogan the main `LICENSE` file refers only to the source release. 
We don't redistribute our dependencies in source or binary there (unlike the javascript libraries for the web UI that we actually do redistribute in source).

**Comment by StephanEwen** [comment]
@fhueske I think the licenses should not be in `src/main/resources`, brause that packs them into the code as well. Then we have the license twice, one packaged from `src/main/resources`, once from the transformer.

**Comment by StephanEwen** [comment]
@fhueske I worked on getting the ASM license in all shaded JAR files. That change would subsume this one. Can you have a look what you think?

BTW: I could not use the shade resource transformer for the ASM license, because of the way that maven/shade handles relative paths and due to the fact that the resource transformer fails when a dependency already brings the same file.

Lesson learned today: It sounds simple to add a specific file in various projects to a JAR. But to do that with Maven (in a project like Flink) can take the better part of a day ;-)

**Comment by fhueske** [comment]
@StephanEwen, looks good to me. I'll close my PR then. Thanks for taking care of the licenses.

**Pull request closed without merging**
