### PR TITLE
FLINK-1732 Gaussian Mixture Model for Flink-ml library

### PR DESCRIPTION
**Pull request by shakir774**
According to IMPRO-3.SS15 warm-up task the Gaussian Mixture Model with associated test suite is implemented.

### CODE REVIEW

**Comment by shakir774** [comment]
Given following error while executing the test suite by Travis CI. 
Even `import org.apache.flink.ml.common._` is imported, what may cause this error.
```
[INFO]                                 ^

[ERROR] /home/travis/build/apache/flink/flink-staging/flink-ml/src/main/scala/org/apache/flink/ml/clustering/GMM.scala:95: error: not found: type Learner

[INFO] class GMM extends Learner[Point,GMModel] {

[INFO]                   ^

[ERROR] /home/travis/build/apache/flink/flink-staging/flink-ml/src/main/scala/org/apache/flink/ml/clustering/GMM.scala:105: error: not found: value parameters

[INFO]     parameters.add(NumIterations, numIterations)

[INFO]     ^

[ERROR] /home/travis/build/apache/flink/flink-staging/flink-ml/src/main/scala/org/apache/flink/ml/clustering/GMM.scala:115: error: not found: value parameters

[INFO]     parameters.add(NumGaussians, numGaussians)

[INFO]     ^

[ERROR] /home/travis/build/apache/flink/flink-staging/flink-ml/src/main/scala/org/apache/flink/ml/clustering/GMM.scala:125: error: not found: value parameters

[INFO]     parameters.add(InitialGaussians,initialGaussians)

[INFO]     ^

[ERROR] /home/travis/build/apache/flink/flink-staging/flink-ml/src/main/scala/org/apache/flink/ml/clustering/GMM.scala:258: error: not found: type Transformer

[INFO] case class GMModel(gmm: DataSet[Gaussian]) extends Transformer[Point, Prediction]

[INFO]                                                    ^

[ERROR] /home/travis/build/apache/flink/flink-staging/flink-ml/src/main/scala/org/apache/flink/ml/clustering/GMM.scala:137: error: value parameters is not a member of org.apache.flink.ml.clustering.GMM

[INFO]     val resultingParameters = this.parameters ++ fitParameters
```

**Comment by sachingoel0101** [comment]
You should port your implementation to the new Pipeline mechanism. Check out the master. It's been around for almost one month now.

**Comment by thvasilo** [comment]
Hello @shakir774 , as @sachingoel0101 mentioned you must rebase your current implementation on the current master as the underlying code for FlinkML has changed considerably. We can review this PR once you have done that.

**Comment by shakir774** [comment]
@thvasilo as we are busy with our next task of IMPRO-3.SS15 for the semester, once we finished with it, I will rebase it according to the new pipeline mechanism.

**Comment by zentol** [comment]
Closing since flink-ml is effectively frozen.

**Pull request closed without merging**
