### PR TITLE
[FLINK-20194][connector/kafka] Fix the KafkaSourceReader offset commit.

### PR DESCRIPTION
**Pull request by becketqin**
## What is the purpose of the change
The patch fixes the offsets commit in the following cases:
    1. The SplitFetcher has exited.
    2. The offsets to be committed is empty.
    3. The offsets commit for finished splits.

## Brief change log
- Fix the SingleThreadFetcherManager to get the running fetchers correctly.
- Change SourceReaderBase.onSplitFinished() to take a map of SplitId -> SplitState.
- Fix Kafka offset commit to coorectly handle the following cases:
    1. The SplitFetcher has exited.
    2. The offsets to be committed is empty.
    3. The offsets commit for finished splits.

## Verifying this change
The unit tests has been added to `KafkaSourceReaderTest`.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes, the argument passed to `SourceReaderBase.onSplitFinish()` has changed)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by becketqin** [comment]
@flinkbot run azure

**Comment by StephanEwen** [comment]
I looked at the API change of the base connector, and it seems reasonable.
We need to make sure this is picked back to the release-1.11 branch together with the other source api changes, though.

**Comment by becketqin** [comment]
@flinkbot run azure

**Comment by becketqin** [comment]
merged to master.
4bde1c9c10c0db2c44e25ea81ba04983b870b518

**Pull request closed without merging**
