### PR TITLE
[FLINK-9666] short-circuit logic should be used in boolean contexts

### PR DESCRIPTION
**Pull request by lamber-ken**
Backport of #6212 .

### CODE REVIEW

**Comment by lamber-ken** [comment]
difficult to find it out.

**Comment by lamber-ken** [comment]
@tillrohrmann, hi, cc

**Comment by zentol** [comment]
We typically don't backport refactorings and code-cleanups.

**Comment by lamber-ken** [comment]
@zentol, thanks for review. by the way, what's the best way to backport refactorings and code-cleanups?

**Comment by zentol** [comment]
wait.

Is this a _backport_ of #6212 for 1.5, or an _extension_ that fixes another occurrence?

**Comment by lamber-ken** [comment]
@zentol, hi, I found another occurrence just after the #6212 closed.
but I can't reopen that pr, so I start a new pr refered to #6212.

**Comment by lamber-ken** [comment]
@tillrohrmann, @zentol, cc.

**Comment by zentol** [comment]
@lamber-ken For the future, please ensure that the first commit message includes the JIRA id (like the PR title) and has a proper name.

**Comment by lamber-ken** [comment]
I see. I didn't know before.

**Pull request closed without merging**
