### PR TITLE
Update PoissonSampler.java

### PR DESCRIPTION
**Pull request by hash-X**
I review this code and find it's style is not suitable for flink. So change the format of the code to a more specification style.

### CODE REVIEW

**Comment by rmetzger** [comment]
good to merge

**Comment by hash-X** [comment]
@rmetzger ,Could you please help me to merge this change to trunk ? thanks.

**Comment by rmetzger** [comment]
This change needs to be merged by a Flink committer.
I've just put the "good to merge" comment so that the other committers know the code has been reviewed by me and is good to merge in my opinion. You basically have to wait until somebody is merging again stuff and then your PR will probably be included.

**Comment by fhueske** [comment]
@hash-X Thanks for your contribution. 
I will merge a bunch commit later today and include this one.

**Comment by hash-X** [comment]
@fhueske @rmetzger  thanks bro. Although It's just a little little contribution now.

**Pull request closed without merging**
