### PR TITLE
[FLINK-2304] Add named attribute access to Storm compatibility layer

### PR DESCRIPTION
**Pull request by mjsax**
- extended FlinkTuple to enable named attribute access
  - extended BoltWrapper for user defined input schema
  - extended FlinkTopologyBuilder to handle declared output schemas
  - adapted JUnit tests
  - added new examples and ITCases
  - updated READMEs

### CODE REVIEW

**Comment by gyfora** [comment]
Looks good to me :+1:

**Comment by mjsax** [comment]
FYI: this PR is "related" to #884 -> if #884 is merged before, this PR needs an update.

**Comment by gyfora** [comment]
And it is also related to #879 which we should probably wait before merging these. It is probably a change of 2-3 lines here but it might stall the other PR long if we are merging small changes right before that one.

**Comment by mjsax** [comment]
Ok. So this PR in put on hold and #884 can be merged "right way".

**Comment by gyfora** [comment]
I merged #884 (it should get updated soon) so you can go ahead updating this so I can merge this.

**Comment by mjsax** [comment]
Update this PR (-> added documentation). Should be ready to get merged.

**Comment by mjsax** [comment]
Just rebased because #879 was merged today. This PR should be ready to get merged now.

**Comment by gyfora** [comment]
Thanks I will merge it later today! :)

**Pull request closed without merging**
