### PR TITLE
FLINK-13317 Merge NetUtils and ClientUtils

### PR DESCRIPTION
**Pull request by xuchao0903**
## What is the purpose of the change

This pull request merges ClientUtils and NetUtils into one class (NetUtils). That way we reduce the duplicated code.

## Brief change log

  - Move ClientUtils.parseHostPortAddress() into NetUtils class
  - Modify the references of ClientUtils.parseHostPortAddress() as NetUtils' method.
  - Remove ClientUtils

## Verifying this change

This change added tests and can be verified as follows:
  - Added two unit tests for parseHostPortAddress() and getCorrectHostnamePort()

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? JavaDocs

### CODE REVIEW

**Comment by StephanEwen** [comment]
@flinkbot approve until architecture

**Comment by StephanEwen** [comment]
The build fails due to checkstyle violations.

**Comment by tillrohrmann** [comment]
@xuchao0903 do you have time to address Stephan's comments? You need to resolve the reported checkstyle violations. If not, I could try to help you with this.

**Comment by xuchao0903** [comment]
@tillrohrmann 
Thank you for helping me to resolve the checkstyle violation.  
I'm not familiar with Git.

**Pull request closed without merging**
