### PR TITLE
[FLINK-2306] Add support for named streams in Storm compatibility layer

### PR DESCRIPTION
**Pull request by mjsax**
- enabled .declareStream() and connect via stream name
     - enabled multiplt output streams
     - added .split() / .select() / strip pattern
     - added helpers in new package utils
     - adapted and extended JUnit tests
     - adapted examples

### CODE REVIEW

**Comment by StephanEwen** [comment]
The CU reports 3 failures.

2 failures in storm-compatibility-core
1 failure in YARN (yarn not responding)

**Comment by mjsax** [comment]
Yes. It a weird compile error and it builds locally... The error is:
`[ERROR] /home/travis/build/mjsax/flink/flink-contrib/flink-storm-compatibility/flink-storm-compatibility-core/src/main/java/org/apache/flink/stormcompatibility/wrappers/StormFiniteSpoutWrapper.java:[27,64] package org.apache.flink.hadoop.shaded.com.google.common.collect does not exist`

I have no clue what's wrong... :/ Any suggestions?

**Comment by StephanEwen** [comment]
Looks like an issue with shaded dependencies.

Have a look here for some background on shading: https://cwiki.apache.org/confluence/display/FLINK/Hadoop+Versions+and+Dependency+Shading

**Comment by mjsax** [comment]
Fixed. This should be ready to get merged. Please review.

**Comment by StephanEwen** [comment]
Will merge this...

**Pull request closed without merging**
