### PR TITLE
[hotfix] [doc] fix misspelling of words

### PR DESCRIPTION
**Pull request by xuzhiwen1255**
## What is the purpose of the change
Fix typo in zh/docs/dev/datastream/overview.md
## Brief change log
 Fix typo(setp -> step) in overview.md

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency):   no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no 
  - The runtime per-record code paths (performance sensitive):  no 
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper:  no 
  - The S3 file system connector:  no

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by XComp** [comment]
Thanks for the contribution, @xuzhiwen1255 . Please provide a well-formatted commit message so that we can proceed with merging the change.

**Comment by xuzhiwen1255** [comment]
@XComp Thank you for your review, I have completed the revision.

**Comment by XComp** [comment]
...but if you changed something it wasn't pushed to your remote branch. :-)

**Comment by xuzhiwen1255** [comment]
@XComp  Sorry, I misunderstood just now, it has been changed.

**Comment by XComp** [comment]
You might want to make yourself more familiar with [the contribution process](https://flink.apache.org/contributing/contribute-documentation.html). In the end, I'd expect a single commit with a proper commit message. For such a small doc change, creating a Jira issue is not necessary. Instead, you can use `[hotfix][doc]` as the prefix. Look at other commits that landed on `master` to get a better understanding of what I mean.

**Pull request closed without merging**
