### PR TITLE
[FLINK-24820][table][docs] Wrong description in documentation for IS DISTINCT FROM

### PR DESCRIPTION
**Pull request by snuyanzin**
## What is the purpose of the change

This is a trivial PR correcting description for `value1 IS DISTINCT FROM value2` in docs
## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: ( no)
  - The runtime per-record code paths (performance sensitive): ( no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? ( no)
  - If yes, how is the feature documented? (not applicable )

### CODE REVIEW

**Comment by snuyanzin** [comment]
@flinkbot run azure

**Comment by snuyanzin** [comment]
@MartijnVisser sorry for the poke
Since you are one of committers dealing with docs, could you please have a look (I've checked same in Chenese page and it looks ok there)

**Comment by snuyanzin** [comment]
@flinkbot run azure

**Comment by snuyanzin** [comment]
rebased to the latest master in order to cope with failing python module

**Review by MartijnVisser — APPROVED** [review]
@snuyanzin Thanks for the fix!

**Pull request merged**
