### PR TITLE
[FLINK-2337] Multiple SLF4J bindings using Storm compatibility layer

### PR DESCRIPTION
**Pull request by mjsax**
exclude logback from Storm dependencies

### CODE REVIEW

**Comment by mjsax** [comment]
Travis failed due to unrelated error:

    Failed tests: 
      ProcessFailureStreamingRecoveryITCase>AbstractProcessFailureRecoveryTest.testTaskManagerProcessFailure:198 The program encountered a ProgramInvocationException : The program execution failed: Job execution failed.

Does anyone know anything about this failing test?

The log warning `SLF4J: Class path contains multiple SLF4J bindings.` is gone for the 4 successful Travis runs.

This PR should be ready to get merged.

**Comment by hsaputra** [comment]
+1
LGTM

**Comment by chiwanpark** [comment]
+1 for merging :)

**Comment by rmetzger** [comment]
+1 looks good

**Comment by StephanEwen** [comment]
Merging this...

**Pull request closed without merging**
