### PR TITLE
[FLINK-3132] [docs] Initial docs restructure

### PR DESCRIPTION
**Pull request by uce**
This PR restructures the documentation by allowing pages with sub-navigations and furthermore fixes some minor issues and adds small utilities.

A preview can be found here: http://uce.github.io/flink

The goal of the changes is to increase readability in terms of structure and layout. The content has not been touched (except for minor things like typos etc.)

### Streaming and Batch Guide

The links under `Programming Guides` were intermixed with both streaming and batch docs, for example we currently have the following mixed points: `DataSet API`, `DataStream API`, `Python API`, `Fault Tolerance` (for both streaming and batch), `State in Streaming Programs`, `Interactive Scala Shell`, `DataSet Transformations`, etc. This was kind of confusing. With this PR, the streaming and batch docs have been grouped to a `Streaming Guide` and `Batch Guide` respectively.

screen shot 2016-01-12 at 14 35 10
screen shot 2016-01-12 at 14 35 16
screen shot 2016-01-12 at 14 42 18

The respective links have been removed from the top level navigation. If you look at the preview, open the programming guides drop down and compare.

Futhermore, it's now very easy to add new top level or sub level elements (see `README.md`).

### Layout changes

Some people complained that the text was too small. This has been addressed and the per page table of contents has been narrowed down a little as well. The default text is now a little larger. An issue with the responsiveness (where the top level elements would wrap a line) has also been addressed.

### Removed content

Removed the TEZ guide, and HDFS and SSH setup instructions from the cluster setup guide. I would like to remove the bundled examples page from the Batch guide as a follow up as well.

## Follow Ups and Know Issues

There are plenty of follow ups, which I would like to file JIRAs for after this is merged.

- Improve getting started guide on the front page
  - Simplify stack figure (Remove embedded, Tez, Optimizer, Stream Builder)
  - Guide the user to interesting pages
- Improve quick starts (ready to run packages, demo scripts, etc.)
- Make docs streaming first (many parts treat batch first)
- Fine-grained restructuring of streaming guide content (separate page for windowing, state, etc.)
- Fine-grained review of content
- Known Issue: Flink ML inserts some whitespace due to Latex scripts (?)
- Known Issue: Check code example code style

---

**The main question for this PR is whether you agree with the restructuring and layout. It would be great to merge this as soon as possible and then address all follow ups until the 1.0 release.**

### CODE REVIEW

**Comment by aljoscha** [comment]
Very nice :dancer:  :+1: 

One thing I'm not sure about are the boxes around the TOC, however. I mean the TOC under the headline that's visible in your third screenshot.

**Comment by rmetzger** [comment]
Thank you for improving the documentation.

I think we can entirely remove the "Docker Connector" section (which is, in the current documentation "Docker containers for connectors". There is no docker connector).

I reworked the quickstart example for KMeans in the new examples pull request, with updated screenshots etc. Maybe we can keep it as an example for how to start a batch job?

**Comment by uce** [comment]
@aljoscha OK, I'm OK with removing it if more people don't like it. No problem.

@rmetzger: OK, I would also like to remove it completely or only link it from the connectors overview page. I was not referring to the Kmeans quick start example but `Batch Guide > Bundled Examples`. More importantly, we would need a good streaming example.

**Comment by darionyaphet** [comment]
[config.html](http://uce.github.io/flink/setup/config.html#common-options) could restructure to table style ?  It's maybe better and clearly :)

**Comment by uce** [comment]
@darionyaphet Yes, but I would file it as a follow-up. Thanks for the suggestion! :)

**Comment by darionyaphet** [comment]
hi @uce I found another small problem : [checkpointing.svg](http://uce.github.io/flink/internals/stream_checkpointing.html#state) in stream_checkpointing.html is Piled up together

**Comment by uce** [comment]
I've checked and couldn't see a difference to the current docs (https://ci.apache.org/projects/flink/flink-docs-master/internals/stream_checkpointing.html). I didn't change anything relevant on the respective page.

If you mean that the image text is not quite readable, I would agree, but this is something I would address in a separate change (since it didn't change here). If you like, open an issue for this.

**Comment by darionyaphet** [comment]
yes I just want to say svg text info is unreadable thank you for you reply .

**Comment by fhueske** [comment]
+1 for the restructuring! Looks much better now. 
Regarding the font size, I am not sure. IMO, it is a bit too large but I can see that the previous setting was too small. Can we go with a setting in the middle?

Otherwise, good to merge.

**Comment by uce** [comment]
@fhueske The previous font size was 14 px, the changed version has 16 px. A screenshot for comparison. Maybe it's OK with 14 px, because the text is narrower now. If more people agree, I'm happy to revert the font size change.

Two screenshots for comparison:

screen shot 2016-01-13 at 11 38 35
(16px)

screen shot 2016-01-13 at 11 39 10
(14px)

**Comment by tillrohrmann** [comment]
I'm in favour of the smaller font size (14px).

**Comment by fhueske** [comment]
Thanks for the quick response, @uce.
+1 for 14px

**Comment by mxm** [comment]
Looks very nice @uce. Would it be possible to shift the left navigation bar to the top of the main text corpus? It makes the main text corpus strangely positioned and takes away space. This affects the code examples which tend to break lines more often now.

Another solution could be to make the navigation bar fixed. Then the alignment of the main corpus would make sense when you have scrolled down. Plus, you have the navigation always available.

**Comment by tillrohrmann** [comment]
I think one problem with a fixed navigation on the side is what happens if the number of entries is so huge that the whole navigation menu cannot be displayed without scrolling. We had such a problem with the Stratosphere documentation back in the days if I remember correctly.

**Comment by uce** [comment]
I didn't notice before, but now I also see that it can feel strange when you scroll down. The text looks right aligned relative to the top navigation bar. But moving the sub navigation to the top might result in confusion when having two lists (sub navigation and per page table of contents). Personally, I would keep it on the left for now. If others feel that it should be moved to the top, I'm happy to do it though. :) The static navigation was a problem for the reason Till mentioned. Do you have another idea?

Regarding the code examples: they will be smaller again with Fabians suggested change. I can then do another pass over the code examples. In general, the more narrow text was something that some users were asking for in the past.

**Comment by mxm** [comment]
Makes sense. Smaller font size will probably do it then.

**Comment by uce** [comment]
If there are no objections, I would like to address Robert's (Docker) and Fabian's (foint size) remarks and merge this. As I've said, not the final truth on the matter, but I would like to see all other things addressed in future PRs.

**Comment by aljoscha** [comment]
+1

**Comment by mxm** [comment]
+1

**Pull request closed without merging**
