### PR TITLE
Flink-13405 Translate "Basic API Concepts" page into Chinese

### PR DESCRIPTION
**Pull request by YngwieWang**
- All nouns are singular
- All `Tuple` are untranslated and capitalized 
- All `Case Classes` are untranslated and capitalized 
@klion26 @xccui @wuchong PTAL

### CODE REVIEW

**Comment by klion26** [comment]
Please avoid using `git merge` in the git history

**Comment by YngwieWang** [comment]
Sorry, should I close this pr and open a new one?

**Comment by klion26** [comment]
You can make a clean history and force push to this branch.
If this is not easy, then close and create a new pr is fine.

**Comment by YngwieWang** [comment]
Thank you very much.

**Pull request closed without merging**
