### PR TITLE
[FLINK-12141] [API/Type Serialization System] Allow @TypeInfo annotation on POJO field declarations

### PR DESCRIPTION
**Pull request by Leeviiii**
## What is the purpose of the change

*Allow @TypeInfo annotation on POJO field declarations.*

## Brief change log

  - *allow @TypeInfo annotation on POJO field *
  - *add a testcase in TypeInfoFactoryTest.java*
  - *change the function analyzePojo to make it can analyze POJO field  with @TypeInfo annotation*

## Verifying this change

This change is already covered by existing tests, such as *TypeInfoFactoryTest*.

This change added tests and can be verified as follows:

*testWithFieldTypeInfoAnnotation*
 - *Added unit test for POJO field declarations with @TypeInfo annotation*
  

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`:  no
  - The serializers: yes
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper:  no
  - The S3 file system connector: no 

## Documentation

  - Does this pull request introduce a new feature? yes 
  - If yes, how is the feature documented? JavaDocs

### CODE REVIEW

**Comment by twalthr** [comment]
@flinkbot approve-until consensus

**Comment by gyfora** [comment]
@twalthr it would be great to merge this PR if you think the changes are good.
To me it looks good, but I am much less experienced with the type system.

**Comment by tzulitai** [comment]
@flinkbot approve consensus

**Comment by NicoK** [comment]
I went ahead and rebased this commit onto the latest master. I also improved a few things such as:
- reduce code duplication with the existing `TypeInfoFactory` handling (this also adds a couple of validity checks for the annotation and the type that the `TypeInfoFactory` returns)
- extended the tests (overriding a class-defined `TypeInfoFactory` works, types without generics work)

I would consider this my review, but if any of the people involved in this thread wants to take a second look that would be great.

**Review by NicoK — APPROVED** [review]

**Pull request merged**
