### PR TITLE
[BP-1.16][FLINK-30592][doc] remove unsupported hive version in hive overview document

### PR DESCRIPTION
**Pull request by chrismartin823**
this is a back port pr to 1.16 branch for fixing   FLINK-30592

### CODE REVIEW

**Comment by chrismartin823** [comment]
> * @flinkbot run azure

@flinkbot run azure

**Comment by chrismartin823** [comment]
> ## CI report:
> * [731b4ae](https://github.com/apache/flink/commit/731b4ae1e8e5df27766bf1549e62789dcad6d1eb) Azure: [PENDING](https://dev.azure.com/apache-flink/98463496-1af2-4620-8eab-a2ecc1a2e6fe/_build/results?buildId=44600)
> 
> Bot commands
> The @flinkbot bot supports the following commands:
> * `@flinkbot run azure` re-run the last Azure build

@flinkbot run azure

**Comment by luoyuxia** [comment]
@flinkbot run azure

**Comment by chrismartin823** [comment]
@flinkbot run azure

**Review by luoyuxia — APPROVED** [review]
LGMT. @wuchong Could you please help merge? Thanks.

**Pull request merged**
