### PR TITLE
[hotfix] Make doc ide_setup.md format better for code formatting

### PR DESCRIPTION
**Pull request by liuml07**
## What is the purpose of the change

Make doc file ide_setup.md format better after e48abd38

### Before:

Screen Shot 2022-09-21 at 5 39 42 PM

### After:

Screen Shot 2022-09-21 at 5 40 48 PM

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

This change is a trivial rework / code cleanup without any test coverage.

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by liuml07** [comment]
CC @afedulov

**Review by afedulov — APPROVED** [review]
@liuml07 thanks for the fix, LGTM.

**Comment by liuml07** [comment]
I see you also contributed to the doc file, could you merge this @Airblader?

**Comment by liuml07** [comment]
Hi @afedulov Could you help commit this? Thanks,

**Comment by afedulov** [comment]
@mxm could you please merge? (I am still blocked on the ICLA formalities)

**Review by mxm — APPROVED** [review]

**Comment by afedulov** [comment]
Thanks!

**Pull request merged**
