### PR TITLE
[FLINK-20619] Removed InputDependencyConstraint

### PR DESCRIPTION
**Pull request by XComp**
## What is the purpose of the change

This PR covers the removal of `InputDependencyConstraint` and `InputDependencyConstraintChecker`.

This PR depends on PR #14578 covering [FLINK-20600](https://issues.apache.org/jira/browse/FLINK-20600) being merged.

 ❗ It includes changes to `@PublicEvolving` API.

## Brief change log

Any usages of the two classes was removed.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by XComp** [comment]
@zhuzhurk you might want to have a look at this PR as well. ...since you suggested the removal in [FLINK-20619](https://issues.apache.org/jira/browse/FLINK-20619).

**Comment by zhuzhurk** [comment]
There is a test failure in python module.
"FAILED pyflink/common/tests/test_execution_config.py::ExecutionConfigTests::test_get_set_default_input_dependency_constraint"

I think we can just remove this test case.

**Review by zhuzhurk — APPROVED** [review]
LGTM.
+1 to merge once CI gives green.

**Comment by XComp** [comment]
Yeah, I realized it this morning that I had `*.java` set up as a filter in my Idea search dialog. 😇 I fixed it.

But are we ok with just removing the public API as is? Or should we provide the skeleton methods not doing anything and labeling them as deprecated?

**Comment by zhuzhurk** [comment]
I think you are right. It would be better to annotate the  methods as `@Deprecated` first and remove it in future versions.

**Comment by zhuzhurk** [comment]
The commit to deprecate `InputDependencyConstraint` looks good to me.

**Review by rmetzger — APPROVED** [review]
The change looks good!

The deprecation seems fine to me.
I'll merge the change!

**Comment by rmetzger** [comment]
The build failure seems unrelated.

**Pull request closed without merging**
