### PR TITLE
[hotfix][comment]remove useless comment

### PR DESCRIPTION
**Pull request by zzsmdfj**
## What is the purpose of the change

remove useless comment

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by KarmaGYZ** [comment]
Thanks for the hotfix, but IMO removed comment is not useless.
-1 for this pr.

**Comment by zzsmdfj** [comment]
> Thanks for the hotfix, but IMO removed comment is not useless.
> -1 for this pr.

that comment is just meaning for "session windows UTTests" ?

**Comment by StephanEwen** [comment]
Is the comment actually wrong/misleading?

If not, I would avoid such refactoring. It is very subjective whether a comment is useful or useless.

**Comment by zzsmdfj** [comment]
> subjective

Thanks Reply. yes, it is subjective whether a comment is useful or useless. that comment "row interval is not valid for session windows" appears four times in class GroupWindowValidationTest. It confuses me when I view the code. so I just want to see if I can make the code cleaner.

**Comment by zentol** [comment]
Other people might not read the entire class, hence the comment appearing at multiple places is not a problem imo.

**Pull request closed without merging**
