### PR TITLE
[WIP][FLINK-13417] Bump ZooKeeper from 3.4.10 to 3.5.6

### PR DESCRIPTION
**Pull request by tillrohrmann**
This is a WIP PR for the ZooKeeper version upgrade.

### CODE REVIEW

**Comment by TisonKun** [comment]
If we don't upgrade curator to 4.x at the same time, it requires excluding some dependencies so that curator-test uses zk 3.5 for testing. You can make use of https://github.com/apache/flink/pull/9840 .

**Comment by tillrohrmann** [comment]
> If we don't upgrade curator to 4.x at the same time, it requires excluding some dependencies so that curator-test uses zk 3.5 for testing. You can make use of #9840 .

Thanks for the pointer Tison. I hoped that maven's dependency management would take care of it by letting the respective dependency management section in Flink's parent `pom.xml`. Let me double check it.

**Comment by tillrohrmann** [comment]
@flinkbot run travis

**Comment by tillrohrmann** [comment]
@flinkbot run azure

**Comment by tillrohrmann** [comment]
Won't upgrade Flink's ZooKeeper version to 3.5 since the ZooKeeper client is not backwards compatible (Zk 3.5 client is not able to talk to a ZooKeeper 3.4 server).

**Pull request closed without merging**
