### PR TITLE
[FLINK-3534] [runtime] Prevent canceling Execution from failing

### PR DESCRIPTION
**Pull request by uce**
@StephanEwen, can you have a look at this?

This should handle cases where a cancelled execution is failed (as reported by @rmetzger), but still allow the `ExecutionGraph` to be failed (and not suffer from the point you raised in #1726).

Robert would like this in the next RC, but in general I think that it's better to have more exposure for a change to the `ExecutionGraph`... I'm undecided right now. What do you think?

### CODE REVIEW

**Comment by StephanEwen** [comment]
Looks good to me!

+1 to merge this

**Comment by uce** [comment]
I've fixed the test failures.

@StephanEwen, the changes can result in the following behaviour: if a slot is released, some of its executions can end up in cancelled rather than failed state. Is that OK? The following happens: The slot's first execution is failed. This triggers an execution graph fail, after which all executions are cancelled. When the slot fails further executions, these are already cancelling and go to state cancelled. Before they would still go state `FAILED`.

**Comment by StephanEwen** [comment]
True, that is rather ugly behavior. I guess the important thing is that at least one of the Executions results in state `failed`.

**Comment by uce** [comment]
My local [Travis build has passed](https://travis-ci.org/uce/flink/builds/112634854). I will merge this to `master` and `release-1.0`.

**Pull request closed without merging**
