### PR TITLE
[FLINK-8554] Upgrade AWS SDK

### PR DESCRIPTION
**Pull request by yanghua**
## What is the purpose of the change

*This pull request upgrades AWS SDK*

## Brief change log

  - *Upgrades AWS SDK*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**yes** / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (**yes** / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by yanghua** [comment]
version: 1.11.319:

```
[INFO] org.apache.flink:flink-connector-kinesis_2.11:jar:1.6-SNAPSHOT
[INFO] +- com.amazonaws:aws-java-sdk-kinesis:jar:1.11.319:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-core:jar:1.11.319:compile
[INFO] |  \- com.amazonaws:jmespath-java:jar:1.11.319:compile
[INFO] +- com.amazonaws:amazon-kinesis-producer:jar:0.12.9:compile
[INFO] |  \- (com.amazonaws:aws-java-sdk-core:jar:1.11.312:compile - omitted for conflict with 1.11.319)
[INFO] \- com.amazonaws:amazon-kinesis-client:jar:1.9.0:compile
[INFO]    \- (com.amazonaws:aws-java-sdk-kinesis:jar:1.11.272:compile - omitted for conflict with 1.11.319)
```

version: 1.11.325

```
[INFO] org.apache.flink:flink-connector-kinesis_2.11:jar:1.6-SNAPSHOT
[INFO] +- com.amazonaws:aws-java-sdk-kinesis:jar:1.11.325:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-core:jar:1.11.325:compile
[INFO] |  \- com.amazonaws:jmespath-java:jar:1.11.325:compile
[INFO] +- com.amazonaws:amazon-kinesis-producer:jar:0.12.9:compile
[INFO] |  \- (com.amazonaws:aws-java-sdk-core:jar:1.11.312:compile - omitted for conflict with 1.11.325)
[INFO] \- com.amazonaws:amazon-kinesis-client:jar:1.9.0:compile
[INFO]    \- (com.amazonaws:aws-java-sdk-kinesis:jar:1.11.272:compile - omitted for conflict with 1.11.325)
```

**Comment by yanghua** [comment]
@StephanEwen here is test error in the [build job](https://travis-ci.org/apache/flink/jobs/380523257),  and it seems the aws sdk is under license "Apache 2.0", so should I do the second item you asked?

**Comment by bowenli86** [comment]
Are there anything in `1.11.325` we desperately need?

If not, I would oppose upgrading AWS SDK too frequently. Highly likely that we don't need any of the new changes in `1.11.325`. As you can see, the current sdk version is `1.11.319` which is upgraded just a few days ago. 

There're a few reasons we should discourage it:

- It doesn't add much value, and we don't really need it
- It costs lots of unnecessary work from both contributors and Flink community (committers, reviewers, etc)
- AWS releases their SDK very frequently, in a much faster pace than we can possibly catch up

**Comment by yanghua** [comment]
@StephanEwen close this or not?

**Pull request closed without merging**
