### PR TITLE
[FLINK-4192] - Move Metrics API to separate module

### PR DESCRIPTION
**Pull request by zentol**
This PR moves several metrics-related classes into a new module.

The new module is located under `flink-metrics/flink-metrics-core`.

Most of the changes are related to
* renaming of `MetricRegistry` to `InternalMetricRegistry`
 * a new `MetricRegistry` interface was added
* replacing usages of `Configuration` with a new `MetricConfig`

Changes unrelated to the above are as follows:
* obviously, creating a new module and adjusting dependencies
* some tests were refactored to properly close the registry
* `getScopeComponents/-String()` was moved from `AbstractMetricGroup` to `MetricGroup`
* fixed a small typo in `Scheduled`  interface

I have verified that it compiles and works for example.The tests in flink-core pass as well, I'll leave the rest to travis.

### CODE REVIEW

**Comment by zentol** [comment]
Note that this PR will cause a few issues with other metric related Pull Requests.

**Comment by StephanEwen** [comment]
Is it important that the metric reporter projects do not depend on "flink-core"? If not, the the entire MetricRegistry could stay in flink-core, and there would be no need to the MetricConfig object.

**Comment by zentol** [comment]
you are correct that the MetricRegistry could remain in flink-core. However, you would still need the new MetricConfig due to the MetricReporter.

**Comment by StephanEwen** [comment]
Could the `MetricReporter` stay in `flink-core`as well, or does that void the separation of dependencies.

You can probably use the Java `Properties` object as a configuration object. Saves you the extra config object. Kafka, for example, uses the `Properties` class extensively and has no own config type at all.

**Comment by zentol** [comment]
The whole point of this PR is to have the MetricReporter in a separate module; other changes are just side-effects.

I'll look into the Properties class.

**Comment by StephanEwen** [comment]
Makes sense (I initially thought it was mainly about the Counter and MetricGroup classes).

**Comment by zentol** [comment]
I've looked into the `Properties` class. I would prefer not to use it since it would force the Reporter implementations to parse things from Strings manually. I would be nicer if we could hide that.

**Comment by StephanEwen** [comment]
I would actually prefer to use a standard library class for configuration, rather then "roll our own". With a few helper methods along the lines of "getAndParseOrReturnDefault()", this can be similarly seamless.

**Comment by zentol** [comment]
Using anything but a simple wrapper around a HashMap (what the MetricConfig currently is) is overkill. We would have a bunch of methods without an actual use-case cluttering up the interface.

If we have to extend `Properties` and add methods for it to become usable, why use it in the first place? What do we gain by using it?

**Comment by zentol** [comment]
I've reverted moving of the MetricRegistry; it was in fact not necessary.

**Comment by StephanEwen** [comment]
The point of using `Properties` is that users of the API can use a class they are familiar with and maybe even reuse configurations and tools they internally that work with `Properties` types. Adding yet another config type means users may have to integrate yet another config type with their own tools and utils.

**Comment by zentol** [comment]
Alright, although I am curious why this wasn't an issue when we merged the metric system initially.

Since you mentioned that we should/could add additional helper methods, please provide a full list of methods that you think are necessary. Otherwise this will turn into longer back-and-forth than necessary.

**Comment by zentol** [comment]
@StephanEwen I've changed the `MetricConfig`to extend `Properties` and remove the `setString()` method. I've kept the other methods for now.

**Comment by StephanEwen** [comment]
Having `MetricsConfig` extend `Properties` mitigates the issue to some extend.

I know I am very adamant on not having an extra config object. It's because I heard it a bunch of times that the plethora of config types annoy developers (in general, not Flink specific) when every tool/system/library introduces their own config types. So it would be nice if Flink did not introduce more than one custom config type.

**Comment by StephanEwen** [comment]
Will merge this, leaving the config as is.

**Comment by StephanEwen** [comment]
I tried to see if we can move the entire set of metrics classes to the independent `flink-metrics-core` module. Here is how that would look like: https://github.com/StephanEwen/incubator-flink/tree/move_metrics

  - The runtime-specific metric groups are in `runtime.metrics` in `flink-runtime`. It makes sense dependency wise, because that way, we can actually use the proper types (like `ExecutionID`)
  - ScopeFormats are also bound to the component metric groups, not the registry as a whole
  - Everything else is in the `flink-metrics-core` module.

Remaining issues:
  - The JMX reporter currently uses the `NetUtils`, which are now not available any more.
  - The `MetricRegistry` relied on `Configuration` before. It can now only rely on `MetricConfig`, which we have to efficiently extract from the configuration.

**Comment by zentol** [comment]
I had a chat with @tillrohrmann about moving all classes when i started working on this issue. We decided to not include implementations in the new module, to be able to use NetUtils and Preconditions. As such, the scope of this issue was defined as moving user-facing interfaces into a separate module.

If you want to move the remaining classes as well, please open a separate JIRA so we can revisit the discussion.

As there is no conflict between your proposal and the changes in this PR, i would propose merging the PR as is.

**Comment by StephanEwen** [comment]
Think of this as part of the discussion with another guy in the community ;-)

The split of metric classes between `flink-core` and `flink-metric-core` made it to me a bit complicated to find the way around the metric code. I made attempt looking at what would actually be the consequences of trying to move all.

I think that this is part of the issue that this PR addresses, rather than a followup.

**Comment by zentol** [comment]
Separating classes certainly makes navigation trickier, but should we sacrifice code-stability (Preconditions/NetUtils) for it? I believe a separation of interfaces and implementation is a good compromise; users can write against the small flink-metrics-core jar, but we retain the ability to use all utilities have.

If we want to move implementations into flink-metrics-core to make navigation easier i would propose to move all classes there. Being able to use JobID etc. directly is imo less of a benefit than the utilities.

**Comment by StephanEwen** [comment]
Actually, we do not even have to move the JobID, if the runtime-specific parts (the component metric groups) are in `flink-runtime`. That part, I believe, we should do anyways.

It certainly is nice to have a complete "self-contained" metrics project with everything. That way, people can actually build their own metrics tooling using some of the implementation classes, or they can set up self-contained tests for reporters (without having flink-core) as a test dependency. If it were not for the `NetUtils`, I would suggest to go for that. The `Preconditions` are used only for `checkNotNull`, which one can do via `java.util.Objects.requireNonNull` as well.

On the other side of the argument are the `NetUtils` (one utility function for port ranges) and making the MetricRegistry use MetricConfig in all places.

**Comment by StephanEwen** [comment]
Had a quick offline discussion with @zentol and @aljoscha with the outcome:

  - Make `flink-metrics-core` strictly the metrics API project for Metrics and Reporters
  - Move all implementations of the metric groups and the MetricRegistry to `flink-runtime`.
  - `flink-core` is actually metric free and depends on the metric API project only.

Users that want to implement reporters only refer to `flink-metrics-core`. For tests, a dependency to `flink-runtime` is needed.

We may move further classes to `flink-metric-core` in the future to reduce test dependencies on `flink-runtime`, but that is an open issue at this point.

**Comment by zentol** [comment]
I've update the PR accordingly. 

The PR is now separated into 4 commits:

1. move all user-facing API into flink-metrics-core
2. move remaining metric classes out of flink-core (mostly to flink-runtime)
3. adjusting imports for all non-metrics classes
4. slight modification in some MetricGroups to use the `TaskDeploymentDescriptor`/`JobGraph` directly

**Comment by aljoscha** [comment]
Why did you remove the `@PublicEvolving` annotations? I think technically they are not required since the code is not in the core or runtime package anymore but it's still a good hint for users that they might change in the future.

**Comment by zentol** [comment]
I took this change from @StephanEwen branch; I don't _know_ why, but I'm assuming for the purpose of making `flink-metrics-core` truly independent.

**Comment by zentol** [comment]
I found out why the `testJobManagerMetricAccess` fails: Since we moved the JMXReporter to flink-runtime the package declaration changed (it now includes "runtime"). The class name was hard-coded in that test leading to a ClassNotFoundException.

I think the JMXReporter should be _somewhere_ else; i dislike that this one reporter has a different package declaration than other reporters that Flink offers. I'm thinking of having it in a separate `flink-metrics-jmx` module under `flink-metrics` that is included in dist.

**Comment by aljoscha** [comment]
That sounds like a good solution, yes!

**Comment by zentol** [comment]
The JMXReporter is no in it's own module. The KafkaTestBase also relied on it, so it now has a test dependency on that module.

**Comment by zentol** [comment]
There's an issue with the kafka JMXReporter dependency (can't find the class when tests are executed), trying to fix it.

**Comment by zentol** [comment]
I've verified locally that the kafka tests now pass.

**Comment by aljoscha** [comment]
How confident are we? 😄 Should we wait for travis to finish or can we merge now?

**Comment by zentol** [comment]
I think we're good. The builds passed before we moved the JMXReporter, and i scanned for usages of the JMXReporter and ran tests in the affected modules.

Let me check one more time whether you can properly configure the JMXReporter in flink-dist, just to be safe.

**Comment by zentol** [comment]
yep, we're good to go IMO.

**Comment by aljoscha** [comment]
Ok, I think anything else we'll discover in the release testing. If any ...

LGTM!

**Comment by zentol** [comment]
merging

**Pull request closed without merging**
