### PR TITLE
[FLINK-25771][connectors][Cassandra][test] Raise the Cassandra driver timeouts at the Cluster level

### PR DESCRIPTION
**Pull request by echauchot**
R: @zentol

### CODE REVIEW

**Comment by echauchot** [comment]
@flinkbot run azure

**Comment by echauchot** [comment]
@zentol the failure seems unrelated (failure on a repeated test CastFunctionITCase.testFunction fails at interation 15) WDYT ?

**Comment by echauchot** [comment]
@flinkbot run azure

**Comment by gaoyunhaii** [comment]
@flinkbot run azure

**Comment by gaoyunhaii** [comment]
@echauchot the PR seems failed on a fixed issue, could you rebase it to the latest master?

**Comment by echauchot** [comment]
@gaoyunhaii done

**Comment by echauchot** [comment]
Hi @zentol, WDYT ?

**Comment by echauchot** [comment]
@zentol thanks for merging !

**Pull request merged**
