### PR TITLE
[FLINK-5978][FLINK-6459][FLINK-6461] Move web-related config parameters to JMOptions

### PR DESCRIPTION
**Pull request by zentol**
This PR contains the remaining steps to moving all web-related configuration parameters to the `JobManagerOptions` class.

* contains a rebased and cleaned up version of #3552 
* moves the `ACCESS_CONTROL_ORIGIN` ConfigOption
* deprecates the remaining web-related default values in ConfigConstants, and replaces all usages of them

### CODE REVIEW

**Comment by greghogan** [comment]
Are we also deprecating use of the default values in `ConfigConstants`?

**Comment by greghogan** [comment]
+1 to merge for 1.3.0

**Comment by zentol** [comment]
I would think that default values in `ConfigConstants` should be deprecated as well, as they are generally subsumed by the corresponding `ConfigOption`.

**Comment by zentol** [comment]
merging to 1.4.

**Comment by greghogan** [comment]
Will this also be merged to 1.3.0? If not, 1.4 will need to replace and deprecate `JOB_MANAGER_WEB_ACCESS_CONTROL_ALLOW_ORIGIN`.

**Comment by zentol** [comment]
Good point, Ill merge the access-control-origin commit to 1.3 as well.

**Comment by zentol** [comment]
I guess this also means i now have to worry about hte order in which i merge things to the branches, urgh.

**Pull request closed without merging**
