### PR TITLE
[FLINK-17132][metrics] Use the latest version of simpleclient_pushgateway to solve the "Failed to push metrics to PushGateway" problem

### PR DESCRIPTION
**Pull request by Godlumen**
## What is the purpose of the change

Solve this problem: Use the flink-metrics-prometheus module to report the metric, pushgateway successfully received the data, but Jobmanager and TaskManager will print "Failed to push metrics to PushGateway" and throw "java.io.IOException: Response code from xxx was 200". [FLINK-17132](https://issues.apache.org/jira/browse/FLINK-17132)

## Brief change log

  - Upgrade <prometheus.version> from 0.3.0 to 0.8.0 in root pom.xml.

## Verifying this change

This change is already covered by existing tests, such as PrometheusPushGatewayReporterTest&PrometheusReporterTaskScopeTest&PrometheusReporterTest.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): yes 
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`:  no
  - The serializers: no 
  - The runtime per-record code paths (performance sensitive):  no 
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no 
  - The S3 file system connector:  no

## Documentation

  - Does this pull request introduce a new feature?  no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by Godlumen** [comment]
> We could go straight for 8.0.1 .
> 
> Have you verified the functionality with an actual prometheus (pushgateway) deployment?

**Comment by Godlumen** [comment]
> We could go straight for 8.0.1 .
> 
> Have you verified the functionality with an actual prometheus (pushgateway) deployment?

Yes, i have verified.
Would you tell me why CLI Report shows UNKOWN on above？Thanks.

**Comment by zentol** [comment]
Because it hasn't picked up the actual build status yet; this is normal shortly after the build was triggered.

**Comment by Godlumen** [comment]
> Because it hasn't picked up the actual build status yet; this is normal shortly after the build was triggered.

Thanks, i got it.
I have upgraded promethus's version to 0.8.1, and verified.

**Pull request merged**
