### PR TITLE
[FLINK-10162][flink-runtime][flink-runtime-web] add host in checkpoint detail

### PR DESCRIPTION
**Pull request by maqingxiang**
Add the host information to the checkpoint so that if the checkpoint fails, you can specifically login to the appropriate machine to see the cause of the failure.

### CODE REVIEW

**Comment by yanghua** [comment]
hi @maqingxiang thanks for your contribution. Please modify the title and description of this PR to make it easier for others to review it. If you don't know too much, you can read the [contribution documentation](https://flink.apache.org/how-to-contribute.html).

**Comment by yanghua** [comment]
It's a good idea to add some tests to your changes to verify its correctness.

**Comment by maqingxiang** [comment]
cc @yanghua 

Thank you for the review, please help review it again.

**Comment by yanghua** [comment]
+1

**Comment by maqingxiang** [comment]
@aljoscha 

Please help review it, thanks.

**Comment by zentol** [comment]
I would like to delay this PR until we've handled #7086 to prevent the current and proposed UI from diverging too much.

**Comment by zentol** [comment]
Closing as we'll need a revised version for the new UI.

**Pull request closed without merging**
