### PR TITLE
[FLINK-28629][sql-gateway][hive] Allow to getCatalogs in the HiveServer2 Endpoint

### PR DESCRIPTION
**Pull request by fsk119**
## What is the purpose of the change

*Implement getCatalogs in the HiveServer2 Endpoint.*

## Brief change log

  - *Implement listCatalogs in the SqlGatewayService*
  - *Implement GetCatalogs in the HiveServer2 Endpoint*

## Verifying this change

This change added tests and can be verified as follows:

  - *Added list all catalogs in the `SqlGatewayServiceITCase`*
  - *Use jdbc to fetch all catalogs in the `HiveServer2EndpointITCase`*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (**yes** / no)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (**yes** / no)
  - If yes, how is the feature documented? (not applicable / docs / **JavaDocs** / not documented)

### CODE REVIEW

**Comment by fsk119** [comment]
@flinkbot run azure

**Comment by fsk119** [comment]
@flinkbot run azure

**Comment by fsk119** [comment]
@flinkbot run azure

**Review by wuchong — APPROVED** [review]
LGTM.

**Pull request closed without merging**
