### PR TITLE
[hotfix][docs] Fix error html tag in batch index documentatition

### PR DESCRIPTION
**Pull request by lamber-ken**
## What is the purpose of the change

Fix error html tag in batch index documentatition

## Brief change log

  - *Change `</br>` to `<br />`*
  - *`<tr>` and `</tr>` appear in pairs*

### CODE REVIEW

**Comment by lamber-ken** [comment]
Old `DataSet Transformations documents` has some error html tag.

[flink-1.4-dataset-transformations-scala](https://ci.apache.org/projects/flink/flink-docs-release-1.4/dev/batch/)
[flink-1.5-dataset-transformations-scala](https://ci.apache.org/projects/flink/flink-docs-release-1.5/dev/batch/)
[flink-1.6-dataset-transformations-scala](https://ci.apache.org/projects/flink/flink-docs-release-1.6/dev/batch/)

image
image

**Comment by lamber-ken** [comment]
@dawidwys hi, cc

**Comment by lamber-ken** [comment]
cc @zentol

**Comment by yanghua** [comment]
+1

**Pull request merged**
