### PR TITLE
[FLINK-15635][table] EnvironmentSettings supports to accept the user ClassLoader

### PR DESCRIPTION
**Pull request by lsyldliu**
> This is a continued work of contribution #19410. 

This PR solves the issue of allowing the user to provide its own classloader for UDFs and at other places where it's more appropriate than the current Thread context classloader.

The PR also contains a couple of hotfixes (mergeable separately):

Deprecate CatalogFunction#isGeneric
Remove CodeGeneratorContext#apply which makes the code unnecessarily more complicated
Fix singleton config in EnvironmentSettings, which among various issues, it's also causing in this case to select the wrong user class loader

### CODE REVIEW

**Review by wuchong — COMMENTED** [review]
Thanks @slinkydeveloper , @matriv , @lsyldliu , the pull request looks good to me in general. I only left 2 comments.

**Comment by wuchong** [comment]
Besides, there are many cases are failed, could you take a look?

**Review by wuchong — APPROVED** [review]
LGTM.

**Comment by wuchong** [comment]
There are too many commits. I will squash them into 2 commits.

**Comment by wuchong** [comment]
@lsyldliu could you help to have a look at the test? It seems {{SplitAggregateITCase.testMinMaxWithRetraction}} is failed.

**Comment by lsyldliu** [comment]
@flinkbot rerun

**Comment by wuchong** [comment]
Merging...

**Pull request merged**
