### PR TITLE
[FLINK-3054] Remove R (return) type variable from SerializationSchema

### PR DESCRIPTION
**Pull request by rmetzger**
- I removed the `JavaDefaultStringSchema`, `DummyStringSchema`, `StringToByteSerializer` and used the `SimpleStringSchema` everywhere.
- I removed the `RawSchema`, it was not used anywhere.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Big +1 from my side.

It is API breaking, though, so we should add this to the list of API changes for 1.0

**Comment by rmetzger** [comment]
Thank you for the review. I'll merge it to master

**Comment by gyk** [comment]
Now is there any easy way to get raw byte array from Kafka when using `FlinkKafkaConsumer*`?

**Comment by rmetzger** [comment]
I think you can use this class as a reference: https://github.com/apache/flink/blob/2c507f93300ad1b53c477e0939f1f2232187b37f/flink-streaming-java/src/main/java/org/apache/flink/streaming/util/serialization/RawSchema.java

**Pull request closed without merging**
