### PR TITLE
[FLINK-11761] Update FlinkKafkaConsumerBaseMigrationTest for 1.8

### PR DESCRIPTION
**Pull request by yanghua**
## What is the purpose of the change

*This pull request updates FlinkKafkaConsumerBaseMigrationTest for 1.8*

## Brief change log

*(for example:)*
  - *Update FlinkKafkaConsumerBaseMigrationTest for 1.8*

## Verifying this change

This change is already covered by existing tests, such as *FlinkKafkaConsumerBaseMigrationTest*.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by zentol** [comment]
@yanghua can you do me a favor and bundle all tests that you update in a single PR? It's all the same stuff, let's do this in one go.

**Comment by yanghua** [comment]
@zentol OK, my plan is open a single PR for the umbrella issue then one subtask one commit. What do you think?

**Comment by zentol** [comment]
@yanghua sounds good!

**Comment by yanghua** [comment]
@zentol Thanks for your suggestion. I have reopened a new PR #8168 for the migration test umbrella issue, this PR's commit has been cherry-picked into that PR. So closing this PR.

**Pull request closed without merging**
