### PR TITLE
[FLINK-25537] [JUnit5 Migration] Module: flink-core

### PR DESCRIPTION
**Pull request by GOODBOY008**
The left in core module.

### CODE REVIEW

**Review by Jiabao-Sun — APPROVED** [review]
Thanks @GOODBOY008 for this hard work, LGTM!
cc @1996fanrui.

**Review by 1996fanrui — APPROVED** [review]
LGTM, and 1.20 is freezed. It's better to merge this PR after 1.20 branch is cut.

**Review by 1996fanrui — CHANGES_REQUESTED** [review]
https://github.com/apache/flink/pull/24945 reverts the InitOutputPathTest to junit4.

We can research why InitOutputPathTest fails after migrating juint5, and fix it later in this PR as well.

**Review by 1996fanrui — COMMENTED** [review]
> > #24945 reverts the InitOutputPathTest to junit4.
> > We can research why InitOutputPathTest fails after migrating juint5, and fix it later in this PR as well.
> 
> @1996fanrui The class failed because of the jdk verison, and I fixed in this pr.

Hi @GOODBOY008 , thanks for the fix. I don't have capacity work in(or detailed analyze) JUnit5 Migration. 

And you and @Jiabao-Sun are committer, so feel free to merge it if both of you think this PR is fine, thanks~

**Pull request merged**
