### PR TITLE
[Flink-15355][plugins] Added parent first patterns for plugins.

### PR DESCRIPTION
**Pull request by AHeise**
## What is the purpose of the change

Certain parent first entries do not work well with unrelocated plugins and custom hadoop bundling. By using a reduced list that only consists of SPI level interfaces and logging frameworks, plugins work without relocations.

## Brief change log

 - Added `CoreOptions` `PLUGIN_ALWAYS_PARENT_FIRST_LOADER_PATTERNS` and `PLUGIN_ALWAYS_PARENT_FIRST_LOADER_PATTERNS_ADDITIONAL`.
 - Using these options in `PluginConfig`, which is used by `PluginManager`.

## Verifying this change

 - Covered by streaming file sink e2e test.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (**yes** / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by AHeise** [comment]
We might need to update the documentation for the new config keys. We may also opt to keep them hidden for now.

**Comment by AHeise** [comment]
@flink run azure

**Comment by AHeise** [comment]
@flinkbot run azure

**Comment by AHeise** [comment]
@flinkbot run azure

**Comment by AHeise** [comment]
@flinkbot run azure

**Comment by AHeise** [comment]
@flinkbot run travis

**Comment by AHeise** [comment]
@flinkbot run travis

**Comment by pnowojski** [comment]
Travis looks green. Can you remove the first commit so I could merge it?

**Pull request merged**
