### PR TITLE
[FLINK-32000][webui] Expose max parallelism in the vertex detail drawer.

### PR DESCRIPTION
**Pull request by dmvk**
https://issues.apache.org/jira/browse/FLINK-32000

### CODE REVIEW

**Review by dannycranmer — APPROVED** [review]
LGTM, nice addition to the dashboard

**Comment by dmvk** [comment]
@flinkbot run azure

**Comment by dmvk** [comment]
@flinkbot run azure

**Comment by dmvk** [comment]
FlinkBot seems to be in some bizarre state. The CI has passed now, it just hasn't updated the comment. I guess it's related to the GH outage from yesterday.

**Pull request merged**
