### PR TITLE
[FLINK-7567]: Removed keepPartitioning parameter from iterate method

### PR DESCRIPTION
**Pull request by mlipkovich**
## What is the purpose of the change

Removed parameter keepPartitioning from DataStream#iterate method since it's ignored. Also slightly modified error message related to different parallelism levels of input and feedback streams

## Brief change log

  - Removed parameter keepPartitioning from DataStream#iterate 

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)  no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no) yes
  - The serializers: (yes / no / don't know) no
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know) no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / no / don't know) no

## Documentation

  - Does this pull request introduce a new feature? (yes / no) no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) not applicable

### CODE REVIEW

**Comment by mlipkovich** [comment]
As I understand the build has failed because of changed API method. The method which was changed has annotation PublicEvolving so there should be a way to change it. As was mentioned by @aljoscha 
https://issues.apache.org/jira/browse/FLINK-7567 there is no way to create a method with updated API and to deprecate the current one because of the default parameter

**Comment by aljoscha** [comment]
You can try and run the build locally to have a look at the file generated by the compatibility plugin. Then we can figure out why it's complaining.

**Comment by mlipkovich** [comment]
The local build works fine. If you mean `mvn verify` by compatibility plugin it also worked with no issues

**Comment by aljoscha** [comment]
A local build of `mvn clean verify` fails for me because the japicmp plugin is complaining. The relevant section of the diff output from japicmp is
```
***! MODIFIED CLASS: PUBLIC org.apache.flink.streaming.api.scala.DataStream  (not serializable)
	---! REMOVED METHOD: PUBLIC(-) boolean iterate$default$3()
	+++  NEW METHOD: PUBLIC(+) org.apache.flink.streaming.api.scala.DataStream setMaxParallelism(int)
	***  MODIFIED ANNOTATION: scala.reflect.ScalaSignature
```

i.e. it's complaining about `iterate$default$3()`. The problem seems to be that Scala will generate some obfuscated method name for the `iterate()` method and the `@PublicEvolving` annotation is not properly applied to that. I tried playing around with the japicmp config in the root pom file but to no avail. Maybe you can find something that works.

What I added is this:
```							<exclude>org.apache.flink.streaming.api.scala.DataStream#iterate$default$3()</exclude>
```

but it seems that doesn't work.

**Comment by mlipkovich** [comment]
Thansk, Aljoscha 
Probably I've forgotten to run `clean`. 
The method `iterate$default$3` is a method which automatically created by Scala for calculation of default value for parameter `keepPartitioning`. I tried different ways to exclude it but it didn't help. Anyway it should be somehow tracked by japicmp so I created the issue there
https://github.com/siom79/japicmp/issues/176

**Comment by aljoscha** [comment]
Thanks! This doesn't help us with our situation, though.

**Comment by mlipkovich** [comment]
Hi @aljoscha 
It turned out that exclude filter works if we escape dollar signs. I commited these changes, but I believe it still should be fixed by japicmp
What do you think about merging this PR?

**Comment by aljoscha** [comment]
Perfect! Thanks for working on this. 👍 

I merged, could you please close this PR?

**Comment by mlipkovich** [comment]
Thanks! Closing it

**Pull request closed without merging**
