### PR TITLE
[FLINK-27529] [connector/common] Fix Integer Comparison For HybridSource sourceIndex

### PR DESCRIPTION
**Pull request by varun1729DD**

### CODE REVIEW

**Comment by tweise** [comment]
Earlier PR for this: https://github.com/apache/flink/pull/19654

Would you mind updating the JIRA number on this PR to refer to https://issues.apache.org/jira/browse/FLINK-27529? 

Do you see a reasonable way to have test coverage for this?

**Comment by varun1729DD** [comment]
> Earlier PR for this: #19654
> 
> Would you mind updating the JIRA number on this PR to refer to https://issues.apache.org/jira/browse/FLINK-27529?
> 
> Do you see a reasonable way to have test coverage for this?

Should be possible; I had tests internally. Update JIRA ticket. Will ping back here

**Comment by varun1729DD** [comment]
@flinkbot run azure

**Comment by varun1729DD** [comment]
@tweise can you help me run the CI/CD please?

**Comment by tweise** [comment]
@flinkbot run azure

**Comment by tweise** [comment]
@varun1729DD whoops, it appears the CI already run for the most recent commit.

**Review by tweise — APPROVED** [review]

**Pull request merged**
