### PR TITLE
[FLINK-3367] Add PublicEvolving and Internal annotations to classes in API modules

### PR DESCRIPTION
**Pull request by fhueske**
This PR includes the commit from #1599.

It adds annotations to all classes in the following modules:
- `flink-core`
- `flink-java`
- `flink-scala`
- `flink-streaming-java`
- `flink-streaming-scala`

By adding annotations to every class, annotation management becomes easier and we can enforce annotations for all new classes in our API modules.

### CODE REVIEW

**Comment by aljoscha** [comment]
Some of the internal sinks sources, such as File* Socket are Internal while others are PublicEvolving. Is there a reason behind this?

**Comment by fhueske** [comment]
The motivation for this was to to make those Internal which can be added via the ExecutionEnvironment. Sources that offer configuration parameters which are not accessible via the ExecutionEnvironment are PublicEvolving. 
Does that make sense or should we make all PublicEvolving?

**Comment by aljoscha** [comment]
I see. Might seem inconsistent, though. :smile: So maybe we should make all of them PublicEvolving.

**Comment by rmetzger** [comment]
Except for two questions, the PR looks good to merge.

**Comment by fhueske** [comment]
Updated and rebased the PR. 
Any objections to merge?

**Comment by fhueske** [comment]
Merging this

**Pull request closed without merging**
