### PR TITLE
[FLINK-17289][docs]Translate tutorials/etl.md to chinese

### PR DESCRIPTION
**Pull request by liying919**
## What is the purpose of the change

Translate tutorials/etl.md to chinese.

## Brief change log

- etl.zh.md is changed into Chinese version.

## Verifying this change

This change is a trivial rework without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no 
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature?  no

### CODE REVIEW

**Comment by liying919** [comment]
> 
> ## CI report:
> 
>     * [dd93ed5](https://github.com/apache/flink/commit/dd93ed53068426549218864c3b4f278bab0929a5) Travis: [FAILURE](https://travis-ci.com/github/flink-ci/flink/builds/163638645) Azure: [PENDING](https://dev.azure.com/apache-flink/98463496-1af2-4620-8eab-a2ecc1a2e6fe/_build/results?buildId=554)
> 
> 
> Bot commands
> The @flinkbot bot supports the following commands:

Hi @rmetzger, could you please tell me how to deal with the Travis timeout failure? I find it happend during test in libraries which is not changed in this PR.

**Comment by liying919** [comment]
>     * @flinkbot run azure

@flinkbot run azure

**Comment by liying919** [comment]
@flinkbot run azure

**Comment by rmetzger** [comment]
I don't think there's a way to fix these Travis failures. But Travis and Azure are testing the same. So if Azure is green, you don't need to worry about Travis.
We are in the process of decommissioning travis.

**Comment by liying919** [comment]
> 
> 
> I don't think there's a way to fix these Travis failures. But Travis and Azure are testing the same. So if Azure is green, you don't need to worry about Travis.
> We are in the process of decommissioning travis.

Got it. Thanks you for the reply :)

**Comment by klion26** [comment]
@liying919 thanks for your contribution, could you please rebase the newly master to resolve the conflict

**Comment by liying919** [comment]
> 
> 
> @liying919 thanks for your contribution, could you please rebase the newly master to resolve the conflict

Hi @klion26 ,  I've rebase the branch.

**Comment by klion26** [comment]
@liying919 thanks for the rebase. seems that there is something some, currently, there are 27 commits for this pr(including many other commits), could you please clean the history?

**Comment by liying919** [comment]
@klion26 It seems that the PR is closed during my rebasing it again. Should I open a new one or there's a way to reopen it?

**Comment by klion26** [comment]
@liying919 thanks for the work, I'll review the new pr late today.

**Pull request closed without merging**
