### PR TITLE
[FLINK-5467] Avoid legacy state for CheckpointedRestoring operators

### PR DESCRIPTION
**Pull request by StefanRRichter**
This PR fixes [FLINK-5467].

### CODE REVIEW

**Comment by StefanRRichter** [comment]
cc @uce @aljoscha

**Comment by uce** [comment]
I'm not aware of all implications of this change, but this fixes the problem I had. The operator does not checkpoint any legacy operator state.

+1 to merge from my side.

**Comment by aljoscha** [comment]
I think this should work. Could you go ahead and merge, @uce ?

**Comment by uce** [comment]
Yep.

**Comment by uce** [comment]
Although it feels like a good test is missing for this since no test caught it. @StefanRRichter Do you think it's feasible to add one?

**Comment by StefanRRichter** [comment]
I guess I could try and add an operator that implements ``CheckpointedRestoring`` to our ``RescalingITCase``.

**Comment by StefanRRichter** [comment]
I modified a test to catch this problem, as suggested.

**Comment by uce** [comment]
Thanks! I verified that the adjusted test fails before this fix and runs fine after the fix. I'm going to merge this to master and release-1.2.

**Pull request closed without merging**
