### PR TITLE
[FLINK-23570][Documentation] Update the maven dependency of the File Sink page in the document

### PR DESCRIPTION
**Pull request by ericliuk**
## What is the purpose of the change

*Update the maven dependency of the File Sink page in the document.
There is a problem with some maven dependencies in the documentation. Chinese and English documentation is not consistent. Some maven dependencies are not available.*

## Brief change log

  - *Update maven dependencies*

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by zentol — CHANGES_REQUESTED** [review]
I think there are more occurrences now that the scala-suffix was removed from flink-runtime.

**Comment by ericliuk** [comment]
I have checked other dependencies. So far, only these two dependencies have been found to be problematic.

**Comment by zentol** [comment]
For 1.13 that is indeed likely the case.
For master however, [this|https://github.com/apache/flink/blame/master/docs/content/docs/dev/datastream/testing.md#L155] reference needs to be changed as well.

**Comment by ericliuk** [comment]
I have updated the flink-runtime dependency.
I removed the {{ $scalaVersion := .Get 1 }} code from [docs/layouts/shortcodes/artifact.html]. Because it will cause artifactId to always increment scalaversion.
And there is already code above this line of code to determine whether scalaversion should be added or not, and this line of code will cause the result of the previous judgment to change incorrectly.

**Pull request merged**
