### PR TITLE
[FLINK-7645][docs] Modify system-metrics part show in the document

### PR DESCRIPTION
**Pull request by yew1eb**
wx20170921-141945 2x

### CODE REVIEW

**Comment by yew1eb** [comment]
wx20170921-141945 2x

**Comment by yew1eb** [comment]
@uce  Let me know your thoughts on it. :)

**Comment by uce** [comment]
Hey @yew1eb, I like this 👍  I think it really makes sense to make this browsable from the table of contents. @zentol What do you think? I would be in favour of merging this if you don't have any objections.

**Comment by zentol** [comment]
merging.

**Pull request closed without merging**
