### PR TITLE
[FLINK-14100][jdbc] Added Oracle dialect

### PR DESCRIPTION
**Pull request by fpompermaier**
## What is the purpose of the change

Add the implementation of the Oracle dialect for JDBC connectors

## Brief change log

- Implemented OracleDialect extending AbstractDialect in JDBCDIalects
- Added default OracleRowConverter
- Added getMergeIntoStatement() into JDBCDialect to handle upsert

## Verifying this change

I tested this change connecting directly to a running database (but I didn't cover all the types).

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): *no*
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: *no*
  - The serializers: *no*
  - The runtime per-record code paths (performance sensitive): *no*
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: *no*
  - The S3 file system connector: *no*

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? docs

### CODE REVIEW

**Comment by eskabetxe** [comment]
@fpompermaier could you solve the conflicts..
@wuchong could you check this

**Comment by cmdares** [comment]
https://ci.apache.org/projects/flink/flink-docs-release-1.12/zh/dev/table/connectors/jdbc.html

Database | Upsert Grammar
-- | --
MySQL | INSERT .. ON DUPLICATE KEY UPDATE ..
PostgreSQL | INSERT .. ON CONFLICT .. DO UPDATE SET ..
**Oracle|Merge into
merge into [target-table] A using [source-table sql] B on ([conditional expression] and [...]...)
when matched then [update sql] 
when not matched then [insert sql]**

**Comment by qinjunjerry** [comment]
@fpompermaier anything pending before the conflicts can be solved and the PR to be merged?

**Comment by eskabetxe** [comment]
I resolved the conflicts and update to new changes introduced in https://issues.apache.org/jira/browse/FLINK-24253 here https://github.com/apache/flink/pull/17676

**Comment by MartijnVisser** [comment]
@eskabetxe Could it be that the commit hasn't been pushed yet? The latest commit I see 8ab267b861904c026a6fa30e98d21742c83d9979 from the 8th of March 2020?

**Comment by MartijnVisser** [comment]
@eskabetxe I misread your comment, thanks for the PR! I'll try to find a reviewer for that.

**Comment by leonardBang** [comment]
Thanks @fpompermaier and @eskabetxe for the contribution to support Oracle Database, I close this PR now.

**Pull request closed without merging**
