### PR TITLE
[FLINK-2386] Rework Kafka consumer for Flink

### PR DESCRIPTION
**Pull request by StephanEwen**
This is a reworked and extended version of #996 . It also build on top of #1017 

It improves the Kafka consumer, fixes bugs, and offers pluggable *fetcher* and *offset committer* to make it work across Kafka versions from 0.8.1 to 0.8.3 (upcoming).

## Functionality

  - The Kafka consumer properly preserves partitioning across failures/restart.
  - Pluggable fetchers / committers for multiple Kafka versions interoperability
    - Fetcher based on the low level consumer API
    - Fetcher based on the upcoming new consumer API (backported and included in the Flink Kafka consumer).
  - Proper cancelability
  - The test coverage is vastly improved.

## Tests

This pull request includes a set of new thorough test for the Kafka consumer

  - Preserving of partitioning and exactly once behavior for
    - 1:1 source to kafka partition mapping
    - 1:n source to kafka partition mapping
    - n:1 source to kafka partition mapping
  - Broker failure
  - Cancelling
    - After immediate failures during deployment
    - While waiting to read from a partition
    - While currently reading from a partition
  - Commit notifications for checkpoints
  - Large records (30 MB)
  - Alignment of offsets with what is committed into ZooKeeper
  - Concurrent produce/consumer programs

## Limitations

The code based on the low-level consumer seems to work well.

The high-level consumer does not work with very large records It looks like a problem in the backported Kafka code, but it is not 100% sure.

## Debug Code

This pull request includes some debug code in the `BarrierBuffer` that I intend to remove. It is there to track possible cornercase problems in the checkpoint barrier handling.

### CODE REVIEW

**Comment by rmetzger** [comment]
How about dropping the backported Kafka code and relying completely on our own implementation against the SimpleConsumer API?
We would need to implement the `KafkaConsumer.partitionsFor()` method ourselves, but I think that's doable.

**Comment by StephanEwen** [comment]
I like this idea a lot. The backported code is not very stable anyways...

**Comment by rmetzger** [comment]
I've opened a pull request with the code removed against your branch: https://github.com/StephanEwen/incubator-flink/pull/14

**Comment by hsaputra** [comment]
So is the #1039 depends on this one?

**Comment by hsaputra** [comment]
Since it is rebased to #1039 already, could this one be closed and do review on that one instead?

**Comment by rmetzger** [comment]
Yes, I think we can close this issue.

**Comment by StephanEwen** [comment]
Subsumed by #1039

**Pull request closed without merging**
