### PR TITLE
repalce map.put with putIfAbsent

### PR DESCRIPTION
**Pull request by RebornHuan**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [ ] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [ ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by NicoK** [comment]
Although this totally makes sense and would be nice to change, we cannot merge it until Java 7 has been dropped (as you see from the TravisCI runs).

**Comment by greghogan** [comment]
@RebornHuan please provide a brief description of the purpose of this change.

**Comment by greghogan** [comment]
@RebornHuan although this change looks to be correct and makes good use of the newer API, there is a trade-off between deleting a line of code called during an error condition and the risk of such small refactorings. I don't think we have a demonstrated benefit to making this change.

**Comment by NicoK** [comment]
but honestly, the previous approach just looks wrong: adding it and in case of a conflict reverting that `put` operation.
What if (and I'm walking in the dark here) something already operates on the invalidly registered task (is this run in parallel?). I cannot spot any parallel use though...

**Comment by zentol** [comment]
The TaskManager class is about to be removed.

**Pull request closed without merging**
