### PR TITLE
[FLINK-22311] [connector/jdbc] Validate maxRetries for XA Sink

### PR DESCRIPTION
**Pull request by afedulov**
This PR continues work done in https://github.com/apache/flink/pull/15674 and addresses the remaining comments.

### CODE REVIEW

**Comment by afedulov** [comment]
@rkhachatryan, PTAL

**Review by rkhachatryan — APPROVED** [review]
Thanks a lot for the PR @afedulov !

Please update `JdbcExactlyOnceSinkE2eTest` (`.withMaxRetries` is not necessary anymore).

Otherwise, LGTM.

**Comment by afedulov** [comment]
Thanks, @rkhachatryan. I guess it is still needed, but on `JdbcExecutionOptions` instead of where I placed it (not sure what happened there :)

**Comment by afedulov** [comment]
Fixed, the test passes now.

**Comment by afedulov** [comment]
@flinkbot run azure

**Pull request merged**
