### PR TITLE
Fix Javadoc links in documentation

### PR DESCRIPTION
**Pull request by aljoscha**

### CODE REVIEW

**Comment by aljoscha** [comment]
on master the link would have to be changed, just like we currently change the javadoc_version entries. But with this we move the part that doesn work for snapshot release out of the actual content files. I mean this part: `https://ci.apache.org/projects/flink/flink-docs-release-{{site.version_javadocs}}`

**Comment by aljoscha** [comment]
More details: currently, we have `version_javadocs` and `version_scaladocs` in `_config.yml` that we need to update when changing branches. The actual javadocs link is hardcoded in `sidenav.html` to `https://ci.apache.org/projects/flink/flink-docs-release-{{site.version_javadocs}}`, which doesn't work on the master branch. That's why I'm changing it to this scheme, where we only have to upadte `javadocs_baseurl` when switching between branches.

And I also have a follow-up PR for documentation where I want to put in Javadoc links. For this I'd like to use `javadocs_baseurl` instead of adding more instances of the problematic, hardcoded url.

**Comment by zentol** [comment]
but the scripts aren't adjusted to update the link, so for the next release branch this will be broken again.

**Comment by aljoscha** [comment]
The scripts never worked because they are not applied on the `release-X` branch, i.e. not on `release-1.6`. `update_release_branch` is applied on master, where it also doesn't work. Updating those links is a manual process, step 12 [here](https://cwiki.apache.org/confluence/display/FLINK/Creating+a+Flink+Release). This is the manually added commit for 1.6: https://github.com/apache/flink/commit/2f13f001efe0a5065ea1b71b1fa872785c437376.

@zentol I can expand step 12 in the release guide, WDYT?

**Comment by zentol** [comment]
`update_release_branch` doesn't exist. `update_branch_version.sh` is applied to master, but the commit is also contained in the `release-X.Y` branches, and as seen in 8d180d5fa69a68a7023b052f83e51ca6a3d35256 it does correctly modify the versions.

What exactly isn't working? If it doesn't work, why not fix it instead of introducing manual steps yet again?

**Comment by zentol** [comment]
ah, you mean the snapshot javadocs aren't working for the snapshot branches as well. Still, can't we fix this trivially in `update_branch_version.sh` by extending it?

**Comment by aljoscha** [comment]
`update_branch_version.sh` is only used on master to update, e.g. `1.6-SNAPSHOT` to `1.7-SNAPSHOT`. If we always point to the "master" docs from master we don't have to update anything. On the other hand, no script is currently ever applied on the `release-x.y` branch. That's why there is this manual step of updating the versions/links on a release branch

**Comment by aljoscha** [comment]
@zentol I already expanded the release guide and I will add `javadocs_baseurl` once I merge this.

**Pull request closed without merging**
