### PR TITLE
[FLINK-34455] Move RestoreMode from flink-runtime to flink-core

### PR DESCRIPTION
**Pull request by Zakelly**
## What is the purpose of the change

According to the FLIP-406, a new RecoveryOptions class will be introduced in flink-core, which contains options for RestoreMode. Thus the RestoreMode would better be moved to flink-core as well.

Although RestoreMode is @PublicEvolving, there is no public user interface usage of this class (normal user would only use it in configuration), so no breaking change introduced.

## Brief change log

 - Move `RestoreMode` to package `org.apache.flink.core.execution`
 - Change all imports of `RestoreMode`

## Verifying this change

This change is a trivial rework and is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (**yes** / no)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), **Checkpointing**, Kubernetes/Yarn, ZooKeeper: (**yes** / no / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by Zakelly** [comment]
@flinkbot run azure

**Comment by Zakelly** [comment]
@flinkbot run azure

**Review by fredia — APPROVED** [review]
@Zakelly Thanks for the PR, LGTM.

**Comment by Zakelly** [comment]
@fredia  Thanks for your review!

**Pull request merged**
