### PR TITLE
[FLINK-27387][hive] Hive dialect supports multi-insert statement

### PR DESCRIPTION
**Pull request by luoyuxia**
## What is the purpose of the change
To support multi-insert statement for Hive dialect.

## Brief change log
   - Construct `ModifyOperation` separately for each insert fragment in one single multi-insert statement.
   - Compose these `ModifyOperation`s  to `StatementSetOperation`.

## Verifying this change
The addition test in [...connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java](https://github.com/apache/flink/compare/master...luoyuxia:FLINK-27387?expand=1#diff-fb5fc4106e27e27f9968e59b643003444fd40af58aa2f147ac301009b53a47ca)#testMultiInsert

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented?  N/A

### CODE REVIEW

**Comment by luoyuxia** [comment]
@flinkbot run azure

**Comment by luoyuxia** [comment]
@flinkbot run azure

**Comment by wuchong** [comment]
Looks good to me in general. Btw, does it also support EXPLAIN? Could you add a test for it?

**Comment by luoyuxia** [comment]
> Looks good to me in general. Btw, does it also support EXPLAIN? Could you add a test for it?

Now, I add a test for explain in [testMultiInsert](https://github.com/apache/flink/pull/19647/files#diff-fb5fc4106e27e27f9968e59b643003444fd40af58aa2f147ac301009b53a47caR450)

**Review by wuchong — APPROVED** [review]
LGTM

**Pull request merged**
