### PR TITLE
[FLINK-19654][python][e2] merge pyflink table and dastream e2e tests

### PR DESCRIPTION
**Pull request by HuangXingBo**
## What is the purpose of the change

*This pull request will merge pyflink table and dastream e2e tests*

 
## Brief change log

  - *merge pyflink table and dastream e2e tests*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by rmetzger** [comment]
Thanks a lot for addressing this so quickly. The change looks good at first glance. Let's see how much e2e time improvement we get from this!

**Comment by rmetzger** [comment]
Could you rebase to latest master? then the e2e tests will pass.

**Comment by HuangXingBo** [comment]
@rmetzger Thanks a lot. I have rebase the master and push again.

**Review by dianfu — APPROVED** [review]
@HuangXingBo Thanks for the PR. LGTM. Merging...

**Pull request merged**
