### PR TITLE
[FLINK-15862][kafka] Remove deprecated KafkaPartitioner

### PR DESCRIPTION
**Pull request by dawidwys**
## What is the purpose of the change

Remove long deprecated `KafkaPartitioner`.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (**yes** / no)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by dawidwys** [comment]
cc @aljoscha

**Comment by aljoscha** [comment]
Yes, please, I like code removal. 👌Let's see if Travis is good but then I think this is good to merge.

**Comment by dawidwys** [comment]
@flinkbot run travis

**Comment by dawidwys** [comment]
@flinkbot run travis

**Comment by dawidwys** [comment]
Travis succeeded. I will merge this.

**Pull request merged**
