### PR TITLE
[FLINK-2898] [build] Invert Travis CI build order

### PR DESCRIPTION
**Pull request by greghogan**

### CODE REVIEW

**Comment by sachingoel0101** [comment]
Wrong title. :')

**Comment by greghogan** [comment]
Thanks for catching that! The commit log is correct, so it is puzzling why the pull request would have a different title.

**Comment by fhueske** [comment]
good to merge

**Comment by fhueske** [comment]
Will merge this PR

**Comment by rmetzger** [comment]
-1 This change breaks the nightly deployment. I'll reopen FLINK-2898.

**Pull request closed without merging**
