### PR TITLE
[FLINK-2493] Simplify names of example program JARs

### PR DESCRIPTION
**Pull request by chenliang613**
The names of example JARs have a bit annoying, propose to replace
"examples/flinnk-java-examples-0.10-SNAPSHOT-ConnectedComponents.jar"
with "examples/ConnectedComponents.jar"
1. Changing java and scala examples'  pom.xml, set finalName to replace
default name "artifactId+version+classifer".
2.update quickstart doc which referring to examples

### CODE REVIEW

**Comment by mbalassi** [comment]
Thanks for picking up the issue. Could you make the changes for the `flink-streaming-examples` and the `flink-storm-compatibility-example` modules too, please? Also travis suggests you have unintentionally broken some references.

**Comment by StephanEwen** [comment]
Here is a reference to the CI result: https://s3.amazonaws.com/archive.travis-ci.org/jobs/77474252/log.txt

You can always run `mvn clean verify` locally.

**Comment by chenliang613** [comment]
@mbalassi  OK, i will make changes for flink-streaming-examples and flink-storm-compatibility-example modules too.

**Comment by chenliang613** [comment]
@StephanEwen  sure! actually i did the "verify operation" at local machine.

At my local machine's log msg showing: got reference jar(as below)from central repository of Maven,so it could build successfully.

Downloading: http://repository.apache.org/snapshots/org/apache/flink/flink-java-examples/0.10-SNAPSHOT/flink-java-examples-0.10-20150827.224410-137.jar

**Comment by StephanEwen** [comment]
@chenliang613 Do you want to open another poll request with the fix?

**Comment by chenliang613** [comment]
@StephanEwen  yes.  may use another solution :)

**Pull request closed without merging**
