### PR TITLE
[FLINK-26835][serialization] Fix concurrent modification exception

### PR DESCRIPTION
**Pull request by ZhangChaoming**
## What is the purpose of the change

Fix concurrent modification exception.

## Brief change log

Fix concurrent modification exception.

## Verifying this change

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (**yes** / no / don't know)
  - The runtime per-record code paths (performance sensitive): (**yes** / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by ZhangChaoming** [comment]
@pnowojski  Could you please help to check this?

**Comment by ZhangChaoming** [comment]
@pnowojski  `ConcurrentHashMap` uses CAS ranther than ReentrenLock after jdk8, which has good performance in multi-thread condition as well as single condition.
> What are the two threads that are causing this concurrent modification exception?

I track all the usages of `subclassSerializerCache`, I can not find out the reason. I gess the `subclassSerializerCache.entrySet().stream()` is to blame.

**Comment by pnowojski** [comment]
I'm not so sure that the performance impact of `ConcurrentHashMap` won't be visible. And this change is on the performance sensitive per-record code path.

I would like to first understand why has this concurrent modification happened and if we can simply avoid it. This code should be not-thread safe for the sake of simplicity.

> I track all the usages of subclassSerializerCache, I can not find out the reason. I gess the subclassSerializerCache.entrySet().stream() is to blame.

But what are the two threads that are touching the same serialiser instance?

**Comment by ZhangChaoming** [comment]
@dawidwys @pnowojski Since I have no idear about the performance impact of `ConcurrentHashMap`, I aggree to @dawidwys' suggestion that alway duplicate a new serializer:

**Review by pnowojski — APPROVED** [review]
LGTM assuming green azure.

@ZhangChaoming , can you rebase on the latest master? It looks like you are basing on a bit old master branch which has some build failures like:
https://issues.apache.org/jira/browse/FLINK-26855

**Comment by pnowojski** [comment]
Thanks @ZhangChaoming . Merged

**Pull request merged**
