### PR TITLE
[FLINK-6774][build] set missing build-helper-maven-plugin version

### PR DESCRIPTION
**Pull request by NicoK**
this PR sets the version number on those sub-modules which did not set it yet

### CODE REVIEW

**Comment by rmetzger** [comment]
Change looks good.

I'll merge it once travis gives green light on my fork.

**Comment by rmetzger** [comment]
With the current travis situation, I can not validate this branch.

**Comment by zentol** [comment]
I could include this in my merge PR https://github.com/apache/flink/pull/4124 if you want @rmetzger

**Comment by rmetzger** [comment]
That would be nice, yes. Thx

**Pull request closed without merging**
