### PR TITLE
[FLINK-32871][SQL] Support BuiltInMethod TO_TIMESTAMP with timezone options

### PR DESCRIPTION
**Pull request by xuzifu666**
## What is the purpose of the change

https://issues.apache.org/jira/browse/FLINK-32871
as issue report，we need TO_TIMESTAMP function with timezone to choose like ： TO_TIMESTAMP('2023-08-10', 'yyyy-MM-dd', 'Asia/Shanghai')

as presto,trino,starrocks:
SELECT timestamp '2012-10-31 01:00 UTC' AT TIME ZONE 'America/Los_Angeles';
2012-10-30 18:00:00.000 America/Los_Angeles

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluster with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by xuzifu666** [comment]
cc @wuchong @twalthr   have a review plz，thanks

**Comment by xuzifu666** [comment]
@flinkbot run azure

**Comment by xuzifu666** [comment]
@flinkbot run azure

**Comment by xuzifu666** [comment]
@flinkbot run azure

**Comment by xuzifu666** [comment]
@flinkbot run azure

**Comment by xuzifu666** [comment]
@flinkbot run azure

**Comment by xuzifu666** [comment]
@flinkbot run azure

**Comment by xuzifu666** [comment]
@flinkbot run azure

**Comment by xuzifu666** [comment]
@flinkbot run azure

**Comment by xuzifu666** [comment]
@flinkbot run azure

**Comment by xuzifu666** [comment]
@flinkbot run azure

**Comment by xuzifu666** [comment]
@flinkbot run azure

**Comment by xuzifu666** [comment]
@flinkbot run azure

**Comment by xuzifu666** [comment]
cc @beyond1920

**Comment by xuzifu666** [comment]
@FangYongs could you have a review plz?

**Comment by xuzifu666** [comment]
@JingsongLi  could you have a review plz or closing the pr?  thanks~

**Comment by MartijnVisser** [comment]
There is no consensus on this Jira ticket, so closing this PR

**Pull request closed without merging**
