### PR TITLE
[FLINK-6299] make all IT cases extend from TestLogger

### PR DESCRIPTION
**Pull request by NicoK**
This way, currently executed tests and their failures are properly logged.

### CODE REVIEW

**Comment by zentol** [comment]
Looks good, +1 to merge.

**Comment by NicoK** [comment]
Strangely, this does not yet provide logging for all test cases. After also applying #3708, `HBaseConnectorITCase`, for example does show up in the `flink-fast-tests-a` standard output but neither in `1.log` nor `2.log`...
let me test this further

**Comment by NicoK** [comment]
actually, the error was in the flink-hbase `pom.xml` - please let me include these hotfixes here as well which fix the actual error and prevent future errors.

**Comment by zentol** [comment]
merging.

**Pull request closed without merging**
