### PR TITLE
[FLINK-2778] Add API for non-parallel non-keyed Windows

### PR DESCRIPTION
**Pull request by aljoscha**
This adds two new operators for non-keyed windows: Regular trigger
operator and evicting trigger operator.

This also adds the API calls nonParallelWindow(...) on DataStream and
the API class NonParallelWindowDataStream for representing these
operations.

This also adds tests for both the operators and the translation from API
to operators.

### CODE REVIEW

**Comment by gyfora** [comment]
Why do we have nonParallelTimewindow in the API? I would assume that time windows can always be prallel.

**Comment by aljoscha** [comment]
They are called `nonParallel` there because non-keyed windows cannot be computed in parallel in the general case. (The general case is when you want to evaluate the window over all elements in a map-style function). Only in special cases can the window be pre-computed in parallel and then merged.

**Comment by aljoscha** [comment]
But you are right, nonParallelWindow is maybe a bit overkill. We should find a better alternative.

The intention was to clearly differentiate them from keyed windows, which can always be computed in parallel.

**Comment by aljoscha** [comment]
What about `windowAll`? (And `timeWindowAll`)

**Comment by StephanEwen** [comment]
I am okay with `windowAll()`. In my opinion, it would be important that the windowing without keys has a different name than the windowing with keys. It will not be be parallel in many cases and a variation in the keyword should help the user realize that the implications of that "global" window are a bit different than those of the "by-key" window.

I'd like to merge this now. We can keep discussing about the exact names, but there are several followup pieces for full event time support that depend on this.

**Comment by gyfora** [comment]
+1

**Comment by aljoscha** [comment]
I changed it already.

**Comment by aljoscha** [comment]
Manually merged...

**Pull request closed without merging**
