### PR TITLE
[utils] Missing getters for ParameterTool

### PR DESCRIPTION
**Pull request by mbalassi**
When using the `ParameterTool` I have found the `Boolean` getter missing, so added the missing functions.

### CODE REVIEW

**Comment by chiwanpark** [comment]
Looks good to merge. +1

**Comment by rmetzger** [comment]
Can you add tests for the methods? I think there is already a class with tests for all methods.

**Comment by mbalassi** [comment]
@rmetzger, sure, somehow I missed those tests. Now fixed.

**Comment by rmetzger** [comment]
Great, thank you.

+1 to merge

**Pull request closed without merging**
