### PR TITLE
[FLINK-7343][kafka] Increase Xmx for tests

### PR DESCRIPTION
**Pull request by pnowojski**
As reported by @NicoK, sometimes 1000m was not enough memory to run at-least-once tests with broker failures on Travis. I remember having the same issue in #4239 where I have set this same value to `2048`. Hopefully it will solve the problems.

### CODE REVIEW

**Comment by greghogan** [comment]
+1 this matches the parent `pom.xml`. Wondering if the same change would fix `flink-hbase` always failing for me when running `mvn verify`.

**Comment by NicoK** [comment]
yes, seems like it was changed from `-Xmx800m` to `-Xmx1536m` by FLINK-6128 and again to `-Xmx2048m` by FLINK-7004 without changing it here. The question should rather be whether we need the specialised options anyway or whether we can remove them.
I tested the latter (removing the `<argLine>...</argLine>` lines but keeping the `<forkCount>1</forkCount>`) and then the root pom's values are inherited which may be a better solution anyway.

**Comment by pnowojski** [comment]
@NicoK sounds reasonable however this will drop `-UseGCOverheadLimit` flag. It should be fine when at the same time we increase the `Xmx`. Btw, having `UseGCOverheadLimit` seems a little bit fishy in the first place...

Pushing fixup with inheriting values from the parent pom.

**Comment by tzulitai** [comment]
+1, LGTM.

**Comment by zentol** [comment]
merging.

**Comment by pnowojski** [comment]
Thanks :)

**Pull request closed without merging**
