### PR TITLE
[FLINK-34190][FLIP-416][checkpoint] Deprecate RestoreMode#LEGACY

### PR DESCRIPTION
**Pull request by Zakelly**
## What is the purpose of the change

In FLIP-416, we decided to deprecate and remove the RestoreMode#LEGACY. This PR facilitate the deprecation.

## Brief change log

  - Annotate RestoreMode#LEGACY with @\Deprecated
  - Doc
  - Deprecation messages in CLI and REST API

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (**yes** / no)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), **Checkpointing**, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / **docs** / **JavaDocs** / not documented)

### CODE REVIEW

**Comment by Zakelly** [comment]
@flinkbot run azure

**Comment by Zakelly** [comment]
Hi @masteryhx , would you please review this one?

**Review by masteryhx — CHANGES_REQUESTED** [review]
Thanks for the pr.
Found Other places:
1. The description in CliFrontendParser#SAVEPOINT_RESTORE_MODE
2. The exception message in SourceStreamTask#triggerCheckpointAsync

Could you also modify them ?

**Review by masteryhx — APPROVED** [review]
Thanks for the update.
LGTM.

**Comment by masteryhx** [comment]
merged f7a2819f...bed79d33 into master

**Pull request closed without merging**
