### PR TITLE
[FLINK-13023][hive] Generate HiveTableSource from a Hive table

### PR DESCRIPTION
**Pull request by xuefuz**
## What is the purpose of the change

Provide implementation of generating HiveTableSource instance from a Hive table, as part of Hive data connector work.

Please note that the PR includes changes in PR #8890 

## Brief change log

  - Added implementation in HiveTableFactory
  - Refactored HiveTableSource and HiveTableInputformat classes
  - Added corresponding tests

## Verifying this change

This change added UT tests .

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by xuefuz** [comment]
cc: @bowenli86, @terry, @lirui-apache

**Comment by bowenli86** [comment]
@xuefuz thanks for your contribution!

LGTM, will merge once Travis build passes

@flinkbot approve all

**Comment by bowenli86** [comment]
There's a compile failure in flink-table-common. I don't think that's because of this PR, thus I restarted the build to see if that's fixed already by someone else.

**Comment by xuefuz** [comment]
Thanks for the review. Not sure it was due to the inclusion of #8890, but I rebased to master to retest.

**Comment by bowenli86** [comment]
Merging

**Comment by bowenli86** [comment]
merged in 1.9.0: b867750b4ba8b58767aa600d732fbfa5fd7c64fe

**Pull request closed without merging**
