### PR TITLE
[FLINK-11161]Unable to import java packages in scala-shell

### PR DESCRIPTION
**Pull request by shuiqiangchen**
## What is the purpose of the change

To solve the problem of unable to import java packages in scala-shell. There is no need to import org.apache.flink.table.api_ initially since we seldom use the class/object under the directory after scala shell started up.

## Brief change log

remove org.apache.flink.table.api._ in importLists in FlinkILoop.scala

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no) no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no) no
  - The serializers: (yes / no / don't know) no
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / no / don't know) no
  - The S3 file system connector: (yes / no / don't know) no

## Documentation

  - Does this pull request introduce a new feature? (yes / no) no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) no

### CODE REVIEW

**Comment by zjffdu** [comment]
Thanks @shuiqiangchen Could you add unit test ?

**Comment by zjffdu** [comment]
ping @shuiqiangchen

**Comment by shuiqiangchen** [comment]
> ping @shuiqiangchen

Sorry for the late reply! I'm thinking about the coverage of unit tests and will finish it soon.

**Comment by twalthr** [comment]
@sunjincheng121 could you take a look at this PR?

**Comment by zentol** [comment]
JIRA has been closed.

**Pull request closed without merging**
