### PR TITLE
[FLINK-1389] Allow changing the filenames of the files created when writing to a directory

### PR DESCRIPTION
**Pull request by rmetzger**
...

### CODE REVIEW

**Comment by StephanEwen** [comment]
I like the idea for that.

I am, though, not a big fan of configuring the output format through the config. I think there was also a consensus to move away from this and use regular parameters (getters and setters) instead.

Why do we need an extra variable for that anyways? Can we not simply make the `%n` part of the path?

**Comment by StephanEwen** [comment]
We could also think about allowing formats to define default extensions.

**Comment by rmetzger** [comment]
Thank you for the feedback.
I'll rework the pull request soon.

**Comment by StephanEwen** [comment]
BTW: How is that done in Hadoop? Can we follow a similar way, to make it easier for users to understand this?

**Comment by rmetzger** [comment]
Hadoops `FileOutputFormat` has the following method
```java
 public static String getUniqueName(JobConf conf, String name) {
    int partition = conf.getInt(JobContext.TASK_PARTITION, -1);
    if (partition == -1) {
      throw new IllegalArgumentException(
        "This method can only be called from within a Job");
    }

    String taskType = (conf.getBoolean(JobContext.TASK_ISMAP, true)) ? "m" : "r";

    NumberFormat numberFormat = NumberFormat.getInstance();
    numberFormat.setMinimumIntegerDigits(5);
    numberFormat.setGroupingUsed(false);

    return name + "-" + taskType + "-" + numberFormat.format(partition);
  }
```
So users have to overwrite the method if they want to use a custom filename.

I'll remove the configuration-based approach.

**Comment by rmetzger** [comment]
I've updated the pull request. Please review again, I would like to merge this soon.

**Comment by fhueske** [comment]
The change looks good, but do why do we need two parameters for 0- and 1-offset indices?
I would only keep the 1-offset index (current behavior).

If you think we really need both, go ahead and merge it ;-)

**Comment by StephanEwen** [comment]
Nice mechanism, +1

I agree with Fabian, having one method should be good, or have you seen a hard requirement for 0-based counters in the file names?

**Comment by rmetzger** [comment]
The only reason why I added the two variants is that I want to give users freedom to choose between these two variants. Its one more line of code that might (someday) make a user happy.

I hope you agree with me that its easier and more efficient for me now to just merge it as it is rather than removing the feature again?

**Comment by fhueske** [comment]
To be honest, I find this additional option more confusing than helpful.

**Comment by rmetzger** [comment]
Okay. Let me implement a different approach that allows users to overwrite a method to put anything they want for the file name.

**Comment by rmetzger** [comment]
I've completely changed the mechanism of setting a custom file name.

**Comment by fhueske** [comment]
Hmmm, using the String pattern seems to be much more comfortable for users, no?

If a user wants to have the data written out with some kind of filename pattern, she needs to implement a new IF and overwrite a method instead of simply setting a configuration parameter.
The only thing you gain is that you can do some "fancy" arithmetics (+/- 1) with the task number.
Not sure if that's worth it. The former way was very elegant and clean, IMO.

If you persist on the having the option to choose between 0 and 1-based indexing, I would vote to go with the former variant and keep both parameters.

**Comment by rmetzger** [comment]
The user who requested this feature actually asked for a custom method to overwrite.

There is one more important use-case for a custom method: If users want to have files named exactly like hadoop, they also need a method. Hadoop is using 6-digit numbers, filled up with zeroes (for example part-m-000001).

I'm tired of changing the pull request until everybody is happy. Its very inefficient and I have better stuff to do with my time. If you want, you can change the code once its merged, but I have rewritten this 3 times now.

**Comment by fhueske** [comment]
Well, you would have saved everybody's time of you had made this requirements clear from the beginning. Besides your first two versions didn't comply with these new requirements either...

**Comment by rmetzger** [comment]
You are right, I should have made the requirements clear in the beginning. I actually had a discussion with the user which approach is the best.
I took the view that a string based method is easier for now and implemented it.
Then, we had the whole discussion here and I thought, now, that everybody is unhappy with my approach, I better do exactly what the user wants, instead of going with a strong opinion.

And now I'm confused and upset. But to be realistic: We only had one user so who wanted to change the filenames at all. If there is ever going to be a second or third user, they either have to do another contribution or overwrite their input format. 

http://bikeshed.com/ (see also: http://en.wikipedia.org/wiki/Parkinson%27s_law_of_triviality)

**Comment by fhueske** [comment]
No worries ;-) I understand that discussing such a "trivial" feature feels like a waste of time. Unfortunately these are the features that are easy to comment on for "everybody" ;-)

Anyway, I guess we could have both methods besides each other if this becomes an issue, i.e., add your String approach as configuration option to FileInputFormat and interprete it in the default `getDirectoryFileName()` method.

For now, you got my +1 for this change. It does not change the default behavior and adds a feature.

**Pull request closed without merging**
