### PR TITLE
[FLINK-11099][Table API&SQL] Migrate flink-table runtime  CRow  Types classes

### PR DESCRIPTION
**Pull request by XuQianJin-Stars**
## What is the purpose of the change

*(To Migrate flink-table runtime  CRow  Types classes.)*

## Brief change log

*(for example:)*

- *Migrate `CRow.Scala` to `CRow.Java` and write it into the `flink-table-common` directory.*
- *Migrate `CRowComparator.Scala` to `CRowComparator.Java` and write it into the `flink-table-common` directory.*
- *Migrate `CRowSerializer.Scala` to `CRowSerializer.Java` and write it into the `flink-table-common` directory.*
- *Migrate `CRowTypeInfo.Scala` to `CRowTypeInfo.Java` and write it into the `flink-table-common` directory.*
- *In addition, there are other file changes due to the above four file changes*

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*

- *Added integration tests for end-to-end deployment with large payloads (100MB)*
- *Extended integration test for recovery after master (JobManager) failure*
- *Added test that validates that TaskInfo is transferred only once across recoveries*
- *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

- Dependencies (does it add or upgrade a dependency): (yes / no)
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
- The serializers: (yes / no / don't know)
- The runtime per-record code paths (performance sensitive): (yes / no / don't know)
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / no / don't know)
- The S3 file system connector: (yes / no / don't know)

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by xueyumusic** [comment]
Hi, @XuQianJin-Stars , according to FLIP-28 it looks CRows may need to migrate into flink-table-runtime module. This moudle will be set up, is it right? @twalthr

**Comment by XuQianJin-Stars** [comment]
@xueyumusic According to the description, flink-table will be removed as the top-level module.Something seems to be wrong.

**Comment by twalthr** [comment]
@xueyumusic yes, the module structure will be setup soon. Once the discussion about the new structure has finished. @XuQianJin-Stars you can put your ported class in `flink-table` for now. We can update the PR once the new structure is ready. I think this will happen in the next few days.

**Comment by XuQianJin-Stars** [comment]
hi @twalthr Well, look forward to it .
thanks
qianjin

**Comment by twalthr** [comment]
@XuQianJin-Stars no need for a new PR, just update the branch or do a force push. Thanks.

**Comment by XuQianJin-Stars** [comment]
@twalthr I update the branch or do a force push. 
thanks
qianjin

**Pull request closed without merging**
