### PR TITLE
[FLINK-6628] Fix start scripts on Windows

### PR DESCRIPTION
**Pull request by zentol**
This PR fixes the `flink-daemon.sh` and `taskmanager.sh` script for cygwin for directories containing spaces.
They were broken in 11c868f91db773af626ac6ac4dcba9820c13fa8a.

The change in the daemon script is straight-forward; to prevent the path containing the space to be interpreted as to arguments we wrap it in `"` which causes the entire path, including the space, to be passed  as a single argument.

The change in the taskmanager script is as subtle as it gets. When storing the call like this `TM_COMMAND="${FLINK_BIN_DIR}/flink-daemon.sh $STARTSTOP taskmanager ${args[@]}"` and executing it later spaces are once again used to separate arguments, breaking the execution. We can't use the trick used above, since then the entire expressions is used as a single argument (i.e. path to an executable) which obviously fails.

### CODE REVIEW

**Comment by greghogan** [comment]
This affects more than Windows ... at least MacOS and I expect Linux as well.

Also need to update `rotateLogFilesWithPrefix` in `config.sh` to: `rotateLogFile "$log"`.

**Comment by zentol** [comment]
@greghogan done.

**Comment by greghogan** [comment]
+1 and to fix in 1.3.0

**Comment by zentol** [comment]
merging.

**Pull request closed without merging**
