### PR TITLE
[FLINK-5039] Bump Avro version

### PR DESCRIPTION
**Pull request by rmetzger**
This is a critical issue for some of our users.

### CODE REVIEW

**Comment by rmetzger** [comment]
Rebased to master to include fixed build.

**Comment by davetorok** [comment]
Thanks for this!  I was going to PR yesterday but you beat me to it.  Successfully running 25,825,230 Avro / GenericRecords in the past 48 hrs.

**Comment by StephanEwen** [comment]
+1 to merge this for 1.2 and 1.1.4

**Comment by fhueske** [comment]
+1 
Merging

**Pull request closed without merging**
