### PR TITLE
[backport to 1.9][FLINK-14145] Fix getLatestCheckpoint(true) returns wrong checkpoint

### PR DESCRIPTION
**Pull request by gyfora**
Backporting of the fix that is already merged to master

### CODE REVIEW

**Comment by wuchong** [comment]
Hi @TisonKun , @1u0 , @gyfora  do we have a consensus whether backport this to 1.9?

**Comment by TisonKun** [comment]
@wuchong this pull request fixes the bug where the CompletedCheckpointStore would not return the last checkpoint correctly if checkpoints are preferred. It is definitely a bug fix and I think we are able to include this in a bugfix version.

**Comment by gyfora** [comment]
I agree, this is a critical fix, that fixes a currently completely broken feature.

I have merged this to 1.9 and closing the PR

**Comment by wuchong** [comment]
Thanks @gyfora for merging this.

**Pull request closed without merging**
