### PR TITLE
[FLINK-14096][client] Merge NewClusterClient into ClusterClient

### PR DESCRIPTION
**Pull request by TisonKun**
## What is the purpose of the change

With the effort under FLINK-10392 we don't need the bridge class NewClusterClient any more. We can just merge NewClusterClient into ClusterClient towards an interface-ized ClusterClient.

cc @tillrohrmann @aljoscha @kl0u 

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by kl0u** [comment]
Hi @TisonKun, as I wrote in the JIRA, this is a big change and it is worth giving it some more visibility than just a sub-issue in a JIRA by discussing it in the user and dev mailing list first.

**Comment by TisonKun** [comment]
close as no consensus

**Comment by TisonKun** [comment]
Thanks for your attention @kl0u !

**Comment by TisonKun** [comment]
@flinkbot run travis

**Comment by TisonKun** [comment]
Hi @kl0u, thanks for your review. Could you help me merge this pull request? Study from ZK community they always prevent themselves from merging their own pull requests. I think it explicitly follows the best practice that involve fellow committers when pushing a commit without too much overhead :-)

**Comment by kl0u** [comment]
Hi @TisonKun, in the Flink community, committers merge their own PRs as long as they have at least one +1 from another committer. After merging this PR and when closing the JIRA issue please add a note to the Jira ticket with the commit hash on the master. As an example, have a look here https://issues.apache.org/jira/browse/FLINK-13959.

Let me know if you need any help :)

**Comment by TisonKun** [comment]
Thanks for your explanation @kl0u. Then I will try to merge this pull request myself :-)

**Comment by kl0u** [comment]
Thanks @TisonKun !

**Pull request merged**
