### PR TITLE
[FLINK-15136][docs] Update the Chinese version of Working with State

### PR DESCRIPTION
**Pull request by klion26**
## What is the purpose of the change

We enabled background cleanup of state with TTL by default in [FLINK-14898](https://issues.apache.org/jira/browse/FLINK-14898), and we should update the Chinese version to respect it.

This ticket will update the Chinese version documentation of the page "Working with State".
 
documentation location : docs/dev/stream/state/state.zh.md

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by klion26** [comment]
cc @wuchong @azagrebin

**Comment by klion26** [comment]
test failed because of irrelevant case, create an [issue](https://issues.apache.org/jira/browse/FLINK-15150) to track it.

**Comment by azagrebin** [comment]
Thanks @klion26 @carp84
merged into master by f90fd6b9dea154a39d26fa3a5a529565d4efb3e1

**Comment by klion26** [comment]
@carp84 @azagrebin thanks for the review and merging.

**Pull request closed without merging**
