### PR TITLE
[FLINK-5128]Get Kafka partitions in FlinkKafkaProducer only if a partitioner is set

### PR DESCRIPTION
**Pull request by Renkai**

### CODE REVIEW

**Comment by tzulitai** [comment]
Thank you for the contribution @Renkai!
+1 to merge this.

**Comment by tzulitai** [comment]
Merging this by the end of the day if there's no other objections!

**Comment by rmetzger** [comment]
+1

**Comment by tzulitai** [comment]
I'll rebase on the batch/streaming connector refactoring and merge this now

**Pull request closed without merging**
