### PR TITLE
[hotfix] consistency: vertexes -> vertices

### PR DESCRIPTION
**Pull request by tison1**
cc @zentol @yanghua

### CODE REVIEW

**Comment by tison1** [comment]
look up dictionary and it says "vertexes" is also vertex pluralities :P

but the most of our code use "vertices", so could this PR thought as keeping consistency?

**Comment by yanghua** [comment]
it seems Flink also uses "vertices", I agree your opinion.

**Comment by yanghua** [comment]
+1 from myside, it depends on @zentol or @tillrohrmann 's opinion.

**Comment by zentol** [comment]
`vertices` is the correct plural, but this is another one of those cases where fixing it might cause more harm than good since it could cause merge conflicts, yet provides no functional benefit.

Additionally this PR makes a lot of whitespace changes that should be reverted in any case.

**Comment by tison1** [comment]
> Additionally this PR makes a lot of whitespace changes that should be reverted in any case.

did you mean the whitespace in comment `* ` is significant?

**Comment by zentol** [comment]
yes

**Comment by tison1** [comment]
> vertices is the correct plural, but this is another one of those cases where fixing it might cause more harm than good since it could cause merge conflicts, yet provides no functional benefit.

... close as @zentol suggested

**Comment by tison1** [comment]
> vertices is the correct plural, but this is another one of those cases where fixing it might cause more harm than good since it could cause merge conflicts, yet provides no functional benefit.

... close as @zentol suggested

**Pull request closed without merging**
