### PR TITLE
[FLINK-2651] Add Netty to dependency management

### PR DESCRIPTION
**Pull request by uce**
Hadoop 2.7.0 pulls in an older Netty version, which clashes with our version. This makes sure to only pull in our version.

To test this, you have to build it with `-Dhadoop.version=2.7.0` set.

I've checked that this is respected in the fat jar.

Additionally, I've bumped the Netty version to the most recent 4.0.31 (from 4.0.27). There is no particular reason for this, but the release notes mention many improvements and fixes. In general, I think it's a good idea to have the most recent version.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Good fix.

I think it is a bit overkill to define a Maven variable for a dependency used only in one place, so why not directly state the version in the dependency management section?

**Comment by hsaputra** [comment]
+1

**Comment by uce** [comment]
OK, I will merge this then. Thanks for the reviews. I will remove the variable.

**Comment by rmetzger** [comment]
Let me check the implications tomorrow: I've put a comment there which explicitly says that putting netty there is dangerous ;)

```xml

	<!-- this section defines the module versions that are used if nothing else is specified. -->
	<dependencyManagement>
		<!-- WARN: 
			DO NOT put 	guava, 
						protobuf, 
						asm,
						netty
					here. It will overwrite Hadoop's guava dependency (even though we handle it
			separatly in the flink-shaded-hadoop module).
			We can use all guava versions everywhere by adding it directly as a dependency to each project.
		-->
		<dependencies>
```

**Comment by StephanEwen** [comment]
I think the comments is wrong (I stumbled across it a while back as well). It came from the time when we were discussing to shade netty as well (which we don't do)...

**Comment by rmetzger** [comment]
I agree. The build is working, for all hadoop versions, so I seems to work.

**Comment by hsaputra** [comment]
But we do shade netty in the flink-shaded-hadoop module [1], don't we?
By explicit pulling specific Netty version I think it would just mean it will shade that particular version of Netty instead of the one from Hadoop. Or maybe I am wrong.

[1] https://cwiki.apache.org/confluence/display/FLINK/Hadoop+Versions+and+Dependency+Shading

**Comment by tillrohrmann** [comment]
Please update the license file in flink-dist accordingly.

**Comment by uce** [comment]
Adjusted LICENSE in bc21de2.

**Comment by StephanEwen** [comment]
@hsaputra I think the wiki page is not correct any more. Netty was discussed to be shaded, but was never added to the relocated artifacts.

That was a good decision, IMHO. Dependencies that upgrade well-behaved need not (and in most cases should not) be shaded. Netty behaved well so far: When the changed API and behavior, they used a different namespace. Same is true for the Apache Commons libraries, for example the switch from commons lang version 2 (in the old namespace) to commons lang version 3 (new package name and artifact id).

Unfortunately, same is not true for Guava, Joda Time, ASM, Protobuf, ...

**Comment by hsaputra** [comment]
That is good to know because I did similar thing in other project to make sure we have the right Netty version. But no shading involve either.

Agree about Guava for sure =(

**Pull request closed without merging**
