### PR TITLE
[FLINK-2957][web-dashboard] Improve the appearance of cancel button

### PR DESCRIPTION
**Pull request by sachingoel0101**
Here are the screenshots:
screenshot 40
screenshot 39

The addition of a cancel *icon* makes this more likely to be used.

### CODE REVIEW

**Comment by sachingoel0101** [comment]
@StephanEwen Is this better?

**Comment by mxm** [comment]
Not really convinced by your changes. What about a normal button like the + - buttons?

**Comment by sachingoel0101** [comment]
I don't understand. Simply a *cross* won't be any better than one with *cancel* right next to it.

**Comment by mxm** [comment]
I meant a button like for the + - buttons but labelled "Cancel".

**Comment by sachingoel0101** [comment]
@mxm , what about something like this? I think this is the most clear way of displaying it.
screenshot 41

**Comment by tillrohrmann** [comment]
+1 for @mxm suggestion to use a simple button like the +/- buttons.

**Comment by sachingoel0101** [comment]
Fair enough, if that's the majority view. I'll push a commit later today
for this.

**Comment by sachingoel0101** [comment]
Here are the new screenshots:
screenshot 48
screenshot 49

**Comment by mxm** [comment]
Some minor commenets. Could we remove the "x" from the button? I think it looks odd. While cancelling, could we display just "Cancelling..." without a button?

**Comment by sachingoel0101** [comment]
screenshot 51
screenshot 50

@mxm how about these?

**Comment by mxm** [comment]
Yes, much better in my opinion.

**Comment by sachingoel0101** [comment]
I've pushed the relevant commit. Should be good to merge. @mxm

**Comment by mxm** [comment]
Does the cancel button also work for jobs which have been restarted?

**Comment by sachingoel0101** [comment]
A restarted job will get in running state, and that should allow it to be cancelled. Should I allow cancelling in the `RESTARTING` state as well?

**Comment by mxm** [comment]
No I think that's fine. I was only concerned whether the button is visible after a restart because you remove the button while cancelling...

**Comment by sachingoel0101** [comment]
It should pop up again when the job gets in running state again.

**Pull request closed without merging**
