### PR TITLE
[FLINK-17565][k8s] Bump fabric8 version from 4.5.2 to 4.9.2

### PR DESCRIPTION
**Pull request by zhengcanbin**
## What is the purpose of the change

Bump fabric8 kubernetes-client from 4.5.2 to 4.9.2.

It is expected that v4.9.2 fixes the issues as follows:

1. [FLINK-17566](https://issues.apache.org/jira/browse/FLINK-17566)
2. [FLINK-17416](https://issues.apache.org/jira/browse/FLINK-17416)

## Brief change log

  - Update pom.xml about the `kubernetes.client.version` property.
  - Update the NOTICE file.
  - Update all the test cases which previously expect the method of `Quantity#getAmount` returns **${memoryAmount}${memoryFormat}**.

## Verifying this change

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by wangyang0918** [comment]
@zhengcanbin Thanks a lot for creating this PR. I am afraid this PR could not work because the new version introduce some additional dependencies(e.g. `com.fasterxml.jackson.datatype:jackson-datatype-jsr310`). Could you please check for that?

```
2020-05-18 14:22:19,882 INFO  org.apache.flink.client.deployment.DefaultClusterClientServiceLoader [] - Could not load factory due to missing dependencies.
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/flink/kubernetes/shaded/com/fasterxml/jackson/datatype/jsr310/JavaTimeModule
	at io.fabric8.kubernetes.client.internal.KubeConfigUtils.parseConfigFromString(KubeConfigUtils.java:44)
	at io.fabric8.kubernetes.client.Config.loadFromKubeconfig(Config.java:505)
	at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:491)
	at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:230)
	at io.fabric8.kubernetes.client.Config.<init>(Config.java:214)
	at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:225)
	at org.apache.flink.kubernetes.kubeclient.KubeClientFactory.fromConfiguration(KubeClientFactory.java:69)
	at org.apache.flink.kubernetes.KubernetesClusterClientFactory.createClusterDescriptor(KubernetesClusterClientFactory.java:58)
	at org.apache.flink.kubernetes.KubernetesClusterClientFactory.createClusterDescriptor(KubernetesClusterClientFactory.java:39)
	at org.apache.flink.kubernetes.cli.KubernetesSessionCli.run(KubernetesSessionCli.java:95)
	at org.apache.flink.kubernetes.cli.KubernetesSessionCli.lambda$main$0(KubernetesSessionCli.java:185)
	at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:30)
	at org.apache.flink.kubernetes.cli.KubernetesSessionCli.main(KubernetesSessionCli.java:185)
Caused by: java.lang.ClassNotFoundException: org.apache.flink.kubernetes.shaded.com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 13 more

```

**Comment by zhengcanbin** [comment]
> @zhengcanbin Thanks a lot for creating this PR. I am afraid this PR could not work because the new `kubernetes-client` version introduce some additional dependencies(e.g. `com.fasterxml.jackson.datatype:jackson-datatype-jsr310`). Could you please check for that?
> 
> ```
> 2020-05-18 14:22:19,882 INFO  org.apache.flink.client.deployment.DefaultClusterClientServiceLoader [] - Could not load factory due to missing dependencies.
> Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/flink/kubernetes/shaded/com/fasterxml/jackson/datatype/jsr310/JavaTimeModule
> 	at io.fabric8.kubernetes.client.internal.KubeConfigUtils.parseConfigFromString(KubeConfigUtils.java:44)
> 	at io.fabric8.kubernetes.client.Config.loadFromKubeconfig(Config.java:505)
> 	at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:491)
> 	at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:230)
> 	at io.fabric8.kubernetes.client.Config.<init>(Config.java:214)
> 	at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:225)
> 	at org.apache.flink.kubernetes.kubeclient.KubeClientFactory.fromConfiguration(KubeClientFactory.java:69)
> 	at org.apache.flink.kubernetes.KubernetesClusterClientFactory.createClusterDescriptor(KubernetesClusterClientFactory.java:58)
> 	at org.apache.flink.kubernetes.KubernetesClusterClientFactory.createClusterDescriptor(KubernetesClusterClientFactory.java:39)
> 	at org.apache.flink.kubernetes.cli.KubernetesSessionCli.run(KubernetesSessionCli.java:95)
> 	at org.apache.flink.kubernetes.cli.KubernetesSessionCli.lambda$main$0(KubernetesSessionCli.java:185)
> 	at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:30)
> 	at org.apache.flink.kubernetes.cli.KubernetesSessionCli.main(KubernetesSessionCli.java:185)
> Caused by: java.lang.ClassNotFoundException: org.apache.flink.kubernetes.shaded.com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> 	... 13 more
> ```

True, updated.

**Comment by wangyang0918** [comment]
@zhengcanbin Thanks for the updating. LGTM now.

One more thing, we need to revert this commit 5846e5458e20308db4f0dd1c87d511a60817472c to verify FLINK-17416 is fixed(i.e. Flink on K8s could work on java 8u252). For FLINK-17566, i have verified it could be fixed by this PR.

nit: Maybe we could use fabric8 kubernetes-client version in the commit message, not fabric8 version.


Moreover, could you rebase the latest master to enable the e2e test?

**Comment by zhengcanbin** [comment]
> @zhengcanbin Thanks for the updating. LGTM now.
> 
> One more thing, we need to revert this commit [5846e54](https://github.com/apache/flink/commit/5846e5458e20308db4f0dd1c87d511a60817472c) to verify [FLINK-17416](https://issues.apache.org/jira/browse/FLINK-17416) is fixed(i.e. Flink on K8s could work on java 8u252). For [FLINK-17566](https://issues.apache.org/jira/browse/FLINK-17566), i have verified it could be fixed by this PR.
> 
> nit: Maybe we could use fabric8 kubernetes-client version in the commit message, not fabric8 version.
> 
> Moreover, could you rebase the latest master to enable the e2e test?

Thanks for the reminder. Done!

**Pull request merged**
