### PR TITLE
Added Model serving - implementation of the Flip -23.

### PR DESCRIPTION
**Pull request by blublinsky**
This adds Module flink-modelserving, that implements model serving library (both java and scala)
and module flink-examples-modelserving in the flink-examples module, for the examples of library usage

This implements Flip-23 https://cwiki.apache.org/confluence/display/FLINK/FLIP-23+-+Model+Serving

## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by blublinsky** [comment]
What is the purpose of this change
Implementation of Flip 23 - Flink model serving
Brief change log
Adds Flink model serving module
Verifying this change

Unit tests for the library.
Sample application in Flink examples/model serving
Documentation
Does this pull request introduce a new feature? 
Yes. Flip-23

**Comment by fhueske** [comment]
Hi @blublinsky, thank you for this contribution! Model serving is a common requirement for many Flink users and it would be great to offer a library to simplify this task.

However, I noticed a serious license issue. The `org.jpmml` dependencies (`pmml-evaluator` and `pmml-evaluator-extension`) are AGPL licensed and can therefore not be included in ASF projects (see [Cat X licenses](https://apache.org/legal/resolved.html#what-can-we-not-include-in-an-asf-project-category-x) for details.). 

Are you aware of an alternative library to evaluate PMML models in the JVM?

Thank you, Fabian

**Comment by rmetzger** [comment]
I agree with @fhueske. The license situation will not permit us to merge this to an Apache project.

Others ran into the issue as well in the context of Apache Spark:
- https://community.hortonworks.com/questions/3020/anyone-know-of-a-java-pmml-evaluator-with-an-apach.html
- https://issues.apache.org/jira/browse/SPARK-1406

Maybe we should reach out to the jpmml community and start a project like this one: https://github.com/jpmml/jpmml-sparkml or at least get into the list on this page: https://github.com/jpmml/jpmml-evaluator with https://github.com/FlinkML/flink-jpmml.

What do you think about closing this pull request and bringing the discussion back to the dev@ mailing list?

**Comment by blublinsky** [comment]
I already remove PMML from the code.
Its just Tensorflow for now

Boris Lublinsky
FDP Architect
boris.lublinsky@lightbend.com
https://www.lightbend.com/

**Comment by shaoxuan-wang** [comment]
Hi @blublinsky, thanks for the contribution. As we talked offline, I have observed there are at least three issues of this PR against the "contribution checklist".  (You can find the "contribution checklist" when you create pull request or [Flink website](https://flink.apache.org/contribute-code.html). Please carefully follow those instructions). I hope those issues can be fixed before moving forward on this PR. 
  - Make sure that the pull request corresponds to a [JIRA issue](https://issues.apache.org/jira/projects/FLINK/issues). 
  - Name the pull request in the form "[FLINK-XXXX] [component] Title of the pull request", where FLINK-XXXX should be replaced by the actual issue number. Skip component if you are unsure about which is the best component. I noticed that you have created [FLINK-12186](https://issues.apache.org/jira/browse/FLINK-12186) on April 14th after we talked offline. So this PR should be named as something like "[FLINK-12186] [ml] Flink model serving"
  - Make sure that the change passes the automated tests, i.e., `mvn clean verify` passes. You can set up Travis CI to do that following [this guide](http://flink.apache.org/contribute-code.html#best-practices). The Travis CI build of this PR was failed and it also needs a rebase due to the conflicts with the master files.

Since there is not much inline review comment yet, I highly suggest that you close this PR and resubmit a new PR once fixed the CI build errors on your personal github.

I have other comments about the interface of model serving and some suggestions of the detailed implementations. I will send those comments to the dev ML with a broader visibility to collect feedback.

**Comment by blublinsky** [comment]
Fixed license issue

Boris Lublinsky
FDP Architect
boris.lublinsky@lightbend.com
https://www.lightbend.com/

**Pull request closed without merging**
