### PR TITLE
[hotfix][docs] Fix some formatting errors in Chinese documents.

### PR DESCRIPTION
**Pull request by liuzhuang2017**
## What is the purpose of the change

- **In english document:**

image

- **In chinese document:**
image

## Brief change log

- **Fix some formatting errors in Chinese documents.**

## Verifying this change
- **This change is a trivial rework / code cleanup without any test coverage.**

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by liuzhuang2017** [comment]
@flinkbot run azure

**Comment by liuzhuang2017** [comment]
@MartijnVisser , Sorry to bother you, can you help me review this pull request? grateful.

**Review by liujingmao — APPROVED** [review]
ok

**Comment by MartijnVisser** [comment]
@liuzhuang2017 Can you please fetch all upstream commits, rebase and push again? Right now all tests fail which make it not possible to merge. 

Something like:
- `git fetch upstream` (depending on how you've named the remote that's pointing to github.com/apache/flink)
- `git rebase upstream/master` to rebase on the `master` branch from apache/flink

**Comment by liuzhuang2017** [comment]
@MartijnVisser , Sorry to bother you again, can you help me review this pull request? grateful.

**Review by MartijnVisser — APPROVED** [review]
LGTM

**Pull request merged**
