### PR TITLE
[FLINK-9265] Upgrade Prometheus version

### PR DESCRIPTION
**Pull request by yanghua**
## What is the purpose of the change

*This pull request upgrades the prometheus's version to the latest version*

## Brief change log

  - *Upgrade the prometheus version*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**yes** / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by StephanEwen** [comment]
Could you add the dependency tree of the upgraded Prometheus dependency to check?

**Comment by yanghua** [comment]
Is there any problem about this upgrading?  Does you mean I should add the dependency tree here as a comment?

**Comment by StephanEwen** [comment]
Yes, before giving +1 to this commit, we need to check that this introduces no new transitive dependency, or need to make sure that dependency is not an issue.

**Comment by yanghua** [comment]
cc @StephanEwen , here is the dependency tree : 

```
[INFO] org.apache.flink:flink-metrics-prometheus:jar:1.6-SNAPSHOT
[INFO] +- io.prometheus:simpleclient:jar:0.3.0:compile
[INFO] \- io.prometheus:simpleclient_httpserver:jar:0.3.0:compile
[INFO]    +- (io.prometheus:simpleclient:jar:0.3.0:compile - omitted for duplicate)
[INFO]    \- io.prometheus:simpleclient_common:jar:0.3.0:compile
[INFO]       \- (io.prometheus:simpleclient:jar:0.3.0:compile - omitted for duplicate)
```

**Comment by StephanEwen** [comment]
Looks good, thanks.

+1 to merge this

**Comment by zentol** [comment]
merging.

**Pull request closed without merging**
