### PR TITLE
[FLINK-12353] Collect all japicmp output under tools directory

### PR DESCRIPTION
**Pull request by Myasuka**
## What is the purpose of the change

Collect all the output of `japicmp` under `tools/japicmp-collect` directory instead of running separate shell script `collect_japicmp_reports.sh` previously.

## Brief change log

  - Change the output directory of `japicmp` plugin to the same `flink-root-dir/tools/japicmp-collect` directory.
  - Remove `collect_japicmp_reports.sh` script.

## Verifying this change

This change is a trivial rework without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): **no**
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: **no**
  - The serializers: **no**
  - The runtime per-record code paths (performance sensitive): **no**
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: **no**
  - The S3 file system connector: **no**

## Documentation

  - Does this pull request introduce a new feature? **no**
  - If yes, how is the feature documented? **not applicable**

### CODE REVIEW

**Comment by Myasuka** [comment]
@flinkbot attention @zentol

**Comment by zentol** [comment]
May take a look next week.

**Comment by Myasuka** [comment]
@StephanEwen Thanks for your review, already updated based on your comments. BTW, the actual property from the "highest base dir" plugin should be `rootDir`.

**Comment by StephanEwen** [comment]
@flinkbot approve all

**Comment by StephanEwen** [comment]
@zentol Do you want to look at this before merging?
From my side this looks good to go...

**Pull request merged**
