### PR TITLE
[FLINK-21419][coordination] Remove GC cleaner mechanism for unsafe memory segments

### PR DESCRIPTION
**Pull request by SteNicholas**
## What is the purpose of the change

*Remove GC cleaner mechanism for unsafe memory segments. Currently the cleaner passed to the `HybridMemorySegment` is encapsulated by `JavaGcCleanerWrapper`. The encapsulated cleaner is guaranteed to run only once, or it is called actively, if it is not called actively, the JVM will call it when gc is called. The mechanism should be to keep the active clean, not rely on gc for clean, therefore the wrapper of `JavaGcCleanerWrapper` could be removed. At the same time, the related mechanism of applying for memory trigger and waiting for gc in the memory manager could also be removed.*

## Brief change log

  - *`MemoryUtils#createMemoryGcCleaner` removes the wrapper of `JavaGcCleanerWrapper`, directly returns the `Runnable` of cleaner.*
  - *`UnsafeMemoryBudget#reserveMemory` removes the memory allocation and the reservation for a long time waiting for GC.*

## Verifying this change

  - *Remove `testReservationFailsIfOwnerNotGced`, `testReservationSuccessIfOwnerGced` test case of `UnsafeMemoryBudgetTest`.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by SteNicholas** [comment]
@flinkbot run azure

**Comment by SteNicholas** [comment]
@xintongsong , could you please help to review this pull request?

**Review by xintongsong — APPROVED** [review]
Thanks @SteNicholas. The PR LGTM.
I'm re-running the ci tests, and will merge this after the tests pass.

**Comment by SteNicholas** [comment]
@flinkbot run azure

**Comment by SteNicholas** [comment]
@xintongsong, the result of CI tests is `SUCCESS`, please help to merge if you are available.

**Comment by xintongsong** [comment]
Thanks @SteNicholas. Merging this.

**Pull request closed without merging**
