### PR TITLE
[hotfix] [yarn-test] Clean up inactive test

### PR DESCRIPTION
**Pull request by TisonKun**
## What is the purpose of the change

1. YARNITCase is `@Ignore` and actually about legacy mode.
2. YARNHighAvailabilityITCase only run on legacy mode, which is inactive
during Travis CI
3. After these two inactive cases removed, those testing class could be
removed, too. They are inherited from legacy components and would not be
supported any more.

To sum up, this PR is to remove unmaintained test.

cc @GJL @zentol @azagrebin

### CODE REVIEW

**Comment by tillrohrmann** [comment]
Thanks for opening this PR @TisonKun. The `YarnITCase` is actually not using the legacy mode but the Flip-6 code path. Instead of removing it, I think we should activate it. I tried to see what's missing and it seems to work by adding the following changes: #6717.

Therefore I would suggest to rather activate the test instead of removing it.

**Comment by TisonKun** [comment]
@tillrohrmann sure but I notice that it relies on `TestingYarnClusterDescriptor` which inherited from `LegacyYarnClusterDescriptor`. I see #6717 but it still use `TestingYarnClusterDescriptor`, is there something missed?

**Comment by TisonKun** [comment]
Ok, it is just `TestingYarnClusterDescriptor.TestJarFinder` which is a util class, we can move it out of `TestingYarnClusterDescriptor`

**Comment by TisonKun** [comment]
FYI, Travis fails on legacy test `JobManagerFailsTest`.

**Comment by tillrohrmann** [comment]
@TisonKun I'm not sure whether we can already remove the `TestingYarnClusterDescriptor` because it is still being used by the `YARNHighAvailabilityITCase`. Only after we have removed the legacy mode, we should remove these tests. Otherwise we risk to run into regressions.

**Comment by TisonKun** [comment]
@tillrohrmann Currently, `YARNHighAvailabilityITCase` is only a test for legacy mode. If we want to maintain `YARNHighAvailabilityITCase` until a total removal of legacy mode, then the precondition of this PR runs into false. That is, `YARNHighAvailabilityITCase` isn't inactive test. If so, please close this and wait for the removal happens.

**Comment by TisonKun** [comment]
... close as it would be covered by FLINK-10392

**Pull request closed without merging**
