### PR TITLE
[FLINK-24911][table] Enable line numbers in SQL Client

### PR DESCRIPTION
**Pull request by snuyanzin**
## What is the purpose of the change

The PR allows to have line numbers in SQL Client for multiline SQL.
In fact line numbers are already implemented in JLine and the only thing the PR does is allowing to toggle line numbers via property.

## Verifying this change

This change is a trivial rework.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: ( no )
  - The runtime per-record code paths (performance sensitive): ( no )
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: ( no )
  - The S3 file system connector: ( no )

## Documentation

  - Does this pull request introduce a new feature? (yes )
  - If yes, how is the feature documented? (docs )

### CODE REVIEW

**Review by reswqa — COMMENTED** [review]
Thank for bring this up, +1 for this. I wonder if we can add some test to this except for manual validation.

**Comment by reswqa** [comment]
> it requires non DumbTerminal while in tests we use only DumbTerminal...

Ah, that's make sense.

> may be only some mocking which could allow to check that Flink property correctly propagates to jline

This should also be fine (at least to some extent better than not testing).

**Review by reswqa — APPROVED** [review]
Thanks for the update, looks good to me.

**Comment by snuyanzin** [comment]
Thanks for taking a look

**Pull request merged**
