### PR TITLE
[FLINK-2404]Primitive add methods for Accumulators

### PR DESCRIPTION
**Pull request by sachingoel0101**
Adds primitive add value methods to Double, Int and Long counter.

Benchmark: Run independently of Flink on the LongCounter accumulator.
No Add | Long Add | long Add
--------- | ------------- | --------
1458.9 | 2785.7 | 2169.7

[Time for 1e+9 additions]

### CODE REVIEW

**Comment by mxm** [comment]
Thanks for repeating your experiment isolated without the whole Flink stack. Here we can clearly see the performance impact of the `Long` auto unboxing.

I will merge your changes later this day.

**Comment by sachingoel0101** [comment]
Should we add some kind of annotation to suggest the usage of the primitive functions? We can't deprecate the older ones probably.

**Comment by mxm** [comment]
We can add a comment that the new ones are faster on primitives. It is not possible to deprecate the older ones because they are inherited from the Accumulator interface which uses Generics. It's just an optimization.

**Comment by sachingoel0101** [comment]
No one will actually find out unless they specifically went through the documentation for these. Most people would only ever see the docs for Accumulator interface. 
I agree though. We can't deprecate them obviously. I'll add the suggestion in docs.

**Comment by mxm** [comment]
For the cases, where we add a primitive type on a Long/Int/DoubleCounter, the optimization will automatically be used.

**Comment by mxm** [comment]
Thanks for the pull request!

**Comment by sachingoel0101** [comment]
Sure. :)

**Pull request closed without merging**
