### PR TITLE
[FLINK-36739] [WebFrontend] Update the NodeJS to v22.11.0 (LTS)

### PR DESCRIPTION
**Pull request by mehdid93**
Contribute-to: https://issues.apache.org/jira/browse/FLINK-36739

## What is the purpose of the change

This pull request raises the version of the NodeJS module which is a pre-requisite to upgrade dependencies in order to address vulnerabilities in Runtime/WebFrontend component. 
There will be another PR to fix vulnerabilities once this is merged.

## Brief change log

NodeJS is v22.11.0/Npm is 10.9.0

## Verifying this change

The Flink UI should be accessible without any difference

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Review by davidradl — APPROVED** [review]

**Review by davidradl — APPROVED** [review]

**Comment by davidradl** [comment]
Reviewed by Chi on 21/11/24. Asked submitter questions

@mehdid93 Looks good - but why are the CI tests failing?

**Comment by mehdid93** [comment]
@flinkbot run azure

**Review by MartijnVisser — CHANGES_REQUESTED** [review]
We can't change the CI flows to work on a container from a non-PMC member unfortunately. Let me check this with the other PMCs on how to unblock you

**Comment by zentol** [comment]
> why are the CI tests failing?

Because the image was modified incorrectly.

**Comment by mehdid93** [comment]
> We can't change the CI flows to work on a container from a non-PMC member unfortunately. Let me check this with the other PMCs on how to unblock you

Sorry about that @MartijnVisser and @zentol I've revert the last commit and thank you for your help @zentol.

**Comment by zentol** [comment]
@mehdid93 You can try your changes with [chesnay/flink-ci:java_8_11_17_21_maven_386_jammy](https://hub.docker.com/layers/chesnay/flink-ci/java_8_11_17_21_maven_386_jammy/images/sha256-85838a97ac7151fac2493de5df7dd8fbb02e3ba1d48d7f64b654866deed07448?context=explore).

I'll open a PR tomorrow to update CI as a whole to use that image.

**Comment by mehdid93** [comment]
@zentol Thank you! I have pushed a commit to use the new Image in order to test the changes

**Comment by mehdid93** [comment]
@flinkbot run azure

**Review by MartijnVisser — COMMENTED** [review]
@mehdid93 Can you please rebase, and make sure that you have one commit with the actual change?

**Comment by mehdid93** [comment]
> @mehdid93 Can you please rebase, and make sure that you have one commit with the actual change?

Yes I have rebased and squashed my commits should be okay now

**Comment by simplejason** [comment]
Glad to see the front-end version upgrades is concerned, I'm trying to upgrade `ng-zorro-antd` and `angular` to v18  and having the same problem regarding `GLIBC 2.28`(#25713).
I think we need to upgrade the containers(maybe only Ubuntu?) in flink-2.0 to make it work :-)

**Review by MartijnVisser — APPROVED** [review]
I've verified this PR by building locally and clicking through the UI. It appears to be OK, but during building there is a bunch of warnings
```
[INFO] npm warn config cache-max This option has been deprecated in favor of `--prefer-online`
[INFO] npm warn EBADENGINE Unsupported engine {
[INFO] npm warn EBADENGINE   package: '@es-joy/jsdoccomment@0.20.1',
[INFO] npm warn EBADENGINE   required: { node: '^12 || ^14 || ^16 || ^17' },
[INFO] npm warn EBADENGINE   current: { node: 'v22.11.0', npm: '10.9.0' }
[INFO] npm warn EBADENGINE }
[INFO] npm warn EBADENGINE Unsupported engine {
[INFO] npm warn EBADENGINE   package: 'eslint-plugin-jsdoc@37.9.7',
[INFO] npm warn EBADENGINE   required: { node: '^12 || ^14 || ^16 || ^17' },
[INFO] npm warn EBADENGINE   current: { node: 'v22.11.0', npm: '10.9.0' }
[INFO] npm warn EBADENGINE }
[INFO] npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[INFO] npm warn deprecated har-validator@5.1.5: this library is no longer supported
[INFO] npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

There's nothing here that makes me look like we shouldn't move forward with upgrading though. I'll merge this

**Pull request merged**
