### PR TITLE
[FLINK-8655] [DataSink] Added default keyspace to CassandraPojoSink

### PR DESCRIPTION
**Pull request by Bekreth**
## What is the purpose of the change

Initial Issue : [https://issues.apache.org/jira/browse/FLINK-8655]
It is not uncommon for users to have a single Cassandra instance for all of their test environments, differentiating what each environment uses based on keyspace.  This PR adds functionality for the CassandraPojoSink to have the keyspace defined at runtime to allow for more flexible configurations.

## Brief change log

  - Added functionality for defining default keyspace at runtime.

## Verifying this change

The changes have been verified manually.  Unit tests will be included following preliminary discussion on the functionality.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? JavaDocs

### CODE REVIEW

**Comment by StephanEwen** [comment]
I see the need for the feature, but I am skeptical concerning the implementation.

This PR reflectively modifies the contents of a String. This is prone to cause problems, for multiple reasons. Strings cache hash codes, and strings themselves are interned and shared.

Is there no other way to pass a default namespace to the mapping?

**Comment by Bekreth** [comment]
Previously, I was trying to leverage the current annotation parsers. 

It would be possible to pass in a keyspace more directly into AnotationParser in the shaded Datastax component, but I'm against this as it requires maintaining a version Datastax that differs from the open source version.

It could be possible to just replace the entire annotation with reflections instead of just editing 1 property, but that still requires some futzing in reflections that I think would be best to avoid.

Another option could be to extend the necessary Datastax classes within the CassandraPojoSink to facilitate the alterations necessary to pass in keyspace dynamically.  I'm thinking this is the most favorable option.

**Comment by Bekreth** [comment]
I've been looking into this more in depth and I'm uncertain there is going to be a cleaner solution.  The DataStax annotation parser will fail during runtime if it can't determine the keyspace either from the Table annotation, or from the connection.  The core Cassandra functionality is built on a stateless connection though, so embedding the keyspace into there would be a bad idea.  

In order to make this work with the current Datastax implementations, it'd be necessary to extend both MappingManager and AnnotationParser from Datastax as well as update the CassandraSinkBase to use these extension. 

Should I try to make a swing at these changes to see what it entail?

**Comment by Bekreth** [comment]
This looks like it'd work out well!  When I made this PR, I was aware that the Cassandra connection happened irrespective of the keyspace and I tried to maintain that in order to minimize the change made.  If the Flink team will to allow stateful connections (`CassandraSinkBase:L88`), then I'd much prefer to see them use your solution.

**Comment by zentol** [comment]
We would have to pass the keyspace via the constructor as the `Configuration` approach doesn't work for streaming.

Generally speaking it isn't a problem to set the keyspace when creating the connection.  But I would like to know what happens if a POJO comes along that explicitly sets the keyspace; is ignored, respected or will it cause an exception?

**Pull request closed without merging**
