### PR TITLE
[FLINK-2184] Cannot get last element with maxBy/minBy.

### PR DESCRIPTION
**Pull request by gallenvara**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [X] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [X] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [ ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

Extend the minBy/maxBy with first parameter. @fhueske sorry for the late update for this pr, can you help with review work?

### CODE REVIEW

**Comment by gallenvara** [comment]
@fhueske @twalthr . Can you help with reviewing this PR?

**Comment by fhueske** [comment]
Thanks @gallenvara, the changes look good to me but we would also need a few tests.

@aljoscha, what do you think about this change? Should we add it to be consistent with the Java API or do you think it would bloat the API too much? IIRC, there have been some discussions about the built-in aggregation functions.

Best, Fabian

**Comment by aljoscha** [comment]
Thanks for notifying @fhueske! And sorry for not noticing this earlier and jumping on so late.

I think this part of the API is already to bloated and (at the same time) not powerful enough. These functions don't allow having multiple "aggregations" in one operation, i.e. you cannot do `inputStream.keyBy(...).min(1).andMax(2).andSum(3)` (not actual API). I think in the long run we should remove this part of the API because the Table API is a nicer way of expressing simple aggregations. What do you think?

**Comment by fhueske** [comment]
Thanks @aljoscha, those are my concerns as well. The methods are very prominent in the core APIs and provide only marginal value. It's pretty straightforward to implement the functionality with a `ReduceFunction` in case you need it.

Are there plans to deprecate the corresponding methods on the Java DataStream API?

**Comment by aljoscha** [comment]
There were, but only in my head. Maybe we should open an issue or discuss on the ML.

**Comment by aljoscha** [comment]
I'm closing this as "Abandoned", since there is no more activity and the code base has moved on quite a bit. Please re-open this if you feel otherwise and work should continue.

**Pull request closed without merging**
