### PR TITLE
[FLINK-20381][yarn] Replace -id by -yid

### PR DESCRIPTION
**Pull request by rmetzger**
## What is the purpose of the change

The "yarn-session.sh -id <appId>" command doesn't work as logged. You need to use "-yid".

### CODE REVIEW

**Comment by rmetzger** [comment]
@kl0u do you know when the argument has changed from -id to -yid? (On 1.12.0-rc1 -yid seems to be the way to go)

**Comment by wangyang0918** [comment]
@rmetzger Thanks for this PR. I am afraid we could not simply use `-yid` instead of `id`. Since all other options does not have the prefix (`y` for short, `yarn` for long) in the `yarn-session.sh`. For example,`yarn-session.sh -qu default -jm 4096 -tm 2048`.

This stopping command became broken since `AbstractYarnCli` is introduced in #13358 without having the prefix.

**Comment by wangyang0918** [comment]
Another concern is that the following command has the same semantic but it could not work too. Because we only check the cli option `cmd.hasOption(applicationId.getOpt())`.

```
echo "stop" | ./bin/yarn-session.sh -Dyarn.application.id=application_1606316139480_0003
```

**Comment by rmetzger** [comment]
Thanks a lot for your review. I will open a new PR restoring the behavior.

**Comment by rmetzger** [comment]
This is the follow up PR https://github.com/apache/flink/pull/14264

**Pull request closed without merging**
