### PR TITLE
[FLINK-3775] [shell] Load Flink configuration before forwarding it

### PR DESCRIPTION
**Pull request by tillrohrmann**
This commit makes sure that the GlobalConfiguration is loaded before the FlinkShell
is started.

- [X] General
  - The pull request references the related JIRA issue
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message

- [X] Tests
  - Has been tested on YARN cluster in combination with #1904

### CODE REVIEW

**Comment by uce** [comment]
Good catch! +1 to merge.

**Comment by zentol** [comment]
Merging.

**Comment by zentol** [comment]
Does this commit only work in combination with #1904?

**Comment by zentol** [comment]
I'm asking since the scala shell tests fail both in travis and locally.

**Comment by tillrohrmann** [comment]
They should work independently of #1904. I have to check why the tests fail.

**Comment by tillrohrmann** [comment]
I've addressed the problem of the failing test cases by introducing a CLI option to specify the configuration directory. That way, we can also set a valid configuration directory for the test cases. Once Travis gives green light, I would merge this PR.

**Comment by tillrohrmann** [comment]
Test failures are unrelated. Merging.

**Pull request closed without merging**
