### PR TITLE
[FLINK-2359] [java api] Add factory methods to the Java TupleX types

### PR DESCRIPTION
**Pull request by ggevay**
I added the creation of the factory method to the TupleGenerator.

I also fixed some inconsistencies between the generator and generated files: it seems that some modifications were made to generated files without modifying the generator. I incorporated these changes to the generator (see the first three hunks in the generator) (except for some whitespace changes in the first three modified files).

I randomly changed some constructor calls into using the new method for testing and demonstration purposes (see the last two changed files).

### CODE REVIEW

**Comment by aljoscha** [comment]
Should we call it `of` instead of `create`? In other parts, such as the windowing helpers we also have `of` for these shortcut constructors.

**Comment by mbalassi** [comment]
I also prefer `of` as a method name.

**Comment by mxm** [comment]
Thanks for adding the generator methods. That's definitely more convenient than using `new`. I also prefer `of` instead of `create`.

**Comment by ggevay** [comment]
Ok, of looks better indeed. I will modify it.

**Comment by fhueske** [comment]
PR looks good to me except for the purely reformatting changes which should be excluded from the PR.
Thanks!

**Comment by ggevay** [comment]
@fhueske:
I included the reformatting changes because the generator is making them. This is happening because some modifications were made directly to some generated codes in the past, which made them inconsistent with the generator. But I guess the goal should be that the generator program would have no effect on the master. One way to achieve this is to commit the changes the generator makes, and the other way would be to change the generator to follow the reformatting. Do you think that I should change the PR to the latter with respect to the reformattings as well? (I already did the latter with respect to some real changes, see my opening comment.)

**Comment by fhueske** [comment]
Ah OK. Its fine to commit the changes if they are caused by the TupleGenerator. 
I don't think it's necessary to adapt the generator to avoid the changes.

**Comment by fhueske** [comment]
I'm going to merge this PR

**Pull request closed without merging**
