### PR TITLE
[FLINK-11530] [docs] Support multiple languages for the docs framework

### PR DESCRIPTION
**Pull request by wuchong**
## What is the purpose of the change

This PR integrate the `jekyll-mulitple-language` plugin for flink docs to support Chinese. 
And all the `xx.zh.md`s have been created but keep the original English contents.

## Brief change log

 - Add `jekyll-mulitple-language` plugin to the Gemfile and `_config.yml`
 - Some modifications for `sidebar.html`, `base.html`, `plain.html`, `redirect.html` to make them support Chinese in case of the current page is a Chinese version.
 - Copy all the existing markdown files to `xx.zh.md` (keep the original content and translate later)

## Verifying this change

This change is a trivial document rework without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by fhueske** [comment]
@flinkbot approve description 
@flinkbot approve consensus
@flinkbot approve attention

**Comment by fhueske** [comment]
Thanks for the PR @wuchong. 
Can you separate the changes for the multilang support and the copied files into two commits? Makes it easier to review the relevant parts.
Thank you.

**Comment by fhueske** [comment]
I played a bit with the documentation and it seems to work well. Didn't understand (and check) all the variables that are set yet ;-)

Are you planning to add a language switch similar to the project webpage?

**Comment by wuchong** [comment]
Hi @fhueske , thanks for the reviewing and advice.

I have separated the changes into two commits. The first is multi-language support, the second is coping all the files.

The variables are described in the http://jekyll-langs.liaohuqiu.net/#variables
I introduced a new variable `baseurl_i18n` in `sidenav.html`.  It is the base url in current language, e.g. `{{ site.baseurl }}/zh` for Chinese, and `{{ site.baseurl }}` for English (as default).

Regarding to the language switch:
Yes, I will add a switch similar to the project website, but in a separate JIRA (just created [FLINK-11732](https://issues.apache.org/jira/browse/FLINK-11732)). This will be added when we satisfied with the translation coverage.

Thanks,
Jark

**Comment by wuchong** [comment]
Btw, the commits to the docs are frequent. I have updated the copied files to the latest commit to docs 70107c4647ecac3df9b1b8c7920e7cb99ad550f1. 

https://github.com/apache/flink/commits/master/docs

**Comment by fhueske** [comment]
Hi @wuchong, thanks for splitting commit and the pointers to the variables.
Adding the switch later makes total sense. 

While browsing the website, I noticed that all links on Chinese pages that are defined with `{{ site.baseurl }}` are pointing to the English pages. Do you want to change them to use `{{ baseurl_i18n }}` (excluding image URLs) when translating the each page or in a bulk fashion?

Either way is fine with me, so +1 to update the last commit and merge the PR.

**Comment by fhueske** [comment]
@flinkbot approve architecture
@flinkbot approve quality

**Comment by wuchong** [comment]
Hi @fhueske , thanks for the suggestion. I think it's a good idea. But I'm afraid we can not use {{ baseurl_i18n }} in markdown files. It is only be declared in `sidenav.html` and seems that it can't be accessed by documentation files.

**Comment by fhueske** [comment]
Oh, I see. Then links would need to be converted to `{{ baseurl_i18n }}/zn` or relative paths.
Anyway, I think this can be done later when the pages are translated.

So +1 to merge the PR.

**Comment by rmetzger** [comment]
What's the status of this PR?

**Comment by wuchong** [comment]
Hi @rmetzger , this PR needs to be rebased on the latest master. But I think before this PR is merged, we should have a consensus on the review process https://github.com/apache/flink-web/pull/190, otherwise, the Chinese documentation synchronization is hard to maintain. Once https://github.com/apache/flink-web/pull/190 is approved, I will update this PR.

**Comment by wuchong** [comment]
I have updated all the `.zh.md` files according to the latest docs commit  https://github.com/apache/flink/commit/86bee8679112e76372a84083b1af18722644e1a0 .

Will merge this pull request after compile passed.

**Comment by bowenli86** [comment]
@kkrugler FYI

**Pull request closed without merging**
