### PR TITLE
[FLINK-31728][examples] Remove scala api dependency

### PR DESCRIPTION
**Pull request by zentol**
Remove an unused dependency on the scala apis, and cleans up related scala build stuff, including some suffixes!

### CODE REVIEW

**Comment by zentol** [comment]
@flinkbot run azure

**Review by mas-chen — COMMENTED** [review]
LGTM, could the archetypes under flink-walkthrough also get updated in this PR as well?

**Comment by zentol** [comment]
> could the archetypes under flink-walkthrough also get updated in this PR as well?

I don't see anything that should be changed there; could you clarify what you mean?

**Review by MartijnVisser — APPROVED** [review]
LGTM

The only Scala reference I could find is in https://github.com/zentol/flink/blob/d_examples_scala/flink-walkthroughs/flink-walkthrough-datastream-java/src/main/resources/archetype-resources/pom.xml#L35 which I believe isn't used anywhere, so could be omitted.

**Pull request merged**
