### PR TITLE
[WIP] Introduce ElasticBloomFilter for Approximate calculation and other situations of performance optimization

### PR DESCRIPTION
**Pull request by sihuazhou**
This PR introduce PartitionedBloomFilter which support rescaling and can deal with data skew problem
 properly.

## Brief change log

- introduce PartitionedBloomFilter for Approximate calculation and other situations of performance optimization.

## Verifying this change

This change can be verified by the unit tests in below files:
- PartitionedBloomFilterTest.java
- LinkedBloomFilterTest.java
- LinkedBloomFilterNodeTest.java
- PartitionedBloomFilterManagerTest.java

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (yes)
     doc: [google doc](https://docs.google.com/document/d/1s8w2dkNFDM9Fb2zoHwHY0hJRrqatAFta42T97nDXmqc/edit?usp=sharing)

### CODE REVIEW

**Comment by sihuazhou** [comment]
For the sake of easy to discussion later..

**Comment by yanghua** [comment]
@sihuazhou This PR has conflicts, can you rebase and fix it?

**Comment by sihuazhou** [comment]
Hi @yanghua , thanks for having a look at this PR. I'm too busy recently, after a while I will come back to rebase this PR, and my other issues.

**Comment by yanghua** [comment]
@sihuazhou OK, I think the community is very interested in this feature. I hope this feature could be approved as soon as possible. Thanks.

**Comment by fhueske** [comment]
Hi @sihuazhou and @yanghua, I would suggest to first get approval from an expert on the affected components and find a committer to shepherd this contribution before putting more work into it.
 
I said before that I think this is valuable contribution, but we need to make sure that it fits into the architecture and that somebody wants to invest the time to review and merge it.
Best, Fabian

**Pull request closed without merging**
