### PR TITLE
[FLINK-20634][dist] Remove start-scala-shell.sh in bin folder when co…

### PR DESCRIPTION
**Pull request by paul8263**
…mpiled with profile scala-2.12 enabled

## What is the purpose of the change

Flink scala shell does not work with Scala 2.12. But it still provides start-scala-shell.sh in bin folder. Need to hide it in scala 2.12 edition.

## Brief change log

- Changed flink-dist module. Now maven will only copy start-scala-shell.sh file to bin folder only when scala-2.11 profile is activated.

## Verifying this change

This change added tests and can be verified as follows:

- Compile Flink with: `mvn clean package -Dscala-2.11`. Verify the file start-scala-shell.sh should exist in bin folder.
- Compile Flink with: `mvn clean package -Dscala-2.12`. File start-scala-shell.sh should not exist in bin folder.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers:no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? no

### CODE REVIEW

**Review by zentol — CHANGES_REQUESTED** [review]
Coyping the entire `bin` assembly just to exclude a single file is not the right approach.

A better approach would be moving the scala-shell copying into it's own assembly with a separate execution that only runs on scala 2.11 .

**Comment by paul8263** [comment]
@zentol Many thanks and I  separated the assembly configuration file that copies start-scala-shell.sh to flink dist bin folder and moved it to its own subproject src folder. The file bin.xml inside flink-dist has been restored. Pls reconsider my solution.

**Comment by zentol** [comment]
I've updated the PR. It wasn't working because you were trying to modify an execution through a profile, but that doesn't actually work; instead this defined an additional execution with the same name.
I've also moved the assembly file to flink-dist to keep them in one place.

**Comment by paul8263** [comment]
Thank you @zentol . Provide another execution with different id for copying start-scala-shell.sh only is better than my solution which overrides the "bin" execution. I spent several days on testing how to perform conditional file copying operation with the help of maven assembly plugin and finally got a workaround. Executions with different ids inside plugin config will be combined while those with same id will be overrided. Then is there anything else should I do with this PR @zentol ?

**Comment by zentol** [comment]
@paul8263 I'll take it from here ;)

**Pull request merged**
