### PR TITLE
[FLINK-11249] FlinkKafkaProducer011 can not be migrated to FlinkKafkaProducer

### PR DESCRIPTION
**Pull request by tvielgouarin**
## What is the purpose of the change

Adding migration test for the universal `FlinkKafkaProducer` and the `FlinkKafkaProducer011`. 

## Brief change log

- Implemented a new `KafkaMigrationTestEnvironmentImpl` that allows to save the tmp files of the KafkaBroker.
- changed 'KafkaBaseTest` to allow modification of the desired Kafka test Environment Implementation.
- Implemented `FlinkKafkaProducerMigrationVersionTest` that test migration of `FlinkKafkaProducer` from pre-made 1.7 savepoint to master without pending transactions.
- Implemented `FlinkKafkaProducer011MigrationTest` that test migration of `FlinkKakfaProducer011`
from pre-made 1.7 savepoint to master without pending transactions.
- Implemented `FlinkKakfaProducerMigrationOperatorTest` that test migration from `FlinkKafkaProducer011` master savepoint to `FlinkKafkaProducer` master without pending transactions

## Verifying this change

This change added tests and can be verified as follows:
- `FlinkKafkaProducerMigrationVersionTest` 
- `FlinkKakfaProducerMigrationOperatorTest`
- `FlinkKafkaProducer011MigrationTest`

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**yes** / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by tvielgouarin** [comment]
hi @pnowojski ,
The Travis check doesn't pass because the migration test of `FlinkKakfkaProducer011` --> `FlinkKafkaProducer` raise an Exception : `org.apache.flink.util.StateMigrationException: The new state serializer for operator state must not be incompatible.` . On master this error seems logic because the bug  `FlinkKafkaProducer011` can not be migrated to `FlinkKafkaProducer`isn't fixed yet. However I did try with @yanghua PR and the exception persist. I guess ever we can't initialize the state of a different operator with testHarness or the bug isn't fixed even after the PR.

**Comment by tvielgouarin** [comment]
So I tried to migrate a job with a `FlinkKafkaProducer011` to a `FlinkKafkaProducer` locally by using a a flink version built from @yanghua PR. And the Exception `org.apache.flink.util.StateMigrationException: The new state serializer for operator state must not be incompatible` still persist. So I guess this PR doesn't totally fixes the issue.

**Comment by rmetzger** [comment]
Note to other reviewers, this is a companion pull request to this PR: https://github.com/apache/flink/pull/7405
@pnowojski is actively reviewing the changes there, but he's away for 2 weeks.

**Comment by pnowojski** [comment]
There were couple of issues with the tests that you proposed @tvielgouarin. One of them was that you were catching and ignoring the exception in your tests and this was hiding some issues, while tests were "passing" and there was quite a lot of code duplication. I have reimplemented most of it and opened another PR  (it has some refactoring/clean ups):
https://github.com/apache/flink/pull/7677

The equivalent code to your PR is [this commit](
https://github.com/apache/flink/pull/7677/commits/673e93a4104fd7bcb9f54275008cb2f90d81c692) from my PR.

**Comment by aljoscha** [comment]
The Jira issue has been resolved by now.

**Pull request closed without merging**
