### PR TITLE
[FLINK-22627][runtime] Remove SlotManagerImpl

### PR DESCRIPTION
**Pull request by KarmaGYZ**
## What is the purpose of the change

 Remove SlotManagerImpl and its related classes. This PR base on the #15812 .

I do not remove the `SlotRequest` because I think it should belong to #15812 as discussed. But I also open to do it in this PR. If the plan changes, pls ping me @tillrohrmann @lqjack .

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by tillrohrmann — APPROVED** [review]
Thanks for creating this PR @KarmaGYZ. The removal looks good to me. I will merge this PR once #15812 has been merged.

**Comment by KarmaGYZ** [comment]
Rebase on #16485

**Comment by tillrohrmann** [comment]
I've merged the PR #16485 @KarmaGYZ. Could you rebase your PR onto the latest master. Then I can merge this PR very soon.

**Comment by KarmaGYZ** [comment]
Thanks for the review and the awesome clean up in #16485, @tillrohrmann ! PR rebased onto the latest master.

**Comment by tillrohrmann** [comment]
Great, thanks @KarmaGYZ. Merging this PR now.

**Pull request closed without merging**
