### PR TITLE
[FLINK-20068] Enhance the topic creation guarantee to ensure all the …

### PR DESCRIPTION
**Pull request by becketqin**
…brokers receive the metadata update.

## What is the purpose of the change
This patch enhances the Kafka topic creation guarantee by adding a check to the `KafkaTestEnvironmentImpl#createTestTopic()` to ensure all the brokers have received the metadata update. This will ensure all the topic metadata information query will see the created topic.

## Brief change log
-  wait until all the brokers have received metadata update before returning from `KafkaTestEnvironmentImpl.createTestTopic()`.

## Verifying this change
The change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by becketqin** [comment]
@PatrickRen Will you help take a look? Thanks.

**Comment by PatrickRen** [comment]
Hi @becketqin , @Sxnan reproduced an instance of failure locally and I investigated the trace-level log. The response of the first `listTopics` request only contained topic-1, and the latter two `listTopics` requests successfully retrieved both topic-1 and pattern-topic. I think this is because the second topic was not ready when the first test case was running. Your changes look good to me. 

Also there's a typo in the test case:
https://github.com/apache/flink/blob/592c2e7ab392cc0bb368d630eff0a89dd5ccf2a4/flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/enumerator/subscriber/KafkaSubscriberTest.java#L86
I think NUM_PARTITIONS should be used instead of NUM_RECORDS_PER_PARTITION, although their values are identical. 

Thanks~

**Comment by becketqin** [comment]
@PatrickRen @Sxnan Thanks for helping verify the fix. I'll merge the PR now.

**Comment by becketqin** [comment]
Merged to master.
cacb4c1fb1d6123d0aeb93d550ffcafa6ad4a8fb
Cherry-picked to 1.11：
18e4c1ba5b66c704b3ea7e5ba8fb7f3499207903

**Pull request closed without merging**
