### PR TITLE
[FLINK-15370][state backends] Make sure sharedResources takes effect in RocksDBResourceContainer

### PR DESCRIPTION
**Pull request by carp84**
## What is the purpose of the change

Currently we never uses the `sharedResources` in `RocksDBResourceContainer`, and in `RocksDBStateBackend.createKeyedStateBackend` we set the shared write buffer manager to the `dbOptions` but never pass/use it in `RocksDBKeyedStateBackendBuilder`, which leads to the result that different RocksDB backends actually are using separate write buffer managers thus the total memory control is invalid.

## Brief change log

Always set write buffer manager to the one from `sharedResources` if it's non-null, in `RocksDBResourceContainer.getDbOptions`.

## Verifying this change

This change added a new `testSharedResources` test case to cover the problematic case.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by carp84** [comment]
@Myasuka @StephanEwen Please help review when time allows, thanks!

**Comment by Myasuka** [comment]
LGTM

It could be better to describe clearly that once `sharedResources` is not null, we would set write buffer manager extracted from `sharedResources`.

**Comment by StephanEwen** [comment]
Taking a look now...

**Comment by StephanEwen** [comment]
Good fix, +1 to merge for both `master` and `release-1.10`.

**Comment by StephanEwen** [comment]
Merging this...

**Pull request closed without merging**
