### PR TITLE
[FLINK-5321] [metrics] LocalFlinkMiniCluster starts JM MetricQueryService

### PR DESCRIPTION
**Pull request by zentol**

### CODE REVIEW

**Comment by zentol** [comment]
We only need it in that case, yes.

**Comment by zentol** [comment]
I can add a check for both the JM/TM to only start the service if the web UI is started as well.

**Comment by StephanEwen** [comment]
I think that approach makes sense.

**Comment by zentol** [comment]
@StephanEwen Could you take another look?

**Comment by StephanEwen** [comment]
+1 to merge this for 1.2 and master

**Comment by zentol** [comment]
merging.

**Pull request closed without merging**
