### PR TITLE
[FLINK-15228][docs] Drop vendor specific deployment documentation

### PR DESCRIPTION
**Pull request by sjwiesman**
## What is the purpose of the change
Based on a mailing list discussion we want to drop vendor specific deployment documentation

ml discussion: http://apache-flink-mailing-list-archive.1008284.n3.nabble.com/DISCUSS-Drop-vendor-specific-deployment-documentation-td35457.html

It would be nice to commit this into release-1.10 along with master as some pages are just incorrect (gce_setup and mapr). 

## Brief change log

The first commit in this PR is from #10558 

Remove the following pages:

- ops/deployment/aws.{zh.}md
- ops/deployment/gce_setup.{zh.}md
- ops/deployment/mapr.{zh.}md

Update internal links
Setup setup external redirects

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by sjwiesman** [comment]
@rmetzger Would you want to maybe take a look at this?

**Comment by rmetzger** [comment]
Thanks for opening the PR. 
Will you do a separate PR for adding a new "vendors" page?

**Comment by sjwiesman** [comment]
Rebased and force pushed to remove #10558 

@rmetzger It was never clear to me from the ml discussion if we were actually doing that. I was working off Ufuks suggestion to just drop these pages for now and keep an updated vendor discussion seperate.

**Comment by rmetzger** [comment]
Yeah, the discussion was not conclusive. I tend to like the idea of the vendor page, but I don't have the capacity to work on it right now. I'm concerned that this idea gets lost.
Are you going to kick off a separate discussion? (Doesn't have to be immediate, as long as you'll eventually do it)

**Comment by sjwiesman** [comment]
Yes, I’ll start one on Monday. I’m guessing if I do it now it will get lost in everyone’s emails over the weekend.

**Comment by rmetzger** [comment]
Cool, thanks. I'm merging this.

**Pull request merged**
