### PR TITLE
[FLINK-7058] Fix scala-2.10 dependencies

### PR DESCRIPTION
**Pull request by pnowojski**
Before fixup:

```
$mvn dependency:tree -DskipTests -pl flink-scala -Pscala-2.11 | grep quasi
[INFO] +- org.scalamacros:quasiquotes_2.10:jar:2.1.0:compile
$ mvn dependency:tree -DskipTests -pl flink-scala -Dscala-2.11 | grep quasi
$ mvn dependency:tree -DskipTests -pl flink-scala | grep quasi
[INFO] +- org.scalamacros:quasiquotes_2.10:jar:2.1.0:compile
$ mvn dependency:tree -DskipTests -pl flink-scala -Pscala-2.10 | grep quasi
[INFO] +- org.scalamacros:quasiquotes_2.10:jar:2.1.0:compile
$ mvn dependency:tree -DskipTests -pl flink-scala -Dscala-2.10 | grep quasi
[INFO] +- org.scalamacros:quasiquotes_2.10:jar:2.1.0:compile
```

After fixup:
```
$ mvn dependency:tree -DskipTests -pl flink-scala -Pscala-2.11 | grep quasi
$ mvn dependency:tree -DskipTests -pl flink-scala -Dscala-2.11 | grep quasi
$ mvn dependency:tree -DskipTests -pl flink-scala | grep quasi
$mvn dependency:tree -DskipTests -pl flink-scala -Pscala-2.10 | grep quasi
[INFO] +- org.scalamacros:quasiquotes_2.10:jar:2.1.0:compile
$ mvn dependency:tree -DskipTests -pl flink-scala -Dscala-2.10 | grep quasi
[INFO] +- org.scalamacros:quasiquotes_2.10:jar:2.1.0:compile
```

### CODE REVIEW

**Comment by zentol** [comment]
You can rebase this PR now.

**Comment by pnowojski** [comment]
@zentol rebased

**Comment by zentol** [comment]
LGTM, +1.

**Comment by aljoscha** [comment]
This is not relevant for the `release-1.3` branch? (I'm asking because that one still has some issues)

**Comment by zentol** [comment]
@aljoscha It is also a problem for 1.3. It's even worse since it still uses the scala.binary.version property, which thus may try to fetch a 2.11 version of quasiquotes which just doesn't exist.

**Comment by zentol** [comment]
I made this a blocker since it means you cannot build 1.3 with the scala 2.11 profile.

**Comment by aljoscha** [comment]
Perfect! (I mean the "making it a blocker and fixing it" part, not the "it being broken" part). 😅

**Comment by zentol** [comment]
@aljoscha Yeah, so this doesn't affect 1.3. In 1.3 scala 2.10 is still the default, so it needs the reverse logic of this PR, which, well, is the one that was present in 1.3.

**Comment by zentol** [comment]
or rather it affects it in a different way. What we _try_ is to have a dependency by default but removed in specific profile, which is just not possible with maven.

**Comment by zentol** [comment]
merging to master,

**Comment by pnowojski** [comment]
Thanks!

**Pull request closed without merging**
