### PR TITLE
[FLINK-11982] [table] File System Connector's support JSON Format and JSON file BatchTableSource

### PR DESCRIPTION
**Pull request by ambition119**
## What is the purpose of the change

fix [ISSUE #11982](https://issues.apache.org/jira/browse/FLINK-11982) 

## Brief change log

-  [flink-connector-json] module to support File System Connector's JSON Format.
-  JsonBatchTableSourceFactory is a BatchTableSourceFactory
-  JsonBatchTableSource is a BatchTableSource

## Verifying this change

Unit tests for add java class.

*[**flink json format doc**](https://ci.apache.org/projects/flink/flink-docs-release-1.8/dev/table/connect.html#json-format) : File system connector use JSON Format example:*
```java
FileSystem connector = new FileSystem().path(path);

// or withFormatSchema
tEnv.connect(connector)
       .withFormat(new Json()
				.schema(new RowTypeInfo(FIELD_TYPES, FIELD_NAMES))
				.failOnMissingField(true)
      )
      .registerTableSource("jsonTable");

// or withFormatJsonSchema
tEnv.connect(connector)
	.withFormat(new Json()
				.jsonSchema("{\"type\":\"object\",\"properties\":{" +
				"\"author\":{\"type\":\"string\"}," +
				"\"title\":{\"type\":\"string\"}," +
				"\"price\":{\"type\":\"number\"}," +
				"\"zip_code\":{\"type\":\"string\"}" +
				"}}")
				.failOnMissingField(true)
        )
	.registerTableSource("jsonTable");

//or withScheam
tEnv.connect(connector)
	.withFormat(new Json().failOnMissingField(true).deriveSchema())
	.withSchema(
				new Schema()
					.field("author", Types.STRING())
					.field("title", Types.STRING())
					.field("price", Types.DOUBLE())
					.field("zip_code", Types.STRING())
          )
	.registerTableSource("jsonTable");

String fullSql = "select * FROM jsonTable";
Table fullTable = tEnv.sqlQuery(fullSql);
``` 

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**yes**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (**no**)
  - The serializers: (**no**)
  - The runtime per-record code paths (performance sensitive): (**no**)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (**no**)
  - The S3 file system connector: (**no**)

## Documentation

  - Does this pull request introduce a new feature? (**yes**)
  - If yes, how is the feature documented? (example)

### CODE REVIEW

**Comment by StephanEwen** [comment]
In this PR, the format "JSON" and the connector "file" are mixed into one aspect.

In the design for sources, we want to keep format and connector separate, so they can be combined (i.e., combine file with Avro, combine Kafka with JSON, etc.).
The way to support JSON files would be to combine the "file" Connector with the Json Format.

There is also a [flink-json](https://github.com/apache/flink/tree/master/flink-formats/flink-json) module already.

Does that approach currently not work?

@twalthr or @dawidwys Could you share some details here?

**Comment by ambition119** [comment]
> In this PR, the format "JSON" and the connector "file" are mixed into one aspect.
> 
> In the design for sources, we want to keep format and connector separate, so they can be combined (i.e., combine file with Avro, combine Kafka with JSON, etc.).
> The way to support JSON files would be to combine the "file" Connector with the Json Format.
> 
> There is also a [flink-json](https://github.com/apache/flink/tree/master/flink-formats/flink-json) module already.
> 
> Does that approach currently not work?
> 
> @twalthr or @dawidwys Could you share some details here?

yes , I dev also use [flink-json module](https://github.com/apache/flink/blob/c1b8f6757cee56ee9744f0533d2ec0118ef82801/flink-connectors/flink-connector-json/pom.xml#L77) like [JsonRowDeserializationSchema](https://github.com/apache/flink/blob/c1b8f6757cee56ee9744f0533d2ec0118ef82801/flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonRowDeserializationSchema.java) in JsonRowInputFormat.

But [org.apache.flink.formats.json.JsonRowFormatFactory](https://github.com/apache/flink/blob/c1b8f6757cee56ee9744f0533d2ec0118ef82801/flink-formats/flink-json/src/main/resources/META-INF/services/org.apache.flink.table.factories.TableFactory) not support File System Connector [ISSUE #11982](https://issues.apache.org/jira/browse/FLINK-11982), so dev JsonBatchTableSourceFactory  and JsonBatchTableSource. 

This implementation has been validated and run for a while in our flink production environment. thanks.

**Comment by dawidwys** [comment]
Hi @ambition119 
I agree with @StephanEwen that this PR mixes the concepts of `connector`(file) and `format`(json).

I don't necessarily understand the comment that `JsonRowFormatFactory` does not support File System Connector. First, there is no file system connector, and second of all this is a format factory thus it should have no notion of connector.

I think you could rework your `JsonBatchTableSource` and `JsonRowInputFormat` to accept any `DeserializationSchema<Row>` similar to how `org.apache.flink.streaming.connectors.kafka.KafkaTableSourceBase` works.

Another issue on a more conceptual layer is that the proposed `RowInputFormat` assumes that each line in a file is a separate record. I agree this is probably the most common case, but not the only one. 
Files can be also written with a different layout (e.g. Parquet), thus we should differentiate that also on the connector level.

I'm guessing you might have been inspired by `CsvTableSource`, but it was one of the first `TableSource`s that was written before we decided to split connectors and formats and its design is flawed. It also uses `RowCsvInputFormat` that as I said in the previous paragraph applies custom block(in this case line) splitting based on configurable delimiter.

**Comment by ambition119** [comment]
> Hi @ambition119
> I agree with @StephanEwen that this PR mixes the concepts of `connector`(file) and `format`(json).
> 
> I don't necessarily understand the comment that `JsonRowFormatFactory` does not support File System Connector. First, there is no file system connector, and second of all this is a format factory thus it should have no notion of connector.
> 
> I think you could rework your `JsonBatchTableSource` and `JsonRowInputFormat` to accept any `DeserializationSchema<Row>` similar to how `org.apache.flink.streaming.connectors.kafka.KafkaTableSourceBase` works.
> 
> Another issue on a more conceptual layer is that the proposed `RowInputFormat` assumes that each line in a file is a separate record. I agree this is probably the most common case, but not the only one.
> Files can be also written with a different layout (e.g. Parquet), thus we should differentiate that also on the connector level.
> 
> I'm guessing you might have been inspired by `CsvTableSource`, but it was one of the first `TableSource`s that was written before we decided to split connectors and formats and its design is flawed. It also uses `RowCsvInputFormat` that as I said in the previous paragraph applies custom block(in this case line) splitting based on configurable delimiter.

Thank you for your reply and discussion. 

First of all, the naming of this PR is a bit confusing. The code function mainly supports json files, such as local or hdfs, so you can rename it to JsonFileXxx.

Second, flink does exist File System Connector, the official document is
https://ci.apache.org/projects/flink/flink-docs-release-1.8/dev/table/connect.html#file-system-connector, provide [CsvBatchTableSourceFactory](https://github.com/apache/flink/blob/master/flink-table/flink-table-planner/src/main/resources/META-INF/services/org.apache.flink.table.factories.TableFactory#L16)  to support reading of csv files.
image

unit test [FileSystem connector CSV Format](https://github.com/apache/flink/blob/master/flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/descriptors/TableDescriptorTest.scala#L59)
add example:
```java
public static void main(String[] args) throws Exception {
		ExecutionEnvironment env = ExecutionEnvironment.getExecutionEnvironment();
		BatchTableEnvironment tEnv = BatchTableEnvironment.create(env);
		FileSystem connector = new FileSystem().path("/path/to/csv/in.csv");

		OldCsv oldCsv = new OldCsv()
			.field("a", Types.STRING())
			.field("b", Types.INT())
			.field("c", Types.BOOLEAN());
		Schema schema = new Schema()
			.field("a", Types.STRING())
			.field("b", Types.INT())
			.field("c", Types.BOOLEAN());

		tEnv.connect(connector)
			.withFormat(oldCsv)
			.withSchema(schema)
			.registerTableSource("csvTable");

		String fullSql = "select * FROM csvTable";
		Table fullTable = tEnv.sqlQuery(fullSql);

		DataSet<Row> fullDS = tEnv.toDataSet(fullTable, Row.class);
		List<Row> result = fullDS.collect();

		System.out.println(result);
}
```

Third, for example, the hive support json file also is one line  a separate record, otherwise it is not supported. eg:
```json
{
	"fruit": [{
		"weight": 8,
		"type": "apple"
	}, {
		"weight": 9,
		"type": "pear"
	}],
	"author": "J. R. R. Tolkien",
	"title": "The Lord of the Rings",
	"category": "fiction",
	"price": 22.99,
	"isbn": "0-395-19395-8",
	"email": "amy@only_for_json_udf_test.net",
	"owner": "amy",
	"zip_code": "94025",
	"fb_id": "1234"
}
```
thanks.

**Comment by dawidwys** [comment]
Ad. 1 Once again we aim to separate connector and formats => JsonFile = Json + File
Ad. 2  It provides `FileSystem` descriptor not connector. See my comments about `CsvTableSource`. It's design is broken and we do not want to repeat this error
Ad. 3 Good to know, hive is not the source of truth though. Unfortunately we cannot accept general purpose code that works in just a single very narrow setup.

**Comment by ambition119** [comment]
> Ad. 1 Once again we aim to separate connector and formats => JsonFile = Json + File
> Ad. 2 It provides `FileSystem` descriptor not connector. See my comments about `CsvTableSource`. It's design is broken and we do not want to repeat this error
> Ad. 3 Good to know, hive is not the source of truth though. Unfortunately we cannot accept general purpose code that works in just a single very narrow setup.

@StephanEwen @dawidwys  Thank you for your suggestions and responses.  I am developing based on flink 1.6.x, and now I understand what you are talking about, so I will close this PR.

**Pull request closed without merging**
