### PR TITLE
[hotfix][docs] Fix query results in data_stream_api

### PR DESCRIPTION
**Pull request by polaris6**
SQL：SELECT UPPER(f0) FROM InputTable，so the result should be in uppercase.

### CODE REVIEW

**Comment by polaris6** [comment]
Hi @leonardBang, could you please help me to review this pr? Thank you very much!

**Comment by leonardBang** [comment]
Thanks @polaris6 for the contribution, could also update the result for `Scala ` and `Python` example ?

**Comment by polaris6** [comment]
Done, thanks @leonardBang

**Review by leonardBang — APPROVED** [review]
Thanks @polaris6 for the update, LGTM, wait the CI green

**Comment by polaris6** [comment]
Hi @leonardBang, could you please help me merge this PR when you have time? Thank you very much!

**Pull request merged**
