### PR TITLE
[FLINK-12422] Remove IN_TESTS for make test code and production code consistent

### PR DESCRIPTION
**Pull request by yanghua**
## What is the purpose of the change

*This pull request removes IN_TESTS for make test code and production code consistent*

## Brief change log

  - *Remove IN_TESTS for make test code and production code consistent*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by yanghua** [comment]
@zjffdu

**Comment by yanghua** [comment]
cc @tillrohrmann

**Comment by yanghua** [comment]
Hi @tillrohrmann Thanks for your suggestion, actually, I have found the error log from Travis, it can not just remove the code snippet.
I am working on another PR when it is OK, I will go back to handle this. If I have a problem, I will ping you.

**Comment by yanghua** [comment]
Hi @tillrohrmann It seems many test cases do not use `YarnTestBase#createYarnClusterDescriptor`, so the Travis is still failed. Maybe here needs furthermore refactor.

**Comment by zjffdu** [comment]
You are right @yanghua This is not a trivial change, need more sophisticated refactoring.

**Comment by yanghua** [comment]
@zjffdu OK, thanks, let me try. if I am blocked, I will ping you guys for help.

**Comment by yanghua** [comment]
Hi @tillrohrmann Added `yarn-site.xml` to the ship file list, but it seems there is still a connection issue between AM and RM.

**Comment by tillrohrmann** [comment]
I guess that some test might not pick the right `yarn-site.xml` up. Maybe @zjffdu can help you with that because he already looked into it a bit.

**Comment by yanghua** [comment]
leaving...

**Pull request closed without merging**
