### PR TITLE
[FLINK-1753] [streaming] Added test for Kafka connector with tuple type

### PR DESCRIPTION
**Pull request by gaborhermann**
Fixed a small bug with Kafka key serializer and extended the KafkaITCase with multiple tests:
* topology that sends Kafka non-String type (Tuple) objects
* topology that uses custom partitioning at Kafka producer.
* topology that uses the regular KafkaSource

### CODE REVIEW

**Comment by rmetzger** [comment]
The code seems to be based on a pretty old state of master ;)

I redesigned the KafkaITCase to integrate it better with Junit: https://github.com/rmetzger/flink/commit/4fcab1746b9456b8286ef4e77bd7fbd4ce10fb47
With the change, I use @BeforeClass and @AfterClass to bring up and shut down kafka. For each test, there is a @test annotated method.

**Comment by gaborhermann** [comment]
Thanks for the remark. I updated the branch and added more tests.

**Comment by rmetzger** [comment]
The code looks good. Tests are running locally.
As soon as travis signals green, I'm +1 to merge.

**Comment by rmetzger** [comment]
I'm merging this PR ....

**Pull request closed without merging**
