### PR TITLE
[FLINK-3340] [runtime] Fix object juggling in drivers

### PR DESCRIPTION
**Pull request by greghogan**
A second attempt at object swapping in reduce drivers.

### CODE REVIEW

**Comment by ggevay** [comment]
So, if I understand correctly, this is aiming to fix the problem that was brought up by [1], but in a different way then proposed there.

I still have the same worry about this solution that I wrote in this comment: [2]: `MutableObjectIterator.next(reuse)` is used at 271 places, according to IntelliJ. If we accept the change in the object reuse contract of `MergeIterator.next(reuse)` introduced by 0a8df6d513fa59d650ff875bdf3a1613d0f14af5, all the call sites can potentially have the same problem as the reduce drivers, so we should check all of these 271 places. For example, just by skimming the list for a few minutes, all the 8 calls in `CrossDriver` seem suspicious at first glance, as well as the calls in `UnionWithTempOperator`, `MutableHashTable.ProbeIterator.next`, and `ReusingBuildFirstHashJoinIterator.callWithNextKey`.

My alternative solution [3] has the drawback that it would introduce an extra copying in `MergeIterator.HeadStream.getHead`, but would change the contract of `MergeIterator.next(reuse)` back to the same as it was before 0a8df6d513fa59d650ff875bdf3a1613d0f14af5.

[1] https://issues.apache.org/jira/browse/FLINK-3291
[2] https://issues.apache.org/jira/browse/FLINK-3291?focusedCommentId=15130452&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15130452
[3] https://github.com/ggevay/flink/commit/b05e12075bb5d0518b6fe12cd8f7de1e6b16f805

**Comment by greghogan** [comment]
Hi, @ggevay, these fixes to the reduce drivers are independent of changes to `MutableObjectIterator`. This patch is intended to fix the bug you reported in [FLINK-3291](https://issues.apache.org/jira/browse/FLINK-3291).

+1 to improving the `MutableObjectIterator` API. Let's continue the conversation over on [FLINK-3291](https://issues.apache.org/jira/browse/FLINK-3291)!

**Comment by ggevay** [comment]
Sorry, but I don't think it is independent, because the bug in the reduce drivers could alternatively be fixed by saying that the bug is actually not in the reduce drivers at all, but in `MergeIterator`, and fix it there instead (as in https://github.com/ggevay/flink/commit/b05e12075bb5d0518b6fe12cd8f7de1e6b16f805). This depends on what we want the contract of `MergeIterator.next(reuse)` to be.

**Comment by greghogan** [comment]
`MergeIterator.next(reuse)` should allow object swapping. The source code documentation should be improved to make this clearer, but this contract is necessary to minimize the copying of objects

**Comment by ggevay** [comment]
OK, after Stephan's comment on FLINK-3291, I agree.

**Comment by StephanEwen** [comment]
This looks good to me.

+1 for merging, but removing the System.out.println

**Comment by greghogan** [comment]
@StephanEwen just to clarify, since time is of the essence, would you like me to update the pull request without the println's?

**Comment by StephanEwen** [comment]
If you can quickly do it, yes.

Otherwise whoever merges this tomorrow, please remove the sysout statements.
We try to keep the maven output a bit cleaner that way. If you want to output something into the logs for the tests, just use a regular slf4j logger...

**Comment by greghogan** [comment]
Pushed. Thanks for the explanation.

**Comment by xhumanoid** [comment]
Hi, I know than issue closed, but he maybe have small bug

https://github.com/apache/flink/pull/1626/files#diff-4a133896fec62bcabc1120b0df8cb8daR205

in hashCode recursion on this.hashCode()

**Comment by greghogan** [comment]
Thank you @xhumanoid for reporting this! I will make the fix.

**Pull request closed without merging**
