### PR TITLE
[hotfix][table sql planner/table sql legacy planner]fix icu license in NOTICE file.

### PR DESCRIPTION
**Pull request by leonardBang**
## What is the purpose of the change

*This pull request fix the icu license, move the icu being under the ICU license block in notice file.*

## Brief change log

  - *update file flink/flink-table/flink-table-planner-blink/src/main/resources/META-INF/NOTICE*
  - *update file flink/flink-table/flink-table-planner/src/main/resources/META-INF/NOTICE*

## Verifying this change

This change is a hotfix for docs without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): ( no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by leonardBang** [comment]
Hello @aljoscha ,could you take a look this PR？

**Comment by aljoscha** [comment]
Looks good, could you fix the commit title to say `[hotfix][table sql planner/table sql legacy planner]fix icu license in NOTICE file`, then I can quickly merge it here on github without checking it out and fixing myself.

**Comment by leonardBang** [comment]
update the commit title.

**Comment by aljoscha** [comment]
perfect, thanks!

**Pull request merged**
