### PR TITLE
[FLINK-2586] Unstable Storm Compatibility Tests

### PR DESCRIPTION
**Pull request by mjsax**
- added BLOCKING flag to FlinkLocalCluster
 - added NullTerminatingSpout and SpoutOutputCollectorObserver plus tests
 - reworked test accordingly
   - set BLOCKING flag for ITCases
   - make infinite spouts finite using NullTerminatingSpout
   - removed sleep time to get stable
 - fixed bug in BoltSplitITCase and SpoutSplitITCase
   - exception in VerifyAndEnrichBolt is swallowed and test would not fail (replaced by errorFlag)
 - reduced sleep-time in BoltSplitITCase and SpoutSplitITCase to reduce testing time
 - fixed WrapperSetupHelperTest
   - reworked to origianl version with more than two inputs
     (was limite to two inputs because more the two inputs per bolt was not supported in between, which is now fixed)
minor code cleanup (removed unused imports, indenting, etc.)

### CODE REVIEW

**Comment by StephanEwen** [comment]
Thank you for addressing this.

Looks good to me, +1 to merge this

**Comment by mjsax** [comment]
Thanks. Will merge this.

**Comment by tillrohrmann** [comment]
@mjsax, most likely it happened by accident but it's good practice to separate the git commit subject from the body by inserting a line break. That way, git can show you a nice one line git history `git log --oneline` without seeing the body of the commit message. Also some other tools format the git log nicely if one follows this rule.

**Comment by mjsax** [comment]
@tillrohrmann I was not aware of that. Thanks for letting me know. Will do so in the future.

**Pull request closed without merging**
