### PR TITLE
[FLINK-5344] Fixed the dockerized doc build, which has been broken fo…

### PR DESCRIPTION
**Pull request by alpinegizmo**
I believe this resolves all of the open issues involving building the docs:

The dockerized build needs different gem versions than those specified in Gemfile.lock.
The -p option was broken by PR 2940.
The build bot needs ruby 1.9 and was also broken by PR 2940.

### CODE REVIEW

**Comment by greghogan** [comment]
I have not followed this ticket, but by having different build profiles are we expecting developers to test against both? Is the incremental build not working with the buildbot version of Ruby?

**Comment by alpinegizmo** [comment]
I've been using the incremental build option for several weeks, and find it to be a significant productivity booster. And yes, it requires ruby 2.0 or higher (which is nearly four years old at this point), while the buildbot is on some flavor of 1.9 (no longer supported, even for critical security bugs).

I'm planning to continue to invest significant time in improving the docs, so I'd like to get this in, but you're right, having two build environments is suboptimal (and actually we already have two, in a way, since the dockerized build uses ruby 2.0). I'm hoping we can get the buildbot upgraded to something less ancient and then drop the 1.9-based Gemfile. @mxm has filed a ticket to that effect; we'll see.

**Comment by mxm** [comment]
Thank you for fixing this, David! I have just verified that this fixes the Buildbot related issues. It is a shame that we only have Ruby 1.9, but for now we will have to deal with this limitation. Especially because we want up-to-date docs for the release :)

Merging this.

**Comment by mxm** [comment]
Had to add this to the root `pom.xml` to convince the Rat plugin to pass.

```xml
                        <exclude>docs/ruby2/Gemfile.lock</exclude>
```

**Comment by greghogan** [comment]
@mxm what script or command is executed to build the docs on buildbot?

**Comment by mxm** [comment]
@greghogan `docs/build_docs.sh`

**Pull request closed without merging**
