### PR TITLE
[FLINK-5109] fix invalid content-encoding header of webmonitor

### PR DESCRIPTION
**Pull request by Hapcy**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x] Documentation --- not touched
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by greghogan** [comment]
Looks good to merge after the tests finish.

One more thought: if your IDE is set to fix trailing whitespace, it's fine in this PR since only a few lines changed but for larger PRs you'll want to limit formatting changes to code near your edits.

**Comment by Hapcy** [comment]
Thank you! I will pay attention to that next time I happen to contribute again.

The checks failed but as I see it didn't fail because of failing tests but because of some kind of crash. I don't think it happened because of my change. What do you think or what to do next?

**Comment by greghogan** [comment]
The builds are run with five different configurations each split into two sets of tests. Looking at the details 9/10 passed which is a success.

**Comment by Hapcy** [comment]
I would like to ask when is a merge expected? Do I have to do anything else?

**Comment by greghogan** [comment]
Unless a PR is urgent we typically allow a few days to see if any additional comments come in from the community. This looks good so I'm merging it now. Thanks for the contribution!

**Pull request closed without merging**
