### PR TITLE
[hotfix][docs] Fixed memory units in "Migration Guide" under "Memory Configuration" page.

### PR DESCRIPTION
**Pull request by liuzhuang2017**
### English document：
- The markdown file is located in docs/content/docs/deployment/memory/mem_migration.md.

image

### Chinese document：

- The markdown file is located in docs/content.zh/docs/deployment/memory/mem_migration.md.
image

**According to the Chinese and English documentation above, I think "Mb" in it should be "MB". Because Mb and MB are not the same,in terms of memory, a byte is the smallest storage slot. Your hard drives, SSDs, USB sticks, and system memory are always measured in bytes.**
Please see "https://www.lifewire.com/what-is-a-megabit-2483412" for detailed differences.
According to experience, they have the following relationship:
- 8 Mb = 1 MB
- 1Mb = 1/8 MB = 0.125 MB

## Brief change log

Changed "Mb" in the documentation to "MB".

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no )
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no )
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? ( no)

### CODE REVIEW

**Comment by liuzhuang2017** [comment]
@MartijnVisser , Sorry to bother you, can you help me review this pr? Thanks you.

**Review by MartijnVisser — CHANGES_REQUESTED** [review]
@liuzhuang2017 Thanks for this, but there are more occasions in the documentation. It would be great if you could fix them all in one go to avoid needing to make multiple PRs.

**Comment by liuzhuang2017** [comment]
@MartijnVisser ,Thanks for your reply, I'll try to fix all these kinds of issues in the documentation based on your suggestions.

**Review by MartijnVisser — APPROVED** [review]
LGTM

**Comment by MartijnVisser** [comment]
Pipeline failure is unrelated to docs change, merging

**Comment by liuzhuang2017** [comment]
@MartijnVisser , Thanks for your review.

**Pull request merged**
