### PR TITLE
Some fixes for Scala type analysis

### PR DESCRIPTION
**Pull request by aljoscha**

### CODE REVIEW

**Comment by aljoscha** [comment]
Any comments? Do we want this?

**Comment by vasia** [comment]
Hey @aljoscha,
it seems this is one needed for the Gelly Scala API :-)
Shall I go ahead and merge it?

**Comment by aljoscha** [comment]
I didn't want to merge it without any comments. But please, go ahead. :smile:

**Comment by StephanEwen** [comment]
It would be good to share a bit of information beyond `Some fixes for Scala type analysis` about what is actually changed. Then others could think about possible implications and give comments.

**Comment by aljoscha** [comment]
This excludes static fields in Scala Pojo analysis (because static fields should not be serialised/deserializerd), removes legacy code from Scala Type Descriptors and makes Scala Type Analysis work with Java Tuples (because several people complained about them not being supported in the Scala API, most prominently they are needed to port Gelly to Scala.)

**Comment by StephanEwen** [comment]
Looks reasonable.

Will merge this with the next batch...

**Comment by vasia** [comment]
Thanks :)

**Pull request closed without merging**
