### PR TITLE
[FLINK-7998] private scope is changed to public to resolve access exception

### PR DESCRIPTION
**Pull request by vetriselvan1187**

### CODE REVIEW

**Comment by greghogan** [comment]
Looks good but I have not tested. Can we also fix the parameter swap referenced in the JIRA?

**Comment by naeioi** [comment]
Also can you replace `params.get("order")` with `params.get("orders")` in TPCHQuery3.scala for consistency with java and the input hint?

**Comment by vetriselvan1187** [comment]
@greghogan @naeioi have done some changes in both TPCHQuery3.scala and TCPCHQuery3.java

**Comment by zentol** [comment]
Thank you for fixing this, merging.

**Pull request closed without merging**
