### PR TITLE
[FLINK-7137] [table] Flink TableAPI supports nested CompositeType mapped to nullable calcite RelDataType by default

### PR DESCRIPTION
**Pull request by walterddr**

### CODE REVIEW

**Comment by fhueske** [comment]
Thanks for the PR @walterddr.
This looks good to me. 
What do you think @twalthr?

**Comment by twalthr** [comment]
I tried to improve the stability regarding nullable types. This should fix FLINK-7177 and FLINK-7137. It ensures that all types have the correct nullability. By default, types are always nullable. If they are not nullable, than we know it for sure.

https://github.com/apache/flink/compare/master...twalthr:FLINK-7137

What do you think? @walterddr @fhueske

**Comment by walterddr** [comment]
@twalthr Thank you for the suggestion, yeah I think this nullable default to false issue will pop up soon somewhere else, might as well just resolve them all together. I incorporated your suggestions and also add some tests so that the problem could be captured during unitest instead of ITCases. Let me know what your thoughts on this are @fhueske @twalthr

**Comment by twalthr** [comment]
Thanks for the tests @walterddr. I will merge this now...

**Pull request closed without merging**
