### PR TITLE
[build] Consolidate scala checkstyle usage and update version to 0.8.0

### PR DESCRIPTION
**Pull request by mbalassi**
Consolidation is done via plugin management, so that configuration is done in one central location.

Version update is needed because the latest releaseof the plugin, 0.8.0 contains a fix for a bug that I have recently run into. [1]

[1] https://github.com/scalastyle/scalastyle/pull/124

### CODE REVIEW

**Comment by tillrohrmann** [comment]
Changes seem not to be complete. Travis test cases fail because of "Unable to find configuration file at location /home/travis/build/apache/flink/flink-yarn-tests/../../tools/maven/scalastyle-config.xml"

**Comment by mbalassi** [comment]
Thanks or catching it, pushed the fix.

**Comment by mbalassi** [comment]
If no objections I would like to merge this Friday morning.

**Comment by StephanEwen** [comment]
+1, looks good to me

A minor "wish" from my side: I like it to not have generated files in the project directories, so I'd suggest to change the output file path to put the file into the "target" dir:
```xml
<outputFile>${project.basedir}/target/scalastyle-output.xml</outputFile>
```

**Comment by mbalassi** [comment]
Great wish, my pleasure to grant it. :smile: 
Merging as soon as travis goes through.

**Pull request merged**
