### PR TITLE
[FLINK-14673][hive] Shouldn't expect HMS client to throw NoSuchObject…

### PR DESCRIPTION
**Pull request by lirui-apache**
…Exception for non-existing function

## What is the purpose of the change

Always to check MetaException when getting function with HMS client.

## Brief change log

  - Removed shim method getFunction.
  - Moved the logic to HiveMetastoreClientWrapper.

## Verifying this change

Existing test cases.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? NA

### CODE REVIEW

**Comment by lirui-apache** [comment]
@xuefuz @bowenli86 This is to port the fix of FLINK-14673 to 1.9.x. Please take a look. Thanks.

**Comment by bowenli86** [comment]
@lirui-apache  I ran into conflicts when rebasing to latest master. Can you resolve the conflicts first?

**Comment by bowenli86** [comment]
@lirui-apache can you confirm you have run build successfully on release 1.9? the CI is for 1.10

**Comment by lirui-apache** [comment]
@bowenli86 Yeah I locally verified hive connector tests pass with both 2.3.4 and 1.2.1. My own Travis build was also successful: https://travis-ci.org/lirui-apache/flink/builds/610152378?utm_medium=notification&utm_source=email
I checked the build logs and the artifacts have version 1.9-SNAPSHOT, so I suppose it built with the correct branch.

**Comment by lirui-apache** [comment]
@bowenli86 Thanks for merging. Closing this one.

**Pull request closed without merging**
