### PR TITLE
[FLINK-2194] [type extractor] Treats Writable type as generic type (interface)

### PR DESCRIPTION
**Pull request by tillrohrmann**
Adds check so that the `Writable` type is treated as a generic type.

### CODE REVIEW

**Comment by tillrohrmann** [comment]
Travis gives green light. Will merge since it's a trivial fix.

**Comment by StephanEwen** [comment]
I am unsure of where this leads us. The purpose of `Writable` is to make sure that we can use the Writable's custom serialization. If the type `Writable` itself is now treated as a generic type, it is serialized with Kryo and that voids the assumption that it uses its own serialization code.

What is the reason for doing it this way? Throwing an error that "raw" Writables are not supported would help them understand the issues easier...

**Comment by tillrohrmann** [comment]
The subtypes of `Writable` are still serialized using the special `Writable` serializer. However, there are situations where you only have a `Writable` type, e.g. for the Mahout DSL or if you have `DataSet` of `LongWritable` and `TextWritable`.. Why should we not allow to use the interface type then?

**Comment by tillrohrmann** [comment]
Moreover, it would be inconsistent IMO with the rest of the typing system. Sometimes interfaces are supported and sometimes not. For the user, this might be confusing since it's nowhere documented, as far as I know.

**Comment by StephanEwen** [comment]
Ah, okay. I was not aware that they are handled by a special writable serializer (that is subclass aware) and that still uses the writable logic. Is it s special kryo serializer that delegates to the writable logic?

**Comment by rmetzger** [comment]
I don't think Kryo is handling classes implementing `Writable` in a special way.
It should be trivial to add a special Kryo serializer for it (see also https://github.com/twitter/chill/issues/191)

**Comment by tillrohrmann** [comment]
I did not mean a special Kryo serializer but our very own `WritableSerializer`. With the current implementation `WritableTypeInformation` has precedence over `GenericTypeInfo`. This means that if the `TypeExtractor` sees a `Writable` subtype, then it creates a `WritableTypeInfo`. If the type is the `Writable` interface, then a `GenericTypeInfo` is returned and, thus, Kryo is used.

**Comment by tillrohrmann** [comment]
@rmetzger suggested to add a specialized Kryo serializer for the `Writable` interface. That way we could directly call the write method of `Writable` types which might be faster than Kryo's default serializer.

**Pull request closed without merging**
