### PR TITLE
[FLINK-11971] Fix kubernetes check in end-to-end test

### PR DESCRIPTION
**Pull request by aljoscha**
@dawidwys You originally added this. Do you think this simpler check would work as well?

@hequn8128 Sorry for taking this issue, but I quickly wanted to fix this before creating a new RC because I was running the end-to-end tests on my Mac.

### CODE REVIEW

**Comment by aljoscha** [comment]
cc @sunjincheng121

**Comment by sunjincheng121** [comment]
@flinkbot approve description
@flinkbot approve consensus

**Comment by sunjincheng121** [comment]
Thank you @aljoscha @dawidwys I am checking the change now...

**Comment by sunjincheng121** [comment]
Thanks for the quick fix @aljoscha!
It works well from my local ENV(iMac)
Merging...

Best,
Jincheng

**Comment by sunjincheng121** [comment]
@flinkbot approve all

**Comment by aljoscha** [comment]
Thanks for merging!

**Pull request closed without merging**
