### PR TITLE
[FLINK-23693][tests] Add principal creation possibilities to SecureTestEnvironment

### PR DESCRIPTION
**Pull request by gaborgsomogyi**
## What is the purpose of the change

There are use-cases where this is needed. A good example is Kerberos authentication handler which is intended to be added as external project in FLINK-23274.

## Brief change log

* Fixed some forgotten reference bugs
* Minor re-ordering to see easily what's de-referenced and what's not
* Added `additionalPrincipals` parameter to `SecureTestEnvironment.prepare`
* Added default kerberos init app entry to contexts in `SecureTestEnvironment.prepare`

## Verifying this change

* Existing unit tests
* New unit tests with local build in the mentioned Kerberos authentication handler (intended to be published soon)

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by gaborgsomogyi** [comment]
cc @gyfora

**Comment by gaborgsomogyi** [comment]
@flinkbot run azure

**Comment by gaborgsomogyi** [comment]
The current solution creates a new keytab file which makes the solution wrong. Reworking it...

**Comment by gaborgsomogyi** [comment]
I've just finished the testing and the provided changes are working as expected.

**Comment by gyfora** [comment]
@flinkbot approve all

**Pull request closed without merging**
