### PR TITLE
[FLINK-10009] [table] Fix the casting problem for function TIMESTAMPADD in Table

### PR DESCRIPTION
**Pull request by XuQianJin-Stars**
## What is the purpose of the change

*Fix the casting problem for function TIMESTAMPADD in Table*

## Brief change log

- *In judging `ScalarOperators` `generateTemporalPlusMinus` function to add the following the `date` conversion `timestamp` of logic, are as follows:*

  ```scala
  case (SqlTimeTypeInfo.DATE, TimeIntervalTypeInfo.INTERVAL_MILLIS) =>
    resultType match {
      case SqlTimeTypeInfo.DATE =>
        generateOperatorIfNotNull(nullCheck, SqlTimeTypeInfo.DATE, left, right) {
          (l, r) => s"$l $op ((int) ($r / ${MILLIS_PER_DAY}L))"
        }
      case SqlTimeTypeInfo.TIMESTAMP =>
        generateOperatorIfNotNull(nullCheck, SqlTimeTypeInfo.TIMESTAMP, left, right) {
          (l, r) => s"$l * ${MILLIS_PER_DAY}L $op $r"
        }
    }
  ```

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*

- *`TIMESTAMPADD` with DATE returns a TIMESTAMP value for sub-day intervals `ScalarFunctionsTest`*
- *Round to the last day of previous month for `ScalarFunctionsTest`*

## Does this pull request potentially affect one of the following parts:

- Dependencies (does it add or upgrade a dependency): (yes / no)
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
- The serializers: (yes / no / don't know)
- The runtime per-record code paths (performance sensitive): (yes / no / don't know)
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / no / don't know)
- The S3 file system connector: (yes / no / don't know)

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by XuQianJin-Stars** [comment]
@twalthr Thank you very much for helping me modify the title of this PR. Could you help me check this PR?

**Comment by sunjincheng121** [comment]
@XuQianJin-Stars Thanks for the PR!

The changes looks good to me. Here hope you can do one more check by test `timestampadd(MINUTE, 1, time '20:20:20')`, I think the process logic of `SqlTimeTypeInfo.TIME, TimeIntervalTypeInfo.INTERVAL_MILLIS` may have the same issue.

Thanks,
Jincheng

**Comment by wuchong** [comment]
Thanks for the work @XuQianJin-Stars ,  the commit looks good to me.

**Comment by XuQianJin-Stars** [comment]
@sunjincheng121 I have just tested calcite, and found that the parsing `timestampadd(MINUTE, 1, time '20:20:20')` type of calcite is TimeStamp. This problem seems to be a bug in calcite.

**Comment by XuQianJin-Stars** [comment]
hi @sunjincheng121 @wuchong 
I have just tested calcite, and found that the parsing `timestampadd(MINUTE, 1, time '20:20:20')` type of calcite is TimeStamp. This problem seems to be a bug in calcite. I have submitted isuse to calcite. The following is the link.
[CALCITE-2699](https://issues.apache.org/jira/browse/CALCITE-2699)
I find it necessary to open a new isuse for tracking timestampadd's time type handling problems.
What do you think?

**Comment by XuQianJin-Stars** [comment]
@sunjincheng121 @wuchong 
I have opened a new isuse to track timestampadd's time type handling problem.
[FLINK-10994](https://issues.apache.org/jira/browse/FLINK-10994)

**Comment by wuchong** [comment]
Thanks @XuQianJin-Stars  for looking into this. I think it's fine to separate it into different issues.

**Comment by sunjincheng121** [comment]
@XuQianJin-Stars Thanks for file the JIARs for the issue of timestampadd's time type both in Flink and Calcite.
+1 to merged.

**Comment by sunjincheng121** [comment]
Merging ...

**Pull request closed without merging**
