### PR TITLE
[FLINK-1743] Add multinomial logistic regression to machine learning library

### PR DESCRIPTION
**Pull request by mtunique**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

1. Refactor `MultipleLinearRegression` to extend `GeneralizedLinearModel`
2. Implement `LogisticRegression`
3. Change `LogisticLoss` with label in {0, 1}
4. Add `LogisticLinerRegression` test case

### CODE REVIEW

**Comment by thvasilo** [comment]
Hello @mtunique and thank you for you contribution! 

Could you briefly describe your changes/additions and how you have tested the implementation for correctness?

**Comment by mtunique** [comment]
@thvasilo 
- Add `MultipleLinearRegression ` to provide interfaces for the set of common properties and functions generalized linear models share.
- Change `LogisticLoss` to let it be with label in {0, 1}
- `LogisticLinerRegression` test: This test is originally from the Apache Spark project. Training Data: Weights are created randomly. Label is calculated by given scale and offset.

**Comment by thvasilo** [comment]
Thank you for the info!

In that case it's a bit ambiguous now which issue this PR is solving. If you are introducing an interface for GLMs we should be having this discussion under that context, because it changes the scope of the PR quite significantly re. design decisions vs. a simple implementation of logistic regression.

If you want, we can split this into different PRs and take it from there.

P.S. Any code that comes from the Spark project mus be clearly labeled as such, please make sure to give proper attribution.

**Comment by mtunique** [comment]
Thanks all for the comments.
The code from Spark has be labeled like some other codes from Spark.
I will spilt this PR into two PRs. The other one is for FLINK-2013.

**Comment by mtunique** [comment]
@thvasilo After #3756 is merged, I will change this PR.

**Comment by bowenli86** [comment]
Hi @mtunique any update on this PR?

**Comment by thvasilo** [comment]
Hello @bowenli86, AFAIK nobody's working on the PR's right now. I'm currently 100% focused on finishing my PhD so I won't have time to review.

**Comment by zentol** [comment]
Closing since flink-ml is effectively frozen.

**Pull request closed without merging**
