### PR TITLE
[FLINK-2767] [scala shell] Add Scala 2.11 support to Scala shell

### PR DESCRIPTION
**Pull request by chiwanpark**
This PR contains following changes:

* Add `ILoopCompat` class for supporting both Scala 2.10 and Scala 2.11 (Inspired by [Scalding REPL](https://github.com/twitter/scalding/blob/develop/scalding-repl/src/main/scala-2.11/com/twitter/scalding/ILoopCompat.scala))
* Some modification of POM to include `flink-scala-shell` with Scala 2.11

I have tested local execution and remote execution with standalone Flink cluster.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Cool, looks like a very nice solution.

The package directors structure seems a bit strange for teh file `flink-staging/flink-scala-shell/src/main/scala/org.apache.flink/api/scala/FlinkILoop.scala`. Is that on purpose?

**Comment by chiwanpark** [comment]
AFAIK, the directory structure is planned to correct in #1106. But I didn't know #1106 is closed. I'll update the directory structure.

**Comment by chiwanpark** [comment]
The directory name is changed.

**Comment by rmetzger** [comment]
@nikste, can you quickly review this PR?

**Comment by StephanEwen** [comment]
I think this looks good, I would merge it...

**Comment by nikste** [comment]
Code looks fine. However, I noticed if I compile the code (for scala version 2.11), and start up the scala shell manually (./start-scala-shell.sh), the autocomplete function (tab) and history (arrow up) are not working anymore.

**Comment by chiwanpark** [comment]
Oh, I'll investigate it.

**Comment by nikste** [comment]
For me it says:
~~~bash
Failed to created JLineReader: java.lang.NoClassDefFoundError: jline/console/completer/Completer
Falling back to SimpleReader.
~~~

**Comment by chiwanpark** [comment]
It occured by jline library version mismatching between Scala 2.10 and 2.11. Since Scala 2.11.5, we don't need jline dependency. Scala REPL uses its own jline library. So I upgraded Scala minor version to 2.11.7 and moved jline to Scala 2.10 only dependencies list.

**Comment by rmetzger** [comment]
Thank you for the review @nikste!

**Comment by fhueske** [comment]
Thanks for the update @chiwanpark!
LGTM, will merge it.

**Pull request closed without merging**
