### PR TITLE
[FLINK-10472] [table] Add CBRT math function supported in Table API and SQL

### PR DESCRIPTION
**Pull request by aai95**
## What is the purpose of the change

*This pull request adds `Cbrt` math function supported in Table API and SQL.*

## Brief change log

  - *Added `Cbrt` math function supported in Table API and SQL.*

## Verifying this change
*This change added test `ScalarFunctionsTest#testCbrt`.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (**yes** / no)
  - If yes, how is the feature documented? (not applicable / **docs** / JavaDocs / not documented)

### CODE REVIEW

**Comment by Guibo-Pan** [comment]
Hi, @aai95 thanks for your PR. We already have a previous `sqrt(numeric)`, which is actually `power(numeric, 0.5)`. I think it's better to align to the previous one.
Thanks.

**Comment by aai95** [comment]
Hello @Guibo-Pan, do you mean that it will be better to use `power(numeric, 1.0 / 3.0)` instead of `java.lang.Math.cbrt()`?

**Comment by Guibo-Pan** [comment]
@aai95 From my side, I wonder if we are going on to add "the fourth root", "the fifth root" and so on, or add a standard "the nth root" function. In that case, I think consistency should take into consideration. It's just an opinion, feel free to remain this or discuss more if you think not.
Thanks.

**Comment by aai95** [comment]
@Guibo-Pan thank you for your suggestion.
The idea about adding the "Nth root" function sounds good to me.
It will be analog of existing `POWER(x, y) = x ^ y`, but can be more useful in SQL like `ROOT(125, 3)` will produce 5, instead of `POWER(125, 1.0 / 3.0)`.
More pleasent syntax, I can rename this issue and rewrite implementation based on idea that `root(x, y) = power(x, 1 / y)`.
What do you think about it?

**Pull request closed without merging**
