### PR TITLE
[FLINK-10193] Add @RpcTimeout to JobMasterGateway.triggerSavepoint

### PR DESCRIPTION
**Pull request by GJL**
## What is the purpose of the change

*This adds the `@RpcTimeout` annotation to `JobMasterGateway.triggerSavepoint` so that the default timeout is overridden.*

cc: @uce @tillrohrmann 

## Brief change log

  - *Add @RpcTimeout to `JobMasterGateway.triggerSavepoint`.*

## Verifying this change

This change added tests and can be verified as follows:

  - *Manually verified the change by running `SlowToCheckpoint` job, which is attached to the FLINK-10193 issue. Savepoint duration was 45s and command used to take savepoint was: `bin/flink savepoint <JOB_ID> file:///tmp/flink-sps`*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (**yes** / no / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by GJL** [comment]
I see the following possibilities to test this:

1. Override `triggerSavepoint` to a NOP, and trigger savepoint twice with increasing timeouts. The second invocation should fail later.
2. Check for presence of the annotation with reflection.

I deliberately did not add tests because Option 1 is slow and depends on
_"good"_ thread scheduling. Option 2 is fragile and not refactoring friendly.

**Comment by tillrohrmann** [comment]
Can't we check in the `JobMaster#triggerSavepoint` method which `timeout` value was passed in? It is not a super good test but it would guard against this specific failure in the future.

**Comment by GJL** [comment]
@tillrohrmann The value of the timeout from the perspective of the method implementation will always be what is passed to the RPC. This is regardless of whether the annotation is present or not because if the annotation is missing, the `AkkaInvocationHandler`, cannot know which item in the args array should be replaced with the default timeout. 

If the call originates from the REST API, the value will be `RpcUtils.INF_TIMEOUT`:
https://github.com/apache/flink/blob/6258a4c333ce9dba914621b13eac2f7d91f5cb72/flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/savepoints/SavepointHandlers.java#L132 

I can add a test to the handler test suite but this will not verify my change.

**Comment by tillrohrmann** [comment]
You're right @GJL. Then I would vote for the first test case. Something along the lines:
```
Future future1 = jm.triggerSavepoint(1 ms);
Future future2 = jm.triggerSavepoint(inf);
future1.get() fails with TimeoutException && !future2.isDone()
```

**Comment by jelmerk** [comment]
Any ETA on this ? for non trivial jobs with a lot of state this is critical

**Comment by tillrohrmann** [comment]
Thanks for the contribution @GJL. Merging this PR.

**Pull request closed without merging**
