### PR TITLE
[docs][typos] Misprint in types.md

### PR DESCRIPTION
**Pull request by snuyanzin**
## What is the purpose of the change

Misprints in types.md
dataytes => datatypes

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by snuyanzin** [comment]
@fapaul sorry for the poke, I noticed you've merged some of my similar PRs.

**Review by fapaul — APPROVED** [review]
LGTM but please change the commit message to `[hotfix][docs] ...` and maybe rebase with the latest master

**Comment by snuyanzin** [comment]
> please change the commit message to [hotfix][docs] ... and maybe rebase with the latest master

sure, done

**Comment by snuyanzin** [comment]
@fapaul sorry for the poke

this is just a friendly notification that I updated the same for Chinese page.
Please let me know if anything else is required from my side

**Comment by fapaul** [comment]
@snuyanzin, I will merge the PR. Can you also check the release-1.15 and release-1.14 to fix them accordingly and open PRs?

**Comment by snuyanzin** [comment]
@fapaul  thanks for merging
yes, sure here there are PRs for 1.15 and 1.14
https://github.com/apache/flink/pull/19536
https://github.com/apache/flink/pull/19535

**Pull request merged**
