### PR TITLE
[FLINK-18632][table-planner-blink] Assign row kind from input to outp…

### PR DESCRIPTION
**Pull request by lzy3261944**
## What is the purpose of the change

This pull request assign row kind from input row to output row, otherwise every output row kind will be initiated by default type(insert type).

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

### CODE REVIEW

**Comment by wuchong** [comment]
Could you add a test to reproduce this problem?

**Comment by lzy3261944** [comment]
> Could you add a test to reproduce this problem?

OK，should i create a new java class named like PojoTypeTest under flink-table-planner-blink module parallel with class NullTypeTest?

**Comment by wuchong** [comment]
I think you can add tests in `StreamTableEnvironmentITCase` and reuse the POJO classes there.

**Comment by lzy3261944** [comment]
> I think you can add tests in `StreamTableEnvironmentITCase` and reuse the POJO classes there.

OK. I have already add a test case.

**Comment by lzy3261944** [comment]
I've simplified the test case, the last one has a little ambiguous.

**Comment by lzy3261944** [comment]
It's my pleasure.

**Pull request merged**
