### PR TITLE
[FLINK-27619][sql] Flink SQL supports NTILE Function

### PR DESCRIPTION
**Pull request by luoyuxia**
## What is the purpose of the change
To support NTILE function.

## Brief change log
  -  Add implementation for [NTILEAggFunction.java](https://github.com/apache/flink/pull/20348/files#diff-e28b9a84f2fe96c5568a9469678f927139dc6addee090020c9912ffd38d25e33) in the [commit](https://github.com/apache/flink/pull/20348/commits/56cd4b7233b125b4327ff4f5b0aa6ceaa776965c)
  - Fix using wrong constant for overwindow in the [commit](https://github.com/apache/flink/pull/20348/commits/f6f1aa0b1269decc43eb368ce50b5ec3619dfddf)

## Verifying this change
UT in [testNTILE](https://github.com/apache/flink/pull/20348/files#diff-81346deaed0bf56b2b392761a0be36cb3d25ace2c6999b7a1c22f797e7c07615R2812), [testOverWindowWithConstants3]([.../src/test/scala/org/apache/flink/table/planner/plan/batch/sql/agg/OverAggregateTest.scala](https://github.com/apache/flink/pull/20348/files#diff-6a5a747091df9819064c631e0ad1faf17aad64916a44481fc9fac2efb8cb8248))

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (**yes** / no)
  - If yes, how is the feature documented? (not applicable / **docs** / JavaDocs / not documented)

### CODE REVIEW

**Comment by luoyuxia** [comment]
Some explanation about the second commit. 
When I try to test such sql 
```sql
SELECT f, NTILE(4) over (order by e) NTILE(3) over (partition by d order by e desc) FROM Table5
```

**Review by wuchong — COMMENTED** [review]
LGTM.

@luoyuxia , could you help to rebase the branch?

**Comment by wuchong** [comment]
@flinkbot run azure

**Comment by wuchong** [comment]
The failed case is caused by FLINK-28844. 

Merging...

**Pull request merged**
