### PR TITLE
FLINK-35596: Make description field transient in AvroEncoding enum to avoid serializing it

### PR DESCRIPTION
**Pull request by venkata91**
## What is the purpose of the change

This change marks `description` field in `AvroEncoding` `transient` so that `AvroEncoding` that is set in `AvroRowDataSerializationSchema` and `AvroRowDataDeSerializationSchema` can be serializable. As part of https://github.com/apache/flink/pull/23395, `AvroEncoding` was introduced which uses the `DescriptionElement` which is not `Serializable`. Due to which this fails when `AvroRowDataSerializationSchema` and `AvroRowDataDeSerializationSchema` gets serialized.

## Verifying this change

- Added unit test to test the serialization and deserialization of `AvroEncoding` enum.
- Also tested it with `KafkaTableITCase` in flink-kafka-connector locally.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (**yes** / no)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by venkata91** [comment]
cc @becketqin

**Comment by venkata91** [comment]
> ## CI report:
> * [8c396c5](https://github.com/apache/flink/commit/8c396c54eeda5bc8f8f656847a372b3421c25a7f) Azure: [FAILURE](https://dev.azure.com/apache-flink/98463496-1af2-4620-8eab-a2ecc1a2e6fe/_build/results?buildId=60262)
> 
> Bot commands

This test passes locally though 🤔 Let me try triggering it again if it is a transient issue.

**Comment by venkata91** [comment]
@flinkbot run azure

**Comment by venkata91** [comment]
> > ## CI report:
> > 
> > * [8c396c5](https://github.com/apache/flink/commit/8c396c54eeda5bc8f8f656847a372b3421c25a7f) Azure: [FAILURE](https://dev.azure.com/apache-flink/98463496-1af2-4620-8eab-a2ecc1a2e6fe/_build/results?buildId=60262)
> > 
> > Bot commands
> 
> This test passes locally though 🤔 Let me try triggering it again if it is a transient issue.

Looks like the issue is fixed as part of https://github.com/apache/flink/pull/24936. Rebased with `master` and this should resolve the flaky test issues. Gentle ping @becketqin @dawidwys

**Review by becketqin — APPROVED** [review]
LGTM. Will wait the CI test to finish before merging.

**Comment by becketqin** [comment]
Also ping @dawidwys in case you see any issues in making the `Description` serializable.

**Comment by venkata91** [comment]
@flinkbot run azure

**Comment by venkata91** [comment]
> Also ping @dawidwys in case you see any issues in making the `Description` serializable.

I pinged already above. @dawidwys do you see any issues with marking `Description` as well `Serializable`. Although we don't see any instances of `Description` that are required to be `Serializable` unlike the `DescriptionElement`. Thoughts?

**Comment by venkata91** [comment]
Another question is: should we implement `Serializable` only for `TextElement` and not extending `DescriptionElement` with `Serializable` as it will affect the implemented classes as well. This doesn't look to be a good practice but I see similar patterns in Flink though.

**Review by jectpro7 — APPROVED** [review]
Thanks for the PR, LGTM

**Comment by dawidwys** [comment]
I think it is not the best idea to make description java serializable. It doesn't feel right to me to make serializable something that never meant to be serializable. The only purpose of the `Description` is to generate documentation. Why don't you fix the serialization issue in place, in `AvroRowDataDeSerializationSchema` rather than opening up potentially many more problem? Can't you adjust the serialization of `AvroRowDataDeSerializationSchema`?

**Comment by becketqin** [comment]
@dawidwys The `AvroRowDataSerializationSchema` has always been serializable, until it got a field of `AvroEncoding` type which is a `DescribedEnum`.

> I think it is not the best idea to make description java serializable. It doesn't feel right to me to make serializable something that never meant to be serializable.

That was my first impression, too. But if you look at the specific case of `DescribedEnum`, this is not a description, but an option value. So it seems expected to be put into a `Configuration` or set as a field in a class that might be serializable. Therefore, intuitively this class should just be serializable like Java enums. Then making descriptions  serializable becomes reasonable.

> Why don't you fix the serialization issue in place, in AvroRowDataDeSerializationSchema rather than opening up potentially many more problems?

Can you elaborate on what might be potential problems of making descriptions serializable?
Arguably, one can always say, use a `String` instead of `DescribedEnum` if the class needs to be serializable. However, this is just non-intuitive and people can easily make mistakes and we will see such backwards incompatible change now and then.

**Comment by becketqin** [comment]
> I'd argue java serialsiation keeps no compatibility by itself. If you want to maintain compatibility you need versioning scheme for the serialised data.

The point is not about the compatibility between two Serializable versions. The case we are talking about is that people may add fields of `DescribedEnum` type into their serializable class without being aware that it is not serializable. Just like what we see here.

> That's a different story. You don't want to have Description serialisable, but you rather want DescribedEnum serialisable. That's a goal I think is reasonable. I guess you could e.g. serialize just the ordinal in DescribedEnum.

Do you mean serialize manually? Yes, there are different ways to fix this particular bug. Like I mentioned, one can use a `String` instead of `DescribedEnum` in their `Serializable` classes. But my main concern is about intuitiveness and future proof.
Just like this bug, by intuition, people will have the `InlineElement` field in their `DescribedEnum` classes. And people will just assume `DescribedEnum` is serializable and put it in their class without a second thought. Yes, we can always put notes to tell users to use `String` instead. But this is some additional overhead of understanding for the API and people may miss it.

So the question is not only about how do we fix this particular bug, but also how can we help users to avoid such bugs in the future.

That said, I do agree that intuitively descriptions need not be serializable, just like enums should be serializable. However, when the DescribedEnum is introduced, we kind of introduced this paradox. So it is more of a trade-off to me. And personally I don't see much material downside of making the description serializable. But I can be convinced if there are actually negative impacts by doing so.

> Nevertheless, just to throw out the most obvious reason that comes to my mind is why wasting space for useless data during runtime? (the description) Or another... you mentioned compatibility... what if we want to fix a typo in an enum description? Why do I need to consider serialisation compatibility in that case?

Making the description serializable does not automatically make them appear in all the serializable runtime classes, right? They will only be there if explicitly included, probably for a good reason.
Also, with the explicit SerializationVersionUID, the backwards compatibility should not be an issue.

**Comment by dawidwys** [comment]
Do as you please. You asked about my opinion and my opinion is that it is not a good idea.

**Comment by venkata91** [comment]
Looks like both @dawidwys and @becketqin agree that `DescribedEnum` (to not just solve for this case but also enable other users in the future to use `DescribedEnum` as a `Serializable`) should be `Serializable` but not `Description` itself. This makes sense to me as well. But then given `DescribedEnum` is an interface and the description (`InlineElement`) is not `Serializable` and therefore either `InlineElement` needs to be `Serializable`.

Few options that I could think of are:

1. Mark `InlineElement` alone `Serializable` instead of `DescriptionElement` given `DescribedEnum` only uses that for now. In the future if `DescribedEnum` is extended to `DescriptionElement` then it needs to be serializable as well.

2. Make `description` transient in `AvroEncoding` - this will solve the current issue, but then in the future some one else can step on that landmine when they `implement` `DescribedEnum`.

3. Another way is apply [SerializationProxy pattern](https://dzone.com/articles/serialization-proxy-pattern). The idea is as follows:

-  Introduce `SerializableDescribedEnum` that implements both `DescribedEnum` and `Serializable`.
- Implement `writeObject` and `readResolve` to serialize/deserialize the `InlineElement` and internally handle the serialization and deserialization of `InlineElement`.
- Also add to documentation in `DescribedEnum` to use `SerializableDescribedEnum` if a serializable version of `DescribedEnum` is required.

4. or the current solution itself.

Initially, I was also hesitant to mark both `Description` and `DescriptionElement` Serializable and it didn't feel right to me given it is done at the `interface` and not at the class either which gets leaked in to all the extending classes. Currently, that is fine but future evolution becomes difficult.

After going through all the above options, I feel the current solution is not that bad given the above options. If others have any other better suggestion, will definitely consider before merging this one.

Thanks for all the great discussions above!

**Comment by venkata91** [comment]
One more thing to add, with all of the above options, we don't really need to make `Description` `Serializable` yet.

**Comment by becketqin** [comment]
@dawidwys Thanks for the comments. I respect your opinion, although personally I still think making description serializable is not a bad idea as it seems.

And thanks @venkata91 for the summary. Given that we do not have a consensus on the fix, my suggestion is following:
1. Just fix this particular case in this patch, using option 2. This way at least we don't introduce tech debt.
2. If we identify another issue caused by the same root cause here, i.e. mistreating the `DescribedEnum` as a serializable, we apply the generic fix by making Description serializable.

Thanks.

**Comment by venkata91** [comment]
@flinkbot run azure

**Comment by venkata91** [comment]
`enums` are by default `Serializable` and the serialization and deserialization mechanism for `enum` is different (see [stackoverflow article](https://stackoverflow.com/questions/15521309/is-custom-enum-serializable-too) and [official Java documentation](https://docs.oracle.com/javase/1.5.0/docs/guide/serialization/spec/serial-arch.html#enum) for more details) from classes that are marked as `Serializable`.

For Flink versions < 1.18, the `ClosureCleaner` tries to serialize every nested field and also tries to serialize the `description` field which is not serializable. This causes the `NotSerializableException` mentioned in https://issues.apache.org/jira/browse/FLINK-35596. As part of Java 17 support, this is further fixed in https://issues.apache.org/jira/browse/FLINK-31919 and got released Flink-1.18

While https://issues.apache.org/jira/browse/FLINK-33058 got released only in Flink-1.19. Therefore, the `AvroEncoding` introduced won't cause any backwards incompatible issues with previous released versions.

Closing this PR as nothing to do here.

**Pull request closed without merging**
