### PR TITLE
[FLINK-6863] Remove batchdependency from streaming-examples

### PR DESCRIPTION
**Pull request by zentol**

### CODE REVIEW

**Comment by greghogan** [comment]
+1 and would it be good to add a note referencing the duplication in the JavaDoc of the two (now duplicated) `WordCountData`?

**Comment by zentol** [comment]
Do we really need the note? I don't think anyone would now add a dependency to the batch examples just to deduplicate the `WordCountData`. It would probably be ineffective as a deterrent as there are plenty of opportunities for deduplication between the batch and streaming examples.

**Comment by greghogan** [comment]
I was thinking more along the lines of a future refactoring allowing for a larger or unlimited corpus, to include for both batch and streaming, but the git annotations are sufficient to document the change if you don't think a note is necessary.

**Comment by zentol** [comment]
merging.

**Pull request closed without merging**
