### PR TITLE
[FLINK-2882] [core] Improve performance of string conversions

### PR DESCRIPTION
**Pull request by greghogan**
Memoize string representations of AbstractID.

Use lookup table for byte-to-hex conversion in StringUtils.

### CODE REVIEW

**Comment by tillrohrmann** [comment]
Thanks for your contribution @greghogan. Efficiency improvements look really good. The test failures seem to be unrelated.

Would be great if you could add a small test for the StringUtils method.

Apart from that, +1 for merging.

**Comment by StephanEwen** [comment]
Looks very good.

I am wondering if we can get rid of the toShortString method. What is that one actually used for?

**Comment by uce** [comment]
Yes, that's good to remove. I pointed that out as well when Greg opened the initial issue.

We can either do it as part of this PR or I can do it as a follow up.

**Comment by greghogan** [comment]
@tillrohrmann There exists StringUtilsTest with small test.

One of the TravisCI errors was a timeout and the other killed by the watchdog. Are timeouts being reworked to use RetryOnException or similar?

@uce It looks like toShortString is used for more than debugging and tests so I'd go for a separate PR.

**Comment by fhueske** [comment]
Looks good. 1+ for removing `toShortString` in a separate issue.
I'll merge this PR.

**Pull request closed without merging**
