### PR TITLE
[BP-1.11][FLINK-19790][json] Clear reused ObjectNode's content for map convert…

### PR DESCRIPTION
**Pull request by libenchao**
…er in RowDataToJsonConverters

## What is the purpose of the change

Fix JSON format serializing map type error.

## Brief change log

  - Clear reused ObjectNode's content for map converter.

## Verifying this change

This change added tests and can be verified as follows:

  - *JsonRowDataSerDeShemaTest.testSerDeMultiRows()*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by libenchao** [comment]
CC @wuchong

**Review by wuchong — APPROVED** [review]
LGTM.

@libenchao , if there is no conflicts when back porting the commits, you can merge it once build is passed without other committers approvement.

**Comment by libenchao** [comment]
@wuchong Sure, thanks for the review.
This issue has a little conflicts between master and 1.11 branch due to "[FLINK-19098][json][csv] Make RowData CSV and JSON converters public", that's why this pr is raised.

**Comment by libenchao** [comment]
closed via b50fc62e5b08363932815e0c68fbea3f08f0011f

**Pull request closed without merging**
