### PR TITLE
[FLINK-24932][state] Bump frocksdbjni to 6.20.3-ververica-2.0

### PR DESCRIPTION
**Pull request by fredia**
## What is the purpose of the change

Bump frocksdbjni to 6.20.3-ververica-2.0

## Brief change log
  - Bump frocksdbjni to 6.20.3-ververica-2.0
  - Update NOTICE file in flink-dist
 
## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

This change is already covered by existing RocksDB state backeend‘s tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Review by MartijnVisser — APPROVED** [review]
@fredia Thanks! I've verified that this allows me to continue further into building Flink on M1 :)  I could run a `mvn clean verify` up until it fails on a Netty error with Queryable State, which is also already occurring in master (will file a ticket shortly). I think this is good to merge. 

Normally I would be a little skeptical because we still have this big performance regression in the codebase, but since this is the existing FrocksDB fork with only additions to support M1 architectures, I think it should be fine

**Comment by fredia** [comment]
@MartijnVisser Thanks for the review and verification.

I compared the benchmark results based on the latest master(f6c7c30118ef26f98a7d422831fa8047f1fd9f98), below are the results. 
As we can see, the performance behaves the same as @Myasuka's [result](https://issues.apache.org/jira/browse/FLINK-24932?focusedCommentId=17569889&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17569889), the performance of version 2.0 is almost the same as that of version 1.0.

In addition to supporting M1, .6.20.3-ververica-2.0 also updates the [dependencies](https://github.com/ververica/frocksdb/pull/56) of zlib, adds `periodic_compaction_seconds` [option](https://github.com/ververica/frocksdb/pull/57) to RocksJava.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/leiyanfei/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/leiyanfei/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



Benchmark | 6.20.3-ververica-1.0 | 6.20.3-ververica-2.0 | ratio
-- | -- | -- | --
org.apache.flink.state.benchmark.ListStateBenchmark.listAdd | 389.803 | 386.465338 | -0.008562433
org.apache.flink.state.benchmark.ListStateBenchmark.listAddAll | 311.726 | 314.086747 | 0.007573148
org.apache.flink.state.benchmark.ListStateBenchmark.listAppend | 387.375 | 385.4015 | -0.005094547
org.apache.flink.state.benchmark.ListStateBenchmark.listGet | 152.5 | 154.95988 | 0.016130361
org.apache.flink.state.benchmark.ListStateBenchmark.listGetAndIterate | 155.356 | 155.927967 | 0.003681654
org.apache.flink.state.benchmark.ListStateBenchmark.listUpdate | 391.685 | 388.147242 | -0.009032151
org.apache.flink.state.benchmark.MapStateBenchmark.mapAdd | 320.924 | 314.778435 | -0.019149596
org.apache.flink.state.benchmark.MapStateBenchmark.mapContains | 66.928 | 67.744243 | 0.012195837
org.apache.flink.state.benchmark.MapStateBenchmark.mapEntries | 439.316 | 438.016991 | -0.00295689
org.apache.flink.state.benchmark.MapStateBenchmark.mapGet | 66.511 | 66.365644 | -0.002185443
org.apache.flink.state.benchmark.MapStateBenchmark.mapIsEmpty | 59.914 | 60.307518 | 0.006568048
org.apache.flink.state.benchmark.MapStateBenchmark.mapIterator | 441.623 | 439.512541 | -0.00477887
org.apache.flink.state.benchmark.MapStateBenchmark.mapKeys | 439.221 | 440.065508 | 0.00192274
org.apache.flink.state.benchmark.MapStateBenchmark.mapPutAll | 85.741 | 85.65495 | -0.001003604
org.apache.flink.state.benchmark.MapStateBenchmark.mapRemove | 335.227 | 358.395208 | 0.069111999
org.apache.flink.state.benchmark.MapStateBenchmark.mapUpdate | 310.086 | 339.343382 | 0.094352476
org.apache.flink.state.benchmark.MapStateBenchmark.mapValues | 443.319 | 446.092917 | 0.006257158
org.apache.flink.state.benchmark.ValueStateBenchmark.valueAdd | 322.669 | 306.841597 | -0.049051514
org.apache.flink.state.benchmark.ValueStateBenchmark.valueGet | 437.556 | 443.970351 | 0.014659497
org.apache.flink.state.benchmark.ValueStateBenchmark.valueUpdate | 331.987 | 336.718447 | 0.014251904
org.apache.flink.state.benchmark.RocksdbStateBackendRescalingBenchmarkExecutor.rescaleRocksDB | 18845.28 | 18719.78056 | -0.006659463
org.apache.flink.state.benchmark.RocksdbStateBackendRescalingBenchmarkExecutor.rescaleRocksDB | 1746.154 | 1848.152231 | 0.058413079



</body>

</html>

**Comment by MartijnVisser** [comment]
@fredia Looks good to me to merge :)

**Review by Myasuka — APPROVED** [review]
LGTM. 
BTW, the `6.20.3-ververica-2.0` version also includes [optimization](https://github.com/ververica/frocksdb/commit/698c9ca2c419c72145a2e6f5282a7860225b27a0) of avoiding `ToString` in TTL related code.

**Pull request merged**
