### PR TITLE
[FLINK-25794][sql-runtime] Clean cache after memory segments in it after they are released to MemoryManager

### PR DESCRIPTION
**Pull request by FangYongs**
## What is the purpose of the change

This pr aims to clean cache in `LazyMemorySegmentPool` after memory segments in it are released to `MemoryManager`

## Verifying this change
This change added tests and can be verified as follows:
  - *Added test `ResettableExternalBufferTest.testSegmentPoolCleanCache` that validates the cache is cleared in  `LazyMemorySegmentPool.cleanCache`

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no) no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no) no
  - The serializers: (yes / no / don't know) no
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know) no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know) no
  - The S3 file system connector: (yes / no / don't know) no

## Documentation

  - Does this pull request introduce a new feature? (yes / no) no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by zjureel** [comment]
Hello @KarmaGYZ @JingsongLi , could you help to review this issue when you're free?

**Comment by JingsongLi** [comment]
Hi @zjureel I replied you in JIRA.

**Comment by zjureel** [comment]
Thanks @JingsongLi , I think I miss the operations in `MemoryManager` :(
And another issue is in `BinaryHashTableTest.testBinaryHashBucketAreaNotEnoughMem`, there's no `table.free` after `table.close`, I think it should be and it causes memory leaks in my cache memory manager. What do you think?

**Comment by zjureel** [comment]
> 

No, the 'area.freeMemory' will call `LazyMemorySegmentPool.returnPage` and return the allocated `MemorySegment` to `LazyMemorySegmentPool.cachePages` only and won't free them to `MemoryManager`

**Pull request closed without merging**
