### PR TITLE
[FLINK-2928][web-dashboard] Fix confusing job status visualization in job overview.

### PR DESCRIPTION
**Pull request by sachingoel0101**

### CODE REVIEW

**Comment by sachingoel0101** [comment]
screenshot 98

**Comment by StephanEwen** [comment]
Nice, I like the label.

Somehow the JobID is missing now. Did you remove that, or was it removed earlier already?

**Comment by sachingoel0101** [comment]
The presence of job id was leading to the cancel button disappearing sometimes due to lack of space which is something very important. I considered a two row approach but that looked ugly.

**Comment by StephanEwen** [comment]
I think solving a layout problem by removing another important UI element is not the way to go.

Does it nor work to let the elements that do not fit in the one row automatically float left/down into a second row?

**Comment by sachingoel0101** [comment]
I'm not very sure about this. Displaying two rows doesn't look good at all. Maybe @iampeter has a better suggestion here.

**Comment by StephanEwen** [comment]
Layout is tricky. But the JobID is a very important field (for example to copy for CLI commands) and needs to stay.

**Comment by sachingoel0101** [comment]
Makes sense. Lemme figure something out here, and I will post an update in a day or two.

**Comment by iampeter** [comment]
Maybe a top right action button, triggering a Bootstrap dropdown with the Cancel action?

action

**Comment by StephanEwen** [comment]
I like that solution, @iampeter

**Comment by sachingoel0101** [comment]
That sounds great. @iampeter thanks for the suggestion. :)
I will see if I can update the PR today.

**Comment by StephanEwen** [comment]
@sachingoel0101 This still misses the Job ID

**Comment by sachingoel0101** [comment]
Hi @StephanEwen, apologies for the delayed response. 
Unfortunately, I haven't been able to work on Flink recently as I've just moved abroad. I've also just joined Samsung, so I will have to check whether I can continue contributing. Since this isn't a blocker issue, I will let you know in a few days if I'll be able to continue working on it.

**Comment by mxm** [comment]
Congrats @sachingoel0101. I hope you stick with us :) Do you think you'll be able to finish the PR?

**Pull request closed without merging**
