### PR TITLE
[FLINK-18256][orc] Exclude ORC's Hadoop dependency and pull in provided vanilla hadoop in flink-orc

### PR DESCRIPTION
**Pull request by wangyang0918**
## What is the purpose of the change

The hadoop-common and hadoop-hdfs have been bundled into the flink-orc_2.11-1.11-SNAPSHOT-jar-with-dependencies.jar. Since we suggest our users to put this jar into lib directory or add dependency in their pom to build fat jar, it might be incorrect to have hadoop here. Flink now is not hadoop free, we have some specific hadoop version classes in the released jars.

 

> How to fix?

Let flink-orc depends on hadoop-common and hadoop-hdfs directly and make them provided.

## Brief change log

* Exclude ORC's Hadoop dependency and pull in provided vanilla hadoop.

## Verifying this change

* `mvn clean package -DskipTests` and using the following command to check there is no hadoop class bundled in
```
jar -tf target/flink-orc_2.11-1.11-SNAPSHOT-jar-with-dependencies.jar
```

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**yes** / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by wangyang0918** [comment]
cc @JingsongLi Could you please help with review?

**Comment by rmetzger** [comment]
Are the `org/apache/hadoop/hive` classes expected to be in there?

**Comment by rmetzger** [comment]
I also found this along the way: https://issues.apache.org/jira/browse/FLINK-18261

**Comment by JingsongLi** [comment]
> Are the `org/apache/hadoop/hive` classes expected to be in there?

Yes, orc-core depends on hive classes.

**Comment by wangyang0918** [comment]
Rebase the latest master to fix the azure pipeline failure.

**Comment by rmetzger** [comment]
The latest CI failure is reported here:  https://issues.apache.org/jira/browse/FLINK-18262

**Comment by rmetzger** [comment]
Merging ...

**Pull request merged**
