### PR TITLE
[FLINK-12197] [Formats] Avro row deser for Confluent binary format

### PR DESCRIPTION
**Pull request by EugeneYushin**
## What is the purpose of the change

Currently, the following avro deserializators are available:

- Core avro binary layout for both Specific/Generic and Row
- Confluent Specific/Generic record layout

The intention of this task is to fill the gap and provide Confluent avro deser for Row type.
This will allow to harness Table API to pipelines that work with avro and Confluent schema registry.

## Brief change log

  - Add ConfluentRegistryAvroRowDeserializationSchema
  - Extract utilities from AvroRowDeserializationSchema
  - Use the same approach as for AvroRowDeserializationSchema, extending AbstractDeserializationSchema instead of AvroDeserializationSchema cause' the latter works with Generic/SpecificRecord abstractions from avro libs 

## Verifying this change

This change added tests and can be verified running JUnit tests for `flink-avro` and `flink-avro-confluent-registry` modules.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): yes
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: yes (deserializers, if this matters)
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by EugeneYushin** [comment]
@dawidwys @twalthr 
guys, can you please take a look?

**Comment by dawidwys** [comment]
Hi @EugeneYushin I have not read the whole PR, but I have one general concern regarding the architecture of this change. Why do we need a whole duplicated `DeserializationSchema`? Can't we just wrap the original `AvroDeserializationSchema` and just introduce a wrapper that converts the output of the schema to `Row`?

@flinkbot approve description
@flinkbot diapprove consensus

**Comment by EugeneYushin** [comment]
Hi @dawidwys. Thanks for a review. Please find my answers below.
>  Why do we need a whole duplicated `DeserializationSchema`? Can't we just wrap the original `AvroDeserializationSchema` and just introduce a wrapper that converts the output of the schema to `Row`?

I've covered this in feature description briefly: 
> Use the same approach as for AvroRowDeserializationSchema, extending AbstractDeserializationSchema instead of AvroDeserializationSchema cause' the latter works with Generic/SpecificRecord abstractions from avro libs

Here's a more detailed explanation.
`AvroDeserializationSchema` doesn't provide any methods which can be re-used in case of `Row` passed as an input class:
- [constructor](https://github.com/apache/flink/blob/master/flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroDeserializationSchema.java#L98) is intended to work with avro SpecificRecord/GenericRecord classes
```
* @param recordClazz class to which deserialize. Should be one of:
*                    {@link org.apache.avro.specific.SpecificRecord},
*                    {@link org.apache.avro.generic.GenericRecord}.
```
- [deserialize()](https://github.com/apache/flink/blob/master/flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroDeserializationSchema.java#L126) method can't be used as a wrapper cause':
-- this method is parametrized with return type, so parents' `AvroDeserializationSchema.deserialize` should return Row, while it's intended to return avro SpecificRecord/GenericRecord
-- it sets reader schema only
-- confluent avro binary format includes schema id in record, which should be used during decoding to set writer schema as well
- [getProducedType()](https://github.com/apache/flink/blob/master/flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroDeserializationSchema.java#L165) deals only with avro SpecificRecord/GenericRecord classes
- the same concerns I have if to choose `RegistryAvroDeserializationSchema` instead of `AvroDeserializationSchema` for extending

Please, let me know if this makes sense to you.

**Comment by EugeneYushin** [comment]
@dawidwys thanks for the suggestion, I've added required changes.
Can you please take a look one more time?

**Comment by EugeneYushin** [comment]
@dawidwys just a kind reminder to check if you had a chance to look into updated version

**Comment by EugeneYushin** [comment]
@dawidwys can you please ping an another person who can help reviewing this PR in case you have no capacity?

**Comment by dawidwys** [comment]
It was impemented for new FLIP-95 Table sources with #12919 . Therefore I am closing this one as it is subsumed.

**Pull request closed without merging**
