### PR TITLE
[FLINK-4510] [checkpoint] Always create CheckpointCoordinator

### PR DESCRIPTION
**Pull request by wuchong**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

This pull request always create checkpoint coordinator even if checkpointing interval is not configured. 

I use a flag to indicate disabled periodic checkpoint,  Instead of using an interval of 0. Because the interval is checked everywhere, too scared to change it...

### CODE REVIEW

**Comment by StephanEwen** [comment]
Thanks for looking into this.

I wonder if we can do this simpler, without changes to the CheckpointCoordinator.
The only thing that really needs to change is that without periodic checkpoints, the `startCheckpointScheduler()` method is not called, which means that the JobStatusListener that "CheckpointActivatorDeactivator" should not be created and started.

**Comment by wuchong** [comment]
Make sense. I will update this PR.

**Comment by wuchong** [comment]
Hi @StephanEwen , I have updated this PR according to your suggestion. In addition, I use an interval of `Long.MAX_VALUE` for disabled periodic checkpoint. In this way, we will not break interval sanity check and no changes will be attached to `CheckpointCoordinator` and `JobSnapshottingSettings`.

**Comment by StephanEwen** [comment]
Will have a look at this again soon.

**Comment by StefanRRichter** [comment]
Thanks for the nice contribution.

I see one minor detail that could cause problems. Even if we do not register the `CheckpointCoordinator` as `JobStatusListener`, it might still be possible that `triggerCheckpoint(long timestamp, CheckpointProperties props)` gets called. In this case it can happen that a periodic trigger is registered. You could introduce another check on the interval to make sure that no periodic trigger can be registered when the CheckpointCoordinator is disabled.

Besides that, the changes look good to me.

**Comment by wuchong** [comment]
Hi @StefanRRichter  , I fixed the conflicts, and add interval check in `triggerCheckpoint`.  Could you have a look again ?

**Comment by StefanRRichter** [comment]
Looks good to me now.

**Comment by uce** [comment]
Thanks for the contribution. I'm going to merge this with slight modifications. We don't need the introduced checks with the current master as there is a check whether periodic checkpoints are activated.

**Pull request closed without merging**
