### PR TITLE
[FLINK-6075] - Support Limit/Top(Sort) for Stream SQL

### PR DESCRIPTION
**Pull request by rtudoran**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x ] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by rtudoran** [comment]
@fhueske 
I have implemented meanwhile also the support for offset and fetch for both rowtime and proctime. This PR includes all the modifications and reviews you made for #3889.
You can either go ahead first with that one and chekc if the basis is ok and merge that - and then we move to this one, or we can consider this directly. This PR will close the JIRA

**Comment by rtudoran** [comment]
@shijinkui @hongyuhong @stefanobortoli 
I add you to the issue to track the progress

**Comment by fhueske** [comment]
Thanks for the update @rtudoran. 
I'm traveling for another week before I return in the office. I hope I'll find time to have a look at #3889 in the next days. I think we should try to get that in first and later rebase this PR once the first part has been merged.

Thank you, Fabian

**Comment by rtudoran** [comment]
@fhueske - Fine for me! I just wanted to finish this as well :)

**Comment by rtudoran** [comment]
@fhueske I will re-factor these contributions (hopefully by the end of the week) based on the things that are already merged from order by. I will ping you soon

**Comment by rtudoran** [comment]
I have updated these contributions against the master branch and based on the latest modifications after the merge of the basis for orderby. I opened a new PR for this #4263.
I will close this one as it is not relevant anymore

**Pull request closed without merging**
