### PR TITLE
[FLINK-3654] Disable Write-Ahead-Log in RocksDB State

### PR DESCRIPTION
**Pull request by aljoscha**

### CODE REVIEW

**Comment by uce** [comment]
Should we add this for `1.0.2` (or `1.0.1` if the RC gets cancelled)?

**Comment by aljoscha** [comment]
Can do, yes. But we shouldn't block, as you said.

**Comment by aljoscha** [comment]
I'm seeing this failure on Travis: https://travis-ci.org/aljoscha/flink/jobs/120638971

Could be a bug introduced by the change. I'm investigating...

**Comment by uce** [comment]
Would you mind triggering a few builds over night?

**Comment by aljoscha** [comment]
done :smile:

**Comment by aljoscha** [comment]
I think we have a winner now. I changed the backup options to not back up the WAL. This seems to have been the problem. Only logical since there is no WAL anymore...

Before, 2 out of 5 travis runs (i.e. 5*5) would have errors. Now all 5 runs that I started were successful.

**Comment by aljoscha** [comment]
Manually merged

**Pull request closed without merging**
