### PR TITLE
[FLINK-34085][config] Remove deprecated string configuration keys

### PR DESCRIPTION
**Pull request by Sxnan**
## What is the purpose of the change

Remove deprecated string configuration keys.

## Brief change log

- Remove deprecated string configuration keys

## Verifying this change

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Review by 1996fanrui — APPROVED** [review]
Thanks @Sxnan for the contribution!

LGTM, feel free to merge it if you think this PR is ready.

**Comment by Sxnan** [comment]
@1996fanrui Thanks for the review!

**Comment by XComp** [comment]
This PR causes a constant test failure in `master`: [YarnFileStageTestS3ITCase](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=61979&view=logs&j=fc5181b0-e452-5c8f-68de-1097947f6483&t=995c650b-6573-581c-9ce6-7ad4cc038461&l=28207) I guess it's because S3 is only enabled in `master`

This wasn't discovered through CI before merging the PR because the corresponding test [is disabled](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=61954&view=logs&j=fc5181b0-e452-5c8f-68de-1097947f6483&t=995c650b-6573-581c-9ce6-7ad4cc038461&l=28206).

**Comment by Sxnan** [comment]
@XComp Thanks for letting me know. This PR indeed breaks the `YarnFileStageTestS3ITCase` and I am looking into it.

**Pull request merged**
