### PR TITLE
[FLINK-11288][build] Add flink-ml-uber module

### PR DESCRIPTION
**Pull request by zentol**
## What is the purpose of the change

This PR adds a `flink-ml-uber` module for packaging a fat `flink-ml` jar with proper licensing.

## Brief change log

* add new module packaging a fat `flink-ml` jar with appropriate NOTICE file
* update flink-dist dependencies
* update flink-dist assembly
* update NOTICE-binary

## Verifying this change

Manually inspect the jars, compare contents with previous `flink-ml` `jar-with-dependencies`.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Could the `flink-ml` module be the uber module itself? So that we don't need another module?

I think we need to kick off a discussion about what out ML library should look in the future, until then I would suggest to do the simplest thing for the `flink-ml` module.

**Comment by zentol** [comment]
@StephanEwen Do you mean to always have flink-ml be a fat-jar and only deploy that one? It would certainly _work_. I opted for a new module since it is less likely to impact the packaging of user jars.
`flink-ml` sees no development at the moment, making it unlikely that there are maintainability repercussions from adding another module.

**Comment by zentol** [comment]
@StephanEwen I also recall a discussion with @tillrohrmann about this very idea; IIRC `flink-ml` allows users to replace certain dependencies (I guess like using a different implementation of an algorithm?), which wouldn't be possible if we only release a fat jar.

**Comment by zentol** [comment]
@StephanEwen ping

**Pull request merged**
