### PR TITLE
[FLINK-35999] Migrate from fmpp-maven-plugin to drill-fmpp-maven-plugin

### PR DESCRIPTION
**Pull request by r-sidd**
## What is the purpose of the change
This PR will remove the log4j dependency from the **fmpp-maven-plugin**

## Brief change log
In the maven package - flink-sql-parser, the fmpp-maven-plugin has a dependency of xbean-reflect, which in-turn has a dependency of log4j jar 1.12. We can exclude this dependency from xbean-reflect. Attaching details below:

https://mvnrepository.com/artifact/org.apache.xbean/xbean-reflect/3.4

https://github.com/apache/flink/blob/master/flink-table/flink-sql-parser/pom.xml

## Documentation

  - Does this pull request introduce a new feature? NO

### CODE REVIEW

**Comment by snuyanzin** [comment]
Thanks for the contribution

I would suggest rather move to drill-fmpp-maven-plugin https://github.com/apache/drill/blob/master/tools/fmpp/pom.xml which is based fmpp-maven-plugin and already excludes some dependencies including log4j

**Comment by r-sidd** [comment]
> Thanks for the contribution
> 
> I would suggest rather move to drill-fmpp-maven-plugin https://github.com/apache/drill/blob/master/tools/fmpp/pom.xml which is based fmpp-maven-plugin and already excludes some dependencies including log4j
> 
> Also Calcite depended on this plugin as well (before it was migrated to gradle)

Okay sure, makes sense, will migrate to drill-fmpp-maven-plugin :)

**Comment by r-sidd** [comment]
@flinkbot run azure

**Comment by r-sidd** [comment]
Hey @snuyanzin thanks for the suggestion, I've made the necessary changes and ran the tests in local :)

**Review by snuyanzin — APPROVED** [review]

**Pull request merged**
