### PR TITLE
[FLINK-2304] Add named attribute access to Storm compatibility layer

### PR DESCRIPTION
**Pull request by mjsax**
- added support for named attribute access
  - extenden FlinkTopologyBuilder to handle declared output schemas
  - adapted JUnit test
  - added new examples and ITCases
  - updated README

### CODE REVIEW

**Comment by rmetzger** [comment]
Is there a JIRA for this change?
Are there any plans for adding documentation for the storm compatibility layer?

**Comment by mjsax** [comment]
There is no JIRA, but I can of course open one (it the policy to open a JIRA for each new feature?). I can also add documentation. But this should be done in a different PR (JIRA for this, too?)

**Comment by rmetzger** [comment]
Yes, there is a policy ;) http://flink.apache.org/coding-guidelines.html
Would be great if you could also document the storm-compat (in a different JIRA+PR)

**Comment by mjsax** [comment]
Close and re-open in new branch to link to JIRA.

**Pull request closed without merging**
