### PR TITLE
[FLINK-7251] Merge the flink-java8 project into corresponding flink project

### PR DESCRIPTION
**Pull request by zjureel**
## What is the purpose of the change

Merge the codes in flink-java8 project into corresponding flink project

## Brief change log
  - *Merge examples into flink-examples project*
  - *Merge runtime test into flink-runtime project*
  - *Merge test case into flink-tests project*
  - *Remove flink-java8 project*

## Verifying this change

*(Please pick either of the following options)*

This changes are examples and test cases without any test coverage

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by zentol** [comment]
This would be easier to review (and for git to keep track of) if the individual commits would actually move a file, and not just copy them.

**Comment by zjureel** [comment]
@zentol Thank you for your suggestion, it sounds good to me and I have fixed them, thanks

**Comment by zentol** [comment]
There's a compilation failure in flink-tests:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project flink-tests_2.11: Compilation failure: Compilation failure:
[ERROR] /home/travis/build/apache/flink/flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/StateBackendITCase.java:[67]
[ERROR] .map(new RichMapFunction<Tuple2<String, Integer>, String>() {
[ERROR] ^^^
[ERROR] The method map(MapFunction<Tuple2<String,Object>,R>) in the type DataStream<Tuple2<String,Object>> is not applicable for the arguments (new RichMapFunction<Tuple2<String,Integer>,String>(){})
[ERROR] /home/travis/build/apache/flink/flink-tests/src/test/java/org/apache/flink/test/example/client/JobRetrievalITCase.java:[99]
[ERROR] final ActorSystem actorSystem = actorSystemSeq.last();
[ERROR] ^^^^
[ERROR] The method last() is ambiguous for the type Seq<ActorSystem>
```

**Comment by zentol** [comment]
The StateBackendITCase can be resolved by bumping the tycho compiler version to 1.0.0, but the scala one remains.

**Comment by zentol** [comment]
Could you check what happens when you remove the tycho-compiler completely?

**Comment by zjureel** [comment]
The `JobRetrievalITCase` is ok when I remove the tycho-compiler completely, I think it may be a bug of the tycho-compiler :(

**Comment by zjureel** [comment]
Maybe it's better to move *ITCase to `Flink-java` project and rename them to *Test, I find it will be alright, what do you think? @zentol

**Comment by zentol** [comment]
Are you talking about things like `FlatMapITCase`? I would suggest to integrate these into the existing ITCase in `flink-tests`.

**Comment by zjureel** [comment]
1. For the `StateBackendITCase`, it can be resolved by bumping the tycho compiler version to 1.0.0, but when I try to use tycho compiler version 1.0.0 in `flink-java`, it will cause lambda exception for `LambdaExtractionTest`. I think it's better to stay in the same version of tycho compiler in different flink project, so I try to modify the code of StateBackendITCase to resolve the problem directly.

2. For the `JobRetrievalITCase`, I try every version of tycho compiler, the problem always exists. I think tycho compiler may be incompatible with `Seq.last()` method. I try to use another method in `Seq` to get the last element in `JobRetrievalITCase`, and it would be ok

@zentol What do you think? Thanks :)

**Comment by zentol** [comment]
We will have to revert every change that requires the tycho plugin to be moved into any other module. Using a different for these modules may have performance impacts and possibly subtle bugs.

Sorry that i didn't notice it earlier.

**Comment by zjureel** [comment]
@zentol Thank you for your reply, and I agree with you that the risk will be a little high for this PR. I'd like to close this PR if there's no better solution, thanks

**Pull request closed without merging**
