### PR TITLE
[FLINK-10603] Reduce kafka test duration

### PR DESCRIPTION
**Pull request by yanghua**
## What is the purpose of the change

*This pull request reduces kafka test duration*

## Brief change log

  - *Reduce kafka test duration*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by zentol** [comment]
Changed have no effect on the test duration:
```04:24:23.681 [INFO] flink-connector-kafka .............................. SUCCESS [10:04 min]```

**Comment by yanghua** [comment]
Hi @zentol It's strange, why I can not find the modern kafka connector's test duration report, however I found the other connectors test report. Comparing with 0.11, the time duration looks normal?

```
04:30:26.649 [INFO] flink-connector-kafka-base ......................... SUCCESS [ 10.444 s]
04:30:26.649 [INFO] flink-connector-kafka-0.8 .......................... SUCCESS [03:08 min]
04:30:26.649 [INFO] flink-connector-kafka-0.9 .......................... SUCCESS [03:48 min]
04:30:26.649 [INFO] flink-connector-kafka-0.10 ......................... SUCCESS [03:18 min]
04:30:26.649 [INFO] flink-connector-kafka-0.11 ......................... SUCCESS [10:12 min]
```

**Comment by zentol** [comment]
the modern connector is run in the `misc` profile since it wasn't properly added to the `connector` profile in `stage.sh`. This coincidentally was a "good" thing since it would've exceeded the max build time.

It looks normal _compared_ to `0.11`, but that one already is a disgrace in terms of test duration.

**Comment by yanghua** [comment]
OK, there may be more than one potential reason. Since 0.11, more tests have been added to the connector (for example, for Producer transactions); in addition, Kafka may have adjusted the default timeout of the relevant API (just like this example), and there may be problems with the test logic itself. I will try to find the problem, but it may take some time.

**Comment by yanghua** [comment]
When I excluded `FlinkKafkaProducer011StateSerializerTest`, `Kafka011ProducerAtLeastOnceITCase` and `Kafka011ProducerExactlyOnceITCase`, the result is : 

```
04:57:10.414 [INFO] flink-connector-kafka-0.8 .......................... SUCCESS [02:29 min]
04:57:10.414 [INFO] flink-connector-kafka-0.9 .......................... SUCCESS [03:09 min]
04:57:10.414 [INFO] flink-connector-kafka-0.10 ......................... SUCCESS [03:10 min]
04:57:10.414 [INFO] flink-connector-kafka-0.11 ......................... SUCCESS [07:33 min]
```

**Comment by yanghua** [comment]
excluded all but `FlinkKafkaProducer011ITCase`, test result : 

```
15:41:23.815 [INFO] flink-connector-kafka-0.8 .......................... SUCCESS [02:38 min]
15:41:23.815 [INFO] flink-connector-kafka-0.9 .......................... SUCCESS [02:52 min]
15:41:23.815 [INFO] flink-connector-kafka-0.10 ......................... SUCCESS [03:13 min]
15:41:23.815 [INFO] flink-connector-kafka-0.11 ......................... SUCCESS [04:30 min]
```

What do you think about the time duration, does it look normal? @pnowojski

**Comment by zentol** [comment]
While randomly disabling tests naturally decreases the test duration this isn't a viable option. Instead we should be looking at decreasing the duration that these tests require.
Since we're still searching for the solution I will close this PR; please move further discussion into the JIRA.

**Comment by yanghua** [comment]
@zentol I think you misunderstood what I meant. I just used the exclusion method to locate which test cases (compared to 0.9) took up too long test time. Because each kafka connector has different test cases, we need to find out if the different test cases cost unreasonable test time. Ultimately, these excluded test cases will definitely be restored. This of course will not be my solution to reduce the test time.

Because the 0.11 version is mainly implemented by @pnowojski , and more producer transaction tests have been added since this version, I hope that he will evaluate it and whether it is reasonable to spend these time.

**Comment by zentol** [comment]
If you want to know how long a particular stack trace takes you can just check the travis logs:
```
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 255.96 sec - in org.apache.flink.streaming.connectors.kafka.FlinkKafkaProducerITCase
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 38.99 sec - in org.apache.flink.streaming.connectors.kafka.FlinkKafkaInternalProducerITCase
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 117.625 sec - in org.apache.flink.streaming.connectors.kafka.KafkaProducerAtLeastOnceITCase
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 83.659 sec - in org.apache.flink.streaming.connectors.kafka.KafkaProducerExactlyOnceITCase
Tests run: 21, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 152.635 sec - in org.apache.flink.streaming.connectors.kafka.KafkaITCase
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.268 sec - in org.apache.flink.streaming.connectors.kafka.FlinkKafkaProducerStateSerializerTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.055 sec - in org.apache.flink.streaming.connectors.kafka.KafkaTableSourceSinkFactoryTest
```

**Comment by yanghua** [comment]
OK, but it seems that I need Travis to run the test and do some validation. I can't run all of these tests locally because it throws a lot of exceptions. So, can we open this PR again? You can ignore its changes until I have reached a conclusion.

**Comment by zentol** [comment]
IMO a PR is not the right place for such a discussion.

**Comment by yanghua** [comment]
If I just made some changes and verified it with Travis, I wouldn't move any subsequent discussions to JIRA. What do you think?

**Comment by zentol** [comment]
You shouldn't be using the Apache Travis for discovering solutions. You can test things in your own travis instance https://travis-ci.org/yanghua/flink and refer to them for further discussions.

**Pull request closed without merging**
