### PR TITLE
[FLINK-11030] Make SpecificData of AvroDeserializationScheme configurable

### PR DESCRIPTION
**Pull request by aljoscha**

### CODE REVIEW

**Comment by dawidwys** [comment]
I think this is a valid approach on the Kafka serialization schema side. Unfortunately the registered factory is not propagated to `AvroSerializer` via `getProducedType`, what will result in a failure if it is used for non-chained operators.

I think if we want to fix it properly and completely we should do a similar thing for `AvroTypeInfo`/`GenericRecordAvroTypeInfo`/`AvroSerializer`.

A workaround that I am aware of for this issue without any changes on flink side would be to use `conversions` field for SpecificData, but unfortunately it is broken for avro <= 1.9, if logical types are used for unions, arrays etc. (https://issues.apache.org/jira/browse/AVRO-2065, https://issues.apache.org/jira/browse/AVRO-1891).

**Comment by aljoscha** [comment]
Closing this for now since this requires more thinking.

**Comment by wittyameta** [comment]
Is there any workaround for this?

**Comment by tarunrathor-pro** [comment]
What is the solution/workaround for this problem of not supporting logicalTypes in avro for ConfluentRegistryAvroDeserializationSchema. We are blocked on this. Many enterprises adopt Confluent Platform and use Schema registry integration. This is a major limitation in using Flink with Confluent Platform

**Comment by sunnylohani** [comment]
@dawidwys 
I am using avro 1.10.0 with Flink Kafka source connector. Can you please explain some details on the workaround you have spoken above ?
I have _java.time.LocalDateTime_ field in my POJO generated by avro-maven plugin. Below is the plugin:

```
<plugin>
        <groupId>org.apache.avro</groupId>
        <artifactId>avro-maven-plugin</artifactId>
        <version>${avro.version}</version>
        <configuration>
          <stringType>String</stringType>
          <enableDecimalLogicalType>true</enableDecimalLogicalType>
          <customConversions>
            org.apache.avro.data.TimeConversions$LocalTimestampMicrosConversion
          </customConversions>
        </configuration>
        <executions>
          <execution>
            <phase>generate-sources</phase>
            <goals>
              <goal>schema</goal>
            </goals>
            <configuration>
              <sourceDirectory>${project.basedir}/src/main/resources/schema</sourceDirectory>
              <outputDirectory>${project.build.directory}/generated-sources/avro</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

But I get below exception when my Flink job receives an avro encoded event from kafka:

_...
Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to java.time.LocalDateTime
        ...
	at org.apache.avro.generic.GenericData.setField(GenericData.java:819)
	at org.apache.avro.specific.SpecificDatumReader.readField(SpecificDatumReader.java:139)
	at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:247)
	at org.apache.avro.specific.SpecificDatumReader.readRecord(SpecificDatumReader.java:123)
	at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:179)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:160)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:153)
	at org.apache.flink.formats.avro.RegistryAvroDeserializationSchema.deserialize(RegistryAvroDeserializationSchema.java:74)_

**Pull request closed without merging**
