### PR TITLE
[FLINK-2152] [bugfix] Used a concurrent list in the open method

### PR DESCRIPTION
**Pull request by andralungu**
This PR fixes the concurrency issue raised by the elements in the broadcast set. I instantiated the list to be a CopyOnWriteArrayList. Hope that fixes the issue!

### CODE REVIEW

**Comment by rmetzger** [comment]
Are you sure this is a fix for FLINK-2512 ?
I don't see how this change is fixing any issue.

**Comment by uce** [comment]
I don't get it. You are not instantiating a CopyOnWriteArrayList here, but just cast the list returned by the runtime context. Either this works and the returned list is already a CopyOnWriteArrayList, in which case this does nothing. Or it's not a CopyOnWriteArrayList and the cast fails at runtime.

What are you trying to fix here? In general, fixes should come with a test to verify them as well. Otherwise, it's too easy to loose fixes and very hard to understand what is being fixed when reviewing.

**Comment by andralungu** [comment]
excerpt from the JIRA 
"This can be fixed by wrapping a concurrent list around the counts variable
e.g. CopyOnWriteArrayList from java.util.concurrrent (in the open method)"

Stood there open for a while so I thought I fixed it. Don't really know what test should be written. The use case is the same, the environment just goes from local to cluster.

**Comment by uce** [comment]
Thanks! I think you are referencing a wrong issue. Can you double check? The new commit looks better. :)

**Comment by mjsax** [comment]
I agree with @rmetzger and @uce https://issues.apache.org/jira/browse/FLINK-2512 is already closed via #1009

**Comment by andralungu** [comment]
Yes, I am sorry about that. It was a propagated typo. Problem solved!

**Comment by uce** [comment]
With the correct issue it makes sense :) Do you know why the concurrent mod exception is occurring in the first place btw?

**Comment by andralungu** [comment]
I guess because more parallel instances are trying to access that broadcast variable.

**Comment by StephanEwen** [comment]
I don't understand this issue.

Is any user code modifying this list? Concurrent read access should be well possible with any regular list.
The system never modifies the list after it has been created once.

**Comment by andralungu** [comment]
Yup that's what I thought as well. 
However, I only tested `zipWithUniqueId` on a cluster. 
A student came to me and said that `zipWithIndex` did not work in a cluster environment (I believed him) and claimed some days after via the Jira issue that this was the fix that worked for him. 

That's all the input I have.

**Comment by StephanEwen** [comment]
Okay, looking at the "zipWithIndex" code, here is what really is the problem:

Each function actually modifies the list, by sorting it. The here proposes solution solves it, by making sure everyone has its own copy of the list. That, btw, would have worked with any ArrayList as well. CopyOnWriteList seems a bit overkill.

A nicer way to solve this is IMHO to use a broadcast variable initializer, which would guarantee that the list is sorted once (by the first one that accesses it) and then everyone shares the same sorted list.
  - Less memory consumption (not super critical, as we are talking about small lists)
  - Less work, since only one sort happens per TaskManager, rather than one sort per task.

**Comment by andralungu** [comment]
so you mean something like

`List<Tuple2<Integer, Long>> offsets = getRuntimeContext().getBroadcastVariableWithInitializer("counts", new ArrayList());`?

**Comment by StephanEwen** [comment]
Is anything happening here, or can we close this?

**Comment by andralungu** [comment]
I asked whether I should change the list initialization. The current commit fixes the bug reported on the Jira issue, but I understood that you'd like it to be different. 

I can also close it, but then we should mark the Jira issue as resolved or say it's not a bug or whatever. I saw it reopened and wanted to fix it...

**Comment by StephanEwen** [comment]
I think if we fix it, let's fix it the best way we can.
We can use broadcast variable initializers (I gave a pointer to that), which makes the solution more efficient.

**Comment by andralungu** [comment]
It seems the issue was already fixed via #1075

**Pull request closed without merging**
