### PR TITLE
[FLINK-23373][task] Fully support object reuse in OperatorChain

### PR DESCRIPTION
**Pull request by twalthr**
## What is the purpose of the change

This adds the missing parts to make object reuse work in OperatorChain.

## Brief change log

See commit messages.

## Verifying this change

This change added tests and can be verified as follows:
`MultipleInputStreamTaskChainedSourcesCheckpointingTest` and `MultipleInputStreamTaskTest`

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): yes
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by dawidwys** [comment]
The change itself looks good. Could you add a test(s) to verify that the copying actually takes place?

**Comment by twalthr** [comment]
Thanks for the feedback @dawidwys. I updated the PR. Please have another look.

**Comment by twalthr** [comment]
Btw I also manually verified the change using the `HiveDialectQueryITCase`.

**Review by dawidwys — APPROVED** [review]
Thanks for addressing my comment and sorry for the delay.

**Pull request closed without merging**
