### PR TITLE
[FLINK-18472][docs] Local Installation Getting Started Guide

### PR DESCRIPTION
**Pull request by sjwiesman**
## What is the purpose of the change

Add a local installation guide to "Try Flink"

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / **docs** / JavaDocs / not documented)

Rendered: 

Screen Shot 2020-07-02 at 10 37 55 AM

### CODE REVIEW

**Comment by sjwiesman** [comment]
cc: @rmetzger @alpinegizmo

**Comment by alpinegizmo** [comment]
A couple of things to fix:

I don't think we publish snapshot builds, so the example with tar and cd is a bit off. (I realize this is probably a stable docs vs master docs issue, and I don't know of a good, easy solution.)

The output does not go to stdout. Maybe something like this:

{% highlight bash %}
$ tail log/flink-*-taskexecutor-*.out
(to,1)
(be,1)
(or,1)
(not,1)
(to,2)
(be,2)
...
{% endhighlight %}

**Comment by alpinegizmo** [comment]
When I left my previous comment, I hadn't really digested the warning/explanation at the top of the page. Maybe that's sufficient.

**Comment by sjwiesman** [comment]
@alpinegizmo Its the same warning we use for the ops playground, I'll find the log message when merging. Thank you both.

**Comment by sjwiesman** [comment]
@alpinegizmo Actually, just to make it very clear, I will only print the warning on snapshot builds and hide the installation steps.

**Pull request closed without merging**
