### PR TITLE
[FLINK-1508] Removes AkkaUtil.ask

### PR DESCRIPTION
**Pull request by tillrohrmann**
This PR removes the AkkaUtil.ask method and replaces all existing occurrences by explicit future handling. Furthemore, it removes the explicit actor address resolution which also introduced a blocking call.

### CODE REVIEW

**Comment by rmetzger** [comment]
I vote to merge this quickly and fix issues as they appear. 
The change touches a lot of different parts of the code and is predestined to become unmergeable quickly.

**Comment by uce** [comment]
Looks good to me.

**Comment by StephanEwen** [comment]
+1 to merge

**Comment by tillrohrmann** [comment]
I'll merge it.

**Pull request merged**
