### PR TITLE
Support mounting custom PVCs, secrets and config maps to job/Task manager pods

### PR DESCRIPTION
**Pull request by blublinsky**
## What is the purpose of the change

A common requirement for Flink applications is usage of custom resources (PVCs, Secrets, configMaps). For example, usage of NFS-based checkpointing, require mounting NFS volumes. There are additional examples of this

## Brief change log

*(for example:)*
  - Added custom resource mounting implementation
  - Added definitions for these resources to KubeConfig options
  - Modified Task and Job manager factories to use provided decorator
  - Add/modify unit tests

## Verifying this change

*(Please pick either of the following options)*

This change added tests and can be verified by. running them

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: yes, make kubernetes deployment more flexible by allowing mount custom PVCs, Secrets and configmaps 
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? yee
  - If yes, how is the feature documented? (JavaDocs)

### CODE REVIEW

**Comment by blublinsky** [comment]
Here is a complete configuration example:

./bin/flink run-application -p 8 -t kubernetes-application \
	-Dkubernetes.cluster-id=flink-native-k8s-application \
	-Dkubernetes.jobmanager.service-account=flink \
	-Dkubernetes.namespace=default \
	-Dkubernetes.container-start-command-template=%java% %classpath% %jvmmem% %jvmopts% %logging% %class% %args% \
	-Dtaskmanager.memory.process.size=8096m \
	-Dkubernetes.taskmanager.cpu=1.0 \
	-Dtaskmanager.numberOfTaskSlots=4 \
	-Djobmanager.memory.process.size=4096m \
	-Dkubernetes.jobmanager.cpu=2.0 \
	-Dkubernetes.container.image=lightbend/customflink:1.0 \
	-Djobmanagerpvcmount=pvc-mount:testclaim:/opt/pvcclaim \
	-Dtaskmanagerpvcmount=pvc-mount:testclaim:/opt/pvcclaim \
	-Djobmanagersecretmount=secret-mount1:nginx-ingress-token-7c9wl:/opt/secret/1,secret-mount2:flink-token-vr6r4:/opt/secret/2 \
	-Dtaskmanagerconfigmapmount=configmap-mount:nginx-ingress-controller:/opt/configmap \
	-Dkubernetes.jobmanager.labels=version:alphav1,deploy:test \
	-Dkubernetes.taskmanager.labels=version:alphav1,deploy:test \
	local:///opt/flink/examples/streaming/StateMachineExample.jar

**Comment by blublinsky** [comment]
Add support for environment variables and owner reference

**Comment by fsw0422** [comment]
+1 for this PR
We have a case where we want to mount a self signed certificate as configMap to test end-to-end locally before even going to dev environment

**Comment by blublinsky** [comment]
Thank you @tillrohrmann, my access to Jira does not work anymore and password reset seems to be broken. Any chance you can help me there?

**Comment by tillrohrmann** [comment]
Does it work to create a new JIRA account @blublinsky?

**Comment by niyanchun** [comment]
a useful PR

**Pull request closed without merging**
