### PR TITLE
[FLINK-3012] Refactor boilerplate code in DataSourceTask

### PR DESCRIPTION
**Pull request by jaoki**
Refactor repetitive and boilerplate code of while and if statements in DataSourceTask
The previous if and else nest and to control the timing to instantiate 'reuse' and the new code emphasizes the point.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Thanks for the interest in helping us maintain clear code.

I think actually that the original code was easier than the code with counter checks. Further more, it moves branches away from loops (easier optimizable by the JIT compiler). Finally, the new code will be wrong if the counter overflows/wraps around, which is not unthinkable. 4 Billion elements is quite within the scope of many applications.

I am curious about other opinions.

**Comment by jaoki** [comment]
@StephanEwen , thank you for your feedback. Looping with an int variable is clearly wrong in Flink's use case, and I can change to long, but, I'd like to hear more of this refactor. I'd withdraw this PR if it is not what the community prefer at the first place. Let me know!

**Comment by zentol** [comment]
I'm not too fond of the new version either and feel like this code bit doesn't really need more clarity, simply because it isn't a lot of code. 

Using a counter at all doesn't really make sense to me, you aren't counting anything effectively. a Boolean seems more intuitive. It is nit-picky but we are going for clarity here after all :)

**Comment by jaoki** [comment]
Thank you for your input. @zentol ! Withdrawing PR.

**Pull request closed without merging**
