### PR TITLE
Flink 4034 Maven dependency convergence

### PR DESCRIPTION
**Pull request by vpernin**
https://issues.apache.org/jira/browse/FLINK-4034
Green build : https://travis-ci.org/vpernin/flink/builds/141717643

### CODE REVIEW

**Comment by vpernin** [comment]
The builds 9896.1, 9896.2 and 9896.3 failed because of yarn tests or JMX reporter.
I do not have the right to restart these 3 jobs.

**Comment by StephanEwen** [comment]
Good idea in general.
I would use variables for all versions used more than once. For example, where ever `io.netty::netty` is used in version 3.x, it should probably refer to a variable which globally defines the version for that artifact.

**Comment by StephanEwen** [comment]
Now that the release is out, I think we should start addressing this. @vpernin does this still work on the latest master version?

**Comment by vpernin** [comment]
Hi,

I was on holidays.
I have to rebase on master and test again, hoping there is not too much new
conflicts.

2016-08-24 14:40 GMT+02:00 Stephan Ewen <notifications@github.com>:

**Pull request closed without merging**
