### PR TITLE
Update docker.md

### PR DESCRIPTION
**Pull request by mattfysh**
## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluster with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by MartijnVisser** [comment]
@mattfysh Thanks for the PR but please take the code contribution guide into account https://flink.apache.org/contributing/contribute-code.html

I can't see why it's important to add this; Flink also works without add, so why is it needed?

**Comment by mattfysh** [comment]
Hi @MartijnVisser - my apologies, I am short on time and hoped someone with PyFlink familiarity would pick this up and immediately identify why this change is required.

The current instructions do not work in Docker, which means they won't work on anyone's machine regardless of host setup

To reproduce, stand up a local cluster in session mode using the following steps:

1. Create a new folder
2. Create a Dockerfile inside the folder with the contents of "Using Flink Python on Docker": https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/deployment/resource-providers/standalone/docker/#using-flink-python-on-docker
3. Create a docker-compose.yaml file with the contents of "Session Mode": https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/deployment/resource-providers/standalone/docker/#session-cluster-yml
4. Change both instances of `image: flink:1.16.0-scala_2.12` to be `build: .`
5. Add a volumes entry to the `jobmanager` as:

        volumes:
            - .:/input

6. Create a word_count.py file with the contents of "The complete code so far" section https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/dev/python/table_api_tutorial/
7. Run `docker-compose up`
8. Enter the jobmanager via `docker exec -it [job_manager_container_id] bash`
9. Run `./bin/flink run --python /input/word_count.py`

This does not work, and throws the following error:

```
Caused by: java.lang.RuntimeException: Failed to create stage bundle factory! Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/fastavro/read.py", line 2, in <module>
    from . import _read
  File "fastavro/_read.pyx", line 11, in init fastavro._read
  File "/usr/local/lib/python3.7/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma
```

This is occurring because when building Python from source, as instructed in the Flink documentation I have updated, certain "optional modules" in Python are not built if host dependencies could not be found. This includes things like readline, sqlite, etc, but also lzma - more information can be found at https://devguide.python.org/getting-started/setup-building/#unix particularly the "optional modules were not found" message

From what I gather, the latest version of PyFlink uses a version of fastavro that requires lzma to be present in the Python build. I assume the instructions I have updated used to work with older version of PyFlink.

**Comment by mattfysh** [comment]
> Flink also works without add, so why is it needed?

Did you test on v1.16?

**Comment by MartijnVisser** [comment]
> Did you test on v1.16?

@dianfu @HuangXingBo I'm assuming we've done that, but you're the Python experts :)

**Comment by mattfysh** [comment]
Is there a desire within the Flink team to ensure that PyFlink achieves similar uptake and robustness as PySpark?

**Comment by MartijnVisser** [comment]
> Is there a desire within the Flink team to ensure that PyFlink achieves similar uptake and robustness as PySpark?

I think any open source community strives to improve their product :) 
Let me ping the maintainers on this PR once more

**Comment by dianfu** [comment]
Sorry for late response. I have missed this PR. The PR LGTM and I guess it should be caused by the bump of fastavro version which is introduced in https://issues.apache.org/jira/browse/FLINK-27058.

**Review by dianfu — APPROVED** [review]

**Pull request closed without merging**
