### PR TITLE
[FLINK-21225][table] Support OVER window distinct aggregates in Table API

### PR DESCRIPTION
**Pull request by LadyForest**
## What is the purpose of the change

* This pull request tries to support OVER window distinct aggregates in `OverConvertRule`. Currently, `OverConvertRule` always sets the distinct flag to false, and could not make rex call for an `agg` expression's children expression like `distinct(avg/count/sum(field))`, thus cause `ExpressionConverter#visit` throwing `RuntimeException` that "`Unknown call expression: avg(field)`".

## Brief change log

  - *The changes applied to `OverConvertRule` add a flag `isDistinct` by checking the function definition of `DISTINCT` and using inner agg expression to generate RexNode if `isDistinct` is true.*

## Verifying this change

This change added tests and can be verified as follows:

  - *`OverAggregateTest#testRowTimeBoundedDistinctWithPartitionedRangeOver`, `OverAggregateTest#testRowTimeUnboundedDistinctWithPartitionedRangeOver`, `OverAggregateTest#testRowTimeBoundedDistinctWithPartitionedRowsOver` and `OverAggregateTest#testRowTimeUnboundedDistinctWithPartitionedRowsOver` are to verify the optimized plan.*
  - *`OverAggregateITCase#testRowTimeBoundedDistinctWithPartitionedRangeOver`, `OverAggregateITCase#testRowTimeUnboundedDistinctWithPartitionedRangeOver`, `OverAggregateITCase#testRowTimeBoundedDistinctWithPartitionedRowsOver` and `OverAggregateITCase#testRowTimeUnboundedDistinctWithPartitionedRowsOver` are to verify the execution result.*
## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by LadyForest** [comment]
@flinkbot run azure

**Comment by LadyForest** [comment]
Hi @wuchong could you take a look when you're free?

**Review by wuchong — APPROVED** [review]
Thanks for the contribution. LGTM.

**Comment by wuchong** [comment]
Could you also open a pull request for 1.12 branch?

**Comment by LadyForest** [comment]
Sure :)

**Pull request merged**
