### PR TITLE
[FLINK-21142][connector-hive] Hide Guava from Hadoop and security tools

### PR DESCRIPTION
**Pull request by twalthr**
## What is the purpose of the change

Some security tools complain that the Guava version in Hive has known vulnerabilities. Also, as seen in the JIRA issue, users are complaining about the Guava version clashing with Hadoop 3.3. There a couple of guides that simply suggest to replace the Guava version:

https://kontext.tech/column/hadoop/561/apache-hive-312-installation-on-linux-guide

http://www.mtitek.com/tutorials/bigdata/hive/install.php

Of course this is not officially supported. But by excluding Guava in our SQL connector JARs we make both security scanning tools and partially users happy. Apparently, Guava classes are still present in the JAR after exclusion (some issue on the Hive side?) therefore we additionally relocate them and have a high chance that Hive fully works after this change.

The issue should be solved after Hive 4.0.0.

## Brief change log

Rely on the Hadoop's Guava + relocate non-excluded Guava classes.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): yes
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by twalthr** [comment]
CC @JingsongLi @lirui-apache

I haven't verified this PR against a running Hive. Could you help me to verify it? It helps in making the scanning tools at bigger customers happy and might help user as well. If the relocated Guava causes issues, we could alternatively filter it entirely and fully rely on Guava on the Hadoop classpath. What do you think?

**Review by Airblader — APPROVED** [review]
LGTM

**Comment by twalthr** [comment]
@wuchong sure, let me update the PR then. We should aim to have less internal forks and perform the changes in Flink so that all can benefit from it.

**Comment by twalthr** [comment]
@wuchong @lirui-apache I added more shading also to the other Hive modules. Could you test whether my changes make it possible to still run Hive? The relocation might be too strict as `com.google` includes `protobuf` as well but maybe this is not a problem for how we use Hive.

**Comment by wuchong** [comment]
@twalthr yes, `protobuf` is also purposed to be relocated. 

cc @luoyuxia, do you have time to help test whether the changes still make Hive connector work?

**Comment by lirui-apache** [comment]
LGTM. To make things a little bit more consistent, maybe we can use `org.apache.hive.shaded` as the prefix of the shaded pattern. We have already done so for parquet in FLINK-23074

**Pull request closed without merging**
