### PR TITLE
[hotfix] Remove execute() after print() in Table API examples

### PR DESCRIPTION
**Pull request by twalthr**

### CODE REVIEW

**Comment by rmetzger** [comment]
I thought we have ITCases for our examples to ensure that they are working?
Maybe we should add those to these examples as well

**Comment by rmetzger** [comment]
Sorry for the rude comment. Thank you for fixing the issue. Very good catch ;)
Maybe we should file a JIRA for adding ITCases for these examples ;)

**Comment by twalthr** [comment]
I will create an issue and assign it to me. I think I will heavily work on the Table API anyway the next time ;)

**Comment by StephanEwen** [comment]
This is a good fix anyways.

I'll merge it for the 0.9 release...

**Pull request closed without merging**
