### PR TITLE
[FLINK-25461][python] Update net.sf.py4j:py4j dependency to 0.10.9.3

### PR DESCRIPTION
**Pull request by MartijnVisser**
## What is the purpose of the change

* Updating net.sf.py4j:py4j from 0.10.8.1 to 0.10.9.3

## Brief change log

* Updated POM, Python dev requirements & setup, NOTICE file

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): yes
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Comment by MartijnVisser** [comment]
@HuangXingBo Do you want to take a look?

**Comment by dianfu** [comment]
@flinkbot run azure

**Review by dianfu — APPROVED** [review]
@MartijnVisser Thanks a lot for the PR. LGTM.

**Comment by dianfu** [comment]
@MartijnVisser Oh, just missed that the source package for Py4J is also needed to be updated: https://github.com/apache/flink/tree/master/flink-python/lib/

**Comment by MartijnVisser** [comment]
> @MartijnVisser Oh, just missed that the source package for Py4J should also be updated: https://github.com/apache/flink/tree/master/flink-python/lib/

Thanks for that @dianfu - I've updated the PR. Should it be mentioned in the README that this needs to be done? I only just saw it in the makefile.

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Comment by MartijnVisser** [comment]
@dianfu I think all issues have now been resolved, PTAL

**Review by HuangXingBo — APPROVED** [review]
LGTM

**Pull request closed without merging**
