### PR TITLE
[FLINK-21896][table-planner-blink] Correct the different serialization result for json plan between jdk8 and jdk11

### PR DESCRIPTION
**Pull request by godfreyhe**
## What is the purpose of the change

*This pr aims to correct the different serialization result for json plan between jdk8 and jdk11. please refer to[ FLINK-21896](https://issues.apache.org/jira/browse/FLINK-21896?focusedCommentId=17307129&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17307129) for more explanation*

## Brief change log

  - *Add serialVersionUID for all logical types*
  - *Update the json result based on new serialization result*

## Verifying this change

This change is already covered by existing tests*.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by godfreyhe** [comment]
cc @dawidwys

**Comment by dawidwys** [comment]
I'd prefer if @twalthr had a look at it.

**Review by twalthr — APPROVED** [review]
LGTM but we should avoid using the Java serialization for anything that has to do with persistence

**Comment by godfreyhe** [comment]
> LGTM but we should avoid using the Java serialization for anything that has to do with persistence. This is actually the reason why we don't have a serialization id set for those classes.

make sense, we will do more improvements to avoid object serialization later

**Pull request closed without merging**
