### PR TITLE
[FLINK-25911][runtime][security] Add delegation token framework documentation

### PR DESCRIPTION
**Pull request by gaborgsomogyi**
## What is the purpose of the change

In FLINK-21232 umbrella ticket delegation token support has been added but during implementation no documentation added for the small pieces. In this PR I've added an in-depth explanation what this feature is about.

## Brief change log

Added documentation

## Verifying this change

```
cd docs
./build_docs.sh
```
Open browser.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? docs

### CODE REVIEW

**Comment by gaborgsomogyi** [comment]
cc @mbalassi

**Comment by gaborgsomogyi** [comment]
Since the main concept of the delegation token framework is based on the Spark solution the documentation is also based on that. I would like to mark that as main source and would like to say thanks for all peoples who contributed to it.

**Comment by gaborgsomogyi** [comment]
@flinkbot run azure

**Comment by mbalassi** [comment]
@gaborgsomogyi could you please add an architecture diagram to explain the lifecycle of the DTs?

Something similar to [these](https://nightlies.apache.org/flink/flink-kubernetes-operator-docs-main/docs/concepts/architecture/) would be great.

**Comment by gaborgsomogyi** [comment]
@mbalassi I've just added high level architecture diagram.

**Comment by gaborgsomogyi** [comment]
Additionally rebased to the latest master.

**Comment by mbalassi** [comment]
Making minor edits directly locally with @gaborgsomogyi's consent and merging.

**Pull request closed without merging**
