### PR TITLE
[FLINK-12351][DataStream] Fix AsyncWaitOperator to deep copy StreamElement when object reuse is enabled

### PR DESCRIPTION
**Pull request by wuchong**
## What is the purpose of the change

Currently, AsyncWaitOperator directly put the input StreamElement into StreamElementQueue. But when object reuse is enabled, the StreamElement is reused, which means the element in StreamElementQueue will be modified. As a result, the output of AsyncWaitOperator might be wrong.

This pull request is aiming to fix this problem.

## Brief change log

- initialize `isObjectReuseEnabled` flag in `AsyncWaitOperator#open()` from `ExecutionConfig`.
- deep copy input `StreamRecord` using serializer if `isObjectReuseEnabled` is true

## Verifying this change

add a test in `AsyncWaitOperatorTest` to verify state snapshot and restore is correct even if object reuse is enabled and the input record is mutable.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): ( no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable )

### CODE REVIEW

**Comment by wuchong** [comment]
Hi @tillrohrmann @pnowojski , it would be nice if you have time to review it.

**Comment by wuchong** [comment]
@flinkbot attention @tillrohrmann

**Review by pnowojski — APPROVED** [review]
Sorry for late response, Jirabot reminded me about this. 

The change I think looks good to me. It would be good to rebase it and re run tests. Woul you be willing to pick up this work @wuchong ?

**Comment by wuchong** [comment]
Sure, @pnowojski , I have been waiting for you the two years :)

**Pull request merged**
