### PR TITLE
[hotfix][docs-zh]Fix Chinese document format errors.

### PR DESCRIPTION
**Pull request by liuzhuang2017**
## What is the purpose of the change
- **In english document:**
image

image

- **In chinese document:**
 
image

image

## Brief change log

- **The modified result looks like this:**

image

image

## Verifying this change

- No need to test.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by liuzhuang2017** [comment]
@MartijnVisser , Sorry to bother you again, can you help me review this pr? Thank you.

**Review by MartijnVisser — CHANGES_REQUESTED** [review]
@liuzhuang2017 Please make sure that the PR and the commit naming conventions are followed. https://flink.apache.org/contributing/code-style-and-quality-pull-requests.html#commit-naming-conventions

**Comment by liuzhuang2017** [comment]
@MartijnVisser , Thank you very much for your review. I'm sorry, this is my oversight, I'll fix him right away,

**Review by MartijnVisser — APPROVED** [review]
LGTM

**Pull request merged**
