### PR TITLE
[FLINK-4230] [DataStreamAPI] Add Session Windowing ITCase

### PR DESCRIPTION
**Pull request by StefanRRichter**
This PR contains an exhaustive integration test for Session Windows.

### CODE REVIEW

**Comment by aljoscha** [comment]
Nice pice of code! I finally understood how it works... 😃 

Some remarks about the code: in some places there are method names that seem to stem from an initial implementation but don't match the current code anymore. For example, `SessionEventGeneratorDataSource.createTestStream()` returns a "generator" so it could be called `createGenerator()`.  Also, there are some unused methods (for example in `EventGeneratorFactory`) and methods with generated Javadoc that don't have any actual content. Could you please have another pass over the code and remove the unused methods and remove or fix the Javadoc. Some of the classes could also use a class-level Javadoc.

In `SessionEventGeneratorImpl`, the name `generateLateTimestamp()` might be a bit misleading. It just creates timestamps in the range of allowed timestamps. Both `InLatenessGenerator` and `AfterLatenessGenerator` use the method in the same way, just the behavior of `canGenerateEventAtWatermark()` determines whether the generated elements will be late or not. Here, a good comment on `canGenerateEventAtWatermark()` might help on the base interface. Also, it might make sense to make the testing source non-parallel. If we have parallelism 2 and one source regularly advances the watermark but the other source never advances the watermark the elements that are generated as "late" by the first source are not considered late at the window operator because the watermark at the window operator cannot advance.

**Comment by StefanRRichter** [comment]
Thanks a lot for the review. I agree on all your points and will address them.

**Comment by aljoscha** [comment]
Oh, and I forgot: the checking for the correct number of elements can be moved out of the window function and into the test itself, like this:

```
JobExecutionResult result = env.execute();

Assert.assertEquals(
                (LATE_EVENTS_PER_SESSION + 1) * NUMBER_OF_SESSIONS * EVENTS_PER_SESSION,
                result.getAccumulatorResult(SESSION_COUNTER_ON_TIME_KEY));
Assert.assertEquals(
                NUMBER_OF_SESSIONS * (LATE_EVENTS_PER_SESSION * (LATE_EVENTS_PER_SESSION + 1) / 2),
                result.getAccumulatorResult(SESSION_COUNTER_LATE_KEY));
```

Also, you can let the test class extend `StreamingMultipleProgramsTestBase`. This will setup a testing cluster with parallelism 4. You can then use this inside your test:
```
StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment()
```

If you make the source non-parallel the window operator will then run with parallelism 4 and counting the number of elements after the job is done will accumulate the counts from all parallel instances.

**Comment by StefanRRichter** [comment]
I improved on the points mentioned in the PR review.

**Comment by aljoscha** [comment]
Thanks for your work! I merged it. Could you please close this PR if it isn't closed automatically.

**Comment by StefanRRichter** [comment]
Thanks Aljoscha, I will close it.

**Pull request closed without merging**
