### PR TITLE
[FLINK-3631] CodeGenerator does not check type compatibility for equa…

### PR DESCRIPTION
**Pull request by ramkrish86**
Adds a check on the CodeGenerator.scala code which does a check on the left and right operands so that all the comparison expressions can work now. (=,!=,>,<)

### CODE REVIEW

**Comment by fhueske** [comment]
Thanks for the PR @ramkrish86 
Looks good. Just one minor thing. Can you add a one line comment to each test that explains why the program should fail such as the tests `testNonWorkingSubstring1()` and `testNonWorkingSubstring2()`? Thanks!

**Comment by ramkrish86** [comment]
I have done the update @fhueske .Thanks for the review.

**Comment by fhueske** [comment]
Perfect, thanks for the update. Good to merge.

**Comment by fhueske** [comment]
Merging

**Pull request closed without merging**
