### PR TITLE
[FLINK-32648][table] Reuse Calcite's `SqlWindowTableFunction`

### PR DESCRIPTION
**Pull request by snuyanzin**
## What is the purpose of the change

The PR is aiming to reuse Calcite's `SqlWindowTableFunction` for window table functions.
One noticeable change is that for `SqlWindowTableFunction` it skips first operand for window function during `org.apache.calcite.sql2rel.StandardConvertletTable#convertWindowFunction` which is actually a query.

Current Flink's code tries to do similar things at  `org.apache.flink.table.planner.plan.rules.logical.ProjectWindowTableFunctionTransposeRule#rewriteWindowCall`

The diff is since Calcite does it on convertlet level there is no need for this operand in plans

## Verifying this change

This change is already covered by existing tests, such as *(please describe tests)*.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: ( no)
  - The runtime per-record code paths (performance sensitive): ( no )
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: ( no)
  - The S3 file system connector: ( no )

## Documentation

  - Does this pull request introduce a new feature? ( no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by snuyanzin** [comment]
@lincoln-lil I noticed you are also working with windows 
may I ask you to have a look here?

**Review by lincoln-lil — COMMENTED** [review]
@snuyanzin this change looks fine! Only one minor comment for the java doc of the `SqlWindowTableFunction`

**Review by lincoln-lil — APPROVED** [review]
LGTM!

**Comment by snuyanzin** [comment]
Thanks for taking a look

**Pull request merged**
