### PR TITLE
[FLINK-2275] Migrate test from package 'org.apache.flink.test.javaApiOperators'

### PR DESCRIPTION
**Pull request by mjsax**
migrated test from execute() to collect()
subtask of https://issues.apache.org/jira/browse/FLINK-2032

### CODE REVIEW

**Comment by mjsax** [comment]
I adapted all tests except for DataSinkITCase and ExecutionEnvironmentITCase.
 - DataSinkITCase -> seems to test writing to file explicit; would not make sense to change it (tell me, if I am wrong)
 - ExecutionEnvironmentITCase ->uses LocalCollectionOutputFormat, and is not writing to disc already

**Comment by StephanEwen** [comment]
All in all this looks good.

The only think that strikes me is the of the test pattern(that way used also before by the tests. I am not a big fan of validating results in an `@After` method. I find the tests more readable if they simply call the comparison themselves at the end:
```java
List<Tuple2<String, Integer>> result = data.collect()

String expected = "Hello,2\n" + 
                  "Dude,5\n" 

compareResultAsTuples(expexted, result)
```
This also solves the issue with the raw type lists, which is usually an indicator that something is not modeled in the right way (unless you dynamically load or instantiate types).

**Comment by StephanEwen** [comment]
This comment is not a blocker for merging this. Let's just not write future tests like this, and whenever we touch something, we could on-the-fly migrate the tests to not follow this pattern any more...

**Comment by mjsax** [comment]
I agree. I just did not want to change the current pattern... However, we should do it the right way in this PR, too. I will update the code accordingly.

**Comment by mjsax** [comment]
Done. Failing tests revile a Kafka problem (in my Travis, too  https://travis-ci.org/mjsax/flink/builds/68598571). Is it known? Module flink-tests passed in all runs.

Should be ready to get merged.

**Comment by rmetzger** [comment]
@gyfora re-enabled a disabled Kafka test in this pull request: https://github.com/apache/flink/pull/747/files
The test is known to be unstable, thats why I disabled it for the time being. Can you disable it again in your PR?

**Comment by gyfora** [comment]
Sorry about re-enabling the failing test, I completely missed it...
Matthias please @ignore it :P

Btw @rmetzger do we have a JIRA for this?

**Comment by mjsax** [comment]
Done. If Travis is green, please merge. :)

**Comment by StephanEwen** [comment]
Looks good, let me merge this...

**Pull request closed without merging**
