### PR TITLE
[BK-1.16][FLINK-26182][Connector/pulsar] Create a e2e tests for Pulsar sink.

### PR DESCRIPTION
**Pull request by syhily**
This is a backport PR for https://github.com/apache/flink/pull/20584.

### CODE REVIEW

**Comment by tisonkun** [comment]
@HuangXingBo This patch adds end-to-end tests for Flink Pulsar connector and I think it's good for backporting to 1.16. However, to pass the end-to-end tests it adjusts some production code so I'm unsure whether it causes more delay to the ongoing 1.16.0 release.

Since you're the release manager, I sincerely ask for your suggestion on whether we could merge this patch to the release-1.16 branch _now_ or after you finish the release.

**Review by tisonkun — APPROVED** [review]

**Comment by HuangXingBo** [comment]
@tisonkun  Thanks a lot for the info. I prepared rc1 and have pushed the tag yesterday. When the release announcement is ready in the form of PR, I will send the vote email today. Does this PR need to cancel rc1, or it have little effect on whether 1.16.0 includes this patch.

**Comment by tisonkun** [comment]
> Does this PR need to cancel rc1

No.

Then I think I can merge this patch as a testing coverage improvement and bugfix now while you can still vote on the rc1 you made yesterday:

1. If rc1 passes the vote, it's OK to include this patch in the first patch release 1.16.1;
2. If it doesn't, it's OK to include it in rc2.

Let me know if it makes sense to you.

**Comment by HuangXingBo** [comment]
Yes. Make sense to me.

**Pull request merged**
