### PR TITLE
[scripts] resolve base path of symlinked executable

### PR DESCRIPTION
**Pull request by mxm**
This bootstraps Flink from a symlinked bin/flink executable. It's a special case but IMHO worthwhile to consider.

### CODE REVIEW

**Comment by uce** [comment]
We have similar code in `config.sh`:

```bash
# Resolve links
this="$0"
while [ -h "$this" ]; do
  ls=`ls -ld "$this"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '.*/.*' > /dev/null; then
    this="$link"
  else
    this=`dirname "$this"`/"$link"
  fi
done
```

Does it make sense to have both scripts in sync as they try to do the same thing?

**Comment by mxm** [comment]
Unfortunately, we cannot access the config.sh file in this case. So code reuse is not possible. I've also seen the code you posted. It looks awfully hacky and we could at least use my code snippet also in the `scripts.sh`.

**Comment by uce** [comment]
Yes, we cannot access it.

I meant to either copy from `config.sh` or Your New Snippet™ to have it in sync.

**Comment by mxm** [comment]
Yes, the two are in sync now.

**Comment by mxm** [comment]
Apparently, the `readlink` utility is not part of POSIX. So we might have to revert to the old way of parsing the output of `ls -ld` to stay compatible. It is actually more reliable than I thought because POSIX specifies that the output of `ls -ld` should always be of the form "link_name -> target".

**Comment by uce** [comment]
OK, can you please update the PR accordingly? I will test it and then we are good to go. :)

**Comment by mxm** [comment]
Here you go. Thanks for testing!

**Comment by uce** [comment]
Corresponding issue in order to track fixed issues for the upcoming release: https://issues.apache.org/jira/browse/FLINK-2572

**Pull request closed without merging**
