### PR TITLE
[FLINK-32975][state] Enhance equal() for all MapState's iterator

### PR DESCRIPTION
**Pull request by jiexray**
## What is the purpose of the change

The assertThat() in junit5 uses Object#equals to compare two Map.Entry. The unnamed class Map.Entry<UK, UV> in ChangelogMapState uses the default Object#equals(), which does not compares the contents of two entries.

## Brief change log

  - *Add a basic equal() implementation for the Map.Entry<UK, UV> in ChangelogMapState.*

## Verification
  
  - Existing test `ChangelogMapStateTest#testEntriesIterator` has covered the change.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

### CODE REVIEW

**Review by masteryhx — CHANGES_REQUESTED** [review]
Thanks for the pr.
I could get the idea but it's better to add a seperate test to verify the method.
We could add such a test in `ChangelogMapStateTest`.

**Comment by jiexray** [comment]
@masteryhx Thank you for the review. I have added a new test in `ChangelogMapStateTest`. In the test, I try to assert the following:
```
state1.iterate().next() equals expected; // assert-1
state2.iterate().next() equals expected; // assert-2

state1.iterate().next() equals state2.iterate().next(); // assert-3
```

`assert-1` and `assert-2` are passed without the overwrite `equal()`. However, `assert-3` will fail without the overwrite `equal()`.

**Review by masteryhx — APPROVED** [review]
LGTM

**Review by masteryhx — CHANGES_REQUESTED** [review]
I have rethinked all logics of MapState#iterator and find RocksDBMapState also has this problem (HeapMapState works well).
So I'd suggest we could also enhance such euqals() for RocksDBMapState and verify the logic in StateBackendTestBase#testMapState.
WDYT?

**Review by masteryhx — APPROVED** [review]
LGTM

**Pull request closed without merging**
