### PR TITLE
[FLINK-31319][BP-1.17][connectors/kafka] Fix kafka new source partitionDiscoveryIntervalMs=0 cause bounded source can not quit

### PR DESCRIPTION
**Pull request by taoran92**
Backport [FLINK-31319](https://issues.apache.org/jira/browse/FLINK-31319) to release-1.17.

### CODE REVIEW

**Review by leonardBang — APPROVED** [review]
Thanks @chucheng92 for the backport, LGTM

**Comment by RamanVerma** [comment]
@chucheng92 please see my comments in the original PR https://github.com/apache/flink-connector-kafka/pull/8 before merging this one.

**Comment by chucheng92** [comment]
> @chucheng92 please see my comments in the original PR [apache/flink-connector-kafka#8](https://github.com/apache/flink-connector-kafka/pull/8) before merging this one.

thanks~ @RamanVerma .fixed yet already.

**Review by PatrickRen — APPROVED** [review]
Thanks for the contribution @chucheng92 ! LGTM.

**Pull request merged**
