### PR TITLE
[FLINK-3334] [conf] Include year-month-day in the log output

### PR DESCRIPTION
**Pull request by StephanEwen**
Modifies the date pattern in all log config files

### CODE REVIEW

**Comment by mxm** [comment]
This will make log files harder to read but I see that it is necessary for production systems.

**Comment by gyfora** [comment]
Looks good :) Thanks Stephan!

**Comment by mxm** [comment]
+1 also from my side.

**Comment by StephanEwen** [comment]
Yeah, streaming systems tend to run for longer than a day, so it makes sense to log the day...

**Comment by StephanEwen** [comment]
Manually merged in d51bec1524a9832a7e6c0f6c5d5be5a42712d365

**Pull request closed without merging**
