### PR TITLE
[FLINK-26191][connectors/elasticsearch] Revert Elasticsearch dependencies to 7.10.2 to keep Apache 2 license

### PR DESCRIPTION
**Pull request by alpreu**
## What is the purpose of the change

We need to revert back to an older Elasticsearch version as the newer versions have a different, more prohibitive license.

## Brief change log
- Revert back from 7.15.2 to 7.10.2 (which is the newest version that still uses the Apache license)

## Verifying this change

This change is already covered by existing tests, such as unit tests, end-2-end tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**yes** / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by fapaul — CHANGES_REQUESTED** [review]
Thanks for the quick fix. If I checked the correct Elasticsearch 6.x is not affect by the new license. Can you confirm that?

I also think you should update the `DockerImageVersions` file to also use the correct elastic search server version.

**Comment by zentol** [comment]
When I checked ES6 is also affected.

**Comment by zentol** [comment]
Let me double-check where I found that...

**Comment by fapaul** [comment]
> When I checked ES6 is also affected.

Is this the License file you have looked at https://github.com/elastic/elasticsearch/blob/6.8/LICENSE.txt? @zentol Maybe I am reading it wrong but it seems fine to me and Apache License applies

**Comment by alpreu** [comment]
> > I was thinking about changing the docker images as well, but I also think testing against the latest minor version makes sense. WDYT?
> 
> I have a little trust issue with elastic since they tend to introduce breaking changes in every minor release ;)

I agree but this would also mean that we have to tell users that we do not support using the connector across minor versions

**Comment by rmetzger** [comment]
Is the flink ci currently generally unstable? The last two PRs I looked at had failures.

**Comment by rmetzger** [comment]
I don't fully get what the discussions about ES6 are about. The version we currently use seems to be `6.8.20`, which (according to the contents of the jar file is ASL 2.0, and the repo LICENSe file on that version seems fine at first sight: https://github.com/elastic/elasticsearch/blob/v6.8.20/LICENSE.txt)

Once CI is passing, I'm +1 on merging this.

**Comment by fapaul** [comment]
@flinkbot run azure

**Comment by rmetzger** [comment]
CI failure reported here: https://issues.apache.org/jira/browse/FLINK-26387?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=17499289#comment-17499289

**Comment by fapaul** [comment]
I am merging this PR since the change only affects elasticsearch and the test failures are known instabilities

**Pull request merged**
