### PR TITLE
[FLINK-2764] [WebClient] [0.10.0-milestone-1] WebClient cannot display multiple Jobs

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Can I merge this?

**Comment by mjsax** [comment]
If no objections I will merge this.

**Comment by aljoscha** [comment]
Is this just a fix for the milestone-1 or the master?

**Comment by mjsax** [comment]
Both. I labeled it as milestone-1 because I opened this PR before it was decided that the next RC will be forked from master. So I would just merge in into master right now (and it will be included in milestone-1 automatically).

**Comment by mjsax** [comment]
Merging this now to master.

**Comment by StephanEwen** [comment]
Thanks for fixing this!

**Pull request closed without merging**
