### PR TITLE
[FLINK-3739] [table] Add a null literal to Table API

### PR DESCRIPTION
**Pull request by twalthr**
This PR adds the NULL literal to Java/Scala Table API as well as SQL API.

### CODE REVIEW

**Comment by yjshen** [comment]
Hi @twalthr, why we need a null literal? Please forgive me if this is a silly question...

**Comment by twalthr** [comment]
There are no silly questions ;-)
SQL fully integrates NULL in all its operators. So we should also allow it in our APIs as our runtime allows it anyway. You need it for e.g. `CASE b WHEN 1 THEN 11 WHEN 2 THEN 4 ELSE NULL END`

**Comment by vasia** [comment]
Hey @twalthr, thanks for the PR!
One comment is that we need to update the docs about the null literal and how to configure the null check. Second, I don't really understand the behavior when the null check is not set. We return some default values, but how were these decided?

**Comment by twalthr** [comment]
I will update the docs. The default values are defined in `CodeGenUtils`.
```
  def primitiveDefaultValue(tpe: TypeInformation[_]): String = tpe match {
    case INT_TYPE_INFO => "-1"
    case LONG_TYPE_INFO => "-1"
    case SHORT_TYPE_INFO => "-1"
    case BYTE_TYPE_INFO => "-1"
    case FLOAT_TYPE_INFO => "-1.0f"
    case DOUBLE_TYPE_INFO => "-1.0d"
    case BOOLEAN_TYPE_INFO => "false"
    case STRING_TYPE_INFO => "\"\""
    case CHAR_TYPE_INFO => "'\\0'"
    case _ => "null"
  }
```

**Comment by fhueske** [comment]
Shouldn't the program fail if we encounter `null` values in the non-null mode? Replacing `null` with default values sounds wrong to me and can easily produce wrong results without anybody noticing it.

**Comment by twalthr** [comment]
@fhueske yes we can also throw an expection if you like.

**Comment by vasia** [comment]
+1 to throwing an exception instead of returning a default value.

**Comment by fhueske** [comment]
OK, sounds good. The exception can be implemented as a separate issue. I'll open a JIRA for that.
This PR looks good and can be merged, IMO.

**Comment by fhueske** [comment]
Created FLINK-3759.

**Comment by twalthr** [comment]
I have updated the documentation. I will update the EBNF grammar as part of FLINK-3086, because it seems to be out of sync anyway. I will assign FLINK-3086 to me, if thats ok?

**Comment by yjshen** [comment]
I happened to have context here for `primitiveDefaultValue`, I think this was originated from Apache Spark's counterpart for create default values for an expression. Let me summarize how it is used to calculate scalar expression's result in Spark:

```
boolean ${result.isNull} = false;
$javaType ${result.value} = ${ctx.defaultValue(type)};
if (result is not null for some input) {
   ${result.value} = calculated result;
} else {
   ${result.isNull} = true;
}
```
Therefore, after the evaluation of this expression, if the result is Null, the `isNull` field is set to `True` and no more touches on `value` field, if not null, the `result.value` point to the final result. The default value is never used.

**Comment by fhueske** [comment]
Ah, thanks @yjshen for the explanation! :-)

**Comment by twalthr** [comment]
@yjshen thanks for the explanation. You are right, the Table API has the same behavior.
I would merge this later together with #1881, if no objections...

**Comment by fhueske** [comment]
If the Table API has the same behavior, why do the default values for nulls appear in the result of the tests?

**Comment by twalthr** [comment]
Because @yjshen's code example only applies if the null check is enabled. If not, there is no additional `isNull` field. So every operation needs a valid return value that is used in the following operations otherwise default.

**Comment by yjshen** [comment]
Are there other systems support `not nullCheck` mode?

**Comment by fhueske** [comment]
@twalthr, OK got it. The default is used in both cases. +1 to merge and fix FLINK-3759 soon.

**Comment by twalthr** [comment]
Merging...

**Pull request closed without merging**
