### PR TITLE
[FLINK-13341][table][connectors] StreamTableSink#consumeDataStream returns DataStreamSink when using blink planner.

### PR DESCRIPTION
**Pull request by kaka11chen**
…returns DataStreamSink when using blink planner.

## What is the purpose of the change

*Add missing StreamTableSink#consumeDataStream returns DataStreamSink implementations when using blink table planner.*

## Brief change log

  - *Add missing StreamTableSink#consumeDataStream returns DataStreamSink implementations when using blink table planner.*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature?  (no)

### CODE REVIEW

**Comment by JingsongLi** [comment]
Thanks @kaka11chen , can you modify the rest connectors? 
`JDBCUpsertTableSink`
`HBaseUpsertTableSink`
`CassandraAppendTableSink`

**Comment by kaka11chen** [comment]
@JingsongLi OK.

**Comment by kaka11chen** [comment]
@JingsongLi CassandraAppendTableSink added.

**Comment by kaka11chen** [comment]
@JingsongLi Thanks.

**Comment by dawidwys** [comment]
Thank you @kaka11chen for your contribution! I merged it.

**Pull request closed without merging**
