### PR TITLE
[FLINK-7249] [build] Bump java.version property to 1.8

### PR DESCRIPTION
**Pull request by zentol**
This PR bumps the java.version property used by the maven-compiler-plugin and quickstarts to 1.8 .

### CODE REVIEW

**Comment by greghogan** [comment]
Also need to update the documentation.

$ grep -lir "java 7" docs/
docs//quickstart/java_api_quickstart.md
docs//quickstart/scala_api_quickstart.md
docs//quickstart/setup_quickstart.md
docs//setup/building.md

**Comment by zentol** [comment]
@greghogan Nice catch, i completely forgot about possible references in the docs. I modified the files you mentioned.

**Comment by greghogan** [comment]
+1 to merge

We can also simplify setting the garbage collector in `flink-dist/src/main/flink-bin/bin/taskmanager.sh` and including the `flink-connector-elasticsearch5` module in `flink-connectors/pom.xml`.

**Comment by zentol** [comment]
I've created JIRAs for addressing the issues you found.

Will merge this.

**Pull request closed without merging**
