### PR TITLE
[FLINK-8227] Optimize the performance of SharedBufferSerializer

### PR DESCRIPTION
**Pull request by dianfu**
## What is the purpose of the change

*This pull request optimize the performance of SharedBufferSerializer*

## Verifying this change

This change is a performance improvement without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by StephanEwen** [comment]
@kl0u or @dawidwys I think this could use your opinion.

General questions:
  - Is there any reason to use a boxed integer over a primitive one? Primitives should be the default choice.
  - Is is correct that this the id is transient?

**Comment by dawidwys** [comment]
I think it is a very good and needed change.

As for @StephanEwen questions:

Ad 1. I see no problem with this `entryId` being primitive `int`. 
Ad 2. I think this field should be transient it is used only during the serialization process to reflect the order in which we serialize the SharedBufferEntries to restore the links between them. It does not play any role outside of serialization.
Ad 3. I agree it should be at least long. It will limit  the number of intermittent state of pattern graph.

After changing `int` to `long` I think it is ok to be merged.

**Comment by dianfu** [comment]
@dawidwys  @StephanEwen Sorry for late response. For question 1 and 2, I have the same thought with @dawidwys and have updated the PR accordingly. For question 3,  I think `int` is enough as we currently store `SharedBufferEntry` in a `HashMap` for each `SharedBufferPage`, and the size of  `HashMap` is `int`. If we want to support `long`, we should also change `HashMap` to something else. What's your thought?

**Comment by dawidwys** [comment]
@dianfu Don't we assign unique id across all pages, not just a single one? The maximum number of entries is MAX_INT * MAX_INT then, isn't it? If I am right, I think we should use `long` then.

**Comment by dianfu** [comment]
The page number is the number of patterns and so it is usually very small.  The `long` is only needed in theory just as you said MAX_INT * MAX_INT resulting to MAX_LONG. If this makes sense, then the `HashMap` may be should also be replaced as the entry number in one page may be MAX_LONG in theory too.  

Changing `int` to `long` will introduce state incompatible issue and we need to take care of that when performing serialization/deserialization. I just wonder if it is worth making this change.

**Comment by dawidwys** [comment]
You are right. I see now this `int` is not the only reason for the limit of `SharedBufferEntry`. Increasing this limit would require way more changes. Let's keep `int` then.

Will merge it soon.

**Comment by dawidwys** [comment]
Merged it. Thanks for the contribution!

**Pull request closed without merging**
