### PR TITLE
[FLINK-8537][table]Add a Kafka table source factory with Avro format support

### PR DESCRIPTION
**Pull request by xccui**
## What is the purpose of the change

This PR adds the Kafka table source factory with Avro format.

### Adding
  - Add an `Avro` format descriptor and the corresponding validator.
  - Add a `KafkaAvroTableSourceFactory` and its version specific implementations.
  - Add a `KafkaTableSourceFactory` and make the json/avro factory extend it.
  - Add `equals()` and `hashCode()` methods to the timestamp/watermark extractors for testing.

### Updating
  - Make `ExistingField` final.
  - Move the `convertToRowTypeInformation()` method to a new helper class `AvroTypeInfoConverter`.

### Dependency
  - Make `flink-avro` depend on `flink-table` and `flink-streaming-scala`.
  - Remove the `flink-avro` dependency from `flink-table` and move the only effcted test `AvroTypesITCase` to `flink-avro`.

## Verifying this change

This change can be verified by the test cases in `AvroTest` and `KafkaAvroTableSourceFactoryTestBase`.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (JavaDocs)

### CODE REVIEW

**Comment by xccui** [comment]
Hi @twalthr @fhueske, I wonder if you could help review this PR when you are convenient.

Thanks, Xingcan

**Comment by xccui** [comment]
Hi @twalthr, I've rebased this PR and fixed some problems.

**Comment by twalthr** [comment]
Thank you for the PR @xccui. The code very looks good to me. I will fix some minor things during merge.

**Comment by xccui** [comment]
Thanks for the review @twalthr. 😄

**Pull request closed without merging**
