### PR TITLE
[FLINK-2943][web-dashboard] Confusing Bytes/Records "read" and "write" labels in WebUI job view

### PR DESCRIPTION
**Pull request by sachingoel0101**
Also includes a hotfix for the taskmanager charts legend and FLINK-2903.

### CODE REVIEW

**Comment by fhueske** [comment]
Thanks for the PR. I will try it out.

One general comment though. Can we please not merge several issues into a single PR? The problem is that this breaks the automatic linking of PRs and JIRA issues. In this case, FLINK-2903 will not receive any comments made on this PR. Separate PRs for individual issues is also requested by our [coding guidelines](http://flink.apache.org/contribute-code.html#coding-guidelines).

**Comment by sachingoel0101** [comment]
Ah. Apologies. Will separate 2903 related work.

**Comment by fhueske** [comment]
Thanks @sachingoel0101!

**Comment by fhueske** [comment]
The changes look good to me. IMO, both should be added to the next RC.
@sachingoel0101, when do you think you can update the PRs?

**Comment by sachingoel0101** [comment]
Probably in a few minutes. :') 
Just building and making a final test right now.

**Comment by sachingoel0101** [comment]
It's okay to include the task manager legend related work with this, right? That's too minor to open a jira and track separately.

**Comment by fhueske** [comment]
I think it's OK.

**Comment by fhueske** [comment]
Thanks for the update @sachingoel0101.
Good to merge!

You will open a new PR for 2903 soon, right? Thanks

**Comment by sachingoel0101** [comment]
Already done. #1326

**Comment by fhueske** [comment]
Merging this PR

**Pull request closed without merging**
