### PR TITLE
[FLINK-12181][Tests] Port ExecutionGraphRestartTest to new codebase

### PR DESCRIPTION
**Pull request by leesf**
## What is the purpose of the change

Port ExecutionGraphRestartTest to new codebase.

## Brief change log

*(for example:)*
  - *Use TaskManagerLocation, SimpleAckingTaskManagerGateway and TestingResourceManagerGateway in repalce of Instance.*
  - *Use SlotPool#releaseTaskManager in replace of Instrance#markDead *

## Verifying this change

This change is a trivial rework.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by tillrohrmann** [comment]
Thanks for opening this PR @leesf. Could you please rebase against the current master to resolve the merge conflicts?

**Comment by leesf** [comment]
@tillrohrmann Rebased.

**Comment by leesf** [comment]
@azagrebin Thanks for you review and sorry for lately reply. Updated the PR and address your comments,  would you please review this pr in your free time?

**Comment by azagrebin** [comment]
Thanks for addressing the comments @leesf !
I created another PR with some more refactoring #8386 on top of this PR.
Please, have a look if you agree, we can close this PR and I will squash our commits into a co-authored one in my PR to merge.
I also included changes from #7809 to port SimpleSlotProvider used in ExecutionGraphRestartTest.

**Comment by leesf** [comment]
@azagrebin Thanks for opening another PR, I will close this one.

**Pull request closed without merging**
