### PR TITLE
[FLINK-21938][docs] Add how to unit test python udfs

### PR DESCRIPTION
**Pull request by YikSanChan**
## What is the purpose of the change

Let users know how to unit test their Python scalar UDF.

## Brief change log

Document how to unit test Python scalar UDF.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

No.

## Documentation

  - Does this pull request introduce a new feature? (yes / no) no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by YikSanChan** [comment]
@rmetzger Hi Robert, is there anything I need to do here?

**Comment by rmetzger** [comment]
No, we have to wait for a reviewer to show up. @HuangXingBo could you take a look?

**Comment by YikSanChan** [comment]
@dianfu Hi Dian, can you please take a look? Thanks

**Comment by dianfu** [comment]
Sure. Very sorry for late response.

**Comment by YikSanChan** [comment]
@dianfu Feel free to let me know if you have any comments

**Comment by dianfu** [comment]
@YikSanChan I'm considering adding another page to hold this information instead of putting it inside ScalarFunction as it applies also to other kinds of user-defined functions. Besides the unit test, the page could also contain the other informations about user-defined function, e.g. logging, how to load a large data set, etc.

**Comment by YikSanChan** [comment]
@dianfu I agree with the proposal, though I don't have much experience on other udfs as well as logging/loading large dataset etc, therefore no sure what to add, correctly. Given this, do you like me to add something, or maybe we can move forward with this one (since the little-doc is better than no-doc)?

**Comment by dianfu** [comment]
@YikSanChan What about rebase this PR after that page is added. I can add that page. Will let you know when it is ready. Thank you a lot~

**Comment by YikSanChan** [comment]
@dianfu Sure, that sounds good! Let me know when you add the page. 👍

**Pull request closed without merging**
