### PR TITLE
[FLINK-27731][Documentation][Build] Remove Hugo Modules integration

### PR DESCRIPTION
**Pull request by MartijnVisser**
## What is the purpose of the change

Remove all the Hugo Modules integration

## Brief change log

Clean-up

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by zentol** [comment]
This change is weird. Shouldn't people run build_docs.sh in docker, which then also runs setup_docs.sh within the same container?

**Comment by zentol** [comment]
Ah I see, the hugo image is hard-wired to call hugo directly...and doesn't contain bash.
Yeah, I'd be curious if we could come up with an alternative to that image, because it seems kinda eh.

e.g.

`docker run -v $(pwd):/src -w /src -p 1313:1313 chesnay/flink-ci:java_8_11 ./build_docs.sh`

**Comment by MartijnVisser** [comment]
> Yeah, I'd be curious if we could come up with an alternative to that image, because it seems kinda eh.

We could decide to fork it and remove the hardwire + add bash.

**Comment by zentol** [comment]
Do we want to maintain a second image that is capable of building the docs (beyond the CI image)? The CI image is a bit heavier than a purpose-built hugo image, but I'm not sure that is such a huge concern.
(at least for the time being; if we use a different image on CI for tasks where hugo is needed then that would be fine.)

**Review by zentol — APPROVED** [review]

**Pull request merged**
