### PR TITLE
[FLINK-34337][core] Sink.InitContextWrapper should implement metadataConsumer method

### PR DESCRIPTION
**Pull request by Jiabao-Sun**
## What is the purpose of the change

[FLINK-34337][core] Sink.InitContextWrapper should implement metadataConsumer method

## Brief change log

Sink.InitContextWrapper should implement metadataConsumer method.
If the metadataConsumer method is not implemented, the behavior of the wrapped WriterInitContext's metadataConsumer will be lost.

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by Jiabao-Sun** [comment]
Hi @pvary, could you help review it when you have time?

**Comment by pvary** [comment]
@Jiabao-Sun: Good catch! Thanks! This need to be in 1.19.0!

OTOH:

> This change is already covered by existing tests.

I think this is not true, as there were no unit tests breaking when I forgot to add this method to the wrapper.

Which test cover the usage of `metadataConsumer`? Do we want to implement one which breaks if this method is missing?

**Comment by MartijnVisser** [comment]
Thanks for flagging and fixing this. Like @pvary says, it would be good to see if we could add a test for this. I'll make sure that this gets to the Blockers list for 1.19

**Comment by Jiabao-Sun** [comment]
Thanks @pvary and @MartijnVisser for the review and I'm trying to add some tests.

I discovered this issue while trying to adapt the Kafka connector to the SinkV2 interfaces, which causes the KafkaWriterITCase to fail in 1.19-SNAPSHOT.

https://github.com/apache/flink-connector-kafka/blob/abf4563e0342abe25dc28bb6b5457bb971381f61/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaWriterITCase.java#L338

**Comment by Jiabao-Sun** [comment]
Hi @pvary, could you help review it again?
Thanks.

**Comment by pvary** [comment]
Sorry for the late response - I have been otherwise occupied.

Thanks for the test. Could we add a test which checks all of the mappings, something like this:
```

    @Test
    void testInitContextWrap() throws Exception {
        final AtomicReference<Sink.InitContext> initContext = new AtomicReference<>();
        final AtomicReference<WriterInitContext> originalContext = new AtomicReference<>();
        final AtomicBoolean consumed = new AtomicBoolean(false);

        final Sink<String> sink =
                new Sink<String>() {
                    @Override
                    public SinkWriter<String> createWriter(WriterInitContext context)
                            throws IOException {
                        WriterInitContext decoratedContext =
                                (WriterInitContext)
                                        Proxy.newProxyInstance(
                                                WriterInitContext.class.getClassLoader(),
                                                new Class[] {WriterInitContext.class},
                                                (proxy, method, args) -> {
                                                    if (method.getName()
                                                            .equals("metadataConsumer")) {
                                                        return Optional.of(
                                                                (Consumer<AtomicBoolean>)
                                                                        o -> consumed.set(true));
                                                    }
                                                    return method.invoke(context, args);
                                                });
                        originalContext.set(decoratedContext);
                        return Sink.super.createWriter(decoratedContext);
                    }

                    @Override
                    public SinkWriter<String> createWriter(InitContext context) {
                        initContext.set(context);
                        return null;
                    }
                };

        final int subtaskId = 1;
        final int parallelism = 10;
        final TypeSerializer<String> typeSerializer = StringSerializer.INSTANCE;
        final JobID jobID = new JobID();

        final MockEnvironment environment =
                MockEnvironment.builder()
                        .setSubtaskIndex(subtaskId)
                        .setParallelism(parallelism)
                        .setMaxParallelism(parallelism)
                        .setJobID(jobID)
                        .setExecutionConfig(new ExecutionConfig().enableObjectReuse())
                        .build();

        final OneInputStreamOperatorTestHarness<String, CommittableMessage<String>> testHarness =
                new OneInputStreamOperatorTestHarness<>(
                        new SinkWriterOperatorFactory<>(sink), typeSerializer, environment);
        testHarness.open();

        assertContextsEqual(initContext.get(), originalContext.get());

        testHarness.close();
    }

    private static void assertContextsEqual(Sink.InitContext initContext, WriterInitContext original) {
        assertThat(initContext.getUserCodeClassLoader().asClassLoader()).isEqualTo(original.getUserCodeClassLoader().asClassLoader());
        assertThat(initContext.getMailboxExecutor()).isEqualTo(original.getMailboxExecutor());
        assertThat(initContext.getProcessingTimeService()).isEqualTo(original.getProcessingTimeService());
        assertThat(initContext.getTaskInfo().getIndexOfThisSubtask()).isEqualTo(original.getTaskInfo().getIndexOfThisSubtask());
        assertThat(initContext.getTaskInfo().getNumberOfParallelSubtasks())
                .isEqualTo(original.getTaskInfo().getNumberOfParallelSubtasks());
        assertThat(initContext.getTaskInfo().getAttemptNumber()).isEqualTo(original.getTaskInfo().getAttemptNumber());
        assertThat(initContext.metricGroup()).isEqualTo(original.metricGroup());
        assertThat(initContext.getRestoredCheckpointId()).isEqualTo(original.getRestoredCheckpointId());
        assertThat(initContext.isObjectReuseEnabled()).isEqualTo(original.isObjectReuseEnabled());
        assertThat(initContext.createInputSerializer()).isEqualTo(original.createInputSerializer());
        assertThat(initContext.getJobInfo().getJobId()).isEqualTo(original.getJobInfo().getJobId());
        assertThat(initContext.metadataConsumer()).isEqualTo(original.metadataConsumer());
    }
```

**Comment by Jiabao-Sun** [comment]
Thanks @pvary for the review. 
Please take a look again.

**Review by pvary — APPROVED** [review]
LGTM +1 pending tests.

Thanks for the catch and the fix @Jiabao-Sun!

**Comment by MartijnVisser** [comment]
> could you rebase the master and rerun the ci?

I've at least rebased this PR and triggered a local run on https://dev.azure.com/martijn0323/Flink/_build/results?buildId=4190&view=results and https://github.com/MartijnVisser/flink/actions/runs/7801927451

**Comment by lincoln-lil** [comment]
I checked https://issues.apache.org/jira/browse/FLINK-34007 and there's a same failure stack before the final fix merged
https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=57270&view=logs&j=bbb1e2a2-a43c-55c8-fb48-5cfe7a8a0ca6&t=a69a379d-ca44-5937-4e62-0ce084a23679&l=7935

**Comment by XComp** [comment]
Your conclusion is correct. The error in the [CI run](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=57346&view=logs&j=bea52777-eaf8-5663-8482-18fbc3630e81&t=43ba8ce7-ebbf-57cd-9163-444305d74117&l=8405) is due to a out-dated branch base. A more recent version of `master` that includes https://github.com/apache/flink/commit/79cccd7103a304bfa07104dcafd1f65a032c88ce (which is needed for the resolution of FLINK-34007) would fix the issue. :+1:

**Comment by Jiabao-Sun** [comment]
Sorry for the late response, shall I rebase the master and rerun the CI?

**Comment by MartijnVisser** [comment]
> Sorry for the late response, shall I rebase the master and rerun the CI?

Yes, that would be great!

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Review by MartijnVisser — APPROVED** [review]
I have a succesful CI run in https://dev.azure.com/martijn0323/Flink/_build/results?buildId=4190&view=results of this PR; the failure at https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=57349&view=logs&j=fc5181b0-e452-5c8f-68de-1097947f6483&t=995c650b-6573-581c-9ce6-7ad4cc038461&l=8982 seems a network issue, not so much this test.  Both CI runs passed the `test_ci_build core` phase which is where these tests are run. I'm going to merge this. Thanks @Jiabao-Sun @pvary

**Pull request merged**
