### PR TITLE
[FLINK-19491][avro] AvroSerializerSnapshot cannot handle large schema

### PR DESCRIPTION
**Pull request by SteNicholas**
## What is the purpose of the change

*Currently Flink can only handle schemas up to a size of 65535 bytes, and `AvroSerializerSnapshot` cannot handle large schema. If size of schame exceed 65535 bytes, the `UTFDataFormatException` could be thrown. `AvroSerializerSnapshot` should introduce a V3 that uses `StringValue.writeString()` and `StringValue.readString()` to handle the string encoding.*

## Brief change log

  - *`AvroSerializerSnapshot` introduces a V3 that uses `StringValue.writeString()` in `writeSnapshot()` and `StringValue.readString()` in `readSnapshot()`.*

## Verifying this change

  - *`AvroSerializerSnapshotTest` adds the test method `largeSchemaWithExceedV2ThresholdSizeShouldResultInCompatibleV3Serializer` to verify the test case whether the large schema which exceeds a threshold size of 65535 bytes is compatible with the new version 3 of `AvroSerializerSnapshot`.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by SteNicholas** [comment]
@AHeise , could you please help to review this pull request if you are available?

**Comment by StephanEwen** [comment]
Thanks for taking a look at this.

The feature code is fine, but I think the tests need some improvements.

  - This misses adding a V2 config snapshot to the test resources and ensuring we can resume from there.

  - The test for large schema re-engineers the V2 method in the tests.
      - This is not necessary. We don't care whether the previous version fails, we only want the new version to succeed
      - Rebuilding functionality in tests and testing that does not help tp guard anything in the production code, so it is ineffective.

**Comment by SteNicholas** [comment]
> Thanks for taking a look at this.
> 
> The feature code is fine, but I think the tests need some improvements.
> 
> * This misses adding a V2 config snapshot to the test resources and ensuring we can resume from there.
> * The test for large schema re-engineers the V2 method in the tests.
>   
>   * This is not necessary. We don't care whether the previous version fails, we only want the new version to succeed
>   * Rebuilding functionality in tests and testing that does not help tp guard anything in the production code, so it is ineffective.

@StephanEwen , thanks for your detailed review. I have followed up your comments about the improvements of tests. Please review again if you are available.

**Comment by StephanEwen** [comment]
I think we need to clarify what actually needs to be done first.

This PR changes some shared versioning scheme of the snapshot metadata framework (in `flink-core`), which It also removes previous serializer snaphot test data.

**Comment by SteNicholas** [comment]
> ome shared versioning scheme of the snapshot metadata framework (in `flink-core`), which It also removes previous serializer snaphot test data.

I used the latest version of serializer snaphot to generate serializer snaphot test data, which previously used the version 2.

**Comment by aljoscha** [comment]
I pushed some changes to your branch, I hope that's ok:
 - I added one prerequisite commit that adds testing infra for testing past serializer snapshots. I also created a snapshot with v2 before bumping the version
- then the second commit (from @SteNicholas) just needs to do the changes and the existing test verifies that we can still restore
- when we bump the version the next time we would again have to create a snapshot before

Strictly speaking, we wouldn't have to test restoring from old versions here because that's covered by `AvroSerializerUpgradeTest` but it's good to be extra sure and `AvroSerializerUpgradeTest` is a bit coarse grained because we only create new snapshots per Flink version and not every time we bump a serializer snapshot version.

cc @StephanEwen

**Comment by SteNicholas** [comment]
@aljoscha I have pushed one commit to exclude the serializer snapshot from license. Please help to review this pull request again.

**Comment by SteNicholas** [comment]
> I pushed some changes to your branch, I hope that's ok:
> 
> * I added one prerequisite commit that adds testing infra for testing past serializer snapshots. I also created a snapshot with v2 before bumping the version
> * then the second commit (from @SteNicholas) just needs to do the changes and the existing test verifies that we can still restore
> * when we bump the version the next time we would again have to create a snapshot before
> 
> Strictly speaking, we wouldn't have to test restoring from old versions here because that's covered by `AvroSerializerUpgradeTest` but it's good to be extra sure and `AvroSerializerUpgradeTest` is a bit coarse grained because we only create new snapshots per Flink version and not every time we bump a serializer snapshot version.
> 
> cc @StephanEwen

@aljoscha I have pushed one commit to exclude the serializer snapshot from license. Please help to review this pull request again.

**Review by aljoscha — APPROVED** [review]
Looks good now!

**Comment by aljoscha** [comment]
Merged!

**Pull request closed without merging**
