### PR TITLE
[FLINK-21407][docs][formats] Remove MongoDb connector as it is not supported in DataStream API. Port to release 1.14

### PR DESCRIPTION
**Pull request by echauchot**
port of [this PR](https://github.com/apache/flink/pull/18284) to release 1.14

### CODE REVIEW

**Review by MartijnVisser — APPROVED** [review]
Awesome, thanks for fixing this to. @fapaul please merge this one too.

**Comment by fapaul** [comment]
@MartijnVisser @echauchot It would be great to know what this PR is supposed to do and read some background information in the PR description. I cannot really understand the change just reading the JIRA.

**Comment by echauchot** [comment]
@fapaul sorry, the discussion was left in the [ticket](https://issues.apache.org/jira/browse/FLINK-21407). 
The aim of the PR is to fix a doc issue where `MongoDb` was incorrectly put in connectors section in place of formats section.
Updating the PR description.

**Comment by echauchot** [comment]
I just ported the [PR for master](https://github.com/apache/flink/pull/18284) here. @MartijnVisser @fapaul PTAL

**Review by MartijnVisser — APPROVED** [review]
Thanks for this @echauchot - LGTM

@fapaul can you merge it?

**Comment by echauchot** [comment]
ping @fapaul

**Comment by echauchot** [comment]
@fapaul thanks for merging !

**Pull request merged**
