### PR TITLE
[FLINK-27986] Refactor the name of finish method for JdbcOutputFormatBuilder

### PR DESCRIPTION
**Pull request by xleoken**
## What is the purpose of the change

It's better use `build` in builder class.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by knaufk — COMMENTED** [review]
Since this API is only @Experimental, I think, we could make this change. "build" is indeed much more common (also within Flink AFAIK) then "finish". 

@fapaul what do you think?

**Comment by fapaul** [comment]
I agree, renaming it to "build" definitely aligns it with other parts of the codebase but I would prefer to make this change part of a ticket and not a hotfix because it affects the API and it should be part of the release notes.

**Comment by leo65535** [comment]
Thanks for your review @fapaul @knaufk, updated the patch that make the `finish` deprecated, and add `build` method.

**Comment by knaufk** [comment]
@leo65535 I am sorry this PR stalled for so long. Could you indeed create a brief ticket for this in the Apache Flink Jira and refer the the ticket in the commit? I will merge it then for Flink 1.16.

**Comment by leo65535** [comment]
Welcome @knaufk, done.

**Pull request closed without merging**
