### PR TITLE
[FLINK-7541] Refactor StateAssignmentOperation

### PR DESCRIPTION
**Pull request by pnowojski**
This PR is a pure refactor and shouldn't change any functionality. It should be covered by existing tests like `CheckpointCoordinatorTest`

### CODE REVIEW

**Comment by pnowojski** [comment]
@StefanRRichter please take a look

**Comment by StefanRRichter** [comment]
Merged in f1b2b83d63. Please close the PR and the JIRA.

**Comment by tillrohrmann** [comment]
Please don't close this PR, because the commit was reverted. Using `Multimap#get` in the `StateAssignmentOperation` makes the `OperatorSubtaskState` not serializable. The `WindowCheckpointingITCase` caught the problem.

**Comment by pnowojski** [comment]
Sorry @tillrohrmann I have missed that :(

@StefanRRichter I pushed a fixed version (but lets wait for travis to pass)

**Comment by StefanRRichter** [comment]
Yes, I also missed it between some unrelated Kafka test failures :-( Will do a second attempt if all is green this time.

**Comment by pnowojski** [comment]
Surprisingly even kafka tests have passed this time oO

**Comment by StefanRRichter** [comment]
Alright, second attempt to merge this.

**Pull request closed without merging**
