### PR TITLE
[FLINK-33356][docs] Fix the messed navigation bar on Flink’s official website

### PR DESCRIPTION
**Pull request by WencongLiu**
## What is the purpose of the change

*Fix the messed navigation bar on Flink’s official website.*

## Brief change log

  - *Fix the messed navigation bar on Flink’s official website.*

Currently, the website returns to normal.

image

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (no)

### CODE REVIEW

**Comment by JunRuiLee** [comment]
@WencongLiu Could you please attach a screenshot to show what the modified page looks like?

**Comment by WencongLiu** [comment]
> @WencongLiu Could you please attach a screenshot to show what the modified page looks like?

Done. I've attached a screenshot. Thanks for reminding me! 🙏 @JunRuiLee

**Review by JunRuiLee — APPROVED** [review]
LGTM

**Review by wanglijie95 — APPROVED** [review]
LGTM, thanks @WencongLiu

**Pull request merged**
