### PR TITLE
[docs] Add clickable stack figure on overview page

### PR DESCRIPTION
**Pull request by uce**
This commit adds a figure giving an overview of Flink's stack. Users can click on components to go to the respective component docs.

screen shot 2015-04-09 at 15 02 39

I'm sure there will be people who vote for other colors etc. Please only provide comments with concrete suggestions on what to change. ;)

This is only for 0.9-SNAPSHOT. Do we want another version for 0.8 w/o Gelly, ML, Table, and, Tez?

### CODE REVIEW

**Comment by rmetzger** [comment]
Nice work, thank you.
I think its fine to add this only to 0.9.

**Comment by StephanEwen** [comment]
I think it is great as it is.

+1 to add!

**Comment by mxm** [comment]
This is awesome. Should be in 0.9! I think it's an attraction to drive users to a newer release when they check out the documentation on the website.

**Comment by uce** [comment]
Thanks. Merging this.

**Comment by mbalassi** [comment]
Thanks, great work:
I'd like to ask for the following renamings in the figure:
  * Optimizer -> Batch Optimizer
  * Stream Builder -> Streaming Optimizer

**Comment by ktzoumas** [comment]
+1, looks great

**Pull request closed without merging**
