### PR TITLE
[FLINK-6414] [build] Use scala.binary.version in place of change-scala-version.sh

### PR DESCRIPTION
**Pull request by greghogan**
Use scala.binary.version as defined in the parent POM and remove the script to swap scala version identifiers.

### CODE REVIEW

**Comment by StephanEwen** [comment]
I remember initially this did not work, because the variables where not properly resolved.
It probably works now, because we force the shade plugin to be evaluated in each project (via the `force-shading` dependency). The shade plugin has the nice side effect of resolving variables.

The thing we should be aware of here is that by going with this change, we must keep the `force-shading` hack. In some sense this PR brings the "force-shading" approach to conclusion.

I remember that there was an alternate suggestion initially to not do the force-shading and rather have a more elaborate `change-scala-version.sh` script instead. 
Just bringing this up so we are aware of the context/implications. I am okay with either approach.

@rmetzger What is you take here?

**Comment by StephanEwen** [comment]
Thinking more about this, I am +1 to the approach here.
Seems easier to maintain, compared to having a complicated script.

**Comment by StephanEwen** [comment]
Merging this for 1.4

**Comment by greghogan** [comment]
@StephanEwen does the recent discussion on packaging shaded dependencies mean that `force-shading` will go away? Or do we keep that even if dependencies are no longer being shaded? Or will only some shaded dependencies (the most problematic) be provided?

**Comment by StephanEwen** [comment]
@greghogan I think we should keep the `force-shading` approach to have every project pass through the shade plugin, for various reasons. Resolving variables (as required here) is one of them, but filtering of configuration files, signature files, etc. are also very good reasons. Also, there may be "single use" shaded dependencies in non-scala projects, which could still be shaded on the fly in the using project directly (netty in flink-runtime would be such a case).

**Comment by rmetzger** [comment]
I think it should be fine to merge this (for 1.4 only please :)). The problem was that in some fields the variable substitution did not work. Maven was still able to resolve it, but sbt was failing to retrieve the dependencies.

**Comment by StephanEwen** [comment]
@rmetzger I have tried to put this into 1.3 as well - seems to work...

**Pull request closed without merging**
