### PR TITLE
[FLINK-35988][table]Reduce the number of state queries in the AppendOnlyFirstNFunction

### PR DESCRIPTION
**Pull request by lexluo09**
## What is the purpose of the change

*Reduce one state query in the AppendOnlyFirstNFunction and optimize the processing performance for large states.*

## Brief change log

  - *Query the state only once.*
  - *Change "currentRank += 1" to "currentRank++".*

## Verifying this change
This change is already covered by existing tests, such as *AppendOnlyFirstNFunctionTest*.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by lexluo09** [comment]
run azure

**Comment by wuchong** [comment]
@flinkbot run azure

**Comment by wuchong** [comment]
@flinkbot run azure

**Comment by lincoln-lil** [comment]
@lexluo09 could you rebase the latest master to see if the ci can pass?

**Comment by lexluo09** [comment]
Thank you, I have already performed the rebase.



> @lexluo09 could you rebase the latest master to see if the ci can pass?
Thank you, I have already performed the rebase.

**Comment by lincoln-lil** [comment]
@flinkbot run azure

**Review by lincoln-lil — APPROVED** [review]

**Pull request merged**
