### PR TITLE
[FLINK-2615]Preserve executors for the entire run of program.

### PR DESCRIPTION
**Pull request by sachingoel0101**
1. Prevents re-starts of local cluster several times on multiple executions.
2. Preserves the executor states for the entire run of the program.

### CODE REVIEW

**Comment by StephanEwen** [comment]
The current behavior is actually desired. You can explicitly start the local executor, and explicitly stop it. When you did not explicitly start it, you get an auto-shut down executor. This is quite flexible, no?

The LocalExecutionEnvironment is a local one-time environment. There is code to extend it to sessions, which is really what we want to "keep context and data around".

For that, there is part of the work here: https://github.com/apache/flink/pull/858
It follows a very principled approach, where the responsibility of deciding clearing / disposal of cached context and data is bound to a session. Sessions have timeouts and scope reapers, and are managed by the execution environments, not the executors.

**Comment by sachingoel0101** [comment]
Aha. I just had a brief look at the PR. 
I had initially thought of implementing a start and stop method in the `ExecutionEnvironment` but decided against it, since it changes the api for very minor changes.
Session management is a way better solution. Any timeline on when those changes could get merged?

**Comment by uce** [comment]
I would move the discussion to the respective PR. Sachin, could you close this PR?

**Comment by sachingoel0101** [comment]
Sure.

**Pull request closed without merging**
