### PR TITLE
[FLINK-6934] [util] remove unused LRUCache class

### PR DESCRIPTION
**Pull request by zhangminglei**
Remove unused ```LRUCache``` class since it was created in 2014.

### CODE REVIEW

**Comment by aljoscha** [comment]
Thanks for working on this! While on it, could you also remove `LRUCacheMap` and `LRUCacheMapTest`? I think these are similarly unused.

**Comment by zhangminglei** [comment]
Sure, Thanks, I had seen those before. ```LRUCacheMap``` and ```LRUCacheMapTest``` will be removed in this PR soon.

**Comment by zhangminglei** [comment]
Hello, @aljoscha PR had been updated. Please helps check it again, thanks!

**Comment by aljoscha** [comment]
Thanks! I merged 😃 

Could you please close this PR?

**Pull request closed without merging**
