### PR TITLE
[FLINK-33128] Add converter.open() method call on TestValuesRuntimeFunctions

### PR DESCRIPTION
**Pull request by jgagnon1**
## What is the purpose of the change

Make sure complex type such as `Array<Row<>>` get converted property in TestValues connector when doing lookup joins.

## Brief change log

- Added a call to concerter.open() on TestValuesRuntimeFunctions (sync and sync)

## Verifying this change

This change added tests and can be verified as follows:

- Added integration tests for lookup join with Array<Row<>> on lookup table.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by rlupiichuk — APPROVED** [review]

**Comment by jgagnon1** [comment]
@flinkbot run azure

**Comment by jgagnon1** [comment]
@flinkbot run azure

**Review by xccui — APPROVED** [review]
Thanks for the fix!

**Comment by gaoyunhaii** [comment]
@flinkbot run azure

**Review by gaoyunhaii — APPROVED** [review]

**Pull request closed without merging**
