### PR TITLE
minor document fix.

### PR DESCRIPTION
**Pull request by jaoki**
Regarding example WordCount class name.

### CODE REVIEW

**Comment by mjsax** [comment]
Any news here, @jaoki ?

**Comment by jaoki** [comment]
@mjsax thank you for paying attention for such a trivial topic :) Will fix it shortly.

**Comment by jaoki** [comment]
@mjsax The build failure seems irrelevant from my small contribution.

**Comment by mjsax** [comment]
+1 for merging.

**Comment by mjsax** [comment]
Merging this...

**Comment by mjsax** [comment]
Thanks for your contribution!

**Pull request closed without merging**
