### PR TITLE
[FLINK-3426] Fixed JobManagerLeader[Re]ElectionTest.testleaderElectio…

### PR DESCRIPTION
**Pull request by zentol**
…n onWindows

### CODE REVIEW

**Comment by StephanEwen** [comment]
Are we sure that this always only uses local file systems? This change would break HDFS or S3 URIs.

**Comment by zentol** [comment]
how about ``` new Path(basePath).toUri()``` instead of ```new File(basePath)toUri()```?

**Comment by tillrohrmann** [comment]
I agree with @StephanEwen that we cannot be sure that the user does not choose a different filesystem than the local one. Thus, I guess replacing `File(basePath).toURI` by `Path(basePath).toUri` is a good idea. 

Have you tested your changes with different `basePath` types @zentol?

**Comment by zentol** [comment]
I've only tried it with local paths.

**Comment by tillrohrmann** [comment]
Alright, thanks for the update @zentol. I'll test the changes with HDFS and if they pass, I'll merge it.

**Comment by tillrohrmann** [comment]
Worked with Hadoop 2.7.1.

**Pull request closed without merging**
