### PR TITLE
[hotfix][build system] Do not trigger dependent jobs if predecessor fails

### PR DESCRIPTION
**Pull request by rmetzger**
Trivial change

### CODE REVIEW

**Comment by rmetzger** [comment]
Good idea! I updated the PR.

**Comment by rmetzger** [comment]
@zentol: looks like there's a bug in CI bot. it says "success" for Azure, even though the build failed. Maybe it is picking up the status of a "subtask" instead of the whole job?

Despite that, are you ok to merge this PR (it would help reducing the load on the CI system)?

**Comment by zentol** [comment]
The CiBot issue should be fixed.

**Comment by rmetzger** [comment]
Thanks a lot!

**Pull request merged**
