### PR TITLE
[FLINK-13845][docs] Drop all the content of removed Checkpointed interface

### PR DESCRIPTION
**Pull request by Myasuka**
## What is the purpose of the change

Drop all the content of removed `Checkpointed` interface.

## Verifying this change

This change is a trivial rework without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): **no**
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: **no**
  - The serializers: **no**
  - The runtime per-record code paths (performance sensitive): **no**
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: **no**
  - The S3 file system connector: **no**

## Documentation

  - Does this pull request introduce a new feature? **no**
  - If yes, how is the feature documented? **not applicable**

### CODE REVIEW

**Comment by Myasuka** [comment]
Previously, I also plan to remove the content of `Checkpointed` interface from web documentation but I think remaining them in the migration doc from Flink-1.1 should be okay.

@flinkbot attention @aljoscha

**Comment by Myasuka** [comment]
@flinkbot run travis

**Comment by Myasuka** [comment]
It seems command `run travis` not taking effect @zentol .

To rerun the CI, I have to close-reopen this PR.

**Comment by StephanEwen** [comment]
This looks good, merging...

**Pull request closed without merging**
