### PR TITLE
[FLINK-7123] [cep] Support timesOrMore in CEP

### PR DESCRIPTION
**Pull request by dianfu**
## What is the purpose of the change

*This pull request adds timesOrMore to CEP pattern API*

## Verifying this change

This change added tests and can be verified as follows:

  - *Added test in TimesOrMoreITCase*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: ( no)

## Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (docs)

### CODE REVIEW

**Comment by dianfu** [comment]
@dawidwys @kl0u Could you help to take a look at this PR? Thanks a lot.

**Comment by kl0u** [comment]
@dianfu I will have a look tomorrow! Thanks for the work btw ;)

**Comment by dianfu** [comment]
@kl0u That's OK. Thanks a lot. :)

**Comment by kl0u** [comment]
LGTM, merging this

**Pull request closed without merging**
