### PR TITLE
[FLINK-10170] [table] Support string representation for map and array types in descriptor-based Table API

### PR DESCRIPTION
**Pull request by tragicjun**
## What is the purpose of the change

Since 1.6 the recommended way of creating source/sink table is using connector/format/schema/ descriptors. However, when declaring map types in the schema descriptor, the following exception would be thrown:

> org.apache.flink.table.api.TableException: A string representation for map types is not supported yet.

This pull request is to add string representation support for map types.

## Brief change log

- Add new `Keyword` and `PackratParser` for map types in TypeStringUtils
- Add normalization logic for map types in `TypeStringUtils.writeTypeInfo()`
- Update relevant unit tests in `TypeStringUtilsTest` and `TableDescriptorTest`

## Verifying this change

This change can be verified  covered by updated unit tests, such as *TypeStringUtilsTest* and *TableDescriptorTest*.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by buptljy** [comment]
@tragicjun +1, this is good, but can you implement the same thing on other types like array? I think they should be in one PR.

**Comment by tragicjun** [comment]
@twalthr In the latest commit, I've replaced bracket **()** with **<>** for all complex types and updated the documentation. To ensure backward compatibility, bracket **()** is still supported by the parsers. Please let me know if anything else is missing.

**Comment by tragicjun** [comment]
Thanks for reminding @buptljy. Array types is a bit more complex than map types. Actually I've already implemented a version on my local branch. But it introduces some implementation tricks, which I thought it would be better to open another issue to discuss. Could you give your suggestions @twalthr?

**Comment by tragicjun** [comment]
@twalthr could you review this again? Anything else I should do before the merge, thanks.

**Comment by tragicjun** [comment]
@buptljy In the latest commit, the array types are supported as well, please check it out.

**Comment by buptljy** [comment]
lgtm.

**Comment by tragicjun** [comment]
Ready to be merged, could you take a look @fhueske @twalthr ?

**Comment by twalthr** [comment]
Thank you @tragicjun. The changes look good to me. I will take care of merging this...

**Pull request closed without merging**
