### PR TITLE
[FLINK-18191] Rename jobmanager.memory.* configuration options into master.memory.*

### PR DESCRIPTION
**Pull request by tillrohrmann**
This commit renames the `jobmanager.memory.*` config options into `master.memory.*` to
align it better with the overall Flink terminology.

cc @zentol.

### CODE REVIEW

**Comment by tillrohrmann** [comment]
Thanks for the quick review @zentol. Unfortunately, there is currently a discussion about renaming the "Flink Master" back into the "JobManager" again. Until this discussion is resolved, we need to put this effort on halt, unfortunately.

**Comment by zentol** [comment]
@tillrohrmann Where is this discussion? I only saw one comment by @aljoscha in FLINK-18209.

**Comment by aljoscha** [comment]
https://lists.apache.org/thread.html/red9d18f7173d53d016f6826410841b2726b9293ceefaea2de0cdeafb%40%3Cdev.flink.apache.org%3E

**Comment by tillrohrmann** [comment]
Closing this PR since it seems to be no longer relevant.

**Pull request closed without merging**
