### PR TITLE
[FLINK-3504] Fix join translation. Equality predicates may only reference fields

### PR DESCRIPTION
**Pull request by fhueske**
Adapts the join translation rule such that only joins with proper equality join predicates are translated.
A proper equality join predicate does only references fields, i.e., it does not reference expressions.

Joins without at least one proper equality join predicates or with an equality join predicate which references an expression are not translated.

### CODE REVIEW

**Comment by vasia** [comment]
Looks good, thanks!
Just one thing. If the `FlinkJoinRule`  doesn't match, could we throw some meaningful exception, e.g. "Join equality predicates should refer to fields only"? Otherwise, the program fails with an ugly `CannotPlanException` and a non-informative message.

**Comment by fhueske** [comment]
Returning `false` does not imply that no plan can be found. It just means that this branch of the plan space cannot be translated, but other rules such as the rule for extracting expressions out of join conditions can lead to branches that result in valid plans. 

So we should not throw an exception in this rule (in fact in no rule). However, we can catch the exception when Calcite did not find a plan and return a more meaningful exception there.

**Comment by fhueske** [comment]
I added a commit to catch Calcite's planner exception and extend the error message.

**Comment by vasia** [comment]
looks good, thanks!

**Comment by vasia** [comment]
Merging this one too!

**Comment by vasia** [comment]
You can close this one too @fhueske.

**Comment by fhueske** [comment]
Thanks!

**Pull request closed without merging**
