### PR TITLE
[FLINK-21407][doc][formats] Add formats to DataStream connectors doc

### PR DESCRIPTION
**Pull request by echauchot**
This PR is the port of [this PR](https://github.com/apache/flink/pull/17523) for 1.14 without the DataSet API changes

### CODE REVIEW

**Comment by echauchot** [comment]
R: @AHeise as discussed slightly_smiling_face

**Comment by AHeise** [comment]
@flinkbot run azure

**Comment by echauchot** [comment]
unrelated failures, relaunching

**Comment by echauchot** [comment]
@flinkbot run azure

**Comment by echauchot** [comment]
I will port [this PR](https://github.com/apache/flink/pull/17640) once the review is finished to 1.14 branch

**Pull request closed without merging**
