### PR TITLE
[FLINK-21903][docs-zh] Translate "Importing Flink into an IDE" page into Chinese

### PR DESCRIPTION
**Pull request by xinggit**
## What is the purpose of the change

The page url is https://ci.apache.org/projects/flink/flink-docs-release-1.12/zh/flinkDev/ide_setup.html
The markdown file is located in 'docs/content.zh/docs/flinkDev/ide_setup.md' now.

The doc is still in English on the master branch.So translate "Importing Flink into an IDE" page into Chinese

## Brief change log

translate 'docs/content.zh/docs/flinkDev/ide_setup.md' file

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? no

### CODE REVIEW

**Comment by xinggit** [comment]
cc @wuchong.  could you help to review this? thanks

**Comment by xinggit** [comment]
cc @wuchong @xccui @klion26 . could you help to review this? thanks

**Comment by xinggit** [comment]
cc @wuchong Excuse me. I have resolved two conflicts for this merge request, please Could you help me review it as soon as possible, and then give me some comments

**Comment by wuchong** [comment]
Thanks @xinggit for the contribution, the translation looks good to me. 

However, please DO NOT use `git merge` to fix conflicts, otherwise, comitters need to resolve the conflicts when rebasing your branch. Please use `git rebase` to rebase your branch to latest master and fix conflicts. IntelliJ IDEA also provide an easy tool to do git rebase, you can find the tool via `VCS -> Git -> Rebase`.

**Comment by xinggit** [comment]
Thank you very much for your review and suggestion, but I'm sorry that I made a mistake and added a lot of commits.
I will open a new PR for the merge request

**Pull request closed without merging**
