### PR TITLE
[FLINK-6217] ContaineredTaskManagerParameters sets off-heap memory size incorrectly

### PR DESCRIPTION
**Pull request by haohui**

### CODE REVIEW

**Comment by haohui** [comment]
The failed tests are being addressed in FLINK-6175.

**Comment by haohui** [comment]
The test failure seems unrelated. Cannot reproduce locally.

**Comment by StephanEwen** [comment]
Good fix, thanks @haohui 

I was wondering - I am a trying to advocate fewer dependencies in Flink (there is always the problem of shading and conflicts) so if there is a way to do this without Guava, that'd be great. I think `commons-lang3` has a joiner as well, or we might just add a joiner to Flink...

**Comment by haohui** [comment]
Totally Agree :-) @StephanEwen please take another look.

**Comment by StephanEwen** [comment]
+1 to merge this

**Comment by tillrohrmann** [comment]
Thanks for your contribution @haohui and the review @StephanEwen. Changes look good to me. Merging this PR.

**Pull request closed without merging**
