### PR TITLE
[FLINK-2751] [Documentation] Add quickstart menu to the navigation bar

### PR DESCRIPTION
**Pull request by rerngvit**
Add quickstart menu to the navigation bar for Flink documentation

### CODE REVIEW

**Comment by chiwanpark** [comment]
Hi @rerngvit, Thanks for sending pull request. But your pull request has some problems.

First, `{{ quickstart }}` is not defined in your changes. As you can see in 19-22 lines of `navbar.html`, you should define `{{ quickstart }}`.

Second, there is no conditional `active` class for quickstart dropdown menu. Please include conditional `active` class in quickstart dropdown menu. Conditional `active` classes for other menus are in line 55 of `navbar.html`.

**Comment by rerngvit** [comment]
@chiwanpark Thanks for reviewing this issue. I modified the pull request according to your comments. Please have a look.

**Comment by chiwanpark** [comment]
Hi @rerngvit, I have tested your pull request.

Because `setup_quickstart.html` contains "setup" keyword in url, there are two active menus (Quickstart, Setup) when we open Quickstart: Setup page. I found a solution like following:

```html
<li class="dropdown{% if page.url contains '/quickstart/' %} active{% endif %}">
```

The solution must be applied not only quickstart but also other dropdown menus such as setup, programming guide, ..., etc..

BTW, there is a typo line 68 of `navbar.html`. A tag must be closed. I know this is not related your changes but fixing it would be better.

After addressing this, we can merge this pull request. :-)

**Comment by rerngvit** [comment]
@chiwanpark Thanks for reviewing this issue. I modified the pull request according to your comments.

**Comment by chiwanpark** [comment]
Looks good to merge. I'll merge this.

**Comment by mxm** [comment]
Looks good. Thanks for the contribution @rerngvit!

**Pull request closed without merging**
