### PR TITLE
[FLINK-24558][API/DataStream]make parent ClassLoader variable which c…

### PR DESCRIPTION
**Pull request by baisui1981**
…reate by ClassLoaderFactory ,relevant issue https://issues.apache.org/jira/projects/FLINK/issues/FLINK-24558

## What is the purpose of the change

 make server side classLoader which create by BloblibraryCacheManager.DefaultClassLoaderFactory pluggable in able to make the parent classloader of  ChildFirstClassLoader variable

## Brief change log

  - add a new interface `ClassLoaderFactoryBuilder` which can be extensible by user，the instance of `ClassLoaderFactoryBuilder` is instantiable by ServiceLoader 
  - add loading phase in `DefaultClassLoaderFactory` , if a customize `ClassLoaderFactoryBuilder` instance can be loaded by ServiceLoader ,then the class loading applies will delegate to it.  
 

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by tisonkun** [comment]
@baisui1981 checkstyle failed. You can run `mvn spotless:apply` to fix it.

**Comment by baisui1981** [comment]
> checkstyle failed. You can run `mvn spotless:apply` to fix it.

i have fix it

**Comment by baisui1981** [comment]
> But the user-jar is the same for all tasks. You can't use a manifest in said jar for differentiating which classes should now be loaded / made accessible. You either a) need the CL factory to create a task-specific classloader (which you can't because jars are the same and CLs are shared) or b) need the cooperation from the user-code to load classes in a specific way.

@zentol Please forgive me for my negligence, I didn’t explain the process clearly. 
Before submit the job to Flink cluster, will package a jar dynamically, at then,the metadata info for the manifest which is relevant to the job will be put in the jar togother:

code as below [FlinkTaskNodeController.java](https://github.com/qlangtech/plugins/blob/864f5bf01fad567fbc09a217f4bbf17c95910f94/tis-incr/tis-realtime-flink/src/main/java/com/qlangtech/plugins/incr/flink/launch/FlinkTaskNodeController.java#L129)
``` java
Manifest manifest = new Manifest();
Map<String, Attributes> entries = manifest.getEntries();
Attributes attrs = new Attributes();
attrs.put(new Attributes.Name(collection.getName()), String.valueOf(timestamp));
 // put Flink job name
entries.put(TISFlinkCDCStart.TIS_APP_NAME, attrs);
```
                                                                                                          
when submit to the server side, in my customized extend point implementation method [ClassLoaderFactoryBuilder.buildServerLoaderFactory](https://github.com/qlangtech/plugins/blob/864f5bf01fad567fbc09a217f4bbf17c95910f94/tis-incr/tis-flink-extends/src/main/java/com/qlangtech/plugins/incr/flink/TISFlinClassLoaderFactory.java#L101),will extract the param from the submitted jar manifest, at then pull the plugin bundles  from TIS plugin repository with http protocol, and initialize the PluginManager which is responsible for load class .

**Comment by baisui1981** [comment]
@zentol @AHeise Thanks to both of you, have already understood me and have understood what I want to express, 
We want to build a product similar to [Jenkins](https://www.jenkins.io/) in the field of bigData, We will  package various functions as Plugin as [Jenkins Plugin](https://plugins.jenkins.io/) and put it in the repository in advance.

dirive by this mission, The **ISSUE** mentioned above was found in the process of building this product, Because building a Flink Job which is drived by user defined DSL in a production  environment and submitting it is **fully automated**, if problems such as dependency conflicts between connectors are found in the process, they cannot be solved by manual intervention, so they just can be solved by facility of CL isolation. One of the ways I thought of this kind of problem.

For FLink, only a new extension point is added, which has no effect on the existing functions of flink. For the OCP principle, I think this is a good way to implement it. And that will Added a new implementation option for users like me

**Comment by AHeise** [comment]
Sorry for coming back so late: I still don't quite understand how the flow is supposed to look like.

Let's say I have a user.jar that through DSL depends on flink-kafka and flink-kinesis, both of them use incompatible guava. Now with your approach, the same user.jar is loaded through 2 classloaders to access kafka and kinesis. Did I get that right?

What I fail to understand is how the incompatible version of Guava are put into the user.jar. If I just shade without relocation then one Guava version simply wins by overwriting the files. So you need to relocate Guava into kafka.guava and kinesis.guava. But at that point, I don't see the need for separate CL anymore.

So I'm missing a piece of information here.

**Comment by baisui1981** [comment]
thanks @AHeise for your reply, Sorry, I have not explained a detail before。For better illustration, I drew a diagram as  below:
[http://qlangtech.oss-us-west-1.aliyuncs.com/Flink%20ClassLoader.png](http://qlangtech.oss-us-west-1.aliyuncs.com/Flink%20ClassLoader.png)


There is a prerequisite for the processing flow. We need to build a plug-in repository based on the http protocol. The user needs to deploy the plugin to the warehouse in advance

there are four steps in the process:
1. build two classloader which is respect to the plugin bundle name  ‘ kafka’ and ‘ kinesis’ . specially the jars relevant to the plugin is store in the remote plugin-warehouse. the gava with different version as you have mentioned will be loaded separately in different URLClassloader，So there will be no class conflict  
2. compile the client side code and make a package which is named as 'user.jar' and submit to `Flink Cluster`. the 'user.jar' is compose of two component, one is classes and another is plugin meta such as 'kafka' and 'kinesis' is stored in the `jar manifest`
3. when flink server side received client apply , create instance of `TISClientFirstClassLoader`  which is extended from `FlinkUserCodeClassLoader`, and  this instance is response for loading class which is relevant to the plugin bundle of 'kafka'  and 'kinesis'.  In the `TISClientFirstClassLoader` will build a classloader array from 'kafka' and 'kinesis' which is parsed from `user.jar` manifest, code as below:
   ``` java
   public TISClientFirstClassLoader(String[] plugins){
     this.tisClassLoaders = new URLClassLoader[plugins.length];
     int i = 0;
     for(String plugin : plugins){
      this.tisClassLoaders[i++] = createChildClassLoader(plugin);
     }
   }

   private URLClassLoader createChildClassLoader(String plugin){
   // get the urls which is belong to the plugin  
   URL[] urls = ....;
    return new URLClassLoader(urls);
   }
   ```
4.  TISClientFirstClassLoader is response for  loading class which is defined at client side, by the classloader array which have just created in the `3` step. code as below:
    ```java 
    public Class<?> findClass(String name) throws ClassNotFoundException {
       for (ClassLoader loader :  tisClassLoaders) {
         try {
             return loader.loadClass(name);       
        } catch (ClassNotFoundException e) {             // not found. try next        }   
     }
     return null;
   }
    ```

**Comment by zentol** [comment]
I'm sorry, but that implementation sounds really unsafe and will only work for the simplest of use-cases.
Let's say you have 2 of your plugin jars that both bundle the same dependency with incompatible version (let's say guava), and said dependency is used by the user (e.g., because it is exposed in the API of the connector).

It's now a coin toss as to whether the correct guava version will be loaded. 

Actually, if we take an application cluster, it is equivalent to just adding the connectors to `lib/`, and in terms of classloader isolation, is generally also equivalent to just bundling everything in the user-jar.


These kind of problems are exactly why we don't want to expose this to users.

**Comment by baisui1981** [comment]
> I'm sorry, but that implementation sounds really unsafe and will only work for the simplest of use-cases. Let's say you have 2 of your plugin jars that both bundle the same dependency with incompatible version (let's say guava), and said dependency is used by the user (e.g., because it is exposed in the API of the connector).
> 
> It's now a coin toss as to whether the correct guava version will be loaded.

@zentol ,I must admit that this situation exists, but whether this is a security consideration can be left to the `Flink Developer` to judge? And i believe that this kind of problem can be circumvented by some means

For flink, all need to do is to add an `Extension Point`. When the user does not extend this `Extension Point`, it has no effect on flink.

**Comment by RocMarshal** [comment]
Hi, @baisui1981 , Could you check the CI result 'src/main/java/org/apache/flink/runtime/execution/librarycache/ClassLoaderFactoryBuilder.java:[22,8] (imports) UnusedImports: Unused import: org.apache.flink.runtime.rpc.FatalErrorHandler.' ? Thx.
or run `mvn spotless:apply` in `flink` directory.

**Comment by baisui1981** [comment]
> Hi, @baisui1981 , Would you mind checking the CI result 'src/main/java/org/apache/flink/runtime/execution/librarycache/ClassLoaderFactoryBuilder.java:[22,8] (imports) UnusedImports: Unused import: org.apache.flink.runtime.rpc.FatalErrorHandler.' ? Thx. or run `mvn spotless:apply` in `flink` directory.

@RocMarshal thanks for your remind , I'm sorry for having not remove this unused import class from carelessness. I have fixed it.

**Comment by RocMarshal** [comment]
@baisui1981 Thanks for the update. 
Please run `mvn spotless:apply` in the flink root directory for fixing the checkstyle.
In my limited read, would you mind introducing some test cases for the change ?

**Comment by baisui1981** [comment]
> Thanks for the update.

thanks for your remind，I will add some test cases for the change.

**Comment by baisui1981** [comment]
> @baisui1981 Thanks for the update. Please run `mvn spotless:apply` in the flink root directory for fixing the checkstyle. In my limited read, would you mind introducing some test cases for the change ?

thanks for your remind，I will add some test cases for the change and fix the checkstyle erros.

**Comment by baisui1981** [comment]
I have make the fixes done,thanks for your reviews @RocMarshal

**Comment by baisui1981** [comment]
@RocMarshal  @zentol @AHeise   PTAL thx

**Comment by baisui1981** [comment]
@RocMarshal @zentol @AHeise PTAL thx

**Comment by baisui1981** [comment]
@RocMarshal @zentol @AHeise could you please give me some suggestion ,how to continue processing for this PR?

**Comment by baisui1981** [comment]
@RocMarshal @zentol @AHeise could you please give me some suggestion ,how to continue processing for this PR?

**Comment by baisui1981** [comment]
@RocMarshal @zentol @AHeise could you please give me some suggestion ,how to continue processing for this PR?

**Comment by baisui1981** [comment]
@RocMarshal @zentol @AHeise could you please give me some suggestion ,how to continue processing for this PR?

**Comment by zentol** [comment]
Will not be supported,

**Pull request closed without merging**
