### PR TITLE
[FLINK-20485][table] Improve performance of data views

### PR DESCRIPTION
**Pull request by twalthr**
## What is the purpose of the change

This improves the performance when using map views in aggregate functions with retraction and distinct aggregates.

## Brief change log

- It reduces the deserialization overhead by using a lazy binary format.
- It reuses internal data structures during deserialization from bytes to external data structure (e.g. required for deduplicating map views using regular Java `Map`).

## Verifying this change

Manually benchmarked using the following test in `AggregateITCase` with LocalGlobal=ON, MiniBatch=ON, HEAP:

```
  @Test
  def testPerf(): Unit = {
    tEnv.executeSql(
      s"""
         |CREATE TABLE datagen (a INT, b BIGINT, c STRING) WITH (
         | 'connector'='datagen',
         | 'rows-per-second'='500000',
         | 'number-of-rows'='1000000',
         | 'fields.a.kind' = 'random',
         | 'fields.a.min' = '1',
         | 'fields.a.max' = '10000',
         | 'fields.b.min' = '1',
         | 'fields.b.max' = '100000',
         | 'fields.c.length' = '1000'
         |)
         |""".stripMargin)

    val sqlQuery =
      "SELECT b, " +
        "  SUM(DISTINCT (a * 3)), " +
        "  COUNT(DISTINCT SUBSTRING(c FROM 1 FOR 2))," +
        "  MAX(DISTINCT a), " +
        "  MIN(DISTINCT b), " +
        "  MAX(a), " +
        "  MIN(b), " +
        "  COUNT(DISTINCT c) " +
        "FROM datagen " +
        "GROUP BY b"

    val result = tEnv.sqlQuery(sqlQuery).toRetractStream[Row]
    result.addSink(new DiscardingSink[(Boolean, Row)])
    env.execute()
  }
```

The performance shows similar number that 1.11 or slightly better.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: yes
  - The runtime per-record code paths (performance sensitive): yes
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? JavaDocs

### CODE REVIEW

**Review by wuchong — COMMENTED** [review]
Thanks for the quick fix. The change looks good to me. I have some minor questions. 

1. `DistinctViewSpec` is not necessary any more?
2. Is there a reason why we not return RAW type in `MapView.newMapViewDataType`?

**Comment by wuchong** [comment]
cc @JingsongLi , do you want to have a look?

**Comment by twalthr** [comment]
Thanks for the review @wuchong. I removed some unused code in another commit.

Regarding 1: `DistinctViewSpec` is not really necessary but might help to improve code readability and gives this special `MapView` a name.

Regarding 2: The RAW type is an internal optimization and should not be exposed via API. A `MapView` is a structured type but with a special meaning. However, it can also be used in regular POJOs etc.

**Review by wuchong — APPROVED** [review]
Thanks for the explanation.

**Pull request closed without merging**
