### PR TITLE
[FLINK-36323][StateBackend] Remove deprecated MemoryStateBackend, FsStateBackend and RocksDBStateBackend.

### PR DESCRIPTION
**Pull request by xing1mo**
## What is the purpose of the change
After [FLINK-19463](https://issues.apache.org/jira/browse/FLINK-19463), the checkpoint storage has been split from the state backends. The deprecated implementation MemoryStateBackend and RocksDBStateBackend are replaced by HashMapStateBackend and EmbeddedRocksDBStateBackend. Those two state backends should be removed in Flink 2.0.

## Brief change log
  - *Remove MemoryStateBackend, FsStateBackend, RocksDBStateBackend. And change related test.

## Verifying this change
This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes
  - The serializers: no 
  - The runtime per-record code paths (performance sensitive): no / don't know
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no 
  - The S3 file system connector: no 

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by Zakelly** [comment]
@flinkbot run azure

**Comment by Zakelly** [comment]
@flinkbot run azure

**Comment by xing1mo** [comment]
@Zakelly CI has passed.

**Comment by Zakelly** [comment]
CI passed.

The conflicts comes from the two PR modifying imports of one test file. Gonna resolve it and merge.

**Comment by Zakelly** [comment]
Local compile succeeds. Merging...

**Pull request closed without merging**
