### PR TITLE
[FLINK-22476] Extend the description of the config option `execution.target`

### PR DESCRIPTION
**Pull request by tony810430**
## What is the purpose of the change

update the description of `execution.targets`

## Brief change log

- add `yarn-application` and `kubernetes-application` into desscription

## Verifying this change

This change is just a document update.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? applicable

### CODE REVIEW

**Comment by KarmaGYZ** [comment]
Thanks for preparing this PR, @tony810430 . You can execute the following command to rebuild the doc:
`mvn clean package -Dgenerate-config-docs -pl flink-docs -am -nsu -DskipTests -Dcheckstyle.skip` .

**Comment by tony810430** [comment]
@KarmaGYZ thanks for review. have updated the generated docs.

**Comment by KarmaGYZ** [comment]
Thanks for the update. LGTM. Do you have other concerns? @tillrohrmann

**Review by tillrohrmann — APPROVED** [review]
Thanks for the PR @tony810430 and the review @KarmaGYZ. LGTM. Merging this PR now.

**Pull request closed without merging**
