### PR TITLE
[FLINK-5982] [runtime] Refactor AbstractInvokable and StatefulTask

### PR DESCRIPTION
**Pull request by tony810430**
This PR wants to merge `AbstractInvokable` and `StatefulTask` to eliminate "lazy initialization" in `Task`.

The following are what I did in this PR:

1. Merge `AbstractInvokable` and `StatefulTask` and use constructor to initialize `Environment` and `TaskStateHandles` in `AbstractInvokable`.
2. Update all subclasses and corresponding tests. For now, batch tasks are still not stateful, so I added `IllegalStateException()` in constructor and `UnsupportedOperationException()` in the methods for supporting stateful task.
3. Update the behavior of `AbstractInvokable` in `Task`, including `loadAndInstantiateInvokable()`, `triggerCheckpointBarrier()` and `notifyCheckpointComplete()`.
4. Add tests for modification in `Task` and tests the constructors' behavior for all concrete  subclasses which inherit `AbstractInvokable`.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Thanks for this refactoring. I had only a quick look so far, but one thought was that this patch could probably be simplified by making `triggerCheckpoint()` (and restore / notifyComplete) not abstract in the `AbstractInvokable`. Instead let it throw the `UnsupportedOperationException`.

That way, we avoid refactoring all the test classes to implement those methods (which would be nice).

**Comment by tony810430** [comment]
@StephanEwen Thanks for the suggestion. I have updated the patch.

**Comment by StephanEwen** [comment]
Thanks, I will try and look at this over the next week.
It is quite a big change, so I might need a bit of time to review it properly...

**Comment by tony810430** [comment]
Hi @StephanEwen 

Have you been reviewing this PR? If not, I would like to rebase it and fix those conflicts. What do you think?

**Comment by StephanEwen** [comment]
Sorry, I did not manage to merge this, yet. Will try to take it on after the 1.3 release.
Thanks for the offer to rebase that. I can ping you when I would be getting close to merging this, so that you could rebase it once then (rather than now and potentially again in a few weeks).

**Comment by tony810430** [comment]
I see. Thank you. =)

**Comment by tony810430** [comment]
Hi @StephanEwen 
Do you have time to review this PR recently?

**Comment by StephanEwen** [comment]
Sorry about the delay. I still have this on my list...

**Comment by tony810430** [comment]
Hi @StephanEwen 
Do you have time recently? Or can we find someone to review it if you are too busy to do this? Thank you.

**Comment by StephanEwen** [comment]
I finally found the time to look at this.

Have rebased it and applied some simplifications:
  - convenience constructors for stateless tasks
  - test utils that provide mock environments directly
  - Task Test Harnesses create the tasks lazily via a factory.

All in all that makes for a good patch in my opinion.

Will merge this...

**Comment by tony810430** [comment]
Thanks a lot for doing these work. Nice to see this PR be merged. =)

**Pull request closed without merging**
