### PR TITLE
[FLINK-23313][docs] Reintroduce temporal table function documentation

### PR DESCRIPTION
**Pull request by leonardBang**
## What is the purpose of the change

* This pull request reintroduce the temporal table function documentation,  the temporal table function feature has never been deprecated but the documentation was deleted when simplify the SQL concepts documentation in FLINK-20456. 

## Brief change log

  - Reintroduce the documentation of `temporal table function`
  - Fix typo in `tableApi.md`

## Verifying this change

This change is a documentation change without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): ( no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by leonardBang** [comment]
cc: @wuchong @sjwiesman, Could you help review this doc change?

**Comment by sjwiesman** [comment]
This looks good to me. @leonardBang should we backport this to 1.14?

**Review by sjwiesman — APPROVED** [review]

**Comment by leonardBang** [comment]
> This looks good to me. @leonardBang should we backport this to 1.14?

Yes,  I'll backport the PR to release-1.14

**Comment by leonardBang** [comment]
That's great if you can help merge @sjwiesman ,  thanks.

**Pull request closed without merging**
