### PR TITLE
[FLINK-14938][Connectors / ElasticSearch] Fix ConcurrentModificationException when Flink elasticsearch failure handler re-add indexrequest

### PR DESCRIPTION
**Pull request by ysn2233**
## What is the purpose of the change
Fix to avoid ConcurrentModificationException when Flink elasticsearch failure handler re-add indexrequest

## Brief change log
  - Use ConcurrentLinkedQueue to maintain bufferRequests in BufferingNoOpRequestIndexer instead of List

## Verifying this change
This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by aljoscha** [comment]
The build fails because of unused imports, could you please fix those.

Thanks for discovering this problem! I think the design is not optimal here because it can happen that during a batch we add more failed requests to the buffer. Ideally, we would have designed the sink in such a way that we can do things without a concurrent queue. However, I think with the current design it's ok to change it to a concurrent queue here.

Side node: I'm not 100 % sure this sink works correctly because of the many concurrent things going on. Not saying that there are problems, just that I don't know. 😅

**Comment by aljoscha** [comment]
@flinkbot run azure

**Comment by ysn2233** [comment]
@flinkbot run azure

**Comment by ysn2233** [comment]
@flinkbot run azure

**Comment by ysn2233** [comment]
It's strange that CI test fails and the re-run command does not work

**Comment by aljoscha** [comment]
No worries, I ran this on my Azure account: https://dev.azure.com/aljoschakrettek/Flink/_build/results?buildId=253&view=results

**Comment by aljoscha** [comment]
Thanks a lot for your fix! I merged 👍

**Pull request closed without merging**
