### PR TITLE
 [FLINK-21103] Increased TTL for download cache entries 

### PR DESCRIPTION
**Pull request by dawidwys**
I increased the timeout for download cache entries and reenabled `SQLClientHBaseITCase` test.

### CODE REVIEW

**Comment by dawidwys** [comment]
Could you @rmetzger @zentol say if it makes sense to you to increase the timeout? We don't have any timeout for the bash cache as far as I can tell.

**Comment by zentol** [comment]
In the long-long term you do want a timeout for individual cache entries, otherwise it will keep growing over time as versions are being bumped. I don't see a problem in _increasing_ the cache timeout though.

**Comment by rmetzger** [comment]
+1 to increase

**Comment by dawidwys** [comment]
Thanks for your opinions! I'll merge the PR after Azure gives green then. I increased the timeout to 3 months from 1 month.

**Comment by dawidwys** [comment]
The build failed because of `ReactiveModeITCase` hang. All other tests passed. I'll merge.

**Pull request merged**
