### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bitchelov**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [ ] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [ ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

Add Travis build status (more informative).

### CODE REVIEW

**Comment by greghogan** [comment]
Is there a Jira ticket for this PR?

**Comment by bitchelov** [comment]
Hi @greghogan ! No, there is no Jira ticket for this PR. It made for convenience and as i said ( to do "README.md" file more informative).

**Comment by greghogan** [comment]
Hi @bitchelov, I don't think we want to advertise the Travis CI status. Builds consistently fail, both due to Flink test instability and issues running on the Travis CI architecture. We test each commit five times over (times two jobs, each running half the tests) and a single failed jobs is marked as a failed build. We are also now seeing jobs timeout due to an unannounced reduction of the maximum runtime from 120 minutes to 50 minutes.

**Comment by bitchelov** [comment]
Okay @greghogan,  I understand. Thanks.

**Pull request closed without merging**
