### PR TITLE
[FLINK-2779][FLINK-2794][streaming][docs] New DataStream API programming guide

### PR DESCRIPTION
**Pull request by ktzoumas**
Not good to merge.

I am putting this up for discussion, but it depends on several pull requests that need to be merged first.

This is a draft of a new DataStream programming guide. The main differences are:
- Several new additions (merged or under way), including the new window builders are documented
- An effort has been made to make the DataStream guide stand-alone, without depending on the DataSet guide. This is not fully achieved yet, as several parts that are common to the two APIs are documented in the DataSet guide and linked to by the DataStream guide.

Scala is currently missing, but I plan to cover it, as well as do a more thorough check (if links are working, proper indentation, fix some incorrect class names etc). 

@aljoscha can you take a look and see if this reflects correctly your recent changes?

### CODE REVIEW

**Comment by StephanEwen** [comment]
Two comments:
  - I would call the section "Buffer Timeout" rather "Controlling Latency" or so. It helps people that are interested in latency to find the section relevant for them
  - The code example in "Making local variables consistent" is wrong, the types of the interfaces/casting is not correct

**Comment by aljoscha** [comment]
Sometimes you write DataSet in the stream guide where it should be DataStream.

**Comment by aljoscha** [comment]
In the section "Transformations" you sometimes use the `` syntax to highlight words, such as DataStream. Inside the table they don't get properly translated, however. (At least on my machine.)

**Comment by gyfora** [comment]
The description of Evictors for the keyed windows are a little bit messy, what gets evicted from where. There is also some conflict with the example and the description: "Retain 1000 elements from the end of the window backwards, evicting all others." vs "and every time execution is triggered, 10 elements are removed from the window". 

As far as I understand triggers and evictors work with the same semantics as now, but there is always a fix time trigger/eviction determined by the window assigner.

**Comment by aljoscha** [comment]
The WindowFunction has a different signature for regular windows and all windows. This should maybe be visible in the transformations section.

**Comment by aljoscha** [comment]
@gyfora Yes, they work with the same semantics. What do you mean by "fix time trigger/eviction determined by the window assigner"?

**Comment by gyfora** [comment]
@aljoscha : what I meant was just that we define some time semantics with the window assigner

**Comment by aljoscha** [comment]
@gyfora, yes, thats right

**Comment by aljoscha** [comment]
The ConnectedStreams example formatting is off (in Transformations section), also there should be something like:
```java
ConnectedStreams<> connectedStreams = someStream.connect(otherStream)
```

**Comment by aljoscha** [comment]
If split is mentioned select should also be mentioned.

**Comment by gyfora** [comment]
"Windows on unkeyed data streams (non-parallel windows)"
I still think that this gives a bad false impression of executing all global windows including time in a non-parallel way.

I can already here people say that Spark can do global time windows in parallel while Flink cant :P

**Comment by aljoscha** [comment]
There should be some streaming specific stuff in the `Execution Config` section. For example, there is `enableTimestamps()` and `setAutoWatermarkInterval()`.

**Comment by StephanEwen** [comment]
Global windows are not parallel, not in any system, it is inherent in the operation.

You can pre-aggregate in parallel, if the windows are time windows. These are probably the most common windows. Any other windows are not even supported in any other system that I have worked with...

**Comment by gyfora** [comment]
That is what I mean, global time reduce.

**Comment by StephanEwen** [comment]
Would be a nice addition to the docs, to state that global time reduce (and other aggregations) are pre-aggregated in parallel.

**Comment by senorcarbone** [comment]
Nice doc so far ^^

One tiny fix on the  *Advanced window constructs* subsection:

[0,1000], [100,1100], **[200,1200]**, ..., [1000, 2000]

**Comment by senorcarbone** [comment]
From a quick read on the documentation (and prior knowledge from google dataflow) it is easy to get a full picture of the new semantics. Even though I like it from a engineering perspective, It needs to be pointed out though that the addition of the *Assigner* restricts our previous windowing semantics to periodic windows, i.e. at the moment you receive a record you have to know all the possible buckets this record will fall into while before we did not have such a constraint. In other words we no longer support dynamic windows where range and slide can change dynamically.

**Comment by aljoscha** [comment]
@senorcarbone It doesn't restrict. You can use an assigner that assigns to one single window. Then using, trigger and evictor you can implement everything that was possible before.

**Comment by senorcarbone** [comment]
Ah Indeed. I just reviewed this with the prospect of custom pre-aggregations in mind and it seems like pre-aggregation strategies operate on bucket-granularity. Solely on windowing semantics what you suggest covers my question though. thanks ^^

**Comment by ktzoumas** [comment]
I addressed the comments above, added the content for Scala, reworked the iterations section, added content to the windows section, and made the DataStream API guide almost identical to the DataSet API guide content-wise (still with links towards the DataSet guide). 

I also made changes to the docs as a whole to reflect the equal status of the DataSet and DataStream APIs.

There are still some features that are missing from the docs or are poorly documented (aggregations and state). I am working on those.

**Comment by ktzoumas** [comment]
Once https://github.com/apache/flink/pull/1238 is merged, this is ready to be merged as well (the docs track the changes in that PR)

**Comment by fhueske** [comment]
It's a bit painful to review because Github is not showing the diff :-(

Here is what I found in `streaming_guide.ml` until but not including `Specifying Keys`:

Intro:
- What are regular programs?
- "The data streams are initially created…" -> "A data stream can be produced by different sources such as …"
- What are distributed files?
- Flink program -> DataStream program

Linking with Flink:
- To write programs with Flink -> To implement a DataStream program
- If you want to add Flink to an existing -> If you want to add Flink's DataStream API to an …
Program Skeleton (Java and Scala):
- Flink DataStream program -> DataStream Program
- If you created a JAR file from you program -> If you created a JAR file from YOUR program
- with your own custom transformation function -> with your own custom transformation FUNCTIONS
- converting every String in the original set to an Integer. -> converting every String in the original STREAM to an Integer.

DataStream abstraction:
- unbounded immutable collection of data of a the same type -> unbounded immutable collection of data ITEMS of a the same type. ?

Lazy Evaluation:
- All Flink programs -> All DataStream programs

Transformations (only checked Java, Scala probably the same…)
- KeyBy
  - Logically partition a stream -> Logically PARTITIONS a stream
  - This transformations -> This transformation
- Reduce + Fold
  - Combines the last element with the last reduced value and emits the new value. -> Combines the current element with the last reduced value and emits the new value. ?
- Aggregations:
  - Rolling aggregations on keyed data stream. -> Rolling aggregations on A keyed data stream.
- Window
  - Windows can be defined on already partitioned KeyedStreams -> Windows can be defined on partitioned KeyedStreams ?
- Window Apply
  - Applies a general function to the window as a whole. -> Applies a general function to WINDOWS as a whole. ?
  - A function that manually sums the elements of a window -> Sentence is incomplete
- Window Reduce / Aggregations
  - Point out difference to rolling reduce / aggregations?
- Iterate
  - The resulting stream of an iteration is a DataStream again. The IterativeStream is only "within" the iteration, right? Shouldn't it be DataStream -> IteratativeStream -> DataStream then?
- Extract Timestamps
  - Extract -> ExtractS
  - Flink windows -> windows

**Comment by fhueske** [comment]
Review 2nd part (until Connectors):

General & Outline
- Inconsistent capitalization of sections
- Switch "Execution Configuration" and "Data Sinks" sections to have Sinks directly after Sources?

Specifying Keys
- "A DataStream is keyed OAS"

Data Types
- and as results of transformations. -> and ON THE results of transformations.

Data Sources (Java and Scala)
- Creates a data set -> Creates a data stream (4 times)

Debugging
- Before running a streaming program on a large data set in a distributed cluster -> Before running a DataStream program in a distributed cluster ?

Debugging - Local Execution Environment
- breakpoint -> breakpointS

Working with time
- The event time paragraph says: "This time is either recorded in a timestamp embedded within the records before they enter Flink, or is assigned at the source." Isn't it Ingestion time if timestamps are assigned at the source?
- Does ingestion time not require watermarks?
- "In order to work with event time semantics, you need to follow three steps" isn't it four steps (last step are two steps)
- What is the getCurrentWatermark() { return Long.MIN_VALUE;}  good for?

Windows on keys data streams
- Why do sliding windows "overlap by AT LEAST 4 secs / 900 elements"? Shouldn't it be: "subsequent windows overlap by 4 secs / 900 elements"?

Advanced window constructs
- "the SlidingTimeWindows assigner in the example" which example are you refering to? It should be size 5000 and slide of 1000 ms and not 1000 and 100ms, right?
- Delta trigger: the current element refers to the element that was last added to the window?

Fault tolerance
- where n is how often a checkpoint is taken in milliseconds. -> where n is the checkpointing interval in milliseconds ?
- Is there no Kafka Sink (KafkaProducer)? It is missing in the sink guarantee table.

Parallelism
- Shouldn't we add here how data is repartitioned if the DOP of subsequent operators increases or decreases?

Controlling latency
- Also show the parameter for the buffer size.

Working with state
- The end effect is that updates to any form of state are the same under failure-free execution and execution under failures.  -> By that Flink guarantees that any form of state is the same under failure-free execution and execution under failures (given that the sources support exactly-once delivery). ?
- The difference between both interfaces is not so well described, in my opinion.

Making local variables consistent
- There is a space in "c heckpoint"
- "For example the same counting, reduce function shown for OperatorStates by using the Checkpointed interface instead" The Checkpointed interface is described before OperatorState

Using the state interface
- Doesn't the checkpointed interface require enableCheckpointing() to be set? It is only mentioned for the OperatorState.
- Doesn't the Serializability requirement also apply to non-parallel state?
- This section is hard to understand. Many different things being mentioned without clear structure.

State checkpoints in iterative jobs
- Fink -> Flink

Iterations
- Strem -> Stream

**Comment by fhueske** [comment]
Last part of review:

Connectors
- (with the exception of Twitter where only a source is provided and Elasticsearch where only a sink is provided) -> The following list only shows sink for HDFS. I'd just remove the exception sentence.

Kafka Source:
- This section describes the FlinkKafkaConsumer082 and not the KafkaSource

Kafka Sink: 
- This sentence is confusing, IMO: "Also the serializer configuration should be left default, the serialization should be set via SerializationSchema."

Elasticsearch:
- "Sink" is sometimes capitalized, sometimes not.
- Not how -> Note how

Hadoop FileSystem
- Hadoop FileSystem -> Hadoop File System
- "Sink" is sometimes capitalized, sometimes not.

Twitter Streaming API
- Remember to keep these pieces of information a secret -> Remember to keep these pieces of information secret (remove "a")
- numberOfTweets determine how many tweet the source emits. -> numberOfTweets determineS how many tweet the source emits.

**Comment by fhueske** [comment]
Overall really good documentation!
I would only improve the state section a bit.

**Comment by ktzoumas** [comment]
Thanks a lot Fabian for the fantastic review! I addressed most of your comments. The state section needs to be rewritten after https://github.com/apache/flink/pull/1239 has been merged.

**Comment by mbalassi** [comment]
Thanks for this big update, guys!

Some comments:
  * Explanation of operator chaining and options are missing.
  * Collection Data Sources: The following sentence should be removed: 'Currently, the collection data source requires that data types and iterators implement Serializable.' This is not true anymore.
  * Transformations DataStream,DataStream → DataStream looks better with a tuple-style input for me: (DataStream, DataStream) → DataStream if that fits on the page.
  * In the source code examples I would use the diamond operator for Java7, e.g. in the Splitter of the WC.

**Comment by ktzoumas** [comment]
@mbalassi: is the operator chaining currently documented somewhere? Same about partitioning between operators of different parallelism

**Comment by mbalassi** [comment]
@ktzoumas chaining has decent documentation in the Javadocs. The behavior of subsequent operations with different parallelism is not really documented unless I am missing something.

**Comment by ktzoumas** [comment]
Added docs for chaining and resource groups

**Comment by aljoscha** [comment]
I will merge this now since the code is also changed. We can iterate on this if need be.

**Comment by aljoscha** [comment]
@asfgit didn't close it automatically, could you please close it @ktzoumas .

**Pull request closed without merging**
