### PR TITLE
[FLINK-3490] Bump Chill version to 0.7.4

### PR DESCRIPTION
**Pull request by fhueske**

### CODE REVIEW

**Comment by fhueske** [comment]
My Travis tests are still pending.

**Comment by rmetzger** [comment]
The Kryo dependency didn't change.
Once travis gives green light, I'm okay with merging this.

**Comment by rmetzger** [comment]
I really hope is a coincidence, but both the PR travis run and your own travis run had the following failure:

Failed tests: 
  ExecutionGraphRestartTest.testFailingExecutionAfterRestart:485 expected:<FINISHED> but was:<FAILED>

See https://s3.amazonaws.com/archive.travis-ci.org/jobs/111430847/log.txt and https://s3.amazonaws.com/archive.travis-ci.org/jobs/111430729/log.txt

**Comment by fhueske** [comment]
Me too :worried:.
Just restarted the failed build.

**Comment by fhueske** [comment]
OK, the restarted build passed the previously failed test. 
Merging

**Pull request closed without merging**
