### PR TITLE
[FLINK-25980][datastream] remove unnecessary condition

### PR DESCRIPTION
**Pull request by hongshuboy**
## What is the purpose of the change

Condition 'currentWatermark != Long.MIN_VALUE' covered by subsequent condition 'timestamp < currentWatermark' 

org.apache.flink.streaming.api.operators.co.IntervalJoinOperator#isLate

```java
private boolean isLate(long timestamp) {
    long currentWatermark = internalTimerService.currentWatermark();
    return currentWatermark != Long.MIN_VALUE && timestamp < currentWatermark;
} 

```

if currentWatermark == Long.MIN_VALUE, timestamp < currentWatermark it's also return false, so condition currentWatermark != Long.MIN_VALUE is unnecessary

We can use the following code directly

```java
private boolean isLate(long timestamp) {
    long currentWatermark = internalTimerService.currentWatermark();
    return timestamp < currentWatermark;
} 
```

## Brief change log

remove unnecessary condition

## Verifying this change

This change is already covered by existing tests, such as *(org.apache.flink.streaming.api.operators.co.IntervalJoinOperatorTest)*.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by hongshuboy** [comment]
@rmetzger hi, can you assign this issue to me, the URL is https://issues.apache.org/jira/browse/FLINK-25980, I want to deal with this problem

**Comment by hongshuboy** [comment]
@flinkbot

**Comment by hongshuboy** [comment]
@flinkbot approve all

**Review by alpreu — APPROVED** [review]

**Comment by hongshuboy** [comment]
:)

**Pull request merged**
