### PR TITLE
[web-dashboard] Added task managers to the new web dashboard

### PR DESCRIPTION
**Pull request by iampeter**
I transfered the task manager REST API code to a RequestHandler (TaskManagersHandler) and added the JS view.

There are no charts yet, but it's a start.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Very nice!

+1 to merge this

**Comment by StephanEwen** [comment]
Let's tag it with this issue when merging: https://issues.apache.org/jira/browse/FLINK-2729

**Comment by uce** [comment]
I will test it and merge if everything works as expected :)

**Comment by uce** [comment]
Works like a charm. ;) I've renamed the handler from `task-managers` to `taskmanagers`, because I feel like it is more in line with the other naming. I would merge this in a few hours if there are no objections. We can extend the interface with charts etc. later imo.

Some screenshots:

screen shot 2015-09-22 at 23 38 39
screen shot 2015-09-22 at 23 38 58

**Comment by mxm** [comment]
+1

Looks really nice!

**Comment by rmetzger** [comment]
Thank you for this great feature!

**Pull request closed without merging**
