### PR TITLE
[FLINK-22898][Connectors/Hive] return default-parallelism in HiveParallelismInference when there is no source infer

### PR DESCRIPTION
**Pull request by luoyuxia**
## What is the purpose of the change

*The pull request is to return default-parallelism in HiveParallelismInference when there is no source infer instead of max(1, default-parallelism) *

## Brief change log

  - *Return default-parallelism in  HiveParallelismInference directly when there's no source infer*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`:  no
  - The serializers:  no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by lirui-apache** [comment]
Thanks @luoyuxia for working on this. Let's add a test case to cover it.

**Comment by luoyuxia** [comment]
@lirui-apache 
I see HiveTableSourceITCase#testParallelismOnLimitPushDown cover the parallelism when infer-source-parallelism is false, should we just reuse this test or add extra test?

**Comment by lirui-apache** [comment]
@luoyuxia Please also add a test case where `TABLE_EXEC_RESOURCE_DEFAULT_PARALLELISM` is not set and the default value (-1) is returned. To make sure returning -1 really works.

**Review by lirui-apache — APPROVED** [review]
+1 pending test

**Pull request closed without merging**
