### PR TITLE
 [Flink-Gelly] [example] added missing assumption to the pageRank example: this is a simplified version of the algorithm so pages must have at least one incoming and one outgoing link

### PR DESCRIPTION
**Pull request by samk3211**

### CODE REVIEW

**Comment by vasia** [comment]
Hi @samk3211! Thank you for spotting this :)
Can you please (1) close #881, (2) add this comment also to GSAPageRank as @andralungu (3) squash your commits to a single one?
Thank you!

**Comment by andralungu** [comment]
I guess the only request that was not fulfilled for this PR was to squash the commits. Then it should be fine.

**Comment by vasia** [comment]
I've actually included this in #1000. Could you close this PR @samk3211? Thanks!

**Comment by samk3211** [comment]
closed

**Pull request closed without merging**
