### PR TITLE
[FLINK-2633] [scala, types] Adds equals and hashCode method to OptionTypeInfo

### PR DESCRIPTION
**Pull request by tillrohrmann**
Adds equals and hashCode method to OptionTypeInfo. This PR allows to compare types containing an option type.

### CODE REVIEW

**Comment by chiwanpark** [comment]
+1 for merging

**Comment by StephanEwen** [comment]
How about we override `hashCode()`, `equals()`, and `toString()` in the `TypeInformation` base class as `abstract`? That forces subclasses to override these methods.

**Comment by chiwanpark** [comment]
+1 for making `hashCode()`, `equals()`, and `toString()` abstract.

**Comment by tillrohrmann** [comment]
+1 for `hashCode()`, `equals()` and `toString()` abstract. But also for introducing `canEqual` as proposed by Martin Odersky (https://www.artima.com/lejava/articles/equality.html). The reason is that we currently have the odd behaviour that the `equals` method of `TypleTypeInfo` and `TupleTypeInfoBase` is not an equality relation (reflexive, symmetric, transitive, consistent). The following code demonstrates this:

```
TupleTypeInfo<Tuple1<Integer>> tupleTypeInfo = new TupleTypeInfo<>(BasicTypeInfo.INT_TYPE_INFO);

TupleTypeInfoBase<Tuple1> anonymousTupleTypeInfo = new TupleTypeInfoBase<Tuple1>((Class<Tuple1>)Tuple1.class, (TypeInformation<?>)BasicTypeInfo.INT_TYPE_INFO) {

	@Override
	public TypeSerializer<Tuple1> createSerializer(ExecutionConfig config) {
		return null;
	}

	@Override
	protected void initializeNewComparator(int localKeyCount) {}

	@Override
	protected void addCompareField(int fieldId, TypeComparator<?> comparator) {}

	@Override
	protected TypeComparator<Tuple1> getNewComparator(ExecutionConfig config) {
		return null;
	}

	@Override
	public String[] getFieldNames() {
		return new String[0];
	}

	@Override
	public int getFieldIndex(String fieldName) {
		return 0;
	}
};

System.out.println(tupleTypeInfo.equals(anonymousTupleTypeInfo)); // false
System.out.println(anonymousTupleTypeInfo.equals(tupleTypeInfo)); // true
```

Thus, the symmetric condition is violated.

This should actually be the norm for all future equality implementation, IMHO.

**Comment by fhueske** [comment]
How about we move the discussion about making methods abstract and introducing new methods to a separate issue?

**Comment by tillrohrmann** [comment]
Is it really necessary to discuss an obvious bug on the mailing list? The `EitherTypeInfo` suffers from the same problem and, thus, it seams to be a systematic error. In order to prevent future mistakes like this, I don't see a different way than making the developer aware that he has to implement these methods.

**Comment by tillrohrmann** [comment]
Oh I have to correct myself. It's even worse then expected. Not only `OptionTypeInfo` and `EitherTypeInfo` are broken but also `EnumTypeInfo` and `TryTypeInfo` because they don't implement `equals`. Furthermore, the `equals` method of `RecordTypeInfo`, `WritableTypeInfo` and `GenericTypeInfo` will fail with a `NullPointerException` when called with `null`. The `PrimitiveArrayTypeInfo` does not implement the `hashCode` method.

**Comment by fhueske** [comment]
Yes, I think that is necessary. FLINK-2633 is about a bug in `OptionTypeInfo`. It is not about the general TypeInformation interface which is not broken, but could (and should) be improved. We should create a new JIRA (changing TypeInfo breaks the public API) and continue the discussion of changing the API over there.

**Comment by fhueske** [comment]
Created [FLINK-2637](https://issues.apache.org/jira/browse/FLINK-2637)

**Comment by tillrohrmann** [comment]
If these changes are API breaking, then this PR is as well API breaking.

**Comment by fhueske** [comment]
Sure, but that should also be reflected in the JIRA issue. 
Please go ahead and update FLINK-2633 and close FLINK-2637 if you want to address all these issues in this PR.

**Comment by tillrohrmann** [comment]
Will do. FLINK-2633 is basically subsumed by FLINK-2637. Thus, I'll close this PR and open a new one for FLINK-2637.

**Comment by fhueske** [comment]
Cool, thanks!

**Comment by fhueske** [comment]
@tillrohrmann You are extending this PR and opening a new one, right? 
Can you close this PR?

**Comment by tillrohrmann** [comment]
Sure.

**Pull request closed without merging**
