### PR TITLE
[FLINK-7201] fix concurrency in JobLeaderIdService when shutdown the …

### PR DESCRIPTION
**Pull request by XuPingyong**

### CODE REVIEW

**Comment by StephanEwen** [comment]
@XuPingyong Can you give us a bit of context for the review?
From the initial exception I would expect that there is something that also needs to be addressed in the `JobLeaderIdService` class...

**Comment by XuPingyong** [comment]
@StephanEwen ,  rpcService of ResourceManager executes with only one single thread, so there is no conflicts when resourcemanager is in service. When resourceManager is shutdown by the other thread, the rpcService had better stop first.

**Comment by tillrohrmann** [comment]
I think it would be better to harden the `JobLeaderIdService` such that it can be shut down concurrently. This actually also applies to the `HeartbeatManager`, the `SlotManager` and the `ResourceManager` itself.

**Comment by tillrohrmann** [comment]
With the changes of #4420, this problem should be resolved. Could you please close this PR then @XuPingyong.

**Comment by XuPingyong** [comment]
Thanks @tillrohrmann !

**Pull request closed without merging**
