### PR TITLE
[FLINK-31319][BP-1.16][connectors/kafka] Fix kafka new source partitionDiscoveryIntervalMs=0 cause bounded source can not quit

### PR DESCRIPTION
**Pull request by chucheng92**
Backport [FLINK-31319](https://issues.apache.org/jira/browse/FLINK-31319) to release-1.16.

### CODE REVIEW

**Review by leonardBang — APPROVED** [review]
Thanks @chucheng92 for the backport, LGTM

**Comment by chucheng92** [comment]
> @chucheng92 please see my comments in the original PR [apache/flink-connector-kafka#8](https://github.com/apache/flink-connector-kafka/pull/8) before merging this one.

yes, i have added it. thanks @RamanVerma

**Comment by chucheng92** [comment]
BP-1.16 ci failure because [FLINK-31477](https://issues.apache.org/jira/browse/FLINK-31477)

**Comment by chucheng92** [comment]
@flinkbot run azure

**Comment by chucheng92** [comment]
@flinkbot run azure

**Review by RamanVerma — APPROVED** [review]
LGTM

**Pull request merged**
