### PR TITLE
[FLINK-15428][e2e] Fix the error command for stopping kafka cluster and exclude kafka 1.10 related test under JDK profile

### PR DESCRIPTION
**Pull request by KarmaGYZ**
## What is the purpose of the change

This PR fix the error command for stopping kafka cluster. This issue cause the failure of retrying execute given command in `retry_times_with_backoff_and_cleanup`.

Besides, as Kafka 0.10 is not compatible with JDK 11, this PR exclude the Avro Confluent Schema Registry nightly end-to-end test when using JDK 11 profile.

## Brief change log

- Fix the error command for stopping kafka cluster
- Exclude the Avro Confluent Schema Registry nightly end-to-end test when using JDK 11 profile

## Verifying this change

Triggle related e2e test.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? no

### CODE REVIEW

**Comment by KarmaGYZ** [comment]
Travis gives green light to relevant test.
https://travis-ci.org/KarmaGYZ/flink/builds/631191277

**Comment by becketqin** [comment]
@flinkbot approve all

**Comment by becketqin** [comment]
Thanks for the patch. LGTM.

**Comment by becketqin** [comment]
It looks that somehow CI tests are in PENDING state even both on Travis and Azure the tests have passed.

**Comment by becketqin** [comment]
merged to both master and release 1.10.

**Pull request closed without merging**
