### PR TITLE
[FLINK-1654] Wrong scala example of POJO type in documentation

### PR DESCRIPTION
**Pull request by chiwanpark**
More detail description and discussion in [JIRA](https://issues.apache.org/jira/browse/FLINK-1654).

### CODE REVIEW

**Comment by tillrohrmann** [comment]
Hi Chiwan, the documentation example is actually working. In order to be treated as a POJO you either need getter/setter or the fields have to be public.

**Comment by StephanEwen** [comment]
Curious why this works.

We should merge this pull request anyways, because it shows the recommended way to do things.

**Comment by chiwanpark** [comment]
As I wrote in JIRA, Fields of Scala class (not case class) are private. ([Reference](http://stackoverflow.com/questions/1589603/scala-set-a-field-value-reflectively-from-field-name)) Because fields declared by `val` keyword don't have setter, Flink TypeExtractor fails to extract information of POJO example in documentation. I attached a result of sample type extraction in [JIRA](https://issues.apache.org/jira/browse/FLINK-1654?focusedCommentId=14348124&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14348124).

Flink TypeExtractor deals with Scala case class differently. Case classes are dealt like Scala tuple.

**Comment by tillrohrmann** [comment]
Then I guess that the Scala API does not identify the ```WordWithCount``` as a POJO but as something different.

**Comment by tillrohrmann** [comment]
Maybe it is treated as a ```GenericType```

**Comment by chiwanpark** [comment]
Yeah. It is treated as a `GenericType`. I think that the example in documentation should be fixed for following POJO requirements.

**Comment by fhueske** [comment]
Thanks for the fix!

**Pull request closed without merging**
