### PR TITLE
[FLINK-2387] add streaming test case for live accumulators

### PR DESCRIPTION
**Pull request by mxm**

### CODE REVIEW

**Comment by StephanEwen** [comment]
How does this PR relate to the recent improvements on the stability of the live accumulator tests?

**Comment by mxm** [comment]
Sorry for the plain description. This pull request adds a test for the streaming part of the live accumulators, i.e. it makes sure that user-defined and Flink internal accumulators work also in streaming programs. The current test only tests the batch side.

The stability of the live accumulator tests should not be affected by this pull request. It uses the same technique as the current (improved) live accumulator tests.

**Comment by StephanEwen** [comment]
Looks good

**Comment by fhueske** [comment]
LGTM, will merge this.

**Comment by fhueske** [comment]
After rebasing to the current master, I had to adapt this PR due to the changes by commit [222245428518d0e1b843947a6184b4a803a78ad5](https://github.com/apache/flink/commit/222245428518d0e1b843947a6184b4a803a78ad5) (replacing ActorRef jobManager by a ActorGateway).
I couldn't merge this PR because one of the Travis builds failed with a NPE in this test: https://travis-ci.org/fhueske/flink/jobs/74219782

This should be investigated.

**Comment by mxm** [comment]
Alright, then let me also rebase and investigate the error. It might be some regression due to rebasing.

**Comment by fhueske** [comment]
Btw. it was just one build that failed with the NPE. 
The other builds passed (except for one with an unrelated issue).

**Comment by mxm** [comment]
I changed the streaming test to reuse the batch test's logic. Should be good to go know. Merging later on.

**Comment by fhueske** [comment]
Did you figure out the reason for the NPE, that prevented me from merging this PR?

**Comment by mxm** [comment]
Yes, it was a race condition that occurred only with the previous streaming test design. The synchronization wouldn't always ensure that the SourceTask had been brought up. Thus we would fail to see any accumulator results for this task.

**Comment by fhueske** [comment]
:-)

**Comment by mxm** [comment]
Yes, exactly :)

**Pull request closed without merging**
