### PR TITLE
Serialized String comparison, Unicode support

### PR DESCRIPTION
**Pull request by zentol**
The StringComparator now works on serialized data.

To this end new string read/write/copy/compare methods were introduced, which use a variable-length encoding for the characters.

~~key-points:~~
  ~~- The most significant bits are written/read first.~~
  ~~- The first 2 bits of the character are used to encode the size of the character.~~
 ~~- A character is at most 3 Bytes big.~~

Additionally, the StringSerializer now has full unicode support. ~~i couldn't find a unicode character that ~~uses more than 22 bits, as such 3 Bytes should be sufficient.~~

### CODE REVIEW

**Comment by fhueske** [comment]
Hi @zentol, @StephanEwen 
What's the status of this PR? Is it still relevant? What is missing to merge it?

**Comment by StephanEwen** [comment]
I am not sure sure about this pull request. The Java Strings already support unicode (interpreting multiple chars as one) and we simply write and read the chars.

I still like serialized string comparison, but that should be in sync with the Java String comparison, which is actually on the char[] model, not on the unicode code point interpretation. Even though both may end up with the same collation, I feat this code makes Flink code deal with unicode code points, without a need to do so.

**Comment by zentol** [comment]
oh well now this has been a while, let's see...

from what i can tell the comparison doesn't work on code points but compares on single bytes, so it should be equivalent to the Java String Comparison. it depends on the serialization code though, so it could not be merged without modifications.

I can only guess why i decided to use codePoints during serialization, i assume it had to with the length of the string. Since some Unicode chars are represented as 2 chars internally just counting the chars written would lead to a wrong result. Here we are also dealing with a CharSequence which doesn't hide the unicode aspect like a String does.

**Comment by zentol** [comment]
I'll close this one; It couldn't be merged in the current state anyway. We can revisit the issue at a later time if need be.

**Pull request closed without merging**
