### PR TITLE
[FLINK-18521][release] Add script for creating snapshot branch

### PR DESCRIPTION
**Pull request by zentol**
Adds a script for creating the release snapshot branches (e.g., release-1.11).

Covers the git branch creation, updates to docs/_config.yml and flink-python/pyflink/version.py.

For testing:
```
export SHORT_RELEASE_VERSION=1.12
export RELEASE_VERSION=1.12.0

cd tools
./releasing/create_snapshot_branch.sh
```

### CODE REVIEW

**Comment by rmetzger** [comment]
I guess you would use this script rather with `RELEASE_VERSION=1.12-SNAPSHOT` instead of `RELEASE_VERSION=1.12.0`? Or am I misunderstanding something?

**Comment by zentol** [comment]
> I guess you would use this script rather with RELEASE_VERSION=1.12-SNAPSHOT instead of RELEASE_VERSION=1.12.0?

That's a good point; I'll adjust it to use ${SHORT_RELEASE_VERSION}-SNAPSHOT where appropriate. I'd like this one to work without having to specify additional variables, if the variables from the release guide have been declared.

**Comment by zentol** [comment]
Actually, none of the fields are supposed to contain `-SNAPSHOT`, as seen in the release-1.10 branch / release guide. So you use the script as is without specifying  anything special, apart from what is written  in the release guide.

**Comment by rmetzger** [comment]
I'm not sure I understand what you are saying.
The script is fine, just the example that you provided confused me, because it created a "release-1.12" branch, where the version was set to "1.12.0" instead of "1.12-SNAPSHOT".

I think you can merge this as-is.

**Comment by zentol** [comment]
> The script is fine, just the example that you provided confused me, because it created a "release-1.12" branch, where the version was set to "1.12.0" instead of "1.12-SNAPSHOT".

The properties shown in the example will be set as part of the usual release process (see the `Create a release branch` section in the [guide](https://cwiki.apache.org/confluence/display/FLINK/Creating+a+Flink+Release).
As such, the example shows what will happen during the normal release process.
You would *not* use it like this: `RELEASE_VERSION=1.12-SNAPSHOT`

**Comment by rmetzger** [comment]
Okay, you are right. I assumed this script was also setting the version in the pom file. However, it doesn't (I should check the code I'm reviewing closer). 
Sorry for the confusion. This is good to go.

**Pull request merged**
