### PR TITLE
[FLINK-4944] Replace Akka's death watch with own heartbeat on the TM side

### PR DESCRIPTION
**Pull request by tillrohrmann**
This PR introduces the HeartbeatActor which is used by the TaskManager to monitor the
JobManager. The HeartbeatActor constantly sends Heartbeat messages to the JobManager
which responds with a HeartbeatResponse. If the HeartbeatResponse fails to be received
for an acceptable heartbeat pause, then the HeartbeatActor sends a HeartbeatTimeout
message to the owner of the HeartbeatActor.

The acceptable heartbeat pause can be extended by the HeartbeatActor if it detects that
it has been stalled by garbage collection, for example.

The HeartbeatActor is started as a child actor of the TaskManager.

Add ClusterOptions

Add comments

### CODE REVIEW

**Comment by tillrohrmann** [comment]
Rebased onto the latest master.

**Comment by tillrohrmann** [comment]
FYI @StephanEwen. Rebased onto the latest master.

**Comment by greghogan** [comment]
@StephanEwen @tillrohrmann is this ready for 1.3?

**Comment by tillrohrmann** [comment]
Not sure whether we want this in or not. It needs at least a review. I've rebased the PR on the latest master.

**Pull request closed without merging**
