### PR TITLE
[FLINK-17264][scripts] Fix broken taskmanager.sh by using -eq to compare num_lines

### PR DESCRIPTION
**Pull request by wangyang0918**
## What is the purpose of the change

Start a taskmanager on Mac via taskmanager.sh will get the following error.

```
wangyang-pc:build-target danrtsey.wy$ ./bin/taskmanager.sh start-foreground [ERROR] Unexpected result ( 1 lines): BASH_JAVA_UTILS_EXEC_RESULT:-Xmx536870902 -Xms536870902 -XX:MaxDirectMemorySize=268435458 -XX:MaxMetaspaceSize=268435456 [ERROR] extractExecutionParams only accepts exactly one line as the input [ERROR] Could not get JVM parameters properly.
```
 

The root cause is FLINK-17023 introduce the following change and it could not work as expected.

```
local num_lines=$(echo "$execution_config" | wc -l)
```
On linux environment, the output is "1". However, on Mac, it is "      1". Maybe we need to add `tr -d '[:space:]'` after `wc`.

## Brief change log

* Add `tr -d '[:space:]'`

## Verifying this change

* Manually test on Mac
* Covered by existing test on linux

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by wangyang0918** [comment]
cc @zentol Could you help to review this simple PR?

**Comment by wangyang0918** [comment]
@zentol I have updated the PR as @aljoscha's suggestion. Use `-eq` instead of `==` for the num comparison.

**Comment by aljoscha** [comment]
I did mean `-ne`. The current code is `if ! [[ ${num_lines} -eq 1 ]]; then`, the `!` is important.

My suggestion was ` if [[ ${num_lines} -ne 1 ]]; then`.

**Comment by wangyang0918** [comment]
Thanks @aljoscha @leonardBang, i have updated the PR to use `-ne`.

**Comment by TsReaper** [comment]
Sorry for introducing this bug in the code. I discover that there are also other scripts (mostly e2e test scripts, for example `test_cli.sh` and `shade.sh`) uses `wc -l` and `==` to compare numbers. Shall we fix them too?

**Comment by leonardBang** [comment]
> Sorry for introducing this bug in the code. I discover that there are also other scripts (mostly e2e test scripts, for example `test_cli.sh` and `shade.sh`) uses `wc -l` and `==` to compare numbers. Shall we fix them too?

The root cause is that tabs alignment https://apple.stackexchange.com/questions/370366/why-is-wc-c-printing-spaces-before-the-number 
If these e2e tests fails in macOS(mostly dev environment), I think we should open a jira to track and repair too.

**Comment by wangyang0918** [comment]
I am not sure how many users are running e2e tests on the Mac. And how many incompatible commands do we have in e2e tests. So maybe we need to create another ticket and have the discussion there.

**Comment by tillrohrmann** [comment]
Thanks for creating this PR @wangyang0918. LGTM. +1 for merging this PR.

**Comment by tillrohrmann** [comment]
Merging this PR now.

**Comment by aljoscha** [comment]
@wangyang0918 I regularly run e2e tests on my mac when debugging issues, so it would be good to also fix those usages. Do you want to open an issue and cut a PR for that? Please ping me if you do.

**Pull request closed without merging**
