### PR TITLE
[FLINK-6710] Remove Twitter-InputFormat

### PR DESCRIPTION
**Pull request by zentol**
This PR removes the twitter InputFormat as it doesn't provide any significant functionality.

### CODE REVIEW

**Comment by rmetzger** [comment]
+1 to remove it (however, please merge this only after at least one other PMC member also +1ed and after some time passed. I don't want to cause any discussions afterwards)

**Comment by zentol** [comment]
sure. no problem.

**Comment by twalthr** [comment]
Maybe we should discuss this on the ML. I know at least one user that used it for fast prototyping a Flink demo application. Maybe it adds not much value but allows for quickly showing a nice streaming demo.

**Comment by zentol** [comment]
Then let's replace it with a generic JsonInputFormat that supports even more use-cases without 1900 lines of bloat.

**Comment by twalthr** [comment]
Yes, a generic JsonInputFormat would be a nice addition.

**Pull request closed without merging**
