### PR TITLE
[FLINK-10175] Fix concurrent access to shared buffer between RocksDBMapState and querable state

### PR DESCRIPTION
**Pull request by StefanRRichter**
## What is the purpose of the change

- Fixing a shared buffer between two threads in `RocksDBMapState`
- Replacing `ByteArrayData[Input|Output]View` with slightly enhanced versions of the already existing `Data[Output|InputDe]Serializer`

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (yes)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by StefanRRichter** [comment]
CC @azagrebin

**Comment by kl0u** [comment]
I was hoping that this also solves https://issues.apache.org/jira/browse/FLINK-10138 but when running it locally, the queryable state end-to-end test still seems to be failing. Any other clues @StefanRRichter or @azagrebin where this may be coming from?

The command to run the test locally is:
```
FLINK_DIR=YOUR_FLINK_DIR ./run-single-test.sh FLINK_DIR/test-scripts/test_queryable_state.sh "rocksdb"
```

**Comment by StefanRRichter** [comment]
@kl0u failing with which exception exactly?

**Comment by kl0u** [comment]
```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed request 73.
 Caused by: java.lang.RuntimeException: Failed request 73.
 Caused by: java.lang.RuntimeException: Error while processing request with ID 73. Caused by: java.lang.ArrayIndexOutOfBoundsException: 17
	at org.apache.flink.core.memory.DataInputDeserializer.readBoolean(DataInputDeserializer.java:123)
	at org.apache.flink.api.java.typeutils.runtime.PojoSerializer.deserialize(PojoSerializer.java:405)
	at org.apache.flink.contrib.streaming.state.RocksDBMapState.deserializeUserValue(RocksDBMapState.java:353)
	at org.apache.flink.contrib.streaming.state.RocksDBMapState.access$100(RocksDBMapState.java:66)
	at org.apache.flink.contrib.streaming.state.RocksDBMapState$RocksDBMapEntry.getValue(RocksDBMapState.java:454)
	at org.apache.flink.queryablestate.client.state.serialization.KvStateSerializer.serializeMap(KvStateSerializer.java:222)
	at org.apache.flink.contrib.streaming.state.RocksDBMapState.getSerializedValue(RocksDBMapState.java:298)
	at org.apache.flink.queryablestate.server.KvStateServerHandler.getSerializedValue(KvStateServerHandler.java:107)
	at org.apache.flink.queryablestate.server.KvStateServerHandler.handleRequest(KvStateServerHandler.java:84)
	at org.apache.flink.queryablestate.server.KvStateServerHandler.handleRequest(KvStateServerHandler.java:48)
	at org.apache.flink.queryablestate.network.AbstractServerHandler$AsyncRequestTask.run(AbstractServerHandler.java:236)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

	at org.apache.flink.queryablestate.server.KvStateServerHandler.handleRequest(KvStateServerHandler.java:95)
	at org.apache.flink.queryablestate.server.KvStateServerHandler.handleRequest(KvStateServerHandler.java:48)
	at org.apache.flink.queryablestate.network.AbstractServerHandler$AsyncRequestTask.run(AbstractServerHandler.java:236)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

	at org.apache.flink.queryablestate.network.AbstractServerHandler$AsyncRequestTask.lambda$run$11(AbstractServerHandler.java:273)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778)
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140)
	at org.apache.flink.queryablestate.network.AbstractServerHandler$AsyncRequestTask.run(AbstractServerHandler.java:236)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.apache.flink.streaming.tests.queryablestate.QsStateClient.getMapState(QsStateClient.java:121)
	at org.apache.flink.streaming.tests.queryablestate.QsStateClient.main(QsStateClient.java:93)
```

**Comment by StefanRRichter** [comment]
Sure, I see that makes sense...same problem of course applies to user key AND user value. Will update the PR.

**Comment by kl0u** [comment]
Perfect! Thanks a lot @StefanRRichter .

**Comment by StefanRRichter** [comment]
Alright, this should do the job.

**Comment by StefanRRichter** [comment]
Thanks for the review @kl0u ! Merging.

**Pull request closed without merging**
