### PR TITLE
[FLINK-19764] Add More Metrics to TaskManager in Web UI

### PR DESCRIPTION
**Pull request by vthinkxie**
## What is the purpose of the change

ref https://issues.apache.org/jira/browse/FLINK-19764

## Brief change log

Add More Metrics to TaskManager in Web UI

## Verifying this change

- visit the TM metrics page
- verify if the TM metrics match the document https://ci.apache.org/projects/flink/flink-docs-release-1.11/ops/memory/mem_setup_tm.html

before:

image

after:

image

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (no needed)

### CODE REVIEW

**Review by XComp — APPROVED** [review]
Thanks for the changes, @vthinkxie. I have minor things:
* The SVG has an asterix (`*`) next to the String `Direct`. Does this have a meaning? If not, I'd say that we remove it.
* There was a request to change the column header `Effective Configuration` to `Configured Values`. The argument was that it's not 100% clear what `effective` means.
* Additionally, there was a request to extend the tooltip to add more information about why Flink cannot gather these metrics. Hence, I'd suggest the following text: `Metrics related to this configuration parameter cannot be monitored. Flink does not have full control over these memory pools.`

FYI: I did a manual test run as well. It looks good. I didn't notice any other issues.

**Comment by vthinkxie** [comment]
Hi @XComp 
fixed, thanks for your comments

**Comment by XComp** [comment]
@vthinkxie confirmed in a private chat that the PR can be merged into master. @rmetzger it would be good if you could take over.

**Comment by rmetzger** [comment]
Thanks. I will check out the PR myself and then maybe merge it.

**Comment by rmetzger** [comment]
I'll merge the change. It works in Safari, Firefox and Chrome.

**Pull request closed without merging**
