### PR TITLE
[FLINK-4934] [gelly] Triadic Census

### PR DESCRIPTION
**Pull request by greghogan**
A triad is any three vertices in a graph. The triadic census produces counts for each of the 4 undirected and 16 directed triad types.

### CODE REVIEW

**Comment by vasia** [comment]
Hi @greghogan,
do we really need a 12k-line csv and a 32k-line csv to test this?

**Comment by greghogan** [comment]
The RMat graph is used across many tests and the intent was to verify the larger tests against secondary frameworks. I have no problem leaving out the files as the command is documented in the base test class.

**Comment by greghogan** [comment]
@vasia the graphs have been removed.

**Comment by vasia** [comment]
Thanks @greghogan. Can you also please update the docs to add the new library methods? It would be nice if you could include what is the triadic census, when it is useful, and usage info.

**Pull request closed without merging**
