### PR TITLE
[FLINK-8489][ES] Prevent side-effects when modifying user-config

### PR DESCRIPTION
**Pull request by zentol**
## What is the purpose of the change

The `ElasticsearchSinkBase` constructor was removing entries from a user-provided collection. We now copy the collection to prevent side-effects.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Looks good, but can this be guarded by a test?

Otherwise I can see a someone in the future going like "oh, I have an idea how to 'optimize' this" and remove that copying operation.

**Comment by zentol** [comment]
I'll add a test where we pass an unmodifiable map to the sink, that should cover it.

**Comment by zentol** [comment]
Added a test for the `ElasticSearchSinkBase` that passes an unmodifiable map containing all properties that we currently try to remove.

I also modified the `ElasticSearchTestBase` to pass an unmodifiable map to the constructors.

**Comment by tzulitai** [comment]
LGTM, once Travis is green.

**Comment by zentol** [comment]
merging,

**Pull request closed without merging**
