### PR TITLE
[FLINK-2591]Add configuration parameter for default number of yarn containers

### PR DESCRIPTION
**Pull request by willmiao**
https://issues.apache.org/jira/browse/FLINK-2591
Add configuration parameter for default number of yarn containers

### CODE REVIEW

**Comment by rmetzger** [comment]
Thanks a lot for opening the pull request.
Can you change the behavior of this a little bit to make the `-n` argument a required argument again? (if the config param is not set)
I think this behavior is the best:
if `yarn.numberOfTaskManagers` == -1 (default value): users have to supply the `-n` argument.
If `yarn.numberOfTaskManagers` is set to `>= 1`, the value will be used by default.
If `yarn.numberOfTaskManagers` is set to `>= 1` and the user specified `-n`, the value of `-n` will have priority.

Can you rename the configuration value to `yarn.defaultNumberOfTaskManagers`?

Can you add a test into the `flink-yarn-tests` which is using a configuration file with `yarn.defaultNumberOfTaskManagers` set to `1` WITHOUT a `-n` argument to see if everything is working as expected?

**Comment by willmiao** [comment]
Thanks for your advices, I'll fix it

**Comment by willmiao** [comment]
Hi rmetzger, I've got a question: what if yarn.defaultNumberOfTaskManagers is set to a invalid value, say -2? Should user have to supply the -n argument?

**Comment by willmiao** [comment]
Hi rmetzger,
 I've got a question: what if yarn.defaultNumberOfTaskManagers is set to a invalid value, say -2? Should users have to supply the -n argument?
I was thinking this behavior may be appropriate:
If yarn.defaultNumberOfTaskManagers < 1 (not set or invalide value): users have to supply the -n argument.
else if the user specified -n, the value of -n will have priority.
else, yarn.defaultNumberOfTaskManagers value will be used by default.

What do you think?

**Comment by rmetzger** [comment]
I agree with your proposal! If `yarn.defaultNumberOfTaskManagers` is set to an invalid value, we should make `-n` required.

**Comment by willmiao** [comment]
I'm sorry that something went wrong with my original repository. So, I open a new PR, and this one will be closed.

**Pull request closed without merging**
