### PR TITLE
[FLINK-5541] Missing null check for localJar in FlinkSubmitter#submit…

### PR DESCRIPTION
**Pull request by zhangminglei**

### CODE REVIEW

**Comment by zhangminglei** [comment]
@tedyu What do you think of this change ?

**Comment by tedyu** [comment]
lgtm

**Comment by zentol** [comment]
checkstyle violation: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project flink-storm_2.11: You have 1 Checkstyle violation. -> [Help 1]

**Comment by zhangminglei** [comment]
Oh my gosh, The newest checkstyle is very awesome, it can detect this kinda message.

**Comment by zhangminglei** [comment]
PR had been updated. Please helps to check again.

**Pull request closed without merging**
