### PR TITLE
[FLINK-23183][connectors/rabbitmq] Fix ACKs for redelivered messages in RMQSource

### PR DESCRIPTION
**Pull request by cmick**
## What is the purpose of the change

This pull request fixes the issue described in FLINK-23183. Currently the redelivered messages are not acknowledged properly upon connection failure (only applicable when autoAck is disabled). When used with a prefetch count in the consumer it may even lead to blocking the source from consuming any more messages.
In the suggested fix, all successfully consumed RMQ messages are be acknowledged, regardless of whether the message is ignored or processed further in the pipeline. In case of redelivered messages, `basicReject` is invoked to acknowledge the message immediately after it's received.

## Brief change log

  - `channel.basicReject` in `RMQSource` is called in case of already processed (and checkpointed) but redelivered messages (e.g. after the job failover)

## Verifying this change

This change added tests and can be verified as follows:

  - `RMQSourceTest#testRedeliveredSessionIDsAck` which tests whether redelivered messages are acknowledged properly
  - `RMQSourceITCase#testMessageDelivery` which tests if the source actually consumes the messages 
  - `RMQSourceITCase#testAckFailure` which reproduces the issue described in FLINK-23183. Exactly-once mode is enabled here (checkpointing and correlationIds) and the source always fails on acknowledgement (but after a successful checkpoint)

The change was also tested on a Flink 1.12 cluster on live data.
 
## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by fapaul — COMMENTED** [review]
Thanks for the fix. The production code change looks very reasonable but I am wondering whether it is possible to add a property integration test in `RMQSourceITCase`. The mockito tests are very complicated already and hard to review. 
WDYT?

**Comment by cmick** [comment]
@fapaul I can write an integration test that would start RabbitMQ, write something to the queue, start Flink job, and check whether all messages are read correctly. So it would effectively test whether the messages are consumed correctly. Is that what you had in mind?

But for this specific problem, I don't know if it would be possible to simulate. For the above to occur, the source must be interrupted (e.g. Flink failure, connection timeout) exactly during the acknowledgment. So, it's easy to mock, but would be difficult repeat in a test. But maybe you would have any suggestion?

**Comment by fapaul** [comment]
My idea is to create an example job that fails on `notifyCheckpointCompleted`  i.e. a custom Map function before the sink. This should prevent the sink from receiving the `notifyCheckpointCompleted` event and the pipeline is restarted.

Overall, I started wondering because the next checkpoint after the job is restarted should acknowledge all the pending records. Can you elaborate a bit more on the prefecht scenario?

**Comment by cmick** [comment]
@fapaul I've added 2 integration tests in 7094db8:
- `testMessageDelivery` - simple test in which we verify that the source actually consumes the messages
- `testAckFailure` - test reproducing the issue described in FLINK-23183 (the worst possible case actually). Exactly-once mode is enabled here (checkpointing and correlationIds) and the source always fails on acknowledgement (I extended this part with custom implementation). This test fails on the current master

What happens exactly, step by step:
1. The source consumes N messages (here N=5 due to prefetchCount set)
2. Checkpoint is triggered and completes, all correlationIds are stored in the checkpoint
3. The source starts the ACK procedure. This may always fail for instance due to connection error. And when it does (here always) we have a problem
4. The job restarts from the last checkpoint
5. RabbitMQ redelivers all N messages (as no ACK was sent) and, after receiving them, the source stops consuming due to prefetchCount set
6. If the redelivered messages are just ignored (as on current master), the job gets stuck and will never process new messages. If the ACK is sent (basicReject in this PR), the transaction is committed on the next checkpoint, and the source resumes normal consume afterwards

So the problem is that the previous implementation (on master) does not send ACK with corresponding `deliveryTag` for some of the messages (it should for all off them). It just ignores them. The initial idea was just to put all message deliveryTags (redelivered or not) into the checkpointed state. This would work, but the proposed solution will have better performance (less state operations) and is semantically correct.

WDYT?

**Review by fapaul — APPROVED** [review]
Thanks a lot for taking the time to add the integration tests.

Can you please squash your two commits to have a single concise one and maybe write a short description in the commit to explain what the change fixes :)

**Comment by cmick** [comment]
@fapaul thanks for review and helpful suggestions. I've rebased on latest master and squashed the commits (I've extended the commit message and this PR description as well).

Exactly the same fix can be applied to 1.12 and 1.13 (no changes) - I've prepared backport fixes for these releases (#16656 and #16657)

**Pull request merged**
