### PR TITLE
[FLINK-26822] Add Source for Cassandra connector

### PR DESCRIPTION
**Pull request by echauchot**
## What is the purpose of the change

Add a flink source for Cassandra database compliant with [FLIP-27](https://cwiki.apache.org/confluence/display/FLINK/FLIP-27%3A+Refactor+Source+Interface)

## Brief change log

Implement everything needed for the source: enumerator, cassandra splits, source reader, split reader etc... + the related unit tests and integration tests.

Moved the annotated Pojo class used in Cassandra batch example to a common place (tests / casssandra utils) to be able to use it with both example and source tests

## Verifying this change

This change added tests and can be verified as follows:
- CassandraSourceITCase: integration test using the new source test framework and a Cassandra test container
- CassandraEnumeratorStateSerializerTest and CassandraSplitSerializerTest:  for serialization tests
- CassandraQueryTest: tests for query generation and query sanity checks
- SplitsGeneratorTest: test for ring ranges creation (use for splits)

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): add connector base and connector test utils
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: adds a new `@Public(Evolving)` API
  - The serializers: add some new ones
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? javadoc

R: @zentol 
CC: @MartijnVisser

### CODE REVIEW

**Comment by echauchot** [comment]
@zentol, I've fixed the architecture tests. Now everything passes.

**Comment by echauchot** [comment]
CC @mzuehlke as you offered help. I'm keeping you updated so that we share maintenance of this connector

**Comment by echauchot** [comment]
> It would be great if @mzuehlke could indeed help out on this due to limited bandwidth at this moment

you mean help reviewing ? I don't know Flink specifics on reviews but can a non-committer give LGTM and then a committer simply merge ?

Anyway I think, as discussed in the ticket that sharing the maintenance of this component is important to avoid the bus factor.

**Comment by MartijnVisser** [comment]
> you mean help reviewing ?

Yes indeed

> I don't know Flink specifics on reviews but can a non-committer give LGTM and then a committer simply merge ?

It could, but the biggest thing that would probably happen is that the committer can verify if the review looks properly so the committers review can be quicker.

**Comment by zentol** [comment]
> I don't know Flink specifics on reviews but can a non-committer give LGTM and then a committer simply merge ?

Correction: No. The committer _must_ check the PR. But as Martijn said it can speed things up.

**Comment by echauchot** [comment]
> > I don't know Flink specifics on reviews but can a non-committer give LGTM and then a committer simply merge ?
> 
> > It could [...]
> 
> Correction: No. The committer _must_ check the PR. But as Martijn said it can speed things up.

Yes this is what I do on Beam project: even though the project accepts that a non-committer reviews, I never merge a PR if I have not reviewed all of it.

**Comment by echauchot** [comment]
Closing, because this PR was moved to the new cassandra dedicated repository: https://github.com/apache/flink-connector-cassandra/pull/3

**Pull request closed without merging**
