### PR TITLE
[hotfix][docs] Fix the incorrect scala checkstyle configure file path

### PR DESCRIPTION
**Pull request by openinx**

### CODE REVIEW

**Comment by openinx** [comment]
@flinkbot run travis

**Comment by openinx** [comment]
The document change should not affect the CI test. Any other concerns ? @rmetzger

**Comment by openinx** [comment]
Ping @KurtYoung @rmetzger @wuchong , Please help to merge this PR. Thanks.

**Comment by KurtYoung** [comment]
Thanks for fixing this @openinx , merging this...

**Pull request merged**
