### PR TITLE
[FLINK-6788]:Remove unused GenericFlatTypePostPass/AbstractSchema class

### PR DESCRIPTION
**Pull request by wangmiao1981**
Removed two unused classes by deleting corresponding files.

Build Success. Run `mvn clean verify` Optimizer module  and existing other tests are passed.

### CODE REVIEW

**Comment by wangmiao1981** [comment]
retest please

**Comment by zentol** [comment]
We are aware that some tests are unstable; we don't need to re-run travis.

Could you rework your branch so that it doesn't include a merge commit by re-basing it on-top of the current master? Thank you.

**Comment by wangmiao1981** [comment]
@zentol Thanks for your time! It is strange that it includes a merge. Let me rebase my branch and push again.

**Comment by zentol** [comment]
Much better. Are you aware that the commit will not be attributed to your github account (because the username/email aren't in sync between your local git and your account)?

The changes themselves are good to merge though.

**Comment by wangmiao1981** [comment]
let me do one more thing to set git user and git email. Just a second. I am using a new laptop now :)

Thanks!

**Comment by wangmiao1981** [comment]
flink_ws_05_31 m.wang$ git config --list
....
remote.origin.url=git@github.com:wangmiao1981/flink.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
remote.upstream.url=git@github.com:apache/flink.git
remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
user.name=wangmiao1981
user.email=wm624@hotmail.com

I pushed again. Above is my local username and email setup. 

Are they synced now?

Thanks!

Miao

**Comment by zentol** [comment]
You still have to re-create the commit so the settings are applied to it.

I would do it like this:
```
git reset HEAD^
git add *
git commit
```

**Comment by wangmiao1981** [comment]
I did one revert and recommit. Is it acceptable now?

**Comment by zentol** [comment]
well it's ok, but now you could just remove the first 2 commits in the branch. :D

**Comment by wangmiao1981** [comment]
It seems that I massed up this PR. 

Let me close it and resubmit a new PR.

**Pull request closed without merging**
