### PR TITLE
[FLINK-7483][blob] prevent cleanup of re-registered jobs

### PR DESCRIPTION
**Pull request by NicoK**
## What is the purpose of the change

Since #4238, when a job is registered but was released before and the ref count hit `0`, its cleanup timeout was not reset. This fixes that and adds more reference-counter tests.

## Brief change log

- reset the cleanup timeout after job re-registration
- add a test for verifying the reference counters contain the expected values

## Verifying this change

This change added a test for verifying reference counter values: `BlobCacheCleanupTest#testJobReferences`.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by NicoK** [comment]
@tedyu this fixes the two issues you found in #4238. Could you have a quick look, also?

**Comment by NicoK** [comment]
FYI: the test instability of `JobManagerCleanupITCase` will be fixed by #4358, the next BLOB-PR in line - I don't want to mess up the following PRs anymore (again) by integrating it separately or here

**Comment by tedyu** [comment]
lgtm

**Comment by NicoK** [comment]
will be fixed by #4358

**Pull request closed without merging**
