### PR TITLE
[FLINK-32705][connectors/common] Remove the beta for watermark alignment

### PR DESCRIPTION
**Pull request by 1996fanrui**
Remove the beta for watermark alignment at doc

### CODE REVIEW

**Comment by 1996fanrui** [comment]
Thanks @pnowojski for the quick review.

I added a new commit to remove the `Experimental`, does it make sense?

**Review by 1996fanrui — COMMENTED** [review]
Thanks @pnowojski for the quick review.

I added a new commit to upgrade the `Experimental` to the `PublicEvolving`, does it make sense?

**Comment by 1996fanrui** [comment]
The actual CI passed, and the uploading log and caching docker image failed.

**Comment by 1996fanrui** [comment]
@flinkbot run azure

**Comment by 1996fanrui** [comment]
@flinkbot run azure

**Comment by 1996fanrui** [comment]
@flinkbot run azure

**Comment by 1996fanrui** [comment]
I will merge this PR tomorrow if no any other comments.

**Review by mas-chen — APPROVED** [review]
I've also tested internally with a few use cases. Thanks for the idleness bug fixes!

**Pull request merged**
