### PR TITLE
[FLINK-36004] Deep copy the BinaryArrayData in ArrayDataSerializer#copy while using custom ArrayData

### PR DESCRIPTION
**Pull request by xuyangzhong**
## What is the purpose of the change

*The method `copy` in Flink’s `ArrayDataSerializer` does not return the expected copied data for the custom `ArrayData`, but instead reuses its internal data. This pr tries to fix it.*

## Brief change log

  - *copy the result in ArrayDataSerializer#copy while using custom ArrayData*
  - *add tests*

## Verifying this change

Tests are added to verify this change.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented?

### CODE REVIEW

**Review by prm-xingcan — APPROVED** [review]

**Review by xccui — APPROVED** [review]
LGTM. Also, did you check other serializers to see if they have similar issues?

**Comment by xuyangzhong** [comment]
Hi, @xccui . I have check all subtasks of TypeSerializer. There’s a class `MapDataSerializer` that seems to exhibit the same issue pattern but operates correctly. I have also added the relevant tests for it.

**Comment by xccui** [comment]
Btw, Jingsong mentioned that the bug has been fixed in Paimon a few months ago and they forgot to port it back to Flink :sweat_smile:
https://github.com/apache/paimon/blob/master/paimon-common/src/main/java/org/apache/paimon/data/serializer/InternalArraySerializer.java

**Comment by xuyangzhong** [comment]
Hi, @xccui I have bp this fix to 1.20 and 1.19. You can take a look if you have time. 
1.20: https://github.com/apache/flink/pull/25208
1.19: https://github.com/apache/flink/pull/25209

**Pull request merged**
