### PR TITLE
[FLINK-15517][Runtime][Configuration][Network] Use back 'network' in 'shuffle' memory config option names

### PR DESCRIPTION
**Pull request by azagrebin**
## What is the purpose of the change

As there is no strong consensus about using new 'shuffle' naming for memory config options. We decided to fallback to the the existing naming and use 'network' instead of 'shuffle'. We still keeping the new naming convention with prefix 'taskmanager.memory.*'.

## Brief change log

Basically, we just need to rename 'taskmanager.memory.shuffle.' to 'taskmanager.memory.network.' as 'shuffle' naming has never been released and adjust docs/comments.

Replacements:
- memory.shuffle -> memory.network
- s(S)huffleMemory -> n(N)etworkMemory
- s(S)huffle m(M)emory -> n(N)etwork m(M)emory

## Verifying this change

trivial renaming

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (docs / JavaDocs)

### CODE REVIEW

**Comment by azagrebin** [comment]
cc @xintongsong

**Comment by xintongsong** [comment]
Found occurrences of "taskmanager.memory.shuffle.*" in flink-dist/src/main/resources/flink-conf.yaml

**Comment by azagrebin** [comment]
Thanks for the reviews @tillrohrmann @xintongsong 
Indeed, now I also replaced "memory.shuffle" with "memory.network"

**Comment by azagrebin** [comment]
Thanks for the reviews @tillrohrmann @xintongsong 
merged into master by 7513d9b184feffdcb6e0c09d1b74f8de21a98e81
merged into 1.10 by a6023e6953189ece1bb8fbb7bc3e117172ad5264

**Pull request closed without merging**
