### PR TITLE
[FLINK-4236] fix error handling for jar files with no main method

### PR DESCRIPTION
**Pull request by mxm**
This change shows only entry classes with a valid main method. It
ignores classes which contain no main method.

### CODE REVIEW

**Comment by zentol** [comment]
+1

**Comment by StephanEwen** [comment]
Merging this...

**Comment by StephanEwen** [comment]
Actually, not merging. This fails due to checkstyle violations.

**Comment by mxm** [comment]
Merging this after a Checkstyle fix.

**Pull request closed without merging**
