### PR TITLE
[FLINK-25801][ metrics]add cpu processor metric of taskmanager

### PR DESCRIPTION
**Pull request by Kwafoor**
## What is the purpose of the change
This PR add container access cpu processor metric.

## Brief change log
  - add container access cpu processor metric.

## Verifying this change
  - This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:
  - Dependencies (does it add or upgrade a dependency): ( **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( **no**)
  - The serializers: (**no** )
  - The runtime per-record code paths (performance sensitive): (**no** )
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: ( **no** )
  - The S3 file system connector: ( **no** )

## Documentation
  - Does this pull request introduce a new feature? (**yes** )
  - If yes, how is the feature documented? (**docs**)

### CODE REVIEW

**Comment by knaufk** [comment]
@zentol what do you think about this change?

**Comment by Kwafoor** [comment]
This change to display flink application cpu resources used so the user can know and adjust flink resources. This feature is particularly useful if multiple applications share resources in cluster like yarn.

**Comment by Kwafoor** [comment]
> This change to display flink application cpu resources used so the user can know and adjust flink resources. This feature is particularly useful if multiple applications share resources in cluster like yarn.

```
metrics.<Double, Gauge<Double>>gauge("Load", mxBean::getProcessCpuLoad);
metrics.<Long, Gauge<Long>>gauge("Time", mxBean::getProcessCpuTime); 
```
The metrics above is about how much resources flink taskmanager used in machine not cluster.If machine is not same in cluster, it's too hard to know how cores flink used in cluster, the machine cores is different.
And by this change, user can calculate the cpu efficiency of flink application.

**Comment by zentol** [comment]
This to me sounds more like something that should be logged; we generally avoid exposing inherently constant values as metrics.

**Comment by Kwafoor** [comment]
> This to me sounds more like something that should be logged; we generally avoid exposing inherently constant values as metrics.

Not inherently constant values.This metric likes taskmanager  current used cores.To give advice to adjust taskmanager instances param.

**Comment by zentol** [comment]
I don't see what that gives you though. if the existing load metric is close to 1 you already know that an increase of the number of CPU cores could make sense. Multiplying the load by a constant factor doesn't really get you anything imo.
If you _actually_ want to determine CPU bottlenecks, then https://nightlies.apache.org/flink/flink-docs-release-1.14/docs/ops/metrics/#system-resources is a better suited anyway.

**Comment by Kwafoor** [comment]
> I don't see what that gives you though. if the existing load metric is close to 1 you already know that an increase of the number of CPU cores could make sense. Multiplying the load by a constant factor doesn't really get you anything imo. If you _actually_ want to determine CPU bottlenecks, then https://nightlies.apache.org/flink/flink-docs-release-1.14/docs/ops/metrics/#system-resources is a better suited anyway.

If multiple applications share resources in cluster like yarn, overall CPU usage on the machine and cpu load is meaningless.All we need to know is how much resources flink used and how efficiency it is.
On one machine is a constant factor but in cluster machine core is different.

**Pull request closed without merging**
