### PR TITLE
[FLINK-3207] [gelly] adds the vertex-centric iteration abstraction

### PR DESCRIPTION
**Pull request by vasia**
As per the mailing list discussion, this PR adds the vertex-centric / pregel iteration abstraction to gelly. In this model, superstep computation happens inside a single UDF, which has access to received messages, can update the vertex state and can generate messages for other vertices. Documentation is also updated with a comparison among available iteration options.

### CODE REVIEW

**Comment by s1ck** [comment]
Hi @vasia this is a nice PR, I commented some minor documentation / naming issues
+1 for merging

**Comment by vasia** [comment]
Hey @s1ck,
thanks a lot for the thorough review! I will address your comments in the following days. The PR is quite old and needs a rebase, too.
For future reviews, keep in mind that it might be better to leave comments on the file diff of the PR instead of commenting on each individual commit. This way replying is easier, comments appear at one place, and the reviewer has the final changed view instead of the partial changes of each commit :)

**Comment by s1ck** [comment]
Ok, I will keep that in mind. Thank you!

**Comment by vasia** [comment]
Hey @s1ck,
thanks a lot for the valuable feedback. I've addressed your comments and rebased on the current master. Regarding the method renamings, I suggest we handle them in a separate issue.

**Comment by vasia** [comment]
Anyone else wants to take a look at this PR or shall I go ahead and merge?

**Comment by vasia** [comment]
I'll merge this today.

**Pull request closed without merging**
