### PR TITLE
[FLINK-28797][hive] HiveSource enables verctor reading for complex da…

### PR DESCRIPTION
**Pull request by luoyuxia**
…ta type with parquet format

## What is the purpose of the change
Enable Hive source verctor reading for complex data with  parquet format.

## Brief change log
- When it's ARRAY/MAP/ROW, `isVectorizationUnsupported` change to return fa;se since Flink's parquet format has supported these types.

## Verifying this change
IT in [HiveTableSourceITCase#testReadParquetComplexDataType](https://github.com/apache/flink/pull/20481/files#diff-e7e74972bb3dbbd76ce12f31dd2315433102943a1bf6ae15deac4f648cfc228aR161)

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Review by wuchong — APPROVED** [review]
LGTM.

**Comment by hackeryard** [comment]
@luoyuxia parquet format has supported complex types for verctor reading, but is it released to specific parquet lib version? maybe lower version is not supported.

**Comment by luoyuxia** [comment]
@hackeryard Do you mean our flink parquet format lib? Yes, we need flink 1.16 for complex types with vector reading.

**Comment by hackeryard** [comment]
@luoyuxia yes, flink-1.11 is use parquet format version 1.10.0, and flink-1.16 is using 1.12.2, does 1.10.0 not supported this?

**Comment by luoyuxia** [comment]
@hackeryard I believe 1.10.0 is also supported.

**Pull request merged**
