### PR TITLE
[hotfix] [doc] Fix typo in zh/docs/dev/datastream/overview.md

### PR DESCRIPTION
**Pull request by xuzhiwen1255**
## What is the purpose of the change
Fix typo in zh/docs/dev/datastream/overview.md

##  Brief change log
Fix typo(setp -> step) in overview.md

##  Does this pull request potentially affect one of the following parts:
Dependencies (does it add or upgrade a dependency): no
The public API, i.e., is any changed class annotated with @Public(Evolving): no
The serializers: no
The runtime per-record code paths (performance sensitive): no
Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
The S3 file system connector: no

##  Documentation
Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by xuzhiwen1255** [comment]
@XComp  Hi,#21936 was accidentally closed when I withdrew the submission, I reopened a pr, is the format correct now? Sorry, please forgive my mistake, because it is the first time I have contributed to flink, some processes are not too familiar.thanks for your guidance,thanks for your guidance.

**Comment by reswqa** [comment]
Thanks @xuzhiwen1255 for the contribution. You should change your commit message to `[hotfix][doc] Fix typo in zh/docs/dev/datastream/overview.md`.

**Comment by xuzhiwen1255** [comment]
@reswqa  Thank you for your review. It has been revised.

**Review by reswqa — APPROVED** [review]

**Comment by XComp** [comment]
No worries, @xuzhiwen1255. Again, you might want to read through the contributions documentation (see the [Apache Flink Wiki](https://cwiki.apache.org/confluence/display/FLINK/Contributors) and the [How to Contribute section of the Flink docs](https://flink.apache.org/contributing/how-to-contribute.html)) before going ahead. It might be also helpful to review these docs through your eyes as a new contributor. Because the feedback of new contributors is helpful to identify flaws in the documentation.

On code contributions: Checking how other PRs look might help as well.

**Comment by xuzhiwen1255** [comment]
@XComp  Thank you, I understand. Later I will read the contribution document and understand the process related to the contribution code.
Thank you for your review.

**Comment by XComp** [comment]
Starting as a new contributor is kind of challenging and can be frustrating. I didn't mean to encourage you with my comments but wanted to give you some pointers that might help you in improving. Thanks for your contribution. :-)

**Pull request merged**
