### PR TITLE
[FLINK-6466] [build] Build Hadoop 2.8.0 convenience binaries

### PR DESCRIPTION
**Pull request by greghogan**
Add Hadoop 2.8 to the create_release_files.sh script and TravisCI test matrix.

Hadoop updated the `httpclient` and `httpcore` dependency versions in ticket 12767 so Flink shading must not specify the old versions.

### CODE REVIEW

**Comment by greghogan** [comment]
@rmetzger @StephanEwen thoughts on releasing 2.8 binaries for Flink 1.3? Are there old versions we can drop for 1.4?

**Comment by StephanEwen** [comment]
I think the convenience binaries are fine. From my side, we can drop convenience builds for Hadoop 2.3 builds in Flink 1.3

Concerning the dependency management entry for `http*`- I think I added that to bump the versions that are pulled by older Hadoop versions (because there were issues). Can you try to bump the version to the latest, rather than removing it from the dependency management section?

**Comment by greghogan** [comment]
@StephanEwen changes made, and I rebased back a few commits for stable tests and also made yarn-tests non-optional.

**Comment by rmetzger** [comment]
I personally think we should not include this into the 1.3 release.
Hadoop 2.8 most likely has new or changed dependencies, with different transitive deps and so on. This can cause issues with our dependency exclusions or shading.

But I'm happy to merge this to `master` for 1.4.

**Comment by greghogan** [comment]
@rmetzger +1, agree that these changes are best made at the beginning of the release cycle.

**Comment by StephanEwen** [comment]
+1 for 1.4 - just spent some good time cleaning up dependencies (also from Hadoop) and this will almost certainly require to do another such pass...

**Comment by greghogan** [comment]
Merging ...

**Pull request closed without merging**
