### PR TITLE
[FLINK-2930] Respect ExecutionConfig execution retry delay

### PR DESCRIPTION
**Pull request by uce**
This only affects job recovery on non-master failures.

### CODE REVIEW

**Comment by StephanEwen** [comment]
This looks like a pretty big issue, actually.
+1 to merge this.

Might not be a release blocker, but if there is another RC, I would add this.

**Comment by tillrohrmann** [comment]
+1, I also stumbled across the problem when I showed Aljoscha's demo at the Flink meetup in Paris.

**Comment by mxm** [comment]
@uce Builds seems to be failing. Can you look into it?

**Comment by uce** [comment]
The problem is that the retries are hard coded in some other places. It was only working before this change, because it was actually not picked up anywhere. I will remove the hard coded parts. Also, I'm removing the getters and setters from the Environment. I don't think that it is the right place. We should keep it in the ExecutionConfig only.

**Comment by uce** [comment]
I've also added FLINK-2958 in this PR.

What's your opinion about FLINK-2959?

**Comment by mxm** [comment]
Thanks for fixing. Merging commits for FLINK-2930 and FLINK-2958.

**Pull request closed without merging**
