### PR TITLE
[hotfix] Ignore Hugo Module files

### PR DESCRIPTION
**Pull request by MartijnVisser**
## What is the purpose of the change

* Make sure that Hugo Modules files (which can be created while working on the current `master` branch) will be ignored when working with the currently support `release-1.15` and `release-1.14` branches

## Brief change log

* Updated .gitignore

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Review by zentol — COMMENTED** [review]
maybe remove leading slash (because it's a bit weird even if it works...)

**Review by zentol — APPROVED** [review]

**Comment by MartijnVisser** [comment]
> maybe remove leading slash (because it's a bit weird even if it works...)

We also have those in for other ignores in the `docs` folder:

```
/docs/api
/docs/.bundle
/docs/.rubydeps
/docs/ruby2/.bundle
/docs/ruby2/.rubydeps
/docs/.jekyll-metadata
```

**Comment by zentol** [comment]
I saw that; it's still weird :P

**Comment by MartijnVisser** [comment]
> I saw that; it's still weird :P

OK, fixed them all in one go

**Pull request merged**
