### PR TITLE
[FLINK-6569] flink-table KafkaJsonTableSource example doesn't work.

### PR DESCRIPTION
**Pull request by haohui**
This PR makes the proposed changes on the document and changes the Java unit tests to reflect the suggested usages of the API.

### CODE REVIEW

**Comment by rmetzger** [comment]
Thank you for addressing this so quickly.
+1 from my side.

**Comment by twalthr** [comment]
-1
@haohui The examples are correct if you use Types class of the Table API: `org.apache.flink.table.api.Types`

**Comment by haohui** [comment]
My understanding is that the snippet should only depend on the Java version of the API (`ROW_NAMED` in flink-core) instead of the one written in Scala that resides in `flink-table`. Correct?

**Comment by twalthr** [comment]
The Java version of the API also depends on the Scala classes of `flink-table`. Everything in `org.apache.flink.table.api` is used in both languages. `org.apache.flink.table.api.scala/java` contain language specific classes.

**Comment by twalthr** [comment]
@haohui can you close this PR?

**Pull request closed without merging**
