### PR TITLE
[FLINK-24538][runtime][tests] Fix ZooKeeperLeaderElectionTest.testLeaderShouldBeCorrectedWhenOverwritten fails with NPE

### PR DESCRIPTION
**Pull request by xmarker**
## What is the purpose of the change

*Fix ZooKeeperLeaderElectionTest.testLeaderShouldBeCorrectedWhenOverwritten fails with NPE*

## Brief change log

  - *Use a local function variable to store the value polled from leaderEventQueue in CommonTestUtils.waitUntilCondition lambda in case instance field changes*

## Verifying this change

*(Please pick either of the following options)*

This change added tests and can be verified as follows:

  - *Use old ZooKeeperLeaderElectionTest.testLeaderShouldBeCorrectedWhenOverwritten unit test*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Review by dmvk — CHANGES_REQUESTED** [review]
Thanks for the PR @xmarker. Sorry this haven't been reviewed earlier. My biggest concern is that the PR doesn't seem to cover all scenarios (eg. `waitForEmptyLeaderInformation` is still prone to the same race condition).

The main problem is in a race condition, where the `leader` property is being assigned by multiple threads without synchronization. There already seems to be the proper mechanics in place to solve this using blocking queues.

I'm wondering, could the fix be as simple as the snippet bellow?

```diff
diff --git a/flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingRetrievalBase.java b/flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingRetrievalBase.java
index f32440199bb..02b131da5a7 100644
--- a/flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingRetrievalBase.java
+++ b/flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingRetrievalBase.java
@@ -118,7 +118,6 @@ public class TestingRetrievalBase {
 
     public void offerToLeaderQueue(LeaderInformation leaderInformation) {
         leaderEventQueue.offer(leaderInformation);
-        this.leader = leaderInformation;
     }
 
     public int getLeaderEventQueueSize() {
```

**Comment by dmvk** [comment]
cc @wangyang0918

**Comment by wangyang0918** [comment]
Sorry for the late response. @dmvk I think your suggestion makes sense to me. Then we will have only one place `waitForNewLeader` or `waitForEmptyLeaderInformation` to update the `leader`.

@xmarker WDYT?

**Comment by XComp** [comment]
Closing this PR in favor of PR #19041

**Pull request closed without merging**
