### PR TITLE
[FLINK-1656] Filter ForwardedField properties for group-at-a-time operators in Optimizer

### PR DESCRIPTION
**Pull request by fhueske**
Restricts forward field information for group-wise operators.

- For `GroupReduce`, `GroupCombine`, and `CoGroup` operators forward field information is restricted to grouping key fields.
- For `MapPartition` operators all forwarded field information is discarded.

Extended documentation accordingly.

### CODE REVIEW

**Comment by StephanEwen** [comment]
I think this is good to fix this.

I was wondering now whether we can actually solve this a bit more global/local property specific. Cancelling out the properties from the non-key fields was originally motivated by the fact that the group operation destroys orders/groupings, which are actually local properties.

Is there a way we can preserve the global properties still? 

What would happen if we move the new code that "cleans" the semantic properties from the API operators to the optimizer's operator descriptor. There we can filter the local properties and global properties independently.

The main benefit is probably to preserve the global properties for `mapPartition()`, which is desirable.

**Comment by fhueske** [comment]
Yes, I agree. The fix is more conservative than necessary.
I think we can safely relax it if we make the rule for forwarded fields on group-wise operators as follows:

*"All forwarded fields of an emitted record must be forwarded from the same input record. Each output record can have forwarded values from a different input record."*

This allows to preserve partitionings (also on composite keys) but voids all grouping / sorting on non-key fields because the order of the emitted records is not specified.

**Comment by StephanEwen** [comment]
Good catch, that is a critical distinction (one output record forwarded from same input record). Mostl relevant to MapPartition, though.

**Comment by fhueske** [comment]
Do you think this rule is "easy enough" for users? 
It would make the handling consistent for all group-wise operators.

**Comment by fhueske** [comment]
I updated the PR as discussed:
- GlobalProperties are filtered with the user-specified semantic properties.
- LocalProperties for are filtered with forward field info for key fields only (sorting/grouping can only be preserved for key fields and is completely destroyed for key-less operators such as AllReduce or MapPartition).

Documentation is adapted accordingly.

**Comment by fhueske** [comment]
Will merge this in about 24h unless somebody raises a flag.

**Pull request closed without merging**
