### PR TITLE
[FLINK-32496][connectors/common] Fix the bug that source cannot resume after enabling the watermark alignment and idleness

### PR DESCRIPTION
**Pull request by 1996fanrui**
backport FLINK-32496 to 1.17

### CODE REVIEW

**Comment by 1996fanrui** [comment]
Hi @RocMarshal @mas-chen , this is the backporting of FLINK-32496 for release-1.17. Could you help take a look this PR in your free time? thanks~

**Review by mas-chen — APPROVED** [review]
+1, sorry I missed this one

**Review by RocMarshal — APPROVED** [review]
LGTM+1 👍 , thanks~!

**Comment by 1996fanrui** [comment]
Thanks @mas-chen  and @RocMarshal  for the review, merging~

**Pull request merged**
