### PR TITLE
[FLINK-28395][Connectors/ElasticSearch] fix create table and query do…

### PR DESCRIPTION
**Pull request by dingweiqings**
## What is the purpose of the change

 Fix test case error  about create table/query document in elasticsearch 6  

## Brief change log
1. add await api on creating table , make sure create table happen before querying document 

## Verifying this change
I have run test case several times and get passed result

*(Please pick either of the following options)*

none

## Does this pull request potentially affect one of the following parts:

none

## Documentation

none

### CODE REVIEW

**Comment by dingweiqings** [comment]
@flinkbot run azure

**Comment by HuangXingBo** [comment]
Thanks a lot for the PR. Could you rebase the newest `master` branch and push again

**Comment by dingweiqings** [comment]
Of course

**Comment by dingweiqings** [comment]
use https://github.com/apache/flink/pull/20608 instead ,so close it

**Pull request closed without merging**
