### PR TITLE
Minor cleanup of Java example code for AsyncFunctions

### PR DESCRIPTION
**Pull request by kkrugler**
Use `CompletableFuture` correctly, via `.supplyAsync()` wrapping `Future.get()`

### CODE REVIEW

**Comment by kkrugler** [comment]
BTW, how do people check .md editing results before pushing? I've tried a few different plugins and command line utilities, but the mix of HTML and markdown has meant none of them render properly.

**Comment by kkrugler** [comment]
Hi @tedyu - not able to assign you as a reviewer, I guess I would need more Git fu to be able to do that.

**Comment by tedyu** [comment]
lgtm

**Comment by StephanEwen** [comment]
Thanks a lot!

Merging this in the next merge batch...

**Pull request closed without merging**
