### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by chenliag613**
add script for setting network proxy for git clone to connect network.
Currently many company's network need use proxy, the script is useful for new users.

### CODE REVIEW

**Comment by chiwanpark** [comment]
Hi, Thanks for your contribution. But I think this PR is not necessary because the change is not specific to Flink but about the general of git.

**Comment by mxm** [comment]
Thanks @chenliag613 for the pull request!

I agree with @chiwanpark. If you're behind a proxy then you probably already know how to work with it. There are also other ways to use a proxy with Git (e.g. external tools or operating system tools). Also, you're assuming a http proxy which is just one type of proxy. For example, it could also be a SOCKS proxy protocol. Furthermore, you're sending the username and password in plain text if you use this command. Depending on the network you're in, this could enable someone to steal your account data.

**Comment by chenliag613** [comment]
Thanks @chiwanpark @mxm .

**Comment by mxm** [comment]
Thank you. Feel free to open another pull request!

**Pull request closed without merging**
