### PR TITLE
[FLINK-16168][build] Add build-debug profile

### PR DESCRIPTION
**Pull request by zentol**
Adds a `debug-build` profile for convenience that prints a dependency tree and shows active profiles.

### CODE REVIEW

**Comment by StephanEwen** [comment]
I would like to understand what information this gives us that other commands don't give us.

For the dependency printing, does this give you a different output than `mvn dependency:tree`?
Or is that to show the trees in all projects?

Similar for active profiles, can't you get this by invoking a specific target from the command line as well?

**Comment by zentol** [comment]
It's not different to invoking things from the command-line, but  it provides an easy hook to activate these plugins when running on travis.

**Comment by zentol** [comment]
Beyond that this also is a nice pointer for people who aren't so familiar with maven.

**Comment by StephanEwen** [comment]
In that case, it would be nice to keep it out of the `pom.xml`, in my opinion. That file is already overflowing, and this seems like a rare tool for which an almost equal alternative exists.

**Pull request closed without merging**
