### PR TITLE
[FLINK-19671][codestyle] Revert .editorconfig change violating our coding style

### PR DESCRIPTION
**Pull request by pnowojski**
https://flink.apache.org/contributing/code-style-and-quality-formatting.html#breaking-the-lines-of-too-long-statements

> Rules about breaking the long lines:
>
> Break the argument list or chain of calls if the line exceeds limit or earlier if you believe that the breaking would improve the code readability
> If you break the line then each argument/call should have a separate line, including the first one
> Each new line should have one extra indentation (or two for a function declaration) relative to the line of the parent function name or the called entity

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by StephanEwen** [comment]
Thanks for spotting this.

Is it also an option to adjust the written coding style?

I think that having the extra indentation for continuation helps to separate it from the general method body. I remember seeing this appreciated by many other devs during reviews.

**Comment by pnowojski** [comment]
There was a lot of discussions around this topic:
- in the ticket itself
- in two mailing lists discussions referenced in the ticket
- some offline discussion between me @zentol and @aljoscha 

Generally speaking, I'm fine with changing this to double indentations, but let's change the code style first and me and @zentol are against a gradual change (we would prefer to reformat the whole code base at once)

**Comment by StephanEwen** [comment]
Fine by me. I think reformatting the code base makes only sense in combination with adding a checkstyle rule, otherwise it will not have a lasting effect and we pay the merge conflict price for a not-so-great outcome.

**Comment by aljoscha** [comment]
I still maintain that the `.editorconfig` file was good as is: Out of the box, you got a setup with import ordering and code style that worked and passed our checkstyle and that quite some people already use anyways. That was better than what we had before.

With this change all indentation is now only 1 level which is not very helpful.

(The code base is not consistent when it comes to indentation and with this config it would mean that new people would start producing a consistent style.)

**Pull request merged**
