### PR TITLE
[FLINK-14302] [kafka] FlinkKafkaInternalProducer should not send `ADD_PARTITIONS_TO_TXN` request if `newPartitionsInTransaction` is empty when enable EoS

### PR DESCRIPTION
**Pull request by tony810430**
## What is the purpose of the change

FlinkKafkaProducer will failed when commit without any data and its transaction coordinator changed. It is due to that client didn't get error message from kafka cluster. However, the root cause is that we shouldn't send `ADD_PARTITIONS_TO_TXN` request if `newPartitionsInTransaction` is empty. So, this PR aims to fix that.

## Brief change log
- Check `newPartitionsInTransaction` in kafka producer is empty before sending `ADD_PARTITIONS_TO_TXN` request to kafka cluster.

## Verifying this change

 - Introduce a new IT case to reproduce this bug, and make sure this patch can pass this test.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): don't know
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: don't know
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not documented

### CODE REVIEW

**Comment by tony810430** [comment]
@flinkbot

**Comment by tony810430** [comment]
@becketqin I have tried this [commit](https://github.com/tony810430/flink/commit/4f6473cdfda7e918075f21a61f961964301a2d5e) to simulate the case, but I failed to reproduce it on my local IDE. The leader indeed be migrated, but the exception didn't happen like I tried in the real kafka cluster. Did you know why? Since I couldn't get log message from TransactionCoordinator in embedded kafka cluster, I didn't know if `NOT_COORDINATOR` error really happened in broker.

**Comment by becketqin** [comment]
@tony810430 Have you tried to configure the log4j by modifying the log4j.properties (or log4j-test.properties) file under the test resource folder?

**Comment by tony810430** [comment]
hi @becketqin 
Thank you for your hints. I have reproduced this exception by using flink tests on my machine.
The first commit makes sure the error will happen, and the second commit is the original patch that aimed to solve this problem.

**Comment by tony810430** [comment]
hi @becketqin, do you have free time to review this PR? I have done the test as you suggested.

**Comment by becketqin** [comment]
@tony810430 Sorry for the late response, I have been traveling quite a bit recently. Will review the PR in one day or two. Thanks.

**Comment by becketqin** [comment]
@tony810430 Sorry, I missed that. Thanks for the patch. Merged to master.

**Pull request merged**
