### PR TITLE
[FLINK-2877] Move Streaming API out of Staging package

### PR DESCRIPTION
**Pull request by aljoscha**

### CODE REVIEW

**Comment by StephanEwen** [comment]
GitHub sync is lagging behind, so only one commit (the latest) in the PR is relevant, the others are already committed.

**Comment by StephanEwen** [comment]
Looks pretty straightforward. Some diffs are displayed probably because of git bugs / limitations. As this was discussed on the mailing list before and all agreed, this should be good.

Only point of discussion could be names. I personally like the names `flink-streaming-java` and `flink-streaming-scala`, so +1 from my side

**Comment by fhueske** [comment]
+1 for `flink-streaming-java` and `flink-streaming-scala`

**Comment by aljoscha** [comment]
Manually merged

**Pull request closed without merging**
