### PR TITLE
[FLINK-29074][Connectors/JDBC] Fix ClassNotFound exception when using jdbc connector by add jar syntax

### PR DESCRIPTION
**Pull request by lsyldliu**
## What is the purpose of the change

*Since [FLINK-15635](https://issues.apache.org/jira/browse/FLINK-15635), in order to solve the class conflict problem, we introduce a user classloader in the table module, this classloader focus on loading the user class. So if the connector is added to TableEnvironment by add jar syntax, the class load behavior in the connector should also use the user classloader, otherwise, maybe occur ClassNotFound exception.*

## Brief change log

Using the user classloader load some classes in JDBC connector.

## Verifying this change

Manually verified the changes.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? ( no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by lsyldliu** [comment]
cc @leonardBang, @PatrickRen

**Comment by lsyldliu** [comment]
Spark: https://github.com/apache/spark/pull/5543/files

**Review by wuchong — COMMENTED** [review]
I only left one minor comment.

**Review by wuchong — APPROVED** [review]
I appended a commit to address this.

**Pull request merged**
