### PR TITLE
[FLINK-4872] [types] Type erasure problem exclusively on cluster execution

### PR DESCRIPTION
**Pull request by twalthr**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

This PR solves a classloader issue in the TypeExtractor that only happens when using object arrays on a cluster. A test for this change would be difficult but in general this feature is already tested in the existing tests.

### CODE REVIEW

**Comment by StephanEwen** [comment]
I think we can do a more solid approach to that. Would be good to not to rely on the context class loader.

  1. You could use the classloader of the component type directly, i.e.,
  `classArray = (Class<OUT>) Class.forName("[" + className, true, componentClass.getClassLoader());`

  2. You can directly obtain the array class via this trick:
  `classArray = (Class<OUT>) (java.lang.reflect.Array.newInstance(componentClass, 0).getClass());`

**Comment by twalthr** [comment]
Thanks for the hint @StephanEwen. I improved the PR.

**Comment by StephanEwen** [comment]
Looks good, +1 to merge

**Comment by twalthr** [comment]
Merging...

**Pull request closed without merging**
