### PR TITLE
[Flink-4450] add a new module "flink-apache-storm" to support new storm verion program (higher than 1.0.0)

### PR DESCRIPTION
**Pull request by liuyuzhong**
@StephanEwen 

1. Create new module "flink-apache-storm" copy from flink-contrib/flink-storm, It support compatibility layer for storm which higher than 1.0.0.

2. Create new module "flink-apache-storm-examples" copy from flink-contrib/flink-storm-examples, given the examples for storm program which version higher than 1.0.0

3. mvn clean verify: ok

4. Test: ok

- run new storm example   

```
  bin/flink run flink/flink-contrib/flink-apache-storm-examples/target/WordCount-StormTopology.jar
  bin/flink run flink/flink-contrib/flink-apache-storm-examples/target/WordCount-BoltTokenizer.jar
  bin/flink run flink/flink-contrib/flink-apache-storm-examples/target/WordCount-SpoutSource.jar  
```

- run old storm example:

```  
 bin/flink run flink/flink-contrib/flink-storm-examples/target/WordCount-StormTopology.jar
  bin/flink run flink/flink-contrib/flink-storm-examples/target/WordCount-BoltTokenizer.jar
  bin/flink run flink/flink-contrib/flink-storm-examples/target/WordCount-SpoutSource.jar  
```

### CODE REVIEW

**Comment by liuyuzhong** [comment]
flink-apache-storm copy from flink-storm,  and update storm version to 1.0.0
flink-apache-storm-examples copy from flink-storm-examples, and update storm version to 1.0.0

**Comment by liuyuzhong** [comment]
Jenkins run error:
```
error file=/home/jenkins/jenkins-slave/workspace/flink-github-ci/flink-mesos/src/test/scala/org/apache/flink/mesos/Utils.scala message=Expected identifier, but got Token(COMMA,,,1674,,)
Saving to outputFile=/home/jenkins/jenkins-slave/workspace/flink-github-ci/flink-mesos/target/scalastyle-output.xml
Processed 13 file(s)
Found 1 errors
Found 0 warnings
Found 0 infos
Finished in 209 ms
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] force-shading ...................................... SUCCESS [  6.625 s]
[INFO] flink .............................................. SUCCESS [  6.213 s]
[INFO] flink-annotations .................................. SUCCESS [  4.565 s]
[INFO] flink-shaded-hadoop ................................ SUCCESS [  1.079 s]
[INFO] flink-shaded-hadoop2 ............................... SUCCESS [ 27.133 s]
[INFO] flink-shaded-include-yarn-tests .................... SUCCESS [ 36.741 s]
[INFO] flink-shaded-curator ............................... SUCCESS [  1.054 s]
[INFO] flink-shaded-curator-recipes ....................... SUCCESS [  5.945 s]
[INFO] flink-shaded-curator-test .......................... SUCCESS [  1.591 s]
[INFO] flink-metrics ...................................... SUCCESS [  0.888 s]
[INFO] flink-metrics-core ................................. SUCCESS [  5.857 s]
[INFO] flink-test-utils-parent ............................ SUCCESS [  1.691 s]
[INFO] flink-test-utils-junit ............................. SUCCESS [ 19.417 s]
[INFO] flink-core ......................................... SUCCESS [01:21 min]
[INFO] flink-java ......................................... SUCCESS [01:03 min]
[INFO] flink-runtime ...................................... SUCCESS [08:49 min]
[INFO] flink-optimizer .................................... SUCCESS [ 28.185 s]
[INFO] flink-clients ...................................... SUCCESS [ 15.102 s]
[INFO] flink-streaming-java ............................... SUCCESS [ 57.792 s]
[INFO] flink-test-utils ................................... SUCCESS [ 17.591 s]
[INFO] flink-scala ........................................ SUCCESS [01:14 min]
[INFO] flink-runtime-web .................................. SUCCESS [ 32.911 s]
[INFO] flink-examples ..................................... SUCCESS [  1.822 s]
[INFO] flink-examples-batch ............................... SUCCESS [ 31.045 s]
[INFO] flink-batch-connectors ............................. SUCCESS [  1.693 s]
[INFO] flink-hadoop-compatibility ......................... SUCCESS [ 17.754 s]
[INFO] flink-contrib ...................................... SUCCESS [  1.082 s]
[INFO] flink-statebackend-rocksdb ......................... SUCCESS [01:15 min]
[INFO] flink-tests ........................................ SUCCESS [08:00 min]
[INFO] flink-streaming-scala .............................. SUCCESS [ 56.492 s]
[INFO] flink-streaming-connectors ......................... SUCCESS [  2.310 s]
[INFO] flink-connector-flume .............................. SUCCESS [ 10.413 s]
[INFO] flink-libraries .................................... SUCCESS [  1.307 s]
[INFO] flink-table ........................................ SUCCESS [03:36 min]
[INFO] flink-metrics-jmx .................................. SUCCESS [  8.609 s]
[INFO] flink-connector-kafka-base ......................... SUCCESS [ 13.582 s]
[INFO] flink-connector-kafka-0.8 .......................... SUCCESS [03:42 min]
[INFO] flink-connector-kafka-0.9 .......................... SUCCESS [03:53 min]
[INFO] flink-connector-elasticsearch ...................... SUCCESS [ 37.185 s]
[INFO] flink-connector-elasticsearch2 ..................... SUCCESS [ 46.210 s]
[INFO] flink-connector-rabbitmq ........................... SUCCESS [  8.074 s]
[INFO] flink-connector-twitter ............................ SUCCESS [ 12.098 s]
[INFO] flink-connector-nifi ............................... SUCCESS [  6.576 s]
[INFO] flink-connector-cassandra .......................... SUCCESS [02:32 min]
[INFO] flink-connector-redis .............................. SUCCESS [ 13.672 s]
[INFO] flink-connector-filesystem ......................... SUCCESS [ 58.438 s]
[INFO] flink-avro ......................................... SUCCESS [ 24.565 s]
[INFO] flink-jdbc ......................................... SUCCESS [ 11.221 s]
[INFO] flink-hbase ........................................ SUCCESS [ 15.708 s]
[INFO] flink-hcatalog ..................................... SUCCESS [ 26.367 s]
[INFO] flink-examples-streaming ........................... SUCCESS [ 52.331 s]
[INFO] flink-gelly ........................................ SUCCESS [01:02 min]
[INFO] flink-gelly-scala .................................. SUCCESS [ 46.746 s]
[INFO] flink-gelly-examples ............................... SUCCESS [ 36.253 s]
[INFO] flink-python ....................................... SUCCESS [01:43 min]
[INFO] flink-ml ........................................... SUCCESS [02:05 min]
[INFO] flink-cep .......................................... SUCCESS [ 24.554 s]
[INFO] flink-cep-scala .................................... SUCCESS [ 18.861 s]
[INFO] flink-scala-shell .................................. SUCCESS [01:10 min]
[INFO] flink-quickstart ................................... SUCCESS [  3.737 s]
[INFO] flink-quickstart-java .............................. SUCCESS [  8.546 s]
[INFO] flink-quickstart-scala ............................. SUCCESS [  2.309 s]
[INFO] flink-storm ........................................ SUCCESS [ 29.819 s]
[INFO] flink-storm-examples ............................... SUCCESS [01:28 min]
[INFO] flink-apache-storm ................................. SUCCESS [ 34.629 s]
[INFO] flink-apache-storm-examples ........................ SUCCESS [02:43 min]
[INFO] flink-streaming-contrib ............................ SUCCESS [ 14.894 s]
[INFO] flink-tweet-inputformat ............................ SUCCESS [  8.222 s]
[INFO] flink-operator-stats ............................... SUCCESS [ 15.517 s]
[INFO] flink-connector-wikiedits .......................... SUCCESS [ 18.067 s]
[INFO] flink-mesos ........................................ FAILURE [01:06 min]
[INFO] flink-yarn ......................................... SKIPPED
[INFO] flink-dist ......................................... SKIPPED
[INFO] flink-metrics-dropwizard ........................... SKIPPED
[INFO] flink-metrics-ganglia .............................. SKIPPED
[INFO] flink-metrics-graphite ............................. SKIPPED
[INFO] flink-metrics-statsd ............................... SKIPPED
[INFO] flink-fs-tests ..................................... SKIPPED
[INFO] flink-java8 ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:05 h
[INFO] Finished at: 2016-09-01T12:00:08+00:00
[INFO] Final Memory: 200M/988M
[INFO] ------------------------------------------------------------------------
Waiting for Jenkins to finish collecting data
[ERROR] Failed to execute goal org.scalastyle:scalastyle-maven-plugin:0.8.0:check (default) on project flink-mesos_2.10: Failed during scalastyle execution: You have 1 Scalastyle violation(s). -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :flink-mesos_2.10
```

Run flink-mesos, but I didn't modify the code in flink-mesos.

**Comment by mxm** [comment]
@liuyuzhong Should be caused by bumping the Scalastyle version from 0.5.0 to 0.8.0. Doesn't occur on my machine though :( Investigating. Probably lowering the Scalastyle version again.

**Comment by mxm** [comment]
@liuyuzhong Try rebasing on the latest master, should be fixed with https://issues.apache.org/jira/browse/FLINK-4570

**Comment by liuyuzhong** [comment]
build success

```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:28 h
[INFO] Finished at: 2016-09-05T04:07:42+00:00
[INFO] Final Memory: 195M/581M
```

but  Finished: UNSTABLE
```
[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/flink-github-ci/flink-contrib/flink-streaming-contrib/target/flink-streaming-contrib_2.10-1.2-SNAPSHOT-javadoc.jar to org.apache.flink/flink-streaming-contrib_2.10/1.2-SNAPSHOT/flink-streaming-contrib_2.10-1.2-SNAPSHOT-javadoc.jar
channel stopped
Putting comment on the pull request
Finished: UNSTABLE
```

**Comment by liuyuzhong** [comment]
Test Result (失败)
```
org.apache.flink.api.scala.runtime.taskmanager.TaskManagerFailsITCase.The JobManager should detect a failing task manager
org.apache.flink.api.scala.runtime.taskmanager.TaskManagerFailsITCase.The JobManager should handle gracefully failing task manager
org.apache.flink.api.scala.runtime.taskmanager.TaskManagerFailsITCase.The JobManager should handle hard failing task manager
org.apache.flink.api.scala.runtime.taskmanager.TaskManagerFailsITCase.The JobManager should go into a clean state in case of a TaskManager failure
org.apache.flink.test.cancelling.MapCancelingITCase.testSlowMapCancelling
org.apache.flink.test.cancelling.MapCancelingITCase.testMapCancelling
org.apache.flink.test.cancelling.MapCancelingITCase.testMapPriorToFirstRecordReading
org.apache.flink.test.cancelling.MapCancelingITCase.testMapWithLongCancellingResponse
org.apache.flink.test.checkpointing.CoStreamCheckpointingITCase.org.apache.flink.test.checkpointing.CoStreamCheckpointingITCase
org.apache.flink.test.checkpointing.EventTimeAllWindowCheckpointingITCase.org.apache.flink.test.checkpointing.EventTimeAllWindowCheckpointingITCase
org.apache.flink.test.checkpointing.SavepointITCase.testTriggerSavepointAndResume
org.apache.flink.test.checkpointing.SavepointITCase.testCheckpointsRemovedWithJobManagerBackendOnShutdown
org.apache.flink.test.classloading.ClassLoaderITCase.testDisposeSavepointWithCustomKvState
org.apache.flink.test.exampleScalaPrograms.WordCountITCase.testJobWithoutObjectReuse
org.apache.flink.test.exampleScalaPrograms.WordCountITCase.testJobWithObjectReuse
org.apache.flink.test.failingPrograms.JobSubmissionFailsITCase.org.apache.flink.test.failingPrograms.JobSubmissionFailsITCase
org.apache.flink.test.recovery.TaskManagerProcessFailureBatchRecoveryITCase.testTaskManagerProcessFailure[0]
org.apache.flink.test.web.WebFrontendITCase.org.apache.flink.test.web.WebFrontendITCase
```

**Comment by liuyuzhong** [comment]
Jenkins run error:

```
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 30.585 sec - in org.apache.flink.test.recovery.TaskManagerProcessFailureStreamingRecoveryITCase
Running org.apache.flink.test.checkpointing.UdfStreamOperatorCheckpointingITCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 40.442 sec - in org.apache.flink.test.recovery.FastFailuresITCase
Running org.apache.flink.test.checkpointing.RescalingITCase
ERROR: Maven JVM terminated unexpectedly with exit code 137
Putting comment on the pull request
Finished: FAILURE
```

**Comment by mxm** [comment]
I think you ran out of memory. Travis CI build passed, so the PR's testing state seems to be fine.

**Comment by mxm** [comment]
It looks like this is basically a copy of the old code adapted to the Storm 1.0.0 dependency. This would duplicate a lot of code. I've started a thread on the mailing list, whether we want to add a new module for Storm 1.0.0 or stop supporting old Storm versions.

**Comment by liuyuzhong** [comment]
@mxm 
Yes, all of this code are copy from old code adapted to Strom 1.0.0. So we close this pull request and wait for decision?  

Actually, I was submit a pull request for old code adpate to storm version to 1.0.0.  
https://github.com/apache/flink/pull/2439

**Comment by mxm** [comment]
@liuyuzhong Let's wait a couple more days for the community to respond. You don't have to close the PR.

**Comment by liuyuzhong** [comment]
@mxm OK.

**Comment by StephanEwen** [comment]
There is not a lot of response on the mailing list. Apparently switching to the newer Storm version does not bother anyone.

My guess would be to switch to Strom 1.0+ and remove the storm 0.8/0.9 code.

What do others think?

**Comment by tzulitai** [comment]
Sorry for chiming in late. Left some comments on the ML thread.
Overall I think it's ok to switch focus on supporting 1.0+ Storm versions only.

**Comment by liuyuzhong** [comment]
OK, how about reopen pull requests #2439 ? Just update storm version to 1.0, and it can support storm 1.0+ version program.

**Comment by StephanEwen** [comment]
Agreed, let's proceed with #2439. Sorry for the back and forth, but these things are important to discuss so that everyone is on board and we make a good decision.

**Comment by liuyuzhong** [comment]
That's OK. I understand. 
It's not so easy to make a decesion.

**Comment by StephanEwen** [comment]
@liuyuzhong Because we proceed with #2439 , can you close this pull request?

**Comment by liuyuzhong** [comment]
ok.

**Pull request closed without merging**
