### PR TITLE
[FLINK-29741][scala] Delete flink-scala and flink-streaming-scala modules

### PR DESCRIPTION
**Pull request by codenohup**
## What is the purpose of the change

Delete flink-scala and flink-streaming-scala modules for deprecated Scala API

## Brief change log
- delete flink-scala module
- delete flink-streaming-scala module
- add scala-lang and twitter chill dependencies to the flink-dist-scala module, as they are required by the table module

## Verifying this change

This change is a code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes
  - The serializers: yes
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by codenohup** [comment]
@flinkbot run azure

**Comment by reswqa** [comment]
@flinkbot run azure

**Comment by codenohup** [comment]
@flinkbot run azure

**Comment by codenohup** [comment]
@flinkbot run azure

**Review by reswqa — APPROVED** [review]
Thanks for the contribution.

**Pull request merged**
