### PR TITLE
[FLINK-16508][k8s] Name the ports exposed by the main Container in Pod

### PR DESCRIPTION
**Pull request by zhengcanbin**
## What is the purpose of the change

1. Currently, we expose some ports via the main Container of the JobManager and the TaskManager, but we forget to name those ports so that people could be confused because there is no description of the port usage. This PR proposes to explicitly name the ports in the Container to help people understand the usage of those ports.

2. Since the port name in the Container must be less than 15 characters, meanwhile we prefer to keep the port name consistent between the Container and the Service, so this PR also makes little change to the existing name of the corresponding ports in the Service. This is a minor change that rarely requires modification from user perspective.

## Verifying this change

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)

### CODE REVIEW

**Comment by zhengcanbin** [comment]
cc @TisonKun. Looking forward to your feedback.

**Comment by zhengcanbin** [comment]
@flinkbot run travis

**Comment by TisonKun** [comment]
Thanks for your contribution @zhengcanbin ! It seems we should also include this improvement in 1.10, would you like to open a PR towards 1.10?

**Comment by zhengcanbin** [comment]
> Thanks for your contribution @zhengcanbin ! It seems we should also include this improvement in 1.10, would you like to open a PR towards 1.10?

Thanks for the review @TisonKun! I will open a PR towards 1.10.

**Pull request merged**
