### PR TITLE
Flink 25846 25848 25977 25792 compound

### PR DESCRIPTION
**Pull request by CrynetLogistics**
https://github.com/apache/flink/pull/18553
https://github.com/apache/flink/pull/18651
https://github.com/apache/flink/pull/18686

### CODE REVIEW

**Comment by CrynetLogistics** [comment]
@flinkbot run azure

**Comment by CrynetLogistics** [comment]
@flinkbot azure run

**Comment by CrynetLogistics** [comment]
@flinkbot azure run

**Comment by CrynetLogistics** [comment]
@flinkbot run azure

**Comment by CrynetLogistics** [comment]
@CrynetLogistics  it's @flinkbot run azure

**Comment by CrynetLogistics** [comment]
@flinkbot run azure

**Comment by CrynetLogistics** [comment]
@flinkbot run azure

**Comment by dawidwys** [comment]
Not sure what is this PR about. Closing for now. Please reopen and fill in the description if you think it is still valid.

**Pull request closed without merging**
