### PR TITLE
[FLINK-1871][gelly] Added Spargel to Gelly migration guide

### PR DESCRIPTION
**Pull request by andralungu**

### CODE REVIEW

**Comment by vasia** [comment]
I like it that you are using the example to show the migration process, but I think it would also be helpful to add a section with more general guidelines, describing all the differences between Spargel and Gelly.

Among others possibly, we should cover the following:
- Gelly has Vertex and Edge type whereas Spargel operates on Tuple2 and Tuple3
- Spargel has separate methods for edges with values and edges without values. In Gelly, there is only one. Edges without values have a NullValue type.
- Spargel's `runOperation` vs. Gelly's `runVertexCentricIteration`
- Spargel's `OutgoingEdge` type is replaced by `Edge` in Gelly.
- How an iteration is configured in each of the APIs.
- Spargel's record API is completely removed from Gelly.

**Comment by andralungu** [comment]
Hi @vasia ,

The general guidelines were added.

**Comment by vasia** [comment]
Hey! This looks good, thanks a lot!
I would make some minor changes in the text and merge.
What do you think about making it a separate section instead of a subsection of the vertex-centric iterations? I think it's current place might confuse users who don't know Spargel.

**Comment by andralungu** [comment]
Hi @vasia !

To me it looked normal, probably because I know Spargel :P 
I moved it in a separate section and rebased. Should be fine now :)

**Pull request closed without merging**
