### PR TITLE
[FLINK-10025] Add getCheckpointConfig API for PythonStreamExecutionEnvironment

### PR DESCRIPTION
**Pull request by yanghua**
## What is the purpose of the change

*This pull request add getCheckpointConfig API for PythonStreamExecutionEnvironment*

## Brief change log

  - *Add getCheckpointConfig API for PythonStreamExecutionEnvironment*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / **JavaDocs** / not documented)

### CODE REVIEW

**Comment by yanghua** [comment]
@zentol this PR's test will be done in [issue-10024](https://issues.apache.org/jira/browse/FLINK-10024) and depends a test class added in PR: #6475

**Comment by zentol** [comment]
This still needs a _python_ test to verify that all properties can be properly set from the python side.

**Comment by yanghua** [comment]
OK, Can you review PR #6475 so that I can write a test with Java?

**Comment by zentol** [comment]
flink-streaming-python is in a limbo state and I can't get a clear answer whether we want to continue maintaining it. After the 1.8 release I'll start a mailing list thread about this very topic.

For the time being I will close this PR, I apologize for wasting your time.

**Pull request closed without merging**
