### PR TITLE
[FLINK-2769] [dashboard] Remove hard coded job server URL

### PR DESCRIPTION
**Pull request by uce**
Removes the hard coded job server URL for the client scripts. This was preventing the web server port configuration to be picked up by the client.

### CODE REVIEW

**Comment by rmetzger** [comment]
Remember to assign the JIRA to yourself ;)

**Comment by aljoscha** [comment]
+1
I built it and ran it on a custom port, data seems to be displayed correctly

**Comment by StephanEwen** [comment]
+1, looks good.

I think the ports / URLs were in there, because originally we had two backend servers running (the old one and the new one) while gradually transitioning requests and adding more REST requests. For a time, the frontend connected to two different backends and did some tunneling/proxy magic to get around XSS restrictions...

**Comment by StephanEwen** [comment]
Merging this...

**Pull request closed without merging**
