### PR TITLE
[FLINK-24846][streaming] Closing the mailbox only after it drains all mails including recursive ones 

### PR DESCRIPTION
**Pull request by akalash**
## What is the purpose of the change

*This PR fixes the handling of the remaining mails on afterInvoke call*

## Brief change log

  - *MailboxProcessor#drain process the recursive mails(mails produced by current mails in the queue) as well *
  - *Closing the mailbox only after it drains all mails including recursive ones*

## Verifying this change

This change added tests and can be verified as follows:

  - *Added a couple of tests in StramTaskTest and MailboxProcessorTest*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by pnowojski — COMMENTED** [review]
Can you elaborate more what is the problem and how are you trying to fix it in this PR? Maybe I'm missing something, but it looks like this doesn't solve the problem, or at least not fully?

 As far as I understand, you want to allow for `drain()` to pick up process recursively created mails to emit more records from AWOP. `drain()` is called in `afterInvoke()`, basically after operators received `finish()`/`endInput()`? If so, doesn't that invalidates the `StreamOperator#finish()` contract?

Instead, shouldn't the solution be that `AWOP#finish()` is waiting for all in flight records to be processed? Basically duplicate logic from `AWOP#endInput()`?

**Comment by akalash** [comment]
@pnowojski, I understand the problem something like this:

1. AsyncWaitOperator#processElement registers the timeout for the entry
2. endInput happens which waits for in-flight inputs but doesn't wait for the registered timeout
3. finish happens
4. mailbox is suspend
5. timer fires which put mail to mailbox (AsyncWaitOperator.ResultHandler#processInMailbox)
6. all timers close
7. mailbox is marked as close which forbids adding new mails
8. drain is called which execute mail described above which recursively try to add new mail to mailbox which fails

In my opinion, it is impossible to be sure that there are no new data possible until we close all potential sources of data like timers. So in this PR I close all timers which should guarantee that no new outside data is possible then I drain mailbox, and only then I mark the mailbox as closed. 

It is difficult to say something about `finish ` contract because it indeed guarantees that no new records from the channel are possible but it doesn't guarantee that records from another place(like timer service) are impossible. If we think that it is not correct we should rewrite `AsyncWaitOperator#waitInFlightInputsFinished` in such a way that it waits for time service as well(which is not so easy to do) or we can ignore all time service events after `endInput` was received. For example, we can rewrite `AsyncWaitOperator.ResultHandler#timerTriggered` to:
```
private void timerTriggered() throws Exception {
            if (!completed.get() && !endInput.get()) {
                userFunction.timeout(inputRecord.getValue(), this);
            }
        }
```

**Comment by pnowojski** [comment]
I think the scenario that you posted works fine. After `endInput()` in step 2. there shouldn't be any timers registered left, as they are being cancelled in `AsyncWaitOperator.ResultHandler#processResults`. And  `AsyncWaitOperator.ResultHandler#completed` seems like is preventing from a race between firing and cancelling the timer at the same time.

Also if you take a look at the reported stacktrace, it's coming from `processResults`, so this is not a timeout trigger. Nevertheless, we should also take the timeout case into consideration.

As far as I understand, the problem described in the ticket applies to `stop-with-savepoint --without-drain`, where `endInput()` is NOT being called. 

In that scenario, maybe we don't want to duplicate the `endInput()` logic, as this would unnecessarily delay the `stop-with-savepoint --without-drain`, while having no meaningful result for the user? Those records would be re-processed by the async function either way after recovering from such savepoint. 

So it looks like we might have two paths to take (in `finish()`?):
1. wait for the results to be processed/timeout
2. cancel those results

Another question, is if there is the same issue for regular cancelation? 

And yet another thing to take into consideration, that with FLIP-147 follow up, we wanted to unify stop-with-savepoint with and without drain. Having this in mind might affect our plans to address this bug?

**Comment by akalash** [comment]
I opened the new PR since the fix has been changed entirely. - https://github.com/apache/flink/pull/17965

**Pull request closed without merging**
