### PR TITLE
[FLINK-21623][table-planner] Introduce CURRENT_ROW_TIMESTAMP() function

### PR DESCRIPTION
**Pull request by leonardBang**
## What is the purpose of the change

* This PR introduce `CURRENT_ROW_TIMESTAMP()` function which returns row-level timestamp.

## Brief change log

 - Follow `CURRENT_TIMESTAMP`  function, but evaluates for per record both in batch and stream job
 - Use TIMESTAMP_LTZ as function return type

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): ( no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (doc)

### CODE REVIEW

**Comment by wuchong** [comment]
Is there any reason why we not use the `BuiltInScalarFunction` to implement this new function? From my point of view, it would be much simpler if we use `BuiltInScalarFunction` because it doesn't need to refactor the codegen logic.

**Comment by leonardBang** [comment]
> Is there any reason why we not use the `BuiltInScalarFunction` to implement this new function? From my point of view, it would be much simpler if we use `BuiltInScalarFunction` because it doesn't need to refactor the codegen logic.

The reason is that the scalar function can not resolv the function name `CURRENT_ROW_TIMESTAMP`, it always use the function name `CURRENT_ROW_TIMESTAMP()`, I think what we want is aligned with `CURRENT_TIMESTAMP`

**Comment by wuchong** [comment]
> > Is there any reason why we not use the `BuiltInScalarFunction` to implement this new function? From my point of view, it would be much simpler if we use `BuiltInScalarFunction` because it doesn't need to refactor the codegen logic.
> 
> The reason is that the scalar function can not resolve the function name `CURRENT_ROW_TIMESTAMP` after I tried, it always use the function name `CURRENT_ROW_TIMESTAMP()`, I think what we want is aligned with `CURRENT_TIMESTAMP`

This should be supported by `SqlFunction#getSyntax` returning `SqlSyntax.FUNCTION_ID`. I think we can extend `BridgingSqlFunction` to support this.

**Comment by leonardBang** [comment]
@wuchong , I implemented the PR with new function stack, but I found there're one minor problem that `current_timestamp` and `current_row_timestamp()` will be different in stream job, because they are evaluated at different timepoint. Do you think do we need to make the two value be same? I think we should

**Comment by wuchong** [comment]
I think we can make it as a synonyms for `current_timestamp` in streaming mode.

**Comment by leonardBang** [comment]
Thanks @wuchong , I update the PR, Appreciate if you can help review.

**Review by wuchong — APPROVED** [review]
LGTM.

**Pull request closed without merging**
