### PR TITLE
[FLINK-4082] Add Setting for enabling/disabling LargeRecordHandler

### PR DESCRIPTION
**Pull request by aljoscha**
By default this is set to disabled because there are known issues when
users specify a custom TypeInformation.

R: @tillrohrmann (the `R:` is for review) I think you know how stuff should work there
CC: @StephanEwen

### CODE REVIEW

**Comment by uce** [comment]
Changes look good, but did you skip the `CombiningUnilateralSortMerger` on purpose?

It's hard to tell, because the `handleLargeRecords` argument was existing before your changes, but it was not configurable. The `CombiningUnilateralSortMerger` always sets `handleLargeRecords` to `true`.

**Comment by aljoscha** [comment]
Nope, I forgot that. Thanks for spotting!

**Comment by aljoscha** [comment]
@uce I addressed the comments.

**Comment by uce** [comment]
Thanks! Looks good to merge. +1

**Pull request closed without merging**
