### PR TITLE
[FLINK-30196][tests] Replace usage of deprecated Mockito methods and update Mockito to 4.11.0

### PR DESCRIPTION
**Pull request by snuyanzin**
## What is the purpose of the change
The PR replaces deprecated with suggested by Mockito's javadoc and release notes e.g.
https://github.com/mockito/mockito/releases/tag/v4.0.0
`org.mockito.Matchers` (removed in 4.x) replaced with `org.mockito.ArgumentMatchers`
`org.mockito.Mockito#verifyZeroInteractions` (removed in 4.x) replaced with `org.mockito.Mockito#verifyNoMoreInteractions`
`org.mockito.ArgumentMatchers#isNull(Class)` (removed in 4.x) replaced with `org.mockito.ArgumentMatchers#isNull()`
Also upgrades Mockito to 4.11.0

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.
## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: ( no )
  - The runtime per-record code paths (performance sensitive): (no )
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no )
  - The S3 file system connector: (no )

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by snuyanzin** [comment]
@Zakelly sorry for the ping
do you mind if I ask you to have a look here (GitHub says you are the most matching person)

**Comment by Zakelly** [comment]
:D  Sure, will take a look

**Review by Zakelly — APPROVED** [review]
LGTM. Would you please resolve the conflicts?

**Comment by snuyanzin** [comment]
@flinkbot run azure

**Comment by snuyanzin** [comment]
@flinkbot run azure

**Pull request merged**
