### PR TITLE
[FLINK-20947][planner] Fix idle source doesn't work when pushing watermark into the source

### PR DESCRIPTION
**Pull request by fsk119**
## What is the purpose of the change

*Fix idle source doesn't work when pushing watermark strategy into table source.*

## Brief change log

  - *Fix the bug.*

## Verifying this change

This change added tests and can be verified as follows:

  - *Idle source plan test.*
  - *Idle source IT cases.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)

### CODE REVIEW

**Comment by fsk119** [comment]
@flinkbot run azure

**Comment by fsk119** [comment]
@flinkbot run azure

**Comment by fsk119** [comment]
The failed test is because of [FLINK-21071](https://issues.apache.org/jira/browse/FLINK-21071?filter=12350060&jql=project%20%3D%20FLINK%20AND%20component%20in%20(%22Connectors%20%2F%20Kafka%22%2C%20Tests)%20AND%20text%20~%20%22Run%20kubernetes%20session%20test%20(default%20input)%22).

**Comment by fsk119** [comment]
The failed test is because of [FLINK-21104](https://issues.apache.org/jira/browse/FLINK-21104?filter=-1&jql=resolution%20in%20(Unresolved%2C%20Fixed)%20AND%20text%20~%20%22UnalignedCheckpointITCase%22%20order%20by%20updated%20DESC). Rebase again...

**Review by wuchong — APPROVED** [review]
LGTM.

**Pull request merged**
