### PR TITLE
Bump version to 1.2-SNAPSHOT

### PR DESCRIPTION
**Pull request by mbalassi**
It is about time to do this.

### CODE REVIEW

**Comment by StephanEwen** [comment]
About time to bump the version ;-)
I think the variables in the docs also need adjustments.

**Comment by mbalassi** [comment]
Good catch, looking into that.

**Comment by StephanEwen** [comment]
I actually need to bump my version, so will merge this and adjust the references in docs

**Comment by mbalassi** [comment]
We also need to bump the version in the metrics imls.

**Comment by StephanEwen** [comment]
What do you mean by "the metrics imls"?

**Comment by mbalassi** [comment]
~~~
mbalassi$ grep 1.1-SNAPSHOT -R .
./docs/_config.yml:version: "1.1-SNAPSHOT"
./flink-metric-reporters/flink-metrics-dropwizard/flink-metrics-dropwizard.iml:    <orderEntry type="library" scope="PROVIDED" name="Maven: org.apache.flink:flink-shaded-hadoop2:1.1-SNAPSHOT" level="project" />
./flink-metric-reporters/flink-metrics-ganglia/flink-metrics-ganglia.iml:    <orderEntry type="library" scope="PROVIDED" name="Maven: org.apache.flink:flink-shaded-hadoop2:1.1-SNAPSHOT" level="project" />
./flink-metric-reporters/flink-metrics-graphite/flink-metrics-graphite.iml:    <orderEntry type="library" scope="PROVIDED" name="Maven: org.apache.flink:flink-shaded-hadoop2:1.1-SNAPSHOT" level="project" />
./flink-metric-reporters/flink-metrics-statsd/flink-metrics-statsd.iml:    <orderEntry type="library" scope="PROVIDED" name="Maven: org.apache.flink:flink-shaded-hadoop2:1.1-SNAPSHOT" level="project" />
~~~

**Comment by mbalassi** [comment]
If it can wait until tomorrow morning CEST I will add these to the change version scripts in tools. If it is urgent go ahead.

**Comment by mbalassi** [comment]
Oh, my bad - those are just IntelliJ files left over on my machine. Adding the doc update to the tools script and quickly rebasing this commit. Sorry for the fuss.

**Comment by mbalassi** [comment]
Did the update, please use this version of the commit. Thanks.

**Comment by StephanEwen** [comment]
I already merged it before you appended the commit, needed it locally to prevent always overwriting my cache with different versions. I basically pushed the same thing now spread over two commits, so we should be fine.

**Pull request closed without merging**
