### PR TITLE
[FLINK-6895][table]Add STR_TO_DATE supported in SQL

### PR DESCRIPTION
**Pull request by buptljy**
## What is the purpose of the change
Add STR_TO_DATE Function supported in SQL
## Brief change log
 * STR_TO_DATE(str string, format string)  
    \-  str is the string that need to be transformed.
    \- format is the pattern of "str"
 * Add tests in ScalarFunctionsTest.scala
 * Add docs in sql.md
## Verifying this change
 * Run unit tests in  ScalarFunctionsTest.scala
## Does this pull request potentially affect one of the following parts:
 * A new sql function
## Documentation
  * Add docs in sql.md

### CODE REVIEW

**Comment by buptljy** [comment]
Actually I am not sure if it is appropriate to return "string" because it should be the inverse of the "DATE_FORMAT()". However, If I return DATE/TIME/DATETIME as the jira issue described, the type of data user receives will be uncertain in one of DATE/TIME/DATETIME.
I will optimize it if anyone can give me some suggestions.

**Comment by twalthr** [comment]
@buptljy what is the status of this PR? Can we close it for now? According to the discussion in FLINK-6895 it needs a rework anyway.

**Comment by buptljy** [comment]
@twalthr 
Sorry for late reply here.
This can be closed now, and I'll submit another PR this week.
I've posted my solution in FLINK-6895, we can have a discussion there.

**Comment by buptljy** [comment]
Submit another [Pull Request](https://github.com/apache/flink/pull/6359) according to the discussion in FLINK-6895.

**Pull request closed without merging**
