### PR TITLE
[BP-1.18][FLINK-34379][table] Fix OutOfMemoryError with large queries

### PR DESCRIPTION
**Pull request by jeyhunkarimov**
This is 1.18 backport for commit https://github.com/apache/flink/commit/cca14d4210634d481cacb11354e870807d570561

### CODE REVIEW

**Comment by lsyldliu** [comment]
The CI is failed.

**Comment by jeyhunkarimov** [comment]
@flinkbot run azure

**Comment by jeyhunkarimov** [comment]
Hi @lsyldliu the failure was related to sth else IMO, I could not reproduce locally. In fact, retriggering the CI seems to green.

**Review by lsyldliu — APPROVED** [review]
LGTM

**Pull request merged**
