### PR TITLE
[FLINK-16683][scripts] Remove Windows scripts

### PR DESCRIPTION
**Pull request by zentol**

### CODE REVIEW

**Comment by rmetzger** [comment]
What about `./docs/build_docs.bat`?

**Comment by zentol** [comment]
This JIRA is only for the start scripts.

**Comment by zentol** [comment]
I thought it would have been removed as part of FLINK-16895.

**Comment by rmetzger** [comment]
I see. Maybe we should remove the file in a hotfix as part of this PR?

**Comment by zentol** [comment]
@rmetzger done

**Pull request merged**
