### PR TITLE
[FLINK-25484][connectors/filesystem] Support inactivityInterval config in table api

### PR DESCRIPTION
**Pull request by lichang-bd**
Change-Id: Ica8ba43307476198c4f525ac40a54ab862b58ea7

## What is the purpose of the change
Support inactivityInterval config in table api

## Brief change log
  - *Add SINK_ROLLING_POLICY_INACTIVITY_INTERVAL table config*
  - *Support file inactive check when rolling which has been already supported in datastream api*

## Verifying this change
This change is a trivial rework / code cleanup without any test coverage.

## Documentation
  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by JingsongLi** [comment]
Thanks @lichang-bd , can you add test to verify?

**Comment by lichang-bd** [comment]
> Thanks @lichang-bd , can you add test to verify?

**Comment by lichang-bd** [comment]
> Thanks @lichang-bd , can you add test to verify?
yeah， I think so， I added a single test and passed the test, please to review it again @JingsongLi

**Comment by JingsongLi** [comment]
@flinkbot run azure

**Comment by JingsongLi** [comment]
@flinkbot run azure

**Comment by lichang-bd** [comment]
please have a look @JingsongLi

**Review by JingsongLi — APPROVED** [review]
Looks good to me!

**Pull request merged**
