### PR TITLE
[FLINK-27536][Connectors / Common] Rename method parameter in AsyncSi…

### PR DESCRIPTION
**Pull request by DavidLiu001**
…nkWriter

## What is the purpose of the change

Change the abstract method's parameter naming in AsyncSinkWriter and AsyncSinkWriterTest
From Consumer<List> requestResult
to Consumer<List> requestToRetry
This is because the consumer here is supposed to accept a list of requests that need to be retried.

## Brief change log

flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriter.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterTest.java
Just rename the parameter of requestResult to requestToRetry

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)    no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)    no
  - The serializers: (yes / no / don't know)    no
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)    no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)    no
  - The S3 file system connector: (yes / no / don't know)    no

## Documentation

  - Does this pull request introduce a new feature? (yes / no)    no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by dannycranmer** [comment]
@DavidLiu001 I can see the [CI build has already failed](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=38732&view=results).

Before pushing your branch please try to build locally and verify it succeeds.

**Comment by DavidLiu001** [comment]
@dannycranmer Thanks. Built locally with "mvn spotless:apply" and verified this PR with "mvn spotless:check", this PR was updated.

**Comment by DavidLiu001** [comment]
@flinkbot run azure re-run the last Azure build

**Comment by dannycranmer** [comment]
@flinkbot run azure

**Comment by DavidLiu001** [comment]
BUILD FAILURE: Failed to execute goal on project flink-connector-elasticsearch-base: Could not resolve dependencies for project org.apache.flink:flink-connector-elasticsearch-base:jar:1.16-SNAPSHOT: Failed to collect dependencies at org.elasticsearch.client:elasticsearch-rest-high-level-client:jar:7.10.2 -> org.elasticsearch.plugin:rank-eval-client:jar:7.10.2: Failed to read artifact descriptor for org.elasticsearch.plugin:rank-eval-client:jar:7.10.2: Could not transfer artifact org.elasticsearch.plugin:rank-eval-client:pom:7.10.2 from/to google-maven-central (https://maven-central-eu.storage-download.googleapis.com/maven2/): Read timed out -> [Help 1]

@dannycranmer  It seems it is the environment issue of Azure.

**Comment by dannycranmer** [comment]
@DavidLiu001 agree. Given this is a non-functional, tech debt PR, merging based on compilation success.

**Pull request merged**
