### PR TITLE
[FLINK-21247][table] Fix problem in MapDataSerializer#copy when there…

### PR DESCRIPTION
**Pull request by cshuo**
… exists custom MapData

## What is the purpose of the change
Iceberg has a custom implementation of MapData, while MapDataSerializer does not process custom MapData properly.

## Brief change log
Fix problem in MapDataSerializer#copy.

## Verifying this change
Adding unit test in MapDataSerializerTest.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: yes.
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by cshuo** [comment]
cc @JingsongLi

**Review by KurtYoung — COMMENTED** [review]
Could you also add some test cases similar with the case reported in the jira?

**Comment by cshuo** [comment]
> Could you also add some test cases similar with the case reported in the jira?

I think what the similar case validates is the coping of input record with custom map data (object-reuse is disabled by default), which is actually covered by the case `testCopy` in `MapDataSerializerTest`.

**Comment by KurtYoung** [comment]
The reported case is failed to covert table to datastream when the table contains filed with MAP type. 
It's better to also verify that your fix can really unblock this use case.

**Comment by JingsongLi** [comment]
The root cause is that there is a custom `MapData` implementation from iceberg source.
You can create a custom source with custom `MapData` to re-produce this problem.

**Review by JingsongLi — APPROVED** [review]
Looks good to me.

**Comment by JingsongLi** [comment]
@cshuo Can you create a PR for release-1.13?

**Pull request merged**
