### PR TITLE
[FLINK-20728][connector] Pulsar SinkFunction

### PR DESCRIPTION
**Pull request by jianyun8023**
## What is the purpose of the change

Add the `SinkFunction` implementation of Pulsar to the connector.

## Brief change log

- Add Pulsar `SinkFunction` implementation
- Supports exactly-one base pulsar Transaction
- Add Pulsar's native type, based on `FormatFactory`

## Verifying this change

This change added tests and can be verified as follows:

- Pulsar sink's basic test
- Exactly-once for sink
- Pulsar's native type unit test

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (**yes** / no)
  - The serializers: (**yes** / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / **don't know**)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (**yes** / no)
  - If yes, how is the feature documented? (not applicable / **docs** / **JavaDocs** / not documented)

### CODE REVIEW

**Comment by jianyun8023** [comment]
The pr depends on #14622

**Comment by AHeise** [comment]
Sorry for coming back so late to this PR. Code-wise, it looks mostly fine. I would add a complete code review later.

However, I'd like to clarify first, why we want to have the old implementation in Flink master at all. From my perspective, this is instant legacy. So there needs to be a strong reason to have it compared to merge only the new interfaces.

Possible reasons could include features that cannot be supported with the new PulsarSink. In general, when would a user choose the old implementation over the new implementation given that the new sink interface is quite stable in Flink 1.13?

I'm duplicating the reply to the Source PR as the answer may be different.

**Comment by jianyun8023** [comment]
> Sorry for coming back so late to this PR. Code-wise, it looks mostly fine. I would add a complete code review later.
> 
> However, I'd like to clarify first, why we want to have the old implementation in Flink master at all. From my perspective, this is instant legacy. So there needs to be a strong reason to have it compared to merge only the new interfaces.
> 
> Possible reasons could include features that cannot be supported with the new PulsarSink. In general, when would a user choose the old implementation over the new implementation given that the new sink interface is quite stable in Flink 1.13?
> 
> I'm duplicating the reply to the Source PR as the answer may be different.

I think the new version of Sink interface is still in iteration and not reliable enough. Providing an older implementation may be a better option for users.
We are following up on the new Sink and will submit it up as well.

**Comment by AHeise** [comment]
I'm closing this PR for the time being similar to #14622 . If we still see a need for it after having the new source in, we can still reopen.

**Pull request closed without merging**
