### PR TITLE
[FLINK-22098][table-planner-blink] Fix bug for window join: plan is wrong if join condition contain 'IS NOT DISTINCT FROM'

### PR DESCRIPTION
**Pull request by beyond1920**
## What is the purpose of the change

Now plan is wrong if window join contain 'IS NOT DISTINCT FROM'. This pull request aims to fix the bug.

## Brief change log

  - Fix bug in `WindowJoinUtil`

## Verifying this change

  - Added test in `WindowJoinTest`
  - 
## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by beyond1920** [comment]
cc @wuchong

**Review by godfreyhe — APPROVED** [review]
Thanks for the contribution @beyond1920. LGTM, please fix the failed test

**Comment by beyond1920** [comment]
@godfreyhe Thanks for review, I've addressed failed case

**Comment by beyond1920** [comment]
@flinkbot run azure

**Pull request closed without merging**
