### PR TITLE
[FLINK-5654] - Add processing time OVER RANGE BETWEEN x PRECEDING aggregation to SQL

### PR DESCRIPTION
**Pull request by rtudoran**
processing time with MapState for event handling

Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [ x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by rtudoran** [comment]
@fhueske @sunjincheng121 @stefanobortoli 
I have made an implementation also for implementing the management of the events in the buffer based on MapState as suggested in #3590 

I also tested the performance of the 2 approaches (ValueState[Queue] vs MapState[Long, JList]) for small windows (2000) and large (10K) and they are roughly the same. Considering this, i still think that having the order is a good gain but both approaches are available to be integrated so you can pick/vote

**Comment by sunjincheng121** [comment]
HI, @rtudoran Thanks for this PR. It's looks very promising. Please rebase code on master first, Then I glad to take a look this changes.
Best,
SunJincheng

**Comment by rtudoran** [comment]
@sunjincheng121  i  will take a look - although the branch was created friday morning - there should not be any conflicts or anything...

**Comment by rtudoran** [comment]
@sunjincheng121 @fhueske @stefanobortoli 

I rebased and created the tests. Please have a look

**Comment by sunjincheng121** [comment]
Hi @rtudoran I am a bit confused that why do we need to change so many files? 

Best，
SunJincheng

**Comment by rtudoran** [comment]
@sunjincheng121  - Apperently there were many conflicts...most of them were stupid conflicts when git was trying to do the automatic merging.
At least in 2 classes the methods you added and the ones i added were put one into the other...instead of one after the other. If you look over the classes you we see that actually there are not so many actual modifications :)

**Comment by rtudoran** [comment]
@sunjincheng121 i actually saw now that there are 64 files changed ...these is definitely due to the rebase...

**Comment by sunjincheng121** [comment]
Hi, @rtudoran  When open a PR. we should keep our commits based on the latest master branch, so that the PR. only contains the change for this issue and will be clearly for other's review.I had check your `Commits` list and changes. There were something wrong when you rebase the code. When I rebase code, I usually use git command as follow: 
```
  git checkout myBranch
  git remote add upstream https://github.com/apache/flink.git
  git fetch upstream
  git rebase upstream/master
```
Everyone's local environment is different, the above operation is for reference only.

Best，
SunJincheng

**Comment by rtudoran** [comment]
@sunjincheng121 @fhueske 
Of course i understand and work on the last master branch when starting an implementation ...as mentioned the initial commit that was done friday evening had the branch from friday morning...
i am not sure what is the order of integrating the PR and the like...but hours are definitely not in the priority queue and therefore we constantly are being pushed in this situation....so although i appreciate the good nature of the comment please consider the context...
Nevertheless...please review the PR and decide whether you are going to integrate this or not

**Comment by rtudoran** [comment]
I have reopened this PR

**Pull request closed without merging**
