### PR TITLE
[FLINK-10853] Provide end-to-end test for Kafka 0.9 connector

### PR DESCRIPTION
**Pull request by yanghua**
## What is the purpose of the change

*This pull request provides end-to-end test for Kafka 0.9 connector*

## Brief change log

  - *Provide end-to-end test for Kafka 0.9 connector*

## Verifying this change

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by yanghua** [comment]
cc @pnowojski

**Comment by yanghua** [comment]
@pnowojski Yes, I found some testing problems, this PR is not ready yet, so I didn't ping you more. Some of the issues you mentioned, I have found out, but not only that, I found that the shell method of sending and reading Kafka messages is not compatible with higher Kafka versions (parameters). I haven't had time to fix it yet, I will ping you when I am ready.

**Comment by pnowojski** [comment]
Ok, let me know once that is ready. Keep in mind that if it is not easy to fix, we can live without `0.9` e2e test.

**Comment by yanghua** [comment]
@pnowojski Providing e2e tests for the 0.9/0.8 connector requires a lot of changes to the scripts, and I don't plan to provide them with end-to-end testing. Because there are too many more valuable things to do. So, I am closing it now.

**Comment by pnowojski** [comment]
Sounds good to me @yanghua.

**Pull request closed without merging**
