### PR TITLE
[FLINK-33960][Scheduler] Fix the bug that Adaptive Scheduler doesn't respect the lowerBound when one flink job has more than 1 tasks

### PR DESCRIPTION
**Pull request by 1996fanrui**
Backporting FLINK-33960 to 1.19

### CODE REVIEW

**Review by qinf — APPROVED** [review]

**Comment by 1996fanrui** [comment]
@flinkbot run azure

**Comment by 1996fanrui** [comment]
@flinkbot run azure

**Comment by 1996fanrui** [comment]
@flinkbot run azure

**Comment by 1996fanrui** [comment]
@flinkbot run azure

**Pull request merged**
