### PR TITLE
[FLINK-4205] Create a simple stratified sampling function for DataSet

### PR DESCRIPTION
**Pull request by doflink**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.
- [ ] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)
- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added
- [ ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by rmetzger** [comment]
@greghogan would you be willing to review this pull request?

**Comment by doflink** [comment]
Till Rohrmann had a look, this pull request needs some more works. Therefore, I think you should not spend time to review it for now.

**Comment by uce** [comment]
Hey @doflink! Do you think you will have time to address Till's comments? If not I think it's best to close this.

**Comment by aljoscha** [comment]
I'm closing this as "Abandoned", since there is no more activity and the code base has moved on quite a bit. Please re-open this if you feel otherwise and work should continue.

**Pull request closed without merging**
