### PR TITLE
[FLINK-3537] Fix code gen for disjunctions.

### PR DESCRIPTION
**Pull request by fhueske**
Fixes code generation for disjunctions and adds tests with regular and join predicates.

### CODE REVIEW

**Comment by twalthr** [comment]
Stupid copy-paste bug. Thanks for fixing!
+1 for merging.

**Comment by vasia** [comment]
I'm merging this.

**Comment by vasia** [comment]
You can close this @fhueske.

**Comment by fhueske** [comment]
Thanks, @vasia

**Pull request closed without merging**
