### PR TITLE
[hotfix] fix unstable JoinJsonPlanITCase

### PR DESCRIPTION
**Pull request by zjuwangg**
## What is the purpose of the change

*fix unstable JoinJsonPlanITCase*

## Brief change log

  -  as title.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no )
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by zentol** [comment]
what kind of failure have you observed?

**Comment by zjuwangg** [comment]
> what kind of failure have you observed, and why do you believe this to fix the issue?

hi @zentol  The detailed error is https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=15017&view=logs&j=e25d5e7e-2a9c-5589-4940-0b638d75a414&t=a6e0f756-5bb9-5ea8-a468-5f60db442a29

Fatal errror is as following:
`Insufficient number of network buffers: required 33, but only 2 available. The total number of network buffers is currently set to 2048 of 32768 bytes each. You can increase this number by setting the configuration keys 'taskmanager.memory.network.fraction', 'taskmanager.memory.network.min', and 'taskmanager.memory.network.max'.
	at org.apache.flink.runtime.io.network.buffer.NetworkBufferPool.internalCreateBufferPool(NetworkBufferPool.java:372)
`

By change the parallelism, I think this should improve the test stablity.

**Comment by zentol** [comment]
And what is the root cause of the issue?

**Comment by zjuwangg** [comment]
> And what is the root cause of the issue?

No limit parallelism causing insufficient number of network buffers in LocalExecutionEnvironment in certain situation.

**Comment by zentol** [comment]
> No limit parallelism causing insufficient number of network buffers in LocalExecutionEnvironment in certain situation.

And what are those certain situations? If the parallelism is a fixed value (because it runs on CI) and the number of required buffers is also a fixed value (because the job didn't change), then why is it failing _sometimes_?

Furthermore, why is only this test being touched? Why are other tests in this class, and by extension other JsonPlanTestBase sub-classes, not affected?

**Comment by zjuwangg** [comment]
> And what are those certain situations? If the parallelism is a fixed value (because it runs on CI with a supposedly constant number of CPU cores) and the number of required buffers is also a fixed value (because the job didn't change), then why is it failing _sometimes_?

It's very good question.
I don't known too much about runtime resource allocate behavior. Is there more  experience or advice to dig into deeper?

**Comment by zjuwangg** [comment]
Close this pr temporally until we exactly know why and fix it.

**Comment by zentol** [comment]
TBH I wouldn't know where to look myself, but it is very odd that this started to happen all of a sudden, and there appear to be several instances. A ticket has been filed for this issue: FLINK-21878

**Pull request closed without merging**
