### PR TITLE
[FLINK-8704] [tests] Port AccumulatorLiveITCase to MiniClusterResource

### PR DESCRIPTION
**Pull request by zhangminglei**
## What is the purpose of the change
This PR contains the first batch of test ports from ```TestingCluster``` to ```MiniClusterResource```.  I will push them one by one. Each test has it's own commit and is self-contained.

## Verifying this change
This change is covered by existing tests.

### CODE REVIEW

**Comment by zentol** [comment]
I would ask you to stop working on this issue.

You do not know what changes are required to properly port these tests. Adding a `MiniClusterResource` (or extend `AbstractTestBase`) is unfortunately not enough for the tests that are not covered by #5535 and #5542.

The remaining tests are really difficult to port as they *heavily* rely on internal API's. You see all that code in `verifyResults()`? All of that must be rewritten to rely on a (new!) abstraction that works for both legacy and Flip-6 clusters.

I appreciate you trying to contribute, but this issue is beyond your capabilities.

**Comment by zhangminglei** [comment]
Thanks @zentol Yes. I also find this issue is more difficult than what I thought before. I have found those test are really difficult when I keep working on this, as there are many internal API's I must know. Thanks again for telling me and I will leave this issue.

**Comment by zhangminglei** [comment]
I see ```verifyResults``` and I found it is too scared for me at this moment.

**Comment by aljoscha** [comment]
@zhangminglei I suggest you follow those issues and check out the solutions in the end. To be honest, I don't yet know how these difficult tests are going to be ported.

**Comment by zhangminglei** [comment]
@aljoscha Okay. thanks. I will follow those issues.

**Pull request closed without merging**
