### PR TITLE
[FLINK-10354] Revert "[FLINK-6328] [chkPts] Don't add savepoints to CompletedCheckpointStore"

### PR DESCRIPTION
**Pull request by dawidwys**
## What is the purpose of the change

This reverts commit 6f570e7b6810e1645a4f7094f17ab9e8559fa139. 

Savepoints are once again counted as checkpoint, so that if failure happens between savepoint and next checkpoint, side effects on exactly one sinks manifested during savepoint, are taken into account.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (**yes** / no / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by tillrohrmann** [comment]
How do we handle the situation when a savepoint is moved and cannot be recovered from anymore?

**Comment by dawidwys** [comment]
Unfortunately we will fail the recovery in this situation , but as discussed with @aljoscha this is a better situation than breaking consistency guarantees. This would be a faulty situation introduced by the user, but one the user can recover from manually.

**Comment by dawidwys** [comment]
In the long term, the plan is to differentiate between two kinds of savepoints: with(cancel-with-savepoint) and without side-effects (without cancel). The latter would be equivalent to last taken checkpoint, while the first one would stop the job creating a consistent savepoint.

**Comment by tzulitai** [comment]
The reverted changes looks good by itself, but I personally don't feel too comfortable giving a +1 here. Perhaps Till should give the final approval here.

If we do plan to revert this, we should at least have a big warning in the savepoints document page about how things could break.

Also as a side note, in the original JIRA discussion, it was mentioned that if we had FLINK-4815 merged, then it can be considered that we readd savepoints to the CompletedCheckpointsStore. How would that relate to the long-term solution that @dawidwys mentioned?

**Comment by aljoscha** [comment]
How simple was the revert? I.e. is it just a `git revert` or what did you need to adapt?

**Comment by dawidwys** [comment]
Yes, it was just a revert, I did not need to adapt anything.

**Comment by aljoscha** [comment]
I think falling back to earlier checkpoints/savepoints is orthogonal to this and covered in https://issues.apache.org/jira/browse/FLINK-4815.

As it is currently, you can have the (quite possible) scenario where you do a savepoint and then your job fails. This leads to data duplication in the sink.

I think the scenario where you do a savepoint, then delete that savepoint, and then try to recover is unlikely. And even if it does happen you can manually fix the situation by editing ZooKeeper entries (I think). There is no possible manual recovery for the above scenario (downstream systems possible have already consumed the emitted and committed data).

What do you think?

@tillrohrmann Is this "revert" still valid or where there changes in the meantime that could break things?

**Comment by aljoscha** [comment]
@dawidwys I looked at the code again and I think it's good to merge. It's a serious bug when it comes to exactly-once sinks.

Could you please also check and merge it on 1.5.x and 1.6.x so that we release the fix when we release new versions of these branches?

**Pull request closed without merging**
