### PR TITLE
 [FLINK-10427] [tests] Port JobSubmitTest to new code base

### PR DESCRIPTION
**Pull request by TisonKun**
## What is the purpose of the change

Port `JobSubmitTest` to new code base

## Brief change log

`JobSubmitTest` has three tests, here is their diagnosis:

`testFailureWhenJarBlobsMissing` should be ported to `TaskTest#...`, FLIP-6 loads library on TM, not JM.

To clarify, it is not applicable for FLIP-6 JM fail job because of failing to load library. So the porting job is active only when porting `TaskTest`. (Because the TaskTest is legacy test, too. we are unable to JUST add a test case onto that for now).

`testFailureWhenInitializeOnMasterFails` is covered by `JobSubmissionFailsITCase#testExceptionInInitializeOnMaster`

`testAnswerFailureWhenSavepointReadFails` is covered by `SavepointITCase#testSubmitWithUnknownSavepointPath`

## Verifying this change

All about removal of tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (**no**)
  - The serializers: (**no**)
  - The runtime per-record code paths (performance sensitive): (**no**)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (**no**)
  - The S3 file system connector: (**no**)

## Documentation

  - Does this pull request introduce a new feature? (**no**)
  - If yes, how is the feature documented? (**no**)

cc @tillrohrmann @GJL

### CODE REVIEW

**Comment by TisonKun** [comment]
FYI travis fails on irrelevant test.

```
org.apache.flink.runtime.jobmanager.scheduler.ScheduleOrUpdateConsumersTest  Time elapsed: 4.514 sec  <<< ERROR!
java.net.BindException: Address already in use
```

**Comment by TisonKun** [comment]
Still fails on `ScheduleOrUpdateConsumersTest`, can be reproduced on master, so it is irrelevant.

**Comment by tillrohrmann** [comment]
Build fails with
```
org.apache.flink.runtime.jobmanager.scheduler.ScheduleOrUpdateConsumersTest  Time elapsed: 5.292 sec  <<< ERROR!
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at org.apache.flink.shaded.netty4.io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
	at org.apache.flink.shaded.netty4.io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1358)
	at org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at org.apache.flink.shaded.netty4.io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1019)
	at org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
	at org.apache.flink.shaded.netty4.io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366)
	at org.apache.flink.shaded.netty4.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at org.apache.flink.shaded.netty4.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at org.apache.flink.shaded.netty4.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by TisonKun** [comment]
@tillrohrmann see also [FLINK-10454](https://issues.apache.org/jira/browse/FLINK-10454), I think it is a separated issue.

**Comment by TisonKun** [comment]
Thanks for your review @tillrohrmann !

**Pull request closed without merging**
