### PR TITLE
[hotfix][docs] Update the links' tags in the 'Debugging Windows & Event Time' page of 'Debugging & Monitoring'

### PR DESCRIPTION
**Pull request by RocMarshal**
## What is the purpose of the change

*Update the links' tags in the 'Debugging Windows & Event Time' page of 'Debugging & Monitoring'*

## Brief change log

*Fix the links' tags in the 'Debugging Windows & Event Time' page of 'Debugging & Monitoring'*

## Verifying this change

*A pure documentation hot fix on link tag for the 'Debugging Windows & Event Time' page of 'Debugging & Monitoring'*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by RocMarshal** [comment]
Hi, @wuchong .
I made a `hotfix`. Please take a look.
Thank you.

**Comment by RocMarshal** [comment]
Hi, @rmetzger 
I made a hotfix. Please take a look.
Thank you.

**Comment by RocMarshal** [comment]
> I'm fine with this change, and the change LGTM. but I'm not very sure if we'll accept such change or do we want to replace all the `{site.baseurl}` with `{% link %}` in one commit.

Hi, @klion26 .
Thank you for your response.

The original reason for proposing such hotfix PR is to keep consistent with my translation work. Whenever I complete the corresponding translation page, I will review the corresponding original page. If there is something that needs to be improved, I hope to put it in one commit. However, it seems that it is not recommended to put it in one commit ([PR12798](https://github.com/apache/flink/pull/12798#discussion_r450615831)). Therefore, I put the similar hotfix into a commit separately. If it might seem insignificant, I will close the PR. In the future, I will not do such operations again and only complete the works described in the corresponding JIRAs.

Of course, at present, I prefer the latter that sounds get twice the result with half the effort. 

@alpinegizmo @klion26 
Could you tell me more details about your suggestions?

Thank you .

**Comment by klion26** [comment]
@RocMarshal Sorry for the confusion. What I mean in the previous comment is that: I'm not sure whether we'll replace `{site.baseurl}` with `{%link %}` in all the documentation in one commit. There are many `{site.baseurl}` in the documentation.

**Comment by RocMarshal** [comment]
ping @wuchong

**Pull request closed without merging**
