### PR TITLE
[FLINK-28948][table] Increase test coverage for lookup full caching + fix metrics

### PR DESCRIPTION
**Pull request by SmirAlex**
## What is the purpose of the change

This pull request introduces more tests for recently added feature with full caching lookup and adds missing metrics

## Brief change log

- Added metrics `hitCounter` and `missCounter`
- Fixed concurrent metrics creation 
- Added unit tests for `LookupFullCache` and `InputFormatCacheLoader`

## Verifying this change

This change added tests and can be verified as follows:

- `LookupFullCacheTest`
- `InputFormatCacheLoaderTest`

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature?  no)
  - If yes, how is the feature documented? (JavaDocs )

### CODE REVIEW

**Comment by SmirAlex** [comment]
Successful pipeline - https://dev.azure.com/asmirnov1/Flink/_build/results?buildId=30&view=results

**Comment by SmirAlex** [comment]
Successful pipeline - https://dev.azure.com/asmirnov1/Flink/_build/results?buildId=30&view=results

**Review by PatrickRen — APPROVED** [review]
Sorry for the delay and thanks for the patch @SmirAlex ! LGTM. Could you rebase the commit the the latest master? I'll merge the PR once the CI passes.

**Comment by PatrickRen** [comment]
@SmirAlex looks like there are new code merged in master 😞  Could you resolve these conflicts? Thanks

**Pull request merged**
