### PR TITLE
[FLINK-14605][hive] Use Hive-1.1.0 as the profile to test against 1.1.x

### PR DESCRIPTION
**Pull request by lirui-apache**
## What is the purpose of the change

Test against Hive-1.1.0.

## Brief change log

  - Changed the 1.1.x profile to use Hive-1.1.0.

## Verifying this change

Manually verified tests pass with 1.1.0.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): yes
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? NA

### CODE REVIEW

**Comment by lirui-apache** [comment]
cc @bowenli86 @xuefuz @zjuwangg

**Comment by bowenli86** [comment]
This surely resolves the testing failure. What does it mean for Flink to work with hive 1.1.1 in production? Is root cause https://issues.apache.org/jira/browse/HIVE-10831 ? Do we need to document this to inform Flink users?

**Comment by lirui-apache** [comment]
> This surely resolves the testing failure. What does it mean for Flink to work with hive 1.1.1 in production? Is root cause https://issues.apache.org/jira/browse/HIVE-10831 ? Do we need to document this to inform Flink users?

@bowenli86 The issue is that Hive parser can't handle the "stored as" syntax. Since we're not using Hive parser in production code (not yet at least), I don't think it'll be a problem in production. And since this is a known Hive issue, which user is probably aware of, I prefer not to document it on our side, otherwise we'll end up documenting all kinds of Hive issues.

**Comment by bowenli86** [comment]
Thanks! LGTM, merging

**Pull request closed without merging**
