### PR TITLE
[FLINK-15360][e2e] Fix the parameter issue in retry_times

### PR DESCRIPTION
**Pull request by KarmaGYZ**
## What is the purpose of the change

This PR fix the parameter issue in `retry_times` function of common.sh.

## Brief change log

Fix the parameter issue in `retry_times` function of common.sh.

## Verifying this change

Trigger container relevant e2e tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

cc: @wangyang0918 @tillrohrmann 
Since it's a blocker issue for e2e test, I open this PR without being assigned first.

### CODE REVIEW

**Comment by KarmaGYZ** [comment]
After https://github.com/apache/flink/commit/bdd432a09a776fec88f465771101893a8151dc1d , the retry_times function could not accept commands with multiple parts split by whitespace. This PR fix that problem.

**Comment by KarmaGYZ** [comment]
Travis give green light to relevant tests https://travis-ci.org/KarmaGYZ/flink/builds/628343573

**Comment by wangyang0918** [comment]
This is really a magic code. However, i think it could work. Because when we define a new local shell variable and then pass it to the function `retry_times_with_backoff_and_cleanup`, it will be treated as one argument. If we directly pass `${@:3}` to the function, since it a shell array, they will be treated as multiple arguments in `retry_times_with_backoff_and_cleanup`.

**Comment by KarmaGYZ** [comment]
@flinkbot run travis

**Comment by zhijiangW** [comment]
Thanks for the fix @KarmaGYZ . After the travis pass, you can ping me then i would merge it.

**Comment by zhijiangW** [comment]
In addition, it is better to copy some descriptions from jira ticket to the commit content. Then it would be helpful to further understand the motivation and changes of this commit. You can also submit a pr for the release-1.10 branch.

**Comment by KarmaGYZ** [comment]
@flinkbot run azure

**Comment by KarmaGYZ** [comment]
Travis passed.
cc @zhijiangW .

**Comment by tillrohrmann** [comment]
Quick question, isn't the problem that we pass the `command` in https://github.com/apache/flink/commit/cce1cef50d993aba5060ea5ac597174525ae895e as multiple strings instead of wrapping the command in `""` before we pass it to `retry_times`? If I look at `retry_times_with_backoff_and_cleanup` then one also needs to pass the `command` and `cleanup_command` as a single string (meaning one needs to wrap it into `""`). The fix seems to underline this as we are joining `${@:3}` into a single string.

**Comment by KarmaGYZ** [comment]
> Quick question, isn't the problem that we pass the `command` in [cce1cef](https://github.com/apache/flink/commit/cce1cef50d993aba5060ea5ac597174525ae895e) as multiple strings instead of wrapping the command in `""` before we pass it to `retry_times`? If I look at `retry_times_with_backoff_and_cleanup` then one also needs to pass the `command` and `cleanup_command` as a single string (meaning one needs to wrap it into `""`). The fix seems to underline this as we are joining `${@:3}` into a single string.
> 
> The problem now is that `retry_times` and `retry_times_with_backoff_and_cleanup` behave differently wrt their parameters.

Before [bdd432](https://github.com/apache/flink/commit/bdd432a09a776fec88f465771101893a8151dc1d), `retry_times` will joining `${@:3}` into a single string. So, I think that commit changes the contract of `retry_times`, not as excepted. This PR fix that problem.

Regarding to the inconsistent parameter, I agreed it's better to align the behavior of two functions. We could work on it in future work. WDYT?

**Pull request merged**
