### PR TITLE
[HOTFIX][coordination] remove the invalid parameter in handleCheckpointSuccess method

### PR DESCRIPTION
**Pull request by lamber-ken**
## What is the purpose of the change

remove the invalid parameter in handleCheckpointSuccess method

## Brief change log

remove the invalid parameter

## Verifying this change

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? ( no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by TisonKun** [comment]
@flinkbot attention @yanghua 

please take a look why we don't use this parameter.

**Comment by yanghua** [comment]
@lamber-ken @TisonKun Please do not remove this parameter. We added specially for the further work. Currently, the checkpoint id counting mechanism does not consider the checkpoint sequence.

**Comment by TisonKun** [comment]
Thanks for your information @yanghua !

Due to the ongoing effort I'd like to close this pull request. @yanghua it would be helpful for further reference if someone file a similar pull request that you link the corresponding JIRA thread here.

**Comment by yanghua** [comment]
OK, the relevant JIRA issue about this parameter is: https://issues.apache.org/jira/browse/FLINK-12514

**Comment by lamber-ken** [comment]
> OK, the relevant JIRA issue about this parameter is: https://issues.apache.org/jira/browse/FLINK-12514

Hi, @yanghua, you can update the param comment when you work on FLINK-12514. 

PS: the failed checkpoint id -> the successed checkpoint id 

```
/**
 * Handle checkpoint success.
 *
 * @param checkpointId the failed checkpoint id used to count the continuous failure number based on
 *                     checkpoint id sequence.
 */
public void handleCheckpointSuccess(long checkpointId) {
	clearCount();
}
```

**Comment by yanghua** [comment]
@lamber-ken Good catch! thanks, I will fix it.

**Pull request closed without merging**
