### PR TITLE
[FLINK-3145][storm] pin Kryo version of transitive dependencies

### PR DESCRIPTION
**Pull request by mxm**

### CODE REVIEW

**Comment by StephanEwen** [comment]
Thanks for discovering and fixing this.

Since that may happen with other projects as well, I was wondering if we should make this a dependency and managed dependency of the root flink project (from which all others inherit). Similar to slf4j, etc...

**Comment by StephanEwen** [comment]
As a separate issue: We could also look into updating our Kryo dependency:

<dependency>
	<groupId>com.esotericsoftware</groupId>
	<artifactId>kryo-shaded</artifactId>
	<version>3.0.3</version>
</dependency>

**Comment by mxm** [comment]
Not sure about the Kryo dependency in the root pom. We already pin the Kryo version via dependency management in the root pom. This eliminates most conflicts in sub projects. The proposed changes are a special solution for the flink-storm module which has conflicting transitive dependencies due to its dependency on Storm.

Kryo version is 2.24.0. Where did you get the 3.0.3 from?

**Comment by StephanEwen** [comment]
Fair enough, let's leave it specific to storm then.

Kryo beyond 2.24.0 changed maven group and artifact names...

**Comment by mxm** [comment]
I'm not really sure about the implications of Kryo in the root pom so I try to fix it where it is a problem first.

>Kryo beyond 2.24.0 changed maven group and artifact names...

Ah I see. Let's update the Kryo version in a separate step.

**Pull request closed without merging**
