### PR TITLE
[FLINK-22096][tests] Fix port conflict for ServerTransportErrorHandlingTest#testRemoteClose

### PR DESCRIPTION
**Pull request by TanYuxin-tyx**
## What is the purpose of the change

Fix port conflict in `ServerTransportErrorHandlingTest#testRemoteClose`. In the test case, a `BindException`  may be thrown when init Netty server. When initializing Netty server, `NetUtils.getAvailablePort()` is called in `createConfig()`. After obtaining the available port, the port may be used by other processes, which may lead to `BindException`. To resolve the issue, a retry is added when calling `initServerAndClient` method.

## Brief change log
  - *Add the number of retries when initializing the Netty server in the test case*

## Verifying this change
  - *Initializing  the Netty server successfully in the test case*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by TanYuxin-tyx** [comment]
This is a new PR to resolve the conflicts of release-1.13. The original PR is https://github.com/apache/flink/pull/17532.

**Comment by wsry** [comment]
@flinkbot run azure

**Comment by wsry** [comment]
I will help to merge this PR after all tests pass.

**Review by wsry — APPROVED** [review]

**Comment by wsry** [comment]
Merged.

**Pull request closed without merging**
