### PR TITLE
[FLINK-1990] [staging table] Support upper case of `as` for expression

### PR DESCRIPTION
**Pull request by chhao01**

### CODE REVIEW

**Comment by aljoscha** [comment]
Thanks for your contribution!

Could you maybe enhance it along these lines: http://stackoverflow.com/questions/6080437/case-insensitive-scala-parser-combinator

Because right now it would only support as and AS, but not As or aS. I know the latter is a rather academic example, but still...

Would you also be interested in adding SQL style aggregations, for example COUNT(field), MAX(field) and so on? I could open a Jira for this.

**Comment by chhao01** [comment]
Thanks for the quick response, I was not sure which is suppose to be. Since it's case-insensitive, I will update the code with unit test soon.

Yes, I am interested in adding the SQL style aggregations, it will be great if you can create the jira and assign to me. :)

**Comment by aljoscha** [comment]
I created this issue for the aggregations: https://issues.apache.org/jira/browse/FLINK-2000. I think I can only assign you if you have a Jira account. Do you have one?

**Comment by chhao01** [comment]
@aljoscha sorry for the delay, my jira id is `chhao01`, and I can start working on the `FLINK-2000` once this got merged.

**Comment by chhao01** [comment]
@aljoscha there is nothing when I open the Travis CI link, is there any hint why this failed?

**Comment by aljoscha** [comment]
I'll check it out.

**Comment by aljoscha** [comment]
For some reason it doesn't like the keywork2Parser when you use String Interpolation. If you replace the line with:
```
    ("""(i?)\Q""" + kw.key + """\E""").r
```

it should work.

**Comment by chhao01** [comment]
Thank you @aljoscha, eventually I got the IDE works with unit test, and I update the code, let's see what travis will say.

**Comment by chhao01** [comment]
Failed in `flink-streaming-connectors` with java 8, does that related to this change?

**Comment by aljoscha** [comment]
Can you post a link to the failed run? Or is it on your local machine? Some of the streaming test cases fail sometimes right now, this is a known problem.

**Comment by aljoscha** [comment]
I'm running my own tests on travis and then I'll merge it.

**Pull request closed without merging**
