### PR TITLE
[FLINK-4226] Typo: Define Keys using Field Expressions example should use window and not reduce

### PR DESCRIPTION
**Pull request by ASRagab**

### CODE REVIEW

**Comment by rmetzger** [comment]
merging ...

**Comment by rmetzger** [comment]
@ASRagab: Could you close the pull request? I can not close the PR from the Github interface and I forgot to include the magic string to close it from the commit message.

**Comment by ASRagab** [comment]
Closing...

**Comment by rmetzger** [comment]
Thank you!

**Pull request closed without merging**
