### PR TITLE
[FLINK-21665][Table] Support [IF NOT EXISTS] and [COMMENT] for create catalog statement

### PR DESCRIPTION
**Pull request by humengyu2012**
## What is the purpose of the change

This pull request supports create catalog by CREATE CATALOG catalog_name [COMMENT catalog_comment]  [WITH (property_name=property_value, ...)] syntax.

## Brief change log

  - Support syntax in flink and hive parser;
  - Support syntax in TableEnvironment.

## Verifying this change

  - Added tests in [SqlCommandParserTest, TableEnvironmentTest, CliClientTest, FlinkSqlParserImplTest, FlinkHiveSqlParserImplTest] to verify syntax support.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? docs

### CODE REVIEW

**Comment by wuchong** [comment]
We can't merge this as this is not a full feature. This only support parsing syntax in sql-parser. Please also support in `TableEnvironment`.

**Comment by humengyu2012** [comment]
Thanks, I will continue to improve.

**Comment by MartijnVisser** [comment]
@humengyu2012 Can you let me know what you think is the status of this PR?

**Comment by humengyu2012** [comment]
This PR has been over too long, resulting in many conflicts that could not be resolved, I will close it.

**Pull request closed without merging**
