### PR TITLE
[FLINK-5749]unset HADOOP_HOME and HADOOP_CONF_DIR to avoid env in build machine failing the UT and IT

### PR DESCRIPTION
**Pull request by wenlong88**
Currently when we are trying to build flink on a machine with HADOOP_HOME environment variable set, Test data will be written to HDFS, instead of local tmp dir which is expected. This will cause tests failed. 
This PR unsets HADOOP_HOME and HADOOP_CONF_DIR environment variable in pom, to make sure maven run the test cases in the exactly way we want.

### CODE REVIEW

**Comment by StephanEwen** [comment]
I think this is a good addition.

We could try and make this change more targeted to the Maven project that has the affected tests. That would help us keeping the root pom.xml more compact. For example if this affects only tests in `flink-fs-tests` then we can for example make this change in `flink-fs-tests`.

Can you share what tests are affected by this?

**Comment by wenlong88** [comment]
hi @StephanEwen, the cases in flink-filesystem-connector will fail first in our building machine. I have go through the cases in flink-fs-tests, I think they will fail too if I remove the change from the root pom. I think it is better to set in the root pom, because the HadoopUtils is in the package flink-java, and many modules have dependency on flink-java and users of the utils may have no idea that the HadoopUtils have dependency on the environment variables that will cause wired failures and it is hard to trace.

**Comment by StephanEwen** [comment]
For the `HadoopUtils` in `flink-java` - I think those need to depend on the variables and are also not in the test scope.

The reason why I am asking also do make the change more to `filesystem-connector` and `fs-tests` is that we want to gradually make Flink depend less and less on Hadoop, so to move all Hadoop dependencies into separate optional modules. More targeted environment variable exclusion would fit that design better.

**Comment by wenlong88** [comment]
ok, I will move the changes to filesystem-connector and fs-tests poms.

**Comment by wenlong88** [comment]
hi @StephanEwen , I have move the changes to child module pom,  `flink-tests` and `flink-hadoop-compatibility` need to be changed too, because the mapreduce related cases will load output compaction setting from the cluster configuration.

**Comment by StephanEwen** [comment]
Looks good, thank you!
Merging this...

**Pull request closed without merging**
