### PR TITLE
[FLINK-4317, FLIP-3] [docs] Restructure docs

### PR DESCRIPTION
**Pull request by uce**
This is the initial layout for the docs restructuring as discussed in FLIP-3.

We move the top level navigation to the left side and allow arbitrary nestings to be defined. The main goal is that users find more of the important content. Therefore the docs are now treating streaming as the default and move some streaming-only content to the top-level.

This kind of left-side navigation layout is also followed by other popular projects like [Google DataFlow docs](https://cloud.google.com/dataflow/docs/) or http://readthedocs.org.

You can preview the new layout here: http://uce.github.io/flink/

We need to follow up with more actual content (see FLIP-3). If we adapt this layout, I would file the required content changes as JIRAs and ask someone to coordinate the writing process among the interested contributors.

### CODE REVIEW

**Comment by aljoscha** [comment]
I really like the new look/structure. 👍 

What's strange is that when I click the breadcrumb links, I get an empty page. For example if I click "API" here:
screen shot 2016-08-19 at 09 39 03

**Comment by uce** [comment]
Yes, we still have to add content for the overview pages, in that case `apis.md`.

**Comment by tillrohrmann** [comment]
Cool changes @uce. I really like them. I was wondering whether we should center the content pane instead of the content pane + navigation menu.

**Comment by rmetzger** [comment]
Where are the streaming connectors linked?

image

**Comment by uce** [comment]
That was a bug. Fixed and updated preview. It's found under `Application Development` on the same level as `State Backends` etc.

**Comment by rmetzger** [comment]
Great, thank you.

+1 to merge :)

**Comment by uce** [comment]
@aljoscha I will add some text to the overview pages.

@tillrohrmann I will check out whether I can do it. It's certainly possible to do it, but we might need to do it as a follow up if I can't get it done in a reasonable amount of time. ;)

Would you like to also merge this for 1.1? If yes, I would add redirects for links that have changed.

**Comment by jgrier** [comment]
This looks great!  I really like the left side navigation.  I think this is a big improvement.

One suggestion:  Can we change the name of the "Testing & Debugging" section to something like "Monitoring and Debugging"?.  Most of what's in that section is about monitoring.

**Comment by uce** [comment]
I've addressed @aljoscha's and @jgrier's comments. @tillrohrmann I could not figure out how to do the centering in a different way, but I'm sure we (someone with more CSS skills) can address this as a follow up.

Since this is quite a major change, I would like to wait a little longer to get some more feedback. The question whether to merge this for 1.1 is open, too.

@greghogan @vasia Are you OK with the way Gelly is linked?

**Comment by greghogan** [comment]
@uce this looks very nice, and navigating libraries is much improved with the extra level(s?) of navigation.

**Comment by rmetzger** [comment]
I'm against merging it to the 1.1.x branch. Its a big change, that we would do between releases.
In a few months, we'll have a new release, then users can enjoy the new layout.

**Comment by StephanEwen** [comment]
+1 to merge this.

Merging it for 1.2 makes more sense to me.
Having it for 1.2-SNAPSHOT makes this already accessible for users and we don't mess up patching the 1.1 docs.

**Pull request closed without merging**
