### PR TITLE
Blink init

### PR DESCRIPTION
**Pull request by ajliualiyun**
## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by asdf2014** [comment]
喜大普奔~ :+1:

**Comment by twalthr** [comment]
@ajliualiyun any PR opened against the Blink branch should still contain a valid title and description. Otherwise it is difficult for the community to decide whether this change should go in or not. I think we don't need a JIRA issue but we should know what a change is about.

CC @KurtYoung

**Comment by amoygao** [comment]
@ajliualiyun @KurtYoung org.apache.flink.sql.parser.impl.FlinkSqlParserImpl is missing in blink branch

**Comment by chucklu** [comment]
@ajlsms  It's terrible to write the commit message in Chinese for such a international open source project.
You could modify the previous commit message according this documentation [Changing a commit message](https://help.github.com/articles/changing-a-commit-message/ 
)

**Comment by chucklu** [comment]
@ajliualiyun   I have checked the commits on https://github.com/ajliualiyun/flink/tree/blink, butI only find one commit 58846f561e522209557b638084bfe5db2f1b5777, where is the other commit a14675b7bbf8f4d82fa5c234b4fa8279baa538b1?
@twalthr It seems the [pull request is created from a fork](https://help.github.com/articles/creating-a-pull-request-from-a-fork/), it's weird the commit a14675b7bbf8f4d82fa5c234b4fa8279baa538b1 did not exist on blink branch of the fork repository.

**Comment by twalthr** [comment]
Thanks for investigating @chucklu. I will close this PR for now. @ajliualiyun feel free to open a new one with proper PR title, description, commit message and base.

**Comment by lincoln-lil** [comment]
hi, liukaiyi
   the `org.apache.flink.sql.parser.impl.FlinkSqlParserImpl` is a generated
class,  you can run maven local install before testing (testing the
extended calcite parser has a little difference against other testing).

liukaiyi <notifications@github.com> 于2019年2月1日周五 下午12:25写道：

**Pull request closed without merging**
