### PR TITLE
[FLINK-18307][scripts] Rename 'slaves' file to 'workers'

### PR DESCRIPTION
**Pull request by StephanEwen**
## Purpose of the change / Change log

This changes the name of the file for the TaskManager workers from *slaves* to *workers*.

**Note:** This change breaks setups that currently use the *slaves* file, because it only checks for the *workers* file. The reason is that production setups should not really rely on that file and the associated start/top scripts (rather use Yarn, Kubernetes, custom init.d scripts) because of all the limitations (for example never restarting failed TaskManagers).
The advantage of not implementing the "backwards compatibility" here is to get rid of the *"slaves"* term in the scripts right away.

## Verifying this change

This change can be verified by building Flink and starting/stopping a standalone session via `bin/start-cluster.sh` / `bin/stop-cluster.sh`.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): **no**
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: **no**
  - The serializers: **no**
  - The runtime per-record code paths (performance sensitive): **no**
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: **no**
  - The S3 file system connector: **no**

## Documentation

  - Does this pull request introduce a new feature? **no**
  - If yes, how is the feature documented? **not applicable**

### CODE REVIEW

**Comment by rmetzger** [comment]
Thanks a lot for addressing this.
Two quick comments:
1. There are still some mentions of "*slave*" in the docs
2. This might cause the Java e2e tests to fail: https://github.com/apache/flink/blob/master/flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/flink/FlinkDistribution.java#L271

**Comment by rmetzger** [comment]
I tested the updated scripts locally, and they work as expected (on a Mac) for starting and stopping a cluster with 3 TaskManagers.

**Comment by StephanEwen** [comment]
Thanks for the fast and thorough review. Will address the issues as you mentioned.

**Comment by StephanEwen** [comment]
Merged in c47fb4704ccd123cb71ee9f3379a166f91f1c217

**Pull request closed without merging**
