### PR TITLE
[FLINK-14332] [flink-metrics-signalfx] add flink-metrics-signalfx

### PR DESCRIPTION
**Pull request by lukess**
## What is the purpose of the change

add flink-metrics-signalfx metrics reporter - https://www.signalfx.com/

## Brief change log

- add sfx metrics reporter
- cleanup test case for signalfx resetting histogram based on EDR 
- package dependencies

## Verifying this change

This change added tests and can be verified as follows:

  - *Added test that validates that additional resetting histogram - https://github.com/signalfx/signalfx-java/tree/master/signalfx-codahale/src/main/java/com/signalfx/codahale/metrics
  - *meter and gauge remain the same with flink-metrics-dropwizard 
  - *flink-conf.yaml
    metrics.reporter.signalfx.class: org.apache.flink.metrics.signalfx.ScheduledSignalFXReporter
    metrics.reporter.signalfx.interval: 60 SECONDS
    metrics.reporter.signalfx.token: xxx
    metrics.reporter.signalfx.filters: KafkaConsumer,KafkaProducer

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): yes, add dependency
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: yes
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: metrics
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? yes

### CODE REVIEW

**Comment by lukess** [comment]
@rmetzger I updated the description, docs, and flink-dist for opt/ release. May I know how to cleanup warnings from automated checks?

**Comment by lukess** [comment]
@flinkbot run travis

**Comment by lukess** [comment]
I think I gonna wait for #9863

**Comment by lukess** [comment]
[FLINK-14308](https://issues.apache.org/jira/browse/FLINK-14308)

**Comment by aljoscha** [comment]
I will review this once #9863 is in. Could you then please rebase and squash into one commit so that I can review it?

**Comment by lukess** [comment]
@aljoscha thank you for your response. I just rebase and squash.

**Comment by zentol** [comment]
Just a few drive-by notes:

1. there should be a discussion on the ML as to whether accept more reporters; we already maintain quite a few and have to start thinking about maintainability. Why could this not be maintained outside of Flink?
2. Wouldn't this be a lot easier to implement if we simply bumped dropwizard? Our current version is fairly old anyway.
3. If 2) doesn't work, then the reporter should be implemented using the new factory approach; see the JMXReporter as an example.

**Comment by lukess** [comment]
@zentol thanks for comment, let me try to answer questions:
1. Are you talking about something like bahir-flink (connector) for metrics? A central place to release flink metrics extensions I think is good. I can move this plugin (and others) as well. My current issue is that our org heavily rely on SFX alert. I do that for our production and for others who using SFX metrics.
2. I think to bump dropwizard probably cannot solve the io.dropwizard.metrics:metrics-core out-of-sync problem when signalfx-codahale and signalfx-java bump the io.dropwizard.metrics:metrics-core dependency. For ScheduledDropwizardReporter users do not need SFX libs as well.
3. I think this is a good way to go. Let me check the new JMXReporter.

**Comment by zentol** [comment]
1) No I wasn't talking about bahir-flink; I meant more for you to create a dedicated repository publish releases etc, and we just link it in the documentation for example. There are also discussion on the ML about a page for sharing flink projects (reporters, connectors, examples, etc.), but I don't know what the current state is on that front.
2) Are there actually conflicts when you depend on flink-metrics-dropwizard but pin the codahale version to whatever SFX is using?
3) Yes, reporters following the factory approach typically do not _need_ to implement `open()`.

**Comment by lukess** [comment]
@zentol 
1. yes, I think I will follow community decision. Both self release or shared release work to me. One thing in my mind is how to control quality and release between upstream and many repos (or one shared repo) 
2. yes, I can bump flink-metrics-dropwizard, and let them depends on the same codahale.
3. ok cool, I just follow the JMXReporter to create new factory, and updated docs.

**Comment by aljoscha** [comment]
@lukess  So what's the outcome for this PR, should we close it and the Jira issue?

**Comment by lukess** [comment]
@aljoscha I'm actually working on changes. After I running this plugin on production for a month I start to see the pain when I need to filter metrics based on path and separator. Graphite separator is dot for example.

**Comment by aljoscha** [comment]
Ok, please ping me if you have anything.

**Comment by lukess** [comment]
@aljoscha I'm running the new SignalFXReporter in our environments. Current implementation:
1. current metric full name is from MetricGroup getScopeComponents(), and remove MetricGroup getAllVariables(), and finally append metricName from notifier. The getAllVariables() store as SFX dimensions that are similar to Graphite 1.1.x tags.
2. SFX AggregateMetricSender works as reporter to send protobuf data point to SFX backend
3. support Gauge, Meter and Counter
4. remove unnecessary tests

**Comment by lukess** [comment]
@aljoscha do you have time to review current progress? thanks

**Comment by aljoscha** [comment]
@zentol Could you maybe take this over? You know more about both metrics and the licensing setup.

**Comment by lukess** [comment]
thanks @aljoscha @zentol
Because I'm using this reporter in our production I also add filter to control the cost.

**Comment by aljoscha** [comment]
Also posted this to the Jira issue: https://issues.apache.org/jira/browse/FLINK-14332

Hi Luke Sun,

I'm very sorry about the hassle with this feature but the Flink community added https://flink-packages.org/ exactly for such cases. We first want to add integrations with external projects there and possibly move them to Flink proper when there is huge community demand.

This is, for example, the entry for the DogStatsD reporter: https://flink-packages.org/packages/dogstatsd-metrics-reporter. I suggest to similarly add the SignalFX reporter there. I'm happy to help with the process for this or get the right people (Robert Metzger) involved.

**Pull request closed without merging**
