### PR TITLE
[FLINK-10559] Remove LegacyLocalStreamEnvironment

### PR DESCRIPTION
**Pull request by TisonKun**
## What is the purpose of the change

Remove `LegacyLocalStreamEnvironment` which based on legacy mode and now we have its replacement `LocalStreamEnvironment`.

It looks like not just a simply removal because some previous miss or mistake.

1. `PythonEnvironmentFactory` still use `LegacyLocalStreamEnvironment`, which I believe is a missing task.

2. `LegacyLocalStreamEnvironment` is with annotation `@Public` by [this commit](https://github.com/apache/flink/commit/af5279e9bd3dec18512a54c59982e3dc1f253cd2). Of course `LocalStreamEnvironment` is `@Public` but `LegacyLocalStreamEnvironment` should never be.

## Brief change log

Remove `LegacyLocalStreamEnvironment.java`.

Replace `LegacyLocalStreamEnvironment` with `LocalStreamEnvironment` in `PythonEnvironmentFactory.java`, I believe it is a missing task.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**no**)
  - The public API, i.e., is any changed class annotated with `(Evolving)`: (**yes**, but I think it is because of a mistake.)
  - The serializers: (**no**)
  - The runtime per-record code paths (performance sensitive): (**no**)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (**no**)
  - The S3 file system connector: (**no**)

## Documentation

  - Does this pull request introduce a new feature? (**no**)
  - If yes, how is the feature documented? (**not applicable**)

cc @tillrohrmann @aljoscha

### CODE REVIEW

**Comment by zentol** [comment]
I would be fine with removing it. The class should never have been public, and I reckon this was simply an oversight when renaming it.

**Comment by TisonKun** [comment]
Thanks for you reply @zentol! Then how to solve this api incompatibility error? I am not familiar with `japicmp:japicmp` :-(

**Comment by zentol** [comment]
you (probably?) have to add an exclusion [here](https://github.com/apache/flink/blob/master/pom.xml#L1623); I've never done that either so I'm not sure on the syntax. But something like `<exclude>org.apache.flink.streaming.api.environment.LegacyLocalStreamEnvironment</exclude>` might suffice.

**Comment by TisonKun** [comment]
thanks, let me do a try.

**Comment by TisonKun** [comment]
ping @zentol travis gives green and I think this pull request is anyway a trivial work. please take a look :-)

**Pull request merged**
