### PR TITLE
[FLINK-4016] initialize FoldApplyWindowFunction properly

### PR DESCRIPTION
**Pull request by rvdwenden**

### CODE REVIEW

**Comment by aljoscha** [comment]
Hi,
I wrote in the issue that you opened. This is a duplicate of https://issues.apache.org/jira/browse/FLINK-3977 and the way to fix it is to make `InternalWindowFunction` properly forward calls to `setOutputType`. If you want, could you please change your fix to that and open a PR against the older issue?

**Comment by rvdwenden** [comment]
I checked in this change with this commit comment:
[FLINK-3977] initialize FoldApplyWindowFunction properly 

Hopefully that’s enough, however, on Travis CI I see that on my commit, the [FLINK-4016] is still triggered.

Regards, RvdWenden

**Comment by aljoscha** [comment]
Hi,
the clean way to go about this is to close this PR and open a new one for `FLINK-3977`. I wrote a new comment in the issue, outlining how the problem can be solved: https://issues.apache.org/jira/browse/FLINK-3977.

**Comment by aljoscha** [comment]
Closing, because the issue has been solved a different way.

**Pull request closed without merging**
