### PR TITLE
[FLINK-14637] Introduce framework off heap memory config

### PR DESCRIPTION
**Pull request by xintongsong**
## What is the purpose of the change

This PR introduces a config option accounting for Flink framework off-heap memory usage (except for network buffers).

## Brief change log
- 402f7a39de80edadf7ad22d7fef5c9bd13f29386: Hotfix of adding shortcuts getting jvm heap/direct memory size in `TaskExecutorResourceSpec`.
- 05f8a709b0fbf7872aa11e33b8c7148c08ec36e6: Introduce config option for framework off-heap memory size.
- a862a0263ef349bf8df8a47242b1a768f0b10489: Introduce framework off-heap memory size in `TaskExecutorResourceSpec`
- f5fbfbd4f113563ea20ee6eed0b70905abcfa3fd: Update memory calculation logics to account for framework off-heap memory size.
- e9e139cea0b3d1ed18fd614c56563c6df036e30f: Generate dynamic configurations with respect to framework off-heap memory size.

## Verifying this change

- Add `TaskExecutorResourceUtilsTest#testConfigFrameworkOffHeapMemory`
- Update `TaskExecutorResourceUtilsTest#testGenerateDynamicConfigurations`
- Update `TaskExecutorResourceUtilsTest#testGenerateJvmParameters`

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by xintongsong** [comment]
@azagrebin, please help review this PR.
Travis passed: https://travis-ci.org/xintongsong/flink/builds/609050197

**Comment by xintongsong** [comment]
@azagrebin, thanks for the review. Comments addressed.

**Comment by xintongsong** [comment]
Travis passed: https://travis-ci.org/xintongsong/flink/builds/611718787

**Comment by azagrebin** [comment]
merged into master by 306b83b2f6c64b37162a0aa3b6ce290c4b34bc4f

**Pull request closed without merging**
