### PR TITLE
[FLINK-4379]  Rescalable non-partitioned state

### PR DESCRIPTION
**Pull request by StefanRRichter**
This pull request introduces rescalable non-partitioned operator state as described in issue [FLINK-4379] and makes following major changes:

# 1) Introducing interfaces `PartitionableStateBackend` and `SnapshotProvider`

For rescaling purposes, non-partitioned state is now stored in a `PartitionableStateBackend`, which provides a method to register operator states under unique names and store state partitions in a list state:

```
<S> ListState<S> getPartitionableState(
	String name,
	TypeSerializer<S> partitionStateSerializer) throws Exception;
```

Notice that a `TypeSerializer` is provided on a per-state basis so that we can realize backward compatibility if the serialization format changes.

Furthermore, we introduce `SnapshotProvider` which offers a method to create snapshots:

```
RunnableFuture<S> snapshot(
	long checkpointId,
	long timestamp,
	CheckpointStreamFactory streamFactory) throws Exception;
```

`PartitionableSnapshotStateBackend` is a combination of both, `PartitionableStateBackend` and `SnapshotProvider`, where the first interface gives a view that is exposed to user code and the later interface is only used by the system to trigger snapshots.

Similar to other state backends (e.g. `KeyedStateBackend`), a `PartitionableSnapshotStateBackend` can be created and restored through the class `AbstractStateBackend`:

```
public PartitionableSnapshotStateBackend createPartitionableStateBackend(
	Environment env,
	String operatorIdentifier)

public PartitionableSnapshotStateBackend restorePartitionableStateBackend(
	Environment env,
	String operatorIdentifier,
	Collection<PartitionableOperatorStateHandle> restoreSnapshots)
```

# 2) Interface `PartitionableCheckpointed` as replacement for `Checkpointed`

User code can use rescalable non-partitioned state by implementing the `PartitionableCheckpointed` interface. This interface is meant to replace the `Checkpointed` interface, which would become deprecated.

```
void storeOperatorState(long checkpointId, PartitionableStateBackend backend) throws Exception;

void restoreOperatorState(PartitionableStateBackend backend) throws Exception;
```

Through the store/restore methods, user code can interact with `PartitionableStateBackend` and register/restore states as previously explained.

Methods from this interface are invoked in `StreamTask::performCheckpoint(...)` and `StreamTask::restoreState()` respectively.

# 3) Interface `StateRepartitioner`

This interface allows implementations of repartitioning strategies the redistribute non-partitioned state when for changing parallelism. Currently, there is only one default strategy implemented in `RoundRobinStatePartitioner`, but in general it is possible to implement different strategies, e.g. a `StatePartitioner` that distributes the union of all previous states parallel subtasks to each parallel subtask. This interface is used in `CheckpointCoordinator::restoreLatestCheckpointedState()`.

# 4) Implementation for KafkaConsumer/Producer

The PR contains implementations of rescalable non-partitioned state for Kafka consumer and producers.

TODO: After review, a description of the new features must still be added to the Flink documentation.

### CODE REVIEW

**Comment by StefanRRichter** [comment]
Please review @tillrohrmann @StephanEwen

**Comment by StefanRRichter** [comment]
Hi,

I have some suggestions for renaming some of the interfaces and their methods in this pull request to come up with some clearer, more consistent naming schemes. I suggest the following changes:

## 1) Renaming the state handle that points to operator state: PartitionableStateHandle -> OperatorStateHandle

## 2) Rename: PartitionableStateBackend -> OperatorStateStore
```
	/**
	 * User-side interface for storing (partitionable) operator state.
	 */
	public interface OperatorStateStore {

		/**
		 * Creates (or restores) the partitionable state in this backend. Each state is registered under a unique name.
		 * The provided serializer is used to de/serialize the state in case of checkpointing (snapshot/restore).
		 */
		<S> ListState<S> getListState(String name, TypeSerializer<S> partitionStateSerializer) throws Exception;
	}
```

## 3) Rename: PartitionableSnapshotStateBackend -> OperatorStateBackend. I propose that the term backend now refers to some (i) store with the ability to (ii) snapshot.
```
	/**
	 * Interface that combines both, the user facing {@link OperatorStateStore} interface and the system interface
	 * {@link SnapshotProvider}
	 */
	public interface OperatorStateBackend
			extends OperatorStateStore, SnapshotProvider<PartitionableOperatorStateHandle> {
	}
```

## 4) Rename: PartitionableCheckpointed -> CheckpointedOperator
	- `storeOperatorState` -> `snapshotState`
	- `restoreOperatorState` -> `restoreState`

```
	public interface CheckpointedOperator {

		/**
		 * This method is called when state should be stored for a checkpoint. The state can be registered and written to
		 * the provided state store.
		 */
		void snapshotState(long checkpointId, OperatorStateStore stateStore) throws Exception;

		/**
		 * This method is called when state should be restored from a checkpoint. The state can be obtained from the
		 * provided state store.
		 */
		void restoreState(OperatorStateStore stateStore) throws Exception;
	}
```

## 5) Rename: StateRepartitioner -> OperatorStateRepartitioner
```
	/**
	 * Interface that allows to implement different strategies for repartitioning of operator state as parallelism changes.
	 */
	public interface OperatorStateRepartitioner {

		List<Collection<OperatorStateHandle>> repartitionOperatorState(
				List<OperatorStateHandle> previousParallelSubtaskStates,
				int parallelism);
	}
```

## 6) Add new interface that allows user-friendly checkpointing code for simple cases that to not require custorm serializer
```
	/**
	 * Simplified interface as adapter to the more complex CheckpointedOperator
	 */
	public interface ListCheckpointed<T extends Serializable> {

		List<T> snapshotState(long checkpointId) throws Exception;

		void restoreState(List<T> state) throws Exception;
	}
```

## 7) OperatorStateBackend lifecycle

Another point that we might want to discuss is the life cycle of `OperatorStateBackend`. Currently, a new backend is created (+restored) for each invocation of the methods in `CheckpointedOperator`. This always provides a clean backend to take the operator state for a snapshot. I wonder if it could make sense to create `OperatorStateBackend` just once for each `AbstractStreamOperator`, similar to the KeyedStateBackend. This would give users the option to actually keep operator state only in the `OperatorStateBackend`. However, we need a way to signal that all state must be passed to the backend before a snapshot. For example, large operator states could be managed in RocksDB this way, and we could provide more proxy collections (currently we only support a list of substates) over time.

What do you think @aljoscha @StephanEwen ?

**Comment by aljoscha** [comment]
I think most of the proposed renames are good. One thing that would be good to change is to remove `SnapshotProvider` and just have that method directly on `OperatorStateBackend`.

I really like the separation between the user facing state store and the backend. I've been meaning to change that for keyed state as well, i.e. the user only gets a way to access state and not all the methods for snapshotting, closing, etc. from the backend.

When I say I like the changes, I mean everything except that they have `Operator` in all of them. In the end, all state is at an operator, plus there is the existing interface `OperatorState` that is an alias for `ValueState`. I don't have a good alternative now, but I think the `Operator` could be confusing.

**Comment by StephanEwen** [comment]
+1, I like the changes.

Concerning (7) - I think creating the state backend once sounds good. It is more in line with the keyed state backend.

Concerning Aljoscha's comments: Removing SnapshotProvider makes sense, if it is only an internal interface and never exposed to the user.

Conderning the name `OperatorState` - I actually like the name. It is state that exists in the instance of an operator, assuming that functions are also (special cases of) operators.
I would add to this pull request that it removes the deprecated `OperatorState` interface (superclass of `ValueState`).

**Comment by rmetzger** [comment]
I think we should also update the documentation as part of this PR (there's a page dedicated to working with state)

**Comment by StephanEwen** [comment]
I would like to go for a follow-up PR. This is currently blocking some other work, so getting it in soon would help.

**Comment by StephanEwen** [comment]
Had an in-depth code walkthrough with @StefanRRichter - comments are addresses as additional commits.

Comments:
  - Use `StateDescriptor` as well for operator state
  - For the `snapshotState()` and `prepareSnapshot()` calls, the checkpoint timestamp should be passed as well.
  - The Kafka Consumer should use the same state as the `snapshotState()` interface, so as to allow for backwards compatible checkpoints/savepoints.

**Pull request closed without merging**
