### PR TITLE
 [FLINK-12902][hadoop] Remove flink-shaded-yarn-tests 

### PR DESCRIPTION
**Pull request by zentol**
Overall, this PR cleans up some dependency issues in `flink-yarn-tests`.

The dependency situation in this module was just insane; you have a few unshaded hadoop dependencies from `flink-yarn-tests`, some shaded hadoop dependencies from `flink-shaded-yarn-tests` and _yet another_ set of shaded hadoop dependencies from `flink-shaded-hadoop`. All of these were available on the test classpath, resulting in what is effectively an incomprehensible classpath.

This was highlighted in the shading patterns in `flink-shaded-yarn-tests`, which absolutely had to be in sync with `flink-shaded-hadoop` as otherwise you ended up with strange `VerifyErrors`.

This PR
a) removes `flink-shaded-yarn-tests` and moves a few of it's (now unshaded) dependencies to `flink-yarn-tests`
b) isolates `flink-yarn-tests`' test classpath from `flink-shaded-hadoop` via exclusions

As such, the test classpath now _only_ contains a few unshaded hadoop dependencies required for the test. `flink-shaded-hadoop` is only used for starting when submitting the applications to YARN, presumably to mirror what would be happening in production.

Additionally, this PR adds missing `test` scopes and removes an unused jackson dependency.

### CODE REVIEW

**Comment by zentol** [comment]
green build: https://travis-ci.org/zentol/flink/builds/545701715

**Comment by sunjincheng121** [comment]
The test fails caused by the PR #8786, And It fixed by #8807, So I think rebase the code can get the success CI test. :)

**Comment by StephanEwen** [comment]
How about rethinking the Hadoop/Yarn dependencies a bit?

If we want a hadoop-free Flink, then no module should bundle and `flink-shaded-hadoop` dependency in *compile* scope. These dependencies should always be *provided*, meaning used for compilation, but would have to be dropped in externally during runtime.

Changing that in the `flink-yarn` modules allows us to drop all the exclusion rules downstream, like in `flink-yarn-tests` or in `flink-dist`, which seems the right way.

**Comment by zentol** [comment]
@StephanEwen It is true that flink-yarn should have a `provided` dependency, but this looks like an orthogonal issue to me. We may need the excluion in flink-yarn-tests in any case though, given that provided dependencies are still available on the test classpath.

**Comment by StephanEwen** [comment]
We can treat it as an orthogonal fix.

Are transitive provided dependencies added to the test class path in Maven? I did not expect that. The mysteries of maven...

**Comment by zentol** [comment]
I double-checked how transitive provided dependencies are handled for tests, and they are indeed placed on the test classpath.

**Pull request merged**
