### PR TITLE
[FLINK-10701] Move modern kafka connector module into connector profile

### PR DESCRIPTION
**Pull request by yanghua**
## What is the purpose of the change

*This pull request moves modern kafka connector module into connector profile*

> Note : This PR is blocked by FLINK-10603.

## Brief change log

  - *Move modern kafka connector module into connector profile*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by zentol** [comment]
-1, this will cause a timeout on travis. Until we reduced the (total) duration of the kafka tests we cannot consolidate them in the connector profile.

**Comment by yanghua** [comment]
@zentol I know the current problem, I know it was blocked by FLINK-10603, I did not expect it to be merged immediately. It is reasonable to finally put the modern kafka connector on this profile.  See [here](https://github.com/apache/flink/pull/6703#issuecomment-433442098).

**Comment by zentol** [comment]
Then you should've said so in the PR; this could've easily been merged by another committer who isn't aware of the test duration issue.

**Comment by yanghua** [comment]
OK, I have updated the description of this PR and the JIRA issue.

**Comment by yanghua** [comment]
leaving...

**Pull request closed without merging**
