### PR TITLE
[FLINK-22982][python] Fix the wrong matching in PythonMapMergeRule

### PR DESCRIPTION
**Pull request by HuangXingBo**
## What is the purpose of the change

*This pull request makes will fix the wrong matching in PythonMapMergeRule*

## Brief change log

  - *Fix the wrong matching in PythonMapMergeRule*

## Verifying this change

  - *Original tests*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by maver1ck** [comment]
@HuangXingBo 
Don't we want any test for the case from Jira ?

**Comment by HuangXingBo** [comment]
Hi, @maver1ck, Thanks for the advice. The rule of `PythonMapMergeRule` is used to deals with the scenario of map operation, but some other calculations are incorrectly judged as map operation perviously. I think adding a special test to verify whether `PythonMapMergeRule` will misjudge is not particularly meaningful, but I am not particularly opposed to doing this.

**Comment by maver1ck** [comment]
I was thinking about more high-level test. Like running `SELECT python_udf(CASE WHEN x THEN y ELSE z END)`

**Comment by HuangXingBo** [comment]
> I was thinking about more high-level test. Like running `SELECT python_udf(CASE WHEN x THEN y ELSE z END)`

You may not understand what I mean. What kind of case is not important. You can think that the case you wrote in 1.12 is supported. But in 1.13, we introduced a new rule to support the case of `table.map`. The reason for this error has nothing to do with your judgment statement as a parameter. The reason for the error is because we called the wrong tool method when judging whether to use python udf. `PythonUtil.isNonPythonCall` and `!PythonUtil.isPythonCall` are not mutually exclusive conditions

**Review by dianfu — APPROVED** [review]

**Pull request closed without merging**
