### PR TITLE
[FLINK-3352] Use HDFS Config in RocksDB Copy Utilities

### PR DESCRIPTION
**Pull request by aljoscha**
This also moves the utilities (HDFSCopyFromLocal and HDFSCopyToLocal) to
the RocksDB package because we would need a HDFS dependency in
flink-core otherwise.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Does it make sense to write the config once in the `RocksDBStateBackend.initializeForJob()` rather than in every state?

**Comment by StephanEwen** [comment]
Otherwise, looks good

**Comment by aljoscha** [comment]
We could write it only once, but is it worth it? It would require piping another parameter through all the rocksdb related classes and I would assume there is only one or two states per operator in normal jobs.

**Comment by StephanEwen** [comment]
The two jobs have separate directories, so the would not interfere, correct?

**Comment by aljoscha** [comment]
Ahhh, rebased on latest master changes again (folding window state...). :sweat_smile:

**Pull request closed without merging**
