### PR TITLE
[FLINK-26077][runtime] Support operators send request to Coordinator and return a response

### PR DESCRIPTION
**Pull request by wuchong**
## What is the purpose of the change

Currently, the communitcation between Operator and Coordiator is sigle-way. That means, after Operator sending a message to Coordiator, it can't wait to get the response message. In some senarios, the Operator may need to retrieve some information stored in the Coordinator. Thus, it would be great if we can have a two-way communication.

## Brief change log

- Add `sendRequestToCoordinator(..)` interface to `TaskOperatorEventGateway` which accepts a request and returns a response future. The `TaskOperatorEventGateway` can be obtained by opereator used to communicate with coordinator.  
- Add `sendRequestToCoordinator` iterface to `JobMasterOperatorEventGateway` as the RPC method for Task to JM. JobMaster implement the interface to handover the request to correspond OperatorCoordinator. 
- Users' OperatorCoordinator should implement `CoordinationRequestHandler` interface (already exist) to handle the received requests. `CollectSinkOperatorCoordinator` already does it in this way.

## Verifying this change

- Added integration test in `CoordinatorEventsExactlyOnceITCase`
- Added unit test in `TaskExecutorOperatorEventHandlingTest`

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by wuchong** [comment]
@gaoyunhaii could you help to review this? when you are available. very appreciated it.

**Comment by gaoyunhaii** [comment]
@wuchong Thanks for the PR! I'll have a look~

**Review by gaoyunhaii — APPROVED** [review]
Thanks @wuchong for the PR! I only have two minor comments.

**Comment by wuchong** [comment]
Thanks @gaoyunhaii for the reviewing. I have addressed the comments and will merge it once the CI passed.

**Pull request merged**
