### PR TITLE
[hotfix] WIP: Remove redundant scala suffix

### PR DESCRIPTION
**Pull request by tisonkun**
## What is the purpose of the change

After flink-runtime becomes scala free. It seems several other modules can get rid of scala suffix. Trying to verify it.

## Brief change log

* Remove flink-scala dep from flink-streaming-java which seems not into use.
* Remove scala suffix for
  * flink-streaming-java
  * flink-client
  * flink-test-util
  * flink-kubernetes

## Verifying this change

If and only if codebase compiled and all existing tests passed.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by tisonkun** [comment]
@flinkbot run azure

**Comment by tisonkun** [comment]
@flinkbot run azure

**Comment by zentol** [comment]
I'm already looking into this topic as part of FLINK-23986. I will close the PR because I have already solved all these problems.

Overall you were on a good track. I'd argue that using reflection against Scala classes isn't really clean. It makes the code hard to write, maintain and extend. Instead there should be a form of FieldAccessFactory extension in the Scala API modules that is instead loaded via reflection.
Furthermore, we can also remove the Scala dependency from flink-cep.
Finally, the removal of suffixes cascades into _way more_ modules than shown here.

**Comment by tisonkun** [comment]
@zentol thanks! Let me try to catch up FLINK-23986.

**Pull request closed without merging**
