### PR TITLE
[FLINK-24160][tests] Use FS checkpoint storage in PartiallyFinishedSourcesITCase

### PR DESCRIPTION
**Pull request by rkhachatryan**

### CODE REVIEW

**Comment by gaoyunhaii** [comment]
Hi @rkhachatryan very thanks for opening the issue! The fix looks very good to me, and for one thing, perhaps we also change the default statebackend type for the other two tests `BoundedSourceITCase` and `StopWithSavepointITCase`? It seems the unaligned checkpoint is opened randomly according to the commits for all these three tests~

**Comment by rkhachatryan** [comment]
Thanks for pointing this out @gaoyunhaii , I've updated `BoundedSourceITCase` and `StopWithSavepointITCase` as well in  66e9789ef076dade78143678c0e7daee54dc57b6.

**Review by gaoyunhaii — APPROVED** [review]
Very thanks for the fix! LGTM and approved~

**Comment by gaoyunhaii** [comment]
Very thanks @rkhachatryan for opening the PR! I'll merge this one and https://github.com/apache/flink/pull/17185~

**Pull request closed without merging**
