### PR TITLE
[Discuss] Simplify SplittableIterator interface

### PR DESCRIPTION
**Pull request by rmetzger**
While working on something, I found the SplittableIterator interface unnecessary complicated.
Let me know if you agree to merge this simplification.

### CODE REVIEW

**Comment by tillrohrmann** [comment]
LGTM

I suspect that the travis fail is caused by faulty colocated subslot disposal. Should be fixed with #317

**Comment by StephanEwen** [comment]
I think in the current state, this makes sense.

I wrote the interface like it was, because it would enable implementations that does not compute/provide all splits on all machines. Think of a collection input format where we send a different subset of the collection to all each node (not supported in the runtime now, but might be at some point).

I guess we can realize something similar by splitting on the client and then sending the sub set iterators directly.

**Comment by fhueske** [comment]
+1
@rmetzger Can you create a JIRA for this?

**Comment by rmetzger** [comment]
Resolved in http://git-wip-us.apache.org/repos/asf/flink/commit/7ac6447f.

**Pull request closed without merging**
