### PR TITLE
[FLINK-6903] [runtime] Activate checkstyle for runtime/akka

### PR DESCRIPTION
**Pull request by greghogan**
Re-opening with corrected title.

@zentol I had this nearly done last week so am creating the pull request for when we are ready to review flink-runtime.

### CODE REVIEW

**Comment by zentol** [comment]
Can we add an exclusion for the logger? That should dramatically lower the changes needed; given the work on Flip-6 the existing JobManager/TaskManager will be removed eventually anyway.

**Comment by greghogan** [comment]
@zentol updated.

**Comment by greghogan** [comment]
@zentol is this worthwhile to review and commit?

**Comment by zentol** [comment]
+1 to merge.

**Pull request closed without merging**
