### PR TITLE
Backport of Kinesis connector changes from 1.5 to release-1.4

### PR DESCRIPTION
**Pull request by tweise**
Backport of Kinesis connector changes from 1.5 release to 1.4.

R: @tzulitai @tillrohrmann

### CODE REVIEW

**Comment by tzulitai** [comment]
I'm not sure that we want to backport the shard-mapping hash function. IMO, that is a new feature and shouldn't go into a bugfix release.

What do you think @tweise?

**Comment by tweise** [comment]
@tzulitai the commits in this PR (except the most recent version change) are from our 1.4.x fork and what we use in production. As discussed on the ML not even the Kinesis version number is strictly a patch compatible change and I don't see an issue including the other changes, too.

**Comment by tzulitai** [comment]
@tweise ok, I don't really have a strong opinion on not including the other changes.

Changes LGTM then, will merge this.

**Comment by tzulitai** [comment]
@tweise I've manually merged this, but forgot to add the "This closes #xxxx" message.
Could you close this PR manually? Thanks!

**Pull request merged**
