### PR TITLE
[FLINK-3174] Add MergingWindowAssigner and SessionWindows

### PR DESCRIPTION
**Pull request by aljoscha**
This introduces MergingWindowAssigner, an extension of WindowAssigner
that can merge windows. When using a MergingWindowAssigner the
WindowOperator eagerly merges windows when processing elements.

For keeping track of in-flight windows and for merging windows this adds
MergingWindowSet, this keeps track of windows per key.

Only when using a WindowAssigners is the more costly merging logic used
in the WindowOperator.

For triggers there is new method Trigger.onMerge() that notifies the
trigger of the new merged window. This allows the trigger to set a timer
for the newly merged window.

This also adds AbstractStateBackend.mergePartitionedStates for merging
state of several source namespaces into a target namespace. This is only
possible for the newly introduced MergingState which is an extension of
AppendingState. Only ReducingState and ListState are MergingState while
FoldingState is now an AppendingState.

This enables proper support for session windows.

This also adds the SessionWindows window assigner and adapts an existing
session example and adds test cases.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Very nice work. 

After an offline chat with @aljoscha , we concluded to slightly adjust the `Trigger` interface to make it simpler for people to develop triggers.

Other than that, this is good to merge...

**Comment by aljoscha** [comment]
I did the changes, I introduced `canMerge()` and added a default `onMerge()` that throws a `RuntimeExeption` in `Trigger`. This way we don't break the API for already existing user triggers.

If there are no objections I will also merge the removal of the non-keyed window operator that this PR is based on.

**Comment by StephanEwen** [comment]
Concerning the removal of the non-keyed window operator: Does that mean that the user functions now see the dummy key?

**Comment by aljoscha** [comment]
No, we introduced the `InternalWindowFunction` before 1.0.0 to decouple the user `WindowFunction` from the window operator implementation. There are now special `InternalWindowFunctions` that don't forward the key to the user function. The API for the user does not change, there an `AllWindowFunction` is used, as before. And that function does not get a key.

**Pull request closed without merging**
