### PR TITLE
[FLINK-6769] Replace usage of deprecated FileSystem#create(Path, boolean)

### PR DESCRIPTION
**Pull request by zentol**

### CODE REVIEW

**Comment by greghogan** [comment]
Is there another usage in `DistCp.java:132: outputStream = targetFs.create(outPath, true)`?

**Comment by zentol** [comment]
Yes, thanks for spotting it. It is now replaced as well.

**Comment by greghogan** [comment]
+1

**Comment by zentol** [comment]
merging.

**Pull request closed without merging**
