### PR TITLE
[FLINK-26578][BP-1.15][docs-zh] Translate new Project Configuration section to Chinese

### PR DESCRIPTION
**Pull request by liyubin117**
1.15 BP for parent PR https://github.com/apache/flink/pull/19100

### CODE REVIEW

**Comment by liyubin117** [comment]
@MartijnVisser I have cherried pick related commits to the new branch based on release-1.15 and no conflicts, given Nifi connector still exists in 1.15, I have retained the change in Nifi module doc :)

**Comment by liyubin117** [comment]
@flinkbot run azure

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Comment by MartijnVisser** [comment]
@liyubin117 Thanks again for the PR. LGTM

**Review by MartijnVisser — COMMENTED** [review]
LGTM

**Pull request merged**
