### PR TITLE
[FLINK-1870] Reintroduce indexed reader functionality to streaming

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Travis failed due to know instable test...

**Comment by StephanEwen** [comment]
Can you give us a bit of context why this is needed?

Also: The `RuntimeContext` object is what is exposed to user-defined functions. Exposing the number of the channel there breaks the abstraction layer.

**Comment by mjsax** [comment]
Needed for Storm compatibility. This information is made available in Storm to the user. Not sure why adding it to `RuntimeContext` breaks abstraction layer (it's only meta information)? Can you explain what you mean by that?

**Comment by StephanEwen** [comment]
The user code should not deal with what channel an element came from. It wires assumptions about the parallelism of the predecessor into the user code. Adjustments of the parallelism become impossible that way.

Why does the storm compatibility need this?

**Comment by mjsax** [comment]
If you implement a Bolt you can retrieve this information from Storm. Thus, the compatibility layer should provide this information, too.

**Comment by StephanEwen** [comment]
I am big time skeptic when it comes to putting this into the `RuntimeContext`.

If we really need to expose that beyond the `StreamInputProcessor`, it would probably be best to pass this into the operator, as part of the "processRecord()" method.

Since StormBolts are implemented as custom operators, they should be able to pick it up from there.

**Comment by mjsax** [comment]
I understand your skeptic, but I don't see it as dangerous as you. If somebody access this information and does not use it properly, it's his/her own fault... (same as using a static variable in an UDF -- we cannot "protect" users from writing bad code).

Nevertheless, originally I had the same idea as you suggest (ie, use `processRecord()`). However, the compatibility layer also used two `CoFlatMapFunction`s which need to access this information, too. 

 - https://github.com/apache/flink/blob/master/flink-contrib/flink-storm/src/main/java/org/apache/flink/storm/api/TwoFlinkStreamsMerger.java
 - https://github.com/apache/flink/blob/master/flink-contrib/flink-storm/src/main/java/org/apache/flink/storm/api/StormFlinkStreamMerger.java

It would be possible to rewrite both functions as custom operators, but this makes the translation code for multiple inputs streams more complex. Thus, I would prefer to expose this information in `RuntimeContext`. We can also extend the JavaDoc to warn the user to use this information carefully...

**Comment by StephanEwen** [comment]
Right, you cannot secure users from writing bad code, of course.

But a good way to guide then to writing good code is to expose only information they can actually use in the abstractions provided to them. Exposing certain information and declaring it as "don't use" is a bit like setting them up to make mistakes, and feels like such a strong sight that the abstractions are not picked correctly.

If this information is needed, I would really take the custom operator variant. We could also think if there is a good way of circumventing to depend on that channel index information in the first place.

**Comment by mjsax** [comment]
Ok. I will try to rework this to the custom operator approach...

About your last statement: We could decide to omit this information in the Storm compatibility layer (and drop this PR completely) -- of course, this would limits the "compatibility level" we can achieve.

Btw: Storm does not give the "channel index" itself to the user, but the task-id of the parallel producer task attached to each input tuple (in Storm, task-ids are unique over all tasks over all operators of the topology). The compatibility will translate the "channel index" into this task-id (using the "channel index" is the only way I see to get this done in the compatibility layer).

**Comment by aljoscha** [comment]
Hi,
I would be strongly against exposing the input channel index in any way to operators/user functions. How the index of a channel maps to an upstream operator is internal to the network layer and dependent on several things, some of which are not even deterministic IMHO. Off the top of my head it should depend on the number of upstream tasks, the parallelism of these upstream tasks and the order in which the system choses to attach the channels.

I think your goal can be achieved by adding a task-id field in the message wrapper and setting this when emitting elements. Setting this for every processed element (if using the Storm combat layer or not) seems quite wasteful to me.

**Comment by mjsax** [comment]
We do not have any message wrappers on the wire. Data is transfered as plain Flink `TupleX` types and are translated into Storm format before handing them over to the bolt. This allows for embedded usage of bolt! Thus, I do not want to change this.

**Comment by aljoscha** [comment]
What do you mean by embedded usage? Also, isn't there the `StormTuple` that is used as output of some operations. Then, even if plain Tuples are used, they could have an additional field with the TaskId. I still think it could be made to work without putting potentially misleading/dangerous stuff into the general API.

**Comment by aljoscha** [comment]
I think that the Storm compatibility layer is very important. I also think, however, that when making decisions about whether to enhance to core API to serve other APIs or making that other API jump through some hoops then the cleanliness of the core API should be favored if possible.

**Comment by mjsax** [comment]
With embedded mode, I mean to use a spout/bolt within a regular Flink streaming program. For this, you could even have a "plain/raw" input stream (eg, `DataStream<String>`) or a POJO. Both can be translated into StormTuple (which is only used for input tuples). Output tuples are of type `Values` and also translated back to `TupleX` type.

Extending the tuples with an additional field would work, too. But I did not like this, because is increases the data that need to be shipped over the network. For embedded mode, we would need to think of a nice "work around" for "plain/raw" and POJO input streams  -- but this should not be a problem. As there are no globally unique task-ids anyway in embedded mode, it might be even ok not to support this feature...

I personally do not see it as a big (very dangerous) problem in exposing "input channel index" to the operators. But if you are strictly against it, I will go with the "additional field" approach to provide this information.

**Comment by aljoscha** [comment]
@mjsax What is the status on this PR? Can it be closed since the feature in Storm will be implemented another way?

**Comment by mjsax** [comment]
I would like to keep this open, until [FLINK-2721](https://issues.apache.org/jira/browse/FLINK-2721) is merged. To make sure, we do not need this -- for this case, we can also close the according JIRA of course.

**Pull request closed without merging**
