### PR TITLE
[FLINK-6312]update curator version to 2.12.0 to avoid potential block

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
As there's a Major bug([CURATOR-344](https://issues.apache.org/jira/browse/CURATOR-344)) in curator release used by flink, we need to update the release to 2.12.0 to avoid potential block in flink.

 (flink use recipes in checkpoint coordinator and we have already occurred problem in zookeeper failover when we're trying to fix [FLINK-6174](https://issues.apache.org/jira/browse/FLINK-6174))

### CODE REVIEW

**Comment by StephanEwen** [comment]
Good idea to upgrade Curator.
Unfortunately, it seems some behavior in Curator has changed. The change causes many tests to hang/fail:

https://travis-ci.org/apache/flink/builds/222777791

I think this would need to be stabilized before we can merge the fix. Can you look into this?

**Comment by WangTaoTheTonic** [comment]
Sure. Seems like it will take a little long time but i'll try my best :)

**Comment by StephanEwen** [comment]
Thanks a lot, @WangTaoTheTonic !

**Comment by WangTaoTheTonic** [comment]
@StephanEwen All tests passed!

**Comment by StephanEwen** [comment]
Thanks for the fix. Merging this...

**Comment by StephanEwen** [comment]
Has been merged in aadfe45a880d0f71f23c7a742ff5264e8dc14bf8

@WangTaoTheTonic Since the PR was not auto-closed, can you close the PR manually?

**Pull request closed without merging**
