### PR TITLE
[FLINK-4943] ConfigConstants: YYARN -> YARN

### PR DESCRIPTION
**Pull request by Makman2**

### CODE REVIEW

**Comment by greghogan** [comment]
I'd recommend collecting typographical and grammatical errors within comments into a larger ticket and pull request.

**Comment by Makman2** [comment]
Though I wouldn't fix more than this one (except I stumble over some typos again) :3
Is there already a larger ticket? @greghogan

**Comment by greghogan** [comment]
I keep an `xxxx_minutiae` branch and push that every few months, typically after a release. There are fixed costs at each level of Flink's ticketing / pull request / verify / commit process.

**Comment by Makman2** [comment]
Feel free to cherry-pick my commit into your branch and close this PR :)

**Comment by fhueske** [comment]
Thanks for the fix @Makman2!
Merging

**Pull request closed without merging**
