### PR TITLE
[FLINK-10944] Increase slot request timout for MiniClusterResource

### PR DESCRIPTION
**Pull request by aljoscha**
Before, tests were sometimes timing out on Travis with missing slots.

@zentol This has two commits, only one of them should go in in the end. The Jira issue is specifically about `EventTimeWindowCheckpointingITCase` (https://issues.apache.org/jira/browse/FLINK-10944) but I think that's not relevant. The other tests can fail/timeout with the same problem. That's why I'm proposing to increase the timeout for all tests that use `MiniClusterResource`. What do you think?

### CODE REVIEW

**Comment by zentol** [comment]
I find it highly unlikely that the timeout is the issue, or that increasing it can have any effect.

The default timeout is 5 _minutes_. The failure literally means that the `MiniClusterResource` did not start within 5 minutes. Other tests running right before this test did not experience this problem in any way, so I'd exclude temporary performance issues on travis.

One interesting thing is that in both reported cases (linked in the JIRA) we allocated 3 slots instead of 6. For an extremely rare performance hiccup to result both times in exactly half the number of requested slows does not sound like a coincidence.

As such, -1.

**Comment by aljoscha** [comment]
Closing to investigate. I think it's a race in the scheduler, or a problem with slot sharing.

**Comment by aljoscha** [comment]
Btw, it's not surprising to always see 3 of 6. This has to do with the number of task managers (2) and the number of slots we have to schedule. I would expect this to either allocate 0, 3, or 6 slots. We mostly get 6, that's why the test only fails sometimes, we don't get 0, because that would indicate that we didn't get any slots, which can't happen in this race, I think.

**Comment by zentol** [comment]
Why would it allocate either 3 or 6? Hold on, why are we requesting 6 slows anyway? The cluster only has 4 available in total as we start 2 TM, with 2 slots each.

```
	private static final int PARALLELISM = 4;

	...

	protected final MiniClusterWithClientResource getMiniClusterResource() {
		return new MiniClusterWithClientResource(
			new MiniClusterResourceConfiguration.Builder()
				.setConfiguration(getConfigurationSafe())
				.setNumberTaskManagers(2)
				.setNumberSlotsPerTaskManager(PARALLELISM / 2)
				.build());
}
```

**Comment by aljoscha** [comment]
Both the source and the sink use slot sharing with one of the 4 window-operator slots. This is also the root of the problem: because of some race or quirk the slot sharing doesn't work as it is supposed to and then the physically available 4 slots are not enough.

When it says 3 in this log, it means "source and window op 1" in one slot, "window op 2" in another slot. And the two slots of the other TM can't be used for some reason. It's a bit confusing because this thing allocates 6 logical slots (tasks really) to 4 physical slots (actual slots).

I know ... 😅

**Pull request closed without merging**
