### PR TITLE
[FLINK-2811][web-dashboard]Add page with Configuration Overview.

### PR DESCRIPTION
**Pull request by sachingoel0101**
Here's a screenshot:
Configuration Page

### CODE REVIEW

**Comment by rmetzger** [comment]
Thank you for resolving the issue so quickly.
I think its good to merge.

**Comment by uce** [comment]
Thanks for this! Looks good. I would make the naming consistent though. You mix `jmConfig` and `config`. I am for `jobManagerConfig` to make it really clear what it is. I will try this out and merge if it works as expected.

**Comment by sachingoel0101** [comment]
On the user end, a url '/config' makes more sense IMO. On the server end, `config` is already mapped to something else, so I chose a `/jmconfig` there.
If you think `/jobManagerConfig` is better however, let me know. I will push a commit for that. 
On a related note, '/jobmanager/config' might be a better choice for url. Are there any job manager statistics which should be made available under a `/jobmanager` url? Running jobs and completed jobs are already there.

**Comment by StephanEwen** [comment]
How about mapping the jobmanager config to `/jobmanager/config` and later mapping the jobmanager log to `jobmanager/logfile`?

**Comment by StephanEwen** [comment]
And the `.out` file to `/jobmanager/stdout` or so...

**Comment by sachingoel0101** [comment]
That sounds good enough. I'll push a fix.

**Comment by sachingoel0101** [comment]
Updated as per @StephanEwen's comments. Here's another screenshot:
capture
The `/logfile` and `/stdout` urls are dummy and contain nothing right now.

**Comment by StephanEwen** [comment]
Two comments:

1) In the old web frontend, we showed the log and out files raw in a new tab. I think that was good, it allows to download/save the files without extra logic.

2) If it is not too much effort, could you sort the config keys (probably on the backend side)? Would make bigger configs easier to navigate...

**Comment by sachingoel0101** [comment]
1. I don't know if someone else is working on this, but this way we can provide a log and out file the way it is displayed, say on travis. Updated in real time. And of course, put a button to download them.
2. Sure. I will add a commit for that and we can decide on 1 after that.

**Comment by uce** [comment]
Regarding 1) Great idea Sachin. I never liked it in Travis, but I see how it can be useful for the JM logs. What about addressing Stephans comments for now and then adding the update + download thing later? This is rather time critical, because we want to add it to the release and there is consensus to remove the old interface.

**Comment by sachingoel0101** [comment]
@uce , Great. I think someone else was working on providing job manager log and out access. If not, I'll give it a shot in a few days.
@StephanEwen, is sorting with respect to size of keys okay? Also, there is no need to do this on the backend. Angular can do that pretty straightforward.
Attaching a screenshot again:
capture

Sorting is by key lengths, which isn't exactly ideal.

**Comment by uce** [comment]
I think alphabetically is better.

**Comment by sachingoel0101** [comment]
I was thinking more about the actual pixel length but achieving that is proving to be kind of hard.
Alphabetically should be okay I think.

**Comment by uce** [comment]
I see. But pixel length or number of characters does not make it easier to navigate when you want to look up a specific key, e.g. `jobmanager.X.Y`.

**Comment by sachingoel0101** [comment]
Yes. You're right. I'd misunderstood Stephan's comment. The goal is to group similar keys together, and sorting alphabetically will definitely take care of that.
On a separate note, does it make sense to have this type of structure:
*Job Manager*
jobmanager.*

*Akka*
akka.

*Recovery*
ha.*

and so on. Of course, if no keys are available under a group, it won't be displayed at all. Or we can just leave it at sorted alphabetically. Your call.

**Comment by sachingoel0101** [comment]
Here's what it looks like right now:
capture

Let me know if you have something else in mind.

**Comment by tillrohrmann** [comment]
Looks good with alphabetical order imo.

**Comment by uce** [comment]
Very good, Sachin. Thanks! I will try it out again and then merge it.

**Comment by sachingoel0101** [comment]
Okay. Cool. :)

**Comment by uce** [comment]
Sachin, do you also have time to fix the job manager logs? Would be good to have it in the release. Go for the simplest solution and don't try to make it too fancy for the first version. ;)

**Comment by sachingoel0101** [comment]
I can work on it but FLINK-2728 is already assigned to @iampeter.
@iampeter, have you started working on it?

**Comment by iampeter** [comment]
@sachingoel0101 unfortunately haven't had time yet, so I guess you can take on it

**Comment by sachingoel0101** [comment]
Okay. I already have the basic functionality up.

**Pull request closed without merging**
