### PR TITLE
[FLINK-11388][fs] Add Aliyun OSS recoverable writer

### PR DESCRIPTION
**Pull request by wujinhu**
## What is the purpose of the change

OSS offers persistence only after uploads or multi-part uploads complete.  In order to make streaming uses OSS as sink, we should implement a Recoverable writer. This writer will snapshot and store multi-part upload information and recover from those information when failure occurs

## Brief change log

- **move utility classes to flink-fs-common**
- **add abstract test classes for recoverable writers(s3/oss)**
- **add OSS recoverable writer**

## Verifying this change

This implementation adds some tests to test logic of recoverable writer. However, in order to run these tests, someone need to have his own Aliyun access key id and access key secret. Then, set environment variables below：
`export ARTIFACTS_OSS_ENDPOINT=<Aliyun OSS endpoint to connect to>`
`export ARTIFACTS_OSS_BUCKET=<Your bucket>`
`export ARTIFACTS_OSS_ACCESS_KEY=<Your access key id>`
`export ARTIFACTS_OSS_SECRET_KEY=<Your access secret>`

These tests are skipped by default.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**yes** / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (**yes** / no)
  - If yes, how is the feature documented? (not applicable / docs / **JavaDocs** / not documented)

### CODE REVIEW

**Comment by wujinhu** [comment]
@StefanRRichter Please help to review this PR, thanks!

**Comment by dawidwys** [comment]
@flinkbot approve description

**Comment by wujinhu** [comment]
@StefanRRichter would you please help review this PR? Thanks :)

**Comment by wujinhu** [comment]
Rebase master.

**Comment by zhouaoe** [comment]
”flink-oss-fs-hadoop-XXX.jar“ built from source code  can‘t   support streaming file sink.
 It 's a common error when Flink users use FileSink/StreamingFileSink to upload objets to OSS.we have received many complaints from customers.  
This feature would be very useful to Flink users。Specially to the people live in APAC，there are a lot of people often use OSS。
Could we reconsider open this PR again？
@wujinhu @flinkbot @dawidwys @rmetzger @hadronzoo

**Comment by wujinhu** [comment]
@kl0u Can we reopen this PR? Some users depend on this feature and I can keep working on it.

**Comment by JingsongLi** [comment]
@wujinhu I think we can, I can help review and merge.

**Pull request closed without merging**
