### PR TITLE
[FLINK-33588][Flink-Runtime] Fix NullArgumentException in DescriptiveStatisticsHistogramStatistics

### PR DESCRIPTION
**Pull request by zhutong6688**
## What is the purpose of the change

Fix NullArgumentException of getQuantile method in DescriptiveStatisticsHistogramStatistics

## Brief change log

This DescriptiveStatisticsHistogramStatistics class has added null initialization
1、DescriptiveStatisticsHistogramStatistics.java

## Verifying this change

3799e5aae7fa3cc0500aa1cd0b06856

During the verification process, the task was submitted to Yarn and run in Yarn cluster mode. After multiple stops and restarts, it was found that the NullArgumentException exception had disappeared. This fully verified the correctness of the modification, improved the stability of program operation, and also improved the accuracy of displaying statistical information in the web UI interface of the Flink task (as shown in the above figure).
The highlighted log section in the above figure is the log I printed to assist in troubleshooting, which can be ignored.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (no)

### CODE REVIEW

**Comment by qinping416** [comment]
This change improves the robustness of the system

**Comment by zhutong6688** [comment]
issue link is https://issues.apache.org/jira/browse/FLINK-33588

**Comment by zhutong6688** [comment]
yes, I like to fix it



---- Replied Message ----
| From | Jing ***@***.***> |
| Date | 12/08/2023 06:18 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [apache/flink] [FLINK-33588][Flink-Runtime] Fix NullArgumentException in DescriptiveStatisticsHistogramStatistics (PR #23749) |

@zhutong6688 would you like to fix the checkstyle issue?

**Comment by zhutong6688** [comment]
@flinkbot run azure

**Comment by JingGe** [comment]
Hi @zhutong6688, you should fix the issue with a new commit, just rerun azure CI won't help.

`09:44:06.641 [ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.27.1:check (spotless-check) on project flink-runtime: The following files had format violations:
09:44:06.641 [ERROR]     src/main/java/org/apache/flink/runtime/metrics/DescriptiveStatisticsHistogramStatistics.java
09:44:06.641 [ERROR]         @@ -175,7 +175,7 @@
09:44:06.641 [ERROR]          ············if·(data·!=·null)·{
09:44:06.641 [ERROR]          ················percentilesImpl.setData(data);
09:44:06.641 [ERROR]          ············}·else·{
09:44:06.641 [ERROR]         -················percentilesImpl.setData(new·double[]{0.0});
09:44:06.641 [ERROR]         +················percentilesImpl.setData(new·double[]·{0.0});
09:44:06.641 [ERROR]          ············}
09:44:06.641 [ERROR]          ········}
09:44:06.641 [ERROR]          ····}
09:44:06.641 [ERROR] Run 'mvn spotless:apply' to fix these violations.`

**Comment by zhutong6688** [comment]
@JingGe It's just a matter of format. It would be great if this command(mvn spotless:apply) could be executed

**Comment by JingGe** [comment]
@zhutong6688 you have to run `mvn spotless:apply` locally, it will change the file format and then you will need to commit and push the changes.

**Comment by zhutong6688** [comment]
@JingGe Okay, I'll resubmit it

**Comment by zhutong6688** [comment]
@JingGe new PR is here https://github.com/apache/flink/pull/23915

**Pull request closed without merging**
