### PR TITLE
[contrib] Storm compatibility

### PR DESCRIPTION
**Pull request by mbalassi**
This is an updated version of #573.

@mjsax addressed a number of comments since then and added Readmes, @szape did a code review and added an extra interface and I have moved the codebase to flink-contrib.

For the latter to be reasonable I felt necessary to break up flink-contrib to smaller submodules, despite @rmetzger advising against this approach. The names of the submodules are questionable, suggestions are welcome.

I've seen test failures in storm-compatibility-core, @mjsax could you take a look please? I managed to make some error in the pom for storm-compatibility examples, so that does not build currently, will check it after I got some sleep. :)

I would like to merge this to master as soon as the 0.9 branch is forked off and we can agree on it.

### CODE REVIEW

**Comment by mbalassi** [comment]
Oh, and one more info for @mjsax: I added you as collaborator to my repo, so you can directly push to this branch.

**Comment by szape** [comment]
This branch has a broken history. I will rewrite the commits. Please do not push anything until then.

**Comment by mbalassi** [comment]
What exactly is broken what the commits?

**Comment by szape** [comment]
The first 10 commits are not rebased on the current master.

**Comment by mbalassi** [comment]
You can just ad one commit at the end, please do not rewrite the complete history for this. That is unnecessary overhead. If you feel confident about it we can even put it in the 0.9 release.

**Comment by mjsax** [comment]
I thought this is a clean branch. I am working on this currently...

**Comment by szape** [comment]
Okay then, it will remain as it is.

**Comment by mbalassi** [comment]
Hey @mjsax, now the changes are on the master, can you make the changes on your side please?
Then it is ready to merge on my side.

**Comment by mjsax** [comment]
Hey, if the new API is stable I am happy to rebase and fix it up. I was just thinking, that it might be the easiest way to got back to commit 2d200c0 or  b06ec1b (both commits from Peter) and rebase from there... What do you think?

**Comment by mbalassi** [comment]
I am not religious about my commits at all, those can be done any time, but would be nice if I did not have to redo them. Peter did more work, I was strongly hoping that adapting to the new source interface can be done on top of these changes.

If you are for removing them, that can of course this is your pull request after all. Thanks for pointing out that I have not attributed those commits to Peter yet, will do so soon and will give you a heads up for breaking the history on this branch.

**Comment by mjsax** [comment]
It should be possible to put your last commit on top, after the rebase is done. I will do it in a new branch to preserve this one and "cherry pick" your last commit at the end.

**Comment by mbalassi** [comment]
Thanks, let us do that then.

**Comment by rmetzger** [comment]
Congrats @mjsax for getting your first big contribution in!
I talked to a few users here in the valley which were showing interest in this feature.

**Comment by mjsax** [comment]
Thanks. :) Cool that people are interested. Missing features are in the pipeline already. Stay tuned ;)

**Comment by rmetzger** [comment]
Cool.
Maybe we should write also a blog post about it

**Comment by mjsax** [comment]
Sure. Why not. Let's discuss tomorrow at the Meetup.

**Pull request merged**
