### PR TITLE
[FLINK-30677][Test] Fix unstable SqlGatewayServiceStatementITCase.testFlinkSqlStatements

### PR DESCRIPTION
**Pull request by link3280**
## What is the purpose of the change

SqlGatewayServiceStatementITCase.testFlinkSqlStatements may fail due to `java.util.NoSuchElementException`. The cause is unsecured access to iterators in the test (not `hasNext()` before `next()`):

https://github.com/apache/flink/blob/4e3cd986cd4304c699d5c7d368ffd6e0ead5a096/flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/AbstractSqlGatewayStatementITCase.java#L286-L297

## Brief change log

- Call `iterato#next()`  only if `iterato#hasNext()`.
- Fix NPE in stringifying Exceptions.
- Use dumpy results for non-query operations.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by link3280** [comment]
cc @XComp @fsk119 @yuzelin

**Comment by link3280** [comment]
CI failed due to 503 from AWS. Re-run CI.

https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=44944&view=logs&j=4eda0b4a-bd0d-521a-0916-8285b9be9bb5&t=2ff6d5fa-53a6-53ac-bff7-fa524ea361a9&l=16864

**Comment by fsk119** [comment]
Sorry for introducing unstable test. I think the main root cause is because of the [FLINK-29950](https://issues.apache.org/jira/browse/FLINK-29950). Before [FLINK-29950](https://issues.apache.org/jira/browse/FLINK-29950), we always use a DUMMY_RESULT_STORE for the non-query results. With the DUMMY_RESULT_STORE, the ResultFetcher will actively put all data into the current buffer. But in the [FLINK-29950](https://issues.apache.org/jira/browse/FLINK-29950), we uses a non-dummy result store that will start a thread periodically to fetch results. In this case, the rest client may get an empty results.  

So I think we should keep the origin behaviour to use the dummy result store. WDYT [Paul Lin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Paul+Lin)

**Comment by link3280** [comment]
I'm OK with it. I'll close the PR.

**Comment by link3280** [comment]
@flinkbot run azure

**Comment by fsk119** [comment]
@flinkbot run azure

**Review by fsk119 — APPROVED** [review]
LGTM. Merge it when CI turn green.

**Comment by link3280** [comment]
Thanks a lot @fsk119

**Pull request closed without merging**
