### PR TITLE
[FLINK-27017][hive] Fix divide by zero exception in Hive dialect

### PR DESCRIPTION
**Pull request by luoyuxia**
## What is the purpose of the change
To fix the divide by zero exception in Hive dialect

## Brief change log
when the operand is `/`, make it call Hive's `GenericUDFOPDivide` for better consistent to Hive in case of dividing by zero.

## Verifying this change
Add sql `select 1 / 0` for dividing by zero.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency):  no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`:  no
  - The serializers:  no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature?  no
  - If yes, how is the feature documented? no

### CODE REVIEW

**Comment by luoyuxia** [comment]
@flinkbot run azure

**Comment by luoyuxia** [comment]
@flinkbot run azure

**Comment by luoyuxia** [comment]
@flinkbot run azure

**Review by wuchong — APPROVED** [review]
LGTM.

**Pull request merged**
