### PR TITLE
[FLINK-1756] [streaming] Rename Stream Monitoring to Stream Checkpointing

### PR DESCRIPTION
**Pull request by mbalassi**
Also set the default checkpoint interval to 1 sec instead of 10.

@senorcarbone, @gyfora please let me know if I have forgotten something when renaming.

### CODE REVIEW

**Comment by gyfora** [comment]
1 sec seems to be little to frequent until we make this very efficient. I would put it around 3-5 sec.

**Comment by gyfora** [comment]
Other than this, it looks good.

**Comment by senorcarbone** [comment]
:+1: nice

Another thing, while you are at it. What about changing the compaction timeout. It is currently set to 2 x interval which might be an overkill for big intervals. Perhaps it should be a constant one instead or triggered on demand upon getting acknowledgements

**Comment by mbalassi** [comment]
@gyfora: Changed default checkpoint interval to 5 secs. 

@senorcarbone: Thanks for the reminder on that. I do not have a really nice idea for the compaction interval right now. It does not make much sense to have a constant as there might not be anything to compact if we have too rare checkpoints. 
The on-demand one can be nice eventually, but I think the current should be good enough for now - we are not expected to store large state anyway.

**Comment by rmetzger** [comment]
Change looks good.
I miss some javadocs on the user facing methods ;)

**Comment by derSascha** [comment]
Looks like the JobGraph missed the renaming.

**Pull request closed without merging**
