### PR TITLE
[FLINK-4579] [StateBackend] Add StateBackendFactory for RocksDB Backend

### PR DESCRIPTION
**Pull request by wuchong**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

This PR also add the rocksdb backend to the standard distribution lib to avoid manually place rocksdb jars to the Flink lib folder.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Looks good. I think we could even go one step further and have a shortcut (`rocksdb`) similar to `filesystem` and `jobmanager`.

We should then also have dedicated options, like `state.backend.rocksdb.checkpointdir`.

**Comment by wuchong** [comment]
Hi @StephanEwen ,  if we want to have a shortcut (`rocksdb`),  what should we do?  Add the rocksdb dependency into `flink-streaming-java` module ?  Or use java reflect ?

**Comment by StephanEwen** [comment]
Good point. I think reflect is good, if it does not add too much work. Keeping the modules separate is nice, I think.

**Comment by wuchong** [comment]
Added a shortcut (rocksdb) for configuring RocksDB state backend and added the dedicated option config `state.backend.rocksdb.checkpointdir`.

**Comment by StephanEwen** [comment]
Looks good, thanks!
Rebasing and merging this...

**Pull request closed without merging**
