### PR TITLE
[FLINK-24964] Upgrade frontend-maven-plugin

### PR DESCRIPTION
**Pull request by maver1ck**
## What is the purpose of the change

Upgrade frontend-maven-plugin to fix compilation issue on Apple M1

## Brief change log

- change plugin version in pom.xml

## Verifying this change

Verified by compilation.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): yes 
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive):  no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by zentol** [comment]
We cannot do this upgrade because this version requires Maven 3.6.0, while we are still using 3.2.5.

**Comment by maver1ck** [comment]
@zentol I will try to check if there is a plugin version fixing M1 bug and working on maven 3.2.5

**Comment by maver1ck** [comment]
@flinkbot run azure

**Comment by maver1ck** [comment]
@zentol How can I rerun pipeline ?

**Comment by maver1ck** [comment]
@zentol I think I found proper version :)

**Comment by rmetzger** [comment]
While testing your change, the build failed with:

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:35 min
[INFO] Finished at: 2021-11-16T20:42:42+01:00
[INFO] Final Memory: 581M/6384M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.1:test-compile (default) on project flink-parquet_2.12: Missing:
[ERROR] ----------
[ERROR] 1) com.google.protobuf:protoc:exe:osx-aarch_64:3.5.1
[ERROR]
[ERROR] Try downloading the file manually from the project website.
[ERROR]
[ERROR] Then, install it using the command:
[ERROR] mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.5.1 -Dclassifier=osx-aarch_64 -Dpackaging=exe -Dfile=/path/to/file
[ERROR]
[ERROR] Alternatively, if you host your own repository you can deploy the file there:
[ERROR] mvn deploy:deploy-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.5.1 -Dclassifier=osx-aarch_64 -Dpackaging=exe -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR]
[ERROR] Path to dependency:
[ERROR] 1) org.apache.flink:flink-parquet_2.12:jar:1.15-SNAPSHOT
[ERROR] 2) com.google.protobuf:protoc:exe:osx-aarch_64:3.5.1
[ERROR]
[ERROR] ----------
[ERROR] 1 required artifact is missing.
[ERROR]
[ERROR] for artifact:
[ERROR] org.apache.flink:flink-parquet_2.12:jar:1.15-SNAPSHOT
```

Ideally we shouldn't require people to perform manual steps to get a clean build. Did it work out of the box for you?

**Comment by maver1ck** [comment]
No. I also stopped on this step. But I think we should fix M1 problems one by one :)

**Comment by rmetzger** [comment]
Thanks for confirming that you are also seeing this issue.

Sadly, the `frontend-maven-plugin` loads the x86 version of node into `flink-runtime-web/web-dashboard/node`, requiring rosetta to run parts of the Flink build.
I assume this is fine for now, given how well rosetta works, but its not a permanent solution (Rosetta was around for ~5 years during the transition from PowerPC to Intel in 2006)

**Comment by maver1ck** [comment]
I think this is good workaround for now.
Upgrading node.js to version with aarch support for sure will be more demanding.

**Comment by maver1ck** [comment]
@rmetzger 
I think the best solution for protoc will be adding this file to maven central. Do we have any friends in protobuf project ?
https://developers.google.com/protocol-buffers/

**Comment by MartijnVisser** [comment]
@rmetzger Do you think we should merge this and create a follow up ticket?

**Comment by rmetzger** [comment]
Sorry for the delay. I'm currently on parental leave and have very little time in front of my screens ;) 

> Do we have any friends in protobuf project ?

Not that I'm aware of :)

Yes, let's merge this and do a separate ticket for the remaining issue(s).

**Comment by rmetzger** [comment]
I'll merge it myself asap (maybe tonight or tomorrow), but I'd also be happy if another Flink committer would merge it in the meantime.

**Comment by MartijnVisser** [comment]
@AHeise Please merge :)

**Comment by rmetzger** [comment]
Thanks @zentol !

**Pull request merged**
