### PR TITLE
[FLINK-27278][docs] Fix wrong indentation in windows docs

### PR DESCRIPTION
**Pull request by liuml07**
## What is the purpose of the change

Fix wrong indentation in doc dev/datastream/operators/windows.md
https://nightlies.apache.org/flink/flink-docs-master/docs/dev/datastream/operators/windows/#processwindowfunction

## Brief change log

Due to special char the current indentation of ProcessWindowFunction in doc dev/datastream/operators/windows.md is wrong. It's not very visible in the source code. However, if you visit the formatted doc ([e.g.](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/datastream/operators/windows/#processwindowfunction)), you will see the wrong indentation. It can be fixed by using spaces in the example code.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no) **no**
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no) **no**
  - The serializers: (yes / no / don't know) **no**
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know) **no**
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know) **no**
  - The S3 file system connector: (yes / no / don't know) **no**

## Documentation

  - Does this pull request introduce a new feature? (yes / no) **no**
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by liuml07** [comment]
#### Before
before

#### After
after

**Review by Myasuka — CHANGES_REQUESTED** [review]
Thanks for creating this PR, I think the chinese doc also has such problem.
Please also fix this problem in docs/content.zh/docs/dev/datastream/operators/windows.md

BTW, you can also change the commit message to `[FLINK-27278][docs] Fix wrong indentation in windows docs`

**Review by cody195 — APPROVED** [review]
👍

**Comment by Myasuka** [comment]
@flinkbot run azure

**Review by Myasuka — APPROVED** [review]
LGTM.

**Pull request merged**
