### PR TITLE
[FLINK-1615] [java api] SimpleTweetInputFormat

### PR DESCRIPTION
**Pull request by Elbehery**
A replacement for PR #442

### CODE REVIEW

**Comment by aljoscha** [comment]
The build still fails because of missing license headers in the model package.

By the way, did you write the files in the model package yourself or were they generated?

**Comment by Elbehery** [comment]
@aljoscha  Yes I wrote these Pojos myself, and I have tested the handler to retrieve distinct data, coz the tweets has redundant fields. 

I have added the License

**Comment by Elbehery** [comment]
@aljoscha  I have checked the Travic log. The problem is in Flink Streaming, so why my branch failed ?!!

**Comment by aljoscha** [comment]
The tests are failing because you use spaces in you code for indentation. Could you please change all indentation to tabs to satisfy the style checker?

**Comment by Elbehery** [comment]
@aljoscha  I have run code format from Intellij, I think the problem should be solved now .. 

I have tried to read the travis build log, but I could not find the cause of the problem, would you please tell me how to find it, for saving time in the future ?

**Comment by aljoscha** [comment]
Unfortunately, Travis cuts of the log if it is too long, like here: https://travis-ci.org/aljoscha/flink/jobs/60177866 (that's from your pull request). You have to click on the "Download log" button, then you can view the whole log, there you see the check style errors.

You can also see the errors if you run a "mvn clean verify" on your local machine.

It seems your code still contains tabs. (From the recently failed travis builds)

**Comment by Elbehery** [comment]
@aljoscha  GOT IT .. Now the build success locally.

**Comment by Elbehery** [comment]
@aljoscha  I have passed the local verification .. The travis build here has passed https://travis-ci.org/apache/flink/jobs/60428756 .. But I do not know why the others are not..

**Comment by aljoscha** [comment]
Our travis builds are a bit unstable right now. I'm running some last tests and then I'll merge this. Thanks for staying with this and working on my requests! :smile:

**Comment by Elbehery** [comment]
:thumbsup:

**Pull request closed without merging**
