### PR TITLE
[FLINK-2874] Fix Avro getter/setter recognition

### PR DESCRIPTION
**Pull request by ukarlsson**

### CODE REVIEW

**Comment by fhueske** [comment]
Hi @ukarlsson, thanks for the pull request. 
Can you please open a [JIRA issue](https://issues.apache.org/jira/browse/FLINK) for this bug and add a bit of context information? That will make it much easier to track this problem and its solution.

Thank you very much, Fabian

**Comment by rmetzger** [comment]
Could you also add a test case that validates the fix?

I'm sorry that we are requesting these things, but managing such a big project requires some structure and quality checks. We still highly appreciate your pull request :)

**Comment by ukarlsson** [comment]
Hello, thanks for your feedback, yes I will add these things.

**Comment by fhueske** [comment]
@ukarlsson Cool, thanks a lot!

**Comment by ukarlsson** [comment]
@fhueske @rmetzger 

Hello,

I have added the Jira issue:

https://issues.apache.org/jira/browse/FLINK-2874

I have also added unit tests.

**Comment by aljoscha** [comment]
I think it's a good fix. It applies to all POJOs, not just Avro-generated classes, but that should be ok.

**Comment by fhueske** [comment]
Looks good to me as well. Should we add this fix to 0.10 RC1 as well?

**Comment by fhueske** [comment]
Will merge this PR.

**Pull request closed without merging**
