### PR TITLE
[FLINK-28679][hive] Use fixed version for hive-service-rpc

### PR DESCRIPTION
**Pull request by fsk119**
## What is the purpose of the change

*Use fixed hive server2 version. Because the different version of hiveserver2 has different interfaces. Currently, the hive connector uses reflection to get the classes in the hive jar with different versions. However, it doesn't work for the hiveserver2 endpoint because the hiveserver2 endpoint needs to implement the interface in the dynamic hive jars. To solve this, we may need to introduce a Proxy to delegate the different requests to a hive-free server.

## Verifying this change

I have run `mvn clean install -T 4 -DskipTests -Pskip-webui-build -Phadoop3-tests,hive3` in my local environment. The problem in the issue doesn't appear. 

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**yes** / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by zentol** [comment]
Please link a build with the hadoop3 profile active to verify that this works.

**Comment by fsk119** [comment]
Thanks for pointing it out. But I find I can not run the nightlies script in my azure pipeline.  It reports 

```
Variables:
  SECRET_S3_BUCKET:
    Parsing expression: <variables.IT_CASE_S3_BUCKET>
    Evaluating: variables['IT_CASE_S3_BUCKET']
    Expanded: Null
    Result: ''
  SECRET_S3_ACCESS_KEY:
    Parsing expression: <variables.IT_CASE_S3_ACCESS_KEY>
    Evaluating: variables['IT_CASE_S3_ACCESS_KEY']
    Expanded: Null
    Result: ''
  SECRET_S3_SECRET_KEY:
    Parsing expression: <variables.IT_CASE_S3_SECRET_KEY>
    Evaluating: variables['IT_CASE_S3_SECRET_KEY']
    Expanded: Null
    Result: ''
  SECRET_GLUE_SCHEMA_ACCESS_KEY:
    Parsing expression: <variables.IT_CASE_GLUE_SCHEMA_ACCESS_KEY>
    Evaluating: variables['IT_CASE_GLUE_SCHEMA_ACCESS_KEY']
    Expanded: Null
    Result: ''
  SECRET_GLUE_SCHEMA_SECRET_KEY:
    Parsing expression: <variables.IT_CASE_GLUE_SCHEMA_SECRET_KEY>
    Evaluating: variables['IT_CASE_GLUE_SCHEMA_SECRET_KEY']
    Expanded: Null
    Result: ''
```

Could you give me some hints on how to run the test with the hadoop3 profile in azure? 

[1] https://dev.azure.com/1059623455/Flink/_build/results?buildId=313&view=logs&j=b1fcf054-9138-5463-c73c-a49979b9ac2a

**Comment by zentol** [comment]
When running personal CI, change https://github.com/apache/flink/blob/master/azure-pipelines.yml#L80 to https://github.com/apache/flink/blob/master/tools/azure-pipelines/build-apache-repo.yml#L127.

For PRs, change https://github.com/apache/flink/blob/master/tools/azure-pipelines/build-apache-repo.yml#L73 to https://github.com/apache/flink/blob/master/tools/azure-pipelines/build-apache-repo.yml#L127.

**Comment by fsk119** [comment]
@zentol The CI test passes with the hive3 profile. Could you spend some time reviewing the PR? Thanks a lot.

**Comment by fsk119** [comment]
The misc module passes both in the [hive3](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=38809&view=results) and [hive2](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=38838&view=results) profiles.

**Review by wuchong — APPROVED** [review]
LGTM.

**Pull request merged**
