### PR TITLE
[FLINK-6105] Use InterruptedIOException instead of IOException

### PR DESCRIPTION
**Pull request by rice904**
This is my first commit of this. It might be have other places also do this change, but I am not sure now.

### CODE REVIEW

**Comment by StephanEwen** [comment]
We could make this change. I have not seen a lot of use of `InterruptedIOException`, probably because it is a bit of a strange class, with its public mutable int field.

I am +/- 0 on this. Do you have a concrete case where this change would lead to a benefit?

**Comment by zhangminglei** [comment]
Maybe @tedyu could share some light on it.

**Comment by greghogan** [comment]
@zhangminglei, not sure if you saw @tedyu's comment on the Jira. There are more instances of this in the same file and package. If these are internal classes and Flink is not using `InterruptedIOException` then would the only effect be in logging a different exception?

**Comment by zhangminglei** [comment]
@greghogan I saw Ted comment on the jira before. But I am not sure whether we will adopt Ted's comments. So, that is why I leave this PR until someone adopt it, I will keep working on this then. As refers to what you said logging a different exception, hmm, probably. I would think it will give us more clear exception. @tedyu What do you think of this ?

**Comment by tedyu** [comment]
I think InterruptedException should be handled uniformly in HadoopInputFormatBase.java

**Comment by aljoscha** [comment]
I'm closing this for now because there doesn't seem to be consensus. `InterruptedIOException` also doesn't allow wrapping the original `InterruptedException`.

**Pull request closed without merging**
