### PR TITLE
[FLINK-4873] Configurable ship path for YARN cluster resources

### PR DESCRIPTION
**Pull request by gyfora**
This PR makes the resource shipping directory configurable for YARN clusters by adding a new config option:  `yarn.resource.ship.path`

Currently the HDFS home directory is used by default which makes it practically impossible to use the YARN cluster without HDFS (which is actually quite feasible if you have a different distributed file system).

### CODE REVIEW

**Comment by gyfora** [comment]
We can also easily backport this to 1.1.*  
We are actually using this change in production there.

**Comment by tzulitai** [comment]
This definitely seems like something that needs to be configurable.
@gyfora would you like to rebase this? I'll look into merging it.

**Comment by gyfora** [comment]
I am travelling right now, will try to look into this over the weekend. This is in no way a blocker for the release I think. :)

**Comment by tzulitai** [comment]
Yes, not a hurry. I'm just scanning through the Yarn-related PRs and noticed this :)

**Pull request closed without merging**
