### PR TITLE
[FLINK-7287][tests] fix test instabilities in KafkaConsumerTestBase

### PR DESCRIPTION
**Pull request by NicoK**
## What is the purpose of the change

fix test instabilities in KafkaConsumerTestBase

## Brief change log

* Properly ignore the `JobCancellationException` (several tests should have always failed but did not due to not waiting for the job execution thread to finish).
* Always wait for the job execution thread to finish before checking the result of and returning from the test (although this is not strictly necessary for the tests, it may uncover any hidden failures between the cancel command and the actual cancellation but it also allows following tests to work with a clean cluster and no interfering jobs).

## Verifying this change

This change is already covered by existing tests extending `KafkaConsumerTestBase`, such as `Kafka010ITCase`.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by tzulitai** [comment]
Thanks for the fix and your notice on the instabilities @NicoK!

Could you check if my understanding of the issue is correct?:
- `Kafka010ITCase.testCommitOffsetsToKafka` was failing on `JobCancellationException`, whereas that exception signals success and should be ignored.
- We were "incorrectly passing" before only because we didn't properly wait for the job to be cancelled.

**Comment by NicoK** [comment]
Yes, both your observations are correct. The pattern in most tests inside `KafkaConsumerTestBase` is to 
1) start a job,
2) do some processing, e.g. until some offset or another finish condition, including some checks
3) cancel the job
4) check for exceptions

Since cancelling the job issues a `JobCancellationException`, this must be ignored.

**Comment by tzulitai** [comment]
Thanks for clarifying!
+1 to merge this to `master` and `release-1.3`.

**Comment by tzulitai** [comment]
Merging ..

**Pull request closed without merging**
