### PR TITLE
[FLINK-7917] The return of taskInformationOrBlobKey should be placed inside synchronized in ExecutionJobVertex

### PR DESCRIPTION
**Pull request by yanghua**
## What is the purpose of the change

*This pull request placed the  taskInformationOrBlobKey inside synchronized in ExecutionJobVertex*

## Brief change log

  - *Placed the  taskInformationOrBlobKey inside synchronized in ExecutionJobVertex*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by yanghua** [comment]
cc @tillrohrmann

**Comment by yanghua** [comment]
cc @zentol

**Comment by yanghua** [comment]
cc @zentol @GJL @tzulitai this PR takes a long time, please review thanks~

**Comment by yanghua** [comment]
cc @kl0u

**Comment by yanghua** [comment]
cc @StefanRRichter

**Comment by yanghua** [comment]
cc @tzulitai

**Comment by dawidwys** [comment]
+1, merging

**Comment by tillrohrmann** [comment]
Thanks for the fix @yanghua and the review @dawidwys.

**Pull request closed without merging**
