### PR TITLE
[FLINK-4668] Fix positive random int generation

### PR DESCRIPTION
**Pull request by apivovarov**
https://issues.apache.org/jira/browse/FLINK-4668

### CODE REVIEW

**Comment by StephanEwen** [comment]
I think this is not necessary. `Random.nextInt(int)` returns only positive values.

**Comment by greghogan** [comment]
I don't think this fixes a bug since I'm not aware of filesystems unable to handle a leading dash.

**Comment by apivovarov** [comment]
it's not even convenient to work with files started with `-`, e.g.
```$ vi -44.txt
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug  1 2016 19:37:21)
Unknown option argument: "-44.txt"
More info with: "vim -h"```

```$ rm -rf "-4.txt"
rm: illegal option -- 4
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file```

**Comment by greghogan** [comment]
These are temporary files automatically deleted by the client. To handle paths with leading dashes one can prefix with a directory (`vi ./-44.txt`) or place after a double dash (`vi -- -44.txt`).

This looks to me like a safe change (I'd first question why we're prefixing with a random string when Java is doing the same in `File.createTempFile`). On the other hand, this isn't fixing an error and there are limitless ways to refactor the existing codebase. And fortunately the anti-pattern is well-known.

**Comment by StephanEwen** [comment]
Yes, looks good to me, too.
(I retract my earlier statement, I was apparently a bit tired and mixed up original version and edit).

**Comment by greghogan** [comment]
I'll merge this ...

**Pull request closed without merging**
