### PR TITLE
[FLINK-2459][cli]Cli API and doc fixes.

### PR DESCRIPTION
**Pull request by sachingoel0101**
1. Remove CliFrontendLoggingTest. Test directly that the logging flag is interpreted correctly.
2. [hotfix] Doc fix for cli api
3. [hotfix] Info command shouldn't print logging option for help.

### CODE REVIEW

**Comment by sachingoel0101** [comment]
@mxm, you should verify if should we do away with the logging test since you reviewed it.
If not, the problem is easily fixed by setting a free port instead of always using the default port.

**Comment by StephanEwen** [comment]
This looks good, thanks you!

One followup issue: The flag to suppress the logging is `-q` or `--sysoutLogging`. The long version seems inconsistent with "q". It should probably be called `--quiet`.

**Comment by StephanEwen** [comment]
Merging this...

**Comment by sachingoel0101** [comment]
Pushed a fix for changing the name to `quiet`

**Comment by StephanEwen** [comment]
The push to rename it to "quiet" came after the merge, so it did not get in...

**Comment by StephanEwen** [comment]
Can you make a separate patch for this?

**Comment by sachingoel0101** [comment]
@StephanEwen, I've force pushed this branch to only contain the name change. You can merge this again.

**Pull request closed without merging**
