### PR TITLE
[hotfix][dist] Fix that flink-gs-fs-hadoop not included in flink-dist

### PR DESCRIPTION
**Pull request by xintongsong**
See [this discussion](https://github.com/apache/flink/pull/15599#issuecomment-1017039938) for the details.

### CODE REVIEW

**Comment by xintongsong** [comment]
Adding `flink-gs-fs-hadoop` as a provided-scope dependency of `flink-dist`, I'm again running into the grpc version issue.
https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=29771&view=logs&j=bea52777-eaf8-5663-8482-18fbc3630e81&t=d6e79740-7cf7-5407-2e69-ca34c9be0efb&l=29490

Note that the errors came from the javadoc check (`mvn javadoc:aggregate`), which is after successfully building the project. It seems to me `dependencyManagement` in `flink-gs-fs-hadoop` is not taking effect in running `mvn javadoc:aggregate` for the whole project. I don't know the reason.

Moving the grpc dependency management to `flink-parent` fixes the problem. However, that means the grpc version applies to the entire project, instead of only the `flink-gs-fs-hadoop` module. Although the CI does not show any problem, I'm not entirely sure about this.

WDYT? cc @galenwarren @zentol

**Comment by galenwarren** [comment]
Yeah, I don't know what the ramifications would be of forcing the grpc version for the entire project, either. That does seem potentially risky.

Instead of moving the dependency management to `flink-parent`, could we duplicate the same dependency-management entries in `flink-dist`? That might be a more focused solution, if it works.

But I agree, the behavior here is a bit puzzling, I'm not sure why these errors crop up in certain cases/environments but not others.

**Comment by xintongsong** [comment]
@galenwarren,

> Instead of moving the dependency management to flink-parent, could we duplicate the same dependency-management entries in flink-dist? That might be a more focused solution, if it works.

It works in terms of fixing the problem. However, I'm not sure this is the correct thing to do. `flink-dist` simply assembles the artifacts. It should not decide the version of dependencies. This issue is more like a problem of maven `javadoc:aggregate` plugin to me, rather than a real dependency problem.

And I've updated the serializer version. Please check it out.

**Comment by galenwarren** [comment]
@xintongsong 

Thanks for making the serializer version change. I'm only seeing it in `GSCommitRecoverableSerializer`, were you also planning to change it in `GSResumeRecoverableSerializer`? 

If you wanted, I think you could also change this line in each of the serializers' `deserialize` methods:

```
Preconditions.checkArgument(version >= 0);
```

... to restrict the version to `version >= 1` instead.  New users of the code should only see version >= 1.  People who used the pre-released code may see version 0, but they would have to modify the deserialization code anyway to handle the old format, so they could change the precondition at that point.

**Comment by galenwarren** [comment]
@xintongsong Thanks.

@sap1ens FYI, the serializer version change will go in with this PR.

**Comment by sap1ens** [comment]
Great, thanks!

**Comment by xintongsong** [comment]
For the record, I've added exclusions for `grpc` artifacts in the `flink-dist` pom, as @zentol suggested offline. This fixes the dependency resolving error without forcing the `grpc` version on the whole project.

The CI success now. Merging this.

**Pull request closed without merging**
