### PR TITLE
[FLINK-25950][Runtime] Delete retry mechanism from ZooKeeperUtils.deleteZNode

### PR DESCRIPTION
**Pull request by JackWangCS**
## What is the purpose of the change

ZooKeeperUtils.deleteZNode implements a retry loop that is not necessary for curator version 4.0.1+. We can use idempotent delete since we already upgraded Curator to 5.2.0.

## Brief change log

  - *Delete retry mechanism from ZooKeeperUtils.deleteZNode*

## Verifying this change

This change is already covered by existing tests, such as ZooKeeperUtilsWriteLeaderInformationTest#testDeleteZNode().

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by JackWangCS** [comment]
Hi @XComp , could you help to review this PR?

**Comment by liuyongvs** [comment]
@JackWangCS It looks good to me

**Comment by JackWangCS** [comment]
> @JackWangCS It looks good to me

Thank you for the code review, let us wait for the CI report.

**Review by XComp — APPROVED** [review]
Thanks @JackWangCS for your patience. I was afk for two weeks. The change looks good. I updated the commit message to comply to the Flink community guidelines.

**Comment by XComp** [comment]
...and rebased the branch. I will merge the change next.

**Pull request merged**
