### PR TITLE
[FLINK-13450][test] Adjust tests to tolerate arithmetic differences between x86 and ARM

### PR DESCRIPTION
**Pull request by wangxiyuan**
## What is the purpose of the change

`math.log` and `math.pow` can actually return slightly different results across platforms because of hardware optimizations. We should use StrictMath instead to ensure the answers are already the same. 

## Brief change log

  - Changed Math.log to StrictMath.log
  - Changed Math.pow to StrictMath.pow

## Verifying this change

This change is already covered by existing tests

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by wangxiyuan** [comment]
@TisonKun, hi, thanks for your comment. I don't know what scope is better, since this pr changed many modules.  any suggestion? Thanks.

**Comment by TisonKun** [comment]
Hi @wangxiyuan I revoke my change request above. After taking a look at the corresponding issue I know the root cause of this pull request is to adjust test so sort it into test component makes sense to me. Besides, what do you think if we change the title of the pull request and the commit to "Adjust tests to tolerate arithmetic differences between x86 and ARM" as the original JIRA written? I think it is more descriptive.

**Comment by TisonKun** [comment]
@flinkbot run travis

**Comment by StephanEwen** [comment]
Could we reduce the changes to the scope where we really need strict results?
It looks like this mainly matters for result verification (some tests) and for the SQL functions.

In other parts, like exponential backoff, strict precision doesn't actually matter.
In some parts, like samplers, the performance is more important than the precision, so we should not use StrictMath there at all.

**Comment by StephanEwen** [comment]
To clarify how this relates to my previous comment ("have just StrictMath"):
Within a module (like SQL scalar functions) I would not try to switch back and forth between Math and StrictMath. But between different uses (sampler versus SQL function) we can differentiate where we need it and where not.

**Comment by wangxiyuan** [comment]
@StephanEwen Thanks for your review. ThenI just change the place where affect the test.

**Comment by wangxiyuan** [comment]
can anyone review this PR? Thanks.

**Comment by wangxiyuan** [comment]
@StephanEwen may this PR be visited again?

**Comment by StephanEwen** [comment]
Looks good to me.
Merging this...

**Pull request closed without merging**
