### PR TITLE
[FLINK-13961][client] Remove obsolete abstraction JobExecutor(Service)

### PR DESCRIPTION
**Pull request by TisonKun**
## What is the purpose of the change

Remove obsolete abstraction JobExecutor(Service)

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

cc @kl0u @aljoscha

### CODE REVIEW

**Comment by TisonKun** [comment]
travis fails on NOTICE-binary checker. I don't think it is relevant to this pull request.

Instead, it looks like an instance of [FLINK-14009](https://issues.apache.org/jira/browse/FLINK-14009). @tillrohrmann is it relevant?

**Comment by tillrohrmann** [comment]
@flinkbot run travis.

**Comment by TisonKun** [comment]
Hi @tillrohrmann, thanks for your review. I don't think this is an issue with high priority, but let me share you some of my concerns.

- `JobExecutor` and `JobExecutorServices` provide poor abstraction based on our codebase.

`JobExecutor` has only one method `executeJobBlocking(JobGraph)`. In my opinion, in order to submit a job and request the result we are supposed to use the client instead of directly access the cluster. `JobExecutorServices` is introduced for the usage in `LocalExecutor#executePlan(Plan)`. 

- A real demand will require clear abstraction.

Back to the introduction of `JobExecutor` and `JobExecutorService`, we are required to provide an abstraction of MiniCluster and FlinkMiniCluster, which clearly points to the interface `executeJobBlocking(JobGraph)`. Now and in the near future, we don't have another `JobExecutor`. Anytime when we find another class takes similar responsibility like `MiniCluster`, we can always add an abstraction bases on that similarity.

**Comment by TisonKun** [comment]
@flinkbot run travis

**Comment by tillrohrmann** [comment]
Even though `JobExecutor` and `JobExecutorService` are not perfect it is clearly better than depending directly on the `MiniCluster` because it follows the [interface segregation principle](https://en.wikipedia.org/wiki/Interface_segregation_principle). 

As long as a user depends on `executeJobBlocking`, we should not remove it. Whether to use the client for communication with the `MiniCluster` or directly talking to it should not be topic of this PR. The same applies to the usage of the interface in the future. You might be right but at the moment we still have users of this interface and, hence, we should not do any second or third step before having done even the first.

I still think that we should close this PR.

**Comment by TisonKun** [comment]
Now I agree with that we don't have to rush into the removal since there are still users of this interface. I will revisit this topic when the prerequisite in my mind ready.

Closed pull request and closed the corresponding JIRA as not a problem.

Thanks for your review @tillrohrmann !

**Pull request closed without merging**
