### PR TITLE
[FLINK-3180] [runtime] Log direct memory usage in MemoryLogger

### PR DESCRIPTION
**Pull request by uce**
The off-heap stats reported by the memory logger didn't include direct memory.

### CODE REVIEW

**Comment by mxm** [comment]
Thanks for the pull request. Could we also include the direct memory in the `getMemoryUsageStatsAsString()` which outputs memory information on task manager startups?

Looks good to merge otherwise!

**Comment by uce** [comment]
I've added some related changes to this PR to display the direct memory usage in the web frontend as well. The current structure didn't make a lot of sense to me:

## Current

screen shot 2015-12-17 at 17 28 42

## This PR

screen shot 2015-12-17 at 18 26 00

It's not that beautiful, but I think the ordering makes more sense now. I've also fixed a bug with the reporting of the PS-Scavenge GC times.

(PS: Sorry for overloading this PR.)

@mxm Is it OK if we address your comment in a follow up? I'm not sure how the respective bean is initialized and how expensive it is. In contrast to the other beans, this is not just a getter which initializes the bean on first access.

**Comment by mxm** [comment]
@uce Sure. We can do that.

**Comment by StephanEwen** [comment]
Nice addition.

+1

**Comment by fhueske** [comment]
LGTM, will merge

**Pull request closed without merging**
