### PR TITLE
[FLINK-4471] Use user code classloader to deserialize state descriptor in Rocks backend

### PR DESCRIPTION
**Pull request by gyfora**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

…r in RocksDb backend

### CODE REVIEW

**Comment by StephanEwen** [comment]
@aljoscha Is this fixed in the "key group" rework? What about merging this for version 1.1.2 anyways?

**Comment by aljoscha** [comment]
It should be fixed by not loading the `StateDescriptor` anymore, yes. We should maybe only merge it on the 1.1.* release branch because for 1.2 it will be overwritten by our changes.

**Comment by gyfora** [comment]
Should I push this on 1.1 then?

**Comment by aljoscha** [comment]
Yes, please. 👍

**Comment by gyfora** [comment]
Done, we can close this I guess if you are fixing it in your PR

**Comment by aljoscha** [comment]
I think so, yes.

**Pull request closed without merging**
