### PR TITLE
[hothix][doc] Correct description of local time zone in table_config_configuration.html

### PR DESCRIPTION
**Pull request by leonardBang**
## What is the purpose of the change

* This pull request revert the change in table_config_configuration.html which polluted by 16ec8337f866b9118488d9cfafd1bb025f7aaedc

## Brief change log

  -  Revert the change and keep it same with Java Class `TableConfigOptions.java`

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): ( no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by leonardBang** [comment]
cc @rmetzger  @tillrohrmann I see you merge a hotfix commit right now, but I found this failed test is not come from my PR as this PR description.......

**Comment by rmetzger** [comment]
Thanks a lot for opening this PR. Sorry that I missed it.
You are right. I just looked at the error message from the CI failure, then checked the last commit on the file mentioned in the error message ... but I didn't check the history of the generated HTML file.
The history of the file shows that there was a commit by Till in between that broke the docs https://github.com/apache/flink/commits/master/docs/layouts/shortcodes/generated/table_config_configuration.html

The issue was probably that Till had an outdated version of the config options locally.

**Comment by rmetzger** [comment]
I added a comment below the commit on master to clarify: https://github.com/apache/flink/commit/27efcd2826cd2515f26da0b9b6bd527b4a09ff7a

**Comment by leonardBang** [comment]
Thanks @rmetzger for the clarification, @guoweiM and I has found this issue and we preapre this PR to fix.
It's fine as long as we fixed it, I close this PR now..

**Comment by rmetzger** [comment]
Thanks & sorry again.

**Pull request closed without merging**
