### PR TITLE
[hotfix][docs] fix error in functions example 

### PR DESCRIPTION
**Pull request by leesf**
fix error in functions example.

### CODE REVIEW

**Comment by leesf** [comment]
cc @twalthr @zentol

**Comment by leesf** [comment]
@flinkbot attention @twalthr @zentol

**Comment by leesf** [comment]
@flinkbot attention @dawidwys would you review this PR in your free time?

**Comment by fhueske** [comment]
Hi @leesf, thanks for your PR!

The fix looks good to me.

@flinkbot approve description consensus architecture quality

I'll merge it.
Thanks, Fabian

**Pull request closed without merging**
