### PR TITLE
Updated method documentation in joinDataSet.scala for UnfinishedJoinOperation.

### PR DESCRIPTION
**Pull request by peedeeX21**
Changed .isEqualTo(..) to .equalsTo(..)

### CODE REVIEW

**Comment by StephanEwen** [comment]
Looks good, +1

**Comment by chiwanpark** [comment]
Looks good. :)
+1 for merging.

**Comment by StephanEwen** [comment]
Merging this...

**Comment by StephanEwen** [comment]
Manually merged. Thank you for the patch!

**Pull request closed without merging**
