### PR TITLE
Implementation of distributed copying utility using Flink

### PR DESCRIPTION
**Pull request by detonator413**
Uses a "dynamic" input format where faster nodes will get more stuff to be copied. 
The finest level of granularity is a file.

### CODE REVIEW

**Comment by mxm** [comment]
Thanks for your pull request! I'm assuming you would use this utility to copy files from your local to a remote file system, right? Your utility starts a Flink job to copy the files to the remote file systems. This only works if you execute it locally because otherwise the task managers need to have the files available and that might defeat the utility's purpose. Also, imagine someone embedding the tool in a Flink program. The person might wonder why his/her program actually executes two jobs (one for the utility, one for the actual job). 

I think this would be more useful as a utility function, e.g. in a `FileUtils` class in `flink-core`. The method there would receive a list of files and then upload the files like you did using Flink's `FileSystem` abstraction. We could still parallelize the method by starting multiple threads to upload the files.

Correct me if I'm wrong or misunderstood your pull request :)

**Comment by detonator413** [comment]
Hi Max,

Look at the distcp utility (http://hadoop.apache.org/docs/r1.2.1/distcp.html <http://hadoop.apache.org/docs/r1.2.1/distcp.html>). The purpose of it is to copy big amount of files within one cluster or between clusters. In local mode the tool will also work for local FS, whereas in the distributed mode only HDFS paths are supposed to be used. I made a simple benchmark on copying 800GB of data within one cluster running Hadoop distcp (using default distcp input format ) and Flink distcp in parallel. Flink job was 1.5 minutes faster (it took approximately 35 minutes in our setup).

Slava

**Comment by mxm** [comment]
Thanks for pointing me to the `distcp` page. So far, I was agnostic of this tool :) The performance difference between Hadoop and Flink should not be too different because the copying of files is mostly IO-bound work. Still, it is 1.5 minutes faster.

Not sure if we can include your code in the Flink examples but definitely under `flink-contrib` where we usually put external tools that are not directly part of Flink.

**Comment by detonator413** [comment]
It could be faster because of dynamic assignment of files to copy as opposed to the default method of distcp where set of files are preassigned to mappers in advance

**Comment by StephanEwen** [comment]
@detonator413 Good point with the dynamic assignment.

What do sou think, would `flink-contrib` or `flink-examples` be a better place? Is it rather a nice tool, or is it also educational code?

**Comment by detonator413** [comment]
Actually hadoop distcp also has an implementation of a dynamic input format which in my taste is a bit overcomplicated. So not sure if this Flink tool will give much benefits in real life (also it's lacking elasticity unlike hadoop distcp), but can be a good example how one can implement his own input format for a slightly unusual usecase.

**Comment by StephanEwen** [comment]
Okay, why not add it to the examples then?

**Comment by mxm** [comment]
Yes, I guess it is a better fit for the examples.

**Comment by StephanEwen** [comment]
Okay, let's merge it to the examples.

@detonator413 Can you add some class-level comments to the files that explains what they do?
Also, we need to remove the author tags. It is an Apache policy that code is not author tagged.

**Comment by detonator413** [comment]
Sure, will push some changes soon

**Comment by detonator413** [comment]
1 profile check mysteriously fails and seems unrelated to the changes I introduced. The code should be now compliant to the guidelines.

**Comment by mxm** [comment]
Yes, this failed check is unrelated to your changes.

**Comment by mxm** [comment]
Should we bundle the utility into a JAR like the other examples? If so, we need to adjust the `pom.xml` file in flink-examples.

**Comment by StephanEwen** [comment]
Will merge this and add a JAR file entry to the pom file...

**Pull request closed without merging**
