### PR TITLE
[FLINK-2902][web-dashboard] Sort completed jobs by end time and running jobs by start time

### PR DESCRIPTION
**Pull request by sachingoel0101**

### CODE REVIEW

**Comment by sachingoel0101** [comment]
Ping.

**Comment by aljoscha** [comment]
Looks good. Are you merging @fhueske ?

**Comment by fhueske** [comment]
Yes, will include this PR as well. Thanks!

**Comment by sachingoel0101** [comment]
If needed, I have an implementation which allows for sorting in both orders over all table columns. I can open  a PR from that branch or push that commit here.

**Comment by fhueske** [comment]
I'm already running tests on Travis and will merge it as it is now.
Would be good if you open a new PR for this. Thanks!

**Comment by sachingoel0101** [comment]
Okay. Cool. Will do that after the release.

**Pull request closed without merging**
