### PR TITLE
[FLINK-11259] Bump Zookeeper to 3.4.13

### PR DESCRIPTION
**Pull request by Fokko**
The patched version provides some hotfixes:
https://zookeeper.apache.org/doc/r3.4.13/releasenotes.html

## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

## Brief change log

Bump Zookeeper dependency

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

  - Dependencies (does it add or upgrade a dependency): yes
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: yes
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by Fokko** [comment]
The error looks related, let me dive into it.

**Comment by Fokko** [comment]
`Kafka09SecuredRunITCase` is failing. Lets see which minor patch of Zookeeper fails the build.

**Comment by zentol** [comment]
Please don't use the Apache Travis for debugging. I will close this PR; feel free to re-open once you got a working solution.

**Comment by thomaslee** [comment]
Late to the party, but pointing out the test failure in question appears to be a ZK auth issue:

https://travis-ci.org/apache/flink/jobs/480142816#L9784

Possible something subtle changed between .10 and .13 but I'm not sure what at this point.

**Comment by thomaslee** [comment]
Comments on https://issues.apache.org/jira/browse/HADOOP-15974 sound awfully similar to the issue we encountered here, but sounds more involved than a simple auth issue.

**Pull request closed without merging**
