### PR TITLE
[FLINK-24802][Table SQL/Planner] Improve cast ROW to STRING

### PR DESCRIPTION
**Pull request by shenzhu**
## What is the purpose of the change

[FLINK-24802](https://issues.apache.org/jira/browse/FLINK-24802) Improve cast ROW to STRING

## Brief change log

Add a space after the comma when casting ROW to string.

## Verifying this change

This change is already covered by existing tests, such as *CastRulesTest.java*.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Review by RocMarshal — APPROVED** [review]
@shenzhu Thanks for the contribution.
Looks good to me on the whole.

ping @wuchong , @twalthr .

**Review by slinkydeveloper — APPROVED** [review]
Thank you for your PR!

**Comment by fapaul** [comment]
@shenzhu thanks for your contribution, can you squash the two commits and maybe change the commit message name to `[FLINK-24802][table] ...`.

I'll then merge the PR.

**Comment by shenzhu** [comment]
> [FLINK-24802][table] Improve cast ROW to STRING

Hey @fapaul , thanks for your help! I just rebased and updated the commit name to `[FLINK-24802][table] Improve cast ROW to STRING`.

**Comment by fapaul** [comment]
@shenzhu There appears to be a test failure in the table module. Can you double-check that the failure is not caused by your changes?

**Comment by shenzhu** [comment]
> @shenzhu There appears to be a test failure in the table module. Can you double-check that the failure is not caused by your changes?

Before the rebase I can see the Azure build SUCCESS, and got FAILURE after I rebase master, let me try build again.

**Comment by shenzhu** [comment]
@flinkbot run azure

**Comment by shenzhu** [comment]
@flinkbot run azure

**Pull request merged**
