### PR TITLE
[FLINK-8010][build] Bump remaining flink-shaded versions

### PR DESCRIPTION
**Pull request by zentol**
## What is the purpose of the change

This PR bumps the remaining flink-shaded dependencies to 2.0.

## Brief change log

* add flink-shaded version property to root-pom (to prevent this issue in the future)
* group flink-shaded dependencies together
* replace dependency version with flink-shaded version property

## Verifying this change

If it compiles we're good.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by aljoscha** [comment]
+1 (once travis is green)

**Comment by greghogan** [comment]
Is anyone else seeing the red/green highlights shifted two lines up for this PR? I'm seeing this in multiple browsers and with plug-ins disabled but only on this PR.

**Comment by zentol** [comment]
@greghogan I also had this in another PR but not this one.

**Comment by zentol** [comment]
scratch that, i have it in this one, here:
```
 				<groupId>org.apache.flink</groupId>
 				<artifactId>flink-shaded-guava</artifactId>
-				<version>18.0-1.0</version>
+				<version>18.0-${flink.shaded.version}</version>
```

**Comment by zentol** [comment]
merging.

**Pull request closed without merging**
