### PR TITLE
[FLINK-23744][sql-client] Fix unstable CliClientTest

### PR DESCRIPTION
**Pull request by fsk119**
…ionInteractiveMode

## What is the purpose of the change

*Fix the unstable test `CliClientTest`. The main reason why it is unstable is because we use the main thread to observe the client thread whether is interrupted. However, the worker thread will clear the INTERUPTED flag and continue its execution. Although we raise the signal we may find the flag is cleared or not set. I think we should check whether the client can continue process the commands after the interruption rather than the thread status here.*

### CODE REVIEW

**Comment by saddays** [comment]
@fsk119 , hi do you find the place  where clear INTERUPTED flag ?

**Comment by fsk119** [comment]
Hi @saddays . I think it's just JVM behavirour.  In doc[1], it says 
```
By convention, any method that exits by throwing an InterruptedException clears interrupt status when it does so.
```
In the test, the `Thread.sleep` will throw the exception when it is interrupted.

[1] https://docs.oracle.com/javase/tutorial/essential/concurrency/interrupt.html

**Review by wuchong — APPROVED** [review]
LGTM.

**Comment by saddays** [comment]
I'm sorry about that introduce a bug, i should have noticed this unstable behaviour.

**Pull request merged**
