### PR TITLE
[FLINK-30971][table-runtime] Modify the default value of parameter 'table.exec.local-hash-agg.adaptive.sampling-threshold'

### PR DESCRIPTION
**Pull request by swuferhong**
## What is the purpose of the change

In our test environment, we set the default parallelism to  1 and got the most appropriate default value of parameter `table.exec.local-hash-agg.adaptive.sampling-threshold`  is `5000000.` However, for these batch jobs with high parallelism in produce environment,  the amount of data in single parallelism is almost less than `5000000`. Therefore, after testing, we found that set to `500000` can get better results.

## Brief change log

Modify the default value of `table.exec.local-hash-agg.adaptive.sampling-threshold`.

## Verifying this change

no test.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? no

### CODE REVIEW

**Comment by swuferhong** [comment]
@flinkbot run azure

**Comment by swuferhong** [comment]
@flinkbot  run azure

**Comment by swuferhong** [comment]
@flinkbot run azure

**Review by godfreyhe — APPROVED** [review]
LGTM

**Pull request merged**
