### PR TITLE
[FLINK-15034] Bump FRocksDB version for memory control

### PR DESCRIPTION
**Pull request by Myasuka**
## What is the purpose of the change

Since FLINK-14483 has already been resolved and a new version of FRocksDB has been released, we should bump the FRocksDB version in Flink for next steps in memory control.

## Brief change log
Bump FRocksDB version in `flink-state-backends/flink-statebackend-rocksdb/pom.xml`

## Verifying this change

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): **yes**
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? **yes**
  - If yes, how is the feature documented? **will be updated in docs of FLINK-14495**

### CODE REVIEW

**Comment by StephanEwen** [comment]
Can you check if any NOTICE / LICENSE files need updates here?

**Comment by Myasuka** [comment]
@StephanEwen thanks for your examination, already updated `flink-dist/src/main/resources/META-INF/NOTICE`

**Comment by StephanEwen** [comment]
Merged in dd82989e6cba7cd2dee1fdf013a67a163dfcb849

**Comment by pnowojski** [comment]
Do you know what could have changed during this upgrade that could explain a performance [regression](https://issues.apache.org/jira/browse/FLINK-15104)?

**Comment by Myasuka** [comment]
@pnowojski From the commits https://github.com/dataArtisans/frocksdb/commits/FRocksDB-5.17.2 , I cannot see real complex changes to cpp files. Most of code is to support java to call more functions via JNI.

@azagrebin what is the difference between `com.data-artisans:frocksdbjni:5.17.2-artisans-2.0` compared with my previous built of `io.github.myasuka:frocksdbjni:5.17.2-artisans-6.0` in [FLINK-14483](https://issues.apache.org/jira/browse/FLINK-14483)?

**Comment by azagrebin** [comment]
@Myasuka I have not rebuilt 2.0, I believe we have your latest built version in maven central

**Pull request closed without merging**
