### PR TITLE
[FLINK-3900] Set nullCheck=true as default in TableConfig

### PR DESCRIPTION
**Pull request by rekhajoshm**
[FLINK-3900] Settig nullCheck as true as default in TableConfig

### CODE REVIEW

**Comment by twalthr** [comment]
Looks good to merge.

**Comment by rekhajoshm** [comment]
@twalthr updated doc.thanks

**Comment by fhueske** [comment]
Merging this PR.

**Comment by rekhajoshm** [comment]
thanks @fhueske

**Pull request closed without merging**
