### PR TITLE
FLINK-4499: [WIP] Introduce findbugs maven plugin

### PR DESCRIPTION
**Pull request by smarthi**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.
- [X] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)
- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added
- [X] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by smarthi** [comment]
Setup a default findbugs-exclude.xml, please feel free to customize as u deem fit for Flink.

**Comment by StephanEwen** [comment]
Thanks for adding this.

I think that pure warning by the plugin will not be read and respected really. So it makes only sense when a "bug" detected by the plugin fails the build.

How about starting with a low set of settings and configuring it to fail when detecting errors? We can then gradually activate more and more visitors.

Also, do you have any experience in how finbugs usually affects the build times?

**Comment by smarthi** [comment]
I updated the findbugs-exclude.xml with some basic rules that can be ignored. 

I set the <effort> to 'default' for now - can't keep it 'High' since it was freezing up my laptop. 

There are still more rules that can be excluded, but I think this is a good start to seed the excluded rules.

Build times take an impact if the <effort> is set to high, I now have that set to 'default'.

**Comment by StephanEwen** [comment]
Cool, thanks! The changes in the code look good.

Give us a bit of time to play with the build and the findbugs output to get a better feeling for this...

**Comment by smarthi** [comment]
Sure. I tried to exclude the most obvious false negatives but didn't go to the full extent. Hopefully this is a good place to start.

**Comment by rmetzger** [comment]
I've compared the build time of the pull request with a recent build on master, and it seems that the impact on the build time is pretty big (right is with findbugs):
image

On my local machine, the build time looks like this:
+findbugs: 15:47 min
-findbugs: 08:24 min

On travis, our builds would be again pretty close to the 2 hours limit with this change.
Maybe we can move the findbugs plugin into a separate profile and run it in a special build on travis?
I'll try that out and report back.

**Comment by StephanEwen** [comment]
Does the runtime depend on the set of activated rules? If yes, should we start with a very small set of rules that fail the build when triggered?

**Comment by uce** [comment]
I think that the increased build times are a blocker for executing this with every CI run. Maybe this could become something that we execute nightly instead? Not ideal, but better than nothing.

**Comment by greghogan** [comment]
@smarthi are you still able to work on this PR? We could enable in a profile when `TRAVIS_EVENT_TYPE=cron` is set in the [environment](https://docs.travis-ci.com/user/environment-variables/).

**Comment by StephanEwen** [comment]
When would `TRAVIS_EVENT_TYPE=cron` be set?

**Comment by greghogan** [comment]
We would need INFRA to enable a daily cron build for Flink. How will we use FindBugs (which may be dead)? Is a goal to export the site artifacts to S3?

**Comment by tedyu** [comment]
Hadoop has switched to spotbugs

**Comment by aljoscha** [comment]
@smarthi, could you please close this PR, now that we have added spotbugs support?

**Pull request closed without merging**
