### PR TITLE
[FLINK-31498][runtime] Only request redundant task manager when all pending slots registered.

### PR DESCRIPTION
**Pull request by huwh**
## What is the purpose of the change
We will request redundant task managers when there are no enough free slots. But if task manager start too slow or yarn/Kubernetes no resource to create new task manager.  This logic will request new task managers in each periodic check.

## Brief change log
  - *Only request new redundant task managers when there is no pending slots.*

## Verifying this change
*(example:)*
  - *Tested manually with 2 required task managers and  2 redundant task managers. Kubernetes only could provide 2 pods, so the 2 redundant task manager will be pending, and no new task manager will be request*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`:(no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Review by reswqa — APPROVED** [review]
Thanks @huwh, only left nit comments about testing.

**Comment by huwh** [comment]
@reswqa Thanks for you review. comments addressed, please take a look.

**Comment by reswqa** [comment]
Thanks for the quick update, merged % CI passed.

**Comment by reswqa** [comment]
@flinkbot run azur

**Comment by reswqa** [comment]
@flinkbot run azure

**Comment by huwh** [comment]
@reswqa I think this PR is mergeable, could you please help merge it in your free time?

**Comment by reswqa** [comment]
@huwh Sure, It seems that CI has passed.

**Pull request merged**
