### PR TITLE
[FLINK-17260] Fix StreamingKafkaITCase instabilities

### PR DESCRIPTION
**Pull request by aljoscha**
This fixes two possible sources of instability:
 - not reading all the messages because of timeout
 - clashes in topic names, which lead to double counting

### CODE REVIEW

**Comment by zentol** [comment]
We should do the same for the `org.apache.flink.tests.util.kafka.SQLClientKafkaITCase`

**Comment by zentol** [comment]
The overall changes are fine though; so +1 once the SQLClientKafkaITCase was adjusted in a similar fashion.

**Comment by aljoscha** [comment]
Good catch! I'll do that.

**Comment by aljoscha** [comment]
I pushed the same changes also for `SQLClientKafkaITCase`

**Comment by aljoscha** [comment]
Thanks again for the thorough reviews, @zentol! 🍵

**Pull request closed without merging**
