### PR TITLE
[FLINK-18422][docs] Update Prefer tag in documentation 'Fault Tolerance training lesson'

### PR DESCRIPTION
**Pull request by RocMarshal**
## What is the purpose of the change  

Update Prefer tag in documentation 'Fault Tolerance training lesson' according to [Prefer Reminder](http://apache-flink-mailing-list-archive.1008284.n3.nabble.com/Reminder-Prefer-link-tag-in-documentation-td42362.html) .The markdown file location is:  flink/docs/learn-flink/fault_tolerance.md

## Brief change log

  - *Update Prefer tag in documentation 'flink/docs/learn-flink/fault_tolerance.md'*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? no

### CODE REVIEW

**Comment by RocMarshal** [comment]
@klion26 
Could you help me to review this PR(https://github.com/apache/flink/pull/12778)
Thank you.

**Comment by RocMarshal** [comment]
Hi, @wuchong 
Could you help me to review this PR(https://github.com/apache/flink/pull/12778)？
Thank you.

**Comment by klion26** [comment]
@RocMarshal  thanks for your contribution, could you please also change the Chinese version?

**Comment by RocMarshal** [comment]
> @RocMarshal thanks for your contribution, could you please also change the Chinese version?

@klion26 
Of course. I had completed the changes in [PR 12727](https://github.com/apache/flink/pull/12727) according to your suggestions, which was already merged into master branch.

Thank you so much.

**Comment by RocMarshal** [comment]
@klion26 ,
I have made some changes according to your suggestions and [David Anderson's reply](http://apache-flink-mailing-list-archive.1008284.n3.nabble.com/Reminder-Prefer-link-tag-in-documentation-td42362.html#a42826) ,please take a look.

Thank you !

**Comment by RocMarshal** [comment]
@wuchong Could you help me to merge this PR if the condition is met ?
Thank you.

**Pull request merged**
