### PR TITLE
[FLINK-16000] Move "Project Build Setup" to "Getting Started" in documentation

### PR DESCRIPTION
**Pull request by aljoscha**
This is pretty much the first thing you have to do when programming with Flink, so it belongs in the "Getting Started" section, this is outlined in [FLIP-42](https://cwiki.apache.org/confluence/display/FLINK/FLIP-42%3A+Rework+Flink+Documentation).

### CODE REVIEW

**Comment by StephanEwen** [comment]
I agree with both of Konstantin's suggestions.

Maybe we could add a sentence that this is the setup for developing a Flink application.
You can still play with other parts without that, like launch a cluster, use SQL CLI, especially with the Docker playgrounds.

**Comment by aljoscha** [comment]
@knaufk I suggest to remove the icons from "Code Walkthroughs" and "Docker Playgrounds". None of the other sections except of the top-level sections have icons so that makes it more consistent. And I would then move "Project Setup" to last position.

@StephanEwen I will add some explanation in the Overview section.

**Comment by aljoscha** [comment]
@knaufk & @StephanEwen I did the changes, I also re-ordered them to make it internally consistent (see commit message). PTAL.

**Comment by aljoscha** [comment]
Thanks for the reviews! Merged.

**Pull request closed without merging**
