### PR TITLE
[FLINK-5441] [table] Directly allow SQL queries on a Table

### PR DESCRIPTION
**Pull request by wuchong**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

This PR allows calling SQL directly on a table :

```scala
myTable.sql("SELECT a, b, c FROM _ WHERE d = 12")
```

### CODE REVIEW

**Comment by wuchong** [comment]
Hi @KurtYoung , thank your for reviewing. I'm not sure about that. Do you mean omitting the "FROM" syntax ?  But it will be hard to validate SQL syntax. Because the query can follow a WHERE clause or JOIN/UNION with other tables.  For example, it's wired and hard to validate the query like this:

```
mytable.sql("SELECT * WHERE a > 13 UNION SELECT * FROM TABLE_B")
```

I think allowing query on other tables is fine here.  What do you think ?

**Comment by KurtYoung** [comment]
I still think this is weird. Currently all API from `Table` is somehow act on the table object, just like a normal OOP program. After introducing `sql` method to `Table`, it can do something completely unrelated to the current object.

**Comment by twalthr** [comment]
@KurtYoung I agree that this syntax can be misused like `table.sql("SELECT * FROM otherTable")`. But right now it is very inconvenient to always register a table first, especially if you want to define multiple queries subsequently.

We could also think about `env.sql("SELECT * FROM _ JOIN _", table, otherTable)`. Other suggestions are very welcome.

Another idea that just came to my mind. We could also use the `toString` method of a Table. This method could implicitly register the Table under a unique name and return that. Then we could support `env.sql(s"SELECT * FROM $table JOIN $otherTable")`.

**Comment by wuchong** [comment]
What about using slf4j syntax `env.sql("SELECT * FROM {} JOIN {}", table1, table2)` ?

**Comment by fhueske** [comment]
Hi, I like @twalthr's suggestion to use `env.sql("SELECT * FROM _ JOIN _", table, otherTable)`. 
I'd also be fine with slf4j syntax as @wuchong proposed.

What do you think @KurtYoung?

**Comment by KurtYoung** [comment]
Hi @fhueske, both solutions are fine with me.

**Comment by twalthr** [comment]
What do you think about my solution of `env.sql(s"SELECT * FROM $table JOIN $otherTable")`? It would be much more readable.

**Comment by wuchong** [comment]
Hi @twalthr , the `env.sql(s"SELECT * FROM $table JOIN $otherTable")` is a nice way. But how to handle the table's table name and register it to env ?

**Comment by fhueske** [comment]
Agreed, for Scala the inlined variant looks really good. Like @wuchong, 
I'm curious how we can intercept the inlined string arguments. Do you know how to do that @twalthr?

**Comment by twalthr** [comment]
We don't have to intercept inline string arguments. We just have to make sure that `Table.toString()` returns an unique identifier that the method previously registered in it's table environment. `Table.toString()` should then always return the same identifier.

**Comment by wuchong** [comment]
@twalthr do you mean register table in his `toString` method ?

**Comment by fpompermaier** [comment]
It's for this reason that I think that Flink needs a "source catalog"
somewhere..

**Comment by fhueske** [comment]
An external catalog would not help in this case. It's actually quite the opposite. The issue is to run a SQL query on an ad-hoc table without the need to explicitly add it to a catalog.

**Comment by twalthr** [comment]
@wuchong if `toString` is called for the first time. It calls `tEnv.registerTableInternal(this)` which uses an atomic counter and generates a unique identifier such as `UnnamedTable$232`. This identifier is returned and saved in the table. Every further call of toString return this identifier.

**Comment by wuchong** [comment]
Thank you @twalthr , I like the idea. So Java users can also use `env.sql("SELECT * FROM " + table1 + " JOIN " + table2)` as a shortcut. What do you think @fhueske ?

**Comment by fhueske** [comment]
Hmm, I think registering tables in `toString()` (which IMO should be free of side effects) is not very clean, but I have to admit that the API looks good. So, I would be OK doing this like that.

Would we also take care to unregister the tables after the query was optimized?

**Comment by twalthr** [comment]
Do we have to take care of unregistering the tables? Right now `fromDataSet/fromDataStream` do also not unregister their unique names.

**Comment by fhueske** [comment]
But what's the point of keeping tables that will never be used again?

**Comment by twalthr** [comment]
I think the point is that we don't know if the table will ever be used again. If we unregister them after optimization, we can not have multiple `toDataStream()` calls for one table.

**Comment by fhueske** [comment]
Yes, you are right. Forgot that we lazily translate the plans. :-/
Let's keep the tables then.

**Comment by twalthr** [comment]
@wuchong any plans to update this PR?

**Comment by wuchong** [comment]
@twalthr Yes,  I will update it in these days.

**Comment by wuchong** [comment]
@twalthr  I have updated this PR regarding to the idea you proposed that `env.sql(s"SELECT * FROM $table JOIN $otherTable")`

**Comment by twalthr** [comment]
Thanks for the quick update @wuchong. The code looks good to merge. Can you add some documentation to the SQL section?

**Comment by wuchong** [comment]
updated the documentation.

**Comment by twalthr** [comment]
Thanks @wuchong. Will merge this.

**Pull request closed without merging**
