### PR TITLE
[FLINK-21966][python]Support Kinesis connector in Python DataStream API

### PR DESCRIPTION
**Pull request by xinbinhuang**
## What is the purpose of the change

Add support for kinesis connector for the Python datastream API

## Brief change log

  - Add FlinkKinesisProducer
    - [ ] Add common setters/getters
  - Add FlinkKinesisConsumer
    - [ ] Add common setters/getters

## Verifying this change

- [ ] Add tests coverage in test_connectors.py

## Does this pull request potentially affect one of the following parts:

- Dependencies (does it add or upgrade a dependency): ( no)
- The public API, i.e., is any changed class annotated with @Public(Evolving): ( no)
- The serializers: (no)
- The runtime per-record code paths (performance sensitive): (no)
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
- The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by DavidFricker** [comment]
We have implemented something similar and started receiving classloader exceptions as below, however the job continues to work fine and stream data from Kinesis:
```
Job has been submitted with JobID 31975670b3660829abf7e69c3a13c2c6
Exception in thread "Thread-11" java.lang.IllegalStateException: Trying to access closed classloader. Please check if you store classloaders directly or indirectly in static fields. If the stacktrace suggests that the leak occurs in a third party library and cannot be fixed immediately, you can disable this check with the configuration 'classloader.check-leaked-classloader'.
        at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$SafetyNetWrapperClassLoader.ensureInner(FlinkUserCodeClassLoaders.java:164)
        at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$SafetyNetWrapperClassLoader.getResource(FlinkUserCodeClassLoaders.java:183)
        at java.lang.ClassLoader.getResource(ClassLoader.java:1084)
        at org.apache.hadoop.conf.Configuration.getResource(Configuration.java:2779)
        at org.apache.hadoop.conf.Configuration.getStreamReader(Configuration.java:3035)
        at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2994)
        at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2967)
        at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2847)
        at org.apache.hadoop.conf.Configuration.get(Configuration.java:1199)
        at org.apache.hadoop.conf.Configuration.getTimeDuration(Configuration.java:1811)
        at org.apache.hadoop.conf.Configuration.getTimeDuration(Configuration.java:1788)
        at org.apache.hadoop.util.ShutdownHookManager.getShutdownTimeout(ShutdownHookManager.java:183)
        at org.apache.hadoop.util.ShutdownHookManager.shutdownExecutor(ShutdownHookManager.java:145)
        at org.apache.hadoop.util.ShutdownHookManager.access$300(ShutdownHookManager.java:65)
        at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:102)
```
We also tried the implementation from this PR and got the same error as above.

Happy to contribute back here and help to debug if someone can point us in the right direction. We are using:
 - Flink 1.13.1
 - apache-flink==1.13.1 (for pyflink)
 - YARN on AWS EMR
 - `flink-sql-connector-kinesis_2.11-1.13.1.jar`
 - `flink run -t yarn-per-job --detached -py /path/to/main.py --pyFiles /path/to/dependencies.zip -pyexec /usr/bin/python3.7 --parallelism 4` to submit the job

**Comment by kbohinski** [comment]
I can help if needed as well!

**Comment by aimran-adroll** [comment]
Thanks @xinbinhuang . This would be a great addition

**Comment by dianfu** [comment]
What's the status of this PR? I can help to review if it's updated.

**Comment by SubNader** [comment]
@xinbinhuang this would be very nice to have. Let me know if I can help.

**Comment by dianfu** [comment]
Closed as it should already been supported.

**Pull request closed without merging**
