### PR TITLE
[FLINK-1505] Separate reader API from result consumption

### PR DESCRIPTION
**Pull request by uce**
@gyfora, can you please rebase on this branch and verify that everything is still working as expected for you?

This PR separates the reader API (record and buffer readers) from result consumption (input gate). The buffer reader was a huge component with mixed responsibilities both as the runtime component to set up input channels for intermediate result consumption and as a lower-level user API to consume buffers/events.

The separation makes it easier for users of the API (e.g. flink-streaming) to extend the handling of low-level buffers and events. Gyula's initial feedback confirmed this.

In view of FLINK-1568, this PR makes it also easier to test the result consumption logic for failure scenarios.

I will rebase #356 on this branch.

### CODE REVIEW

**Comment by gyfora** [comment]
Thank you!
I will try it over the weekend and give you feedback.

**Comment by gyfora** [comment]
We have rebased and tried, it works fine for us, thank you. I will add several minor changes afterwards but thats just for our convenience.

So from my side 
+1

**Comment by senorcarbone** [comment]
+1 from me as well, works fine! Nice decoupling :)

**Comment by uce** [comment]
Ok, thanks. I will merge this then.

**Pull request closed without merging**
