### PR TITLE
[FLINK-2632] Web Client does not respect the class loader of submitted jobs

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
I just did a quick test via `bin/start-local.sh` and `bin/start-webclient.sh`. Uploaded WordCount example via WebClient UI and submitted it successfully.

**Comment by rmetzger** [comment]
+1

**Comment by fhueske** [comment]
Thanks @mjsax for fixing this so quickly!
Will merge it

**Comment by mxm** [comment]
+1

I think the JobSubmissionServlet's interaction with the CliFrontend is a bit hacky. We should probably refactor this in the future. But that's a separate concern. Thanks for the fix.

**Pull request closed without merging**
