### PR TITLE
[FLINK-1168] Adds multi-char field delimiter support for CsvInputFormats

### PR DESCRIPTION
**Pull request by fhueske**
This commit includes parts of Cbro's pull request and subsumes PR #247

This closes #247

### CODE REVIEW

**Comment by fhueske** [comment]
Are there other opinions on this?

**Comment by StephanEwen** [comment]
Since you added a charset for the delimiter, it would be good to have this consistent with the String conversion.

1.  Either both cannot be configured and are only applicable to UTF-8
2.  Or we define a charset for the input format as a whole, which is used for delimiter and StringParser

**Comment by fhueske** [comment]
That's a good point. I copied the code from the DelimitedInputFormat which allows to specify the charset for the record delimiter. 
So if we go with
1. we should also fix the DelimitedIF to UTF-8.
2. we need to extend the StringValue which does not support charsets.

1) would be the easy fix. Charset support could be added later. Any objections with going for 1)?

**Comment by StephanEwen** [comment]
+1 for going for (1)

**Comment by fhueske** [comment]
Updated the PR and will merge once Travis completed the build.

**Pull request closed without merging**
