### PR TITLE
[FLINK-36013] [runtime] Introduce the transition from Restarting to CreatingExecutionGraph state

### PR DESCRIPTION
**Pull request by ztison**
## What is the purpose of the change

The `AdaptiveScheduler` omits the `WaitingForResources` state when rescaling to avoid an additional waiting in that state. 

## Brief change log

- Pass the `forcedRestart` flag into the `Restarting` state 
- Directs the state transition to the `CreatingExecutingGraph` instead of `WaitingForResources` if flag `forcedRestart` is set

## Verifying this change

This change added tests and can be verified as follows:

  - Added test to verify final state transition if the flag is set or not

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by ztison** [comment]
@flinkbot run azure

**Comment by XComp** [comment]
@fredia why did you merge this PR? It wasn't even approved, yet. 🤔

**Comment by XComp** [comment]
ok, that's odd - looks like this is a glitch in Github? The commit https://github.com/apache/flink/commit/54b0d6a858cd18e57fde60966a01cd673cb6da7a that is connected with the merge event above is related to https://github.com/apache/flink/pull/25229 (FLINK-35827). The change of this PR didn't make it to `master` but the PR is closed and marked as "Merged" anyway.

**Comment by fredia** [comment]
@XComp I didn't merge this PR, and I checked the master branch and it does not include the commits of this PR. 👀
Not sure if this is related https://github.com/orgs/community/discussions/132824

**Comment by XComp** [comment]
yeah, interesting. Thanks for the pointer to the discussion. That's also what the GH support indicated in the support ticket above

**Pull request merged**
