### PR TITLE
[FLINK-25544][streaming][JUnit5 Migration] The api package of module flink-stream-java

### PR DESCRIPTION
**Pull request by Jiabao-Sun**
## What is the purpose of the change

[FLINK-25544][streaming][JUnit5 Migration] The api package of module flink-stream-java

## Brief change log

[JUnit5 Migration] The api package of module flink-stream-java

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? ( no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by Jiabao-Sun** [comment]
Hi @GOODBOY008, could you help review this PR when you have time?

**Comment by Jiabao-Sun** [comment]
Test case count checked.

| branch | succeed | ignored | total |
| --- | ---- |---|--- | 
|pr |     1076 | 80 | 1156 (Disabled 8) |    
|master| 1076 | 88 (Ignored 8) | 1164  |

**Comment by Jiabao-Sun** [comment]
Hi @ferenc-csaky, could you help review this PR as well?
Thanks a lot.

**Comment by ferenc-csaky** [comment]
> Hi @ferenc-csaky, could you help review this PR as well? Thanks a lot.

Yep, already on it. Probably can be done with it today or tomorrow.

**Review by ferenc-csaky — COMMENTED** [review]
Mostly looks good, added some minor comments, suggestions, PTAL.

**Comment by Jiabao-Sun** [comment]
Thanks @ferenc-csaky for the hard review.
Could you help check it again?

**Review by ferenc-csaky — APPROVED** [review]
Thank you for the quick response, LGTM!

**Review by GOODBOY008 — APPROVED** [review]
@Jiabao-Sun LGTM

**Pull request merged**
