### PR TITLE
FLINK-3657: Change access of DataSetUtils.countElements() to 'public'

### PR DESCRIPTION
**Pull request by smarthi**

### CODE REVIEW

**Comment by zentol** [comment]
I think this method's use-case is **way** too specific to offer it as part of the API.

You also touch 3 files purely for formatting.

**Comment by fhueske** [comment]
I'm not sure if it is too specific. The fact that somebody reimplemented the functionality hints that it might be useful. 
However, the name would need to be changed to something like `countElementsPerPartition()`, IMO.

**Comment by andrewpalumbo** [comment]
This method would be very useful to us, e.g., when assigning ordinal indices to the elements of a `DataSet` from an external mapping.  I would not think that this is too specific a use case.

**Comment by zentol** [comment]
Please stop force pushing for squashed changes, it obfuscates which comments you addressed, forcing us to through the _entire _PR again.

**Comment by smarthi** [comment]
Not sure as to why u think this is "way to specific", this is a very convenient feature to have when dealing with Distributed Row Matrix (DRM) blocks for distributed Machine Learning computations. We found ourselves 3 different variants doing the same thing and Flink happened to have one that directly did it for Flink's datasets. Hence this PR.

@fhueske thanks for your feedback, it would be great to have this in the planned 1.0.1 bug release.

**Comment by uce** [comment]
As a side note (I didn't look at the code changes): We can't rename the method name for `1.0.1` as `DataSetUtils` is annotated with `PublicEvolving`, meaning that we are only allowed to change between minor versions, that is for `1.1.0`.

**Comment by fhueske** [comment]
@uce, API stability is not an issue. The method was `private` before and part of the accessible API. IMO, the question is rather whether we want to add new features in a bugfix release.

**Comment by smarthi** [comment]
@uce @fhueske to add more context to this PR, we r in the final stretch of a planned 0.12.0 Mahout release that adds Flink as a distributed engine for Samsara linear algebra. I will be demoing the Mahout-Flink integration at my talk in ApacheCon, Vancouver, May 9-11. If this can't make it in 1.0.1, I guess we need to go with a redundant clone in Mahout until this becomes available in a future Flink release and want to avoid that.

**Comment by andrewpalumbo** [comment]
I've actually come across several use cases for this when Implementing a blockified matrix multiplication operator.  Exposing this method as public would be very helpful. It would be great to have in your 1.0.1 release.  Thanks.

**Comment by hsaputra** [comment]
If it is on the Dataset or any extendible public APIs, I would be worried. The change was to expose private to public without modifying existing behavior. Would be ok from my side.

**Comment by hsaputra** [comment]
@smarthi Could you remove some of the refactoring or clean up changes included with this PR?

It can be added as separate PR please. Thanks.

**Comment by mbalassi** [comment]
I think @smarthi has a point that the functionality is a nice fit for `DataSetUtils` and he has properly added it to the scala API and covered the tests.
It is true that it has some minor refactoring obfuscating the core PR, but besides that LGTM. If noone thinks otherwise I would merge this Tuesday morning with optionally excluding the refactor parts if it is considered that bothersome.
Unfortunately for the Mahout release I think the policy is as @fhueske suggests that we should reserve new features for the next, 1.1.0 release line.

**Comment by hsaputra** [comment]
@mbalassi : There is already request from @zentol and me to clean up the PR, so would love to get this merge excluding the refactor parts. Thanks.

I think we should merge this to master and 1.1.0, the question is whether this should go to 1.0.1 release, which @fhueske and @uce think should not.

**Comment by smarthi** [comment]
Closing this PR without merging as its "way too specific", thanks for all the feedback.

**Comment by uce** [comment]
@smarthi I think it's not too specific at all since its part of `DataSetUtils` and not `DataSet`. Let's merge the changes to master for `1.1`.

**Comment by hsaputra** [comment]
+1 for merging to master. 

But would love to isolate the changes to exclude refactoring changes if possible

**Comment by andrewpalumbo** [comment]
Is it possible to get this merged into the 1,0.2 release?

**Comment by hsaputra** [comment]
I think it will go to 1.1.x release. Need some clean up to isolate the changes needed.

**Comment by fhueske** [comment]
Thanks for the update @smarthi. Will merge this PR.

**Pull request closed without merging**
