### PR TITLE
[FLINK-13400]Remove Hive and Hadoop dependencies from SQL Client

### PR DESCRIPTION
**Pull request by yiduwangkai**
What is the purpose of the change
This pull request will remove all dependencies on Hive/Hadoop and replace catalog-related tests by a testing catalog

Brief change log
Add new module flink-end-to-end-tests-hive in flink-end-to-end-tests
remove all dependencies on Hive/Hadoop in flink-sql-client
and move to new module flink-end-to-end-tests-hive
support catalog-related tests
Add SQLClientHiveITCase.java/TestHiveCatalogFactory.java in new module flink-end-to-end-tests-hive
Modify SqlParserHelper.java/ExecutionContextTest.java/DependencyTest.java

Verifying this change: no, because some of these modifications is about testing

Does this pull request potentially affect one of the following parts:
Dependencies (does it add or upgrade a dependency): (no)
The public API, i.e., is any changed class annotated with @public(Evolving): (no)
The serializers: (no)
The runtime per-record code paths (performance sensitive): (no)
Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
The S3 file system connector: (no)
Documentation
Does this pull request introduce a new feature? (no)
If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by yiduwangkai** [comment]
@fsk119  @lirui-apache pls help me review, thx

**Comment by fsk119** [comment]
Thanks for your contribution. Please make sure you pass the CI test at least before review. Currently I notice your branch fails because of the missing license.

I find your branch still uses the YAML file to test SQL Client and Hive. However, this is not suggested right now. Could you do as the #15944 to use the SQL file as the init file?

By the way I don't think it's the standard way to implement the E2E Tests? Please read the [doc](https://github.com/apache/flink/blob/master/flink-end-to-end-tests/README.md#writing-tests). I think we should start a real hive cluster. What do you think @lirui-apache?

**Comment by yiduwangkai** [comment]
@fsk119 hi, according to you,the amount of work will be a bit huge，First of all, I need to run a hive docker environment. I see the code, and I seem to need to modify the docker file, because I need to create the hive image by myself, right?，and then I need to run the sql-client.sh script to perform e2e testing，right?

**Comment by yiduwangkai** [comment]
@lirui-apache how do you think about this

**Comment by lirui-apache** [comment]
@yiduwangkai Thanks for working on this!
To implement real e2e test for hive connector, I agree we should use a real hive cluster (probably via docker). If that's too much work, we can do it as a follow-up and focus on refactoring here. And the new test should follow the convention of e2e tests, e.g. use init script/DDL instead of yaml file as @fsk119 has pointed out.

**Comment by fsk119** [comment]
@snuyanzin Sorry for the late response. I think SqlGatewayE2ECase is a good point to restart the work. We have introduced a hive docker in the test.

**Comment by luoyuxia** [comment]
Fix via #22690

**Pull request closed without merging**
