### PR TITLE
[FLINK-16201][sql] Support JSON_VALUE for blink planner

### PR DESCRIPTION
**Pull request by XuQianJin-Stars**
## What is the purpose of the change

Support `JSON_VALUE` function for blink planner

## Brief change log

*(for example:)*

- Introduce `JSON_VALUE` to `FlinkSqlOperatorTable`
- Add corresponding test cases

## Verifying this change

*(Please pick either of the following options)*

This change added tests in `JsonFunctionsTest.scala` 

*(example:)*

- *Added integration tests for end-to-end deployment with large payloads (100MB)*
- *Extended integration test for recovery after master (JobManager) failure*
- *Added test that validates that TaskInfo is transferred only once across recoveries*
- *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

- Dependencies (does it add or upgrade a dependency): (yes / no)
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
- The serializers: (yes / no / don't know)
- The runtime per-record code paths (performance sensitive): (yes / no / don't know)
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / no / don't know)
- The S3 file system connector: (yes / no / don't know)

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by wuchong** [comment]
Hi @XuQianJin-Stars , could you rebase this pull request? I think `JSON_VALUE` is the most important function which we should support among the json functions. 

Hi @libenchao , could you help to review this once it is ready?

**Comment by XuQianJin-Stars** [comment]
> Hi @XuQianJin-Stars , could you rebase this pull request? I think `JSON_VALUE` is the most important function which we should support among the json functions.
> 
> Hi @libenchao , could you help to review this once it is ready?

well，Let me do it.

**Comment by libenchao** [comment]
> Hi @libenchao , could you help to review this once it is ready?
@wuchong sure, the review work for json functions is ongoing, one by one.

**Comment by twalthr** [comment]
Finalized in #16776.

**Pull request closed without merging**
