### PR TITLE
[FLINK-9720] [Scheduler] Add ResourceAttribute and MesosResourceAttribute.

### PR DESCRIPTION
**Pull request by liurenjie1024**
## What is the purpose of the change

*This pull request is one of PRs for adding tag support to flink scheduler. *

## Brief change log

  - *Add ResourceAttribute interface.*
  - *Add MesosResourceAttribute class.*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by liurenjie1024** [comment]
@tillrohrmann Can you help to review this?

**Comment by tillrohrmann** [comment]
Hi @liurenjie1024, thanks for opening this PR. The Flink community is currently preparing the Flink 1.6 release and, thus, it might take a bit longer for the review to happen. Please bear with us until then.

**Comment by liurenjie1024** [comment]
Hi @tillrohrmann Flink 1.6 has released, could you please help to review this?

**Comment by tillrohrmann** [comment]
Closing for inactivity.

**Pull request closed without merging**
