### PR TITLE
modify the number of parameters

### PR DESCRIPTION
**Pull request by zeliu**
The number of arguments is 4, not 5

--input-topic <topic> 
--output-topic <topic>
--bootstrap.servers <kafka brokers>
--group.id <some id>

### CODE REVIEW

**Comment by MartijnVisser** [comment]
@zeliu Thanks for opening the ticket and the PR, but this seems incorrect. The number of arguments is indeed 4, but the code is checking if the number of provided arguments is less than 5. Since 4 is less than 5, the code is indeed working as intended.

**Comment by zeliu** [comment]
@MartijnVisser  Thanks for your reply, but if the number of arguments less than 5, it will throw exceptions.
In org.apache.flink.streaming.kafka.test.KafkaExample ,I provided 4 parameters, and it will report an  #error.
```
  if (parameterTool.getNumberOfParameters() < 5) {
            System.out.println(
                    "Missing parameters!\n"
                            + "Usage: Kafka --input-topic <topic> --output-topic <topic> "
                            + "--bootstrap.servers <kafka brokers> "
                            + "--group.id <some id>");
            throw new Exception(
                    "Missing parameters!\n"
                            + "Usage: Kafka --input-topic <topic> --output-topic <topic> "
                            + "--bootstrap.servers <kafka brokers> "
                            + "--group.id <some id>");
        }

```

**Comment by MartijnVisser** [comment]
> In org.apache.flink.streaming.kafka.test.KafkaExample ,I provided 4 parameters

Please explain exactly how you've done this.

**Comment by zeliu** [comment]
@MartijnVisser  
 **I can only provide a screenshot of IDE. I provided 4 parameters, but it reported an error**


image

**Pull request closed without merging**
