### PR TITLE
[FLINK-7301] [docs] Rework state documentation

### PR DESCRIPTION
**Pull request by twalthr**
## What is the purpose of the change

*This PR restructures state related documentation pages. It introduces some state introduction page and moves some files (from `setup/` to `ops/`) according to the new documentation structure.*

## Brief change log

*Documentation changes only.*

## Verifying this change

*Built with built script and links checked.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by twalthr** [comment]
CC @alpinegizmo

**Comment by twalthr** [comment]
@alpinegizmo I thought about adding redirects, but we would be in redirect hell if we would add every single page in the future. Actually, only links to the master docs change and we should not use links to master docs in trainings/stackoverflow anyway. Proper links to released docs remain unchanged.

**Comment by alpinegizmo** [comment]
@twalthr Duh, of course, you're right. 

+1

**Comment by twalthr** [comment]
Thanks @alpinegizmo. I will merge this now.

**Pull request closed without merging**
