### PR TITLE
[FLINK-21640]Job fails to be submitted in tenant scenario

### PR DESCRIPTION
**Pull request by cuibo01**
Modify the "high-availability.zookeeper.path.root" permissions.

### CODE REVIEW

**Comment by cuibo01** [comment]
in my pc， they were successful
image

**Comment by cuibo01** [comment]
@tillrohrmann @wangyang0918 can u review and merge the PR? thx

**Comment by cuibo01** [comment]
@zentol can u review and merge the PR? thx

**Comment by xintongsong** [comment]
As discussed in the JIRA ticket, we decided not to apply the changes.

**Pull request closed without merging**
