### PR TITLE
[FLINK-15670][API] Provide a Kafka Source/Sink pair as KafkaShuffle

### PR DESCRIPTION
**Pull request by curcur**
## What is the purpose of the change

This pull request is to provide a Kafka Source/Sink pair to simulate a KafkaShuffle that can:
1. Read topics that are already partitioned by key and process them without partitioning them again (avoid shuffles); and
2. Use this to decompose the job into smaller jobs and independent pipelined regions that failover independently.

## Brief Change Log
  - Extend Datastream API to allow user-defined SinkFunction to manipulate watermark
  - Kafka Shuffle Producer change
    - Write timestamp and watermark information together with a record in Kafka
    - Use `KeyGroupRangeAssignment` to assign records to different Kafka partitions
  - Kafka Shuffle Consumer change, Kafka Fechter Change
    - Each consumer read partitions equal to the key group indices that it got assigned. For now, the number of partitions is enforced to equal to the number of consumer parallelism.
    - KafkaShuffleFechter encapsulates the logic of record emitting and watermark emitting. 

## Verifying this change
This change added tests:
1. End-2-end tests
2. partition assignment tests

Some other tests are missing:
1. Specific watermark tests
2. failover tests

## Does this pull request potentially affect one of the following parts:
  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes)
  - The serializers: (don't know)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (JavaDocs)

### CODE REVIEW

**Comment by curcur** [comment]
Please refer to 

PR https://github.com/apache/flink/pull/11725 

for details.

The PR is reverted because of conflicts with 
[FLINK-17659] Rework WatermarkStrategy, add Suppliers for TimestampAssigner/WatermarkGenerator

committed last night.

**Comment by curcur** [comment]
local azure is running here:

https://dev.azure.com/mymeiyuan/Flink/_build/results?buildId=15&view=logs&j=1f3ed471-1849-5d3c-a34c-19792af4ad16

**Comment by curcur** [comment]
@pnowojski 

The local azure is green now.

https://dev.azure.com/mymeiyuan/Flink/_build/results?buildId=15&view=results

**Comment by pnowojski** [comment]
Thanks @curcur , merging :)

**Comment by curcur** [comment]
Thanks @pnowojski !

**Pull request merged**
