### PR TITLE
[FLINK-6288] fix FlinkKafkaProducer's custom Partitioner is always invoked with number of partitions of default topic

### PR DESCRIPTION
**Pull request by zjureel**
…voked with number of partitions of default topic

Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [ ] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [ ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by zjureel** [comment]
@tzulitai I created the new PR here for issue 6288. As discussed in [https://github.com/apache/flink/pull/3766](url), there are two ways to control timeout of fetching kafka meta

1. Depend on the timeout mechanism of kafka. When fetching partition meta from kafka, some timeout configurations should be setted.
2. Using `Future` to get the partiton meta of kafka, and user can set the timeout with configuration.

In the new api, meta of kafka may be feched before data is sended, and some exceptions such as network or disk problem may still block data send even that user set the request timeout of kafka. So in the PR, I use Future to control the timeout of fetching kafka meta.

The problem may not be so complicated, and we can use the timeout mechanism of kafka directly. What do you think of it? Thanks.

**Comment by tzulitai** [comment]
@zjureel my main concern is the need of our own timeout when Kafka has the `max.block.ms` configuration. This seems to be the max timeout you're talking about?

**Comment by zjureel** [comment]
Yes, user can config the timeout and retry times to fetch kafka meta beyond the configuration of kafka itself.  @tzulitai

**Comment by tzulitai** [comment]
@zjureel then I would suggest to remove the usage of ExecutorService for the timeout. In what other cases would that be required?

**Comment by zjureel** [comment]
@tzulitai I agree with you and `ExecutorService` is really unnecessary. I will update the code and remove `ExecutorService`

**Comment by tzulitai** [comment]
This looks good! I'll do some final tweaks to the styling of the code and then merge this :)

**Comment by tzulitai** [comment]
@zjureel I'll be merging this only for 1.4-SNAPSHOT. The main reason is that there is a lot of deprecation / API change with this, and I'll like to ship it along with other API changes we had in mind to make sure they go nicely together.

This is of highest priority for at the moment, and I'll make sure it gets into 1.4-SNAPSHOT as soon as possible.

@gyfora I understand that this was sort of a blocker for you, but I would prefer to not rush the changes into the release. I hope you can understand.

**Comment by gyfora** [comment]
Well, I can understand it but will mean that we have to keep running with a custom build because there is no way to work around this nicely.

**Comment by gyfora** [comment]
On the other hand this is potentially causing major data skew or errors for any people who are using the dynamic topics (they might not even be aware of it).

**Comment by tzulitai** [comment]
I think you've made a good point Gyula.
Alright, let me try to stretch a bit and merge this for 1.3.0 also.

**Comment by gyfora** [comment]
Thanks @tzulitai I don't feel very strongly about either way, I am just concerned for other users. I leave this decision to you I know you are already flooded with other stuff around the release.

**Comment by tzulitai** [comment]
I'm currently waiting for a Travis run locally for https://github.com/tzulitai/flink/tree/FLINK-6288.
That branch also includes more tests and tweak cleanups for the feature.

Once it gives green, will merge to `master` and `release-1.3.0`.

**Comment by zjureel** [comment]
@gyfora Thanks for you suggestion, and I agree with you that problems which cause errors to users should be addressed at a higher priority level. 

Thank you for merging this issues :) @tzulitai

**Pull request closed without merging**
