### PR TITLE
[FLINK-1472] Fixed Web frontend config overview with wrong value.

### PR DESCRIPTION
**Pull request by qmlmoon**

### CODE REVIEW

**Comment by StephanEwen** [comment]
I like the idea - that means that the webfrontend now shows what values are actually used, even if they are not in the config.

To make it even nicer, it would be cool to:
  - Show which values come from the config (top) and show for which ones what default is used (in a second section below)
  - add a Unit test that checks that all keys from the `ConfigConstants` are converted. I think it is easy to check this via enumerating all fields in the class using reflection.

**Comment by qmlmoon** [comment]
The configuration view is separated into user and default now:
qq20150308-1

**Comment by StephanEwen** [comment]
Nice, looks good to me.

+1 to merge

**Comment by rmetzger** [comment]
According to travis, the code doesn't seem to build.

**Comment by qmlmoon** [comment]
The default key value pairs are added manually. It seems that some of the keys in `ConfigConstant` is deleted recently.

**Comment by aljoscha** [comment]
Hi,
sorry for the long wait on this. I really like the feature but the implementation is not scalable: If new config values are added this needs to be updated in several places now.

Could you change ConfigConstants and add a static initializer block that builds the hash maps that you manually build in DefaultConfigKeyValues using reflection. The code would just need to loop through all fields that have _KEY at the end, and then find the matching default value without the _KEY at the end. From the default value field the type of the value can be determined and it can be added to the appropriate hash map. This way, the defaults will always stay up to date with the actual config constants.

**Comment by qmlmoon** [comment]
That would be a nice way, but
1) key/value pairs are not always distinguished by _KEY suffix, we have to format all the fields in ConfigConstants
2) some values are not in the ConfigConstants. e.g task manager slot = 1, akka_startup_time=aka_ask_timeout

In summary, we need a formatted one-to-one map of the key/value pairs in ConfigConstants

**Comment by aljoscha** [comment]
But then I think the solution is to normalise the constants in ConfigConstants.

**Comment by StephanEwen** [comment]
I agree to enforce normalization in the `ConfigConstants`, by adding a test case that reflectively gets all fields and checks whether they start with "DEFAULT_" or end in "_KEY".

The mapping between keys/values will probably have to be done manually, unless we add annotations above the key fields declaring what the default value is.

The type of the default value should help to figure out what "get" method to use. (getInteger, getDouble) in order to get the correct conversion method.

**Comment by aljoscha** [comment]
Yes, but then we should change this now and not build more code on top of this that can fail in the future if someone forgets to add the names to the correct hash set in some other class.

**Comment by aljoscha** [comment]
I added a Jira for this: https://issues.apache.org/jira/browse/FLINK-1936

**Comment by fhueske** [comment]
@qmlmoon We merged a new web dashboard a few days ago which makes this PR obsolete. Sorry for not merging it earlier. Could you close this PR please?
Thank you

**Comment by sachingoel0101** [comment]
@fhueske This issue is present in the new frontend also. See the attached screenshot:
capture

We should probably continue in another PR though.

**Comment by fhueske** [comment]
Yes, this should be addressed through a new PR.
The JIRA issue FLINK-1472 is still open.

**Pull request closed without merging**
