### PR TITLE
[FLINK-4843] Test for FsCheckpointStateOutputStream::getPos()

### PR DESCRIPTION
**Pull request by StefanRRichter**
This PR Introduces a test to check FsCheckpointStateOutputStream::getPos().

### CODE REVIEW

**Comment by StephanEwen** [comment]
Thanks for adding this test. I think it would be good to extend it to cases where `write(byte[])` is called as well. I would also use some more "odd" numbers for buffer size, so make sure there is no case where it works if the "in mem threshold" is a multiple of the buffer size. For example, user `17` as buffer size and `31` as memory-threshold.

**Comment by StefanRRichter** [comment]
Thanks for the review! I improved the test as suggested.

**Comment by StephanEwen** [comment]
Thanks for the update, looks good!

+1 to merge this

**Comment by uce** [comment]
Merging

**Pull request closed without merging**
