### PR TITLE
[FLINK-30948][Formats/AWS] Remove GlueSchemaRegistry Avro and JSON fo…

### PR DESCRIPTION
**Pull request by hlteoh37**
…rmats from main repository

## What is the purpose of the change
Externalize the GlueSchemaRegistry Avro and JSON formats to flink-connectors-aws

## Brief change log
- Removed flink-avro-glue-schema-registry
- Remove flink-json-glue-schema-registry
- Removed associated EndToEnd tests

## Verifying this change
This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes
  - The serializers: yes
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Review by MartijnVisser — CHANGES_REQUESTED** [review]
@hlteoh37 In some of the pipeline YAML files there are still occurrences to Glue, like:

`SECRET_GLUE_SCHEMA_ACCESS_KEY`
`SECRET_GLUE_SCHEMA_SECRET_KEY`
`IT_CASE_GLUE_SCHEMA_ACCESS_KEY`
`IT_CASE_GLUE_SCHEMA_SECRET_KEY`

I think these should also be removed, they were introduced as part of [FLINK-19667] Add AWS Glue Schema Registry integration (#14737)

**Comment by hlteoh37** [comment]
Good catch, removed those, and also found some additional suppressions we needed to remove.

**Review by Samrat002 — APPROVED** [review]
LGTM 🚀

**Review by MartijnVisser — APPROVED** [review]
LGTM

**Pull request merged**
