### PR TITLE
[FLINK-35825][hive] HiveTableSource supports report statistics for text file

### PR DESCRIPTION
**Pull request by reswqa**
## What is the purpose of the change

*HiveTableSource supports report statistics for text file*

(NB. Most of the authorship belongs to @WencongLiu)

## Brief change log

  - *Introduce a `TextFormatStatisticsReportUtil` to estimate statistics for text fie.*

## Verifying this change

covered by ut.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by reswqa** [comment]
@flinkbot run azure

**Review by xuyangzhong — COMMENTED** [review]
Thanks for this contribution. LGTM overall. I left some comments. PTAL.

**Comment by reswqa** [comment]
Thanks @xuyangzhong for the review, updated.

**Review by xuyangzhong — APPROVED** [review]
Thanks for the update. +1

**Comment by reswqa** [comment]
Thanks for the review, rebased the latest master. I will merge this after CI green.

**Pull request merged**
