### PR TITLE
[FLINK-11366][tests] Port TaskManagerMetricsTest to new code base

### PR DESCRIPTION
**Pull request by Myasuka**
## What is the purpose of the change
Port `TaskManagerMetricsTest` to new code base.

## Brief change log

  - Move `TaskManagerMetricsTest`'s test to `TaskExecutorTest#testHeartbeatTimeoutWithResourceManager`

## Verifying this change
This change added tests and can be verified as follows:

  - Verify taskmanager's metrics registry was not shutdown due to the disconnect to RM

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by Myasuka** [comment]
I close-reopen this PR to rebuild checks for unexpected ITcase broken ( refer to [FLINK-9920](https://issues.apache.org/jira/browse/FLINK-9920)).

CC @tillrohrmann would you please take a look at this PR?

**Comment by GJL** [comment]
I think it is better to delete the original test:

- `TaskManagerMetricsTest` was asserting that the MetricRegistry is not closed
when a TaskManager reconnected to the JobManager. However, in the new code,
the Taskmanager (TaskExecutor) does not have a direct reference to the
MetricRegistry anymore. The responsibility of closing the MetricRegistry is
now in the TaskManagerRunner. 

- Resource cleanup happens in `TaskExecutor#postStop()`, not on
disconnect/reconnect.

- The TaskManager now connects to more than one instance, i.e.,
ResourceManager and JobManager. However, your ported test, only tests the
behavior for ResourceManager reconnects.

- Lastly, you are piggybacking on `testHeartbeatTimeoutWithResourceManager`
which is not good practice because every test should only test one
aspect/concept.

I will revert your changes in `testHeartbeatTimeoutWithResourceManager`. Let
me know if you think otherwise.

**Comment by Myasuka** [comment]
@GJL Thanks for your clarification.
The only thing I feel a bit confused is that, please correct me if I am wrong, `MetricRegistry` shut down when `TaskManagerRunner` called `closeAsync()` not during resource cleanup during `TaskExecutor#postStop()`.

On the whole, I think your advise sounds more reasonable.

**Comment by GJL** [comment]
@Myasuka You are correct.

**Comment by GJL** [comment]
Merging without changes in `TaskExecutorTest.java`...

**Pull request closed without merging**
