### PR TITLE
[FLINK-21358][docs] Adds savepoint 1.12.x to savepoint compatibility diagram

### PR DESCRIPTION
**Pull request by XComp**
## What is the purpose of the change

I assumed that there are no changes that would be break the compatibility for `1.12.x`

## Brief change log

* added new row and column for 1.12.x to the English and Chinese version

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? no

### CODE REVIEW

**Comment by tillrohrmann** [comment]
cc @rmetzger and @dianfu. Do you remember any backwards compatibility breaking changes in the 1.12 release?

**Comment by dianfu** [comment]
@tillrohrmann @XComp Sorry for the late response. There are no known backwards compatibility issues in my head.

**Comment by XComp** [comment]
@dianfu would you be so kind and take over the merging of the PR then?

**Review by dianfu — APPROVED** [review]
Sure, the PR LGTM. Merging...

**Pull request closed without merging**
