### PR TITLE
[FLINK-2312][utils] Randomly Splitting a Data Set according to weights given

### PR DESCRIPTION
**Pull request by sachingoel0101**
Adds a method for randomly splitting a data set.

However, there are a few problems. We're effectively creating several data sources from one, and each of these sources will act independently later on, and the execution will be kicked off for each one separately. This leads to the splitting happening several times, thus, what actually remains is several different random samples from data which aren't exhaustive. @pp86, do you have any idea how to deal with this?

### CODE REVIEW

**Comment by pp86** [comment]
Hi @sachingoel0101 ,

wouldn't it be better to implement the method for a generic DataSet rather than a DataSet of LabeledVector?

**Comment by tillrohrmann** [comment]
I agree, a generalized implementation would be favorable.

**Comment by sachingoel0101** [comment]
This leads to non-mutually exclusive splits. I tracked down the reason for this: The input data is parallelized differently while performing the splits for every fraction. This leads to an altogether different sequence of random numbers, hence the problem. 
@tillrohrmann, I use a seed value to initialize, as in the cross-validation PR. Is there any way I can fix the parallelization of data, so running the split for every fraction leads to exactly same sequence of numbers. Persist would write the data to disk, which is something of an overhead isn't it?

**Comment by sachingoel0101** [comment]
Right now, there is no way to achieve this. After support for persisted results is added, this can be re-visited again. Closing for now.

**Pull request closed without merging**
