### PR TITLE
[FLINK-20946][python] Optimize Python ValueState Implementation In PyFlink

### PR DESCRIPTION
**Pull request by HuangXingBo**
## What is the purpose of the change

*This pull request will Optimize Python ValueState Implementation In PyFlink*

## Brief change log

  - *Optimize Python ValueState Implementation In PyFlink*

## Verifying this change

This change added tests and can be verified as follows:

  - *Original Tests*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by WeiZhong94** [comment]
@HuangXingBo Thanks for your PR! 

I think we can do better in this PR, e.g. improve the logic of SynchronousValueRuntimeState. Now the update operation of SynchronousValueRuntimeState will cause 2 network requests, we can optimize it to 1.

**Comment by HuangXingBo** [comment]
@WeiZhong94 Thanks a lot for the suggestion. I have updated the PR at the latest commit.

**Review by WeiZhong94 — APPROVED** [review]
LGTM, +1 to merge.

**Review by dianfu — APPROVED** [review]
LGTM.

**Pull request closed without merging**
