### PR TITLE
[FLINK-28395][Connectors/ElasticSearch] create table and await for su…

### PR DESCRIPTION
**Pull request by dingweiqings**
## What is the purpose of the change

 Fix test case error  about create table/query document in elasticsearch 6  

## Brief change log
1. add await api on creating table , make sure create table happen before querying document 

## Verifying this change
I have run test case several times and get passed result

*(Please pick either of the following options)*

none

## Does this pull request potentially affect one of the following parts:

none

## Documentation

none

### CODE REVIEW

**Comment by dingweiqings** [comment]
@HuangXingBo I open a new branch

**Comment by dingweiqings** [comment]
Replaced by#20318  which is already merged ,so close  this pr.

**Comment by MartijnVisser** [comment]
Needs to be moved to https://github.com/apache/flink-connector-elasticsearch

**Comment by dingweiqings** [comment]
> Needs to be moved to https://github.com/apache/flink-connector-elasticsearch

Of course

**Pull request closed without merging**
