### PR TITLE
[FLINK-5414] [table] Bump up Calcite version to 1.11

### PR DESCRIPTION
**Pull request by haohui**
This PR resembles #3338 except that it canonizes the nullable types.

@wuchong can you please take a look?

### CODE REVIEW

**Comment by wuchong** [comment]
Hi @haohui , the code looks very good to me. Thanks for investigating this, waiting for the CI pass.

@twalthr , I think you would like to have a look.

**Comment by twalthr** [comment]
Thanks @wuchong and @haohui. I will look at it today.

**Comment by twalthr** [comment]
@haohui your build is failing. Can you have a look at it again?

**Comment by haohui** [comment]
Sorry stuck with something. Will update the PR in a day or two.

**Comment by haohui** [comment]
Fix the unit tests.

There are two additional changes:

1. There are precision differences when converting `double` to `BigDecimal`. Fix the unit tests.
2. When registering UDFs Flink needs to distinguish nullable and non-nullable types. Patched `UserDefinedFunctionUtils`. We need a solution like FLINK-5177 to handle these cases systematically.

**Comment by haohui** [comment]
@twalthr can you please take another look? Thanks.

**Comment by twalthr** [comment]
Thanks for the update @haohui. I fixed the decimal issues by applying changes from @wuchong's PR. I think for now we should not do the primitive checking for scalar functions, this should be part of FLINK-5177. I will merge this now. But we should definitely solve FLINK-5177 soon. I will assign it to me.

**Pull request closed without merging**
