### PR TITLE
[FLINK-21986][State Backends] fix native memory used by RocksDB not be released timely after job restart

### PR DESCRIPTION
**Pull request by zoltar9264**
fix native memory used by RocksDB not be released timely after job restart

## What is the purpose of the change

This pull request fix the problem described in [FLINK-21986](https://issues.apache.org/jira/browse/FLINK-21986). 

Concisely, *RocksDBOperationUtils#addColumnFamilyOptionsToCloseLater()* invoke *ColumnFamilyHandle#getDescriptor()* twice just for get ColumnFamilyOptions used by ColumnFamilyHandle. Every invocation create a new ColumnFamilyOptions instance, but only one added to "to close later list". 
That resulted in some ColumnFamilyOptions was not closed and task manager native memory used by RocksDB can't be released timely. This situation often leads to task manager OOM killed by container manager such as Yarn and Kubernetes.

## Brief change log

  - *RocksDBOperationUtils#addColumnFamilyOptionsToCloseLater()* only invoke *ColumnFamilyHandle#getDescriptor()* once to get ColumnFamilyOptions instance.

## Verifying this change

This change can be verified as follows:

  - Run a test job use RocksDBStateBackend and store a mass of state data (such as regular join job [flink-21986-regular-join-test-case](https://github.com/zoltar9264/flink-21986-regular-join-test-case/blob/master/src/main/java/top/zoltar/flink/issue/StreamingJob.java) )
  - Manually trigger restart (such as kill a task manager manually) and verifying that other task manager process RSS memory decrease after restart. As shown in the picture below :

image

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by zoltar9264** [comment]
@flinkbot run travis
@flinkbot run azure

**Comment by zoltar9264** [comment]
@flinkbot run azure

**Comment by zoltar9264** [comment]
@flinkbot run azure

**Review by tillrohrmann — APPROVED** [review]
Thanks for creating this fix @zoltar9264. The change looks good to me. I think this is a good improvement. The failing test seems to be unrelated. Merging this PR now.

**Pull request closed without merging**
