### PR TITLE
[FLINK-5407] Fix savepoints for iterative jobs

### PR DESCRIPTION
**Pull request by StefanRRichter**
This PR fixes savepoints for iterative jobs. Savepoints failed with NPE because the code assumed that operators in an operator chain are never null. For iterative jobs, this can happen.

### CODE REVIEW

**Comment by StefanRRichter** [comment]
cc @aljoscha

**Comment by aljoscha** [comment]
Changes look very good! I fixed the formatting of the newly added methods in `TestingCluster` to conform to Scala coding guidelines.

I rebased on master, will wait for Travis to give the green light and then merge.

**Comment by aljoscha** [comment]
Merged, could you please close this PR?

**Comment by StefanRRichter** [comment]
Thanks for reviewing and merging @aljoscha !

**Comment by senorcarbone** [comment]
Hey! In this upcoming [PR ](https://github.com/apache/flink/pull/1668) there is a custom operator responsible for the logging at the iteration head. Hope this does not break your tests in case they assume a null op.
Also, in case any of you is familiar with asynchronous checkpoints with ListState, could you check my last question in the same PR? thanks :)

**Pull request closed without merging**
