### PR TITLE
[FLINK-29201][docs] Add setting up of maven-wrapper

### PR DESCRIPTION
**Pull request by snuyanzin**
## What is the purpose of the change
The PR adds information about setting up of maven-wrapper
Otherwise (in case there is a much higher version than recommended) it could lead to non-compilable within IDE flink-connector-hive and flink-sql-client modules
Similar issue during compile/build from command line was mentioned at https://issues.apache.org/jira/browse/FLINK-27640

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.
## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: (no )
  - The runtime per-record code paths (performance sensitive): (no )
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no )

## Documentation

  - Does this pull request introduce a new feature? ( no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Review by XComp — CHANGES_REQUESTED** [review]
Thanks for contributing this change. I'm wondering whether we should also add this item to the Chinese version of the documentation. I guess, it's ok to copy over the English version into the Chinese documentation. We could create a follow-up Jira issue that covers the proper translation into Chinese (I guess, labeling the Jira issue using `starter` would be good). This follow-up Jira issue might need to include a general revision of the IDE Setup. [d188c2f](https://github.com/apache/flink/commit/d188c2fc7617dfcca2978e3bad34cb4e3085c3f9) update the English documentation as well without touching the Chinese version.

**Comment by snuyanzin** [comment]
Thanks for the feedback, yes I think you're right.
I've added English version to Chinese page and created a follow-up jira issue https://issues.apache.org/jira/browse/FLINK-29197

**Comment by XComp** [comment]
Thanks @snuyanzin . Could you also create the follow-up ticket (or check whether there is something like that already) in Jira?

**Comment by snuyanzin** [comment]
I've created a follow-up tasks for that https://issues.apache.org/jira/browse/FLINK-29201

**Comment by snuyanzin** [comment]
closed in favor of https://github.com/apache/flink/pull/19782

**Pull request closed without merging**
