### PR TITLE
[FLINK-6176] [scripts] Add JARs to CLASSPATH deterministically

### PR DESCRIPTION
**Pull request by greghogan**
Sorts files read from Flink's lib directory and places the distribution JAR to the end of the CLASSPATH.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Looks like a good change. Do we want the same deterministic class path order also when launching Yarn and Mesos containers?

/cc @rmetzger @EronWright

**Comment by greghogan** [comment]
@StephanEwen will look at refactoring this.

**Comment by EronWright** [comment]
With respect to making this change for Mesos, look to `mesos-appmaster.sh` and `mesos-taskmanager.sh` which produce the classpath.  Those scripts do import `config.sh` but don't use `constructFlinkClassPath` at the moment, related to inclusion of the Hadoop classpath I believe.  But there's potential for unification.

Note that the `lib` directory is scanned recursively; please verify the behavior in that regard.

Overall this change seems like a hack attempting to mask a true conflict (reportedly between the Flink and kinesis connector libs).   Seems to me that if ordering matters (and i hope it doesn't), placing Flink last would tend to destabilize the system.

**Comment by greghogan** [comment]
@EronWright this will not fix conflicts but will make debugging easier since the classpath will be consistent across filesystems and Flink installations. We currently have no order to the classpath.

**Comment by EronWright** [comment]
I believe the `yarn-session.sh` applies to the client-side only (which launches the AM into the cluster).   To adjust the classpath for the AM/TM, I believe some adjust is needed here:

https://github.com/apache/flink/blob/release-1.2/flink-yarn/src/main/java/org/apache/flink/yarn/AbstractYarnClusterDescriptor.java#L644

**Comment by greghogan** [comment]
Updated for YARN @StephanEwen @EronWright

**Comment by StephanEwen** [comment]
Changes look good to me. Merging this...

**Pull request closed without merging**
