### PR TITLE
[FLINK-7428][network] avoid buffer copies when receiving messages

### PR DESCRIPTION
**Pull request by NicoK**
## What is the purpose of the change

The `LengthFieldBasedFrameDecoder` used so far creates one additional copy in its `#extractFrame()` method which is avoidable in our use case and changed by this PR (based upon #4528).

## Brief change log

- let `NettyMessageDecoder` inherit from `LengthFieldBasedFrameDecoder` (instead of being an additional step in the pipeline)
- override `LengthFieldBasedFrameDecoder#extractFrame()` similarly to the `ObjectDecoder` class provided by netty itself

## Verifying this change

This change is already covered by existing tests, such as NettyMessageSerializationTest as well as many other tests involving network communication, e.g. IT cases.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (yes: network "deserialisation")
  - The runtime per-record code paths (performance sensitive): (yes)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes: network communication)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (JavaDocs)

### CODE REVIEW

**Comment by NicoK** [comment]
FYI:
- newer netty 4.0.xx versions also use `buffer.slice(index, length)` inside their `extractFrame()` method (see https://github.com/netty/netty/commit/891be30a28c6dc5a1edf1cb5a3690644cf4ff66e) and despite the comment on `extractFrame()`, this is also safe when used outside the `decode()` method as long as the buffer is retained (and then released later). By letting `NettyMessageDecoder` inherit from `LengthFieldBasedFrameDecoder` though, we also gain a smaller channel handler pipeline.
- netty 4.1 offers an even improved `buffer.retainedSlice(index, length)` implementation (see https://github.com/netty/netty/commit/3a9f47216143082bdfba62e8940160856767d672) but we can't go that way yet due to our netty-router dependency

**Comment by NicoK** [comment]
we also need to double-check this against the previous issue of d92e422ec7089376583a8f57043274d236c340a4 which may be solved by the way I am using the `LengthFieldBasedFrameDecoder` now compared to back then, or the changes that happened since then

**Comment by greghogan** [comment]
@NicoK what do you think of creating a parent issue for your collection of network improvements?

**Comment by NicoK** [comment]
Thanks, @greghogan - I put most of them under FLINK-7315 now (at least the ones which are loosely related).

Regarding the PR itself, I still need to investigate whether the previous issues went away.

**Comment by KurtYoung** [comment]
If I remember correctly, the reason we chose to do an extra copy inside `extractFrame` is that we faced some memory problem when using `slice`. Is this no longer an issue or have taken care by another PR?

**Comment by zentol** [comment]
@KurtYoung I think https://github.com/apache/flink/pull/4529#issuecomment-321851427 addresses that.

**Comment by KurtYoung** [comment]
@zentol So the rationale behind this is when all netty's memory comes from flink's managed memory, then this is not an issue, right?

**Comment by NicoK** [comment]
I haven't had time to test this yet - I doubt that this is simply solved by using our memory segments but I need to understand the problem better.

Maybe this also goes away with [flow control](https://issues.apache.org/jira/browse/FLINK-7282) being added since then we have more control over what the sender sends and can make sure that we have enough buffers to process its data.

**Comment by zhijiangW** [comment]
Hey @NicoK , would this PR be covered in FLINK-1.5? We experienced the netty direct memory out of memory sometimes in production cased by `extractFrame`, so we expect this improvement. :)

**Comment by NicoK** [comment]
With the recent update of the netty version in flink-shaded (see https://github.com/apache/flink-shaded/commit/1233f1bb0e2b9fafa4260603aa130b7eb9995a7a), most of this PR is indirectly included. However, I probably need to fall back to the original code creating a copy at least for the fallback non-credit based paths due to the original problem.

Additionally, since the introduction of the credit-based flow control we should not use too much memory on the receiver side anymore: memory size in the range of once in our buffers, at most one (or two depending on the above) more copies in netty temporarily.

Ultimately, we could go one step further of decoding directly to our buffers here, but that is not covered by this PR and will only work with credit-based flow control.

**Comment by NicoK** [comment]
@zhijiangW looks like we're not upgrading the netty version in Flink 1.5 at this stage due to the timing, i.e. too quite late in the development cycle. We will do the upgrade after releasing Flink 1.5 so that we have enough time to test it.

If you want to try out whether an upgrade changes anything for you, please feel free to pull from #5571 and upgrade `flink-shaded-netty` in the root `pom.xml` to `4.0.56.Final-3.0` once [flink-shaded](https://github.com/apache/flink-shaded) 3.0 is released.

**Comment by zhijiangW** [comment]
Thanks for telling me the plan of it. I will do that if necessary. :)

**Comment by NicoK** [comment]
let me close this PR since this will be done by upgrading netty instead

**Pull request closed without merging**
