### PR TITLE
[BP-1.18][FLINK-35750][runtime/metrics] Fix that the latency marker metrics aren't updated after failover.

### PR DESCRIPTION
**Pull request by RocMarshal**
(cherry picked from commit 615d19735b0691b57262a110e6078c3488349f5a)

## What is the purpose of the change

BP for 1.18 of https://github.com/apache/flink/pull/25021

### CODE REVIEW

**Comment by RocMarshal** [comment]
@flinkbot run azure

**Comment by RocMarshal** [comment]
@flinkbot run azure

**Review by 1996fanrui — APPROVED** [review]
LGTM

**Comment by 1996fanrui** [comment]
@flinkbot run azure

**Comment by 1996fanrui** [comment]
@RocMarshal please rebase the release-1.18 branch.

**Pull request merged**
