### PR TITLE
[FLINK-24433][Tests][Buildsystem] Remove additional pre-installed packages to clean up more diskspace

### PR DESCRIPTION
**Pull request by MartijnVisser**
## What is the purpose of the change

* This PR removes additionally pre-installed packages on the Azure VMs to clean-up more diskspace before starting the E2E tests

## Brief change log

* Remove installed packages

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Review by zentol — COMMENTED** [review]
I'm not necessarily against this change, but it does seem like we're just throwing stuff against the wall and hoping something sticks.

The previous change (4c138a440f8de315470a663fd751b7293ff3ceb8) should have no effect because the log files under src/test aren't used on CI; we use `tools/ci/log4j.properties` instead.
Which still logs at INFO, as it should as otherwise debugging is impossible (ideally we'd even be logging on DEBUG).
(So even if it had worked it's not really a sound change)

In https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=35664&view=results the issues looks more like an ES e2e test entering a failure loop. It's not surprising this can fill the disk, and it's unlikely we're gonna solve that by providing more disk space.
While the log files created by flink-dist are limited in size, testcontainers is also forwarding everything into the watchdog script, which _isn't_ limited.

I'd rather look into what the ES tests are up to.

**Comment by MartijnVisser** [comment]
> In https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=35664&view=results the issues looks more like an ES e2e test entering a failure loop. It's not surprising this can fill the disk, and it's unlikely we're gonna solve that by providing more disk space.

We thought so too, but the error message is shown immediately when this test is starting. The error message indicates that there isn't enough disk space and ES therefore going into read-only mode. So I'm suspecting it's something that starts before this test that uses more disk space. But that just takes a long time to debug due to the run times.

**Comment by zentol** [comment]
> So I'm suspecting it's something that starts before this test that uses more disk space. But that just takes a long time to debug due to the run times.

Have you considered copying/calling into the bash utils to log the environment info after each test?

> We thought so too, but the error message is shown immediately when this test is starting.

OK that's fair. `Elasticsearch6SinkE2ECase.testScaleDown` ran just fine though before the failing test.
Are we doing any cleanup in between individual test cases?
Since the next test (`testBasicSink`) indeed fails immediately does it mean we _right there_ crossed the disk space threshold? (that'd be quite the coincidence)

We know we had 2gb available when the test started, since testcontainers checks that:
`Docker environment should have more than 2GB free disk space`
What is the test using those for?

side-note: Is there a ticket for having the test only use a limited number of retries?

**Comment by MartijnVisser** [comment]
> Have you considered copying/calling into the bash utils to log the environment info after each test?

That already exists. There's usually around 20GB free when starting, see https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=35682&view=logs&j=bea52777-eaf8-5663-8482-18fbc3630e81&t=11b0df07-3e5e-58da-eb81-03003e470195&l=290 or https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=35664&view=logs&j=bea52777-eaf8-5663-8482-18fbc3630e81&t=11b0df07-3e5e-58da-eb81-03003e470195&l=290 as examples. 

When the Bash based tests end, it shows there is still around 12GB available. From a failed run:

```
2022-05-14T05:19:06.6557479Z May 14 05:19:06 Filesystem      Size  Used Avail Use% Mounted on
2022-05-14T05:19:06.6558259Z May 14 05:19:06 /dev/root        90G   78G   12G  88% /
```

> Are we doing any cleanup in between individual test cases?

I don't believe we are

> side-note: Is there a ticket for having the test only use a limited number of retries?

https://issues.apache.org/jira/browse/FLINK-27642

What I don't understand is why the `Elasticsearch6SinkE2ECase` is outputting so many log lines, compared to for example `SmokeKafkaITCase`. I've asked @alpreu if he can look into this.  Created https://issues.apache.org/jira/browse/FLINK-27649 for that.

Could we at least merge this band-aid, while fixing https://issues.apache.org/jira/browse/FLINK-27649 and https://issues.apache.org/jira/browse/FLINK-27642

**Comment by MartijnVisser** [comment]
Merging to at least mitigate https://issues.apache.org/jira/browse/FLINK-24433 while also waiting for https://github.com/apache/flink/pull/19735 as a permanent fix

**Comment by zentol** [comment]
> That already exists.

Not for the java tests though (which is the bit that would be relevant in this case).

**Pull request merged**
