### PR TITLE
[FLINK-19867][table-common] Validation fails for UDF that accepts var…

### PR DESCRIPTION
**Pull request by lirui-apache**
…-args

## What is the purpose of the change

Fix the failure to extract eval method for functions with var-arg parameter.

## Brief change log

  - Check var-arg parameter first in `ExtractionUtils.isInvokable`
  - Add test case

## Verifying this change

Added test case

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? no

### CODE REVIEW

**Comment by lirui-apache** [comment]
Hi @twalthr , could you please take a look at the proposed changes here? Thanks!

**Comment by twalthr** [comment]
Sure, will assign this to me.

**Review by twalthr — APPROVED** [review]
Thanks for the fix. The changes look good to me. I will merge this.

**Comment by lirui-apache** [comment]
Thanks Timo for the review

**Pull request closed without merging**
