### PR TITLE
[FLINK-5340] Document job uptime/downtime/restartTime/fullRestarts me…

### PR DESCRIPTION
**Pull request by zentol**
job_docs

### CODE REVIEW

**Comment by alpinegizmo** [comment]
"The time that the job has not been running in a failing/recovering situation." is confusing. How about this:

The time the job has spent in a failing/recovering situation.

**Comment by zentol** [comment]
@alpinegizmo That's better, but still a bit unambiguous. The `downtime` only measures since the last time the job went into a non-running state, whereas the description could mean "Total job downtime since job submission." :/

**Comment by alpinegizmo** [comment]
@zentol Ok, that's an important distinction, but now I see another ambiguity. Does one of these work?

  For jobs currently in a failing/recovering situation, the time elapsed during this outage.

  The time elapsed during the job's most recent failure.

If my job fails and isn't running for 5 minutes and then recovers, after recovery what does `downtime` report? 0, or 5 minutes?

**Comment by zentol** [comment]
After recovery it will report `0`. So `For jobs currently in a failing/recovering situation, the time elapsed during this outage.` would be accurate.

**Comment by zentol** [comment]
@alpinegizmo I've updated the wording.

**Comment by alpinegizmo** [comment]
Looks good to me.

**Comment by zentol** [comment]
merging.

**Pull request closed without merging**
