### PR TITLE
[FLINK-20144][docs] Change link format in docs/ops dir

### PR DESCRIPTION
**Pull request by Shawn-Hx**
## What is the purpose of the change

Change link format from:

`{{ site.baseurl }/... }`

to:

`{% link ... %}`

## Brief change log

Change all link format in `docs/ops` dir.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

Execute `./build_docs.sh` normally.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by Shawn-Hx** [comment]
@flinkbot run azure

**Comment by Shawn-Hx** [comment]
Hi, @sjwiesman 
Could you help to review at your convenience ?
Thanks.

**Comment by sjwiesman** [comment]
@Shawn-Hx Thank you for doing this! Can you please rebase your branch and resolve the conflict?

**Comment by Shawn-Hx** [comment]
@sjwiesman Thanks for reminder. Have resolved the conflict. PTAL.

**Comment by sjwiesman** [comment]
Grazi, merging . . .

**Pull request closed without merging**
