### PR TITLE
[hotfix] Fix CsvRowDataDeserializationSchema constructor

### PR DESCRIPTION
**Pull request by afedulov**
The `csvSchema` field was wrongly initialized.

### CODE REVIEW

**Review by wuchong — APPROVED** [review]
Thanks @afedulov , LGTM.

**Review by MartijnVisser — APPROVED** [review]
LGTM

**Comment by afedulov** [comment]
@MartijnVisser could you also merge?

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Comment by MartijnVisser** [comment]
The failing test is unrelated and tracked under https://issues.apache.org/jira/browse/FLINK-26882

**Comment by MartijnVisser** [comment]
@afedulov Will you also create the backport to `release-1.15` ?

**Comment by afedulov** [comment]
Thanks, @MartijnVisser .  Here is the backport PR https://github.com/apache/flink/pull/19288

**Pull request merged**
