### PR TITLE
[FLINK-6155] Introduce an endpoint id for RpcEndpoints

### PR DESCRIPTION
**Pull request by tillrohrmann**
An endpoint id allows to assign a unique name to a `RpcEndpoint`. This name can be used
to look up the rpc endpoint within the RpcService. In the case of the `AkkaRpcService` implementation, it corresponds to the actor name used for the `AkkaRpcActor`.

Remove component endpoint name methods from the `HighAvailabilityServices`.

### CODE REVIEW

**Comment by tillrohrmann** [comment]
Rebasing on the latest master.

**Comment by tillrohrmann** [comment]
Travis passed. Rebasing on the latest master. If travis passes again, then I will merge this PR.

**Comment by StephanEwen** [comment]
Good changes!

I think we could actually drop the explicit endpoint name from the `TaskExecutor` and always let it use a random name (as is the default when no explicit name is given). That would simplify the code a bit and it should work since the connection is always established by the `TaskExecutor` towards the `ResourceManager` and `JobManager`, but never the the other way around.

**Comment by tillrohrmann** [comment]
Thanks for the review @StephanEwen. You're right that it should not be necessary to assign a name to the `TaskExecutor` and the `ResourceManager`. Will change it so that these components assign a random name.

Will then rebase the PR and once Travis gives green light, I will merge it.

**Comment by tillrohrmann** [comment]
I think I have to correct myself. In the general case, there might be the need to connect from the dispatcher component to `ResourceManager`. If the `ResourceManager` runs in a different process in standalone mode, then we have to be able to configure a fixed endpoint name, I think.

**Comment by tillrohrmann** [comment]
Failing test case has just been fixed. Merging this PR.

**Pull request closed without merging**
