### PR TITLE
[hotfix][javadocs] Fix broken inline link

### PR DESCRIPTION
**Pull request by rovo98**
## What is the purpose of the change

To fix broken javadoc inline link.

## Brief change log

Fixed javadoc inline link

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by rovo98** [comment]
@flinkbot run azure

**Comment by rovo98** [comment]
@flinkbot run azure

**Review by Myasuka — CHANGES_REQUESTED** [review]
@rovo98 The CI failed due to spotless-check, you could check the problem in the CI results and update your PR then.

**Comment by rovo98** [comment]
Yes, I have seen the problem before. It seems the previous commit violates the code format, and I have updated (from 6d73e9b to ce116b0 ) the PR following the instruction given by CI results.  
(I have setup IDE according to https://ci.apache.org/projects/flink/flink-docs-master/docs/flinkdev/ide_setup/, already run mvn spotless:apply) 
What else should I do？Thanks for you review.

**Comment by Myasuka** [comment]
If you could run `mvn clean package` successfully localy, let's wait for the result of CI.

**Comment by rovo98** [comment]
@Myasuka Sorry for the delay reply. The CI result is success, Would you consider to help merging this PR ？ thanks.

**Review by Myasuka — APPROVED** [review]
Thanks for your reminder, LGTM

**Pull request merged**
