### PR TITLE
[FLINK-22483][runtime][coordination] Recover checkpoints when JobMaster gains leadership

### PR DESCRIPTION
**Pull request by edu05**
## What is the purpose of the change

Moves the synchronization of checkpoint pointers with in-memory state out of the `JobManager`'s (which would make it unresponsive to RPC for the duration of the sync)

## Brief change log

  - Deleted old place where checkpoint pointer sync was taking placed
  - Added checkpoint pointer sync immediately after checkpoint store creation
  - Refactored test to be a bit more meaningful

## Verifying this change

- Unit tests
- Ideally the creator of the JIRA ticket would verify if the PR fixes their issue

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: yes
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by edu05** [comment]
@flinkbot run azure

**Comment by edu05** [comment]
> ## CI report:
> 
>     * [b0cc015](https://github.com/apache/flink/commit/b0cc015e1658ffb88ef1dba003b3dc994446ab36) Azure: [PENDING](https://dev.azure.com/apache-flink/98463496-1af2-4620-8eab-a2ecc1a2e6fe/_build/results?buildId=20389)
> 
> 
> Bot commands
> The @flinkbot bot supports the following commands:
> 
>     * `@flinkbot run travis` re-run the last Travis build
> 
>     * `@flinkbot run azure` re-run the last Azure build

@flinkbot run azure

**Comment by edu05** [comment]
will re-open as azure is not rerunning

**Comment by dmvk** [comment]
Replaced by https://github.com/apache/flink/pull/16487

@edu05 For a future reference, there is no need to close & re-open the PR. It may take some time for CI to re-run as our current bot implementation periodically scans PRs for updates and the current interval is fairly large (due to github api rate limits). I'll think about how we can make things more convenient in the future.

**Comment by edu05** [comment]
> Replaced by #16487
> 
> @edu05 For a future reference, there is no need to close & re-open the PR. It may take some time for CI to re-run as our current bot implementation periodically scans PRs for updates and the current interval is fairly large (due to github api rate limits). I'll think about how we can make things more convenient in the future.

Thanks, I've just noticed that.

**Pull request closed without merging**
