### PR TITLE
[FLINK-21742][sql-client] Support REMOVE JAR statement in SQL Client

### PR DESCRIPTION
**Pull request by SteNicholas**
## What is the purpose of the change

*In the sql-client, users should submit statements for operation that remove jar as follows:*
```
Flink SQL> REMOVE JAR /local/test.jar;
[Info] The specified jar is removed from session classloader.
```
*`CliClient` should support `REMOVE JAR` syntax in SQL Client.*

## Brief change log

  - *Add `RemoveJarOperation` to support `REMOVE JAR` syntax for `CliClient`.*

## Verifying this change

  - *`CliClientITCase` adds `REMOVE JARS` cases for `testSqlStatements` to verify whether `CliClient` supports the `REMOVE JAR` syntax.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by wuchong** [comment]
I would prefer to review this PR after #16010 is merged. Then you can use `show jars` to verify `remove jar`.

**Comment by SteNicholas** [comment]
> I would prefer to review this PR after #16010 is merged. Then you can use `show jars` to verify `remove jar`.

Yes, I would like to use `show jars` to verify `remove jar` after the above PR is merged.

**Comment by SteNicholas** [comment]
@wuchong , I have rebased master branch and used `SHOW JARS` to verify the implementation for `REMOVE JAR`.

**Comment by wuchong** [comment]
Hi @SteNicholas , do you have time to update it?

**Comment by SteNicholas** [comment]
@wuchong , I have addressed your detailed comments and updated this pull request. Could you please help to review again? Sorry for later update.

**Review by wuchong — APPROVED** [review]
LGTM.

**Pull request merged**
