### PR TITLE
[FLINK-18958] Lose column comment when create table

### PR DESCRIPTION
**Pull request by oikomi**
**What is the purpose of the change**
add colum comment  when users use describe instruction .

**Verifying this change**
Tested manually on a local cluster.

UT case see  BatchTableEnvironmentTest.testExecuteSqlWithDescribeForComment  and BatchTableEnvironmentTest.testExecuteSqlWithDescribe

also I have test in my production env as follow.

image

### CODE REVIEW

**Comment by fsk119** [comment]
@oikomi Thanks for your contribution. But could you offer some test cases to verify your work? I think you should offer tests that when users use describe instruction, they can also have information about column comments.  You can take a look at org.apache.flink.table.api.batch.BatchTableEnviromentTest#testExecuteSqlWithDescribe as an example.

**Comment by oikomi** [comment]
hi  @fsk119  I have commited  a UT for colum comment and I have found a bug when not use blink planner, thank you very much!

**Comment by oikomi** [comment]
@flinkbot run azure

**Comment by lsyldliu** [comment]
@wuchong can you help review this pr when you are free？

**Comment by oikomi** [comment]
@flinkbot run travis
@flinkbot run azure

**Comment by oikomi** [comment]
@flinkbot run azure

**Comment by wuchong** [comment]
Thanks for the contribution @oikomi , after going through it roughly, I have some concern that we are making the `TableSchema` fatter and fatter. The community had some discussion to introduce a `CatalogTableSchema` to preserve the metadata information of catalog table and keep TableSchema clean to describe a schema (see FLINK-17793). 

So I'm hesitated whether we should wait for FLINK-17793 or update `TableSchema` further.

**Comment by oikomi** [comment]
@wuchong  OK , let's wait for FLINK-17793 .

**Pull request closed without merging**
