### PR TITLE
[FLINK-5985] [Backport for 1.2] Report no task states for stateless tasks on checkpointing

### PR DESCRIPTION
**Pull request by StefanRRichter**
This PR is a backport of #3523 to Flink 1.2.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Good fix!

I think that verifying the possibility to reconfigure a job with respect to stateless operators warrants an ITCase. Can we extend the `SavepointITCase` for that?

**Comment by StephanEwen** [comment]
Looks good.

+1 for merging this!

**Comment by uce** [comment]
Could you merge this @StefanRRichter? I think it is one of the last blockers for 1.2.1 and it's a pretty critical issue...

**Comment by StefanRRichter** [comment]
Yes, will do today.

**Comment by StefanRRichter** [comment]
Merging this.

**Pull request merged**
