### PR TITLE
[FLINK-10426] [tests] Port TaskTest to new code base

### PR DESCRIPTION
**Pull request by TisonKun**
## What is the purpose of the change

Port `TaskTest` to new code base

## Brief change log

Port every existing tests to FLIP-6 code base. Mainly remove the dependency of `ActorGateway`, `ActorGatewayTaskExecutionStateListener` and `ActorGatewayTaskManagerActions`. See also #6729 [FLINK-10386](https://issues.apache.org/jira/browse/FLINK-10386).

Also add a test to test task fails on blob missing `TaskTest#testExecutionFailsInBlobsMissing`. See also #6768 [FLINK-10427](https://issues.apache.org/jira/browse/FLINK-10427).

With a refactor of `createTask` → `TaskBuilder`

## Verifying this change

This pull request itself is about tests. Thus the guardian is itself.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`:  (**no**)
  - The serializers:  (**no**)
  - The runtime per-record code paths (performance sensitive):  (**no**)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper:  (**no**)
  - The S3 file system connector:  (**no**)

## Documentation

  - Does this pull request introduce a new feature?  (**no**)
  - If yes, how is the feature documented? (**no**)

cc @StephanEwen @uce @aljoscha @tillrohrmann (with a lookup of `TaskTest` history)

### CODE REVIEW

**Comment by TisonKun** [comment]
This pull request need a rebase on #6729 and thus now WIP.

**Comment by TisonKun** [comment]
After a rebase on #6729 and its followings, I think this pull request is ready to be reviewed.

cc @tillrohrmann and @uce .

**Comment by tillrohrmann** [comment]
Thanks for your contribution @TisonKun. I think you merged at some point and now the git history is a bit messed up (some of your commits appear twice). Could you please clean this up. Otherwise, it is really hard for me to resolve the merge conflicts

**Comment by TisonKun** [comment]
@tillrohrmann sure

**Pull request closed without merging**
