### PR TITLE
Allow KeySelectors to implement ResultTypeQueryable

### PR DESCRIPTION
**Pull request by rmetzger**

### CODE REVIEW

**Comment by twalthr** [comment]
getUnaryOperatorReturnType() does already call ResultTypeQueryable if available.

**Comment by rmetzger** [comment]
Without the change, I'm getting the following error, even though my KeyExtractor implements ResultTypeQueryable:
```java
Exception in thread "main" java.lang.IllegalArgumentException: The types of the interface org.apache.flink.api.java.functions.KeySelector could not be inferred. Support for synthetic interfaces, lambdas, and generic types is limited at this point.
	at org.apache.flink.api.java.typeutils.TypeExtractor.getParameterType(TypeExtractor.java:640)
	at org.apache.flink.api.java.typeutils.TypeExtractor.getParameterTypeFromGenericType(TypeExtractor.java:664)
	at org.apache.flink.api.java.typeutils.TypeExtractor.getParameterType(TypeExtractor.java:627)
	at org.apache.flink.api.java.typeutils.TypeExtractor.validateInputType(TypeExtractor.java:686)
	at org.apache.flink.api.java.typeutils.TypeExtractor.getUnaryOperatorReturnType(TypeExtractor.java:235)
	at org.apache.flink.api.java.typeutils.TypeExtractor.getKeySelectorTypes(TypeExtractor.java:189)
	at org.apache.flink.api.java.typeutils.TypeExtractor.getKeySelectorTypes(TypeExtractor.java:183)
	at org.apache.flink.api.java.operators.JoinOperator$JoinOperatorSets.where(JoinOperator.java:871)
	at flink.generators.programs.TPCHGeneratorExample.main(TPCHGeneratorExample.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

**Comment by twalthr** [comment]
It's a bug in line 689. The input validation tries to get the generic parameters that are not available, in this case the validation should be skipped.

**Comment by rmetzger** [comment]
Do you want to fix it or should I do it?

**Comment by twalthr** [comment]
I can create a fix for that.

**Comment by rmetzger** [comment]
Cool, thank you

**Comment by StephanEwen** [comment]
So, this pull request can be closed?

**Comment by rmetzger** [comment]
I'll close it.
I've filed a jira for the issue and assigned it to @twalthr: https://issues.apache.org/jira/browse/FLINK-1471

**Comment by aalexandrov** [comment]
I would advocate to adding this one as well as a fallback option.

I have a situation where I want to use KeySelector that might return Java TupleXX instances parameterized with Scala types, e.g.:

```
class SelectFoo extends KeySelector[Tuple3[Int, Int, String], Tuple3[Int, String]] {
    override def getKey(v: Tuple3[Int, Int, Int]) = new Tuple2(v.f0, v.f2)
}
``

Even though in this cases  the generic parameters are available, the Scala types cannot be inferred because the actual type field type parameters are erased by Scala and  are seen only as java.lang.Object from the Java reflection API.

**Comment by aalexandrov** [comment]
I think that [this StackOverflow article explains my problem](http://stackoverflow.com/questions/11586944/how-to-obtain-the-raw-datatype-of-a-parameter-of-a-field-that-is-specialized-in).

**Comment by twalthr** [comment]
I looked into your issue. Scala has a very strange behavior at this point. I don't know why it converts `Int` to `Object`. The TypeExtractor gets `Tuple3<Object, Object, String>` which results in an input mismatch exception which is correct. If you take `Integer` instead of `Int` everything works fine. 

@aljoscha do you have an idea?

**Comment by aljoscha** [comment]
Nope, sorry, also have no Idea why this is happening.

**Comment by aalexandrov** [comment]
I think that this only happens for the primitive types. I think this is by design.

If you want to inspect generic parameters, Scala forces you to use the Scala reflection API. There is no way around that.

**Pull request closed without merging**
