### PR TITLE
Updates the AssignerWithPunctuatedWatermarks and the AssignerWithPeriodicWatermarks javadocs.

### PR DESCRIPTION
**Pull request by kl0u**
This PR is just to update the documentation of the aforementioned classes to reflect how they are actually used in the runtime code.

### CODE REVIEW

**Comment by kl0u** [comment]
This just updates the javadocs of the assigners. 

Please review!

**Comment by kl0u** [comment]
This PR just updates documentation. 
Please review.

**Comment by kl0u** [comment]
Hello! This PR simply updates the documentation to reflect recent changes to the code. 
Could somebody review this?

**Comment by StephanEwen** [comment]
Looks good, merging this...

Thanks for updating these docs!

**Comment by kl0u** [comment]
No problem @StephanEwen ! 
Thanks for merging this.

**Pull request closed without merging**
