### PR TITLE
[hotfix][scala] Let type analysis work on some Java types

### PR DESCRIPTION
**Pull request by aljoscha**
This is mostly to allow Vertex, which is a Java Tuple2<> to be used in
the Scala Gelly API.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Seems to contain a second fix, to skip static fields in data types.

**Comment by StephanEwen** [comment]
Does the Scala API not treat Java classes the same way as its own classes?
That sounds absolutely like the right thing to do. Why not do as much compile time analysis as possible...

To understand this better, does the Scala type analysis now generate
 - Java Tuple TypeInformation?
 - Does it treat Java POJOs as POJO types?
 - ...

**Comment by aljoscha** [comment]
It does not treat Java classes the same. For some strange reason, the Scala Type analysis in Scala 2.10 can sometimes not "see" the fields of classes defined in Java.

The Scala Type analysis treats Java Tuples as what they are, POJOs. We could maybe add special case handling to make it treat Java tuples as Java tuples.

**Comment by StephanEwen** [comment]
How hard is it to add Java Tuple support to the Scala API? May be also interesting for people that want to use mutable tuples in Scala...

**Comment by aljoscha** [comment]
See here: https://github.com/apache/flink/pull/669

**Pull request closed without merging**
