### PR TITLE
[FLINK-23859][typo][flink-core][flink-connectors]fix typo for code

### PR DESCRIPTION
**Pull request by hapihu**
There are some typo issues in these modules.

 
```bash
# Use the Codespell tool to check typo issue.
pip install codespell

codespell -h
 ```

1、 codespell flink-java/src

```bash
flink-java/src/main/java/org/apache/flink/api/java/operators/PartitionOperator.java:125: partioning ==> partitioning

flink-java/src/main/java/org/apache/flink/api/java/operators/PartitionOperator.java:128: neccessary ==> necessary
 ```
2、 codespell flink-clients/

```bash
flink-clients/src/test/java/org/apache/flink/client/program/DefaultPackagedProgramRetrieverTest.java:545: acessible ==> accessible
 ```

3、codespell flink-connectors/ -S '.xml' -S '.iml' -S '*.txt'

 ```bash
flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/SourceReaderOptions.java:25: tht ==> that

flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/catalog/PostgresCatalogTestBase.java:192: doens't ==> doesn't

flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/dialect/JdbcDialect.java:96: PostgresSQL ==> postgresql

flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/batch/connectors/cassandra/CustomCassandraAnnotatedPojo.java:38: instanciation ==> instantiation

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserCalcitePlanner.java:822: partion ==> partition

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserTypeCheckProcFactory.java:943: funtion ==> function

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveASTParseDriver.java:55: funtion ==> function

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveASTParseDriver.java:51: characteres ==> characters

flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/util/KinesisConfigUtil.java:436: paremeters ==> parameters

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserBaseSemanticAnalyzer.java:2369: Unkown ==> Unknown

flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/config/ConsumerConfigConstants.java:75: reprsents ==> represents

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/functions/hive/HiveFunctionWrapper.java:28: functino ==> function


flink-connectors/flink-connector-hbase-2.2/src/main/java/org/apache/flink/connector/hbase2/source/HBaseRowDataAsyncLookupFunction.java:62: implemenation


flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/cursor/StartCursor.java:70: ture ==> true


flink-connectors/flink-connector-pulsar/src/test/resources/containers/txnStandalone.conf:907: partions ==> partitions

flink-connectors/flink-connector-pulsar/src/test/resources/containers/txnStandalone.conf:468: implementatation ==> implementation


flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/src/enumerate/BlockSplittingRecursiveEnumerator.java:141: bloc ==> block

flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/src/reader/SimpleStreamFormat.java:37: te ==> the


flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/deserializer/KafkaRecordDeserializationSchema.java:70: determin ==> determine

flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/subscriber/TopicListSubscriber.java:36: hav ==> have

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserQBSubQuery.java:555: correlatd ==> correlated


flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaConsumerBaseTest.java:263: intial ==> initial
flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaConsumerBaseTest.java:302: intial ==> initial
flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcher.java:249: wth ==> with
flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/sink/writer/FileWriterBucketStateSerializerMigrationTest.java:232: comitted ==> committed

flink-connectors/flink-connector-rabbitmq/src/main/java/org/apache/flink/streaming/connectors/rabbitmq/RMQDeserializationSchema.java:96: invokation ==> invocation

flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaConsumerTestBase.java:171: doesnt ==> doesn't
```
 

4、codespell flink-core/ -S '.xml' -S '.iml' -S '*.txt'

 
```bash
flink-core/src/main/java/org/apache/flink/api/common/typeutils/TypeSerializerConfigSnapshot.java:194: preform ==> perform

flink-core/src/main/java/org/apache/flink/configuration/CheckpointingOptions.java:150: aways

flink-core/src/main/java/org/apache/flink/configuration/ConfigOption.java:164: documention ==> documentation
flink-core/src/main/java/org/apache/flink/configuration/ConfigOption.java:175: documention ==> documentation
flink-core/src/main/java/org/apache/flink/core/fs/RecoverableFsDataOutputStream.java:54: retured ==> returned

flink-core/src/test/java/org/apache/flink/api/common/io/DelimitedInputFormatTest.java:352: skipp ==> skip

flink-core/src/main/java/org/apache/flink/util/InstantiationUtil.java:216: occurences ==> occurrences
 ```

### CODE REVIEW

**Comment by hapihu** [comment]
```bash
5、codespell flink-dist/ -S '*.xml' -S '*.iml' -S '*.txt' -S '*/target/*'

flink-dist/src/main/flink-bin/bin/config.sh:378: Auxilliary ==> Auxiliary
flink-dist/src/main/flink-bin/bin/config.sh:505: becuase ==> because
```



```bash
6、codespell flink-end-to-end-tests/ -S '*.xml' -S '*.iml' -S '*.txt' -S '*/target/*' -S '*.ans' -S '*.sql'

flink-end-to-end-tests/flink-netty-shuffle-memory-control-test/src/main/java/org/apache/flink/streaming/tests/NettyShuffleMemoryControlTestProgram.java:85: positve ==> positive

flink-end-to-end-tests/flink-python-test/python/python_job.py:38: pipleline ==> pipeline

flink-end-to-end-tests/test-scripts/common_yarn_docker.sh:200: succesfully ==> successfully

flink-end-to-end-tests/test-scripts/kafka-common.sh:98: propery ==> propert
```

**Comment by hapihu** [comment]
```bash
7、codespell flink-examples/ -S '*.xml' -S '*.iml' -S '*.txt' -S '*/target/*'

flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/join/WindowJoin.java:42: steams ==> streams
flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/join/WindowJoin.java:44: steams ==> streams
flink-examples/flink-examples-streaming/src/main/scala/org/apache/flink/streaming/scala/examples/join/WindowJoin.scala:31: steams ==> streams
flink-examples/flink-examples-streaming/src/main/scala/org/apache/flink/streaming/scala/examples/join/WindowJoin.scala:34: steams ==> streams
flink-examples/flink-examples-batch/src/main/java/org/apache/flink/examples/java/misc/CollectionExecutionExample.java:83: availble ==> available
```

**Comment by hapihu** [comment]
#8、
codespell flink-formats/ -S '*.xml' -S '*.iml' -S '*.txt' -S '*/target/*'


flink-formats/flink-orc/src/main/java/org/apache/flink/orc/vector/AbstractOrcColumnVector.java:85: Unsupport ==> Unsupported
flink-formats/flink-orc-nohive/src/main/java/org/apache/flink/orc/nohive/vector/AbstractOrcNoHiveVector.java:70: Unsupport ==> Unsupported
flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/RowDataToAvroConverters.java:70: accroding ==> according
flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/typeutils/AvroFactory.java:71: initalize ==> initialize

**Comment by hapihu** [comment]
# 1、 
codespell flink-java/ -S '*.xml' -S '*.iml' -S '*.txt' -S '*/target/*'

flink-java/src/main/java/org/apache/flink/api/java/DataSet.java:1538: writen ==> written

**Review by infoverload — APPROVED** [review]

**Comment by zentol** [comment]
I will revisit this PR once the feature freeze has concluded.

**Comment by pnowojski** [comment]
This PR failed the build and caused master branch to not compile :(

**Pull request merged**
