### PR TITLE
[FLINK-2324] [streaming] Partitioned state checkpointing rework + test update

### PR DESCRIPTION
**Pull request by gyfora**
This commit reworks the way partitioned operator states are checkpointed eliminating per-key checkpointing to increase performance and also updates the StreamCheckpointingITCase to use partitioned state to check exactly-once semantics + it adds a new ITCase to test partitioned state recovery.

**Rework of partitioned state checkpointing**
Previously each OperatorState method would return a PartitionedStateHandle object upon snapshotting which would contain a Map of Key -> StateHandle, storing the partitioned states by key. This had two negative implications:
* At every checkpoint we stored the states for each key independently (slowing the checkpoints and overloading the storage layer)
* We had to keep the keys in-memory (this might cause memory issues with large keys)

This has been changed in this commit to store the map of states at each operator in 1 statehandle, minimizing the time it takes to take a snapshot and also minimizing the load on the storage layer. This might change slightly when we start thinking about state repartitioning for operator scaling.

**Update StreamCheckpointingITCase with partitioned states**
In the StreamCheckpointingITCase I replaced the RichReduceFunction (which was working incorrectly as it is not checkpointed) with a RichFlatMapFunction implementing the stateful group reduce functionality using partitioned states, to count the number of strings received for a specific prefix.
Using this we now test that exactly-once processing happens.

### CODE REVIEW

**Comment by gyfora** [comment]
After playing around with the StreamCheckpointingITCase, it seems like we actually don't even have at least once guarantees because of some bug in the implementation (either in the barrier buffer or with the event alignment):

The RichFlatMap that did the counting (preceeded by a groupBy) did not always count the correct number of inputs or prefixes (meaning the state was checkpointed earlier than it should have been).

What was interesting that all other operators counted exactly the right amount of inputs all the time, then I realised they were all forward connected (pointwise connection pattern which didnt trigger any blocking logic in the barrier buffer). So I changed the connection between the filter and map to shuffle, and now that map also fails sometimes on incorrect number of inputs received.

I will try rebasing this on @StephanEwen 's barrier buffer rework in https://github.com/apache/flink/pull/938, let's see if that fixes it.

**Comment by gyfora** [comment]
So far it seems to work rebased on #938 (but I am getting some test failures due to some deadlock in that PR).

**Comment by aljoscha** [comment]
We should try to find out what the problem was in the beginning, let's wait for @StephanEwen. I think @rmetzger is also investigating the issue.

**Comment by gyfora** [comment]
Definitely.

**Comment by StephanEwen** [comment]
I think we should not change the existing tests but add new ones. The current `StreamCheckpointingITCase` is there to test the non-partitioned state.

Update: I just saw that is has actually been changed before, so we lost test coverage for the `Checkpointed` interface. That's not good...

**Comment by gyfora** [comment]
The test still tests the Checkpointed interface, and regarding the partitioned state, since the job is a wordcount, it is very natural to add partitioned state to test the proper exactly-once functionality. 

Nothing has been removed, it was only extended. It tests all 3 cases, Checkpointed, Partitioned and non-partitioned states

**Comment by StephanEwen** [comment]
Are we talking about the same `StreamCheckpointingITCase` ? It has just one test method...

(https://github.com/apache/flink/blob/6571a83fa9acbbb229b78f160cd076429418c4be/flink-tests/src/test/java/org/apache/flink/test/checkpointing/StreamCheckpointingITCase.java)

**Comment by gyfora** [comment]
Yes but it has 3 stateful operators
2 of them use non-partitioned operator states and 1 uses the checkpointed interface. Assertions verify the behaviour.

Now I added a 4th stateful operator (replacing the reduce) which uses partitioned states to verify correct count.

**Comment by StephanEwen** [comment]
The `Checkpointed` variant used to be check in the settings "source", "chained" and "after repartition". That is no longer the case, so we lost the coverage there.

In genera, I think we should not adjust tests and remove anything that they currently test. There should be a new test instead.

**Comment by gyfora** [comment]
I can rewrite this of course and create new test classes but in any way the StreamCheckpointingIT case needs to be changed because it was not well designed in the first place.

It had uncommented tests, and never checked checkpointing after shuffle which was in fact broken for some reason I am still not sure (see some notes above).

My only worry is that if we add new test classes for all the cases, checkpointed, partitioned, non-partitioned (where the checkpointing actually happens together with the same logic so I don't see a reason for having separate test) then we end up with a lot of these pretty heavy tests.

**Comment by StephanEwen** [comment]
I think it is fine to have a set of heavy tests, this is a core and crucial feature. It may very well be that these variants are eventually implemented differently under the hood (especially partitioned state). So far, this feature is far from overtested.

The fact that the checks after the re-partitioning are disabled is, in fact, a problem.

Let me re-add a pure `Checkpointed` variant of this test, with enabled checks after the repartitioning.

**Comment by gyfora** [comment]
Alright :)

**Comment by StephanEwen** [comment]
So, the `StreamCheckpointingITCase` actually has the problem that is uses this reducer that is implicitly on an infinite window. Since that is not checkpointed, all results after that reducer are not correctly recovered.

**Comment by gyfora** [comment]
Yes, I have written this above (that's why I replaced it with one using the partitioned states). But that's not the only problem. If you introduce a shuffle between two maps (.shuffle()) then those are not correctly checkpointed either.

**Comment by gyfora** [comment]
I am adding an IT case to this PR that tests partitioned states independently.

**Comment by gyfora** [comment]
Merging your PR fixed the exactly-once guarantees @StephanEwen , great!

I also added an extra test for Partitioned states.

Do you think it is okay to leave the StreamCheckpointingITCase how I modified it? Now it tests all the different checkpointing mechanisms together. If you add a test for the Checkpointed interface itself, this should be good.

**Comment by gyfora** [comment]
Any concerns against merging this? @senorcarbone?

**Comment by gyfora** [comment]
I will actually add one more test to verify the correct behaviour of all the wrapper statehandle classes.

**Comment by senorcarbone** [comment]
That would be good ^^
then it's :+1: from me, at least for now.
It's generally good performance-wise to have less serialised states. This means that we will have a constant number of issued writes to external storage (== #subtasks). On the other hand this also makes our life harder a bit when it comes to repartitioning, as you already mentioned we need to revisit this.

**Comment by aljoscha** [comment]
I was too busy but I would like to take a quick look. I will look at it tomorrow morning.

**Comment by gyfora** [comment]
No pressure

**Comment by aljoscha** [comment]
I think the changes are ok for now but we need to think hard about how we can unify incremental state, partitioned state, out-of-core state and scale-out/in in the future. This will then probably have to be redone again. What do you think @StephanEwen ?

**Comment by gyfora** [comment]
This is why I tried to make the interface general, to work simply with StateHandle-s. As that will most likely stay, we can implement the advanced logic on top of that.

**Comment by aljoscha** [comment]
Yes, of course, that's nice. :smile:

**Comment by gyfora** [comment]
If no other comments I would like to merge this.

**Pull request closed without merging**
