### PR TITLE
[FLINK-8711] [yarn] Remove code which auto-magically changes slots per TM

### PR DESCRIPTION
**Pull request by tillrohrmann**
## What is the purpose of the change

The FlinkYarnSessionCli auto-magically amends the number of slots with which the
TMs are started. This was thought as a convenience function. However, it breaks the
execution of jobs where we have multiple slot sharing groups. Therefore, this commit
removes this code.

As a consequence, the user has to make sure that he specifies enough slots and
containers for the pre Flip-6 code such that the number of total slots is greater
or equal than the parallelism of the job.

**Important:** This PR changes Flink's behaviour wrt starting Flink Yarn session clusters. It can become necessary that the user specifies the correct number of slots with which he wants to launch his TMs.

## Verifying this change

This change is already covered by existing tests, such as the Yarn test cases.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes it changes Flink's behaviour)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by zentol** [comment]
Could we instead also account for SlotSharingGroups? The existing behavior has been there for quite a while hasn't it :/

**Comment by tillrohrmann** [comment]
This is not possible. The problem arises when you start a session cluster where you don't know the Flink job to submit. 

Personally, I'm not a huge fan of too much auto magic which leads to unexpected behaviour. Instead I would prefer that things fail if not properly started (e.g. not enough slots) instead of trying to figure out the right number of slots (which apparently breaks things).

**Comment by StephanEwen** [comment]
In FLIP-6 mode, the right thing is to not have the number of TaskManagers preconfigured, but to start them when needed. Does that work already?

The Yarn session would then
  - Start Dispatcher + ResourceManager (= Yarn App Master)
  - Start JM when job i ssubmitted
  - Allocate TMs when JobManager requests slots
  - TMs are held by the ResourceManager after the JM releases them, and kept in the session for a certain time before they are returned to YARN.

I am +1 to remove this "auto change slots" code, it really breaks abstraction, and go for the above model

**Comment by tillrohrmann** [comment]
Thanks for the review @zentol and @StephanEwen. Travis passed. Merging this PR.

**Pull request closed without merging**
