### PR TITLE
[FLINK-3310] [runtime, runtime-web] Add back pressure statistics

### PR DESCRIPTION
**Pull request by uce**
This PR introduces back pressure statistics to the web frontend.

The idea is that tasks, which are back pressured by the network or slow upstream tasks are blocked on  buffer requests to the network stack. An example stack trace for these calls looks like this:
```
java.lang.Object.wait(Native Method)
o.a.f.[...].LocalBufferPool.requestBuffer(LocalBufferPool.java:163)
o.a.f.[...].LocalBufferPool.requestBufferBlocking(LocalBufferPool.java:133) <--- BLOCKING
...
```

This PR introduces a mechanism to gather a sample of stack traces of running tasks. Depending on the number of stack traces stuck in the above calls, the task is assumed to experience back pressure. Depending on the ratio, back pressure is categorized into classes `OK` (<= 0.10) , `LOW` (<= 0.5), and `HIGH` (else).

The user can trigger the sampling via the web frontend. Results are cached for a certain amount of time (`60s`) before triggering further stack trace samples in order to not flood the task managers.

## Questions

What's your opinion on the following defaults:
- Categories `OK` (<= 0.10) , `LOW` (<= 0.5), and `HIGH` (else).
- `100` samples with `50 ms` delay between samples.
- `60s` default refreshing interval before web front end triggers new samples.

Furthermore, do you think we should allow to disable these features?

In future versions of Flink, I think that we need to start thinking about splitting the ExecutionGraph up a little bit. We need something like the old `ManagementGraph` in order to stop overloading the `ExecutionGraph` with non-core stuff.

### Back pressure tabs

screen shot 2016-02-02 at 17 57 05

### First click, sampling in progress

screen shot 2016-02-02 at 17 57 11

### Sampling done

screen shot 2016-02-02 at 17 57 19

### Show sub tasks

screen shot 2016-02-02 at 17 57 24

### Sample is refreshed

screen shot 2016-02-02 at 17 58 18

screen shot 2016-02-02 at 17 58 28

### CODE REVIEW

**Comment by fhueske** [comment]
Will this also be displayed / collected for batch jobs? Might this raise questions / confuse users?

**Comment by uce** [comment]
Yes, it's independent and relevant for both streaming and batch. 

I think you are raising a valid point with your last question. In contrast to the other information in the web frontend, this one is more involved. We can rename the tab to "Advanced" and then put back pressure statistics there (and other advanced monitoring functionalities in the future). Do you like this idea? Do you have any other ideas?

**Comment by StephanEwen** [comment]
Is it actually a bad thing that this is available for batch jobs? Batch jobs have multiple pipelined tasks as well, and this would figure out where in the pipeline the bottleneck is.

**Comment by uce** [comment]
It's definitely a good thing in my opinion. I was just asking whether we should "hide" it behind an Advanced tab (with further advanced monitoring features in the future).

**Comment by StephanEwen** [comment]
We can still move the tab in the UI later.
I don't think there is a thing like "breaking changes" in the UI ;-)

**Comment by uce** [comment]
Did anyone have time to check this out? Would appreciate it :-) Or do we want to postpone this until after the 1.0 release?

**Comment by StephanEwen** [comment]
I would very much like to have this in the 1.0 release.

**Comment by StephanEwen** [comment]
This looks pretty good all in all.

One thing I do not like that much is that the sampling process needs a coordinator on the ExecutionGraph. A functionality that is purely for information / visualization should have ideally no fields and state on the ExecutionGraph.

It looks very feasible to move the sample coordinator into the sample REST handler, keeping it out of the JobManager completely.

With such a change, I think this is good to merge

**Comment by uce** [comment]
I've addressed the comments and moved the code to the runtime monitor, which now starts the sample coordinator with an actor to receive the responses (instead of going though the job manager). Thanks for the review. I'm going to merge this after Travis gives a green light.

**Pull request closed without merging**
