### PR TITLE
[FLINk-1680] Remove Tachyon test, rename maven module

### PR DESCRIPTION
**Pull request by rmetzger**
I removed our dependencies to Tachyon.
The Tachyon test cluster (version 0.5) seemed to be unstable.
Upgrading to Tachyon 0.7 was causing some dependency issues with Hadoop.

Since the "flink-tachyon" module never contained any special code for Tachyon, I just removed the Tachyon test. 
There is still a (very stable) test using the HDFS mini cluster to verify that our file system abstractions are working properly

### CODE REVIEW

**Comment by StephanEwen** [comment]
Looks good in general.

Any reason that the tests cannot be part of `flink-tests`? Just thinking that we may reduce our maven project sprawl a bit ;-)

**Comment by hsaputra** [comment]
+1

**Comment by rmetzger** [comment]
The problem is that we can only include this module for the hadoop2 builds. Therefore, I can not add the code to a module which is always present (`flink-tests`)

**Comment by StephanEwen** [comment]
I see, makes sense...

**Comment by fhueske** [comment]
OK, will merge this one as well

**Pull request closed without merging**
