### PR TITLE
[FLINK-14699][type] Move ClosureCleaner to flink-core

### PR DESCRIPTION
**Pull request by TisonKun**
## What is the purpose of the change

`ClosureCleaner` is currently under `flink-java`. However, it doesn't stick to `flink-java` and used in `flink-streaming-java`. IMHO `flink-streaming-java` should not base on `flink-java`( `flink-batch-java` in fact ). Thus, I propose to move `ClosureCleaner` to `flink-core`.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (don't know)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by TisonKun** [comment]
@aljoscha please give this pull request a look :-)

**Comment by aljoscha** [comment]
I think we better move the `ClosureCleaner` to the `org.apache.flink.util` package. What do you think?

**Comment by TisonKun** [comment]
@aljoscha the original purpose of this change is for module dependency issue. If we change the FQN, shall we potentially risk breaking b/w compatibility? IIRC ClosureCleaner once suffer from such issue.

**Comment by TisonKun** [comment]
FYI https://issues.apache.org/jira/browse/FLINK-13586

**Comment by aljoscha** [comment]
You're right. 😅 Good catch!

**Pull request merged**
