### PR TITLE
[FLINK-2155] Enforce import restriction on usage of Flink shaded package and Commons Validate

### PR DESCRIPTION
**Pull request by lokeshrajaram**
@rmetzger sorry I had issues squashing commits hence this new pull request. Not sure if I am doing it right. Sorry for the trouble

### CODE REVIEW

**Comment by uce** [comment]
Hey @lokeshrajaram. This is not right, but it's not a problem. We can easily fix it. :-) I suggest that you do the following:

1. If you don't have the Flink repository as a remote, add it: `git add remote flink https://git-wip-us.apache.org/repos/asf/flink.git` and do a fetch `git fetch flink`. This depends on whether you cloned your fork or the main repo.

2. Checkout a new branch from flink/master: `git checkout -b YOUR_BRANCH flink/master`.

3. Cherry pick your commit: `git cherry-pick 3f07464`. This will add your commit to the new branch. There should be no conflicts.

4. Now force push this to the branch of *this* pull request: `git push -f origin YOUR_BRANCH:checks_for_import`. Assuming that origin is your forked repository. You have to force push, because you are changing the history of this branch.

**Comment by lokeshrajaram** [comment]
@uce Thanks for the instructions. will follow this and create a new pull request. sorry for the trouble.

**Comment by uce** [comment]
You don't have to update the pull request when you force push to the branch of this pull request. :-)

**Comment by lokeshrajaram** [comment]
@uce Thanks a lot for the for your help. Followed your instructions and got it right but worked on a new branch. created a new pull request and hence closing this.

**Pull request closed without merging**
