### PR TITLE
[hotfix][Apache Kafka Connector][docs] Fixed kafka.md sink example error

### PR DESCRIPTION
**Pull request by mingwayXue**
## What is the purpose of the change

Fixed kafka.md sink example error

## Brief change log

update kafka.md sink example code

## Verifying this change

just update kafka.md document,and Chinese documentation did not contain this.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by mingwayXue** [comment]
@flinkbot run azure

**Comment by mingwayXue** [comment]
> ## CI report:
> * [5cf7c25](https://github.com/apache/flink/commit/5cf7c25f9ab637f5bebb7205e8078c146c5653d3) Azure: [FAILURE](https://dev.azure.com/apache-flink/98463496-1af2-4620-8eab-a2ecc1a2e6fe/_build/results?buildId=29426)
> 
> Bot commands

@flinkbot run azure

**Comment by mingwayXue** [comment]
@MartijnVisser Hi, MartijnVisser. Could you help to confirm this document fix? Chinese documentation is not contain this same code.

**Comment by MartijnVisser** [comment]
@mingwayXue Thanks for your contribution! This PR should be a backport of https://github.com/apache/flink/pull/17667 because that was merged first.

**Comment by mingwayXue** [comment]
> @mingwayXue Thanks for your contribution! This PR should be a backport of #17667 because that was merged first.

ok, thanks

**Pull request closed without merging**
