### PR TITLE
[FLINK-6656] [cep] Change element PriorityQueue to MapState.

### PR DESCRIPTION
**Pull request by kl0u**
This is to leverage the fact that RocksDB already returns the
keys sorted. So now elements, instead of being stores in a PQ
and all of them being deserialized and serialized at each incoming
element, the are stored in a MapState with the key being the
timestamp and the value, a List of elements that refer to the
same timestamp.

### CODE REVIEW

**Comment by aljoscha** [comment]
This looks good! Why is the element processing reordered in places in the tests, though?

**Comment by kl0u** [comment]
The re-ordering is just to verify that at watermark time, we actually order
by event-time.

**Comment by dawidwys** [comment]
Just a question from my side to understand this change better. Does it really leverage the fact of keys being returned in order? To evaluate `getSortedTimestamps` you need to iterate whole keySet anyway.

I see though it benefits from laziness of value deserialization and partitioning of the incoming events (by timestamp). 

Is my understanding correct?

**Comment by kl0u** [comment]
Hi @dawidwys ! Your understanding is correct in the sense that it does not leverage to the fullest the fact of keys being returned in order. The reason is that this is valid only in RocksDB state backend. 

But when it comes to insertion to the PriorityQueue, this can come in handy as inserting will be fast. In addition, as you said, we only deserialize the values we need, when we need them, instead of everything all the time.

**Comment by dawidwys** [comment]
Thanks for clarification!

Z pozdrowieniami! / Cheers!

Dawid Wysakowicz

*Data/Software Engineer*

Skype: dawid_wys | Twitter: @OneMoreCoder

<http://getindata.com/>

2017-05-22 18:01 GMT+02:00 Kostas Kloudas <notifications@github.com>:

**Comment by rmetzger** [comment]
@kl0u asked me to merge this PR to the release-1.3 branch. It seems the change is good to merge.

**Pull request merged**
