### PR TITLE
[FLINK-32279][table-runtime] Shuffle HashJoin support spill to disk when enable operator fusion codegen

### PR DESCRIPTION
**Pull request by lsyldliu**
## What is the purpose of the change

*For shuffle hash join, we don't support spill to disk currently if operator fusion codegen, so this PR main purpose is to fix the problem.*

## Brief change log

  - *Shuffle hash join support spill to disk if operator fusion codegen enabled*

## Verifying this change

This change added tests and can be verified as follows:

*(example:)*
  - *Integration tests in OperatorFusionCodegenITCase can verify it*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (JavaDocs)

### CODE REVIEW

**Comment by wuchong** [comment]
Could you rebase this PR?

**Comment by lsyldliu** [comment]
> Could you rebase this PR? And the compile is failed.

done

**Review by wuchong — APPROVED** [review]
LGTM.

**Comment by wuchong** [comment]
The failed case is tracked by [FLINK-32632](https://issues.apache.org/jira/browse/FLINK-32632)

**Pull request merged**
