### PR TITLE
[FLINK-18428][API/DataStream] Rename StreamExecutionEnvironment#continuousSource() to StreamExecutionEnvironment#source().

### PR DESCRIPTION
**Pull request by becketqin**
## What is the purpose of the change
Rename `StreamExecutionEnvironment#continuousSource()` to `StreamExecutionEnvironment#source()` according to the original FLIP-27 design.

## Brief change log
Rename `StreamExecutionEnvironment#continuousSource()` to `StreamExecutionEnvironment#source()`

## Verifying this change
This is a method rename.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (docs / JavaDocs)

### CODE REVIEW

**Comment by twalthr** [comment]
Why don't we call this method `fromSource`? We have `fromElements`, `fromCollection`, `fromParallelCollection`. It is confusing that we also have `addSource`, `readFile`, and `createInput`.

**Comment by dawidwys** [comment]
+1 from my side

Personally I am fine with either `fromSource`/`addSource`/`source`.

**Comment by becketqin** [comment]
@twalthr I think the clearest naming is either `StreamExecutionEnvironment#dataStreamFromSource()` or `DataStream#fromSource()`. But given the current status, I agree that `StreamExecutionEnvironment#fromSource()` is better than just `source()`. At least this would give a consistent style after we deprecate `readFile()`, `addSource()` and `createInput()`. I'll update the patch.

**Comment by becketqin** [comment]
@twalthr @dawidwys Thanks for the review. I'll merge the patch after the CI tests pass.

**Comment by StephanEwen** [comment]
+1 from my side

**Comment by StephanEwen** [comment]
Merging this as part of the current batch of fixes...

**Pull request closed without merging**
