### PR TITLE
[FLINK-7764] [kafka] Enable the operator settings for FlinkKafkaProducer010

### PR DESCRIPTION
**Pull request by xccui**
## What is the purpose of the change

This PR fixes the operator setting (name, uid, parallelism, etc.) problem of  FlinkKafkaProducer010.

## Brief change log

  - Override all the `DataStreamSink` public methods in `FlinkKafkaProducer010.FlinkKafkaProducer010Configuration`

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by StephanEwen** [comment]
cc @aljoscha and @pnowojski 
I think there is some work for Flink 1.4 to make the Kafka 0.10 sink a regular sink function, so that the code that constructs the sink transformation is not needed any more.

This change would be relevant to 1.3.3 though.

**Comment by aljoscha** [comment]
We actually still need to do this because we cannot remove the `writeToKafkaWithTimestamps()` methods without breaking compatibility. (They are marked as deprecated, though). 

@xccui For the `release-1.3` branch the fix has to be slightly modified. Are you also up for fixing that?

**Comment by xccui** [comment]
Thanks for the review @StephanEwen and @aljoscha. I'd like to fix this thoroughly. However, I don't have much experience working on other branches. Shall I checkout the `release-1.3` branch and edit it directly?

**Comment by aljoscha** [comment]
@xccui Yes, you would check out the `release-1.3` branch, do your fix there and then create a PR against the `release-1.3` branch.

**Comment by xccui** [comment]
Hi @aljoscha, I've created another PR #4819 for the `release-1.3` branch.

**Comment by xccui** [comment]
Hi @aljoscha, I wonder if you could take a look at this PR (as well as #4819) when you are convenient. Thanks!

**Comment by aljoscha** [comment]
Thanks, @xccui! 😃 

I merged this, could you please close the PR?

**Comment by xccui** [comment]
Thanks!

**Pull request closed without merging**
