### PR TITLE
[FLINK-3333] [Documentation][DataSet] Improve documentation of DataSet object-reuse modes

### PR DESCRIPTION
**Pull request by fhueske**
@ggevay, @greghogan Please have a look at this PR. 
I basically copied the content of the [proposal in the Google document](https://docs.google.com/document/d/1jpPr2UuWlqq1iIDIo_1kmPL9QjA-sXAC9wkj-hE4PAc).

### CODE REVIEW

**Comment by ggevay** [comment]
Why was the "Emitting input objects" field changed? For example, is there a problem with emitting input objects from a JoinFunction? (Like here: http://apache-flink-user-mailing-list-archive.2336050.n4.nabble.com/Quick-question-about-enableObjectReuse-td4797.html)

**Comment by greghogan** [comment]
What if that JoinFunction is chained to a MapFunction that modifies its inputs? It is the probe-side record which needs protecting, and the example user function emits from both records.

**Comment by ggevay** [comment]
Oops, you are right!

**Comment by fhueske** [comment]
Yes @greghogan, that's why I changed it.

**Comment by ggevay** [comment]
By the way, I think that the change of the input rules about the non-iterator UDFs will actually allow us to simplify some code: all those drivers that work with such UDFs that get input objects through parameters, can be changed to always do object reuse, even when object reuse is turned off. This is made possible by the "Note: Objects may be modified after the method call is left. Therefore, it is not safe to remember objects across function calls." part in the "Reading input objects" field. This should improve performance in the object reuse disabled case.

**Comment by fhueske** [comment]
That's a good point, but I don't think we should actually do this. 
It is fine to be more conservative than the provided guarantees. However, by updating the drivers to strictly follow the object-reuse guarantees we would risk to (silently) break existing code.

**Comment by fhueske** [comment]
Any objections to merge this PR?

**Comment by fhueske** [comment]
will merge this

**Pull request closed without merging**
