### PR TITLE
[hotfix] Fix typos of comment

### PR DESCRIPTION
**Pull request by hustonic**
## What is the purpose of the change

Fix typos of comment

### CODE REVIEW

**Comment by hustonic** [comment]
#22370

**Comment by hustonic** [comment]
Associated with this PR: #22370

**Comment by hustonic** [comment]
@MartijnVisser Hi, do you think it's right this time?

**Review by healchow — APPROVED** [review]
LGTM

**Comment by hustonic** [comment]
@reswqa Hi, Can you help me merge this PR?

**Comment by reswqa** [comment]
Thanks @hustonic.

**Pull request merged**
