### PR TITLE
[FLINK-4983] Web UI: Add favicon

### PR DESCRIPTION
**Pull request by siliconcat**
Adds favicon.ico to the Flink dashboard. Uses same icon than main site

### CODE REVIEW

**Comment by Makman2** [comment]
Not a web-dev, though doesn't need this some modifications in the according HTMLs to properly perenst the favicon?

**Comment by siliconcat** [comment]
It does, let me see why the file does not apear in the PR

**Comment by siliconcat** [comment]
Now, the index file with the modification is there. Sorry for that.

**Comment by greghogan** [comment]
Could we enhance the favicon itself? I tried `http://realfavicongenerator.net/` and there are many other 'favicon generators'.

I used this image: https://github.com/apache/flink-web/blob/asf-site/img/logo/png/1000/flink_squirrel_1000.png

**Comment by siliconcat** [comment]
I just re-used the one in the main Flink site. No artist myself :)

Not sure how this could break the build either?

**Comment by Makman2** [comment]
> Could we enhance the favicon itself?

Maybe we can use the grayscale / black-white version of the flink logo, could fit more into the default dashboard design^^

> Not sure how this could break the build either?

Seems the CI is not really stable nowadays, also submitted a PR which just deleted a single letter in a documentation comment, and CI failed^^

**Comment by greghogan** [comment]
The Travis CI tests have never been stable. There are five parallel builds each split into two jobs and 9 of 10 passed for the latest commit on this PR. The tests are significantly more stable when running `mvn verify` outside of Travis CI.

**Comment by siliconcat** [comment]
Ok, what about this? Black and white for the favicon in browsers. In colour for the mobile screens. Generated using the favicon generator above...

Couldn't test the iphone, as I don't have one.

**Comment by greghogan** [comment]
Why not keep the color image for the favicons? The smaller size looks like a black blob to my eyes. The current color icon is distinctive and will look even better at 32x32. If we wanted to use B&W would it be better to use the outline image for the favicons?

**Comment by Makman2** [comment]
yeah I think also an outline image is better :)

**Comment by rmetzger** [comment]
I've created a fix: https://github.com/rmetzger/flink/commit/28a3aed8633246717c52599c25ced928436a6f97
and pushed it to my travis account (Github has a service outage, that's why travis builds are not triggered)
I'll probably merge it tomorrow morning, given that Travis is finally happy with it :)

**Pull request closed without merging**
