### PR TITLE
[FLINK-25830][docs]Typo mistake in "Metric Report page" of the documentation

### PR DESCRIPTION
**Pull request by forrestlmj**
## What is the purpose of the change

Fix Typo mistake in "Metric Report page" of the documentation.There should have a space between "metrics.reporter.my_jmx_reporter.scope.variables.excludes:" and "job_id;task_attempt_num" in the YAML part.

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by forrestlmj** [comment]
Hi,community:
This is my first pull request to Apache Flink,should I @ someone to merge this?Not sure who will review this commit, Please let me know if I am missing something:)

**Comment by forrestlmj** [comment]
hi,@gaoyunhaii ,will you review this pr and merge it please?Thanks.

**Review by RocMarshal — APPROVED** [review]
Good catch.
LGTM +1 (non-binding.)

**Review by gaoyunhaii — APPROVED** [review]
Thanks @forrestlmj for the PR! Verified locally and LGTM

**Pull request closed without merging**
