### PR TITLE
[FLINK-16582][runtime][test] Fix the buffer leaks in NettyBufferPoolTest

### PR DESCRIPTION
**Pull request by gaoyunhaii**
## What is the purpose of the change

This PR fixes the possible buffer leaks in `NettyBufferPoolTest`. 

## Brief change log

- 5028c1a894f46687d38fe91b34d096d858786772 records all the created buffers during test, and release them after test.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): **no**
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: **no**
  - The serializers: **no**
  - The runtime per-record code paths (performance sensitive): **no**
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: **no**
  - The S3 file system connector: **no**

## Documentation

  - Does this pull request introduce a new feature? **no**
  - If yes, how is the feature documented? **not applicable**

### CODE REVIEW

**Review by XComp — APPROVED** [review]
LGTM :+1: Thanks for this contribution @gaoyunhaii . May you rebase the branch and create backports for 1.16 and 1.15?

**Comment by XComp** [comment]
I force-pushed the rebase myself.

**Comment by gaoyunhaii** [comment]
Hi @XComp  very thanks for reviewing and very sorry for missing the previous message, I'll create the backports and merge it after the ci  passed.

**Comment by XComp** [comment]
The backports are created. Feel free to have a look, merge all PRs after the CI is green and finalize the Jira issue. Thanks :-)

**Comment by gaoyunhaii** [comment]
Ah, very thanks for that! I'll finalize the issue today.

**Pull request closed without merging**
