### PR TITLE
[FLINK-3867] Provide Vagrant/Ansible based VMs to easily setup Flink

### PR DESCRIPTION
**Pull request by jneuff**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.
- [X] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)
- [X] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added
- [X] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by rmetzger** [comment]
Thanks a lot for opening a pull request for this.
I like having virtual machines and deployment available for new projects, so in general I like the idea a lot.

However, I wonder if the Flink repository is the right place for such deployment scripts. The `flink-docker` module in the same directory is also something I would like to relocate in the long term.
There are some problems with having these in the Flink repository:
- They tend to outdate over time, because most of the committers don't maintain these scripts.
- They are not really part of the release cycle. We don't update the versions on releases, they are somehow part of the source release, but not really documented or tested.
- As you've seen yourself, it can take some time until a pull requests is reviewed and merged. So its probably easier to maintain such scripts somewhere else.

There is a special page on the Flink website for linking to repositories containing helpful Flink material: http://flink.apache.org/community.html#third-party-packages.
Maybe you can put the code into a GitHub repository and link it from the third party packages pages at the Flink site.

Another good location could be "Apache Bigtop", a project specifically for the deployment of Hadoop-related projects.

**Comment by uce** [comment]
I agree. +1 to link in 3rd party packages if this is up to date and close this PR. What do you think @rmetzger and @jneuff?

**Comment by kempa-liehr** [comment]
I just separated the Flink-VM into a separate repository [https://github.com/kempa-liehr/DSVMs], such t you can close this pull request. 

However, could you arrange to link https://github.com/kempa-liehr/DSVMs into [https://flink.apache.org/community.html#third-party-packages]?

**Comment by jneuff** [comment]
Sorry, this has slipped my mind. @kempa-liehr Great idea!

**Pull request closed without merging**
