### PR TITLE
[FLINK-24274][docs] Wrong parameter order in documentation of State Processor API (for 1.14)

### PR DESCRIPTION
**Pull request by zoltar9264**
## What is the purpose of the change

Fix documentation problem described in [FLINK-24274](https://issues.apache.org/jira/browse/FLINK-24274) for 1.14.

## Brief change log

Adjust parameter order in documentation of State Processor API.

## Verifying this change

Not needed.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by zoltar9264** [comment]
@sjwiesman Hi Seth Wiesman, this PR fix problem described in [FLINK-24274](https://issues.apache.org/jira/browse/FLINK-24274) for 1.14.

**Comment by zoltar9264** [comment]
@wuchong Hi wuchong, can you help review this PR ?

**Comment by MartijnVisser** [comment]
@zoltar9264 This PR is aimed at the `release-1.14` branch. Could you first open a PR that targets the `master` branch?

**Comment by zoltar9264** [comment]
@MartijnVisser Thank you for reply. I have previously opened [PR-17292](https://github.com/apache/flink/pull/17292) for master branch.

**Review by MartijnVisser — APPROVED** [review]
Thanks for the fix! LGTM

**Comment by MartijnVisser** [comment]
@zoltar9264 Thanks again for both PRs. I've merged them.

**Pull request merged**
