### PR TITLE
[FLINK-3011, 3019, 3028] Cancel jobs in RESTARTING state

### PR DESCRIPTION
**Pull request by uce**
This addresses issues with cancelling jobs, which are in the `RESTARTING` state. A job enters this state  after a failure as soon as all job vertices are in their final state. It then stays in this state until it is redeployed (e.g. default 100s currently). In this state, the job cannot be cancelled. If the failure is permanent (for example missing slots), the job can never be cancelled.

This PR includes changes to the ExecutionGraph and to the clients:

**ExecutionGraph** (FLINK-3011)
- Remove the state transition from `FAILED` to `RESTARTING` in `restart()`. This was breaking the semantics of `FAILED` being a terminal state. It was only relevant for a test as far as I can tell.
- When cancelling during restarts, two job states are relevant:
  - `RESTARTING`: try to set the state directly to `CANCELED` as all vertices have been already failed when the job enters the `RESTARTING` state. If the state transition to `CANCELED` succeeds, the restart will be ignored with a log message.
  - `FAILING`: try to set the state to `CANCELLING` and wait for the failing of the vertices to finish. This will finish the cancellation as usual in `jobVertexInFinalState()`. 

When reviewing the `cancel()`, `jobVertexInFinalState()`, and `restart()` methods are relevant.

**CLIFrontend** (FLINK-3019)
- List restarting jobs with scheduled jobs

```
$ bin/flink list
No running jobs.
---------------- Scheduled/Restarting Jobs -------------------
17.11.2015 15:14:01 : 4b3fa06c88e5a2a4963241e7afca7b7d : Streaming WordCount (RESTARTING)
--------------------------------------------------------------
```

**WebFrontend** (FLINK-3028)
- Show the cancel button if the job is restarting. It was only displayed for running or created jobs before.

---

I want to merge this for 0.10.1 and 1.0.

### CODE REVIEW

**Comment by gyfora** [comment]
I verified the intended behaviour on a cluster application, it works for cancelling from both the command line and also from the web interface.

+1 from my side, this is a critical fix for production environments

**Comment by StephanEwen** [comment]
Looks good. I am wondering, though, whether RESTARTING jobs should be rather listed among RUNNING jobs?

**Comment by StephanEwen** [comment]
Pretty nice otherwise, +1

**Comment by uce** [comment]
I've updated the PR as you suggested and rebased on the current master. Waiting for Travis. After that I, think it is ready to be merged to `release-0.10` and `master`.

**Comment by uce** [comment]
Failed test is unrelated. Merging...

**Pull request closed without merging**
