### PR TITLE
[CLEANUP] Add space between quotes and plus sign in String concat for readability in flink-yarn module

### PR DESCRIPTION
**Pull request by hsaputra**
While working on Flink on YARN, do some simple nit cleanups to add space between quote and plus sign for readability in yarn module for readability.

Use StringBuilder instad of StringBuffer in FlinkYarnClient since the String materializes immediately, so no need synchronize protection.

### CODE REVIEW

**Comment by StephanEwen** [comment]
I like this.
I would actually like to make this a checkstyle rule. Most of the code is in this shape, occasional files go with a different style.

**Comment by hsaputra** [comment]
+1

We agree that we would play it loose with style but this kind of cleanup helps readability.

I will send PR to change the check style to be more strict on this kind of violations.

**Comment by hsaputra** [comment]
Builds pass, will merge this EOD if no more comment.

**Comment by StephanEwen** [comment]
+1, good to merge

**Comment by hsaputra** [comment]
Thanks @StephanEwen merging ...

**Comment by uce** [comment]
Thanks Henry, please add this rule. :)

**Comment by rmetzger** [comment]
+1 for adding a rule (otherwise, I will not learn it ;) )

**Comment by hsaputra** [comment]
Thanks all, will do

**Pull request closed without merging**
