### PR TITLE
[FLINK-21367][Connectors / JDBC] Support objectReuse in JDBC sink

### PR DESCRIPTION
**Pull request by Bruschkov**
## What is the purpose of the change
* Users should now be able to use the jdbc-sink when object reuse is enabled (or from stateful functions, where object reuse is enabled explicitly)

## Brief change log

*(for example:)*
  - Jdbc-sink and JdbcOutputFormat now implement InputTypeConfigurable, through which a serializer is obtained for the incoming records. When object reuse is enabled, a copy of each record (via the serializer) is stored in the jdbc-batch, as opposed to the record itself, when object reuse is disabled.

## Verifying this change
This change is a trivial rework / code cleanup without any test coverage.
## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): don't know
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation
  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by rkhachatryan** [comment]
@flinkbot run azure

**Comment by rkhachatryan** [comment]
Hi @Bruschkov, are you still working on this PR?
(it would be nice to have it in 1.14)

**Comment by Bruschkov** [comment]
Hi @rkhachatryan ,
in principle yes, I was a bit short on time in the last couple of weeks.

In Principle this is in "LGTM"-status and is missing only tests, yes?

Best regards
Jan

**Comment by rkhachatryan** [comment]
Yes, production code changes LGTM, only some tests are missing.
Thanks!

**Comment by rkhachatryan** [comment]
Hi @Bruschkov, I've implemented the test in #16528 and also added some refactorings (to the existing code).
Please let me know if you have any concerns about these PRs.

**Comment by Bruschkov** [comment]
Hi @rkhachatryan 
looking good, thanks for adding the tests!

Please merge as you see fit, I have nothing to add.

Best regards

**Pull request closed without merging**
