### PR TITLE
[FLINK-26961][BP-1.14][connectors][filesystems][formats] Update Jackson Databi…

### PR DESCRIPTION
**Pull request by snuyanzin**
This is a 1.14 backport of PR https://github.com/apache/flink/pull/19303

### CODE REVIEW

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Comment by snuyanzin** [comment]
probably the reason of failing is 
```
Apr 04 11:16:48 Failure: There are unwanted classes in the /home/vsts/work/1/s/flink-end-to-end-tests/../flink-table/flink-table-planner/target/flink-table-planner_2.11-1.14-SNAPSHOT.jar jar: META-INF/versions/9/module-info.class
```
currently not clear how to fix it

**Comment by MartijnVisser** [comment]
Ah I assumed it was a broken test 🙈 

To resolve that we need to have a look at https://github.com/apache/flink/blob/release-1.14/flink-table/flink-table-planner/pom.xml#L348-L358

It's probably required to add `<exclude>META-INF/versions/9/module-info.class</exclude>`. Most likely caused because this newer version of Jackson compiles for multiple Java versions.

**Comment by snuyanzin** [comment]
@flinkbot run azure

**Comment by snuyanzin** [comment]
@MartijnVisser thanks for the hint
it looks it helped

**Review by MartijnVisser — APPROVED** [review]
LGTM

**Comment by MartijnVisser** [comment]
@snuyanzin Thank you for the PR! Much appreciated

**Pull request merged**
