### PR TITLE
[FLINK-25000][BUILD] Upgrade Scala 2.12.15

### PR DESCRIPTION
**Pull request by pan3793**
## What is the purpose of the change

Upgrade Scala 2.12.15 to support JDK 17

https://github.com/scala/scala/releases

## Brief change log

  - Upgrade Scala 2.12.15 

## Verifying this change

  - This change is already covered by existing tests

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): yes
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by pan3793** [comment]
Seem the upgrade breaks testCompatibilityWithFlink_1_3

**Comment by zentol** [comment]
Upgrading Scala at this is not possible since it breaks compatibility with existing Scala applications.

**Comment by MartijnVisser** [comment]
The root cause is explained is https://issues.apache.org/jira/browse/FLINK-12461

**Comment by pan3793** [comment]
Got it, thanks @MartijnVisser

**Pull request closed without merging**
