### PR TITLE
 [FLINK-10209][build] Exclude jdk.tools dependency from hadoop 

### PR DESCRIPTION
**Pull request by zentol**
## What is the purpose of the change

This PR excludes the `jdk.tools` dependency from hadoop when building with java 9. This dependency is for the `tools.jar` that was distributed in jdk8 and below, but no longer present in jdk9+.

## Brief change log

* add `java9` profile that is automatically activated when using java 9
* add `dependencyManagement` entry for `hadoop-common` that excludes the `jdk.tools` dependency
* restrict `japicmp` plugin to flink artifacts
  * This change was necessary since the plugin apparently looks at all artifacts defined in the pom. The added `hadoop-common` entry in the `dependencyManagement` has no version attached and thus can't be resolved on it's own in non-hadoop modules, which always caused the build to fail. Explicitly filtering for flink modules appears to fix this.

## Verifying this change

Use `mvn help:active-profiles` to verify that the profile is not activated on java 8 but on java 9.

I ran this commit (along with other prerequisites for java 9) here: https://travis-ci.org/zentol/flink/builds/423911810

### CODE REVIEW

**Comment by StephanEwen** [comment]
Thanks for the fix!

I assume that it does not work to always exclude the dependency from Hadoop, in Java 8 as well?
What error do we get in that case?

Slightly off topic:

Would it make sense to start moving `flink-hadoop-shaded` to the `flink-shaded` project? We could have simply the latest bugfix of each minor version. That would also allow us to properly analyze dependencies, shade them, get the dependency convergence in Flink under control, etc.

In the long run, we want to encourage exporting the HADOOP_CLASSPATH anyways, rather than adding Hadoop to Flink. The shaded artifacts would be mainly a convenience thing, and we don't  have to match all vendor-specific versions.

**Comment by zentol** [comment]
Echoing my response from the JIRA:

> Travis is passing even if we exclude the dependency in general. However I'm not really comfortable with making this change for jdk8 builds since I don't really know about possible repercussions in different environments.

Moving hadoop to flink-shaded will make it more difficult for users to run hadoop versions that we do not provide directly. This will also help very little in regards to dependency convergence as it is unlikely we will find a setup where all dependencies are converged for different hadoop versions.

**Comment by StephanEwen** [comment]
This context may make my line of thinking easier to understand:

The hadoop-shaded module is a convenience artifact, one where we discussed previously to phase it out eventually. It is used (1) to compile against (for HDFS / YARN / Kerberos code) and (2) to add as a jar to the lib folder.

  - Concerning a general exclusion tor the jdk.tools dependency: Since we don't compile Hadoop itself and we don't redistribute that dependency (it is a system dependency) I cannot see how a general exclusion would be a problem. It simplifies the build files, which is something really good.

  - We should encourage use of HADOOP_CLASSPATH rather than use of our Hadoop fat jar anyways. That reduces the value of the second use of the hadoop-shaded  project, the packaging into the dist lib folder. If we purely go for the HADOOP_CLASSPATH variant, we could remove that project all together and simply have a provided or optional Hadoop dependency.

  - The fat hadoop jar is used for client side functionality only, and since version 2, Hadoop claims to have a stable setup (HDFS protocol, Kerberos config, etc.) , so we don't need each major/minor version, but one of every major version should work. We should not need the vendor specific versions either. And, there is still the HADOOP_CLASSPATH workaround in case any of the vendor-specific versions has a compatibility problem after all.

  - Concerning moving Hadoop to flink-shaded: We don't have to find a setup that converges across Hadoop versions, that is exactly the point. We pick some Hadoop versions for which we want to build convenience jars and converge these manually or by shading.

**Comment by zentol** [comment]
The build files wouldn't be really be simpler; we will still need a jdk9 profile regardless.
I've found too many threads on google where users had issues which could be resolved by adding the `jdk.tools` dependency to consider this a 100% safe change.

Since the degree of simplification is questionable and there are otherwise no benefits to generally excluding the dependency the risks far exceed the rewards. If even a single person is inconvenienced by this it already wasn't worth it.

I will merge the PR as is.

Let's move the discussion for moving hadoop to `flink-shaded` into a dedicated JIRA since it will just get lost here.

**Pull request merged**
