### PR TITLE
[FLINK-3080] Relax restrictions of DataStream.union()

### PR DESCRIPTION
**Pull request by aljoscha**
Before, it would not allow unioning with predecessors (also transitive)
and streams of differing parallelism.

### CODE REVIEW

**Comment by mxm** [comment]
Looks good. Is there a test case for this?

**Comment by vasia** [comment]
Hi @aljoscha,
thanks for fixing this! It seems that, with this change, when you union a stream with itself you get each element twice. If this is intentional, could you please also update the docs?

**Comment by aljoscha** [comment]
Yes, you get each element twice, so it behaves like bag-union.

@mxm I added a test case.

**Comment by aljoscha** [comment]
Also changed the doc.

**Pull request closed without merging**
