### PR TITLE
[FLINK-9758] Fix ContinuousFileProcessingTest failure due to not setting runtimeContext

### PR DESCRIPTION
**Pull request by Myasuka**
## What is the purpose of the change

Fix ContinuousFileProcessingTest failue due to not setting runtimeContext

## Brief change log
ContinuousFileProcessingTest did not set runtime context for monitoringFunction, which will result in UT failure due to IllegalStateException if log level is set to DEBUG, just setRuntimeContext in this test.

## Verifying this change

*(Please pick either of the following options)*

This change is already covered by existing tests, such as *ContinuousFileProcessingTest* with debug-level.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by yanghua** [comment]
looks good from my side~

**Comment by dawidwys** [comment]
Hi @Myasuka ,
Thank you for your contribution. How about extracting it to a helper method e.g. `createTestContinousFileMonitoringFunction`?

**Comment by Myasuka** [comment]
@dawidwys thanks for your suggestion, I have already refactor code with a helper method to create the continuous-monitoring function.

**Comment by dawidwys** [comment]
+1, merging

**Pull request closed without merging**
