### PR TITLE
[FLINK-24099][docs] Refer to nightlies.apache.org

### PR DESCRIPTION
**Pull request by zentol**
The new documentation is hosted under `nightlies.apache.org`.
Note that certain links, like flink-docs-stable, are not setup yet.

### CODE REVIEW

**Comment by dmvk** [comment]
LGTM 👍

**Review by dmvk — CHANGES_REQUESTED** [review]
Some of the links seem to be broken:

eg.
https://ci.apache.org/projects/flink/flink-docs-stable/docs/dev/table/sql/overview/
https://nightlies.apache.org/flink/flink-docs-stable/docs/dev/table/sql/overview/

**Comment by zentol** [comment]
> Note that certain links, like flink-docs-stable, are not setup yet.

**Comment by zentol** [comment]
This is not a problem because flink-web does not point to nightlies.apache.org yet.

**Review by dmvk — APPROVED** [review]
LGTM then! ;)

**Pull request merged**
