### PR TITLE
[FLINK-27051] fix CompletedCheckpoint.DiscardObject.discard is not idempotent

### PR DESCRIPTION
**Pull request by WencongLiu**
## What is the purpose of the change

*fix CompletedCheckpoint.DiscardObject.discard is not idempotent.*

## Brief change log

*(for example:)*
  - *fix CompletedCheckpoint.DiscardObject.discard is not idempotent.*
  - *The data was properly deleted.*
  - *discardObject is called on already (partially) deleted data. -> such a call should NOT throw an exception
An error occurred while deleting the data. -> This should throw an exception*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by WencongLiu** [comment]
@flinkbot run azure

**Comment by XComp** [comment]
Thanks for creating the PR, @WencongLiu . Can you elaborate a bit more on what your goal is here? How do you think the proposed change can make Checkpoint cleanup idempotent?

**Comment by WencongLiu** [comment]
Perhaps my understanding of this method is not quite right. Can you give me some hints?

**Comment by XComp** [comment]
ah sorry, I missed that the boolean variables are set to `true` in the if blocks. Forget what I said. :-D Anyway, can't we just call the clear method when the best effort deletion completed successfully instead? That wouldn't require creating multiple fields here. Additionally, it would be good to have some test cases for that behavior.

**Comment by WencongLiu** [comment]
Yea, the clear method should not be called in 'finally' and should be called when all deletion are completed. My concern is that these functions being called multiple times could throw unnecessary exceptions:

```
metadataHandle.discardState();
StateUtil.bestEffortDiscardAllStateObjects(operatorStates.values());
storageLocation.disposeStorageLocation();
```

A test for this behavior is indeed required.

**Comment by WencongLiu** [comment]
cc @XComp

**Comment by WencongLiu** [comment]
@flinkbot run azure

**Comment by WencongLiu** [comment]
cc @XComp

**Comment by XComp** [comment]
it's on my list of things to do. I will get back to it after the release is finalized.

**Comment by XComp** [comment]
> My concern is that these functions being called multiple times could throw unnecessary exceptions:

That's actually a good point - now I remember the history of this issue: The actual goal is to harden the contract of `StateObject#discardState` instead of introducing some workaround in the calling objects. That's why I started collecting the subtasks under FLINK-26606. FLINK-27051 is actually blocked by the other subtasks, I guess. WDYT?

**Comment by WencongLiu** [comment]
@XComp I'm interested in the background of your ticket. Based on the description, I think the key point of this ticket is that "CompletedCheckpoints are being discarded in CheckpointsCleaner". Could you provide the specific codepath for this? Additionally, I would like to learn more about "the contract of StateObject#discardState" . If these are clear, I would be happy to drive the entire issue.

**Pull request closed without merging**
