### PR TITLE
[FLINK-9452] Flink 1.5 document version title shows snapshot

### PR DESCRIPTION
**Pull request by yanghua**
## What is the purpose of the change

*This pull request fixed 1.5 document version title*

## Brief change log

  - *Removed 1.5-SNAPSHOT to  1.5 version*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by yanghua** [comment]
cc @tillrohrmann @zentol

**Comment by zentol** [comment]
will fix things while merging...

**Comment by yanghua** [comment]
@zentol I have tried to switch to release-1.5 and fix it, but it seems in release-1.5 branch, I can not send a PR correctly, the PR will contains many changes.

**Comment by alpinegizmo** [comment]
@zentol I think the baseurl variable also needs to be changed -- for a stable release, it should not point to master.

**Comment by zentol** [comment]
@alpinegizmo nice catch!

**Comment by zentol** [comment]
merged, @yanghua please close the PR. Thanks!

**Comment by yanghua** [comment]
ok, closing...

**Pull request closed without merging**
