### PR TITLE
 [FLINK-5006] SystemProcessingTimeServiceTest.testTimerSorting fails

### PR DESCRIPTION
**Pull request by BorisOsipov**
Hello!

I'v reproduced this issue on my environment several times.
I found that the test uses ScheduledThreadPoolExecutor  as threadFactory (actually [SystemProcessingTimeService](https://github.com/apache/flink/blob/master/flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SystemProcessingTimeService.java) uses). ScheduledThreadPoolExecutor does not guarantee that tasks will be executed immediately after delay:

> Delayed tasks execute no sooner than they are enabled, but without any real-time guarantees about when, after they are enabled, they will commence. 

See Oracle [docs ](http://bit.ly/2fobpXv)
Thus, order of executions and adding timestamps to ArrayBlockingQueue isn't defined. So it looks like the test is not correct.
In changes I increased intervals between tasks, it helps to avoid falling. 
If I am correct, maybe it makes sense to get rid of this test?

### CODE REVIEW

**Comment by StephanEwen** [comment]
I guess the problem is that when the tasks get registered at the `ScheduledThreadPoolExecutor`, multiple tasks may have a delay of zero, which makes the order of triggering undefined.

What do you think?

**Comment by BorisOsipov** [comment]
Yes it is. The ThreadPoolExecutor is not claiming to be a real-time system with any sort of timing guarantees. 
The only thing it will guarantee is that it doesn't run tasks too early.

**Comment by StephanEwen** [comment]
It's not about timing guarantees here, only about order of running timers.
The problem is that they are sorted by the delay which is affected by races/stalls, rather than by proper timestamp.

Since Flink actually relies on timer triggering order, I think we need to implement our own timer service, which sorts by actual timestamp, rather than by delay.

**Comment by aljoscha** [comment]
@StephanEwen I think it's not a problem that these physical, low-level timers don't fire in order of their timestamp because the ordering of timers is maintained in the implementation of `InternalTimerService` (in a queue in the current implementation). Also, under normal circumstances we only have one active timer at the `ProcessingTimeService` (`SystemProcessingTimeService`).

**Comment by StephanEwen** [comment]
@aljoscha Okay, if that is the only thing that we use it for, then order is indeed not important for that service. Are we sure it is not used in other places?

**Comment by aljoscha** [comment]
@StephanEwen It's used to drive the automatic watermark generation and the inactivity timer in the `BucketingSink`, but those are cases where the order doesn't matter.

**Comment by StephanEwen** [comment]
Okay, if that is the case, then we should probably simply remove the "test timer sorting" test and note down that this does not give any guarantees on the order of timers.

@BorisOsipov What do you think about this?

**Comment by BorisOsipov** [comment]
@aljoscha thank you for additional research and comments.
@StephanEwen I think we can remove it as I proposed earlier.

I'v removed test and added javadoc to registerTimer method. Please look at this.
Is it ok?

**Comment by StephanEwen** [comment]
Looks good, merging this!

Thanks, @BorisOsipov for bearing with us on this one through the long discussion!

**Pull request closed without merging**
