### PR TITLE
[hotfix][docs-zh] Delete redundant lines in pulsar.md

### PR DESCRIPTION
**Pull request by zhuanshenbsj1**
## What is the purpose of the change
**A few lines(about java11) in  Chinese pulsar document are redundant.**

**English document：**
image
**Chinese document：**
image

## Brief change log

Delete redundant lines in pulsar.md.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

### CODE REVIEW

**Comment by MartijnVisser** [comment]
@zhuanshenbsj1 Thanks for this, but I actually think this should not be removed from the Chinese version but added to the English documentation

**Comment by zhuanshenbsj1** [comment]
> @zhuanshenbsj1 Thanks for this, but I actually think this should not be removed from the Chinese version but added to the English documentation

@MartijnVisser  Thanks for your reply , I have adjusted the doc of two versions to be consistent.

**Comment by MartijnVisser** [comment]
@syhily Can you confirm this?

**Review by MartijnVisser — APPROVED** [review]
LGTM

**Pull request merged**
