### PR TITLE
[FLINK-4359] [table] Add INTERVAL type

### PR DESCRIPTION
**Pull request by twalthr**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

This PR introduces INTERVAL types for Table API/SQL. Here are some examples how intervals can be used in the APIs. More examples can be found in `TemporalTypesTest`.

```
 testAllApis(
    1.year,
    "1.year",
    "INTERVAL '1' YEAR",
    "+1-00")

testAllApis(
    'f0 + 2.day,
    "f0 + 2.day",
    "f0 + INTERVAL '2' DAY",
    "1990-10-16")
```

### CODE REVIEW

**Comment by twalthr** [comment]
@aljoscha would be great if you could have a quick look on it.

**Comment by aljoscha** [comment]
Is the `INTERVAL` prefix needed to make it work with the parser? Otherwise it would be nice to just write `2 DAYS`, or something like that.

By the way, the reason for the two different interval types is that the millis type does not have enough range to represent years?

**Comment by twalthr** [comment]
The first line is Scala Table API, second line is Java Table API and the string with the INTERVAL prefix is standard SQL. So we cannot change the standard ;)

Yes, I think that is the reason. Calcite does it like that and Oracle too.
https://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements003.htm#i38598

**Comment by aljoscha** [comment]
Ok, I figured as much. A bit ugly but I guess everyone has to do it like this. 😅 

From a quick glance the API and implementation look good. 👍

**Comment by twalthr** [comment]
Merging this...

**Pull request closed without merging**
