### PR TITLE
[FLINK-2798] Serve static files for the new web frontend from the classloader

### PR DESCRIPTION
**Pull request by rmetzger**
This pull request is based on https://github.com/apache/flink/pull/1202.

In order to make the new web interface run on YARN, I changed the way how static files are loaded: They are now loaded using the classloader.

### CODE REVIEW

**Comment by StephanEwen** [comment]
I gave some comments on the commit.

Looks mainly good, I am only confused why you changed all request URLs to relative from absolute. This may have other implications. If it is just to get rid of a "slash" in when creating the file path, you should probably rather prune repeated slashes instead...

**Comment by rmetzger** [comment]
Thank you for the review. I'm trying to update the PR within the next 24 hours
Sorry for not explaining why I changed all the request URLs to relative paths: When accessing the web interface through YARN, the files are not served from the root address, but using a proxy from the RM ` http://quickstart.cloudera:8088/proxy/application_1440768826963_0005/`.
By making all request URLs relative, we can make sure everything is working as expected.

Let me know if there is a more elegant way of avoiding this.
I made a similar change to the old web interface.

**Comment by uce** [comment]
Note: We have to check the startup logic of my changes in the YARN case as well (either in this PR or the other one).

**Comment by rmetzger** [comment]
I will wait until your pull request is merged to master.

**Comment by rmetzger** [comment]
Max took the relevant changes from this PR into https://github.com/apache/flink/pull/1246. Closing ...

**Pull request closed without merging**
