### PR TITLE
[FLINK-12621]. Use MiniCluster instead of JobExecutor

### PR DESCRIPTION
**Pull request by zjffdu**
## What is the purpose of the change

This is a refactoring PR which remove `JobExecutor` and use `MiniCluster` instead. `JobExecutor` is specifically used for local mode, I don't think we need to introduce such kind of new class/interface for local mode, we could just use the existing `MiniCluster`.

## Brief change log

* Remove `JobExecutor` &  `JobExecutorService`
* Use `ClusterClient` to replace `JobExecutorService`

## Verifying this change

Current CI is passed, no new code is introduced, just some refactoring.

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by zjffdu** [comment]
@tillrohrmann  Could you help review it ? I notice you are original author of `JobExecutor`.

**Comment by zjffdu** [comment]
@tillrohrmann  Thanks for the review. I think we should unify the flink's local client and remote client. This is related with https://github.com/apache/flink/pull/8533 which also try to unify them in scala shell. 
I don't think we should differentiate local client and remote client in api perspective. Otherwise it is very difficult for downstream project to integrate with flink. E.g. I have already hit issues when integrating flink into zeppelin notebook because of flink's api difference in local mode and remote mode. Does it make sense to you ?

**Comment by tillrohrmann** [comment]
I understand the general idea @zjffdu. What I'm unsure about is where exactly the `JobExecutorService` poses a problem because it should only be used by the `LocalExecutor` internally. As far as I know, this interface should not be leaked anywhere.

I guess the best thing to do would be to create a design document which describes how Flink's client should look like in the future. Until then, we should close this PR.

**Comment by TisonKun** [comment]
ref #9643 and [FLINK-13961](https://issues.apache.org/jira/browse/FLINK-13961).

**Comment by kl0u** [comment]
Isn't also this the same as this https://github.com/apache/flink/pull/9643 discussion which seems to have been already resolved? This is the other duplicate jira https://issues.apache.org/jira/browse/FLINK-13961

**Comment by zjffdu** [comment]
That's right @kl0u , I will close this PR

**Pull request closed without merging**
