### PR TITLE
[FLINK-7702] Fix Javadoc build issues

### PR DESCRIPTION
**Pull request by aljoscha**
This remove the `genjavadoc` tool which doesn't work with our code base right now and also adds a dependency in the root pom that is needed for building the Javadocs (description in the commit).

R: @twalthr

### CODE REVIEW

**Comment by twalthr** [comment]
@aljoscha I tried to build the docs on my local machine but it still fails with:

```
[ERROR] Error while creating javadoc report: Missing:
----------
1) org.apache.directory.jdbm:apacheds-jdbm1:bundle:2.0.0-M2

  Try downloading the file manually from the project website.

  Then, install it using the command:
      mvn install:install-file -DgroupId=org.apache.directory.jdbm -DartifactId=apacheds-jdbm1 -Dversion=2.0.0-M2 -Dpackaging=bundle -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there:
      mvn deploy:deploy-file -DgroupId=org.apache.directory.jdbm -DartifactId=apacheds-jdbm1 -Dversion=2.0.0-M2 -Dpackaging=bundle -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency:
  	1) org.apache.flink:flink-connector-kafka-base_2.11:jar:1.5-SNAPSHOT
  	2) org.apache.hadoop:hadoop-minikdc:jar:2.7.2
  	3) org.apache.directory.server:apacheds-jdbm-partition:jar:2.0.0-M15
  	4) org.apache.directory.jdbm:apacheds-jdbm1:bundle:2.0.0-M2

----------
1 required artifact is missing.

for artifact:
  org.apache.flink:flink-connector-kafka-base_2.11:jar:1.5-SNAPSHOT
```

Using: `mvn javadoc:aggregate -DadditionalJOption="-Xdoclint:none" -Dmaven.javadoc.failOnError=false`

**Comment by aljoscha** [comment]
Did you use the branch that has both commits? Not the first PR that doesn't have the `maven-bundle-plugin` fixes?

**Comment by aljoscha** [comment]
For me it does work locally but it could be an issue that I have something in my caches that you don't have. Which would be bad because then it wouldn't work on the buildbot either.

**Comment by twalthr** [comment]
Wait I might build the wrong branch. Let me check it again.

**Comment by twalthr** [comment]
It worked. +1 for this.

**Pull request merged**
