### PR TITLE
[FLINK-18631] [serialization] Serializer for scala sealed trait hierarchies

### PR DESCRIPTION
**Pull request by shuttie**
## What is the purpose of the change

A [custom serializer for scala ADT](https://issues.apache.org/jira/browse/FLINK-18631) non-recursive sealed trait class hierarchies. Using ADTs in Scala with Flink always resulted in severe performance degradation due to Kryo fallback, which we hopefully trying to address in this PR. 

Example code which is handled by this serializer:
```
sealed trait Event {
  def id: Int
}
case class Pageview(id: Int, page: String) extends Event
case class Click(id: Int, url: String) extends Event
```

Recursive ADTs are not supported, as it may require some refactoring inside of the `TypeAnalyzer`. 

Example of unsupported code:
```
sealed trait Tree
case class Node(left: Tree, right: Tree) extends Tree
case class Leaf(value: Int) extends Tree
```

## Brief change log

  - SealedTraitSerializer and SealedTraitTypeInfo implementation for sealed trait serialization support.
  - add a test for SealedTraitTypeInfo
  - PR to apache/flink-benchmarks with benchmark code showing the impact
  - add migration support if ADT is extended with new members
  - mention limitations of ADT support in the docs (like generic ADTs)

## Verifying this change

This change added tests and can be verified as follows:
- added a normal and nested ADT tests to ScalaSpecialTypesSerializerTest
- added new test SealedTraitSerializerTest
- added a test SealedTraitSerializerCompatibilityTest to check compatibility in ScalaSealedTraitSerializerSnapshot

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: **yes**
  - The runtime per-record code paths (performance sensitive): **yes**
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? **a separate paragraph in docs**

### CODE REVIEW

**Comment by shuttie** [comment]
Benchmark results for flink-scala-1.12-SNAPSHOT-20200720:
```
SerializationFrameworkMiniBenchmarks.serializerScalaADT  thrpt  custom  30  2506.848 ± 66.692  ops/ms
SerializationFrameworkMiniBenchmarks.serializerScalaADT  thrpt  kryo    30  450.202  ± 15.389  ops/ms
```
5.56 times faster than Kryo.

**Comment by shuttie** [comment]
@flinkbot run azure

**Comment by shuttie** [comment]
@rmetzger is there any chance that this PR can be reviewed?

**Comment by rmetzger** [comment]
Sorry for the delay. I try to find somebody who can take a look.

**Comment by rmetzger** [comment]
Note: There's a comment in the JIRA ticket.

**Comment by jvican** [comment]
Hi! Is there any blocker to get this merged?

**Comment by zentol** [comment]
Scala APIs are deprecated. Any potential serializer implementation for Scala types must be implemented in Java (if at all).

**Pull request closed without merging**
