### PR TITLE
[FLINK-17255][python] Add HBase connector descriptor support in PyFlink.

### PR DESCRIPTION
**Pull request by shuiqiangchen**
## What is the purpose of the change

HBase connector descriptor is already supported since 1.10.0 at Java side. We should also support it in PyFlink.

## Brief change log
 - add HBase connector descriptor methods corresponding to java side in descriptors.py
 - add HBaseDescriptorTests in test_descriptors.py
 - add HBase connector usage documentation in connect.md

## Verifying this change

This change added tests and can be verified as follows:

- added HBaseDescriptorTests in test_descriptors.py

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? ( no)

### CODE REVIEW

**Comment by dianfu** [comment]
@flinkbot run azure

**Comment by dianfu** [comment]
@zentol Do you know why the CI was not triggered even manually triggered with `@flinkbot run azure`?

**Comment by dianfu** [comment]
@flinkbot run azure

**Comment by shuiqiangchen** [comment]
@flinkbot run azure

**Comment by dianfu** [comment]
@shuiqiangchen Thanks for the PR. LGTM. Merging...

**Pull request merged**
