### PR TITLE
[BP-1.12][FLINK-22434] Store suspended execution graphs on termination to keep them accessible

### PR DESCRIPTION
**Pull request by fapaul**
Backport of #15799 
@tillrohrmann Can you have another look at 5638689? I resolved a lot of conflicts for this commit

### CODE REVIEW

**Comment by tillrohrmann** [comment]
What was the main problem why you had the merge conflicts @fapaul?

**Review by tillrohrmann — APPROVED** [review]
From what I can tell, the changes look good to me. Let's see what CI says. If it gives green light, then it should be fine.

**Comment by fapaul** [comment]
> What was the main problem why you had the merge conflicts @fapaul?

It was mainly based on the fact the `JobManagerRunnerImpl` was refactored in 1.13 into the `JobMasterServiceLeadershipRunner`. So for 1.12, I had to put in some thoughts on how to achieve the same behaviour.

**Comment by fapaul** [comment]
@flinkbot run azure

**Pull request merged**
