### PR TITLE
[FLINK-5954] Always assign names to the window in the Stream SQL API.

### PR DESCRIPTION
**Pull request by haohui**
Please see jira for more details.

### CODE REVIEW

**Comment by sunjincheng121** [comment]
HI, @haohu thanks for your contribution!
Can you tell me why we need this change? and can you add simple unit test ?

Best,
SunJincheng

**Comment by haohui** [comment]
Sorry for the late response. This is a prerequisite step for FLINK-6012 -- translating the group auxiliary functions (e.g., `TUMBLE_START`) to the corresponding Flink expressions (e.g., `WindowStart`).

A more detailed description is on the FLINK-5954.

**Comment by sunjincheng121** [comment]
Hi, @haohui Thanks for your explanation, and I'll  see the  detail in the FLINK-5954.
Thanks,
SunJincheng

**Comment by fhueske** [comment]
Thanks for the PR @haohui.
Looks good to me. +1 to merge

**Pull request closed without merging**
