### PR TITLE
[FLINK-13789] move prefix out of the format string

### PR DESCRIPTION
**Pull request by haodang**
## What is the purpose of the change

Fixing https://issues.apache.org/jira/browse/FLINK-13789 by moving `prefix` out of the format string.

## Brief change log

- moving `prefix` out of the format string

## Verifying this change

This change is almost a trivial rework and we've been running such a version on our production environment and have verified the fix.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by haodang** [comment]
@carp84, Thank you, Yu!  Let me add a unit test.
Not sure of why the build failed, will investigate.

**Comment by StephanEwen** [comment]
If we are now doing string concatenation anyways, should we just remove `String.format` all together here? In this way (mixing the two) it seems a bit strange (and is probably also a bit less efficient).

**Comment by TisonKun** [comment]
make sense to change it into

```java
    return prefix + "-" + transactionalId;
```

since we don't want to do more format job here.

**Comment by zentol** [comment]
@flinkbot run travis

**Pull request merged**
