### PR TITLE
[FLINK-28698][runtime-web] fix order of aggregate durations to follow task state transitions

### PR DESCRIPTION
**Pull request by yangjunhan**
## What is the purpose of the change

This PR closes FLINK-28698, which it fix the order of aggregated metrics status durations in order to follow the natural task state transitions: CREATED, SCHEDULED, DEPLOYING, INITIALIZING, RUNNING

## Brief change log

Change the table row order to CREATED, SCHEDULED, DEPLOYING, INITIALIZING, RUNNING.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by yangjunhan** [comment]
Hi, @xintongsong . This fix is relatively trivial. Could you help me review and merge this?

**Review by xintongsong — APPROVED** [review]
Thanks @yangjunhan. LGTM. Merging this once the CI passes.

**Comment by yangjunhan** [comment]
@xintongsong Besides the previous commit, I have also fixed the order of duration badges in the subtask table. Please take a look at that as well, thanks.
image

**Review by xintongsong — APPROVED** [review]
LGTM

**Comment by xintongsong** [comment]
@flinkbot run azure

**Pull request closed without merging**
