### PR TITLE
[FLINK-16533] [client] ExecutionEnvironment supports execution of existing plan

### PR DESCRIPTION
**Pull request by godfreyhe**
## What is the purpose of the change

*Add two methods in ExecutionEnvironment to support execution of existing plan:
public class ExecutionEnvironment {
    @Internal
    public JobExecutionResult execute(Plan plan) throws Exception {
    .....
    }

    @Internal
    public JobClient executeAsync(Plan plan) throws Exception {
    .....
    }
}

Those added methods are internal, and are similar to StreamExecutionEnvironment#execute(StreamGraph) and StreamExecutionEnvironment#executeAsync(StreamGraph)*

## Brief change log

  - *add execute(Plan) and executeAsync(Plan) in ExecutionEnvironment, and adapt it's sub-classes to implement new methods*
  - *Extract plan generation logic to PlanGenerator*

## Verifying this change

This change added tests and can be verified as follows:

  - *Added PlanGeneratorTest for plan generation*
  - *Extended ExecutionEnvironmentITCase for execution of existing plan*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (**yes** / no)
  - If yes, how is the feature documented? (not applicable / docs / **JavaDocs** / not documented)

### CODE REVIEW

**Comment by kl0u** [comment]
Hi @godfreyhe ! Given that the discussion on FLIP-84 is not done (according to https://cwiki.apache.org/confluence/display/FLINK/Flink+Improvement+Proposals), could you close this PR?

**Comment by godfreyhe** [comment]
@kl0u I sorry I forgot to update the `Adopted/Accepted but unreleased FLIPs` list, I update it now. in fact it was accepted (http://mail-archives.apache.org/mod_mbox/flink-dev/202003.mbox/%3CCADQYLGv1KbwJMeQTxN8gdUq__pctZcH%3DfJe16R_ygNmKoj%3D8Rg%40mai )

**Comment by twalthr** [comment]
Sorry, for entering the discussion around FLIP-84 so late @godfreyhe. But maybe we need to change something in the design again. I will discuss this with others in a couple of days.

**Comment by godfreyhe** [comment]
hi @twalthr. I will suspend the related work of FLIP-84 and wait your feedback.

**Comment by godfreyhe** [comment]
hi @twalthr. I will suspend the related work of FLIP-84 and wait your feedback.

**Comment by kl0u** [comment]
@godfreyhe Can you close this PR? From the JIRA discussion it seems that we decided to go with a different solution, right?

**Comment by godfreyhe** [comment]
@kno10 thanks for reminding, I closed it.

**Pull request closed without merging**
