### PR TITLE
[FLINK-27088][Documentation] Fix the example of using StringDeseriali…

### PR DESCRIPTION
**Pull request by ZP315**
[FLINK-27088][Documentation] Fix the example of using StringDeserializer for deserializing Kafka message value as string 

## What is the purpose of the change

This pull request fixed the example of using StringDeserializer for deserializing Kafka message value as string.

## Brief change log

  - Replacing StringSerializer with StringDeserializer

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by MartijnVisser — APPROVED** [review]
LGTM. Let's get this merged when the CI has passed

**Comment by MartijnVisser** [comment]
And thanks for the PR @ZP315  :) - When this is merged, could you also create a backport towards the `release-1.15` and `release-1.14` branch and ping me so I can merge those?

**Comment by ZP315** [comment]
> And thanks for the PR @ZP315 :) - When this is merged, could you also create a backport towards the `release-1.15` and `release-1.14` branch and ping me so I can merge those?

Yes, It's a great pleasure to do.

**Comment by ZP315** [comment]
> And thanks for the PR @ZP315 :) - When this is merged, could you also create a backport towards the `release-1.15` and `release-1.14` branch and ping me so I can merge those?

Thank you for your reviews and approval.
I have created a pull request in [https://github.com/apache/flink/pull/19383](https://github.com/apache/flink/pull/19383)  for release-1.15 branches and [https://github.com/apache/flink/pull/19382](https://github.com/apache/flink/pull/19382)  for release-1.14 branches.

**Pull request merged**
