### PR TITLE
[FLINK-24886][core] TimeUtils supports the form of m.

### PR DESCRIPTION
**Pull request by liuyongvs**
## What is the purpose of the change

*TimeUtils supports the form of m, which fits user habits*

### CODE REVIEW

**Review by snuyanzin — APPROVED** [review]

**Comment by Thesharing** [comment]
I think it's great to support using "m" to denote minutes. But I think we shouldn't change the existing configurations from "min" to "m". It breaks consistency of configuration across versions and confuses the users.

**Comment by liuyongvs** [comment]
@Thesharing , but if not modified the  existing configurations, it will throw exception. and the "m" is also supports. so i think it is not problem, what do you think @tillrohrmann

**Review by tillrohrmann — CHANGES_REQUESTED** [review]
Why will it throw an exception @liuyongvs? I think this is a sign that we shouldn't merge this change as is. Moreover, why does this PR changes so many unrelated files? If we support "m", then we should keep supporting "min" as well.

**Comment by liuyongvs** [comment]
> Why will it throw an exception @liuyongvs? I think this is a sign that we shouldn't merge this change as is. Moreover, why does this PR changes so many unrelated files? If we support "m", then we should keep supporting "min" as well.

it is not  unrelated files. because the unit test  will compare and make it not passed. That is why i commit serveral times.

**Review by tillrohrmann — COMMENTED** [review]
But why do you touch all these unrelated files like `WindowTableFunctionTest.xml`? or the `WindowAggregateTest.xml`?

**Comment by hililiwei** [comment]
Can 'm' and 'min' be supported at the same time?

**Comment by liuyongvs** [comment]
hi @Thesharing @tillrohrmann sorry for late response. if we do not want to make changes such as docs and many file, we can change code from
MINUTES(ChronoUnit.MINUTES, singular("min"), plural("minute")),
 to this        
 MINUTES(ChronoUnit.MINUTES, singular("min"), singular("m"), plural("minute")),
wil you receive it or just simple modify the comments from 10 m to 10 min

rest.flamegraph.cleanup-interval
after which cached stats are cleaned up if not accessed. It can"
                                + " be specified using notation: \"100 s\", \"10 m\"."

**Comment by Thesharing** [comment]
> hi @Thesharing @tillrohrmann sorry for late response. if we do not want to make changes such as docs and many file, we can change code from MINUTES(ChronoUnit.MINUTES, singular("min"), plural("minute")), to this MINUTES(ChronoUnit.MINUTES, singular("min"), singular("m"), plural("minute")), wil you receive it or just simple modify the comments from 10 m to 10 min
> 
> rest.flamegraph.cleanup-interval after which cached stats are cleaned up if not accessed. It can" + " be specified using notation: "100 s", "10 m"."

This makes me a bit confused. I get that the core change of this improvement is `MINUTES(ChronoUnit.MINUTES, singular("m"), singular("min"), plural("minute"))`. I'm wondering what test cases is not passed after the change and why they are broken. Would you please list all the test cases that are not passed?

**Comment by liuyongvs** [comment]
@Thesharing it will need modify lots of files. you can see my commits before such as docs and XXplan.out, which will validate the plan contents

**Comment by liuyongvs** [comment]
hi @Thesharing , orignial commits are 4, i just reset the first commit and rebase code, then ci is running and you can see the log

**Comment by Thesharing** [comment]
> hi @Thesharing , orignial commits are 4, i just reset the first commit and rebase code, then ci is running and you can see the log

Thank you for the rebasing the code. I've checked the failed test cases. If we make sure the order of minute units stay the same , the broken tests will pass.

Would you mind change the line
```
MINUTES(ChronoUnit.MINUTES, singular("m"), singular("min"), plural("minute"))
```
into
```
MINUTES(ChronoUnit.MINUTES, singular("min"), singular("m"), plural("minute"))
```
and run the CI again?

**Comment by tillrohrmann** [comment]
> > hi @Thesharing , orignial commits are 4, i just reset the first commit and rebase code, then ci is running and you can see the log
> 
> Thank you for rebasing the code. I've checked the failed test cases. If we make sure the order of minute units stay the same , the broken tests will pass.
> 
> Would you mind change the line
> 
> ```
> MINUTES(ChronoUnit.MINUTES, singular("m"), singular("min"), plural("minute"))
> ```
> 
> into
> 
> ```
> MINUTES(ChronoUnit.MINUTES, singular("min"), singular("m"), plural("minute"))
> ```
> 
> and run the CI again?

Why is the order of units important?

**Comment by Thesharing** [comment]
> Why is the order of units important?

Because [tests](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=29288&view=logs&j=0c940707-2659-5648-cbe6-a1ad63045f0a&t=075c2716-8010-5565-fe08-3c4bb45824a4&l=25123) like `StreamOperatorNameTest` will generate optimized plans based on the first one of the units, i.e. "min". If we change the code into `MINUTES(ChronoUnit.MINUTES, singular("m"), singular("min"), plural("minute"))`, the first one is "m" instead of "min". Then the plans will be generated with "m", which makes these tests failed. That's why @liuyongvs touches those unrelated files like `WindowTableFunctionTest.xml` and `WindowAggregateTest.xml`. He changes "min" into "m" in these files. 

If we change the order into `MINUTES(ChronoUnit.MINUTES, singular("min"), singular("m"), plural("minute"))`, these tests shall be passed.

test-case

**Comment by tillrohrmann** [comment]
Thanks for the clarification @Thesharing. This makes sense.

**Comment by liuyongvs** [comment]
> ```
> MINUTES(ChronoUnit.MINUTES, singular("min"), singular("m"), plural("minute"))
> ```

yes, but if we change to MINUTES(ChronoUnit.MINUTES, singular("min"), singular("m"), plural("minute")). i worry the user later may be weird。 if you think it is ok, i will change the order.

**Comment by liuyongvs** [comment]
hi @tillrohrmann @Thesharing  ci passed now

**Comment by liuyongvs** [comment]
hi @tillrohrmann @Thesharing ,do you have time ,sorry to @ you

**Review by tillrohrmann — APPROVED** [review]
Thanks for creating this PR @liuyongvs. LGTM. Merging this now.

**Pull request closed without merging**
