### PR TITLE
[FLINK-28019][table] fix error when retract a staled record if state ttl enabled in RetractableTopNFunction

### PR DESCRIPTION
**Pull request by lincoln-lil**
## What is the purpose of the change
We found an error occurred when retract a staled record when enable state ttl in RetractableTopNFunction, the reason is the uncomplete path when deal with staled records. This should be fixed.

## Brief change log
update the staled record error handling logic in retractRecordWithRowNumber and processElement of the RetractableTopNFunction.

## Verifying this change
add new tests for RetractableTopNFunctionTest

## Does this pull request potentially affect one of the following parts:
  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with @Public(Evolving): (no)
  - The serializers: (no )
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation
  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by lincoln-lil** [comment]
The failure case "org.apache.flink.connector.kafka.sink.FlinkKafkaInternalProducerITCase#testInitTransactionId" is irrelevant.

**Comment by lincoln-lil** [comment]
@flinkbot  run azure

**Comment by lincoln-lil** [comment]
@flinkbot run azure

**Review by JingsongLi — APPROVED** [review]
Looks good to me!

**Pull request merged**
