### PR TITLE
[FLINK-2408] Define all maven properties outside build profiles

### PR DESCRIPTION
**Pull request by rmetzger**
See JIRA issue for details.

@aalexandrov, can you take a look at this?

### CODE REVIEW

**Comment by aalexandrov** [comment]
Is the removal of the property-based activation (`-Dscala-2.11`) also intentional? I think this might be used in the travis.yml.

**Comment by rmetzger** [comment]
I don't think that I'm removing the activation of the `scala-2.11` profile.
If the `scala-2.11` property is set, the default value of the property will be overwritten to scala 2.11

**Comment by aalexandrov** [comment]
Then it should be good to merge.

**Comment by chiwanpark** [comment]
Hi, pom.xml file of flink-scala module has also profile based dependency setting. Is it okay without modification?

**Comment by aalexandrov** [comment]
If sbt can resolve profile-based dependencies this should be OK.

**Comment by rmetzger** [comment]
sbt can't do that.
We are lucky here because the `maven-shade-plugin` is generating a dependency-reduced pom with the effective settings.
(Take a look in your `/home/robert/.m2/repository/org/apache/flink/flink-scala/0.10-SNAPSHOT/flink-scala-0.10-SNAPSHOT.pom` directory to see how the deployed POM looks like)

**Comment by aalexandrov** [comment]
I guess the "s" in the name is the giveaway...

**Comment by chiwanpark** [comment]
Do this PR need modification? It seems good to merge.

**Comment by rmetzger** [comment]
I will rebase and merge it.

**Pull request closed without merging**
