### PR TITLE
[FLINK-8596][CLI] Also catch NoClassDefFoundErrors

### PR DESCRIPTION
**Pull request by zentol**
## What is the purpose of the change

This PR modifies the CliFrontend to also catch `NoClassDefFoundErrors` when loading the YARN CLI, as otherwise the entire CLI would crash if hadoop wasn't on the classpath.

## Verifying this change

This change added tests an end-to-end test that is run on travis.

### CODE REVIEW

**Comment by aljoscha** [comment]
+1 to merge

**Comment by zentol** [comment]
E2E test isn't fully working yet, debugging...

**Comment by aljoscha** [comment]
There's also a `ClassNotFoundException` in the logs, which is not ignored.

**Comment by zentol** [comment]
merging.

**Pull request closed without merging**
