### PR TITLE
[hotfix][Runtime/Configuration] Fix typo in ProcessMemoryUtils Class

### PR DESCRIPTION
**Pull request by zhuyufeng0809**
## What is the purpose of the change

Fix log information typo in sanityCheckJvmOverhead method of ProcessMemoryUtils Class

## Brief change log

modified the case of a string word in sanityCheckJvmOverhead method of ProcessMemoryUtils Class

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by zhuyufeng0809** [comment]
Hi @Myasuka , could you help me to review this PR

**Review by Myasuka — APPROVED** [review]
LGTM.

**Comment by zhuyufeng0809** [comment]
@Myasuka Sorry, this is caused by my wrong operation of my fork repository. I deleted the branch of the PR in my fork repository. I thought it would have no impact, but after deletion, I found that the PR was automatically closed and I could not reopen it. I created a branch with the same name, but I still can't reopen it. This gave me a lesson. Sorry, I won't do it again

**Comment by zhuyufeng0809** [comment]
emmmmm I click the restore button, which seems to restore the branch I deleted

**Comment by Myasuka** [comment]
@flinkbot run azure

**Comment by zhuyufeng0809** [comment]
Hi @Myasuka , can this PR be merged or need do something else?

**Comment by Myasuka** [comment]
Just merged.

**Pull request merged**
