### PR TITLE
[hotfix][javadocs] Fix the doc content in the createFieldGetter method of RowData

### PR DESCRIPTION
**Pull request by chenzihao5**
## What is the purpose of the change

I found a doc error that it should be position instead of type.

## Brief change log

3434897fc4707240e27650d457b7e86250e7e36f

## Verifying this change

Just a hotfix , no need to add test.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by chenzihao5** [comment]
@twalthr hi, Timo Walther. Please help to confirm this small fix. Thanks.

**Comment by chenzihao5** [comment]
@flinkbot run azure

**Comment by chenzihao5** [comment]
@MartijnVisser Hi, MartijnVisser. Could you help to confirm this small fix? Thanks.

**Review by MartijnVisser — CHANGES_REQUESTED** [review]
Thank you for your contribution. 

Please update your commit message to follow the Code Style & Quality Guidelines, which can be found at https://flink.apache.org/contributing/code-style-and-quality-pull-requests.html#commit-naming-conventions. Right now it mentions `[docs]` as what it fixes, this should be `[javadocs]`

**Comment by chenzihao5** [comment]
> Thank you for your contribution.
> 
> Please update your commit message to follow the Code Style & Quality Guidelines, which can be found at https://flink.apache.org/contributing/code-style-and-quality-pull-requests.html#commit-naming-conventions. Right now it mentions `[docs]` as what it fixes, this should be `[javadocs]`

@MartijnVisser Thanks for your correction. I have modified.

**Review by MartijnVisser — APPROVED** [review]
Thanks for this (Y)

@fapaul Can you merge it?

**Comment by chenzihao5** [comment]
@twalthr Can you help to merge this? Thanks very much.

**Comment by MartijnVisser** [comment]
@chenzihao5 This PR was created after the release branch for 1.15 was cut and needed to be rebased. I've just done that and pushed it. I'll wait for the CI to pass and then I will merge it. Apologies for the delay.

**Comment by chenzihao5** [comment]
@MartijnVisser That's okay, thanks a lot.

**Comment by MartijnVisser** [comment]
Thanks for the PR and the understanding @chenzihao5 - Merged :)

**Pull request merged**
