### PR TITLE
[FLINK-8657][doc]Fix incorrect description in the document for externalized checkpoint…

### PR DESCRIPTION
**Pull request by sihuazhou**
## What is the purpose of the change

This PR addressed issue [FLINK-8657](https://issues.apache.org/jira/browse/FLINK-8657). I checked that external checkpoint also supported rescale both in code and practice. But in the doc it still note that "do not support Flink specific features like rescaling."

## Brief change log

- Fix incorrect description for externalized checkpoint vs savepoint.
- Fix incorrect description for memory state backend.

## Verifying this change

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by sihuazhou** [comment]
@aljoscha Cloud you have a look at this?  I'm afraid I don't understand things correctly.

**Comment by aljoscha** [comment]
@StefanRRichter Could you have a look at this?

**Comment by StefanRRichter** [comment]
The docs are not "incorrect" and this is on purpose. Background is that, in general, externalized checkpoints are only required to support a subset of the features that savepoints provide and we do not want that user rely on their checkpoints to be rescalable. While this might be true now, this might change for all or some implementations in the future, so we simply do not want to give a guarantee that we then must maintain.

**Comment by sihuazhou** [comment]
Aha, I got it. But I also found the description of Memory state backend is wrong in these PR, the description is `The MemoryStateBackend can be configured to use asynchronous snapshots. While we strongly encourage the use of asynchronous snapshots to avoid blocking pipelines, please note that this is a new feature and currently not enabled by default.`, but I found `asynchronous snapshots` is enabled by default, it seems like out of date, could you please also have a look ? @StefanRRichter

**Comment by StefanRRichter** [comment]
Yes, that is outdated.

**Comment by sihuazhou** [comment]
@StefanRRichter If that is outdated, could you please merge this PR to fix it?

**Comment by StefanRRichter** [comment]
Thanks for the correction, LGTM 👍

**Pull request closed without merging**
