### PR TITLE
[hotfix] [docs] Update README.md to remove Maven 

### PR DESCRIPTION
**Pull request by asafm**
## What is the purpose of the change

Small fix to README

## Brief change log

No need for pre-installed maven, since we have Maven Wrapper

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

This change is a trivial rework / code cleanup without any test coverage.

### CODE REVIEW

**Comment by snuyanzin** [comment]
having maven wrapper does not protect from running with installed maven

**Comment by asafm** [comment]
@snuyanzin Why would you want users, to run with their installed Maven? If you want all users to have reproducible builds, they should only use the maven wrapper, pinned to a specific version.

**Comment by snuyanzin** [comment]
1. the PR is incomplete: removal requirement for maven is not enough since to make it reproducible there is no info how to enable it in IDE. In that case in terminal there will be wrapper used and in IDE not if follow instructions only
2. across the documentation there are lots of of mentions of just `mvn ...` without mentioing `./mvnw`
3. Is there any issue which could be reproduced by wraper and not reproduced by installed maven or vice versa or what is the reason to have the restriction to wrapper only?
4. Should we have a restriction for maven-wrapper version then?

**Comment by asafm** [comment]
Guys, I just thought it make sense that if you use internally maven wrapper, then the getting started README should mention that and not "force" users to download maven and run the build incompatible with the way you guys run internally.
Feel free to close this PR :)

**Pull request closed without merging**
