### PR TITLE
[FLINK-2353] Respect JobConfigurable interface in Hadoop mapred wrappers

### PR DESCRIPTION
**Pull request by fhueske**
Hadoop's mapred API features the `JobConfigurable` interface which offers a function `configure(JobConf)` to configure user-defined classes such as InputFormats, OutputFormats, and InputSplits.

Flink's Hadoop compatibility wrappers do not respect this interface.

Only the last commit is part of this commit due to sync problems of GH mirror.

### CODE REVIEW

**Comment by hsaputra** [comment]
@fhueske , looks like this PR is mix with other commits. May want to rebase first to just get your changes.

**Comment by fhueske** [comment]
Yes, I know. 
As stated above this is due to sync issues between Apache Git master and Github mirror. The PR consists only of the last commit. The others are already in Apache Git but not yet synced to GH.

**Comment by hsaputra** [comment]
Ah sorry, miss the last part of the PR comment.

**Comment by StephanEwen** [comment]
The relevant commit looks good
+1

**Comment by StephanEwen** [comment]
Merging this, together with the HBaseOutput Example, which needs adjusting according to this...

**Comment by fhueske** [comment]
Already did. Sorry for not announcing before.

**Pull request closed without merging**
