### PR TITLE
SignalWindow

### PR DESCRIPTION
**Pull request by nragon**
Related with https://github.com/apache/flink/pull/3639
but might be better with a new window.
This concept can also be represented with a state on trigger keeping the signaled event, but I think with this window we are able to get better throughput.
Also, this window is almost the same as TimeWindow

### CODE REVIEW

**Comment by StephanEwen** [comment]
I think this will not work. Windows are keys in hash tables. Mutating a key while it is already in the hash table makes it effectively impossible to find or delete any more.

**Comment by nragon** [comment]
But the hash code and equals remais the same, just like in TimeWindow. The only difference is that we can merge and control signaled events.

**Comment by nragon** [comment]
@StephanEwen I'm doing some test with this type of window. I'll try to see some other way (hash related as you said)

**Comment by nragon** [comment]
@StephanEwen would this implementation work? In you opinion, at first sight :)

**Pull request closed without merging**
