### PR TITLE
[FLINK-7127] [runtime] Remove unnecessary null check or add null check;

### PR DESCRIPTION
**Pull request by mylog00**
To avoid NPE I decided add null check instead remove it one.

### CODE REVIEW

**Comment by mylog00** [comment]
Link to passed tests build: https://travis-ci.org/mylog00/flink/builds/253949055

**Comment by tzulitai** [comment]
Thanks for the fix!
LGTM, merging ..

**Comment by tzulitai** [comment]
One other thing:
For commit messages, they should convey the exact final fix.
So, instead of "Remove unnecessary null check OR add null check", it should simply state how it is fixed. I'll adjust it appropriately this time for you :)

**Comment by mylog00** [comment]
Thanks for the advice. I will not repeat this mistake again in the future :)

**Pull request closed without merging**
