### PR TITLE
[FLINK-20540][jdbc] Fix the defaultUrl for AbstractJdbcCatalog in JDBC connector

### PR DESCRIPTION
**Pull request by kougazhang**
…dn-flink:5432flink via JDBC

## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by leonardBang — CHANGES_REQUESTED** [review]
@kougazhang Thanks for the contribution, the change generally looks good. 
But I change the issue tittle to make it clear, that's great if you can also update the commit message and PR title as following:
PR title: `[FLINK-20540][docs][jdbc] Fix the baseurl for pg database in JDBC connector page`
commit message: `[FLINK-20540][docs][jdbc] Fix the baseurl for pg database in JDBC connector page`
And we also need to update the PR description to make it's more specific.

**Comment by zentol** [comment]
Can we maybe change the code instead to handle this case more gracefully?

**Comment by leonardBang** [comment]
> Can we maybe change the code instead to handle this case more gracefully?

Thanks @zentol , that's a better way, I rechecked the code and found is problematic which should use the formatted `this.baseUrl` rather than the function parameter `baseUrl`:
```		
this.baseUrl = baseUrl.endsWith("/") ? baseUrl : baseUrl + "/";
this.defaultUrl = baseUrl + defaultDatabase; => this.defaultUrl = this.baseUrl + defaultDatabase; 
```
And thus the document update is unnecessary and we should change the code and update the test or add a new test to cover the change.
@kougazhang HDYT?

**Comment by kougazhang** [comment]
> > Can we maybe change the code instead to handle this case more gracefully?
> 
> Thanks @zentol , that's a better way, I rechecked the code and found is problematic which should use the formatted `this.baseUrl` rather than the function parameter `baseUrl`:
> 
> ```
> this.baseUrl = baseUrl.endsWith("/") ? baseUrl : baseUrl + "/";
> this.defaultUrl = baseUrl + defaultDatabase; => this.defaultUrl = this.baseUrl + defaultDatabase; 
> ```
> 
> And thus the document update is unnecessary and we should change the code and update the test or add a new test to cover the change.
> @kougazhang HDYT?

@leonardBang , I think your suggestion is very good, and I'll change the code as you suggest.
When I found this bug, I wanted to change the code in this way. This is jira link: [Addr](https://issues.apache.org/jira/browse/FLINK-20540?focusedCommentId=17246236&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17246236)
I am glad to see we have same idea.

**Comment by kougazhang** [comment]
@zentol , hello,  I have updated the PR, please code review.

**Review by leonardBang — CHANGES_REQUESTED** [review]
@kougazhang There're failed tests, the test [code](https://github.com/apache/flink/blob/aa34f060a06041b6e84afa54c8ae5507dba0342d/flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/catalog/PostgresCatalogTestBase.java#L125) also need to update, please update the PR.

**Comment by wuchong** [comment]
Hi @kougazhang, do you have time to update this PR?

**Comment by kougazhang** [comment]
> Hi @kougazhang, do you have time to update this PR?
Yes, i will finish it this week.

**Comment by kougazhang** [comment]
> @kougazhang There're failed tests, the test [code](https://github.com/apache/flink/blob/aa34f060a06041b6e84afa54c8ae5507dba0342d/flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/catalog/PostgresCatalogTestBase.java#L125) also need to update, please update the PR.

Hi, I updated the test code. And the code passed auto test.

**Review by leonardBang — APPROVED** [review]
Thanks @kougazhang for the update, LGTM

**Review by wuchong — COMMENTED** [review]
LGTM.

**Pull request merged**
