### PR TITLE
[FLINK-2748] accumulator fetch failure leads to duplicate job result response

### PR DESCRIPTION
**Pull request by mxm**

### CODE REVIEW

**Comment by uce** [comment]
+1 Looks good. Feel free to merge.

**Comment by rmetzger** [comment]
-1. Build fails
```
Results :

Failed tests: 
  AccumulatorErrorITCase.testFaultyAccumulator:97 Root cause should be:
Tests in error: 
  AccumulatorErrorITCase.testInvalidTypeAccumulator:118 Â» IO Failed to retrieve ...
```

**Comment by mxm** [comment]
Good thing I wrote this test :) Should pass now.

**Comment by uce** [comment]
Of course only merge if the builds pass. You are catching IOException but it should be Exception as before.

**Comment by mxm** [comment]
Sure, merging without passing tests is like Russian roulette :)

**Pull request closed without merging**
