### PR TITLE
[FLINK-9702][State Backends, Checkpointing] Improvement in (de)serialization of keys and values for RocksDB state

### PR DESCRIPTION
**Pull request by klion26**
## What is the purpose of the change

When Flink interacts with state in RocksDB, object (de)serialization often contributes significantly to performance overhead. In particular, currently every state has to serialize the backen's current key before each state access. This PR wants to  reduce this effort by sharing serialized key bytes across all state interactions. 

## Verifying this change

This change is already covered by existing tests

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (**no**)
  - The serializers: (**no**)
  - The runtime per-record code paths (performance sensitive): (**no**)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (**no**)
  - The S3 file system connector: (**no**)

## Documentation

  - Does this pull request introduce a new feature? (**no**)
  - If yes, how is the feature documented? (**not applicable**)

### CODE REVIEW

**Comment by klion26** [comment]
cc @StefanRRichter

**Comment by StefanRRichter** [comment]
Thanks for your help in finishing this issue! If you don't mind, I will add some more commits from my original branch https://github.com/StefanRRichter/flink/commits/serialiation-improvements that are not included here and then finalize and merge this.

**Comment by klion26** [comment]
@StefanRRichter Thank you for your reply. It's ok for me.

**Comment by klion26** [comment]
@StefanRRichter Seems like you have merged the code from another pr, I'll close this.

**Pull request closed without merging**
