### PR TITLE
[FLINK-3866] StringArraySerializer type should be mutable

### PR DESCRIPTION
**Pull request by mushketyk**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by mushketyk** [comment]
Hi, Could someone please review this small bug-fix?

**Comment by rmetzger** [comment]
Hi @mushketyk, I'll try to find somebody to review this

**Comment by mushketyk** [comment]
Hi @rmetzger, Thank you for helping with this!

**Comment by fhueske** [comment]
Thanks for the fix @mushketyk!

Looks good to merge

**Comment by mushketyk** [comment]
@fhueske Thank you for your review!
Could you please merge it? I don't have write permissions.

**Comment by fhueske** [comment]
Sorry for the delay @mushketyk!
Will merge it tomorrow. Thanks, Fabian

**Comment by mushketyk** [comment]
Thank you for your help @fhueske!

**Pull request closed without merging**
