### PR TITLE
[FLINK-24492][table-planner]incorrect implicit type conversion between numeric and (var)char

### PR DESCRIPTION
**Pull request by xuyangzhong**
## What is the purpose of the change

Before, the result of the sql "select 1 = '1'" is false, which is wrong.  And when "1 = '1'" is in join conditions, it will throw an exception, instead of returning a true or false result. 

"=" should have the same behavior with ">" and "<", which have the correct results. So before calcite solves this bug or Flink supports this kind of implicit type conversion, we'd better temporarily forbidding this implicit type conversion in "=" and "<>" and all throwing a clear exception, instead of giving a wrong result.

## Brief change log

  - In the codegen function, check the validity of implicit type conversion to avoid conversion between numeric and (var)char.
  - According to flip-154, add many test cases to test implicit type conversion now supported.
  - Change the existing test cases

## Verifying this change

This change added tests to verify this change.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented?

### CODE REVIEW

**Comment by twalthr** [comment]
@godfreyhe Please pay attention to the code quality. This PR adds more legacy:

```
@Rule public LegacyRowResource usesLegacyRows = LegacyRowResource.INSTANCE;
```

which could have been avoided. Also, when opening `ImplicitTypeConversionITCase` in an IDE, the file is full warnings.

`toAppendStream`, `registerTable` all of that is deprecated. `DataStreamConversions` is for implicit conversions. Not intended for Java code.

**Comment by twalthr** [comment]
Also, `SqlExpressionTest` adds more CAST tests. We are currently in the process in unifying the casting tests to `CastFunctionITCase` see also FLINK-24403. TBH I would vote for reverting this PR.

CC @matriv you are more involved in the casting topic, what is you opinion to this PR?

**Comment by matriv** [comment]
@twalthr Thx for pinging! I would also vote to revert it and use the new format of `CastRulesTest` and `CastFunctionITCase` (soon to be updated with a more complete set of all supported and unsupported casts with: https://github.com/apache/flink/pull/17579) for the tests. Maybe it worths creating a new but similar class, to test implicit casting at a lower expression level, without the need to write comparison expressions for each one of them.

**Comment by twalthr** [comment]
@godfreyhe can you revert this PR? Let's have another discussion around it. Esp. it also mentions FLIP-154 which has neither been voted nor accepted by the Flink community yet.

**Comment by godfreyhe** [comment]
@twalthr Thanks for driving this. I will pay more attention to the code quality of test cases. Currently, `select 1 = '1'` will generate wrong result, and all Flink (SQL) versions will be affected. About master, two solutions: 1) revert this commit, 2) or improve the test code and remove the validation code after the cast rule cover this bug. About other branches, we will not pick the cast feature to the lower versions, so just improve the test code. Improving the test case is common action, the second solution for master branch is better ? WDYT?

**Comment by twalthr** [comment]
@godfreyhe I'm also fine with the second option. The fix itself is valid. It is just the tests that need some cleanup. I think @matriv mentioned that we might extend the current cast testing infrastructure for implicits as well?

**Comment by matriv** [comment]
It would be nice yes, to follow the new pattern and use it also to consolidate or implicit casting into one place, I'd fine to keep the fix and have a followup PR to restructure the tests.

**Comment by godfreyhe** [comment]
ok, I will create a issue to improve the tests

**Pull request closed without merging**
