### PR TITLE
[FLINK-4879] [Kafka-Connector] class KafkaTableSource should be public just like KafkaTableSink

### PR DESCRIPTION
**Pull request by hzyuemeng1**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [ ] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [ ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by rmetzger** [comment]
Thank you for opening a pull request.

@fhueske @twalthr @uce I think its okay to make the class public, in case users want to use a custom Kafka consumer, right?

**Comment by fhueske** [comment]
I think it's fine to make `KafkaTableSource` public. 
However, I think users usually want to go for a version-specific `KafkaTableSource` like `Kafka090TableSource`. The version-specific sources are all declared `public`.

**Comment by hzyuemeng1** [comment]
@fhueske @rmetzger ,thanks all for review this pr,I am very interesting in Table SQL,can anyone merge this pr?

**Comment by hzyuemeng1** [comment]
@wuchong can u help me to inform someone to merge this pr,thanks

**Comment by wuchong** [comment]
+1 to merge this. I think it's fine to make `KafkaTableSource` public, just like `FlinkKafkaConsumerBase`.

**Comment by tzulitai** [comment]
+1 this looks fine to me, no problem with making it public.

**Comment by hzyuemeng1** [comment]
thanks for ur review,i am very interesting about Table SQL,and want to make it better

2016-10-24 

hzyuemeng1 



发件人：Jark <notifications@github.com>
发送时间：2016-10-24 09:57
主题：Re: [apache/flink] [FLINK-4879] [Kafka-Connector] class KafkaTableSource should be public just like KafkaTableSink (#2678)
收件人："apache/flink"<flink@noreply.github.com>
抄送："hzyuemeng1"<hzyuemeng1@corp.netease.com>,"Author"<author@noreply.github.com>

+1 to merge this. I think it's fine to make KafkaTableSource public, just like FlinkKafkaConsumerBase.

**Pull request closed without merging**
