### PR TITLE
[FLINK-8704][tests] Port SlotCountExceedingParallelismTest

### PR DESCRIPTION
**Pull request by zentol**
## What is the purpose of the change

This PR ports the `SlotCountExceedingParallelismTest` to flip6. The existing test was renamed to `LegacySlotCountExceedingParallelismTest`, and a ported copy was added.

### CODE REVIEW

**Comment by pnowojski** [comment]
@zentol, why did you have to copy `LegacySlotCountExceedingParallelismTest`? Shouldn't the new one work as well for non FLIP6?

**Comment by zentol** [comment]
that is true, yes. I'll update the PR, hang on.

**Comment by zentol** [comment]
ah i remembered why.

I had to copy the test because this test is in `flink-runtime`. Here we don't have access to the `MiniClusterResource`.

**Comment by zentol** [comment]
merging

**Pull request closed without merging**
