### PR TITLE
[FLINK-3169] Remove Key class

### PR DESCRIPTION
**Pull request by zentol**

### CODE REVIEW

**Comment by StephanEwen** [comment]
This could really use some description of what is done in this PR. For example, what happens to all the classes that depend on `Key`?

**Comment by zentol** [comment]
most occurrences of Key were replaced with Value, with casts to comparable when it was necessary.

**Comment by zentol** [comment]
SparseKeySchema and PossPassUtils were removed since they depended on Key, but were unused.

**Comment by zentol** [comment]
The Pair type was removed as per FLINK-2344

**Comment by StephanEwen** [comment]
Hmm, I think we should change a few more things:
  - Quite a few distribution classes can probably go. The new range partitioner uses a different interface (@fhueske should be able to confirm this).
  - The `NormalizableKey` interface should not be purely applicable to value types, if possible it should extend only `Comparable`.

**Comment by fhueske** [comment]
Yes, it looks like `UniformIntegerDistribution`, `UniformDoubleDistribution`, `SimpleDistribution`, `SimpleIntegerDistribution` and `SimpleDataDistributionTest` can be removed.

**Comment by zentol** [comment]
Ok, I've removed the distributions that @fhueske listed, removed a few javadoc references to the Key class, and NormalizableKey no longer extends the Value interface.

**Comment by StephanEwen** [comment]
Seems fine now

**Comment by zentol** [comment]
Merging this.

**Pull request closed without merging**
