### PR TITLE
[FLINK-3277] Use Value types in Gelly API

### PR DESCRIPTION
**Pull request by greghogan**

### CODE REVIEW

**Comment by StephanEwen** [comment]
Thanks for checking this out.

Do you have an estimate of how this affects Gelly performance for some algorithms? How much does this improve the performance?

**Comment by greghogan** [comment]
@StephanEwen in [FLINK-3768](https://github.com/apache/flink/pull/1896) I compared an optimal algorithm to the current implementation in Gelly and the optimal algorithm was 53% faster. There is some additional complexity in the optimal algorithm that I have since removed so I'd expect it to be about 60% faster.

**Comment by vasia** [comment]
But was the difference you saw because of the different logic of the algorithm or because of using Value types? I was under the impression that the algorithm was quite different.

**Comment by greghogan** [comment]
The two implementations have small differences but the algorithm is the same. I'll be removing the two steps which are concerned with degree skew since I had not previously looked at the degree distribution but I haven't found a graph that exhibits degree skew under the algorithm's optimization to generate triplets from the vertex with smallest degree. Would be nice to have a proof, though.

I expect most of the performance difference to be in `DegreeCounter` and `TriadBuilder` caching objects but not supporting object reuse. Using immutable boxed primitives has the same effect as disabling object reuse since deserialization must create a fresh object each time.

**Comment by vasia** [comment]
I see. Thanks for the explanation!

**Pull request closed without merging**
