### PR TITLE
FLINK-2322 Unclosed stream may leak resource

### PR DESCRIPTION
**Pull request by tedyu**
What size should I use for tab ?

### CODE REVIEW

**Comment by StephanEwen** [comment]
You should use tabs ;-)

Otherwise this is a good fix. To optimize it: You need not close the stream in two places, the finally clause will do it anyways.

**Comment by tedyu** [comment]
I did use tabs. I have the following in .vimrc:
set tabstop=2       " numbers of spaces of tab character

**Comment by aljoscha** [comment]
Maybe your vim is set to replace tabs with spaces, but in the files that you changed there are definitely spaces now.

**Comment by tedyu** [comment]
I used the following command:
mvn clean package -DskipTests eclipse:eclipse

However, under flink-java, I only found one .classpath file:
/Users/tyu/flink/flink-java/target/.classpath

How do people generate project file for Eclipse ?

Thanks

**Comment by StephanEwen** [comment]
Usually, you never manually generate `.classpath` files and other IDE config files.

For Eclipse, simply import the code as a Maven project. Actually, all the information for that is in the README.md file.

**Comment by tedyu** [comment]
Anything I can do to move this forward ?

**Comment by StephanEwen** [comment]
The CI builds still fail for this patch, have a look at the Travis report.
All tests and checks need to pass before merging a change.

**Comment by tedyu** [comment]
I looked at https://travis-ci.org/apache/flink/jobs/73803261 but couldn't figure out which test failed.

**Comment by StephanEwen** [comment]
Looks good, merging this...

**Pull request closed without merging**
