### PR TITLE
[FLINK-26793][documentation] Add recommendations about the write timeout to the javadoc of Cassandra sink and output format

### PR DESCRIPTION
**Pull request by echauchot**
Please read the comments in the ticket that concluded to adding more details and recommendations regarding the issue.
R: @AHeise

### CODE REVIEW

**Comment by echauchot** [comment]
R: @zentol I pinged you because we worked together on cassandra. Feel free to ping another reviewer if that makes too many reviews.

**Comment by echauchot** [comment]
@MartijnVisser could we review this one please ? Please don't forget to read the comments in the ticket that contain the details of the experimentation for diagnostic.

**Comment by echauchot** [comment]
@MartijnVisser @zentol friendly ping

**Comment by MartijnVisser** [comment]
@echauchot Sorry, I'll have a look today :)

**Review by MartijnVisser — APPROVED** [review]
@echauchot Thanks for the improvement, it most likely will be helpful for users! LGTM

**Pull request merged**
