### PR TITLE
[hotfix] [doc] Fix typo for s3a config in AWS deployment documentation

### PR DESCRIPTION
**Pull request by tony810430**
Should use `fs.s3a.buffer.dir` in `core-site.xml` to set s3a directories for buffering files.

### CODE REVIEW

**Comment by tony810430** [comment]
Hi @haohui 
I thought that sentence is for configuration like `state.backend.fs.checkpointdir` in `flink-conf.yaml`. AFAIK, `s3://` works well if I correctly setup in `core-site.xml`.
Point me out if I was misunderstanding. Thank you.

**Comment by haohui** [comment]
The configuration will lead you to use the old s3 filesystem instead of the s3a filesystem.

See https://wiki.apache.org/hadoop/AmazonS3 for more details.

**Comment by tony810430** [comment]
I see. I will update it. Thank you.

**Comment by tony810430** [comment]
Hi @haohui 
Have addressed that. Please advise if there is still anything need to be changed. Thank you.

**Comment by haohui** [comment]
LGTM

**Comment by tzulitai** [comment]
LGTM, merging ..
Thanks for the fix and reviews!

**Pull request closed without merging**
