### PR TITLE
[FLINK-12686][runtime] Disentangle StreamGraph/StreamNode/StreamGraph…

### PR DESCRIPTION
**Pull request by ifndef-SleePy**
…Generator from StreamExecutionEnvironment

## What is the purpose of the change

* Disentangle `StreamGraph/StreamNode/StreamGraphGenerator` from `StreamExecutionEnvironment`, so `StreamGraph` could support any environment

## Brief change log

* Use parameters directly in `StreamGraph/StreamNode/StreamGraphGenerator` instead of `StreamExecutionEnvironment`
* Introduce a global option to turn off slot sharing in `StreamGraphBuilder`. It's a internal API which is not exposed to user currently
* Remove hard-coded `ScheduleMode` in `StreamingJobGraphGenerator`, make it configurable

## Verifying this change

* Add unit tests in `StreamingJobGraphGeneratorTest` and `StreamGraphBuilderTest`

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by ifndef-SleePy** [comment]
Close and reopen to trigger Travis checking again.

**Comment by ifndef-SleePy** [comment]
Hi @aljoscha , it seems that there is something wrong with Travis building. I have filed a JIRA issue to track this Travis problem, https://issues.apache.org/jira/browse/FLINK-12866.
Will try Travis building again after it has been resolved.

**Comment by aljoscha** [comment]
I merged this. Thanks a lot for your contribution! 👌

**Comment by ifndef-SleePy** [comment]
Thank you for detailed review and nice suggestions!

**Pull request closed without merging**
