### PR TITLE
[FLINK-21838][docs] retranslate "JDBC SQL Connector" page into Chinese

### PR DESCRIPTION
**Pull request by jjiey**
## What is the purpose of the change

[FLINK-21838](https://issues.apache.org/jira/browse/FLINK-21838)
Retranslate "JDBC SQL Connector" page into Chinese.

## Brief change log

* Retranslate "JDBC SQL Connector" page into Chinese, the doc file is located in 'docs/content.zh/docs/connectors/table/jdbc.md'.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by jjiey** [comment]
CC. @wuchong

**Comment by wuchong** [comment]
@leonardBang could you help to review this?

**Comment by leonardBang** [comment]
ok, I'll review this one

**Review by leonardBang — COMMENTED** [review]
Hi, @jjiey , Thanks for your contribution, could you reference this PR(https://github.com/apache/flink/pull/14675) and update this one?

Looks like we lost the `jdbc` zh doc when migrate from legacy doc website to current one(https://github.com/apache/flink/pull/14903), let us fix the jdbc page in this PR.

CC @sjwiesman, I found some Chinese doc pages are lost in (https://github.com/apache/flink/pull/14903) such like `jdbc zh`, `kafka zh`, we'd better open an issue to fix them to avoid duplication work.

**Comment by jjiey** [comment]
Hi, @leonardBang, this PR is the modification I made after copying [#14903](https://github.com/apache/flink/pull/14903). The main modifications are as follows:
* Most of it is to modify the blank space
* Added translation of sql comments (There was no translation before)

**Comment by sjwiesman** [comment]
@leonardBang please open ticket if you find missing pages

**Review by leonardBang — APPROVED** [review]
LGTM, thanks @jjiey

**Comment by leonardBang** [comment]
> @leonardBang please open ticket if you find missing pages

I created https://issues.apache.org/jira/browse/FLINK-21917, @jjiey Do you want to work for this?

**Comment by jjiey** [comment]
> > @leonardBang please open ticket if you find missing pages
> 
> I created https://issues.apache.org/jira/browse/FLINK-21917, @jjiey Do you want to work for this?

@leonardBang Yes, I'm willing todo it. @wuchong Please assign it to me, thanks.

**Review by wuchong — APPROVED** [review]
LGTM.

**Pull request merged**
