### PR TITLE
[FLINK-36369][table] Move deprecated user-visible classes in table modules to the legacy package

### PR DESCRIPTION
**Pull request by xuyangzhong**
## What is the purpose of the change

*Move deprecated user-visible classes in table modules to the legacy package*

## Brief change log

*Move deprecated class in these following modules*
  - *table-common*
  - *table-api-java*
  - *table-api-java-bridge*

*Both table-api-scala and table-api-scala-bridge modules are in deprecated state, so no rename is needed.*
*Both table-runtime and table-planner modules are not directly perceived by users, so they are skipped.*

## Verifying this change

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented?

### CODE REVIEW

**Comment by xuyangzhong** [comment]
@flinkbot run azure

**Comment by xuyangzhong** [comment]
@flinkbot run azure

**Comment by lincoln-lil** [comment]
@xuyangzhong Is there a complete list of classes that need to be moved? 
We need to update it in jira's release notes as part of the user informs.

**Comment by xuyangzhong** [comment]
> @xuyangzhong Is there a complete list of classes that need to be moved? We need to update it in jira's release notes as part of the user informs.

I'll update the list in this jira later.

**Review by lincoln-lil — APPROVED** [review]

**Pull request merged**
