### PR TITLE
[FLINK-8660] Enable the user to provide custom HAServices implementation

### PR DESCRIPTION
**Pull request by kbialek**
## What is the purpose of the change
This pull request makes it possible to use alternative (to ZK) HA backend implementation

## Brief change log
* Added HighAvailabilityServicesFactory interface
* Added new option HighAvailabilityMode.FACTORY_CLASS
* Configuration property "high-availability" can be set either to none, zookeeper or FQN of factory class
* HighAvailabilityServicesUtils uses configured factory to instantiate HighAvailabilityServices
* Updated docs

## Verifying this change
This change added tests and can be verified as follows:
* Added new test class HighAvailabilityServicesUtilsTest
* Updated test class HighAvailabilityModeTest
* Manually verified by using own HA backend implementation

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: yes, if this feature is used, otherwise no
  - The S3 file system connector: no

## Documentation
  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? docs and JavaDocs

### CODE REVIEW

**Comment by StephanEwen** [comment]
I think this is a nice approach.

I would suggest to not split the config options between `high-availability` and factory that is only used in *CUSTOM* mode, but use the `high-availability` option for both. The option describes the high availability services factory, with *NONE* and *ZOOKEEPER* as special constants/shortcuts.

Have a look at the `StateBackendLoader` class for an example of that.
https://github.com/apache/flink/blob/master/flink-runtime/src/main/java/org/apache/flink/runtime/state/StateBackendLoader.java#L92

**Comment by kbialek** [comment]
Closing without merge, because of:
1. Test failure
2. I'd like to implement Stephan's idea

**Comment by kbialek** [comment]
Now uses high-availability configuration property can be set either to none, zookeeper or FQN of factory class

**Comment by kbialek** [comment]
Looks like build process was terminated by kernel. Can someone retrigger it?

**Comment by tillrohrmann** [comment]
You could rebase on the latest master and force push to retrigger the build.

**Comment by StephanEwen** [comment]
I think this looks quite good now.

Since 1.5 feature freeze is over for a bit, would suggest to merge this into master (1.6-SNAPSHOT).

Looking at the code (this PR and the high availability configuration in general), I would suggest to work towards the following design in the future:

  - We don't have specific high availability enums and setting, everything is just an implementation of HAServices. Some HAServices are in fact not highly available (maybe we need to find a better name for HAServices).
  - There are factories for all HAServices
  - We simply have "none" and "zookeeper" as aliases for the respective factories.

That mirrors the design of he state backends and their configuration, which is nice, because we never need to do special checks like "isHighAvailabilityEnabled".

**Comment by Xeli** [comment]
I am in the process of building a HAService for our kubernetes set up without having to use zookeeper (https://stackoverflow.com/q/52104759/988324) and this PR would be very helpful.

Would it be possible to merge this into 1.7? (or 1.6.1? :D)

**Comment by tillrohrmann** [comment]
Yes I think we should try to get this PR into 1.7 since it allows to implement your own `HighAvailabilityServices`. I'll try to find some time next week to take a look what the current state is.

**Comment by tillrohrmann** [comment]
Merged via 3bc7bc2e80af1e277ffb4906e6aca416a9de954b and 324d7bed226cb707512879842c33788f7f715ff2

**Pull request closed without merging**
