### PR TITLE
[FLINK-2641] integrate off-heap memory configuration

### PR DESCRIPTION
**Pull request by mxm**
- remove taskmanager.heap.mb and jobmanager.heap.mb
- introduce taskmanager.memory.size and jobmanger.memory.size
  which allow to control total combined heap and off-heap memory

- add offheap configuration parameter taskmanager.memory.off-heap
- remove offheap ratio parameter and reuse memory fraction parameter

- rename taskmanager.memory.fraction to taskmanager.memory.managed.fraction
- rename taskmanager.memory.size to taskmanager.memory.managed.size

- set JVM -XX:MaxDirectMemorySize parameter correctly

- remove number of network buffers config entry
- allow configuration of network memory size via new entry
  taskmanager.memory.network.size
- adapt code and tests to changes

- remove deprecated ConfigConstants.TASK_MANAGER_MEMORY_SEGMENT_SIZE_KEY

- fail when obsolete config entries are detected

### CODE REVIEW

**Comment by StephanEwen** [comment]
This renames a lot of configuration keys. Is it not possible to do it a bit less invasive? Rename the `taskmanager.heap.size` to `taskmanager.jvm.size` and keep the rest?

We have to be clear and careful with the term managed memory also, as the regular JVM heap is managed memory (managed by the JVM / GC) as opposed to the unmanaged memory in a C++ program.

**Comment by StephanEwen** [comment]
Also, the mechanism for network memory configuration changed (memory size now, was number of buffers). Why changing that? Was the old mechanism bad?

**Comment by mxm** [comment]
In addition to the discussion in the JIRA, I had to change the way the network memory is configured because otherwise I cannot calculate the direct memory size correctly. The default network buffer size is not easy to get in the startup scripts without also putting it in the config. Besides that, I think it will be much easier for users to configure the network buffer size using an absolute value rather than some obscure numberOfNetworkBuffers.

> We have to be clear and careful with the term managed memory also, as the regular JVM heap is managed memory (managed by the JVM / GC) as opposed to the unmanaged memory in a C++ program.

In Flink, we always use the term managed memory to refer to our own memory management. So I think it makes sense to stick to that term. The former name `taskmanager.memory.size` was not clearer in any way because one would think that this refers to the total memory size rather than the Flink managed memory size.

**Comment by StephanEwen** [comment]
I think this is tricky, a config flag that used to refer to something different (memory manager size) now refers to a new concept (jvm memory size). This is bound to cause issues...

**Comment by mxm** [comment]
That's why the pull request has the check for obsolete keys which fails to start Flink when old config entries are detected. In addition, it has sanity checks to check whether managed memory size < heap+offheap memory size. To make things clearer, we could use taskmanager.jvm.size (although the actual size depends on many other things).

**Comment by rmetzger** [comment]
The pull request should also update the documentation. In particular these configuration values affect the documentation in many places.

**Comment by mxm** [comment]
Yes, that will follow. I wanted to kick-off the discussion first because I had this gut-feeling that it might cause more discussion than in the JIRA once the pull request had been opened.

**Comment by mxm** [comment]
How about we rename `taskmanager.memory.size` to `taskmanager.memory`? Then there wouldn't be any possible clash. I could also live with `taskmanager.jvm.memory.size`.

**Comment by mxm** [comment]
Closing this in favor of #1129. For further discussion please see https://issues.apache.org/jira/browse/FLINK-2667.

**Pull request closed without merging**
