### PR TITLE
[FLINK-2238][scala api]Add env.fromCollection(set) method to scala api

### PR DESCRIPTION
**Pull request by sachingoel0101**
Used the same technique as in env.fromCollection(Seq) to first convert the data to a Java Collection.

### CODE REVIEW

**Comment by fhueske** [comment]
Hi @sachingoel0101, 

thanks for the PR!
I think we don't need a new method specifically for Sets. It is sufficient to change the parameter type of the first `fromCollection` from `Seq` to `Iterable` to support `Set` (and other non-Seq collections).

**Comment by sachingoel0101** [comment]
Ah. Yes. That does make more sense. :+1: 
Updating now.

**Comment by fhueske** [comment]
Thanks for the update, @sachingoel0101!

Good to merge.

**Comment by fhueske** [comment]
merging

**Comment by StephanEwen** [comment]
This change was actually API breaking (binary compatibility). It should actually be tagged like that.

For the release 0.10, there should also be a list of what was broken.

Who takes care of that?

**Comment by fhueske** [comment]
Damn, that's on me. :-/ 
I'll revert the commit for the 0.9 branch and recommit for 0.10 with corrected commit message.

Is there already an API change list for 0.10 or do we need to start one?

**Comment by StephanEwen** [comment]
No problem, it happens ;-)
Good idea to put it in 0.10 but not in 0.9.1.

I think there is no API change list yet. Should we start one in the wiki?

**Comment by fhueske** [comment]
Alright, I reverted the commit for the release-0.9 branch and created a [wiki page](https://cwiki.apache.org/confluence/display/FLINK/0.10+Release) for issues relates to the 0.10 release including API-breaking changes.

**Pull request closed without merging**
