### PR TITLE
[FLINK-4418] [client] Improve resilience when InetAddress.getLocalHos…

### PR DESCRIPTION
**Pull request by rehevkor5**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

…t() throws UnknownHostException

- If InetAddress.getLocalHost() throws UnknownHostException when
attempting to connect with LOCAL_HOST strategy, the code will move on
 to try the other strategies instead of immediately failing.
- Also made minor code style improvements for trying the different
strategies.

### CODE REVIEW

**Comment by rehevkor5** [comment]
I don't think the Jenkins build failure was due to my changes.

**Comment by rmetzger** [comment]
+1 to merge

**Comment by StephanEwen** [comment]
This looks good to me.

The `ConnectionUtils` was due some cleanup, could use even a but more cleanup ;-)

**Comment by rehevkor5** [comment]
@StephanEwen do you want me to take a look & see what straightforward refactoring I can make, and squeeze that into this PR? I can't tell if that was a hint or not :)

**Comment by StephanEwen** [comment]
I would merge this fix by itself first.
Then, if you have a nice way in mind to make this simpler, I'd be happy to look at another pull request ;-)

**Comment by StephanEwen** [comment]
Merging this...

**Pull request closed without merging**
