### PR TITLE
[hotfix] Skip some e2e tests on aarch64

### PR DESCRIPTION
**Pull request by wangxiyuan**
## What is the purpose of the change

There are two e2e test run fail on aarch64. They are  `Streaming bucketing end-to-end test` and `PyFlink end-to-end test`.

1. For  `Streaming bucketing end-to-end test`[1], it may be the `netty` problem. It needs more debug.

2. For  `PyFlink end-to-end test`[2], there are two problem:
    a. MiniConda doesn't support aarch64 currently.
    b. Pyarrow which Pyflink depends on doesn't support aarch64 currently. 

We can skip these two tests  on aarch64 until the problem is fixed.

[1]: https://logs.openlabtesting.org/logs/periodic-20-flink-mail/github.com/apache/flink/master/flink-end-to-end-test-cron-hadoopfree/94a8261/job-output.txt.gz
[2]: https://logs.openlabtesting.org/logs/periodic-20-flink-mail/github.com/apache/flink/master/flink-end-to-end-test-cron-hadoop241/54ca93b/job-output.txt.gz

## Brief change log

Skip `Streaming bucketing end-to-end test` and `PyFlink end-to-end test` on aarch64 platform.

## Verifying this change

This change is already covered by existing e2e tests,.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no*)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by rmetzger** [comment]
@flinkbot run azure

**Comment by rmetzger** [comment]
The NPM failures were caused by some outage on NPMs systems.

**Comment by wangxiyuan** [comment]
@rmetzger Thanks for the quick review. Can this be merged now?

**Comment by rmetzger** [comment]
Yes, I'm merging it now ...

**Pull request closed without merging**
