### PR TITLE
[FLINK-6139] [doc] Documentation for running Flink with MapR

### PR DESCRIPTION
**Pull request by tzulitai**
Includes how to properly build Flink & setup job client to be able to run Flink on YARN with a MapR cluster.

### CODE REVIEW

**Comment by rmetzger** [comment]
I would propose to add a special "mapr" build profile to our maven files to do all the exclusions. Otherwise, the documentation looks pretty scary :)

**Comment by tzulitai** [comment]
@rmetzger that definitely makes sense, I'll try to include that with the PR.

**Comment by rmetzger** [comment]
Cool, thank you!

**Comment by tzulitai** [comment]
@rmetzger I've added the "mapr" build profile to our Maven build.

Now the build command is shortly: `mvn clean install -Pvendor-repos,mapr`. Much less daunting for users :) Currently, both `mapr` and `vendor-repos` must be used together.
We could perhaps shorten this further into a single profile, by also adding the MapR repo in `mapr` profile. What do you think?

**Comment by rmetzger** [comment]
I think its fine like this.

**Comment by rmetzger** [comment]
+1 to merge

**Comment by tzulitai** [comment]
Thanks for the review, merging to {{master}} and {{release-1.2}}.

**Pull request closed without merging**
