### PR TITLE
[FLINK-5153] Support YARN application tags

### PR DESCRIPTION
**Pull request by patricklucas**
Adds a new config option `yarn.tags`, a comma-separated list of strings
passed to YARN as application tags.

### CODE REVIEW

**Comment by patricklucas** [comment]
I manually tested the behavior of this new feature as well as the other YARN application options touched by this change with various Hadoop versions (2.3/2.4/2.6) on a YARN cluster.

The Travis builds have tended to fail by timing out after 50 min, but everything tests fine locally.

**Comment by rmetzger** [comment]
Hi Patrick,
the change looks good in general (you updated the documentation as well :) ).
One thing I'm missing a bit from the change is a test case.
We have an entire package (which is, admittedly pretty ugly) for YARN tests.
Maybe you can just pass your new config option to one of the existing tests and then check if the tag has been set.

**Comment by patricklucas** [comment]
I added the test (which of course also required reflection) to an existing test case. I figured that was the lesser of the two evils of requiring another test application be deployed and hiding a test within a (somewhat) unrelated one.

It was a bit tricky to actually run the tests, but I verified the correct behavior with both hadoop < 2.4 and >= 2.4.

**Comment by rmetzger** [comment]
I'll merge the change now.

I've also tested it.

**Comment by rmetzger** [comment]
@patricklucas Can you manually close the PR? We usually do this automatically, but I forgot to add the right string the commit message.

**Pull request closed without merging**
