### PR TITLE
[FLINK-2683] [runtime] Add dedicated operator for processing time windows.

### PR DESCRIPTION
**Pull request by StephanEwen**
Adds new dedicated implementations for grouped windows on aligned processing time (tumbling and sliding time windows). A lot of code is written to be easily adaptable to event-time implementations.

The pull request currently includes only the operator implementations - the operators are not yet integrated with the APIs and stream graph builder.

The new operators fix many problems that the current time operators have, including cleanup of stale keys, deadlocks, resource leaks, incorrect time alignment, and occasional wrong results.

The pull request also adds quite a few tests for the operators and data structures, including checks whether data structures are released and whether threads are properly disposed.

One can try out the implementation by running the `GroupedProcessingTimeWindowExample` that I added for experimental purposes into the examples project (should be removed before merging).

#### Speed

The new implementations are also much faster:

Setup is a streaming program that generates (Long, Long) tuples, and groups them (field 0) in a window of 2500 msecs sliding by 500 msecs, and aggregates them (field 1). I use 10k unique keys in the example

Times:
 - current implementation: 50K / core / sec (gets slower over time, high GC overhead)
 - new implementation w/o pre-aggregation: 800K / sec / core (moderate GC overhead)
 - new implementation w/ pre-aggregation: 3mio / sec / core (low GC overhead)

This build on #1133

### CODE REVIEW

**Comment by gyfora** [comment]
This is a pretty massive addition, but I am excited :)
I will try to look through it today and tomorrow!

**Comment by senorcarbone** [comment]
wow! I also want to look into this in more detail, it looks promising.
@StephanEwen if you find a bit of time, can you write some more details to guide the reviewing a bit? Kudos for the high quality work!

**Comment by aljoscha** [comment]
I don't think the unit tests are correct. I was playing around with the tests while adding the integration of the timer service into the StreamTask. I noticed that most of the tests that should test windowing behavior still succeeded even though no time triggering is actually done.

**Comment by aljoscha** [comment]
If the operators don't react to watermarks  and don't forward watermarks that means that any downstream operators cannot rely on watermarks.

**Comment by StephanEwen** [comment]
Concerning Watermarks: I think that is the assumption right now, yes.

Since the operators produce records with timestamps based on their processing time, they cannot simply forward watermarks. They should be able to auto-generate watermarks based on their processing time, but I am not sure if that is what we would want...

**Comment by StephanEwen** [comment]
Thanks for the pointer with the tests, will have a look and fix this...

**Comment by StephanEwen** [comment]
Actually, I think the tests are okay. The triggers are part of some tests only, because this is a unit test that checks many features independently.

  - There are two tests that validate behavior of triggers (regular case and exception case). Both hang with out a trigger.
  - Many tests test parameterization, timestamp alignments, and scheduling. They need no triggers or mock triggers, so those naturally run without proper triggers.
  - Some test define corner conditions around windowing / closing. These are valid even if everything happens in close(), so they are correct as well.
  - Some tests check pure closing behavior (emit trailing data, make sure exceptions are propagated)

I will add another test that checks the correct operation of tumbling window triggers, but aside from that, I think the test coverage is good.

**Comment by aljoscha** [comment]
Ok, if this is out of the way I would suggest to merge it.

**Comment by StephanEwen** [comment]
Manually merged in b8f58fab56c727b8d44d2a90bbb389ab7544989e

**Pull request closed without merging**
