### PR TITLE
[FLINK-15933][catalog][doc] Update content of how generic table schem…

### PR DESCRIPTION
**Pull request by lirui-apache**
…a is stored in hive via HiveCatalog

## What is the purpose of the change

Update docs as a result of FLINK-15858.

## Brief change log

  - Add descriptions about hive v.s. generic table
  - Move `Supported Types` to HiveCatalog page since it's more closely related
  - Minor updates to the support of `TIMESTAMP` type

## Verifying this change

NA

## Does this pull request potentially affect one of the following parts:

NA

## Documentation

NA

### CODE REVIEW

**Comment by lirui-apache** [comment]
@bowenli86 @JingsongLi Let me know if you think the change makes sense. Thanks.

**Comment by lirui-apache** [comment]
@bowenli86 We don't have any console output for "DESCRIBE mykafka;" now. I'll add the output for "DESCRIBE FORMATTED mykafka;" instead.

**Comment by lirui-apache** [comment]
@bowenli86 Docs updated. Please have another look. Thanks.

**Comment by bowenli86** [comment]
> @bowenli86 We don't have any console output for "DESCRIBE mykafka;" now. I'll add the output for "DESCRIBE FORMATTED mykafka;" instead.

why we don't have any console output for a table? Seems like a bug?

**Comment by lirui-apache** [comment]
> > @bowenli86 We don't have any console output for "DESCRIBE mykafka;" now. I'll add the output for "DESCRIBE FORMATTED mykafka;" instead.
> 
> why we don't have any console output for describing a table? Seems like a bug?

Because we have changed to store the generic table schema as properties. So from Hive perspective, the table doesn't have any columns.

**Comment by bowenli86** [comment]
> > > @bowenli86 We don't have any console output for "DESCRIBE mykafka;" now. I'll add the output for "DESCRIBE FORMATTED mykafka;" instead.
> > 
> > 
> > why we don't have any console output for describing a table? Seems like a bug?
> 
> Because we have changed to store the generic table schema as properties. So from Hive perspective, the table doesn't have any columns.

my bad, I thought it's a flink cli...

LGTM, merging

**Pull request closed without merging**
