### PR TITLE
[FLINK-3161][dist] Externalize cluster start-up and tear-down when available

### PR DESCRIPTION
**Pull request by greghogan**
Parallelizes cluster start-up and tear-down when pdsh is available

### CODE REVIEW

**Comment by greghogan** [comment]
I haven't had access to a cluster in a few days but if needed or if this is still open I'll post timings next time.

**Comment by rmetzger** [comment]
I filed a JIRA for the failed test case: https://issues.apache.org/jira/browse/FLINK-3265

**Comment by rmetzger** [comment]
Seems that `pdsh` is available in all Ubuntu versions. So I guess the tool is popular enough to be present for some of our users.

I think some tests on a cluster would be valuable to make sure we didn't oversee anything.

**Comment by StephanEwen** [comment]
Since this tests that `pdsh` is available, this should be good to merge...

**Comment by fhueske** [comment]
I'm not familiar with `pdsh` but is there a way to pass the `FLINK_SSH_OPTS` on?

**Comment by greghogan** [comment]
The `pdsh` section on [Environment Variables](http://linux.die.net/man/1/pdsh) lists two options:

> PDSH_SSH_ARGS
> Override the standard arguments that pdsh passes to the ssh(1) command ("-2 -a -x -l%u %h"). The use of the parameters %u, %h, and %n (as documented in the rcmd/exec section above) is optional. If these parameters are missing, pdsh will append them to the ssh commandline because it is assumed they are mandatory.

> PDSH_SSH_ARGS_APPEND
> Append additional options to the ssh(1) command invoked by pdsh. For example, PDSH_SSH_ARGS_APPEND="-q" would run ssh in quiet mode, or "-v" would increase the verbosity of ssh. (Note: these arguments are actually prepended to the ssh commandline to ensure they appear before any target hostname argument to ssh.)

By default `pdsh` is enforcing protocol version 2, disabling the authentication agent, and disabling X11 forwarding. For consistency we can blank out PDSH_SSH_ARGS and set PDSH_SSH_ARGS_APPEND to FLINK_SSH_OPTS.

**Comment by greghogan** [comment]
New commit that passes FLINK_SSH_OPTS to pdsh.

64 x c4.large

0m4.210s	0m4.181s
0m4.203s	0m4.283s
0m4.262s	0m4.196s

0m13.969s	0m12.533s
0m13.906s	0m13.169s
0m14.122s	0m12.343s

16 x c4.large
0m1.270s	0m1.267s
0m1.277s	0m1.164s
0m1.470s	0m1.180s

0m3.961s	0m2.985s
0m3.638s	0m3.014s
0m3.410s	0m3.159s

1 x c4.large
0m0.543s	0m0.449s
0m0.547s	0m1.300s
0m0.542s	0m0.452s

0m0.439s	0m1.247s
0m0.448s	0m1.439s
0m0.439s	0m0.827s

**Comment by greghogan** [comment]
New commit which passes FLINK_SSH_OPTS to pdsh.

Also, some sample timings starting and stopping an AWS cluster of various sizes, with ssh and pdsh comparable on a single node and pdsh noticeably faster on large clusters.

64 x c4.large | ssh | pdsh
------------- | --- | ----
start | 13.969s | 4.210s
stop | 12.533s | 4.181s
start | 13.906s | 4.203s
stop | 13.169s | 4.283s
start | 14.122s | 4.262s
stop | 12.343s | 4.196s

16 x c4.large | ssh | pdsh
------------- | --- | ----
start | 3.961s | 1.270s
stop | 2.985s | 1.267s
start | 3.638s | 1.277s
stop | 3.014s | 1.164s
start | 3.410s | 1.470s
stop | 3.159s | 1.180s

1 x c4.large | ssh | pdsh
------------- | --- | ----
start | 0.439s | 0.543s
stop | 1.247s | 0.449s
start | 0.448s | 0.547s
stop | 1.439s | 1.300s
start | 0.439s | 0.542s
stop | 0.827s | 0.452s

**Comment by fhueske** [comment]
Hi @greghogan, thanks for the update!

Looks good to merge.

**Comment by fhueske** [comment]
Merging this

**Pull request closed without merging**
