### PR TITLE
[FLINK-11442] upgrade oss sdk version

### PR DESCRIPTION
**Pull request by wujinhu**
## What is the purpose of the change

Upgrade oss sdk version to exclude org.json dependency

https://issues.apache.org/jira/browse/FLINK-11442

## Brief change log

Upgrade oss sdk version from 3.1.0 to 3.4.1

## Verifying this change

This change does not add tests

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**yes** / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by wujinhu** [comment]
**Testing results:**

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.flink.fs.osshadoop.HadoopOSSFileSystemITCase
[INFO] Running org.apache.flink.fs.osshadoop.HadoopOSSFileSystemBehaviorITCase
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.055 s - in org.apache.flink.fs.osshadoop.HadoopOSSFileSystemITCase
[WARNING] Tests run: 8, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 6.429 s - in org.apache.flink.fs.osshadoop.HadoopOSSFileSystemBehaviorITCase
[INFO]
[INFO] Results:
[INFO]
[WARNING] Tests run: 11, Failures: 0, Errors: 0, Skipped: 2

**Comment by wujinhu** [comment]
@StefanRRichter Please help to review this PR, thanks :)

**Comment by greghogan** [comment]
LGTM. Upstream fix looks to be [here](https://github.com/aliyun/aliyun-oss-java-sdk/commit/956b0e656ec452a38b0851a29eb67ced409ebb70). Updated dependency tree does not include org.json

[INFO] +- com.aliyun.oss:aliyun-sdk-oss:jar:3.4.1:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.3:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.6:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  +- org.jdom:jdom:jar:1.1:compile
[INFO] |  +- org.codehaus.jettison:jettison:jar:1.1:compile
[INFO] |  |  \- stax:stax-api:jar:1.0.1:compile
[INFO] |  +- com.aliyun:aliyun-java-sdk-core:jar:3.4.0:compile
[INFO] |  +- com.aliyun:aliyun-java-sdk-ram:jar:3.0.0:compile
[INFO] |  +- com.aliyun:aliyun-java-sdk-sts:jar:3.0.0:compile
[INFO] |  \- com.aliyun:aliyun-java-sdk-ecs:jar:4.2.0:compile

**Comment by wujinhu** [comment]
Thanks @greghogan  Would you pls help to merge this PR? It seems StefanRRichter is not available now.

**Comment by wujinhu** [comment]
@StefanRRichter Please help to review this PR, thanks :)

**Comment by StefanRRichter** [comment]
LGTM as well, merging.

**Comment by wujinhu** [comment]
Thanks @StefanRRichter

**Pull request merged**
