### PR TITLE
[FLINK-3560] [examples] Remove unchecked output of usage statement in examples

### PR DESCRIPTION
**Pull request by tillrohrmann**
This PR effectively removes all unconditioned outputs of the usage message of the examples.

### CODE REVIEW

**Comment by tillrohrmann** [comment]
That is a good point @vasia. Will add the missing `ProgramDescriptions`.

**Comment by tillrohrmann** [comment]
Added the missing `ProgramDescriptions`.

**Comment by StephanEwen** [comment]
I remember a discussion from a while back that we actually wanted to drop `ProgramDescription`.

It comes from the days when programs had to implement  specific interface and it does not really go together very well with the idea of a simple static main-method as the entry point.

**Comment by uce** [comment]
I think Stephan has a point and we should maybe not encourage usage of `ProgramDescription` in the examples, because we advertise the simple main-method entry point in all the docs.

Other than that, I think it's a good idea to remove the unconditional usage printing.

**Comment by tillrohrmann** [comment]
`ProgramDescription` has not been marked as deprecated so far. Furthermore it can be used to show information about the program using `bin/flink info` and is not mandatory. 

Admittedly, this feature isn't used by many programs but I think it does not hurt to keep and implement this interface, unless we plan to remove it soon. There was a [discussion](http://mail-archives.apache.org/mod_mbox/flink-dev/201505.mbox/%3CCAGco--b_ViG6Nx-7c1_OeNekiUrgdQJtRvrFu8+ZXw96nFwriw@mail.gmail.com%3E) which also involved `ProgramDescription`. However, it does not look to me as if it converged to some real action points.

**Comment by fhueske** [comment]
I don't think the examples should implement the `ProgramDescription` interface. This might give the impression that implementing this interface is mandatory while it is a very optional thing.

I think it is not a problem that optional program parameters such as `max-iterations` won't be printed anymore. I would expect users to look at the code anyways to understand what is happening and there they will see the optional parameters.

**Comment by tillrohrmann** [comment]
Hmm but if it is nowhere implemented then we could directly remove `ProgramDescription`. I mean why keeping code in the base which is not used? 

Furthermore, I don't think that it would harm if people implemented this interface. And if they look in the code, then they will also see that it's highly optional.

**Comment by StephanEwen** [comment]
From my side, +1 for removing the `ProgramDescription` interface.

I think it is a mismatch with the `main()` method based approach, because it needs to instantiate the class, while the general entry point is static. That does not go well together in my opinion. People will write programs with no default constructor. Previously, with the `Program` interface, such a constructor was also mandatory, it did fit better there.

**Comment by tillrohrmann** [comment]
That is a good point with the instantiation of the instances. I will update the PR accordingly.

**Comment by tillrohrmann** [comment]
Removed the `ProgramDescription` interface and rebase the PR on the latest master.

**Comment by uce** [comment]
Thanks, Till! I think this is ready to finally be merged. I will go ahead and do it.

**Pull request closed without merging**
