### PR TITLE
[FLINK-25546][FOLLOWUP] Fix illegal file name

### PR DESCRIPTION
**Pull request by wForget**
## What is the purpose of the change

I get an error when I run 'git rebase upstream/master' on windows:

```
error: invalid path 'flink-connectors/flink-connector-base/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension '
error: could not detach HEAD
```

The error is caused by the `org.junit.jupiter.api.extension.Extension` file name having a space, and this change was introduced in #21161

## Brief change log

Rename `org.junit.jupiter.api.extension.Extension` to remove a space

## Verifying this change

minor fix

## Does this pull request potentially affect one of the following parts:

no

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by wForget** [comment]
cc @snuyanzin

**Comment by Gianzie** [comment]
我说今天在家里Windows上怎么死活切不到master，原来是文件多了个空格哈哈

**Comment by wForget** [comment]
> 我说今天在家里Windows上怎么死活切不到master，原来是文件多了个空格哈哈

You can run `git config core. detect NTFS false` to bypass it.

**Comment by Wuzbre** [comment]
> > 我说今天在家里Windows上怎么死活切不到master，原来是文件多了个空格哈哈
> 
> 你可以跑来绕过它。-----------谷歌翻译-----------您可以运行 git config core。检测 NTFS false 以绕过它。`git config core. detect NTFS false`

I also get 1 error when I use `git clone https://github.com/apache/flink.git` in window11 `Error: Invalid path 'flink-connectors/flink-connector-base/src/ test/resources/ META-INF/services/org.junit.jupiter.api.extension.Extension ''. But when I try to use your method `git config --global core.detectNTFS false` it doesn’t work. The answer I got from stackoverflow `git config --global core.protectNTFS false` can successfully pull down the code.

**Comment by snuyanzin** [comment]
@wForget thanks for the contribution and fixing this
Can you please rebase the PR to the recent master version where issue with wiki was fixed (the reason of ci failing)

**Comment by wForget** [comment]
> @wForget thanks for the contribution and fixing this Can you please rebase the PR to the recent master version where issue with wiki was fixed (the reason of ci failing)

thanks, rebased

**Comment by wForget** [comment]
@snuyanzin  There was an OOM error, is this related? https://github.com/wForget/flink/actions/runs/12001935716/job/33454467401

**Comment by wForget** [comment]
> @snuyanzin There was an OOM error, is this related? https://github.com/wForget/flink/actions/runs/12001935716/job/33454467401

I reported an issue and tried to fix it. https://issues.apache.org/jira/browse/FLINK-36786

**Pull request merged**
