### PR TITLE
[hotfix][docs] fix typos

### PR DESCRIPTION
**Pull request by YngwieWang**
@aljoscha , I found two typos and fix them. PTAL

### CODE REVIEW

**Comment by 1u0** [comment]
@YngwieWang thank you for contribution!

Could you please fix the PR subject and the commit message to include `[docs]` part.
Also, please update the Chinese version of the document (`api_concepts.zh.md`).

**Comment by YngwieWang** [comment]
> @YngwieWang thank you for contribution!
> 
> Could you please fix the PR subject and the commit message to include `[docs]` part.
> Also, please update the Chinese version of the document (`api_concepts.zh.md`).

Thanks for your comment, I'm a novice. I will close this PR and open a new one.

**Comment by TisonKun** [comment]
@YngwieWang you can make use of `git commit --amend` and then `git push --force` to rewrite subject of a commit in pull request.

**Comment by YngwieWang** [comment]
> @YngwieWang you can make use of `git commit --amend` and then `git push --force` to rewrite subject of a commit in pull request.

Thanks for your comment, it helps me.

**Pull request closed without merging**
