### PR TITLE
[FLINK-29128][Connectors/Kafka] Add a new situation for split changes handling result.

### PR DESCRIPTION
**Pull request by leozhangsr**
## What is the purpose of the change

Fix the bug relative to [FLINK-29128](https://issues.apache.org/jira/browse/FLINK-29128).
Add a new situation for split changes handling result to avoid the IllegalStateException which is thrown by the kafka consumer api(function: consumer.position).

## Brief change log

  - Get the kafka consumer's assignment first, the topic partition set.
  - Get starting offset by the consumer if the assigned topic partition set contains the specific topic partition.
  - Otherwise leave information for the new situation, since this partition has been finished and unassigned.

## Verifying this change

This change is already covered by existing tests, such as KafkaPartitionSplitReaderTest#testAssignEmptySplit, but the log level must set to debug.

## Does this pull request potentially affect one of the following parts:
  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Review by mas-chen — COMMENTED** [review]
Please add a unit test

**Comment by leozhangsr** [comment]
> Please add a unit test, let's discuss more about how to solve this correctly in the JIRA ticket

I have just replied you in the JIRA ticket.Please check if it makes sense.

For the test case, the logger level is set to OFF in the flink-connectors/flink-connector-kafka/src/test/resources/log4j2-test.properties. If I set it to debug, will it lead to a unexpected effect?
I wonder if these is another way to test this bug since it only work when LOG.isDebugEnabled().
I have run this changes local, it works well.

**Comment by leozhangsr** [comment]
I had just refresh the review request, and [PatrickRen](https://github.com/PatrickRen) is removed accidently, please add him back.

**Comment by MartijnVisser** [comment]
@leozhangsr The Flink Kafka connector resides in it's own repository, if this code change is still relevant, please open the PR in https://github.com/apache/flink-connector-kafka

**Pull request closed without merging**
