### PR TITLE
[FLINK-30614][serializer] Remove old method of resolving schema compa…

### PR DESCRIPTION
**Pull request by AlexYinHan**
## What is the purpose of the change

*For Milestone-2 of FLIP-263, this PR removes the old method of resolving schema compatibility.*

## Brief change log

  - *Remove the old method.*
  - *Remove the default implementation of the new method.*
  - *Remove unnecessary tests cases.*
  - *Make deprecated serializer classes throw exceptions when calling resolveSchemaCompatibility()*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes)
  - The serializers: (yes)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Review by masteryhx — COMMENTED** [review]
Thanks for the PR. Overall LGTM.
Just two minor comments:
1. Could you also update the doc description ? you could search "The old method
`TypeSerializerSnapshot#resolveSchemaCompatibility(TypeSerializer newSerializer)` has been marked as deprecated
and will be removed in the future."
2. `GenericArraySerializerConfigSnapshot` and `EitherSerializerSnapshot` could be removed in the other PR.

**Comment by AlexYinHan** [comment]
@masteryhx Thanks for the comments. I have update the docs. PTAL.

**Comment by Zakelly** [comment]
I'd suggest removing `GenericArraySerializerConfigSnapshot` and `EitherSerializerSnapshot` with another commit by this PR.

**Comment by AlexYinHan** [comment]
@flinkbot  run azure

**Review by masteryhx — APPROVED** [review]
Thanks for the update. LGTM.

**Review by Zakelly — APPROVED** [review]

**Pull request merged**
