### PR TITLE
[FLINK-21452][connector/common] Stop snapshotting registered readers in source coordinator.

### PR DESCRIPTION
**Pull request by AHeise**
## What is the purpose of the change

Sources used to store their registered readers into the snapshot. However, when downscaling, they have unmatched readers that violate a couple of invariants.
The solution is to not store registered readers - they are re-registered on restart anyways.
To keep it backward compatible, the best option is to always store an empty list of readers while writing the snapshot and discard any recovered readers from the snapshot.

## Verifying this change

A respective ITCase will be added as part of #13845 (FLINK-19801).

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (**yes** / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by StephanEwen** [comment]
+1

Thanks for fixing this so quickly!

**Review by pnowojski — COMMENTED** [review]
Shouldn't we have an ITCase of rescaling and FLIP-27?

**Comment by AHeise** [comment]
> Shouldn't we have an ITCase of rescaling and FLIP-27?

Yes, we should. It would very much look like UnalignedCheckpointITCase.

**Review by rkhachatryan — APPROVED** [review]

**Comment by AHeise** [comment]
Added it and waiting for AZP to turn green.

**Comment by AHeise** [comment]
Failed due to unrelated FLINK-17510 ... merging.

**Pull request merged**
