### PR TITLE
[FLINK-9543][METRICS] Expose JobMaster ID to metric system

### PR DESCRIPTION
**Pull request by lamber-ken**
## What is the purpose of the change
This pull request makes flink can expose JM_ID to metric system

## Brief change log

  - Expose JobMaster ID to metric system

## Verifying this change

  - Expose JobMaster ID to metric system

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (JavaDocs)

### CODE REVIEW

**Comment by lamber-ken** [comment]
@zentol, cc.

**Comment by lamber-ken** [comment]
@zentol , cc.

**Comment by lamber-ken** [comment]
hi, @zentol, cc.

**Comment by bowenli86** [comment]
Can you also add documentation to the Metrics page?

**Comment by zentol** [comment]
This PR isn't complete. As noted in the JIRA I would like to delay work on this JIRA until 1.7, once the legacy code is dropped this will be significantly easier to implement properly.

**Comment by lamber-ken** [comment]
@zentol, ok

**Comment by zentol** [comment]
Closing this PR for now.

**Comment by lamber-ken** [comment]
> Closing this PR for now.

Hi, @zentol, maybe it's time to bring up this issue again now. 

We can't distinguish some metrics of jobmanager, because these metrics don't contains `ResourceID` like `flink_jobmanager_Status_JVM_CPU_Load`、`flink_jobmanager_Status_JVM_CPU_Time` and so on.

From `org.apache.flink.runtime.metrics.util.MetricUtils`, we can see that missing ResourceID info when init JobManagerMetricGroup.
```
public static JobManagerMetricGroup instantiateJobManagerMetricGroup(
		final MetricRegistry metricRegistry,
		final String hostname) {
	final JobManagerMetricGroup jobManagerMetricGroup = new JobManagerMetricGroup(
		metricRegistry,
		hostname);
         ...

	return jobManagerMetricGroup;
}

public static TaskManagerMetricGroup instantiateTaskManagerMetricGroup(
		MetricRegistry metricRegistry,
		TaskManagerLocation taskManagerLocation,
		NetworkEnvironment network) {
	final TaskManagerMetricGroup taskManagerMetricGroup = new TaskManagerMetricGroup(
		metricRegistry,
		taskManagerLocation.getHostname(),
		taskManagerLocation.getResourceID().toString());
         ...

	return taskManagerMetricGroup;
}
```

**Pull request closed without merging**
