### PR TITLE
[FLINK-8249] [KinesisConnector] [hotfix] aws region is never setted in KinesisProducer

### PR DESCRIPTION
**Pull request by eskabetxe**
## What is the purpose of the change

solve the issue related, adding aws region to kinesis producer configuration

## Verifying this change

This change added tests and can be verified as follows:
  - Added test that validates that region is correctly setted

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: ( no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? ( no)

### CODE REVIEW

**Comment by tzulitai** [comment]
Thanks for the fix @eskabetxe.
Can you squash commits fd9395f and 170372a, and rebase them onto latest `release-1.4` branch?

**Comment by eskabetxe** [comment]
@tzulitai done on https://github.com/apache/flink/pull/5160

this could be closed

**Comment by tzulitai** [comment]
Thanks. @eskabetxe can you manually close this? Only the issuer of the PR can close it :)

**Comment by eskabetxe** [comment]
done

**Pull request closed without merging**
