### PR TITLE
[FLINK-7958][metrics] Allow reporters to define default delimiter

### PR DESCRIPTION
**Pull request by zentol**
## What is the purpose of the change

This PR allows reporters to define their default delimiter. Previously we always defaulted to `.`.

Reporters may now implement the `DelimiterProvider` interface with which they may define a delimiter. This delimiter is used if no delimiter was explicitly configured for the reporter.

## Brief change log

* Add DelimiterProvider interface
* modify Prometheus&JmxReporter to define the default delimiter
* modify delimiter setup in the MetricRegistry
* add a test to the MetricRegistryTest to verify functionality

## Verifying this change

This change added tests and can be verified as follows:

Run MetricRegistryTest#testDelimiterOverride.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)

## Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (javadoc)

### CODE REVIEW

**Comment by bowenli86** [comment]
I would suggest another solution - rather than adding another interface 'DelimiterProvider', add `getDelimiter()` which returns '.' as an interface default method to `MetricReporter`. Any reporter impl classes that don't override it will use the default delimiter.

BTW, is it better to have `String getDelimiter()` rather than `char getDelimiter()`? Because 1) Flink has to convert char to string anyway 2) the former one provides more flexibility in defining delimiters, e.g. as multi chars

**Comment by zentol** [comment]
true, we can use default methods for this, I was concerned about backwards compatibilty but forgot about that option.

**Comment by zentol** [comment]
I would stay with char delimiters for now. We already define delimiters as chars in the MetricRegistry interface and various internal methods that people may be using.

**Comment by zentol** [comment]
I would also stick with interface option since it makes it easier to deal with backwards compatibility. We can just add another interface and keep the code path for the old interface, without polluting the `MetricReporter` interface.

**Pull request closed without merging**
