### PR TITLE
[hotfix] Removed shaded import

### PR DESCRIPTION
**Pull request by kl0u**

### CODE REVIEW

**Comment by rmetzger** [comment]
The fix looks okay.
However, can you add a rule to the checkstyle config in "tools/maven/checkstyle.xml" to ensure that the build will fail if people use wrong imports?

**Comment by kl0u** [comment]
Yes, give me a sec.

**Comment by mxm** [comment]
+1 going to merge. Let's fix the Checkstyle rule in a separate issue/pull request.

**Comment by mxm** [comment]
Follow-up issue is here: https://issues.apache.org/jira/browse/FLINK-2155

**Pull request closed without merging**
