### PR TITLE
[FLINK-32112][docs] Fix the deprecated state backend sample config in Chinese document

### PR DESCRIPTION
**Pull request by xmzhou00**
## What is the purpose of the change

This pull request fixed State Backend sample config error in zh-doc

## Brief change log

update State Backends configuration in zh-doc:
before  -> state.backend: filesystem
after     -> state.backend: hashmap   

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by WencongLiu** [comment]
Thanks for the changes @xmzhou00 . LGTM

**Review by WencongLiu — APPROVED** [review]

**Review by xmzhou00 — COMMENTED** [review]
please review，thanks @WencongLiu

**Comment by WencongLiu** [comment]
Could you update your commit message to [FLINK-32112][docs] ? @xmzhou00

**Comment by xmzhou00** [comment]
> Could you update your commit message to [[FLINK-32112](https://issues.apache.org/jira/browse/FLINK-32112)][docs] ? @xmzhou00

Could you tell be more specific. This is my first time submitting a Apache Flink PR  @WencongLiu

**Comment by xmzhou00** [comment]
> @xmzhou00 Please polish your commit message to make it more standardized. See [Flink's Commit naming conventions](https://flink.apache.org/how-to-contribute/code-style-and-quality-pull-requests/#4-commit-naming-conventions).
> 
> Such as:
> 
> [[FLINK-32112](https://issues.apache.org/jira/browse/FLINK-32112)][docs] Fix the deprecated state backend sample config in Chinese document
> 
> BTW, the title of this PR should be modified.
> 
> @reswqa will help you merge this PR. 😄

OK, Thanks for your direction 😄

**Review by reswqa — COMMENTED** [review]
Thanks @xmzhou00 and @WencongLiu, approved.

**Review by reswqa — APPROVED** [review]

**Comment by WencongLiu** [comment]
@xmzhou00 
There is a "." typo in the beginning of commit message. Please fix it. Could you please create a new PR to merge this commit to branch `1.17-release` ? Don't forget to follow the same format with this PR.

**Comment by reswqa** [comment]
> There is a "." typo in the beginning of commit message. 
+1, and there is another type: `docus` -> `docs`.

**Comment by reswqa** [comment]
Merged in ab5af143.

**Pull request closed without merging**
