### PR TITLE
[hotfix] [FLINK-31221] Fix Typo in YarnConfigOptions.

### PR DESCRIPTION
**Pull request by slfan1989**
## What is the purpose of the change
JIRA: FLINK-31221. Fix Typo in YarnConfigOptions.
I found a typo in YarnConfigOptions, I will fix it

## Brief change log

Fix Typo Issue.

## Verifying this change

Manually verified.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by slfan1989** [comment]
After I found this typo problem, I checked all the codes under moudle(flink-yarn), only this typo.

**Comment by slfan1989** [comment]
@1996fanrui Can you help review this pr? Thank you very much!

**Review by 1996fanrui — CHANGES_REQUESTED** [review]
Hi @slfan1989 , thanks for your contribution. Please build the docs based on this doc[1].

[1] https://github.com/apache/flink/blob/master/docs/README.md

**Comment by slfan1989** [comment]
@flinkbot run azure

**Comment by slfan1989** [comment]
@flinkbot run azure

**Comment by slfan1989** [comment]
@flinkbot run azure

**Review by 1996fanrui — APPROVED** [review]
Thanks for the fix.

LGTM

**Pull request merged**
