### PR TITLE
[FLINK-27851][table-planner] support to access source pks through MiniBatchAssigner

### PR DESCRIPTION
**Pull request by xuyangzhong**
## What is the purpose of the change

Currently, if we enable mini-batch, then Join can't access pk information from source through MiniBatchAssigner. 

## Brief change log

  - Support to get pks through MinibatchAssigner in FlinkRelMdUniqueKeys and FlinkRelMdUpsertKeys.
  - Add test cases to verify it.

## Verifying this change

A test case is added to verify this change.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers:  no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented?

### CODE REVIEW

**Comment by xuyangzhong** [comment]
@flinkbot run azure

**Comment by swuferhong** [comment]
+1 LGTM

**Comment by xuyangzhong** [comment]
@flinkbot  run azure

**Comment by swuferhong** [comment]
CI failed, @xuyangzhong, you can have a look.

**Comment by xuyangzhong** [comment]
@flinkbot run azure

**Review by lsyldliu — COMMENTED** [review]
LGTM

**Pull request closed without merging**
