### PR TITLE
[FLINK-26187][docs] Chinese docs only redirect for chinese urls

### PR DESCRIPTION
**Pull request by zentol**
Fix various redirects in the chinese docs, such that we only redirect if the users accessed a chinese url.

### CODE REVIEW

**Review by autophagy — COMMENTED** [review]
It looks like there were a few that werent changed, like:

- https://github.com/zentol/flink/blob/26187/docs/content.zh/docs/connectors/table/filesystem.md?plain=1#L6
- https://github.com/zentol/flink/blob/26187/docs/content.zh/docs/connectors/datastream/formats/parquet.md?plain=1#L5
- https://github.com/zentol/flink/blob/26187/docs/content.zh/docs/connectors/datastream/formats/avro.md?plain=1#L5

etc. But I'm assuming that these were ignored since the pages are untranslated?

**Comment by zentol** [comment]
Nah, the regex didn't find them. The number of spaces before the alias isn't standardized 😢

**Comment by zentol** [comment]
I'll amend the PR in a bit.

**Comment by autophagy** [comment]
Ah, okay! The ones I found with some ripgrepping were:
- `docs/ops/batch/blocking_shuffle.md`
- `docs/ops/state/checkpointing_under_backpressure.md`
- `docs/ops/state/task_failure_recovery.md`
- `docs/connectors/datastream/formats/azure_table_storage.md`
- `docs/connectors/datastream/formats/text_files.md`
- `docs/connectors/datastream/formats/parquet.md`
- `docs/connectors/datastream/formats/mongodb.md`
- `docs/connectors/datastream/formats/avro.md`
- `docs/connectors/table/filesystem.md`

**Comment by zentol** [comment]
I think that's all of them.

**Review by autophagy — APPROVED** [review]
:+1: :sparkles:

**Pull request merged**
