### PR TITLE
[FLINK-10935][ResourceManager] Implement KubeClient with Fabric8 Kubenetes clients

### PR DESCRIPTION
**Pull request by chunhui-shi**
##What is the purpose of the change
As part of native kubernetes integration. Introduce client wrapper to access Kubernetes service.

##Brief change log
* _Implement KubeClient interface and actual implementation.
* _Add mock kube server which is derived from Fabric's mock implementation.
* _A unit tests of KubeClient.

##Does this pull request potentially affect one of the following parts:
* Dependencies (does it add or upgrade a dependency): (no)
* The public API, i.e., is any changed class annotated with @Public(Evolving): ( no)
* The serializers: (no )
* The runtime per-record code paths (performance sensitive): ( no )
* Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no )
* The S3 file system connector: ( no )
##Documentation
* Does this pull request introduce a new feature? (yes)
* If yes, how is the feature documented? (the document will be introduced in later pull requests)

### CODE REVIEW

**Comment by chunhui-shi** [comment]
This is the second pull request coming after #7844.

**Comment by tillrohrmann** [comment]
There is a dependency convergence error. Please fix this error @chunhui-shi.

**Comment by tianchen92** [comment]
Hi @tillrohrmann, we have fixed the dependency convergence error, could you please help review this PR and the first PR of k8s [#7844](https://github.com/apache/flink/pull/7844) ? 
After fixing some bugs in k8s integration, now flink can work fine in minikube environment, I think it is a good time to push it back to community. After these two PRs are merged, we would like to open new PRs to continue this work. 
Looking forward to your feedback, thanks very much!

**Comment by wangyang0918** [comment]
Close this PR since it is already supported for a long time.

**Pull request closed without merging**
