### PR TITLE
[FLINK-25942][table-planner] Use jdk 8 and java time modules for duration and optional ser/de

### PR DESCRIPTION
**Pull request by slinkydeveloper**
## What is the purpose of the change

Cleanup of previous custom ser/de for duration, and introduced jdk8 module for ser/de

## Brief change log

* Use jdk 8 and java time modules for duration and optional ser/de

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Review by matriv — APPROVED** [review]
LGTM, Thank you @slinkydeveloper !

**Comment by fapaul** [comment]
I would actually propose to create a ticket for this change. To me as someone with less table knowledge, it is not clear why it is safe to remove the previous serde and why it was developed in the first place.

**Comment by slinkydeveloper** [comment]
I opened an issue here https://issues.apache.org/jira/browse/FLINK-25942. The only reason why we have on master that Duration custom ser/de is that until https://issues.apache.org/jira/browse/FLINK-25588 we hadn't the jackson module.

**Comment by fapaul** [comment]
@slinkydeveloper thanks for the clarification.

**Pull request merged**
