### PR TITLE
[FLINK-3438] ExternalProcessRunner fails to detect ClassNotFound exception because of locale settings

### PR DESCRIPTION
**Pull request by stefanobaghino**
This should be regarded as a temporary solution to this issue in particular. See the discussion going on at [[FLINK-3438]].

[FLINK-3438]: https://issues.apache.org/jira/browse/FLINK-3438

### CODE REVIEW

**Comment by aljoscha** [comment]
Anyone against merging this as a (maybe temporary) solution?

**Comment by StephanEwen** [comment]
Should be okay for the tests.

Just make sure you don't try to parse the returned stderr stream, but simply take non-empty stream as an exception with a copy of the stderr data.

**Comment by stefanobaghino** [comment]
I'm going into the direction proposed by @StephanEwen, the change looks trivial.

**Comment by stefanobaghino** [comment]
Running the test locally with the same `PROFILE` as the failing tests do not yield the same results (i.e. all tests pass). Is there a way to determine if this was just a hiccup in the CI environment? Meanwhile, I'm rerunning the tests on our fork.

**Comment by StephanEwen** [comment]
The test failure looks unrelated to this fix.

+1 to merge this

**Comment by tillrohrmann** [comment]
Thanks for your contribution @stefanobaghino. Will merge it.

**Pull request closed without merging**
