### PR TITLE
[build][minor] Add missing licenses

### PR DESCRIPTION
**Pull request by yew1eb**

### CODE REVIEW

**Comment by StephanEwen** [comment]
Thanks, good addition.
Have you checked whether the shell scripts still work now, or whether they get confused by the headers?

If all works, can you remove the exclusions from the RAT checks (root pom.xml) for these files, so that the presence of headers is checked in the future?

**Comment by yew1eb** [comment]
@StephanEwen, I see, we need a script to automatically check the headers licenses.
I will think about how to implement this script...

**Comment by StephanEwen** [comment]
We already have a script, it is the RAT plugin: https://github.com/apache/flink/blob/master/pom.xml#L957

You only need to make sure that these files are not excluded from the check...

**Comment by yew1eb** [comment]
thx,  OIC,   I have updated this PR.  :)

**Comment by yew1eb** [comment]
@StephanEwen  ping

**Comment by greghogan** [comment]
Adding the license to `browserconfig.xml` looks fine, but why change the user configurations `masters`, `slaves`, and `zoo.cfg`? Are these even copyrightable?

**Comment by StephanEwen** [comment]
The `masters` and `slaves` file probably does not need a license header (although the rules of when you need one and when not are not very clear to me).

I think config files frequently have a license header, so I would take the `zoo.cfg` change.

@yew1eb Are you okay if we merge this without the changes to `masters` and `slaves`?

**Comment by yew1eb** [comment]
@StephanEwen, @greghogan , I'm sorry to reply late, a little busy recently.

Stephan, I agree with you. 

This PR has been updated.

**Comment by greghogan** [comment]
+1

**Pull request closed without merging**
