### PR TITLE
[BP-1.18][FLINK-33149][build] Bump snappy to 1.1.10.4

### PR DESCRIPTION
**Pull request by RyanSkraba**
## What is the purpose of the change

Backport of https://github.com/apache/flink/pull/23458 to `release-1.18`

Bump the version of snappy to address a vulnerability.

## Verifying this change

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): **yes**
  - The public API, i.e., is any changed class annotated with **no**
  - The serializers: **no**
  - The runtime per-record code paths (performance sensitive): **no**
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: **no**
  - The S3 file system connector: **no**

## Documentation

  - Does this pull request introduce a new feature? **no**
  - If yes, how is the feature documented? **not applicable**

### CODE REVIEW

**Comment by XComp** [comment]
@flinkbot run azure

**Comment by XComp** [comment]
```
16:26:18.071 [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.11.0:install-node-and-npm (install node and npm) on project flink-runtime-web: Could not extract the Node archive: Could not extract archive: '/__w/2/.m2/repository/com/github/eirslett/node/16.13.2/node-16.13.2-linux-x64.tar.gz': EOFException -> [Help 1]
16:26:18.071 [ERROR] 
16:26:18.071 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
16:26:18.071 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

Azure retry initiated because of the error in compile stage. It looks like an infrastructure issue.

**Review by XComp — APPROVED** [review]
LGTM :+1:

**Comment by JingGe** [comment]
@flinkbot run azure

**Review by JingGe — APPROVED** [review]
LGTM

**Pull request merged**
