### PR TITLE
[FLINK-15089][connectors] Puslar catalog

### PR DESCRIPTION
**Pull request by yjshen**
## What is the purpose of the change

This PR implements Pulsar catalog which is part of [FLIP-72](https://cwiki.apache.org/confluence/display/FLINK/FLIP-72%3A+Introduce+Pulsar+Connector).

The Pulsar catalog supports the following features by extending `AbstractCatalog` API:
- Open and close the catalog
- Database operations: list, get, exists, create, drop (create and drop should first check if the user has sufficient permissions)
- Table operations: list, get, exist, create, drop (create and drop should first check if the user has sufficient permissions)

## Brief change log

- The main functionality of Catalog exists in `PulsarCatalog` and `PulsarMetadataReader`.
- Pulsar Schema <-> Flink type conversion exists in `SchemaUtils`.

## Verifying this change

This PR will be tested by unit tests and integration tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes) . Add Pulsar dependencies.
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (https://docs.google.com/document/d/1LMnABtXn-wQedsmWv8hopvx-B-jbdr8-jHbIiDhdsoE/edit?usp=sharing)

### CODE REVIEW

**Comment by yjshen** [comment]
@bowenli86 Hi Bowen, I've updated the PR with tests. Could you please help review it? Thanks!

**Comment by bowenli86** [comment]
hi @yjshen  sorry for the late response, I'm really busy right now and may have some time later April to take a detailed look. Can you try to find some other committers to help review?

**Comment by KurtYoung** [comment]
Hi @yjshen , sorry for the late response on this. I think right now the community is busy with finishing 1.11 planned features thus don't have much capacity for reviewing this. I would raise this during 1.12 feature planning and hopefully we can get this and pulsar connectors in Flink 1.12.

**Comment by yjshen** [comment]
Hi @bowenli86 @KurtYoung, thanks for the update. Looking forward to further discussions on this PR.

**Pull request closed without merging**
