### PR TITLE
[FLINK-3167] Improve documentation for window apply

### PR DESCRIPTION
**Pull request by rtudoran**
Small correction and extension for the window apply example

### CODE REVIEW

**Comment by zentol** [comment]
it appears that you used the wrong issue ID; it should be 31**76** but is 31**67**.

**Comment by rmetzger** [comment]
Thank you for opening a pull request for fixing this.
I think its good to merge.

**Comment by fhueske** [comment]
Will merge this PR

**Comment by rtudoran** [comment]
Hi,
Should I do a re-commit and a pull request with the correct JIRA Number? 

    On Wednesday, 6 January 2016, 16:02, zentol <notifications@github.com> wrote:
 

 it appears that you used the wrong issue ID; it should be 3176 but is 3167.—

**Comment by fhueske** [comment]
Hi @rtudoran, I merged your PR.
No need to open another one for this issue :-)

**Pull request closed without merging**
