### PR TITLE
[hotfix][doc] Refine code examples in data_stream_api

### PR DESCRIPTION
**Pull request by liuml07**
## What is the purpose of the change

Refine code examples in data_stream_api

## Brief change log

 * Fix variable names to make code example cleaer
 * Make it clear different examples in the same code block
 * Add necessary package import so code example is runnable
 * Update both zh and en docs

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by liuml07** [comment]
CC @twalthr

**Comment by Myasuka** [comment]
@liuml07 Please refine the commit message to `[hotfix][doc] Refine code examples in data_stream_api ` before I merge this PR.

**Comment by Myasuka** [comment]
The CI failed due to FLINK-29427

@flinkbot run azure

**Comment by Myasuka** [comment]
The CI failed due to FLINK-24119

@flinkbot run azure

**Comment by liuml07** [comment]
Thank you @Myasuka for prompt review and commit.

**Pull request merged**
