### PR TITLE
[hotfix] Fix doc about temporal functions

### PR DESCRIPTION
**Pull request by yittg**
## What is the purpose of the change

Looks like it's a typo, fix me if i'm wrong, it's confused.

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluster with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by yittg** [comment]
cc @wuchong

**Review by MartijnVisser — CHANGES_REQUESTED** [review]
Thanks for your PR @yittg - Please update your PR to follow the commit naming conventions (see https://flink.apache.org/contributing/code-style-and-quality-pull-requests.html#commit-naming-conventions). It should be something like [hotfix][docs] What you're actually changing with your commit.

**Comment by yittg** [comment]
@MartijnVisser Thanks for your suggestion, i've updated the commit message, PTAL

**Comment by MartijnVisser** [comment]
@yittg I've just taken a real look: I'm not sure it's a typo. Looking at https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/functions/systemfunctions/ it looks like you can use YEAR(date) function directly in SQL and also use it in the Table API, while the other interval functions currently can only be used in the Table API (there's no equivalent function yet implemented for SQL). Your PR removes the YEAR(date) from the list of SQL functions. Have you verified that this function is indeed not available?

**Comment by yittg** [comment]
@MartijnVisser I think it's documented in the following row at line#442. it always using pattern  of INTERVAL '1' YEAR to present interval. Would you take a look?

**Comment by yittg** [comment]
I think YEAR(date) is not used for interval , it's too weird. If I understand wrongly, feel free to close this PR. @MartijnVisser

**Review by MartijnVisser — APPROVED** [review]
@yittg You're right, I didn't look properly. Thanks for the fix! Could you also create backports towards the `release-1.15` and `release-1.14` branch?

**Comment by yittg** [comment]
> Could you also create backports towards the `release-1.15` and `release-1.14` branch?

Happy to do it.

**Pull request merged**
