### PR TITLE
[FLINK-17569][FileSystemsems]support ViewFileSystem when wait lease revoke of hadoop filesystem

### PR DESCRIPTION
**Pull request by wxplovecc**
What is the purpose of the change

This pull request makes `HadoopRecoverableFsDataOutputStream#revokeLeaseByFileSystem` support `ViewFileSystem`  when using viewfs the `revokeLeaseByFileSystem` method will not wait the file Lease to revoke because of  not instance of  `DistributedFileSystem`

## Brief change log

  -  resolve the real path and FileSystem of ViewFileSystem then wait to revoke the file lease 

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by wxplovecc** [comment]
@flinkbot run azure

**Comment by StephanEwen** [comment]
Thank you for diagnosing this and suggesting this patch!

The patch looks good.

Any chance you could add a simple test that can verify this? Maybe extend the test that rund on the HDFS minicluster and wrap it in a viewFs?

**Comment by wxplovecc** [comment]
@StephanEwen Ok, I will try to add a test

**Comment by wxplovecc** [comment]
@StephanEwen added some viewfilesystem test by HDFS minicluster, after test I found last commit was not work because of #11815 has mentioned and the `truncate` method also need resolved path

**Comment by StephanEwen** [comment]
Thank you for looking into the test.

Unfortunately, this PR now contains a very large amount of unrelated code format changes and we cannot review or merge it like that [1]. These re-formattings hide the real important changes, hide root causes for line changes, in the git history, etc. Please make sure your IDE does not auto-format classes on save or so. The PR must really include only the relevant changes, not unrelated additional changes.

[1] https://flink.apache.org/contributing/contribute-code.html

**Comment by wxplovecc** [comment]
updated

**Pull request closed without merging**
