### PR TITLE
[WIP][FLINK-2386] Add new Kafka Consumers

### PR DESCRIPTION
**Pull request by rmetzger**
I'm opening a WIP pull request (against our rules) to get some feedback on my ongoing work.
Please note that I'm on vacation next week (until August 17)

**Why this rework?**

The current `PersistentKafkaSource` does not always provide exactly-once processing guarantees because we are using the high level Consumer API of Kafka.
We've chosen to use that API because it is handling all the corner cases such as leader election, leader failover and other low level stuff.
The problem is that the API does not allow us to
- commit offsets manually
- consistently (across restarts) assign partitions to Flink instances  

The Kafka community is aware of these issues and actively working on a new Consumer API. See https://cwiki.apache.org/confluence/display/KAFKA/Kafka+0.9+Consumer+Rewrite+Design and https://issues.apache.org/jira/browse/KAFKA-1326
The release of Kafka 0.8.3 is scheduled for October 2015 (see plan: https://cwiki.apache.org/confluence/display/KAFKA/Future+release+plan)

Therefore, I decided for the following approach:
Copy the code of the unreleased, new Kafka Consumer into the Flink consumer and use it.
The new API has all the bells and whistles we need (manual committing, per-partition subscriptions, nice APIs), but it is not completely backwards compatible.

We can retrieve topic metadata with the new API from Kafka 0.8.1, 0.8.2 (and of course 0.8.3)
We can retrieve data from Kafka 0.8.2 (and 0.8.3)
We can only commit to Kafka 0.8.3

Therefore, this pull request contains three different user facing classes `FlinkKafkaConsumer081`,  `FlinkKafkaConsumer082` and `FlinkKafkaConsumer083` for the different possible combinations.
For 0.8.1 we are using a hand-crafted implementation against the simple consumer API (https://cwiki.apache.org/confluence/display/KAFKA/0.8.0+SimpleConsumer+Example) so we had to do what we originally wanted to avoid.
I tried to make that implementation as robust and efficient as possible. I'm intentionally not handling any broker failures in the code. For these cases, I'm relying on Flink's fault tolerance mechanisms (which effectively means redeploying the Kafka sources against other online brokers)

For reviewing the pull request, there are only a few important classes to look at:
- FlinkKafkaConsumerBase
- IncludedFetcher
- LegacyFetcher (the one implementing the SimpleConsumer API)
I fixed a little bug in the stream graph generator. It was ignoring the "number of execution retries" when no checkpointing is enabled. 

Known issues:
- this pull request contains at least one failing test
- the KafkaConsumer contains at least one known, yet untested bug
- missing documentation

I will also open a pull request for using the new Producer API. It provides much better performance and usability.

Open questions:
- Do we really want to copy 20k+ lines of code into our code base (for now)? 
If there are concerns about this, I could also manually implement the missing pieces. Its probably 100 lines of code for getting the partition infos for a topic, and we would use the Simple Consumer also for reading from 0.8.2.

- Do we want to use the packaging I'm suggesting here (additional maven module for `flink-connector-kafka-083`). We would need to introduce it anyways when Kafka releases 0.8.3 because the dependencies are not compatible.
But its adding confusion for our users.
I will write more documentation for guidance.

### CODE REVIEW

**Comment by uce** [comment]
Thanks for all the information Robert! I will have a more detailed look at the classes you mentioned until you are back. Regarding the open questions:

1) Copying code
- I don't see a problem with this in general. I would assume that the copied solution will lead to less surprises in the end. After the new API is released by Kafka, we can remove the code, right?

2) Packaging
- I think it's OK with proper documentation and as you said we have to do it anyways at some point in time.

---

I've started a discussion about a bug fix release for 0.9. I think this issue is a blocker for that release. What's your stand on this? What do you think how much longer it will take after you are back?

**Comment by StephanEwen** [comment]
Since Kafka is Apache, copying should be okay. It is good style, though, to add to every copied file a note of origin.

And this is a temporary solution anyways, since we can get rid of most of the copied files as soon as the new Kafka release is properly out.

**Comment by StephanEwen** [comment]
I'll take a stab at checking out this monster ;-)

**Comment by StephanEwen** [comment]
I am in the middle of polishing this, adding more tests, and fixing quite a few remaining bugs. Will hopefully open a new pull request soon.

**Comment by StephanEwen** [comment]
I think we can close this pull request, it has been subsumed by #1028

**Pull request closed without merging**
