### PR TITLE
[hotfix][filesystem]improve the filesystem connector doc

### PR DESCRIPTION
**Pull request by zhisheng17**
## What is the purpose of the change

improve the filesystem connector doc

### CODE REVIEW

**Comment by leonardBang** [comment]
Thanks @JingsongLi for the contribution, LGTM, could you rebase and squash this to one commit?

**Review by leonardBang — APPROVED** [review]

**Comment by zhisheng17** [comment]
@leonardBang thanks, i have rebase and squash the commit

**Comment by leonardBang** [comment]
@flinkbot run azure

**Review by wuchong — APPROVED** [review]
LGTM.

**Pull request merged**
