### PR TITLE
FLINK-4437 Lock evasion around lastTriggeredCheckpoint may lead to lost updates to related fields

### PR DESCRIPTION
**Pull request by tedyu**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [ ] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [ ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by ramkrish86** [comment]
If the lock scope is going to be moved for the entire triggerCheckpoint() method then 

`// since we released the lock in the meantime, we need to re-check
				// that the conditions still hold. this is clumsy, but it allows us to
				// release the lock in the meantime while calls to external services are
				// blocking progress, and still gives us early checks that skip work
				// if no checkpoint can happen anyways`

Then the above comment and the checks that we perform below it can also be removed since we don't release and acquire the lock again.

**Comment by StephanEwen** [comment]
Will merge this and remove redundant comments/code...

**Comment by StephanEwen** [comment]
Have to step back. This pull request is completely broken: It does not compile and after fixing this the build fails with checkstyle errors.

I would suggest to close it, I have actually reproduced this fix in the meantime.

**Comment by tedyu** [comment]
Pardon.

See if the current formation is the same as your reproduction.

**Comment by tedyu** [comment]
What's the command line for running EventTimeWindowCheckpointingITCase alone ?

I tried 'mvn test -Dtest=EventTimeWindowCheckpointingITCase' which didn't work.

Thanks

**Comment by tedyu** [comment]
```
Executing Maven:  -B -f /home/jenkins/jenkins-slave/workspace/flink-github-ci/pom.xml -Dmaven.repo.local=/home/jenkins/jenkins-slave/maven-repositories/1 clean install -Dflink.forkCount=1C
```
I don't see flink-github-ci in the source tree.

**Comment by tedyu** [comment]
I ran test suite which patch which failed here:
```
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 201.106 sec <<< FAILURE! - in org.apache.flink.runtime.jobmanager.TaskManagerFailsWithSlotSharingITCase
The JobManager should handle gracefully failing task manager with slot sharing(org.apache.flink.runtime.jobmanager.TaskManagerFailsWithSlotSharingITCase)  Time elapsed: 200.43 sec  <<< ERROR!
java.util.concurrent.TimeoutException: Futures timed out after [200000 milliseconds]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:153)
        at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:86)
        at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:86)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
        at scala.concurrent.Await$.ready(package.scala:86)
        at org.apache.flink.runtime.minicluster.FlinkMiniCluster.waitForTaskManagersToBeRegistered(FlinkMiniCluster.scala:455)
        at org.apache.flink.runtime.minicluster.FlinkMiniCluster.waitForTaskManagersToBeRegistered(FlinkMiniCluster.scala:439)
        at org.apache.flink.runtime.minicluster.FlinkMiniCluster.start(FlinkMiniCluster.scala:330)
        at org.apache.flink.runtime.minicluster.FlinkMiniCluster.start(FlinkMiniCluster.scala:269)
        at org.apache.flink.runtime.testingUtils.TestingUtils$.startTestingCluster(TestingUtils.scala:86)
        at org.apache.flink.runtime.jobmanager.TaskManagerFailsWithSlotSharingITCase$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(TaskManagerFailsWithSlotSharingITCase.scala:73)
        at org.apache.flink.runtime.jobmanager.TaskManagerFailsWithSlotSharingITCase$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(TaskManagerFailsWithSlotSharingITCase.scala:53)
        at org.apache.flink.runtime.jobmanager.TaskManagerFailsWithSlotSharingITCase$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(TaskManagerFailsWithSlotSharingITCase.scala:53)
        at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
        at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
        at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
        at org.scalatest.Transformer.apply(Transformer.scala:22)
        at org.scalatest.Transformer.apply(Transformer.scala:20)
        at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
        at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
        at org.apache.flink.runtime.jobmanager.TaskManagerFailsWithSlotSharingITCase.withFixture(TaskManagerFailsWithSlotSharingITCase.scala:38)
```
Doesn't seem to be related to patch.

**Comment by StephanEwen** [comment]
@tedyu No problem, happens to everyone.

I actually took your code and extended it a bit. Merged in 4da40bcb9ea01cb0c5e6fd0d7472dc09397f648e

**Comment by StephanEwen** [comment]
@tedyu Should we close this pull request?

**Pull request closed without merging**
