### PR TITLE
[hotfix][docs] fix typo in table api operations

### PR DESCRIPTION
**Pull request by akinfelami**
scan is misspelled as scane

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (don't know)
  - The S3 file system connector: (don't know)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Review by reswqa — APPROVED** [review]
Thanks for fixing this.

**Comment by reswqa** [comment]
I wonder if this fix also apply to `master` branch?

**Comment by akinfelami** [comment]
Looks like it does - https://github.com/apache/flink/blob/master/docs/content/docs/dev/table/tableApi.md#from

**Comment by reswqa** [comment]
Thank you for your confirmation. I manually picked up the master(via https://github.com/apache/flink/commit/543091275f1f5cce00302053c1216907608cd40b).

**Pull request merged**
