### PR TITLE
[FLINK-31878][connectors] Fix the wrong name of PauseOrResumeSplitsTask#toString

### PR DESCRIPTION
**Pull request by TanYuxin-tyx**
## What is the purpose of the change

*Fix the wrong name of PauseOrResumeSplitsTask#toString in connector fetcher*

## Brief change log

*Fix the wrong name of PauseOrResumeSplitsTask#toString in connector fetcher*

## Verifying this change

This change is a typo fix without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Review by reswqa — APPROVED** [review]
Thanks @TanYuxin-tyx for the fix, LGTM. Merged % CI.

**Comment by MartijnVisser** [comment]
Wouldn't this break all connectors that have implemented this method already, like Kafka?

**Review by liuyongvs — APPROVED** [review]
LGTM +1

**Comment by TanYuxin-tyx** [comment]
@reswqa @MartijnVisser @liuyongvs Thanks for reviewing.

**Pull request merged**
