### PR TITLE
[FLINK-13117][table-planner-blink] Do not need to backup and restore …

### PR DESCRIPTION
**Pull request by XuPingyong**
…streamEnv config in BatchExecutor

## What is the purpose of the change

Because streamEnv can not be reuse for batch table job, streamEnv config is no need to backup and restore.

## Brief change log

Minor fix in BatchExecutor.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: ( no )
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: ( no )
  - The S3 file system connector: ( no)

## Documentation

  - Does this pull request introduce a new feature? ( no)

### CODE REVIEW

**Comment by Myasuka** [comment]
Is this PR refers to a wrong JIRA issue number?

**Comment by wuchong** [comment]
Oh...  You are right @Myasuka , this PR refers to a wrong JIRA id by mistake. However, I have merged this...

**Comment by Myasuka** [comment]
Actually, there also existed some commits referred to wrong JIRA issue number. How about leaving comments in FLINK-13117 to redirect the correct JIRA so that developers could follow the correct order then.

**Comment by wuchong** [comment]
Sure. Thanks for the advice @Myasuka

**Pull request closed without merging**
