### PR TITLE
[FLINK-2090] toString of CollectionInputFormat takes long time when t…

### PR DESCRIPTION
**Pull request by mushketyk**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

…he collection is huge

### CODE REVIEW

**Comment by mushketyk** [comment]
Set maximum limit for the toString result, as suggested by Stephan here: https://issues.apache.org/jira/browse/FLINK-2090

**Comment by StephanEwen** [comment]
Looks good. Can you remove the Guava dependency, though? We try to avoid Guava as much as possible, because it causes too many dependency issues...

**Comment by StephanEwen** [comment]
@mushketyk Are you going to update this pull request?

**Comment by mushketyk** [comment]
@StephanEwen Sorry, somehow I missed your comment. I'll update the PR today.

**Comment by mushketyk** [comment]
@StephanEwen I've updated the PR according to your review.

**Comment by StephanEwen** [comment]
Looks good, merging this...

**Comment by mushketyk** [comment]
Awesome! Thank you.

**Pull request closed without merging**
