### PR TITLE
[Flink-1934] Add approximative k-nearest-neighbours (kNN) algorithm to machine learning library

### PR DESCRIPTION
**Pull request by danielblazevski**
I added approximate knn algorithms.  In another PR, there are two exact methods, one basic algorithms using a prirority queue and another using a quadtree (see: https://github.com/apache/flink/pull/1220 ).  

For this PR, I added z-value based knn and LSH (Locality Sensitive Hashing) based knn.  Z-values are good for low-to-moderate dimension.  For details, see the paper [2] someone put on the exact JIRA issue: 
https://issues.apache.org/jira/browse/FLINK-1745
https://www.cs.utah.edu/~lifeifei/papers/mrknnj.pdf

The z-value approach isn't applicable for larger dimensions, so I used -- as the paper suggests -- a more standard LSH approach. 

The paper describes a fairly sophisticated MapReduce (MR) design, which I did not use.  Using the same MR design pattern as the exact method, I found really good performance improvement!  In JIRA, I ran this by @tillrohrmann, and he was OK with a less optimized version for now. Here is a link for a talk I recently gave on this, which includes links for the video and slides:
http://www.meetup.com/ny-scala/events/231163636/

Because both the LSH and z-value use the same MR design pattern as the exact versions, I reformatted the codebase from the PR for exact version a bit to make it more modular.

### CODE REVIEW

**Comment by danielblazevski** [comment]
btw, not sure what the standards are, should I squash all this into one commit before doing a PR?  Or do you occasionally like to see many commits of a PR?

**Comment by chiwanpark** [comment]
Hi @danielblazevski, thanks for opening pull request. I would like to split approximative knn and exact knn. If the approximative method needs exact knn implementation, could you wait until merging #1220? I'll merge it in few days (maybe today or tomorrow at latest).

**Comment by danielblazevski** [comment]
@chiwanpark happy to wait. Should I close and re-open a PR when that's done or just leave this open knowing that it will not begin being reviewed until the other is merged?

**Comment by chiwanpark** [comment]
I think that closing this and re-opening after #1220 is merged is better because reviewing is easier.

**Comment by danielblazevski** [comment]
Sounds good, about to close

**Comment by danielblazevski** [comment]
Closing this and making a new PR to avoid conflicts.  My guess is that the conflicts are there since I opened the PR initially before the exact KNN PR was merged

**Pull request closed without merging**
