### PR TITLE
[FLINK-7034] Bump Dropwizard Metrics version to 3.2.3

### PR DESCRIPTION
**Pull request by aljoscha**
R: @zentol

### CODE REVIEW

**Comment by zentol** [comment]
I would only bump it to `3.1.5`. This version also contains the required fix.

Switching to 3.2 should imo only be done after manually testing all reporters since we don't have IT cases in place.

**Comment by aljoscha** [comment]
Gotcha, I'll "downgrade" to `3.1.5`.

**Comment by aljoscha** [comment]
(And yes, this already seems to complicated for a one-line version change. 😅)

**Comment by zentol** [comment]
+1.

**Comment by aljoscha** [comment]
Thanks for reviewing! 😃

**Pull request closed without merging**
