### PR TITLE
[hotfix][connector] fix typo in filters of maven shade plguin

### PR DESCRIPTION
**Pull request by docete**
## What is the purpose of the change

Fix typo in filters of maven shade plugin.

## Brief change log
* Fix typo

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by docete** [comment]
I check maven plugin code and did some experiments. The conclusion is that Maven maps plugin configuration in xml to a Mojo(by @parameter annotation). And when the mojo has an array parameter(<excludes></excludes> in this case), maven do not check the sub-tag of that parameter.

**Comment by docete** [comment]
That's why the typo exclude works.

**Comment by wuchong** [comment]
Thanks for the explanation @docete . Looks good to me. 
Wait the travis compile pass.

Btw, do you intend to merge this to  1.9?

**Comment by docete** [comment]
> Thanks for the explanation @docete . Looks good to me.
> Wait the travis compile pass.
> 
> Btw, do you intend to merge this to 1.9?

Yes, should i create another PR for 1.9?

**Comment by wuchong** [comment]
@docete , not needed. I will cherry pick to 1.9.

**Comment by docete** [comment]
@wuchong OK, Thanks.

**Pull request merged**
