### PR TITLE
[FLINK-33340] Upgrade jackson from 2.14.3 to 2.15.3

### PR DESCRIPTION
**Pull request by snuyanzin**
## What is the purpose of the change

The PR is to bump jackson to 2.15.3 

## Brief change log

pom and NOTICE files

## Verifying this change

This change is a trivial rework 

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes )
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: ( no )
  - The runtime per-record code paths (performance sensitive): ( no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: ( no )
  - The S3 file system connector: (no )

## Documentation

  - Does this pull request introduce a new feature? ( no)
  - If yes, how is the feature documented? (not applicable )

### CODE REVIEW

**Comment by Shreya111111** [comment]
@snuyanzin I want to work on this issue

**Review by TanYuxin-tyx — APPROVED** [review]
LGTM. In addition, I checked 2.15.3 is the latest version of 2.15.x. I do have a minor question though. Could the reason for not using 2.16.0 be related to potential bugs and compatibility concerns? thanks.

**Comment by JingGe** [comment]
@TanYuxin-tyx I think it is always recommended to use one lower version, since the most up-to-date version might not be stable enough, especially with the first new minor version x.x.0 release.

**Review by JingGe — APPROVED** [review]
LGTM

**Comment by snuyanzin** [comment]
Thanks for taking a look

>I think it is always recommended to use one lower version, since the most up-to-date version might not be stable enough, especially with the first new minor version x.x.0 release.

+1

**Comment by TanYuxin-tyx** [comment]
OK. Thanks for the explanation.

**Pull request merged**
