### PR TITLE
[FLINK-11821] fix the error package location of KafkaDeserializationSchemaWrapper.java

### PR DESCRIPTION
**Pull request by lamber-ken**
## What is the purpose of the change

fix the error package location of KafkaDeserializationSchemaWrapper.java

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (yes)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by zentol** [comment]
Why do you consider the current package to be wrong?

**Comment by lamber-ken** [comment]
> Why do you consider the current package to be wrong?

hi, the mismatch between KafkaDeserializationSchemaWrapper class's package name and file's location

**Comment by lamber-ken** [comment]
image

**Comment by aljoscha** [comment]
Very strange that this even compiles ...

The correct way of fixing this is to change the `package ...` statement, though. I think the file is in the right location.

**Comment by aljoscha** [comment]
@flinkbot approve consensus

**Comment by lamber-ken** [comment]
@aljoscha you mean just need to fix the `package ...`
not move it to `org.apache.flink.streaming.util.serialization`?

**Comment by lamber-ken** [comment]
@aljoscha, it's ok to let the `KafkaDeserializationSchemaWrapper` under package `...util.serialization` and there is not much need to move it to package `...internals` from my side.

image

**Comment by lamber-ken** [comment]
@flinkbot approve all

**Comment by aljoscha** [comment]
It is a class that is specific to Kafka and that is internal, that's why it should be in the `kafka.internals` package.

**Comment by lamber-ken** [comment]
> It is a class that is specific to Kafka and that is internal, that's why it should be in the `kafka.internals` package.

right, but other classes like `JSONKeyValueDeserializationSchema`, `KeyedSerializationSchemaWrapper`, `KeyedSerializationSchemaWrapper` and so on are in flink-connector-kafka-base module and they are also specific to Kafka currently.

**Comment by aljoscha** [comment]
I agree, yes. The reason only `KafkaDeserializationSchemaWrapper` is in the correct location is that it was changed as part of https://issues.apache.org/jira/browse/FLINK-8354. `JSONKeyValueDeserializationSchema` should also be in the Kafka package, but not internal, While the wrappers should be in the internal Kafka package. I did not move `JSONKeyValueDeserializationSchema` and `KeyedSerializationSchema` because they are user-facing classes.

**Comment by aljoscha** [comment]
@lamber-ken Do you want to move both `KeyedSerializationSchemaWrapper` and `KafkaDeserializationSchemaWrapper` to the `kafka.internals` package? These two are internal classes that are also marked as `@Internal` so we can move them there without breaking anything. We have to move quickly, because I want to create a first release candidate (RC) for Flink 1.8.0 as soon as possible.

**Comment by lamber-ken** [comment]
@aljoscha, `TypeInformationKeyValueSerializationSchema` also marked as `@Internal`, should I move it now to `kafka.internals` package now?

**Comment by lamber-ken** [comment]
@aljoscha, I pushed two commits to fix the problem, cc.

**Comment by aljoscha** [comment]
`TypeInformationKeyValueSerializationSchema` is a strange case. I think you're right that it should be `@PublicEvolving`, because it is meant to be used by users.

**Comment by aljoscha** [comment]
Thanks a lot for working on this so quickly, @lamber-ken! 😃 I'll merge once Travis is green and then I can start creating a release candidate.

**Comment by aljoscha** [comment]
Merged, thanks again, @lamber-ken!

**Comment by lamber-ken** [comment]
@aljoscha，you are welcome.

**Pull request closed without merging**
