### PR TITLE
[FLINK-31082][table-planner] Setting maven property 'flink.resueForks' to false in table planner module

### PR DESCRIPTION
**Pull request by swuferhong**
## What is the purpose of the change

This pr is aims to alleviate the CI OOM problem mentioned in issue: https://issues.apache.org/jira/browse/FLINK-18356.

Setting maven property `flink.resueForks` to false in table planner module can only reduce the frequency of oom error, but can't solve this problem.

## Brief change log

- change the `pom.xml` in table planner module.

## Verifying this change

This pr need to run CI for multiple times to verify that the CI OOM problem will not frequently happen.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? no docs.

### CODE REVIEW

**Review by MartijnVisser — APPROVED** [review]
@swuferhong Thanks for the PR! Can you also create backports to the `release-1.17` and `release-1.16` branch?

**Comment by swuferhong** [comment]
> @swuferhong Thanks for the PR! Can you also create backports to the `release-1.17` and `release-1.16` branch?

Hi, @MartijnVisser. Because the root case of the error `exit 137 OOM` has not been completely found, I want to observe the master CI for a period of time, or cherry-pick it into the previous branch after finding a complete repair method. WDYT?

**Comment by MartijnVisser** [comment]
I would at least move it to `release-1.17` given that we're trying to stabilize that as much as possible.

**Comment by swuferhong** [comment]
> I would at least move it to `release-1.17` given that we're trying to stabilize that as much as possible.

Ok, I will do it.

**Pull request merged**
