### PR TITLE
[FLINK-297] [web frontend] First part of JobManager runtime monitor REST API

### PR DESCRIPTION
**Pull request by StephanEwen**
This pull requests is the first step towards the new JobManager monitoring web frontend.

The code for the new web server that handles the requests is in `flink-runtime-web`. That way, we keep
the core runtime project free of the fat dependencies that come with some web frameworks.

The new webserver runs side by side the old one for now.
You can activate the new web server by adding `jobmanager.new-web-frontend: true` to the config.

By default, the server listens at `http://localhost:8082`.

The implementation uses almost pure netty, which is fast and lightweight (dependency wise), and we are using netty anyways in the network stack for data exchange.

The server currently answers the following requests:

http://localhost:8082/overview
http://localhost:8082/jobs
http://localhost:8082/jobs/\<job-id\>
http://localhost:8082/jobs/\<job-id\>/vertices
http://localhost:8082/jobs/\<job-id\>/plan

Here, \<job-id\> refers to a the ID of a current or archived job.

All requests respond with JSON.

I am working with someone that helps me draft a frontend (HTML5 + angular.js) that renders the information and issues the requests against the given URLs. I'll share more as soon as we have something that is worth sharing.

### CODE REVIEW

**Comment by StephanEwen** [comment]
A simple way to try this out is to execute the class `TestRunner` in the `flink-runtime-web` project. It starts a mini cluster, starts the new web server and runs three jobs (to have some jobs in the history to serve).

**Comment by uce** [comment]
Does this subsume #297?

**Comment by StephanEwen** [comment]
I think it will. I will try and add further code for the new webfrontend in the next days, and then open a new pull request that subsumes this one and #297

**Comment by StephanEwen** [comment]
If no one objects, I would like to merge this, with a switch to choose between the old web frontend, and the new web frontend.

This should get the development of this started better...

**Comment by hsaputra** [comment]
+1 for the merge. This should provide good building blocks to build new features for the web frontend module.

**Comment by chiwanpark** [comment]
Looks good to merge. After merging this PR, we need to modify PR #885.

**Comment by mxm** [comment]
+1 good to merge and this is a prerequisite for getting a first version of the new web UI in.

**Pull request closed without merging**
