### PR TITLE
[FLINK-19360] Fink startup fails when $JAVA_HOME have space

### PR DESCRIPTION
**Pull request by raghavgautam**
The problem is that $JAVA_RUN in flink-daemon.sh is unquoted which leads to splitting by bash. This patch adds the missing quotes.

### CODE REVIEW

**Review by zentol — CHANGES_REQUESTED** [review]
This doesn't touch enough places. There is a similar usage in `flink-console.sh` (that starts processes in the foreground), `config.sh#L485` and `flink`.

Essentially, you have to look for all usages of `$JAVA_RUN`.

**Comment by raghavgautam** [comment]
@zentol I have addressed your review comment. Please take another look.

**Review by zentol — CHANGES_REQUESTED** [review]
What about `flink-dist/src/main/flink-bin/mesos-bin/mesos-jobmanager.sh` and `flink-dist/src/main/flink-bin/bin/flink`?

**Comment by raghavgautam** [comment]
@zontol Please continue review.

**Pull request merged**
