### PR TITLE
[FLINK-18039]

### PR DESCRIPTION
**Pull request by becketqin**
## What is the purpose of the change
Currently the `SourceCoordinator` assumes that `resetToCheckpoint()` method is invoked before the `start()` method is invoked. This is because it is difficult to isolate the behavior of the enumerator before and after the reset. In general, it is safer to re-create a new instance of the `OperatorCoordinator` instead of restart it on the fly.

This patch implements the above re-creation logic for the SourceCoordinator. It has two commits. 

The first commit add a new method `cancelAsyncCalls()` to the `SplitEnumeratorContext`. It helps the enumerator implementations to cleanly close itself. For example, a Kafka enumerator may have a periodic partition discovery async call running, which uses a consumer instance. When closing the enumerator, one needs to first stop all the async calls before closing the consumer instance. `cancelAsyncCalls()` helps users do that. Otherwise each enumerator has to implement their own logic.

The second patch introduces a `RecreateOnResetOperatorCoordinator` class. The purpose of this class is to make sure the checkpoints are always reset to a newly created operator coordinator instance. This is a wrapper class for an `OperatorCoordinator`. It delegates all the methods to the contained `OperatorCoordinator` except `resetToCheckpoint()`. When `resetToCheckpoint()` is called, it first closes the containing `OperatorCoordinator`, create a new instance and reset the newly created `OperatorCoordinator` instance to the given checkpoint.

## Brief change log
75c6ec4c8432735152f1a597aac807faba412ed3 adds a `cancelAsyncCalls()` method to the `SplitEnumeratorContext`.
c85823ceb5fbf877398faf98764874d8fcc6d1e2 introduce a new class of `RecreateOnResetOperatorCoordinator` to create a new operator coordinator instance upon checkpoint reset.

## Verifying this change
New unit tests are added to verify the change:
ExecutionNotifierTest
SourceCoordinatorProviderTest
RecreateOnResetOperatorCoordinatorTest

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by StephanEwen** [comment]
Thanks for the patch! I like the general direction, but am unsure about a few details.

The earlier version of the code had the re-creation separately in the `RecreateOnResetOperatorCoordinator` class. In hind-sight, I think that was better.
  - The `OperatorCoordinatorHolder` has already a somewhat complex task (threading model, checkpoint guarantees, in the future probably execution versioning). I think it would be nice to keep future responsibilities out of this class. The "recreate on reset" sounds like it can fit into a separate class well (like in the earlier version).
  - This also allows us to make this optional. Coordinator implementations that want that behavior can use it by wrapping themselves into the `RecreateOnResetOperatorCoordinator`, others simply go as they are.

Does the "quiesced context" have to throw exceptions? In other quiescing implementations the components turn their methods into no-ops instead, which means no unexpected exceptions during closing/recreation.

The quiesced context uses a way of counting in-progress message sends.
  - Is the purpose here to avoid locks because of dangers of deadlocks?
  - I think the same mechanism we use in "sendEvent()" is also needed in "failJob()". Both are interactions with outside components.
  - Could we avoid having the `Thread.sleep(1)` statement?

The code below is a suggestion for a quiesced context that does not throw an exception and uses wait/notify instead of sleeping.

```java
class QuiesceableContext implements OperatorCoordinator.Context {

    private final OperatorCoordinator.Context context;
    private Object lock;
    private int callsInProgress;
    private boolean quiesced;

    @Override
    public CompletableFuture<Acknowledge> sendEvent(
            OperatorEvent evt,
            int targetSubtask) throws TaskNotRunningException {

        if (enterAndCheckQuiesced()) {
            return CompletableFuture.completedFuture(null);
        }

        try {
            return context.sendEvent(evt, targetSubtask);
        } finally {
            exit();
        }
    }

    private boolean enterAndCheckQuiesced() {
        synchronized (lock) {
            if (quiesced) {
                return true;
            }
            callsInProgress++;
            return false;
    }

    private booleanexit() {
        synchronized (lock) {
            callsInProgress--;
            if (callsInProgress == 0) {
                lock.notifyAll();
            }
        }
    }

    private void quiesce() {
        synchronized (lock) {
            quiesced = true;
            while (callsInProgress > 0) {
                lock.wait();
            }
        }
    }
}
```

**Comment by becketqin** [comment]
@StephanEwen Thanks for the comment. Please see the reply below:

#### `RecreateOnResetOperatorCoordinator` v.s. having the logic in `OperatorCoordinatorHolder`.
I actually moved back and forth a little bit on this. My initial motivation of having a separate class was exactly as you mentioned - the users can choose to recreate on reset or not. The downside is that users has one more thing to think about. Given that the global failure itself should be rare and performance is not the key consideration in that case. I was thinking that maybe we can just always recreate the coordinator. Therefore I moved the logic to `OperatorCoordinatorHolder`. But I don't have a strong opinion on this and would be happy to have a separate `RecreateOnResetOperatorCoordinator` class.

#### Regarding exception in `QuieseableContext`.
In general, I think the API should communicate back the accurate result of an invocation to the caller. That means if an event was not successfully sent, we should avoid swallowing the exception and pretend it has been successfully sent. For example, the quiesced coordinator may have some followup external interaction with external system after successfully sending an event to a task. Not throwing exception in this case might cause problem. Ideally we should have a `QuiescedException` thrown in this case so the users know that this coordinator should no longer perform any action that may cause side-effects, not necessarily to Flink but maybe some other systems.

#### In terms of the lock-free style coordination.
What we are trying to guard against is the following race condition. 
1. The user thread in closing coordinator checks the quiesced flag and found it is not set, so it proceeds. Right before it actually sends an event, the user thread is context switched out.
2. The quiescing thread sets the quiesced flag to the context and resets the valve. At this point the valve is reset and open to serve the event sending from the new coordinator.
3. The user thread in closing coordinator comes back and send the event. Because the valve is open, that event will get in and sent to the task.

So the in-progress thread counter here is to make sure after `quiesce()` is returned, no user thread is in any of the context method invocation. The assumption here is that the event sending logic will finish super fast, i.e. putting the event into a queue in this case. So the quiescing thread can avoid the expensive context switch, which is going to happen when using locks. From the quiescing thread's perspective, it basically does the following in order:
1. block any further invocation on the context.
2. wait for the ongoing invocations on the context to exit (this is very fast) in a spin lock manner.
3. clean up the context to serve the new coordinator.

We can actually just remove the entire `Thread.sleep(1)` part and make it a tight while loop. I put the sleep there for kind of a silly reason - in case there is a single CPU core available in the entire system, the spin-lock manner will waste one OS scheduler slot. I actually usually just use a tight while-loop and the code will jump out that loop super quickly (e.g. a few iterations) without expensive context switch.

In the past we see this lock-free trick has 100x performance compared with the wait/notify synchronization. But that being said, I guess this trick does not gain us much here as we only have one thread sending events, and the quiesce happens rarely. So a wait/notify synchronization would probably be much more readable.

#### Why not synchronize on `failJob()`
My first thought was if the `failJob()` call went through right before the quiescence, that `failJob()` instruction will be sitting in the scheduler queue and the scheduler will still fail the job later again. So guarding against it only reduce the probability of failing the job twice, but does not completely preventing that from happening.

But I agree it is confusing and is better to also put the same synchronization logic as we did for `sendEvent()`.

**Comment by StephanEwen** [comment]
This looks good to me, +1 to merge

**Comment by zhijiangW** [comment]
@becketqin FYI: this PR has conflicts now to be resolved.

**Comment by becketqin** [comment]
Merged to master. 
24201cc1b6c46c689abbff8635a01cec7b088983
e01cab2f713802f6fb92f7472a258c07f2c18af7

Cherry-picked to release-1.11
05db48562c215417f4faa038689cdc18a4582479
0326daf6e97b02dcb18e479ce88a50bc4b644295

**Pull request closed without merging**
