### PR TITLE
[FLINK-14395] Refactor ES 7 connectors to make them keep consistency with es 6 connectors

### PR DESCRIPTION
**Pull request by yanghua**
## What is the purpose of the change

*This pull request refactors ES 7 connectors to make them keep consistency with es 6 connectors*

## Brief change log

  - *Moved table-specific code and test from sql connector to general connector*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by yanghua** [comment]
cc @aljoscha

**Comment by aljoscha** [comment]
While checking this I saw that the ES7 connector pom is slightly different from the ES6 pom: we don't have the `log4j-to-slf4j` dependency on ES7 and we have a superfluous `version` tag on the `maven-surefire-plugin`.

Did you remove the `log4j-to-slf4j` dependency on purpose for ES7? And we should probably remove the `plugin` tag.

**Comment by yanghua** [comment]
@aljoscha Yes, I removed `log4j-to-slf4j` from es7 connector. We do not need to depend on it. OK, I will remove it from the `plugin`.

**Comment by aljoscha** [comment]
But there was a valid reasons for that dependency, see here: https://github.com/apache/flink/blob/e2c4213a8f0664285658f25f2169487eb952909e/flink-connectors/flink-connector-elasticsearch6/pom.xml#L74. I don't know what the situation is for the ES7 connector.

**Comment by yanghua** [comment]
@aljoscha I see this information before. But here we introduced es7 relevant dependencies. We have to delete this dependency, otherwise, it will cause an error when running `ElasticsearchSinkITCase#testElasticsearchSink`. The error message is as follows:

```
java.lang.RuntimeException: An error occurred in ElasticsearchSink.
	at org.apache.flink.streaming.connectors.elasticsearch.ElasticsearchSinkBase.checkErrorAndRethrow(ElasticsearchSinkBase.java:381)
	at org.apache.flink.streaming.connectors.elasticsearch.ElasticsearchSinkBase.checkAsyncErrorsAndRequests(ElasticsearchSinkBase.java:386)
	at org.apache.flink.streaming.connectors.elasticsearch.ElasticsearchSinkBase.invoke(ElasticsearchSinkBase.java:307)
	at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:56)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitRecord(OneInputStreamTask.java:173)
	at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.processElement(StreamTaskNetworkInput.java:151)
	at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.emitNext(StreamTaskNetworkInput.java:128)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:69)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:280)
	at org.apache.flink.streaming.runtime.tasks.mailbox.execution.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:151)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:422)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:696)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:521)
	at java.lang.Thread.run(Thread.java:748)
Caused by: ElasticsearchException[Elasticsearch exception [type=class_cast_exception, reason=org.apache.logging.slf4j.SLF4JLoggerContext cannot be cast to org.apache.logging.log4j.core.LoggerContext]]
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:491)
	at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:402)
	at org.elasticsearch.action.bulk.BulkItemResponse.fromXContent(BulkItemResponse.java:139)
	at org.elasticsearch.action.bulk.BulkResponse.fromXContent(BulkResponse.java:199)
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1727)
	at org.elasticsearch.client.RestHighLevelClient.lambda$performRequestAsyncAndParseEntity$10(RestHighLevelClient.java:1520)
	at org.elasticsearch.client.RestHighLevelClient$1.onSuccess(RestHighLevelClient.java:1598)
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onSuccess(RestClient.java:556)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:300)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:294)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	... 1 more
```

**Comment by aljoscha** [comment]
Please see https://github.com/apache/flink/blob/abbd6b02d743486f3c0c1336139dd6b3edd20840/flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch6/ElasticsearchSinkITCase.java#L36 and https://github.com/apache/flink/blob/e2c4213a8f0664285658f25f2169487eb952909e/flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch7/ElasticsearchSinkITCase.java#L36

**Comment by yanghua** [comment]
Oh, I know, I did not see this comment before. When I saw the exception, I removed this dependency, the test passed. So I thought, we may not need it.

Now, it seems we still need it.

**Comment by yanghua** [comment]
@aljoscha WDYT about the new changes?

**Comment by yanghua** [comment]
Travis failed because of no output error.

**Comment by yanghua** [comment]
@flinkbot run travis

**Comment by yanghua** [comment]
@aljoscha Any opinion?

**Comment by aljoscha** [comment]
Yes, I merged this now. :ok_hand:

**Pull request closed without merging**
