### PR TITLE
[FLINK-9172][table][sql-client] - Support external catalogs in SQL-Client

### PR DESCRIPTION
**Pull request by EronWright**
## What is the purpose of the change

_Based on #7392.  Please see commits prefixed with FLINK-9172._

Adds support for catalogs to the SQL Client environment file, using descriptors.  For example, here's a sample catalog of type `taxi-data` being registered into `sql-client-defaults.yaml`:
```
catalogs:
  - name: nyc
    type: taxi-data
    rides-file: /Users/david/stuff/flink-training/trainingData/nycTaxiRides.gz
    fares-file: /Users/david/stuff/flink-training/trainingData/nycTaxiFares.gz
```

## Brief change log
[FLINK-9172] [table] [sql-client] - Support external catalogs in SQL-Client
- add `CatalogEntry` to configuration types
- enhance `Environment` to include `catalogs` in overall configuration
- enhance `ExecutionContext` to register the configured catalogs
- cleanup test-table-factories.yaml (references to non-existent classes)
- update test dependencies of sql-client to include flink-table's test classes (for `TestExternalCatalogFactory`)

## Verifying this change

This change added tests and can be verified as follows:

- enhanced unit test `DependencyTest` to test discovery of catalog factories
- enhanced unit test `EnvironmentTest` to test merging of catalog configuration
- enhanced unit test `EnvironmentTest` to test the detection of duplicate catalogs/tables/functions
- enhanced unit test `ExecutionContextTest` to test external catalogs

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? **yes**
  - If yes, how is the feature documented? not documented (see FLINK-11245)

### CODE REVIEW

**Comment by rmetzger** [comment]
@twalthr @walterddr want's the status of this PR?

**Comment by twalthr** [comment]
This is a valuable contribution and definitely a feature that we want to have. My only concern here is that this PR exposes a catalog interface at another end which will be deprecated very soon as part of FLINK-11275. I would suggest to wait until FLINK-11476 has been merged.

**Comment by twalthr** [comment]
@EronWright it seems that the unified catalog API might be delayed and it makes sense to allow this feature sooner. I will review this pull request today.

**Comment by bowenli86** [comment]
Thanks for your valuable contribution, @EronWright !  I left some comments in the JIRA ticket. Can you please rebase and adapt this PR? I can help review it as soon as you submit again. Thanks!

**Pull request closed without merging**
