### PR TITLE
[FLINK-1391] Register common Avro types at Kryo

### PR DESCRIPTION
**Pull request by rmetzger**

### CODE REVIEW

**Comment by StephanEwen** [comment]
I like the idea. Can we make the registration conditional on whether the enclosing type is an Avro Type?

**Comment by rmetzger** [comment]
Yep.

**Comment by rmetzger** [comment]
Ah no. Its not a good idea ;)
We don't see that the user is using an Avro POJO when we use the POJO serializer.
So we have to register the types always.

**Comment by rmetzger** [comment]
Merged to release-0.8 in: http://git-wip-us.apache.org/repos/asf/flink/commit/10f89c73

**Pull request closed without merging**
