### PR TITLE
[FLINK-19170] fix parameter naming error

### PR DESCRIPTION
**Pull request by ThunderSuuuuu**
## What is the purpose of the change

fix parameter naming error

## Brief change log

fix parameter naming error

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: ( no)
  - The runtime per-record code paths (performance sensitive): ( no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: ( no )
  - The S3 file system connector: ( no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by XComp — APPROVED** [review]
Thanks ThunderSuuuuuu for looking into that. FYI: There's no need to create FLINK Jira issues for typo fixes. Instead, write `[hotfix][<component>]` as a prefix to your commit message.

**Comment by ThunderSuuuuu** [comment]
> Thanks ThunderSuuuuuu for looking into that. FYI: There's no need to create FLINK Jira issues for typo fixes. Instead, write `[hotfix][<component>]` as a prefix to your commit message.

Thanks for your reply. Should I renaming this PR's title?

**Comment by XComp** [comment]
> > Thanks ThunderSuuuuuu for looking into that. FYI: There's no need to create FLINK Jira issues for typo fixes. Instead, write `[hotfix][<component>]` as a prefix to your commit message.
> 
> Thanks for your reply. Should I renaming this PR's title?

Hi @ThunderSuuuuu , you don't have to change it now since FLINK-19170 is already created. In the end, the commit message is the thing that matters. And I realized that it does not match the [commit guidelines](https://flink.apache.org/contributing/contribute-documentation.html#submit-your-contribution). The commit message should be prefixed with the Jira issue in the following way: `[FLINK-XXXXX] ...` Feel free to change that.

**Comment by rmetzger** [comment]
Thanks a lot for reviewing this @XComp! Merging ... (and closing the JIRA & changing the commit msg)

**Pull request merged**
