### PR TITLE
[FLINK-5717][streaming] Fix NPE on SessionWindows with ContinuousProc…

### PR DESCRIPTION
**Pull request by wanglijie95**
…essingTimeTrigger

## What is the purpose of the change
Fix NPE on SessionWindows with `ContinuousProcessingTimeTrigger`, as described in FLINK-5717.

## Brief change log
Fix the NPE error when SessionWindows with `ContinuousProcessingTimeTrigger` is used.

## Verifying this change

Add `testSessionWindowsWithContinuousProcessingTimeTrigger` in `WindowOperatorTest`

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): **no**
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: **no**
  - The serializers: **no**
  - The runtime per-record code paths (performance sensitive): **no**
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: **no**
  - The S3 file system connector: **no**

## Documentation

  - Does this pull request introduce a new feature? **no**
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by aljoscha** [comment]
Thanks for the fix! I think, however, that `WindowOperatorTest` is not the right place to put the test, it should be added in `ContinuousProcessingTimeTriggerTest`. I know that the fix for `ContinuousEventTimeTrigger` also made this mistake but we should now fix it. For this you would first need to add the `Test`, you can do this based on `ContinuousEventTimeTriggerTest` and then add a new test for this fix there. What do you think?

**Comment by wanglijie95** [comment]
> Thanks for the fix! I think, however, that `WindowOperatorTest` is not the right place to put the test, it should be added in `ContinuousProcessingTimeTriggerTest`. I know that the fix for `ContinuousEventTimeTrigger` also made this mistake but we should now fix it. For this you would first need to add the `Test`, you can do this based on `ContinuousEventTimeTriggerTest` and then add a new test for this fix there. What do you think?

Thanks for review!  You are right, `ContinuousProcessingTimeTriggerTest` is more suitable. I will change it later.
As for the mistake maded by the fix for `ContinuousEventTimeTrigger`, I think it should be fixed in a new PR.

**Comment by aljoscha** [comment]
Feel free to fix `ContinuousEventTimeTrigger` and ping me in the PR. 👌

**Comment by wanglijie95** [comment]
Hi @aljoscha , when I checked the implementation of `ContinuousEventTimeTrigger` and `ContinuousProcessingTimeTrigger`, I was confused in two methods :  `OnElement` and `clear`.

First of all, I think that `ContinuousEventTimeTrigger` and `ContinuousProcessingTimeTrigger` should also fire at the end of window. I saw that `ContinuousEventTimeTrigge` has registered a timer with `window.maxTimestamp()` in `OnElement` : https://github.com/apache/flink/blob/6227fffbe67c9ce4c5591ed1e940f6c34ee137bb/flink-streaming-java/src/main/java/org/apache/flink/streaming/api/windowing/triggers/ContinuousEventTimeTrigger.java#L59
But I didn't find that in `ContinuousProcessingTimeTrigger.`.

Secondly, I think that `ContinuousEventTimeTrigger` should delete the timer with `window.maxTimestamp()` in `clear`, but it didn't. 

Are the above bugs? Or some other considerations, I am a little confused.

**Comment by aljoscha** [comment]
Yes, I think you're right on both questions. The `maxTimestamp` trigger was introduced in https://issues.apache.org/jira/browse/FLINK-5149, but not for the processing-time trigger.

In general, I think the continuous triggers are a bit weird and not many people use them, that's why they managed to keep these bugs for so long. 😅

**Comment by wanglijie95** [comment]
OK, I will  fix them by the way.

**Comment by aljoscha** [comment]
I'm closing this as "Abandoned", since there is no more activity. Please re-open if you want to continue working on this.

**Pull request closed without merging**
