### PR TITLE
[FLINK-27315][docs] Fix the demo of MemoryStateBackendMigration

### PR DESCRIPTION
**Pull request by EchoLee5**
## What is the purpose of the change

JobManagerStateBackend changed to JobManagerCheckpointStorage

## Brief change log

JobManagerStateBackend changed to JobManagerCheckpointStorage

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by EchoLee5** [comment]
cc @Myasuka I resubmitted the pr, please review it, thank you.

**Review by Myasuka — APPROVED** [review]
LGTM. 
Please change the git message to `[FLINK-27315][docs] Fix the demo of MemoryStateBackendMigration` with force push.

**Comment by EchoLee5** [comment]
@Myasuka Thank you for merging my fixes, but why is there still no change on the flink official website?

**Comment by Myasuka** [comment]
@EchoLee5 The official website is not updated continously, please check it tomorrow.

**Comment by EchoLee5** [comment]
> @EchoLee5 The official website is not updated continously, please check it tomorrow.

Thanks, I get it.

**Pull request merged**
