### PR TITLE
[FLINK-15130] Drop 'RequiredParameters' and 'Options'

### PR DESCRIPTION
**Pull request by snuyanzin**
## What is the purpose of the change

The PR drops deprecated classes
`flink-java/src/main/java/org/apache/flink/api/java/utils/Option.java`
`flink-java/src/main/java/org/apache/flink/api/java/utils/OptionType.java`
`flink-java/src/main/java/org/apache/flink/api/java/utils/RequiredParameters.java`
`flink-java/src/main/java/org/apache/flink/api/java/utils/RequiredParametersException.java`
`flink-java/src/test/java/org/apache/flink/api/java/utils/OptionsTest.java`
`flink-java/src/test/java/org/apache/flink/api/java/utils/RequiredParametersTest.java`

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: ( no)
  - The runtime per-record code paths (performance sensitive): ( no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by snuyanzin** [comment]
@flinkbot run azure

**Review by RocMarshal — APPROVED** [review]
Nice~. @snuyanzin 
LGTM +1. （non-binding.）

**Comment by snuyanzin** [comment]
Thanks for the feedback, rebased

**Review by XComp — APPROVED** [review]
Thanks for this change @snuyanzin and @RocMarshal for reviewing this PR. I'm going to go ahead and merge the change.

**Pull request merged**
