### PR TITLE
[FLINK-3097] [table] Add support for custom functions in Table API

### PR DESCRIPTION
**Pull request by twalthr**
As described in FLINK-3097, this PR implements the possibility of adding custom row functions for the Table API.

In the tests you can find some examples how custom functions can look like:
```
table.select("TRIM(f0)")
table.select("SYSTEM_TIME()")
table.select("SUBSTRING(SUBSTRING(f0, 2, 5), 0, 1)")
table.select("SUBSTRING(f0, 1), SUBSTRING(f0, 2, 5)")
```

The Scala Table API is not supported yet, since I'm still waiting for #1237.

### CODE REVIEW

**Comment by aljoscha** [comment]
This looks good. :+1: Can you also integrate the support for Scala, i.e. extract it from #1237 

My only concern is that it introduces yet another instance where TypeInformation is shipped to the cluster. I think we should tackle the problem at some point. Maybe generate the code on the client and ship the code as a string. Then use Janino to just compile it to a final class.

**Comment by twalthr** [comment]
@fhueske I will rebase and merge this into the `tableOnCalcite` branch today, ok?

**Comment by fhueske** [comment]
Yes, sounds good!

**Comment by aljoscha** [comment]
@twalthr Is this in the calcite branch now? Can this PR then be closed?

**Comment by twalthr** [comment]
I'm currently preparing it for the `tableOnCalcite` branch. I will close this PR.

**Pull request closed without merging**
