### PR TITLE
[hotfix][docs] CEP docs review to remove weasel words, fix passive voice, typos an…

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
I was reading through the CEP and made a quick sweep of tidying up docs for improved readability. I think it needs a bit more work, but it's a long document, so will happen over time.

### CODE REVIEW

**Comment by alpinegizmo** [comment]
+1

**Comment by StephanEwen** [comment]
Thanks, merging this...

**Comment by StephanEwen** [comment]
Would be great to also have this in the 1.3 docs, but cherry-picking the committ does not work...

**Comment by ChrisChinchilla** [comment]
@StephanEwen I noticed that just as I submitted it, will look next week :)

**Pull request closed without merging**
