### PR TITLE
fixup! [FLINK-33060][state] Fix the javadoc of ListState interfaces about not allowing null value

### PR DESCRIPTION
**Pull request by Zakelly**
## What is the purpose of the change

Fixing up the https://github.com/apache/flink/pull/23441 since the spotless check is broken.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by Zakelly** [comment]
@flinkbot run azure

**Comment by masteryhx** [comment]
@flinkbot run azure

**Comment by Zakelly** [comment]
Validated via my local compile.

**Comment by Zakelly** [comment]
The compile ci passed https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=54430&view=logs&j=b59e5554-36c7-5512-ab1a-b80b74075fce&t=849d419c-1b8f-52b7-e455-d4bc36ec43ad

**Pull request closed without merging**
