### PR TITLE
[FLINK-15537][table-planner-blink] Type of keys should be `BinaryRow`…

### PR DESCRIPTION
**Pull request by cshuo**
## What is the purpose of the change

Fix bug of distinct aggregate codegen when key type of distinct `MapView` is `BaseRow`.

## Brief change log
  - This PR mainly fix some problems of `DistinctAggCodeGen`.
  - BTW, refine name problems of `ListAgg` aggregate function in tests..

## Verifying this change

This change added tests and can be verified as follows:

  - Added integration tests in `AggregateITCase`.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by wuchong** [comment]
Tests are failed, please have a look.

**Comment by cshuo** [comment]
@flinkbot run travis

**Comment by cshuo** [comment]
> Tests are failed, please have a look.

Hi, @wuchong , failed case fixed.

**Comment by wuchong** [comment]
The failed case `TaskExecutorITCase.teardown` is not related to this PR, it seems is tracked by FLINK-15247. 
Merging...

**Pull request merged**
