### PR TITLE
[FLINK-20006] Fix the unstable FileSinkITCase

### PR DESCRIPTION
**Pull request by gaoyunhaii**
## What is the purpose of the change

This PR fixes the unstable `FileSinkITCase`. The original implementation has some logical error, e.g., it does not keep the state for the source function, and for streaming mode it does not ensure some data are committed in the first attempt. This cause the sink either does not test the actual scenario or cause repeat commits.

## Brief change log

- 1de2eca68fe489aadb55ed3084d18f4cd7ea723f fixes the unstable ITCase.

## Verifying this change

*(Please pick either of the following options)*

This change is a test fix.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): **no**
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: **no**
  - The serializers: **no**
  - The runtime per-record code paths (performance sensitive):**no**
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: **no**
  - The S3 file system connector: **no**

## Documentation

  - Does this pull request introduce a new feature? **no**
  - If yes, how is the feature documented? **not applicable**

### CODE REVIEW

**Comment by aljoscha** [comment]
If BATCH and STREAMING are so different it might make sense to have to separate ITCases?

**Comment by gaoyunhaii** [comment]
Yes, currently the logic diverge a lot. However, there are still some utility methods get used by both cases, like the `BucketAssigner`, method to check result, etc.. Do you think it would made sense if we have an `AbstractFileSinkITCase` that contains the common parts and have two different IT Cases for blocking mode and streaming mode?

**Comment by aljoscha** [comment]
I think that would be the way to go, yes.

**Comment by rmetzger** [comment]
Our builds are very unstable because of this failure. If you are not able to fix it within the next hour, I would recommend you to push a hotfix disabling the unstable test.

**Review by aljoscha — APPROVED** [review]
This looks good, I'm merging!

**Comment by aljoscha** [comment]
Merged!

**Comment by rmetzger** [comment]
Thanks a lot!

**Pull request closed without merging**
