### PR TITLE
[FLINK-20245][hive][docs] Document how to create a Hive catalog from DDL

### PR DESCRIPTION
**Pull request by lirui-apache**
## What is the purpose of the change

Document how to create `HiveCatalog` with DDL and add table of supported options.

## Brief change log

  - Document how to create `HiveCatalog` with DDL and add table of supported options.

## Verifying this change

NA

## Does this pull request potentially affect one of the following parts:

NA

## Documentation

NA

### CODE REVIEW

**Comment by lirui-apache** [comment]
Screen Shot 2020-11-26 at 2 37 31 PM
Attached is a screenshot of the updated page.

**Comment by lirui-apache** [comment]
@dawidwys @JingsongLi Could you take a look at the PR? It only updates the eng page, I'll sync the changes to zh page once we think it's good enough.

**Review by dawidwys — APPROVED** [review]
LGTM, @lirui-apache Will you update the zh page in this PR or will you create a follow-up issue?

@JingsongLi Do you want to have a look as well?

**Comment by lirui-apache** [comment]
I'll update the zh page in this PR.

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request closed without merging**
