### PR TITLE
[FLINK-7697][connectors] Add metrics for ElasticSearchSink

### PR DESCRIPTION
**Pull request by piygoyal**
## What is the purpose of the change

This pull request add metrics to the Elasticsearch connectors, to make it easier to operate and monitor in a production environment.

## Brief change log

The following metrics have been added:
 - ItemRequest success count (counter)
 - ItemRequest failure count (counter) grouped by error type.
 - BulkRequest failure count (counter) grouped by error type.
 - BulkRequest latency (gauge)

<b> Note: </b>Gauge doesn't feel like the right metric type for measuring bulkRequest latency, as it will only capture the last requestLatency before the gauge gets polled. Flink metric system currently lacks a timer type that can be used to capture event latencies in a richer way. I opened FLINK-12680 to track addition of a timer type.
Another metric-related thing we noticed during internal reviews is that the SimpleCounter is not thread safe, which makes it somewhat risky/expensive to use it in a multithreaded context. I opened FLINK-12681 to track making SimpleCounter thread-safe.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage. Also manually verified the metrics by hooking with our internal time-series system.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by piygoyal** [comment]
@flinkbot attention @tzulitai

**Comment by tankilo** [comment]
Will there be any new progess? Currently in 1.9.0, es connector is still a black box. I've tried to turn on logging of `org.elasticsearch.client.RequestLogger`. Hope there will be metrics such as `time cost of bulk request`.

**Comment by EsmeraldaYS** [comment]
影响了哪个版本

**Comment by einarjohnson** [comment]
are there any metrics available for the elasticsearch sink?

**Pull request closed without merging**
