### PR TITLE
[FLINK-1655] Renamed StreamInvokable to StreamOperator and all its subclasses and tests in a similar fashion.

### PR DESCRIPTION
**Pull request by akshaydixi**
Changes made are:

* StreamInvokable -> StreamOperator
* ChainableInvokable -> ChainableStreamOperator
* SinkInvokable -> SinkStreamOperator
* SourceInvokable -> SourceStreamOperator

* CoFlatMapInvokable -> CoFlatMapStreamOperator
* CoGroupedReduceInvokable -> CoGroupedReduceStreamOperator 
* CoInvokable -> CoStreamOperator
* CoMapInvokable -> CoMapStreamOperator
* CoReduceInvokable -> CoReduceStreamOperator
* CoWindowInvokable -> CoWindowStreamOperator

* GroupedWindowBufferInvokable -> GroupedWindowBufferStreamOperator
* WindowBufferInvokable -> WindowBufferStreamOperator

* CounterInvokable -> CounterStreamOperator
* FilterInvokable -> FilterStreamOperator
* FlatMapInvokable -> FlatMapStreamOperator
* GroupedFoldInvokable -> GroupedFoldStreamOperator
* GroupedReduceInvokable -> GroupedReduceStreamOperator
* MapInvokable -> MapStreamOperator
* ProjectInvokable -> ProjectStreamOperator 
* StreamFoldInvokable -> FoldStreamOperator
* StreamReduceInvokable -> ReduceStreamOperator

### CODE REVIEW

**Comment by mbalassi** [comment]
Nice, thanks for also updating the minor details. `GroupedWindowBufferStreamOperator` is a bit long of a name for my taste, but other than LGTM. :)

**Comment by gyfora** [comment]
I personally don't like the sound of all these class names too much. It seems to be too redundant and too long in most cases. I know the ...Invokables weren't so much better either but at least they were short.

Let us think about this for a little before making these changes.

**Comment by gyfora** [comment]
Hey
Sorry I made a major refactoring today, and I also did the renaming with much shorter names.

**Comment by akshaydixi** [comment]
Ok. So should I delete this branch then?

**Comment by gyfora** [comment]
yes please

**Pull request closed without merging**
