### PR TITLE
[FLINK-22987][ci] Fix scala suffix check

### PR DESCRIPTION
**Pull request by zentol**
Ports most parts of the scala checker to java and fixes existing issues along the way. We now parse the module name from the dependency-plugin line, and no longer use tee.

### CODE REVIEW

**Comment by zentol** [comment]
The test failure is due to a missing scala suffix: FLINK-23001

**Review by rmetzger — APPROVED** [review]
+1 to merge. The checker seems to work (given the CI failure ;) ) and I didn't spot anything in the code.

What's the strategy regarding the merge? I guess we need to fix FLINK-23001 first, or shall we ignore this module?

Secondly, I was wondering how we can avoid cases like this in the future (where the check silently stops working?).
Ideas:
- assert a reasonable number of modules we expect at least (50+) (this way, we notice if the parsing breaks again, but of course that's not really a comprehensive check)
- We have some kind of canary we expect to fail (i.e. fail if we don't find violations in the e2e tests) (this is unstable, because the e2e tests could just stop depending on scala at some point)

**Comment by zentol** [comment]
> What's the strategy regarding the merge?

I think ignoring the module now and re-enabling it later should be fine.

> Secondly, I was wondering how we can avoid cases like this in the future (where the check silently stops working?).

Well...it's a bit tricky, and I'm struggling to think of a truly reliable way to ensure that.
A sanity check that more than 0 module was parsed would be a good first step; it would've caught the parsing issue. This is actually the only way I see to actually catch parsing issues.
However, the tee issue is a bitch; if something breaks on the bash side then there's nothing we ca do.

**Comment by rmetzger** [comment]
> I think ignoring the module now and re-enabling it later should be fine.

Okay, but then let's make FLINK-23001 a blocker for 1.14 ?

> A sanity check that more than 0 module was parsed would be a good first step;

Allright, let's do it.

Thanks for your answers.

**Comment by zentol** [comment]
I made a small change to the bash script such that it exits the script by default with a non-zero exit code, and only exits with 0 if the check ran successfully. This way, if anything breaks on the bash side such that the checker isn't called successfully we should see a failure on CI.

**Pull request merged**
