### PR TITLE
[FLINK-2694] [test-stability] Hardens the JobManagerProcessReapingTest.testReapProcessOnFailure test case

### PR DESCRIPTION
**Pull request by tillrohrmann**
The `JobManagerProcessReapingTest.testReapProcessOnFailure` predetermines the port for the `JobManager` which is started by using `NetUtils.getAvailablePort`. This can cause problems if in the meantime another process has opened a socket binding to this port. In order to harden this test case, the `JobManager` is now allowed to pick itself a free port. The selected port is extracted from the logging output of the `JobManager`.

### CODE REVIEW

**Comment by tillrohrmann** [comment]
Failing test case is `org.apache.flink.yarn.YARNSessionFIFOITCase.testJavaAPI` and, thus, unrelated.

**Comment by uce** [comment]
This is more robust, because Akka has retry loop when trying to bind to the randomly picked port, right? The change looks good and works fine. +1

Optional: I would add two comments to test: one that the log4j log level needs to be >= INFO and that the log message needs to be "Starting JobManager...". If one of these two things changes, the test will not work anymore and it might be helpful for debugging if it every happens.

**Comment by tillrohrmann** [comment]
I think that the Akka will just randomly pick a free port. Thus, there is no need for retrying.

I'll add the comments to the test. That's a good point :-)

Merging this then.

**Comment by uce** [comment]
Ah yeah they directly bind the socket :D

**Pull request closed without merging**
