### PR TITLE
[FLINK-5324] [yarn] JVM Opitons will work for both YarnApplicationMas…

### PR DESCRIPTION
**Pull request by hzyuemeng1**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [ ] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [ ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

…terRunner and YarnTaskManager with yarn mode

### CODE REVIEW

**Comment by hzyuemeng1** [comment]
@ChengXiangLi ,can u review this PR?

**Comment by hzyuemeng1** [comment]
@wuchong ，can u check this issue?

**Comment by StephanEwen** [comment]
I would like to pick up this pull request.
How about we interpret the `env.java.opts` as "common options" that are passes to both JobManager and TaskManager. Then we additionally define options specific for JobManager / TaskManager / AppMaster:

  - `env.java.opts.taskmanager`
  - `env.java.opts.jobmanager`
  - `env.java.opts.appmaster`

The TaskManager should then use the  `env.java.opts.taskmanager` + `env.java.opts` options.

Can you also use the new options abstraction for this?
https://github.com/apache/flink/blob/master/flink-core/src/main/java/org/apache/flink/configuration/ConfigOptions.java

**Comment by tillrohrmann** [comment]
Added by other PR.

**Pull request closed without merging**
