### PR TITLE
[FLINK-13705][docs] Broken links in Hive documentation

### PR DESCRIPTION
**Pull request by sjwiesman**
## What is the purpose of the change

Fix the broken links in the hive documentation

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by sjwiesman** [comment]
cc @bowenli86

**Comment by bowenli86** [comment]
LGTM, thanks!

**Comment by tillrohrmann** [comment]
Please pay attention that the commit message has the right format when merging PRs @bowenli86. It should be `[FLINK-13705][docs] ....`

**Comment by bowenli86** [comment]
woops....haven't needed to fix such things for a long time and missed that. thanks @tillrohrmann for pointing that out

@sjwiesman please add jira ticket number to the commit message in the future. 

thanks all

**Pull request closed without merging**
