### PR TITLE
[FLINK-1376] [runtime] Add proper shared slot release in case of a fatal TaskManager failure

### PR DESCRIPTION
**Pull request by tillrohrmann**
This PR introduces SharedSlots as being a special Slot type and as such being released properly in case an Instance has been marked dead. This fixes the problem that a dead instance, which has not been shutdown properly, causes a job not being removed properly from the system, because it is not aware of the SubSlots.

Adds test cases where only the task manager is killed by a Kill message (hard shutdown)

Requires thorough review because it touches some delicate scheduling/slot logic.

### CODE REVIEW

**Comment by StephanEwen** [comment]
I am looking into this right now and testing it locally. Seems to work so far. Will try to give a vote by tomorrow...

**Comment by rmetzger** [comment]
Hi,
maybe thats a helpful datapoint for you:
I have a Flink cluster started where all TaskManagers died (misconfiguration). The JobManager needs more than 200 seconds to realize that (on the TaskManagers overview, you see timeouts < 200). When submitting a job, you'll get the following exception:

```
org.apache.flink.client.program.ProgramInvocationException: The program execution failed: java.lang.Exception: Failed to deploy the task CHAIN DataSource (Generator: class io.airlift.tpch.NationGenerator) -> Map (Map at writeAsFormattedText(DataSet.java:1132)) (1/1) - execution #0 to slot SubSlot 0 (f8d11026ec5a11f0b273184c74ec4f29 (0) - ALLOCATED/ALIVE): java.lang.NullPointerException
	at org.apache.flink.runtime.taskmanager.TaskManager.org$apache$flink$runtime$taskmanager$TaskManager$$submitTask(TaskManager.scala:346)
	at org.apache.flink.runtime.taskmanager.TaskManager$$anonfun$receiveWithLogMessages$1.applyOrElse(TaskManager.scala:248)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at org.apache.flink.yarn.YarnTaskManager$$anonfun$receiveYarnMessages$1.applyOrElse(YarnTaskManager.scala:32)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:162)
	at org.apache.flink.runtime.ActorLogMessages$$anon$1.apply(ActorLogMessages.scala:41)
	at org.apache.flink.runtime.ActorLogMessages$$anon$1.apply(ActorLogMessages.scala:27)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118)
	at org.apache.flink.runtime.ActorLogMessages$$anon$1.applyOrElse(ActorLogMessages.scala:27)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at org.apache.flink.runtime.taskmanager.TaskManager.aroundReceive(TaskManager.scala:78)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

	at org.apache.flink.runtime.executiongraph.Execution$2.onComplete(Execution.java:311)
	at akka.dispatch.OnComplete.internal(Future.scala:247)
	at akka.dispatch.OnComplete.internal(Future.scala:244)
	at akka.dispatch.japi$CallbackBridge.apply(Future.scala:174)
	at akka.dispatch.japi$CallbackBridge.apply(Future.scala:171)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

	at org.apache.flink.client.program.Client.run(Client.java:345)
	at org.apache.flink.client.program.Client.run(Client.java:304)
	at org.apache.flink.client.program.Client.run(Client.java:298)
	at org.apache.flink.client.program.ContextEnvironment.execute(ContextEnvironment.java:55)
	at flink.generators.programs.TPCHGenerator.main(TPCHGenerator.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:437)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:353)
	at org.apache.flink.client.program.Client.run(Client.java:250)
	at org.apache.flink.client.CliFrontend.executeProgram(CliFrontend.java:389)
	at org.apache.flink.client.CliFrontend.run(CliFrontend.java:358)
	at org.apache.flink.client.CliFrontend.parseParameters(CliFrontend.java:1068)
	at org.apache.flink.client.CliFrontend.main(CliFrontend.java:1092)
```

I think a NPE is never desired. Does this pull request cover this case?

**Comment by tillrohrmann** [comment]
No I don't think that this has something to do with the shared slot
release. It should be handled in a separate ticket.

**Comment by rmetzger** [comment]
Okay, I'll file a JIRA

**Comment by StephanEwen** [comment]
I think this is a good fix, overall. There is one issue I would really like to fix, and that is the serializability of the `Instance` class. This class is not meant to be serialized and moved around, which can be reflected by the fact that it holds an Actor Ref, and the necessity to make a lot of the fields transient.

I assume that the instance needs to be serialized as part of the ExechutionGraph archiving, where the ExecutionGraph is sent via an actor message to the archiver.

I would like to solve that differently. The execution graph is "cleaned" before archiving (see #344 ) to reduce memory footprint. At this point, I would replace the `Instance` in the Executions with the `Instance Connection Info`, which holds all info necessary. Then we won't have to send instances through actor messages, which would be the cleaner solution.

**Comment by tillrohrmann** [comment]
+1 for removing unnecessary ExecutionGraph information before archiving.

**Comment by StephanEwen** [comment]
This one has been manually merged (but I made a typo in the "This closes #xxx" message ;-) )

@tillrohrmann Can you close the PR manually?

**Comment by tillrohrmann** [comment]
Of course. Thanks for merging.

**Pull request closed without merging**
