### PR TITLE
[FLINK-36390][core] Remove deprecated open(Configuration) method in RichFunction

### PR DESCRIPTION
**Pull request by reswqa**

### CODE REVIEW

**Review by codenohup — COMMENTED** [review]
LGTM overall.
@reswqa I have a small question: Why are the _OpenContext_ interfaces empty, while the _DefaultOpenContext_ and _WithConfigurationOpenContext_ are quite simple? Could these simple _OpenContext_ subclass be combined into one?

**Comment by reswqa** [comment]
Thanks for the reveiw.

>I have a small question: Why are the OpenContext interfaces empty, while the DefaultOpenContext and WithConfigurationOpenContext are quite simple? Could these simple OpenContext subclass be combined into one?

This is by design: We want to use different implementations to distinguish different cases (passing different combinations of arguments to `Open`) to avoid incompatible changes to interfaces/classes.

**Review by codenohup — APPROVED** [review]
Okey, i understand, thank you for your reply. 
Looking forward more interesting feature based on it.  👍

**Comment by reswqa** [comment]
Thanks for the reveiw!

**Pull request merged**
