### PR TITLE
[FLINK-8126] [build] Fix and update checkstyle

### PR DESCRIPTION
**Pull request by greghogan**
## What is the purpose of the change

Update to the latest checkstyle version and fix the errors not previously detected.

## Brief change log

- update checkstyle to version 8.4 from version 6.19
- in `checkstyle.xml` move `SuppressionCommentFilter` under `TreeWalker` and remove `FileContentsHolder` (see checkstyle/checkstyle pr4714)
- correct latent checkstyle errors

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by zentol** [comment]
+1

**Comment by zentol** [comment]
merging,

**Comment by StephanEwen** [comment]
I am not seeing some problem in IntelliJ with the checkstyle plugin (seems to not be able to parse the checkstyle config).

Anyone else seeing this issue? I am on an older IntelliJ version, so might be that (reluctant to update because switching Scala versions works less well in newer IntelliJ versions).

**Comment by zentol** [comment]
Which checkstyle version is configured in IntelliJ @StephanEwen ? Could be that we have to upgrade it there as well. IIRC we set recommend setting it to 6.X in the IDE setup guide because of some parsing errors in 8.X, which now may be resolved.

**Comment by zentol** [comment]
Setting the version in IntelliJ to 8.4 seems to work.

Settings -> Other Settings -> Checkstyle -> Checkstyle version drop-down menu

**Pull request closed without merging**
