### PR TITLE
[FLINK-10997][formats] Bundle kafka-scheme-registry-client

### PR DESCRIPTION
**Pull request by zentol**
## What is the purpose of the change

With this PR `flink-avro-confluent-registry` bundles `kafka-scheme-registry-client` as intended.
The relocation pattern for jackson was additionally modified as it currently only applied to parts of jackson.

## Verifying this change

Manually verified.

### CODE REVIEW

**Comment by StephanEwen** [comment]
+1 to the idea, but we should do it differently.

If you want the Avro dependency not in the shaded jar, simply set it to provided.

This also automatically drops all transitive dependencies, so no need to maintain the exclusion list. The exclusion list is cumbersome and fragile, which seems to be also the reason why travis failed: one missing exclusion resulting in a collision on the service entries between different jackson version (one from Avro, other from Schema Registry).

**Comment by zentol** [comment]
My understanding was that users would define a dependency on `flink-avro-confluent-registry` and pull avro into the user-jar. If avro is set to provided it would have to be explicitly included by the user instead.

Maybe @dawidwys can chime in here.

**Comment by dawidwys** [comment]
My understanding/plan when I first worked on it was as @zentol described that the only dependency user should specify is `flink-avro-confluent-registry`, but I see also @StephanEwen point that keeping list of exclusions up-to-date could be fragile. I don't know which one is better. If we go with the `provided` scope for `flink-avro` we should probably update the docs that it should be additionally included.

**Comment by dawidwys** [comment]
How about if we include just what we need for the confluent schema-registry in the uber-jar:

	<configuration>
		<artifactSet>
			<includes>
				<include>io.confluent:*</include>
				<include>com.fasterxml.jackson.core:*</include>
				<include>org.apache.zookeeper:zookeeper</include>
				<include>com.101tec:zkclient</include>
			</includes>
		</artifactSet>
		<relocations combine.children="append">
			<relocation>
				<pattern>com.fasterxml.jackson</pattern>
				<shadedPattern>org.apache.flink.formats.avro.registry.confluent.shaded.com.fasterxml.jackson</shadedPattern>
			</relocation>
			<relocation>
				<pattern>org.apache.zookeeper</pattern>
				<shadedPattern>org.apache.flink.formats.avro.registry.confluent.shaded.org.apache.zookeeper</shadedPattern>
			</relocation>
			<relocation>
				<pattern>org.apache.jute</pattern>
				<shadedPattern>org.apache.flink.formats.avro.registry.confluent.shaded.org.apache.jute</shadedPattern>
			</relocation>
			<relocation>
				<pattern>org.I0Itec.zkclient</pattern>
				<shadedPattern>org.apache.flink.formats.avro.registry.confluent.shaded.org.101tec</shadedPattern>
			</relocation>
		</relocations>
	</configuration>

**Comment by StephanEwen** [comment]
Keeping a "compile" dependency is good for user dependency management.
Let's got with the list of includes then, because they also define what needs to go into the relocations.

Maybe shorten the relocation prefix a little.

**Comment by zentol** [comment]
Ive changed the configuration to use inclusions. Additionally covered FLINK-10987 for this module.

**Comment by StephanEwen** [comment]
Looks good, +1

**Comment by dawidwys** [comment]
@zentol shall we merge this?

**Comment by jasoncsinn** [comment]
Hi @zentol ,

Sorry to revive an old PR but I was wondering why this artifact shades io.confluent:kafka-schema-registry-client but does not relocate the dependency (as it does with the others).

I have a project which requires a newer version of the schema registry client (5.3.0), but including this artifact in my project causes the calling code to randomly select a client version (the client dependency cannot be explicitly excluded from this artifact as it is shaded, but coincides with the classpath of the newer version). 

If there isn't any particular reason for this, would it be possible to relocate this dependency as well?

**Pull request merged**
