### PR TITLE
[FLINK-21998][hive] Copy more code from hive and move them to a dedicated package

### PR DESCRIPTION
**Pull request by lirui-apache**
## What is the purpose of the change

Copy more code from hive and move them to a dedicated package

## Brief change log

  - Move the copied hive classes to package `org.apache.flink.table.planner.delegation.hive.copy`
  - Copy more hive code

## Verifying this change

Existing tests

## Does this pull request potentially affect one of the following parts:

NA

## Documentation

NA

### CODE REVIEW

**Comment by twalthr** [comment]
@lirui-apache could you give the community more context about this change in the JIRA issue? I think most people in the Flink community would immediately reject copying more code from Hive to Flink unless there is a good reason for it.

**Comment by lirui-apache** [comment]
Hi @twalthr The copied code is used to support hive dialect for different hive versions. And also allows us to extend hive syntax to support more features in the future. It was discussed in the `Support Multiple Hive Versions` section of [FLIP-152](https://cwiki.apache.org/confluence/display/FLINK/FLIP-152%3A+Hive+Query+Syntax+Compatibility).

**Comment by twalthr** [comment]
@lirui-apache please always fill out the JIRA description. Even if it means copying the explanation from the FLIP. I got pinged  to check this PR because it looks suspicious for people that are not familar with the topic.

**Comment by lirui-apache** [comment]
@twalthr Sure, will do.

**Review by wuchong — APPROVED** [review]
LGTM.

**Pull request merged**
