### PR TITLE
[hotfix] Expose current watermark to Triggers

### PR DESCRIPTION
**Pull request by aljoscha**

### CODE REVIEW

**Comment by StephanEwen** [comment]
What is the implication of this change?

**Comment by aljoscha** [comment]
I want to add this because it enables triggers that can essentially discard late elements. It does not change any previous behavior but just enables some nifty custom trigger tricks.

I don't want to add big changes to the Triggers themselves this short before the release, that's why I'm only suggesting to add this small change.

**Comment by StephanEwen** [comment]
Okay, makes sense.

+1 from my side

**Comment by rmetzger** [comment]
Merging & including this one into the RC1 as well.

**Pull request closed without merging**
