### PR TITLE
[FLINK-8600] Don't use flaky truncate() test in BucketingSink

### PR DESCRIPTION
**Pull request by aljoscha**
R: @kl0u

### CODE REVIEW

**Comment by aljoscha** [comment]
(I realised this doesn't add any tests or anything but `BucketingSink` is currently problematic with S3 anyways.)

**Comment by aljoscha** [comment]
@kl0u Thanks for the review!

I changed the code to check `useTruncate` before calling. Regarding `fsConfig`, the settings in there are for `FileSystem` while the settings that are configured using a setter are for the behaviour of the `BucketingSink` itself. Does that make sense?

**Comment by kl0u** [comment]
@aljoscha Yes it does. I did not get it in the first place but I think that this clarifies things!

**Comment by aljoscha** [comment]
@kl0u I changed my mind on this. 😅 Now the only change is to allow circumventing the `truncate()` checks via the setting. The checks themselves are still in place. I'm also not changing the call-sites to try and keep the change as localised as possible. WDYT?

**Comment by kl0u** [comment]
+1 to merge.

**Pull request closed without merging**
