### PR TITLE
[FLINK-27432][runtime] Replace Time with Duration in TaskSlotTable

### PR DESCRIPTION
**Pull request by Jiabao-Sun**
## What is the purpose of the change
[FLINK-27432][runtime] Replace Time with Duration in TaskSlotTable

## Brief change log
[FLINK-27432][runtime] Replace Time with Duration in TaskSlotTable

## Verifying this change
This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by Jiabao-Sun** [comment]
Hi @XComp, @zentol, could you help review this when you have time?
Thanks.

**Comment by Jiabao-Sun** [comment]
Hi @leonardBang, do you have time to help review it?
Many thanks for that.

**Review by XComp — APPROVED** [review]
Looks reasonable. :+1:  I will accept that one because there is already a dedicated Jira issue created. But for the future, it's best to do this in one go instead of refactoring the code for individual classes. It's easier to review if I could just grep through the code and see if there are still `Time` imports left

**Comment by XComp** [comment]
Additionally, it's considered a good habit to not ping people right away within days. Mentions are noticed and if a contributor finds time to review it, he/she will get to it. Our mailbox would become quite noisy if we get a mention for every PR all the time. ;-)

But thanks for your good work. :-)

**Pull request merged**
