### PR TITLE
[FLINK-32158] Unify the getMultiInputOperatorDefaultMeta and getOneInputOperatorDefaultMeta methods into the same getInputOperatorDefaultMeta method

### PR DESCRIPTION
**Pull request by jiaoqingbo**
## What is the purpose of the change

Unify the getMultiInputOperatorDefaultMeta and getOneInputOperatorDefaultMeta methods into the same getInputOperatorDefaultMeta method. Because 1 is a special case of Multi, there is no need to repeat the definition.Same applies to getStateTtlForMultiInputOperator and getStateTtlForOneInputOperator methods

## Brief change log
Unify the getMultiInputOperatorDefaultMeta and getOneInputOperatorDefaultMeta methods into the same getInputOperatorDefaultMeta method
Unify the getStateTtlForMultiInputOperator and getStateTtlForOneInputOperator methods into the same getStateTtlForInputOperator method

## Verifying this change

This change is already covered by existing tests 

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by jiaoqingbo** [comment]
@LadyForest  @godfreyhe could you help take a look when you have time? Thanks.

**Comment by jiaoqingbo** [comment]
@flinkbot run azure

**Comment by jiaoqingbo** [comment]
@flinkbot run azure

**Comment by LadyForest** [comment]
Hi @jiaoqingbo, Thanks for the contribution!
IMO, `getOneInputOperatorDefaultMeta` is heavily used since almost all stateful operators (except for Join) are OneInputStreamOperator, so it might be tedious to invoke `getInputOperatorDefaultMeta().get(0)`. You might want to rebase the master to see the change FLINK-32053.

**Pull request closed without merging**
