### PR TITLE
[FLINK-23057] add variable expansion for FLINK_ENV_JAVA_OPTS in flink-console.sh

### PR DESCRIPTION
**Pull request by Zor-X-L**
## What is the purpose of the change

Add variable expansion for FLINK_ENV_JAVA_OPTS in flink-console.sh similar to flink-daemon.sh, to make env.java.opts like "-Xlog:gc*:file=${FLINK_LOG_PREFIX}.gc.log" work properly in native kubernetes application mode.

## Brief change log

- add `FLINK_ENV_JAVA_OPTS=$(eval echo ${FLINK_ENV_JAVA_OPTS})` before starting the JVM.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by Zor-X-L** [comment]
@flinkbot run azure

**Comment by Zor-X-L** [comment]
@flinkbot run azure

**Comment by Zor-X-L** [comment]
> 
> ## CI report:
> 
>     * [78ef7fa](https://github.com/apache/flink/commit/78ef7fad6e570accede686df317f69cf03499a65) Azure: [FAILURE](https://dev.azure.com/apache-flink/98463496-1af2-4620-8eab-a2ecc1a2e6fe/_build/results?buildId=19433)
> 
> 
> Bot commands
> The @flinkbot bot supports the following commands:

**Comment by Zor-X-L** [comment]
[78ef7fa](https://github.com/apache/flink/commit/78ef7fad6e570accede686df317f69cf03499a65) Azure: [FAILURE](https://dev.azure.com/apache-flink/98463496-1af2-4620-8eab-a2ecc1a2e6fe/_build/results?buildId=19433)

**Comment by Zor-X-L** [comment]
@flinkbot run azure

**Comment by rmetzger** [comment]
The CI failure is a known test instability. Instead of merging with master, I recommend rebasing and force-pushing your branch. This will create a clean git history.

**Review by rmetzger — APPROVED** [review]
Change looks good to me.

@wangyang0918 do you want to take a final look?

**Comment by wangyang0918** [comment]
Thanks @Zor-X-L for preparing the PR and @rmetzger for the review.
nit: It will be great if you could use the `git rebase` instead of `git merge`.

+1 from my side.

**Review by wangyang0918 — APPROVED** [review]

**Comment by Zor-X-L** [comment]
@rmetzger @wangyang0918 Thanks for the advice!

**Comment by rmetzger** [comment]
Thanks a lot for updating the PR so quickly, and thanks @wangyang0918 for taking a look.

I'm merging this PR now.

**Pull request merged**
