### PR TITLE
[FLINK-2844][jobmanager] remove old web interface

### PR DESCRIPTION
**Pull request by mxm**
The new web interface supports all features of the old web interface once #1164 and #1233 have been merged. It's time to remove the old one.

### CODE REVIEW

**Comment by mxm** [comment]
The WebFrontendITCase still needs to be adapted.

**Comment by StephanEwen** [comment]
This should also remove all Jetty dependencies (runtime pom and root pom)

**Comment by sachingoel0101** [comment]
`YarnSessionFIFOITCase` checks the old job manager web interface. We should change that too.

**Comment by mxm** [comment]
An update from my side. I have

- adapted the `WebFrontendITCase`
- adapted the `YarnSessionFIFOITCase`
- removed the Jetty dependencies

Based on  #1222 I changed the serving of the static files to work with the fat jar and a temporary directory. This is the default way now and ensures that everything works standalone and on YARN.

**Comment by rmetzger** [comment]
I suspect we can close https://github.com/apache/flink/pull/1222 then?

**Comment by mxm** [comment]
Yes, #1222 is obsolete now.

**Comment by mxm** [comment]
Build passes (`ScalaShellLocalStartupITCase` has some hickups).

**Comment by StephanEwen** [comment]
Nice, will merge this...

**Pull request closed without merging**
