### PR TITLE
[FLINK-10412] toString field in AbstractID should be transient to avoid been serialized

### PR DESCRIPTION
**Pull request by yanghua**
## What is the purpose of the change

*This pull request mark toString field in AbstractID as transient to avoid been serialized *

## Brief change log

  - *Mark toString field in AbstractID as transient to avoid been serialized*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by StephanEwen** [comment]
I would like to not do this change.

I fear that there are some corner cases in which Java serialization is still used and where this can break setups. The benefit of this change seems not big enough to risk that.

**Comment by yanghua** [comment]
hi @StephanEwen How can it "break setup" without serializing it? It's just an internal variable that improves the performance of the `toString()` method. Other than that, it hasn't been used elsewhere. And when `toString()` is called again, it will be generated again, and `toString()` sets the behavior of this variable to be idempotent.

**Comment by StephanEwen** [comment]
If existing savepoints have an AbstractID serialized in it, will the deserialization fail if that field changes?

**Comment by yanghua** [comment]
Hi @StephanEwen , I verified the scene you said and did not lead to failure. Proceed as follows:

1. Serialize the current version of AbstractID to a local file;
2. Deserialize from the local file and convert the deserialized Object type to a new AbstractID (mark the toString field as transient);
3. Compare the fields and hashcode to be consistent;

Since this test comes from two separate methods and the AbstractID is modified in the middle, it seems impossible to write a directly running test case.

**Comment by yanghua** [comment]
@tillrohrmann and @zentol What's your opinion?

**Comment by tillrohrmann** [comment]
I took a look at the different sizes of a serialized `AbstractID` with and without the transient keyword:

* old `AbstractID`: 126 bytes
* old `AbstractID` with `toString` being called before serialization: 160 bytes
* transient `AbstractID`: 93 bytes

The issue has been created because ZhuZhu observed scalability issues when deploying very large jobs. I think he has a point given the different object sizes, because the `InputChannelDeploymentDescriptor` consists to a good part of `AbstractIDs`. Given this and that serialization is not a problem, I'm actually in favour of this improvement.

What we could do @yanghua is to serialize the old `AbstractID` and store the serialized data as a file in the testing resource folder. Then we could add a test, that the new AbstractID can be deserialized from this file.

**Comment by yanghua** [comment]
@tillrohrmann I have tried to do it the way you said it, but because the fully qualified names of the two classes are different, an exception is thrown when the type conversion is done.

**Comment by tillrohrmann** [comment]
Why are the fully qualified names different @yanghua? I actually just tried to do the same and it works.

**Comment by tillrohrmann** [comment]
This is the branch: https://github.com/tillrohrmann/flink/commit/5179eac7d19b342e161cb188f78e51458075aaff @yanghua

**Comment by tillrohrmann** [comment]
Since @StephanEwen initially rejected this PR I would still like to hear his opinion before merging this PR.

**Comment by yanghua** [comment]
> If existing savepoints have an AbstractID serialized in it, will the deserialization fail if that field changes?

In order to verify the scenario described by @StephanEwen  in the test, don't we need to define two versions of AbstractID?

**Comment by tillrohrmann** [comment]
I created the resource files with the serialized `AbstractID` before applying your changes. That way we still have serialized data of the old `AbstractID` available.

**Comment by yanghua** [comment]
Oh, @tillrohrmann I understood.

**Comment by yanghua** [comment]
Hi @tillrohrmann and @StephanEwen Any progress about this issue?

**Comment by StephanEwen** [comment]
If we are sure that this does not break serialization that I am good with changing it.

**Comment by yanghua** [comment]
@tillrohrmann Anything else that needs to be changed? Or can we merge it?

**Comment by tillrohrmann** [comment]
As of this [documentation](https://docs.oracle.com/javase/8/docs/platform/serialization/spec/version.html#a6519), making a nontransient field transient is identical as removing a field from a class. What happens is that an earlier version won't find the field data in the serialized stream and will initialize the field with the default value (`null`). In general this is an incompatible change when relying on Java serialization, however in our case if `toString == null`, then we will simply regenerate the `toString` field when calling `toString`. Therefore, I think it is ok to merge this change. 

I will proceed with merging.

**Pull request closed without merging**
