### PR TITLE
[FLINK-6303] Documentation support build in docker on OSX

### PR DESCRIPTION
**Pull request by mtunique**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by patricklucas** [comment]
Thanks for the PR @mtunique! I actually ran into this today and have a fix [in a branch](https://github.com/patricklucas/flink/tree/FLINK-6330_improve_docker_docs) that I will hopefully open a PR for tomorrow.

I had exactly your change, but tweaked it slightly to tolerate being called from sudo.

You could either just wait for me to merge that change, or continue with this PR, but please implement the change as I did in the branch I linked above.

**Comment by mtunique** [comment]
I will follow the branch.

**Comment by patricklucas** [comment]
Here's the PR: #3751

**Comment by mtunique** [comment]
@patricklucas I have changed this PR follow #3751. In order to make the PRs clearly, the PR #3751 should just fix the issue FLINK-6330.

**Comment by greghogan** [comment]
@mtunique please manually close this PR since it is subsumed by #3751.

**Pull request closed without merging**
