### PR TITLE
[FLINK-2102] [ml] Add predict operation for LabeledVector

### PR DESCRIPTION
**Pull request by thvasilo**
Add predict function for labeled data for SVM and MLR.

These functions return for each example in the input DataSet[LabeledVector] a pair (Double, Double) - (truth, prediction)

This output can then be used to evaluate the performance of the Predictors

### CODE REVIEW

**Comment by thvasilo** [comment]
Currently there is a lot of boilerplate, but these should be minimized once the syntactic sugar for map with broadcast vars is merged.

**Comment by sachingoel0101** [comment]
One further possible addition would be to add a class to evaluate accuracy. We could provide statistics such as F1-score, Precision at k,etc. 
Where would that fit in the pipeline mechanism though?

**Comment by thvasilo** [comment]
@sachingoel0101 Yes, that is partially covered by [FLINK-2108](https://issues.apache.org/jira/browse/FLINK-2108), and an evaluation framework (along with cross-validation) is in our immediate plans.

**Comment by tillrohrmann** [comment]
Nice work @thvasilo. The only thing which is missing is the update to the online docs where we say which types are supported for which operation.

**Comment by thvasilo** [comment]
OK I'm on it.

**Comment by thvasilo** [comment]
@tillrohrmann I added a description for SVM and MLR

**Comment by tillrohrmann** [comment]
LGTM. I will merge it as a temporary solution for the manual evaluation.

**Pull request closed without merging**
