### PR TITLE
Using try-resource in JarHelper

### PR DESCRIPTION
**Pull request by darionyaphet**
## What is the purpose of the change

Since Java 7, we can use  try-resource to manage IO Stream which could auto close when it finished. This one is more concise

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by zentol** [comment]
While using try-with-resource is certainly preferable, the unfortunate reality is that the future of the scala-shell module is uncertain. As such I would reject this contribution for the time being, because a any time invested here might be for naught.

**Comment by darionyaphet** [comment]
Do we have any plans in scala-shell module?

**Comment by zentol** [comment]
@darionyaphet The problem is that the scala-shell is currently not compatible with scala 2.12 (FLINK-10911), and it's only a matter of time until support for scala 2.11 is dropped.

**Comment by darionyaphet** [comment]
> @darionyaphet The problem is that the scala-shell is currently not compatible with scala 2.12 ([FLINK-10911](https://issues.apache.org/jira/browse/FLINK-10911)), and it's only a matter of time until support for scala 2.11 is dropped.

OK  depressed and this one I have closed

**Pull request closed without merging**
