### PR TITLE
[FLINK-4259]: Unclosed FSDataOutputStream in FileCache#copy(): Added a …

### PR DESCRIPTION
**Pull request by nssalian**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

Description of Changes:
Add a close statement for closing the FSDataOutputStream.
Requesting review.

- [ ] General
  - The pull request references the related JIRA issue ("[FLINK-4259] Unclosed FSDataOutputStream in FileCache#copy()")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [ ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

…close statement to close the FSDataOutputStream object

### CODE REVIEW

**Comment by mbalassi** [comment]
@nssalian has just reached out to me in person. I will have a look at this.

**Comment by nssalian** [comment]
Thanks @mbalassi

**Comment by mbalassi** [comment]
The code change is very concise and looks right, the one issue that bugs me is that there are no direct tests in place to verify it - and it is not necessarily straight forward to test as it is a resource leak issue.

I tried building the project locally and in fact `PythonPlanBinderTest` that uses the change transitively got stuck, but I could not manage to reproduce the issue when running solely that test from IntelliJ.

I have fired up a travis test myself and the PR is also triggering one, let us whether those go through.

@nssalian do you see a straight forward way to test the behaviour? 

PS: Could you enabled the travis build on your repo, please? (As Flink comes with a travis.yml all you need to do is to go to Travis, login with your github user and hit enable on the repo.)

**Comment by nssalian** [comment]
hi @mbalassim thank you for the review. I have kicked off a build for my flink repo. Let me observe what happens.
With regards to a test, I was thinking something on the lines  of FileCacheDeleteValidationTest.java with creating and checking whether the output stream is closed.

**Comment by zentol** [comment]
I think it would be fine to merge it without a test; we merged plenty of PR's like this without requiring a test.

The PythonPlanBinderTest failing is odd, but i would guess that it is unrelated to this change. Nevertheless, does it get stuck every time you execute it? And, of course, does it no longer fail without this commit?

**Comment by nssalian** [comment]
Hi @zentol , thank you.I ran the build once locally and it went through. Just kicked off another for sanity.

**Comment by nssalian** [comment]
Hi @mbalassi and @zentol, I ran the builds twice and both instances the PythonBinderTest passed.
The 2nd build ran with a failure on 2 with:
MVN exited with EXIT CODE: 1.
java.io.FileNotFoundException: build-target/lib/flink-dist-*.jar (No such file or directory)

which, if I am not wrong, isn't related here.
Please let me know if you need me to add anything additional.

**Comment by mbalassi** [comment]
Thanks @nssalian, merging then.

**Comment by nssalian** [comment]
Thanks @mbalassi  and @zentol for the review.

**Pull request closed without merging**
