### PR TITLE
[hotfix][flink-walkthrough] Fix typo in name for archetype-resources/pom.xml

### PR DESCRIPTION
**Pull request by sky-walking**
[hotfix][flink-walkthrough] Fix typo in name for archetype-resources/pom.xml

### CODE REVIEW

**Review by MartijnVisser — CHANGES_REQUESTED** [review]
Thank you for your contribution. 

Please update the PR to follow the PR guidelines as can be found on https://flink.apache.org/contributing/reviewing-prs.html and update your commit message to follow the Code Style & Quality Guidelines, which can be found at https://flink.apache.org/contributing/code-style-and-quality-preamble.html.

**Comment by sky-walking** [comment]
Thank you very much！

**Comment by MartijnVisser** [comment]
@sky-walking No problem. The commit message and PR is still not exactly matching the guidelines. See https://flink.apache.org/contributing/code-style-and-quality-pull-requests.html. It should be something like `[hotfix][docs] Fix typo in name for archetype-resources/pom.xml`

**Comment by sky-walking** [comment]
Thank you for your review. I have finished correcting it.

**Review by MartijnVisser — APPROVED** [review]
Thank you, LGTM. @fapaul can you please merge?

**Review by fapaul — CHANGES_REQUESTED** [review]
Please adjust the commit message it is not a docs change. i.e. `[flink-walkthrough]`

**Review by fapaul — APPROVED** [review]
LGTM

**Pull request merged**
