### PR TITLE
[FLINK-27121][docs-zh]Translate "Configuration#overview" paragraph and the code example in "Application Development > Table API & SQL" to Chinese

### PR DESCRIPTION
**Pull request by leizhou666**
## What is the purpose of the change

https://issues.apache.org/jira/browse/FLINK-27121
Translate "Configuration#overview" paragraph and the code example in "Application Development > Table API & SQL" to Chinese
PR: https://github.com/apache/flink/pull/19387

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by luoyuxia** [comment]
@leizhou666 Thanks for you contribution. LGTM
@MartijnVisser Could you please help merge?

**Comment by mayuehappy** [comment]
LGTM + 1

**Comment by leizhou666** [comment]
> 

thanks very much!!!

**Comment by leizhou666** [comment]
>

**Review by MartijnVisser — APPROVED** [review]
@leizhou666 Thanks a lot for this, LGTM. Please make sure that your commit message follows the code contribution guidelines in the future, see https://flink.apache.org/contributing/contribute-code.html

**Pull request merged**
