### PR TITLE
[FLINK-4247] [table] CsvTableSource.getDataSet() expects Java ExecutionEnvironment

### PR DESCRIPTION
**Pull request by twalthr**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

Adds explicit notice to `getDataSet/getDataStream` methods of `TableSource`.

### CODE REVIEW

**Comment by zentol** [comment]
+1. We could also use the `@Internal` annotations for this.

Out of curiosity, could you explain we can't just restrict access to the methods?

**Comment by twalthr** [comment]
Yes, good idea. We can not restrict it as it is defined in an interface. If we would make it `protected`, we could not call it from the outside.

**Comment by StephanEwen** [comment]
Would be great to reflect the "do not use" with proper visibility. A JavaDoc comment is usually not helping at all.

Also, the dependency on the java API classes in the Scala classes does not seem right. Usually the Scala classes hide the Java API streams and environments.

Both of these things are usually strong indicators that there are some abstraction issues.
Would be good to get that right, while the API is fresh and malleable.

**Comment by twalthr** [comment]
@StephanEwen A user can also call `CsvInputFormat.nextRecord()` because it is public, but this was never a problem. If we want to restrict visibility of `TableSource` interface methods, we have to convert the interfaces to classes and provide 3 class for batch, stream, batch&stream. Also not very nice.

In general, the Scala classes hide the Java API streams and environments within the Table API. But in this case the user wants to implement a custom TableSource and since the Table API is internally using the Java API I think it is ok, if Java API and not Scala API is used for that.

**Comment by fhueske** [comment]
+1 for sticking to Java DataSet / DataStream for the reasons @twalthr gave. The methods should be tagged with the `@Internal` annotation when we add them to the Table API.

I would not rename `TableSource` to `TableInputFormat` because 1) it has no relationship to the `InputFormat` interface and 2) there is already a `TableInputFormat` for HBase tables (name is not very fortunate though...).

**Comment by fhueske** [comment]
Do we agree to stick with the current implementation? If yes, let's close this PR.

**Comment by twalthr** [comment]
I think adding some comments the methods doesn't hurt. I would merge this PR as it is.

**Comment by fhueske** [comment]
Agreed @twalthr. 
IMO, +1 to merge

**Pull request closed without merging**
