### PR TITLE
[FLINK-35501] Use common IO thread pool for RocksDB data transfer

### PR DESCRIPTION
**Pull request by rkhachatryan**
Please ignore the 1st commit - it comes from #24880 

---

```
Currently, each RocksDB state backend creates an executor backed by a
thread pool.

This makes it difficult to control the total number of threads per TM
because it might have at least one task per slot and theoretically, many
state backends per task (because of chaining).

Additionally, using a common thread pool allows to indirectly control
the load on the underlying DFS (e.g. the total number of requests to S3
from a TM).

This change allows to control the total number of data transfers per TM.
```

### CODE REVIEW

**Comment by rkhachatryan** [comment]
@flinkbot run azure

**Comment by rkhachatryan** [comment]
@flinkbot run azure

**Review by StefanRRichter — APPROVED** [review]
LGTM

**Comment by rkhachatryan** [comment]
Thanks for the review!
Merged into master

**Pull request merged**
