### PR TITLE
[FLINK-16115][filesystem] Make aliyun oss filesystem could work with plugin mechanism

### PR DESCRIPTION
**Pull request by wangyang0918**
## What is the purpose of the change

From release-1.9, Flink suggest users to load all filesystem with plugin, including oss. However, it could not work for oss filesystem. The root cause is it does not shade the org.apache.flink.runtime.fs.hdfs and org.apache.flink.runtime.util. So they will always be loaded by system classloader.
What we need to do is shading the two packages `org.apache.flink.runtime.fs.hdfs` and `org.apache.flink.runtime.util`, just like s3 and azure.

## Brief change log

* shading two packages `org.apache.flink.runtime.fs.hdfs` and `org.apache.flink.runtime.util`

## Verifying this change

* Configure the HA storage to oss and manually run a standalone Flink cluster 

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by wangyang0918** [comment]
@AHeise I think you are familiar with plugin and shading. Could you please take a look?

**Comment by wangyang0918** [comment]
@AHeise I think if we put the oss filesystem jar in lib directory, then it could work. Because we use system classloader to load the `OSSFileSystemFactory`. And when it want to load the `HadoopFileSystem` class, the class in the same jar(flink-oss-fs-hadoop-1.x.jar) will be used first.

**Comment by pnowojski** [comment]
I don't know @AHeise .

While we are at this change, why do we need to relocate anything in order to make this work with plugins? Is this, this issue that we are lacking some proper SPI package/module?

**Comment by wangyang0918** [comment]
@pnowojski Thanks for your comment.
If we do not relocate the two packages `org.apache.flink.runtime.fs.hdfs` and `org.apache.flink.runtime.util`, then the `HadoopFileSystem` will be loaded by parent classloader since it is in the `PLUGIN_ALWAYS_PARENT_FIRST_LOADER_PATTERNS`. However, we expect them to be loaded by plugin classloader.

**Comment by AHeise** [comment]
The issue is that `flink-hadoop-fs` is shaded into `flink-dist` (mostly because of MapR, but also for Kerberos).
In flink-dist, ctor of `HadoopFileSystem` has this signature:
`public HadoopFileSystem(org.apache.hadoop.fs.FileSystem hadoopFileSystem)`

In relocated plugins, it is 
```
public class org.apache.flink.runtime.fs.hdfs.HadoopFileSystem extends org.apache.flink.core.fs.FileSystem {
  public org.apache.flink.runtime.fs.hdfs.HadoopFileSystem(org.apache.flink.fs.shaded.hadoop3.org.apache.hadoop.fs.FileSystem);
```

The original [error](https://issues.apache.org/jira/browse/FLINK-16115) shows that the wrong HadoopFileSystem was loaded.

**Comment by wangyang0918** [comment]
@AHeise Thanks for your additional explanation. Your analysis is on point.

@pnowojski Do you have other concerns and could you help with merging?

**Comment by zentol** [comment]
I agree with @AHeise that this FS is likely just broken.
The only way this could've worked is if another filesystem is in /lib that bundles flink-hadoop-fs, without relocating contained classes and relocates hadoop. I don't know whether any filesystem qualifies.

I think the proposed changed makes sense.

AFAIK we cannot add an end-to-end test since Aliyun OSS cannot be setup locally and we don't have any credentials.

**Comment by wangyang0918** [comment]
@zentol Yes, you are right. We can not set up a local oss and we could not add a oss token in the test script.
I have manually run a standalone cluster with oss filesystem enable. And it works fine.

**Comment by AHeise** [comment]
Then LGTM and ready to be merged from my side @zentol .

**Comment by wangyang0918** [comment]
@zentol Could you have another look and help with merging?

**Pull request merged**
