### PR TITLE
[FLINK-5417][DOCUMENTATION]correct the wrong config file name

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
As the config file name is conf/flink-conf.yaml, the usage "conf/flink-config.yaml" in document is wrong and easy to confuse user. We should correct them.

### CODE REVIEW

**Comment by WangTaoTheTonic** [comment]
I use Illustrator‎ to edit svg file, which will add some header infos that cause CI failed. Is there any prefered svg editor?

**Comment by zentol** [comment]
you should be able to open the svg file with any text editor and add the license manually.

**Comment by zentol** [comment]
I will take a look at these changes.

Just a small note: We are not getting notified of pushed changes, a small comment is always good to get attention ;)

**Comment by zentol** [comment]
When viewing the documentation in firefox there is now a lot of whitespace above the diagram. The dimensions have slightly changed as well :/

**Comment by WangTaoTheTonic** [comment]
Hi @zentol , I've updated the svg using Inkscape. 
Is the whitespace you refer to on the topest(the red highlighted part)? I think it's normal as the original one has them to. It would not affect view in documents.
default

**Comment by zentol** [comment]
well that's the thing, i did rebuild the documentation and in the new version the whitespace was shown. The old version didn't have that. I'll try the updated version and will make screenshots if i see it again ;)

**Comment by zentol** [comment]
Nice, the updated version is better :)

**Comment by WangTaoTheTonic** [comment]
I guess it is probably that the illustrator added sth.

**Comment by zentol** [comment]
Could be; it's a bit frightening to see how much the results differ based on which application one uses :/

Anyway, I will add this to my batch of commits to merge. However, the massive diff drove me crazy, so I massaged the svg file a bit and the diff is now a bit smaller (see here: https://github.com/zentol/flink/commit/4c8d2bde83aeb9d066845c26ea937228d077f867). Hope you don't mind that.

**Comment by WangTaoTheTonic** [comment]
Surely not :)

**Pull request closed without merging**
