### PR TITLE
[FLINK-18411][tests] Fix CollectionExecutorTest failed to compiled in release-1.11

### PR DESCRIPTION
**Pull request by wuchong**
## What is the purpose of the change

I think this is caused by "[FLINK-18352] Make DefaultClusterClientServiceLoader/DefaultExecutorServiceLoader thread-safe", commit id: eeeff7a5. 

## Brief change log

- Use `new DefaultExecutorServiceLoader()` instead of `DefaultExecutorServiceLoader.INSTANCE` which has been removed in eeeff7a5.

## Verifying this change

N/A.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by wuchong** [comment]
Could you help to review this @kl0u @aljoscha ?

**Comment by aljoscha** [comment]
LGTM once azure is green! Thanks for fixing it!

**Comment by wuchong** [comment]
Passed in my repo: https://dev.azure.com/imjark/Flink/_build/results?buildId=180&view=results

Will merge this now to save the builds.

**Comment by wuchong** [comment]
Passed in my repo: https://dev.azure.com/imjark/Flink/_build/results?buildId=180&view=results

Will merge this now to save the builds.

**Pull request merged**
