### PR TITLE
[FLINK-15408][table-planner-blink]Interval join supports no equal condition

### PR DESCRIPTION
**Pull request by wangxlong**
## What is the purpose of the change

Interval join supports no equal condition

## Brief change log

Remove restrictions that do not allow equivalent join in StreamExecIntervalJoinRule

## Verifying this change

This change added tests and can be verified as follows:
1. IntervalJoinITCase#testRowTimeInnerJoinWithoutEqualCondition

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: (no )
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by godfreyhe — COMMENTED** [review]
Thanks for the contribution @wangxlong . Sorry for the late review, LGTM overall. It's better we can add a plan test in `IntervalJoinTest` about the change.

**Comment by godfreyhe** [comment]
it's better you can rebase the latest master

**Comment by wangxlong** [comment]
@godfreyhe Thanks for your reviewing. I have add a plan test and rebased the master.

**Comment by godfreyhe** [comment]
+1 to merge

**Pull request merged**
