### PR TITLE
[hotfix][web]Modify the configuration of prettier

### PR DESCRIPTION
**Pull request by zekai-li**
The default value of "endOfLine" for Prettier is LF，This does not apply to Windows developers.

### CODE REVIEW

**Comment by zekai-li** [comment]
@flinkbot run azure

**Comment by zekai-li** [comment]
@is

**Comment by zekai-li** [comment]
@flinkbot run azure

**Comment by zekai-li** [comment]
@rehevkor5

**Comment by zekai-li** [comment]
@flinkbot run azure

**Comment by zekai-li** [comment]
@hadronzoo

**Comment by zekai-li** [comment]
@is Please help review.

**Comment by zentol** [comment]
Already fixed on master.

**Pull request closed without merging**
