### PR TITLE
[FLINK-24983][build] Upgrade surefire to 3.0.5-M5

### PR DESCRIPTION
**Pull request by zentol**
Resolve "Corrupted STDOUT" issues with SUREFIRE-1658.

### CODE REVIEW

**Review by nicoweidner — COMMENTED** [review]
The change looks fine. CI failed - it might be because of the bumped surefire version, I can't really tell the root cause though

**Comment by zentol** [comment]
Oh it's definitely related. I'm wondering why I never saw that on CI with Java 17...

but more to the point, it's because the `integration-tests` surefire execution is setup to run anything that isn't a unit test, and it apparently throws up when dealing with certain scala constructs...

**Comment by nicoweidner** [comment]
> Oh it's definitely related. I'm wondering why I never saw that on CI with Java 17...
> 
> but more to the point, it's because the `integration-tests` surefire execution is setup to run anything that isn't a unit test, and it apparently throws up when dealing with certain scala constructs...

Yeah, I suspected that some behavior changed with the new surefire version - but I couldn't figure out where this malformed class name that it complains about comes from...

**Comment by nicoweidner** [comment]
Or maybe test class detection changed between surefire versions? Now that I think about it, it reads like it simply picks up this class now which is at top-level in its parent file:
https://github.com/apache/flink/blob/master/flink-scala/src/test/scala/org/apache/flink/api/scala/typeutils/InstantiationUtilTest.scala#L74-L94
Maybe it would also be solved by making this a subclass of the test class?

**Comment by zentol** [comment]
There are probably way more instances of this, and if there's some anonymous class then Scala will generate similar files.

**Review by nicoweidner — APPROVED** [review]

**Comment by zentol** [comment]
huh, this only happens on Java 8, no wonder I didn't run into it :/

**Pull request merged**
