### PR TITLE
[FLINK-19647][Connectors/HBase]Support the limit push down for the hb…

### PR DESCRIPTION
**Pull request by shouweikun**
…ase connector"

## What is the purpose of the change

Support limit push down for HBase connector

## Brief change log

  -  implements `SupportLimitPushdown` in HBase1 and HBase2
  

## Verifying this change

This change added tests and can be verified as follows:

-
## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes /**no**)
  - The serializers: (yes /*no* / don't know)
  - The runtime per-record code paths (performance sensitive): (**yes** / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by shouweikun** [comment]
@flinkbot run azure

**Comment by shouweikun** [comment]
@flinkbot run azure

**Comment by shouweikun** [comment]
@flinkbot run azure

**Comment by shouweikun** [comment]
@flinkbot run azure

**Comment by shouweikun** [comment]
@lirui-apache Would u mind taking a review?

**Comment by ferenc-csaky** [comment]
@shouweikun Do you have the capacity to update this PR and reopen it against the `https://github.com/apache/flink-connector-hbase` repo?

**Comment by snuyanzin** [comment]
@shouweikun  thanks for your contribution

The Flink HBase connector resides in it's own repository nowadays, if this code change is still relevant, please open the PR in https://github.com/snuyanzin/flink-connector-hbase

**Pull request closed without merging**
