### PR TITLE
[FLINK-8648] [kinesis] Allow for customization of emitRecordAndUpdateState in Kinesis connector.

### PR DESCRIPTION
**Pull request by tweise**
## What is the purpose of the change

Allow customization of record emission in the Kinesis consumer. In this case we will use it to implement custom watermark logic but it could also be used for any other logic that inspects the record with contextual information about the shard.

## Brief change log

- Trivial change to remove final from the declaration to enable override.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

I didn't add a test, but perhaps we can add a NOOP example with override in the test package just to have the compile path covered?

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by tweise** [comment]
R: @tzulitai

**Comment by tzulitai** [comment]
Just curious, before I proceed to merge this:
could you briefly describe what your custom override would consist of?
I'm asking because we may be able to find a cleaner solution (or not 😅). The method was made final, because that part is critical for exactly-once guarantees.

It would also be interesting to get to know what you are trying to achieve here.

**Comment by tweise** [comment]
@tzulitai see https://gist.github.com/tweise/7fad5d5df0abf54670a52d0d02d61179 for details.

As indicated in the email thread, emit override will track watermark state and delegate the record to the base implementation.

**Comment by tweise** [comment]
@tzulitai any update?

**Comment by tzulitai** [comment]
I see, so it is basically a quicker workaround for per-shard watermarks for the Kinesis Consumer.

Since we discussed that we'll likely have a reworked consumer in 1.6 that hopefully includes per-shard watermarks, I'll agree to merge this temporary workaround change now for 1.5.

**Pull request closed without merging**
