### PR TITLE
From stream to h base

### PR DESCRIPTION
**Pull request by HilmiYildirim**
[Flink-2055] I changed DataStream.writeToFile to DataStream.write and changed visibility from private to public. Further, I implemented an example how to use DataStream.write to write the Stream into HBase.

The hbase-site.xml is annoying in the resource folder of flink-hbase. It changes the configuration of the hbase java api, but my hbase configuration differs from that in the hbase-site.xml. Maybe it is better to delete this file.

### CODE REVIEW

**Comment by StephanEwen** [comment]
I like the idea of this, but we have to be aware that this breaks the existing streaming API by
renaming the `writeToFile()` method.

Since `writeToFile` is misleading anyways, I am in favor of this change.

**Comment by fhueske** [comment]
How about adding a `writeToFile()` method that accepts a `FileInputFormat`?
This would only break code where the method is used with a non-FileInputFormat.

**Comment by StephanEwen** [comment]
That is a very nice idea!

**Comment by HilmiYildirim** [comment]
Good idea. I am working on it.

**Comment by HilmiYildirim** [comment]
I had some merging conflicts. Therefore, I did a new Pull Request https://github.com/apache/flink/pull/706

**Pull request closed without merging**
