### PR TITLE
flink-6033 Support UNNEST query in the stream SQL API

### PR DESCRIPTION
**Pull request by suez1224**
…y is supported, and WITH ORDINALITY is not yet supported.

Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [ ] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [ ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by twalthr** [comment]
Thanks for the PR @suez1224. I think we need to rework this PR a little bit, before we can merge it. I saw that you had problems using basic type arrays such as `Integer[]`. I think we should cover this in a separate issue, because adding a type involves changes in multiple files and needs good tests. 

I would propose to introduce `LogicalUnnestRule` that convert the logical plan into a logical `FlinkLogicalCorrelate`. This approach would not require a `DataStreamCorrelateUnnestRule` and would work for both batch and streaming.

What do you think?

**Comment by suez1224** [comment]
Thanks a lot for reviewing the PR, @twalthr. It turns out the change in basic type arrays is not needed. 

Regarding introducing the LogicalUnnestRule, I think it's a good idea. I'll look into that

**Comment by suez1224** [comment]
@twalthr , can you take a look when you have time? I have added the LogicalUnnestRule and unitest for batch as well.  Thanks a lot.

**Comment by fhueske** [comment]
Thanks for the update @suez1224!
Looks good to me. Will do some minor refactoring and merge this PR.

Best, Fabian

**Pull request closed without merging**
