### PR TITLE
[FLINK-17789][API/Core] DelegatingConfiguration should remove prefix …

### PR DESCRIPTION
**Pull request by pyscala**
## What is the purpose of the change

1.DelegatingConfiguration should remove prefix instead of add prefix in toMap
2.Make `toMap` consistent with `addAllToProperties` in class `DelegatingConfiguration`

## Brief change log

1.DelegatingConfiguration should remove prefix instead of add prefix in toMap
2.Make `toMap` consistent with `addAllToProperties` in class `DelegatingConfiguration`

## Verifying this change

This change added tests and can be verified as follows:
unit test `testDelegationConfigurationToMapConsistentWithAddAllToProperties` in class `DelegatingConfigurationTest`

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? ( no)

### CODE REVIEW

**Comment by pyscala** [comment]
Hi @JingsongLi ,  Looking forward to your review, thanks.

**Comment by pyscala** [comment]
Hi @zentol  , Thanks for your commits. Can you review this PR for us ?

**Comment by JingsongLi** [comment]
Thanks @pyscala for your contribution. Changes looks good to me overall. But I want to hear from @zentol

**Comment by pyscala** [comment]
> Thanks @pyscala for your contribution. Changes looks good to me overall. But I want to hear from @zentol

Thanks @JingsongLi  for your reply.

**Comment by JingsongLi** [comment]
@flinkbot run azure

**Comment by JingsongLi** [comment]
@pyscala Can you rebase for triggering testing?

**Comment by pyscala** [comment]
> @pyscala Can you rebase for triggering testing?

@JingsongLi I will do it later

**Comment by pyscala** [comment]
Hi @JingsongLi 
Current error seems to have nothing to do with our changes.
Looking forward to your reply , thanks

**Comment by zentol** [comment]
@pyscala You haven't rebase on the latest master, and are about a week behind.

**Comment by pyscala** [comment]
Hi @JingsongLi @zentol Thanks for detailed reply. is this OK ? Or I close this PR and create a new one ?

**Comment by JingsongLi** [comment]
@pyscala You can squash your commits, and cherry-pick to latest master, then replace your `FLINK-17789` branch. And force push to your `FLINK-17789` branch.

**Comment by pyscala** [comment]
Hi @JingsongLi @zentol  Done, Everything looks good

**Pull request merged**
