### PR TITLE
[FLINK-2584] Check for unshaded classes in fat jar and shade curator

### PR DESCRIPTION
**Pull request by rmetzger**
This PR is an addition for FLINK-2584, removing the transitive guava dependencies from the fat jar introduced by Apache Curator.

Its also adding a check ensuring that shaded classes (guava, asm) are not showing up in the fat jar.

### CODE REVIEW

**Comment by uce** [comment]
Nice work :) This needs to go into the milestone branch as well.

What do you mean with "We can easily integrate curator's netty into the jar file."?

**Comment by rmetzger** [comment]
I saw that curator has a netty dependency.
If we are running into netty conflicts because of curator's netty dependency, it's very easy to just shade curator's netty into curator.

My change is creating a new apache curator jar for us, where guava is located in `org.apache.curator.shaded.com.google`. We can do exactly the same for netty if needed.

**Comment by StephanEwen** [comment]
I'll merge this now into `master` and `0.10.0-milestone1`.

In the long run, we can hopefully convince curator to offer a shaded version in addition to the unshaded version.

**Comment by rmetzger** [comment]
Make sure it does not break with @tillrohrmann's recent merge ;)

**Pull request closed without merging**
