### PR TITLE
[FLINK-2139] [streaming] Streaming outputformat tests

### PR DESCRIPTION
**Pull request by mbalassi**

### CODE REVIEW

**Comment by mbalassi** [comment]
The socket test failed once in ten runs on travis, some messages were lost while writing and reading to the socket.  do not think that we can avoid that completely. I can feed in less input data or remove the test.

**Comment by aljoscha** [comment]
I would be against adding a test for which we already know that it sometimes fails.

**Comment by aljoscha** [comment]
I think we need to name the "tests" ITCase. In my understanding the tests that bring up a test cluster and execute a program are ITCases since they take longer to run than simple tests. I might be wrong, though. Anyone else have an opinion?

**Comment by mbalassi** [comment]
Both are good points. 

As for the socket test I can do one of the following:
   * Do not test it
   * Test it with smaller data
   * Mock the socket with some collection

I am not not really happy with any of these options to be honest, but maybe I am just missing something.

As for the ITCases, you are right, I have to admit that I was looking at the [AvroOutputFormatTest](https://github.com/apache/flink/blob/master/flink-staging/flink-avro/src/test/java/org/apache/flink/api/avro/AvroOutputFormatTest.java) and named my tests accordingly. So you would suggest renaming that too then?

**Comment by aljoscha** [comment]
Probably then, yes :smile: (for the rename)

**Comment by mbalassi** [comment]
Ok, I am renaming that and adding an ignore for the socket test and a JIRA to fix it.

**Pull request closed without merging**
