### PR TITLE
[FLINK-11162][rest] Provide a rest API to list all logical operators

### PR DESCRIPTION
**Pull request by jinglining**
# FLINK-11162

## What is the purpose of the change

This pull request is a followup of [#11162](https://issues.apache.org/jira/browse/FLINK-11162) and provide a rest API to list all logical operators.

## Brief change log

Provide a rest API to list all logical operators

## Verifying this change

This change added tests in JobOperatorsHandlerTest
## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? docs

### CODE REVIEW

**Comment by jinglining** [comment]
@tillrohrmann can you review

**Comment by yanghua** [comment]
@jinglining Thanks for your contribution. You should probably be more patient, we need to agree on the implementation, and then come back to review code.

**Comment by jinglining** [comment]
@yanghua code is one way to show the method

**Comment by jinglining** [comment]
@zentol can you review it.

**Comment by zentol** [comment]
As out-lined in the JIRA I would like to have this but the required changes for a proper implementation (that covers metrics, backpressure, the web UI, etc....) are so significant that I don't believe anyone has time for this right now.

**Pull request closed without merging**
