### PR TITLE
[FLINK-36001][state] Hotfix for OperatorIDPairTest missing header

### PR DESCRIPTION
**Pull request by gaborgsomogyi**
Hotfix for https://github.com/apache/flink/pull/25267

### CODE REVIEW

**Comment by gaborgsomogyi** [comment]
cc @gyfora

**Review by fapaul — APPROVED** [review]
Please verify that the change fixes the problem and/or wait for a green CI :)

**Comment by gaborgsomogyi** [comment]
Yeah, till now always done that just had a hectic day 😅 Sorry guys!

**Comment by gaborgsomogyi** [comment]
Going to visit back and merge it when green. Thanks for the notification!

**Pull request merged**
