### PR TITLE
[FLINK-28514][network] Remove data flush in SortMergeResultPartition

### PR DESCRIPTION
**Pull request by TanYuxin-tyx**
## What is the purpose of the change

*Remove the data flush in SortMergeResultPartition because it is useless.*

## Brief change log

  - *Remove the data flush in SortMergeResultPartition because it is useless.*

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

This change is already covered by existing tests, such as *SortMergeResultPartitionTest*.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by TanYuxin-tyx** [comment]
@flinkbot run azure

**Comment by TanYuxin-tyx** [comment]
@flinkbot run azure

**Comment by TanYuxin-tyx** [comment]
@flinkbot run azure

**Comment by wsry** [comment]
@flinkbot run azure

**Comment by wsry** [comment]
@TanYuxin-tyx Thanks for the change. LGTM.

**Pull request merged**
