### PR TITLE
[FLINK-33437][connector] SinkV2 clear legacy state

### PR DESCRIPTION
**Pull request by dyccode**
## What is the purpose of the change
This pull request clears the legacy state of Sinkv2.

## Brief change log
SinkV2 clears legacy states after initialization.

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by dyccode** [comment]
@flinkbot run azure

**Comment by dyccode** [comment]
@flinkbot run azure

**Review by masteryhx — COMMENTED** [review]
LGTM.
I just thinked whether it could be tested easily.
Since it's related to the migration of Kafka Sink, Do you have any other comments?
@PatrickRen

**Comment by dyccode** [comment]
@masteryhx  Thanks for the review.What I need to do to merge this pr? Looking forward to your reply.

**Review by masteryhx — APPROVED** [review]
Sorry for the late reply.
The PR is fine. I will merge it.

**Comment by masteryhx** [comment]
merged efbd8c40 into master

**Pull request closed without merging**
