### PR TITLE
[FLINK-23073][formats / CSV] Fix space handling in Row CSV timestamp parser

### PR DESCRIPTION
**Pull request by sjwiesman**
## What is the purpose of the change

FLINK-21947 Added support for TIMESTAMP_LTZ in the CSV format by replacing `java.sql.Timestamp.valueOf` with `java.time.LocalDateTime.parse`. `Timestamp.valueOf` internally calls `trim()` on the string before parsing while `LocalDateTime.parse` does not. This caused a breaking change where the CSV format can no longer parse timestamps of CSV's with spaces after the delimiter. We should manually re-add the call to trim to revert the behavior.

## Brief change log

Add trim() to convertToTimestamp

## Verifying this change

- Trivial

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by sjwiesman** [comment]
cc @leonardBang

**Comment by leonardBang** [comment]
@sjwiesman Thanks for the contribution,  Could you also add `trim()` for `RuntimeConverter` in  `CsvRowDeserializationSchema` ？ and it will be great if we can add a test to cover this.

**Comment by sjwiesman** [comment]
@leonardBang thanks for pointing that out, and I've added a unit test. Please take another look when you get a chance

**Review by leonardBang — APPROVED** [review]
Thanks @sjwiesman for the update, LGTM

**Comment by sjwiesman** [comment]
thank you! will merge on green

**Comment by sjwiesman** [comment]
I realize we are having a discussion on the ML about not merging PR's with unrelated test failures but this test is already failing on master and is being tracked. I hope no one gets too upset with me 😅

**Pull request closed without merging**
