### PR TITLE
[FLINK-23375][connector/jdbc] Build proper JDBC test jar.

### PR DESCRIPTION
**Pull request by afedulov**
## What is the purpose of the change

Current `flink-connector-jdbc-tests.jar` does not contain class files.  This PR enables a proper tests jar build, similar to `files-connector-files-tests.jar`.

## Brief change log

A trivial change to `pom.xml`.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency):  no 
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`:  no 
  - The serializer:  no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

### CODE REVIEW

**Comment by fapaul** [comment]
@afedulov why do we want to generate a test jar for jdbc? So far we have been only using them if test classes are needed somewhere outside the module.

**Comment by afedulov** [comment]
@fapaul the original reporter clarified his needs on the ticket: https://issues.apache.org/jira/browse/FLINK-23375

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Review by fapaul — APPROVED** [review]
Thanks for the clarification I verified that the test classes are now bundled. @afedulov do you also want to backport this change?

**Pull request merged**
