### PR TITLE
[FLINK-4864] [table] Shade Calcite dependency in flink-table

### PR DESCRIPTION
**Pull request by wuchong**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.
- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)
- [x] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added
- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

This can solve version conflicts when users have a own Calcite dependency in the classpath.

### CODE REVIEW

**Comment by fhueske** [comment]
Thanks for the PR @wuchong.
I tried to build a Table API program with the flink-table dependency, but the compilation failed with the following error message:

> Caused by: scala.reflect.internal.Types$TypeError: bad symbolic reference. A signature in TableEnvironment.class refers to term parser in value org.apache.sql which is not available.

I'm not sure what exactly is going wrong, but it looks like the package `org.apache.sql` is not correct. It should probably be `org.apache.calcite.sql` which has a `parser` subpackage.

Thanks, Fabian

**Comment by wuchong** [comment]
Hi @fhueske . It seems that shading dependency in Scala project is very odd. By adding Calcite dependency to the Table API program project with the flink-table dependency, the compilation failure disappears. But this is not the way we want.

Have no idea how to fix this... but I will try to figure it out.

**Comment by wuchong** [comment]
Besides the compilation problem , Calcite has a bug [CALCITE-1461](https://issues.apache.org/jira/browse/CALCITE-1461) which will break shading. Maybe we should wait for this issue solved and released.

**Comment by fhueske** [comment]
Thanks for investigating this and submitting a PR to Calcite, @wuchong! 

Maybe @rmetzger has an idea of what's going wrong with the shading?

**Comment by rmetzger** [comment]
I tried reproducing the issue reported by @fhueske. The only issue I got was `Caused by: org.codehaus.commons.compiler.CompileException: Line 8, Column 13: Class "org.apache.calcite.rel.metadata.MetadataDef" not found`. 
I think that'll be fixed with CALCITE-1461. I guess @fhueske's issue is something local with the development environment.

**Comment by fhueske** [comment]
Thanks for looking into this @rmetzger. I'll check again on my setup.

**Comment by fhueske** [comment]
OK, I could reproduce the issue on my setup, but I have no idea why this happens. I checked the jar file and the Calcite classes seem to be correctly relocated (files are at correct location in jar file, import statements of compiled classes are adapted) and also the Flink Table API classes are compiled with adapted import statements. I created a new Flink project from the Scala Quickstart and the compilation fails in IntelliJ and with Maven.

I guess we have to take a deeper look into this issue :-/

**Comment by fhueske** [comment]
The problem is only present if the Flink application is compiled with the Scala compiler. If I use the Java Quickstart, everything works until the CALCITE-1461 bug appears. @rmetzger pointed me into the right direction. The Scala compiler does not rely on pure bytecode but seems to bypass some type and package information in a so-called `ScalaSig` attribute which is not evaluated by the Java compiler. Apparently, the Maven Shade plugin does not update this special Scala attribute.

**Comment by rmetzger** [comment]
Thank you for looking into the details of this. If the user who ran into the issue is using Java, they can fix the issue themselves by relocating our or their Calcite version locally.

If the user uses Scala, we could look into fixing the issue with a patch to the shade plugin (maybe using a custom [transformer](https://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html#transformers)?) Since I ran into the issue before I suspect that we'll run into the issue again.

**Pull request closed without merging**
