### PR TITLE
[BP-1.14][FLINK-27174][connector/kafka] Fix checking of bootstrapServers when already provided in producer Properties

### PR DESCRIPTION
**Pull request by onyourhead**
This is a backport PR for #19628

### CODE REVIEW

**Comment by onyourhead** [comment]
Sorry I don't quite understand what you mean. Should I rebase my branch fix-kafkasink-check-1.14 onto the latest release-1.14 branch, and then force push.

**Comment by fapaul** [comment]
> Sorry I don't quite understand what you mean. Should I rebase my branch fix-kafkasink-check-1.14 onto the latest release-1.14 branch, and then force push.

Yes exactly, I think the problem the CI currently shows has been fixed but you need to rebase and force push.

**Comment by onyourhead** [comment]
@flinkbot run azure

**Comment by onyourhead** [comment]
@flinkbot run azure

**Pull request merged**
