### PR TITLE
FLINK-2605 Unclosed RandomAccessFile may leak resource in StaticFileS…

### PR DESCRIPTION
**Pull request by tedyu**
…erverHandler

### CODE REVIEW

**Comment by tedyu** [comment]
Your reasoning w.r.t. current scope of try block was the same as mine.

I think it is good to make the scope as accurate as possible. Generally speaking, we don't want to react to unrelated exception.

Please keep the current formation.

**Comment by StephanEwen** [comment]
+1

**Comment by hsaputra** [comment]
+1

LGTM

**Comment by chiwanpark** [comment]
+1

Merging...

**Pull request closed without merging**
