### PR TITLE
[FLINK-16070] [table-planner-blink] blink stream planner supports remove constant keys from an aggregate

### PR DESCRIPTION
**Pull request by godfreyhe**
## What is the purpose of the change

*currently AggregateProjectPullUpConstantsRule is in cost-based phase (logical phase), while RelMdPredicates does not work when meeting RelSubset. So we can add AggregateProjectPullUpConstantsRule into hep planner to fix the bug.*

## Brief change log

  - *add AggregateProjectPullUpConstantsRule into default_write phase*

## Verifying this change

This change added tests and can be verified as follows:

  - *Added testGroupByConstantKey method in AggregateTest to validate constant group key in queres*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by godfreyhe** [comment]
@JingsongLi thanks for the review, I have added a IT case to test upsert sink with primary key

**Comment by JingsongLi** [comment]
Can you create a PR for release-1.10?

**Comment by godfreyhe** [comment]
> +1, should we add this rule to batch too?

Batch has already contained this rule

**Comment by JingsongLi** [comment]
Merged, thanks for the contribution.

**Pull request merged**
