### PR TITLE
[FLINK-3184] [timeouts] Decrease timeouts

### PR DESCRIPTION
**Pull request by tillrohrmann**
This PR introduces a client side timeout of 60 s and a cluster side timeout of 10 s. Both timeouts can be configured via `akka.client.timeout` and `akka.ask.timeout` in the configuration.

### CODE REVIEW

**Comment by uce** [comment]
Good changes.

I like the configuration key changes, but we have to keep in mind that they are API breaking. With 1.0 approaching, I think it's good to do the changes now and not later. So I'm personally +1.

If someone has an objection, we can add a deprecated variant with the old keys and log a warning if necessary.

**Comment by StephanEwen** [comment]
I like having lower ask timeouts.

+1 from my side

**Comment by tillrohrmann** [comment]
This is true. Might be a bit anticipated but I plan to remove them completely with my next PR. I want to introduce a `RestartStrategy` which can be set on a job basis and basically encapsulates the restart logic.

**Comment by StephanEwen** [comment]
With upcoming Mesos integration (and some YARN refactoring), we can probably drop the heartbeats between master and worker as well from Akka.

**Comment by StephanEwen** [comment]
What is the `RestartStrategy` about?

**Comment by tillrohrmann** [comment]
The idea is to decouple the restart logic from the `JobManager` and to make it configurable on a per job basis. Different strategies are conceivable. For instance, what we have right now, a fixed delay restart strategy. Additions could be an exponential backoff restart strategy or later a scale in/out restart strategy. Furthermore, this allows to set the delays on a per job basis which might be relevant for specific SLAs.

But in general it's more like a preliminary step towards the scale in/out restart strategy, I guess.

**Comment by uce** [comment]
I've created https://docs.google.com/document/d/1987ydc2rez79Pph7qBbcXwu6XzMU2Hm-nX8kORLoZBM/edit?usp=sharing and added the config renaming as an API breaking change. I will share this list on the ML.

**Comment by uce** [comment]
Ahhh sorry for my stupid comment. The actual config values didn't change.

**Comment by StephanEwen** [comment]
Looks good.

We talked a lot about setting the default execution retry delay to 0 (from its way to high current value). Should we do this here as well (is that a safe change?)

**Comment by tillrohrmann** [comment]
We could set the default execution retry delay to 0 assuming that any longer timeout in a streaming use case would render the job wrong anyway. However, if a longer timeout is acceptable, then we would lose the ability to recover from a lost task manager which usually takes some time to reconnect to the cluster (given that we use all instances).

I would be more in favour of having an exponential back off strategy as the default. This would give us a quick recovery in case that we have enough resources available but also the possibility to wait for a TM reconnection. We could implement such a restart strategy once the PR #1470 is merged.

What do you think?

**Comment by StephanEwen** [comment]
That sounds like a good idea!

+1 to merge this one then...

**Comment by mbalassi** [comment]
I do like the exponential back off as default, enables streaming but is flexible enough to tolerate temporal resource unavailability.

Having simply 0 as default does not seem safe for me.

**Comment by tillrohrmann** [comment]
Will rebase and then merge this PR.

**Comment by tillrohrmann** [comment]
Testing failure seems to be unrelated. Merging the PR.

**Pull request closed without merging**
