### PR TITLE
Eratosthenes Sieve, a helpful and interesting example of using DeltaIteration

### PR DESCRIPTION
**Pull request by dsnz**

### CODE REVIEW

**Comment by greghogan** [comment]
Thank you for this contribution. Please open a [ticket](https://issues.apache.org/jira/browse/FLINK) describing your algorithm and its appropriateness as an example running on a distributed stream processor.

**Comment by dsnz** [comment]
Hello,
I can describe the algorithm but I cannot say anything about appropriateness as an example running on a distributed stream processor. I don't use Flink, I just tried to learn quickly its API and get a handle of it and certainly I cannot run/try distributed instances.
Is this okay ? How can I best help with this example ?

**Comment by greghogan** [comment]
The code would need to be cleaned up. I would look to the other examples, add comments, remove unused code, change anonymous inner classes to be static inner classes, etc. There is also the question, what makes a good Flink example? Single-threaded programs [1](http://primesieve.org/segmented_sieve.html) and [2](http://sweet.ua.pt/tos/software/prime_sieve.html) can sieve 10^9 numbers in under 1 second. I think we are better off with batch examples that demonstrate Flink's performance (such as processing sparse datasets).

If you are interested in adding to the existing examples that would be a good discussion for the [dev](https://flink.apache.org/community.html#mailing-lists) mailing list. I also expect that more users are reading the online documentation than inspecting the examples so that is another opportunity for contributions.

**Comment by uce** [comment]
@dsnz Thanks for this PR. In general, I think it's a good idea to think about what kind of example programs we have. Unfortunately, I don't think that this example adds much in comparison to the already available ones. Would you mind closing this PR? I'm happy to revisit this if a discussion as suggested by Greg on the dev mailing list comes to the conclusion that we should add this or other examples.

**Comment by dsnz** [comment]
Hi,

The examples given (by greghogan) are specialized C++ programs. I don't say that this example shows Flink's capabilities relative to other solutions but that it's a very helpful for the novice to understand how to setup a new Flink program and use the DeltaIteration API call and is also in the spirit of some other Flink examples like 'Pi Estimation'.
In fact it helped me a lot to learn about developing with Flink because the documentation was/is quite lacking in many areas.

Most novices do benefit from examples first and from good documentation later when they grasp the subject.

I'm closing this anyway as I'm not in the Flink community of users and don't have time and further interest to start a discussion for such a simple example.

**Pull request closed without merging**
