### PR TITLE
[FLINK-34345][runtime] Remove TaskExecutorManager related logic

### PR DESCRIPTION
**Pull request by caicancai**
## What is the purpose of the change

[FLINK-31449](https://issues.apache.org/jira/browse/FLINK-31449) removed DeclarativeSlotManager related logic. Some related classes should be removed as well after [FLINK-31449](https://issues.apache.org/jira/browse/FLINK-31449), such as:

- TaskExecutorManager
- TaskExecutorManagerBuilder
- TaskExecutorManagerTest
- org.apache.flink.runtime.resourcemanager.slotmanager.TaskManagerRegistration
- PendingTaskManagerSlot
- TaskManagerSlotId
- SlotStatusUpdateListener
- TestingTaskManagerSlotInformation

## Brief change log

[FLINK-34345][runtime] Remove TaskExecutorManager related logic

### CODE REVIEW

**Comment by caicancai** [comment]
related to https://issues.apache.org/jira/browse/FLINK-31449

**Comment by caicancai** [comment]
@RocMarshal @1996fanrui If you have time, can you help me review it? Thank you.

**Review by 1996fanrui — APPROVED** [review]
Thanks @caicancai for the cleanup!

It looks like these codes are no longer used, LGTM assuming the CI is green.

**Review by 1996fanrui — CHANGES_REQUESTED** [review]
After I check, I think there are other classes can be removed as well, such as:

- TaskManagerRegistration
   - Note: It's `org.apache.flink.runtime.resourcemanager.slotmanager.TaskManagerRegistration` 
   - `org.apache.flink.runtime.jobmaster.TaskManagerRegistration` cannot be removed.
- PendingTaskManagerSlot
- TaskManagerSlotId
- SlotStatusUpdateListener
- org.apache.flink.runtime.resourcemanager.slotmanager.SlotManagerConfigurationBuilder
- TestingTaskManagerSlotInformation

Please help double check these classes, and check is there other classes can be removed as well, thanks!

**Comment by caicancai** [comment]
> After I check, I think there are other classes can be removed as well, such as:
> 
>     * TaskManagerRegistration
>       
>       * Note: It's `org.apache.flink.runtime.resourcemanager.slotmanager.TaskManagerRegistration`
>       * `org.apache.flink.runtime.jobmaster.TaskManagerRegistration` cannot be removed.
> 
>     * PendingTaskManagerSlot
> 
>     * TaskManagerSlotId
> 
>     * SlotStatusUpdateListener
> 
>     * org.apache.flink.runtime.resourcemanager.slotmanager.SlotManagerConfigurationBuilder
> 
>     * TestingTaskManagerSlotInformation
> 
> 
> Please help double check these classes, and check is there other classes can be removed as well, thanks!

org.apache.flink.runtime.resourcemanager.slotmanager.SlotManagerConfigurationBuilder 
I saw that some classes are used, are you sure to delete them?

**Comment by 1996fanrui** [comment]
> org.apache.flink.runtime.resourcemanager.slotmanager.SlotManagerConfigurationBuilder
I saw that some classes are used, are you sure to delete them?

It seems my IDEA doesn't  index well. It's indeed  used.

**Review by 1996fanrui — APPROVED** [review]
Thanks @caicancai for the update!

LGTM.

BTW, Flink 1.19 has been code frozen. The new features and improvements cannot be merged, and bugfixes and doc can be merged.

I'm not sure could the code cleanup be merged, I will ask in the [[ANNOUNCE] Flink 1.19 feature freeze & sync summary on 01/30/2024](https://lists.apache.org/thread/jyd4rtk7zbb1hdflbnoktzc8xyff5sqm) thread.

**Comment by caicancai** [comment]
Thank you for your review and patient reply

**Comment by 1996fanrui** [comment]
The master branch has been cut to 1.20, merging~

**Pull request merged**
