### PR TITLE
[hotfix][docs] Delete kafka connector docs

### PR DESCRIPTION
**Pull request by ruanhang1993**
## What is the purpose of the change

Delete kafka connector docs

## Brief change log

Delete kafka connector docs

## Verifying this change

This change is a cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no 
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by YuanHanzhong** [comment]
I am wondering the reason you delete it.

**Comment by ruanhang1993** [comment]
> I am wondering the reason you delete it.

The kafka documents have been moved to the project `flink-connector-kafka` and we do not need these documents now.

**Comment by JingGe** [comment]
Hi @ruanhang1993 How will users find the kafka connector doc while they are reading docs on https://flink.apache.org/?

**Comment by ruanhang1993** [comment]
> Hi @ruanhang1993, just out of curiosity, how will users find the kafka connector doc while they are reading docs on https://flink.apache.org/?

Connector docs will be copied by `integrate_connector_docs` in `setup_docs.sh`. Other connector docs have been removed like ES, JDBC.

**Review by JingGe — APPROVED** [review]
Thanks for your effort! LGTM

**Pull request merged**
