### PR TITLE
Update japicmp comparison version to latest Flink 1.8.0

### PR DESCRIPTION
**Pull request by aljoscha**

### CODE REVIEW

**Comment by aljoscha** [comment]
When I merged this, I'll also merge it on `release-1.8`, right?

**Comment by zentol** [comment]
afaik this should only be merged to master, for which you've got my +1.

**Comment by zentol** [comment]
now that I think about it though, that would mean that, if a Public API was added in 1.8.0, we could remove it in 1.8.1 again. curious...

**Comment by aljoscha** [comment]
That's why I thought adding it to `release-1.8` would also make sense.

**Comment by zentol** [comment]
OK, let's think this through properly.

The 1.X.0 release compares against the last 1.(X-1).Z release.
The release-1.X branches always compare against the latest 1.X.Y release.

This creates a tree structure, with the latest releases _always_ being leaf nodes.

```
A -> B : B checks compatibility against A

1.6.0 -> 1.6.1 -> 1.6.2 -> ...
            \-> 1.7.0 -> 1.7.1 -> 1.7.2 -> 1.7.3
                   \-> 1.8.0 -> 1.8.1 -> 1.8.2 ...
```

Can there be incompatible changes between leaf nodes, i.e. 1.6.3 and 1.7.3, without this breaking other incompatibilities?
I think one case might be that 1.6.4 adds a new Public API, but 1.7.3 adds a _different version_ of this API.

My conclusion would be that we have to run the check twice; against the latest version in the previous series as well as the latest version in the current series.
1.6.0 -> 1.6.1 -> 1.6.2 --\\
            \-> 1.7.0 -> 1.7.1 -> 1.7.2 -> 1.7.3
                   \-> 1.8.0 -> 1.8.1 -> 1.8.2 <--/

**Comment by aljoscha** [comment]
merged

**Pull request closed without merging**
