### PR TITLE
[FLINK-14398][SQL/Legacy Planner]Further split input unboxing code into separate methods

### PR DESCRIPTION
**Pull request by haodang**
## What is the purpose of the change

When a resultant table is wide, the large number of non-trivial input unboxing code can push the generated byte code beyond the 64kb limit for some methods.  This PR splits them into individual methods.

## Brief change log

In CodeGen, when a split is needed, we create individual methods for each of the expressions inside `reusableInputUnboxingExprs`, which is in addition to the split of result setters.

## Verifying this change
The code path in this change is exercised at the same time when existing code split takes place and all existing unit tests that verify code splits should be able to verify this.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (yes)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by wuchong** [comment]
Hi @haodang , you can at me when this PR is ready to be reviewed.

**Comment by zentol** [comment]
If the PR isn't ready to be reviewed, why is it open?

**Comment by wuchong** [comment]
I also have this question. According to the contribution guideline, the pull request should be opened  only if it is ready to be reviewed. An working in process branch can be verified in your own repository.

**Comment by haodang** [comment]
Thank you @wuchong @zentol for the response.  The code is ready for review now.  I was having issues with my IDE last night and wanted push it here to run tests and unblock as I fix things locally.

There is one thing that I'd like to discuss for this version of implementation: technically we haven't split `all` code blocks inside `CodeGenerator#reusableInputUnboxingExprs`, because currently the split happens in `CodeGenerator#generateResultExpression` and more expressions could be added to  `CodeGenerator#reusableInputUnboxingExprs` after `CodeGenerator#generateResultExpression` is called.

The rationale was to minimize splitting and split unboxing input code only relevant to those result setters (which was the root cause of the JIRA issue).  Wanted to hear your thought on this and see if there is an approach that fits the codebase better.

**Comment by wuchong** [comment]
Hi @haodang , I just found this pull request is based on release-1.8. However, usually, the community suggests to open pull requests on master first, and then will be cherry-picked to previous release braches. 

Could you open another pull request against master branch and continue the discussion?

**Comment by haodang** [comment]
Makes sense @wuchong.  I can do that.  Will try to get that in over the next few days.

**Comment by haodang** [comment]
closing in favor of PR https://github.com/apache/flink/pull/10000

**Pull request closed without merging**
