### PR TITLE
[FLINK-951] Reworking of Iteration Synchronization, Accumulators and Aggregators

### PR DESCRIPTION
**Pull request by markus-h**
Iteration synchronization through JobManager
Unification of Accumulators and Aggregators (removal of former Aggregators)
Adjusted testcases accordingly

I redid the work of my very old pull request https://github.com/apache/flink/pull/36
A more detailed description can be found in jira https://issues.apache.org/jira/browse/FLINK-951

I came across some unexpected behaviour with akka that made a small hack neccessary. Perhaps somebody with more experience in akka can find a better solution. See IterationHeadPactTask line 392.

### CODE REVIEW

**Comment by uce** [comment]
Nice to see that you picked this up again. :-) I know from experience that it can be tricky to port the old RPC calls to Akka msgs, so kudos. ;-)

- I actually agree with your reformatings, but we had a discussion recently (http://apache-flink-incubator-mailing-list-archive.1008284.n3.nabble.com/DISCUSS-Issues-with-heterogeneity-of-the-code-td4292.html#a4443) to refrain from reformattings. I think it makes it harder to review your changes. We haven't really written this down somewhere (this is actually a good reminder that we need to do this), but you should keep it in mind.

- I only had a quick look at the hack you pointed out. I think we should *not* merge it in the current state (in any case I would vote to postpone merging this until *after* the upcoming milestone release). Can you provide more information about what kind of Exception is thrown? Waiting for 10 ms is not robust against different timings on different machines.

I think the blocking Await is OK in this case. We should add tests for the basic JM <-> IterationHeadTask interaction though.

**Comment by markus-h** [comment]
Thanks for your comments!
I will try to revert my formattings. I am used to doing STRG+F while programming that probably changed the formatting.

I also got rid of the Thread.sleep(). The problem was acutally a different one. Akka delivered the same response object to threads on the same machine, but I thought it would be copies. Now I do a hard copy of the response, that seems to fix the problem.

I am not sure how to test the interaction between IterationHead and JM though. Is there some similiar testcase that I could use as a basis?

**Comment by markus-h** [comment]
There seems to be a race condition somewhere in my code but I have trouble finding it since I can not reproduce it locally. I thought my last change would fix it but it didn't.
So if somebody has some free time and knows a bit about race conditions feel free to help me :-)

**Comment by uce** [comment]
Have the latest commits fixed it? :)

**Comment by markus-h** [comment]
I am not sure but it looks very good :-)
I think I found the problem and the latest test did not fail. I am not sure why the travis result is not shown inside the pull request anymore.

**Comment by markus-h** [comment]
Is someone still interested in this change? Again it has been more then 3 weeks since opening this pull request and I fixed all comments that were given. Since I touch a lot of files it will get harder to rebase this again the longer it takes. 
If this change is not interesting for you I can close it, just tell me.

**Comment by rmetzger** [comment]
Hey @markus-h, sorry for not reacting to your pull request (other changes also sometimes need a lot of time until they are merged)
I think @StephanEwen would be the best reviewer for this pull request. He is currently at Strata in London. Maybe he has time to take a closer look here once he is back.

**Comment by StephanEwen** [comment]
I had a look at the pull request and I like very much what it tries to do.

The problem right now is that I can hardly say without investing a lot of time whether this is in good shape to merge. This pull request does a at least two very big things at the same time:
 - Move iteration synchronization to the JobManager
 - Unify aggregators and accumulators into one.

With all the example / testcase adjustments, this becomes a lot to review. The description of the pull request also does not make it easy, since many questions and decisions that arise are not explained:
 - What interface do the unified aggregators/accumulators follow: The aggregators, or the accumulators.
 - How is the blocking superstep synchronization currently done. With actor ask?
 - How is the aggregator/accumulator unification achieved, when aggregators are created per superstep, and accumulators once?

This is a lot for a very delicate and critical mechanism. I think if we want to merge this, we would need more details on how things were changed (what is the concept behind the changed, not just what are the code diffs).
We may need to break it into multiple self-contained changes that we can individually review and merge, to make sure that it gets properly checked and will work robustly.

**Comment by markus-h** [comment]
Sorry for not driving this further. I think this pull request is now way too outdated to have any chance of rebasing it to the current master, therefore I will close it.

**Pull request closed without merging**
