### PR TITLE
[FLINK-12223][Runtime] HeapMemorySegment.getArray should return null after being freed

### PR DESCRIPTION
**Pull request by liyafan82**
## What is the purpose of the change

Fix a bug in class HeapMemorySegment. The getArray method should return null after the segment is freed. But it does not.

## Brief change log

  - Fix the bug in class HeapMemorySegment
  - Add a UT in HeapMemorySegmentTest.
  

## Verifying this change

This change added tests and can be verified as follows:

  - Test HeapMemorySegmentTest.testGetArrayAfterFree will fail without this fix, and it runs successfully with this patch.
  
## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by liyafan82** [comment]
Hi @zentol , would you please take a look at this PR?

**Comment by liyafan82** [comment]
@flinkbot attention @StephanEwen

**Comment by azagrebin** [comment]
@liyafan82 
I rebased the PR and squashed the commits. Please, take a look if the final state is ok, then I will merge it when CI is green.

**Comment by liyafan82** [comment]
> @liyafan82
> I rebased the PR and squashed the commits. Please, take a look if the final state is ok, then I will merge it when CI is green.

LGTM, thanks for your effort.

**Comment by azagrebin** [comment]
@flinkbot run travis

**Pull request merged**
