### PR TITLE
FLINK-25535 The JVM parameter does not take effect

### PR DESCRIPTION
**Pull request by cuibo01**
## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by cuibo01** [comment]
@twalthr @Airblader @tillrohrmann hi , can u review the PR

**Comment by cuibo01** [comment]
on yarn cluster Parameters:
exec /bin/bash -c "$JAVA_HOME/bin/java -Xmx469762048 -Xms469762048 -XX:MaxMetaspaceSize=268435456 ... org.apache.flink.yarn.entrypoint.YarnApplicationClusSocket error Event: 32 Error: 10053.ff-heap.size=134217728b **-D jobmanager.memory.jvm-overhead.min=201326592b -D jobmanager.memory.jvm-metaspace.size=268435456b -D jobmanager.memoryConnection** closing...Socket close.r.memory.jvm-overhead.max=201326592b 1> ... 2> ...

**Review by tillrohrmann — COMMENTED** [review]
Thanks for creating this PR @cuibo01. I think the fix itself is good. I am wondering whether it actually fixes a problem. Did you observe a problem with splitting `-D foo=bar`? If I am not mistaken, then Flink also understands this format. Otherwise the memory configuration would have never worked.

**Comment by cuibo01** [comment]
> Thanks for creating this PR @cuibo01. I think the fix itself is good. I am wondering whether it actually fixes a problem. Did you observe a problem with splitting `-D foo=bar`? If I am not mistaken, then Flink also understands this format. Otherwise the memory configuration would have never worked.

thx @tillrohrmann, got, Because jobmanager.memory.jvm-overhead.min is behind the runClass(YarnApplicationClusSocket), it is used as a parameter by runClass, not by System#Property.

**Pull request closed without merging**
