### PR TITLE
[FLINK-9328][state] Fix RocksDBStateBackend restore problem due to StateBackendTestBase not registering snapshots

### PR DESCRIPTION
**Pull request by Myasuka**
## What is the purpose of the change

Currently, StateBackendTestBase class does not register snapshots to SharedStateRegistry in testValueState, testListState, testReducingState, testFoldingState and testMapState UTs, which may cause RocksDBStateBackend to restore from PlaceholderStreamStateHandle during the 2nd restore procedure if one specific sst file both existed in the 1st snapshot and the 2nd snapshot handle.

## Brief change log

Add sharedStateRegistry and register each snapshot to it.

## Verifying this change

This change fix UT problem.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by tzulitai** [comment]
Hi @Myasuka, it seems like your local branch is not properly rebased on the latest master.
Could you try rebasing again and reopening the PR?

**Comment by Myasuka** [comment]
Sorry for the late reply, @tzulitai I have already rebased on the latest master now.

**Comment by Myasuka** [comment]
The failing UT JobManagerFailsITCase in [#25170.9-build](https://travis-ci.org/apache/flink/jobs/393258719) is not related with this PR, shall I re-trigger the CI process?

**Comment by azagrebin** [comment]
Hi @Myasuka , this has been actually already fixed in #6467, can we close it? what do you think?

**Comment by Myasuka** [comment]
@azagrebin Sure, since the test code already fixed, just close this PR.

**Comment by StefanRRichter** [comment]
Outdated. This was already fixed in master.

**Pull request closed without merging**
