### PR TITLE
[FLINK-21565][Table SQL/API] Support more integer types in TIMESTAMPADD

### PR DESCRIPTION
**Pull request by shenzhu**
## What is the purpose of the change

This pull request adds support for more integer types in `TIMESTAMPADD`.

## Brief change log

- Add support from `TINYINT`/`SMALLINT` to `INTERVAL_DAY_TIME`/`INTERVAL_YEAR_MONTH`

## Verifying this change

This change added tests and can be verified as follows:
- Unit tests are added to cover changes in this PR.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Review by RocMarshal — COMMENTED** [review]
Good job. @shenzhu . it looks to me on the whole. 
It would be better if you could add some ITest cases for the change .

**Comment by shenzhu** [comment]
> Good job. @shenzhu . it looks to me on the whole. It would be better if you could add some ITest cases for the change .

Hey @RocMarshal , thanks for your review! I added more tests in `CalcITCase`

**Review by RocMarshal — APPROVED** [review]
Thanks for the update @shenzhu .
We still need a committer or pmc to do the final review.
ping @AHeise .

**Comment by AHeise** [comment]
Table is not my turf. @twalthr can you PTAL?

**Review by snuyanzin — APPROVED** [review]

**Comment by shenzhu** [comment]
Hey @twalthr , would you mind taking a look at this PR when you have a moment? Thanks!

**Comment by shenzhu** [comment]
Hey @wuchong , would you mind taking a look at this PR when you have a moment? Thanks!

**Comment by shenzhu** [comment]
Hey @twalthr , sorry to bother you, would you mind taking a look at this PR when you have a moment? Thanks!

**Comment by shenzhu** [comment]
Hey @twalthr @wuchong , could you please take a look at this PR when you have a moment? Thanks!

**Comment by shenzhu** [comment]
Hey @zentol , would you mind taking a look at this PR when you have a moment? Thanks!

**Comment by shenzhu** [comment]
Hey @wuchong @beyond1920 , would you mind taking a look at this PR when you have a moment? Thanks!

**Comment by beyond1920** [comment]
@shenzhu Thanks a lot for contribution.
Very sorry for late response.
I would review it ASAP.

**Comment by beyond1920** [comment]
@shenzhu LGTM. Thanks for contribution.

**Review by beyond1920 — APPROVED** [review]

**Comment by shenzhu** [comment]
> apache/flink@3ebe919

Hey @beyond1920 , thanks for your review!

**Pull request closed without merging**
