### PR TITLE
[FLINK-6261] [table] Support TUMBLE, HOP, SESSION group window functions for SQL queries on batch tables

### PR DESCRIPTION
**Pull request by fhueske**

### CODE REVIEW

**Comment by haohui** [comment]
Thanks for the PR! It looks good to me overall. One problem is that `dataSet.LogicalWindowAggregateRule` has duplicated quite a bit of code in the `dataStream.LogicalWindowAggregateRule`.

Maybe it makes sense to refactor some of the code into a common class, so that we can follow the same pattern for the implementation of the WindowStart / WindowEnd functions?

**Comment by fhueske** [comment]
Thanks for the review @haohui! 

You're right about the code duplication. I had started with addressing DataSet and DataStream in one class but ended up with many `if(stream)` conditions. 
I'll refactor that into an abstract class with two subclasses and update the PR soon.

**Comment by fhueske** [comment]
Hi @haohui, I updated the PR and refactored the rule into an abstract class that is extended by a rule for datastream and another one for dataset.

**Please note**: I also removed support for `GROUP BY FLOOR/CEIL` on streams. My motivation is the following:
- it can be expressed with `TUMBLE` (which is even more expressive)
- We will add support for "non-windowed" aggregations (see PR #3646 by @shaoxuan-wang ) which can include the `GROUP BY FLOOR/CEIL` case. These aggregations will compute the same result but behave differently at runtime. Instead of collecting data and emitting a final result, they will be incrementally computed and send out more updates. I think the behavior of system is more predictable if we only translate Calcite's group window functions into DataStream group windows and all other grouped aggregates into non-windowed aggregates. We target the non-windowed aggregates for the next release.
- It will make the translation easier. The pattern matching of `FLOOR/CEIL` seems a bit fragile to me. I like Calcite's group window functions more.

Please let me know what you think about this change and if you have concerns.

Best, Fabian

**Comment by haohui** [comment]
The PR looks pretty good. Thanks @fhueske for improving the documentation.

+1 (non-binding)

**Comment by fhueske** [comment]
Thanks for the review @haohui!

Just to make sure: You're OK with removing support for windows defined as `GROUP BY CEIL(rowtime() TO HOUR)`?

Thanks, Fabian

**Comment by haohui** [comment]
Yes. I agree with you that `FLOOR` / `CEIL` are quite fragile and it is much clearer to use the `TUMBLING` / `HOP` / `SESSION` constructs.

**Comment by fhueske** [comment]
Thanks, will merge this PR :-)

**Pull request closed without merging**
