### PR TITLE
[FLINK-20871][API/DataStream] Make DataStream#executeAndCollectWithCl…

### PR DESCRIPTION
**Pull request by stevenzwu**
…ient() public

### CODE REVIEW

**Comment by stevenzwu** [comment]
@flinkbot run azure

**Comment by stevenzwu** [comment]
Regarding the whitespace format change, I have run `mvn com.diffplug.spotless:spotless-maven-plugin:apply` to verify

**Comment by dawidwys** [comment]
Hi @stevenzwu ,
What is the exact motivation for the change? Is it only to be able to cancel the job after a certain number of elements? If so as far as I can tell from the code, closing the iterator from `CloseableIterator<T> executeAndCollect(String jobExecutionName)` will do the trick.

Anyway, if you feel we need access to the `JobClient` I think we should fix the `ClientAndIterator` class before making it publicly accessible. Right now it is marked `Internal`. Personally I am also not the biggest fan of accessing fields directly instead of via getters. That should not be a bigger problem in an `Internal` class, but might be problematic in a public one.

@sjwiesman WDYT?

**Comment by dawidwys** [comment]
BTW if you want to retrigger the azure build you can add a comment to the PR: `@flinkbot run azure`

**Comment by sjwiesman** [comment]
I agree with @dawidwys that this method was made internal on purpose. The only reason it isn't private is to share functionality with the deprecated methods in DataStreamUtils. Ideally, I would like to keep it that way if `executeAndCollect` works for you. 

If not, then I think `ClientAndIterator` needs to be updated before being made public. Proper `getters` and updated javadoc.

**Comment by stevenzwu** [comment]
@davidwys yes, the motivation is to be able to cancel the job after a certain number of elements. I didn't realize that closing the iterator from CloseableIterator<T> can cancel the job as well. Will close this PR and jira.

**Comment by sjwiesman** [comment]
I'll will update the javadoc to be more clear :)

**Comment by stevenzwu** [comment]
@sjwiesman thx. I should have looked into the iterator code first.

**Comment by stevenzwu** [comment]
@davidwys @sjwiesman I'd like to reopen this request. Now the additional requirement is to retrieve `JobID` to trigger jobmanager failover. e.g.

https://github.com/apache/flink/blob/91cc3082c23b38513250d78bbb385271bd223df3/flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/src/FileSourceTextLinesITCase.java#L136

**Comment by zentol** [comment]
Use `DataStream#collectAsync` + `StreamExEnv#executeAsync`.

**Pull request closed without merging**
