### PR TITLE
[hotfix] Fix the problem that BatchShuffleItCase not subject to configuration.

### PR DESCRIPTION
**Pull request by reswqa**
## What is the purpose of the change

*Fix the problem that `BatchShuffleItCase` not subject to configuration.*

## Brief change log

  - *pass configuration to `StreamExecutionEnvironment.getExecutionEnvironment`*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive):  no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Review by xintongsong — APPROVED** [review]
LGTM

**Comment by xintongsong** [comment]
@flinkbot run azure

**Comment by xintongsong** [comment]
@flinkbot run azure

**Comment by reswqa** [comment]
@flinkbot run azure

**Comment by xintongsong** [comment]
@flinkbot run azure

**Pull request closed without merging**
