### PR TITLE
[hotfix][ci] Fix hugo docs builds

### PR DESCRIPTION
**Pull request by rmetzger**
The destination argument is relative to the source

### CODE REVIEW

**Review by zentol — APPROVED** [review]
+1, but maybe add a comment that this will put the docs under docs/target.

Bonus points for adding -v to the command for debugging such issues in the future.

**Review by zentol — CHANGES_REQUESTED** [review]
tools/ci/docs.sh is referenced in `build-apache-repo.yml`

**Comment by rmetzger** [comment]
Good catch. We should look into unifying the two scripts

**Review by zentol — APPROVED** [review]
+1

**Comment by rmetzger** [comment]
Thx, merging!

**Pull request merged**
