### PR TITLE
[FLINK-23581][docs] Change site.download_url to https://flink.apache.…

### PR DESCRIPTION
**Pull request by hapihu**
The url of the download link is not written correctly, so the link is invalid.

The wrong link information is as follows：
 `[download page]({{ site.download_url }}) `
It should be modified as follows：
 `[download page](https://flink.apache.org/downloads.html) `

**The modifications involved are as follows：**

```bash
1.  [download page]({{ site.download_url }})   
Modified as follows: 
[download page](https://flink.apache.org/downloads.html)
 
2. [下载页面]({{ site.zh_download_url }}) 
Modified as follows: 
[下载页面](https://flink.apache.org/zh/downloads.html)
  
3. [Downloads / Additional Components]({{site.download_url}}#additional-components)
Modified as follows: 
[Downloads / Additional Components](https://flink.apache.org/downloads.html#additional-components)

```

### CODE REVIEW

**Comment by wuchong** [comment]
@sjwiesman could you help to check this? It seems the `[download page]({{ site.download_url }})` is not rendered correctly. Maybe we forgot to set the property `site.download_url`.

**Review by zentol — CHANGES_REQUESTED** [review]
We should add a new `DownloadPage` property to `docs/config.toml` under `[params]`, and migrate all links to that property using `{{ .Site.Params.DownloadPage }}`.

**Comment by hapihu** [comment]
@zentol , Hi 
Thank you for your review.
I have made the changes according to your suggestion.
I consulted Hugo's official documentation：https://gohugo.io/content-management/shortcodes/#param.
Please help me review it again.
Thank you very much!

**Comment by sjwiesman** [comment]
@hapihu I'd like to ask for one more change to this PR. Can you please add a new shortcode (under `layouts/shortcodes`) called `downloads.html` that automatically picks the right param based on the language of the page. It should look something like this:

```html
{{ if eq "/zh" .Site.LanguagePrefix }}
	{{ .Site.Params.ZhDownloadPage }}
{{ else }}
	{{ .Site.Params.DownloadPage }}
{{ end }}
```

In the docs, links will look like:

```md
[downloads]({{< downloads >}})
```

This way the English and Chinese docs will always point to the correct page, and we don't need to worry about using different links when translating.

**Comment by hapihu** [comment]
> @hapihu I'd like to ask for one more change to this PR. Can you please add a new shortcode (under `layouts/shortcodes`) called `downloads.html` that automatically picks the right param based on the language of the page. It should look something like this:
> 
> ```
> {{ if eq "/zh" .Site.LanguagePrefix }}
> 	{{ .Site.Params.ZhDownloadPage }}
> {{ else }}
> 	{{ .Site.Params.DownloadPage }}
> {{ end }}
> ```
> 
> In the docs, links will look like:
> 
> ```lisp
> [downloads]({{< downloads >}})
> ```
> 
> This way the English and Chinese docs will always point to the correct page, and we don't need to worry about using different links when translating.

Hi @sjwiesman , Thank you for your guidance.
I have made the changes as suggested.

**Comment by hapihu** [comment]
Hi @zentol ,Would you like to review it for me again.
Thank you very much!

**Pull request merged**
