### PR TITLE
[FLINK-2448]Create new Test environments on getExecutionEnvironment calls. Allow sharing of results.

### PR DESCRIPTION
**Pull request by sachingoel0101**

### CODE REVIEW

**Comment by zentol** [comment]
Does this work properly with collect() calls? as in, would the following plan still work?

`env = ..
env.registerCacheFile()
...
someSet.collect()
<doSomethingThatUsesTheCacheFile>
env.execute()
`

if we wipe all cache entries in the collect() call, the files will not be registered in the execute(), right? The plans these methods create are separate i think.

**Comment by sachingoel0101** [comment]
Ah yes. You're right. Lemme see if I can write a workaround to this.

**Comment by sachingoel0101** [comment]
Should there be a unit test to verify this functionality?

**Comment by StephanEwen** [comment]
I am not sure this is solving it the right way. I find it more intuitive if cache files stay registered. They are part of the environment and should be "sticky", like configuration settings as well (they don't get lost after execution).

We could add a method to clear registered cache files. But if the problem is really only the MultiplProgramsTest base, then this should be fixed to return a new ExecutionEnvironment from a (the) TestEnvironmentFactory every time you call `getExecutionEnvironment()`.

**Comment by sachingoel0101** [comment]
I'm not sure if I can form an opinion on this. I personally haven't used them at all with Flink, only with Hadoop. A call to clear cache files certainly makes sense though.

**Comment by StephanEwen** [comment]
A call to clear cache files does not hurt, but let's fix the MultipleProgramsTest base to produce fresh ExecutionEnvironments in its factory, rather than repeatedly handing out the same one. That is a good fix anyways.

**Comment by sachingoel0101** [comment]
Was there a specific reason to not generate fresh environments in the first place? Or was it just to minimize object creations?
Here's what I propose though: Since there is already a `clearSinks` argument to `createProgramPlan`, we can use that as an indicator that the cache file list has to be cleared too, since it indicates a new Execution.
Further, instead of throwing an exception in case a `name` is re-registered, we check if the `filePath` is actually the same. If not, then we throw an exception, otherwise just silently ignore it.

**Comment by zentol** [comment]
using clearsinks would cause the above example with collect() to fail, since this clears sinks aswell. (the sinks are only not cleared when getExecutionPlan is called, it has nothing to do with a new execution).

just checking the filepath wouldn't work in my case, i distribute a folder that resides in the same location whose content varies.

**Comment by sachingoel0101** [comment]
Ah yes, you're right. We cannot use `clearSinks`.
To answer the second part, the folder will still be added. It is only at runtime that all the directories and files inside a folder are recursively copied. So, just adding the folder once should work.

**Comment by StephanEwen** [comment]
I think the reason to not create a new environment every time was simply that it was easier to write that way and it never hurt before. You can run multiple programs on the same environment after all.

For tests, it is cleaner, though, to have a fresh one, as otherwise you may "inherit" configuration from a previous test (as is the case with the registered cache files).

**Comment by sachingoel0101** [comment]
Okay. For now, I have modified all Test environments which were using a context factory, except for the `PreviewPlanEnvironment` which cannot be done as the test depends on the environment being shared.

**Comment by sachingoel0101** [comment]
It turns out the `JavaProgramTestBase` accesses the shared environment's execution result. However, it is used nowhere. I have removed the unused code and modified all Test environment factories to always return a new Environment.

**Comment by StephanEwen** [comment]
So, this is now removing some safeguard checks in the test to make this work. That does not seem quite right. Why not keep the environment and keep access to the latest execution result?

**Comment by sachingoel0101** [comment]
To access the last execution result, the environment needs to be shared. And since we're creating a new execution environment in the program, it wouldn't work.
I'm not sure if the assert for last execution result not being null is useful. If the program succeeded, shouldn't this be always *not null*?

**Comment by StephanEwen** [comment]
Yes, if you read the message of the checks you removes, it is precisely to figure that out: Whether a program actually triggered execution.

We've build a kick-ass distributed system here. I am quite sure we can a reference to some field into another class, if we want...

**Comment by sachingoel0101** [comment]
Okay, I figured out a way to share the environments. :)
Let me know if this is a valid approach.
Waiting for travis to pass.

**Comment by sachingoel0101** [comment]
Travis passes. :)
I asked on the dev list about the two small changes in flink-gelly. @vasia

**Comment by StephanEwen** [comment]
I do not quite understand the idea behind this pull request. It adds a public `setAsShared()` method to the core `ExecutionEnvironment` which is only relevant for tests.

Can you not simply change the test base such that the TestContextFactory creates a new Environment every time and remembers that as the last environment? Do some tests assume shared environments?

**Comment by sachingoel0101** [comment]
Yes, that's perfectly doable. I actually did that initially. The only reason to add it to the `ExecutionEnvironment` was to remove that little bit of code duplication in `getLastJobExecutionResult`. 
I guess we should keep it restricted to test environments only. Apologies.

**Comment by sachingoel0101** [comment]
@StephanEwen, this should be mergeable now.
I've separated the Gelly change as a second commit.

**Comment by StephanEwen** [comment]
I think this looks good. Will merge this...

**Comment by sachingoel0101** [comment]
Okay. Great. :)

**Pull request closed without merging**
