### PR TITLE
[FLINK-5710] Add ProcTime() function to indicate StreamSQL

### PR DESCRIPTION
**Pull request by huawei-flink**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by fhueske** [comment]
Thanks for reopening the PR! 
I made a few comments on #3271 before and after it was closed that should be addressed.

Thanks, Fabian

**Comment by huawei-flink** [comment]
@fhueske I've addressed most of the points, however there is a thing that is not clear to me yet. So far, the procTime() function generates a timestamp. My understanding is that this is not correct, and it should be something else. could it be a default timestamp (e.g. epoch)? the actual timestamp normalized to the second? what is the best option in your opinion?

**Comment by fhueske** [comment]
Hi @huawei-flink,

thanks for the update! The changes are now pretty much aligned with #3252. I'm in the process of merging #3252 (running last tests). It would be great if you could rebase your changes on top of the master once #3252 has been merged.

In order to test the feature, you can integrate `proctime()` into the `LogicalWindowAggregateRule` and extend the `WindowAggregateTest` for processing time tumbling windows.

Thanks, Fabian

**Comment by fhueske** [comment]
FYI: PR #3252 was just merged.

**Comment by haohui** [comment]
FYI: #3370 is the commit we use internally for this feature. Please feel free to take it if it helps implementing this PR.

**Comment by fhueske** [comment]
Hi @huawei-flink, do you plan to follow up on this PR?
Otherwise, I'd merge #3370 after adding a test.

Thanks, Fabian

**Comment by huawei-flink** [comment]
Hi Fabian,

I will follow up in the next days, probably early next week. is it ok?

Stefano

**Comment by huawei-flink** [comment]
I managed to merge the changes from PR #3370 into my branch after rebase, and the test works. I will push the code later today. sorry if I am a little latent, but I am travelling and connectivity is sometimes a problem.

**Comment by fhueske** [comment]
That would be great @huawei-flink! There are a few contributions waiting for this addition.
Thank you!

**Comment by fhueske** [comment]
Hi, it looks like something went wrong when updating the PR. 
Can you rebase your changes on the latest master?

Thanks

**Comment by fhueske** [comment]
Hi @huawei-flink, 
as I said before, there are a few contributions waiting for this patch. 
I decided to move one and merge PR #3370.

Thanks a again for working on this and sorry for the inconvenience,
Fabian

**Comment by huawei-flink** [comment]
@fhueske no problem, I understand. It was bad timing, as I was on the run for more than two weeks, with little time to follow this. We'll  contribute on other issues.

**Comment by fhueske** [comment]
Thanks @huawei-flink 
Looking forward to your contributions!

**Pull request closed without merging**
