### PR TITLE
[FLINK-14689]Add catalog related commands support in SQL Parser

### PR DESCRIPTION
**Pull request by zjuwangg**
## What is the purpose of the change
Add catalog related commands support in SQL Parser :

- SHOW CATALOGS
- DESCRIBE CATALOG catalogName
- USE CATALOG catalogName
The PR is only about parser related changes to support catalog related commands and Hooking up with table env will come later.

## Brief change log
  - [aacc11](https://github.com/apache/flink/pull/10149/commits/aacc11c30aa8cae9389ebf2a43782fa7cb149158)Add show catalogs support in SQL Parser

  - [2b472b](https://github.com/apache/flink/pull/10149/commits/2b472bee6a0a8677ca30cd82c753ba9d0b80411e)Add describe catalog syntax in SQL Parser
  - [a746f79](https://github.com/apache/flink/pull/10149/commits/a746f791dab3a4d7cfda8de3d4ad5a62fd45a44d)Add use catalog syntax in Sql Parser

## Verifying this change

This change added tests and can be verified as follows:
  - *FlinkSqlParserImplTest#testShowCatalogs*
  - *FlinkSqlParserImplTest#testDescribeCatalog*
  - *FlinkSqlParserImplTest#testUseCatalog*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: ( no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by zjuwangg** [comment]
cc @xuefuz @bowenli86 @lirui-apache  to have a review

**Comment by zjuwangg** [comment]
> I'm not very familiar with sql parser, I wonder how the parsed command is connected to TableEnvironment?
> 
> side note on the ticket title: these are just commands, not DDLs

addressed

**Comment by zjuwangg** [comment]
> Thanks for the contribution. The PR looks good to me. To clarify, the PR is only about parser related changes to support catalog related commands and Hooking up with table env will come later.
> 
> It would be good to clarify this in the PR description area.

Addressed

**Comment by bowenli86** [comment]
LGTM, merging.

@zjuwangg just a friendly reminder that, please add component tag to the commit message. E.g. 
this one should be `[FLINK-14689][table] Add catalog related commands support in SQL Parser`

**Pull request closed without merging**
