### PR TITLE
[FLINK-5608] [webfrontend] Cancel button stays visible in narrow windows

### PR DESCRIPTION
**Pull request by rehevkor5**
- Most importantly, the Cancel button has been changed to float
right, and will only wrap downward if pushed out by the job name
- Also combined the job name and job id into a single horizontal
element, reducing the overall horizontal space taken by the main
navbar components in the job view, making the main navbar components
less likely to wrap downward and be overlapped by the secondary navbar.
- Compiled code has been rebuilt

Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [ ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by uce** [comment]
Thanks for the PR. I also sometimes had the bad experience while testing that the cancel button was not visible. This change definitely solves it. I tested it and it works as expected. I made some screenshots and would love some feedback from other contributors before changing this.

## Wide

Current:
screen shot 2017-01-24 at 09 49 24

This PR:
screen shot 2017-01-24 at 09 49 37

## Narrow

Current:
screen shot 2017-01-24 at 09 49 44

This PR:
screen shot 2017-01-24 at 09 49 52

**Comment by zentol** [comment]
How come the state of tasks is no longer shown?

**Comment by kl0u** [comment]
The screenshots look good! My only concern is @zentol 's comment.

**Comment by uce** [comment]
Good point. @rehevkor5 is it possible to only hide the color boxes when the browser window is very narrow?

**Comment by rehevkor5** [comment]
Thanks @uce that's helpful! Didn't think of putting screenshots in the PR.

@zentol The global job state counts didn't seem like the most important thing to show when the browser is narrow, given that this view is about a particular job. So, I added these CSS classes to it ".hidden-xs .hidden-sm .hidden-md" the behavior of which is described on http://getbootstrap.com/css/#responsive-utilities I am not sure what width @uce used for the "wide" screenshots, but it probably was less than 1200px, otherwise it would show up. I can remove the ".hidden-md" class if you want it to show up in the 992px to 1200px range, too... however it does make it more likely for the other more job-specific elements (start/end, duration) to wrap & get lost. Perhaps it would be a good idea to reorder the elements? Put start/end & duration first, and overall job stats last so that it's the first one to wrap? Let me know if you have a preference.

**Comment by rehevkor5** [comment]
@zentol I updated the commit: the overall job status count is now displayed in medium-width (but not small or below), and I move the job status count to the right of job start/end & duration.

Also, I applied the float-right fix to the "Stop" button, which I didn't notice before.

You can see that the fix isn't perfect when the job name is long, but it's still better than what it was. Screenshots from Chrome 55.0.2883.95, controlling window width in the dev tool.

1200px:


1128px (you can see the top navbar wrapping down & peeking out from behind the secondary navbar:


1020px (back to normal because left navbar is collapsed):


992px (wrapping again):


991px:

**Comment by StephanEwen** [comment]
I think this looks nice...

+1

**Comment by uce** [comment]
Thanks for addressing my comments. Looks very good now. I'm going ahead and merging this.

**Pull request closed without merging**
