### PR TITLE
[FLINK-2218] Web client cannot distinguesh between Flink options and program arguments

### PR DESCRIPTION
**Pull request by mjsax**
added new input fields 'options' to WebClient
adapted WebClient-to-JobManager job submission logic
updated documentation (including new screenshots)
(some additional minor cleanup in launch.html and program.js)

### CODE REVIEW

**Comment by rmetzger** [comment]
Are there any other possible options for the options field except for the parallelism?
I think users might be confused how the options and arguments differ.

**Comment by mjsax** [comment]
Right now, there is only `-c` that must be used if no Manifest (program-class or Main-Class argument) is given. We can also clarify via tooltips or help-popup, that options are "Flink parameters" and arguments go straight to the user program. As an alternative we could also rename both to "Flink Options" and "Program Arguments" to make the difference clearer. I was just using both terms because CLI uses them too.

**Comment by chiwanpark** [comment]
+1 for renaming. I confused the difference between the options and arguments.

**Comment by mjsax** [comment]
Btw: CliFontend support the follows options: -c / --class , -m / --jobmanager , -p / -- paralleslism

To have the same options, we might want to extend CliFontend for those. What do you think? Furthermore, WebClient parses options -c and -p in an own code path. This results in code duplication and manual synchronization of options in CliFrontend and WebClient. We should reuse CliFrontend code in WebClient (if possible). What do you think?

**Comment by StephanEwen** [comment]
Yes, would be great if we could reuse CLI code., agreed...

**Comment by mjsax** [comment]
Just updated this PR:
  - renamed "Options" to "Flink Options" and "Arguments" to "Program Arguments" in WebUI
  - removed redundant code and integrated CliFrontend

**Comment by mjsax** [comment]
Any news on this PR?

**Comment by aljoscha** [comment]
in web_client.md you still have "Options" and "Arguments" (if I'm not mistaken).

Does anyone have objections to merging this after that is fixed?

**Comment by mxm** [comment]
+1 for merging it!

**Comment by mjsax** [comment]
You are right. I just updated it.
What about the failing YARN test. Is there already a JIRA for it? https://travis-ci.org/apache/flink/builds/72019686

**Comment by mxm** [comment]
This only occurs with your changes, right? Then let's first fix the issue of the failing tests before merging.

**Comment by mjsax** [comment]
I don't know exactly. My changes should not influence YARN component (as fas as I can tell). YARN test have been instable a lot -- I would guess, it is a general issue.

**Comment by mxm** [comment]
The yarn tests build fine on my machine with your branch. Seems to be a general issue within the YARN tests.

**Comment by mjsax** [comment]
Ok. So this PR can be merged, I guess. I will open a JIRA for the failing test.

**Comment by mxm** [comment]
Yes, please open a JIRA. Merging.

**Pull request closed without merging**
