### PR TITLE
[FLINK-32747][table] Fix ddl operation for catalog which is loaded from CatalogStore

### PR DESCRIPTION
**Pull request by FangYongs**
## What is the purpose of the change

Currently `CatalogManager` can load catalog from `CatalogStore`, but we cannot perform ddl for the loaded catalog. This pr aims to support these operations.

## Brief change log
  - Add catalog loaded from `CatalogStore` to `catalogs` in `CatalogManager`
  - Get catalog from method `getCatalog` instead of `catalogs.get` for operations such as ddl and list tables/views

## Verifying this change

This change added tests and can be verified as follows:

  - Added test case `CatalogManagerTest.testExistingCatalogInStore`

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no) no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no) no
  - The serializers: (yes / no / don't know) no
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know) no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know) no
  - The S3 file system connector: (yes / no / don't know) no

## Documentation

  - Does this pull request introduce a new feature? (yes / no) no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by hackergin** [comment]
Thank you for addressing this issue.

Over looks good to me.  Only one minor comment.

Could we incorporate a test case into the `testCatalogStore`? This would involve verifying that after invoking the getCatalog method, the Catalog instance is properly stored in catalogs (initialized catalog).  WDYT ?

**Comment by hackergin** [comment]
I believe it is a serious issue that should be included in version 1.18 too.  

cc @leonardBang

**Comment by FangYongs** [comment]
Thanks @hackergin and @leonardBang , I have updated this PR

**Review by leonardBang — APPROVED** [review]
Thanks @FangYongs for the fix, LGTM. You can try to merge by yourself.

**Comment by FangYongs** [comment]
@leonardBang OK, thanks

**Pull request merged**
