### PR TITLE
[FLINK-9992][tests] Fix FsStorageLocationReferenceTest#testEncodeAndDecode by adding retries to generate a valid path

### PR DESCRIPTION
**Pull request by dianfu**
## What is the purpose of the change

*Not all the characters could be used in the hostname: https://stackoverflow.com/questions/28568188/java-net-uri-get-host-with-underscores. For example, underscores could not be used in the hostname. Currently, FsStorageLocationReferenceTest#testEncodeAndDecode will generate the hostname randomly and it may happen that it generates a character which is not supported. This PR fixes this problem by adding retries to generate a valid path*

## Brief change log

  - *Add retries to generate a valid path in FsStorageLocationReferenceTest.randomPath*

## Verifying this change

This change is a trivial rework without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by dianfu** [comment]
cc @StephanEwen

**Comment by kezhuw** [comment]
@dianfu How about `StringUtils#generateRandomAlphanumericString` or its length-varying variant ? If the generated url is invalid, it would be better to generate a valid url. Retrying 5 times does not improve test stability that much.

**Comment by dianfu** [comment]
@kezhuw Thanks for your comments. 
- Regarding to "retrying 5 times", I think that's enough considering the frequency of this issue(it occurs two times in the last two weeks). 
- Regarding to use **generateRandomAlphanumericString** instead of **getRandomString**, I'm fine with this. However, it depends on the test purpose of this test case. For example, the generated string of **generateRandomAlphanumericString** only contains characters and digit, I'm not sure if this is what we want for this test case FsStorageLocationReferenceTest. What's your thought? @StephanEwen

**Comment by StephanEwen** [comment]
Thanks for fixing this instability.

Some comments from my side:
  - It would be nice to have non-alphanumeric characters.
  - The retries are okay, but we could also have a list of forbidden chars (like underscore, colon, whitespace) that we avoid in the random string generation.
  - If you want to stick with re-tries, I would suggest to make it a while loop until you have a valid string. The number 5 for retries seems very arbitrary.

Other note: The test is missing the ':' between host and port, so it never has a port but counts the number into the hostname.
Would be nice to fix that as well.

**Comment by dianfu** [comment]
@StephanEwen Thanks a lot for the review. I have updated the PR with the following changes:
- Add the missing the ':' between host and port
- Retry in a while loop until got a valid string. I prefer this option because I'm not confident that excluding "underscore, colon, whitespace" is enough. Considering that this is only used in test case and I think that retry should be enough.

**Comment by StephanEwen** [comment]
+1 to merge this

**Comment by dianfu** [comment]
@StephanEwen Thanks for the review. Merging...

**Pull request closed without merging**
