### PR TITLE
[FLINK-1942][gelly] GSA Iteration Configuration

### PR DESCRIPTION
**Pull request by andralungu**

### CODE REVIEW

**Comment by vasia** [comment]
This looks good in general. The only issue we should consider is whether having one IterationConfiguration type for both vertex-centric and GAS (and probably other iteration models we might add in the future) is a good idea. There are some options that all iteration configurations will share, like name and parallelism, but there are also many model-specific settings, like udf-specific broadcast sets and the options that #537 will introduce. Any thoughts on this?

**Comment by andralungu** [comment]
Hi @vasia, 

The alternatives to having a single config class for all types of iterations are:
- having two separate classes in spargel and in gsa = massive duplication of code
- having an InterationConfiguration abstract class that VertexCentricIterationConfiguration and GatherSumApplyIterationConfiguration will inherit. 

I would personally go for the second approach! What do you think?

**Comment by vasia** [comment]
Yap, that's what I had in mind! Only the class names are a bit too long. Maybe VertexCentricConfiguration and GSAConfiguration? Or something similar?

**Comment by andralungu** [comment]
PR updated.

**Comment by vasia** [comment]
This looks good! Thanks for the update @andralungu!
Will merge :)

**Pull request closed without merging**
