### PR TITLE
FLINK-2523: Makes the task cancellation interval configurable. 

### PR DESCRIPTION
**Pull request by kl0u**
This PR is rebased on top of https://github.com/apache/flink/pull/1583 . Please review that first.

### CODE REVIEW

**Comment by kl0u** [comment]
Please review. 
IMPORTANT NOTE: This PR is rebased on top of #1583 . Please review that first.

**Comment by kl0u** [comment]
Just rebased. Please review this PR.

**Comment by tillrohrmann** [comment]
Thanks for your contribution @kl0u. Changes for the task cancellation interval look good. 

Maybe it would be good to add a test case which makes sure that the `TaskCanceler` really cancels an `Invokable` every n seconds.

**Comment by kl0u** [comment]
@tillrohrmann @aljoscha @StephanEwen I just rebased on the current master.
It passes on my travis.

This PR is rebased on top of https://github.com/apache/flink/pull/1583.

Please review.

**Comment by zentol** [comment]
will merge this today.

**Comment by rmetzger** [comment]
Thank you. The changes in b75fd3f look good!

**Comment by kl0u** [comment]
Thanks a lot! I will rebase in a bit!

**Comment by rmetzger** [comment]
You don't need to rebase. Chesnay did that already.

**Comment by kl0u** [comment]
Thanks a lot @zentol and @rmetzger

**Pull request closed without merging**
