### PR TITLE
[FLINK-5831] [webui] order, search and filter metrics

### PR DESCRIPTION
**Pull request by nellboy**
Metrics are now ordered, and searchable when displaying which metrics graphs to display in the web ui.
screen shot 2017-02-20 at 16 09 58

### CODE REVIEW

**Comment by rmetzger** [comment]
Thank you for opening a pull request addressing the issue.

I know it is out of scope of the JIRA, but since you are working on it already, I was wondering if we can improve the optics of the metric selector dropdown a bit.
I think it would look much nicer, if the search text field spans the entire width of the box, and if the selectable entries are aligned on the left.
What do you think?

**Comment by nellboy** [comment]
Ok,  this has been updated now. 
screen shot 2017-02-21 at 11 02 41

**Comment by rmetzger** [comment]
Cool, very nice!

**Comment by greghogan** [comment]
@nellboy please rebase to master.

**Comment by greghogan** [comment]
@nellboy and also thanks for this contribution! Merging ...

**Pull request closed without merging**
