### PR TITLE
[FLINK-10203]Support truncate method for old Hadoop versions in HadoopRecoverableFsDataOutputStream

### PR DESCRIPTION
**Pull request by art4ul**
## What is the purpose of the change

The new StreamingFileSink ( introduced in 1.6 Flink version ) use HadoopRecoverableFsDataOutputStream wrapper to write data in HDFS.

HadoopRecoverableFsDataOutputStream is a wrapper for FSDataOutputStream to have an ability to restore from the certain point of file after failure and continue to write data. To achieve this recover functionality the HadoopRecoverableFsDataOutputStream use "truncate" method which was introduced only in Hadoop 2.7.

Unfortunately, there are a few official Hadoop distributives which latest version still use Hadoop 2.6 (These distributives: Cloudera, Pivotal HD ). As the result, Flinks Hadoop connector can't work with this distributives.

Flink declares that supported Hadoop from version 2.4.0 upwards (https://ci.apache.org/projects/flink/flink-docs-release-1.6/start/building.html#hadoop-versions)

I guess we should emulate the functionality of "truncate" method for older Hadoop versions.
The fix of this issue is vital for us as Hadoop 2.6 users.

### Emulation of truncate logic for old versions of Hadoop ( 2.6 and lower):
1. Create a new file with '.truncated' extension in the same folder and write the content of the file with the required length. 
2. Remove original file.
3. Rename the truncated file using the name of the original one.

**In case of failure:**
On the first step of invocation of ‘truncate’ method it checks if the original file exists:
* If the original file exists - start the process from the beginning (point 1). 

* if original file not exists but exists the file with extension  *.truncated .

The absence of original file tells us about that truncated file was written fully and source crushed on the stage of renaming the truncated file. (I want to believe in the guarantee of atomicity of HDFS renaming operation) We can use it as a resultant file and finish the truncation process. 

## Brief change log

  - Add new abstraction Truncater
  - Add Implementation for old Hadoop version ( LegacyTruncater)
  - Add Implementation for Hadoop 2.7 and upwards

## Verifying this change

This change contains a test for LegacyTruncater. 

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: ( no)
  - The runtime per-record code paths (performance sensitive): (don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes)
  - The S3 file system connector: ( no)

## Documentation

  - Does this pull request introduce a new feature? (no, but I think it should be documented)
  - If yes, how is the feature documented? JavaDoc

### CODE REVIEW

**Comment by StephanEwen** [comment]
@art4ul Initially, we wanted to keep the new StreamingFileSink code simple and clean, that's why we decided to only with Hadoop 2.7+ for HDFS and retained the old BucketingSink, to support prior Hadoop versions.

Is it a critical issue on your side to not use the BucketingSink?

**Comment by art4ul** [comment]
@StephanEwen Yes it's critical because we need to write Parquet files .

**Comment by art4ul** [comment]
@StephanEwen I try to explain you our case: the new Streaming FileSink ideally suitable for write into parquet files and we was so exited when founded it in the new 1.6 version , because we worked on our Sink implementation in parallel . But as I mention before we use latest Cloudera 5.15 distributive based on Hadoop 2.6 and unfortunately we can't upgrade it to higher version of Hadoop.

**Comment by StephanEwen** [comment]
I see, that is a fair reason. There are parallel efforts to add Parquet support to the old BucketingSink, but I see the point.

Before going into a deep review,  can you update the description with how exactly the legacy truncater should be working: what copy and rename steps it does and how it behaves under failure / repeated calls. 

Also, I would suggest to name it `Truncater` rather than `TruncateManager`. Too many managers all around already ;-)

**Comment by art4ul** [comment]
@StephanEwen I've attached the [PDF file](https://issues.apache.org/jira/secure/attachment/12937334/legacy%20truncate%20logic.pdf) with the description of legacy truncater logic to the [JIRA ticket](https://issues.apache.org/jira/browse/FLINK-10203).
Please take a look :)

**Comment by art4ul** [comment]
Hi guys! Maybe there are some comments regarding this PR? I would like to continue discussion

**Comment by StephanEwen** [comment]
We were of at the Flink Forward conference the last week, so slow progress on PRs...

In principle, the design looks fine. To double check:
  - Does HDFS permit to rename to an already existing file name (replacing that existing file)?
  - If yes, this sounds reasonable. If not, this could be an issue (need to delete the original file before rename, failure in that case means file does not exist on recovery).

There is another option to approach this:
  - The recoverable writer has the option to say if it can also "recover for resume" or only "recover for commit". "Recover for resume" leads to appending to the started file, while only supporting "recover for commit" means that a new part file would be started after recovery.
  - This version could declare itself to only "recover for commit", in which case we would never have to go back to the original file name, but only copy from the "part in progress"-file to the published file name, avoiding the above problem.
  - That would mean we need to have the "truncater" handle the "truncate existing file back" logic and "truncating rename". The legacy hadoop handler would only implement the second - truncating rename.

**Comment by art4ul** [comment]
@StephanEwen I really like your idea regarding recoverable writer with "Recover for resume" property. I found the method which you are talking about:
```boolean supportsResume()```
in [RecoverableWriterm](https://github.com/apache/flink/blob/master/flink-core/src/main/java/org/apache/flink/core/fs/RecoverableWriter.java) interface, but as far as I can see this method is not using in the Flink project. 
Using search by the whole project I found only implementation of this method, but no one invocation of the method https://github.com/apache/flink/search?q=supportsResume&unscoped_q=supportsResume

**Comment by kl0u** [comment]
Hi Artsem, you are correct that it is not used but I already have a branch
for it and there is an open Jira for that that I have assigned to myself.

**Comment by art4ul** [comment]
Hi @kl0u , maybe could you share your ticket regarding the implementation of logic to support supportsResume() method?

**Comment by kl0u** [comment]
Hi @art4ul ! There is already an open PR for that issue and it is this one:
https://github.com/apache/flink/pull/7047
you can also review it if you want so that it can get merged faster. From the name of the PR you can also find the issue number.

**Comment by JTaky** [comment]
Hey @art4ul. 
I believe you are not interested in this change anymore? If you can hear me is it ok if I try to finalize your contribution? From what I understand it is nearly done.
Thanks

**Comment by art4ul** [comment]
@JTaky Yes please

**Comment by JTaky** [comment]
sorry guys. The current pull request had quite of discrepancies with a master, it was much easier to simply push a new one.

**Comment by kl0u** [comment]
@JTaky thanks for updating the PR. Could you close this one and put a pointer here to the new PR you opened so that the next reviewer can find the discussion?

**Comment by kl0u** [comment]
Closed as there is an updated version in https://github.com/apache/flink/pull/11747

**Pull request closed without merging**
