### PR TITLE
[FLINK-8354] Add KafkaDeserializationSchema that directly uses ConsumerRecord

### PR DESCRIPTION
**Pull request by aljoscha**
This is a rebased and cleaned-up version of #6615 that only has the Consumer changes.

# What is the purpose of the change

* Add a new deserialization schema that directly uses `ConsumerRecord`, thereby exposing all available Kafka functionality.

## Brief change log

* First we do some cleanup on the Kafka code
* Then we introduce the new schema, the existing schema now implements the new schema, for backwards compatibility
* Consumers and tests are adapted to use the new schema

## Verifying this change

* This is covered by existing tests

### CODE REVIEW

**Comment by aljoscha** [comment]
cc @alexeyt820
cc @azagrebin

**Comment by aljoscha** [comment]
Merged!

**Comment by lamber-ken** [comment]
@aljoscha hi, the java file was placed at wrong package
[KafkaDeserializationSchemaWrapper.java](https://github.com/apache/flink/blob/master/flink-connectors/flink-connector-kafka-base/src/main/java/org/apache/flink/streaming/connectors/kafka/internals/KafkaDeserializationSchemaWrapper.java)

**Comment by aljoscha** [comment]
@lamber-ken How do you mean?

**Comment by lamber-ken** [comment]
@aljoscha, hi, the mismatch between KafkaDeserializationSchemaWrapper class's package name and file's location. #7902

**Comment by aljoscha** [comment]
Now I see, yes, we need to fix this.

**Pull request closed without merging**
