### PR TITLE
[FLINK-13475][hive]Reduce dependency on third-party maven repositories

### PR DESCRIPTION
**Pull request by zjuwangg**
## What is the purpose of the change

*Reduce dependency on third-party maven repositories*

## Brief change log
  - *Reduce dependency on third-party maven repositories*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by zjuwangg** [comment]
cc @lirui-apache @xuefuz to review.

**Comment by lirui-apache** [comment]
@zjuwangg Thanks for working on this. PR LGTM, but please make sure it doesn't break any test for Hive-1.2.1 as well.
BTW, how about the jms dependencies? Is it possible to avoid that too?

**Comment by zjuwangg** [comment]
> @zjuwangg Thanks for working on this. PR LGTM, but please make sure it doesn't break any test for Hive-1.2.1 as well.
> BTW, how about the jms dependencies? Is it possible to avoid that too?

Yep, I tested with profile hive-1.2.1 in my box and remove the jms dependency in the lastest commit.

**Comment by zjuwangg** [comment]
@bowenli86 @wuchong @xuefuz 
Could you have a review when you have time?

**Comment by xuefuz** [comment]
PR looks good to me. @lirui-apache , do you have additional comment?

**Pull request closed without merging**
