### PR TITLE
[FLINK-1707][WIP]Add an Affinity Propagation Library Method

### PR DESCRIPTION
**Pull request by joey001**
I just finished the initial version of AP implementation and pass some preliminary test. The input of the program include two files:
1 similarity graph : each line indicates the similarity between two vertices. if <v1, v2, simi> exists, the user is obligatory to ensure the existence of   <v2,v1, simi>. I am considering validating the graph before run the algorithm.
2 vertex preference: each line indicates the preference of each vertex.
The outputs format is : <vertexId, exemplarId>,   indicating the id of the vertex and the id of its exemplar. 

In the value of each vertex, there is a hashmap storing all the similarities, responsibilities,availabilities to all its neighbor vertex. There are updated in the vertex centric iteration.
I still do some test and verification? Any advices?

### CODE REVIEW

**Comment by andralungu** [comment]
For the test: did you have a look at the other Gelly tests(https://github.com/apache/flink/tree/master/flink-staging/flink-gelly/src/test/java/org/apache/flink/graph/test/example)? They are pretty easy to follow. 
Unless your algorithm gives non-deterministic results. Is this the case?

**Comment by andralungu** [comment]
@joey001, 

How did you rebase this? It should not normally contain everyone's commits... Right now it looks like 18 people participated in the implementation of Affinity Propagation :)

Also a common practice is to write a "PR updated" comment after adding something to your pull request. That way people will be notified and will review your changes asap. If you don't comment, you run the risk of having your PR hang in here longer ;)

**Comment by vasia** [comment]
Hey @joey001!

Are you still working on this? Let us know if you need help!

**Comment by andralungu** [comment]
Hi @vasia ,

I believe the problem @joey001 had was that in one of the test modes, he got the classical "Too few memory segments provided. You need at least 33 segments, etc". As far as I remember, @StephanEwen said there is ongoing work in that direction. We probably cannot merge anything with failing tests anyway :)

**Comment by joey001** [comment]
Hello,  i will submit a right version of AP algorithm in this ASAP. I am so occupied by two urgent papers unfortunately.  Now, I mainly have 3 questions for the work.
1,The first is how to rebase the branch, as commented by andralungu , i must merge the work in a wrong way. I am now confused by the my git. i was considering do open a brand new branch for committing?
2. The other one is "Too few memory segments provided". As @andralungu said, It sames that the problem couldn't be solved immediately?
3. In AP algorithm in the original paper, normal distributed small values are added to the weights of edges to remove degeneracies, however, the generation of normal distribution data is not supported yet. Currently, all the current test are passed, but i guess it's still a problem.

**Comment by andralungu** [comment]
For 1, I would open a fresh PR, I guess this is too messy to try to fix. 

Normally, you should:
change to master
git remote -v
pull the latest state - git pull upstream master
and then change back to your branch
git rebase master

then when pushing 

git push -f origin <branch-name>

For 3. Open the new PR and we will have a look at the current solution :)

**Comment by vasia** [comment]
Hi @joey001,

any news regarding this PR? If you have no time to work on this, that's fine! You can close the PR and someone will hopefully pick up the issue. Just let us know :)
Thank you!

**Comment by joey001** [comment]
@vasia 
It turns out that I don't have enough time and energy for this problem. I will close the PR and hope the code will at least benefit the future followers. Very nice to cooperate with you even a short period and know such a wonderful project!

**Comment by vasia** [comment]
Thanks for the fast response and your kind words :)
Glad to have collaborated with you, too!

**Pull request closed without merging**
