### PR TITLE
[FLINK-6275] [yarn] Fix unprotected access to resourceManage in YarnF…

### PR DESCRIPTION
**Pull request by zhangminglei**
…linkApplicationMasterRunner.

Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [ ] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [ ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by StephanEwen** [comment]
I think this should be done differently. The access to the resourceManager should be under the lock, but not the waiting on the termination future. Otherwise the lock is held too long.

**Comment by zhangminglei** [comment]
@StephanEwen Thanks. I might close this PR as there is a refactor to ```YarnFlinkApplicationMasterRunner ``` by combining with ```AbstractYarnFlinkApplicationMasterRunner``` in one class. See : https://issues.apache.org/jira/browse/FLINK-6351

**Comment by zentol** [comment]
@zhangminglei could you close this PR?

**Comment by zhangminglei** [comment]
@zentol Sorry. I just forgot. I close it right now.

**Pull request closed without merging**
