### PR TITLE
[FLINK-3112] Remove unused RecordModelPostPass

### PR DESCRIPTION
**Pull request by fhueske**
Class is not used and a leftover of the Record API.

### CODE REVIEW

**Comment by zentol** [comment]
@jaoki found a reference to this class in

https://github.com/apache/flink/blob/master/flink-core/src/main/java/org/apache/flink/api/common/Plan.java#L318-L319

**Comment by fhueske** [comment]
Good catch, @jaoki and thanks for making me aware of this @zentol.

`Plan` was originally implemented for the Record API. For the later DataSet API, `JavaPlan` extends `Plan` and only overrides the `getPostPassClassName()` method. I checked the code and `Plan` is nowhere instantiated, only `JavaPlan`. 

I will move the `getPostPassClassName()` from `JavaPlan` to `Plan` and remove `JavaPlan`.

**Comment by fhueske** [comment]
Going to merge this PR.

**Comment by jaoki** [comment]
@fhueske , I'm glad to make myself a bit useful to the project. :)

**Pull request closed without merging**
