### PR TITLE
[FLINK-14998] [FileSystems] Remove FileUtils#deletePathIfEmpty

### PR DESCRIPTION
**Pull request by jay-li-csck**
## What is the purpose of the change
This pull request is remove useless in Flink production code.

## Brief change log
Remove FileUtils#deletePathIfEmpty and unit test

## Verifying this change

This change is a  code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: ( no )
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? ( no)

### CODE REVIEW

**Review by Myasuka — CHANGES_REQUESTED** [review]
Thanks for creating this PR.
Please fill up the description of this PR and ensure the CI could pass.

**Comment by jay-li-csck** [comment]
@flinkbot run azure

**Comment by jay-li-csck** [comment]
@flinkbot run azure

**Comment by jay-li-csck** [comment]
@flinkbot run azure

**Comment by jay-li-csck** [comment]
hi @Myasuka  ci already pass

**Review by Myasuka — APPROVED** [review]
Thanks for the update. LGTM.

**Pull request closed without merging**
