### PR TITLE
[Flink-7218] [JobManager] ExecutionVertex.getPreferredLocationsBasedOnInputs() will always return empty

### PR DESCRIPTION
**Pull request by summerleafs**
I really like the new PR template, so i use it instead of the default one on github~

You can view, comment on, or merge this pull request online at:[https://github.com/apache/flink/pull/4369](https://github.com/apache/flink/pull/4369)

## What is the purpose of the change

The ExecutionVertex.getPreferredLocationsBasedOnInputs will always return empty, cause `sourceSlot` always be null until `ExectionVertex` has been deployed via 'Execution.deployToSlot()'. So allocate resource base on preferred location can't work correctly, we need to set the slot info for `Execution` as soon as Scheduler.scheduleTask() called successfully.

## Brief change log
- Once `Scheduler.scheduleTask()` called successfully and return a SimpleSlot, we record the slot info by new field `assignedFutureSlot` in `Execution`. `assignedFutureSlot`  will be used in `ExectionVertex. getPreferredLocationsBasedOnInputs ()` to get ExecutionVertex's preferred locations.

## Verifying this change

This change added tests and can be verified as follows:
- The test case is under ExecutionGraphSchedulingTest. testExecutionVertexGetPreferredLocationsBasedOnInputs(), i have simulated the process of the JobGraph deployment and validated the results in this test case.

## Does this pull request potentially affect one of the following parts:

- Dependencies (does it add or upgrade a dependency): **(no)**
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: **(no)**
  - The serializers: **(don't know)**
  - The runtime per-record code paths (performance sensitive): **(no)**
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: **(yes)**:

## Documentation
  - Does this pull request introduce a new feature? **(no)**

### CODE REVIEW

**Comment by StephanEwen** [comment]
Hi @summerleafs!

I think we cannot use this approach to fix this. The most important thing is that this introduces a blocking operation (`.get()` on the future) in the call, which will make the while `schedueEager()` call block. Since the ExecutionGraph runs in an actor-style context, methods must never block. Everything must be implemented with future completion functions.

**Comment by summerleafs** [comment]
@StephanEwen You are right, i think we should fix this in `Scheduler.allocateSlot`. If the `ret` from the `scheduleTask` is an SimpleSlot  then we record it in `Execution`, how do you think?

**Comment by summerleafs** [comment]
Hi @StephanEwen , i changed the code with the thinking described above. Please help me review it again. Thanks a lot.

**Comment by summerleafs** [comment]
duplicate with FLINK-7866.

**Pull request closed without merging**
