### PR TITLE
[FLINK-10565] [tests] Refactor SchedulerTestBase

### PR DESCRIPTION
**Pull request by TisonKun**
## What is the purpose of the change

Basically, current SchedulerTestBase covers Scheduler tests, which is a schedule mechanism of legacy mode. We can remove it from SchedulerTestBase. Besides, inner SchedulerTestBase there are two useful testing class TestingSlotPool and TestingSlotPoolSlotProvider. Extract them for further usage.

## Brief change log

1. Remove tests for legacy class `Scheduler` from `SchedulerTestBase`.
2. Extract `TestingSlotPool` and `TestingSlotPoolSlotProvider`. Especially for the following clean up of `Scheduler` and `Instance`.

**UPDATE** Part 2 is reverted as suggested.

## Verifying this change

This change is a trivial rework and covered by themselves.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**no**)
  - The public API, i.e., is any changed class annotated with `(Evolving)`: (**no**)
  - The serializers: (**no**)
  - The runtime per-record code paths (performance sensitive): (**no**)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (**no**)
  - The S3 file system connector: (**no**)

## Documentation

  - Does this pull request introduce a new feature? (**no**)
  - If yes, how is the feature documented? (**not applicable**)

cc @tillrohrmann @StefanRRichter

### CODE REVIEW

**Comment by StefanRRichter** [comment]
Overall, the changes look good. Why exactly did you extract the inner classes for this PR? I could not find any additional uses and it only makes the review slightly harder. If we find a use case where extraction makes sense at some point, we can extract them then. So I would suggest to revert the extraction for now and then I would merge the PR.

**Comment by TisonKun** [comment]
@StefanRRichter I do the extract because a `TestingSlotPoolSlotProvider` can be used to replace `Scheduler` used in other tests. At those places what is needed is a `SlotProvider`.
However, you are right and I should have not mix them together. I think I am a bit delirious that time. Would revert it soon.

**Comment by StefanRRichter** [comment]
Ok, then I would suggest to just split that extraction for a later time and take it stepwise. Thanks for your work!

**Comment by TisonKun** [comment]
The revert done. Thanks for your review @StefanRRichter !

**Pull request closed without merging**
