### PR TITLE
[FLINK-3869] Relax window fold generic parameters

### PR DESCRIPTION
**Pull request by aljoscha**
Before, the WindowFunction in a fold/apply could not emit a type that
was different from the accumulator type of the fold. This restriction is
unnecessary.

### CODE REVIEW

**Comment by StephanEwen** [comment]
This is an API breaking change.

Is there a way to overload the  functions to make this non-API breaking?

**Comment by aljoscha** [comment]
I thought it wasn't breaking because it only changes the generic parameters. Any existing user code should still work as before. Or does the generics change break binary compatibility?

**Comment by aljoscha** [comment]
@StephanEwen Scala won't let me have overloaded functions. I can only fix it for the Java API because there it is non-breaking. It is, however, a severe limitation for the Scala API.

**Comment by StephanEwen** [comment]
I think the API breaking changes preventer will reject this.
It is all public methods, and the signature changes (implicit parameters and context bounds are parameters in the bytecode)

**Comment by aljoscha** [comment]
So we shouldn't fix and but keep track of it for Flink 2.0?

**Comment by StephanEwen** [comment]
I would say so

**Comment by aljoscha** [comment]
Kk, I added it to our "breaking changes for Flink 2.0" umbrella ticket. Closing this.

**Pull request closed without merging**
