### PR TITLE
[FLINK-3556] [runtime] Remove false check in HA blob store configuration

### PR DESCRIPTION
**Pull request by uce**
If you use the `RocksDBStateBackend` and configure HA w/o setting the state backend to `filesystem`, restoring your job will fail, because the BLOBs are not persisted. The really ugly part is that this does not log a warning  or anything. I'm leaning towards making this a release blocker, but it can also be postponed to `1.0.1`, if that follows very soon.

### CODE REVIEW

**Comment by tillrohrmann** [comment]
Changes look good to me. Good catch @uce :-) +1 for merging.

One minor thing: We check that the configuration contains the `ZOOKEEPER_RECOVERY_PATH` and then give the configuration to the `FileSystemBlobStore`. Wouldn't it make more sense to directly pass in the value of `ZOOKEEPER_RECOVERY_PATH` or do the checking of the correctness of the value in the `FileSystemBlobStore`? If we pass the configuration, then we don't actually know, which values will be used internally. This would untie the `BlobServer` and the `FileSystemBlobStore` a bit.

**Comment by uce** [comment]
Thanks Till! The check was duplicated in `BlobServer` and `FileSystemBlobStore`. Now only config is passed and it's the responsibility of `FileSystemBlobStore` to construct itself correctly or fail.

**Comment by uce** [comment]
PS I had a local Travis build with this (1st commit), which succeeded https://travis-ci.org/uce/flink/builds/112830163 and the blob and recovery tests succeed on my local laptop with the latest commit.

**Comment by tillrohrmann** [comment]
+1 for merging

**Comment by uce** [comment]
OK, going to merge to master and release-1.0.

**Pull request closed without merging**
