### PR TITLE
[hotfix][docs] Fix the Intellij key nouns.

### PR DESCRIPTION
**Pull request by liuzhuang2017**
## What is the purpose of the change

- I think the Intellij should be changed to IntelliJ IDEA. For details, please refer to the official website https://www.jetbrains.com/idea/ and https://en.wikipedia.org/wiki/IntelliJ_IDEA.

## Brief change log

- Modify Intellij to IntelliJ IDEA.

## Verifying this change

- This change is a trivial rework / code cleanup without any test coverage.

### CODE REVIEW

**Comment by liuzhuang2017** [comment]
@flinkbot run azure

**Comment by liuzhuang2017** [comment]
@MartijnVisser , Sorry to bother you again, can you help me review this pr? Thank you.

**Comment by liuzhuang2017** [comment]
@flinkbot run azure

**Comment by liuzhuang2017** [comment]
@mbalassi ,Sorry to bother you again, can you help me review this pr? Thank you.

**Review by MartijnVisser — APPROVED** [review]
LGTM

**Comment by liuzhuang2017** [comment]
@MartijnVisser , Thank you very much for your review.

**Pull request merged**
