### PR TITLE
[FLINK-20606][connectors/hive, table sql] sql cli with hive catalog c…

### PR DESCRIPTION
**Pull request by AkisAya**
…annot create function using user classes from jar which specified by -j option

## What is the purpose of the change

fix sql cli with hive catalog behaves right when create a function using jar specified by -j option

## Brief change log

- In CatalogFunctionImpl#isGeneric(), use thread context classloader to load class

## Verifying this change

This change added tests and can be verified as follows:

  - *build a new flink dist and start the cluster*
  - *modify sql-client-defaults.yaml to add a hive catalog*
  - *start sql cli with a -j point to user jar file*
  - *use hive catalog and create a function using the udf class from user jar*
  - *create successfully*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Review by lirui-apache — APPROVED** [review]
Thanks for fixing the issue. LGTM

**Comment by wuchong** [comment]
Could you add a test to cover this problem? 
I think you can add a test in `org.apache.flink.table.client.gateway.local.LocalExecutorITCase` and create executor using `createModifiedExecutor(CATALOGS_ENVIRONMENT_FILE, clusterClient, replaceVars)` which contains Hive catalog.

**Comment by AkisAya** [comment]
> Could you add a test to cover this problem?
> I think you can add a test in `org.apache.flink.table.client.gateway.local.LocalExecutorITCase` and create executor using `createModifiedExecutor(CATALOGS_ENVIRONMENT_FILE, clusterClient, replaceVars)` which contains Hive catalog.

ok, i will try to add a test

**Comment by AkisAya** [comment]
@flinkbot run azure

**Comment by AkisAya** [comment]
@flinkbot run azure

**Review by wuchong — APPROVED** [review]
Thanks for the updating @AkisAya . LGTM.

**Pull request merged**
