### PR TITLE
[FLINK-17311][python][AZP] Add the logic of compressed in tgz before uploading artifacts

### PR DESCRIPTION
**Pull request by HuangXingBo**
## What is the purpose of the change

*This pull request will Add the logic of compressing compiled result to flink.tar.gz before uploading artifact*

## Brief change log

  - *Add the logic of compressing compiled result to flink.tar.gz before uploading artifact in build-python-wheels.yml*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by rmetzger** [comment]
@zentol It seems that ci-bot has never pushed a branch for `db62ebb` to `flink-ci/master`. Is this by design (because it checks if there's a diff between the commits, and if the push was just a rebase, it won't see a diff)?

**Comment by rmetzger** [comment]
@HuangXingBo was the force push from c94cfb4 to db62ebb just a rebase to current master?
Do you think we can merge this PR as is, or should we try to manually trigger a CI build to verify again?

**Comment by HuangXingBo** [comment]
Thanks, @rmetzger . I just rebased to current master. The logic will be only tested in corn job. And I have tested related test in my free Azure CI https://dev.azure.com/hxbks2ks/FLINK-TEST/_build/results?buildId=203&view=results. So I think we don't need to wait for CI build.

**Comment by rmetzger** [comment]
ok. Will merge

**Pull request closed without merging**
