### PR TITLE
[FLINK-14560] [runtime] The value of taskmanager.memory.size in flink-conf.yaml is set to zero will cause taskmanager not to work

### PR DESCRIPTION
**Pull request by faaronzheng**
## What is the purpose of the change
In order to fix the issue FLINK-14560

## Brief change log
ConfigurationParserUtils.java : I modify the logical in getManagedMemorySize() to obtain a correct result when TaskManagerOptions.LEGACY_MANAGED_MEMORY_SIZE is set to zero.

TaskManagerServices.java : I modify the condition in getManagedMemoryFromHeapAndManaged() to calculate the taskmanager.memory.size according to fraction  even when taskmanager.memory.size is set to zero . 

TaskManagerHeapSizeCalculationJavaBashTest.java : Add a scenario with taskmanager.memory.size equal to 0

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.
TaskManagerHeapSizeCalculationJavaBashTest.compareHeapSizeShellScriptWithJava()
NettyShuffleEnvironmentConfigurationTest.calculateHeapSizeMB()
NetworkBufferCalculationTest.calculateNetworkBufFromHeapSize()
YarnConfigurationITCase.testFlinkContainerMemory()

This change added tests and can be verified as follows:

By setting taskmanager.memory.size : 0

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): ( no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by faaronzheng** [comment]
> Thanks for opening this PR @faaronzheng. It took me a while to understand the underlying problem. Instead of defining `0` to be the "take the fraction" value, I would suggest to remove the default value from `LEGACY_MANAGED_MEMORY_SIZE`. If the user should set this value to `0`, then it should fail as it represents an invalid system configuration.

 LEGACY_MANAGED_MEMORY_SIZE is already removed the default value, I think it is okay to remove the default value from MANAGED_MEMORY_SIZE in release-1.9 and branch

**Comment by tillrohrmann** [comment]
@faaronzheng I think `LEGACY_MANAGED_MEMORY_SIZE` still has a default value: https://github.com/apache/flink/blob/master/flink-core/src/main/java/org/apache/flink/configuration/TaskManagerOptions.java#L195.

I would propose the following: Let's remove the default value from `LEGACY_MANAGED_MEMORY_SIZE` in `master` and from `MANAGED_MEMORY_SIZE` in `release-1.9`. Then let's update the code to simply check whether `(LEGACY_)MANAGED_MEMORY_SIZE` has been set or not instead of comparing the default values with each other. Could you update this PR accordingly and open another one against `release-1.9`?

**Comment by faaronzheng** [comment]
> @faaronzheng I think `LEGACY_MANAGED_MEMORY_SIZE` still has a default value: https://github.com/apache/flink/blob/master/flink-core/src/main/java/org/apache/flink/configuration/TaskManagerOptions.java#L195.
> 
> I would propose the following: Let's remove the default value from `LEGACY_MANAGED_MEMORY_SIZE` in `master` and from `MANAGED_MEMORY_SIZE` in `release-1.9`. Then let's update the code to simply check whether `(LEGACY_)MANAGED_MEMORY_SIZE` has been set or not instead of comparing the default values with each other. Could you update this PR accordingly and open another one against `release-1.9`?

Surely

**Comment by tillrohrmann** [comment]
Let me know once you've updated the PR @faaronzheng.

**Comment by faaronzheng** [comment]
> * @flinkbot run travis

@flinkbot run travis

**Pull request closed without merging**
