### PR TITLE
[FLINK-4212] [scripts] Lock PID file when starting daemons

### PR DESCRIPTION
**Pull request by greghogan**

### CODE REVIEW

**Comment by StephanEwen** [comment]
Is the `flock` command available by default on the common UNIX-style OSs?

Ubuntu has it by default, what about MacOS?

**Comment by greghogan** [comment]
Looks like it is available in Linux and BSD but not MacOS. We can skip locking if `flock` is not available. The race condition only manifests when starting duplicate managers on the same system in parallel.

**Comment by StephanEwen** [comment]
This works on my machine (Ubuntu Linux 14.04)

Can someone verify it for MacOS? (@uce, @aljoscha, @tillrohrmann)?

**Comment by uce** [comment]
Checked it out locally and all processes start up as expected. @greghogan I think it's good to merge.

**Comment by greghogan** [comment]
Merging this ...

**Pull request closed without merging**
