### PR TITLE
[FLINK-7864] [DataStream API] Support side-outputs in CoProcessFunction

### PR DESCRIPTION
**Pull request by bowenli86**
## What is the purpose of the change

Support side-outputs in CoProcessFunction

## Brief change log

- Support side-outputs in CoProcessFunction
- Added integration tests

## Verifying this change

This change added tests and can be verified as follows:

  - *Added integration tests for CoProcessFunction*

## Does this pull request potentially affect one of the following parts:

  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes)

## Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (docs)

### CODE REVIEW

**Comment by aljoscha** [comment]
Thanks! This looks good. 👍 

There is some unrelated changes in the contexts, where the `timerService()` and `timeDomain()` methods are shifted around. I'll undo those.

**Comment by aljoscha** [comment]
I merged this. Could you please close the PR?

**Comment by bowenli86** [comment]
Those are actually intentional to reorder the methods so they conform to the order in the interface. Well, it's fine to not merge those

**Comment by aljoscha** [comment]
Ok, sorry about that. If you want you can create a hot fix commit and ping me in the PR for me to merge it.

**Comment by bowenli86** [comment]
Sounds good. Thanks!

**Pull request closed without merging**
