### PR TITLE
[FLINK-19511] Rename the 'SinkTransformation' to 'LegacySinkTransformation'

### PR DESCRIPTION
**Pull request by guoweiM**
## What is the purpose of the change

We use the 'SinkTransformation' to represent the new sink API after the FLIP-143. So this commit renames the 'SinkTransformation' to 'LegacySinkTransformation'.
## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by gaoyunhaii** [comment]
Very thanks @guoweiM for opening this PR! It seems that are still some references to `SinkTransformation` in the method comments:

`PartitionTransformation`: line 79
`LegacySinkTransformation` line 40, 81, 93

after the modification.

**Comment by guoweiM** [comment]
Thanks @gaoyunhaii for your care. I will rename references in the `LegacySinkTransformation`. But for the `PartitionTransformation`:line79 I think it might be typo. Maybe we should use 'Transformation' only.

**Comment by kl0u** [comment]
Yes @guoweiM and @gaoyunhaii the `PartitionTransformation` javadoc is wrong and it is copied (I think) in many transformations. Actually I refactor it as part of this PR https://github.com/apache/flink/pull/13556 so feel free to leave it as is here so that we avoid conflicts :)

**Comment by kl0u** [comment]
Hi @guoweiM ! Could you rebase this PR on the current master and then I will merge. Feel free of course to squash the commits here into a single commit.

**Comment by guoweiM** [comment]
ok np.

**Comment by guoweiM** [comment]
done.

**Comment by guoweiM** [comment]
@flinkbot run azure

**Review by kl0u — APPROVED** [review]
Thanks for the work @guoweiM ! Merging this!

**Pull request closed without merging**
