### PR TITLE
[FLINK-4271] [DataStreamAPI] Enable CoGroupedStreams and JoinedStreams to set parallellism

### PR DESCRIPTION
**Pull request by wuchong**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

The CoGroupStream will construct the following graph. 

```
source -> MAP ---
                            |->  WindowOp -> Sink
source -> MAP ---
```

By now , the MAP and WindowOp can not set parallelism.  We can keep the MAP has same parallelism as previous operator (chaining). And we can change {{CoGroupedStreams.apply}} to return a  {{SingleOutputStreamOperator}} instead of {{DataStream}}, so that we can set WindowOp's parallelism.  The same thing has be done to {{JoinedStream}}.

So that we can do the following things:

```
DataStream<T> result = one.coGroup(two)
     .where(new MyFirstKeySelector())
     .equalTo(new MyFirstKeySelector())
     .window(TumblingEventTimeWindows.of(Time.of(5, TimeUnit.SECONDS)))
     .apply(new MyCoGroupFunction())
     .setParallelism(10)
     .name("MyCoGroupWindow");
```

### CODE REVIEW

**Comment by wuchong** [comment]
The CI failed because of japicmp, as we changed the public API. 

Have no idea how to fix this...

**Comment by StephanEwen** [comment]
@wuchong The CI fails because this change breaks backwards compatibility. I understand though that this is a pretty critical change and may actually warrant to break the backwards compatibility.

Let me think what we can do there...

**Comment by aljoscha** [comment]
@StephanEwen I think technically it doesn't break the API because `SingleOutputStreamOperator` is a subclass of `DataStream`, right? (It might break binary compatibility though, because the signature of the method changes) It might only be the checker that is to sensitive.

**Comment by StephanEwen** [comment]
I think it breaks binary compatibility, not source compatibility.
The specific return type is part of the method signature used by the JVM for linking.

**Comment by wuchong** [comment]
I agree with @aljoscha . Can we reduce the checker's sensitivity to pass this change ? How do we do when we need to break compatibility?

**Comment by StephanEwen** [comment]
We should not change the checker sensitivity. It is very important that it checks for binary compatibility - that was the promise of Flink 1.0.

If we want to break compatibility, we can define an exception rule to the checker.

I think we should explore other options before. We can specify the parallelism between `window(...)` and `apply(...)` without breaking the compatibility. It would be a bit less nice, because it is different from how the other functions do it, but it allows us to maintain the promise of compatibility.

What do you think about that?

**Comment by wuchong** [comment]
I think, specify parallelism between `window(...)` and `apply(...)` is not nice. We not just need `setParallelism` function but also `name`, `uid`, `slotSharingGroup` and many other functions in `SingleOutputStreamOperator`. If we copy these to `WithWindow`, it will be very duplicate.

**Comment by StephanEwen** [comment]
True, this may warrant a case of breaking APIs.

**Comment by wuchong** [comment]
Hi @aljoscha @tillrohrmann , what do you think about this?

**Comment by aljoscha** [comment]
As I said, I think it would be very good to change the return type to `SingleOutputStreamOperator`. However, breaking binary compatibility should also not be taken lightly.

**Comment by zentol** [comment]
I'm not so sure about breaking compatibility. Let's keep in mind that users can work around this by casting the returned `DataStream` to a `SingleOutputStreamOperator`.

**Comment by StephanEwen** [comment]
@zentol I think that works only in theory. In practice, probably no user is going to realize that this trick is possible (even if we put it into the JavaDocs). It also seems pretty mean thing to force a user to do.

I am quite torn at the moment whether this is an incident to break the API - I am leaning towards yes.

**Comment by StephanEwen** [comment]
I am at the point where I would suggest to actually break the API and apply a proper fix. Tough step, but the alternatives seem even worse.

I wrote a [discuss] mail to the dev list, let's see if someone objects, otherwise I would merge this in the next days (adding the japicmp exception rule).

**Comment by StephanEwen** [comment]
I just thought of a different trick: We could add a second variant of the `apply(..)` function (for example called `with(...)` as in the DataSet API) and have the proper return type there (calling apply() and cast).

We can then immediately deprecate the `with()` function to indicate that it is a temporary workaround and is to be replaced by `apply(...)` in Flink 2.0.

**Comment by aljoscha** [comment]
Wouldn't this suffer from the same problem as the "casting solution"? People would use `apply` and then wonder why there is no `setParallelism`, not bothering to read the Javadoc to find out that there is also `with`.

**Comment by StephanEwen** [comment]
We could "deprecate" the `apply()` method and redirect to `with(...)`. That would be easier to find than a comment about casting.

**Comment by StephanEwen** [comment]
I would like to come to an agreement with everyone how to proceed.

From the discussion on the mailing list, I see that quite some people are opposed to breaking the compatibility unless we name the next release 2.0. Since that has not been decided upon, we need a different fix.

How about we introduce (and immediately deprecate) the `with(...)` method. We should describe there that this is a temporary workaround. The `with(...) method only differs in the return type and calls `apply(...)`, casting the returned value.

Would everyone be okay with that?

**Comment by wuchong** [comment]
I'm ok with the `with(...)` approach. In addition, we should create a JIRA under [FLINK-3957]
"Breaking API changes for Flink 2.0", to keep track of deprecating  and changing the `apply` method return type.

**Comment by tillrohrmann** [comment]
+1 for this approach.

**Comment by rmetzger** [comment]
I'm also okay with `with()`

**Comment by greghogan** [comment]
Are there strong reasons to use `apply` for `DataStream` and `with` for `DataSet`? Could we deprecate the `apply` so that users having switched to `with` will not lose API compatibility with 2.0?

**Comment by tillrohrmann** [comment]
But then we would have to change it for all windowed operators.

Furthermore the advantage of `apply` is that it is consistent with the Scala API and Scala's `apply` function treatment where you don't have to specify the method name explicitly.

**Comment by StephanEwen** [comment]
It seems we are go for the `with(...)` approach.
Pending decision is whether we want `with` to be the long-run solution, or stay with `apply`.

The reason why `DataStream` has `apply()` and `DataSet` has `with()` is that different people wrote the API functions and everyone has their favorite name and style that they stick to ;-)

I agree that consistency should be key in the future. The `DataStream` API has more traction right now, and should long-term subsume the DataSet API, so I have a slight bias to keep the DataStream style for now (many people will not even use the `with(...)` variant because they don't set individual parallelism).

**Comment by StephanEwen** [comment]
@wuchong Do you want to update this PR with the `with(...)` approach and file the JIRA for Flink 2.0 breaking changes?

**Comment by wuchong** [comment]
Yes, I would like.

**Comment by wuchong** [comment]
Hi @StephanEwen @aljoscha , I have updated this PR with the `with(...)` approach , could you have a look at it?

And log FLINK-4503 JIRA for Flink 2.0 breaking changes.

**Comment by StephanEwen** [comment]
The methods look good. They need a `@PublicEvolving` annotation and I think we should mark them with `@Deprecated` and comment that they are a temporary workaround while the `apply()` method has the wrong return type.

**Comment by wuchong** [comment]
Hi @StephanEwen , comments addressed.  

I'm not sure whether the comments are correct. Let me know if I'm wrong.

**Comment by wuchong** [comment]
Hi @aljoscha  @StephanEwen , this issue has been blocked for some days. It would be great, if you can  have a look  again ?

**Comment by StephanEwen** [comment]
Looks good, thanks!

Merging this...

**Pull request closed without merging**
