### PR TITLE
[FLINK-27006][Table SQL / API] Support CharSingleValueAggFunction

### PR DESCRIPTION
**Pull request by luoyuxia**
## What is the purpose of the change
To support `CharSingleValueAggFunction` in case of `CHAR` type. 

## Brief change log
Add `CharSingleValueAggFunction ` for case `CHAR`.

## Verifying this change
Added test in `AggregateITCase.scala#testGroupBySingleValue`

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented?  NA

### CODE REVIEW

**Comment by luoyuxia** [comment]
@JingsongLi Could you please help review?

**Comment by luoyuxia** [comment]
@flinkbot run azure

**Review by wuchong — APPROVED** [review]
Thanks for the contribution and sorry for the late review. 

LGTM.

**Comment by wuchong** [comment]
Will merge it once the CI passed. I have rebased the branch to the lastest master.

**Comment by wuchong** [comment]
The failed case in the table module is tracked by issue FLINK-27792 which might be a problem in the unaligned checkpoint.

**Pull request merged**
