### PR TITLE
Improved exception for missing type of InputFormat

### PR DESCRIPTION
**Pull request by twalthr**
As per discussion on the dev mailing list.

### CODE REVIEW

**Comment by hsaputra** [comment]
To reduce code duplication and tracing, we could just throw the exception inside createInput(InputFormat<X, ?> inputFormat, TypeInformation<X> producedType) by wrapping IllegalArgumentException with InvalidProgramException:

{code}
public <X> DataSource<X> createInput(InputFormat<X, ?> inputFormat, 
                                                              TypeInformation<X> producedType) {
  try {
    Preconditions.checkArgument (inputFormat != null, "InputFormat must not be null.");
    Preconditions.checkArgument (producedType != null, 
      "Produced type information must not be null.");
  } catch (IllegalArgumentException iaex) {
    throw new InvalidProgramException(
    "The type returned by the input format could not be automatically determined. " + 
    " Please specify the TypeInformation of the produced type explicitly by using "
    + " the createInput(InputFormat, TypeInformation)' method instead.", iaex);
  }		
  
  return new DataSource<X>(this, inputFormat, producedType, Utils.getCallLocationName());
}
{code}

So the other createInput methods callers dont have to deal with the exception.

**Comment by StephanEwen** [comment]
Good idea, Henry, if we can make sure that the IllegalArgumentException is not thrown in any other cases.

**Comment by StephanEwen** [comment]
I'll merge this...

**Comment by StephanEwen** [comment]
I tried to implement Henry's idea, but I noticed the error message is very specific to the site where it is created, since it refers to an alternate method of `DataSet`. It does not make sense to have that specific message in a different place. I would leave it as it is for now...

**Pull request closed without merging**
