### PR TITLE
[Hotfix][docs] Fixed typos.

### PR DESCRIPTION
**Pull request by RocMarshal**
## What is the purpose of the change

*Fixed typos*

## Brief change log

*Fixed typos*

## Verifying this change

*Fixed typos*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by tisonkun** [comment]
image

It is not a typo.

Closing...

**Comment by RocMarshal** [comment]
@tisonkun Hi, I attach 3 pics about it. PTAL. Thank you.

**Comment by tisonkun** [comment]
https://github.com/apache/flink/blob/2a7e7d7e92f0610502e59f6104391a83dc8b5692/flink-yarn/pom.xml#L44-L54

@RocMarshal nope. Our codebase is in the pattern `flink-runtime_${scala.binary.version}`.

If you suffer from double underscore issue, you can provide minimal reproduce steps and seek the cause.

**Comment by RocMarshal** [comment]
> https://github.com/apache/flink/blob/2a7e7d7e92f0610502e59f6104391a83dc8b5692/flink-yarn/pom.xml#L44-L54
> 
> @RocMarshal nope. Our codebase is in the pattern `flink-runtime_${scala.binary.version}`.
> 
> If you suffer from double underscore issue, you can provide minimal reproduce steps and seek the cause.

@tisonkun  Yes, our codebase is in the pattern `flink-runtime_${scala.binary.version}`. However, the value of variable `scala_version` in documentation configuration is `_2.11`. So,  double underscore was shown in the [page](https://ci.apache.org/projects/flink/flink-docs-master/docs/connectors/table/overview/) .  Thank you for your attention.

**Review by tisonkun — CHANGES_REQUESTED** [review]
Thanks for your detailed analyze @RocMarshal ! You're right that this pull request could be a valid fix.

I found the root cause that we config scala version with a prefix underscore

https://github.com/apache/flink/blob/4cc1246bce744c7ba4417b483643b8478132aff4/docs/config.toml#L55

I don't know whether or not we handle this case properly, though. That is, if we have to create a series of "fix typo" to handle this pattern. Generally I think a variable named "ScalaVersion" should be "2.11" instead of "_2.11" and we handle the prefix underscore separately, which is what we do in the prod codebase.

Would you mind to do an investigation and handle this config properly?

**Comment by RocMarshal** [comment]
@tisonkun Thank you for your reply. I found this problem during the investigation of version upgrade.
It’s probably that `ScalaVersion = "_2.11" ` was  discussed carefully when the documentation was upgraded.
And there are many typos about  variable reference `site.scala_version_suffix` and `site.version` instead of  `scala_version` and `version`.

I'm not sure that we should keep `ScalaVersion = "_2.11"` or update it to `ScalaVersion = "2.11"`. The former requires fewer changes, while the latter requires more changes, but can be better read.
Please let me know your opinions.

**Review by tisonkun — APPROVED** [review]
I go through the codebase and it seems only this section suffer the underscore issue. Let's postpone the discussion of style later.

**Comment by tisonkun** [comment]
Thank you! Merging...

**Pull request merged**
