### PR TITLE
[FLINK-27150][runtime-web] Improve error message rendering

### PR DESCRIPTION
**Pull request by rkhachatryan**
```
- don't hide after a timeout (was: 4.5s)
- expand the message box
```

This allows for example to clearly see what the arguments the program is missing on submission.

Screenshot_2022-03-30_23-20-57

### CODE REVIEW

**Comment by rkhachatryan** [comment]
@vthinkxie, @Airblader could you take a look at this proposal please?

**Comment by Airblader** [comment]
UX-wise a toast message isn't really designed for something like this; it's now more a full-blown dialog, for which there are different UI components. In particular, a fixed width of 1000px obviously won't work for anyone who has their browser window smaller than that, and I'd assume that the toast message does not react well to that. Using a relative width like `90vw`, if supported, would probably alleviate that issue a bit, but it's still a bit of a band-aid fix.

**Comment by rkhachatryan** [comment]
> Using a relative width like 90vw, if supported

Do you know how this support can be detected?
I've tried '%' which I think should be supported universally, but it didn't work.
Sorry, for proabably a noob question, I'm not very familiar with the UI stuff.


> it's still a bit of a band-aid fix

I totally agree, but AFAIK we don't have enough capacity for a proper solution (and I personally don't have enough UI knowledge for that). So I think it should be fine for the time being, WDYT?

**Comment by Airblader** [comment]
> Do you know how this support can be detected?

Can you maybe try using `width: auto`? I believe that should fit the size automatically, and would at least be a bit nicer.

**Comment by rkhachatryan** [comment]
I've tried `width: auto` and it worked, thanks for the suggestion (pushed 2308446).

**Review by Airblader — APPROVED** [review]

**Pull request merged**
