### PR TITLE
[FLINK-4213] [gelly] Provide CombineHint in Gelly algorithms

### PR DESCRIPTION
**Pull request by greghogan**
`VertexDegrees` has changed from using a `ReduceFunction` to using a `GroupReduceFunction` as in directed `TriangleListing`.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Looks good to me.
How much faster does it get with the hash combiner?

**Comment by greghogan** [comment]
Depends how much faster we can make sorting in the `NormalizedKeySorter` :)

I'll keep working on a comparison, I've been running into the deadlock in FLINK-4163.

**Comment by StephanEwen** [comment]
Does the deadlock occur only with the combiner, or also with the sorter?

**Comment by greghogan** [comment]
Yes, and the job plan attached to the ticket shows the only combine as a "Sorted Combine" (from distinct).

**Pull request closed without merging**
