### PR TITLE
cleaned up readme

### PR DESCRIPTION
**Pull request by aertoria**
Cleaned up some readme. Would like to contribute more

### CODE REVIEW

**Comment by fhueske** [comment]
Hi @aertoria,
thanks for the PR and welcome to the Flink community!
Is it intentional, that your PR only adds are remove empty lines?

Talking about future contributions, which parts of the system would you be interested in? We have a few issues marked as "starter" task in JIRA which should be good for people who want to start contributing.
See the [How to contribute guide](http://flink.apache.org/how-to-contribute.html) and ask on the mailing list if you have any questions.

**Comment by aertoria** [comment]
Hey Febian,

You may ignore that pull request. I was just demonstrating my friend how to get start contribute a apache projects. We should welcome him Brad to contribute!

Thanks,

Ethan wang.

**Comment by fhueske** [comment]
Ah OK :-)
Would you mind, closing the PR then? 

Thanks, Fabian

**Comment by aertoria** [comment]
closed

**Comment by aertoria** [comment]
Done.

**Pull request closed without merging**
