### PR TITLE
[FLINK-1296] Add sorter support for very large records

### PR DESCRIPTION
**Pull request by StephanEwen**
This allows the sorter to handle records larger than the memory sort buffers.

### CODE REVIEW

**Comment by StephanEwen** [comment]
I think that this one can go into the 0.9 master now.

**Comment by rmetzger** [comment]
+1

**Comment by uce** [comment]
+1 

I will merge this in the next batch.

**Comment by uce** [comment]
OK I've rebased this PR on the current master. All tests are running locally (Travis is still flaky). @mxm is running some cluster tests. I'll push to master after his OK. :-)

**Comment by uce** [comment]
Cluster tests worked fine. If no one objects I'll merge this later today.

**Pull request closed without merging**
