### PR TITLE
[FLINK-21646][table-planner-blink] Support StreamExecWindowAggregate json serialization/deserialization

### PR DESCRIPTION
**Pull request by godfreyhe**
## What is the purpose of the change

*This pr aims to support json serialization/deserialization for StreamExecWindowAggregate*

## Brief change log

  - *Port the classes in windowingSpecs.scala to Java*
  - *Port the classes in plannerWindowProperties.scala to Java*
  - *Port FlinkRelBuilder.PlannerNamedWindowProperty to Java*
  - *Support Duration json serialization/deserialization*
  - *Support StreamExecWindowAggregate json serialization/deserialization*

## Verifying this change

This change added tests and can be verified as follows:

  - *Added WindowAggregateJsonPlanTest and WindowAggregateJsonITCase which could verify the change*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by zjuwangg** [comment]
It seems a81f035dc4ec463e7c7c7323b54249ec9e194cc2 is also introduced mistakenly in this pr ...

**Comment by godfreyhe** [comment]
> It seems [a81f035](https://github.com/apache/flink/commit/a81f035dc4ec463e7c7c7323b54249ec9e194cc2) is also introduced mistakenly in this pr ...

Before this pr is based on https://github.com/apache/flink/pull/15194, and once https://github.com/apache/flink/pull/15194 is merged, I will rebase the master and drop the first commit

**Comment by godfreyhe** [comment]
@zjuwangg I have rebased the master

**Review by zjuwangg — APPROVED** [review]
LGTM!
Thanks for your hard work.
Let's wait the CI pass.

**Pull request closed without merging**
