### PR TITLE
Clean up naming of State/Checkpoint Interfaces

### PR DESCRIPTION
**Pull request by aljoscha**
The interfaces are used on StreamTask (for now) but were called
*Operator.

Also, the methods on operator were suggesting that it is only user
function state while it could also be state of a stateful system
operator such as a windowing operator.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Looks good

I actually liked the function name `restoreInitialState`. This makes it very clear that this method sets only the initial state, not any state whensoever.

**Comment by aljoscha** [comment]
But what does restoreInitialState mean? What is the initial state? The state when the operator was first created?

**Comment by StephanEwen** [comment]
It would mean "the state with which that operator instance is started".
It is just a personal preference - just keep it as it is if you want...

**Comment by aljoscha** [comment]
Nah, you can change it of course. :smile_cat:

**Comment by mbalassi** [comment]
I think this is redundant now.

**Comment by aljoscha** [comment]
Why? There is still a naming difference between methods that to similar things at different levels.

**Comment by mbalassi** [comment]
Sorry, I thought we had this mostly in already. My bad.

**Comment by aljoscha** [comment]
No problemo :smile: It's only internal, though, now user-facing.

**Comment by fhueske** [comment]
@aljoscha, is this PR still valid after the recent refactoring and extension of the streaming state interfaces?

**Comment by aljoscha** [comment]
It's still valid, I think the names are still off
```
public abstract class StreamTask<OUT, O extends StreamOperator<OUT>> extends AbstractInvokable implements
		OperatorStateCarrier<StateHandle<Serializable>>, CheckpointedOperator, CheckpointNotificationOperator {
```

The StreamTask implements interfaces that have Operator in their names, and they are inconsistent.

**Comment by StephanEwen** [comment]
I actually like this. Can you rebase to master, and maybe change one name:

`CheckpointCommittingTask` --> `CheckpointCompleteNotifiyee` or `CheckpointCompleteNotificationReceiver`

**Comment by aljoscha** [comment]
I rebased it and consolidated the state related interfaces into one interface.

**Comment by StephanEwen** [comment]
I like this, feels more intuitive to me and makes sense that a task either implements all of the methods, ot none...

+1 to merge

**Comment by aljoscha** [comment]
ok, I'm merging it

**Pull request closed without merging**
