### PR TITLE
[FLINK-28850][table-planner] Support table alias in LOOKUP hint

### PR DESCRIPTION
**Pull request by lincoln-lil**
## What is the purpose of the change
FLINK-28848 introduces the new LOOKUP hint, but doesn't support table alias due to calcite's snapshot not hintable, now CALCITE-5251 has been merged(and will be included in calcite-1.32.0) , we can move on supporting alias in flink. And the copied file of snapshot relnode can be deleted when flink done upgrading of calcite-1.32.0.

## Brief change log
* copy Snapshot node from calcite-1.26.0 and cherry-pick the hint support for it (CALCITE-5251) 
* add alias support for LOOKUP hint and update related tests

## Verifying this change
LookupJoinTest  LookupJoinJsonPlanTest

## Does this pull request potentially affect one of the following parts:
  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with @Public(Evolving): (no)
  - The serializers: (no )
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation
  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (docs)

### CODE REVIEW

**Comment by lincoln-lil** [comment]
> @flinkbot run azure

failed by a known case:  https://issues.apache.org/jira/browse/FLINK-29315

https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=41103&view=logs&j=ab8d7049-0920-5f52-eeed-e548522c2880&t=a7d66b08-71af-51c3-2721-4b90fa4f94e3

**Review by godfreyhe — COMMENTED** [review]
Thanks for the contribution @lincoln-lil , LGTM overall, I have two minor comments:
1. if we want to keep the first commit when merging, the class should be formatted
2. it's better we can still  keep some tests for hints with table name

**Comment by lincoln-lil** [comment]
@godfreyhe thanks for reviewing this! I've updated the pr according to your comments, the Snapshot was formatted correctly in the first commit and added two more cases that use table name as hint option(previously, only one case was kept)

**Review by godfreyhe — APPROVED** [review]
LGTM

**Pull request closed without merging**
