### PR TITLE
[FLINK-15515][hive][doc] Document that Hive connector should be used …

### PR DESCRIPTION
**Pull request by lirui-apache**
…with blink planner

## What is the purpose of the change

Document Hive connector only works with blink planner.

## Brief change log

  - Document Hive connector only works with blink planner

## Verifying this change

NA

## Does this pull request potentially affect one of the following parts:

NA

## Documentation

NA

### CODE REVIEW

**Comment by lirui-apache** [comment]
cc @JingsongLi @bowenli86 @xuefuz 

We have documentation about [using Hive connector from scala shell](https://ci.apache.org/projects/flink/flink-docs-master/dev/table/hive/scala_shell_hive.html). However, it seems scala shell always uses old planner. Would like to know your opinions what we should do about that doc. Thanks.

**Comment by lirui-apache** [comment]
@bowenli86 I have updated the zh docs.
For scala shell, I think we shouldn't let users use it for hive connector, until we resolve https://issues.apache.org/jira/browse/FLINK-15539.  @zjffdu what do you think?

**Comment by zjffdu** [comment]
Right, currently running hive-connector in scala shell is not recommended.

**Comment by bowenli86** [comment]
LGTM, merging

**Pull request closed without merging**
