### PR TITLE
[FLINK-5588][ml] add a data normalizer to ML library

### PR DESCRIPTION
**Pull request by skonto**
- Adds a Normalizer (per sample). 
- Throws an exception if NaN values are used, following the scikit-learn approach. An Imputer will be added later. Also I plan to make the rest of preprocessing algos compatible in another PR.
- Supports p norm value as a double. L1,L2, LMax norms are predefined for easier use.

### CODE REVIEW

**Comment by skonto** [comment]
@thvasilo @tillrohrmann  pls review.

**Comment by thvasilo** [comment]
Hello @skonto thanks for your contribution!

I'm currently snowed under paper deadlines, so I can't give you a time for when I'll be able to go through this, hopefully within the next 2-3 weeks.

**Comment by skonto** [comment]
@tillrohrmann  the tests never finished :( Is there a way to re-trigger it besides a commit?

**Comment by tillrohrmann** [comment]
Hi @skonto, if you have activated the Travis integration for your own repo, then you can restart the testing job there. For the apache account it is not possible. However, I've seen that only the last build ran out of time. We're currently at the very limit in terms of runtime what Travis allows. That is a known issue and we try to address it soon.

**Comment by greghogan** [comment]
@skonto another option, if the master branch has a newer commit, is to rebase and force push.

**Comment by tillrohrmann** [comment]
But please don't do a force push on a branch which has been opened as a PR. If there was a review ongoing, then the force push might invalidate it (e.g. if you changed something in the relevant files).

**Comment by skonto** [comment]
Ok sorry for that I did squash the commits, also I am used to it from other projects where the comments are invalidated.

**Comment by skonto** [comment]
WIP I will add the unit scaler here.

**Comment by zentol** [comment]
Closing since flink-ml is effectively frozen.

**Pull request closed without merging**
