### PR TITLE
[FLINK-24762][table-runtime] Remove agg function: INCR_SUM

### PR DESCRIPTION
**Pull request by cshuo**
## What is the purpose of the change

The removal of INCR_SUM should be completed in FLINK-13529, but that PR only removes function definition of INCR_SUM. This PR will complete the removal work for INCR_SUM.

## Brief change log
  - Removes the AggregateFunction implementation  for INCR_SUM

## Verifying this change
  - No need to verifying

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Review by tsreaper — APPROVED** [review]
Thanks for the commit. Looks good to me.

**Comment by cshuo** [comment]
cc @JingsongLi plz have a look.

**Review by snuyanzin — APPROVED** [review]

**Review by RocMarshal — APPROVED** [review]
LGTM +1.
@AHeise @MartijnVisser Would you mind doing the final review when you have moments?

**Review by JingsongLi — APPROVED** [review]
Thanks @cshuo , looks good to me!

**Pull request merged**
