### PR TITLE
[Flink-26011][test] backport 1.15 - ArchUnit test for formats test code

### PR DESCRIPTION
**Pull request by JingGe**
backport to 1.15  #19357

### CODE REVIEW

**Comment by JingGe** [comment]
@flinkbot run azure

**Review by MartijnVisser — COMMENTED** [review]
What's not possible for me to assess is if this will break something causing user issues when upgrading from Flink 1.15.0 to Flink 1.15.1.

**Comment by JingGe** [comment]
Thanks @MartijnVisser for pointing it out. This pr focuses on the architectural test for test code. It belongs to the infra topic and will be used to improve the architecture and code quality. It should have no impact on any Flink 1.15.x upgrade at all, i.e. users will not have to change any of their application code when doing a patch release upgrade.

**Comment by JingGe** [comment]
Loop @zentol @AHeise in. May I know your thoughts?

**Pull request closed without merging**
