### PR TITLE
[FLINK-2456][fix]add a repository ID for hadoop2 in flink-hbase module

### PR DESCRIPTION
**Pull request by HuangWHWHW**
add a repository for hadoop-2 in flink-hbase.
It can be downloaded through a specified mirror like:

<mirror>
        <id>repo2</id>
        <name>Human Readable Name for this Mirror.</name>
        <url>http://repo2.maven.org/maven2/</url>
        <mirrorOf>hadoop-2-repo2</mirrorOf>
    </mirror>

Or it will not affect the normal network environment when default.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Thanks for providing this path!
Can you help us understand this fix a bit? Why is this extra repository entry required for the HBase module, and not for any other modules?

**Comment by HuangWHWHW** [comment]
This is just a method to solve the problem that some modules' dependencies cannot be downloaded from central maven repository.
You can specify every module dependency ID so that we can downloading dependencies from either central maven repository by default or other channel by setting maven mirrors when mvn package.
As for HBase, it`s just that I get some trouble in downloading this module dependency.
And sorry for the url.
I just want to push a example about maven mirror on the comment but it was blocked because of the XML format.
This complete code should be like this:

    "<mirror>"
        "<id>repo2</id>"
        "<name>Human Readable Name for this Mirror.</name>"
        "<url>http://repo2.maven.org/maven2/</url>"
	"<mirrorOf>hadoop-2-repo2</mirrorOf>"
    "</mirror>"

**Comment by StephanEwen** [comment]
The repository you add is the default Maven repository - it should be used by default anyways.

Is the change there override your mirror repository for HBase with the default repository?

**Comment by HuangWHWHW** [comment]
The most important In the HBase pom.xml I add is the repository ID:

"<repositories>"
			"	<repository>"
			"		<id>hadoop-2-repo2</id>"
"					<url>https://repo.maven.apache.org/maven2</url>"
"					<releases>"
"						<enabled>true</enabled>"
"					</releases>"
"					<snapshots>"
"						<enabled>false</enabled>"
"					</snapshots>"
"				</repository>"
"			</repositories>"

By using this id, you can get the hadoop-2 from any way(for example using mirror with this ID).
The default repository is the url(https://repo.maven.apache.org/maven2) above.
And the default means you need not do anything with maven configuration just print "mvn package".
As I see, every flink dependency is using this url.
Did I misunderstand? Is the hadoop-2 default repository path is another?

**Comment by HuangWHWHW** [comment]
The most important In the HBase pom.xml I add is the repository ID:

"<repositories>"
"<repository>"
"<id>hadoop-2-repo2</id>"
"<url>https://repo.maven.apache.org/maven2</url>"
"<releases>"
"<enabled>true</enabled>"
"</releases>"
"<snapshots>"
"<enabled>false</enabled>"
"</snapshots>"
"</repository>"
"</repositories>"


By using this id, you can get the hadoop-2 from any way(for example using mirror with this ID).
The default repository is the url(https://repo.maven.apache.org/maven2) above.
And the default means you need not do anything with maven configuration just print "mvn package".
As I see, every flink dependency is using this url.
Did I misunderstand? Is the hadoop-2 default repository path is another?

**Comment by HuangWHWHW** [comment]
The most important in the Flink-hbase pom.xml I add is the repository ID:

""

By using this id, you can get the hadoop-2 from any way(for example using mirror with this ID).
The default repository is the usl(https://repo.maven.apache.org/maven2) above.
And the default means you need not do anything with maven configuration just print "mvn pakcage".
As I see, every flink dependency is using this url.
Did I misunderstand?Is the hadoop-2 default repository path is another?

**Comment by HuangWHWHW** [comment]
The most important in the Flink-hbase pom.xml I add is the repository ID:

image


By using this id, you can get the hadoop-2 from any way(for example using mirror with this ID).
The default repository is the usl(https://repo.maven.apache.org/maven2) above.
And the default means you need not do anything with maven configuration just print "mvn pakcage".
As I see, every flink dependency is using this url.
Did I misunderstand?Is the hadoop-2 default repository path is another?

**Comment by StephanEwen** [comment]
I understand.

Will merge this...

**Comment by StephanEwen** [comment]
Thank you for taking the time to explain the reason behind this issue...

**Comment by HuangWHWHW** [comment]
My plessure.

**Pull request closed without merging**
