### PR TITLE
[FLINK-25962][format-avro] Use namespaces for generated records

### PR DESCRIPTION
**Pull request by RyanSkraba**
## What is the purpose of the change

It's currently under discussion whether an Avro record can have the bare name `record`.  While the spec doesn't forbid this, some versions (including the current 1.11.0) of the Avro Python SDK consider this to be an error, and the default generated schema are unreadable from Pythonj.

It's a best practice to assign a namespace to the record, which avoids this issue.

## Brief change log

- Use the namespace `org.apache.flink.avro.generated` consistently in the code where a bare record is encountered.
- Update `AvroBulkFormatTest` to show how the magic numbers for the Blocks can be calculated.

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is already covered by existing tests, such as *AvroBulkFormatTest*, *AvroSchemaConverterTest*.

It's tricky to write a cross-language unit test; the current generated Schema is accepted by the Java Avro SDK and fails with the Python Avro SDK.  

A generated schema can be checked with the Python SDK in a virtual environment like this:
```
>>> from avro import schema
>>> schema.parse('{"type":"record","name":"record","fields":[{"name":"a1","type":"long"}]}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venvrOkH7pO9/lib64/python3.10/site-packages/avro/schema.py", line 1203, in parse
    return make_avsc_object(json_data, Names(), validate_enum_symbols)
  File "/tmp/venvrOkH7pO9/lib64/python3.10/site-packages/avro/schema.py", line 1159, in make_avsc_object
    return RecordSchema(name, namespace, fields, names, type_, doc, other_props)
  File "/tmp/venvrOkH7pO9/lib64/python3.10/site-packages/avro/schema.py", line 878, in __init__
    NamedSchema.__init__(self, schema_type, name, namespace, names, other_props)
  File "/tmp/venvrOkH7pO9/lib64/python3.10/site-packages/avro/schema.py", line 263, in __init__
    new_name = names.add_name(name, namespace, self)
  File "/tmp/venvrOkH7pO9/lib64/python3.10/site-packages/avro/name.py", line 158, in add_name
    raise avro.errors.SchemaParseException(f"{to_add.fullname} is a reserved type name.")
avro.errors.SchemaParseException: record is a reserved type name.
```

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by RyanSkraba** [comment]
I've fixed the merge conflicts in this PR: for older PRs  like this, does the Flink project prefer merging or rebasing?

**Review by zentol — COMMENTED** [review]
Are there any compatibility concerns around changing the schema generation?

Should we add a test that verifies the generated schemas are compatible with python?

**Comment by RyanSkraba** [comment]
Hello!  These are both good notes.  I have some opinions, but I'd appreciate any ideas or feedback!

There _might_ be compatibility concerns, although this is mitigated by two points:

1. The changed schema is a drop-in replacement: bytes serialised by the old schema can be deserialized transparently by the new schema and vice versa.
2. If the old schema was persisted somewhere (file or registry), and the user is using Avro schema resolution while reading, adding an explicit namespace won't cause any problems.

In my experience, there will probably be at least one user doing some custom processing or storage of generated schemas, and we can't prove they won't be surprised by the change.  That being said, we are definitely encountering users today that want to use the generated schema with a Avro Python SDK.

> Should we add a test that verifies the generated schemas are compatible with python?

I don't want to point fingers, but I think that this Java/Python interoperability failure is an Avro issue, and should be addressed there.  It would be unreasonable (for example) for Flink to verify that it's not accidentally creating schemas that can't be read by the Rust SDK... I created AVRO-3591 for the next major release of Avro (and I am very motivated to keep the confidence in Avro's interoperability high).

**Comment by zentol** [comment]
@RyanSkraba gotcha; could you rebase the branch against master?

**Pull request merged**
