### PR TITLE
[FLINK-18731][table-planner-blink] Fix monotonicity logic of UNIX_TIMESTAMP & UUID functions

### PR DESCRIPTION
**Pull request by godfreyhe**
## What is the purpose of the change

*UNIX_TIMESTAMP function has INCREASING monotonicity only if it has empty function arguments, else has NOT_MONOTONIC monotonicity*

## Brief change log

  - *Correct the monotonicity logic of UNIX_TIMESTAMP function in FlinkSqlOperatorTable*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by godfreyhe** [comment]
cc @wuchong

**Comment by wuchong** [comment]
1. Maybe we should also fix the `isDeterministic`. What do you think to have a specific `UnixTimestampSqlFunction` class? The logic stayed in `FlinkSqlOperatorTable` is quite verbose. 
2. Maybe we should also fix `UUID#getMonotonicity`?
3. Is it possible to have a test to reproduce the problem?

**Comment by godfreyhe** [comment]
Thanks for the suggestion, 
> 1. Maybe we should also fix the `isDeterministic`. What do you think to have a specific `UnixTimestampSqlFunction` class? The logic stayed in `FlinkSqlOperatorTable` is quite verbose.

we can't fix `isDeterministic`, because different from `getMonotonicity(SqlOperatorBinding call)`,  `isDeterministic()` knows nothing about operand count. One approach is we can split `UNIX_TIMESTAMP` into two different functions, but I think it's unnecessary.
If we only fix `getMonotonicity`, I trend to keep the logic in `FlinkSqlOperatorTable`.

> 2. Maybe we should also fix `UUID#getMonotonicity`?

good catch

> 3. Is it possible to have a test to reproduce the problem?

Tests have been added

**Comment by godfreyhe** [comment]
@flinkbot run azure

**Review by wuchong — APPROVED** [review]
LGTM.

**Comment by wuchong** [comment]
@flinkbot run azure

**Comment by godfreyhe** [comment]
my private azure is green https://dev.azure.com/godfreyhe/godfreyhe-flink/_build/results?buildId=74&view=results

**Pull request closed without merging**
