### PR TITLE
[FLINK-26164] Document watermark alignment

### PR DESCRIPTION
**Pull request by dawidwys**
## What is the purpose of the change

Add documentation for watermark alignment

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (**yes** / no)
  - If yes, how is the feature documented? (not applicable / **docs** / JavaDocs / not documented)

### CODE REVIEW

**Review by smattheis — COMMENTED** [review]
LGTM. Only suggestions:
- "On the other side of the spectrum" is clear to me. Maybe we could point out that this solves the problem of "fast and slow operator input" and which is not the same as "idle input/source".
- "When enabling the alignment, you need to tell Flink, which group should the source belong" Is it right that the user defines the group and defines the label "alignment-group-1"? If so, I suggest to make that explicit: "The user has to define an alignment group that consists of ... and is done by ....".

**Comment by dawidwys** [comment]
@smattheis Could you take another look? I tried addressing your concerns. I also elaborated a bit more on the limitations and recommendations.

**Comment by smattheis** [comment]
@flinkbot approve all

**Review by smattheis — APPROVED** [review]
LGTM.

**Pull request closed without merging**
