### PR TITLE
[FLINK-21388] [flink-parquet] support DECIMAL parquet logical type when parquet primitive type is INT32

### PR DESCRIPTION
**Pull request by echauchot**
## What is the purpose of the change

support DECIMAL parquet logical type when parquet primitive type is INT32

## Brief change log

The support for INT64 was already done (matching _int64/DECIMAL_ to _BasicTypeInfo.INT_TYPE_INFO_)
Simply added support for INT32 (matching _int32/DECIMAL_ to _BasicTypeInfo.INT_TYPE_INFO_)

## Verifying this change

This change added tests and can be verified as follows:
ParquetSchemaConverterTest#testDecimalParquetLogicalType

## Does this pull request potentially affect one of the following parts:
  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by echauchot** [comment]
@HuangZhenQiu can you ping a committer as you proposed to review this PR ?
Thanks

**Comment by echauchot** [comment]
@fhueske as you merged the previous related PR, can you please review this one ?
Thanks.

**Review by HuangZhenQiu — APPROVED** [review]

**Comment by HuangZhenQiu** [comment]
@JingsongLi
Would you please review this PR?

**Comment by echauchot** [comment]
@HuangZhenQiu to be honest I still have a doubt on the whole parquet support for DECIMAL. parquet [doc](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#decimal) says that the primitive type (int32, or int64) stores the unscaled value (before the decimal point) but I sill don't know where is the scaled value (after the decimal point) stored in the parquet field. As the support for int64 in flink was already done through _BasicTypeInfo.INT_TYPE_INFO_ I did the same but I fear we lose the decimal part in those cases.

**Comment by JingsongLi** [comment]
Are you worried about the decimal point? In fact, int32 or Int64 contains integer and decimal parts, so precision and data will not be lost. You can take a look at Java's `BigDecimal`, which is also saved with Int64.

**Review by JingsongLi — APPROVED** [review]
Looks good to me, thanks @echauchot

**Comment by echauchot** [comment]
> Are you worried about the decimal point? In fact, int32 or Int64 contains integer and decimal parts, so precision and data will not be lost. You can take a look at Java's `BigDecimal`, which is also saved with Int64.

Yes indeed, I was worried about that. Ok I did not know that int32 or Int64 contained both unscaled value and scale. Thanks for the information.

Thanks also for merging

**Pull request merged**
