### PR TITLE
[hotfix] [docs] Fix typo in index.md of Getting Started section

### PR DESCRIPTION
**Pull request by amalkurup89**
## What is the purpose of the change

      Documentation Fixtures

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive):no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper:  no
  - The S3 file system connector: mo

### CODE REVIEW

**Comment by amalkurup89** [comment]
@rmetzger 'test_ci misc' job of Azure build failed. Do I need to retrigger it, as the change is just a documentation fix. Please point

**Comment by rmetzger** [comment]
No, you an ignore this failure.
I don't fully understand what problem you are trying to fix in this PR.
From how I understand Flink's docs generation, the ".html" extension is needed for the generated html files to work.

**Comment by amalkurup89** [comment]
@rmetzger Two href links in index.md file of master branch are not working. When clicked on the link, it shows up ‘Page not found’ error. I have rectified those 2 href links to navigate to the correct pages

**Comment by rmetzger** [comment]
On current master, both links work for me: https://ci.apache.org/projects/flink/flink-docs-master/getting-started/

**Pull request closed without merging**
