### PR TITLE
[FLINK-10292] Generate JobGraph in StandaloneJobClusterEntrypoint only once

### PR DESCRIPTION
**Pull request by yanghua**
## What is the purpose of the change

*This pull request makes JobGraph in StandaloneJobClusterEntrypoint just been generated only once*

## Brief change log

  - *Generate JobGraph in StandaloneJobClusterEntrypoint only once*

## Verifying this change

This change is already covered by existing tests, such as *ClassPathJobGraphRetrieverTest#testJobGraphRetrieval*.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by yanghua** [comment]
@tillrohrmann This is very strange, why this PR change causes the yarn test to time out, and some applications cannot reach the RUNNING state.

**Comment by yanghua** [comment]
It seems that it is blocked by PR #6816 .

**Comment by yanghua** [comment]
@tillrohrmann can roughly review the PR changes before Travis turns green. Considering that it is inseparable from [FLINK-10291](https://issues.apache.org/jira/browse/FLINK-10291), I expect it to catch up with the release point of flink 1.7.

**Comment by tillrohrmann** [comment]
Hi @yanghua, at the moment I'm busy with other things. Thus, I'm not sure whether I find the time to review this for the 1.7 release. I'll try to get back asap.

**Comment by yanghua** [comment]
hi @tillrohrmann You know, we didn't remove the assertion when dealing with FLINK-10527. It caused the PR test to fail, so please ignore the test failure here. If you have time, you can look at this PR.

**Comment by yanghua** [comment]
leaving...

**Pull request closed without merging**
