### PR TITLE
FLINK-10918 Fix error while checkpointing on window keyed state rock …

### PR DESCRIPTION
**Pull request by imamitsehgal**
…db backend

## What is the purpose of the change

*To fix the directory creation error while running on Windows with RockDBBackend*

## Brief change log

  - *Changed the RocksDBKeyedStateBackend to remove leading '/' in checkpoint path on windows*

## Verifying this change

This change is already covered by existing tests, such as *(please describe tests)*.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: ( no )
  - The runtime per-record code paths (performance sensitive): ( no )
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: ( no )
  - The S3 file system connector: ( no )

## Documentation

  - Does this pull request introduce a new feature? ( no)

### CODE REVIEW

**Comment by imamitsehgal** [comment]
What is the purpose of the change?
To fix the issue with creating directory while running on windows with keyed state and rocksdbbackend.
Brief change log
RockDBKeyedStateBackend class changes to remove leading '/' in the path string
Verifying this change
This change is already covered by existing tests, such as (please describe tests).
Documentation
Does this pull request introduce a new feature? NO

**Comment by imamitsehgal** [comment]
The build is passing on the forked branch, the failure here is unrelated
https://travis-ci.org/imamitsehgal/flink/builds/459154746

**Comment by imamitsehgal** [comment]
I have not added any additional test case around this because this is very specific for Windows OS and runs fine on Linux. So the four test cases fails on my windows laptop IncrementalRocksStreamOperatorSnapshotRestoreTest which after making this change pass through. However there are quite a few other unrelated test cases which are failing on windows with or without this change.

**Comment by imamitsehgal** [comment]
> @imamitsehgal thank you for your contribution. Could you please add a test to verify this? (Before the patch has been applied the test should fail, and after the patch has been applied the test should pass).

I have not added any additional test case around this because this is very specific for Windows OS and runs fine on Linux. So the four test cases fails on my windows laptop IncrementalRocksStreamOperatorSnapshotRestoreTest which after making this change pass through. However there are quite a few other unrelated test cases which are failing on windows with or without this change.

**Comment by tillrohrmann** [comment]
I think this issue has been solved differently in the meantime. See #11095. Closing this PR now.

**Pull request closed without merging**
