### PR TITLE
[FLINK-19861][document][table-planner/api] Improve functions document which are not deterministic

### PR DESCRIPTION
**Pull request by wangxlong**
## What is the purpose of the change

 Improve functions document which are not deterministic

## Brief change log

Highlight the behavior of now function in /dev/table/functions/systemFunctions.md.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no / don't know)
  - The runtime per-record code paths (performance sensitive): (no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no / don't know)
  - The S3 file system connector: (no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by wuchong** [comment]
Thanks @wangxlong . Could you help to update other similar functions, e.g. `UNIX_TIMESTAMP`, `LOCALTIMESTAMP`, `CURRENT_TIMESTAMP`>

**Comment by wangxlong** [comment]
My pleasure. I will update it tonight.

**Comment by wangxlong** [comment]
@wuchong  Updated.

**Comment by wuchong** [comment]
Sorry @wangxlong , I checked the implementation again and found that only `UUID`, `NOW()`, `UNIX_TIMESTAMP`, `PROCTIME()` are not deterministic.

**Comment by wangxlong** [comment]
> Sorry @wangxlong , I checked the implementation again and found that only `UUID`, `NOW()`, `UNIX_TIMESTAMP`, `PROCTIME()` are not deterministic.

It doesn't matter. I will update it now, I'm sorry I didn't check all of them.

**Review by wuchong — APPROVED** [review]
LGTM.

**Comment by wuchong** [comment]
Hi @wangxlong , do you have an email? I would like to chat with you in private but couldn't find your contact information.

**Comment by wangxlong** [comment]
> Hi @wangxlong , do you have an email? I would like to chat with you in private but couldn't find your contact information.

Hi @wuchong , My email is 18868816710@163.com, I can be reached by this email.

**Pull request merged**
