### PR TITLE
[hotfix][tests] Replace MockOperatorStateBackend with default

### PR DESCRIPTION
**Pull request by rkhachatryan**
Addition of  `MockOperatorStateBackend` in #17645 was unnecessary because `DefaultOperatorStateBackend` would suffice.
cc: @Myasuka

### CODE REVIEW

**Review by Myasuka — COMMENTED** [review]
If removing `MockOperatorStateBackend`, I think the constructor of `MockStateBackend(boolean emptySnapshot)` is useless.

**Comment by rkhachatryan** [comment]
> If removing MockOperatorStateBackend, I think the constructor of MockStateBackend(boolean emptySnapshot) is useless.

`new MockStateBackend(true)` is still used by `UnalignedCheckpointFailureHandlingITCase` while other tests use `false`
(this is because `UnalignedCheckpointFailureHandlingITCase` actually sends the snapshot to JM which won't serialize mock state handle).

**Review by Myasuka — APPROVED** [review]
Thanks for the clarification, LGTM.

**Comment by rkhachatryan** [comment]
Thanks for the review!
Merged 1009978672bf5989e5e3afae94b938cec1e685f3 into master.

**Pull request merged**
