### PR TITLE
Test PR, please ignore

### PR DESCRIPTION
**Pull request by zentol**
I'm using this PR to test changes to the travis setup.

You can safely ignore this, and I will close it once I'm done.

### CODE REVIEW

**Comment by greghogan** [comment]
May also be able to revert `-Dflink.forkCountTestPackage=1` to 2 in `tools/travis_mvn_watchdog.sh` with memory increased from 4 GB to 7.5 GB (https://docs.travis-ci.com/user/ci-environment/).

**Comment by zentol** [comment]
@greghogan Sure, I'll try that in the second run!

**Comment by zentol** [comment]
This PR stabilized build times around 55 minutes. While we are not below 50 yet we can still tweak some stuff, so I propose merging it (after re-enabling RAT of course) and go from there.

This should at least reduce the PR/master build queues.

https://travis-ci.org/apache/flink/builds/245845600

**Comment by greghogan** [comment]
I'm working on a PR to print some system information (with output folding) to the TravisCI log which may be useful in debugging these sort of changes. It would be nice if we could fold each Maven module as well.

**Pull request closed without merging**
