### PR TITLE
[hotfix][docs] ' Chinese document' Format repair

### PR DESCRIPTION
**Pull request by MikuSugar**
## What is the purpose of the change

- Fix document format

## Brief change log

- 'Alter Chinese document format repair

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

- Dependencies (does it add or upgrade a dependency): (yes / **no**)
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
- The serializers: (yes / **no** / don't know)
- The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
- The S3 file system connector: (yes / **no** / don't know)

## Documentation

- Does this pull request introduce a new feature? (yes / **no**)
- If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by MikuSugar** [comment]
之前有一次提交，因为合并操作有错误，所以重新提交（There was a previous submission, because there was an error in the merge operation, so it was submitted again）https://github.com/apache/flink/pull/16119

**Comment by MikuSugar** [comment]
@Airblader 我已经重新提交了，麻烦你看一下，谢谢～（I have resubmitted it. Please have a look at it. Thanks ）

**Review by Airblader — APPROVED** [review]
LGTM, thanks for updating it!

**Comment by MikuSugar** [comment]
It's just like the picture below. It's a mess
image

**Comment by MikuSugar** [comment]
Hello @tisonkun, @wuchong, @leonardBang - Please review this PR and let me know your feedback ? Thanks

**Review by wuchong — APPROVED** [review]
Thanks for fixing it @MikuSugar .

**Pull request merged**
