### PR TITLE
[FLINK-4368] [distributed runtime] Eagerly initialize the RPC endpoint members

### PR DESCRIPTION
**Pull request by StephanEwen**
This eagerly initialized the RPC members like
  - self gateway
  - self reference
  - main thread executor
and makes them immutable.

This also adds structural comments to the `RpcProtocol` class.

### CODE REVIEW

**Comment by StephanEwen** [comment]
@tillrohrmann What do you think about this?

The downside that I can see is that the RPC endpoint can actually receive calls before the constructor is completed, basically as soon as the base class' constructor is complete. That may actually be an issue.

**Comment by tillrohrmann** [comment]
I think the changes look good.

You're right that this is a problem. The constructor should complete before the rpc endpoint is reachable. 

With the former implementation there was a similar problem though: First you start the actor and then you initialize the self context. If a message arrived between these two calls which triggers access to the self context, it would have caused a NPE.

Maybe one can solve the problem by not publishing the connection address of the rpc endpoint before the constructor has been executed? Then no gateway could connect against the endpoint and send request until the whole endpoint has been initialized.

Or we let the underlying rpc server (e.g. actor) ignore all messages until he has been explicitly told differently. But this would entail that the user has to call something like `rpcEndpoint.startReceivingMessages()`.

**Comment by StephanEwen** [comment]
+1 for your suggestion.

I will merge this commit then, and then we add the `rpcEndpoint.startReceivingMessages()` on top of it.

**Comment by StephanEwen** [comment]
Manually merged into `flip-6` feature branch in https://github.com/apache/flink/commit/08af7def60d54c22126b902e6fa57101d5fbb8fa

**Pull request closed without merging**
