### PR TITLE
[1.8][FLINK-14104][build] Add opt-in jackson 2.10.1 profile

### PR DESCRIPTION
**Pull request by zentol**
This PR adds an opt-in profile that bumps jackson dependencies to 2.10.1. This version contains fixes for a large number of security fixes.
This upgrade is an opt-in feature as we usually don't bump dependencies for bugfix releases, and this is done shortly before the next release, giving us little time to let it mature.

green cron job that I ran yesterday: https://travis-ci.com/flink-ci/flink/builds/136505905

### CODE REVIEW

**Comment by zentol** [comment]
hmm...`dependencies.md` is for user projects; let me check whether a user would run into issues if he would try to package something like kafka with 3.0.0 . If a problem comes up I will update the documentation, otherwise I will leave it as is.

**Comment by zentol** [comment]
As far as I can tell this would only fail for users if they package jackson directly. If they bundle a dependency that already contains jackson (like what a connector would do) it doesn't fail.

BUt then again there are connector which don't create a fat jar, so they might run into this. Will update the documentation and quickstarts.

**Comment by zentol** [comment]
@hequn8128 I've updated the PR.

**Comment by zentol** [comment]
Note that in contrast to 1.9/master this PR also affects `flink-shaded-hadoop`, which I did not tests myself since there's just no way to very that everything still works (hence why I'm not touching that for other versions).

**Comment by hequn8128** [comment]
@zentol Thanks a lot for the Note! Not sure about this. If we don't bump the version of jackson in `flink-shaded-hadoop` for 1.9/master, we may still encounter the security problems with the pre-bundled hadoop jars?

**Comment by zentol** [comment]
yes, flink-shaded-hadoop would still be affected.

I think that's fine _for now_, as not all users are affected by this due to either not using hadoop at all or pointing Flink to an existing hadoop setup (i.e. being independent of flink-shaded-hadoop).

I really want to stay out of managing hadoop dependencies since it's just a minefield; it's just not feasible to ensure it actually remains functional with the rest of the hadoop ecosystem.

**Comment by hequn8128** [comment]
@zentol Thanks a lot for the explanation. Make sense to me.
LGTM. :+1:

**Pull request merged**
