### PR TITLE
[FLINK-2242] deprecate RemoteCollector interface and implementation

### PR DESCRIPTION
**Pull request by mxm**

### CODE REVIEW

**Comment by StephanEwen** [comment]
+1

I would go as far as to remove it, as this will work in a very limited way and requires direct client to TaskManager communication.

`DataSet.collect()` should fully subsume this.

**Comment by uce** [comment]
I've opened the issue to deprecate, but I think removing is good. +1 to remove as well.

**Comment by mxm** [comment]
I would prefer deprecating it first and removing it in the next major release. If we would do so we should create a JIRA issue to keep track of removing it for the future release.

**Comment by StephanEwen** [comment]
Looks good, merging this...

**Pull request closed without merging**
