### PR TITLE
[FLINK-5497] remove duplicated tests

### PR DESCRIPTION
**Pull request by xhumanoid**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [ ] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [ ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

Hi, I did work:
1) extract testSpillingHashJoinWithMassiveCollisions to separate class ReOpenableHashTableITCase. Test ran 2 times in every classes, total 4 times by 17s each
2) extract common code from ReusingReOpenableHashTableITCase and NonReusingReOpenableHashTableITCase to base class ReOpenableHashTableTestBase. Difference between tests only in types of JoinIterators, all other staff for preparing tests the same

### CODE REVIEW

**Comment by xhumanoid** [comment]
@aljoscha  @rmetzger

**Comment by StephanEwen** [comment]
Thanks you for the effort to increase testing performance.

 I think we have to look very closely here, because it may easily decrease the test coverage. I think there were subtle differences between the tests concerning reusability of result holder objects.
The hash table classes are at the core of many DataSet operations and had subtle bugs before that we caught and fixed by massively expanding test coverage. We must absolutely preserve that.

That being said, removing exact duplicates makes total sense - we simply need to double check that these are in fact exact duplicates and not fuzzy duplicates.

**Comment by xhumanoid** [comment]
@StephanEwen 
Hi, I did check more than double time

This two part of code fully equals:

```java
Tuple2<Integer, Integer> record;
final Tuple2<Integer, Integer> recordReuse = new Tuple2<>();

if (record = buildSide.next(recordReuse)  != null ) { .. }
while (record = buildSide.next(record)  != null ) { .. } 
```

```java
Tuple2<Integer, Integer> record;		
final Tuple2<Integer, Integer> recordReuse = new Tuple2<>();

if (record = buildSide.next(recordReuse)  != null ) { .. }
while (record = buildSide.next(recordReuse)  != null ) { .. }
```

after `if` record and recordReuse are pointing to one object.

Other point it's comment:
'This test is basically identical to the "testSpillingHashJoinWithMassiveCollisions" test, only that the number', 
but when @aljoscha did refactoring (2 years ago) he replaced record =>  recordReuse for one function (both place), but for second function replaced only in one place.

p.s. i spent evening until unraveled this code from first commits =\

**Comment by StephanEwen** [comment]
Thanks!
I will try to get to this in the remainder of the week.
Speeding up builds is a valuable thing :-)

**Comment by StephanEwen** [comment]
Okay, I finally found the time to double check this.

The changes are good, merging this...

**Comment by StephanEwen** [comment]
Thank you for fixing this!

**Pull request closed without merging**
