### PR TITLE
[FLINK-4269] Decrease log level in RuntimeMonitorHandler

### PR DESCRIPTION
**Pull request by aditivin**
@uce - I changed the log level to DEBUG in RuntimeMonitorHandler. 

PS - This is my first contribution, please forgive any mistakes :)

### CODE REVIEW

**Comment by nssalian** [comment]
Hi @aditivin , welcome to the community. Thank you for the PR as well.
A few suggestions:
1) Upon opening a PR, it is best to add more information regarding testing or even checks that you have done.
I believe the PR template helps add more information with regards to testing /checks.

2) I don't see much testing that can be done here, anything you see that can help testing the debug logging, @aditivin?

3) One additional point would be to enable the travis build on your repository.
 (As Flink comes with a travis.yml all you need to do is to go to Travis, login with your github user and hit enable on the repo.) A local build helps understand if there are issues that could occur. 
This link should be helpful: https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo

**Comment by zentol** [comment]
+1 to merge.

Just for future considerations: The Flink community uses rebasing instead of merging branches to avoid these pesky merge commits. :)

**Comment by aditivin** [comment]
Thanks @nssalian , @zentol - I'll keep the points in mind for next time.

I will try testing the logging and update this thread. Also, I've enabled travis in my repository :)

**Comment by zentol** [comment]
Please don't spend your time to write an actual test for this; for this change it is not necessary.

**Comment by zentol** [comment]
merging

**Pull request closed without merging**
