### PR TITLE
[FLINK-1874] [streaming] Connector breakup

### PR DESCRIPTION
**Pull request by mbalassi**
Connectors separated into maven modules, named e.g. flink-kafka-connector. 

Plus an additional commit to remove the flume connector from the docs for the next release as it is mostly commented out currently and I do not see it as a priority to be fixed before the release.

### CODE REVIEW

**Comment by rmetzger** [comment]
Great, thank you for fixing this.
I'll soon review it!

**Comment by rmetzger** [comment]
I'm not so sure about the module names.
The parent is called.
`flink-streaming-connectors-parent`
The modules itself are called:
```diff
+	<modules>
+		<module>flink-flume-connector</module>
+		<module>flink-kafka-connector</module>
+		<module>flink-rabbitmq-connector</module>
+		<module>flink-twitter-connector</module>
+	</modules>
```

It would be more logical to call them:
`flink-streaming-connectors-flume`, `flink-streaming-connectors-kafka`.

Including `streaming` into the name would make it clear that these connectors are not usable with the batch system.
For `kafka` we might want to provide a batch source at some point (we do already through the kafka hadoop input format).

I think I'm slightly in favor of calling them `flink-streaming-connectors-flume`.
Any other opinions?

**Comment by StephanEwen** [comment]
Should we so clearly differentiate between the streaming and the batch connector projects?

Why not have a `flink-connector-kafka` that contains both a batch and a streaming source? They will probably share a lot of code anyways.

Long term, when the streaming API supports batch API data sources (as bounded streams), this will come as a natural fit.

**Comment by mbalassi** [comment]
I added the `parent` suffix to the main pom, because that is how we tend to name modules not containing source code themselves. Then I have realized that the name is becoming too long and partially irrelevant for the reasons Stephan mentioned.

I'd go for `flink-connector-kafka` then and have the modules in streaming for now.

**Comment by rmetzger** [comment]
Okay, I agree with you that we can name the modules the way marton suggested it.

**Comment by mbalassi** [comment]
Thanks, merging as soon as travis verifies.

**Pull request closed without merging**
