### PR TITLE
[FLINK-7654][RabbitMQ Connector] Update RabbitMQ Java client to 4.2.0 

### PR DESCRIPTION
**Pull request by yew1eb**
## What is the purpose of the change

RabbitMQ Java Client: 
Starting with 4.0, this client releases are independent from RabbitMQ server releases.
These versions can still be used with RabbitMQ server 3.x.

## Brief change log

  - *Change rabbitmq version from 3.3.1 to 4.2.0*
  - *Modify exception handling*
  - *Modify the package path for the RMQSinkTest class*
  - *Update the license description in README.md*

## Verifying this change

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: ( no )
  - The runtime per-record code paths (performance sensitive): ( no )
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: ( no )

## Documentation

  - Does this pull request introduce a new feature? ( no)

### CODE REVIEW

**Comment by yew1eb** [comment]
cc @tzulitai

**Comment by yew1eb** [comment]
@tzulitai Hi Gordon, can you please take a look at this PR?

**Comment by tzulitai** [comment]
Hi @yew1eb! Thank you for working on this.

Since this is a dependency update, could you provide information on what additional transitive dependencies this upgrade may have pulled in? Also, was this change also verified / checked on a cluster execution?

If the above has been checked, I think this LGTM.

**Comment by yew1eb** [comment]
@tzulitai, Thank you. I will follow  your suggestion.

**Comment by tzulitai** [comment]
Thanks and feel free to ping me to keep me updated.

**Comment by yew1eb** [comment]
Hey @tzulitai, The 4.2.0 version does not bring any other dependencies, we can safely upgrade.

```
[INFO] |  +- org.apache.flink:flink-shaded-guava:jar:18.0-1.0:provided
[INFO] |  +- org.apache.commons:commons-math3:jar:3.5:provided
[INFO] |  \- org.apache.sling:org.apache.sling.commons.json:jar:2.0.6:provided
[INFO] +- com.rabbitmq:amqp-client:jar:4.2.0:compile
[INFO] +- org.apache.flink:flink-streaming-java_2.11:test-jar:tests:1.4-SNAPSHOT:test
[INFO] +- org.apache.flink:flink-runtime_2.11:test-jar:tests:1.4-SNAPSHOT:test
[INFO] |  +- org.apache.flink:flink-java:jar:1.4-SNAPSHOT:provided
[INFO] |  +- org.apache.flink:flink-shaded-hadoop2:jar:1.4-SNAPSHOT:provided
```


## Check RabbitMQ Sink & Source

### Start a RabbitMQ(3.6.12)server on docker.
```
docker run -d --name rabbitmq --publish 5671:5671 \
 --publish 5672:5672 --publish 4369:4369 --publish 25672:25672 --publish 15671:15671 --publish 15672:15672 \
rabbitmq:management
```


### WriteRabbitMQ job
```
        final RMQConnectionConfig connectionConfig = new RMQConnectionConfig.Builder()
                .setHost("localhost")
                .setPort(5672)
                .setVirtualHost("flink")
                .setPassword("guest")
                .setUserName("guest")
                .build();

        DataStream<String> tsSource = env.addSource(
                new SimpleStringGenerator(500));

        tsSource.addSink(new RMQSink<String>(
                connectionConfig,            // config for the RabbitMQ connection
                "flink",                 // name of the RabbitMQ queue to send messages to
                new SimpleStringSchema()));

```
### ReadRabbitMQ job
 ```
       final RMQConnectionConfig connectionConfig = new RMQConnectionConfig.Builder()
                .setHost("localhost")
                .setPort(5672)
                .setVirtualHost("flink")
                .setPassword("guest")
                .setUserName("guest")
                .build();

        DataStream<String> tsSource = env.addSource(new RMQSource<String>(connectionConfig, "flink",                 // name of the RabbitMQ queue to send messages to
                false, new SimpleStringSchema()));

        tsSource.addSink(new PrintSinkFunction<String>());

```

I observed rabbitmq admin UI and flink UI, the message was normally received and sent, no exception log.

**Comment by yew1eb** [comment]
CC @tzulitai

**Comment by tzulitai** [comment]
Thanks for the verifications @yew1eb, will merge this then.

**Pull request closed without merging**
