### PR TITLE
[FLINK-18694] Add unaligned checkpoint config to web ui

### PR DESCRIPTION
**Pull request by kbohinski**
## What is the purpose of the change

* Show in web ui if unaligned checkpoints are enabled.

## Brief change log

* Adds unaligned checkpoint config to REST endpoint, and web ui.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no) No
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no) No
  - The serializers: (yes / no / don't know) No
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know) No
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / no / don't know) No
  - The S3 file system connector: (yes / no / don't know) No

## Documentation

  - Does this pull request introduce a new feature? (yes / no) No
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by kbohinski** [comment]
https://issues.apache.org/jira/browse/FLINK-18694

@flinkbot run azure

**Comment by kbohinski** [comment]
@flinkbot run azure

**Comment by kbohinski** [comment]
Hey @rmetzger not sure what to do with build output.

**Comment by rmetzger** [comment]
This is the error the CI system is reporting
```
2020-07-23T23:08:09.6743463Z java.lang.AssertionError: The API was modified in a compatible way, but the snapshot was not updated. To update the snapshot, re-run this test with -Dgenerate-rest-snapshot being set.
2020-07-23T23:08:09.6743967Z 	at org.junit.Assert.fail(Assert.java:88)
2020-07-23T23:08:09.6744412Z 	at org.apache.flink.runtime.rest.compatibility.RestAPIStabilityTest.assertCompatible(RestAPIStabilityTest.java:130)
2020-07-23T23:08:09.6745021Z 	at org.apache.flink.runtime.rest.compatibility.RestAPIStabilityTest.testDispatcherRestAPIStability(RestAPIStabilityTest.java:89)
2020-07-23T23:08:09.6745500Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-07-23T23:08:09.6745859Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-07-23T23:08:09.6746312Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-07-23T23:08:09.6746694Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-07-23T23:08:09.6747087Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
2020-07-23T23:08:09.6747652Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2020-07-23T23:08:09.6748116Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
2020-07-23T23:08:09.6748585Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2020-07-23T23:08:09.6749500Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
2020-07-23T23:08:09.6750017Z 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
2020-07-23T23:08:09.6750377Z 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
2020-07-23T23:08:09.6750806Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
2020-07-23T23:08:09.6751258Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
2020-07-23T23:08:09.6751684Z 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
2020-07-23T23:08:09.6752056Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
2020-07-23T23:08:09.6752541Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
2020-07-23T23:08:09.6752928Z 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
2020-07-23T23:08:09.6753423Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
2020-07-23T23:08:09.6753812Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
2020-07-23T23:08:09.6754164Z 	at org.junit.runners.Suite.runChild(Suite.java:128)
2020-07-23T23:08:09.6754501Z 	at org.junit.runners.Suite.runChild(Suite.java:27)
2020-07-23T23:08:09.6754840Z 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
2020-07-23T23:08:09.6755235Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
2020-07-23T23:08:09.6755622Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
2020-07-23T23:08:09.6756196Z 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
2020-07-23T23:08:09.6756577Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
2020-07-23T23:08:09.6756960Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
2020-07-23T23:08:09.6757547Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
2020-07-23T23:08:09.6758228Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
2020-07-23T23:08:09.6758721Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
2020-07-23T23:08:09.6759199Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
2020-07-23T23:08:09.6759684Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
2020-07-23T23:08:09.6760199Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
2020-07-23T23:08:09.6760655Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
2020-07-23T23:08:09.6761096Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```
I guess you need to follow the instructions. The command will create some changes locally that you have to commit as part of this PR.

**Comment by kbohinski** [comment]
Ah sorry, thought it had to do with azure command. Sorry & thx!

**Comment by kbohinski** [comment]
@flinkbot run azure

**Comment by AHeise** [comment]
Thank you very much for your contribution. I'm going to try it out locally and do a review then, but it already looks very good.

**Comment by rmetzger** [comment]
@AHeise thanks a lot for reviewing the change! I'm happy to merge it once you approve the change.

**Comment by kbohinski** [comment]
Great! Sorry I chose “Not enabled” as I thought “Disabled” may have a user thinking it’s optimal to enable it, will change. When is the freeze? I can try at it this weekend.

**Comment by AHeise** [comment]
> Great! Sorry I chose “Not enabled” as I thought “Disabled” may have a user thinking it’s optimal to enable it, will change. When is the freeze? I can try at it this weekend.

Nothing to be sorry about ;). But I'd assume users would not blindly enable a feature, so I'd go with consistency.

Freeze is 2-3 months away (exact date still up to debate) as we just had Flink 1.11. So nothing time-critical. The other ticket would also be a separate PR. So it's independent of this PR where only the label needs to be renamed.

We could, of course, also think about back-porting this PR and the ticket to 1.11. I guess it's small enough to not count as a feature, but it's also not a bugfix. WDYT @rmetzger ?

**Comment by rmetzger** [comment]
> We could, of course, also think about back-porting this PR and the ticket to 1.11. I guess it's small enough to not count as a feature, but it's also not a bugfix. WDYT @rmetzger ?

I would prefer to keep it out. We try to keep the changes in bugfix releases as small as possible to maintain stability. And this is indeed not really a fix.

**Review by AHeise — APPROVED** [review]
LGTM. Thank you for your contribution.

Could you please squash everything into one commit with appropriate commit message (could be copied from ticket) before @rmetzger merges?

**Comment by rmetzger** [comment]
Yes, I'll squash and merge this (soon).

**Comment by zhijiangW** [comment]
As @rmetzger is on vacation, I will take care to merge it directly.

**Comment by zhijiangW** [comment]
BTW, do we also need this fix for release-1.11.0, @AHeise ?

**Comment by rmetzger** [comment]
Thanks for merging this @zhijiangW. I personally believe we should not backport this to 1.11, as this is not a bugfix, rather a small improvement.

**Comment by kbohinski** [comment]
Hi @AHeise 

Getting started on https://issues.apache.org/jira/browse/FLINK-18851

I finished the rest portion but I wanted to ask the least altering way to get the info to the api

I was thinking of adding a new enum `UNALIGNED_CHECKPOINT` to https://github.com/apache/flink/blob/master/flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointType.java

I started down this path but it seems I would need to make a lot of edits all over the project to support this. Any better suggestions?

Thanks!

**Comment by kbohinski** [comment]
Actually looks like I can just update CheckpointStatsTracker.

**Comment by AHeise** [comment]
Hey @kbohinski , thank you very much for starting this, but the ticket is currently assigned to someone else. It would be good to clarify first if there is already some progress to avoid duplicate work. Let's go to the ticket.

**Pull request merged**
