### PR TITLE
[FLINK-3965] [gelly] Delegating GraphAlgorithm

### PR DESCRIPTION
**Pull request by greghogan**
A DelegatingGraphAlgorithm wraps a GraphAlgorithm result with a delegating proxy object. The delegated object can be replaced when the same algorithm is run on the same input with a mergeable configuration. This allows algorithms to be composed of implicitly reusable algorithms without publicly sharing intermediate DataSets.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Sounds very interesting. Can you explain a bit more (at an example maybe) what this does?
I think I lack the background to understand this simply from the description here.

**Comment by greghogan** [comment]
There is more discussion in the ticket description, but for Gelly the idea is to keep algorithms small and discrete yet not duplicate computation.

My first take on this merely cached algorithm outputs and if the configurations were "equal" would use the prior result.

This second take is able to merge configurations which is much more powerful. We can do this because `DataSet`s are lazily evaluated and we can replace the old `DataSet` when we want to change how we generate the result. We "replace" the `DataSet` by actually wrapping it in a proxy class for which the `MethodHandler` always defers to the replaceable `DataSet`.

**Comment by greghogan** [comment]
@StephanEwen do you think this is a good and proper strategy?

**Comment by StephanEwen** [comment]
I see no problem with merging this, from a code perspective.

I do not completely get all the mechanics and reasoning behind this, so would be great if @vasia could comment on this.

**Comment by vasia** [comment]
Hi,
I don't completely get the reasoning either, but it sounds interesting indeed!
@greghogan, could you maybe clarify the following for me:
- What do you mean by "mergeable" configuration? Can you give an example?
- Is the `DelegatingGraphAlgorithm` intended for internal Gelly use, i.e. for the library implementations or is this something that we'd expose to Gelly users as another abstraction?

I know that I haven't been very active during the past weeks, but I see that we now have merged also a `GraphAnalytic` and `AbstractGraphAnalytic` in addition to the existing `GraphAlgorithm` and we also have "Graph Algorithms" under `org.apache.flink.graph.asm` according to the docs. To be honest, I don't completely understand the differences among all of these abstractions and I'm a bit worried we might confuse users.

**Comment by greghogan** [comment]
Hi @vasia,

Configurations can be merged if there exists a configuration which satisfies all configuration constraints. It is left to the algorithm to decide whether and how to merged the values.

I see the library algorithms as exemplars for and inspiration to Gelly users.

A `GraphAnalytic` encapsulates accessing computed values via accumulators after execution. Do you think this functionality could be added to `GraphAlgorithm`?

**Comment by vasia** [comment]
I've had an offline discussion with @greghogan about this. We won't be advertising `DelegatingGraphAlgorithm` as a user-facing feature. +1 from me!

**Pull request closed without merging**
