### PR TITLE
[FLINK-2540] [optimizer] [runtime] Propagate union batch exchanges to union inputs

### PR DESCRIPTION
**Pull request by uce**
The DataExchangeMode of union nodes was not respected when translating an OptimizedPlan to a JobGraph. This could result in deadlocks, when a branched data flow was closed.

Union nodes with a batch exchange will propagate their exchange mode to all inputs of their inputs when the JobGraph is generated.

This PR adds a test for this and propagates the data exchange mode of union nodes to their input in the JobGraphGenerator.

### CODE REVIEW

**Comment by tillrohrmann** [comment]
Is it intended that this PR is based on FLINK-2398?

**Comment by StephanEwen** [comment]
Other then the branch mixup, this looks good.

Will test it and merge it, if it works...

**Comment by StephanEwen** [comment]
Ah, the github mirror is out of sync again - that's why this pull request includes bac21bf5d77c8e15c608ecbf006d29e7af1dd68a again (which is in the apache master, but not in the github mirror).

**Comment by StephanEwen** [comment]
Merging this, looks good, test works and catches the problematic condition!

**Pull request closed without merging**
