### PR TITLE
[FLINK-19651][Connectors/JDBC] Support the filter push down for the JDBC connector

### PR DESCRIPTION
**Pull request by zhuyufeng0809**
## What is the purpose of the change

Support the filter push down for the JDBC connector

## Brief change log

Add some classes to convert expression

## Verifying this change

it works in my company production

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by zhuyufeng0809** [comment]
@flinkbot run azure

**Comment by MartijnVisser** [comment]
@zhuyufeng0809 @qingwei91 We now have the situation that there are two identical Jira tickets with FLINK-16024 (which was there first) and FLINK-19651 (which is a duplicate). Both have PRs. 

Can you collaborate to get to one PR? I do like that https://github.com/apache/flink/pull/20140 has new tests, which is very much appreciated.

**Comment by zhuyufeng0809** [comment]
Thanks @MartijnVisser  , the test of #2005 was really good. Can you review the two PRs first and give some opinions, I think we can extract the advantages of both PRs and refactor them into one PR

**Comment by qingwei91** [comment]
Hi @zhuyufeng0809 shall we sync up and discuss what to do?
I am in London, so my time zone would be GMT+1, if you're in a similar timezone maybe we can have a call?

**Comment by libenchao** [comment]
@zhuyufeng0809 Sorry that I noticed this issue and PR just now (after I merged https://github.com/apache/flink/pull/20140 and closed https://issues.apache.org/jira/browse/FLINK-16024). I really appreciate your work, but now we have to close this PR since it has been implemented.

**Pull request closed without merging**
