### PR TITLE
Fixed Vertex Degree algorithm implementation

### PR DESCRIPTION
**Pull request by MattePalte**
After a comparison with iGraph for Python I noticed that the algorithm didn't return the right value in terms of degree.
The degree should be the sum of all incident edge therefore: degree = indegree + outdegree. https://en.wikipedia.org/wiki/Degree_(graph_theory) . The problem with the previous version was that the degree was not correctly computed because the if the vertex A had a incoming edge and an outgoing edge towards the same vertex B it was counted only 1 in the computation of degree of vertex A. To fix it I proposed simply to increase the counter of degree variable every time that we have an increase of outDegree or inDegree.

## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by greghogan** [comment]
Thanks @MattePalte. I think the current "degree" count is still useful. Perhaps this could be named an "undirected degree" and the new "in + out" plain "degree" computed when the result field is accessed.

**Comment by MattePalte** [comment]
Yes, it could be definitely useful @greghogan . The only problem that could arise is that we are in the package for directed graph, therefore it might sound confusing to see an undirected thing, but anyway there might be someone interested in it. It's up to you, your point is reasonable.

**Comment by rmetzger** [comment]
This change causes the CI tests for gelly to fail
```
21:29:53.138 [ERROR] Failures: 
21:29:53.138 [ERROR]   EdgeDegreesPairTest.testWithRMatGraph:85 expected:<25769422553763> but was:<25726306338944>
21:29:53.138 [ERROR]   EdgeSourceDegreesTest.testWithRMatGraph:85 expected:<24344780464601> but was:<24072788429071>
21:29:53.138 [ERROR]   EdgeTargetDegreesTest.testWithRMatGraph:85 expected:<24236304419969> but was:<23961992270548>
21:29:53.138 [ERROR]   VertexDegreesTest.testWithRMatGraph:118 expected:<1800402753642> but was:<1769121685180>
21:29:53.138 [ERROR]   VertexDegreesTest.testWithUndirectedSimpleGraph:70 Different elements in arrays: expected 6 elements and received 6
 expected: [(0,(2,2,2)), (1,(3,3,3)), (2,(3,3,3)), (3,(4,4,4)), (4,(1,1,1)), (5,(1,1,1))]
 received: [(0,(4,2,2)), (1,(6,3,3)), (2,(6,3,3)), (3,(8,4,4)), (4,(2,1,1)), (5,(2,1,1))] expected:<(0,([2],2,2))> but was:<(0,([4],2,2))>
21:29:53.138 [ERROR]   AverageClusteringCoefficientTest.testWithCompleteGraph:63->validate:52 expected:<1.0> but was:<0.24725274725274754>
21:29:53.138 [ERROR]   AverageClusteringCoefficientTest.testWithRMatGraph:78->validate:52 expected:<0.329437> but was:<0.30570018163337975>
21:29:53.138 [ERROR]   GlobalClusteringCoefficientTest.testWithCompleteGraph:66->validate:52 expected:<48645> but was:<196742>
21:29:53.138 [ERROR]   GlobalClusteringCoefficientTest.testWithRMatGraph:81->validate:52 expected:<1003442> but was:<1588939>
21:29:53.138 [ERROR]   LocalClusteringCoefficientTest.testCompleteGraph:90->validate:80 expected:<46> but was:<92>
21:29:53.138 [ERROR]   LocalClusteringCoefficientTest.testRMatGraph:113 expected:<1922057004917> but was:<1896417809662>
21:29:53.138 [ERROR]   TriadicCensusTest.testWithCompleteGraph:70 expected:<003: 0; 012: 0; 102: 0; 021d: 0; 021u: 0; 021c: 0; 111d: 0; 111u: 0; 030t: 0; 030c: 0; 201: 0; 120d: 0; 120u: 0; 120c: 0; 210: 0; 300: 16,215> but was:<003: 99,452; 012: -296,194; 102: 48,645; 021d: 48,645; 021u: 48,645; 021c: 99,452; 111d: 0; 111u: 0; 030t: 0; 030c: 0; 201: -48,645; 120d: 0; 120u: 0; 120c: 0; 210: 0; 300: 16,215>
21:29:53.138 [ERROR]   TriadicCensusTest.testWithDirectedRMatGraph:129 expected:<003: 113,435,893; 012: 6,632,528; 102: 983,535; 021d: 118,574; 021u: 118,566; 021c: 237,767; 111d: 129,773; 111u: 130,041; 030t: 16,981; 030c: 5,535; 201: 43,574; 120d: 7,449; 120u: 7,587; 120c: 15,178; 210: 17,368; 300: 4,951> but was:<003: 112,611,090; 012: 7,775,566; 102: 79,803; 021d: 372,130; 021u: 371,578; 021c: 747,469; 111d: -47,444; 111u: -47,720; 030t: 16,981; 030c: 5,535; 201: -32,221; 120d: 7,449; 120u: 7,587; 120c: 15,178; 210: 17,368; 300: 4,951>
21:29:53.138 [ERROR]   TriadicCensusTest.testWithUndirectedRMatGraph:103 expected:<003: 113,435,893; 012: 0; 102: 7,616,063; 021d: 0; 021u: 0; 021c: 0; 111d: 0; 111u: 0; 030t: 0; 030c: 0; 201: 778,295; 120d: 0; 120u: 0; 120c: 0; 210: 0; 300: 75,049> but was:<003: 107,069,303; 012: 10,726,296; 102: 225,147; 021d: 1,003,442; 021u: 1,003,442; 021c: 2,027,768; 111d: 0; 111u: 0; 030t: 0; 030c: 0; 201: -225,147; 120d: 0; 120u: 0; 120c: 0; 210: 0; 300: 75,049>
21:29:53.138 [ERROR]   TriadicCensusTest.testWithUndirectedSimpleGraph:45 expected:<003: 3; 012: 0; 102: 8; 021d: 0; 021u: 0; 021c: 0; 111d: 0; 111u: 0; 030t: 0; 030c: 0; 201: 7; 120d: 0; 120u: 0; 120c: 0; 210: 0; 300: 2> but was:<003: 28; 012: -76; 102: 6; 021d: 13; 021u: 13; 021c: 40; 111d: 0; 111u: 0; 030t: 0; 030c: 0; 201: -6; 120d: 0; 120u: 0; 120c: 0; 210: 0; 300: 2>
21:29:53.138 [ERROR]   EdgeMetricsTest.testWithCompleteGraph:67->validate:50 expected:<triangle triplet count: 16,215; rectangle triplet count: 32,430; maximum triangle triplets: 1,035; maximum rectangle triplets: 1,035> but was:<triangle triplet count: 16,215; rectangle triplet count: 82,156; maximum triangle triplets: 1,035; maximum rectangle triplets: 3,151>
21:29:53.138 [ERROR]   EdgeMetricsTest.testWithRMatGraph:82->validate:50 expected:<triangle triplet count: 107,817; rectangle triplet count: 315,537; maximum triangle triplets: 820; maximum rectangle triplets: 3,822> but was:<triangle triplet count: 107,859; rectangle triplet count: 375,343; maximum triangle triplets: 820; maximum rectangle triplets: 4,756>
21:29:53.138 [ERROR]   VertexMetricsTest.testWithCompleteGraph:75->validate:55 expected:<vertex count: 47; edge count: 2,162; unidirectional edge count: 0; bidirectional edge count: 1,081; average degree: 46; density: 1; triplet count: 48,645; maximum degree: 46; maximum out degree: 46; maximum in degree: 46; maximum triplets: 1,035> but was:<vertex count: 47; edge count: 2,162; unidirectional edge count: 2,162; bidirectional edge count: 0; average degree: 46; density: 1; triplet count: 196,742; maximum degree: 92; maximum out degree: 46; maximum in degree: 46; maximum triplets: 4,186>
21:29:53.138 [ERROR]   VertexMetricsTest.testWithRMatGraph:94->validate:55 expected:<vertex count: 902; edge count: 12,009; unidirectional edge count: 8,875; bidirectional edge count: 1,567; average degree: 13.314; density: 0.01477663; triplet count: 1,003,442; maximum degree: 463; maximum out degree: 334; maximum in degree: 342; maximum triplets: 106,953> but was:<vertex count: 902; edge count: 12,009; unidirectional edge count: 12,009; bidirectional edge count: 0; average degree: 13.314; density: 0.01477663; triplet count: 1,588,939; maximum degree: 676; maximum out degree: 334; maximum in degree: 342; maximum triplets: 228,150>
21:29:53.138 [INFO] 
21:29:53.138 [ERROR] Tests run: 623, Failures: 19, Errors: 0, Skipped: 0
```

If we want to merge this, we should file a JIRA ticket, include the ticket id in the commit and adapt the CI tests.
Sorry @MattePalte that our contribution process is not super straightforward :( We have quite a few processes and tests in place to ensure stability of Flink.

**Comment by rmetzger** [comment]
I'm closing this PR as it seems to be stale. Please re-open if you want to continue working on it.

**Pull request closed without merging**
