### PR TITLE
[FLINK-9666] short-circuit logic should be used in boolean contexts

### PR DESCRIPTION
**Pull request by lamber-ken**
## What is the purpose of the change
  - short-circuit logic should be used in boolean contexts, | -> ||, & -> &&

## Brief change log

  - short-circuit logic should be used in boolean contexts, | -> ||, & -> &&

## Verifying this change

  - short-circuit logic should be used in boolean contexts, | -> ||, & -> &&

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (JavaDocs)

### CODE REVIEW

**Comment by lamber-ken** [comment]
hi, @StephanEwen, cc, thx

**Comment by lamber-ken** [comment]
hi, @StephanEwen, @tillrohrmann cc.

**Comment by lamber-ken** [comment]
hi, @tillrohrmann , what does this mean? 
I don't understand, need I delete the branch?
image

**Comment by tillrohrmann** [comment]
Not sure where this comes from. But I've merged your commit into the master. See da37daa8ba.

**Comment by lamber-ken** [comment]
hi, @tillrohrmann, if you don't know, I'll ignore it. it's no problem, :smiley: 

This information is always displayed at the bottom of the page. here's it.

image

**Comment by lamber-ken** [comment]
maybe it's a bug

**Comment by zentol** [comment]
@lamber-ken This happened because @tillrohrmann modified the commit message to close the PR, which modified the commit hash.
As such, from GitHubs perspective, the PR was closed without the contained commit (as identified be the hash) being merged.

**Comment by lamber-ken** [comment]
@zentol, ok

**Pull request closed without merging**
