### PR TITLE
[FLINK-3800] [jobmanager] Terminate ExecutionGraphs properly

### PR DESCRIPTION
**Pull request by tillrohrmann**
This PR terminates the ExecutionGraphs properly without restarts when the JobManager calls
cancelAndClearEverything. It is achieved by allowing the method to be only called with an
SuppressRestartsException. The SuppressRestartsException will disable the restart strategy of
the respective ExecutionGraph. This is important because the root cause could be a different
exception. In order to avoid race conditions, the restart strategy has to be checked twice
whether it allows to restart the job: Once before and once after the job has transitioned to
the state RESTARTING. This avoids that ExecutionGraphs can become orphans.

Furthermore, this PR fixes the problem that the default restart strategy is shared by multiple
jobs. The problem is solved by introducing a RestartStrategyFactory which creates for every
job its own instance of a RestartStrategy.

- [X] General
  - The pull request references the related JIRA issue
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message

- [X] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by uce** [comment]
Good fix, Till! Changes look good, +1 to merge soon for 1.0.3.

**Comment by rmetzger** [comment]
Code looks good.
It seems that the test is still a bit unstable:
```
Tests in error: 
  LeaderChangeJobRecoveryTest.before:73 Â» Timeout Futures timed out after [10000...
```
in 3 of 5 runs: 
https://s3.amazonaws.com/archive.travis-ci.org/jobs/124781545/log.txt
https://s3.amazonaws.com/archive.travis-ci.org/jobs/124781546/log.txt
https://s3.amazonaws.com/archive.travis-ci.org/jobs/124781547/log.txt

**Comment by tillrohrmann** [comment]
Maybe I have to increase the timeout for Travis here. Will do it.

**Comment by uce** [comment]
The build fails with timeouts while waiting for the TMs to connect again. This is weird as the changes look unrelated to this. Do you have an idea what this might be?

**Comment by tillrohrmann** [comment]
I increased the timeouts another time. Maybe the timeout was still set too low. Let's see.

**Comment by tillrohrmann** [comment]
Unrelated test case failures. Will be merging this PR to master and the 1.0-release branch.

**Pull request closed without merging**
