### PR TITLE
[FLINK-25576][Connectors][JDBC] Upgrade com.h2database:h2 to 2.0.206

### PR DESCRIPTION
**Pull request by MartijnVisser**
## What is the purpose of the change

* Update com.h2database:h2 to latest version, 2.0.206

## Brief change log

* Updated POM with new version number

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): yes
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Comment by alpreu** [comment]
@flinkbot run azure

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Review by alpreu — APPROVED** [review]

**Comment by MartijnVisser** [comment]
@fapaul Can you merge? I'll also create a backport for 1.14 and 1.13 (to be sure)

**Pull request merged**
