### PR TITLE
[FLINK-28985][table]Create table statement supports create table like view

### PR DESCRIPTION
**Pull request by waywtdcc**
## What is the purpose of the change

*Support language: create table  like view, in jira :https://issues.apache.org/jira/projects/FLINK/issues/FLINK-28985*

## Brief change log
*Support language: create table  like view*

## Verifying this change

  - *org.apache.flink.table.planner.operations.SqlCreateTableConverter#lookupLikeSourceTable*
  - *org.apache.flink.table.planner.operations.SqlToOperationConverterTest#testCreateTableLikeViewWithFullPath*
  

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by waywtdcc** [comment]
@flinkbot run azur

**Comment by waywtdcc** [comment]
@flinkbot run azure

**Comment by waywtdcc** [comment]
@flinkbot run azure

**Comment by waywtdcc** [comment]
@JingsongLi hi,WDYT?

**Comment by MartijnVisser** [comment]
@waywtdcc You should make sure that you first have your PR passes the CI build and is mergable. As, since this would involve exposing new SQL syntax to the user, it would probably require a FLIP and a vote.

**Pull request closed without merging**
