### PR TITLE
[FLINK-13062] Set ScheduleMode based on boundedness of streaming Pipeline

### PR DESCRIPTION
**Pull request by aljoscha**
## What is the purpose of the change

The new Blink-based Table Runner needs "streaming pipelines" to be executed with `ScheduleMode.LAZY_FROM_SOURCES` if all sources are bounded. The current Blink code base uses a global flag for this and configures the `StreamGraphGenerator` accordingly.

We propose to add an `isBounded()` property to `Transformation` (formerly known as `StreamTransformation`). The property would only be explicitly settable on sources, other transformations inherit the property from their inputs. The `StreamGraphGenerator` must use `ScheduleMode.LAZY_FROM_SOURCES` if all sources are bounded, otherwise, it should use ScheduleMode.EAGER, as is the currently existing behaviour.

## Brief change log

* ccf6f96 refactors `DataStreamSource` as preparation
* 03aa30b adds the `isBounded()` property to `Transformation`, along with tests for the inheritance logic
* 277c947 adds a new *public* method on `StreamExecutionEnvironment` for adding bounded sources
* c37ffb9 changes `StreamGraphGenerator` to set the `ScheduleMode` based on the newly added boundedness property, along with tests

## Verifying this change

This change added tests and can be verified as follows:

* new tests in 03aa30b for the `isBounded()` property on `Transformation`
* new tests in c37ffb9, i.e in `StreamGraphGeneratorTest`

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? yes, there is a new public API method for adding bounded sources
  - If yes, how is the feature documented? documented in Javadocs, as for now this is more of an under-the-radar featre

### CODE REVIEW

**Comment by aljoscha** [comment]
This is an alternative proposal for #8931 

cc @ifndef-SleePy

**Comment by ifndef-SleePy** [comment]
Wow, It's amazing that you have already finished this proposal!

I have taken a glance at it. I got your point. And I believe it could make planner work for 1.9. Furthermore I need to discuss with the guys who are responsible for planner implementation to make sure it could satisfy their requirements for both 1.9 and the further. Since it's midnight in my timezone, I guess I can't give you feedback until tomorrow :(

**Comment by aljoscha** [comment]
Sure, please take time to sleep! 😃

**Comment by guoweiM** [comment]
Thanks @aljoscha . I think it is ok for BlinkPlanner to choose a proper schedule mode  in 1.9.
I have a little question about how planner set the configuration of runtime.  Sometime a planner might need directly configure the engine to schedule the Job in a specific way. For example there are bounded sources but the planner want use the third scheduling strategy.

My point is we might need a common way to let the planner configure how the engine is execute in the future.  What do you think ?

**Comment by XuPingyong** [comment]
Thanks @aljoscha .  I think boundedness of streaming Pipeline is not related to the streaming/batch behavior. A bounded source(eg. Collection source) can run not only batch job, but also streaming job.

**Comment by aljoscha** [comment]
Another alternative would be to set the `ScheduleMode` based on the `ExecutionMode`, which is already configured in the `ExecutionConfig`.

**Pull request closed without merging**
