### PR TITLE
[hotfix][release-notes] Update release notes for 1.11, 1.12, 1.13 with accumulators semantics change in MiniClusterJobClient

### PR DESCRIPTION
**Pull request by echauchot**
Updating release notes as discussed
R: @tillrohrmann

### CODE REVIEW

**Review by tillrohrmann — APPROVED** [review]
Thanks a lot for creating this PR @echauchot. LGTM. Merging this PR and backporting it to `release-1.13`, `release-1.12` and `release-1.11`.

**Comment by tillrohrmann** [comment]
I think I might have given you bad advice. FLINK-18685 seems to be only fixed in Flink 1.13.0. Hence we only need to update the release docs for 1.13. I will update the PR accordingly.

**Comment by echauchot** [comment]
> I think I might have given you bad advice. [FLINK-18685](https://issues.apache.org/jira/browse/FLINK-18685) seems to be only fixed in Flink 1.13.0. Hence we only need to update the release docs for 1.13. I will update the PR accordingly.

Hi Till, I'm back from vacations, thanks for review / merge. 
The reason why I was updating 1.11, 1.12  and 1.13 is because the jobclient feature commit beae8e7a20dfa915ce02fd3e5186d4b5e71fbbef is present in all 1.11, 1.12 and 1.13 branches not olnly in 1.13 even if the ticket https://issues.apache.org/jira/browse/FLINK-18685 was closed on 1.13

**Comment by tillrohrmann** [comment]
Hmm, @rmetzger only linked a single merge commit and set the fixVersion to `1.13.0`. If this is indeed the case, could you update the JIRA ticket @echauchot?

**Comment by echauchot** [comment]
> Hmm, @rmetzger only linked a single merge commit and set the fixVersion to `1.13.0`. If this is indeed the case, could you update the JIRA ticket @echauchot?

My bad, I was fooled by intellij github plugin search feature. The commit is indeed only in 1.13 so everything is ok.
Sorry for the noise :slightly_smiling_face:

**Pull request closed without merging**
