### PR TITLE
[FLINK-3916] [table] Allow generic types passing the Table API

### PR DESCRIPTION
**Pull request by twalthr**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

This PR reworks the type handling of Flink's TypeInformation to Calcite's RelDataTypes. The new approach allows generic types passing through the Table API and enables improved Pojo field access in future. The PR might also implements parts of FLINK-3615.

### CODE REVIEW

**Comment by twalthr** [comment]
@vasia Could you review the `FlinkPlannerImpl` changes? I changed many lines that you wrote. All test cases are still successful but maybe I forgot something.

**Comment by vasia** [comment]
Thanks for the ping @twalthr! I don't see anything suspicious :)

**Comment by twalthr** [comment]
I would like to merge this if there are no objections. It is a very important improvement.

**Comment by twalthr** [comment]
Merging...

**Pull request merged**
