### PR TITLE
[FLINK-23847][connectors][kafka] improve error message when valueDeseriali…

### PR DESCRIPTION
**Pull request by camilesing**
## What is the purpose of the change

This pull request makes the error msg can be clearer when KafkaConsumer inits, valueDeserializer is null.

`this.deserializer = checkNotNull(deserializer, "valueDeserializer"); `change to `this.deserializer = checkNotNull(deserializer, "valueDeserializer cannot be null");`

## Brief change log
This pull request makes error msg can be clearer when KafkaConsumer init, valueDeserializer is null

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by camilesing** [comment]
@rmetzge  can you review it? thx

**Comment by camilesing** [comment]
@tsreape hi, can you review it? thx

**Comment by camilesing** [comment]
@NicoK hi, can you review it? thx

**Comment by camilesing** [comment]
@NicoK hi, can you review it? thx

**Comment by MartijnVisser** [comment]
@camilesing The Flink Kafka connector resides in it's own repository nowadays, if this code change is still relevant, please open the PR in https://github.com/apache/flink-connector-kafka

**Pull request closed without merging**
