### PR TITLE
FLINK-4462 Add RUN_TIME retention policy for all the flink annotations

### PR DESCRIPTION
**Pull request by ramkrish86**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.
- [ ] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)
- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added
- [ ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

(Ram)

### CODE REVIEW

**Comment by StephanEwen** [comment]
Is that needed? The `japicmp` plugin can work with the annotations without runtime retention. Would be great if that plugin can check the presence of annotations, that seems like the right place.

**Comment by ramkrish86** [comment]
> Would be great if that plugin can check the presence of annotations, that seems like the right place.

I see. I have not worked with 'japicmp'. My intention was to use plain java reflection APIs 

`Annotation[] anns = c.getDeclaredAnnotations();`

I can see if the same can be done with the 'japicmp' too. And if so will close this PR. Thanks @StephanEwen .

**Comment by ramkrish86** [comment]
Is 'jApiCmp' added in class path?  I am not able to see the API/Interfaces exposed. Trying to make use of it.

**Comment by StephanEwen** [comment]
The `japicmp` is a maven plugin that is added to projects like `flink-core`. It is not part of any code.

**Comment by ramkrish86** [comment]
@StephanEwen 
I meant the library only. I did not mean it is added in code. Am not sure what are the APIs in that library to make use.

**Comment by ramkrish86** [comment]
@StephanEwen 
As said above am not sure how to use the japicmp library. I can see that from the IDE am not able to use any of the APIs provided from the library. May be am missing something?
Also reading the docs of japicmp it says how to pass two different versions of a jar file and see what are the public interface differences. So am not sure how japicmp internally does it.
Do you have an problem in adding this RUN_TIME annotation?  I think it helps in adding plain java reflection based utils to idenfity classes/interfaces missing them. 
I can update my PR based on your thoughts on jaipcmp usage.

**Pull request closed without merging**
