### PR TITLE
[FLINK-6582] [docs] Project from maven archetype is not buildable by default

### PR DESCRIPTION
**Pull request by greghogan**
The pom.xml for flink-quickstart-java and flink-quickstart-scala must specify scala.version and scala.binary.version.

### CODE REVIEW

**Comment by greghogan** [comment]
@rmetzger what is happening in `create_release_files.sh:deploy_to_maven`? Are we overwriting the 2.11 quickstart jars with 2.10 jars? Are we still looking to publish against Scala 2.10 rather than 2.11?

**Comment by rmetzger** [comment]
The script is deploying scala 2.10 for the quickstarts, yes.
I think the reason for this is that scala 2.10 is still considered "default" in Flink.

**Comment by greghogan** [comment]
After asking the question I added the second commit which inherits the scala version as is the current / expected behavior.

**Comment by rmetzger** [comment]
the change *looks* good to merge. I'm currently building Flink to quickly try it out

**Comment by rmetzger** [comment]
Not sure what's happening, but when I'm trying to generate a project from the archetype, I'm getting:

```
Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.4:generate (default-cli) on project standalone-pom: The defined artifact is not an archetype 
```

**Comment by greghogan** [comment]
@rmetzger I am seeing the same issue and will look into this.

**Comment by rmetzger** [comment]
Thank you.

**Comment by greghogan** [comment]
@rmetzger latest commit is simpler and tested successfully for java and scala: `mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate -DarchetypeGroupId=org.apache.flink -DarchetypeArtifactId=flink-quickstart-java -DarchetypeCatalog=local -DarchetypeVersion=1.4-SNAPSHOT`.

**Comment by rmetzger** [comment]
Thanks a lot for fixing the issue.

I've tested it again, and it works.
Merging.

**Pull request closed without merging**
