### PR TITLE
[FLINK-4997] [streaming] Introduce ProcessWindowFunction

### PR DESCRIPTION
**Pull request by aljoscha**
This is an updated/enhanced version of #2756.

I did roughly these changes:
 - Add support for the `AggregatingFunction`/`ProcessWindowFunction` combination
 - Mark the new methods/interfaces as `@PublicEvolving`
 - Change how the Scala wrapper functions work because we recently moved all of them to use `WrappingFunction`. This is not complete yet and I created issues for fixing that: https://issues.apache.org/jira/browse/FLINK-5740 and https://issues.apache.org/jira/browse/FLINK-5741
 - Add tests in `WindowTranslationTest.java` and `WindowTranslationTest.scala`.

@VenturaDelMonte and @manuzhang, would you like to have a look at this. I took quite a while because there was some upheaval in the internals of that part of the code and the tests. I'm sorry for that.

### CODE REVIEW

**Comment by VenturaDelMonte** [comment]
I checked the code and it looks fine according to me. I see you are dealing with RichFunction inheritance in wrapper classes. It is something that bothered me too when I was working on the previous PR. Actually there could be a similar minor issue in RichProcessWindowFunction due to duplicate code, however I cannot see any easy workaround for it. 
Regarding the overall feature, are you planning to do anything similar for #2946 or should I reflect these changes also there?

**Comment by manuzhang** [comment]
LGTM. Really excited to see we move further in this direction, and faster if possible.

**Comment by aljoscha** [comment]
@VenturaDelMonte I opened this: https://issues.apache.org/jira/browse/FLINK-5740. I want to make `WrappingFunction` an interface because, as you noted, `RichProcessWindowFunction` does currently not work.

I would merge this then. If you want you can pick up the work on the all-window case again and carry it to an end in the same way. What do you think?

**Comment by VenturaDelMonte** [comment]
Sure, I can take care of the all-window case!

**Pull request closed without merging**
