### PR TITLE
[FLINK-33023][table-planner][JUnit5 Migration] Module: flink-table-planner (TableTestBase)

### PR DESCRIPTION
**Pull request by Jiabao-Sun**
## What is the purpose of the change

[FLINK-33023][table-planner][JUnit5 Migration] Module: flink-table-planner (TableTestBase)
## Brief change log

JUnit5 Migration Module: flink-table-planner (TableTestBase)

## Verifying this change

This change is already covered by existing tests

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by Jiabao-Sun** [comment]
Hi @leonardBang.
Would you mind to help review this PR when you have time?

**Comment by Jiabao-Sun** [comment]
@flinkbot run azure

**Comment by leonardBang** [comment]
@xuyangzhong Would you like to help review this PR?

**Review by xuyangzhong — COMMENTED** [review]
Thank for your huge contribution about replacing junit4 with junit5 in table-planner module. The whole pr looks good to me. I mainly have two confusion.
1. Is it a good time to remove the dependency in module `table-planner` to avoid other contributor continuing using junit4?
2. I found that you spent some time to remove `public` for each test functions. But it is a weak constraint for contributor to following this implicit rule. How to make this rule more visible for contributor? (maybe using custom check style or something else)

**Comment by Jiabao-Sun** [comment]
> Thank for your huge contribution about replacing junit4 with junit5 in table-planner module. The whole pr looks good to me. I mainly have two confusion.
> 
> 1. Is it a good time to remove the dependency in module `table-planner` to avoid other contributor continuing using junit4?
> 2. I found that you spent some time to remove `public` for each test functions. But it is a weak constraint for contributor to following this implicit rule. How to make this rule more visible for contributor? (maybe using custom check style or something else)

Thanks @xuyangzhong for the hard review.
1. Currently we can't remove junit4 dependencies from table-planner, because there are still some tests using Junit4 and have not been migrated to complete. After all the tests are migrated by Junit5, we can do this.
2. I think we can add this check to ARCH Tests, but it may still need to wait until Junit5 is fully migrated.

Please help check it again when you have time.
Thanks again.

**Comment by xuyangzhong** [comment]
LGTM. cc @leonardBang for the final check.

**Review by xuyangzhong — APPROVED** [review]

**Review by leonardBang — APPROVED** [review]
Thanks @Jiabao-Sun for the contribution and @xuyangzhong for the review work, LGTM

**Pull request merged**
