### PR TITLE
[FLINK-6407] [build] Upgrade AVRO to 1.8.2

### PR DESCRIPTION
**Pull request by zhangminglei**
Upgrade to the last maintenance releases of **AVRO** 1.8.2

### CODE REVIEW

**Comment by zhangminglei** [comment]
cc @zentol

**Comment by zentol** [comment]
Please don't cc in on every pull request. Other people do reviews as well.

**Comment by zhangminglei** [comment]
Okay. I remember.

**Comment by greghogan** [comment]
No one has raised an objection to this update and Avro 1.8 is ~18 months old so I'll merge this.

**Comment by zhangminglei** [comment]
Thanks, Greg. You are very welcome.

**Pull request closed without merging**
