### PR TITLE
[FLINK-1450] Added fold operator for the Streaming API

### PR DESCRIPTION
**Pull request by akshaydixi**
Tried to follow the steps described in the JIRA Issue comments:
- Created a FoldFunction and a RichFoldFunction
- Created a StreamFoldInvokable
- Integrated it to the DataStream for both Java and Scala
- Implemented StreamFoldTest based on StreamReduceTest

### CODE REVIEW

**Comment by akshaydixi** [comment]
Thanks @gyfora . I've added fold into GroupedDataStream and WindowedDataStream in subsequent commits.

**Comment by gyfora** [comment]
I added some other minor comments :)


Also if you are interested in taking this one step further there are some possibilities (after I merged this):

 - add combiners/aggregators  (that basically make it possible to apply folds in parallel by using ReduceFunctions), this is mostly applicable for windowing
 - add window PreAggregators for fold operators as well -> even better if we have combiners

I will add some JIRA-s for these, but we should definitely sync on skype or hangout if you decide to go further.

**Comment by akshaydixi** [comment]
Ok @gyfora, thanks for reviewing! 
I picked this issue since it seemed a good way to get a handle of flink-streaming as I'm interested in pursuing FLINK-1534 and FLINK-1617. But I'll be glad to work more on this and try to implement more of the features you've described. They do seem challenging so I'll count on your help in the tougher bits :)

**Comment by gyfora** [comment]
Hey,

I squashed some of your small fix commits to your last, one and also fixed several minor issues:

-I swapped the type parameter order to make the type extraction work properly
-I made the parameter order consistent through the scala and java api
-The GroupedFoldInvokable completely disregarded the first element in the stream (also the test logic for this class was broken)
-And some minor windowing related stuff

I didnt include your last commit since I already added those fixes to yours.

**Comment by akshaydixi** [comment]
Thanks @gyfora. I'll try to not mess up commit history in future contributions!

**Pull request closed without merging**
