### PR TITLE
[FLINK-2357] Add the new web dashboard and monitoring REST API

### PR DESCRIPTION
**Pull request by StephanEwen**
This pull request adds two new big features: The monitoring REST API and the web dashboard.

It is joint work by @iampeter and me (although @iampeter did all the stellar UI wonders, kudos!)

## Web dashboard

The web dashboard is a frontend implemented against the monitoring REST API (see below). Compared to the old web frontend:

 - It combines views about optimizer plan, runtime dataflow, details about vertices and subtasks
 - Has better overview pages that show more information at a glance
 - Shows updating metrics (records, bytes)
 - Shows updating user accumulators
 - Timeline decoupled from online-only library
 - Shows more information about status, exceptions, config
 - Is more structured and maintainable
 - Has a nicer design (personal opinion)

Here is are some teaser screenshots, showing the overview, job dataflow view, and timeline. Clicking on the nodes shows the details about subtasks, etc.

bild1

bild2

bild3

To try it out, make sure you have this entry in the `conf/flink-conf.yaml` file: `jobmanager.new-web-frontend: true`

The dashboard is not complete, yet, it lacks for example TaskManager details and log file access.
Before removing the old web frontend, these missing aspects need to be added.

## Monitoring API

The monitoring API is a REST API that allows you to issue HTTP requests like `http://jobmanager:8081/jobs/7684be6004e4e955c2a558a9bc463f65` to query the status of jobs. The responses are JSON encoded.

It is used by the web dashboard, but can be used to realize custom monitoring tools.

There is a detailed doc describing the capabilities (`docs/internals/monitoring_rest_api.md`), here is a summary list of supported requests:

  - `/config`
  - `/overview`
  - `/jobs`
  - `/joboverview`
  - `/joboverview/running`
  - `/joboverview/completed`
  - `/jobs/<jobid>`
  - `/jobs/<jobid>/config`
  - `/jobs/<jobid>/exceptions`
  - `/jobs/<jobid>/accumulators`
  - `/jobs/<jobid>/vertices`
  - `/jobs/<jobid>/vertices/<vertexid>`
  - `/jobs/<jobid>/vertices/<vertexid>/subtasktimes`
  - `/jobs/<jobid>/vertices/<vertexid>/accumulators`
  - `/jobs/<jobid>/vertices/<vertexid>/subtasks/accumulators`
  - `/jobs/<jobid>/vertices/<vertexid>/subtasks/<subtasknum>`
  - `/jobs/<jobid>/vertices/<vertexid>/subtasks/<subtasknum>/attempts/<attempt>`
  - `/jobs/<jobid>/vertices/<vertexid>/subtasks/<subtasknum>/attempts/<attempt>/accumulators`
  - `/jobs/<jobid>/plan`

### CODE REVIEW

**Comment by rmetzger** [comment]
Very nice.
I tried the new interface locally, and it seems to work.

I suspect these values are still test values? http://i.imgur.com/d9ZRR7g.png
There is certainly more work to do until the web interface has the same features as the old interface (task manager overview / monitoring)

**Comment by StephanEwen** [comment]
Yes, the values you refer to are still placeholders.

I would like to merge this in its current state and improve on it in the master branch. The old frontend is still the default, and this one has to be explicitly activated, to there should be no conflict.

**Comment by rmetzger** [comment]
I agree with this approach, so +1 to merge ;)

**Comment by mxm** [comment]
Your change set is very large large but this inevitably comes with major reworks like this. What I checked out already works nicely. Improvements here and there will be made over the next weeks. +1 for merging.

**Comment by StephanEwen** [comment]
The change set is large, but the overlap with the existing code base is not too big. A bit in the JobGraph and JobManager, mainly for attaching extra information and accessing accumulators, that is it. It introduces no change to any other component, so should be pretty non-critical.

**Comment by rmetzger** [comment]
Another follow-up todo is adding support for yarn:

```
11:31:01,955 ERROR org.apache.flink.runtime.jobmanager.JobManager                - WebServer could not be created
org.apache.flink.configuration.IllegalConfigurationException: The path to the static contents (/yarn/nm/usercache/robert/appcache/application_1441703985068_0007/container_e07_1441703985068_0007_01_000001/resources/web-runtime-monitor) is not a readable directory.
	at org.apache.flink.runtime.webmonitor.WebRuntimeMonitor.<init>(WebRuntimeMonitor.java:137)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.flink.runtime.jobmanager.JobManager$.startWebRuntimeMonitor(JobManager.scala:1741)
	at org.apache.flink.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:134)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:356)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1651)
	at org.apache.flink.yarn.ApplicationMaster$.main(ApplicationMaster.scala:69)
	at org.apache.flink.yarn.ApplicationMaster.main(ApplicationMaster.scala)
```

**Comment by StephanEwen** [comment]
The YARN support needs to ship the static contents to the JobManager (AppMaster). The current implementation does not support to serve the static contents out of a JAR file...

**Comment by aljoscha** [comment]
For a streaming job, when I open the running job overview the plan is displayed correctly. When I then switch over to another tab and return to the plan view all the operators are disconnected and shown one above the other.

**Comment by StephanEwen** [comment]
I have seen that before, yes. Piotr is actually looking into this, it seems a bug in the "Dagre" library that is used for the graph.

**Comment by StephanEwen** [comment]
Manually merged in 482d4373facbf2e24bc76eb04b2a5550434c91b8

**Pull request closed without merging**
