### PR TITLE
[FLINK-30016][docs] Mention system metrics dependencies update

### PR DESCRIPTION
**Pull request by czchen**
## What is the purpose of the change

* Mention system metrics dependencies update in release note.

### CODE REVIEW

**Review by MartijnVisser — CHANGES_REQUESTED** [review]
@czchen Thanks for the quick fix! Please also make sure that you update `flink-1.16.md` in the `content.zh` folder. And after I've merged it, please also create a backport to the `release-1.16` branch.

**Comment by czchen** [comment]
@MartijnVisser Updated `content.zh` as requested.

**Review by MartijnVisser — APPROVED** [review]
@czchen Thank you! Can you also create a backport to `release-1.16` after I've merged this one?

**Comment by czchen** [comment]
@MartijnVisser PR in https://github.com/apache/flink/pull/21320.

**Pull request merged**
