### PR TITLE
[FLINK-11722][javadocs] Fix the outdated java doc in AkkaRpcServiceUtils

### PR DESCRIPTION
**Pull request by libenchao**
## What is the purpose of the change

*Fix the outdated java doc in `AkkaRpcServiceUtils.createRpcService()`*
- `createRpcService` is responsible for creating RpcService of AkkaSystem, not just for `TaskManager`, but other components as well.
- the parameter `port` has wrong description.

## Brief change log

 - *update `AkkaRpcServiceUtils.createRpcService()`'s java doc*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by libenchao** [comment]
@rmetzger Thanks for the review. I have updated the description.

**Comment by jianbin-allseeing** [comment]
@flinkbot approve all

**Comment by rmetzger** [comment]
@flinkbot please re-evaluate the labels for this pull request

**Comment by tillrohrmann** [comment]
Thanks for creating this PR @libenchao and sorry for my late reply. Unfortunately, the code base has changed in the meantime so that this PR is no longer needed. I will close this PR now.

**Comment by libenchao** [comment]
@tillrohrmann Thanks for the reminder, I'll check all my early PRs whether they are still valid.

**Pull request closed without merging**
