### PR TITLE
[FLINK-25808][rest][docs] JsonTypeInfo property uses valid java identier

### PR DESCRIPTION
**Pull request by zentol**
using '@class' causes swagger to generate a client that cannot be compiled

This is technically a breaking change, but since this field is not documented it should be fine.

### CODE REVIEW

**Comment by dmvk** [comment]
e2e tests are failing on the NPM proxy

**Review by dmvk — APPROVED** [review]
LGTM 👍 One thought, should we maybe rename `clazz` to `className` to get it more of a "professional" feel?

**Comment by zentol** [comment]
@flinkbot run azure

**Comment by zentol** [comment]
sure, we can use `className`

**Pull request merged**
