### PR TITLE
[FLINK-5258] [docs] reorganize the docs to improve navigation and reduce duplication

### PR DESCRIPTION
**Pull request by alpinegizmo**
Goals:
* improve navigation and discoverability: important topics shouldn't be hard to find
* reduce duplication: ideally every piece of information would have one natural place to be
* arrange the content in a natural, linear ordering for those who want to read (or skim through) everything

This pull request moves content around, and in some cases merges sections with major overlap. When I noticed them I fixed small wording problems and typos, and I did somewhat more significant editing in the concepts section. 

The results can be reviewed at https://alpinegizmo.github.io/flink-docs/

### CODE REVIEW

**Comment by StephanEwen** [comment]
Thanks a lot for this pull request!
I think this looks very good - much better than the current state.

Two changes I would make:
  - Drop "Projects and Dependencies", it is so outdated that it is misleading these days
  - The same holds for "How to add a new DataSet Operator"

Otherwise, I would merge this, as it is a big improvement over the current version.

**Comment by StephanEwen** [comment]
Thanks for addressing this.
Looks good to me overall, merging this...

**Comment by mindprince** [comment]
We seem to have lost changes from https://github.com/apache/flink/commit/c024b0b6cae16a0b668d864c77e923820c262087 and https://github.com/apache/flink/commit/91414d9611a5a14d4d73ae5ea090c16406dcf025 during the reorg. :-(

I wonder if we lost more such changes.

cc - @alpinegizmo @fhueske @mxm

**Comment by fhueske** [comment]
Hi @mindprince, thanks a lot for pointing out this issue. 

I had a look at the diffs and found that the following changes got lost or refactored:
- c024b0b : `./docs//setup/fault-tolerance.md` and `./docs/dev/api_concepts.md`
- 91414d9 : `./docs//setup/fault-tolerance.md`
- 3698379: `./docs//setup/fault-tolerance.md`

Since the docs have been refactored, we should check where these changes need to go.

**Pull request closed without merging**
