### PR TITLE
[FLINK-11836] Update NOTICE-binary and licenses-binary for Flink 1.8.0

### PR DESCRIPTION
**Pull request by aljoscha**

### CODE REVIEW

**Comment by aljoscha** [comment]
It turns out that we had both `LICENSE.slf4j` and `LICENSE.slf4j-api` before, with identical contents. I'll see what I can do about sorting the license files before concatenating. 👌

**Comment by aljoscha** [comment]
@zentol I'm now sorting the `NOTICE` files before concatenation. This makes the diff bigger now but should lead to less changes in the future.

**Comment by zentol** [comment]
Ha, we may want to keep `LICENSE.slf4j` actually. I don't know where the `slf4j-api` one comes from (it is not from any Flink module), so we should keep the slf4j license to be sure we have it.

**Comment by zentol** [comment]
Beyond that, +1.

**Comment by aljoscha** [comment]
ok, will manually keep that. But someone might forget that in the future 😅

**Comment by aljoscha** [comment]
thanks!

**Comment by aljoscha** [comment]
merged

**Pull request closed without merging**
