### PR TITLE
[hotfix] Prevent CheckpointCommitter from failing job

### PR DESCRIPTION
**Pull request by zentol**
This PR fixes an issue in the `GenericWriteAheadSink` that @aljoscha stumbled upon.

If the sink fails while writing the data into the external storage the sink retries again on the next notify; it will never fail the job. However, the CheckpointCommitter does not behave that way; if the storage cannot be queried it will throw an exception that is not catched by the sink.

The exceptions are now catched and logged by the sink.

@aljoscha Could you try out whether this fixes the issue?

### CODE REVIEW

**Comment by aljoscha** [comment]
I'm checking now but I'm assuming it will fix it from looking at the code. Could we also a a test for this?

**Comment by aljoscha** [comment]
This does in fact fix the problem. Running smoothly now. 😃

**Comment by zentol** [comment]
That's great to hear, working on a test right now.

**Comment by aljoscha** [comment]
Thanks! 👍

**Comment by zentol** [comment]
- added test

**Comment by aljoscha** [comment]
Test looks good!

Please go ahead and merge if you're ready.

**Comment by zentol** [comment]
merging

**Pull request closed without merging**
