### PR TITLE
Update version to 1.5-SNAPSHOT

### PR DESCRIPTION
**Pull request by aljoscha**

### CODE REVIEW

**Comment by bowenli86** [comment]
👍

**Comment by yew1eb** [comment]
:clap:

**Comment by tillrohrmann** [comment]
+1

**Comment by StephanEwen** [comment]
:yellow_heart:

Very nice!

**Comment by StephanEwen** [comment]
Crazy realization is that there are 91 pom.xml files in Flink.
Its a large project :-)

**Comment by Aitozi** [comment]
🎉

**Pull request closed without merging**
