### PR TITLE
[FLINK-2771] Fix for IterateTest.testSimpleIteration fail on Travis

### PR DESCRIPTION
**Pull request by rekhajoshm**
[FLINK-2771] Fix for IterateTest.testSimpleIteration fail on Travis

### CODE REVIEW

**Comment by StephanEwen** [comment]
Thanks for looking into this.
Making the iteration timeout longer makes the test more stable, but still not absolutely stable. It also increases the time that the build takes, for every build.

I think a good start would be to increase the timeout to 5000 (a bit more stability), and then actually improve the test and the iterations themselves:

  - The test case could be modified to actually run the program with a large iteration timeout. But the program is started in a separate thread, and the main thread checks for the result periodically (every 50ms or so) and cancels the program as soon as the expected result is there. That way, the test will return fast if the execution is fast, and will still be pretty reliable, because the termination has a long timeout.

  - We should change the stream iteration behavior from a timeout-based termination to a proper "end-of-stream-event" based termination. That would also automatically make the test reliable and predictable. This is a bit more involved, but would be the best solution. I'd be happy to write more about that in a design doc, if you want to do that.

Please let us know if you would be up for helping out with these efforts!

**Comment by rekhajoshm** [comment]
Yes, glad to @StephanEwen . Looking forward to your design for timeout-based termination to a proper "end-of-stream-event" based termination. thanks!

**Comment by uce** [comment]
I think the proper solution to this is outside of the scope of this PR. This hasn't occurred in a long time. I will change the timeout to the suggested 5000 ms and merge this.

**Comment by uce** [comment]
Turns out the test has been removed in the mean time. Could you please close this PR @rekhajoshm?

**Comment by rekhajoshm** [comment]
done @uce

**Pull request closed without merging**
