### PR TITLE
[FLINK-5829] Bump Calcite version to 1.12 once available.

### PR DESCRIPTION
**Pull request by haohui**
This PR bumps the Calcite version from 1.11 to 1.12.

The main issue is that it conflicts with FLINK-4288, as the `tableMap` field becomes protected which makes unregistering table no longer trivial.

As the first iteration I disable the related tests in this PR. We need to come up with a solution.

### CODE REVIEW

**Comment by twalthr** [comment]
Thanks @haohui for looking into this. I think you forgot to include the modified pom.xml. Can you remove all "unregisterTable" code instead of throwing an exception? It would be great if you could have a look into the resulting flink-table jar and job jar that includes the flink-table on order to check if shading filters are still valid.

**Comment by haohui** [comment]
The failed test is unrelated to the changes. @twalthr @fhueske can you please take a look?

**Comment by fhueske** [comment]
Thanks @haohui. 
I think this PR is good to merge. 
Since the support to unregister tables was added after Flink 1.2 was released, we are not removing a released feature.

@twalthr, do you want to have a look as well?

**Comment by twalthr** [comment]
Thanks @haohui. I will merge this.

**Pull request closed without merging**
