### PR TITLE
[hotfix][docs] Fix typo in CLI docs

### PR DESCRIPTION
**Pull request by trushev**

### CODE REVIEW

**Review by rmetzger — CHANGES_REQUESTED** [review]
Why are these typos? The idea of these examples is to store the savepoint in the `/tmp` directory, not in the file system root.

**Comment by trushev** [comment]
@rmetzger `/tmp/flink-savepoints` is a consistent path for savepoints on this page, so I think `/tmp-flink-savepoints` is a typo

savepoints_path

**Comment by rmetzger** [comment]
Ah, sorry, of course. Looks like I didn't have my morning coffee yet ☕ .

**Comment by trushev** [comment]
> Why are these typos? The idea of these examples is to store the savepoint in the `/tmp` directory, not in the file system root.

I agree that's why I want to replace `/tmp-flink-savepoints` with `/tmp/flink-savepoints`

**Comment by rmetzger** [comment]
Thanks a lot for your contribution!

**Review by rmetzger — APPROVED** [review]

**Pull request merged**
