### PR TITLE
[FLINK-3573] [table] Implement more String functions for Table API

### PR DESCRIPTION
**Pull request by twalthr**
This PR implements the remaining string functions:

CHARACTER_LENGTH
CONCAT
UPPER
LOWER
INITCAP
LIKE
SIMILAR

And simplifies the CallGenerators a bit.

### CODE REVIEW

**Comment by fhueske** [comment]
Good to merge

**Comment by mbalassi** [comment]
Do not forget to add the licence header to `NotCallGenerator` when merging. :)

**Comment by twalthr** [comment]
@mbalassi Thanks, I added the header. Good to merge if build succeeds.

**Comment by twalthr** [comment]
Merging this...

**Pull request closed without merging**
