### PR TITLE
[FLINK-33779][table] Cleanup usage of deprecated BaseExpressions#cast

### PR DESCRIPTION
**Pull request by liuyongvs**
## What is the purpose of the change

*Replace the usage of deprecated org.apache.flink.table.api.internal.BaseExpressions#cast(TypeInformation) with cast(DataType)*

## Brief change log

* Cleanup usage of deprecated org.apache.flink.table.api.internal.BaseExpressions#cast(TypeInformation) *

## Verifying this change
* original unit test *

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no )
  - The runtime per-record code paths (performance sensitive): (no )
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by liuyongvs** [comment]
hi @snuyanzin @dawidwys  could you help review this pr?

**Comment by liuyongvs** [comment]
hi @lsyldliu @xuyangzhong will you also help review this?

**Review by xuyangzhong — APPROVED** [review]
LTGM. Thanks for this contribution. Can you modify the description of this pr? A lot of content seems to be based on templates.

**Comment by liuyongvs** [comment]
@xuyangzhong thanks for your rewiew and modify the description of this pr

**Review by snuyanzin — APPROVED** [review]
Thanks for contribution @liuyongvs 
thanks for review @xuyangzhong 

LGTM

**Pull request merged**
