### PR TITLE
[FLINK-1800][docs] Add beta badge to components in flink-staging

### PR DESCRIPTION
**Pull request by rmetzger**

### CODE REVIEW

**Comment by uce** [comment]
The changes are good.

I very much like the text on the bottom of the left navigation.

A matter of taste: I like the blue badge, but it really draws the visual attention to it. This might be good or bad. Personally, I prefer something less prominent.

screen shot 2015-04-01 at 13 46 38

As an example for something less prominent:

screen shot 2015-04-01 at 13 48 05

**Comment by mbalassi** [comment]
+1 for Ufuk's suggestion.

**Comment by StephanEwen** [comment]
+1 for Ufuk's suggestion

I would remove "Beta" from Spargel, it is actually very stable. Question is whether it stays or gets subsumed by Gelly

**Comment by uce** [comment]
I'm merging this with my change.

I will leave Spargel with the beta tag (as it is in staging) and start a discussion on dev@ about what to do with it in the future.

**Comment by uce** [comment]
Actually, you are right. I'll remove Beta from Spargel.

**Pull request closed without merging**
