### PR TITLE
[FLINK-18550][sql-client] use TableResult#collect to get select result for sql client

### PR DESCRIPTION
**Pull request by godfreyhe**
## What is the purpose of the change

*This pr aims to use TableResult#collect to get select result instead of using user defined sink. which could reduce a lot of code.*

## Brief change log

  - *use TableResult#collect to get select result for sql client*
  - *remove useless code about Deployment in sql client*
  - *use RowKind instead of Tuple2 to represent changes in sql client*
  - *fix data loss in ChangelogCollectResult*

## Verifying this change

This change is already covered by existing tests, such as LocalExecutorITCase, and add some new test to verify the change, such as MaterializedCollectBatchResultTest, ChangelogCollectResultTest.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by godfreyhe** [comment]
cc @twalthr It's very appreciate that you could help reviewing this pr

**Comment by godfreyhe** [comment]
cc @JingsongLi

**Comment by godfreyhe** [comment]
cc @wuchong

**Comment by wuchong** [comment]
continue reviewing in #14958

**Pull request closed without merging**
