### PR TITLE
[FLINK-14970]Doomed test for equality to NaN

### PR DESCRIPTION
**Pull request by caidezhi**
## What is the purpose of the change
scala pattern matching can't handle "NaN","NegativeInfinity " etc.
in Flink planner module( GenerateUtils, CodeGenerator), some code logic fall into this issue.
the PR target to fix this. 
## Brief change log
fix pattern matching issue in below classes:
org.apache.flink.table.planner.codegen.GenerateUtils
org.apache.flink.table.codegen.CodeGenerator

## Verifying this change

This change is  covered by UT
org.apache.flink.table.planner.codegen.GenerateUtilsTest

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no )
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: ( no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? ( no)

### CODE REVIEW

**Comment by KurtYoung** [comment]
Hi @caidezhi , thanks for fixing this. Could you add some tests to this bug?

**Comment by caidezhi** [comment]
@KurtYoung I have add some UT cases as you suggested. Would you please help to review? Thanks.

**Comment by KurtYoung** [comment]
There are some test failures after you changed this, could you check that?

**Comment by caidezhi** [comment]
hi @KurtYoung the latest build failed("misc" module ), but it is not related to the PR. Do you think it is required  to trigger another build?(the travis-ci seems quite busy, a request may stay in the queue for a whole day :( )

**Comment by caidezhi** [comment]
Hi @KurtYoung , i also aware of that.  Calcite uses BigDecimal for handling DOUBLE, FLOAT. when we pass unnormal numerical value((eg: INFINITY, NaN) literalType=DoubleType, literalValue=null are passed to method "GenerateUtils.generateLiteral",  the program will go to another branch, the pattern matching which has bug will not cause any impact.

can we just remove the pattern matching logic to make it clean? if it is ok, i will make another commit for this PR. Thanks.

**Comment by caidezhi** [comment]
Only ` Double.NaN`  does't work.  I update the Jira issue description and the type as "Improvement-Trivial".  Deleting the `NaN` test seems not worth a PR. 
Sorry for causing any inconvenience, will be more careful in future. 
(Thanks for your patience :) )

**Comment by KurtYoung** [comment]
I think it's still worthy to clean up some wrongly written codes. If you wish you could continue to refine the PR

**Comment by caidezhi** [comment]
Thanks Kurt. refine PR as you suggested.

**Comment by KurtYoung** [comment]
Merging...

**Pull request merged**
