### PR TITLE
[FLINK-2180] [streaming] Iteration test fix

### PR DESCRIPTION
**Pull request by gaborhermann**
* Fixed the iteration test at DataStreamTest
* Added more tests for DataStream
* Added a fix for the iteration test by giving the user the opportunity to end an iteration at a given value

### CODE REVIEW

**Comment by mbalassi** [comment]
Please properly rebase this branch, so we will not see the "noise" commits from others.

**Comment by mbalassi** [comment]
What is the state of this PR, @gaborhermann?

**Comment by gaborhermann** [comment]
I updated the PR. Added the fix for the iteration test. Probably not getting a new element within the maximum wait time caused the failing of the iteration tests. After this fix it should not be a problem.

**Comment by gyfora** [comment]
Reduce fold and aggregations are being removed from non-grouped DataStream, so we might want to remove that commit.

**Comment by gaborhermann** [comment]
Thanks for the heads up, I removed the aggregation test.

**Comment by gyfora** [comment]
What's the purpose of having this EndOfIteration predicate? Can you give me a use-case where this functionality is desired?

**Comment by gaborhermann** [comment]
The main purpose of this is to enable a deterministic (non-time based) test for iteration as it sometimes failed for some reason on Travis. (See [here] (https://issues.apache.org/jira/browse/FLINK-2180?focusedCommentId=14576968&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14576968)). I thought it might also be useful to users for debugging purposes (similarly to maxWaitTime) and it was also easier to introduce it in the API level.

**Comment by gyfora** [comment]
I am currently preparing a new PR with a rework of how the iterations are constructed in the StreamGraph it will be ready today. It will solve many issues that we currently have and will make the iterations much more robust.

I am also adding a bunch of new tests.

I think this is still a good addition because some of my tests will depend on the maxWaitTime. I propose to add your changes afterwards. I volunteer to port your commits to my changes :)

**Comment by gaborhermann** [comment]
Okay, thanks :)

**Comment by mbalassi** [comment]
I think this has been merged manually by @gyfora.

**Pull request closed without merging**
