### PR TITLE
[FLINK-2686] Show exchange mode in JSON plan

### PR DESCRIPTION
**Pull request by zentol**
Extends the PlanJSONDumpGenerator to also include the Data Exchange mode. It will be shown like this:

```
...
"parallelism": "2",
"predecessors": [
	{"id": 5, "ship_strategy": "Forward", "exchange_mode": "PIPELINED"}
],
"driver_strategy": "Map",
...
```

### CODE REVIEW

**Comment by StephanEwen** [comment]
The JSON plan generation has actually two points now (that we should try to consolidate). The other one is on "https://github.com/apache/flink/blob/6e0e67d2e0d5180d6fba492e8ab9cc8fb18fdf68/flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/jsonplan/JsonPlanGenerator.java" and deals with attaching the JSON plan to every JobGraph so that the runtime dashboard can draw a graph. That plan is a bit different then the optimizer JSON (because it is not iteration aware and chained tasks are only one operator any more), but otherwise follows similar logic.

**Comment by zentol** [comment]
it appears that one already includes the exchange mode.

```
...
if (operatorLevelCaching != null) {
	gen.writeStringField("caching", operatorLevelCaching);
}
						
gen.writeStringField("exchange", edge.getSource().getResultType().name().toLowerCase());

gen.writeEndObject();
...
```

**Comment by StephanEwen** [comment]
Ah, right you are...

**Comment by StephanEwen** [comment]
Looks good to merge.

Think this need a followup where the exchange type is displayed in the plan visualizer.

**Comment by uce** [comment]
Visualization for this would be great!

**Comment by zentol** [comment]
Merging this once Travis passes.

**Pull request closed without merging**
