### PR TITLE
[FLINK-4148]  incorrect calculation minDist distance in QuadTree

### PR DESCRIPTION
**Pull request by xhumanoid**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.
- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)
- [x] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added
- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by nssalian** [comment]
Hi @xhumanoid , thanks for the PR. Could you please check the Failure messages and fix the build? Can help review once the PR is cleanly mergable.

**Comment by xhumanoid** [comment]
slave was killed without any notifications:

ERROR: Maven JVM terminated unexpectedly with exit code 137
Putting comment on the pull request
Finished: FAILURE

**Comment by nssalian** [comment]
Seems good to me. @zentol do you have time to add some extra review on this?

**Comment by zentol** [comment]
I'm sorry, I completely forgot about this one. I will merge it with the next batch.

**Comment by Fokko** [comment]
Looks good, please merge. Should have been fixed long ago :-)

**Pull request closed without merging**
