### PR TITLE
[FLINK-12014][Doc]Flink CEP Doc missing "SkipToNextStrategy"

### PR DESCRIPTION
**Pull request by Tom-Goong**
## What is the purpose of the change

Improve the inaccurate description of AfterMatchSkipStrategy in the documentation

## Brief change log

modify cep.md file in the path: docs/dev/libs/cep.md

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency):  **no**
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`:  **no**
  - The serializers:  **no**
  - The runtime per-record code paths (performance sensitive):  **no**
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper:  **no**
  - The S3 file system connector:  **no**

## Documentation

  - Does this pull request introduce a new feature?  **no**

### CODE REVIEW

**Comment by dawidwys** [comment]
Would you mind extending also the example section?

**Comment by dawidwys** [comment]
@flinkbot approve-until consensus

**Comment by Tom-Goong** [comment]
> Would you mind extending also the example section?

It already has it.
In fact, this is the reason I can find the problem, but I also checked the code to confirm that it is currently five.


image

**Comment by dawidwys** [comment]
Sorry @Tom-Goong, my mistake, didn't spot it.
+1, merging

**Pull request merged**
