### PR TITLE
[FLINK-6723] Activate strict checkstyle for flink-libraries

### PR DESCRIPTION
**Pull request by zentol**
Move checkstyle plugin into flink-libraries pom.

### CODE REVIEW

**Comment by greghogan** [comment]
+1

Are the tests failing for lack of the fix reordering the pom in `flink-dist`?

**Comment by tzulitai** [comment]
@greghogan I think the failing tests for this is due to https://issues.apache.org/jira/browse/FLINK-6836 (a different issue from the pom ordering fix).

**Comment by greghogan** [comment]
Thanks @tzulitai.

**Comment by zentol** [comment]
merging.

**Pull request merged**
