### PR TITLE
[FLINK-1709] [wip] Add SlotCountExceedingParallelismTest

### PR DESCRIPTION
**Pull request by uce**
This is the initial simple case. I'll push the other variants to this branch.

### CODE REVIEW

**Comment by StephanEwen** [comment]
The test looks good.

One question: Why are you not simply using the `Client` to submit the JobGraph to the JobManager. This has the nice benefit that we test the usual code paths with that as well.

The test-kit messages are IMHO mainly for testing the reaction of an actor to some isolated messages outside regular control flow.

**Comment by uce** [comment]
Regarding submission via `Client`: You are right. I just hadn't thought of that.

**Comment by uce** [comment]
Changed the test accordingly and rebased. Can we merge this?

**Comment by uce** [comment]
Will squash and merge. :)

**Pull request closed without merging**
