### PR TITLE
[FLINK-2989] job cancel button doesn't work on YARN

### PR DESCRIPTION
**Pull request by mxm**
In addition to the REST-compliant "DELETE /jobs/<jobid>", allows
cancellation also via a special GET request of the form
"GET /jobs/\<jobid\>/yarn-cancel".

That enables us to cancel jobs from the web frontend on YARN while
keeping a REST-compliant DELETE alternative.

### CODE REVIEW

**Comment by rmetzger** [comment]
Maybe not as part of this PR, but in the long term, we should add a integration test for cancelling a job running in a YARN session.

**Comment by mxm** [comment]
+1 for the integration test

**Comment by rmetzger** [comment]
Since Flink 0.10.1 is around the corner, we should merge this PR ;)

**Comment by mxm** [comment]
I'm assuming everyone is ok with this workaround for now. If not please speak up. I'll merge this in time for 0.10.1.

**Comment by tillrohrmann** [comment]
LGTM

**Pull request closed without merging**
