### PR TITLE
[FLINK-4081] [core] [table] FieldParsers should support empty strings

### PR DESCRIPTION
**Pull request by twalthr**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

This PR adds the FieldParser error state `EMPTY_STRING` to all FieldParsers. Until now the behavior was inconsistent, e.g. IntParser had it but FloatParser not. This PR allows for `null` values in advanced input formats such as `RowCsvInputFormat`.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Using an error state for an empty string seems a bit unorthodox.
I take it returning `0` does not work for some reason?

**Comment by fpompermaier** [comment]
For our use cases it is important to know whether a value of cell is empty or it is 0.
The EMPTY_STRING error could be intercepted by the csv parser in order to generate Row objects with null values instead of 0 using the Table API

**Comment by StephanEwen** [comment]
I am confused here, the return value is not the parsed value, but the length that got parsed.

**Comment by twalthr** [comment]
The length is not sufficient to differentiate between empty column and empty string.
E.g. if you have quoted strings: `,,` and `,"",`
With the changes in this PR we don't modify the return values, but deposit the information of an empty column in the error state.

**Comment by StephanEwen** [comment]
Okay, I think the main source of confusion here is that `EMPTY_STRING` does actually not refer to an empty string (as specific to the string parser) but to something like "null", "empty column", or "missing value".

Let's call it something like that and then it actually makes sense to me to communicate that via an error state. Because it is actually not a regular value (as an empty string would be).

**Comment by twalthr** [comment]
@StephanEwen I renamed `EMPTY_STRING` to `EMPTY_COLUMN`. All parsers that have a "format" (like Double, Boolean, Integer etc.) return `-1` and set `EMPTY_COLUMN`. The `StringParser` returns the String but sets `EMPTY_COLUMN` in case no quoting could be found.

So in `..,12,,xyz,..` the column `,,` will always be set as `EMPTY_COLUMN` consistently across all parsers.

**Comment by twalthr** [comment]
If there are no objections, I would like to merge this PR next week. Other my other PRs depend on this.

**Comment by StephanEwen** [comment]
That looks more consistent.

If the tests pass, +1 from my side

**Pull request closed without merging**
