### PR TITLE
[FLINK-14252][coordination] Encapsulate Dispatcher services in DispatcherServices

### PR DESCRIPTION
**Pull request by tillrohrmann**
## What is the purpose of the change

This PR is based on #9786.

The `DispatcherServices` container contains all required `Dispatcher` services
except for the `JobGraphStore` which needs to passed in separately to make it work
with the `MiniDispatcher`.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by TisonKun** [comment]
@flinkbot run travis

**Comment by TisonKun** [comment]
The corresponding JIRA is FLINK-14252 instead of FLINK-14525 :P

**Comment by TisonKun** [comment]
From FLINK-14259  I guess it is towards a testable codebase but I still cannot get the point without a vivid test that relies on this separation.

**Comment by tillrohrmann** [comment]
The reason why there is a `DispatcherServices` and a `PartialDispatcherServices` is that the `AbstractDispatcherResourceManagerComponentFactory` should not need to know about which `JobManagerRunnerFactory` the `Dispatcher` uses. That's why the runner factory is part of the `DispatcherFactory` where we complete the `PartialDispatcherServices` and create the `DispatcherServices`. Hence, the two data containers are introduced in order to better separate concerns.

**Comment by TisonKun** [comment]
Thanks for your information @tillrohrmann . If the problem is that `AbstractDispatcherResourceManagerComponentFactory` should not need to know about which `JobManagerRunnerFactory` the `Dispatcher` uses, we could let `DispatcherFactory` takes this responsibility as you do now. Specifically, `DispatcherFactory#createDispatcher` takes all parameters the constructor of `PartialDispatcherServices` takes, in its body it create the completed `DispatcherServices` with an internally known `JobManagerRunnerFactory`. 

`PartialDispatcherServices` is a temporary POJO in only `AbstractDispatcherResourceManagerComponentFactory` that we directly make a completed one in `DispatcherFactory#createDispatcher`.

Here is a patch based on your branch about the idea above.( https://gist.github.com/TisonKun/2f43982d0b4f5276688149070f88b9c0 )

**Comment by tillrohrmann** [comment]
Well, additionally I wanted to make the passing of the parameters easier by encapsulating them into a container. I think that methods with too many parameters easily become unwieldy. That was the initial motivation for introducing the `DispatcherServices` container. Moreover, it should not harm to introduce a couple of helper classes.

**Comment by TisonKun** [comment]
@tillrohrmann I wonder isn't that `DispatcherServices` is introduced for share services among multiple leader epoch?

**Comment by tillrohrmann** [comment]
It happens to be but it is not the intention to manage the contained services as we do with the `JobManagerSharedServices`. It could be potentially extended to do that in the future.

**Comment by TisonKun** [comment]
Aha. Always I thought `JobManagerSharedServices` and `DispatcherServices` are mainly for sharing services between leader epoch so that we don't instance the same services per epoch.

**Comment by TisonKun** [comment]
Though we use the same JobMaster and Dispatcher (endpoint) for all epoch now.

**Comment by tillrohrmann** [comment]
`JobManagerSharedServices` indeed is. `DispatcherServices` is simply a container to group arguments, which belong together, together.

Thanks for the review @TisonKun. Merging this PR now.

**Comment by tillrohrmann** [comment]
Removed inheritance relationship between `PartialDispatcherServices` and `DispatcherServices`.

**Pull request closed without merging**
