### PR TITLE
[FLINK-2866] [FLINK-2888] [FLINK-2891] Fixes for various release blocking issues

### PR DESCRIPTION
**Pull request by StephanEwen**
Default state value is returned as copies in key value state. To circumvent this (if ever becomes a performance issue), one can use null as the default state and manually check/initialize to an immutable default value.

Window user functions have access to key/value state even window is evaluated (part 2 - pert 1 was committed by Aljoscha earlier). The main part here is a rework of the PreAggregatingWindow tests to make them more meaningful.

This also includes #1282

### CODE REVIEW

**Comment by aljoscha** [comment]
+1
Code looks good, I actually solved it the same way but got stuck on the tests... :smile:

**Comment by fhueske** [comment]
We should not open PRs that reference multiple JIRA. PR comments are only mirrored to the first JIRA issue.

**Comment by aljoscha** [comment]
A new test fails very often:
  AccumulatingAlignedProcessingTimeWindowOperatorTest.testKeyValueStateInWindowFunction:782 expected:<4> but was:<1>

**Comment by StephanEwen** [comment]
Yeah, it is hard to make these tests deterministic, as they depend on processing time trigger. Thought I found a trick, but it is apparently not a rock solid test. I'll try and rework the test for more stability...

**Comment by StephanEwen** [comment]
Okay, figured out that the cause of the problem was: The test UDF calls (evaluated in the processing time timer) emits elements before updating the state. The test driver already received all elements and checks the state before it is updated. Switching the statements seems to fix the instability...

**Comment by StephanEwen** [comment]
Fix seems to work, three successive Travis runs (15 builds) do pass now...

**Comment by aljoscha** [comment]
Ok, then we should merge it since this is blocking the release. :smile:

**Comment by StephanEwen** [comment]
Manually merged into branches `master` and `release-0.10`

**Pull request closed without merging**
