### PR TITLE
[FLINK-5855][Streaming Connectors] Unprotected access to pendingFiles…

### PR DESCRIPTION
**Pull request by zhangminglei**
…PerCheckpoint in BucketingSink.

Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [ ] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [ ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by zhangminglei** [comment]
cc @tillrohrmann

**Comment by tillrohrmann** [comment]
Not sure why we're synchronizing on the `pendingFilesPerCheckpoint` field at all, because it is only the restored state object. Maybe @kl0u can shed some light on that.

**Comment by kl0u** [comment]
Hi @zhangminglei, thanks for looking into this! I tend to agree with @tillrohrmann that there is not need for locking there, as there is no sharing of the data-structure between different threads. The same holds for the lock at line 726. So these 2 `synchronized()` clauses could go away.

I will have a more thorough look on the whole locking scheme in the class in the following days. But for now I think that this PR could be closed and the JIRA could be updated.

What do you think?

**Comment by zhangminglei** [comment]
@kl0u Thanks for review , very appreciate it. Yep, BTW, I would like to work on what you will thorough the code in the following days and keep watching this class ```synchronized()```. Hopes work on the new jira if you could assign to me. I will close this PR and JIRA as well.

**Comment by kl0u** [comment]
Yes. This sounds good, but you reopened this pull request right? Shouldn't this be closed?

**Comment by zhangminglei** [comment]
@kl0u Yep. I reopened this PR again for waiting you message me. Haha ~ Okay, Now, I will close it and then create another jira and cc you.

**Comment by kl0u** [comment]
@zhangminglei Perfect!

**Pull request closed without merging**
