### PR TITLE
[FLINK-2904][web-dashboard] Fix truncation of task counts when the number is large.

### PR DESCRIPTION
**Pull request by sachingoel0101**
@greghogan can you verify if this solves the problem? I cannot test with such large number of tasks directly.

### CODE REVIEW

**Comment by sachingoel0101** [comment]
Here's a screenshot though:
screenshot 52

IMO this should be included in the release.

**Comment by sachingoel0101** [comment]
Ping.

**Comment by greghogan** [comment]
@sachingoel0101 thank you for taking these tickets. This patch handles large counts quite nicely. The only negative I see is that the colored boxes are generally no longer aligned. How about adding something like `min-width: 3em` in both files to replace the original `width: 2em`?

**Comment by sachingoel0101** [comment]
That'll take up unnecessary space for labels with small values like, say, 3-4.

**Comment by mxm** [comment]
I think it's fine that the boxes are not all the same size for large numbers..

**Comment by sachingoel0101** [comment]
Hi @mxm, is there any further improvement needed on this? If not, I think it should be merged.

**Comment by rmetzger** [comment]
+1 to merge

**Comment by StephanEwen** [comment]
Will merge this pull request...

**Pull request closed without merging**
