### PR TITLE
[Flink-2768][Documentation] Fix wrong java version requirement in quickstart

### PR DESCRIPTION
**Pull request by rerngvit**
Fix wrong java version requirement in quickstart (1.6 -> 1.7)

### CODE REVIEW

**Comment by hsaputra** [comment]
+1
LGTM

**Comment by hsaputra** [comment]
Could you squash the commits into one please?

**Comment by rerngvit** [comment]
@hsaputra Thank you for reviewing this PR. I squashed the commits into one as per your comment. Please have a look.

**Comment by chiwanpark** [comment]
+1
Looks good to merge.

**Comment by StephanEwen** [comment]
Will merge this...

**Pull request closed without merging**
