### PR TITLE
[FLINK-4402]: Wrong metrics parameter names in documentation

### PR DESCRIPTION
**Pull request by nssalian**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [ ] General
  - JIRA- https://issues.apache.org/jira/browse/FLINK-4402
   - Title: Wrong metrics parameter names in documentation

- [ ] Documentation
  - Changed the task and operator metrics in https://ci.apache.org/projects/flink/flink-docs-master/apis/metrics.html to align with ConfigConstants.java

- [ ] Tests & Build
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by rmetzger** [comment]
Thank you for your contribution.
I think its good to merge. @zentol can you confirm?

**Comment by zentol** [comment]
+1

**Comment by rmetzger** [comment]
merging ...

**Comment by nssalian** [comment]
Thank you @rmetzger  and @zentol

**Pull request closed without merging**
