### PR TITLE
[FLINK-1433] Add HADOOP_CLASSPATH to start scripts

### PR DESCRIPTION
**Pull request by rmetzger**

### CODE REVIEW

**Comment by fhueske** [comment]
LGTM

**Comment by StephanEwen** [comment]
Does this mean that we now have multiple hadoop dependencies in the class path? The ones that are part of the Flink lib directory, plus the ones in the HADOOP_CLASSPATH variable.

**Comment by rmetzger** [comment]
It depends on what the user does with the `HADOOP_CLASSPATH`.
In my understanding, it is meant as a variable for adding 3rd party jar files to Hadoop. The jar files of hadoop are added to the `CLASSPATH` variable in the `libexec/hadoop-config.sh` script. There, you see variables like `HADOOP_COMMON_LIB_JARS_DIR`, `HDFS_LIB_JARS_DIR`, `YARN_LIB_JARS_DIR`, ... being added to the CLASSPATH. In the very last step, they add the HADOOP_CLASSPATH variable (by default to the end of the classpath, but there is an additional option to put it in front of it).

I found that we need to add this on Google Compute Engine's Hadoop deployment. They have their Google Storage configured by default but it currently doesn't work in non-yarn setups because the Google Storage jar is not in our classpath. On these clusters, the `HADOOP_CLASSPATH` variable contains the path to the storage-jar.

**Comment by StephanEwen** [comment]
Okay, if it is an auxiliary classpath then it should be fine.

**Comment by mxm** [comment]
Looks good to merge.

Like Robert said, the `HADOOP_CLASSPATH` is used to add third party libraries. From `hadoop-env.sh`:

    # Extra Java CLASSPATH elements.  Automatically insert capacity-scheduler.
    for f in $HADOOP_HOME/contrib/capacity-scheduler/*.jar; do
    if [ "$HADOOP_CLASSPATH" ]; then
      export HADOOP_CLASSPATH=$HADOOP_CLASSPATH:$f
    else
      export HADOOP_CLASSPATH=$f
    fi
    done

**Comment by rmetzger** [comment]
Merging it.

**Pull request closed without merging**
