### PR TITLE
[FLINK-5488] stop YarnClient before exception is thrown

### PR DESCRIPTION
**Pull request by fanyon**

### CODE REVIEW

**Comment by zentol** [comment]
This looks like something that should be done in a `finally` block.

**Comment by fanyon** [comment]
In `YarnClusterClientV2`, I think yarn client should be stopped in `finalizeCluster()`, which is empty right now

**Comment by tzulitai** [comment]
@fanyon could you rebase this PR?

**Comment by zjureel** [comment]
@tzulitai I have make a new PR https://github.com/apache/flink/pull/4022 for this issue and close this PR soon, thanks :)

**Pull request closed without merging**
