### PR TITLE
[FLINK-20241][hive] Improve exception message when hive deps are miss…

### PR DESCRIPTION
**Pull request by lirui-apache**
…ing on JM/TM

## What is the purpose of the change

When hive deps are missing on JM/TM, users get exception messages like:
```
CorruptConfigurationException: Could not read the user code wrapper: invalid type code: 18
```
This PR is to avoid corrupting the object output stream, so that we instead get exceptions like:
```
ClassNotFoundException: org.apache.flink.connectors.hive.HiveSource
```

## Brief change log

  - Use separate SerDe for `JobConf` in `JobConfWrapper`.
  - Update `HiveTableInputFormat` to use `JobConfWrapper`.
  - Use `SerializedValue` to wrap `StorageDescriptor` and `SerDeInfo` in `HiveTablePartition`, `HiveWriterFactory` and `HiveCompactReaderFactory`.
  - Removed `TimestampedHiveInputSplit` as it's not used any more, so no need to worry about how it's serialized.

## Verifying this change

Existing and added test cases

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: yes
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? NA

### CODE REVIEW

**Comment by StephanEwen** [comment]
The change to `JobConfWrapper` looks good.

For the `SerializableWrapper` - have you considered reusing `SerializedValue` ? It is a similar, only that it lazily deserialized, which makes it easier to supply a custom classloader when needed.

**Comment by lirui-apache** [comment]
@StephanEwen Thanks for reviewing. I wasn't aware of `SerializedValue`. And yes I think we should reuse it.

**Comment by lirui-apache** [comment]
I made `SerializedValue` cache the deserialized value so that we don't deserialize repeatedly. I hope that's OK, otherwise I can do that in the hive classes.

**Comment by rmetzger** [comment]
Side note: I filed a ticket for the unrelated test failure: https://issues.apache.org/jira/browse/FLINK-20360

**Comment by lirui-apache** [comment]
@StephanEwen @JingsongLi Would you mind have a look at the PR? Thanks.

**Comment by StephanEwen** [comment]
Can we put the caching logic into a `CachedSerializedValue`?

I am afraid that changing the `SerializedValue` can break existing code which relies on the fact that a new copy of the object is created on de-serialization.

Otherwise this looks good to me.

**Comment by lirui-apache** [comment]
Hi @StephanEwen , I have reverted the changes to `SerializedValue` and added `CachedSerializedValue` instead. Please have another look.

**Comment by StephanEwen** [comment]
Thanks!
Looks good, +1 from my side!

**Review by JingsongLi — APPROVED** [review]
Thanks for the contribution, looks good to me.

**Pull request merged**
