### PR TITLE
[FLINK-7062] [table, cep] Support the basic functionality of MATCH_RECOGNIZE

### PR DESCRIPTION
**Pull request by dianfu**
## What is the purpose of the change

*This pull request adds the basic support of  MATCH_RECOGNIZE.*

## Brief change log

*(for example:)*
  - *The MATCH_RECOGNIZE clause is transformed to CEP job with the existing CEP API*

## Verifying this change

This change added tests and can be verified as follows:
  - *Added test that validates MATCH_RECOGNIZE is parsed correctly and expected results are got*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)

## Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (JavaDocs)

### CODE REVIEW

**Comment by dianfu** [comment]
@kl0u @dawidwys @wuchong It will be great if you could take a look at this PR. This PR add the basic support for cep on sql. Thanks in advance. :)

**Comment by fhueske** [comment]
I'd like to have a look at this PR as well. Thank you!

**Comment by dianfu** [comment]
@fhueske Great, thanks.

**Comment by dianfu** [comment]
@fhueske @kl0u @dawidwys @wuchong Any feedback?

**Comment by dianfu** [comment]
@fhueske Could you help to take a look at this PR in case you missed? This PR has been ready for more than one month. Very appreciated.

**Comment by dianfu** [comment]
@twalthr  Have updated the PR and looking forward to your comments.

**Pull request closed without merging**
