### PR TITLE
[FLINK-6301] [flink-connector-kafka-0.10] Upgrading Kafka clients version to 0.10.2.0

### PR DESCRIPTION
**Pull request by vidhu5269**

### CODE REVIEW

**Comment by tzulitai** [comment]
Hi @vidhu5269, thanks for the PR!
I agree that we should bump the Kafka 0.10 version, for various reasons (JAAS security feature enhancements, as well as the memory leak you mentioned in the JIRA).

Did you also check if the version bump resulted in any new dependencies?
Also, have you tested this change on a actual cluster execution? We should do that for these version bumps, to test if there's any dependency issues.

**Comment by vidhu5269** [comment]
Hi @tzulitai
Thanx for the quick reply. So far I have only gone through Kafka release notes for api compatibility check and worked with flink unit/integration tests to verify that nothing breaks with this change. 
I will also run a simple consume-transform-produce application within a few days to validate cluster execution as well. 
When you say dependencies, did you mean transitive dependencies which Maven pulls in or do you have something else in mind? Do tell me if I am missing something here.

**Comment by tzulitai** [comment]
Thanks for validating it on cluster execution. Please feel free to ping me on updates.

Yes, I mean the dependencies that Maven pull in. Ideally, `mvn dependency:tree` should be identical before / after the change except from the Kafka 0.10 version bump. If something is different, we should check the extra dependencies' license compatibility with ASL 2.0 as well as any other conflicts with already existing dependencies (which should be justified via the cluster execution).

**Comment by vidhu5269** [comment]
Hi @tzulitai 

Apologies for such a long delay. It took me quite a while to come back to this.

I ran the updated connector on the cluster and didn't see any dependency conflicts. The job using it was reading from a gzipped avro topic and producing into two different topics: a text and an avro topic. Both the consumption and production worked as expected.

It was done on a standalone cluster with 2 workers and 1 master with 8 slots/worker. The job was using 10 slots and was running on the both the workers. Each worker had 8 vCPUs and 8 GB of RAM. 

With this job, I also verified that there wasn't any memory leak with the `kafka-clients` version change.

Following is the diff between the master and version change commit from `mvn dependency:tree`:
```
20c20
< [INFO] +- org.apache.kafka:kafka-clients:jar:0.10.0.1:compile
---
> [INFO] +- org.apache.kafka:kafka-clients:jar:0.10.2.0:compile
27,28c27,28
< [INFO] +- org.apache.kafka:kafka_2.11:jar:0.10.0.1:test
< [INFO] |  +- com.101tec:zkclient:jar:0.8:test
---
> [INFO] +- org.apache.kafka:kafka_2.11:jar:0.10.2.0:test
> [INFO] |  +- net.sf.jopt-simple:jopt-simple:jar:5.0.3:test
31,35c31,33
< [INFO] |  +- org.scala-lang.modules:scala-parser-combinators_2.11:jar:1.0.4:test
< [INFO] |  +- net.sf.jopt-simple:jopt-simple:jar:4.9:test
< [INFO] |  \- org.apache.zookeeper:zookeeper:jar:3.4.6:provided
< [INFO] |     +- jline:jline:jar:0.9.94:provided
< [INFO] |     \- io.netty:netty:jar:3.7.0.Final:provided
---
> [INFO] |  +- com.101tec:zkclient:jar:0.10:test
> [INFO] |  +- org.apache.zookeeper:zookeeper:jar:3.4.6:provided
> [INFO] |  \- org.scala-lang.modules:scala-parser-combinators_2.11:jar:1.0.4:test
70a69
> [INFO] |  |  +- io.netty:netty:jar:3.8.0.Final:provided
```
From what we can see here, apart from the new kafka-clients library, there are a few changes coming from its tests-jar as well.
1. The tests-jar has new version of `net.sf.jopt-simple:jopt-simple` and `com.101tec:zkclient:jar:0.10` in `test` scope. 
2. `jline:jline` is not there in the new version.
3. `3.8.0-Final` of `io.netty:netty` is being pulled in (from `flakka-remote`) instead of `3.7.0-Final`. 

Since the job and the unit tests worked as expected, I am assuming that these dependency changes are not breaking anything. Do tell me if I am missing something here.

Although, these are not new dependencies but I still verified that `zkclient` and `netty` both have ASL 2.0 whereas, jopt-simple has `MIT` which is also compatible with ASL 2.0. So, we should be good as far as licensing goes.

**Comment by vidhu5269** [comment]
I also see that a few of the continuous-integration builds have failed. Is there something I should do in that regard?

**Comment by tzulitai** [comment]
I think the version bump is due to the fact that there are broken API behaviour since moving to 0.10.2.1. See #4321 (I think there's duplicate work here and there).

**Comment by StephanEwen** [comment]
Thank you, @vidhu5269 for diagnosing that and suggesting this fix.

Like @tzulitai mentioned, we need to adjust some more Flink code to be able to use the new Kafka version (unfortunately, Kafka APIs and behavior is not quite as stable as the general claims say).

I would suggest to continue on #4321. @vidhu5269 do you want to try out that version and see if it addresses your issues?

**Comment by vidhu5269** [comment]
Thanx for the support @StephanEwen and @tzulitai.
Sure, we will keep an eye on #4321 and will verify the fix once it's merged.
Feel free to close this pull request.

**Comment by StephanEwen** [comment]
@vidhu5269 The account management from the Apache/Github integration actually means that we cannot manually close pull requests, only via commit messages. So we would need you to close the pull request for us ;-)

**Comment by vidhu5269** [comment]
@StephanEwen : Oh, ok. Didn't know the policy.

**Comment by vidhu5269** [comment]
Closing this pull request as the change mentioned here is already covered as part of #4321.

**Pull request closed without merging**
