### PR TITLE
[FLINK-15706][table-planner-blink] LastValueAggFunctionWithOrderTest compilation error due to incompatible types

### PR DESCRIPTION
**Pull request by JingsongLi**
## What is the purpose of the change

LastValueAggFunctionWithOrderTest failed to compile in nightly build with below error:
```
03:02:41.792 [INFO] -------------------------------------------------------------
03:02:41.792 [ERROR] COMPILATION ERROR : 
03:02:41.792 [INFO] -------------------------------------------------------------
03:02:41.792 [ERROR] /home/travis/build/apache/flink/flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/functions/aggfunctions/LastValueAggFunctionWithOrderTest.java:[78,37] incompatible types: inference variable T has incompatible bounds
    equality constraints: N,java.lang.Byte,N,T,T,T,T,org.apache.flink.table.dataformat.BinaryString,T,T
    lower bounds: java.lang.Byte,org.apache.flink.table.dataformat.BinaryString
```

## Brief change log

Remove all generic type for `AggFunctionTestBase` to avoid potential compile errors.

## Verifying this change

None

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency):no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector:no

## Documentation

  - Does this pull request introduce a new feature?no

### CODE REVIEW

**Comment by JingsongLi** [comment]
I didn't find out why, but keep deep diving.
`LastValueAggFunctionWithOrderTest`  has not been changed for a long time, and relevant changes should not cause this problem.
It seems likely to have something related to the java compiler environment.

This PR remove `Arrays.asList`, which is the most common cause of this error. So I think we can merge this first to avoid potential compile error risk.

**Comment by dawidwys** [comment]
I don't think this is a valid solution. I would not merge this PR as it could just potentially make it even harder to track back the problem.

What I would definitely suggest is to remove the generic parameter from the class `LastValueAggFunctionWithOrderTest` as it is wrong there and tbh it's hard to say to what type it is inferred to. Most probably it's always `Object` 

Also it would make much sense to flatten the structure of those tests.

**Comment by JingsongLi** [comment]
Hi @dawidwys , I removed all generic type for `AggFunctionTestBase` to avoid potential compile errors. Please take a look.

**Comment by JingsongLi** [comment]
Forgot to update commit message.

**Comment by JingsongLi** [comment]
Updated the PR by flatten tests structure instead of removing generic type.

**Pull request closed without merging**
