### PR TITLE
[FLINK-2530]optimize equal() of AcknowledgeCheckpoint

### PR DESCRIPTION
**Pull request by ffbin**
optimize  unwanted check of "that.state != null"

### CODE REVIEW

**Comment by zentol** [comment]
i don't think these statements are equivalent.

Assume that this.state == null and that.state != null.

In the original version we evaluate that.state == null, which is False, so the overall result is False.

In your version we would evaluate (this.state == null || this.state.equals(that.state)), which is True, making the overall result true.

Unless i made a mistake, -1.

**Comment by ffbin** [comment]
@zentol hi. You are right.I want to change 
"(this.state == null ? that.state == null : (that.state != null && this.state.equals(that.state)))" to
"(this.state == null ? that.state == null : this.state.equals(that.state))", because equals()  will check null of  that.state and if  that.state is null it will return false.
What is your suggestion? Thanks.

**Comment by zentol** [comment]
Looking at the pure logic this would work, but you can't remove "that.state != null" since that could result in a NullPointerException inside equals.

**Comment by StephanEwen** [comment]
Is this really in need of optimization? It is written failsafe, where it does not crash even if `state` does not handle null values properly. This is good, because it helps prevent future bugs. The performance cost is minimal.

Concerning performance:  This is an actor message send and processed asynchronously by the JobManager. These code paths should never saturate the CPU in any reasonable setup, and even the computation during the processing of this message is dominated by other parts (cache misses during hash table lookups). Checking more, this method is never even executed. It is there only for the sake of testing / debugability.

Please double check whether statements really need fixing. Eliminating checks for the sake of performance is really only necessary on the most performance critical code paths (the inner loops of the runtime operators and algorithms).

**Comment by ffbin** [comment]
@zentol @StephanEwen Thanks.This is not performance critical code and  some check is better.

**Pull request closed without merging**
