### PR TITLE
[FLINK-8006] [Startup Shell Scripts] Enclosing $pid in quotes

### PR DESCRIPTION
**Pull request by elbaulp**
## What is the purpose of the change

When executing `./bin/start-local.sh` The following errors appears:

flink-1.3.2/bin/flink-daemon.sh: line 79: $pid: ambiguous redirect

This is because $pid contains spaces, so to fix it I've enclose I replaced all $pid by "$pid"

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

No

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by greghogan** [comment]
Do we also need to quote within sub-expressions? Have you looked at the stop script?

**Comment by elbaulp** [comment]
@greghogan Didn't realized!, its failing too. I am going to fix it.

**Comment by elbaulp** [comment]
@greghogan Done, sorry for ignoring the stop script.

**Comment by greghogan** [comment]
@elbaulp au contraire, thank you for fixing this bug. Do we need quotes for the following?

line 69: pid=$FLINK_PID_DIR/flink-$FLINK_IDENT_STRING-$DAEMON.pid
line 181: done < ${pid}.tmp
line 182: rm ${pid}.tmp

**Comment by elbaulp** [comment]
@greghogan Oh, of course, didn''t saw it, how many $pids! Done.

**Comment by greghogan** [comment]
+1

**Comment by StephanEwen** [comment]
LGTM

+1 to merge

**Comment by elbaulp** [comment]
Hi, Do I need to do something more in order to this PR be merged?

**Comment by zentol** [comment]
merging.

**Pull request closed without merging**
