### PR TITLE
[FLINK-6232] [table] Add processing time window inner join to SQL.

### PR DESCRIPTION
**Pull request by fhueske**
This is continuation and extension of PR #3715 and #4266 by @hongyuhong.

### CODE REVIEW

**Comment by wuchong** [comment]
The code looks good to me. Good refactoring!

+1 to merge.

BTW, I have a question. This time-windowed join is different with `DataStream.join(...).window(...)`.  The `DataStream.join.window` is joining two streams on a same window (such as 1 hour tumbling window).  Do we have plan to support it?

**Comment by fhueske** [comment]
Thanks for the review @wuchong. 

The `DataStream` join semantics can be implemented with this join by first window grouping both inputs with a UDAGG that collects all records in a list, and then joins the lists on the same time with `left.t BETWEEN right.t AND right.t` (we do not support a single `==` predicate on time so we need `>=` and `<=`, but this could be added, IMO). And then a UDF that crosses the lists. 

I think this is how you would need to do it in SQL (you could use UNNEST to do the Cartesian product). The Table API could have a syntactic shortcut for that but the internal logical representation would again be the same. 

Not sure if it adds much value. I think the windowed join semantics of this PR are nicer because they do not have cut-off points at the window boundaries (two records could be only 3 msecs apart but would not join because they are in different tumbling windows).

**Comment by fhueske** [comment]
Hi @hongyuhong, it would be great if you could have a look as well since this PR is mostly your work.  
I'll appreciate any feedback.

Thank you, Fabian

**Comment by hongyuhong** [comment]
Hi @fhueske, sorry for the late feedback. The refactoring looks pretty great to me, i think it's good to be merged. The only thing i worry about is that there is no enough message for the user to figure out the exact error, do we have plan to improve this?

Thanks very much.
Yuhong

**Comment by fhueske** [comment]
Hi @hongyuhong, thanks for your feedback!
I agree, passing good error messages to users is important. However, this is very difficult in the optimizer because the optimizer is exploring different paths. If we throw an exception in the optimizer, we would kill the exploration and miss a valid plan. That's why I'm very hesitant to throw exceptions in rules. However, if the optimizer does not find a valid execution plan, it quits with an error message that tells the user that no valid plan could be found but does not point to a particular problem (such as an invalid join condition). 

A good solution for this is still needed. Maybe we can collect potential problems during optimization and provide these when the translation fails.

**Comment by fhueske** [comment]
Merging.

I'll open a JIRA to discuss how to pass error messages to users.

Thanks @hongyuhong and @wuchong!

**Pull request closed without merging**
