### PR TITLE
[FLINK-32539][tests] Update violations as a result of FLINK-27415 changes

### PR DESCRIPTION
**Pull request by snuyanzin**
## What is the purpose of the change

The PR updates violations after changes done at https://github.com/apache/flink/pull/20006

the changes is a result of 
```
mvn verify -pl flink-architecture-tests/flink-architecture-tests-production/ -Darchunit.freeze.store.default.allowStoreUpdate=true
```

## Verifying this change

This change is a trivial rework 

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: ( no)
  - The runtime per-record code paths (performance sensitive): ( no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: ( no)
  - The S3 file system connector: ( no)

## Documentation

  - Does this pull request introduce a new feature? ( no)
  - If yes, how is the feature documented? (not applicable )

### CODE REVIEW

**Review by reswqa — APPROVED** [review]
Thanks for the fix!

**Review by dannycranmer — APPROVED** [review]

**Comment by dannycranmer** [comment]
@snuyanzin thanks for fixing this

**Comment by zentol** [comment]
I'm curious why the architecture tests didn't fail in #20006.

**Comment by snuyanzin** [comment]
I guess because the PR was based on commits from Jun **2022** (more than 1 year ago)

**Comment by zentol** [comment]
that explains it :sweat_smile:

**Comment by hanyuzheng7** [comment]
@snuyanzin thank you for fix it.

**Pull request merged**
