### PR TITLE
[FLINK-19594][web] Make subtask index start from zero

### PR DESCRIPTION
**Pull request by zlzhang0122**
What is the purpose of the change
This pull request modified web ui subtasks starting index from 0, which can make consistent in the REST API.

Brief change log
*modify web ui subtasks starting index, remove +1 syntax

Verifying this change
This change is a trivial rework / code cleanup without any test coverage.

## Documentation
This pull request doesn't introduce a new feature.

### CODE REVIEW

**Comment by Myasuka** [comment]
@flinkbot run azure

**Comment by Myasuka** [comment]
Thanks for your contribution, @zlzhang0122 Could you please paste the new web UI pictures here after applying your changes?

**Comment by zlzhang0122** [comment]
> Thanks for your contribution, @zlzhang0122 Could you please paste the new web UI pictures here after applying your changes?

Sure.
SubTasksTab
BackpresureTab
CheckpointTab

**Comment by Myasuka** [comment]
The changes LGTM, @zlzhang0122 could you squash your commits as single one commit?
I noticed that you have one commit to modify the time format and the other two commits to merge branch when I plan to merge your code.

BTW, I think `[FLINK-19594][web] Make subtask index start from zero` could be a better title.

**Comment by zlzhang0122** [comment]
> The changes LGTM, @zlzhang0122 could you squash your commits as single one commit?
> I noticed that you have one commit to modify the time format and the other two commits to merge branch when I plan to merge your code.
> 
> BTW, I think `[FLINK-19594][web] Make subtask index start from zero` could be a better title.

@Myasuka Thanks for your reply, I have finished it.

**Comment by Myasuka** [comment]
@zlzhang0122 Could you rename your commit title also as `[FLINK-19594][web] Make subtask index start from zero`? We don't have component as `[flink-runtime-web]`. Moreover, don't leave spaces between `[FLINK-19594]` and `[web]`.

**Comment by zlzhang0122** [comment]
> [FLINK-19594][web] Make subtask index start from zero

Sure.

**Comment by zlzhang0122** [comment]
> @zlzhang0122 Could you rename your commit title also as `[FLINK-19594][web] Make subtask index start from zero`? We don't have component as `[flink-runtime-web]`. Moreover, don't leave spaces between `[FLINK-19594]` and `[web]`.

Sure.

**Pull request merged**
