### PR TITLE
[hotfix] Update copyright NOTICE year to 2024

### PR DESCRIPTION
**Pull request by caicancai**
## What is the purpose of the change

Update copyright NOTICE year to 2024

## Brief change log
Update copyright NOTICE year to 2024

## Verifying this change
Update copyright NOTICE year to 2024

## Does this pull request potentially affect one of the following parts:

no

## Documentation
Does this pull request introduce a new feature? (no)
If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by caicancai** [comment]
@1996fanrui @RocMarshal  If you have time, can you help reivew some of this PR, thank you

**Review by 1996fanrui — APPROVED** [review]
Thanks @caicancai for the fix! 

The change LGTM, would you mind updating the PR description as well?

**Comment by caicancai** [comment]
> would you mind updating the PR description as well?

**Comment by caicancai** [comment]
> Thanks @caicancai for the fix!
> 
> The change LGTM, would you mind updating the PR description as well?

OK，Do you think this modification is appropriate?

**Pull request closed without merging**
