### PR TITLE
[FLINK-9339] Accumulators are not UI accessible running in FLIP-6 mode

### PR DESCRIPTION
**Pull request by yanghua**
## What is the purpose of the change

*This pull request fixed a issue : accumulators are not UI accessible running in FLIP-6 mode*

## Brief change log

  - *fixed header and handler error mapping*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by yanghua** [comment]
cc @zentol

**Comment by zentol** [comment]
This does fix the issue, but I'd like to extend this a bit. The root issue is that we're registering the handler for an arbitrary header, which is ridiculously error-prone.

So i propose changing all instances of
`handlers.add(Tuple2.of(<arbitrary_headers>, <handler>));`
to 
`handlers.add(Tuple2.of(<handler>.getMessageHeaders(), <handler>));`

**Comment by yanghua** [comment]
@zentol you mean change all places in this PR?  current change can fix the issue, for others, I think in a new issue we could do the refactor. what's your idea? 
if you agree this suggestion, I could create a new refactor issue. if not I will change all the places.

**Comment by zentol** [comment]
we can do it in this issue.

**Comment by yanghua** [comment]
cc @zentol

**Comment by zentol** [comment]
merging.

**Pull request closed without merging**
