### PR TITLE
[FLINK-22602][Formats][Parquet] Upgrade Parquet dependency to 1.12.2

### PR DESCRIPTION
**Pull request by cuibo01**
## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by Airblader — APPROVED** [review]

**Comment by cuibo01** [comment]
@xintongsong @dianfu @JingsongLi @aljoscha pls review, thx

**Comment by cuibo01** [comment]
@twalthr @sjwiesman @StephanEwen @zentol pls review, thx

**Comment by cuibo01** [comment]
@twalthr @lirui-apache @rkhachatryan @guoweiM @dianfu pls review, thx

**Comment by cuibo01** [comment]
@tillrohrmann can u review the pr?

**Comment by cuibo01** [comment]
@xintongsong hi can you review this pr？

**Comment by cuibo01** [comment]
@rmetzger @AHeise @tsreaper hi can you review this pr？

**Comment by MartijnVisser** [comment]
@cuibo01 Could you upgrade to the latest version of the Parquet dependencies? I see that 1.12.2 is now released.

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Comment by MartijnVisser** [comment]
@cuibo01 Can you also please rebase on master and squash your commits? Sorry for the hassle.

**Comment by cuibo01** [comment]
> @cuibo01 Can you also please rebase on master and squash your commits? Sorry for the hassle.

ok thx @MartijnVisser

**Comment by cuibo01** [comment]
> @cuibo01 Can you also please rebase on master and squash your commits? Sorry for the hassle.

hi @MartijnVisser , github provides rebase and squash, and does not need to be manually combined.

**Comment by MartijnVisser** [comment]
@cuibo01 I know, but the CI won't pass without you rebasing since this is still pointing to a CI installation that's no longer valid. Without a green CI build, the PR can't get merged.

**Comment by cuibo01** [comment]
> @cuibo01 I know, but the CI won't pass without you rebasing since this is still pointing to a CI installation that's no longer valid. Without a green CI build, the PR can't get merged.

got it , i have rebase and squished

**Comment by cuibo01** [comment]
@MartijnVisser squished done, can u review and merge?

**Comment by MartijnVisser** [comment]
@cuibo01 I've done, the code looks good but the commit isn't according to the commit naming conventions (see https://flink.apache.org/contributing/code-style-and-quality-pull-requests.html#commit-naming-conventions)

Could you change it to `[FLINK-22602][Formats][Parquet] Upgrade Parquet dependency to 1.12.2`

**Review by MartijnVisser — APPROVED** [review]
Thanks for this @cuibo01 LGTM
@fapaul Can you merge this?

**Comment by cuibo01** [comment]
thx for your review @MartijnVisser @Airblader , @fapaul can u merge the mr, thx

**Pull request merged**
