### PR TITLE
[hotfix] Compile error of ForStStateExecutor

### PR DESCRIPTION
**Pull request by Zakelly**
## What is the purpose of the change

Compile error due to creating invoker from one PR and modifying the signature by another PR.

### CODE REVIEW

**Comment by Zakelly** [comment]
I'd propose we merge this ASAP after the CI compile stage passed.

**Review by fredia — APPROVED** [review]

**Comment by Zakelly** [comment]
@flinkbot run azure

**Comment by Zakelly** [comment]
@flinkbot run azure

**Comment by Zakelly** [comment]
Compile CI passed: https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=62691&view=logs&s=ab6e269b-88b2-5ded-2544-4aa5b1124530&j=b59e5554-36c7-5512-ab1a-b80b74075fce

Merging...

**Pull request merged**
