### PR TITLE
[FLINK-4839] [cluster management] JobManager handle TaskManager's slot offering

### PR DESCRIPTION
**Pull request by KurtYoung**
This PR is based on #2643 , only the last commit is related.

### CODE REVIEW

**Comment by tillrohrmann** [comment]
Changes look good to me. Thanks for your contribution. +1 for merging.

**Comment by tillrohrmann** [comment]
Will merge it :-)

**Comment by tillrohrmann** [comment]
You can close this PR now.

**Comment by KurtYoung** [comment]
Thanks for you reviewing @tillrohrmann , closing it now.

**Pull request closed without merging**
