### PR TITLE
[FLINK-4091] Fix Guava shading in Cassandra connector

### PR DESCRIPTION
**Pull request by zentol**
This PR modifies the guava shading in the Cassandra connector. It no longer uses the same pattern as flink-dist which lead to version conflicts.

### CODE REVIEW

**Comment by theomega** [comment]
Are you sure that this fixes the problem (I haven't tried): The change only changes the references in the connectors-code to the new package. But someone needs to provide this package, or am I getting something wrong?

**Comment by zentol** [comment]
you are right, guava is not properly included and shaded under the new reference.

**Comment by zentol** [comment]
*now

**Comment by rmetzger** [comment]
Just verified the fix.

+1 to merge

**Comment by zentol** [comment]
merging

**Pull request closed without merging**
