### PR TITLE
[FLINK-23189][checkpoint] Count and fail the task in case of IOExceptions in CheckpointCoordinator

### PR DESCRIPTION
**Pull request by pnowojski**
This PR supersedes https://github.com/apache/flink/pull/16637. It's adding a two commits on top of the original one.

## What is the purpose of the change

This pull request make some kinds of failures be checked against CheckpointFailureManager and be deciding whether these errors should be just logged or checked against the number of tolerable failures and maybe fail the job. So it separate IO_EXCEPTION from TRIGGER_CHECKPOINT_FAILURE enum and add IO_EXCEPTION to the reason which will checked against the number of tolerable failures. With this we can let users perceived some unrecoverable error faster. Also it Migrate from EXCEPTION enum to IO_EXCEPTION because according to the code it is exactly IO_EXCEPTION.

## Brief change log

  - *Separate IO_EXCEPTION from TRIGGER_CHECKPOINT_FAILURE enum*
  - *Add IO_EXCEPTION to identify the disk error and increase the number of failure count*
  - *Add a unit test case for IO_EXCEPTION scene*
  - *Migrate from EXCEPTION enum to IO_EXCEPTION*

## Verifying this change

  - *Added IO_EXCEPTION scene to CheckpointCoordinatorTest and modify the number of CheckpointFailureManagerTest*
  - *Add unit test case in CheckpointCoordinatorTest for IO_EXCEPTION scene*
  - *Modify JobMasterStopWithSavepointITCase for IO_EXCEPTION scene*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Review by akalash — APPROVED** [review]
LGTM

**Comment by tillrohrmann** [comment]
@pnowojski I guess it was an oversight but squashing fixup commits is usually a good practice.

**Comment by pnowojski** [comment]
@tillrohrmann thanks for pointing this out, but I left those commits separate on purpose as they are authored by two different persons and I don't want to take over authorship of others work. Both from the respect to the contributions and from potential legal reasons.

**Comment by tillrohrmann** [comment]
Then I would suggest to not use git's `--fixup` functionality because it can lead to problems if people use the `autosquash` feature when rebasing. If they choose a revision that is before the commit you are fixing, then it will automatically squash it. That again will lead to incompatible commit histories.

**Pull request merged**
