### PR TITLE
[FLINK-25536] Adjust the order of variable declaration and…

### PR DESCRIPTION
**Pull request by zuston**
… comment in StateAssignmentOperation

## What is the purpose of the change

Just to adjust the order of variable declaration and comment in StateAssignmentOperation

### CODE REVIEW

**Review by Myasuka — APPROVED** [review]
Thanks for the contribution! The PR LGTM.

Please rename the commit message to get rid of `Minor Fix:`.

**Comment by zuston** [comment]
Done. 
Thanks for your review @Myasuka.

**Comment by zuston** [comment]
@flinkbot run azure

**Comment by zuston** [comment]
Thanks @Myasuka

**Pull request merged**
