### PR TITLE
[hotfix][docs] Updated description of HOP and CUMULATE parameters

### PR DESCRIPTION
**Pull request by mans2singh**
## What is the purpose of the change

* Description and markup update

## Brief change log

* Description and markup update

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by mans2singh** [comment]
@Airblader,  @tisonkun, @wuchong, @leonardBang - Can you please review this documentation PR and let me know your feedback ? Thanks

**Review by Airblader — APPROVED** [review]
LGTM, thanks for fixing this! We need to re-run Azure to get the CI to pass, though.

**Comment by Airblader** [comment]
@flinkbot run azure

**Review by leonardBang — APPROVED** [review]
LGTM

**Comment by Airblader** [comment]
I'm guessing the PR needs to be rebased so that CI can pass.

**Comment by mans2singh** [comment]
@Airblader @leonardBang - Thanks for your review.   Please let me know if there is anything required from my side.   Thanks

**Comment by mans2singh** [comment]
@Airblader @leonardBang @wuchong @tisonkun - Please let me know if you have any recommendations on this PR.  Thanks.

**Comment by leonardBang** [comment]
@mans2singh The CI test is failed so we can not merge this one as the community discussed in mail list _**[DISCUSS] Do not merge PRs with "unrelated" test failures.**_, I suggest you to re-trigger the CI test (command: ```@flinkbot run azure```) or rebase your code to latest master which also can trigger the CI.

**Comment by mans2singh** [comment]
@leonardBang I've rebased the branch against master.  Please let me know if you have any additional recommendations.  Thanks again.

**Comment by leonardBang** [comment]
Thanks @mans2singh The build has passed, I‘ll find committer to help merge soon

**Review by godfreyhe — APPROVED** [review]

**Pull request merged**
