### PR TITLE
[FLINK-1767] [streaming] Make StreamExecutionEnvironment return JobExecutionResult

### PR DESCRIPTION
**Pull request by ggevay**

### CODE REVIEW

**Comment by hsaputra** [comment]
Could give more description about how you go about with the PR?

**Comment by hsaputra** [comment]
Will help review if more description about the direction of the patch

**Comment by ggevay** [comment]
Yes, sorry for not providing a description.
I changed the return type of StreamExecutionEnvironment.execute() from void to JobExecutionResult, and then added return statements to all the implementations. I also changed the return type of ClusterUtil.runOnMiniCluster, since that was called by the above functions.
I tested the modification by printing the netRuntime field of the JobExecutionResult in one of the streaming examples.

**Comment by rmetzger** [comment]
LGTM

**Comment by mbalassi** [comment]
The integration for the scala AP is missing, other than that LGTM. Merging it and adding the scala.

**Pull request closed without merging**
