### PR TITLE
[FLINK-28938][hive] Fix HiveServer2 Endpoint can not set variable correctly

### PR DESCRIPTION
**Pull request by luoyuxia**
## What is the purpose of the change
To fix HiveServer2 Endpoint can not set variable correctly.

## Brief change log
  -  Call method `HiveSetProcessor#setVariable` to set variable.

## Verifying this change
UT in `HiveServer2EndpointITCase#testOpenSessionWithConfig`.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Review by fsk119 — COMMENTED** [review]
I add a commit to improve the messages when invoking unsupported exception

**Comment by luoyuxia** [comment]
@fsk119 Thanks for the appended commit. The commit LGTM.

**Comment by fsk119** [comment]
@flinkbot run azure

**Comment by fsk119** [comment]
@flinkbot run azure 

The pipeline blocks. rerun

**Comment by fsk119** [comment]
@flinkbot run azure

**Pull request merged**
