### PR TITLE
[FLINK-11042][kafka,tests] Drop invalid kafka producer tests

### PR DESCRIPTION
**Pull request by pnowojski**
Main point of testFlinkKafkaProducerFailTransactionCoordinatorBeforeNotify is to fail transaction coordinator (by using kafkaProducer.getTransactionCoordinatorId(); ) and we expect that this will cause failure of Flink job. However that's not always the case. Maybe because transaction coordinator can be re-elected before KafkaProducer even notices it or for whatever the reason, sometimes the failure is not happening.

Because of a bug in the test, if failure hasn't happened, the test will not fail.

Generally speaking this test is invalid and should be dropped.

## Brief change log

besides dropping the tests there are couple of hotfixes (please check individual commits for more information).

## Verifying this change

This pr is touching only a test code.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by tzulitai** [comment]
@pnowojski can you help me understand why the test is failing if the job isn't failing?
If the job isn't failing, shouldn't the exactly-once verification still pass anyways?

**Comment by pnowojski** [comment]
@tzulitai honestly no idea. The test was/is deadlocking from time to time and looking at how much time we had to investigate previously into debugging Kafka deadlocks, I don't think it's worth it for the test that we would like to drop anyway. I'm hoping that either we will not be triggering this deadlock in the other tests or that Kafka guys will fix it before we encounter it again in some hypothetical future test.

**Comment by tzulitai** [comment]
Ok. Since we've already been removing tests that rely on shutting down Kafka brokers (which were mostly the ones causing a lot of the instabilities), I don't feel strongly against removing this one either.

+1 from my side.

**Comment by pnowojski** [comment]
Thanks, merging.

**Pull request merged**
