### PR TITLE
FLINK-3839 Added the extraction of jar files from a URL spec that is …

### PR DESCRIPTION
**Pull request by thormanrd**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.
- [ ] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)
- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added
- [ ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

…a directory in the form of file:///path/to/jars/<*>

### CODE REVIEW

**Comment by rmetzger** [comment]
Thank you for your contribution. There is a typo in the pull request title. its important that its correct so that our jira picks up the pull request.
Please also check out our contribution guidelines: http://flink.apache.org/contribute-code.html

They state in particular the following:
> No reformattings. Please keep reformatting of source files to a minimum. Diffs become unreadable if you (or your IDE automatically) remove or replace whitespaces, reformat code, or comments. Also, other patches that affect the same files become un-mergeable. Please configure your IDE such that code is not automatically reformatted. Pull requests with excessive or unnecessary code reformatting might be rejected.

**Comment by thormanrd** [comment]
Corrected the typo.  Gotta add FLINK to my dictionary.

**Comment by StephanEwen** [comment]
I think we unfortunately need to redo this pull request.
It is almost impossible to review, because 90% of the changes in the diff are code re-formattings. It is very hard to spot lines with actual changes, so details will almost certainly slip the reviewer.

I hop you still have the changes prior to applying the auto-code reformat actions.

**Comment by thormanrd** [comment]
I do have them.  I need to make time to re-do the PR.  What is the best way to sync my fork with the apache master?  I can pull from apache master, push to my forked master?  Or should I create a PR from apache master to my forked master?  Or does it matter?

**Comment by mxm** [comment]
Hi @thormanrd! Thanks for your PR. As Robert and Stephan already pointed out, it contains a lot of reformats which are generally encouraged. They make the pull request's essentials hard to review and can even introduce subtle bugs. 

The prefered way of syncing up with the master is to rebased against the master before you open a pull request:

```
git pull --rebase upstream master
``` 
`upstream` is the main Flink repository. Maybe it's called `origin` in your case. Check using `git remote -v`.

After the pull request has been opened you should only push additional commits (no rebasing) to keep the comments and discussion. In the end, either you or the committer rebases again.

**Pull request closed without merging**
