### PR TITLE
[FLINK-10784] Update FlinkKafkaConsumerBaseMigrationTest for 1.7

### PR DESCRIPTION
**Pull request by yanghua**
## What is the purpose of the change

*This pull request updates FlinkKafkaConsumerBaseMigrationTest for 1.7*

## Brief change log

  - *Update FlinkKafkaConsumerBaseMigrationTest for 1.7*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by zentol** [comment]
@yanghua Can you explain how you generated the snapshots? (step-by-step)

**Comment by yanghua** [comment]
Hi @zentol I followed this `TODO` message : 

```
/**
	 * TODO change this to the corresponding savepoint version to be written (e.g. {@link MigrationVersion#v1_3} for 1.3)
	 * TODO and remove all @Ignore annotations on write*Snapshot() methods to generate savepoints
	 */
private final MigrationVersion flinkGenerateSavepointVersion = null;
```
step 1:
changed the `null` to `MigrationVersion.v1_7` and 

step 2:
removed the `@ignore` annotation in method `writeSnapshot`, 

step 3:
then run this test method.

step 4:
recover the `@ignore` annotation and reset `flinkGenerateSavepointVersion` to `null`

**Comment by zentol** [comment]
with the current master?

**Comment by yanghua** [comment]
Yes, it seems that this is wrong, I think I should do these things on the release-1.7.0 branch.

**Comment by zentol** [comment]
correct 👍

**Comment by yanghua** [comment]
@zentol Thank you for your guidance, I will update the snapshot file.

**Comment by yanghua** [comment]
@zentol Now all the snapshot files of the PRs about Migration opened by me have been regenerated based on the tag `release-1.7.0`.

**Pull request merged**
