### PR TITLE
[FLINK-7069] [metrics] Granular exception catching in MetricRegistry

### PR DESCRIPTION
**Pull request by zentol**
This PR makes the exception catching in the MetricRegistry more granular when adding or removing metrics.

A reporter that throws an exception prevented other reporters, the MetricQueryService and the ViewUpdater from being notified about added or removed metrics.

### CODE REVIEW

**Comment by aljoscha** [comment]
The changes look good! 👍 

What about a test, though? 😅

**Comment by zentol** [comment]
sure, i can add a test.

**Comment by zentol** [comment]
@aljoscha added a test

**Comment by aljoscha** [comment]
Perfect, this LGTM now!

**Comment by zentol** [comment]
merging.

**Pull request closed without merging**
