### PR TITLE
[FLINK-7133]Excluding optional asm dependencies from elasticsearch 

### PR DESCRIPTION
**Pull request by Adebski**

### CODE REVIEW

**Comment by tzulitai** [comment]
Thanks for the PR @Adebski!
Given that this was tested already for both local and cluster execution,+1 from me once Travis is green.
Could you also include a comment, preferably referencing the JIRA, on why the dependency is excluded?

**Comment by Adebski** [comment]
You mean in the pom.xml itself yes?

**Comment by tzulitai** [comment]
yes

**Comment by aljoscha** [comment]
Thanks for fixing this @Adebski. 👍 I merged, could you please close this PR?

**Pull request closed without merging**
