### PR TITLE
fix scrolling issue in Firefox

### PR DESCRIPTION
**Pull request by lovelock**
## What is the purpose of the change

1. Fix scrolling bug in Firefox. Logs view both in TaskManager and JobManager can't scroll with mouse in Firefox because of the bug in monaco-editor of version 0.16.0, which is mentioned [here](https://github.com/microsoft/monaco-editor/issues/1353)

## Brief change log

1. Upgrade monaco-editor from `^0.16.0` to `^0.18.0`. The current version of monaco-editor is 0.22.3, but it won't compile.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

### CODE REVIEW

**Review by Airblader — APPROVED** [review]
LGTM, we should get this merged.

**Comment by Airblader** [comment]
@vthinkxie This is a pretty small and straight-forward fix. Would be good if someone with merge rights took a look.

**Comment by Airblader** [comment]
This will actually also be fixed by #16603.

**Comment by twalthr** [comment]
Should be fixed in #16603. Please reopen if this is not the case.

**Pull request closed without merging**
