### PR TITLE
[FLINK-27794][connectors/jdbc] Fix the wrong primary key for MysqlCatalog when there are tables with same name in different databases

### PR DESCRIPTION
**Pull request by dusukang**
## What is the purpose of the change
Use MysqlCatalog to get the primary key of the table when there are tables with same name in different databases.

## Brief change log
Pass the database name as catalog parameter for retrieving primary keys by full table identifier in `metaData.getPrimaryKeys(database, schema, table)`

## Verifying this change
This change is a code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by dusukang** [comment]
@flinkbot run azure

**Comment by dusukang** [comment]
see[https://github.com/apache/flink/pull/19741](https://github.com/apache/flink/pull/19741)

**Comment by dusukang** [comment]
cc @leonardBang

**Comment by dusukang** [comment]
@flinkbot run azure

**Comment by dusukang** [comment]
@flinkbot run azure

**Comment by leonardBang** [comment]
Thanks @dusukang for the contribution, LGTM

**Review by leonardBang — APPROVED** [review]

**Pull request merged**
