### PR TITLE
[FLINK-31131][doc] Fix the missed INITIALIZING of ExecutionState in the state_machine doc

### PR DESCRIPTION
**Pull request by WencongLiu**
## What is the purpose of the change

*This pull request is proposed to fix the missed INITIALIZING of ExecutionState in the state_machine doc.*

## Brief change log

  - * Fix the missed INITIALIZING of ExecutionState in the state_machine doc.*

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Review by liuyongvs — APPROVED** [review]
LGTM

**Review by 1996fanrui — APPROVED** [review]
Hi @WencongLiu , thanks for the contribution.

Could you update the PR title and commit message to `[FLINK-31131][doc] Fix the missed INITIALIZING of ExecutionState in the state_machine doc`?  We should add the module name and the initial letter should be upper case.

And these changes LGTM.



LGTM,

**Comment by WencongLiu** [comment]
> Hi @WencongLiu , thanks for the contribution.
> 
> Could you update the PR title and commit message to `[FLINK-31131][doc] Fix the missed INITIALIZING of ExecutionState in the state_machine doc`? We should add the module name and the initial letter should be upper case.
> 
> And these changes LGTM.

Done. @1996fanrui

**Comment by 1996fanrui** [comment]
Thanks for the update, merging.

**Pull request merged**
