### PR TITLE
[FLINK-20727][connector] pulsar SourceFunction

### PR DESCRIPTION
**Pull request by jianyun8023**
## What is the purpose of the change

Add the `SourceFunction` implementation of Pulsar to the connector.

## Brief change log

- Add Pulsar SourceFunction implementation
- Supports exactly-one
- Support dynamic discovery of Topic
- Implementation is similar to kafka

## Verifying this change

This change added tests and can be verified as follows:

- Adding basic tests for Source (start, stop, snapshot, checkpoint)
- Pulsar service based on testcontainers
- Unit tests for Pulsar authentication functionality
- Topic dynamic discovery tests
- Pulsar client cache tests
- Watermark function testing

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**yes** / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (**yes** / no)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / **don't know**)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (**yes** / no)
  - If yes, how is the feature documented? (not applicable / **docs** / **JavaDocs** / not documented)

### CODE REVIEW

**Comment by AHeise** [comment]
Sorry for coming back so late to this PR. Code-wise, it looks mostly fine. I would add a complete code review later.

However, I'd like to clarify first, why we want to have the old implementation in Flink master at all. From my perspective, this is instant legacy. So there needs to be a strong reason to have it compared to merge only the new interfaces.

Possible reasons could include features that cannot be supported with the new PulsarSource. In general, when would a user choose the old implementation over the new implementation given that the new source interface is quite stable in Flink 1.13?

I'm duplicating the reply to the Sink PR as the answer may be different.

**Comment by jianyun8023** [comment]
> Sorry for coming back so late to this PR. Code-wise, it looks mostly fine. I would add a complete code review later.
> 
> However, I'd like to clarify first, why we want to have the old implementation in Flink master at all. From my perspective, this is instant legacy. So there needs to be a strong reason to have it compared to merge only the new interfaces.
> 
> Possible reasons could include features that cannot be supported with the new PulsarSource. In general, when would a user choose the old implementation over the new implementation given that the new source interface is quite stable in Flink 1.13?
> 
> I'm duplicating the reply to the Sink PR as the answer may be different.

Because the older version of Source has been verified in production and is stable for users to use. The implementation in the new version has yet to be verified.
This is the reason why I want to keep the old version of Source.

**Comment by jianyun8023** [comment]
If you only need the new version of the source implementation, I can just submit the new version of the implementation and make the Table based on the new Source.

**Comment by AHeise** [comment]
> Because the older version of Source has been verified in production and is stable for users to use. The implementation in the new version has yet to be verified.
> This is the reason why I want to keep the old version of Source.

That's certainly a good argument, but why wouldn't the users simply take the streamnative version if they want to have the stable version?

I'm mostly concerned that if we reach a stable version in the process of bugfixing Flink 1.13, we will add (for all practical purposes) dead code in this PR. Even worse, it may confuse users and they may accidentally choose the old version instead of the new version. Then, the user may experience all the downsides of the old source architecture without even realizing it (there are a few implications regarding checkpointing). To solve it, I guess we would mark the `PulsarSourceFunction` as deprecated, which would mean that we would add code now for 1.13.0 and deprecate it in 1.13.X or latest in 1.14.0. So we are adding code now where we immediately need to think about how to get rid of.

I think the best argument for merging the PR is that the user may actually use the stable `PulsarSourceFunction` in 1.13.0 and then switch to the new `PulsarSource` in 1.13.X without changing dependencies. Another important consideration is if the user can use the old function for use cases where the new `PulsarSource` does not suffice (yet).

Another option is that we prepare this PR (1-2 review cycles) and leave it unmerged until we know that the new `PulsarSource` misses critical feature for 1.13 and merge it then. Until then, I'd prefer to bet on a good first `PulsarSource` (I have no doubts that you will make a good job in porting it) and solve any actual issues with fast bugfix releases.

**Comment by jianyun8023** [comment]
We discussed it and we started by merging the new Source, which allows Flink to not carry the old baggage, the old version is supported and we maintain it in the streamnative/pulsar-flink repository. I'm submitting the new Source implementation today.

**Comment by AHeise** [comment]
Okay sounds good. Then let's close this PR for the time being. If we still see a need for it after having the new source in, we can still reopen.

**Comment by AHeise** [comment]
@jianyun8023 Sorry I have probably missed the new PRs and can't find them through PR search, could you please link them to me (or add me as a reviewer?).

**Comment by jianyun8023** [comment]
> @jianyun8023 Sorry I have probably missed the new PRs and can't find them through PR search, could you please link them to me (or add me as a reviewer?).
@AHeise Sorry it took so long to push up the Pulsar implementation based on the `Source` interface. I'm sorry for making you wait so long.

new Pulsar Source: #15304

**Pull request closed without merging**
