### PR TITLE
[FLINK-14578][table] load/unloadModule() should throw RuntimeException rather than checked exception

### PR DESCRIPTION
**Pull request by bowenli86**
## What is the purpose of the change

To adhere to FLIP to make load/unloadModule() API throw RuntimeException rather than checked exceptions.

Very sorry again for not conforming to what we proposed in our FLIP.

## Brief change log

- made load/unloadModule() throw ValidationException as discussed with Dawid

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)
## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by bowenli86** [comment]
@dawidwys @xuefuz @lirui-apache @zjuwangg

**Comment by bowenli86** [comment]
@dawidwys @xuefuz @lirui-apache @zjuwangg

**Comment by bowenli86** [comment]
@dawidwys @lirui-apache @zjuwangg

**Comment by bowenli86** [comment]
> Thanks for the contribution. The diff itself looks fine. However, wouldn't it be better if we change existing exception classes (such as ModuleNotFoundException) to runtime?
> 
> The downside of having a general exception (such as ValidationException) is the difficult for an exception handler to differentiate the root cause. (Otherwise, one would have to parse the exception msg.)
> 
> Thus, I prefer retaining the existing exception classes but changing them to runtime.

I'm not sure if catching the unchecked exception here is optimal for users as they are not declared in API signature and users aren't sure what unchecked exceptions will be thrown unless looking at implementations. Besides, loading/unloading module will most likely happen via config or interactive programming, in which case the error message matters more. If users ran into this via a table API program, that's a bug and they should fix their program rather than catching the exceptions. Thus I think throwing ValidationException is fine, and it aligns better with other parts of Flink SQL.

Though it seems a bit unnecessary given the above use case explained, I also don't have strong opinions of making ModuleNotExistException/ModuleAlreadyExistException RuntimeException or extend ValidationException.

**Comment by xuefuz** [comment]
To my understanding, loading/unloading modules is exposed in TableEnvironment, so it's possible that user programmatically call those methods. The original code did declare throwing exceptions.

As majority of APIs in TableEnv doesn't throw any exception, I'm okay not to declare any exception and this PR can merge.

**Comment by zjuwangg** [comment]
LGTM. I agree with Xuefu's comments.

**Comment by dawidwys** [comment]
Hi, as I said before I am not entirely against having a custom exception as long as they are `RuntimeExceptions`. There are a few very important things to consider when adding one.

1. We do want to differentiate between user problem (ValidationException) and system problem (TableException). For this to work we should make sure all exceptions that we throw extend from one or the other. IMHO, this is very helpful e.g. in case of SQL client, where we could close the client on `TableException` as this is an unrecoverable problem, whereas on `ValidationException` we could just print a message to the user.
2. If we want to open up the exceptions part we should think through the class hierarchy well. It would probably make sense to have a class in between the `ValidationException` and `ModuleAlreadyExistException` that tells that it comes from the `Module` module. The problem then is how do we combine the `ModuleException` with `TableException` and `ValidationException`, as there might be exceptions in both of those categories. Another option would be to extend the ValidationException to add additional context to it or to other exceptions.
3. It is easier to introduce a new more specific exception in the future than to remove it. If we want to remove some specific exception it requires changes to the client code. This is why I am a bit hesitant towards opening the discussion on exceptions hierarchy, as this is not such an easy thing as I tried to describe in the 2. point.
4. I see no immediate benefit of throwing a `ModuleAlreadyExistException` instead of a `ValidationException` in these methods. It adds a contract that we would have to adhere to in the future, as I described in the 3. point.
5. This last point does not necessarily relates to the changes in this PR, but wanted to mention that anyway. We should be careful to not end up with a control flow based on `Exception`s as this is much harder to program against and is less performant than reacting to the return value. I do fear that having dozens of exceptions encourages it.

Just to sum up. I am ok with having custom **unchecked** exceptions in these methods. I would really appreciate though if the class hierarchy of these is improved.

**Comment by bowenli86** [comment]
@xuefuz @zjuwangg @dawidwys thanks for your review! Merging

**Pull request closed without merging**
