### PR TITLE
[FLINK-7670][doc] fix typo in docs runtime section

### PR DESCRIPTION
**Pull request by keweishang**
The following link to Savepoints page
`[Savepoints](..//setup/savepoints.html)`
change to
`[Savepoints](../setup/savepoints.html)`

Otherwise, the link wouldn't work.

### CODE REVIEW

**Comment by zentol** [comment]
+1

**Comment by tzulitai** [comment]
LGTM, thanks for the fix @keweishang. Merging this to `release-1.3` ..

**Comment by tzulitai** [comment]
I merged. @keweishang could you please close this PR, thanks!

**Comment by keweishang** [comment]
@tzulitai thanks for merging the fix!

**Pull request closed without merging**
