### PR TITLE
[FLINK-5995][checkpoints] fix Get a Exception when creating the ListS…

### PR DESCRIPTION
**Pull request by sunjincheng121**
…tateDescriptor with a TypeInformation

Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [×] General
  - The pull request references the related JIRA issue ("[FLINK-5995] Fix Get a Exception when creating the ListStateDescriptor with a TypeInformation")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [ ] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by StephanEwen** [comment]
Thanks for finding and fixing this, important fix!

It would be great if you could add a test for this, to make sure the bug is not accidentally re-introduced later by someone. You can follow the pattern of this test: `flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/StateDescriptorPassingTest.java`

**Comment by sunjincheng121** [comment]
Hi,@StephanEwen, Thanks a lot for your comment. I seriously think about where to add the test more is reasonable, because the change of this PR is `OperatorStateBackend`, so I added the test case in`java/ src/test/java/org/apache/flink/runtime/state/operatorStateBackendTest.java` Is this make sense for you? feel free to tell me if it is incorrect.
Best,
SunJincheng

**Comment by StephanEwen** [comment]
That sounds reasonable!

**Comment by sunjincheng121** [comment]
@StephanEwen I had update the PR. I appreciated if you can review this PR.
Best,
SunJincheng

**Comment by StephanEwen** [comment]
Looks good. I would actually like to extend the test by one more, just to make sure that the proper `ExecutionConfig` is passed (which is not currently tested - the execution config in the test is null).

A good way to do that would be to create a state of some non-standard type (like `File`) which goes to Kryo and then check that Kryo has the proper registration from the execution config.

**Comment by sunjincheng121** [comment]
@StephanEwen I added a test to make sure the `ExecutionConfig` was passed, but I'm not sure whether I understand you correctly. feel free to tell me If it is not right.
Thanks,
SunJincheng

**Comment by sunjincheng121** [comment]
HI,guys, Welcome anyone to review this PR.
@StephanEwen Can you continue review this PR.
Best，
SunJIncheng

**Comment by StephanEwen** [comment]
Looks good, merging this...

**Pull request closed without merging**
