### PR TITLE
[FLINK-4378]Enable RollingSink to custom HDFS client configuration

### PR DESCRIPTION
**Pull request by wenlong88**
Adding a new interface to rolling sink

### CODE REVIEW

**Comment by wenlong88** [comment]
the change is a little bigger than expected. because {{FileSystem}} will be cached once created ,to make sure the user defined configuration work,   {{fs.%s.impl.disable.cache}} need to be set true and I cache the file system to avoid creating the filesystem duplicated.

**Comment by aljoscha** [comment]
The changes look good! 👍 Thanks for the work. We recently (today) merged an updated version of `RollingSink` called `BucketingSink`. Would you be willing to forward port your changes to that as well. If you don't want to I can also do it.

**Comment by aljoscha** [comment]
@wenlong88 Are there any updates on this?

**Comment by wenlong88** [comment]
sorry,@aljoscha,  I have miss the last message in august, I will update the pr quite soon

**Comment by wenlong88** [comment]
@aljoscha i have rebase the newest master branch, and forward port the changes in rollingsink to bucketsink

**Comment by aljoscha** [comment]
@wenlong88 thanks for the update! What's the reason for setting the `fs.%s.impl.disable.cache` parameter explicitly?

**Comment by wenlong88** [comment]
I have commented above, it is to make sure that the customized configuration work

**Comment by aljoscha** [comment]
Ah I see. I didn't see that before, sorry. I'll merge this once it passes on Travis.

Thanks for your work! 😃

**Comment by wenlong88** [comment]
all of the test in travis have passed. thanks for merging this. ^_^

**Comment by aljoscha** [comment]
I merged it. 👍 Could you please close this PR?

I changed `setHDFSConfig()` to `setFSConfig` to reflect the fact that a `FileSystem` is not necessarily used only for HDFS, I hope that's ok.

**Comment by wenlong88** [comment]
it is ok for me

**Pull request closed without merging**
