### PR TITLE
[FLINK-23551][Connectors/ORC] Bump ORC to 1.7.0

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What is the purpose of the change

This PR aims to update Apache ORC dependency from 1.5.6 to 1.7.0 in order to bring the latest bug fixes and updates.
Apache ORC 1.5.6 is too old and the following versions are available. Apache ORC community highly recommends to use the latest one.
- 1.7.0: https://orc.apache.org/news/2021/09/15/ORC-1.7.0/
- 1.6.11: https://orc.apache.org/news/2021/09/15/ORC-1.6.11/
- 1.5.12: https://orc.apache.org/news/2020/09/30/ORC-1.5.12/

Note that **Apache Spark** uses Apache ORC 1.6.10 as of today.

## Brief change log

- Update orc.version to 1.7.0

## Verifying this change

Since this is a dependency change, this should pass all the existing unit tests via CIs.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): yes
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this please, @wangyang0918 , @twalthr , @rmetzger ?

**Comment by dongjoon-hyun** [comment]
Could you review this please, @gyfora and @mbalassi ?

**Comment by dongjoon-hyun** [comment]
@flinkbot run azure

**Comment by dongjoon-hyun** [comment]
@flinkbot run travis

**Review by dongjoon-hyun — COMMENTED** [review]
Sorry guys. I missed the previous CI failure log. 
I realized that the Flink's cloned `PhysicalWriterImpl` is outdated and misses several APIs.

**Comment by mbalassi** [comment]
Hi @dongjoon-hyun,

Please let us know when you open the updated version. Thanks!

**Comment by dongjoon-hyun** [comment]
Thank you, @mbalassi ! :)

**Pull request closed without merging**
