### PR TITLE
[FLINK-28094][kinesis][glue] Updating AWS SDK versions for Kinesis connectors and Glue Schema Registry formats

### PR DESCRIPTION
**Pull request by dannycranmer**
## What is the purpose of the change

Updating AWS SDK dependencies to latest versions to pull recent bug fixes and add support for new AWS regions.

## Brief change log

Upgrading dependencies:
* AWS SDK v2 from `2.17.52` to `2.17.247`
* AWS SDK v1 from `1.12.7` to `1.12.276`
* Kinesis Consumer Library from `1.14.7` to `1.14.8`

For the following connectors/formats:
* Kinesis Data Streams
* Kinesis Data Firehose
* Glue Schema Registry JSON
* Glue Schema Registry AVRO

## Verifying this change

- Unit tests/e2e tests
- Manual regression
  - `flink-glue-schema-registry-avro-test` :: `mvn clean test -Prun-end-to-end-tests` (providing GSR keys)
  - `flink-glue-schema-registry-json-test` :: `mvn clean test -Prun-end-to-end-tests` (providing GSR keys)
  - `flink-connector-kinesis` :: Verified with local test app (EFO source/Polling source/Sink)

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): yes
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by dannycranmer** [comment]
@flinkbot run azure

**Review by mrapcooper — APPROVED** [review]
Nice to see the upgrade of the AWS SDK. Understood the movement of guava/aws-sdk dependency management to resolve dependancy conflicts as a good move also.

**Comment by dannycranmer** [comment]
@flinkbot run azure

**Review by hlteoh37 — APPROVED** [review]
Looks good. Like the move to BOMs

**Review by z3d1k — APPROVED** [review]
LGTM

**Pull request merged**
