### PR TITLE
[FLINK-11547][flink-connector-kinesis] Fix JsonMappingException in DynamoDBStreamsSchema

### PR DESCRIPTION
**Pull request by tinder-dthomson**
## What is the purpose of the change

This pull request resolves an exception while using the provided `DynamoDBStreamsSchema` class in the Flink Kinesis Connector.

## Brief change log

  - Replace `ObjectMapper` instance with `RecordObjectMapper` in `DynamoDBStreamsSchema`

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`:  no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by tweise** [comment]
@flinkbot approve all

**Comment by tinder-dthomson** [comment]
@tweise looks like CI failed for some transient reason:

```
rm: cannot remove '/home/vsts/work/1/s/flink-end-to-end-tests/test-scripts/temp-test-directory-39845753958/tmp/backup': No such file or directory
The STDIO streams did not close within 10 seconds of the exit event from process '/bin/bash'. This may indicate a child process inherited the STDIO streams and has not yet exited.
##[error]Bash exited with code '2'.
```

How can we trigger a new run?

**Comment by tweise** [comment]
@flinkbot run azure

**Comment by tweise** [comment]
@rmetzger above did not trigger rerun for the failed test. How do I go about it?

**Comment by rmetzger** [comment]
The most reliable way is pushing a new commit (empty commit in this case I guess). I've asked @zentol to look into why the manual trigger didn't work.

**Comment by rmetzger** [comment]
@flinkbot run azure

**Comment by tinder-dthomson** [comment]
@rmetzger there appears to be something broken with the CI. Is there anything we can do to move this forward?

**Comment by tweise** [comment]
@flinkbot run azure

**Comment by tweise** [comment]
The bot command is working now, let's wait for the test result. I see successful CI runs in other PRs.

**Comment by tinder-dthomson** [comment]
@tweise success! What are the next steps?

**Comment by tweise** [comment]
Actually all test runs show a failure when you click through, regardless what is shown in the status here. That's quite confusing. The failures also have nothing to do with the change in this PR.

**Comment by tweise** [comment]
@flinkbot run azure

**Comment by rmetzger** [comment]
We are looking into the CI bot issues. Sorry for the inconveniences

**Comment by rmetzger** [comment]
The problem is probably just a side-effect of a bug in the CI bot (it was triggering the same build multiple times, and we can not distinguish the builds properly from the status GitHub is reporting). We should not have this problem with regular builds.

**Pull request merged**
