### PR TITLE
[FLINK-4322] Unify CheckpointCoordinator and SavepointCoordinator

### PR DESCRIPTION
**Pull request by uce**
The CheckpointCoordinator now also takes over the role of the SavepointCoordinator. Savepoints are just like other checkpoints - they only store the metadata in addition. Restoring from a savepoint means loading it into the CheckpointStore at startup.

This simplifies the code quite a bit. We get rid of the savepoint coordinator and related classes and cumbersome restoring logic in the main code. For the tests, we can replace some integration tests with unit tests.

`PendingSavepoint` instances are finalized to become a `CompletedCheckpoint` like regular `PendingCheckpoint` instances, but in addition store the savepoint meta data and complete a Promise for callbacks. `PendingSavepoints` cannot be subsumed and a `CompletedCheckpoint` from a savepoint does not delete its associated state when being disposed.

@StephanEwen did most of the work and I added and fixed some tests.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Thanks for joining this effort. I'll try to have a look at the tests in the next days.

**Comment by StephanEwen** [comment]
Looked very good. Fixed a minor issue (test log level) and merged this.

**Comment by ramkrish86** [comment]
The unification looks great and now things are simple in terms of restoration. Thanks.

**Comment by ramkrish86** [comment]
Reading the code once again, just few doubts/questions
->If a save point is triggered and that is happening with in the duration of the 'MINIMUM_TIME_BETWEEN_CHECKPOINTS' we still throw back a decline result? Is it not needed that since Save points are externally triggered we need to isolate that with the internal timing we maintain? 
Correct me if am missing something here. Thanks.

**Comment by StephanEwen** [comment]
Savepoints are excepted form the concurrent checkpoints and time between checkpoints limitation. These checks run only if the triggered checkpoint is not a savepoint (in the triggerCheckpoint(...)) method.

**Comment by ramkrish86** [comment]
Ya. So may be this code
`if (lastTriggeredCheckpoint + minPauseBetweenCheckpoints > timestamp) {`
The if block should also go inside the previous 'if' condition that checks for !savePoint, right?

**Comment by StephanEwen** [comment]
You are right, this was an oversight on my side. This check should also be within the `if (!isSavepoint())` block. Thanks for reviewing this.

Do you want to create a fix for that?

**Comment by ramkrish86** [comment]
Yes. I can do it. Thanks. 
Is it better to raise a JIRA for that for accounting or just raise a PR with the same issue ID?

**Comment by StephanEwen** [comment]
JIRA issue never hurts. But in this case, it could piggy-bag on the previous issue. Your choice ;-)

**Pull request closed without merging**
