### PR TITLE
[hotfix][docs] Remove redundant "." from sample code

### PR DESCRIPTION
**Pull request by nyingping**
## What is the purpose of the change

Remove redundant "." from sample code

## Brief change log

Remove redundant "." from sample code

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)no
  - The serializers: (yes / no / don't know)no 
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)no 
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)no 
  - The S3 file system connector: (yes / no / don't know)no

## Documentation

  - Does this pull request introduce a new feature? (yes / no)no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)not applicable

### CODE REVIEW

**Review by Myasuka — COMMENTED** [review]
Thanks for creating this PR!
Could you check whether this fix involves all redundant `.` in the docs?
And could you also squash all commits into one?

**Comment by nyingping** [comment]
Thank you for review. 
Yes, I have searched  intellij idea to make sure I fix all the characters of   redundant `.`.

**Comment by Myasuka** [comment]
@nyingping could you please squash all 8 commits into one in this PR?

**Comment by nyingping** [comment]
@Myasuka updated. sorry for delay.

**Review by Myasuka — COMMENTED** [review]
@nyingping I think you should rename the commit message as `[hotfix][docs] Remove redundant "." from sample code`

**Comment by nyingping** [comment]
@Myasuka Updated.

**Comment by Myasuka** [comment]
@flinkbot run azure

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Review by MartijnVisser — APPROVED** [review]
LGTM

**Comment by nyingping** [comment]
@Myasuka @MartijnVisser Thanks a lot!

**Pull request merged**
