### PR TITLE
FLINK-2949 [WIP]: Add method 'writeSequencefile' to DataSet

### PR DESCRIPTION
**Pull request by smarthi**

### CODE REVIEW

**Comment by rmetzger** [comment]
Thank you for the contribution. To me it seems that the pull request so far consists only of unrelated changes.
Did you make any progress on resolving the issue?

I'm also not sure whether there is consensus in the community to add such a method to the DataSet. 
Adding such method to one of the most visible classes in Flink is usually a controversial thing ;)

**Comment by smarthi** [comment]
@rmetzger This fell off my radar briefly as other things took priority. Let me know what you think about adding this to DataSet API, this follows from a similar change that was put in for reading HAdoopFiles from ExecutionEnvironment.

Ofcourse, there are work arounds without having to mess with the DataSet APIs, so if you feel that this change is not acceptable to the community, I can withdraw this PR.

**Comment by StephanEwen** [comment]
I would like to not add this to DataSet. Nick said it well in the discussion of another issue: This gives nice syntactic sugar, looks super in examples and on slides. But concerning practical day to day use, the benefit is limited (at least over an external utility method), and it causes API bloat with leads to maintenance issues.

The other changes in this pull request look good, so if you could factor them out, would make sense to merge them.

**Comment by smarthi** [comment]
I was gonna close this Jira and withdraw the PR. Closing now..

**Pull request closed without merging**
