### PR TITLE
[FLINK-3999]: Rename the `running` flag in the drivers to `canceled`

### PR DESCRIPTION
**Pull request by nssalian**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-3999] Rename the `running` flag in the drivers to `canceled`")
  - Added the cancelled flag instead of the running flag to replace the functionality since it was not truly "running".
 - Modified the operators to have the cancelled instead of running even in tests

- [ ] Documentation
  - Modified the Example for the Loading Data where the import statement needed to be changed.

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed
  - Ran a Travis build and local mvn tests as well.

@ggevay  if you could help review. Thank you.

### CODE REVIEW

**Comment by ggevay** [comment]
Could you please explain why are the first and last commit (65b3ff78f100ed1b13ec2fcc727f4869823b5918 and ba4f429043f3985db5ab37a3902a6fee15a7440e) necessary? Are they related to FLINK-3999?

**Comment by nssalian** [comment]
@ggevay  they are not related.. I think it caught from me old branch on to this one. The 3 in the middle 	2ef4401, 	46d91b0, 	1433a5d are relevant here. Apologies for the mix up.

**Comment by StephanEwen** [comment]
I am a bit skeptical about these types of changes.

Maintaining stability of Flink is crucially important now. With changes like these we risk introducing subtle bugs without fixing a bug or improving a functionality or anything. It just changes a naming preference.

The kind of bugs one can introduce with changes like that are very subtle (we have seen that in cases where the cancelling logic was fragile depending on how the flag was exactly set) and hard to catch all in reviews. Not everything is fully covered by bullet proof tested in practice.

I would actually suggest to rather contribute on issues where there is a clearer benefit.

**Comment by nssalian** [comment]
@StephanEwen ,thanks for that, that makes sense. But it is hard for someone new to understand the problem you mention. If someone familiar with the product, could review new JIRAs for clear benefit / validity, that would encourage folks jumping on the tasks to know it better. I realize it may not be feasible but it saves time too to let them know in advance. I can certainly close the PR and make it Not a Problem. But if there is a better way to have this clearer , I would appreciate it before the effort is put in.

**Comment by ggevay** [comment]
OK, I see your point now @StephanEwen.
@nssalian, I'm sorry for opening the jira; I didn't think it through from this perspective at the time.

**Comment by uce** [comment]
@nssalian Your suggestion regarding JIRAs makes very much sense. Let's try to ensure that this does not happen again. But no single person can do this alone... we have to do it as a community.

**Comment by nssalian** [comment]
Thanks @uce, agreed, it would be a community effort indeed. I will try to help as much as possible.
 @ggevay, it's alright. I'll close the PR.

**Comment by StephanEwen** [comment]
@nssalian Thanks for understanding.

We as a community together have actually gone into that mode (more conservative and stability focused) not too long ago. So it is still a bit of a learning process for everyone here (committers and contributors).

**Pull request closed without merging**
