### PR TITLE
[hotfix][doc][sql-client] Modify typo in sql client doc

### PR DESCRIPTION
**Pull request by Clarkkkkk**
This closes #6635

### CODE REVIEW

**Comment by fhueske** [comment]
Hi @Clarkkkkk, thanks for your PR.

Did you observe that a configuration without quotes does not work?
I have an example setup with a Kafka source (and sink) that work without the quotes.

If it works, we should not change the docs, IMO.

Best, Fabian

**Comment by Clarkkkkk** [comment]
Hi @fhueske , the SQL client dosen't work without the quotes, and it will throw a NoMatchingTableFactoryException which is not a good error message as I thought.

**Comment by fhueske** [comment]
That's weird. I have a working configuration without quotes.

@twalthr, can you have a look at this fix?

**Comment by twalthr** [comment]
No this change is not necessary. `0.11` is correctly converted into a string "0.11". Only trailing zeros cause issues such as `0.10` which is translated into "0.1". @Clarkkkkk can you validate this change again?

**Comment by fhueske** [comment]
If it is a tailing `0` issue, we should add the quotes, IMO.

**Comment by Clarkkkkk** [comment]
@fhueske @twalthr Yep, I'm using kafka 0.10.

**Comment by GJL** [comment]
Can we close this PR if the change is not needed?

**Comment by fhueske** [comment]
I think we should merge it. 
The version should be parsed as a String and not as a number.

**Comment by twalthr** [comment]
I will take care of merging this...

**Pull request closed without merging**
