### PR TITLE
[FLINK-29992][hive] fix lookup join fail with Hive table as lookup table source

### PR DESCRIPTION
**Pull request by luoyuxia**
## What is the purpose of the change
To fix the lookup join fail with Hive table as lookup table source

## Brief change log
Implement `copy` method in `HiveLookupTableSource`.

## Verifying this change
Added test `HiveLookupJoinITCase`

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by luoyuxia** [comment]
@flinkbot run azure

**Review by leonardBang — APPROVED** [review]
Thanks @luoyuxia for the contribution, LGTM

**Comment by leonardBang** [comment]
@luoyuxia Could you also open PRs for release-1.14  ,  release-1.14   and release-1.16 ?

**Comment by luoyuxia** [comment]
@leonardBang 
1.16: https://github.com/apache/flink/pull/21310
1.15: https://github.com/apache/flink/pull/21309
1.14: https://github.com/apache/flink/pull/21311

**Pull request merged**
