### PR TITLE
[FLINK-11747] [ Connectors / ElasticSearch] Expose RestHighLevelClient to allow for custom sniffing

### PR DESCRIPTION
**Pull request by Salatich**
## What is the purpose of the change
Expose Client in Elastic sinks for API users. It needs, for instance, for sniffing mechanism.

## Brief change log

* Adding public getter in base elastic sink class for getting access to RestClient. 

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes)
  - The serializers: (no )
  - The runtime per-record code paths (performance sensitive): (no )
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by tzulitai** [comment]
@flinkbot disapprove architecture

This would not work.
The client is only created in the `open` method, and is therefore always `null` pre-flight on the client side. That's why the connector allows the `RestClient` to be configured via a `RestClientFactory`.

@Salatich can you briefly describe how the client is used to allow for custom sniffing?

**Comment by tzulitai** [comment]
@flinkbot disapprove architecture

**Comment by desiam** [comment]
@tzulitai From https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/_usage.html, you generally need a reference to the low-level rest client when initializing the sniffer, which can be obtained from the high level rest client.

Some additional context in [FLINK-11747](https://issues.apache.org/jira/browse/FLINK-11747)

**Comment by desiam** [comment]
@tzulitai If it's difficult to expose the RestHighLevelClient, we may look into creating our own implementation of the Elasticsearch 6 ElasticsearchSink.

**Comment by zentol** [comment]
Further design discussions should be moved to the JIRA.

**Pull request closed without merging**
