### PR TITLE
[FLINK-2428] Clean up unused properties in StreamConfig

### PR DESCRIPTION
**Pull request by hczerpak**
- Removed outEdges property as it looks totally unused
- Corrected spelling in 2 properties

Apologies for not squashed commits. If somebody could tell me how to do it I will! Tried few times and only making more meaningless commits.

### CODE REVIEW

**Comment by rmetzger** [comment]
To squash commits, you have to call "git rebase -i HEAD~10" (its called interactive rebase). Then, put "fixup" or "squash" instead of "pick" to the commits you want to squash.

Your branch contains a lot of merge commits. I would first rebase to origin (assuming its the flink repo) and then do the interactive rebase.

**Comment by StephanEwen** [comment]
I think this breaks the code. The `setOutEdges()` method is actually used (even though the call site can probably be removes as well, given that they are not read any more).

This also makes one java file executable, which is probably an accident.

**Comment by fhueske** [comment]
Hi @hczerpak do you plan to update this PR? Otherwise, I'd like to close it. Thanks

**Comment by hczerpak** [comment]
Close please, thanks

**Comment by fhueske** [comment]
Thank you!

**Pull request closed without merging**
