### PR TITLE
[FLINK-21139][Build] Fix unstable ThresholdMeterTest

### PR DESCRIPTION
**Pull request by HuangZhenQiu**
## What is the purpose of the change
Fix the unstable ThresholdMeterTest with SystemClock

## Brief change log

  - Move ThresholdMeter from flink-metrics to flink-runtime module
  - Use Clock internally in ThresholdMeter
  - Update ThresholdMeterTest with ManualClock to resolve the issue of clock jump in test cases.

## Verifying this change
This change added tests and can be verified as follows:
  - It can be verified in the new ThresholdMeterTest.
 
## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Review by xintongsong — APPROVED** [review]
Thanks @HuangZhenQiu. The fix looks good to me.
I did a bit clean-ups, please take a look.

**Comment by HuangZhenQiu** [comment]
@xintongsong 
Thanks. Your changes are reasonable and needed.

**Review by zentol — COMMENTED** [review]
Could someone expand on why we need the `ThresholdMeter` at all?
Isn't the `MeterView` already providing everything we need?

**Comment by xintongsong** [comment]
@zentol,
`ThresholdMeter` is introduced for tracing the rate of starting new worker failures, in FLINK-10868.
It's different from `MeterView` in the following ways:
* It needs to be updated on every event. (The events does not occur on a per-record bias.)
* It provides a `checkAgainstThreshold` method.

Thanks for the reminder on the commit tag. Merging this.

**Comment by xintongsong** [comment]
Closed via b9e576fb845b817d804da3d68471ff8a4723dcf3

**Pull request closed without merging**
