### PR TITLE
[FLINK-36508][table-common] Remove all deprecated methods in SymbolType

### PR DESCRIPTION
**Pull request by lajith2006**
## What is the purpose of the change

[[FLINK-36476](https://issues.apache.org/jira/browse/FLINK-36476)](https://issues.apache.org/jira/browse/FLINK-36476) Remove all deprecated methods under public APIs in table modules

subtask:

 [FLINK-36508](https://issues.apache.org/jira/browse/FLINK-36508) Remove all deprecated methods in `SymbolType `

## Brief change log

Remove deprecated methods

## Verifying this change

This change is already covered by existing tests

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`:  no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature?  no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Review by davidradl — APPROVED** [review]

**Review by davidradl — APPROVED** [review]

**Review by xuyangzhong — APPROVED** [review]
LGTM. Could you please update your title to `[FLINK-36508][table-common] Remove all deprecated methods in SymbolType`? BTW, there are some conflicts with the master branch.

**Comment by lajith2006** [comment]
@flinkbot run azure

**Comment by lajith2006** [comment]
> LGTM. Could you please update your title to `[FLINK-36508][table-common] Remove all deprecated methods in SymbolType`? BTW, there are some conflicts with the master branch.

Hi @xuyangzhong Updated Title and resolved conflicts.

**Comment by davidradl** [comment]
@lajith2006 could you squash the commits please.

**Review by snuyanzin — APPROVED** [review]

**Pull request closed without merging**
