### PR TITLE
[FLINK-1927] [py] Operator distribution rework

### PR DESCRIPTION
**Pull request by zentol**
Python operators are no longer serialized and instead rebuilt on each node. This also means that the dill library is no longer necessary.

### CODE REVIEW

**Comment by mxm** [comment]
Wow! Great to see that we get rid of the only python-side dependency. It was a bit unclear under which terms we could ship the library anyways. Have you done any measurements how this effects the performance? IMO the performance impact should be near zero, perhaps even faster now.

**Comment by zentol** [comment]
I didn't check performance, it shouldn't have any noticeable effect on it.

**Comment by aljoscha** [comment]
But doesn't this mean that the lambdas now must be stateless, i.e. if a user refers to some variable outside the lambda this will not be serialised with the closure anymore (because there is no serialization of the closure anymore).

**Comment by zentol** [comment]
@aljoscha that variable must be declared somewhere within the plan file. during the plan rebuild this would be executed as well, so i don't think this is a problem. in fact, i think this wouldn't work *before* this PR.

**Comment by zentol** [comment]
oh snap i just noticed a big flaw... well let's put this PR on hold for a bit.

I'm simply re executing the plan file on each node, but forgot to deal with arguments that were passed to the file -.-

**Comment by aljoscha** [comment]
Ok, keep at it. :smile_cat:

**Comment by zentol** [comment]
Implementing this in a clean way has become trickier that i initially expected, as such I'll postpone it and close this PR for now.

**Pull request closed without merging**
