### PR TITLE
[FLINK-25223][connectors/elasticsearch] Disable Elasticsearch 7 Testcontainer tests due to frequent CI failures

### PR DESCRIPTION
**Pull request by gaoyunhaii**
This PR picks https://github.com/apache/flink/pull/18062 to 1.14

### CODE REVIEW

**Comment by zentol** [comment]
What about https://github.com/apache/flink/blob/3db9717e8cc373c68ec93b0b78aae3191469984d/flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkITCase.java?

Can you do a simple text search for `ElasticsearchContainer` and disable all referencing tests?

**Comment by gaoyunhaii** [comment]
Hi @zentol very thanks for the review! I initially think the class content is changed... Do we also need to disable the cases using `ElasticsearchContainer` in `elasticsearch6`~?

**Comment by MartijnVisser** [comment]
Elasticsearch 7 doesn't exist in Flink 1.14, it's only going to be released in 1.15

**Review by MartijnVisser — CHANGES_REQUESTED** [review]
As mentioned, Elasticsearch 7 doesn't exist in 1.14, it's only been added for 1.15. See https://issues.apache.org/jira/browse/FLINK-24323

**Comment by zentol** [comment]
@MartijnVisser git begs to differ: https://github.com/apache/flink/tree/release-1.14/flink-connectors/flink-connector-elasticsearch7

**Comment by zentol** [comment]
That ticket you linked was only about _porting the existing sink_ to the new API.

**Comment by zentol** [comment]
> Then do we also need to disable the cases using ElasticsearchContainer in elasticsearch6~?

Disable _every_ test that uses the ElasticsearchContainer.

**Comment by MartijnVisser** [comment]
> @MartijnVisser git begs to differ: https://github.com/apache/flink/tree/release-1.14/flink-connectors/flink-connector-elasticsearch7 https://github.com/apache/flink/tree/release-1.13/flink-connectors/flink-connector-elasticsearch7

Ugh, you're right (as always). Let's just say I need a holiday. Apologies.

**Comment by zentol** [comment]
Closing the PR as older branches should not be affected by the memory issue.

**Pull request closed without merging**
