### PR TITLE
[FLINK-3578] Support RichFunctions for Scala Window Function and AllWindowFunction

### PR DESCRIPTION
**Pull request by StephanEwen**
This adds support RichFunctions for Scala Window Function and AllWindowFunction.
RichFunction method calls (`open()`, `close()`, `RuntimeContext`) are properly forwarded.

This also consolidates the various wrapper classes for fold() and reduce() functions.

### CODE REVIEW

**Comment by aljoscha** [comment]
Looks very good! :+1:

**Comment by aljoscha** [comment]
One thing is that we should maybe have tests/ITCases that verify that rich functions actually work.

**Comment by StephanEwen** [comment]
Yes, have started in tests already...

**Comment by StephanEwen** [comment]
Tests have been added for RichWindowFunctions, plus for combinations with Reduce and Fold for pre-aggregation.

Merging this...

**Pull request closed without merging**
