### PR TITLE
[FLINK-6587] [table] Simplification and bug fixing of the ExpressionParser

### PR DESCRIPTION
**Pull request by twalthr**
This PR fixes several issues related to the ExpressionParser and the resolution of expression produced by it. Only special cases are handled by the parser, other expressions will resolved by the function catalog. I also updated the data types such that they are in sync with `org.apache.flink.table.api.Types`.

### CODE REVIEW

**Comment by shaoxuan-wang** [comment]
@twalthr, it seems we have reserved the keyword with the case insensitive. For instance, we cannot use "Sum" and "SUM", as "sum" is reserved. Did we intent to filter the keyword like this?

**Comment by twalthr** [comment]
@shaoxuan-wang the function catalog is case insensitive anyway. With this PR we have almost no keywords anymore. So a "sum" could be overwritten by "SUM".

**Comment by fhueske** [comment]
The PR looks good to me. +1 from my side.

**Comment by twalthr** [comment]
Thanks @fhueske. I will merge this and update the documentation.

**Pull request closed without merging**
