### PR TITLE
Some updates for programming_guide.md

### PR DESCRIPTION
**Pull request by chenliang613**
Some updates for the section "Program Skeleton" of programming_guide.md

### CODE REVIEW

**Comment by StephanEwen** [comment]
Most of this is good, but in parts, it confuses the `DataSet` and `DataStream` API. The `DataSet` API has no functionality to write to sockets.

**Comment by chenliang613** [comment]
ok, update the sockets part.

**Comment by StephanEwen** [comment]
This looks good, will merge this!

**Comment by StephanEwen** [comment]
I merged this in 3c1b5f0e7f28d18868e941712d2ca42b140ef3a0 , but forgot the closing message.

Can you manually close this pull request?

Thank you!

**Comment by chenliang613** [comment]
ok, done!

**Pull request closed without merging**
