### PR TITLE
[FLINK-8475][config][docs] Integrate akka options

### PR DESCRIPTION
**Pull request by zentol**
## What is the purpose of the change

This PR integrates the Akka `ConfigOptions` into the configuration docs generator.

## Brief change log

* Add missing descriptions to config options (derived from existing description/javadocs)
* integrate akka configuration table into `config.md`

### CODE REVIEW

**Comment by aljoscha** [comment]
The changes look good but I noticed some weirdness:
 - `akka.client.timeout` doesn't have a description now but it did have one earlier
 - `akka.startup-timeout` has `(none)` as default while it had `akka.ask.timeout` previously

**Comment by zentol** [comment]
@aljoscha Fixed.

**Comment by zentol** [comment]
akka.startup-timeout has no default value because that's how the ConfigOption is actually defined; in other words ATM we can't guarantee anything about the default.

**Comment by zentol** [comment]
Note that the existing docs were wrong regardless, see AkkaUtils:
```
    val startupTimeout = configuration.getString(
      AkkaOptions.STARTUP_TIMEOUT,
      (akkaAskTimeout * 10).toString)
```

**Comment by aljoscha** [comment]
More reason for the more advanced configuration stuff where you can actually specify such things directly in the configuration code. 😅 

Changes look good now, though. 👍

**Comment by zentol** [comment]
merging.

**Pull request closed without merging**
