### PR TITLE
[FLINK-5382][web-frontend] Fix problems with downloading TM logs on Yarn

### PR DESCRIPTION
**Pull request by sachingoel0101**
Handle transition URL relative to current page.

### CODE REVIEW

**Comment by rmetzger** [comment]
Thanks a lot for providing a fix for the issue.
I'll test it soon.

**Comment by sachingoel0101** [comment]
Unrelated failures on travis.

**Comment by rmetzger** [comment]
I tested the changes and they worked on my YARN cluster.
Thank you for quickly fixing the issue.
I'll merge the fix to master and the release-1.2 branch.

**Comment by rmetzger** [comment]
I forgot to close the PR while merging. Could you manually close it?

Thanks a lot.

**Pull request closed without merging**
