### PR TITLE
[DRAFT][FLINK-36336] Remove deprecated dataset API dependency exclude table module

### PR DESCRIPTION
**Pull request by codenohup**
## What is the purpose of the change

Remove deprecated dataset API dependency exclude table module

## Brief change log

- Remove deprecated dataset API dependency exclude table module

## Verifying this change

This change is a code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by codenohup** [comment]
@flinkbot run azure

**Comment by codenohup** [comment]
@flinkbot run azure

**Comment by codenohup** [comment]
@flinkbot run azure

**Comment by codenohup** [comment]
@flinkbot run azure

**Comment by codenohup** [comment]
@flinkbot run azure

**Comment by codenohup** [comment]
@flinkbot run azure

**Comment by reswqa** [comment]
@flinkbot run azure

**Comment by codenohup** [comment]
@flinkbot run azure

**Comment by codenohup** [comment]
@flinkbot run azure

**Pull request closed without merging**
