### PR TITLE
[FLINK-22042][flink-core] Fix reading bigint(20) UNSIGNED type field cannot be cast

### PR DESCRIPTION
**Pull request by wangxiaojing**
## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by wuchong** [comment]
BIGINT UNSIGNED must be mapped to DECIMAL(20, 0).
See https://ci.apache.org/projects/flink/flink-docs-master/docs/connectors/table/jdbc/

**Comment by wangxiaojing** [comment]
in flink sql ddl is 
````
create table testOne(
 id DECIMAL(20,0)
 )WITH (
  'connector.type' = 'jdbc',
   'connector.url' = 'jdbc:mysql://localhost:3306/flink_db?characterEncoding=UTF-8&useSSL=false',
   'connector.table' = 'testlxone',
    'connector.username' = 'root',
     'connector.password' = '123456', 
     'connector.write.flush.max-rows' = '1' 
)
````
Bigint that has been mapped to decimal (20,0) is unsigned ，but error，
 java.math.BigInteger cannot be cast to java.math.BigDecimal
	at org.apache.flink.api.common.typeutils.base.BigDecSerializer.copy(BigDecSerializer.java:33)

**Comment by CecilHarvey** [comment]
same problem here - already using decimal (20,0) and still not working.
will try this patch

**Comment by CecilHarvey** [comment]
I adapted  this patch manually to flink 1.12.4 which I'm using and it fixes the issue.

**Pull request closed without merging**
