### PR TITLE
[FLINK-5360] Fix argument names in WindowedStream

### PR DESCRIPTION
**Pull request by mushketyk**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by xhumanoid** [comment]
After commit we have inconsistency between javadoc comment and arguments.
for both
_public SingleOutputStreamOperator<T> maxBy(int positionToMaxBy)_
_public SingleOutputStreamOperator<T> maxBy(String field)_

" the data stream by the **given position**. If more elements have the same "

**Comment by mushketyk** [comment]
Hi @xhumanoid 

I've updated my PR according to your review.

**Comment by xhumanoid** [comment]
The same javadoc issue apply for minBy ;)
I pointed maxBy only as example

**Comment by mushketyk** [comment]
Hi @xhumanoid,

Sorry, I didn't notice that the same applies to `minBy` :)
I've updated the code according to your review.
Could you please review it again?

**Comment by xhumanoid** [comment]
@aljoscha could you check and merge commit?

**Comment by aljoscha** [comment]
I'm running a last check and then I'm merging. Thanks for reviewing @xhumanoid! And thanks for fixing it @mushketyk. 👍

**Comment by aljoscha** [comment]
Merged. Could you please close this PR and the Jira issue?

**Comment by mushketyk** [comment]
Thank you @aljoscha, @xhumanoid 

Closing the issue.

**Pull request closed without merging**
