### PR TITLE
[FLINK-22346][sql-client] Remove sql-client-defaults.yaml

### PR DESCRIPTION
**Pull request by fsk119**
## What is the purpose of the change

*Remove sql-client-defaults.yaml*

### CODE REVIEW

**Comment by fsk119** [comment]
@flinkbot run azure

**Comment by fsk119** [comment]
The failed reason is 

```
Apr 19 15:44:35   Warning  Failed       16s (x3 over 59s)  kubelet            Failed to pull image "test_kubernetes_pyflink_application": rpc error: code = Unknown desc = Error response from daemon: pull access denied for test_kubernetes_pyflink_application, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

trigger test again...

**Comment by wuchong** [comment]
The build is failed 

```
Apr 20 06:11:54 Traceback (most recent call last):
Apr 20 06:11:54   File "setup.py", line 225, in <module>
Apr 20 06:11:54     copy_files(conf_paths, CONF_TEMP_PATH)
Apr 20 06:11:54   File "setup.py", line 52, in copy_files
Apr 20 06:11:54     dst_path = copy(src_path, os.path.join(output_directory, os.path.basename(src_path)))
Apr 20 06:11:54   File "/__w/3/s/flink-python/dev/.conda/lib/python3.7/shutil.py", line 245, in copy
Apr 20 06:11:54     copyfile(src, dst, follow_symlinks=follow_symlinks)
Apr 20 06:11:54   File "/__w/3/s/flink-python/dev/.conda/lib/python3.7/shutil.py", line 120, in copyfile
Apr 20 06:11:54     with open(src, 'rb') as fsrc:
Apr 20 06:11:54 FileNotFoundError: [Errno 2] No such file or directory: '/__w/3/s/flink-dist/../flink-table/flink-sql-client/conf/'
```

Maybe we should remove "copy SQL client configuration files" entry in dist assemblies.

**Review by wuchong — APPROVED** [review]
LGTM.

**Pull request merged**
