### PR TITLE
[FLINK-23562][CI] Update CI JDK to 1.8.0_292

### PR DESCRIPTION
**Pull request by rmetzger**
```
≻ docker run --rm rmetzger/flink-ci:ubuntu-amd64-02878c6 java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

### CODE REVIEW

**Review by zentol — APPROVED** [review]

**Comment by rmetzger** [comment]
Reported Kafka failure in https://issues.apache.org/jira/browse/FLINK-23391

**Comment by zentol** [comment]
Let's run CI again, bit worried about 2 different connectors failing :/

**Comment by rmetzger** [comment]
Both failures have Jira tickets.
This is the other one: https://issues.apache.org/jira/browse/FLINK-22889

On my personal CI, "only" python failed: https://dev.azure.com/rmetzger/Flink/_build/results?buildId=9160&view=results (looks similar to https://issues.apache.org/jira/browse/FLINK-21004)

**Review by zentol — APPROVED** [review]
+1

**Comment by rmetzger** [comment]
Thanks for the review! Merging ...

**Pull request merged**
