### PR TITLE
[FLINK-25065][docs] Update  document for jdbc connector

### PR DESCRIPTION
**Pull request by gaurav726**
## What is the purpose of the change

The pr updates documentation for `lookup.cache.caching-missing-key` config in jdbc connector 

## Brief change log

  - *jdbc.md*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (docs)

### CODE REVIEW

**Comment by wuchong** [comment]
@gaurav726 , could you update the content for Chinese documentation as well? The file is located in `docs/content.zh/docs/connectors/table/jdbc.md`.

**Comment by gaurav726** [comment]
@wuchong  done, please review

**Comment by gaurav726** [comment]
@wuchong  pipeline got succeed

**Review by wuchong — APPROVED** [review]
LGTM.

**Pull request merged**
