### PR TITLE
[FLINK-4366] Enforce parallelism=1 For AllWindowedStream

### PR DESCRIPTION
**Pull request by wuchong**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

This PR avoid users try to set a parallelism on an all-windowed stream. 

I add an `isAllWindow` field to mark a transformation is  all-windowed. I'm appreciate if there is better solutions.

### CODE REVIEW

**Comment by aljoscha** [comment]
Hi,
thanks for tackling this. I think the way to go about this is by subclassing `SingleOutputStreamOperator` and overriding `setParallelism` there.

**Comment by StephanEwen** [comment]
I agree with Aljoscha, there may be more operators that need to constrain the parallelism. So a more generic solution would be good.

**Comment by wuchong** [comment]
Thanks for advice. Do you have any ideas about the subclass's naming.

**Comment by aljoscha** [comment]
Something like `NonParallelSingleOutputStreamOperator` but that's quite a mouthful. (`SingleOutputStreamOperator` is already too long for my taste ...). Or maybe `NonParallelStreamOperator`.

Maybe we could have it like you initially proposed but not named `allWindow` and in such a way that you cannot switch it back. For example: `SingleOutputStreamOperator.forceNonParallel()` that would set an internal flag that can never be unset from the outside again.

**Comment by aljoscha** [comment]
IMHO this looks good to merge now. 👍 

@StephanEwen what do you think?

**Comment by StephanEwen** [comment]
Yes, this is good, thanks!

+1 to merge this

**Comment by StephanEwen** [comment]
Merging this...

**Comment by StephanEwen** [comment]
Have to rerun tests on this one. The Scala API completeness check failed, so I had to adjust it.
Will merge pending successful tests...

**Pull request closed without merging**
