### PR TITLE
[FLINK-16096][docs-zh] Translate dev/table/catalog.zh.md into Chinese

### PR DESCRIPTION
**Pull request by zhule0601**
## What is the purpose of the change

This pull request translates the overview part of the file system document into Chinese.

## Brief change log

  - Translate docs/dev/table/catalogs.zh.md into Chinese

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`:  no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by wuchong** [comment]
Could you help to review this? @lirui-apache

**Comment by lirui-apache** [comment]
@zhule0601 Thanks for working on this! I went through the PR and left some comments.

**Comment by zhule0601** [comment]
@lirui-apache Thank you for your review！I made some changes based on your suggestions.It would be great if you could help review again.

**Comment by lirui-apache** [comment]
@zhule0601 Thanks for updating. I think we can just use the English word for `Catalog`, no need to translate it to `目录`。Except for that, the PR LGTM.

**Comment by zhule0601** [comment]
@lirui-apache Hi lirui, I think your suggestion about the word `Catalog`  is correct and I have pushed the code to the repository.

**Pull request closed without merging**
