### PR TITLE
[FLINK-5909] [gelly] Interface for GraphAlgorithm results

### PR DESCRIPTION
**Pull request by greghogan**
Create AlgorithmResult and AnalyticResult interfaces for library algorithms to implement. This flattens algorithm results to a single tuple.

Also create interfaces for UnaryResult, BinaryResult, and TertiaryResult implementing methods to access the 0th, 1st, and 2nd vertices.

### CODE REVIEW

**Comment by vasia** [comment]
Hi @greghogan, thank you for the PR.

I didn't spot anything that needs fixing, but I'm wondering what's the motivation to add these interfaces. I see how `toVerboseString()` is useful, but not really why `AnalyticResult` is needed. Also, why introduce  `UnaryResult`, `BinaryResult`, and `TertiaryResult` instead of simply using tuple types?

I also see that this PR contains no changes to the docs and that the current 1.3-SNAPSHOT docs already reflect the changes of this PR. What am I missing here?

**Comment by greghogan** [comment]
Thanks for the review @vasia. The Unary/Binary/TertiaryResult interfaces will allow follow-on algorithms to work with POJOs or non-conforming Tuples (where we don't assume source and target vertices are fields 0 and 1). A common AnalyticResult interface is helpful with drivers that store both directed and undirected results.

The improvements to the library methods docs do reflect an expectation of this PR.

**Comment by vasia** [comment]
Thanks for the clarification @greghogan. +1 from me.

**Comment by vasia** [comment]
Does `AnalyticResult` also need a method like `toVerboseString()`? Could we replace both with a e.g. `Result` type?

**Comment by greghogan** [comment]
@vasia, I created `PrintableResult` with a `toPrintableString` method and is now used for both algorithms and analytics.

**Comment by vasia** [comment]
Thanks @greghogan. Looks good!

**Pull request closed without merging**
