### PR TITLE
[FLINK-2653] Enable object reuse in MergeIterator

### PR DESCRIPTION
**Pull request by greghogan**

### CODE REVIEW

**Comment by StephanEwen** [comment]
Thank, Greg, for this contribution, this is a good idea.

I think we need to extend it a bit. We observed that the object reuse mode does not work with all types, especially certain user-defined types that are serialized with Kryo. This is due to problems with empty instantiations and object-to-object copies. For that reason, we made the non-reusing mode the default, and the reusing mode optional.

All parts were one could not configure reuse/non-reuse were realized with non-reuse, to be on the safe side.

To keep this safe, I would like to use by default the non-reusing mode and the reusing mode when object reuse has been activated. For that, the reuse flag would have to be passed to the `UnilateralSortMerger`, and interpreted in the intermediate merge (line 1588ff).

If you could add this, it would be perfect and on the safe side.

**Comment by greghogan** [comment]
Stephan, while looking for the `UnionWithTempOperator` bug elsewhere, I noticed that `AllReduceDriver.run()`, `ReduceDriver.run()`, and `ReduceCombinerDriver.sortAndCombine()` locally create new objects before every call to `MutableObjectIterator.next(T)`. This looks to be double allocating new objects in the case that the `TypeSerializer` does not support object reuse.

Also, `ReduceCombinerDriver.sortAndCombine.run()` is not switching on `objectReuseEnabled`.

**Comment by StephanEwen** [comment]
You are right, in those drivers, it is handled in the wrong way. Probably an artifact from the time before the `MultableObjectIterator` had both variants of the `next()` method. It used to have only the reusing variant.

Clearly, this should be fixed.

Here is the guide that I try to follow when working with the mutable objects:

  - All `MultableObjectIterator`s have two variants of the `next()` method - one for reuse, one without.
  - The variant without reuse it crucial, as not every situation can work with object reuse.
  - The variant with reuse is optional, but should be implemented where possible for performance.
  - The task drivers (AllReduceDriver, ...) or algorithms (sorter / hasher) know whether they want to work with reuse or not, and call the respective method in that case.

**Comment by greghogan** [comment]
@StephanEwen, the requested changes are now in a second commit for this pull request. I'm not seeing any messages through JIRA. The only location I was unable to access the configuration (and therefore had to hard code `false`) was with the `DataSinkProcessor` for Tez.

**Comment by StephanEwen** [comment]
Looks good to me.

The CI report seems to refer to a different commit, though, I assume that is due to rebasing?

**Comment by greghogan** [comment]
I did not rebase.
  https://github.com/greghogan/flink/commits/2653_mergeiterator_object_reuse

Travis CI did build and test for my repo when I pushed the updated branch.
  https://travis-ci.org/greghogan/flink/builds/81660560

**Comment by StephanEwen** [comment]
+1 to merge this

**Comment by StephanEwen** [comment]
Merging this...

**Pull request closed without merging**
