### PR TITLE
[FLINK-36142][table] Remove TestTableSourceWithTime and its subclasses to prepare removing TableEnvironmentInternal#registerTableSourceInternal

### PR DESCRIPTION
**Pull request by xuyangzhong**
## What is the purpose of the change

Remove TestTableSourceWithTime, TestLegacyProjectableTableSource and TestNestedProjectableTableSource prepare removing TableEnvironmentInternal#registerTableSourceInternal.

Note: this work involves removing the existing UT and IT tests for LegacyTableSource and LegacyTableSink(LegacyTableSource and LegacyTableSink will be cleaned in FLINK-36134).

## Brief change log

  - *Remove TestTableSourceWithTime, TestLegacyProjectableTableSource and TestNestedProjectableTableSource*
  - *Update or remove the related tests.*

## Verifying this change

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented?

### CODE REVIEW

**Comment by xuyangzhong** [comment]
The plans related to the deleted UTs are not be deleted temporarily, and will be deleted together when the entire test classes need to be cleared.

**Comment by xuyangzhong** [comment]
@flinkbot run azure

**Comment by lincoln-lil** [comment]
@xuyangzhong When I review these changes, I'm wondering if we could just remove all `LegacyTableSourceTest`s, since eventually we will remove them, would that still require multiple modifications in subtasks before removing it?

**Comment by xuyangzhong** [comment]
> @xuyangzhong When I review these changes, I'm wondering if we could just remove all `LegacyTableSourceTest`s, since eventually we will remove them, would that still require multiple modifications in subtasks before removing it?

Sure. I have updated this pr to remove all `LegacyTableSourceTest` and `LegacyTableSourceITCase`.

**Review by lincoln-lil — APPROVED** [review]
LGTM!

**Pull request merged**
