### PR TITLE
[FLINK-32511][FileSystems] Upgrade GCS connector to 2.2.15

### PR DESCRIPTION
**Pull request by jayadeep-jayaraman**
## What is the purpose of the change

Upgrade GCS connector to 2.2.15.

## Brief change log

Upgrade the GCS Connector bundled in the Flink distro from version 2.2.11 to 2.2.15. The new release contains multiple bug fixes and enhancements discussed in the [Release Notes](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/v2.2.15/gcs/CHANGES.md) . Notable changes include: 

1. Improved traceability 
2. Experimental support for read and write via GRPC

## Verifying this change

This change is already covered by existing tests, such as *(please describe tests)*.

`mvn -Pfast -pl flink-filesystems/flink-gs-fs-hadoop clean test`

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by jayadeep-jayaraman** [comment]
@flinkbot run azure

**Review by MartijnVisser — APPROVED** [review]
@jayadeep-jayaraman Thanks for this. LGTM

**Comment by patricklucas** [comment]
What was the purpose of the changes to [`.idea/vcs.xml`](https://github.com/apache/flink/pull/22930/files#diff-a6dab70bd0e9ffc91d8419ad52225baff3a3e7c9d8e1724f7ed6d96b661d804a) in this change?

**Comment by MartijnVisser** [comment]
> What was the purpose of the changes to [`.idea/vcs.xml`](https://github.com/apache/flink/pull/22930/files#diff-a6dab70bd0e9ffc91d8419ad52225baff3a3e7c9d8e1724f7ed6d96b661d804a) in this change?

It shouldn't have been in there, thanks for notifying. I've reverted that specific change via 7b5fe279cdebaa7b712141da286cde2f864c6bbf

**Pull request merged**
