### PR TITLE
[FLINK-2406] [FLINK-2402] Abstract the BarrierBuffers and add a "at least once" version (BarrierTracker)

### PR DESCRIPTION
**Pull request by StephanEwen**
Currently, the checkpointing mechanism provides "exactly once" guarantees. Part of that is the step that temporarily "aligns" the data streams, performed by the `BarrierBuffer`. This step increases the tuple latency temporarily.

By offering a version that does not provide "exactly-once", but only "at-least-once", we can avoid the latency increase. This is relevant for super-low-latency applications (< 10 ms) that tolerate duplicates.

This pull request does:

  - Add an interface for the functionality of the barrier buffer, to allow adding different implementations
  - Add the `BarrierTracker` which only tracks checkpoint barriers, without aligning the streams.
  - Add broader tests for the BarrierBuffer, including trailing data and barrier races.
  - Checkpoint barriers are handled by the buffer directly, rather than being returned and re-injected.
  - Simplify logic in the BarrierBuffer and fix certain corner cases.
  - Give access to spill directories properly via I/O manager, rather than via GlobalConfiguration singleton.
  - Rename the "BarrierBufferIOTest" to "BarrierBufferMassiveRandomTest"
  - A lot of code style/robustness fixes (proplery define constants, visibility, exception signatures)

@gyfora  and @uce : The reworked variant of the BarrierBuffer eventually returns `null` when all buffers and events have been consumed. The previous impementation repeatedly returned the `EndOfPartitionEvent`. That seemed inconsistent with the implementation of the "vanilla" InputGate, which eventually returns `null` when all partitions have finished.

### CODE REVIEW

**Comment by aljoscha** [comment]
Looks good. But why did you not yet wire the BarrierTracker, i.e. provide a user setting so that it can actually be enabled?

**Comment by uce** [comment]
From Gyulas's comment in #937, there seems to be a deadlock. @gyfora, can you provide more input?

**Comment by gyfora** [comment]
This is the same issue as in Stephan's build: https://travis-ci.org/apache/flink/jobs/72752909

**Comment by rmetzger** [comment]
I tried this pull request on a cluster, because the current code is failing with the following exception when running it with a checkpoint interval of 1 second and a buffer timeout of 0 ms.
```
01:08:41,472 ERROR org.apache.flink.streaming.runtime.tasks.OneInputStreamTask   - Flat Map (114/120) failed
java.lang.RuntimeException: Error in barrier buffer logic
        at org.apache.flink.streaming.runtime.io.BarrierBuffer.releaseBlocks(BarrierBuffer.java:192)
        at org.apache.flink.streaming.runtime.io.BarrierBuffer.processBarrier(BarrierBuffer.java:252)
        at org.apache.flink.streaming.runtime.io.StreamInputProcessor.processInput(StreamInputProcessor.java:163)
        at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask.invoke(OneInputStreamTask.java:70)
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:577)
        at java.lang.Thread.run(Thread.java:745)
01:08:41,472 INFO  org.apache.flink.runtime.taskmanager.Task                     - Flat Map (114/120) switched to FAILED with exception.
java.lang.RuntimeException: Error in barrier buffer logic
        at org.apache.flink.streaming.runtime.io.BarrierBuffer.releaseBlocks(BarrierBuffer.java:192)
        at org.apache.flink.streaming.runtime.io.BarrierBuffer.processBarrier(BarrierBuffer.java:252)
        at org.apache.flink.streaming.runtime.io.StreamInputProcessor.processInput(StreamInputProcessor.java:163)
        at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask.invoke(OneInputStreamTask.java:70)
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:577)
        at java.lang.Thread.run(Thread.java:745)
```

The code from this PR is working, however, I got the following WARN messages, probably because the barriers are triggered too early (in the job lifecycle):
```
08:59:24,775 WARN  org.apache.flink.streaming.runtime.io.BarrierBuffer           - Received checkpoint barrier for checkpoint 4 before completing current checkpoint 3. Skipping current checkpoint.
08:59:24,785 WARN  org.apache.flink.streaming.runtime.io.BarrierBuffer           - Received checkpoint barrier for checkpoint 4 before completing current checkpoint 3. Skipping current checkpoint.
08:59:24,786 WARN  org.apache.flink.streaming.runtime.io.BarrierBuffer           - Received checkpoint barrier for checkpoint 4 before completing current checkpoint 3. Skipping current checkpoint.
08:59:24,787 WARN  org.apache.flink.streaming.runtime.io.BarrierBuffer           - Received checkpoint barrier for checkpoint 4 before completing current checkpoint 3. Skipping current checkpoint.
08:59:25,223 WARN  org.apache.flink.streaming.runtime.io.BarrierBuffer           - Received checkpoint barrier for checkpoint 5 before completing current checkpoint 4. Skipping current checkpoint.
08:59:25,225 WARN  org.apache.flink.streaming.runtime.io.BarrierBuffer           - Received checkpoint barrier for checkpoint 5 before completing current checkpoint 4. Skipping current checkpoint.
08:59:25,226 WARN  org.apache.flink.streaming.runtime.io.BarrierBuffer           - Received checkpoint barrier for checkpoint 5 before completing current checkpoint 4. Skipping current checkpoint.
08:59:25,229 WARN  org.apache.flink.streaming.runtime.io.BarrierBuffer           - Received checkpoint barrier for checkpoint 5 before completing current checkpoint 4. Skipping current checkpoint.
```

**Comment by StephanEwen** [comment]
I think the current code (pre this pull request) does not tolerate missing barriers. Missing barriers can happen at startup time, when one source took much longer to start than the other sources.

**Comment by StephanEwen** [comment]
Actually, the failure is not a deadlock. It just seems that the run is so slow that the test takes more than 5 minutes. The stack trace indicates that various tasks are still running (one is actually just being deployed when the "deadlock" is declared).

**Comment by gyfora** [comment]
Interesting... I had the same issue on my builds when I rebased on this PR.

**Comment by gyfora** [comment]
You can observe it on this build for instance: https://travis-ci.org/gyfora/flink/builds/73018512

**Comment by uce** [comment]
It's the same problem I guess, if you look at this Thread:

```

"Custom Source (6/6)" daemon prio=10 tid=0x00007f96a80c9800 nid=0x112cf runnable [0x00007f9684c36000]
   java.lang.Thread.State: RUNNABLE
	at java.io.ObjectStreamClass.readNonProxy(ObjectStreamClass.java:675)
	at java.io.ObjectInputStream.readClassDescriptor(ObjectInputStream.java:829)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1600)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1516)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1770)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1349)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:369)
	at java.util.ArrayList.readObject(ArrayList.java:696)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1001)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1892)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1797)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1349)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:369)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:302)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:264)
	at org.apache.flink.streaming.api.graph.StreamConfig.getNonChainedOutputs(StreamConfig.java:275)
	at org.apache.flink.streaming.runtime.tasks.OutputHandler.createChainedCollector(OutputHandler.java:147)
	at org.apache.flink.streaming.runtime.tasks.OutputHandler.<init>(OutputHandler.java:104)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.registerInputOutput(StreamTask.java:97)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:518)
	at java.lang.Thread.run(Thread.java:701)
```

It's still being deployed.

**Comment by StephanEwen** [comment]
Any reservations against merging this?

**Comment by gyfora** [comment]
That it causes the issue i wrote :P

**Comment by gyfora** [comment]
But if you think this is some random issue occuring for me, go ahead. It looks good and is a critical fix.

**Comment by StephanEwen** [comment]
It is strange that some tests take forever now. I cannot see why this test causes this. I also cannot reproduce this locally, it only occurs on Travis.

But I debug this further...

**Comment by gyfora** [comment]
Unfortunately I also cannot reproduce it locally.

**Comment by StephanEwen** [comment]
Think I found it. It actually sometimes failed infinitely often on close() calls (due to outdated sanity checks) and recovered every time, so the test took longer than 5 minutes...

**Comment by uce** [comment]
Out of curiosity: why was it failing sometimes on Travis and not locally? And how did you discover this? From the program level logs?

Another thing that came to my mind: in the long run, do we need a more complex way of configuring the retry policy? In my understanding, the number of retries is fixed. I can see an issue for very long run programs, which fail once in a while, but operate normally most of the time -- then at some point they will fail because of the fixed number of retries.

**Comment by StephanEwen** [comment]
It failed when at the end of the program, queued channel data was present at the end of the job. This happens only with slow consumers. Apparently, the local machines are usually fast enough to never leave queue data, and Travis is the slow one again ;-)

**Comment by uce** [comment]
I really love Travis :heart:

**Comment by StephanEwen** [comment]
Manually merged in 8f87b7164b644ea8f1708f7eb76567e58341b224

**Pull request closed without merging**
