### PR TITLE
[FLINK-4063] Add Metrics Support for Triggers

### PR DESCRIPTION
**Pull request by aljoscha**
R: @zentol for review. Is this the right way to do it?

### CODE REVIEW

**Comment by zentol** [comment]
well it would work, but i think we can improve it a little. :)

The AbstractStreamOperator contains a protected MetricGroup field which you can use in the WindowOperator instead of going through the RuntimeContext. You can access it directly or via getMetricGroup().

Also, you create 2 groups with a constant name. This means that all metrics that are registered in a trigger now contain "WindowOperator.Trigger" in their final metric name.

Now the Trigger group is probably _fine_, but is now also mandatory. I would prefer removing it; if users want to group their metrics by Trigger they can easily do so themselves.

The WindowOperator group should be removed. It is inconsistent with other operators and provides no really specific information. It will usually be redundant since the operator name often contains the String "window" somewhere.

**Comment by aljoscha** [comment]
Ok, good to know. I'll change it. 😃

**Comment by aljoscha** [comment]
@zentol updated, this is super minimal now.

**Comment by zentol** [comment]
+1

**Pull request closed without merging**
