### PR TITLE
[FLINK-3550] [FLINK-3552] Rework WindowJoin and SocketWindowWordCount example

### PR DESCRIPTION
**Pull request by StephanEwen**
__Note: This is based on #1744__

This pull request give some of the example a more proper streaming feeling.

## WindowJoin

This changes the example to not work on files or small static collections, but on generated infinite streams with configurable data rate. This lets users get a better feeling of continuous windowed joins.

As part of that change (remove file inputs), this also rewrites the corresponding tests.

## SocketWindowWordCount

The example describes how to open a server socket via *netcat* and connects to that socket.
It applies sliding window word counting to the created stream.

### CODE REVIEW

**Comment by aljoscha** [comment]
Looks good :+1:

**Comment by aljoscha** [comment]
With two small inline comments.

**Comment by StephanEwen** [comment]
Will adjust the example to use the parameter tool
and merge this...

**Comment by StephanEwen** [comment]
Manually merged

**Pull request closed without merging**
