### PR TITLE
[FLINK-15702][SQL]Make sqlClient classloader aligned with other components

### PR DESCRIPTION
**Pull request by liupc**
## What is the purpose of the change

Currently, Flink sqlClient still use hardcoded `parentFirst` classloader to load user specified jars and libraries, this is easily causing classes conflicts. In [FLINK-13749](https://issues.apache.org/jira/browse/FLINK-13749) , we already make the classloader consistent in both client and remote components.

So this PR will try to do the same for sqlClient, and make the classloaders consistent.

## Brief change log

  - *Make the classloader of sqlClient respecting the classloading policy and thus make it consistent with other flink components*

## Verifying this change

Can be verified by existing UT: *DependencyTest*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: ( no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by liupc** [comment]
@TisonKun  Thanks for reply, it's good to use `ClientUtils.buildUserCodeClassLoader` to deduplicate codes. I've updated.

**Comment by liupc** [comment]
@flinkbot run travis

**Comment by liupc** [comment]
@TisonKun gentle ping~

**Comment by TisonKun** [comment]
@liupc Thanks for your contribution!

**Pull request merged**
