### PR TITLE
[FLINK-1710] [table] Switch compile backend to Janino

### PR DESCRIPTION
**Pull request by aljoscha**
This greatly reduces compile time while still supporting the same
feature set.

I added Janino in flink-bin/LICENSE and flink-bin/NOTICE. I hope this is correct. Can someone comment on this?

### CODE REVIEW

**Comment by StephanEwen** [comment]
Looks good!
Any concrete numbers in how the compile time changes? I assume this is now shipping java code strings which get compiled in each function / serializer / comparator?

**Comment by aljoscha** [comment]
Correct, we ship java code in a String that is then compiled and invoked by proxy functions.

On my machine, the time spent in mvn verify on flink-table goes down from about 2:45 to 45 seconds. On travis it goes down from 7 min to about 2 min.

**Comment by StephanEwen** [comment]
Do we have a breakdown on how much time gets spent in what parts?
  - Client
  - execution
  - compilation inside the runtime

**Comment by aljoscha** [comment]
What do you mean by execution? I would imagine that all of these are a couple of milliseconds only. When you run all the Table API tests and IT cases in your IDE the tests fly by in about 5 seconds.

**Pull request closed without merging**
