### PR TITLE
[FLINK-1531] Fixes KryoSerializer's EOFException forwarding

### PR DESCRIPTION
**Pull request by tillrohrmann**
Adds proper EOFException forwarding to the KryoSerializer.

### CODE REVIEW

**Comment by rmetzger** [comment]
Looks good
+1

**Comment by rmetzger** [comment]
We should also put the fix into the release-0.8 branch.

**Comment by tillrohrmann** [comment]
Tests for release-0.8 are running.

**Comment by tillrohrmann** [comment]
Ok, I'll merge it.

**Pull request closed without merging**
