### PR TITLE
[FLINK-21664][table-api] Support STATEMENT SET syntax in TableEnvironment

### PR DESCRIPTION
**Pull request by SteNicholas**
## What is the purpose of the change

*Currently we have discussed the grammar about multi-line statements as follows:*
```
BEGIN STATEMENT SET;
INSERT INTO ... SELECT ...;
INSERT INTO ... SELECT ...;
END;
```
*`SqlParser` should support `STATEMENT SET` syntax in `TableEnvironment`.*

## Brief change log

  - *Add `SqlStatementSet` to support `STATEMENT SET` syntax for `SqlParser`.*

## Verifying this change

  - *`FlinkSqlParserImplTest` adds `testStatementSetWithSingleInsertInto`, `testStatementSetWithMultiInsertInto`, `testStatementSetWithoutInsertInto` and `testStatementSetWithCreateTable` to verify whether `SqlParser` supports the `STATEMENT SET` syntax.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by fsk119** [comment]
Thanks for your contribution @SteNicholas.

I have some thoughts about this PR. Because our goal is to submit statement set in the sql client. However,  the `Executor` is just a wrapper of the `TableEnvironment` that can notice the `Operation` rather than `SqlNode`.  Therefore, we need to introduce operations.

The second question is how sql client submits statement. In the FLIP, we reach consensus that the desired behaviour looks like
```
Flink SQL> BEGIN STATEMENT SET;
 
[Info] Begin the statement set.
 
Flink SQL> INSERT INTO emps1 SELECT * FROM emps(x, y);
 
[Info] Add the statement into the statement set.
 
Flink SQL> INSERT INTO emps2 SELECT * FROM emps(x, y);
 
[Info] Add the statement into the statement set.
 
Flink SQL> END;
 
[Info] Submitting SQL statement set to the cluster...

```

I think the proposed grammer may not achieve the final goal.

**Comment by SteNicholas** [comment]
@fsk119 , thanks for your detailed review. The question you mentioned above has already been discussed by @wuchong . I would like to unify the parser behavior of TableEnvironment and SQL Client.

**Comment by SteNicholas** [comment]
@wuchong @fsk119 , I have followed the statement set syntax as follows:
```
BEGIN STATEMENT SET;
INSERT INTO xx SELECT * FROM xxx;
END;
```
Please help to review this update for the statement set syntax.

**Comment by SteNicholas** [comment]
@wuchong , thanks for detailed review. I have followed your comments and only supported the statement set parser. Please help to review again.

**Review by wuchong — APPROVED** [review]
LGTM

**Pull request merged**
