### PR TITLE
[FLINK-36273][table] Remove deprecated Table/SQL configuration in 2.0

### PR DESCRIPTION
**Pull request by xuyangzhong**
## What is the purpose of the change

*Remove deprecated Table/SQL configuration in 2.0. This is a subtask of https://issues.apache.org/jira/browse/FLINK-35473.*

## Brief change log

  - *Add a config in values source to let it can disable agg push down*
  - *Remove deprecated Table/SQL configuration in 2.0*

## Verifying this change

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented?

### CODE REVIEW

**Comment by xuyangzhong** [comment]
@flinkbot run azure

**Comment by xuyangzhong** [comment]
@flinkbot run azure

**Review by lincoln-lil — COMMENTED** [review]
The 1st commit LGTM!

**Comment by lincoln-lil** [comment]
For 2nd commit,  went over all options mentioned in https://issues.apache.org/jira/browse/FLINK-35473
All deprecated options there were remove except the occurrences in corresponding release notes.

The changes looks good!

**Review by lincoln-lil — APPROVED** [review]
@xuyangzhong Thanks for the changes! Good for merging.
Btw, the hive connector already start the externalize process and has a copy in the new repo: https://github.com/apache/flink-connector-hive
So related changes should be synced there after corresponding 2.0 branch is setup, you can create a jira to track it.

**Pull request merged**
