### PR TITLE
[FLINK-29158] Fix logging in DefaultCompletedCheckpointStore

### PR DESCRIPTION
**Pull request by rkhachatryan**
## What is the purpose of the change

Fix swapped log messages on checkpoint subsumption.

## Verifying this change

This change is a trivial rework without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? no

### CODE REVIEW

**Review by Myasuka — APPROVED** [review]
LGTM. Thanks for the update.

**Comment by rkhachatryan** [comment]
@flinkbot run azure

**Comment by rkhachatryan** [comment]
@flinkbot run azure

**Comment by fredia** [comment]
@flinkbot run azure

**Pull request closed without merging**
