### PR TITLE
[FLINK-3366] Rename @Experimental annotation to @PublicEvolving

### PR DESCRIPTION
**Pull request by fhueske**

### CODE REVIEW

**Comment by StephanEwen** [comment]
Can you update the JavaDoc of the `@PublicEvolving` annotation?

Otherwise, good to merge...

**Comment by fhueske** [comment]
Thanks for catching that @StephanEwen.
JavaDocs are updated.

**Comment by fhueske** [comment]
Will merge this

**Comment by rmetzger** [comment]
+1 to merge

**Pull request closed without merging**
