### PR TITLE
[FLINK-26848][JDBC]Support to write data when disable flush-interval and max-rows

### PR DESCRIPTION
**Pull request by hehuiyuan**
## What is the purpose of the change

sink.buffer-flush.interval | The flush interval mills, over this time, asynchronous threads will flush data. Can be set to '0' to disable it. Note, 'sink.buffer-flush.max-rows' can be set to '0' with the flush interval set allowing for complete async processing of buffered actions.
-- | --
sink.buffer-flush.max-rows | The max size of buffered records before flush. Can be set to zero to disable it.

`Asynchronous thread flush` is disabled&nbsp; when set `sink.buffer-flush.interval` = 0,&nbsp; then disable `sink.buffer-flush.max-rows`, which causes the data is not written out.

The data are not written when disable `flush.interval` and `max-rows`. I think it should write out when the data arrive.

image

### CODE REVIEW

**Comment by hehuiyuan** [comment]
@flinkbot run azure

**Comment by hehuiyuan** [comment]
Hi @MartijnVisser , have a look when you are free.

**Comment by MartijnVisser** [comment]
@hehuiyuan I'm not a JDBC expert, so I can't review this PR.

**Comment by rkhachatryan** [comment]
Thanks for the PR @hehuiyuan , I'm also not an expert in connectors/JDBC.
@fapaul, @JingsongLi, maybe you could take a look?

**Comment by hehuiyuan** [comment]
hi  @fapaul @JingsongLi  ,     have a look this pr.

**Comment by MartijnVisser** [comment]
We've now moved the code from the JDBC connector to its own dedicated repository; please re-route this PR to https://github.com/apache/flink-connector-jdbc

**Pull request closed without merging**
