### PR TITLE
[FLINK-19453][table-common] Deprecate old source and sink interfaces

### PR DESCRIPTION
**Pull request by twalthr**
## What is the purpose of the change

Deprecates all old source and sink interfaces and their helper interfaces that are not required in FLIP-95.

## Brief change log

Deprecation annotation and comment added.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes
  - The serializers: no
  - The runtime per-record code paths (performance sensitive):no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper:  no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? JavaDocs

### CODE REVIEW

**Comment by twalthr** [comment]
CC @wuchong

**Comment by wuchong** [comment]
Shall we also deprecate the interfaces `AppendStreamTableSink`, `RetractStreamTableSink`, `UpsertStreamTableSink`, `StreamTableSource`... which are located in `flink-table-api-java-bridge` module?

**Comment by twalthr** [comment]
Thanks for the hint @wuchong. I deprecated even more interfaces. Let me know if you spotted more.

**Review by wuchong — APPROVED** [review]
Thanks for the updating. LGTM.

+1 to merge.

**Pull request closed without merging**
