### PR TITLE
[FLINK-3372] Setting custom YARN application name is ignored

### PR DESCRIPTION
**Pull request by ndimiduk**

### CODE REVIEW

**Comment by rmetzger** [comment]
+1 to merge

**Comment by tillrohrmann** [comment]
Changes look good to me :-) +1 to merge

**Comment by StephanEwen** [comment]
Merging this...

**Comment by StephanEwen** [comment]
Will add this as well to 0.10-SNAPSHOT

**Comment by StephanEwen** [comment]
Actually, this is only relevant for 0.10-SNAPSHOT, 1.0-SNAPSHOT has this behavior already

**Comment by fhueske** [comment]
Hi @ndimiduk, the ASF bot only closes PRs which are merged into master.
Can you manually close this one? Thanks

**Pull request closed without merging**
