### PR TITLE
[FLINK-1851] Add support for casting in Table Expression Parser

### PR DESCRIPTION
**Pull request by aljoscha**
Also fix code generation for casting between primitives.

### CODE REVIEW

**Comment by rmetzger** [comment]
Looks good.
I would expect a change in the documentation when you add support for a new feature ;)

**Comment by aljoscha** [comment]
For the Table API I tried to keep the "website documentation" to a bare minimum while putting a lot of description in the javadoc/scaladoc, that's why there is no documentation about the operations and expressions in the doc.

**Comment by fhueske** [comment]
@aljoscha, please correct me if I am wrong, but there are also no JavaDocs or ScalaDocs added or modified by this PR.

**Comment by aljoscha** [comment]
Correct, nothing is added. I need to spent some time on this when I'm back from vacation.

**Comment by aljoscha** [comment]
I updated the documentation, it is very bare bones but should be sufficient. Should we now merge this?

**Comment by fhueske** [comment]
Looks good. Will merge this now.

**Pull request closed without merging**
