### PR TITLE
[FLINK-19885] Add More Metrics to JobManager in Web UI

### PR DESCRIPTION
**Pull request by vthinkxie**
## What is the purpose of the change

ref https://issues.apache.org/jira/browse/FLINK-19885

## Brief change log

Add More Metrics to JobManager in Web UI

## Verifying this change

- visit the JM metrics page
- verify if the JM metrics match the document https://ci.apache.org/projects/flink/flink-docs-release-1.11/ops/memory/mem_setup_jobmanager.html
before:

image

after:

image

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (no needed)

### CODE REVIEW

**Review by XComp — CHANGES_REQUESTED** [review]
Hi @vthinkxie Thanks for adding the new section. Due to your work we figured out that there might be a mismatch between the `-Xmx` parameter and the maximum heap returned by the metrics system. We tracked it down and I created [FLINK-19904](https://issues.apache.org/jira/browse/FLINK-19904) to cover it in the docs. 

In addition to that, we'd like to add a tooltip explaining the difference. Could you add a conditional tooltip in the cell of the heap metrics in case the max of the metrics is different than the configured value. If that's to tricky, make the tooltip unconditional. I created [FLINK-19897](https://issues.apache.org/jira/browse/FLINK-19897) to cover this bit for the TaskManager overview as well.

Additionally, I'd like you to add the advance section we also have for the TaskManager overview of [FLIP-102](https://cwiki.apache.org/confluence/display/FLINK/FLIP-102%3A+Add+More+Metrics+to+TaskManager). The advance section does not need to contain the "Network Segments" as they are present for the JobManager. Keep in mind that the "Network Garbage Collection" should actually be named "Garbage Collection". This is also covered by [FLINK-19897](https://issues.apache.org/jira/browse/FLINK-19897) to fix it for the TaskManager overview.

Other than that - good work. :-) Sorry that I wasn't specific enough beforehand on the issues mentioned above.

**Comment by vthinkxie** [comment]
image

**Comment by XComp** [comment]
Hi @vthinkxie , thanks for the quick changes. Two thing's I want to raise:
* Is there a reason you didn't add the Garbarge Collection?
* About the conditional tool tip: The heap size will be in bytes having the "b" prefix to indicate the used unit. Can you clarify how you came up with the `1024m` for the configuration endpoint? There might be some miscommunication from my side.

**Comment by vthinkxie** [comment]
- GarbageCollector has `Status.JVM.GarbageCollector.PS_MarkSweep.Time` `Status.JVM.GarbageCollector.PS_MarkSweep.Count` `Status.JVM.GarbageCollector.PS_Scavenge.Time` and `Status.JVM.GarbageCollector.PS_Scavenge.Count` I'm not sure all metrics are needed or not
- I have tried setting the value in the `flink-conf.yaml`, `10240000b` `10240000bytes` and `1024m` or `1G`, all of them can work as configurations, it is hard to compare the string with the number even if there is accurate knowledge about the legal configuration

**Comment by XComp** [comment]
> * GarbageCollector has `Status.JVM.GarbageCollector.PS_MarkSweep.Time` `Status.JVM.GarbageCollector.PS_MarkSweep.Count` `Status.JVM.GarbageCollector.PS_Scavenge.Time` and `Status.JVM.GarbageCollector.PS_Scavenge.Count` I'm not sure if all metrics above are needed or not

The available metrics depend on the JVM being used. The list is dynamically created. I would still see it as interesting "advanced" option. 

> * I have tried setting the value in the `flink-conf.yaml`, `10240000b` `10240000bytes` and `1024m` or `1G`, all of them can work as configurations, it is hard to compare the string with the number even if there is accurate knowledge about the legal configuration

You're right that different units are supported for `flink-conf.yaml`. The configuration value for heap returned by the REST endpoint will be in bytes, though.

**Comment by vthinkxie** [comment]
The configuration value for heap returned by the REST endpoint will is the same string which configured in the `flink-conf.yaml`
截屏2020-11-02 下午7 14 09

**Comment by XComp** [comment]
> * is there a full metric name list? the frontend has to query a specific metric name before listing them on the page, which is provided in the TM Rest API, but not in the JM Rest API.

`/jobmanager/metrics` will return the provided metrics. My understanding is that any metric prefixed by `Status.JVM.GarbageCollector.*` should be listed in the GC section.

**Comment by XComp** [comment]
> * is there a full metric name list? the frontend has to query a specific metric name before listing them on the page, which is provided in the TM Rest API, but not in the JM Rest API.
> * The configuration value for heap returned by the REST endpoint will is the same string which configured in the `flink-conf.yaml`, not in `bytes`
> 
> 截屏2020-11-02 下午7 14 09

I see what you mean. I verified it locally. [PE #13747](https://github.com/apache/flink/pull/13747) ([FLINK-19662](https://issues.apache.org/jira/browse/FLINK-19662)) will change this behavior returning only byte values.

**Comment by XComp** [comment]
After reviewing [PR #13870](https://github.com/apache/flink/pull/13870) (TaskManager-related changes) we came to the conclusion that the optional tooltip would be harder to achieve to rounding errors. To avoid confusion on the user's side we decided to have the tooltip being static. Hence, no changes are necessary in that sence.

**Comment by vthinkxie** [comment]
Hi, I have added the GC panel, here is the screenshot
image

**Comment by vthinkxie** [comment]
updated
image

**Review by XComp — APPROVED** [review]
Thanks for the changes, @vthinkxie . There's nothing else I need to add. Could your squash the commits and I will initiate the merging of the branch into master.

FYI: We discussed offline that there's still an issue with the word wrapping of the tooltips. This is already addressed in [2f17ca0](https://github.com/apache/flink/pull/13870/commits/2f17ca0c4a3ba350263399c1eb03e54f3afb3d4c#diff-7babc92e31fb394810476a4a32c57b02e6da4170923a60a6cd06cfc75fad70b0L75) and will be fixed on `master`.

**Comment by XComp** [comment]
Thanks for all your work, @vthinkxie . @azagrebin will take over and merge the changes into `master`.

**Comment by azagrebin** [comment]
Thanks for working on this @vthinkxie @XComp
merging this

**Pull request closed without merging**
