### PR TITLE
[FLINK-3617] Prevent NPE in CaseClassSerializer and informative error message.

### PR DESCRIPTION
**Pull request by chermenin**
To not to change current implementation of serialization now just NullFieldException has been added.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Looks like a good solution.
Since these serializers are very performance critical, I am curious what is more efficient:
  - The if-null-check you implemented here
  - a try/catch block that catches the nullpointer exception and throws the NullFieldException

Are you interested in microbenchmarking that?

**Comment by chermenin** [comment]
Yep, i'll do a benchmark to test approaches and compare them each other at this week. I will write the results here. Big thanks for your idea)

**Comment by chermenin** [comment]
I've got results and here are:

Benchmark          | Mode  | Cnt  |    Score  |  Error  | Units
-------------------|-------|------|-----------|---------|--------
Just operation      | avgt  | 200  |   74.672  |  0.944  | ns/op
if-else (_not_ null value)      | avgt  | 200  |  915.718  |  5.534  | ns/op
try-catch (_not_ null value)    | avgt  | 200  |   74.183  |  0.405  | ns/op
if-else (null value)         | avgt  | 200  |  901.775  |  5.368  | ns/op
try-catch (null value)       | avgt  | 200  | 8649.317  | 40.462  | ns/op

In this way `if-else-check` always adds more than 800 nanoseconds per operation to run-time.
While `try-catch-block` doesn't slow down normal performance. We really need this option, because null value isn't normal value for us now. I will change the code in the closest future.

**Comment by chermenin** [comment]
@StephanEwen What do you think about merging this PR?

**Comment by StephanEwen** [comment]
Looks good, thanks, will merge this...

**Comment by StephanEwen** [comment]
This has been merged a while back in fdce1f319c512fc845b64cbb7cbfb10f9d899021
I forgot to add the keywork that the bot closes the pull request.

Can you manually close this pull request?

**Pull request closed without merging**
