### PR TITLE
[FLINK-25223][connectors/elasticsearch] Disable Elasticsearch 7 Testcontainer tests due to frequent CI failures

### PR DESCRIPTION
**Pull request by gaoyunhaii**
This PR picks https://github.com/apache/flink/pull/18062 to 1.13

### CODE REVIEW

**Comment by zentol** [comment]
See https://github.com/apache/flink/pull/18131#issuecomment-995792767; same issue with this PR.

**Comment by MartijnVisser** [comment]
Elasticsearch 7 doesn't exist in Flink 1.13, it's only going to be released in 1.15

**Review by MartijnVisser — CHANGES_REQUESTED** [review]
As mentioned, Elasticsearch 7 doesn't exist in 1.13, it's only been added for 1.15. See https://issues.apache.org/jira/browse/FLINK-24323

**Review by MartijnVisser — COMMENTED** [review]
Apologies, I was wrong in my previous statement 😓

**Comment by zentol** [comment]
Closing the PR as older branches should not be affected by the memory issue.

**Pull request closed without merging**
