### PR TITLE
[FLINK-6615][core] simplify FileUtils

### PR DESCRIPTION
**Pull request by bowenli86**
## What is the purpose of the change

simplify FileUtils

## Brief change log

simplify FileUtils

## Verifying this change

This change is already covered by existing tests

## Does this pull request potentially affect one of the following parts:

none

## Documentation

no

### CODE REVIEW

**Comment by StephanEwen** [comment]
Is there any problem with the current implementation?
The current implementation was carefully done to gracefully handle concurrent removals and allow to pick whether to clean directories with or without files.

**Comment by bowenli86** [comment]
I was looking into [FLINK-6615](https://issues.apache.org/jira/browse/FLINK-6615), and I think 6615 is not a problem due to files may be created concurrently. But I found the current impl of `deleteDirectory()` to be cumbersome.

The new code also handles concurrent removals well, and I can add back `cleanDirectory()` though it's not used anywhere yet. I'm happy to keep the original impl if you prefer it. Which version do you like better?

**Comment by StephanEwen** [comment]
Fair enough. Seems there are tests for the behavior already, so +1 to merge this

Merging...

**Comment by StephanEwen** [comment]
Actually, going back here. I would like to not merge this after all. The reason being that in my test run, I found that this does not handle concurrent deletes correctly after all:
https://travis-ci.org/StephanEwen/incubator-flink/jobs/287502995

**Comment by StephanEwen** [comment]
I think here is an interesting example of why I am often hesitant with cleanup refactorings, unless there is a pressing need to clean up.

It is very hard to judge if the cleaned up version is really as robust as the original code. This change looked correct at a first glance, but the concurrency tests caught a subtle difference in some runs.

**Comment by bowenli86** [comment]
@StephanEwen Thanks for letting me know. I'll close this PR

**Comment by StephanEwen** [comment]
@bowenli86 I hope you don't mind that I pushed back a bit. It's my job to be careful about such things...

**Pull request closed without merging**
