### PR TITLE
[FLINK-1183] Generate gentle notification message when Flink is started with Java 6

### PR DESCRIPTION
**Pull request by ajaybhat**
I've closed the [previous PR ] (https://github.com/apache/flink/pull/277) in favor of this new one. Pls review it.

### CODE REVIEW

**Comment by uce** [comment]
Thanks for the PR but I vote to postpone such a warning message.

We didn't have a real consensus on the issue (see http://mail-archives.apache.org/mod_mbox/flink-dev/201411.mbox/%3CCANC1h_tZ4KQxJiiCmfJLqoXHEbfRD1uAtR1Fn0jAYWz-uecJfw@mail.gmail.com%3E). Currently, I don't see any fundamental reason to drop the support or warn about dropping the support. In any case, your proposal is confusing as Flink runs perfectly fine with Java 6.

Any opinions on this?

**Comment by rmetzger** [comment]
Hi,
I agree that the message is not correct. Flink will run very well with Java 6.
BUT: I think we should print a warning because Java 6 is EOL. It is actually a security issue to run java 6 because it isn't patched anymore.
So I would certainly vote for having a warning.

**Comment by uce** [comment]
I would be fine with such a message if it was more "gentle". ;-)

**Comment by hsaputra** [comment]
I would love to keep the PR with modified message about Flink is running in Java6 .

**Comment by fhueske** [comment]
I agree. We should print a notification message that tells the user that it is not recommended to run on Java6 due to its EOL. 
As @rmetzger said, Flink runs fine with Java6 but this might change in the future and we want to prepare users for that.

**Comment by StephanEwen** [comment]
How about setting the message to something like

 "Warning: You are running Flink with Java 6, which is not maintained any more by Oracle or the OpenJDK community. Flink currently supports Java 6, but the support for Java 6 may be stopped in future versions due to the unavailability of bug fixes security patched."

**Comment by hsaputra** [comment]
+1 gentler and informative =)

**Comment by ajaybhat** [comment]
Thanks for the comments. Do you think the new message is better?

**Comment by uce** [comment]
Yes +1 for the new message.

I will merge this in the next batch. It's not super important, but I think this should go into 0.8.0 if there is a new RC.

**Comment by rmetzger** [comment]
I think its fine to just merge it to the release-0.8 branch
It will then automatically go into 0.8.1. I'll create a version in JIRA....

On Thu, Jan 15, 2015 at 2:52 PM, Ufuk Celebi <notifications@github.com>
wrote:

> Yes +1 for the new message.
>
> I will merge this in the next batch. It's not super important, but I think
> this should go into 0.8.0 if there is a new RC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/flink/pull/296#issuecomment-70087926>.
>



-- 
Robert Metzger, Kontakt: metzgerr@web.de, Mobil: 0171/7424461

**Pull request closed without merging**
