### PR TITLE
[FLINK-5247] Fix incorrect check in allowedLateness() method. Make it a no-op for non-event time windows.

### PR DESCRIPTION
**Pull request by mindprince**
Also, fix outdated documentation.

### CODE REVIEW

**Comment by mindprince** [comment]
cc - @kl0u, @aljoscha for review

**Comment by mindprince** [comment]
Ping @aljoscha

**Comment by mindprince** [comment]
Thanks for the review @kl0u 

I didn't do it because there was no logger defined in the file.

**Comment by kl0u** [comment]
Hi @mindprince . What do you mean "in the file"? The allowed lateness can always be specified in the program by the developer, right? So logging a message is always a valid approach.

**Comment by xhumanoid** [comment]
I think @mindprince mean: at now logger not defined in class file

this classes without
private static final Logger LOG

**Comment by StephanEwen** [comment]
Thank you for fixing this.
I think it is good as it is, will merge this for Flink-1.2 and master...

**Comment by mindprince** [comment]
Merged in https://github.com/apache/flink/commit/87af84194911eb1e0c3b3a894bb3f04b628fbf11 and https://github.com/apache/flink/commit/4697b97a0101cf04b43c4a6e4887adba10b4a69a

**Pull request closed without merging**
