### PR TITLE
[FLINK-1458] Allow Interfaces and abstract types in TypeExtractor

### PR DESCRIPTION
**Pull request by aljoscha**
Kryo already supports them, so it was just a question of the
TypeExtractor allowing them.

I also added tests for this.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Looks good to me so far, modulo two comments:
  - Since the type extractor code is changed a lot, it would be good to have a test validating that the TypeExtractor allows abstract types and interfaces.
  - I would change the log level of the messages (abstract types are less performant, type is no POJO) to INFO, since WARN implies to me that something is wrong (which is not)

**Comment by aljoscha** [comment]
But I extended the test with a SerializerTest for both Interfaces (traits) and abstract classes. The other thing I will change, yes.

**Comment by StephanEwen** [comment]
The tests cover that the serializer supports this. One issue was that the type extractor rejected the types, even though they were supported.

**Comment by aljoscha** [comment]
You're right.

**Comment by pm-pushpendra-jaiswal** [comment]
Hi @aljoscha  
Still getting this warning on compiling for accessing a of type Map[String,Any]
Type Any has no fields that are visible from Scala Type analysis. Falling back to Java Type Analysis (TypeExtractor).

Flink version 1.1.1

**Pull request closed without merging**
