### PR TITLE
[hotfix][docs] add Back to top button

### PR DESCRIPTION
**Pull request by leesf**
## What is the purpose of the change

Add back to top button for connectors overview docs.

## Brief change log

Add back to top button for connectors overview docs.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by lamber-ken** [comment]
hi, @leesf , happy new year. thanks for your pr. I think it's better to check all docs which need add back to top button.
for example, [java_lambdas](https://ci.apache.org/projects/flink/flink-docs-release-1.7/dev/java_lambdas.html) doc

**Comment by lamber-ken** [comment]
happy new year :tada: 

hi, @zentol. I think it's better these [java_lambdas](https://ci.apache.org/projects/flink/flink-docs-release-1.7/dev/java_lambdas.html), [ml](https://ci.apache.org/projects/flink/flink-docs-release-1.7/dev/libs/ml), [broadcast_state](https://ci.apache.org/projects/flink/flink-docs-release-1.7/dev/stream/state/broadcast_state.html) doc need to add back to top button. do you think so? if so, it's no need to open a new ps

best lamber-ken

**Comment by leesf** [comment]
@lamber-ken happy new year, thanks for your reviewing. I could check all docs without Back to top button and update my another pr (https://github.com/apache/flink/pull/7360) since this pr is merged. cc @zentol

**Comment by lamber-ken** [comment]
> @lamber-ken happy new year, thanks for your reviewing. I could check all docs without Back to top button and update my another pr (#7360) since this pr is merged. cc @zentol

:+1:

**Pull request merged**
