### PR TITLE
[FLINK-3655] [core] Support multiple paths in FileInputFormat

### PR DESCRIPTION
**Pull request by fhueske**
## What is the purpose of the change

* Add support to `FileInputFormat` to read from multiple paths. At the moment only a single path is supported that can be recursively read if the path is a directory.
* Maintain compatibility with existing input formats that extend `FileInputFormat`

This PR is an extension / rework of PR #1990.

## Brief change log

`FileInputFormat` is declared as `@Public` interface.

* deprecate the `protected` variable `FileInputFormat.filePath` of type `Path`. We need to store more than one path to support multiple paths.
* deprecate the method `FileInputFormat.getFilePath()`. We need to return a list of paths.
* add a private member variable to `FileInputFormat` to store multiple paths.
* add methods to set and get multiple paths.
* add a `deprecated` method `public boolean FileInputFormat.supportsMultiPaths()` with default implementation `return false;` that input formats can override if they support multiple paths. If the method returns `true`, the deprecated `filePath` variable is not used anymore and will always be `null`. 
* changed all public sub classes of `FileInputFormat` to not directly access the deprecated `filePath` variable but use the more generic `getFilePaths()` method.
* We cannot override `supportsMultiPaths` in `DelimitedInputFormat` and `BinaryInputFormat` because they are part of the public API and not final.

## Verifying this change

* added a couple of tests to validate that splits and statistics are correctly generated.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): **no**
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: **YES**
  - The serializers: **no**
  - The runtime per-record code paths (performance sensitive): **no**
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: **no**
  - The S3 file system connector: **no**

## Documentation

  - Does this pull request introduce a new feature? **yes**
  - If yes, how is the feature documented? Only in JavaDocs so far.

### CODE REVIEW

**Comment by zentol** [comment]
What would speak against creating a new FileInputFormat that supports multiple paths instead? Common code could be moved into a shared super class (I _think_ that would be allowed).

**Comment by fhueske** [comment]
Thanks for the question @zentol. That might be a cleaner solution, but I don't think we could move much into the shared super class. Everything that's not `private` would need to be duplicated to maintain binary compatibility. However, most method are `protected` or `private`.

**Comment by fhueske** [comment]
Thanks for the review @zentol. 

I've addressed your feedback, improved the backwards compatibility as discussed offline, and added multi-path support to additional input formats.

**Comment by fhueske** [comment]
Will merge this.

**Comment by Jason-liujc** [comment]
Question, how do one use this with StreamExecutionEnvironment? It seems in the readFile call, the file path just gets overwritten here: 

https://github.com/apache/flink/blob/6c7b195d57c3bad5bc1f2251de75ac744dbbe4a7/flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java#L1322

**Comment by fhueske** [comment]
Hi @Jason-liujc,

You are right. `StreamExecutionEnvironment.readFile()` only supports a single path but it's also just a convenience method. 
I think you can replicate the logic of the `private createFileInput()` method which calls `StreamExecutionEnvironment.addSource()`.

Hope this helps,
Fabian

**Comment by Jason-liujc** [comment]
Thanks Fabian!

After switching to using `StreamExecutionEnvironment.addSource()`, I encountered this error in Flink 1.8: 

```
org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: FileInputFormats with multiple paths are not supported yet.",
        "\tat org.apache.flink.runtime.webmonitor.handlers.JarRunOverrideHandler.lambda$getJobGraphAsync$10(JarRunOverrideHandler.java:475)",
```

So it seems under `createFileInput()`, the function calls `new ContinuousFileMonitoringFunction()` which does the file path check and it fails because there are multiple of them. Is there anyway I can get around this?

Thanks,
Jason

**Comment by edgarco** [comment]
@Jason-liujc 

I've also just encountered this issue, did you ever find a work around? Seems the ContinuousFileMonitoringFunction is not fully implemented to use multiple paths

**Comment by Jason-liujc** [comment]
Yea I basically cloned the source code for `ContinuousFileMonitoringFunction` and added the reading from multiple directories capability to it. 

I can't really share the source code right now as we need internal approval to do it. But basically, in the `run()` function, loop through each path and do `monitorDirAndForwardSplits()` on that given path. There's some kinks you might have to work out to get the checkpoint to work properly but that's the general idea.

**Pull request closed without merging**
