### PR TITLE
[FLINK-30019][hive] Remove the unused HiveTableFileInputFormat in hive conn…

### PR DESCRIPTION
**Pull request by Aitozi**
…ector

## What is the purpose of the change

clean up unused class.

## Brief change log

Remove the HiveTableFileInputFormat

### CODE REVIEW

**Review by luoyuxia — APPROVED** [review]
Thanks for contribution. LGTM.
Btw, could you please update the pr title to 
`[FLINK-30019][hive] Remove the unused HiveTableFileInputFormat in hive connector`

**Comment by Aitozi** [comment]
> Thanks for contribution. LGTM. Btw, could you please update the pr title to `[FLINK-30019][hive] Remove the unused HiveTableFileInputFormat in hive connector`

Sure, done!

**Comment by Aitozi** [comment]
> @Aitozi Could you please rebase the master, and then I'll find a committer help merge. Thanks.

thanks, done

**Comment by luoyuxia** [comment]
> Thanks for contribution. LGTM. Btw, could you please update the pr title to `[FLINK-30019][hive] Remove the unused HiveTableFileInputFormat in hive connector`

I mean the title of the pr, not the commit.

**Comment by Aitozi** [comment]
> > Thanks for contribution. LGTM. Btw, could you please update the pr title to `[FLINK-30019][hive] Remove the unused HiveTableFileInputFormat in hive connector`
> 
> @Aitozi Hi, I mean the title of the pr, not only the commit.

Aha, updated😄

**Comment by luoyuxia** [comment]
@wuchong Could you please help merge?

**Pull request merged**
