### PR TITLE
[hotfix][docs] Fix some formatting errors in Chinese documents.

### PR DESCRIPTION
**Pull request by liuzhuang2017**
## What is the purpose of the change
- **In english document:**

image

- **In chinese document:**
image

## Brief change log

- Fix some formatting errors in Chinese documents.

## Verifying this change
- No need to test.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by liuzhuang2017** [comment]
@MartijnVisser , Sorry to bother you again, can you help me review this pr? Thank you.

**Comment by liujingmao** [comment]
good

**Review by liujingmao — APPROVED** [review]
ok

**Comment by JingsongLi** [comment]
```
2022-08-11T03:19:37.7347614Z Error: Error building site: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/apache/flink-connector-elasticsearch/docs@v0.0.0-20220810114753-9bc0c896d0a6/content/docs/connectors/datastream/elasticsearch.md:56:1": failed to render shortcode "py_download_link": failed to process shortcode: "/home/vsts/work/1/s/docs/layouts/shortcodes/py_download_link.html:27:40": execute of template failed: template: shortcodes/py_download_link.html:27:40: executing "shortcodes/py_download_link.html" at <partial "docs/interpolate" $connector.sql_url>: error calling partial: partial that returns a value needs a non-zero argument.
```

It seems something wrong.

**Comment by liuzhuang2017** [comment]
@flinkbot run azure

**Comment by liuzhuang2017** [comment]
@flinkbot run azure

**Pull request closed without merging**
