### PR TITLE
[FLINK-6018][statebackend] Properly initialise StateDescriptor in Abs…

### PR DESCRIPTION
**Pull request by sunjincheng121**
…tractStateBackend.getPartitionedState()

Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [×] General
  - The pull request references the related JIRA issue ("[FLINK-6018]  Properly initialise StateDescriptor in AbstractStateBackend.getPartitionedState()")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [×] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by sunjincheng121** [comment]
HI,guys, Welcome anyone to review this PR.
Best，
SunJIncheng

**Comment by aljoscha** [comment]
This looks good! I'll wait for travis and then merge.

**Comment by sunjincheng121** [comment]
HI, @aljoscha Thank you for your attention to this JIRA.
Best,
SunJincheng

**Comment by aljoscha** [comment]
Thanks for your contribution! 😃 I just merged.

Could you please close this PR?

**Comment by StephanEwen** [comment]
I think this could have really used a test. It is tricky bug that will easily be re-introduced without a test that guards the fix.

**Comment by StephanEwen** [comment]
There is also another method in `AbstractKeyedStateBackend`: `getOrCreateKeyedState` which does not silently use an empty `ExecutionConfig` but throws an exception. That method could also use the same execution config, now that it is available.

**Comment by StephanEwen** [comment]
This change may alter the format of savepoints, because it now forwards type-registrations to the Kryo serializer, which it did not do before.

Since we announced savepoint compatibility, we need to understand when this would happen. Is it something that could not really happen before (because whenever the method was called, the serializer was properly initialized outside), or did this actually occur in some cases?

@sunjincheng121 Can you share how you stumbled across this bug? Was it a code cleanup, or a bug you encountered while running Flink?

**Comment by sunjincheng121** [comment]
Hi, @StephanEwen thanks for your attention to this JIRA. This issue only a code cleanup. In fact this is not a bug. When I work on [FLINK-5995](https://issues.apache.org/jira/browse/FLINK-5995), when using `DefaultOperatorStateBackend#getOperatorState` got an exception, Then I checked out the `AbstractKeyedStateBackend#getPartitionedState`, Then find the code duplicate check. Just like description of this JIRA. 
About `AbstractKeyedStateBackend#getOrCreateKeyedState` I'm not sure, but I suggest do the same thing with  `getPartitionedState`. Because I had check `WindowOperator's windowStateDescriptor` also use `input.getType().createSerializer(getExecutionEnvironment().getConfig())` init the `typeSerializer`. 
What do you think?

**Comment by aljoscha** [comment]
@StephanEwen you're right, this is problematic. The funny thing is, that this actually works for Kryo. Having a serialiser without any registered types/serializer works when the restoring serialiser does have registered types/serializers. It does probably not work the other way round. I started implementing the fixup, tests here: https://github.com/aljoscha/flink/tree/jira-6018-state-init-fixups

**Comment by StephanEwen** [comment]
This change is probably uncritical:
  - It seems this code path was never executed (by chance) because the `RuntimeContext` pre-initializes state descriptors, and all the operators directly supply serializers to the descriptors.
  - As @aljoscha mentioned, in the current case or the KryoSerializer, adding more configuration is not a problem.

Okay, +1, this seems safe.

**Comment by StephanEwen** [comment]
@aljoscha Can you share https://github.com/aljoscha/flink/tree/jira-6018-state-init-fixups with @tzulitai who is looking into serializer upgrade paths?

**Pull request closed without merging**
