### PR TITLE
[FLINK-6590] Integrate automatic docs generation

### PR DESCRIPTION
**Pull request by zentol**
Rebased version of #3916; builds on #5052.

This PR partially integrates the docs generation introduced in FLINK-5781/#3495  into the actual documentation.

The following sections now use the generated tables:
* WebFrontend
* Metrics
* Kerberos
* Zookeper (security)
* Queryable state
* HistoryServer

Of course, some pictures:

web
metrics
kerberos
zookeeper
qs
hs

For the parameters listed under `Common Options` i propose simply linking to the corresponding table as shown here:
env1
env2

### CODE REVIEW

**Comment by alpinegizmo** [comment]
Very pleased to see this coming to fruition.

**Comment by kl0u** [comment]
Building the documentation seems to be working, and the docs look nice.
Thanks a lot for the work @zentol .

+1 to merge

**Comment by yew1eb** [comment]
nice!
LGTM

**Comment by zentol** [comment]
merging

**Pull request merged**
