### PR TITLE
[hotfix][doc] Remove duplicate dot in generating_watermarks.md

### PR DESCRIPTION
**Pull request by wangzhuoz**
## What is the purpose of the change

Remove duplicate dot in docs/content.zh/docs/dev/datastream/event-time/generating_watermarks.md and docs/content/docs/dev/datastream/event-time/generating_watermarks.md

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by MartijnVisser** [comment]
Hi. You've now created a second PR for the same problem, with your first one being https://github.com/apache/flink/pull/18175. Please close one PR and make sure that the one you leave open meets the PR and Code Style & Quality Guidelines.

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Comment by MartijnVisser** [comment]
@wangzhuoz Can you please rebase your branch?

**Comment by wangzhuoz** [comment]
> @wangzhuoz Can you please rebase your local branch on `master` ?

sry,very busy recently.
ths for your patience,I've done fellow your suggestion.

**Comment by MartijnVisser** [comment]
@wangzhuoz No problem. I don't see any pushes yet on this PR, please make sure that you've rebased and then push it again.

**Comment by MartijnVisser** [comment]
@wangzhuoz I've cherry-picked your commits (so it will show that you've contributed) and created a new PR to help you a bit. You can find it at https://github.com/apache/flink/pull/18250

**Comment by wangzhuoz** [comment]
> 

I'm so appreciate you done that , continue to learn flink and git .
thank you.

**Pull request closed without merging**
