### PR TITLE
[FLINK-13424][hive] HiveCatalog should add hive version in conf

### PR DESCRIPTION
**Pull request by lirui-apache**
## What is the purpose of the change

To avoid overriding the hive version users specify in the yaml file.

## Brief change log

  - Add hive version to hive conf in `HiveCatalog`
  - Hive table factory and source/sink will retrieve hive version from hive conf. And errors out if hive version is not present.

## Verifying this change

Existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no
## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? NA

### CODE REVIEW

**Comment by lirui-apache** [comment]
cc @xuefuz @zjuwangg

**Comment by lirui-apache** [comment]
Latest Travis build succeeded: https://travis-ci.com/flink-ci/flink/builds/121001697

**Comment by bowenli86** [comment]
ran tests locally and found the test is failing

```
[ERROR] Errors:
[ERROR]   TableEnvHiveConnectorTest.setup:59 » NullPointer Hive version cannot be null
[INFO]
[ERROR] Tests run: 227, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by lirui-apache** [comment]
@bowenli86 Thanks for pointing out! Just rebased and fixed this test.

**Comment by bowenli86** [comment]
Hi @lirui-apache there's another failure

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 9.478 s <<< FAILURE! - in org.apache.flink.table.catalog.hive.HiveCatalogITCase
[ERROR] testGenericTable(org.apache.flink.table.catalog.hive.HiveCatalogITCase)  Time elapsed: 0.236 s  <<< ERROR!
org.apache.flink.table.api.TableException: Create BatchTableEnvironment failed.
	at org.apache.flink.table.catalog.hive.HiveCatalogITCase.testGenericTable(HiveCatalogITCase.java:93)
Caused by: java.lang.reflect.InvocationTargetException
	at org.apache.flink.table.catalog.hive.HiveCatalogITCase.testGenericTable(HiveCatalogITCase.java:93)
Caused by: java.lang.NoSuchMethodError: org.apache.flink.table.codegen.ExpressionReducer.<init>(Lorg/apache/flink/table/api/TableConfig;)V
	at org.apache.flink.table.catalog.hive.HiveCatalogITCase.testGenericTable(HiveCatalogITCase.java:93)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   HiveCatalogITCase.testGenericTable:93 » Table Create BatchTableEnvironment fai...
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

**Pull request closed without merging**
