### PR TITLE
[FLINK-9108][docs] Fix invalid link

### PR DESCRIPTION
**Pull request by Matrix42**
## What is the purpose of the change

Fix invalid link

### CODE REVIEW

**Comment by alpinegizmo** [comment]
+1

**Comment by zentol** [comment]
merging

**Comment by Matrix42** [comment]
@zentol Is this closed by accident?

**Comment by zentol** [comment]
ehh...whoops. Yes i closed it by accident, thanks for catching it. I'll merge the commit in a second...

**Pull request closed without merging**
