### PR TITLE
[FLINK-4440][gelly] Add Vertex.create and Edge.create helper methods

### PR DESCRIPTION
**Pull request by mushketyk**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [x] General
  - The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
  - The pull request addresses only one issue
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [x] Documentation
  - Documentation has been added for new functionality
  - Old documentation affected by the pull request has been updated
  - JavaDoc for public methods has been added

- [x] Tests & Build
  - Functionality added by the pull request is covered by tests
  - `mvn clean verify` has been executed successfully locally or a Travis build has passed

### CODE REVIEW

**Comment by mushketyk** [comment]
Added helper methods to make Gelly API more concise.
Now one can write this:
```
Vertex<Integer, NullValue> v = Vertex.create(42);
Edge<Integer, Integer, NullValue> e = Edge.create(5, 6);
```

Instead of this:
```
Vertex<Integer, NullValue> v = new Vertex<Integer, NullValue>(42, NullValue.getInstance());
Edge<Integer, Integer, NullValue> e = new Edge<Integer, Integer, NullValue>(5, 6, NullValue.getInstance());
```

**Comment by vasia** [comment]
Hi @mushketyk,
thank you for this PR. Is there a corresponding JIRA for it? If not, can you please create one and tag the PR with it?
Also, make sure you read the [How to contribute guide](https://flink.apache.org/how-to-contribute.html) and make sure your PR checks all the items in the list above.
Let us know if you have questions!

**Comment by mushketyk** [comment]
Hi @vasia 
I've created a JIRA issue for the pull request.
What do you think about this change?

**Comment by mushketyk** [comment]
Closing according to discussion in JIRA.

**Pull request closed without merging**
