### PR TITLE
[FLINK-13276][hive][doc] write documentation and quickstart for Flink-Hive integration

### PR DESCRIPTION
**Pull request by bowenli86**
## What is the purpose of the change

This PR adds documentation and quickstart for Flink-Hive compatibility.

## Brief change log

- added documentation and quickstart for Flink-Hive compatibility.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)
## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (docs)

### CODE REVIEW

**Comment by bowenli86** [comment]
@sjwiesman @xuefuz @lirui-apache @zjuwangg Hi, can you take a look?

If you find there are more content or details should be added, you can either leave comments here and have me add them, or feel free to create JIRA tickets and work on them yourself

**Comment by bowenli86** [comment]
@xuefuz thanks for your review.

4 is already there, 5 and 6 will be in `catalog.md`. I will add bullet points of 1, 2, and 3 for others to write detailed doc.

**Comment by xuefuz** [comment]
Sounds good. It would be also great if we can tell user where to get further help, which probably just needs a couple of sentences. Thanks.

**Comment by bowenli86** [comment]
> Sounds good. It would be also great if we can tell user where to get further help, which probably just needs a couple of sentences. Thanks.

general help page is at https://flink.apache.org/gettinghelp.html for all flink features, we don't need to have a "getting help" section just for the hive feature

**Comment by bowenli86** [comment]
merged in 1.10.0: 73c4e107fcec2ff1ed4a75735b79405571afd525 1.9.0: 39850423058ac70729fdc5a0d9866f18cb825bfc

**Pull request closed without merging**
