### PR TITLE
[hotfix][doc] There is a link redirection problem in the Chinese document of Checkpointing

### PR DESCRIPTION
**Pull request by WTZ468071157**
## What is the purpose of the change

*There is a link redirection problem in the Chinese document of Checkpointing.
When I wanted to click on the link of 'working with state' in the Chinese document to get more information, the page jumped to 404, but when I checked the English document, I found that turn to correct page. So i fix the link of 'working with state' in the Chinese document.*
image

## Brief change log
- Modify the link of 'working with state' in the Chinese document of Checkpointing.

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no) no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no) no
  - The serializers: (yes / no / don't know) no
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know) no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know) no
  - The S3 file system connector: (yes / no / don't know) no

## Documentation

  - Does this pull request introduce a new feature? (yes / no) no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) no

### CODE REVIEW

**Review by MartijnVisser — APPROVED** [review]
Thank you for fixing this. You've created this PR to point to the `release-1.14` branch, but it also exists in the `master` branch. Can you also fix it for that branch in a separate PR?

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Comment by WTZ468071157** [comment]
Yes, obviously, I am very happy to do this. There is new PR for master: https://github.com/apache/flink/pull/18183.

**Comment by MartijnVisser** [comment]
@WTZ468071157 You probably need to rebase since there was an issue with some of the Python tests that have been resolved. When that's done, the build will probably succeed which is needed before we can approve the PR.

**Comment by WTZ468071157** [comment]
Hi, @MartijnVisser I rebase the new branch into mine, and i am so happy for your review. Thank you!

**Pull request closed without merging**
