### PR TITLE
[FLINK-2156] Scala modules cannot create logging file

### PR DESCRIPTION
**Pull request by dawidwys**

### CODE REVIEW

**Comment by chiwanpark** [comment]
Hi @dawidwys, Thanks for opening pull request.
Your pull request looks good to merge. This PR will be merged in few days if there is no objection.

**Comment by chiwanpark** [comment]
BTW, because your PR is based on your master branch, not topic branch, you should [overwrite master branch in your repository](http://stackoverflow.com/questions/1125968/force-git-to-overwrite-local-files-on-pull) after this PR is merged.

Creating a topic branch and sending pull request based on the branch are commonly recommended. :)

**Comment by StephanEwen** [comment]
We do execute multiple tests concurrently (multiple forks). Does this lead to problems when all forks see the fork number "1" ? I am wondering, because at some places, we use the fork number to prevent port conflicts.

Then again, how could these parts have worked before when the fork number was missing in the first place?

**Comment by tillrohrmann** [comment]
FlinkML uses scalatest to run its tests. Scalatest  didn't use the fork
number and simply executed all tests sequentially. This shouldn't be a big
problem, because there are only few tests to run.

**Comment by chiwanpark** [comment]
If we need to parallelize tests run by scalatest, the test cases should extend [ParallelTestExecution](http://doc.scalatest.org/2.2.4/index.html#org.scalatest.ParallelTestExecution).

But I think that we don't need to parallelize test yet.

**Comment by StephanEwen** [comment]
Ah, I see. Then the change looks good, correct?

**Comment by chiwanpark** [comment]
@StephanEwen I think so.

**Comment by chiwanpark** [comment]
Merging this...

**Pull request closed without merging**
