### PR TITLE
[FLINK-25312][hive] HiveCatalog supports Flink's managed table

### PR DESCRIPTION
**Pull request by LadyForest**
## What is the purpose of the change

This PR aims to let `HiveCatalog` support Flink's managed table. More details can be found at [FLIP-188](https://cwiki.apache.org/confluence/display/FLINK/FLIP-188%3A+Introduce+Built-in+Dynamic+Table+Storage)

## Brief changelog

This PR contains two commits.
  - 5c2d53d2 migrate `HiveCatalogTest` and `HiveCatalogITCase` to use assertJ
  - d7dc483a let hive support Flink's managed table
    -   enable `HiveCatalog#supportsManagedTable`
    -   inject `connector = 'default'` for `HiveCatalog#createTable` and remove `connector = 'default'` for `HiveCatalog#getTable`
    -  disallow `alter table` changing the catalog table type between `HIVE_TABLE`, `FLINK_MANAGED_TABLE` and `FLINK_NON_MANAGED_TABLE.`
  

## Verifying this change

This change added tests and can be verified as follows:
- Extend `HiveCatalogTest` to verify table parameters and options when creating and getting Flink's managed table, and verify the expected exception thrown when alter table is changing the catalog table type.
- Extend `HiveCatalogITCase` to verify enriched options and connector key is injected when creating and getting Flink's managed table

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**yes** / no) add test dependency
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (**yes** / no)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by LadyForest** [comment]
@flinkbot run azure

**Comment by LadyForest** [comment]
@flinkbot run azure

**Comment by JingsongLi** [comment]
@flinkbot run azure

**Review by JingsongLi — APPROVED** [review]
Thanks @LadyForest for the contribution, looks good to me!

**Pull request merged**
