### PR TITLE
[FLINK-14184] [core] Add LocalContextListener

### PR DESCRIPTION
**Pull request by stephenc**
## What is the purpose of the change

Provide a mechanism for topologies to initialize/tear down classloader singletons and set up thread context information (such as the `MDC` for logging)

## Brief change log

- Created a `LocalContextListener` interface
- Exposed the `LocalContextListener` into the `ExecutionConfig` by allowing registration of the class. We need to register by class to ensure that control over instantiation of the listener is maintained by Flink.
- Created a `LocalContextListeners` helper class to assist in maintaining the local context listener contract
- Wired up the `Task` to invoke the listeners. 

## Verifying this change

This change added tests and can be verified as follows:
- Added tests that verify the `open` and `close` contract of `LocalContextListeners` 

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? JavaDocs

### CODE REVIEW

**Comment by bobtiernay-okta** [comment]
@stephenc Curious what the status of this PR is. Are you still actively working on it?

**Comment by stephenc** [comment]
Well I didn't get much encouragement so I've kind of left it where it is and our topologies are unnecessarily complex and leak a lot requiring task manager restarts after jobs restart several times

**Comment by bobtiernay-okta** [comment]
What type of encouragement / buy-in is needed to get this over the finish line? I'm happy to help if needed.

Btw, I've found a few workaround hacks to make this type of thing work for the interim. Let me know if you are interested and I'd be happy to share.

**Comment by stephenc** [comment]
Seems there is no interest, and I am no longer working with flink right now so cannot drive it myself

**Pull request closed without merging**
