### PR TITLE
[FLINK-28060][kafka] Bump Kafka to 3.2.1

### PR DESCRIPTION
**Pull request by zentol**

### CODE REVIEW

**Review by HuangXingBo — COMMENTED** [review]
change the kafka version of `test_pyflin.sh` and `test_sql_client.sh` too?

**Review by godfreyhe — COMMENTED** [review]
How to verify the change? In particular, the regression are eliminated

**Comment by zentol** [comment]
> change the kafka version of test_pyflin.sh and test_sql_client.sh too?

Good catch; I didn't search for `.sh` files.

> How to verify the change? In particular, the regression are eliminated

The Kafka folks used the reproducer that was provided in FLINK-28060 to verify the fix in KAFKA-13840.

**Review by HuangXingBo — APPROVED** [review]

**Comment by ijuma** [comment]
Fyi, Kafka 3.2.3 was released. We recommend upgrading to that.

**Pull request merged**
