### PR TITLE
[FLINK-13689] [Connectors/ElasticSearch] Fix thread leak in Elasticsearch connector when cluster is down

### PR DESCRIPTION
**Pull request by static-max**
## What is the purpose of the change

Fixes thread leaks caused by unclosed Elasticsearch clients

## Brief change log

  - Created new method *verifyClientConnection()* in *ElasticsearchApiCallBridge*
  - Moved test calls in existing Elasticsearch connectors to this new method
  - verifyClientConnection() is called in *ElasticsearchSinkBase#open()* after client has been created. If an error occurs, close() in 'ElasticsearchSinkBase' can now clean up the client. This was not possible before as the Exception was thrown before the client variable was assigned.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

I tested the change on our development cluster by applying the change on top of release tag 1.9.1. No problems so far and the threads don't leak anymore. Recovery works fine, I tested different scenarios with the Elasticsearch cluster shut down,.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by aljoscha** [comment]
Do you think you might be able to add a test that verifies that we close the client even if the `createClient()` methods throws an exception. Not sure that's easily possible so I'm not against merging without such a test.

**Comment by static-max** [comment]
Thanks for the review!
I will try to create a test to verfiy that close() gets called, but I'm off for the next days, so it would take at least a week for me to respond, if that's ok.

**Comment by aljoscha** [comment]
Cool, that's fine. Enjoy your days off!

**Comment by static-max** [comment]
I did not find a convenient way to check if close() was called. The Elasticsearch client does not expose the underlying CloseableHttpAsyncClient, so we need to use reflection and I don't know if this is wanted by the Flink team.

**Comment by aljoscha** [comment]
Thanks a lot! I merged this now.

**Pull request closed without merging**
