### PR TITLE
[FLINK-1201] Add flink-gelly to flink-addons (with commit history)

### PR DESCRIPTION
**Pull request by vasia**
Hi everyone,
here's the new PR for the graph api.
I have addressed the comments of #326 and looking forward to additional feedback!
-V.

### CODE REVIEW

**Comment by rmetzger** [comment]
Thank you.
Looks good. History is preserved and you addressed my comments.

+1 for merging it.

**Comment by fhueske** [comment]
Haven't had a closer look yet, but one thing that I noticed is the naming of the test files. 
In the current codebase all tests are named XyzTest (or XyzITCase) instead of TestXyz. Not sure if its worth changing though...

**Comment by vasia** [comment]
No worries, I can rename the tests. It's better to be consistent :)
May I ask, what is the difference between a XyzTest and a XyzITCase test though? Thnx!

**Comment by fhueske** [comment]
Sure, XyzTest are unit tests which are executed in Maven's test phase. These should execute rather fast. Everything that brings up a full Flink system is an integration test case (XyzITCase) and executed during mvn verify. These are used for long running tests.

**Comment by vasia** [comment]
Alright, thanks @fhueske! So, it seems all of our tests are integration test cases. I will update later today I hope :)

**Comment by vasia** [comment]
Tests renamed :)

**Comment by fhueske** [comment]
One more thing ;-)
Did we collect ICLAs from all people contributing significant parts to Gelly?

**Comment by cebe** [comment]
@fhueske why is that needed? [Gelly is Apache 2.0](https://github.com/project-flink/flink-graph/blob/master/LICENSE) licensed and Flink too: https://github.com/apache/flink/blob/master/LICENSE

**Comment by fhueske** [comment]
This is not about the license of the software / code itself. The [ASF homepage](http://www.apache.org/licenses/#clas) says

> The ASF desires that all contributors of ideas, code, or documentation to the Apache projects complete, sign, and submit (via postal mail, fax or email) an Individual Contributor License Agreement (1) (CLA) [ PDF form ]. The purpose of this agreement is to clearly define the terms under which intellectual property has been contributed to the ASF and thereby allow us to defend the project should there be a legal dispute regarding the software at some future time. A signed CLA is required to be on file before an individual is given commit rights to an ASF project.

An ICLA also prevents that major parts of the code base need to be removed / rewritten, if a contributor decides to change the license in the future.

**Comment by cebe** [comment]
I see, did not know about this. thanks!

**Comment by vasia** [comment]
Right, thanks @fhueske for bringing this up!
@balidani, @andralungu, @cebe: could you please complete and sign [this form](https://www.apache.org/licenses/icla.pdf) (if you haven't already)? Thank you!

**Comment by hsaputra** [comment]
Good catch, Fabian. Yes, please do submit ICLA to secretary before we could
continue.

**Comment by cebe** [comment]
> @cebe: could you please complete and sign this form (if you haven't already)? Thank you!

done.

**Comment by balidani** [comment]
Sorry, I will only be able to fill the form on Sunday, my internet
connection is horrible here. Is that ok?

Daniel

**Comment by vasia** [comment]
@balidani that's OK :)
@cebe we've got the acknowledgement for you, thanks! 
@andralungu has submitted hers today.

**Comment by rmetzger** [comment]
I'm really sorry that I've messed up this pull request by renaming "flink-addons" to "flink-staging" :(
I was doing it in a rush.... Really sorry.

**Comment by andralungu** [comment]
I got the ACK from Apache. My ICLA has been filed :)

**Comment by vasia** [comment]
@rmetzger does this mean I need to do the history filtering magic again and open a new pr?
@andralungu thanks a lot!
@balidani have you submitted yours?

**Comment by balidani** [comment]
@vasia yes, just submitted mine

**Comment by vasia** [comment]
Great, thanks ^^

**Comment by rmetzger** [comment]
@vasia: You don't need to open a new pull request, force pushing to the branch this PR is based on will update it.
I don't know if you need to do the history filtering magic again. Maybe a rebase is sufficient.

**Comment by vasia** [comment]
Simple renaming didn't seem to keep the history, so I did the filtering again :)
Didn't you have the same problem when moving flink-addons to flink-staging?

Let me know if it's fine now. Thanks!

**Comment by vasia** [comment]
I'm getting the following error on travis:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.12.1:check (validate) on project flink-gelly: Failed during checkstyle execution: Unable to find suppressions file at location: /tools/maven/suppressions.xml: Could not find resource '/tools/maven/suppressions.xml'. -> [Help 1]
```

Any idea how to solve this? Thanks!

**Comment by zentol** [comment]
in the pom.xml in flink-gelly; change <artifactId>flink-addons</artifactId> to flink-staging

**Comment by vasia** [comment]
Ha! Thanks :))

**Comment by balidani** [comment]
@vasia my ICLA has been filed!

**Comment by vasia** [comment]
Thanks @balidani. 
And travis tests now pass :tada:

**Pull request closed without merging**
