### PR TITLE
[FLINK-22993][filesystem] Fix the issue that CompactFileWriter won't emit EndCheckpoint with Long.MAX_VALUE checkpointId even though the inputs end.

### PR DESCRIPTION
**Pull request by luoyuxia**
## What is the purpose of the change

* This pull request is to fix the issue that CompactFileWriter won't emit EndCheckpoint with Long.MAX_VALUE checkpointId even though the inputs end. *

## Brief change log

  - *Delete method notifyCheckpointComplete and override method commitUpToCheckpoint in CompactFileWriter*
  - *In method commitUpToCheckpoint fo CompactFileWriter, it call super. commitUpToCheckpoint and emit EndCheckpoint *

## Verifying this change

This change is already covered by existing tests

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Review by JingsongLi — COMMENTED** [review]
Can you add test case?

**Comment by luoyuxia** [comment]
Sure, I will add test case.

**Comment by luoyuxia** [comment]
@JingsongLi Now, I have added test to check emiting EndCheckpoint with Long.MAX_VALUE when end of input in CompactFileWriterTest.

**Review by JingsongLi — APPROVED** [review]
Thanks @luoyuxia for the update. Looks good to me.

**Pull request merged**
