### PR TITLE
[FLINK-25147][connectors][test] Migrate Cassandra connector tests to testContainers backport to release 1.14

### PR DESCRIPTION
**Pull request by echauchot**
This PR is the backport of [this merged PR](https://github.com/apache/flink/pull/18115) to release 1.14

R: @zentol

### CODE REVIEW

**Comment by echauchot** [comment]
@flinkbot run azure

**Comment by echauchot** [comment]
@flinkbot run azure

**Comment by echauchot** [comment]
@flinkbot run azure

**Comment by echauchot** [comment]
@zentol I always get the AZP tests cancelled, do you know what's going on ?

**Comment by MartijnVisser** [comment]
@flinkbot run azure

**Comment by MartijnVisser** [comment]
> @zentol I always get the AZP tests cancelled, do you know what's going on ?

There are some CI issues which could be related. Let me try it

**Comment by echauchot** [comment]
thanks @tillrohrmann  for merging !

**Pull request merged**
