### PR TITLE
[hotfix][docs][kafka] Corrected idleness name

### PR DESCRIPTION
**Pull request by mans2singh**
## What is the purpose of the change

* Corrected idleness name

## Brief change log

* Corrected idleness name

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`:  no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no 
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no 
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by mans2singh** [comment]
@flinkbot run azure

**Comment by mans2singh** [comment]
@leonardBang @wuchong - Can you please review this minor enhancement ?  Thanks

**Review by leonardBang — APPROVED** [review]
LGTM, but we need re-trigger the CI to make sure all tests passed(event the test is not related to this PR)

**Comment by leonardBang** [comment]
@flinkbot run azure

**Comment by mans2singh** [comment]
@leonardBang - Thanks for kicking off the azure build.  It looks like test have passed. Please let me know if there is anything else required.

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
