### PR TITLE
[FLINK-4945] KafkaConsumer logs wrong warning about confirmation for …

### PR DESCRIPTION
**Pull request by StefanRRichter**
This PR fixes an unjustified warning about unknown checkpoints in FlinkKafkaConsumerBase.

### CODE REVIEW

**Comment by StefanRRichter** [comment]
R @rmetzger

**Comment by tzulitai** [comment]
So does the misleading warning only pop up on the first checkpoint notification after startup?
If that's the case, then this looks good to me.

**Comment by StefanRRichter** [comment]
At least at on the first checkpoint was the only time I ever observed it.

**Comment by rmetzger** [comment]
Thank you for fixing this.
I'll merge the change.

**Pull request closed without merging**
