### PR TITLE
[FLINK-9367] [Streaming Connectors] Allow to do truncate() in calss BucketingSink when hadoop version is lower than 2.7

### PR DESCRIPTION
**Pull request by zhangxinyu1**
## What is the purpose of the change

In the current implementation of class BucketingSink, we cannot use truncate() function if the hadoop version is lower than 2.7. Instead, it use a valid-length file to mark how much data is valid.
However, users which reads data from HDFS may not or should not know how deal with this valid-length file. 
Hence, we need a configuration to decide whether use the valid-length file. If not, we should rewrite the valid file.

## Brief change log

Add a function `enableForceTruncateInProgressFile()` for BucketingSink to decide whether use the valid-length file. If it's true, the valid-length file wouldn't be produced. Instead, the valid in-progress file will be rewritten. 

## Verifying this change

This change is a trivial work without any test coverage.

### CODE REVIEW

**Comment by zhangxinyu1** [comment]
@kl0u @joshfg @StephanEwen Could you please take a look at this pr?

**Comment by StephanEwen** [comment]
Do you have a Hadoop version older than  2.7?

We are currently attempting to rewrite the Bucketing Sink completely for better compatibility with S3 and with better support for Parquet / ORC. We were actually thinking to drop support for file systems that do not support `truncate()` - so getting this feedback would be good.

**Comment by zhangxinyu1** [comment]
@StephanEwen Thanks your reply. Is their any issue about BuckingSink rewriting? We also want to use the BuckingSink which support for parquet and orc.

**Comment by zhangxinyu1** [comment]
@StephanEwen Thanks for your reply. BTW, is their any issue about BucketingSink rewriting? We also want to use the BucketingSink which supports for parquet and orc.

**Comment by StephanEwen** [comment]
@kl0u please link the issue once you created it.

This is currently very early, in design discussions between @kl0u, me, and @aljoscha.
The main points about the rewrite are
  - Use Flink's FileSystem abstraction, to make it work with shaded S3, swift, etc and give an easier interface
  - Add a proper "ChunkedWriter" abstraction to the FileSystems, which handles write, persist-on-checkpoint, and rollback-to-checkpoint in a FileSystem specific way. For example, use truncate()/append() on POSIX and HDFS, use MultiPartUploads on S3, ...
  - Add support for gathering large chunks across checkpoints, to make Parquet and ORC compression more effective.

**Comment by kl0u** [comment]
Thanks for the useful input here @zhangxinyu1 and @StephanEwen. As soon as I have sth concrete I create the JIRA and post it here.

**Comment by zhangxinyu1** [comment]
@kl0u Thanks. Would you please consider to implement a BucketingSource which we can use it to read data from FileSystems? Besides we also care about the limit of bandwidth.

**Comment by kl0u** [comment]
@zhangxinyu1 as soon as this sink is ready, I believe that the existing File Source will be able to read the output of the Bucketing Sink. As far as bandwidth limitations are concerned, could you elaborate a bit on what you mean? You want to tell the source to read at speed X records/sec?

**Comment by zhangxinyu1** [comment]
@kl0u Great! I look forward for it. 
About the bandwidth limitation, we hope jobs can read resource below the speed x bytes/sec.

**Pull request closed without merging**
