### PR TITLE
[FLINK-2841] Correcting roadmap link to point to confluence.

### PR DESCRIPTION
**Pull request by ssaumitra**

### CODE REVIEW

**Comment by chiwanpark** [comment]
I would like to shepherd this PR.

Hi @ssaumitra, thanks for opening pull request! But, your PR has a problem to merge. Because the document is about FlinkML, the link should point to roadmap of FlinkML.

**Comment by ssaumitra** [comment]
Oh, my bad, I thought Flink Roadmap is the only main page maintained for sub-projects too. Is this the correct one? https://cwiki.apache.org/confluence/display/FLINK/FlinkML%3A+Vision+and+Roadmap

**Comment by chiwanpark** [comment]
@ssaumitra Yes, the link is correct. :)

**Comment by ssaumitra** [comment]
Made the change. I have amended the past commit because it was kind-of incorrect.

**Comment by StephanEwen** [comment]
Looks good, merging this!

**Pull request closed without merging**
