### PR TITLE
[FLINK-3116] Remove RecordOperator

### PR DESCRIPTION
**Pull request by jaoki**

### CODE REVIEW

**Comment by zentol** [comment]
Looks good. +1

**Comment by hsaputra** [comment]
+1
LGTM

**Comment by jaoki** [comment]
The travis error is in streaming-java, but my change was made in core and optimizer 
```
[INFO] flink-runtime-web .................................. SUCCESS [ 16.675 s]
[INFO] flink-streaming-java ............................... FAILURE [01:57 min]
[INFO] flink-examples ..................................... SKIPPED
```
and error seems to relate to some jar file?
```
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :flink-streaming-java
Trying to KILL watchdog (2290).
./tools/travis_mvn_watchdog.sh: line 204:  2290 Terminated              watchdog
MVN exited with EXIT CODE: 1.
java.io.FileNotFoundException: build-target/lib/flink-dist-*.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.zip.ZipFile.<init>(ZipFile.java:121)
	at sun.tools.jar.Main.list(Main.java:1060)
	at sun.tools.jar.Main.run(Main.java:291)
	at sun.tools.jar.Main.main(Main.java:1233)
find: `./flink-yarn-tests/target/flink-yarn-tests*': No such file or directory
PRODUCED build artifacts.
1.log  2.log  build_info  mvn.out
The command "./tools/travis_mvn_watchdog.sh 300" exited with 1.
```

Most probably it is irrelevant from my change?

**Comment by StephanEwen** [comment]
Thanks for your contribution!

I will merge this PR in the next set of cleanups that remove the remaining Record code...

**Comment by fhueske** [comment]
Will merge this PR

**Pull request closed without merging**
