### PR TITLE
[FLINK-5088] [network] Add capacity limit option to partitions

### PR DESCRIPTION
**Pull request by uce**
We worked with @StephanEwen on this. The changes build on top of FLINK-5159 (see #2882). Only the most recent commit is relevant.

# Changes

The goal of the changes was to allow limiting the capacity of produced partitions in addition to the back pressure that is introduced via the buffer pools. 

## PIPELINED_BOUNDED partition type

This adds a further result partition type (`PIPELINED_BOUNDED`) that is translated to pipelined runtime partitions that can configure a maximum capacity for their output queues via:

    taskmanager.net.max-out-queue-length

By default, they have unbounded length (`0`) and behave like regular PIPELINED results.

## RemoteInputChannel capacity limit

If the outbound queues are limited, we need to capacity limit the inbound remote channels, too. Otherwise, we only shift the problem to the receiver, which potentially consume the bounded queues fast and buffers the data.

## Known Issues

For the time being the back pressure stats reported in the web interface are not correct as they only take the buffer pools into account. If we keep the default at unlimited, it should be OK to address this in a follow up.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Since the capacity limit refers both to input and output queues, we should probably rename `taskmanager.net.max-out-queue-length` to `taskmanager.net.max-queue-length`.

**Comment by uce** [comment]
I agree with the renaming you propose.

I would not allow `flush()` to override the capacity limit as this has the potential to circumvent the capacity limit with a low latency `OutputFlusher`. Should we keep the `tryFlush` and `flush` differentiation or replace `flush` with `tryFlush`?

---

I've tested this on a cluster and didn't run into problems. Before merging, I still need to add some unit tests though. Most probably, this will not make it to 1.1.4.

**Comment by uce** [comment]
I renamed the config key and added unit tests for the sub components. This should be good enough to get it in if Travis gives us an OK. As a follow up I would like to finish a end to end test similar to the `InputGateConcurrentTest`. What do you think Stephan?

**Comment by uce** [comment]
@StephanEwen I think we're going to leave this out of the upcoming 1.2 release after all. From cluster tests it seems like it didn't help as much as we wanted. What do you think?

**Comment by StephanEwen** [comment]
Agreed, let's keep it as a debug branch.

I think this is a useful, but not complete, step towards getting rid of the network buffers configuration.
Especially introducing the explicitly "capacity constrained / back-pressured" partition type is a good thing, in my opinion.

**Pull request closed without merging**
