### PR TITLE
[FLINK-1716] Adds CoCoA algorithm

### PR DESCRIPTION
**Pull request by tillrohrmann**
This PR adds the CoCoA algorithm using l2-norm and hinge-loss functions. Thus, it can be used to train soft-margin SVM.

This PR is based on #539 and #543.

### CODE REVIEW

**Comment by tillrohrmann** [comment]
I rebased the PR on the current master. When Travis gives green light and if there are no objections, I'll merge this PR.

**Comment by tillrohrmann** [comment]
Travis failed because of some Gelly test case. Travis running on my own repo passed, though. I'll merge the PR then.

**Comment by vasia** [comment]
Hi @tillrohrmann! Thanks for the heads up :)
The failing test is `DegreesWithExceptionITCase` and it seems that it fails because of not throwing the excepted exception type. We had a discussion about this in #475 and if I get it correctly, we can't be sure which exception will be reported to the client, because of the job cancelling. Thus, we removed the check of the exception type and message and only checked for failure.
However, I see you added some exception checks in 36b762e. So, I'm not sure what we're supposed to do with this test now, so that it doesn't fail o.O

**Comment by tillrohrmann** [comment]
Oh ok, I was not aware of #475. I just added the additional checks because of the fail message in the try block that you expect a ```NoSuchElementException```. If this is not a case, then we can just adapt the fail message and revert the additional checks I've introduced. Sorry for screwing up your test cases.

**Pull request closed without merging**
