### PR TITLE
[FLINK-4896] [gelly] PageRank algorithm for directed graphs

### PR DESCRIPTION
**Pull request by greghogan**

### CODE REVIEW

**Comment by vasia** [comment]
Hi @greghogan,
thanks for this PR. Do you have any idea how this implementation compares with the existing ones? I'm curious since it uses a bulk iteration and the existing ones are using delta iterations. Is the idea to keep this one as the library implementation and move the existing scatter-gather and gsa ones to the examples?
Thanks!

**Comment by greghogan** [comment]
Running on a c4.xlarge with 4 slots and a 4 GB preallocated TaskManager heap. EdgeList measures the time to simplify the graph since the library PageRank using Scatter-Gather ("PageRankSG") requires each vertex to have both incoming and outgoing edges. "PageRank" is the algorithm from this PR.

Algorithm | Scale 16 | Scale 18
------------ | ------------- | -------------
EdgeList | 2537 ms | 8779 ms
PageRank | 9563 ms | 39558 ms
PageRankSG | 11188 ms | 47736 ms

**Comment by greghogan** [comment]
@vasia Running on a c4.xlarge with 4 slots and a 4 GB preallocated TaskManager heap. EdgeList measures the time to simplify the graph since the library PageRank using Scatter-Gather ("PageRankSG") and Gather-Sum-Apply ("PageRankGSA") require each vertex to have both incoming and outgoing edges. "PageRank" is the algorithm from this PR. Each execution is performing 10 iterations.

Algorithm | Scale 16 | Scale 18 | Scale 20 | Scale 22
------------ | ------------- | ------------- | ------------- | -------------
EdgeList | 2.537 s | 8.779 s | 34.105 s | 141.512 s
PageRank | 9.563 s | 39.558 s | 168.401 s | 740.345 s
PageRankSG | 11.188 s | 47.736 s | 216.688 s | 1041.176 s
PageRankGSA | 14.001 s | 60.663 s | 268.568 s | 1241.344 s
Speedup over SG | 23% | 26% | 35% | 50%

I'm surprised that pageRankSG is performing faster than PageRankGSA.

The current SG and GSA implementations would vw good examples, and already have integration tests.

**Comment by greghogan** [comment]
@vasia was there more you wanted to review here?

**Comment by vasia** [comment]
Thanks for the results @greghogan! Updating the docs would be nice, otherwise +1.
Do you think we should move existing implementations in the examples (there are still relevant to demonstrate iteration APIs) and keep this one as the only library method since it's the fastest and more general one?

**Comment by greghogan** [comment]
@vasia moved SG and GSA implementations to examples and updated docs.

**Pull request closed without merging**
