### PR TITLE
[FLINK-3067] Enforce zkclient 0.7 for Kafka

### PR DESCRIPTION
**Pull request by rmetzger**

### CODE REVIEW

**Comment by StephanEwen** [comment]
Curious, why did the dependency management entry not work?

Right now, we have two versions in the dependencies, one by us, one transitive by Kafka. Is it well defined which one is chosen? To my understanding, that is where dependency management entries define which version is chosen. If the dependency management alone did not work, I would assume it should still stay for that reason.

**Comment by rmetzger** [comment]
It seems that the `dependencyManagement` section is mainly intended to control our versions.
So with a dependencyManagement section, you can make sure that we are using the same zkclient across all our submodules (for all our declared zkclient dependencies).
Since we didn't declare a zkclient dependency for the flink-connector-kafka, the `dependencyManagement` doesn't have any effect for other projects.

See also: http://stackoverflow.com/questions/28312975/maven-dependencymanagement-version-ignored-in-transitive-dependencies

**Comment by rmetzger** [comment]
I added the dependencyManagement section again, just to make sure

**Comment by gyfora** [comment]
This seems to solve the dependency issue for our project +1

**Comment by StephanEwen** [comment]
+1 to merge

**Comment by rmetzger** [comment]
merging to release-0.10 and master.

**Pull request merged**
