### PR TITLE
[FLINK-4278]: Unclosed FSDataOutputStream in multiple files in the project

### PR DESCRIPTION
**Pull request by nssalian**
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.

- [ ] General
  - JIRA: https://issues.apache.org/jira/browse/FLINK-4278
  - Added the close statements for the FSStateBackend, StringWriter and FileSystemStateStorageHelper for the unclosed FileDataOutputStream objects.
  - Each commit in the PR has a meaningful commit message (including the JIRA id)

- [ ] Documentation
  - No documentation needed here.

- [ ] Tests & Build
  - `mvn clean verify` has been executed successfully locally or a Travis build has failed but the failure does not seem related. Can do a re-run and verify on the PR itself.

### CODE REVIEW

**Comment by nssalian** [comment]
Hi @rmetzger, @tedyu do you have some time to help review this?
I am not sure if the failures are related.

**Comment by StephanEwen** [comment]
Sorry, this does not build right now. I would review it once it builds.

**Comment by nssalian** [comment]
Thanks @StephanEwen. Let me check again with the tests.

**Comment by nssalian** [comment]
@StephanEwen, let me close this and open a new one after some testing. Will post an new PR this week.

**Pull request closed without merging**
