### PR TITLE
[FLINK-36792][table] Remove FlinkJoinPushExpressionsRule.

### PR DESCRIPTION
**Pull request by liuyongvs**
## What is the purpose of the change

A bit reasoning for the change
high calcite version has fixed, current calcite version is 1.34

## Verifying this change

This change is already covered by existing tests

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by liuyongvs** [comment]
hi @snuyanzin , may not! every rule whether can be removed should be checked.
for example FlinkPruneEmptyRules this rule will cause some test failed because plan changed.
and i also check other rule copy from calcite in flink can not removed.

**Comment by davidradl** [comment]
Reviewed by Chi on 28/11/24 business as usual progressing with committer involved.

**Comment by liuyongvs** [comment]
hi @snuyanzin will you look again?

**Comment by liuyongvs** [comment]
hi @snuyanzin

**Review by snuyanzin — APPROVED** [review]

**Pull request merged**
