### PR TITLE
[FLINK-34199] Add tracing for durations of rescaling/restoring RocksDB incremental checkpoints from downloaded and local state

### PR DESCRIPTION
**Pull request by StefanRRichter**
## What is the purpose of the change

This PR extends #24031 with traces for the rescaling/restore times from local state.

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluster with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by rkhachatryan — COMMENTED** [review]
I'm a bit confused by the purpose this PR:
- from the title and docs, it seems to be to measure the restore time for local state
- but the implementation measures restore time for all state 

Or am I missing something?

Regardless, I think the latter (measure restore times) makes sense.
Besides of that, measuring remote and/or local state size would be more useful than restore time from local state.

WDYT?

**Comment by StefanRRichter** [comment]
I think the description is correct, depending on you point of view. Recovery today has two phases: 

1. If there is any remote state it will be downloaded and becomes local state.
2. Then we either rescale or reopen the DB from local state.

And the PR is about measuring the 2nd phase (after we have already duration for the first).

**Comment by StefanRRichter** [comment]
Besides that, I already merged a PR that measures local/remote state sizes. And in our meeting we found that all of the metrics are useful :)

**Comment by rkhachatryan** [comment]
Right :sweat_smile:
Then I guess the only confusion for me is about "local" in names and docs: remote state that is downloaded can be called "local", but it's pure implementation detail. It can't be used for local recovery yet; so it's not local from the user point of view.

**Comment by StefanRRichter** [comment]
I wrote the docs slightly different, hope that makes it clearer.

**Review by rkhachatryan — APPROVED** [review]
Thanks!
LGTM

**Pull request closed without merging**
