### PR TITLE
Stream graph + internal refactor

### PR DESCRIPTION
**Pull request by gyfora**
This is a refactor for the internal representation of the streaming topologies + a major refactor of the streaming internals

### CODE REVIEW

**Comment by mxm** [comment]
This is a huge PR but from what I've seen you made very sensible changes.

**Comment by mbalassi** [comment]
When merging two things to look out for: I have already pushed the key bugfix for the StreamConfig and have have to make sure to not only close this PR but also #508.

**Comment by mbalassi** [comment]
By the way scrolling through the code: Big :+1: for the `streamoperator` package and for the `StreamNode`.

**Comment by aljoscha** [comment]
Regarding StreamRecord, is the UID still required? In my understanding we are working towards state-snapshotting, so that would not require to have IDs in records anymore, correct? I mentioned at some earlier point that the IDs are not used anymore, so what's the status now?

If we got rid of the UID then we can also get rid of StreamRecord and StreamRecord serializer.

**Comment by aljoscha** [comment]
Package org.apache.flink.streaming.runtime.streamtask could be renamed to org.apache.flink.streaming.runtime.tasks, the streaming part is already clear from *.streaming.* in the package prefix. io and partitioner are also not called streamio and streampartitioner. This would make things more homogenous.

**Comment by aljoscha** [comment]
By the way, all these comments I'm making. I'm just making them to keep track of things. If we discuss them and want to implement some changes I can also do this myself, just want to get opinions here.

**Comment by aljoscha** [comment]
Package org.apache.flink.streaming.api.datastream.temporaloperator could be renamed to org.apache.flink.streaming.api.datastream.temporal, the former seems to be quite a mouthful.

**Comment by aljoscha** [comment]
Also, there are packages streamgraph and streamoperator which could be renamed to graph and operators, to improve consistency.

Further, there are two concepts we call operators here, this might lead to confusion. There are the actual operator implementations in streamoperator and there are things like SingleOutputStreamOperator and StreamCrossOperator. I know that the batch API is also very messy in naming these things but maybe we can find better names for the streaming API while we still have a chance to change things. :smile:

**Comment by aljoscha** [comment]
Package api.function and its sub packages should be pluralised for consistency.

**Comment by aljoscha** [comment]
Apart from these naming issues I really like the idea behind the streaming API. :smile:

**Comment by gyfora** [comment]
I fixed all the comments, except for the SingleOutputStreamOperator thing. Let's leave that for later :D

**Comment by gyfora** [comment]
I will merge this later today if no objections .

**Comment by aljoscha** [comment]
+1 for merge

**Comment by hsaputra** [comment]
This is great patch, but as @mxm mentioned before, it almost impossible to review patches with this size.

If the PR could not be chopped into separate PRs, lets try to have smaller commits to help. Before merge we could squash it to make it just one commit.

**Comment by gyfora** [comment]
It is already merged.

**Comment by hsaputra** [comment]
Ah yes, it should be fine. I should have replied this as more generic comment for future PRs.

Sorry if I confused you @gyfora

**Comment by gyfora** [comment]
Haha no problem. I will make sure it is more reviewable in the future PRs.

**Pull request closed without merging**
