### PR TITLE
[FLINK-4735] [cluster management] Migrate some job execution related akka messages to rpc calls

### PR DESCRIPTION
**Pull request by KurtYoung**
This includes the following operations about job execution:
1. checkpointing
2. kvstate
3. savepoint
4. classloading props

### CODE REVIEW

**Comment by StephanEwen** [comment]
Looks good, thanks, will merge this.

I would suggest two followups:
  - We can remove the "dispose savepoint" method, because that is functionality disappearing right now. Savepoints need no special remove logic any more, they are just a directory in a filesystem.

  - We can reduce the number of message classes (like `TriggerSavepointResponse`) by using exceptions more prominently. The "triggerSavepoint()" method could simply return a String (success) or throw an exception (failure). Exceptions are propagated by the RPC, so the caller future will always get it as a response.

**Comment by KurtYoung** [comment]
@StephanEwen Sounds reasonable. This PR has some overlayer with #2594, will address your comment after that one merged and rebase to the latest flip-6 branch

**Comment by KurtYoung** [comment]
This PR now contains some work from master branch picked by Stephan.
Rebased to the latest flip-6

**Comment by StephanEwen** [comment]
Merged to the `flip-6` feature branch in 34fef4752e94b3d0c7afe7a9525799bb651a07b4

**Pull request closed without merging**
