### PR TITLE
[FLINK-24029][docs] Update doc example sql field in release-1.13.2 to dept_id

### PR DESCRIPTION
**Pull request by zhwangke**
Current sql in doc of branch release-1.13 is still dep_id and we should fix it to dept_id

### CODE REVIEW

**Comment by zhwangke** [comment]
@Myasuka  Please help to review this PR about correcting typos

**Comment by Myasuka** [comment]
Though this PR is samll, I think @wuchong is better to review this.

**Review by wuchong — COMMENTED** [review]
Could you fix `DeptId` in line 108 as well?

**Comment by zhwangke** [comment]
> Could you fix `DeptId` in line 108 as well?

@wuchong done

**Review by wuchong — APPROVED** [review]
LGTM

**Review by wuchong — CHANGES_REQUESTED** [review]
Could you also update the English version which is located in `docs/content/docs/dev/table/sql/gettingStarted.md`.

**Review by wuchong — COMMENTED** [review]
LGTM.

**Review by wuchong — APPROVED** [review]

**Pull request merged**
