### PR TITLE
[FLINK-19998] Fixing Invalid Links in docs

### PR DESCRIPTION
**Pull request by vintageplayer**
## What is the purpose of the change

In the docs/concepts/stateful-stream-processing.md file, under the first section (What is State), the following two links are broken:

1. Checkpoints: [checkpoints]({{ site.baseurl}}{% link dev/stream/state/checkpointing.md %})
2. Savepoints: [savepoints]({{ site.baseurl }}{%link ops/state/savepoints.md %})

This results in the target link as follows:

1. For Checkpoints: https://ci.apache.org/projects/flink/flink-docs-master//ci.apache.org/projects/flink/flink-docs-master/dev/stream/state/checkpointing.html
2. For Savepoints: https://ci.apache.org/projects/flink/flink-docs-master//ci.apache.org/projects/flink/flink-docs-master/ops/state/savepoints.html

## Brief change log

removing {{ site.baseurl}} from both the links, keeping it in lines with the link templates in the doc. 

## Verifying this change

This change is a trivial code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by vintageplayer** [comment]
@rmetzger Have updated the pull request description. Please take a look. Thanks.

**Review by Myasuka — COMMENTED** [review]
I think this bug is caused by mix usage of  `{ site.baseurl}}` and `% link`, we might expend previous JIRA ticket and fix all broken links by searching `site.baseurl }}{% link`, `site.baseurl}}{% link` and so on.

**Comment by vintageplayer** [comment]
> I think this bug is caused by mix usage of `{ site.baseurl}}` and `% link`, we might expend previous JIRA ticket and fix all broken links by searching `site.baseurl }}{% link`, `site.baseurl}}{% link` and so on.

I've a regex. Can I update the same pull request? Or should I create a new one abandoning this?
@Myasuka

**Comment by Myasuka** [comment]
I think you could extend current JIRA's description and update current PR. This is just documentation link fix and caused by the same reason, we don't need to distinguish what the actual content said.

**Comment by vintageplayer** [comment]
> I think you could extend current JIRA's description and update current PR. This is just documentation link fix and caused by the same reason, we don't need to distinguish what the actual content said.
> 
> You could combine new updates with current as one commit and force update your branch for PR.

The pull request is updated with the new commit. Please review @Myasuka

**Review by Myasuka — CHANGES_REQUESTED** [review]
I think we should also fix the 49th line of `docs/concepts/index.zh.md` for `[SQL]({{ site.baseurl}}{% link`

**Comment by Myasuka** [comment]
LGTM, @vintageplayer please rename the commit title as `[FLINK-19998] Remove site.baseurl from {% link %} tags` and I'll then merge this PR.

**Review by Myasuka — APPROVED** [review]

**Comment by Myasuka** [comment]
@vintageplayer Could you please help rename the commit title so that I could directly merge your commit?

**Pull request merged**
