### PR TITLE
[FLINK-17736] Add flink cep example

### PR DESCRIPTION
**Pull request by dengziming**
## What is the purpose of the change

This pr add a flink cep example

## Brief change log

Most code if from the [flink official website](https://ci.apache.org/projects/flink/flink-docs-release-1.10/dev/libs/cep.html) and I ran it locally to ensure it do work correctly.

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency):(yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no**)
  - The runtime per-record code paths (performance sensitive): (yes / **no**)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no**)
  - The S3 file system connector: (yes / **no**)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / **JavaDocs** / not documented)

### CODE REVIEW

**Comment by klion26** [comment]
@dengziming thanks for the contribution. But, as the [contribute guild](https://flink.apache.org/contributing/contribute-code.html#create-jira-ticket-and-reach-consensus) said, we should reach consensus on Jira side before filing a pr.

**Comment by rmetzger** [comment]
I agree with @klion26! I commented in the JIRA ticket.

**Comment by dengziming** [comment]
@rmetzger Thank you for your comment, I will check it.

**Comment by rmetzger** [comment]
Based on the JIRA discussion, I propose to close this PR until the discussion has resolved.

**Pull request closed without merging**
