### PR TITLE
[FLINK-14463] [Kafka Consumer] Merge Handover in flink-connector-kafka and flink-connector-kafka-0.9	

### PR DESCRIPTION
**Pull request by Jiayi-Liao**
## What is the purpose of the change

Handover.java exists both in flink-connector-kafka(kafka 2.x) module and flink-connector-kafka-0.9 module. We should put this file into kafka base module to avoid repeated codes.

## Brief change log

Remove Handover in  flink-connector-kafka(kafka 2.x) module and flink-connector-kafka-0.9 module, and add Handover in flink-connector-kafka-base module.

## Verifying this change

Unit testing.

### CODE REVIEW

**Comment by yanghua** [comment]
@buptljy Thanks for your contribution. This PR has checkstyle errors.

**Comment by buptljy** [comment]
@yanghua Thanks for your reminding. It's fixed now.

**Comment by buptljy** [comment]
@flinkbot run travis

**Comment by yanghua** [comment]
@buptljy Still two error msgs:

```
02:48:55.083 [ERROR] /home/travis/build/flink-ci/flink/flink-connectors/flink-connector-kafka-0.10/src/test/java/org/apache/flink/streaming/connectors/kafka/internal/Kafka010FetcherTest.java:[180,79] package Handover does not exist
02:48:55.083 [ERROR] /home/travis/build/flink-ci/flink/flink-connectors/flink-connector-kafka-0.10/src/test/java/org/apache/flink/streaming/connectors/kafka/internal/Kafka010FetcherTest.java:[329,77] package Handover does not exist
02:48:55.083 [ERROR] -> [Help 1]
```

**Comment by buptljy** [comment]
Thanks. It works now. @yanghua 

cc @aljoscha

**Comment by zentol** [comment]
Kafka 0.9 connector has been removed.

**Pull request closed without merging**
