### PR TITLE
[FLINK-1941] documentation for the Gather-Sum-Apply iterations in Gelly

### PR DESCRIPTION
**Pull request by vasia**
This one adds a high-level description of GSA iterative model and an example of implementing SSSP with GSA in Gelly. Also, a section on available configuration options for the GSAIteration.

### CODE REVIEW

**Comment by vasia** [comment]
Thanks for the review @andralungu!
You're right, I'll add a comparison paragraph. I guess I should probably also add the same SSSP example with the corresponding drawings for the vertex-centric case as well, to better show how computation is distributed :)

**Comment by vasia** [comment]
Added comparison section and SSSP drawings for vertex-centric ^^

**Comment by andralungu** [comment]
+1 to merge

**Comment by vasia** [comment]
and will merge :)

**Pull request closed without merging**
